### ISSUE TITLE
Windows client functionality is severely limited

### ISSUE THREAD

**Issue by Frowny** [qTox/qTox#1]
Everyone is offline, including myself
![offline](https://cloud.githubusercontent.com/assets/2028361/3395649/fb4af44a-fd01-11e3-96d7-f70a94363325.PNG)

**Comment by tux3** [comment]
You can bypass the problem by just starting another client at the same time, then it will work, but I have no idea why. Or overwriting our tox_save with another client's.

I'm trying to fix this, but this is a really strange bug.

**Comment by Frowny** [comment]
I’m confused.
![×2](https://cloud.githubusercontent.com/assets/2028361/3397438/f95ec338-fd1e-11e3-9c44-312370800c99.PNG)

**Comment by tux3** [comment]
By another client, I meant any client that does not have this bug !
So, uTox, toxic, etc etc.

If you do this just once, then it'll create a valid tox_save and you won't have to do it again.
I know it's not really a solution, but I have no idea what's causing this bug right now.

**Comment by tux3** [comment]
I found the problem, it should work now.
