### ISSUE TITLE
Can't copy&paste message log

### ISSUE THREAD

**Issue by ctrlcctrlv** [qTox/qTox#10]
Can't tell if feature or bug.

**Comment by tux3** [comment]
Bug!
Expect a fix in ~5 minutes

**Comment by ctrlcctrlv** [comment]
Hmm, still can't copy multiple lines, or times, or user names, but it's better than before.

**Comment by tux3** [comment]
Copying multiple lines is going to be harder, I can make names copyable thought.

**Comment by ctrlcctrlv** [comment]
Maybe an option to "save message log" in the right click menu would work just as well and be easier to implement.

Great work on this by the way.

**Comment by tux3** [comment]
Thanks, I'll add the "save message log" idea.

**Comment by tux3** [comment]
I'm planning to change the way text is displayed so you can select multiple lines. Reopening.

**Comment by msteinbeck** [comment]
ProjectTox-Qt-GUI has a very good chatview implementation. Maybe it can be reused here. It supports emoticons, copy/paste and is very flexible to use.

**Comment by suhr** [comment]
> emoticons

Unicode emoticons are cool and we probably should adopt it. 😎

**Comment by dubslow** [comment]
I would argue that, based on a 1.5 hour long and counting flame war on #tox-ontopic, this issue be prioritized somewhat.

**Comment by tux3** [comment]
@dubslow this issue is fixed in the newChatForm branch, however the branch is not quite perfect, some visual bugs still need to be fixed, and it hasn't been tested much.

**Comment by tux3** [comment]
This is finally fixed! It took a bit more than 5 minutes, sorry about that.
