### ISSUE TITLE
qTox doesn't remember nickname in history

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#1000]
When history logging is enabled, qTox does not remember the contact's name. When a contact changes their name and qTox is restarted, all their old messages in the log use their current (changed) name, and not the name that was used at that moment, which can be confusing.

**Comment by agilob** [comment]
issue 1000.

I think it's a feature and that's how it should work. Skype and gajim do the same.

**Comment by TheLastProject** [comment]
Apparently this is a duplicate of #659. I failed to search issues well enough :(

I personally disagree that it makes sense as a feature, but that's maybe because I come from a place where using another nickname for roleplaying purposes is reasonably common. For me, losing the nick state as it was means losing info about "who" I was talking to. It is also confusing if you've known people under a certain nickname for a long time and they suddenly change their name, but the history no longer shows the old name you know them by.

**Comment by ProMcTagonist** [comment]
It is definitely not a feature. The name is a part of the context of the conversation as TheLastProject described. The conversation should be preserved in history exactly as it was.

**Comment by zetok** [comment]
Closing, since it's a duplicate.
