### ISSUE TITLE
qTox Nukes Avatar of Other Online Client

### ISSUE THREAD

**Issue by lehitoskin** [qTox/qTox#1002]
When I have a client up that has set an avatar and I turn on qTox, that avatar (and hash) are deleted. I'm not exactly sure what's going on, but it's pretty annoying. This only happens when both clients are running at the same time.

**Comment by dubslow** [comment]
So if you set the avatar in the other client, then open qtox without closing the other one, it doesn't read the correct avatar, and as a result overwrites it? You've confirmed this with more than one other client?

**Comment by lehitoskin** [comment]
@dubslow That seems to be what's going on. If I run qTox only, it'll display the avatar in the buddylist without any shenanigans. I haven't checked it out on other clients yet.

**Comment by dubslow** [comment]
So if you set in in Blight, then close Blight and open qTox, everything works like a charm? Yet if you open qTox while Blight is running, then qTox overwrites the files?

Can you check the files with your file browser (instead of opening qTox)? qTox doesn't have any way to know when other clients are running, so if the first paragraph is correct, I'm not sure how it could be a qTox problem. Are you properly closing/flushing the files in Blight?

**Comment by lehitoskin** [comment]
@dubslow If I set the avatar in Blight, close it, then open qTox, it'll recognize the avatar+hash in the avatar directory. If I close qTox and open Blight, then the avatar+hash is recognized and everything's loaded just fine. This only occurs when the two clients are on at the same time. I'm definitely remembering to close the files after I write data...

**Comment by lehitoskin** [comment]
Upon further investigation, I have found out an interesting detail. The deletion doesn't occur until the two peers see one another as online. If I remove one of them from the friendlist, there is no deletion.

**Comment by dubslow** [comment]
Oh. I thought we were talking about the same profile lol. That's much more to go on, thank you.

**Comment by lehitoskin** [comment]
:P I guess that's my fault for not being more clear. Yeah, the two clients are running off their own, separate .tox data files.

**Comment by lehitoskin** [comment]
Latest changes to Blight make this not happen anymore. kthx
