### ISSUE TITLE
Progress bar doesn't work when tranfering files from OSX to Ubuntu with auto_accept_files_from_friend on

### ISSUE THREAD

**Issue by Nokta-strigo** [qTox/qTox#1004]
While transferring files from OSX to Ubuntu via qTox (on both ends) progress bar on OSX was showing 0% all the time till the transfer end. On Ubuntu end I have "Auto accept files from this friend" checked. If I uncheck  "Auto accept files from this friend" and accept receiving of the file manually, progress bars on both ends work fine. In reverse direction all works fine in any case.
On OSX it's the last Jenkins build, on Ubuntu it was compiled from today's github src.

**Comment by Nokta-strigo** [comment]
I'm sorry, it's copy of #376

**Comment by dubslow** [comment]
GUI issue fixed by new chatform, comment for reopen
