### ISSUE TITLE
Groupchat peer muting

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#1007]
Provide `/set -a ‹peer›` for muting peer audio and `/set +a  ‹peer›` for unmuting.
PS: Toxy already implements this. Ask @Impyy for details.

**Comment by ProMcTagonist** [comment]
+1
Would be good if we could mute text too. Cough audiobotsharp.

**Comment by zetok** [comment]
Perhaps relying on commands is not the best way to go about this - instead/additionally there should be a way to click on the peer in column on that left that #2013 introduces, and pick an option to mute peer.

**Comment by suhr** [comment]
I'd like to have both variants.

**Comment by tox-user** [comment]
Implemented in https://github.com/qTox/qTox/pull/5124.
