### ISSUE TITLE
Place groupchats at top of the contact list

### ISSUE THREAD

**Issue by vasyahuyasa** [qTox/qTox#1010]
Now groupchats placed below online contacts. Also in Tox UI guidelines groupchats placed at top of the contact list.
![2015-01-13-012628_1366x768_scrot](https://cloud.githubusercontent.com/assets/10506304/5712508/12aed056-9ac4-11e4-9bf7-0c53df2379bb.png)

**Comment by dubslow** [comment]
This is a subjective preference, can I get a weigh in from other users?

**Comment by Zer0-One** [comment]
groupchats are naturally going to have the most activity, so i kinda like the idea of having them up at the top.

if people want this, it would fit very easily into my next PR, since i'm working with the friends list anyway.

**Comment by Xylemon** [comment]
@Zer0-One I would say go for it, the idea seems practical.

**Comment by vasyahuyasa** [comment]
With groupchats behavior like it right now it will be annoying with big contact list when people going online/offline, that make groupchats moving.

**Comment by ProMcTagonist** [comment]
Conversations need better organization in general. New windows, separation of friends and groups, etc. ItsDuke put a dropdown above the column for switching views. Was that deemed bad UX?

**Comment by krepa098** [comment]
+1

**Comment by zetok** [comment]
> This is a subjective preference, can I get a weigh in from other users?

as such it should be an option

**Comment by taingra** [comment]
I'd like things to be sorted by activity. That way the chats you most commonly are at the top and you don't have to scroll past all the chats you rarely use. 

Also, it might be a good idea to have a seperate contacts list from the list of active chats, like the way the Google Hangouts app is structured.

**Comment by srkunze** [comment]
Why not sorting by last activity like Facebook does?

**Comment by srkunze** [comment]
@paranoid-after I agree.

I do not care if one or five users, but I care about the most recent message most. As long as I can search for chats (aka contacts) I do not mind if they move down the list.

**Comment by Zer0-One** [comment]
It really sounds like we need a new "tab" that sorts the same friend/group widgets by activity.

**Comment by srkunze** [comment]
Just make it a setting. :D

**Comment by zetok** [comment]
> Just make it a setting. :D

yep

"List":
`Sort alphabetically`
`Sort by activity, then alphabetically`
and check:
`Keep groupchats at top: ✔|✗`

↑ is there some better way to go about it?

**Comment by ghost** [comment]
And what if i want chats to be at the bottom? Option should allow that too.

**Comment by ProMcTagonist** [comment]
@Zer0-One 
The mockup handles that.

**Comment by TheLastProject** [comment]
I didn't respond to this yet?

My opinion is: Yes, sort it to top, so groupchats are separated from normal chats, instead of mixed up with them like they are currently.

**Comment by tux3** [comment]
Done.
