### ISSUE TITLE
There's no way to quickly get own Tox ID

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1012]
It should be accessible in easy, fast way, **max** 2 clicks.
Currently to copy Tox ID one has to go to settings, click on tab and copy ID. **4 clicks if one knows where to look**. IMHO that should be changed. I've tried to think about that problem, but haven't come with best way that would provide global access in easy and user-friendly way (user must know that it's about getting ID)

Some ideas:
1. It could be done like in Venom, i.e., after clicking on green status button beside being able to change status one could copy Tox ID. Handicap is that there are still 2 clicks required, and user is not in any way informed/pointed to that way of copying ID.

\2. There could be added some button under green status button (no idea where else could it be located, since practically no other place is accessible globally all the time). This button would clearly indicate that it would copy Tox ID. Handicap is that there really isn't much of free space beside green button, and it would be kinda outside of mockup looks. On the plus side, there's only 1 click, and (provided that button will be self-explanatory [button design + tooltip]) it would be user-friendly.
# 

Additionally, in user-input fields in chats, when r-clicking there could be added field to menu `Paste my Tox ID`

Any other ideas?
@ItsDuke ?

**Comment by dubslow** [comment]
The last thing should be in its own issue.

Maybe a button on the same "row" as the user search field, when that's implemented?

**Comment by ItsDuke** [comment]
@zetok a few questions about IDs:
1 - They are essentially your username, correct? It's how people identify and add you?
2 - Why would a button for it need to be in the UI itself? Are people going to be pressing "copy ID" as much as they are going to say...change their status? add an attachment? take a screenshot?

I agree that most things should require as few clicks as possible, but I feel like giving the "copy ID" function a button all it's own might be a bit overkill. That's assuming people are going to be constantly clamoring to copy their ID's. I could realistically think people might copy it once or twice per day as they add a new contact (or go on an adding spree), but perhaps I'm underestimating the problem.

I would imagine a happy medium could indeed being in the green status dot drop down menu, or when you click your avatar, a dropdown would come up to change your avatar or copy your ID, or hell, even in the toolbar in File > Copy My ID. There are plenty of 2-click places to put it that would make sense to the user.

But again, maybe I'm underestimating the frequency with which IDs are copied.

**Comment by stqism** [comment]
@ItsDuke 

> But again, maybe I'm underestimating the frequency with which IDs are copied.

It's hard to say, but we really should be pushing more people to stuff like toxme.
It's currently maintaining records for tens of thousands of users quite fine, and does greatly devalue the need for a copy ID button being right up front.

**Comment by Zer0-One** [comment]
i would agree with @stqism. perhaps building in some more DNS-discovery functionality should be higher up on the priority list.

**Comment by zetok** [comment]
@ItsDuke 
I don't think that usage frequency is high enough to justify button, but I thought that button would be something that would be more self-explanatory than clicking on avatar/status orb to get it, and thus it would be justified. Maybe I am wrong in that. Dunno, that's why I'm asking whether my idea could be used ;-)

If it being a bit "hidden" isn't a problem then I guess it's fine to have it in status orb/avatar menu?

EDIT: @dubslow last thing isn't really a request, but rather it's there to ask BTW whether anyone feels like something like that is needed.
I guess I could have marked it as such better..

**Comment by zarelit** [comment]
@dubslow @zetok Considering that the ID is often needed when you add a friend, what about adding it as a label in the "Add friends" dialog like RetroShare does?
I feel like it's consistent with a "here's my ID, here I paste your ID, now we're friends" logic

**Comment by zetok** [comment]
@zarelit RetroShare doesn't have a good UI to begin with, so copying what they do doesn't seem like a good idea.
From my personal experience, that "logic" doesn't work when it comes to users. Explaining to user what to do in retroshare was, to put simply, pain in the ass. And user still was confused.

Going to "Add" tab just to copy ID is hardly an improvement from going to settings to get it, especially considering that you don't need to manually manage your Tox ID to just add your friend's Tox ID..

That's at least how I see it.

**Comment by codedust** [comment]
@zetok I think most users would obviously click the "add friend" button when they want to add a friend.
Considering that, the "add friend" dialog seems to be the logic place for your Tox ID.

**Comment by ArchangeGabriel** [comment]
Normally, if I go to “Add Friend”, it’s because I already know the ToxID of the friend I want to add, and I shouldn’t need my ToxID then.

**Comment by codedust** [comment]
@ArchangeGabriel Yes. That's what people do if they know how the procedure works. People who don't know how to add friends would first check this dialog. (At least that's what I would do if I didn't knew the concept.)
We should add an explanation to the "add frieds" dialog (we should do this no matter how we decide about this issue) and imo, we also should place the your own Tox ID there (and maybe somewhere else too).

**Comment by ArchangeGabriel** [comment]
OK, make senses, maybe open a new issue about add friend window for this explanation text and whether to have ID there or not?

For this issue, I would propose to be able to right click on you identity (which currently appears to do nothing) and have a “Copy ID” line, just like for other contacts.

**Comment by NetworkJack2** [comment]
I think adding a third bar in the black area on the top between alias, and status, (someone like venom), with a simple click copies it, and much of the functionality of settings -> identity -> profiles implemented in a drop down menu for either right click, or long press(phone style)

such as load(mabey rename to "import"), export, new tox id for the drop down menu. A redundant "copy" might also help. This at least sounds simple, I am told it is not, but it is something to consider.

**Comment by ovidiusabou** [comment]
I would expect clicking the avatar or the name to bring up a profile view that includes the tox ID and the capability to change the name and the picture. It would require two clicks but it's pretty straightforward. The concept of a profile that's accessible by clicking your own name/photo is pretty widespread.

This would mean moving the public info and tox id sections of the identity settings tab to this profile view

**Comment by ProMcTagonist** [comment]
@ovidiusabou 
The profile view you're describing is the Identity tab. I'm also not keen on giving up 1-click name, status message, and avatar editing.

@ArchangeGabriel 

> right click on you identity

I would like this. Right now right clicking tries to edit and that's wrong.

**Comment by ovidiusabou** [comment]
@ProMcTagonist do you change the name that often or more often than sharing your ID? The way it works right now is more oriented towards a power user IMO. Most programs I can think of have a profile page that is accessible by clicking your picture or your name.

Right clicking in general is not intuitive enough in my opinion

**Comment by ovidiusabou** [comment]
See this as an example:

![qtox-profile](https://cloud.githubusercontent.com/assets/991166/6471267/1e67ecac-c1f2-11e4-9838-b0b5f6933435.png)

**Comment by Mutisk-zz** [comment]
What if the avatar could be made a draggable so that translates to pasting the user id?

This should also change it so the "change avatar dialog" only shows on right clicks, maybe even menu selected. (right now it's activated on any mouse button, and I've accidentally made it more than once already)

**Comment by ovidiusabou** [comment]
That would be a nice shortcut, but it's not intuitive, you have to know upfront about it, so it doesn't fix the issue. Still, a nice idea though.

**Comment by Mutisk-zz** [comment]
I could argue it's intuitive for some now. Me, I do it a lot in KDE for sharing http-links, inputting file and folder locations to terminals, opening files.

Would a tool tip *Drag to copy/paste ID" help? (I think new users would discover it).
Edit: I can do it with Psi, dragging a contact pastes the jabber ref.

I would like to see both what @ovidiusabou proposed and also a draggable method be implemented. That it does not update the chat area when clicking your own ID is inconsistent, since it does for all contacts.

Edit2 (apologies): If I can copy friends id by right-click into menu, why not also grace the 'self' with the same?

**Comment by TheLastProject** [comment]
What about simply educating the user? We should have a "first run" page anyway (see #1249), so we could just put a screenshot of qTox in there, with a few arrows and circles indicating what everything does, like this (but with more descriptions and readable text):
![qtox_intro_2](https://cloud.githubusercontent.com/assets/1885159/6555431/4daa1fbc-c666-11e4-8053-c899a910e378.png)

Obviously, this is a VERY quick mock-up, but it should get my idea across.

**Comment by ovidiusabou** [comment]
@TheLastProject That's a very good idea, regardless of the UI. I think it should be a separate issue, because to me it seems to be unrelated.

**Comment by zetok** [comment]
Since PR was merged, closing this issue.
