### ISSUE TITLE
Clipped device names in settings on Windows 8

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#1014]
Picrelated: ![](http://a.pomf.se/bvjjdb.png)

**Comment by derMart** [comment]
Hi, I discovered another bug but its highly related to this one, so I will post it here.
In the last jenkins win32 build (http://104.219.184.93:8080/job/qTox-win32/413/) device names are not clipped but any non ASCII char is invalid (those cannot be opened). In my custom build it's valid, but clipped (see https://github.com/tux3/qTox/pull/1008). I am using OpenAL soft 1.16.0.  I suspect this due version change. Strings seem to be replaced from "local encoding" to UTF8 from 1.15.1 -> 1.16.0 (at least on windows). Replacing 1.16.0 dll in my custom build with jenkins' one confirms this. Is it possible jenkins still uses 1.15.1? Could you upgrade to 1.16.0? That way audio should work on most languages at least.

**Comment by suhr** [comment]
@tux3 @dubslow

**Comment by tux3** [comment]
I will be updating Jenkin's OpenAL to 1.16.0 soon.

EDIT: This should be fixed now.

**Comment by derMart** [comment]
yup, https://tux3-dev.tox.im/jenkins/job/qTox-win32/416/ and https://tux3-dev.tox.im/jenkins/job/qTox-win64/100/ fix utf8 characters and clipped device names. @suhr can you confirm this?
