### ISSUE TITLE
qTox doesn't handle well UTF names of bootstrap nodes

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1016]
`"Core: Bootstraping from Martin SchrÃ¶der, addr` ← should be `Schröder`

**Comment by dubslow** [comment]
Is that in terminal or in log? Probably a simple misconversion somewhere

**Comment by zetok** [comment]
@dubslow in terminal, but my terminal has no problem with utf, since both of those (with error and without) were copied from terminal..

**Comment by dubslow** [comment]
No I know, I'm asking for purposes of trying to track down the issue (although frankly, this is very minor on the massively long list of issues to look at).
