### ISSUE TITLE
unable to copy/paste out

### ISSUE THREAD

**Issue by zwischen** [qTox/qTox#1017]
I am unable to copy/paste text in and out of qtox.  If I highlight a section of qtox text I want to save for any reason, the entire log is saved--not just the section I request.   Nor can I copy/paste into qtox from my files...though I was able to copy/paste from term into qtox.

**Comment by dubslow** [comment]
There is an entirely rewritten chat form nearly ready for merging into master that should hopefully fix a variety of copy/pasting issues.

**Comment by zwischen** [comment]
great!  I look forward to that!
