### ISSUE TITLE
Set WM_URGENT when attention is required

### ISSUE THREAD

**Issue by mgmillani** [qTox/qTox#1020]
The WM_URGENT hint allows the window manager to call attention of the user when the window requires immediate attention (e.g. a message was received).

This is possible with XSetWMHints():
http://tronche.com/gui/x/xlib/ICC/client-to-window-manager/wm-hints.html#XWMHints

**Comment by dubslow** [comment]
This is X specific, while qTox is cross platform. Notifications are on the todo list, but doing them in a cross platform manner will be quite difficult.

**Comment by mgmillani** [comment]
I see. 'QApplication::​alert' seems to use '_NET_WM_STATE_DEMANDS_ATTENTION' instead, so I was searching for the wrong thing. I guess setting 'WM_URGENT' is not necessary then.
Thanks anyway!
