### ISSUE TITLE
[Suggestion] Add "new groupchat" to "invite to" menu

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#1021]
Currently, when an user wants to start a group chat with another user, they first have to create a new groupchat clicking the groupchat button, and then invite an user to it. To me, this workflow is not logical, and I propose the following solution:

Add a "new groupchat" option to the "invite to" menu option when you right-click an user. Clicking this option should create a new groupchat, switch to it, and immediately invite the other user.

**Comment by dubslow** [comment]
If you're starting a groupchat, doesn't that mean you want to invite more than one other person? So you'd still have to invite other people with current methods.

**Comment by TheLastProject** [comment]
Well, yes, but this method gets rid of a step, not making people explicitly open a group chat first, which I feel will make the process simpler and more consistent.

Maybe the group chat icon could then be changed to show a dialog box allowing you to select multiple people in your friend list to invite, to make the button itself more useful? That's just a secondary idea not related the this specific issue, though.

**Comment by ArchangeGabriel** [comment]
That’s a great idea, we could select multiple contacts (keeping Ctrl pressed like anywhere else) and then invite to, and here either an existing group or a new one. That would be great!

**Comment by sudden6** [comment]
This has been fixed along the way, please comment to reopen if it isn't fixed.
