### ISSUE TITLE
Graphical error in data transmission

### ISSUE THREAD

**Issue by Lednerb** [qTox/qTox#1022]
If the name of the file is too long, the edge is too small and does not grow.

![grafik-bug](https://cloud.githubusercontent.com/assets/2056876/5794190/68464dc0-9f63-11e4-9497-19d42e2d05c2.png)

**Comment by mannol** [comment]
Wow dude, your font is really blurry! I'm surprised you can even read it; maybe it's a bug in qTox?

**Comment by zetok** [comment]
it'll be fixed by chatlog v3 (#974)

**Comment by Lednerb** [comment]
:+1:
