### ISSUE TITLE
Emoticon sizes don't change when settings change them (may be locked to font size)

### ISSUE THREAD

**Issue by redsteakraw** [qTox/qTox#1026]
Emoticons don't change size, qTox's settings don't have and effect on the size.  They appear to be locked to the font size.  They also can't get smaller.  qTox is scaling down the size in my case as I compared the original .png files used.  I also tried to set the setting to the actual pixel size as the emoticon images and it still has no effect.

**Comment by dubslow** [comment]
This may change with the new chat form.

**Comment by redsteakraw** [comment]
I also tested this with another qTox user and the bug was replicated

**Comment by zetok** [comment]
@redsteakraw it's a ~known "issue", since that setting doesn't really change anything, AFAIK

**Comment by dubslow** [comment]
Twould seem that this _will_ change with the new chat form. :)
