### ISSUE TITLE
problem with video call on acer running windows 7

### ISSUE THREAD

**Issue by gott3rfunk3n83** [qTox/qTox#1031]
Recently updated qtox this november. But when i tried to video call from my acer laptop to my asus. The video from asus is picked up by the acer, but the video from my acer to the asus only displays a black screen. I the camera on the laptop and its workin fine and during the call the camera indicator lights are on. Must be some glitch in the new update.

**Comment by DanTheBritish** [comment]
Are you running the latest version on both ends of the call?

**Comment by gott3rfunk3n83** [comment]
Yep same updated version. I'm gonna try to uninstall then start from
scratch on both machines and see if problem persists.

**Comment by gott3rfunk3n83** [comment]
Still not fixed. Tried the latest nightly build. When i open video call it messes up the camera driver of my netbook then all apps cant use the camera anymore because it only displays a washed out white image. Have to uninstall then reinstall the camera drivers again to get it working. Hope it gets fixed.

**Comment by tux3** [comment]
@gott3rfunk3n83 Can you tell what is the model of you camera ?

**Comment by gott3rfunk3n83** [comment]
Its the built in camera of my netbook.

**Comment by tux3** [comment]
This should be fixed with FFmpeg.
