### ISSUE TITLE
Broken Tox Data Descryption Password Dialogs

### ISSUE THREAD

**Issue by srkunze** [qTox/qTox#1034]
I used toxic to create several encrypted Tox Data files. They appear in qTox and I can work with them without an issue. However, there are several, I would say combined, issues with this kind of setup:

1) opening up the client, it asks me for the password of the last ToxID **without** telling me which one.
2) clicking on "Cancel" does always result in an "empty password" message which leads me back to password input

Clicking on "OK" with wrong passphrase leads to dialog "Password Error" where I can choose between "Reinit current profile", "change profile" and "try again".

3) dialog "Password Error" looks damaged (buttons missing, buttons somewhere else in the client, buttons not clickable) most of the times, sometimes qTox crashes when displaying it
4) clicking on "Reinit current profile" and "change profile" of the dialog "Password Error" qTox always crashes
5) clicking on "Try again" crashes sometimes, if not leads back to password input

**Comment by dubslow** [comment]
These are known issues; encryption is disabled in the UI currently for these reasons. Fixes are mostly complete in the encryption PR, but there's still a few bugs I need to fix before merging. I.e., hold on.

**Comment by srkunze** [comment]
Something I can do to help?
