### ISSUE TITLE
Broken russian nicknames in history after restart

### ISSUE THREAD

**Issue by soredake** [qTox/qTox#1036]
![uwiheh](https://cloud.githubusercontent.com/assets/5204968/6094168/64fa4d14-af27-11e4-90ba-5122c5531db7.png)

**Comment by dubslow** [comment]
@apprb

**Comment by apprb** [comment]
Can't reproduce.

**Comment by suhr** [comment]
Windows is used, I presume?

**Comment by soredake** [comment]
Yeah, windows.
