### ISSUE TITLE
Can't create emoticons that contain < or >

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#1037]
```
<emoticon file="concern.png">
<string>:<</string>
</emoticon> 
```

Doesn't display the file in chat. Neither does

```
<emoticon file="angry.png">
  <string>😠</string>
  <string>>:(</string>
</emoticon>
```

**Comment by dubslow** [comment]
Did you try &lt; and &gt; ?

**Comment by ProMcTagonist** [comment]
I'm not sure what you mean.

**Comment by tux3** [comment]
He probably means &lt; and &gt; but GitHub shows that as < and > when you type it in comments

**Comment by ProMcTagonist** [comment]
I'll try that right now.

EDIT:

Still no luck with 

```
<emoticon file="concern.png">
<string>:&lt;</string>
</emoticon> 
```

and

```
<emoticon file="angry.png">
  <string>😠</string>
  <string>&gt;:(</string>
</emoticon>
```

When I click on the emoticons from the popup, the correct text is inserted, it just doesn't show the image when I send it.

**Comment by tux3** [comment]
This is fixed.

You should use &lt; and &gt;  but < and > should work too in most cases.

**Comment by ProMcTagonist** [comment]
Thanks :)

**Comment by ProMcTagonist** [comment]
Clicking the emoticon puts the &code into the chat box, which then doesn't get recognized as the correct sequence to show an emoticon. I also can't use > or < in the xml file or everything after that character gets cut off-- no other emoticons show up in the popup. Typing the sequence works fine.

Desired behavior: clicking an emoticon from the popup inserts the same string that you would type to get it.

**Comment by dubslow** [comment]
That's a regression due to the chatform handling emoticons better. The popup should be modified accordingly.
