### ISSUE TITLE
Switching and Re-ordering Chats like Browsers do

### ISSUE THREAD

**Issue by srkunze** [qTox/qTox#1043]
ctrl + page-up/down <<< switch to next tab
ctrl + shift + page-up/down <<< move current tab down or up

chat = tab

**Comment by tux3** [comment]
Dup of #997
See also #1019

**Comment by suhr** [comment]
And https://github.com/tux3/qTox/issues/645

**Comment by ProMcTagonist** [comment]
I like these. You should suggest them in the keybinds issue.

**Comment by zetok** [comment]
Closing, since it's a duplicate and has been done.
