### ISSUE TITLE
Better auto-updates, possible in the background as opt-in

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#1044]
The current idea :
Auto updates would now be fully silent, installed and downloaded in the background.
They can be disabled/enabled in the settings, and are disabled by default.
But on first run, the user is prompted to enable auto updates (opt in). 
All current users of qTox will also be prompted when they first update to qTox with the new update system.
We could also add a "Check updates now" button in the settings.
And we could display the version/build date somewhere (we already display it in the log).

**Comment by tux3** [comment]
Note to self : You'll probably want to install a custom service running as system. Make absolutely sure it only accepts signed files, wouldn't want a blatant local priv escalation. The good ol scheduler could work too but people don't want a qtox-updater visible in taskmgr, like that jusched shit. So a service, taking RPC calls somehow. COM ? Ugh. Look at that ServiceController thing. Maybe just a thin wrapper that ocan only start qtox-updater? But then that's not silent. So rewrite a full service. Also, we need atomic upgrades. Nobody should have to wait for updates to install. Symlink magic? Hard links? A thin wrapper?

**Comment by Draako** [comment]
Perhaps an option to run the updater as a (Windows) service? Some accounts in Windows are run as standard users and thus a password is needed for every single update.

**Comment by zetok** [comment]
It should be a build time option whether provide that option (as it already is) and it should be **opt-out** option, instead of opt-in.

> We could also add a "Check updates now" button in the settings.

Actually, there's generally needed page `About`, in which one could check it like in ff, also in `About` there should be listed license, since it's one of GPL requirements.

Perhaps `About` could be located next to other settings tabs?

**Comment by tux3** [comment]
I'm happy with what we have now, let's not over-engineer it.
