### ISSUE TITLE
Use svg instead of png

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1050]
I already bumped into this problem even though i am not using HiDPI monitor. Tray icons do not scale good when size of taskbar changes. This is especially true on linux where users have more freedom to change things like this. Changing tray icon format to svg immediately offers perfect solution and on top of that we can get rid of `_2x` icons. I think client should completely migrate to using svg simply because thats the format design is done in anyway and it offers perfect scaling. Someone with HiDPI monitor should comment on this too.

**Comment by ghost** [comment]
@dubslow any objections? If not i would get started.

**Comment by dubslow** [comment]
Go right ahead, with your other PR we know have svg support anyways.
