### ISSUE TITLE
When using compact contact list, new friends appear in the large style

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#1051]
Wish I could delete things

**Comment by dubslow** [comment]
I had unchecked the box and then elected not to restart, then came back several hours later and forgot I had unchecked without restarting

**Comment by ProMcTagonist** [comment]
It's still a problem that users get mixed results when they check the option and don't restart. If it requires a restart anyway, it should refrain from changing anything until restart.

**Comment by dubslow** [comment]
Good thing it doesn't require restart :)
