### ISSUE TITLE
Webcam displays only grey in the lower half of the image

### ISSUE THREAD

**Issue by roberdorfer** [qTox/qTox#1055]
Arch linux 64 bit

![screenshot_2015-01-26_17-55-38](https://cloud.githubusercontent.com/assets/6862450/5903911/c5dc697a-a584-11e4-8e49-6e979471e864.png)

Setting camera output to yuyv in guvcview fixes the issues in guvcview, but doesn't have an effect on qtox.

**Comment by zetok** [comment]
@RoBi89 is issue still reproducible one newest builds https://wiki.tox.chat/binaries ?

**Comment by roberdorfer** [comment]
Seems to be fixed, at least I couldn't reproduce it anymore.

**Comment by agilob** [comment]
It's reproducible when one of the users has slow upload ;/

**Comment by tux3** [comment]
If it's your own webcam doing this in the settings, it's a bug (it seems to be fixed?), if it's in a video chat, that's "just" bad video quality due to toxcore being unreliable.
Please leave a comment if you still have this bug.
