### ISSUE TITLE
Package fails lintian

### ISSUE THREAD

**Issue by riking** [qTox/qTox#1056]
The Ubuntu Software Center shows the following Lintian failures, prompting an install confirm dialog ("this package is of low quality"):

```
E: qtox: maintainer-name-missing support@tox.im
Use of uninitialized value $name in pattern match (m//) at /usr/share/perl5/Lintian/Check.pm line 214.
```

I tested the x86_64 deb package.

Additionally, these other warnings are produced when running lintian plain (Ubu software center likely ignores some of these):

```
$ lintian qtox-x86_64.deb 
E: qtox: statically-linked-binary usr/bin/qtox
E: qtox: debian-changelog-file-missing
E: qtox: no-copyright-file
E: qtox: misplaced-extra-member-in-deb _gpgorigin (unexpected member at position 3)
E: qtox: extended-description-is-empty
E: qtox: maintainer-name-missing support@tox.im
Use of uninitialized value $name in pattern match (m//) at /usr/share/perl5/Lintian/Check.pm line 214.
W: qtox: unknown-section default
W: qtox: binary-without-manpage usr/bin/qtox
```

**Comment by tux3** [comment]
@stqism

**Comment by dubslow** [comment]
It's complaining about statically linked lol, most of these will never be satisfied I think (though most of them probably could be). Maybe when tox is "done" we'll properly dynlink.

**Comment by riking** [comment]
Only the top two need to be fixed, I think.

**Comment by zetok** [comment]
Closing, since there is no proper packaging ATM.

Please comment for reopen if with new package repository this still will be an issue. (the one on Tox wiki is not yet a new repo, which is WIP)
