### ISSUE TITLE
No Tray Icon on xfce desktop linux

### ISSUE THREAD

**Issue by israuor** [qTox/qTox#1057]
no matter what I do, can't get a tray icon to appear.

**Comment by agilob** [comment]
Did you compile it yourself? What version of Qt was qTox built with?

We need a label for issues about tray icon...

**Comment by israuor** [comment]
yes.. compiles myself from git.  How can I see the Qt version qTox was built with?

**Comment by agilob** [comment]
Check in your package manager.

**Comment by israuor** [comment]
I've got qt 5.4.0-3 installed. 

and also 4.8.6-4

**Comment by suhr** [comment]
Try using Qt 5.5.0. Also, see https://github.com/tux3/qTox/issues/968

**Comment by strk** [comment]
Was this fixed by 5fd2828 @israuor ?
+1 for a "trayicon" label...

**Comment by israuor** [comment]
can tell you in a minute.. compiling ... 

nope.. still no tray icon.

**Comment by strk** [comment]
Sorry it turns out you need to enable the new code passing
ENABLE_SYSTRAY_UNITY_BACKEND=YES to qmake

Also please report the value of the XDG_CURRENT_DESKTOP variable
in the env you start qtox from

**Comment by israuor** [comment]
slooooowly... what do i have to do exaktly ?

**Comment by agilob** [comment]
```$ ENABLE_SYSTRAY_UNITY_BACKEND=YES; qmake
$ make
$ ./qtox```

**Comment by israuor** [comment]
still no tray icon :-(

**Comment by msteinbeck** [comment]
Just tested the current qTox build with Xubuntu 14.04 and system tray now works. @israuor maybe it works for you too?!?

**Comment by agilob** [comment]
bump

**Comment by vessd** [comment]
Today I had a tray icon
qt 5.4.1-2
archlinux current (xfce 4.12)
![2015-03-14 17 14 52](https://cloud.githubusercontent.com/assets/8783865/6651953/a932cd4c-ca6d-11e4-8878-140a03756232.png)

**Comment by tux3** [comment]
Yes, this should be fixed now.
