### ISSUE TITLE
Audio stopped working in Ubuntu 14.04

### ISSUE THREAD

**Issue by strk** [qTox/qTox#1058]
It used to work just fine "recently" but unfortunately I still hadn't found the working commit. Meanwhile I log the issue...

**Comment by strk** [comment]
I'm not sure it is related, but is it normal that the "Playback" and "Microphone" sliders in "Audio Settings" pane of the "Audio/Video" tab in settings are always reset to 0 at startup ?

**Comment by tux3** [comment]
@strk the sliders are still just placeholders, they don't do anything.

Can you post the content of ~/.config/tox/qtox.log, please ?

I can't immediately reproduce with my Ubuntu 14.04 netbook.

**Comment by strk** [comment]
On Tue, Jan 27, 2015 at 04:54:41PM -0800, tux3 wrote:

> @strk the sliders are still just placeholders, they don't do anything.

Ah, that's interesting!

> Can you post the content of ~/.config/tox/qtox.log, please ?

I'd first try to confirm the problem as I'm not sure it's a real one.
Is the GroupBot supposed to stream music on call ?

**Comment by tux3** [comment]
The groupbot itself doesn't stream anything afaik, but users in the audio groupchat can.

**Comment by strk** [comment]
Thanks, with this info and some gentle partecipant I can confirm everything still works as of b6f79e736599e4b147d31cce4a6d9518a8afab12 -- sorry for the noise
