### ISSUE TITLE
qtox.log uses confusing YYYY-DD-MM date format

### ISSUE THREAD

**Issue by alexanderino** [qTox/qTox#1060]
qtox.log uses a non-standard date format that can be potentially misunderstood. For instance, today is represented as 2015-28-01. The long format also follows the same pattern.

Here is a snippet from my qtox.log (running the latest Win64 build):

```
2015-28-01 19:00:14 file logger starting
19:00:14 built on:  20:34:44 Jan 27 2015 ( 1422390769 )
19:00:14 commit:  a62b1dc7ace77e7633bf192ca77a24865bbff988 
```

Ideally, the ISO8601 standard (YYYY-MM-DD) would be the most logical choice as it's unambiguous and makes the most sense.

_Edit: fixed typo as per @zetok's comment._

**Comment by zetok** [comment]
@alexanderino you meant YYYY-MM-DD, since that's ISO8601 standard?

**Comment by alexanderino** [comment]
You're absolutely right, that's what I meant. It pays to proofread one more time! :+1:

**Comment by dubslow** [comment]
Erps, ma bad lol

**Comment by alexanderino** [comment]
Thanks for the quick response. Confirming that the issue is fixed in the latest build:

```
2015-01-29 07:50:03 file logger starting
07:50:03 built on:  12:44:28 Jan 28 2015 ( 1422448942 )
07:50:03 commit:  edef42ec698546df14d11d89f053e306a1020dc3
```
