### ISSUE TITLE
qTox loses history

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1062]
Running multiple instances of qTox with different history settings often results in qTox unchecking checked settings, which results in history loss.

Please fix.

**Comment by dubslow** [comment]
> multiple instances

I'm not about to implement file locking for all the files qTox uses. Instead, I'd rather implement having multiple profiles from the same instance, à la that other issue.

**Comment by tux3** [comment]
A simple solution would be to just refuse to open two instances on the same profile at the same time. Something like that could be done with IPC, maybe. File locking could work too. Maybe a single lock per profile.

@dubslow I'm not sure why you're wontfix'ing it, though. It's an actual bug in qTox, and not impossible to fix. You can just leave it for later if you don't want to tackle that right now.

**Comment by dubslow** [comment]
Because I should implement running multiple IDs from one instance, and that would eliminate the need for multiple instances; then, we could "fix" this by simply "banning" multiple instances with the IPC. So won't fix in the direct sense.

**Comment by tux3** [comment]
Ok

**Comment by zetok** [comment]
> A simple solution would be to just refuse to open two instances on the same profile at the same time.

Except that bug isn't about running same profile, but different profiles…

**Comment by tux3** [comment]
Saving history is a personal setting and we have a lock on profiles now, so this particular bug ought to be fixed. If there's still a bug, it's likely to be something else, but please leave a comment and I'll reopen.
