### ISSUE TITLE
NSIS Error

### ISSUE THREAD

**Issue by Disinterpreter** [qTox/qTox#1066]
NSIS Error on install qTox.
It's bug on windows 32bit and windows 64bit.

```
---------------------------
NSIS Error
---------------------------
Installer integrity check has failed. Common causes include
incomplete download and damaged media. Contact the
installer's author to obtain a new copy.

More information at:
http://nsis.sf.net/NSIS_Error
---------------------------
ОК   
---------------------------
```

**Comment by tux3** [comment]
Can you tell where you downloaded qTox ?

I can't reproduce with the latest qTox 64bit installer on a fresh Windows 7.
Are you sure you didn't have a corrupt download ?

**Comment by Disinterpreter** [comment]
I install qTox from link in main github page. https://github.com/tux3/qTox/blob/master/README.md#downloads And i use Windows 7 64bit. I  tried download 64bit and 32bit, but both links give NSIS error.

**Comment by Disinterpreter** [comment]
Fixed. Close plz.
