### ISSUE TITLE
tray icon does not show correctly in metacity (gnome flashback)

### ISSUE THREAD

**Issue by strk** [qTox/qTox#1067]
I'm running gnome flashback (metacity) on an Ubuntu 14.04.01 and the tray icon only shows as a pixel, near the middle of the gnome panel.

**Comment by strk** [comment]
This image shows my panel before (up) and after (down) opening up qtox:
http://strk.keybit.net/tmp/qtoxtray.png

Note the small white dot on the left of the keyboard icon in the middle of the panel.
NOTE: it

**Comment by strk** [comment]
Sorry, I meant to note that the small dot is a vertical white bar during startup, then becomes a dot.
Also it is invisible if I switch "Light icon" off.

Final note, I did see the icon once (only once) some time ago... as if it was a race condition.
Could it be some memory error corrupting the in-memory icon ?

**Comment by worfox** [comment]
Try installing sni-qt, that worked for me with GNOME 3. Might be the same problem here.

**Comment by strk** [comment]
I do have sni-qt installed already, both 32 nd 64 bit

ii  sni-qt:amd64 0.2.6-0ubuntu1 amd64 indicator support for Qt
ii  sni-qt:i386  0.2.6-0ubuntu1 i386  indicator support for Qt

**Comment by EthanJoyce** [comment]
I'm experiencing this exact same issue with MATE 1.8.1-r1. The tray icon simply appears as a sinlge black pixel.

**Comment by donjan** [comment]
Same with gnome-panel 3.8.0 (Ubuntu 14.04).

**Comment by zetok** [comment]
Is this still the case with newest builds https://wiki.tox.chat/binaries#other_linux ?

**Comment by strk** [comment]
Binary, just downloaded and tested, remains shown in the "tray"
(the one on the center rather than the one on the right, but that's ok).

Both "light" and dark icon tested.

**Comment by donjan** [comment]
Confirming with the current binary build (commit 030a72f5611976fb91b2408d5bcdda541b63b6ed), the tray icon works fine. Thanks for your effort!

**Comment by strk** [comment]
Do you know what fixed the bug @zetok ? As the same is happening with uTox now and would be nice to know how to fix (see https://github.com/GrayHatter/uTox/issues/235)

**Comment by zetok** [comment]
@strk in qTox's case (IIRC), bump of Qt version fixed it.. so not really applicable for µTox.

**Comment by strk** [comment]
@zetok are you able to tell the Qt version that did NOT work and the one that DID ? I might look at the changelog for QT itself...

**Comment by zetok** [comment]
@strk IIRC 5.4 didn't work, while 5.5 did work.
