### ISSUE TITLE
Enter Key Not Sending Message

### ISSUE THREAD

**Issue by sierramountain** [qTox/qTox#1068]
Why doesn't the enter key send when messaging, it only seems to return? I'm using the 32bit window version.  Does anyone know how to fix this issue, not sure if its my computer or the program. Thanks!

**Comment by dubslow** [comment]
On GNU-Linux, my numpad enter key doesn't work, but the primary enter key on the keyboard does.

**Comment by sierramountain** [comment]
Good point, however for me neither the numpad or the primary enter key can 'send', both return

**Comment by srkunze** [comment]
Is the "primary enter key" not the RETURN key?

I remember them to have different purposes like: return -> new line, enter -> submit form

**Comment by sierramountain** [comment]
Yes it is has two functions 'return' and 'submit' generally speaking but finding that it will only 'return' when using it in Tox
