### ISSUE TITLE
[optional] Change status to “away” after being inactive for a while

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#107]
Add to user settings the option and the delay value.

**Comment by dubslow** [comment]
Skype at least is able to detect activity on a computer-wide basis, though I have no idea how.

**Comment by ProMcTagonist** [comment]
Skype doesn't just yellow you after you leave it alone for a while? It detects if you're using other applications? That's pretty interesting.

**Comment by tux3** [comment]
Fixed by #447
