### ISSUE TITLE
Make microphone slider work

### ISSUE THREAD

**Issue by soredake** [qTox/qTox#1074]
Because I hear some of my friends is pretty quiet, and I have to do qtox louder through windows mixer. Thanks.

**Comment by ghost** [comment]
As he says. Audio sliders affect nothing and you need to change volume in windows audio mixer. It's not a problem tet-a-tet, but group voice chat with 3 more people is kinda hell.

Windows 7@64-bit

**Comment by fenque** [comment]
When will it be implemented? I hear your friends quietly because of this.

**Comment by tux3** [comment]
Implemented by 4a40269698d2e8a8b492916e43916e59f95a9f31
