### ISSUE TITLE
qTox icon looks pixelated on Windows 8

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#1075]
As reported by Evropi

**Comment by freezurbern** [comment]
This is an issue on Windows 7, primarily the desktop icon.

**Comment by zetok** [comment]
Is this still an issue with newest builds https://wiki.tox.chat/binaries#windows ?

**Comment by NoxNoctium** [comment]
It is, icon didn't change in quite some time. I could look into creating one with all common sizes added.

**Comment by agilob** [comment]
Is it sill an issue after using SVG icons?

**Comment by DanTheBritish** [comment]
![image](https://cloud.githubusercontent.com/assets/4997521/12079354/8f3411a0-b22d-11e5-91d1-700d66c227c5.png)
![image](https://cloud.githubusercontent.com/assets/4997521/12079352/85974090-b22d-11e5-9407-7263c8f72e21.png)
Still using tiny icon for me (Windows 10, latest build on Jenkins)

**Comment by sudden6** [comment]
Should be fixed by https://github.com/qTox/qTox/pull/4127

Please comment if it isn't.
