### ISSUE TITLE
qTox doesn't go into the foreground when restoring from tray in some cases [Windows]

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#1084]
Situation:
- enable "Minimize to tray"
- minimize qtox
- restore it from tray

-> it's restored minimized

This looks like normal behaviour (technically) but users like me want to see the qtox window immediately when clicking the tray.

**Comment by towlie** [comment]
Summary: qTox should never restore into the minimized state when clicking the tray icon. It should foreground the window.

**Comment by towlie** [comment]
I had to remove a part of the first post because it deserves a seperate issue and the real behaviour was worse then described.

**Comment by DaoDezi** [comment]
Same issue with qtox in lubuntu 14.10 (LXDE). Qtox never shows the main window if it's minimized by clicking on the taskbar. Enabled "Minimize to tray".
PS: with "Minimize" button on window's header same problem
