### ISSUE TITLE
Psuedo-offline messaging causes some messages to be delivered twice

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#1089]
When chatting with someone with a bad Internet connection, I often receive a pseudo-offline message twice. This is not too much of a problem, but more of a slight annoyance. It'll go along the lines of this:

```
Friend: Yeah
Friend is now offline
Friend is now online
Friend: Yeah
```

Despite the "Yeah" message only being sent once by the friend.

**Comment by dubslow** [comment]
@apprb

**Comment by apprb** [comment]
Hm you right, in current implementation exist non-zero possibility for unnecessary triggering resending a message. Will fix soon :)

**Comment by dubslow** [comment]
Comment for reopen

**Comment by TheLastProject** [comment]
Well, this may have solved it for qTox (I haven't ran into the situation qTox to qTox again) but a Toxic user did cause double messages to appear on my side. A better fix would probably involve filtering out double messages on the receiver's side. I assume toxcore does not have any way to tell a resent message apart from the original message?

**Comment by dubslow** [comment]
Each message gets a ~unique ID. I'd be curious to know if it was the same for those spurious messages.

Also, file a bug report with Toxic :)
