### ISSUE TITLE
[Regression] qTox cannot into stereo audio input

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1090]
Needs patched toxcore to (not)work https://gist.github.com/zetok/a326be414c73eb64c48f

It's not a recent regression, thanks for @suhr for finding out what caused sound to not be working.

qTox doesn't stream sound with patched toxcore.

**Comment by dubslow** [comment]
@tux3

**Comment by zetok** [comment]
still a problem on 2ea3d73756b5e846dac461f9762eaca12dad8134

**Comment by tux3** [comment]
@zetok Does it work now?

If not, what exactly is the problem? I tested 2 channel audio (although with a mono microphone, so a bit pointless...) today and it seems to work.

**Comment by zetok** [comment]
I'll re-test when new AV will get merged into qTox - before that there's no point in testing something that is going to change anyway.

**Comment by antis81** [comment]
@zetok Going to close this issue as we can handle stereo input devices now. Could you please retest?
