### ISSUE TITLE
Only the first audio conversation works, then no sound and errors (microphone)

### ISSUE THREAD

**Issue by calimeroteknik** [qTox/qTox#1092]
# The issue

The first audio conversation I establish between two clients works, but then for the second (and other subsequent) attempts I get no sound.
# Diagnosis

It turns out it's an error with the microphone:
If I restart a client but not the other, and start an audio conversation, the client that hasn't been restarted produces the sound from the client that was restarted.

Logs of the two machines in the scenario described:
http://calimero.tk/paste/qtox64bit-audiocall-error.txt
http://calimero.tk/paste/qtox32bit-audiocall-error.txt (one more error, 'Core: Dropped audio frame')

My platforms: GNU/Linux (Arch Linux, 32bit & 64bit)
Software versions: tox-git gb7e0033 & qtox-git 5bd3cd0
# Towards a solution

qTox grabs the audio output at startup and I have to close it to be able to use other sound software (e.g. listen to music).
Somebody else complained about this on windows as well when I evoked this on the groupchat.

It would be great if it could grab (initialize?) the audio only when an audio call needs it, and release it at the end of the audio call.
I'm saying this here because this bug could be solved/bypassed simply by doing this.

**Comment by zetok** [comment]
@calimeroteknik things from AUR are not supported; please build manually and see if issue still exists

**Comment by dubslow** [comment]
@tux3 People have complained before about opening the audio sources at qTox starting, rather than when they're actually needed

**Comment by tux3** [comment]
I believe this is fixed, does someone still have this bug?
