### ISSUE TITLE
Encrypt profile.tox

### ISSUE THREAD

**Issue by taschenlampe** [qTox/qTox#1094]
I hope that this issue was not already addressed before...If so, close this thread.

My question is: why is the profile.tox were I store my config+contacts not protected with a password?
I stumbled into this, when I copied my profile.tox from one PC to an other one. This worked very good. But then I realized that this is far too easy.
->My profile ID could be stolen and misused without any effort.

Is there a way to protect my profile.tox. I think this would make sense.

**Comment by srkunze** [comment]
https://github.com/tux3/qTox/pull/985

You can close this issue and test the pull request to make sure it fits your needs. ;)

**Comment by dubslow** [comment]
_fingers crossed_ The above PR will hopefully be merged today, and among other things will introduce exactly this functionality.

**Comment by srkunze** [comment]
@dubslow Do you have a list of all issues that can be closed by this? :D

**Comment by dubslow** [comment]
@srkunze Nope :)
