### ISSUE TITLE
Better Recognition Whether I Received Messages

### ISSUE THREAD

**Issue by srkunze** [qTox/qTox#1095]
A friend of mine had problem with recognizing whether he received a message from one of his contacts or not. A green circle around a green circle seems not to be enough.

He suggested a small envelop to indicate unread messages.

**Comment by ProMcTagonist** [comment]
I think instead that this is a perfect opportunity to put a new message count in the circle.

**Comment by srkunze** [comment]
> I think instead that this is a perfect opportunity to put a new message count in the circle.

Sounds good.

**Comment by sudden6** [comment]
There's now a mail icon on new messages, so I think this is fixed.
