### ISSUE TITLE
qtox memory issue

### ISSUE THREAD

**Issue by soredake** [qTox/qTox#1096]
I get into the audio/video menu and qtox freezes and ate a lot of memory.
Windows 8.1 x64
log:

```
20:10:13 CameraWorker: Suspend
01:40:17 CameraWorker: Resume
01:40:42 CameraWorker: Suspend
01:40:42 CameraWorker: Resume
01:40:44 CameraWorker: Suspend
01:40:44 CameraWorker: Resume
01:40:46 CameraWorker: Suspend
01:40:46 CameraWorker: Resume
```

![screenshot at 01-43-49](https://cloud.githubusercontent.com/assets/5204968/6032571/67311d40-ac13-11e4-9e3d-c4ca82832db4.png)

**Comment by sudden6** [comment]
does the video preview show a picture?

**Comment by tux3** [comment]
Does it eventually unfreeze if you wait a bit longer, or is it completely stuck ?
In the camera led flashing while it's stuck ?

**Comment by soredake** [comment]
My camera has no led. And it's completely stuck.

**Comment by soredake** [comment]
Ooops, this happend again, no log written at this time.
