### ISSUE TITLE
[Regression] Faux offline messging doesn't work

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1098]
on 5bd3cd041d224a174df6dba59c1b9821aab1b611

![no faux](https://cloud.githubusercontent.com/assets/3148759/6038632/86b2f380-ac56-11e4-8469-333dcc111537.png)

Message was "sent" when peer was offline. In meanwhile qTox was restarted few(?) times.
Other peer is online, and message wasn't delivered for quite long time (few minutes already) after peer appeared as online. There is connection between peers, since other peer receives typing notifications.

**Comment by apprb** [comment]
In current implementation qTox tries to resend undelivered messages only after peer changes own status. So, will try to fix it along with #1089.

**Comment by zetok** [comment]
closing since #1117 got merged, I'll reopen if stumbled upon that issue again

**Comment by zetok** [comment]
on 733c684759d0009293c8f5ed0f1271101692f386
![muh month old message](https://cloud.githubusercontent.com/assets/3148759/6285111/dda59a30-b8ef-11e4-8a0e-7b8933510ba3.png)

Pls fix ;_;

**Comment by zetok** [comment]
Still there on 9dff3feac72f77819d8d47b5b3b56513dea8fa34. Since @Zer0-One lost ID to which that message was being "sent" some time ago, this issue is blocked until I (or anyone) get that problem with contact that is still "alive", or until it will be possible to "merge" contacts, so that qTox could continue trying to send message to ID that is still being used.

**Comment by zetok** [comment]
from #1805, thanks to @PKEv:

---

Description:

Info:
OS: Win 7 x32

Reproducible: Always 

Steps to reproduce:
1. in settings setup "Faux offline messaging" 
2. send message to offline friend 
3. restart app
4. message look like it was delivered then you restart app

What happened:
message look like it was delivered, but in fact no

What should happen:
message must  be undelivered and sended only then friend be online

---

find broken index in db
message in app:
![default](https://cloud.githubusercontent.com/assets/6053197/8016843/b332c49e-0bf1-11e5-9556-087ae77e75d6.png)
history in db:
![1](https://cloud.githubusercontent.com/assets/6053197/8016847/c52baf08-0bf1-11e5-81ab-b7f3c4c017cc.png)
status in db: (look - id's Much more than in the table history 
![2](https://cloud.githubusercontent.com/assets/6053197/8016865/16bc2c4e-0bf2-11e5-91c4-4d51999785e7.png)

How it happened I do not know.....
(in setting: pragma_synchronous = FULL)
UPD: (all message sended to offline friend)

---

strange what count 'message' < count 'status'

**Comment by initramfs** [comment]
Is this issue still present?

**Comment by zetok** [comment]
> Is this issue still present?

Since messages still haven't been delivered, yep,

**Comment by anthonybilinski** [comment]
Can't repro on tip. 

1. in settings setup "Faux offline messaging"
(default)
2. send message to offline friend
3. restart app
4. message look like it was delivered then you restart app
not currently the case, message is still pending, is delivered when friend comes online.
