### ISSUE TITLE
Groupchats lose your name after a while

### ISSUE THREAD

**Issue by F1ynn** [qTox/qTox#110]
![gp_bug](https://cloud.githubusercontent.com/assets/8000053/3489596/87db9538-0539-11e4-9fd0-15939465e2ed.PNG)

**Comment by dubslow** [comment]
If we're reporting groupchat bugs, then:

1) Often for me, upon being invited to that particular group (only one I've used), it only shows one user <Unknown> in the chat, and I can't send or receive any messages;

2) Groupchats are not remembered upon exiting and restarting, so I need to be invited every time I open the client

**Comment by dubslow** [comment]
Here's a new message I hadn't noticed before, regarding 1):

```
"Core: Group invite by 0" 
"Trying to join groupchat invite by friend 0" 
"Core: Group namelist change 0:0 0" 
 Widget::onGroupNamelistChanged: Group not found, creating it
```

That would explain why there's only one user...

**Comment by mouseym** [comment]
there are quite a few problems with groupchat;

becoming unknown after a while;
invite on the bot doesn't always work (TCP problem, core related)
console gets spammed with the above messages
list of names do not wrap, end up getting cut off
groupchats suddenly drop you for no reason (left with 1 person in chat)
no warning of being dropped out of chat, messages just no longer send

i think a few of these are core related anyway and are probably unfixable within toxgui

**Comment by krepa098** [comment]
In my core branch I'm simply polling an up-to-date list of group members on regular basis which turned out to be more reliably than using tox_callback_group_namelist_change.
