### ISSUE TITLE
Change "Ok" "No" "Cancel" to "Decrypt" "Delete" "Cancel" in the decryption dialogs

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#1100]
http://uxmovement.com/buttons/why-the-ok-button-is-no-longer-okay/

**Comment by dubslow** [comment]
Which dialogs, specifically?

**Comment by ProMcTagonist** [comment]
![decrypt chat history](https://cloud.githubusercontent.com/assets/4358079/6052155/69effb02-ac84-11e4-9432-1baaedc16393.png)

OK -> Decrypt, No -> Delete

![delete chat history](https://cloud.githubusercontent.com/assets/4358079/6052172/933913fe-ac84-11e4-81d2-bf3633b256ed.png)

Yes -> Delete

![decrypt data file](https://cloud.githubusercontent.com/assets/4358079/6052156/69f57a6e-ac84-11e4-927d-496415460984.png)

Yes -> Decrypt

**Comment by dubslow** [comment]
This is... difficult, it would require major refactoring. Qt has [these](http://qt-project.org/doc/qt-4.8/qdialogbuttonbox.html#StandardButton-enum) by default, and... well doing something custom may be difficult.

**Comment by ProMcTagonist** [comment]
You're really not allowed to change their labels? I'm taken aback.

**Comment by dubslow** [comment]
You can of course, but it's something of a hack. These use pre-baked QMessageDialog type things, and messing with the buttons requires digging into the internals of the dialogs... or subclassing, neither of which is fun. I may get around to it at some point, but not right now.

**Comment by dubslow** [comment]
Or maybe not so much of a hack.

TIL some more about Qt :)
