### ISSUE TITLE
Black background in tray icon (no transparency)

### ISSUE THREAD

**Issue by DaoDezi** [qTox/qTox#1102]
Lubuntu 14.10 LXDE

screenshots
![jlblkhe](https://cloud.githubusercontent.com/assets/3148759/9578101/1f6479ec-4fdf-11e5-88f3-914c693f5792.png)
![8kiufzn](https://cloud.githubusercontent.com/assets/3148759/9578109/31bacb96-4fdf-11e5-803a-c6b62a86f141.png)

**Comment by suhr** [comment]
Qt version?

**Comment by DaoDezi** [comment]
Sorry. 
Yes. qtox
from repo.tox.im

**Comment by ghost** [comment]
The opaque background is a bug in Qt itself (even KDE 3 did it wrong), and it's a huge pain in the ass to work around from what I've read. [If we're lucky it might actually get fixed this year](https://bugreports.qt.io/browse/QTBUG-35832).

As for the background being _black_ specifically, that's a value provided by the systray/WM theme itself, so blame LXDE for using bad defaults there. I get white on E17.

**Comment by zetok** [comment]
Is this still a problem with current qTox builds https://wiki.tox.chat/binaries#other_linux ?

From linked Qt bug report

> Anyway it's still in dev branch for now, so targeted for 5.5.

So I guess that qTox builds should no longer have this problem, since static Qt 5.5 is being used in them.

**Comment by zetok** [comment]
No answer, assuming that it was fixed, thus closing.

**Comment by DaoDezi** [comment]
All ok now.
