### ISSUE TITLE
Display the version somewhere

### ISSUE THREAD

**Issue by Nepoxx** [qTox/qTox#1106]
I was about to post on an issue with the version of qTox I have, but the version is nowhere to be found on the qTox UI. I suggest at least adding it to the advanced portion of the settings menu.

**Comment by dubslow** [comment]
qTox is as yet unversioned. You can find the commit in `qtox.log` though.

**Comment by simonkrauter** [comment]
I recommend to show the commit or compile date somewhere in the settings and a link to the website.

**Comment by agilob** [comment]
See `about` tab.
