### ISSUE TITLE
Audio studdering/lag when resizing window in group chat [Windows binary]

### ISSUE THREAD

**Issue by ploz** [qTox/qTox#1107]
While in a group chat, resizing the qTox window causes only your audio output to studder to all the other members of the group. Works while resizing under the following conditions:
-while looking at any conversation with atleast one message in it
-looking at the settings page
-looking at the "Transfered Files" page
-looking at the "Add Friends" page
Audio does not studder when looking at a conversion with no messages inside. Reproduction rate: 100%. Could only produce in group chats, not one on one audio.

**Comment by zetok** [comment]
If #802 was closed (audio put in separate thread than GUI), then why resizing would affect audio?

**Comment by zetok** [comment]
@ploz is this still the case with newest qTox builds https://wiki.tox.chat/binaries#windows ?

**Comment by zetok** [comment]
No answer, assuming that it was fixed, thus closing.
