### ISSUE TITLE
error while loading shared libraries: libQt5Svg.so.5

### ISSUE THREAD

**Issue by ttk2** [qTox/qTox#1114]
qtox: error while loading shared libraries: libQt5Svg.so.5: cannot open shared object file: No such file or directory

This started yesterday on my Fedora 21 install after updating to that days nightly. I used yum provides to find and install qt5-qtsvg-5.4.0-1.fc21.i686, with is supposed to provide this library, but that did not change the error. 

Just let me know if you have any questions. 

Thanks!

**Comment by dubslow** [comment]
Can you try again?

```
fpm -s dir -t rpm -n qtox --rpm-os linux -a x86_64 -v $QTOX_VER --iteration $BUILD_NUMBER --rpm-compression xz --rpm-digest sha256 -m "Tox Foundation <support@tox.im>" --vendor "Tox Foundation" -S utox --url https://tox.im --license GPLv3+ -d openal -d opencv -d qt5-qtbase -d qt5-qtsvg usr

fpm -s dir -t deb -n qtox -a x86_64 -v $QTOX_VER --iteration $BUILD_NUMBER -m "Tox Foundation <support@tox.im>" --vendor "Tox Foundation" -S utox --url https://tox.im --license GPLv3+ --deb-compression xz -d libopenal1 -d libqt5core5a -d libqt5gui5 -d libqt5network5 -d libqt5widgets5 -d libqt5xml5 -d libqt5opengl5 -d libopencv-core2.4 -d libopencv-highgui2.4 -d libqt5sql5 -d libqt5sql5-sqlite -d libopencv-imgproc2.4 -d apt-transport-https -d libqt5svg5 --after-install postinstall.sh usr
```

I just added `-d qt5-qtsvg` to the rpm command, though judging by the difference between the deb and rpm commands, I'm not entirely sure that this will fix it.

**Comment by ttk2** [comment]
I don't have build tools like fpm locally, is what you changed going to be in the nightly? (at which point I will just wait and install it tomorrow and report back) 

If not I will go through and get it all setup to rebuild locally.

**Comment by stqism** [comment]
@dubslow
please don't paste fpm commands to people, they don't know what they are nor should they. All you've done is confused him. 

@ttk2 Changes are usually deployed to the repo in under 4 minutes so it's been live for a while.

**Comment by dubslow** [comment]
Yes that was all correct, the builds are updated live, not just nightly. I changed something on the Tox server that makes what goes in the repo, and @ttk2 I was asking you to `yum update` or whatever the yum update command is. :) You'll not need to do anything your self, save updating and trying the new build.

**Comment by ttk2** [comment]
I tried yum update and didn't find anything when I first saw your comment, I ran yum clean and it comes up now, that's probably somthing with my local yum config, sorry for holding yall up. 

As for the new build same error still 

qtox: error while loading shared libraries: libQt5Svg.so.5: cannot open shared object file: No such file or directory

**Comment by ttk2** [comment]
several builds later still in the same position, since I seem to be the only on getting this it must be an oddity of my setup

**Comment by ttk2** [comment]
Ok so Qtox is now running without issue again, I have been testing tox every time I see it updated in my package manager (which is every day or so), but after installing Calibre it works, a lot of QT dependencies where installed with Calibre so I think one of them provided the needed lib.

**Comment by dubslow** [comment]
Yeah sorry, I don't really know how to RPM dependencies.

**Comment by ttk2** [comment]
Its no big deal, if someone else has this issue they can do what I did and just install Calibre, if it really becomes a problem it should not be too hard to track down which package the dependency is in now that its narrowed down to that small set. 

Thanks for your help!

**Comment by dubslow** [comment]
I'm reasonably certain it's `qt5-qtsvg`, though I would appreciate if you can test that. I'm just not sure how to tell that to the rpm. (See my original reply in this thread.)
