### ISSUE TITLE
Cursor disappears in group chat after some time

### ISSUE THREAD

**Issue by CosmicToast** [qTox/qTox#1118]
I don't know how to reproduce, but the typing cursor ( the `|` in textarea ) disappears after some time for me.
Only happens in group chat.
Running on win8.1 x86_64.

**Comment by zetok** [comment]
Does this still happen on newest qTox builds https://wiki.tox.chat/binaries#windows ?

**Comment by zetok** [comment]
No answer, assuming that it was fixed, thus closing.
