### ISSUE TITLE
problem with id tox

### ISSUE THREAD

**Issue by griffondor** [qTox/qTox#1126]
it would solve the problem of the id ausi ​​, we would like as a user it is possible to change computer keeping the meem id to keep all contact without having to export and import the profile Profile EVERY time / il faudrait réglé le problème de l'id ausi, on aimerais en tant qu'utilisateur il soit possible de changer d'ordi en gardant le même id pour garder tout les contacts sans avoir a exporter les profils et importer les profils à chaques fois

**Comment by dubslow** [comment]
This is a core issue
