### ISSUE TITLE
simplifying application for creating group 's chat bot on qtox

### ISSUE THREAD

**Issue by griffondor** [qTox/qTox#1127]
we want to create bot for group of tox as simple as botserv bot for irc channel for creating

**Comment by dubslow** [comment]
You're looking for https://github.com/JFreegman/ToxBot

**Comment by griffondor** [comment]
in fact, I find that the process is too difficult, I can not do myself

**Comment by griffondor** [comment]
resolved :  < irungentoo > I'll ask jfreegman A fair that users can creates salons

**Comment by griffondor** [comment]
this is the group command to create salons now
