### ISSUE TITLE
Installation error with git

### ISSUE THREAD

**Issue by tone77** [qTox/qTox#1128]
I report an error while installing qTox with git on Ubuntu 14.04 32bit

I run in the shell the following commands:
git clone https://github.com/tux3/qTox.git
cd qTox
./simple_make.sh

In script "install_libfilteraudio.sh" when run
gcc *.o -shared -o libfilteraudio.$EXT -Wl,--out-implib,libfilteraudio.$STATIC_EXT
there's the following error:
Creating shared object file
/usr/bin/ld: unrecognized option '--out-implib'
/usr/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status

and so, after, the installation stops with the following error:
/usr/bin/ld: cannot find -lfilteraudio
collect2: error: ld returned 1 exit status
make: **\* [qtox] Error 1

To resolve the dependency with "filter_audio" I run in the shell:
git clone https://github.com/irungentoo/filter_audio.git
cd filter_audio
sudo make install

Note: The installation creates also
/usr/local/lib/libfilteraudio.a
/usr/local/lib/libfilteraudio.so.0.0.0
/usr/local/lib/libfilteraudio.so.0
/usr/local/lib/libfilteraudio.so

I launched the script "simple_make.sh" yet and the installation is complete
without errors.

I run in the shell
./qtox

OK!

**Comment by dubslow** [comment]
I believe this is fixed, comment for reopen
