### ISSUE TITLE
deleting user data

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1131]
> if (!GUI::askQuestion(tr("Old encrypted chat history", "popup title"), tr("There is currently an unused encrypted chat history, but the password you just entered doesn't match.\nWould you like to try again?\nCanceling will delete the old history and set the password to what you just entered.", "This happens when enabling encryption after previously \"Disabling History\""), true, true))  

.

> Canceling will delete the old history and set the password to what you just entered. 

.

> Canceling will delete the old history

WTF?

Why are you so keen on deleting user data when they want to just cancel some strange shit?

I've made issue since it's not the first time that qTox does some strange, unintuitive shit that results in deleting user data.

If you could please change the way you go around it, **so that users won't have to fear pressing intuitively `Cancel` when some strange shit pops up**, and **make sure to ask at least twice _in clear way_ whenever there's possibility of deleting user data**.

**Comment by ProMcTagonist** [comment]
@dubslow stated in #1100 that it's much harder than it looks to rename the generic buttons the way they should be named, to reflect their actions.

**Comment by zetok** [comment]
@ProMcTagonist yes, but it doesn't mean that when pressing "cancel" one expects to **delete** something. It doesn't mean that there shouldn't be a "cancel", but rather that question should contain only something like `Are you sure that you want to *delete* your old history?`
