### ISSUE TITLE
Calls lag with >2 people on worse internet connections

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1140]
A friend of mine is using the Windows version of qTox and can't participate in group calls because he lags out. He can, however, participate in Skype calls with 4-5 people without any issues. Perhaps an option should be added that transmits and receives audio at a lower bitrate, for your client only.

**Comment by dubslow** [comment]
@tux3 @irungentoo

**Comment by zetok** [comment]
@anotera adaptive bitrate is planned, no ETA though (it's not a major thing compared to other stuff that has to be implemented, so I wouldn't expect it coming soon)

**Comment by agilob** [comment]
please report to https://github.com/irungentoo/toxcore if it's still an issue
