### ISSUE TITLE
demand for translations

### ISSUE THREAD

**Issue by griffondor** [qTox/qTox#1146]
would translate a function on a similar qtox google translate

**Comment by suhr** [comment]
> google translate

Oh hell, please no.

**Comment by tux3** [comment]
It's unclear what you're asking. Do you want qTox to include builtin Google Translate support, for translating arbitrary text ?

I'm not sure that's in the scope of the project.

**Comment by griffondor** [comment]
yes or similar open source translation

**Comment by griffondor** [comment]
if you could not include google translate , built an open source option similar to google translate for text translation to qtox

**Comment by dubslow** [comment]
Oh that'll be _easy_.

Quick guys, I'm sure we can utterly replace Google Translate in less time than it'll take to finish Tox completely!

**Comment by tux3** [comment]
I don't think rewriting Google Translate is part of our goals as an IM client, closing for now.
