### ISSUE TITLE
Bittorrent

### ISSUE THREAD

**Issue by griffondor** [qTox/qTox#1148]
I would love that tox supports bittorrent client for file transfer

**Comment by dubslow** [comment]
I doubt that this will ever happen. Unless I'm misinterpreting you...?

**Comment by tux3** [comment]
qTox is an instant messaging client, and while it has a lot of features, I don't think a bittorrent client is appropriate. 
Please also remember that toxcore already has a file transfer feature, this would conflict with it.
If you think toxcore should use a bittorrent-like technology for file transfers, then this is not any issue in qTox and you should bring that issue to toxcore.
Closing for now.
