### ISSUE TITLE
qTox closes when monitor it is on disappears

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#1150]
On KDE 4.13.3, qTox closes when the monitor it is disconnected

How to reproduce:
1. Connect a second monitor
2. Drag qTox to second monitor
3. Disconnect second monitor

Expected result:
KDE moves qTox to the first monitor, like all other applications.

Actual result:
qTox silently closes (I have not been able to test if it will keep running if "close to tray" is selected, that may or may not be related).

**Comment by tux3** [comment]
Dup of #518

**Comment by zetok** [comment]
Closing, since it's a duplicate.
