### ISSUE TITLE
New busy icon looks too much like blocking

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#1151]
Old busy icon: ![Old busy icon](https://raw.githubusercontent.com/tux3/qTox/6a578887712d576036455cc71a731bbd4dd90519/img/status/dot_busy_2x.png)
New busy icon: ![New busy icon](https://raw.githubusercontent.com/tux3/qTox/master/img/status/dot_busy_2x.png)

The new busy icon looks a lot like the [no parking sign](https://upload.wikimedia.org/wikipedia/commons/a/af/Sweden_road_sign_C35.svg), which indicates it is forbidden to park. Notice the word "forbidden". The association of "forbidden" with busy users seems overly strong to me, and much more fitting to someone you have blocked, because you are then literally unable to chat to them until you unblock them, and they are forbidden from talking to you.

I would like to suggest reinstating the old busy icon, and keeping the new busy icon to use as the status icon for blocked users (as soon as this support arrives in qTox).

**Comment by zetok** [comment]
↑ this

**Comment by ghost** [comment]
↓ that

**Comment by dubslow** [comment]
The problem it was changed to solve is that the old one looks the same as the away icon.

**Comment by suhr** [comment]
cast @ItsDuke

PS: don't think I like this icon too

**Comment by ProMcTagonist** [comment]
I vouch for the one that Venom used.

![600px-africa_-_do_not_enter svg](https://cloud.githubusercontent.com/assets/4358079/6205127/80521af0-b518-11e4-9cb6-9aab68e319a8.png)

With Tox Red, of course.

It fits in better, and is still distinguishable to color-blind users.

**Comment by dubslow** [comment]
+1

**Comment by urras** [comment]
:+1:

**Comment by tux3** [comment]
Fixed in https://github.com/tux3/qTox/commit/f83dacb9c43a3830723ecf4ae303c71a744ce171, we now use a busy icon that look like Venom's one.
