### ISSUE TITLE
Simplify building with CMake

### ISSUE THREAD

**Issue by firegurafiku** [qTox/qTox#1153]
Ideally, compiling the project should be as simple as opening it by IDE or giving simple `make && make install` sequence. But now it takes a lot of steps to prepare developer's environment to build qTox from scratch, which includes running various helper scripts and so on.

Currently qTox uses QMake as a build system which may be considered as obsolete, many open source Qt projects (including KDE) have already switched to CMake build system. So, I suggest switching too. 

**Pros:**
- Project still can be opened by QtCreator.
- Fully featured scripting language.
- Ability to add custom build steps.
- Possibility to automatically download, compile and locally install all dependencies (like ToxCore and libsodium) with CMake's `ExternalProject` module.

**Cons:**
- Still need to manually edit CMakeLists.txt to add a file to project (no GUI support in QtCreator).
- That fully featured language looks a bit ugly the first time you see it.

I think I can convert existing build into CMake, but there is no sense trying if this effort is not going to be adopted by the community.

**Comment by dubslow** [comment]
I had considered once long ago porting to CMake, but I don't know anything about it and didn't consider learning it from scratch worth the effort. If @tux3 concurs however, I'd be happy to see someone else do it.

**Comment by suhr** [comment]
mb use something less monstrous than CMake?

**Comment by firegurafiku** [comment]
> mb use something less monstrous than CMake?

What for example? AFAIR, CMake is a kind of _de facto_ standard for modern C++ development and has good support for Qt. And it is not very monstrous comparing to _autotools_.

**More pros for CMake:**
- Really cross platform (= not so many problems when building for Windows).
- Requires neither Python (unlike _scons_ and _waf_), nor Java (unlike _mvn_), nor Unix shell (unlike _autotools_) which may be hard to install on Windows.
- Works and used by many developers (unlike coming-soon _qbs_).
- Natively supports out-of-source builds.

Ideally, I hope to configure build system to be able to automatically fetch all dependencies, compile them and create a binary with just running “Build” command in QtCreator, thus making the project more friendly for newcomers.

**Comment by sudden6** [comment]
I would support a change in the build system. The current way with some shell scripts is very complicated and error prone.
For example: My distro uses qmake for qt4 and qmake-qt5 for qt5, so all the scripts don't work, and it took me a while to figure out the problem.
I would support cmake, seems easy if done right. But does it support Android?

**Comment by firegurafiku** [comment]
> But does it support Android?

This seems to be the hardest part. Despite CMake supports cross-compilation, there may be some subtle troubles (as for my experience with setting CMake build for AVR microcontrollers). But at least this is [doable](http://qt-project.org/forums/viewthread/36359).

**Comment by 5paceToast** [comment]
I support CMake in this case.
While I normally prefer scons (despite requiring python, I find it much cleaner), with Qt CMake has the best support and feature-parity (moc is hard).

**Comment by zetok** [comment]
@firegurafiku 

> But now it takes a lot of steps to prepare developer's environment to build qTox from scratch, which includes running various helper scripts and so on.

Nope. It requires you to have dependencies installed.

"Helper" scripts are for those who cannot install dependencies themselves, or don't use system that has sane support for using anything other than binaries.

Beside having dependencies installed, you only have to run `qmake` before `make && make install`.

It's clearly stated in documentation what are dependencies of qTox. If you have problem with installing them, perhaps you should consider improving the way they are build and installed?

> Project still can be opened by QtCreator.

Hardly a **Pro** argument, if only _gain is no regression_.

> Requires neither Python (unlike scons and waf), nor Java (unlike mvn), nor Unix shell (unlike autotools) which may be hard to install on Windows.

I think that current build system doesn't require those too? Or am I wrong?

> Ideally, I hope to configure build system to be able to automatically fetch all dependencies, compile them and create a binary with just running “Build” command in QtCreator, thus making the project more friendly for newcomers.

Please consider situation from other side as well; i.e. why would you hinder experience for those who aren't newcomers and simply are able to and want to install dependencies by themselves, or have sane distro that does it for them?

Do you plan on installing system-wide some random shit that script would download from somewhere on the internet?

# 

@sudden6 

> The current way with some shell scripts is very complicated and error prone.

There is `INSTALL.md`. If you have problems with understanding what is written there, please say which parts aren't clear, so that it could be improved.

> For example: My distro uses qmake for qt4 and qmake-qt5 for qt5, so all the scripts don't work, and it took me a while to figure out the problem.

This is a problem with your distro. Scripts are to help, but _best_ way of installing qTox is to follow instructions in `INSTALL.md`

---

Also, to all here; unless you're going to spend time resolving issues with build system and helping people with problems after switch, please don't write that you _support_ CMake.

**Comment by firegurafiku** [comment]
@zetok

> It's clearly stated in documentation what are dependencies of qTox. If you have problem with installing them, perhaps you should consider improving the way they are build and installed?

I have no problem with installing them and in principle can quite happily live with QMake. Instead, I have the problem with C++ dependency resolution infrastructure which is absent. While may other languages (Haskell, Java, Python, Ruby, so on) provide me with the ability to just specify which libraries of which versions I would like to use as dependencies, C and C++ make be manually find them all and install, using package manager or manually. As for now, I know the only one way to achieve more automatic dependency resolution in C++ projects — CMake's [`ExternalProject`](http://www.cmake.org/cmake/help/v3.0/module/ExternalProject.html) feature.

> Do you plan on installing system-wide some random shit that script would download from somewhere on the internet?

Nope. I was talking about fetching random shit of specific revision, compiling by specific compiler and installing into specific subdirectory inside the build directory.

> Please consider situation from other side as well; i.e. why would you hinder experience for those who aren't newcomers and simply are able to and want to install dependencies by themselves, or have sane distro that does it for them?

This is why I've asked your opinion beforehand. And I _do_ have a sane distro with all required dependencies present (except for ToxCore), but I can imagine what a pain it is to make a Windows build. Windows is still installed on the most of desktops and there is a lot of developers stuck to Windows. After all, enhancing support for Windows will make the project more popular and provide us with more nodes in DHT and better network performance.

If you don't think that Windows build is a pain, try building existing code with not MinGW but Visual Studio. CMake can handle that.

> > Requires neither Python (unlike scons and waf), nor Java (unlike mvn), nor Unix shell (unlike autotools) which may be hard to install on Windows.
> 
> I think that current build system doesn't require those too? Or am I wrong?

It was a part of explanation why CMake. Of course, QMake itself does not require anything of that, but, for example, `bootstrap.sh` script requires Unix shell on Windows. The main downside of QMake, in my opinion, it the lack of flexibility: you can neither have custom target, nor write arbitrary logic into build script.

**Comment by zetok** [comment]
@firegurafiku 
Thanks for your answer. It looks like using CMake would indeed improve at least some things.

That being said, I want few (IMHO) mandatory things that are requirement for switch to CMake:
1. Documentation of how one should deal with CMake. 
Everything that is doable now with QMake, should be documented how to do with CMake. By that I mean: how to deal with **defines**, [how to add new translation](https://github.com/tux3/qTox/wiki/Translating) to existing ones, etc..

From your description it would seem that you want to introduce a way to compile(?) needed dependencies in qTox's repo subdirs. There's (not sure if obviously) a need for less automagicall way of building qTox, that would work ~like current way, i.e. deps should be already in place for `make && make install` to work.
2. Proper way of compiling without automagic

↑ should be documented too.

# 

Aside from that, little nitpick

> And I _do_ have a sane distro with all required dependencies present (except for ToxCore),

Nope.
Sorry, but your distro isn't sane. Sane distro (i.e. Gentoo) makes it easy (i.e. `emerge -o qtox`) to install all qTox dependencies, and if one wants ( `s/-o//`), qTox as well. Dependencies include toxcore, libfilteraudio, and their deps… :P

# 

That being said, I have hope that CMake won't make it much harder to support qTox under Gentoo… (I know it will ;_; )

**Comment by sudden6** [comment]
@zetok 

> "Helper" scripts are for those who cannot install dependencies themselves, or don't use system that has sane support for using anything other than binaries.
> 
> Beside having dependencies installed, you only have to run qmake before make && make install.

I fully agree with you on that. This is the way nearly all software in the unix world is installed and so should qTox do it.

> There is INSTALL.md. If you have problems with understanding what is written there, please say which parts aren't clear, so that it could be improved.

I have to admit, INSTALL.md is much cleaner now than it was. Nevertheless I find it very confusing.
I would restructure it to the following points:
- short table of contents (current version OK)
- dependencies an where to get them (currently missing where to get them)
- General Linux install steps
  - clone repository
  - qmake
  - make && make install
- Instructions for specific Distributions
- Mac Instructions
- Win Instructions

I also find the INSTALL.md formating very confusing, just plain text is more readable.

In my opinion there shouldn't be any "Simple Make" scrips at all, those tend to fail just for someone who hasn't even the slightlies idea how to debug them or report an error.

Another point with the current build system is the integration with jenkins. At the moment this is somehow integrated with qmake. This is the right job for a script, it only has to work on a specific system and those who use it can quickly check how it works. Also separating this would make the qTox.pro file (or any other buildsystems files) much easier to read/use.

**Comment by VelorumS** [comment]
Anyone started porting to CMake?

**Comment by SkyzohKey** [comment]
We personally uses MesonBuild for [Ricin](https://github.com/RicinApp/Ricin). The fact is that meson is just a lot more fast than CMake and the scripting language is a simple python-like, so really simple to use. I would recommend u to try it and see if you like it ^^

**Comment by VelorumS** [comment]
@SkyzohKey, noisy syntax, less features, less compatibility.

I basically came here because for the platform on which I'm planing to port qTox uses qmake or CMake. And qmake was a bit dodgy when cross-compiling.

**Comment by SkyzohKey** [comment]
[**@ChipmunkV**](https://github.com/ChipmunkV) commented on [26 Nov 2015, 13:10 GMT+1](https://github.com/tux3/qTox/issues/1153#issuecomment-159897830):

> [@SkyzohKey](https://github.com/SkyzohKey), noisy syntax, less features, less compatibility.
> 
> I basically came here because for the platform on which I'm planing to port qTox basically uses qmake or CMake. And qmake was a bit dodgy when cross-compiling.

meson have approximately the same features as cmake, it's just more fast. And the python syntax is really more clear that the cmake one. For compatibility i dunno.

**Comment by CosmicToast** [comment]
Please avoid straying off topic.

After a quick look around meson, it has multiple issues:
- assuming the lowest common denominator for dependencies is outright silly
- the syntax is "python-like", but differs from it, with no visible reason for this design
- does not support generic cross compiling
- only uses ninja : more of a headache
- does not support conditional dependencies

Moreover, I see no justification for the claims of being "faster", but I could not find any benchmarks.
Scripting forms of build configuration are typically much slower than feature-compatible declarative ones. This hints at it being much less feature complete (also see above). "it's just more fast" is a gross oversimplification of what you're trying to sell.

Either way, please see the opening post (specifically the Pros section, which Meson does not provide), as well as the title. If you still think Meson is a better choice, I would personally prefer it being discussed elsewhere rather than here (most people watch this for details on the progress of porting to CMake, I would assume, me included).

**Comment by sudden6** [comment]
I think this discussion died, because the qmake project file was cleaned up and thus the main reason for this issue vanished.

**Comment by firegurafiku** [comment]
After looking more deeply to the way how it's supposed to build Android applications in CMake, I decided it would be just plain overcomplication and didn't insist on CMake anymore. QMake really seems to be fine for now (or maybe OBS in future?)

**Comment by tux3** [comment]
I think we're going to stay with QMake for the time being. I have nothing against CMake, but changing the build system is complex and would break a lot of things. We have other priorities at the moment (like fixing bugs!).

Closing for now, but this might be worth reopening later.
