### ISSUE TITLE
Autostart does not work: Unknown option 'P'

### ISSUE THREAD

**Issue by Talkless** [qTox/qTox#1158]
After enabling Autostart, KDE (Kubuntu 14.01) Autostart settings does have qTox line, but qTox does not actually start.

If I try to execute generated autostrat command manually:

```
$ "/usr/bin/qtox" -P "Vincas"
Unknown option 'P'.
```

qtox --help states that it should be lowercase `-p`.

**Comment by dubslow** [comment]
@novist Why does it even set the `-p` flag? Wouldn't it be more intuitive to just use standard behavior, i.e. open the last used profile?

**Comment by zetok** [comment]
@dubslow no, it's a per-profile setting..

**Comment by ghost** [comment]
Someone for some reason decided to change parameter to lowercase. ~~Anyway ill fix it~~.
