### ISSUE TITLE
interface freezes completely during loading large history

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1160]
https://github.com/krepa098/qTox/issues/9

**Comment by dubslow** [comment]
Ideally instead of loading 7 days history, we can load a set "amount" of history, and load more on demand as the user scrolls up (which is how Skype/Facebook do it).

Alternatively, there's probably a loop in which we can throw in some qApp->processEvents() calls.

**Comment by zetok** [comment]
Should be fixed by #2013, or at least sufficiently mitigated.

**Comment by tux3** [comment]
Should be fixed by the new database.

**Comment by zetok** [comment]
Just for the record;
with a 230MB big DB it took 4 min for qTox to start, and when I clicked on contact to load messages, it hanged after loading them (i.e. by "loading" messages I mean the point where RAM usage jumped to 10GB).
![20160120 qtox ram usage with 230mb big db](https://cloud.githubusercontent.com/assets/3148759/12473701/875ef048-c00c-11e5-8666-de452e7cef65.png)

Note that this is an extreme case, where DB that big was created by receiving spam from my spambot for quite a long time - under normal conditions (e.g. using qTox for years) my DB is still only 3 MB big, and only very small part of it is being loaded.

Even with really big DB (16 MB) qTox loading was only slightly slower (a few seconds), and qTox felt a bit sluggish with all those messages loaded - even this condition would be IMHO hard to meet.

If someone will manage to hit a real performance problem, issue should be reopened. Or, is someone is interested in improving things even further, feel free to do so :)

Edit: tested on 24bccb7bdd9572ba71055683df68f07121f4a177
