### ISSUE TITLE
Emoticon breakage

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#1161]
After the updates, some emoticon shorthands have been broken, displaying as ![brokenemoticon](https://cloud.githubusercontent.com/assets/1885159/6203164/5180d3fc-b512-11e4-86f5-514487989882.png)

Known broken shorthands:
Cylgom pack:
<3

All packs:
:-/

**Comment by dubslow** [comment]
@krepa098

**Comment by subliun** [comment]
:-/ is broken in all packs

**Comment by TheLastProject** [comment]
9bbd7a5 did NOT fix this for me. <3 is still broken.

**Comment by TheLastProject** [comment]
I can confirm c631fff to fix the issue for me after manually applying it. Please add this to the main qTox build.
