### ISSUE TITLE
broken emoticons

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1162]
no idea why some of them aren't displayed
![emo](https://cloud.githubusercontent.com/assets/3148759/6203332/0313e55e-b514-11e4-8275-f69257bdb12c.png)

EDIT: looks like it's related to #1161

**Comment by redsteakraw** [comment]
It seems the way they are parsed they need a space in between unless there is a seperate specific string with both codepoints together like the flag emoji.  Not sure how to fix this one.

**Comment by suhr** [comment]
Can be closed now?

**Comment by agilob** [comment]
Yes, I can't reproduce.
