### ISSUE TITLE
Context menu doesn't disappear after using copy, paste, select all etc. (New chatform)

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#1163]
After clicking copy it copies the selected text but the context menu reappears.
@krepa098

**Comment by krepa098** [comment]
Can't reproduce. Anyone else having this problem? Can you please tell me what OS you're using?

**Comment by towlie** [comment]
@krepa098 Windows 7

**Comment by towlie** [comment]
It's a windows only bug. It doesn't happen on linux here.

**Comment by towlie** [comment]
Fixed with https://github.com/tux3/qTox/commit/a930b398d4648fbcf5b04c29816d184bc44bc862
