### ISSUE TITLE
Toggle speakers volume button doesn't work

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1164]
Using the newest nightlies (Feb 15) between Win7 in a VM and Debian Jessie.
If I disable speakers (using the button) on both of them, I can still hear the sound from my microphone twice.
pavucontrol confirms as well that qTox makes sounds when the speakers are supposed to be disabled.

**Comment by Nokta-strigo** [comment]
Approve this problem. Doesn't work on Ubuntu with just compiled qTox (Git commit: bcc3ad703887db2eab06df46cfa5a85871d4615d) and on OSX, latest Jenkins build. Toggle microphone works fine on both.

**Comment by zetok** [comment]
Can't reproduce on newest qTox, closing.
