### ISSUE TITLE
Add "Open folder" field near recieved file

### ISSUE THREAD

**Issue by Disinterpreter** [qTox/qTox#1165]
Add "Open folder" field when file/image has been recieved how it work in skype.
qTox:
![jushzwz](https://cloud.githubusercontent.com/assets/3816155/6203681/2e4977e0-b53f-11e4-9b75-8637f8119a53.png)
Skype:
![exx34uk](https://cloud.githubusercontent.com/assets/3816155/6203694/a05a2762-b53f-11e4-9183-cb0c46a64114.png)

**Comment by zetok** [comment]
Also `Open file`

**Comment by freezurbern** [comment]
On Windows 7, the checkmark makes the link cursor appear, but does nothing. The checkmark could be used to open the file in the default program for that file type.

**Comment by dubslow** [comment]
One non-obvious work around is the button between starting a group chat and settings; it's a list of transferred files which can be clicked to open.
