### ISSUE TITLE
Compact contact list does not make group chat compact

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#1169]
If there is a group chat in the contact list, switching to the compact contact list will not make the group chat be displayed compactly.

**Comment by zetok** [comment]
Have you read a tooltip?

**Comment by TheLastProject** [comment]
It does say "qTox restart needed" but seeing e90293b47a8a0a830a7418094cb72caeb9ea2f62 I believe that is probably outdated.

**Comment by dubslow** [comment]
Restarts are not supposed to be needed, that tooltip is also a bug

**Comment by zetok** [comment]
k, #1193
