### ISSUE TITLE
Cant use special keys in toxgui (OSX)

### ISSUE THREAD

**Issue by mouseym** [qTox/qTox#117]
This is probably an OSX specific problem, but, for example i can't insert the apple logo into the chat. (Option + Shift + K).

I'm not sure if this is because toxgui doesn't recognise the key combination or blocks the keys as you can copy and paste in the apple symbol from a different application.

This isn't a major problem in anyway and can be left as very low priority.

**Comment by tux3** [comment]
That's a limitation of Qt, you can't use "special" input shortcuts.
It's probably not easily fixable.

**Comment by mouseym** [comment]
that's what i thought, it's not a massive problem either way, amended the title to reflect this

**Comment by msteinbeck** [comment]
Maybe we must add them manually. I have no Mac OS X to test it, but maybe @mouseym could do that?

**Comment by tux3** [comment]
I'm not seeing any easy resolution, closing for now.
