### ISSUE TITLE
[Regression] Broken quoting ( greentext )

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1173]

**Comment by griffondor** [comment]
lol

**Comment by ProMcTagonist** [comment]
Zetok, myself, and many others have demonstrated again and again the problems with the current implementation's odd, arbitrary, and confusing criteria for what should and should not be quotestyled.
It's a mess. 

Any line that begins with > or ＞ should be green. Simple.

**Comment by suhr** [comment]
> Any line that begins with > or ＞ should be green. Simple.

Things like `>_<` must not be green. Super simple.

**Comment by ProMcTagonist** [comment]
Why?

**Comment by suhr** [comment]
Because it is not a quote. It is a text form of an emoticon.

**Comment by ProMcTagonist** [comment]
Understood and agreed. But until a suitable way is found to accomplish that **without** breaking hundreds of normal ways quotes are used daily for the sake of a couple emoticons that average users will never see...

It's a matter of priorities.

**Comment by suhr** [comment]
Actually, https://github.com/tux3/qTox/pull/1124 is a compromise. The string that doesn't have spaces, digits or letters is hardly a quote.

> couple emoticons that average users will never see

Wrong, this kind of emoticons is pretty popular.

**Comment by ProMcTagonist** [comment]
> The string that doesn't have spaces, digits or letters is hardly a quote.

That's pretty arbitrary of you.

> Wrong, this kind of emoticons is pretty popular.

The "Average User" who's been thrown around as an excuse has graphical emoticons enabled and will therefore never see any text emoticons affected by quote styling.

**Comment by suhr** [comment]
> That's pretty arbitrary of you.

Probably so, yet I'd prefer to find a compromise instead of saying NOTABUG.

> The "Average User" who's been thrown around as an excuse has graphical emoticons enabled and will therefore never see any text emoticons affected by quote styling.

Well, the main problem with the “Average User” is that he doesn't exist: there's different groups of users with the different preferences. And the group that uses `>_>`-like emoticons in text form is not that small to completely ignore it.

**Comment by zetok** [comment]
![broken quotes](https://cloud.githubusercontent.com/assets/3148759/6227390/ecce2e38-b696-11e4-87d6-25328c357e7b.png)

@suhr

> And the group that uses `>_>`-like emoticons in text form is not that small to completely ignore it.

No, but it's a lot smaller than group affected by qTox failing at having consistent behaviour.
Consistent behaviour is much better than trying to provide "perfect" solution, and creating bugs.

**Comment by suhr** [comment]
> Consistent behaviour is much better than trying to provide "perfect" solution, and creating bugs.

It is better for programmers, but not for humans. Anyway, I agree that current behavior should be changed.

**Comment by ProMcTagonist** [comment]
Consistent behavior is better for everyone.

**Comment by TheLastProject** [comment]
What if we explicitly exclude `>*>` and `>*<` with \* being up to 3 characters (as I often see these used with _, ., 3, o, and much more)?

I think that would probably not highlight that smiley and all its common variations, yet cause no more than absolute minimum false positives. It even allows for some of the rarer variations like `>...<`.

I think that more than 3 characters between >< or >> would be amazingly rare.

**Comment by ProMcTagonist** [comment]
Sounds worth trying.

**Comment by tsdko** [comment]
`[20:29] みちる: #1173 is insane`
Stop trying to make up rules, you won't ever know about every exception. Highlighting anything between `>` and `␤` is enough.

**Comment by hexafluoride** [comment]
```
[20:50:42] <hexafluoride> just offer the option to make it meme arrow epin green colored text
[20:50:43] <hexafluoride> and make it off by default
[20:50:44] <hexafluoride> /discussion
```

I raise a very valid point here.

**Comment by ProMcTagonist** [comment]
Why hasn't anyone tried what @TheLastProject suggested? It solves the face issue, everyone is happy, no? I'll take that over off by default. It's supposed to be a delightful surprise, not something you have to dig in the options to enable.

**Comment by dubslow** [comment]
Submit a PR...?

**Comment by zetok** [comment]
@dubslow but PR was closed?

**Comment by dubslow** [comment]
I mean a new one that does what TheLastProject suggested.
