### ISSUE TITLE
Connecting to the DHT doesn't work well

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#1175]
We should retry with different nodes if we don't have a connection after ~5s.

And what's up with core connected/disconnecting us like crazy at startup ? Pretty sure that's a bug too, gotta fix that.

**Comment by dubslow** [comment]
@irungentoo

This is a TODO thing for core, which may be partially addressed by the new API.

**Comment by NoxNoctium** [comment]
#1123 might refer to the same problem.

**Comment by zetok** [comment]
Some people have said that qTox didn't want to work, so µTox was launched instead, and after that on the next start qTox worked.

Especially the first time qTox is started.

**Comment by tux3** [comment]
I can't repro anymore.
