### ISSUE TITLE
add a method to easily find someone

### ISSUE THREAD

**Issue by griffondor** [qTox/qTox#1179]
I think user id with a hash is not very user-friendly
So a search method with nickname should be good.
You may have choice to add nickname or not to your hash id

**Comment by suhr** [comment]
See https://github.com/irungentoo/toxcore/issues/1222

**Comment by agilob** [comment]
Can it be closed?

**Comment by tux3** [comment]
We still have toxme.se support and soon toxme.io, so I think we're covered.
