### ISSUE TITLE
File bubbles are oversized

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#1180]
Is this a resolution and scale issue, unique to my monitor?

They're too big in comparison to everything else. It looks incorrect. 

![too big file bubbles](https://cloud.githubusercontent.com/assets/4358079/6205196/43b96686-b51b-11e4-8a8f-e256a9846d31.png)
This was edited to show the bubbles closer to the buttons and other controls. Nothing was resized or scaled.

**Comment by suhr** [comment]
Same bug for me.

**Comment by tux3** [comment]
I made them 14px smaller, there's still just enough space for the contents.

![snap11](https://cloud.githubusercontent.com/assets/5155966/12471505/721d40b2-bffe-11e5-9c63-4269f25be068.jpg)

**Comment by tux3** [comment]
TODO: Make it less wide so the margin is the same

**Comment by tux3** [comment]
This is how it looks now: 
![snap13](https://cloud.githubusercontent.com/assets/5155966/12486229/f73fb58c-c061-11e5-8199-5967e7136c35.jpg)
