### ISSUE TITLE
Duplicate messages appearing

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#1181]
![not again](https://cloud.githubusercontent.com/assets/6127392/6205380/df1aee72-b531-11e4-8dcf-72221988a11f.png)

**Comment by TheLastProject** [comment]
I am noticing this too. I suppose my comment on #1089 is incorrect. I speculate that this happens until you open the chat conversation with that person, but I'm not completely sure.

**Comment by dubslow** [comment]
@krepa098 ?

**Comment by krepa098** [comment]
It's not a bug. It's a feature called "echos from the past" _scnr_

I can actually reproduce this now.
