### ISSUE TITLE
The name column should be resizable

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#1190]
See xchat. When the mouse is over the invisible line dividing the names and the messages, it should become a <-> and let me drag to resize.

**Comment by zetok** [comment]
one of ways of displaying peers from #2013 implements that.

Should be closable after PR gets merged.

**Comment by Diadlo** [comment]
Related issues: #635 #1219

**Comment by sudden6** [comment]
Duplicate of  #514
