### ISSUE TITLE
Missing Chat Logs (load history dynamically)

### ISSUE THREAD

**Issue by srkunze** [qTox/qTox#1198]
After a recent update, older chat logs are missing and I found no easy way to reload all of it.

Playing around, right-clicking revealed I could use 'Load chat history...' to load older chat logs but only if I click directly in the chat output (clicking the contact does not reveal that option) and choosing an older date.

1) I have to reset that for every restart of qTox. That is inconvenient.
2) I have to set it for every contact separately. That is inconvenient.

Possible solution: why not using rearward scrolling to dynamically load older chat logs? (like Facebook)

I could imagine that the current procedure is because of https://github.com/tux3/qTox/issues/1160 but I would appreciate a more dynamic and therefore need-oriented approach.

**Comment by dubslow** [comment]
@krepa098 +1 for dynamic loading

**Comment by zetok** [comment]
Done in #2013, after it will get merged, issue can be closed.

**Comment by srkunze** [comment]
Truly appreciated! Thanks.

**Comment by zetok** [comment]
Thanks to @ovalseven8, from https://github.com/tux3/qTox/issues/3003:

# 

Old and unmerged PR's, but perhaps helpful:
https://github.com/TheSpiritXIII/qTox/commit/5b9d9cc7fbaf104f73bea48f59e9c93ea4ec54d8
https://github.com/TheSpiritXIII/qTox/commit/e9f702edd7cc0643c25e4100426e71946f3426d2

**Comment by ProMcTagonist** [comment]
A lot of users think chat history doesn't work at all because of lacking this

**Comment by sudden6** [comment]
Dynamic loading is now implemented.
