### ISSUE TITLE
Default to Lowest Resolution in A/V Preview

### ISSUE THREAD

**Issue by lovelaced** [qTox/qTox#1201]
I've found that when my webcam is initialized, it defaults to the highest resolution and lags my entire computer, making tox (and everything else) completely unusable. If the default were the lowest resolution available this wouldn't be an issue (or the preview window was a tab of its own). The lag makes it pretty much impossible to select a lower resolution.

**Comment by ProMcTagonist** [comment]
Installing Tox and having 640x480 video calls unless you dive into settings sounds terrible for users.

I don't think that's the right solution.

**Comment by lovelaced** [comment]
Which is why my other suggestion was having the video preview in another tab.

**Comment by ghost** [comment]
Low res default for settings preview, high res default for transmission.

**Comment by tux3** [comment]
Or picking a middle ground ?

**Comment by tux3** [comment]
This should be fixed with FFmpeg, we now pick a lower-middle resolution, at the highest available FPS.
