### ISSUE TITLE
qTox always starts maximized (Windows)

### ISSUE THREAD

**Issue by Draako** [qTox/qTox#1207]
qTox always starts maximized, the position is not remembered and none of the options set in a shortcut (either to open in normal, minimized or maximized window) are respected.

**Comment by dubslow** [comment]
Probably related to the saving bug on Windows

**Comment by davidak** [comment]
also on OS X 10.9

tox starts in fullscreen mode. after ending that, it's over the whole screen, each start.

**Comment by agilob** [comment]
@Draako  looking at issues [you reported](https://github.com/tux3/qTox/issues/created_by/Draako), you have a problem with privileges to read/write files. No one else reported it and they all seem to be specific only for you.

**Comment by tux3** [comment]
This is actually a dupe of the settings saving bug, closing since the unrelated title and dup is not helpful in tracking this issue.
