### ISSUE TITLE
Emoticon size doesn't increase above certain value

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1210]
![big I need](https://cloud.githubusercontent.com/assets/3148759/6235656/f5f20bca-b6db-11e4-8855-5350c27769e2.png)

**Comment by ProMcTagonist** [comment]
I'm not affected.

700px
![big smilies](https://cloud.githubusercontent.com/assets/4358079/6235916/d5c9ba96-b69a-11e4-8b23-abfd8610f26e.png)
8px
![small smilies](https://cloud.githubusercontent.com/assets/4358079/6235927/ea45f70a-b69a-11e4-9335-f05d60203ba2.png)

Pack-specific issue?

**Comment by PKEv** [comment]
correct in #1957

**Comment by PKEv** [comment]
maybe close  @zetok ?

**Comment by zetok** [comment]
@PKEv um, why?

This issue is not closable, since there are limits on emoticon sizes that seem artificial - i.e. with one set of emoticons I can set it to 48px, with other one to tiny size of 25px..

That's kinda too limiting.

**Comment by PKEv** [comment]
Unlimited size leads to errors in the work, and the impossibility of selecting Emoticon

**Comment by PKEv** [comment]
maybe change label to "proposal"

**Comment by zetok** [comment]
@PKEv Yeah, unlimited size isn't good either, but.. could it be possible to dynamically determine max size of emoticons on runtime, based on DPI / resolution / something? Or would that be prone to errors?

**Comment by PKEv** [comment]
I make it so in my pr

**Comment by zetok** [comment]
I guess it can be closed
