### ISSUE TITLE
TwitterEmojiSimple should be limited to unicode and :emoticon: emoticons

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1211]
![don't touch my…](https://cloud.githubusercontent.com/assets/3148759/6235847/7139f94a-b6dd-11e4-93ba-a5870ea0b825.png)

**Comment by itsrachelfish** [comment]
I agree, I like being able to type :( and :D and ^_^ and :3 without it turning into a picture.

But sometimes emojis can be fun too~ :+1: :sparkles: :sparkling_heart: :crescent_moon: :ice_cream:

**Comment by redsteakraw** [comment]
TwitterEmojiSimple bugfix patch fixed this.  @dubslow

**Comment by dubslow** [comment]
@redsteakraw https://help.github.com/articles/closing-issues-via-commit-messages/
