### ISSUE TITLE
Chat form flickers and says "Busy" during any resizing

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#1213]
Very ugly and distracting.

**Comment by kushagrasurana** [comment]
the notification can be removed by removing all the busyNotification code present in
genericchatform.cpp 
chatmessage.cpp
chatlog.cpp

but should it be removed? considering the efforts made to display this notification.

**Comment by ProMcTagonist** [comment]
> considering the efforts made to display this notification.

Why?

> should it be removed?

Yes.

It should resize fluidly in front of my eyes.
