### ISSUE TITLE
qtox tray icon doesn't work

### ISSUE THREAD

**Issue by bitchecker** [qTox/qTox#1218]
the tray icon doesn't start with qtox application and if enabled the program will not close properly but it still run also if you close it from window. the only way to stop it is kill.

run on Fedora 21 with XFCE

**Comment by bitchecker** [comment]
[update]
- if you remove "close in tray" qtox will close!
- if you remove "use brilliant icon" the icon works alternately: once, many others do not!

**Comment by ghost** [comment]
Fix in works, still testing: https://github.com/novist/qTox/tree/tray-icon-fix

**Comment by tux3** [comment]
Does it work with the latest version ?

**Comment by bitchecker** [comment]
no, still works alternately, once, many others do not!!

**Comment by tux3** [comment]
@bitchecker did you compile it from source or did you download it ?

**Comment by bitchecker** [comment]
@tux3 i've installed from RPM official repository!

**Comment by zetok** [comment]
RPM repo is supposed to work now, could you test with newer version?

**Comment by ghost** [comment]
Fix not merged yet though. If panel is created after qTox is opened good chance it will crash.

**Comment by bitchecker** [comment]
@zetok RPM repo doesn't works!!

i'm trying to update and no updates where found!
i've also tried to remove and reinstall but always same version will installed!

**Comment by bitchecker** [comment]
[update]

with version `qtox-1.0-1512.x86_64` tray icon still work not properly!

**Comment by tux3** [comment]
@bitchecker I'm not sure I can reproduce again.

Can you say again what exactly the problems are now with the latest version?
Can you only reproduce with Fedora 21 and XFCE?
What should I do exactly to see the problems and reproduce them?
Thanks.

**Comment by bitchecker** [comment]
hi @tux3,
no i can't reproduce the problem because the tray icon works alternately, if i launch qtox 10 times, tray icon can start all 10 time, never or random number yes and the remaining no.

at the moment i'm running `qtox-1.0-1527.x86_64` always on Fedora 21 with XFCE

feel free to ask me help with some procedure that i can run for help you to debug and solve the problem! :+1:

**Comment by tux3** [comment]
@bitchecker So the problem is that the tray icon doesn't always appear?

If I start qTox ~20 times, is it roughly enough to have a chance to see the problem?

**Comment by bitchecker** [comment]
i hope! :D

**Comment by akhilman** [comment]
Also doesn't work on mate desktop XDG_CURRENT_DESKTOP="MATE". Setting XDG_CURRENT_DESKTOP="gnome" makes icon visible.

**Comment by tux3** [comment]
@akhilman I pushed a fix for MATE, can you confirm if this works with the latest version of qTox?

**Comment by akhilman** [comment]
@tux3 all works fine, thank you.
