### ISSUE TITLE
Chatlog: scale name column to longest name

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1219]
There is lots of free space before nickname. Nickname column should scale to longest name of all chat participants (with a limit?). I added image where red arrow illustrates where both nicknames should move. Reclaimed space then could be used to display more text.

![chatlog](https://cloud.githubusercontent.com/assets/7602544/6245168/59b9a086-b764-11e4-8a2e-d415f5969857.png)

P.S. chatog widget is awesome. kudos @krepa098!

**Comment by TheLastProject** [comment]
This change would cause the text to jump to the left or right each time you switch chat, which I feel would be disorienting and therefore not a desirable change.

**Comment by ghost** [comment]
I see your point. Though still some would prefer some space savings. How about an option then?

**Comment by zetok** [comment]
Rather than some option, user should be able to resize that column, so that its size would still be consistent, and user would have a way to "not waste space".

About implementation "detail"; I think that size of column should be a global value, i.e. if user changes it in one chat, size of column in all chats reflects that change.

**Comment by ghost** [comment]
Not sure how it can be consistent if name lengths of different people are different. Sure it would add some flexibility but "one size fits all" is not really valid approach.

**Comment by dubslow** [comment]
I think it is. My IRC client does it that way and it works fine.

**Comment by zetok** [comment]
There's an improvement in #2013 that allows user to resize column. Not yet what this issue is about, but it's an improvement.

> Not sure how it can be consistent if name lengths of different people are different. Sure it would add some flexibility but "one size fits all" is not really valid approach.

Actually, just disregard my earlier comment.
Option it is then. And per friend / groupchat setting.

**Comment by sudden6** [comment]
Duplicate of  #514
