### ISSUE TITLE
Display Online Friend Only

### ISSUE THREAD

**Issue by lehitoskin** [qTox/qTox#122]
It would be cool if the program had an option to display only online friends (versus All friends), much like Venom does.

**Comment by ghost** [comment]
Oh and don't forget to respect gender equality while you are at it.

**Comment by dcharles525** [comment]
@mannol1 :+1:

**Comment by tux3** [comment]
I'm planning to sort the friendlist by status (online first, then away, etc), is that okay ?
It should have roughly the same result since if a friend isn't online, (s)he/xe/it/they will be moved way down to the back of the friendlist.

**Comment by lehitoskin** [comment]
¿Porque no los dos?

**Comment by tux3** [comment]
Why not I guess, but wouldn't that be redundant ? Wouldn't want to add 992398731753 options for everything or it'd confuse people. What do you think ?

**Comment by msteinbeck** [comment]
I would like to have this feature :)

**Comment by lehitoskin** [comment]
@tux3 I meant more like, have everyone displayed (while sorted), or just the online people (still sorted). So the sorting happens in either choice, but we won't have to look at a whooooole lot of offline friends in one of the scenarios. The scrollbar is a greater indication of how many friends we have online as opposed to looking at the point where our online friends meet with the offline friends.

**Comment by tux3** [comment]
Ok
