### ISSUE TITLE
[Feature request] ability to change colour of group title / topic

### ISSUE THREAD

**Issue by griffondor** [qTox/qTox#1224]
users would like to put the colors in groups of securities

**Comment by griffondor** [comment]
I have a feature request : users want to put the topic in the group of color tox software when creating a lounge titles can not mettres color and fat also
it is possible to have a function like this?

**Comment by dubslow** [comment]
Essayez encore en français svp, je ne peux pas te comprendre

**Comment by griffondor** [comment]
seras t'il possible que lorsqu'on crée un salon dans qtox de mettre les titres en couleurs ? au lieu de noir et blanc

**Comment by ArchangeGabriel** [comment]
@griffondor want to be able to modify the “markup” of group titles, by changing color or using bold.

**Comment by agilob** [comment]
You can do that already, just use HTML:

```
<strong>bold</strong>
<u>underlined</u>
<strong><u>bold underline</u></strong>
```

At least works here, both in status and group description:
![strong](https://cloud.githubusercontent.com/assets/2544251/6400725/eb0a1bf8-bdf2-11e4-8ab3-652517683b9d.png)

---

![strongu](https://cloud.githubusercontent.com/assets/2544251/6400726/eb0c704c-bdf2-11e4-8087-69fb62357b41.png)

---

![red](https://cloud.githubusercontent.com/assets/2544251/6400793/6587b0ca-bdf3-11e4-9c79-d4ffac3e416d.png)

I think HTML should be striped from window title.

**Comment by griffondor** [comment]
the group titles are always in black is annoying, you can not put color?

**Comment by agilob** [comment]
![red1](https://cloud.githubusercontent.com/assets/2544251/6401473/a3189648-bdf8-11e4-809c-7c2185983fe0.png)

**Comment by griffondor** [comment]
it's run by cons if I do not want to underscore in the title, I should be how?

**Comment by griffondor** [comment]
it works for the titles to the color in the group ;)

**Comment by agilob** [comment]
`<font color="red">sdasda</font>`

You can change "red" to any other color name.

**Comment by griffondor** [comment]
Is it be possible to put in émiticones group titles ?

**Comment by sudden6** [comment]
Colors will not be supported by all clients, thus closing. Emoticons are supported now.
