### ISSUE TITLE
3 dependencies are not found (Debian)

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1225]
Debian: 7.8 (wheezy) 64-bit
qTox: 1.0-1253 (nightly)

> root@debian:/home/user# apt-get install qtox
> Reading package lists... Done
> Building dependency tree  
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
> qtox : Depends: libopencv-core2.4 but it is not installable
>        Depends: libopencv-highgui2.4 but it is not installable
>        Depends: libopencv-imgproc2.4 but it is not installable

It is possible find only the version 2.3 of these packages.

**Comment by dubslow** [comment]
We've had fairly major issues with this before -- simply put, Wheezy is too damn old (with an insufficient collection of backports). @stqism

**Comment by agilob** [comment]
Current Debian 8 has those packages in standard repo, can be closed.
https://packages.debian.org/jessie/libopencv-highgui2.4
