### ISSUE TITLE
asked to update, then updater doesn't run

### ISSUE THREAD

**Issue by freezurbern** [qTox/qTox#1227]
qTox asked to install an update on the next run, but when I ran it qTox-updater.exe gave this message box:

> qtox-updater.exe - Application Error
> The application was unable to start correctly (0xc000007b). Click OK to close the application. 
> OK   

Windows 7 64-bit.
I can't find qTox' version, the "version" file isn't human readable, qtox.exe has no product version defined.

**Comment by dubslow** [comment]
@tux3
