### ISSUE TITLE
Crash ASSERT: "e->globalPos == QGuiApplicationPrivate::lastCursorPosition"

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1229]
https://gist.github.com/zetok/51f0135cf66aaf98b8f2

**Comment by dubslow** [comment]
What do you mean "switch contact"?

**Comment by zetok** [comment]
I clicked on contact different than the one with whom I was talking

**Comment by suhr** [comment]
Is this still an issue?

**Comment by zetok** [comment]
I haven't experienced that in quite a while; most likely it was a Qt bug.
