### ISSUE TITLE
Broken friend invite message on receiving side

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#1230]
Sent:
![invitesent](https://cloud.githubusercontent.com/assets/1885159/6272711/1ec0bd1e-b86a-11e4-8c53-8b38a8633137.png)

Received:
![invitereceived](https://cloud.githubusercontent.com/assets/1885159/6272722/2f5d5916-b86a-11e4-8aa6-a6f5b87c59d7.png)

**Comment by zetok** [comment]
Couldn't reproduce, closing.
