### ISSUE TITLE
Desktop Sharing

### ISSUE THREAD

**Issue by urras** [qTox/qTox#1234]
uTox has had desktop sharing for quite some time now, and it appears that uTox is the only client to offer desktop sharing.

**Comment by tux3** [comment]
This has just been implemented.

**Comment by Balloon2mars** [comment]
Using 6/9/2015 windows x64 qTox, I don't see the option anywhere to set desktop as display device.

**Comment by tux3** [comment]
@Balloon2mars Where did you download qTox?

**Comment by agilob** [comment]
but it's not user-friendly

**Comment by ProMcTagonist** [comment]
@agilob user-friendliness meaning in-call switching and composing streams? https://wiki.tox.im/GSoC/2015/Ideas#Multimedia_Streaming

**Comment by Balloon2mars** [comment]
@tux3 was from normal tox.im downloads > jenkins

**Comment by tux3** [comment]
@Balloon2mars Okay this is fixed now.

**Comment by zetok** [comment]
@agilob yep, but sadly there is no real UI for it, so.. if you have an idea how to do it well for both sending and receiving side, making an issue with mock-up would be great
