### ISSUE TITLE
Implement the mockup's Friend Request system 

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#1237]
![friend request](https://cloud.githubusercontent.com/assets/4358079/6282034/cf994f26-b882-11e4-8f46-d661cd00f7fe.png)

Having this instead of popups will be cleaner and won't impact catching user attention once desktop notifications are added too (#483).

Cast @itsDuke for UX details

**Comment by ItsDuke** [comment]
@ProMcTagonist the current version I have in the mockup is the following (forgive the terrible m'lady joke):
![capture](https://cloud.githubusercontent.com/assets/7714365/6947314/569756ba-d874-11e4-85c4-47d717897943.PNG)

You'd click the green friend request notification (in your post) and it would open down into a list of your current pending friend requests that you could accept, deny, or simply leave for later.

**Comment by ProMcTagonist** [comment]
I like it. My only concern is that those accept/reject buttons may be very small click targets. 

And welcome back :)

**Comment by ItsDuke** [comment]
It's possible. Though If I'm correct in assuming the buttons are drawn by the program and not just static button shapes, then we can make them a bit larger to accommodate users who are prone to mis-cliicks :)

**Comment by suhr** [comment]
Bump. Window appearing out of nowhere is the worse UX ever.

**Comment by zetok** [comment]
Looks like #2092 implements something different form what this issue is about.

**Comment by zetok** [comment]
So, I think that there's a discussion needed, what is better - the way it's done in that PR, or the way mockup handles it?

**Comment by agilob** [comment]
TBH, I don't like any of them, I would rather keep current search bar and sorter above the contacts list. https://github.com/tux3/qTox/issues/2066 is similar, but more important IMO.

**Comment by noerw** [comment]
I like the way it would be done here better, regarding friend requests.

Suggestion:
Keep the search bar above the online/offline/..-filter, as this is a feature that should be accessible fast. Searching for contacts is done to save time, and clicking 2 times or more in a dropdown doesn't really do the job (input focus on the textfield via ctrl-f would be perfect^^).
Below that search bar, the filter (full width when no friend request is present) and the friend requests would be shown as in [comment 2](https://github.com/tux3/qTox/issues/1237#issuecomment-88569902).

**Comment by zetok** [comment]
~done in redo of #2092 – #2978, thus closing.

Not quite the mock-up, but that should do. For eventual changes to the current way in which things are being done, a new issue should be opened.
