### ISSUE TITLE
Emoticons no longer show their tooltip

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#1238]
New chatform problem?

**Comment by dubslow** [comment]
@krepa098

**Comment by redsteakraw** [comment]
It works on my build(built today running on Plasma 5/KDE on Linux), what platform was this bug on?  Can anyone duplicate this issue? @dubslow @krepa098

**Comment by krepa098** [comment]
Indeed they are missing.

**Comment by ProMcTagonist** [comment]
Debian Jessie. Openbox. Fresh git pull and recompile as of right now and it's still an issue.

**Comment by ProMcTagonist** [comment]
They show tooltips for me now on de423571eb16bab230f8de5e277c3b0b20315e00. I'll reopen if anyone says it's still broken for them.
