### ISSUE TITLE
URL detection needs to be better

### ISSUE THREAD

**Issue by mindcombatant** [qTox/qTox#1239]
![screenshot from 2015-02-20 01 41 42](https://cloud.githubusercontent.com/assets/9550058/6284322/a64762a4-b8a3-11e4-8f13-34e3014acf16.png)

"example.com" should show up as a URL, same with anything with a valid TLD.
"http://example" should not, as there is no TLD.
"http://[emoji or other invalid character]" should not either.
"http://[other language characters].[TLD]" should still work, i think those can be valid URLs.

**Comment by TheLastProject** [comment]
URL detection is amazingly hard to get right. In fact, I don't believe anyone gets it right. In fact, you'll notice that Github gets most wrong in this issue. However, I'll give a list of common "valid" and "invalid" URLs so a possible new, sufficiently correct, implementation could be tested more easily. The idea is that, when testing this, you just paste these URLs in a chat or so and see if the correct ones get highlighted or not

Valid:
example.com
www.example.com
http://example.com
https://example.com
ftp://example.com
ihatethesenewtlds.website/whydotheyexist
http://旅游.在线/
example@example.com
mailto:example@example.com
http://example
127.0.0.1
http://127.0.0.1
2001:0DB8:AC10:FE01:0000:0000:0000:0000
2001:0DB8:AC10:FE01::

Invalid:
mailto:example.com
127.0.0.1.16
256.0.0.1

Note: I personally consider an implementation that doesn't care about IP addresses sufficiently correct for normal use.

**Comment by DanTheBritish** [comment]
http://example is a valid URL, however only in an intranet environment.

**Comment by TheLastProject** [comment]
@LapFox Thanks for the note, I have updated my test list

**Comment by zetok** [comment]
Current URL detection was improved in #2137; 
![URL detection](https://cloud.githubusercontent.com/assets/3148759/9564802/e1ca615a-4ea8-11e5-9bcf-730deb42026f.png)

Can issue be closed?
