### ISSUE TITLE
Tray icon is invisible, Arch Linux + Gnome Shell (with Topicons extension)

### ISSUE THREAD

**Issue by vladimiry** [qTox/qTox#1245]
I have latest version installed (244d6da  Feb 20, 2015). All tray icon features are working (if interact with certain place in taskbar) but the tray icon itself is invisible.

![tray icon is invisible](https://cloud.githubusercontent.com/assets/1560781/6314552/cd89252c-b9f3-11e4-828d-963301edb4ae.png)

**Comment by tux3** [comment]
Please update to the latest version, there are fresh new system tray icon improvements.

**Comment by vladimiry** [comment]
@tux3 I have checked on the latest version, qtox -v output:

```
qTox 
Git commit: 6cef2a93498abc238cea19b42a76956462045589
```

The problem still remains. When the application starts some image (apparently the tray icon image) only flashes for a split second and then gone to invisible mode.

I can provide more details if you specify what kind of information would be helpful.

**Comment by tux3** [comment]
@vladimiry if you could post the exact version of gnome-shell you're using and the content of ~/.config/tox/qtox.log that'd help a lot.

I'll try to install gnome-shell and see if I can reproduce.

**Comment by vladimiry** [comment]
@tux3 

GNOME Shell 3.14.3 (installed as corresponding Arch [package](https://www.archlinux.org/packages/extra/x86_64/gnome-shell/))

Log:

```
2015-02-23 01:42:59 file logger starting
01:42:59 built on:  00:34:53 Feb 23 2015 ( 1424640857 )
01:42:59 commit:  6cef2a93498abc238cea19b42a76956462045589 

01:42:59 Nexus: Starting up
01:42:59 Core: loading Tox from "/home/vy/.config/tox/vy.tox"
01:42:59 Audio:  "Trying to open output Built-in Audio Analog Stereo"
01:42:59 Audio: Opening audio output  "Built-in Audio Analog Stereo"
01:42:59 Audio:  "Trying to open input Built-in Audio Analog Stereo"
01:42:59 Audio: Opening audio input  "Built-in Audio Analog Stereo"
01:42:59 SystemTrayIcon: Using Qt backend
01:42:59 IPC: Our global ID is  11348908201140376308
01:42:59 Core: Starting up
01:42:59 Core starting with IPv6 enabled
01:42:59 IPC: Creating the global shared memory and taking ownership
01:42:59 Core::loadConfiguration: reading from  "/home/vy/.config/tox/vy.tox"
01:43:01 Core: Bootstrapping to the DHT ...
01:43:01 "Core: Bootstrapping from sonOfRa, addr 144.76.60.215, port 33445"
01:43:01 "Core: Bootstrapping from stal, addr 23.226.230.47, port 33445"
01:43:04 Core: Connected to DHT
01:43:04 Core: writing tox_save to  "/home/vy/.config/tox/vy.tox"
01:43:04 Settings: Saving in  "/home/vy/.config/tox/qtox.ini"
```

If you need perhaps I could prepare and provide Virtualbox image with clean Arch installed + Gnome Shell + qTox.

**Comment by tux3** [comment]
It seems that you're using the old Qt fallback backend instead of the new Status Notifier, this means that your qTox wasn't compiled right.

How did you install qTox ? Did you download it from a repositiory or did you compile it yourself ?

I think i should just set enable the statusnotifier backend by default on linux.

**Comment by vladimiry** [comment]
That was built from sources by this script https://aur.archlinux.org/packages/qt/qtox-git/PKGBUILD With one difference, I've changed pkgver=r2363.244d6da to actual latest version. It seems like qmake-qt5 was involved.

Should I provide output of build process?

**Comment by tux3** [comment]
I'll make a change to enable the new system tray icon by default, this might break the build, but at least if it compiles it'll work.

**Comment by tux3** [comment]
As of 43c8c45b827fb244e9906fd79421fe5dedeab082 if you can compile from source it should work.

**Comment by vladimiry** [comment]
Unfortunately failed to build:

```
==> Starting build()...
/usr/lib/qt/bin/uic ../src/mainwindow.ui -o ui_mainwindow.h
/usr/lib/qt/bin/uic ../src/widget/form/settings/generalsettings.ui -o ui_generalsettings.h
/usr/lib/qt/bin/uic ../src/widget/form/settings/avsettings.ui -o ui_avsettings.h
/usr/lib/qt/bin/uic ../src/widget/form/settings/identitysettings.ui -o ui_identitysettings.h
/usr/lib/qt/bin/uic ../src/widget/form/settings/privacysettings.ui -o ui_privacysettings.h
/usr/lib/qt/bin/uic ../src/widget/form/loadhistorydialog.ui -o ui_loadhistorydialog.h
/usr/lib/qt/bin/uic ../src/widget/form/setpassworddialog.ui -o ui_setpassworddialog.h
/usr/lib/qt/bin/uic ../src/chatlog/content/filetransferwidget.ui -o ui_filetransferwidget.h
/usr/lib/qt/bin/uic ../src/widget/form/settings/advancedsettings.ui -o ui_advancedsettings.h
/usr/lib/qt/bin/uic ../src/android.ui -o ui_android.h
gcc -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT -fPIE -DGIT_VERSION="\"43c8c45b827fb244e9906fd79421fe5dedeab082\"" -DTIMESTAMP=1424646737 -DLOG_TO_FILE -DQTOX_PLATFORM_EXT -DQTOX_FILTER_AUDIO -DENABLE_SYSTRAY_STATUSNOTIFIER_BACKEND -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I/usr/lib/qt/mkspecs/linux-g++ -I../../qtox -I../libs/include -isystem /usr/include/gtk-2.0 -isystem /usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/lib/i386-linux-gnu/gtk-2.0/include -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/cairo -isystem /usr/include/pango-1.0 -isystem /usr/include/atk-1.0 -isystem /usr/include/qt -isystem /usr/include/qt/QtOpenGL -isystem /usr/include/qt/QtSvg -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtXml -isystem /usr/include/qt/QtSql -isystem /usr/include/qt/QtCore -I. -I. -I. -o closures.o ../src/platform/statusnotifier/closures.c
In file included from /usr/include/glib-2.0/glib/galloca.h:32:0,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from ../src/platform/statusnotifier/closures.c:23:
/usr/include/glib-2.0/glib/gtypes.h:32:24: fatal error: glibconfig.h: No such file or directory
 #include <glibconfig.h>
                        ^
compilation terminated.
Makefile:2467: recipe for target 'closures.o' failed
make: *** [closures.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build qtox-git.
```

Perhaps I should update some OS packages.

**Comment by tux3** [comment]
As expected, it broke the build.

You will need to install libgtk-2.0, libglib-2.0, libcairo, libpango, libatk-1.0 and libgdk-pixbuf-2.0 to compile the new system tray icon code. Both libraries and headers.

**Comment by vladimiry** [comment]
Still no visible tray icon. But in addition tray icon actions are not available now, when I interact with certain place on taskbar (guessing the place where an icon should be), and no tray image flashing, so it has now become worse.

New Log (tested on clean profile after removing /home/vy/.config/tox/ content)

```
2015-02-23 02:47:53 file logger starting
02:47:53 built on:  02:41:44 Feb 23 2015 ( 1424648469 )
02:47:53 commit:  43c8c45b827fb244e9906fd79421fe5dedeab082 

02:47:53 Nexus: Starting up
02:47:53 Core: loading Tox from "/home/vy/.config/tox/vy.tox"
02:47:53 Audio:  "Trying to open output Built-in Audio Analog Stereo"
02:47:53 Audio: Opening audio output  "Built-in Audio Analog Stereo"
02:47:53 Audio:  "Trying to open input Built-in Audio Analog Stereo"
02:47:53 Audio: Opening audio input  "Built-in Audio Analog Stereo"
02:47:53 SystemTrayIcon: Using Status Notifier backend
02:47:53 IPC: Our global ID is  11865246540059039816
02:47:53 Core: Starting up
02:47:53 IPC: Creating the global shared memory and taking ownership
02:47:53 Core starting with IPv6 enabled
02:47:53 Core::loadConfiguration: reading from  "/home/vy/.config/tox/vy.tox"
02:47:55 Core: Bootstrapping to the DHT ...
02:47:55 "Core: Bootstrapping from Nikolai Toryzin, addr 31.7.57.236, port 443"
02:47:55 "Core: Bootstrapping from sonOfRa, addr 144.76.60.215, port 33445"
02:47:56 Core: Connected to DHT
02:47:56 Core: writing tox_save to  "/home/vy/.config/tox/vy.tox"
02:47:56 Settings: Saving in  "/home/vy/.config/tox/qtox.ini"
```

I had already installed these Arch packages (gdk-pixbuf2, atk, pango, cairo, gtk2) but to compile I had to make 2 symlinks:
- from /usr/lib/glib-2.0/include/glibconfig.h  to  /usr/include/glib-2.0/glibconfig.h
- from /usr/lib/gtk-2.0/include/gdkconfig.h to  /usr/include/gtk-2.0/gdkconfig.h

**Comment by tux3** [comment]
Ok, I'll see if I can fix it.

**Comment by dubslow** [comment]
I for one can no longer see a tray icon, where the Qt version worked fine. I doubt I have the right stuff for the StatusNotifier one though.

**Comment by vladimiry** [comment]
@dubslow I just need got it working, so if "Qt version worked fine" how can I test that fine version?

**Comment by tux3** [comment]
@vladimiry I'm not seeing any system tray at all in stock gnome shell, do you have any extensions installed ?

Also, please try with the very latest version, I made it works on gnome classic so with a little bit of hope it'll work on gnome shell too.

**Comment by vladimiry** [comment]
> do you have any extensions installed ?

I forgot to mention it, my bad, this extension https://extensions.gnome.org/extension/495/topicons/

> try with the very latest version

Will do.

**Comment by vladimiry** [comment]
@tux3 yes now icon is visible, thanks.

But some tray icon actions are changed - **_now there is no way to maximize app from tray**_ since both left and right mouse tray icon clicking shows tray menu, but right mouse click should restore app from tray.

Log

```
2015-02-24 00:56:16 file logger starting
00:56:16 built on:  00:50:54 Feb 24 2015 ( 1424728150 )
00:56:16 commit:  51882425610adb534f46757ecb504f002a491324 

00:56:16 Nexus: Starting up
00:56:16 Core: loading Tox from ""
00:56:16 Audio:  "Trying to open output "
00:56:16 Audio: Opening audio output  ""
00:56:16 Audio:  "Trying to open input "
00:56:16 Audio: Opening audio input  ""
00:56:16 SystemTrayIcon: Using Unity backend
00:56:17 Core: Starting up
00:56:17 Core starting with IPv6 enabled
00:56:17 IPC: Our global ID is  12524737578445042238
00:56:17 IPC: Creating the global shared memory and taking ownership
00:56:17 Core: Error loading self avatar
00:56:18 Core: Bootstrapping to the DHT ...
00:56:18 "Core: Bootstrapping from lkwg82, addr 144.76.93.230, port 33445"
00:56:18 "Core: Bootstrapping from Impyy, addr 178.62.250.138, port 33445"
00:56:23 Core: Bootstrapping to the DHT ...
00:56:23 "Core: Bootstrapping from Thierry Thomas, addr 78.225.128.39, port 33445"
00:56:23 "Core: Bootstrapping from Manolis, addr 130.133.110.14, port 33445"
00:56:24 Core: Connected to DHT
00:56:24 Settings: Saving in  "/home/vy/.config/tox/qtox.ini"
00:56:24 Core: writing tox_save to  "/home/vy/.config/tox/qTox User.tox"
00:56:24 Settings: Loading from  "/home/vy/.config/tox/qtox.ini"
00:56:24 Using embeded bootstrap nodes list
00:56:24 Settings: Saving in  "/home/vy/.config/tox/qtox.ini"
00:56:24 QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
00:56:24 QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
```

**Comment by tux3** [comment]
Yes, unfortunately the Unity backend (libappindicator) doesn't allow to detect left clicks from right clicks.
Even getting it to open a context menu at all was a hack.

I'll see if I can detect better wether to use the Qt backend or Unity on GNOME.

**Comment by vladimiry** [comment]
Workaround is add "Minimize/Maximize" (to toggle app window visibility) item to tray menu.

**Comment by jurf** [comment]
Oh hey, GNOME does have a "system tray", just press `Win + M`, or bump the mouse against the bottom edge. Left and right click actions work there too. Though I don't see the icon either (well, sometimes I do see it, but rarely), only the space where the icon should be. It doesn't affect mouse actions, or the menu.

**Comment by vladimiry** [comment]
@DoctorJellyface have you used latest version 5188242? I have visible tray icon on that version (with Topicons extension).

> GNOME does have a "system tray", just press Win + M, or bump the mouse against the bottom edge

Yes, but Topicons extension makes these "Win + M" icons more usual and convenient to use.

**Comment by jurf** [comment]
I agree. But support for the official version should be prioritized over support for an extension.

> @DoctorJellyface have you used latest version 5188242? I have visible tray icon on that version (with Topicons extension).

No. Still waiting for the AUR script to be fixed before I can compile.

**Comment by vladimiry** [comment]
@tux3  Perhaps this could be helpful. I've tested on 5188242 behavior on Standard tray and Topicons

![compare standard icon and topicons extension](https://cloud.githubusercontent.com/assets/1560781/6357877/9aef1f86-bc78-11e4-89ae-cfe7fec87d2d.png)

As you can see on Standard tray only left part of the icon is visible (about 5px in width). The behavior the same as with Topicons (both left/right click shows tray menu).

**Comment by jurf** [comment]
Note: trying launching qTox and immediately switching to the (standard) system tray. Wait for the icon to appear, and then, lo and behold, the icon looks normal.

**Comment by vladimiry** [comment]
I have installed latest version 641fc8c Looks like left/right mouse clicks behavior is fixed now, thanks.

But the icon is cut off a little (in both Topicons/Standard modes), here is current icons using Topicons extension (first image) and Standard Gnome tray:
![topicons](https://cloud.githubusercontent.com/assets/1560781/6507072/a2c30b2a-c360-11e4-9eff-b4280b860a90.png)
![standard](https://cloud.githubusercontent.com/assets/1560781/6507075/a97a66e8-c360-11e4-9dfd-3675e98e8d4f.png)

**Comment by vladimiry** [comment]
I have noticed that icons are cut-off only if I turn off/on Topicons extension dynamically. If I load system with Topicons extension turned off icon looks good.

Looks like this issue should be closed. Thanks for your work.
