### ISSUE TITLE
Segfault in SystemTrayIcon::setVisible(bool) ()

### ISSUE THREAD

**Issue by lvml** [qTox/qTox#1247]
When I leave qTox, I consistently get a segefault at this backtrace:

```
#0  0x00000000004d18a0 in SystemTrayIcon::setVisible(bool) ()
#1  0x00000000004572ee in Widget::~Widget() ()
#2  0x0000000000457409 in Widget::~Widget() ()
#3  0x00000000004d19df in Nexus::~Nexus() ()
#4  0x00000000004d19f9 in Nexus::~Nexus() ()
#5  0x00000000004d3946 in Nexus::destroyInstance() ()
#6  0x0000000000429ded in main ()
```

The same kind of segfault happenes when I toggle the "Show System Tray" button in the preferences.

(This might be related to #908 but that one was closed long ago...)

**Comment by tux3** [comment]
On fvwm2

**Comment by zetok** [comment]
Is this still the case with newest binaries?

**Comment by zetok** [comment]
No answer, assuming that it was fixed, thus closing.
