### ISSUE TITLE
Build fail on Arch [bug]

### ISSUE THREAD

**Issue by randomname314** [qTox/qTox#1251]
Build fail on Arch. 

aur/filter_audio-git r22.11a23db-1 [installed](16)

g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -std=c++0x -Wall -W -D_REENTRANT -fPIE -DGIT_VERSION="\"559f7a60e8364d03370c7c4bb2e25a2b5a0580c3\"" -DTIMESTAMP=1424600999 -DLOG_TO_FILE -DQTOX_PLATFORM_EXT -DQTOX_FILTER_AUDIO -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I/usr/lib/qt/mkspecs/linux-g++ -I../../qtox -I../libs/include -isystem /usr/include/qt -isystem /usr/include/qt/QtOpenGL -isystem /usr/include/qt/QtSvg -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtXml -isystem /usr/include/qt/QtSql -isystem /usr/include/qt/QtCore -I. -I. -I. -o audiofilterer.o ../src/audiofilterer.cpp
../src/audiofilterer.cpp: В функции-члене «bool AudioFilterer::enableDisableFilters(int, int, int)»:
../src/audiofilterer.cpp:46:75: ошибка: нет декларации «enable_disable_filters» в этой области видимости
     return filter && 0 == enable_disable_filters(filter, echo, noise, gain);
                                                                           ^
../src/audiofilterer.cpp:47:1: предупреждение: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:4646: ошибка выполнения рецепта для цели «audiofilterer.o»
make: **\* [audiofilterer.o] Ошибка 1

**Comment by mensinda** [comment]
I had the same build error. Rebuilding filter-audio from the AUR fixed the problem for me. 

My current version: r28.5254f2d-1

**Comment by randomname314** [comment]
Thx. After updating filter_audio qtox builds normally.
