### ISSUE TITLE
Error compilation qtox-git in Archlinux

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1252]
Makefile:4386 : la recette pour la cible « audiofilterer.o » a échouée
make: **\* [audiofilterer.o] Erreur 1
==> ERREUR : Une erreur s’est produite dans build().
    Abandon...
==> ERREUR: Makepkg n'a pas pu construire qtox-git.

When i'm trying to update qtox-git in Archlinux...

**Comment by ArchangeGabriel** [comment]
You need to update filter_audio-git (current version is r28).

**Comment by ghost** [comment]
Thank you ! That's work ! 
Have a good day !
