### ISSUE TITLE
64 bit update windows 8.1 still broken 

### ISSUE THREAD

**Issue by cjpit** [qTox/qTox#1254]
Still getting the dreaded 7b - had done an uninstall and install from scratch, and I think I got one update in that worked...

https://gist.github.com/cjpit/2c82f358ac9749e0dee3

**Comment by cjpit** [comment]
ok mystery solved.  Turns out I have never been able to get the update to work, and it would always download a full delta.... because.... I had an old version of the 32bit still installed.  The update was always pulling down the 32 bit ver, and bleh it just had a mental breakdown. Uninstalled 32 bit, 64bit, reinstalled old 64 bit, asked for update, only downloaded 2 files for the update, and updated fine....

so all good!

**Comment by tux3** [comment]
Good to know, thanks!

**Comment by freezurbern** [comment]
> qtox-updater.exe - Application Error
> The application was unable to start correctly (0xc000007b). Click OK to close the application. 
> OK

**Comment by cjpit** [comment]
Looks like we are back to the same problem though:
07:50:30 AutoUpdater::getLocalFlist: Can't open local flist
07:50:30 AutoUpdater::parseflist: Empty data
07:50:30 AutoUpdater: Need to update  59  files

**Comment by cjpit** [comment]
although it updated ok, go figure
