### ISSUE TITLE
QTox - webcam freezes both in transit and preview on one end

### ISSUE THREAD

**Issue by d33tah** [qTox/qTox#1256]
Me and my friend recently upgraded to latest QTox available in our Linux distributions (me - Fedora 21 64bit, QTox built on 21:30:26 Feb 19 2015, friend's - Mint 17 Cinnamon 32-bit, built on 21:30:24 Feb 19 2015).

After the upgrade we experienced that the application crashes less often, but the Mint (friend's) webcam started freezing quite often (every minute or so). The freeze is also visible in the friend's webcam preview in Audio/Video settings. I am getting the impression that the video I am receiving distorts a tiny bit. The main workaround we found to make webcam send video again is by changing the resolution in the video settings, after which the webcam data starts flowing for some time. I don't think that just waiting for the webcam to start working again ever helped. Other functionality seems to work fine - the voice is sent and received properly and video from my own webcam works fine.

Below is the lsusb -v information about the camera:

Edited to remove long text by Dubslow:
https://gist.github.com/dubslow/16ffef257bc4558f0c55

**Comment by tux3** [comment]
This should be fixed with FFmpeg.
