### ISSUE TITLE
Unable to compile from sources?

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#1258]
```
androidgui.o: In function `AndroidGUI::AndroidGUI(QWidget*)':
androidgui.cpp:(.text+0xb9d): undefined reference to `qInitResources_android()'
```

Do I need any extra libs?

**Comment by tux3** [comment]
That was fixed just a couple minutes ago.

I had forgotten to exclude the Android files from the Desktop build, and it eventually broke.
