### ISSUE TITLE
Emoticons that contain spaces don't get recognized and imagified

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#1260]
```
<emoticon file="test.svg">
  <string>(´･ ω ･`)</string>
</emoticon>
```

![broken emoticon](https://cloud.githubusercontent.com/assets/4358079/6322054/58f2a912-bac1-11e4-9959-6bcb6428f660.png)

I found [this specification page](https://kopete.kde.org/emoticons/emoticonspec.html) for KDE-type emoticon packs, which doesn't mention anything to do with spaces. Is it possible to fix this?

**Comment by tux3** [comment]
I'm a bit worried that if we can't stop at word boundaries (spaces, ...) this is going to make smiley parsing _much_ slower. It could get noticeable when pasting large amounts of text. Especially with that twitter smiley pack.

**Comment by dubslow** [comment]
@krepa098 ?

**Comment by krepa098** [comment]
I think the amount of false positives would be quite high too. To me, it seems like a lot of trouble for little gain :/

**Comment by ProMcTagonist** [comment]
Alright, that makes sense. I'm gonna close it.
