### ISSUE TITLE
Unicode emoticons

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#127]
Add unicode emoticons input.

**Comment by dubslow** [comment]
This more-or-less exists, can be closed I think

**Comment by zetok** [comment]
Except #304

**Comment by dubslow** [comment]
Well... that wasn't technically a regression, since the emoticons were never bundled into the executable... though they probably should be...

Also, even so, you should be able to use the emoticons menu to add unicode emoticons, even if the images are missing as per 304.

**Comment by zetok** [comment]
I can't access menu without emoticons

**Comment by dubslow** [comment]
Oh. Well.

**Comment by dubslow** [comment]
Er... closable? Oldest open issue :)

**Comment by suhr** [comment]
Indeed fixed.
