### ISSUE TITLE
dependency libappindicator-dev isn't in INSTALL.md

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#1271]
On Debian. I don't see it in INSTALL.md. Didn't PR because a lot seems to be going on with notification and tray stuff right now. Just in case you didn't know.

**Comment by tux3** [comment]
This is actually intentional, but the INSTALL.md hasn't been updated yet.

**Comment by ProMcTagonist** [comment]
21fa791415c0c55452991f732f7138f3a8c31204

thanks

**Comment by tux3** [comment]
I actually went ahead and disabled it by default just now.
