### ISSUE TITLE
I am not able to see the qTox window on Mac

### ISSUE THREAD

**Issue by Piste** [qTox/qTox#1273]
I have used qTox and updated it for about 6-7 months. I update almost weekly. The latest update (last week?) broke my qTox. I now have an icon in the dock, the process is running but no window. How do I troubleshoot this? Which log file can I dig into?

**Comment by dubslow** [comment]
The was an update that broke the updating system, and the [blog post](https://blog.tox.im/2015/02/18/Update-on-the-state-of-Tox/) told OS X users to reinstall, rather than update. Please do so and update this issue :)

@stqism

**Comment by Piste** [comment]
I have never used the built-in upgrade. Didn't know there was one. I always re-download the latest dmg and drag and drop qTox on my Applications folder.

**Comment by Piste** [comment]
I have re-downloaded the .dmg and reinstalled and now it works. I am confused but this issue can be closed.
