### ISSUE TITLE
Typing notifications rare bug

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1280]
Requires qTox to continuously send typing notifications, from POV of receiving user:
![typing notifications](https://cloud.githubusercontent.com/assets/3148759/6374263/af6c5606-bd07-11e4-88dc-eb01bd0661df.png)

↑ ATM I was still using old qTox with broken typing notifications that were being sent all the time (no I didn't type anything)

thanks to @TheLastProject for introducing bug that led to discovery of this bug.
thanks to @agilob for supplying screenshot

**Comment by TheLastProject** [comment]
https://github.com/tux3/qTox/blob/9946a4642ed51593f90fcd70b1f596941d6b1cfc/src/chatlog/chatmessage.cpp#L114 refers to `[user]...`. So that's the place setting it, so we should follow the rabbit hole from there :)

**Comment by agilob** [comment]
related to the old verion of qtox. Can be closed.

**Comment by zetok** [comment]
@agilob 

> related to the old verion of qtox. Can be closed.

How exactly bug being old means that it got fixed, especially if code haven't been fixed?

Also, why are you claiming that it's about old version of qTox?

Reproducible on: a841224683116e75852d6d2ebc9a9f1dc70ec957
![still broken](https://cloud.githubusercontent.com/assets/3148759/7787541/aedb551a-0209-11e5-80be-aed29b0d2301.png)

@tux3 please reopen.

**Comment by NoxNoctium** [comment]
encountered this too recently: 
![image](https://cloud.githubusercontent.com/assets/2098025/8115970/7b045370-107f-11e5-88da-d7731e0cddb0.png)

**Comment by zetok** [comment]
Still reproducible on 1.4.0

**Comment by ProMcTagonist** [comment]
I've gotten it, vouching.

**Comment by sudden6** [comment]
Doesn't seem to happen on recent builds.
