### ISSUE TITLE
qTox closes to tray even if the option is not enabled

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#1281]
Happens when it can't go online.

**Comment by tux3** [comment]
I can't reproduce. Can you actually open it back after it closed to tray ?

**Comment by suhr** [comment]
This happens together with https://github.com/tux3/qTox/issues/953 (yes, it is actually not fixed). Rare bug that can be fixed by removing some files in tox directory. I really don't know how to reproduce this.

>  Can you actually open it back after it closed to tray ?

Yep.

**Comment by PKEv** [comment]
this problem is already fixed?

**Comment by agilob** [comment]
No, I disabled close to tray and closed qtox. worked as expected.

**Comment by PKEv** [comment]
I can't repeat in Windows 7

**Comment by agilob** [comment]
fixed in #1619
