### ISSUE TITLE
Kinect v1 won't be detected as Webcam

### ISSUE THREAD

**Issue by NoxNoctium** [qTox/qTox#1283]
I'm currently using a Microsoft Kinect on my Windows system and installed a Directshow filter to use it as a webcam. It does work with Skype and Google Hangouts, however qTox won't recognize it as video input device. The software in use is: http://codingbytodesign.net/2013/03/17/kinect-for-pc-and-skype-means-kinectcam/ 
The source only seems to be available for the v2 version, it should be helpful to get it working on v1 anyways:
http://codingbytodesign.net/wp-content/uploads/2015/02/KinectCamV2Src.zip

**Comment by zetok** [comment]
Some stuff in AV changed, can you re-test whether it still doesn't work for you?

**Comment by NoxNoctium** [comment]
Yes, it still won't show up. ffmpeg can't detect it either so I guess it's not directly a problem of qTox but the used AV-library. 
However, as I stated in the original report, it does work in Skype and Google Hangouts.

**Comment by sudden6** [comment]
Closing because many things changed for video and this bug is quite old. Please comment if the problem still exists.
