### ISSUE TITLE
New compiled Linux binary

### ISSUE THREAD

**Issue by dcharles525** [qTox/qTox#129]
title says it all

**Comment by Xylemon** [comment]
I can't run the binary on my Fedora 20 machine:

"./toxgui: error while loading shared libraries: libxcb-sync.so.1: cannot open shared object file: No such file or directory"

**Comment by dcharles525** [comment]
I get
error while loading shared libraries: libxcb-render-util.so.0: cannot open shared object file: No such file or directory

**Comment by tux3** [comment]
I didn't link libxcb statically. I'm stupid.

If you're on Ubuntu, Debian, or a derivative, run `apt-get install libxcb*` to fix this.

**Comment by Xylemon** [comment]
I already have the default and devel packages for "libxcb" and I still get the error I posted above.

**Comment by tux3** [comment]
@Xylemon do you have libxcb-sync1 installed as well ?
Installing libxcb\* will take care of this. Note the *

**Comment by tux3** [comment]
Note to self : forgot to link with libicui18n (libicu52)

**Comment by Xylemon** [comment]
Doing "sudo yum install libxcb*" gives me:

"Package libxcb-devel-1.9.1-3.fc20.x86_64 already installed and latest version
Package libxcb-doc-1.9.1-3.fc20.noarch already installed and latest version
Package libxcb-1.9.1-3.fc20.x86_64 already installed and latest version
Nothing to do"

So it seems that's all the packages Fedora has for libxcb. With all those installed I still can't launch the binary.

**Comment by tux3** [comment]
I'll provide a glorified .zip with all the dependencies next time.
Unless someone has a better solution.

**Comment by msteinbeck** [comment]
> I can't run the binary on my Fedora 20 machine

A few days ago someone posted this at tox-dev:
http://fpaste.org/115876/46841991/
Maybe it contains some libraries you missed?

**Comment by Xylemon** [comment]
No, I already had all of those dependencies installed. I can compile qTox, it just would've been nice to use a binary instead of recompiling it all the time.
