### ISSUE TITLE
Can't past screenshot after hitting print screen key

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1290]
After hitting print screen key, nothing happen when I try to paste in the message box. In Skype for example, doing it shows the screenshot in the message box and pressing enter sends the image to the contact.

**Comment by DerekTso** [comment]
hi, may i know if there's any process for this enhancement ? thanks.

**Comment by Diadlo** [comment]
@DerekTso There is no progress

**Comment by DerekTso** [comment]
@Diadlo got it, thanks
