### ISSUE TITLE
Putting HTML in names?

### ISSUE THREAD

**Issue by JFreegman** [qTox/qTox#1295]
Who thought this was a good idea? https://imgur.com/9rTdN0r

**Comment by agilob** [comment]
It's standard QLabel behavior to parse HTML. Every Qt application does it.
I think parsing HTML is a feature, not bug.

 You can also put JS, QML and CSS in there.

**Comment by srkunze** [comment]
Lol? IMHO, a name is a atomic string.

**Comment by JFreegman** [comment]
@agilob

> Every Qt application does it.

And if all Tox clients were written in Qt you would have a valid argument.

**Comment by TheLastProject** [comment]
This has been fixed in #1299.

**Comment by srkunze** [comment]
Can be closed, right?
