### ISSUE TITLE
Windows bug with name on save image (can't save received file)

### ISSUE THREAD

**Issue by Disinterpreter** [qTox/qTox#1304]
Small bug when you save image. You can't save image on geting name, bacause Windows write "Incorrect file name"

![jvx35vx](https://cloud.githubusercontent.com/assets/3816155/6421289/63dbf88a-bede-11e4-9fc7-ca18d978ea2f.png)

**Comment by agilob** [comment]
were you trying to save an image sent by someone from Linux/UNIX?

On Windows a filename cannot contain any of the following characters:

```
\ / : * ? " < > | 
```

**Comment by dubslow** [comment]
Sounds to me like you should just change the title to one appropriate for your OS (i.e., remove the colons).

**Comment by zetok** [comment]
> Sounds to me like you should just change the title to one appropriate for your OS (i.e., remove the colons).

It should be handled by qTox, after all, how could user know why file can't be saved..
(anyone willing to do it, please don't forget about case where filename is made only of "special" character)

**Comment by agilob** [comment]
I don't think this case should be handled by qTox, as other applications firefox, skype, gajim don't rename files, just throw errors, but if anyone wants to play with it. Maybe replacing illegal characters with `_` should be enough. If you think replacing chars is bad, then... use [boost::filesystem](http://theboostcpplibraries.com/boost.filesystem)

**Comment by PKEv** [comment]
it should do qtox because there is a point "autoaccept and save files:"

**Comment by zoff99** [comment]
please change illegal chars to "_" on atox for windows.

this bug is open for 2 years now :-(
will there be a fix?

**Comment by Disinterpreter** [comment]
@zoff99 lol xD
