### ISSUE TITLE
File transfers around 20mb seem to cause clients going online and offline

### ISSUE THREAD

**Issue by dcharles525** [qTox/qTox#1308]
I sent a 20mb png to one of my contacts and the contacts client would seem to go offline and online several times during the file transfer, after the transfer completed everything went back to normal.

**Comment by dubslow** [comment]
@irungentoo We've had similar reports over several months

**Comment by dcharles525** [comment]
@dubslow @irungentoo Update: We think it has something to do with going through tor, the contact was connected through tor, when the contact started getting the file all the contacts except for the ones connected through tor also would go offline, hope this helps.

**Comment by suhr** [comment]
See https://github.com/irungentoo/toxcore/issues/1220.

**Comment by aaannndddyyy** [comment]
since disconnects are very short, it would already help greatly if qtox were able to resume the transfer . . .

**Comment by ProMcTagonist** [comment]
@aaannndddyyy +1, it would be awesome if resuming actually worked.

Imagine asking a prospective user to resend files over and over, frustrating them, vs everything going through with a few offlines and resumes which seem more like acceptable alpha non-showstopping glitchiness.

**Comment by TheNain38** [comment]
Yes it would be really cool if someone could do a PR and implement file resuming. I was going to do it but I lack a bit of knowledge to do that correctly.

**Comment by agilob** [comment]
Closing because it's closed in upstream (and because it's upstream)
