### ISSUE TITLE
Can't call a contact when removing it while in call and readding it.

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#1312]
See https://github.com/notsecure/uTox/issues/248

**Comment by TheLastProject** [comment]
Just wanted to note that this is solved by a restart of qTox, so it doesn't permanently damage anything. Still, it's a bug that should be fixed.

**Comment by towlie** [comment]
https://github.com/irungentoo/toxcore/commit/6f5d1a3b8e15a3d6feae2eec6a3cf28bdd53bce0
