### ISSUE TITLE
Can't select audio devices, file save path, or resolution on OS X

### ISSUE THREAD

**Issue by LordHDL** [qTox/qTox#1313]
File path defaults to /Users/UserName.  Clicking it doesn't allow you to change it.

Audio devices only show the currently selected output and input devices, not the full list of devices.  Rescan audio devices doesn't affect this.

Similarly, the video resolution cannot be changed.

Tested on build 783.

**Comment by TheLastProject** [comment]
You can only change the file path when "Autoaccept files" is enabled. I agree that it'd be nice to be able to set a default directory anyway, even without autoaccepting files.

I don't have any notes on your other statements.

**Comment by zetok** [comment]
Will need to be re-tested when there will be builds for OSX available again.

**Comment by vit9696** [comment]
> File path defaults to /Users/UserName. Clicking it doesn't allow you to change it.

This is fixed at the moment.

**Comment by zetok** [comment]
cc @RowenStipe ?

Can it be closed?

**Comment by RowenStipe** [comment]
Yes
