### ISSUE TITLE
Context menu instantly disappears (OS X)

### ISSUE THREAD

**Issue by LordHDL** [qTox/qTox#1314]
Secondary clicks bring up the context menu, which then disappears immediately.  Workaround is to release the click very fast.

**Comment by zetok** [comment]
https://github.com/tux3/qTox/wiki/Useful-bug-reports

**Comment by LordHDL** [comment]
Not sure this is specific to OS version, but I am on 10.10.2.

Another test revealed that this doesn't happen with a mouse.  To reproduce, use a trackpad (I have a MacBook Pro 2011) and secondary click on a contact on the left side bar, or within a conversation in the white space.

The disappearing only happens if "Tap to click" is off in trackpad settings.  With "Tap to click" on, a 2-finger tap lets the menu function normally.

It also seems that if you click twice in a row really fast that will also prevent the menu from disappearing.

**Comment by dubslow** [comment]
This really sounds like an upstream problem to me

**Comment by stqism** [comment]
I have tap to click off and can't reproduce this on my Macbook using the trackpad at all. 
![screen shot 2015-03-02 at 3 17 23 am](https://cloud.githubusercontent.com/assets/2031258/6439740/c0ee8904-c08a-11e4-8e89-1ed744370f3d.png)

Oddly enough I did notice the window hide/open suddenly when clicking on it though. (cc: @dubslow)

**Comment by LordHDL** [comment]
Were you using Control + click?  I found that method works normally as well.  It's only a 2-finger click with a physical press of the trackpad that does it.

Here's a video: https://www.dropbox.com/s/rfk19xblm74xwx2/qTox%20Clicks.mp4.xz?dl=0

**Comment by stqism** [comment]
@LordHDL I've never used control + click ever and am doing exactly what you're doing and can't reproduce it on a fresh install of OS X.

**Comment by LordHDL** [comment]
I'm not able to test with a clean installation, but I did try a guest account and got the same behavior.

Is there any other information I could give that could help pinpoint possible causes?

**Comment by stqism** [comment]
It might actually be a setting on your end, but I can't tell.

**Comment by zetok** [comment]
Will need to be re-tested when there will be builds for OSX available again.

**Comment by zetok** [comment]
cc @RowenStipe ?

Can it be closed?

**Comment by RowenStipe** [comment]
@zetok does not seem to be present with my system, would call it safe to close.

**Comment by ProMcTagonist** [comment]
@LordHDL please comment if your issue is still occuring
