### ISSUE TITLE
connection problems

### ISSUE THREAD

**Issue by bitchecker** [qTox/qTox#1315]
in last days i'm having so much problems with qtox connection, in facts i run qtox and i can't go "online"!

i try to close and reload but nothing seems to change, the only way that seems to work is brutally kill application ( sometimes more than one time ).

run on fedora 21 on xfce

**Comment by NoxNoctium** [comment]
see #1175

**Comment by bitchecker** [comment]
@markus1540 it seems to be the same problem but in qtox i can't choose bootstrap node, so i click on RECONNECT button but nothing still change.

as i wrote, the only way is trying to brutally kill qtox and retry.

**Comment by bitchecker** [comment]
[update]

i've notice that if i start qTox from CLI, i can see all DHT connection and it works better with network but tray icon still not works ( https://github.com/tux3/qTox/issues/1218 )

**Comment by stqism** [comment]
Does this bug appear in any other clients? We need to figure if it's upstream or qt..

**Comment by bitchecker** [comment]
i don't know what happens with other clients...but i've retried for to test if via CLI it goes better and i can see from output that it tries to connect on bootstrap node...but no DHT connection!
it seems a freeze!

**Comment by vladimiry** [comment]
I also have problems with the connection. I have in my contacts list one friend who using Windows 7 and q-tox. I'm on Arch Linux and q-tox too. Often we marked as offline in the lists of each other, only helps to exit the program and restart.

**Comment by vladimiry** [comment]
I have noticed that this happens often after resuming from sleep mode.

**Comment by bitchecker** [comment]
@vladimiry at the moment on my system is working fine!
i never go in sleep mode, so i don't think that is "linked" to sleep-mode.

**Comment by vladimiry** [comment]
I'm just trying to help to figure this out.

The situation. Yesterday we talked with my friend using qtox. After that we have not turned off our computers, but the computers went into sleep mode. Today I see that we are marked as offline in each other contact lists. If I (or my friend) reran the qtox we go online. And this happens all the time.

That is, the qtox definitely has some problems with the reestablishing network connection, problems with keeping connection between users.

**Comment by zetok** [comment]
> @vladimiry at the moment on my system is working fine!
> i never go in sleep mode, so i don't think that is "linked" to sleep-mode.

Sounds like it's working for you, thus closing the issue.
As @markus1540 pointed out, it may be a duplicate of #1175.

# 

@vladimiry that resuming problem - #883.
