### ISSUE TITLE
OS X Yosemite qTox crash on accepting audiocalls

### ISSUE THREAD

**Issue by NoxNoctium** [qTox/qTox#1317]
Upon accepting an audiocall in qTox the application crashes.
Crashlog is here: https://gist.github.com/markus1540/ade79218407f41f977ec
Can't provide other logfiles or a backtrace as I don't have physical access to the machine ATM.

**Comment by stqism** [comment]
@markus1540 So we can have useful feedback I need you to do this:
- Download https://jenkins.libtoxcore.so/job/qTox%20OS%20X/lastSuccessfulBuild/artifact/qtox_bulk
- run `sudo mv ~/Downloads/qtox_bulk /Applications/qtox.app/Content/MacOS/qtox`
- Reproduce what made it crash and gist that, it'll be far more verbose and helpful :)

**Comment by bitchecker** [comment]
there may be a common error ( https://github.com/tux3/qTox/issues/1321 ) ?

**Comment by suhr** [comment]
Can be closed now.
