### ISSUE TITLE
[regressions] History not saved, user online/offline message not issued

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#1319]
Conversation history doesn't show any more after client restart.

These regressions are in Feb 28 version, compared to mid-January.

**Comment by dubslow** [comment]
@apprb

**Comment by TheLastProject** [comment]
Both of these features work fine for me. Are you sure said functionality is enabled in your client?

Also, make sure you're not chatting with a tox-prpl user, somehow qTox can't save their chat history, probably because their messages are NULL-terminated still.

**Comment by yurivict** [comment]
Indeed, if was off. I never knowingly turned it off, it might be that the issue is that it turns off by itself.

**Comment by zetok** [comment]
duplicate of #1062 ?

**Comment by yurivict** [comment]
Now another problem with history happened: part of history with one user is gone, only the last message stayed. "Privacy/Keep chat history" is checked. And there is no option "Keep for so many days" anywhere, so I assume it should be "forever"? Or there is some other default?

**Comment by TheLastProject** [comment]
Duplicate of #1198? (as in, not a bug, just unclear functionality)

**Comment by dubslow** [comment]
I just remembered, by default on 7 days of history is shown. You can right click to load more history. See if that helps.

**Comment by yurivict** [comment]
Yes, this works. 7 days.

There should be an option for the users to choose the length, including "forever"

**Comment by yurivict** [comment]
Yes, this works. 7 days.

There should be two options for the user: for how long to show history. And for how long to keep history.

**Comment by TheLastProject** [comment]
Or just dynamic loading, as described in #1198? I guess an option to choose how long to keep history for makes sense but, well, the settings menu needs to be a lot cleaner before adding more options.

**Comment by yurivict** [comment]
Yes, dynamic loading, combined with 'Keep history for' option is best.

**Comment by tux3** [comment]
Ok, so the bug seems to be resolved, but we need dynamic history loading now.

**Comment by zetok** [comment]
Since the bug was allegedly fixed, and dynamic loading is in #1198, closing this issue.
