### ISSUE TITLE
qTox videocall crash

### ISSUE THREAD

**Issue by bitchecker** [qTox/qTox#1321]
i've received a videocall and qTox crashed!

so there are several problems with video because i've reported also https://github.com/tux3/qTox/issues/1240

run on Fedora 21 with XFCE

**Comment by agilob** [comment]
is it related to the old API?

@bitchecker  does it work now?

**Comment by bitchecker** [comment]
at the moment it seems not crash...but this is the video call result

![istantanea - 11052015 - 22 41 13](https://cloud.githubusercontent.com/assets/11056930/7574780/275cb4c2-f830-11e4-9e03-850747a3613a.png)

**Comment by tux3** [comment]
Ok, so at least this issue seems to be fixed.

The video call being all gray is because the sliders in the settings have completely wrong ranges on some platforms. This'll be fixed with the new video code.

If it crashes again, please leave a comment.
