### ISSUE TITLE
Compile Instructions missing dependency

### ISSUE THREAD

**Issue by qw3ry** [qTox/qTox#1322]
It seems like the dependency package libappindicator-dev is missing in the [installation instructions](https://github.com/tux3/qTox/blob/master/INSTALL.md) INSTALL.md (followed the instructions for debian/ubuntu on an ubuntu 14.04 machine)

**Comment by zetok** [comment]
Indeed it does. Several other too.

**Comment by tux3** [comment]
libappindicator is not needed by default anymore.
