### ISSUE TITLE
qtox: error while loading shared libraries

### ISSUE THREAD

**Issue by bitchecker** [qTox/qTox#1324]
i've reported this bug much times ago on IRC channel and it was marked as SOLVED after few minutes but when i've reinstalled qTox i see the same error:

``` bash
qtox: error while loading shared libraries: libappindicator.so.1: cannot open shared object file: No such file or directory
```

can be solved definitively?

run on Fedora 21 with XFCE

**Comment by bitchecker** [comment]
[update]

i've checked on: https://repo.tox.im/x86_64/ that the last version of qtox available on official repository is 459 but system automatically install 382 as i see from

``` bash
# rpmquery qtox
qtox-1.0-1382.x86_64
```

so the question is simply, WHY?

**Comment by stqism** [comment]
You catch more flies with honey than vinegar.

Also, pretty sure it's a /dev/tty bug on the signing machine but only around 4% of Linux users use rpm based systems so it's fairly hard to notice issues.

**Comment by bitchecker** [comment]
I'm here just to bring those problems, as much as I can! :+1:

**Comment by stqism** [comment]
> WHY?

Sounds an awful lot like yelling at people working for free for the common good.

**Comment by bitchecker** [comment]
do not misunderstand, I think the question is more than legitimize! :+1:

**Comment by stqism** [comment]
Lemmie rewrite your message for you:

> [update]
> 
> i've checked on: https://repo.tox.im/x86_64/ that the last version of qtox available on official repository is >459 but system automatically install 382 as i see from
> 
> rpmquery qtox
> qtox-1.0-1382.x86_64
> so the question is simply, WHY?

Is less demandy yelling when written as just

> [update]
> 
> i've checked on: https://repo.tox.im/x86_64/ that the last version of qtox available on official repository is >459 but system automatically install 382 as i see from
> 
> rpmquery qtox
> qtox-1.0-1382.x86_64

See, the first can be easily taken as yelling and demanding answers as to repo bugs, whereas the 2nd looks like it provides some details you feel might help us resolve the issue. :)

**Comment by bitchecker** [comment]
@stqism i think that you're trying to focus attention on a stupid problem because i've wrote only "why" in capital letters because i would like to emphasize it; also because it seems so much strange that there are so much version availables but system will install only specific one.
having deb/rpm repositories no one controls, for example with a vm, that updates goes ok?

**Comment by urras** [comment]
I'll work on this when I get a chance

**Comment by bitchecker** [comment]
@urras now I'm cross-by posting anywhere, someone checks the repository rpm because it does not work well at all! the resolution of this problem, allowing the updates appropriate could allow to close several issues without doing any that!

**Comment by urras** [comment]
@bitchecker Just curious, are you able to install the bootstrap daemon and toxic from the repo as well?

**Comment by stqism** [comment]
@dubslow Issue fixed, closed please.

**Comment by bitchecker** [comment]
@urras with toxic i've same output of https://github.com/Tox/toxic/issues/306#issuecomment-76698792

bootstrap daemon doesn't works too!

this is output:

Resolution dependencies
-> Running transaction control
---> Package tox-bootstrapd.x86_64 0: 0.0.1-318 set to be installed
-> Processing dependence: libconfig9 for the package: tox-bootstrapd-0.0.1-318.x86_64
-> Dependency Resolution completed
Error: Package: tox-bootstrapd-0.0.1-318.x86_64 (tox)
             Require: libconfig9

**Comment by stqism** [comment]
@dubslow This issue was fixed when the rpm repo was fixed, close please.

**Comment by DinoDevel** [comment]
Please reopen.

```
> qtox
qtox: error while loading shared libraries: libappindicator.so.1: cannot open shared object file: No such file or directory
```

qtox-1.0-1512.i386
openSUSE 13.1 (i586)

**Comment by Rewarp** [comment]
openSUSE 13.2
Running Plasma 5.3
Installation of qtox via zypper shows:

```
Problem: nothing provides qt5-qtbase needed by qtox-1.0-1563.x86_64
 Solution 1: do not install qtox-1.0-1563.x86_64
 Solution 2: break qtox-1.0-1563.x86_64 by ignoring some of its dependencies
```

Installation of toxic via zypper shows:

```
Problem: nothing provides libconfig needed by toxic-0.6.0-494.x86_64
 Solution 1: do not install toxic-0.6.0-494.x86_64
 Solution 2: break toxic-0.6.0-494.x86_64 by ignoring some of its dependencies
```

Forcing an installation throws this error

```
qtox: error while loading shared libraries: libappindicator.so.1: cannot open shared object file: No such file or directory
```

**Comment by zetok** [comment]
Fixed, qTox builds are now static, closing.
