### ISSUE TITLE
Crash when receiving a video call

### ISSUE THREAD

**Issue by d33tah** [qTox/qTox#1329]
Built: 21:30:26 Feb 19 2015
Other details as in #1257. Core dump available here: http://a.pomf.se/vyednq.lzma

**Comment by d33tah** [comment]
Happens on "21:20:13 Feb 28 2015" build as well. Core dump here: http://a.pomf.se/krwgyb.lzma

**Comment by bitchecker** [comment]
https://github.com/tux3/qTox/issues/1321

**Comment by tux3** [comment]
This should be fixed with FFmpeg.
