### ISSUE TITLE
Slow switching to groupchat with long log

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#133]
How to reproduce:
- Open groupchat and wait until log gets long
- Switch somewhere else
- Return to groupchat

It takes about 3 seconds to switch on a large chat.

**Comment by tux3** [comment]
That's because every message adds 3 widgets to the layout, so the widget spam makes everything lag after some time.
This is fixed in the newChatForm branch.

**Comment by tux3** [comment]
Should be fixed by the new chat code.
