### ISSUE TITLE
cam settings(windows)

### ISSUE THREAD

**Issue by Gradom** [qTox/qTox#1333]
Hello guys,i would like to report a big problem of the section audio/video..when i open this tab i can set all the values of audio and video...but..there is a problem about the cam because in the preview the immage became all grey and i can't change the values..but the weird thing is that the grey immage remain in windows too!!! for example if i open acer crystal cam the image is all grey!!the only way to set the right values is to start skype and set values from ther...and if i open again qtox...i have the same problem!! Run on windows 7 64bit Home Premium

**Comment by bitchecker** [comment]
you are already one step ahead https://github.com/tux3/qTox/issues/1321

**Comment by zetok** [comment]
@bitchecker what do you mean?

Also, if you don't have any real reason, could you please stop spamming issues?

**Comment by bitchecker** [comment]
@zetok it's simple to understand!
on windows @TheBlackPanther can enter into audio/video setting but they broke system settings. Into linux, qtox crashes also if you only try to go to set up audio or video! :+1:

**Comment by zetok** [comment]
Those are separate issues.

**Comment by Gradom** [comment]
i don't think are separate..i think that under windows it has a proble but under linux it gives the same problem but with another aspect..because the programm or crash or stop running..and the big problem is that it has the possibility to use my hardware and change the values of the cam in all the system

**Comment by tux3** [comment]
This should be fixed with FFmpeg.
