### ISSUE TITLE
toolTip image preview is broken when filename has spaces

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1334]
Description:
Image preview in toolTip doesn't work. 

Info:
OS: Hardened Gentoo Linux
Qt: 5.4.1
qTox: 05:07:01 Mar  4 2015 ( [1425463520](https://jenkins.libtoxcore.so/job/qTox-linux-amd64-debug/268/) )  ; also on compiled 75a0e8ac2eb65a678bba6659c35b9881190d5472 with #1328 and #1332 applied.

Reproducible: Always

Steps to reproduce:
1. Send .png image that has **spaces in name**.

What happened:
toolTip image doesn't show image preview.

What should happen:
toolTip image should show image preview.

Additional info:
![y u no spaces](https://cloud.githubusercontent.com/assets/3148759/6485879/d535eb5a-c27e-11e4-8e9d-e6449fa1b72d.png)

Images to test with: https://a.pomf.se/mzwmkh.tar

@TheLastProject pls

**Comment by TheLastProject** [comment]
I ran into that myself, but couldn't figure out why. I clearly forgot to HTML escape the image name, which I didn't run into in my testing, oops! Will fix this as soon as I get the chance.
