### ISSUE TITLE
groupchats are lost when the application is closed.

### ISSUE THREAD

**Issue by bitchecker** [qTox/qTox#1347]
as i wrote in subject, if you've groupchats and you close application, when you re-open qTox you find only contacts but no groupchats!

run on Fedora 21 with XFCE

**Comment by Gradom** [comment]
I found the same problem on windows(i run qtox on windows 7)i closed the app and i lost the groupchat

**Comment by NoxNoctium** [comment]
this will be fixed with the new groupchats, https://github.com/alnf/toxcore/wiki/New-Group-Chats

**Comment by zetok** [comment]
Please close.

**Comment by bitchecker** [comment]
@zetok problem is not solved, i think, @markus1540 linked "Documentation on new distributed tox group chats (GC)." but the problem is still here!

**Comment by zetok** [comment]
@bitchecker not only this is a duplicate, but also qTox has nothing to do with how groupchats are managed.

**Comment by TheLastProject** [comment]
Duplicate of #896.

**Comment by bitchecker** [comment]
@zetok first of all, sorry for duplicate.
what does it means "qTox has nothing to do with how groupchats are managed." ?? i only reported that deleting groupchat is not a good feature for user because if they create a groupchat, i think that they need it, you know?

**Comment by suhr** [comment]
Close in favour of https://github.com/tux3/qTox/issues/896.
