### ISSUE TITLE
error about enabled encryption on fresh install

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1352]
Description:
On fresh qTox install from repo there's a warning about no password when encryption is enabled(!)
In settings encryption was not checked.

Info:
OS: Linux Mint 17.1 Mate x86_64 livecd
Hardware: KVM

Reproducible: Didn't try to reproduce

Steps to reproduce:
1. Run Mint livecd
2. Install qTox from Tox repo and try to run it from terminal
3. Error

What happened:
Warning about enabled encryption

What should happen:
Normal start without warning

Additional info:
![tfw fresh encryption](https://cloud.githubusercontent.com/assets/3148759/6541611/def67e14-c4d3-11e4-810c-6d3756526cfd.png)

**Comment by dubslow** [comment]
No idea how this could possibly happen. The default is no encryption, and there wasn't even any settings file, right?

**Comment by ffjia** [comment]
I can see the same warning for Mac version, when starting qtox for the first time.

**Comment by dubslow** [comment]
I'm beginning to think there's some bug in the settings code, affecting this as well as #1360, #1196, #1207, and... some other one I can't find back right now.

**Comment by dubslow** [comment]
@zetok Can you run qtox (on a fresh install, with the same reproducibility) with `break src/coreencryption.cpp:293`, and when it pauses there, `p encrypt`. If it says true, and this is the first time running qTox, then the popup will appear in a few more lines of code. Before continuing however, please verify whichever .ini file (if any!) has encryptTox=false or true.

**Comment by dubslow** [comment]
For bonus points, you could `break src/misc/settings.cpp:172` and step through while checking `p encryptTox`... actually scratch that.

I'll push a commit momentarily with an attempted fix. I may or may not have an idea (though it wouldn't explain some of the other issues I referenced).

**Comment by tux3** [comment]
Ok, the new profile code is much more sane, so this shouldn't even be possible anymore.
