### ISSUE TITLE
qTox doesn't have a systemtray on Plasma 5 once closed or minimized user can't recover qTox

### ISSUE THREAD

**Issue by redsteakraw** [qTox/qTox#1353]
Environment variables:
$XDG_CURRENT_DESKTOP
KDE

$KDE_SESSION_VERSION
5

Latest qTox build options

```
g++ -c -m64 -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIE -DGIT_VERSION="\"bd12381beaa3f928710bd0b2a5435eb95214b0d1\"" -DTIMESTAMP=1425747507 -DLOG_TO_FILE -DQTOX_PLATFORM_EXT -DQTOX_FILTER_AUDIO -DENABLE_SYSTRAY_STATUSNOTIFIER_BACKEND -DENABLE_SYSTRAY_GTK_BACKEND -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -Ilibs/include -isystem /usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib64/glib-2.0/include -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/lib64/gtk-2.0/include -I/usr/lib/i386-linux-gnu/gtk-2.0/include -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -isystem /usr/include/atk-1.0 -isystem /usr/include/cairo -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/pango-1.0 -isystem /usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib64/glib-2.0/include -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/lib64/gtk-2.0/include -I/usr/lib/i386-linux-gnu/gtk-2.0/include -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -isystem /usr/include/atk-1.0 -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/cairo -isystem /usr/include/pango-1.0 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I.
```

qTox log of enabling system tray

```
13:08:25 IPC: postEvent  "activate" to 0
13:08:26 IPC: Previous owner timed out, taking ownership 6573914165259976360 -> 7250642871317807360
13:08:27 Nexus: Starting up
13:08:27 Core: loading Tox from "/home/redsteakraw/.config/tox/157C974F016F.tox"
13:08:27 Audio:  "Trying to open output Built-in Audio Digital Stereo (HDMI)"
13:08:27 Audio: Opening audio output  "Built-in Audio Digital Stereo (HDMI)"
13:08:27 Audio:  "Trying to open input Monitor of Built-in Audio Analog Stereo"
13:08:27 Audio: Opening audio input  "Monitor of Built-in Audio Analog Stereo"
13:08:29 "Theme tree: (Breeze)"
13:08:30 Core: Starting up
13:08:30 Core starting with IPv6 enabled
13:08:30 Core::loadConfiguration: reading from  "/home/redsteakraw/.config/tox/157C974F016F.tox"
13:08:31 Core: Bootstrapping to the DHT ...
13:08:31 "Core: Bootstrapping from astonex, addr 178.62.125.224, port 33445"
13:08:31 "Core: Bootstrapping from mousey, addr 37.187.46.132, port 33445"
13:08:35 Core: Connected to DHT
13:08:35 Core: writing tox_save to  "/home/redsteakraw/.config/tox/157C974F016F.tox"
13:08:35 Settings: Saving in  "/home/redsteakraw/.config/tox/qtox.ini"
13:08:35 Settings: Saving personal in  "/home/redsteakraw/.config/tox/qtox.ini"
13:08:46 Widget: No system tray detected!
13:08:53 active chat
```

**Comment by gnuanu** [comment]
I had this issue in Kubuntu 15.04, not only with qTox but with some other applications as well. It seems like an issue with system tray and now it got resolved after upgrade to 15.04 Beta2.

**Comment by redsteakraw** [comment]
Tested and this no longer is an issue on plasma 5.3

**Comment by gusarg81** [comment]
Hi, this is not fixed (at least for me). Tested in Kubuntu 15.04 and 15.10 beta 2:

[16:15:58.651] src/widget/widget.cpp:1706 : Warning: No system tray detected!  

Using qTox e1509a9.

Cheers,

**Comment by zetok** [comment]
From #2347, thanks to @Jacobtey:

# 

Yes, I'm sure. I've used qtox and qtox-qt5.4.2 packages. No tray icon both black and white. I've tried them in kubuntu vivid vervet than upgraded it to wily beta2. No effect as well. Now I've got Kubuntu 15.10 beta2: plasma 5.4.2 qt 5.4.2 kde framework 5.14.0. Everything works correctly except qtox tray icon. What info else should I give?

---

@Jacobtey tested builds of PR #2132, and apparently it didn't work.

builds:

https://build.tox.chat/job/qTox-testing_build_linux_x86-64_release/13/artifact/qTox-testing_build_linux_x86-64_release.tar.xz
and
https://build.tox.chat/job/qTox-testing-qt5.4.2_build_linux_x86-64_release/15/artifact/qTox-testing-qt5.4.2_build_linux_x86-64_release.tar.xz

**Comment by gusarg81** [comment]
Hi again,

Just in case, I've tested latest (150-eaf44c4 according to deb package) and still no system tray icon:

[16:40:59.651] src/widget/widget.cpp:1706 : Warning: No system tray detected!

Cheers.

**Comment by zetok** [comment]
@gusarg81 yep, thanks.

@agilob are you sure that you didn't compile qTox with GTK tray backend when you were testing your PR?

**Comment by gusarg81** [comment]
@zetok no problem, let me know if you need more testing (I can compile it too if needed).

Cheers.

**Comment by zetok** [comment]
> Just in case, I've tested latest (150-eaf44c4 according to deb package) and still no system tray icon:

oh wait - the packages in repos aren't the one that I've linked to - i.e. `qTox-testing` builds aren't pushed to repos

**Comment by Jacobtey** [comment]
Hallelujah! I've got it with ./simple_make.sh
![systemsettings1](https://cloud.githubusercontent.com/assets/7997512/10320938/ad57e7be-6c7e-11e5-8e71-6a32133a994e.png)

**Comment by agilob** [comment]
So you were missing some libraries ;)

**Comment by zetok** [comment]
> So you were missing some library ;)

@agilob that's not it - `simle_make.sh` compiles qTox with support for GTK tray backends, while builds on jenkins don't.

**Comment by Jacobtey** [comment]
Well. Why haven't they be found during installation of qTox from repository?
Only made with ./simple_make.sh qTox has an icon in tray. Compiled by U one and qTox from repository have not.

**Comment by zetok** [comment]
> I will try it that way th next weeks, just provide them the direct download link and give a small introduction

qTox build on jenkins isn't compiled with support for GTK tray backends.

Generally, I've tried to make jenkins builds as static as possible, and linking to GTK wouldn't help with it.

@agilob's PR is supposed to render dependency on GTK ~deprecated, though it seems that it still depends on it in order to make tray work under KDE5.

**Comment by zetok** [comment]
So, according to @agilob, it's not reproducible on Arch (i.e. PR works without support for GTK) - that makes me wonder if kubuntu isn't at fault here…

**Comment by gusarg81** [comment]
Ok, tested building from git and works just fine on Kubuntu (15.10) :)

**Comment by redsteakraw** [comment]
@zetok  @agilob 

This is a hack no GTK dependencies should be needed for a Qt 5 app.  [KDE modularised their libs so they are like any other 3rd Party Qt lib.](http://www.frameworks.org/api) What is needed is the old GTK and other hacked libs to be thrown out and replaced with one capible Frameworks 5 lib [KNotifications](http://api.kde.org/frameworks-api/frameworks5-apidocs/knotifications/html/classKStatusNotifierItem.html).  This will also allow the trays to be present in Unity as well.  For a background on the Sytemtray situation in KDE / desktop linux [read this blog that outlines the situation](http://blog.martin-graesslin.com/blog/2014/03/system-tray-in-plasma-next).  However if you want to continue the old system tray spec [There is a recent project to bring back old system tray icons in KDE](http://blog.davidedmundson.co.uk/blog/xembed_back).  It won't merge until KDE Plasma 5.5 so it isn't a solution for the near term.  KNotifications is the only fix for all the use cases while being a native Qt lib.

**Comment by Jacobtey** [comment]
@redsteakraw why  KNotifiations doesn't work for qTox in Kubuntu?

**Comment by zetok** [comment]
@gusarg81 

> Ok, tested building from git and works just fine on Kubuntu (15.10) :)

Did you test it with or without GTK support?
(if you just ran `simple_make.sh` then it's with GTK support)

https://github.com/tux3/qTox/wiki/Tray-icon

**Comment by redsteakraw** [comment]
@zetok  @agilob Also native [Qt lib can be used for Qt 5.4+](http://blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons) if that is set to the minimum Qt lib version the problem and complexity for all desktops can be simplified.  Ideally just mandating Qt 5.4 and using the native lib will simplify the build system and this issue in general.

**Comment by gusarg81** [comment]
@zetok I just used the script simple_make.sh (which installs libgtk2.0-dev, but it means it compiles with GTK support?)

**Comment by Jacobtey** [comment]
> `simle_make.sh` compiles qTox with support for GTK tray backends, while builds on jenkins don't.

And what kind of tray backends should builds on jenkins support?

**Comment by agilob** [comment]
> This is a hack no GTK dependencies should be needed for a Qt 5 app

Bug in Gnome3 - we can't do it, G3 can't take svg as tray icon.

> This will also allow the trays to be present in Unity as well 

Bug in Qt 5.0-5.4, we can't do it, tray icon is located in random location on start and refuses to put itself in tray. We had at least 2 issues about it.

> KNotifications is the only fix for all the use cases while being a native Qt lib. 

This is not a solution... we would end up having: qtox-gtk, qtox-unity and third... qtox-kde.

What I did in that branch simplifies trayicon, G3 and KDE use the same Qt backend. It worked for me when I tested it on Arch with latest Plasma and G3.

The real solution would be to stuck with Qt4 where all G3, G2, Openbox, Awesome, Windows and Mac, KDE4 and KDE5 tray icon works. qbittorrent stuck with qt4 and they don't have problem with tray icons ;< Qt4 is less buggy then Qt5.

**Comment by Getron** [comment]
I think this can be fixed, but, i don't know how.

For example, the NoMachine (Free Remote Desktop Client) has the same problem with tray icon long time, until today, and, i have today installed the newest update for client, and the icon it works on my Fedora 22 KDE (Plasma 5) for NoMachine. Therefore, i think, it can be fixed from the App itself, somehow.

Just to inform the devs, maybe, they ask the devs from NoMachine, how it was fixed, the better way, and the same way to implement on the qTox.

Thanks

**Comment by agilob** [comment]
This is most probably problem with KDE5 or Qt. It works completely fine on my Arch.

Btw. it is not a good idea to use KDE on Fedora, Fedora don't like KDE and Qt and they purposely decrease quality of KDE packages and delay Qt updates. [Also biggest Qt/KDE contributor to Fedora repos](https://lists.fedoraproject.org/pipermail/kde/2015-October/016315.html) left the team a few days ago so it will be worse and worse.

I can provide you my build compiled with Qt 5.5.1.

**Comment by ghost** [comment]
#1820

**Comment by kehugter** [comment]
↑ was fixed. Is this one still an issue?

**Comment by zetok** [comment]
Is this issue still reproducible?

**Comment by Jacobtey** [comment]
Everything works fine

**Comment by zetok** [comment]
Since it's fixed, closing.

If someone can still reproduce, please comment for reopen.
