### ISSUE TITLE
Menu bar icon makes main window disappear

### ISSUE THREAD

**Issue by LordHDL** [qTox/qTox#1354]
To reproduce, check the "Show system tray icon" option, then click the icon in the menu bar: https://www.dropbox.com/s/nn2n3wvzeacuu40/qTox%20Menu%20Bar%20Icon.mp4.xz?dl=0

**Comment by tux3** [comment]
It's supposed to hide/show it when you left click and give a menu when you right click.

**Comment by LordHDL** [comment]
Forgot to mention I was left clicking in the video.  However I get the same result when right clicking as well, both with trackpad and mouse.  Here are my settings:

![screen shot 2015-03-08 at 11 38 12 am](https://cloud.githubusercontent.com/assets/5182602/6546372/af43c67c-c587-11e4-9654-aa71d1bf61f5.png)
