### ISSUE TITLE
Ability to sort users on last activity

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#1356]
Much like Skype's ability to sort both on contact and on recent:
![skypescreen](https://2.bp.blogspot.com/-tIm6mhQzTCk/TpoHED6ZSYI/AAAAAAAAB-Q/uSUyRz2Ouio/s1600/Skype-Screenshot2.jpg)

Recent would be decided by the timestamp of the last incoming message from that contact, falling back to the date they were added to your friend list if there hasn't been any incoming message yet. Obviously, this means that newly added friends, groupchats, or a new message received by a friend or in a groupchat would cause them to be bumped to the top of the list.

**Comment by ProMcTagonist** [comment]
![screenshot - 03082015 - 02 36 08 pm](https://cloud.githubusercontent.com/assets/4358079/6547811/82b23a26-c5a0-11e4-872a-621f45e2bba3.png)

**Comment by TheLastProject** [comment]
I'm pretty sure that was never meant to sort on recent, just show all contacts or only online contacts? I'm also not sure if I like that design-wise, but oh well.

**Comment by ProMcTagonist** [comment]
If the mockup is followed in this respect, it's where Recent should be.

What were you thinking of? A tabs system like Skype and Antox?

**Comment by TheLastProject** [comment]
I personally was, yeah, because tabs seemed more clear by default to me. But honestly, I'm fine either way, as long as I could easily sort users on status or most recent message.

**Comment by srkunze** [comment]
Looks like we need a holistic approach anyway: https://github.com/tux3/qTox/issues/1010

**Comment by TheSpiritXIII** [comment]
So, I'm going to be implementing this. I'm almost done with contact grouping ( #1010 ) and I'm wondering whether we should use the same UI. As such, it would look like this: 
![screenie](https://cloud.githubusercontent.com/assets/4027687/8058568/4d8116b6-0e88-11e5-9691-66f1163d5c9b.png)

I'm personally a bit worried that users may get confused a little because it might appear as if they lost their locally made groupings. Thoughts?

**Comment by TheLastProject** [comment]
I personally think that looks really well. The main issue lies in the Recent next to Search Contact. If we remove the friends/groups/etc. features from it and change the default to "Name", then it becomes more clear as a sorting method.

For keeping locally made groupings, I think it would be best for the group to be displayed when you mouseover a contact as well, so you can still quickly figure the grouping of a certain contact even when sorted on recent instead of name.

**Comment by zetok** [comment]
Oh, it's quite nice, provided that there will be more "history circles" that will be automatically created when there'll be need, i.e. how about something similar to what ff has:
![ff-like?](https://cloud.githubusercontent.com/assets/3148759/8058715/2aef63ac-0eb3-11e5-9db4-d9dc19352878.png)
?

**Comment by TheSpiritXIII** [comment]
@TheLastProject I'm envisioning using a menu that includes actions with check-boxes with separators to make filters more obvious., e.g:
[ ] Alphabetical
[x] Recent
'---------------
[x] All
[ ] Online
[ ] Offline
[ ] Freinds
[ ] Groups

In this case, we can make the combo-box display "Recent | All".

@zetok That's what I'm thinking too.

**Comment by zetok** [comment]
> I'm personally a bit worried that users may get confused a little because it might appear as if they lost their locally made groupings. Thoughts?

They shouldn't be, simplest way to handle it is to reserve groups only to views that are capable of displaying them - i.e. only to views that display in alphabetical order, otherwise it doesn't make much sense.

@TheLastProject sorry, but display where on mouse hoover? There are already tooltips for `name` / `status`, and soon there will be most likely tooltip for avatar, which will show fully sized avatar. So.. if not a tooltip, then what? And how exactly displayed?

@TheSpiritXIII I'm not sure whether I like your idea, mind providing more background on how it's going to look, function, where it will be placed, and how users will be supposed to know what it does?

Anyone "afraid" can just simply go back to `All`, view.

**Comment by TheSpiritXIII** [comment]
@zetok My idea was for choosing two multiple filters at a time, e.g group by recent activity AND only show those online.

I figured out how to implement it in Qt. There would be two groups you can check from, letting you have any combination of them:
![screenie](https://cloud.githubusercontent.com/assets/4027687/8061314/346ace1e-0e98-11e5-94d4-b5964fa6842d.png)

EDIT: @TheLastProject How about showing the contact grouping name when you right click? It can be the first action on the context menu and be disabled.

**Comment by ProMcTagonist** [comment]
@TheSpiritXIII I really like what you've done with the dropdown, that should replace the current dropdown for sure. We could change Alphabetical to A-Z to make the combined text less of a mouthful. 

I'm not sure about the Recent view mockup but I'm also not sure right now of what would be better.

**Comment by TheLastProject** [comment]
@TheSpiritXIII I would personally go for "Name" instead of "Alphabetical", or perhaps "Status". The new dropdown seems like a good way to combine functionality. I also don't think putting it in the right click menu makes sense, because right clicks are meant to change the state of something generally.

@zetok Why can't we put the grouping name on a third line below status?

**Comment by zetok** [comment]
@TheLastProject

> Why can't we put the grouping name on a third line below status?
1. It would be limited to non-compact mode of contact list.
2. Name and status even in non-compact mode barely fit in available space, putting there anything else would make it horribly clobbered.

# 

> I would personally go for "Name" instead of "Alphabetical",

Yep, `Name` sounds much better

**Comment by TheLastProject** [comment]
It wouldn't be limited to the non-compact lists because I was talking about on the hover on mouse over

On 16 June 2015 16:15:19 CEST, zetok notifications@github.com wrote:

> @TheLastProject
> 
> > Why can't we put the grouping name on a third line below status?
> 1. It would be limited to non-compact mode of contact list.
> 2. Name and status even in non-compact mode barely fit in available
>    space, putting there anything else would make it horribly clobbered.
> 
> # 
> 
> > I would personally go for "Name" instead of "Alphabetical",
> 
> Yep, `Name` sounds much better
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tux3/qTox/issues/1356#issuecomment-112446845

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by TheSpiritXIII** [comment]
I have already implemented all of this in my "circles" branch where I am just waiting for tux3 to give me some feedback. I put the grouping name in the context menu. You can see it by right clicking a circle, and then select the "Move to..." menu where you have "Remove from circle 'Circle Name'" and other options. It's a bit hidden, but at least you can now tell who is where and if you want to move a contact, you'll already be in the menu to choose where.

**Comment by zetok** [comment]
> It wouldn't be limited to the non-compact lists because I was talking about on the hover on mouse over

Except that all space available is, (or will be) already used for toolTips when hovering over..?
Using tooltips for that could cause confusion between what's a status or name set by user, and group to which they belong.

Confusion, since tooltips, as opposed to name/status, display status/name (or at least they should) in not altered way - e.g. anyone can freely use newline characters there.

**Comment by TheLastProject** [comment]
I noticed that the recent sorting doesn't actually sort by recency. It groups on date, and then sorts alphabetical. This makes it useless for seeing what conversations are active if you chat with a larger group of people throughout the day.

**Comment by ProMcTagonist** [comment]
I'd rather have a nonseparated list of users sorted by recency.

**Comment by PKEv** [comment]
@zetok maybe close?

**Comment by zetok** [comment]
@PKEv I'm not sure if it should be closed - i.e. @TheLastProject pointed out that currently contacts aren't being sorted by recent events, but rather they are being grouped based on when last interaction with them occurred, and then groups are being "sorted".

@TheLastProject do you think that this issue can be closed?

**Comment by sudden6** [comment]
Implemented in recent builds.
