### ISSUE TITLE
new tray icon

### ISSUE THREAD

**Issue by zwischen** [qTox/qTox#1360]
the new tray icon in qtox is waaaaaay too big and doesn't provide me with useful information.  can it either be eliminated, optional or be scaled down so it's similar in size to other tray icons?  it looks out of place in its present form and only tells me my qtox on-line status--something I set myself and presumably know without having to refer to an icon.  

![qtox icon](https://cloud.githubusercontent.com/assets/10013562/6566235/ba761606-c674-11e4-99dd-2f464aaf15df.jpg)

**Comment by ProMcTagonist** [comment]
This doesn't happen for me.

**Comment by zetok** [comment]
@zwischen https://github.com/tux3/qTox/wiki/Useful-bug-reports

**Comment by TheLastProject** [comment]
First off, the icon is already optional. However, the size issue is a bug, probably specific to your DE. What DE are you using? Also, please provide info as asked in @zetok's link.

**Comment by dubslow** [comment]
@tux3

**Comment by zwischen** [comment]
My OS is Linux (Trisquel 7.0).   The tray icon appeared spontaneously on Mar.3rd.  I have never enabled the 'show tray icon' option in qtox's settings.  Today I enabled the icon tray, then disabled it again:  this got rid of the icon only as long as qtox remained open.  When I closed qtox (still with 'show tray icon' disabled) the icon reappeared on restart.

**Comment by TheLastProject** [comment]
I have been told the default Trisquel DE is a modified GNOME3 fallback mode, explicitly requiring no graphic acceleration, in case that's relevant.

`<pehjota> Yeah, it's Metacity and GNOME Panel, instead of Clutter and GNOME Shell, with a Trisquel GTK+ theme.`

**Comment by dubslow** [comment]
Huh, that's strange. Can you check the contents of ~/.config/tox/qtox.ini when closed and report what the showTrayIcon (or whatever the name is) variable is?

Edit: And post the contents of ~/.config/tox/qtox.log from when you close it with systray disabled, and then it starts enabled. (I want to see if it saved on close as it's supposed to...)

**Comment by zwischen** [comment]
the edit wasn't here when I first read your post.  I checked the config file with qtox closed:  under GUI the only tray listings were:  LightTrayIcon= false, minimizeToTray= false.  under GENERAL:  showSystemTray=false, autostartInTray =false and closeToTray=false.     

I'll go back and hunt up the log

**Comment by zwischen** [comment]
23:19:19 Core: Disconnected to DHT 
23:19:19 Core: Connected to DHT 
23:19:19 Core: writing tox_save to  "/home/shannon/.config/tox/dmehg'l.tox" 
23:19:20 Settings: Saving in  "/home/shannon/.config/tox/qtox.ini" 
23:19:20 Settings: Saving personal in  "/home/shannon/.config/tox/qtox.ini" 
23:19:22 Core: writing tox_save to  "/home/shannon/.config/tox/dmehg'l.tox" 
23:19:22 Settings: Saving in  "/home/shannon/.config/tox/qtox.ini" 
23:19:22 Settings: Saving personal in  "/home/shannon/.config/tox/qtox.ini" 
hope this is what you need.....

**Comment by dubslow** [comment]
Okay, it looks like the setting is saving properly, as you verified in your first reply... and even when it's set to false in the .ini file, the icon still appears?

**Comment by zwischen** [comment]
I'm afraid so.....it appears on every re-start

**Comment by agilob** [comment]
bump?

**Comment by tux3** [comment]
So, is the bug about settings not saving? If so that's an important problem, but it should be in another issue so we can better keep track of it.

As said before, disabling the tray icon is possible, and I'm not sure if the size problem is an issue with your DE. 

@agilob can you repro this bug?

**Comment by agilob** [comment]
No, actually I never had any problems with tray icon...

**Comment by tux3** [comment]
I don't really have the time to go install trisquel atm, but the settings not saving issue has been reported on other platforms and I'll definitely be working on this one.

**Comment by ovalseven8** [comment]
On Lubuntu 14.04 there is the same issue:
https://i.imgur.com/Jf77ux3.png
(On the left the size is OK - but on the right it's too big)

**Comment by sudden6** [comment]
Is this still an issue? If not please close.

**Comment by sudden6** [comment]
Closed, since no update provided.
