### ISSUE TITLE
no window about

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#1361]
No window to see current version of program (in Windows) and is good to see what new in current version

**Comment by dubslow** [comment]
You can see the git version in the log file.

**Comment by agilob** [comment]
`About` section can go on the top of `Advanced` tab.

**Comment by PKEv** [comment]
Can you show it? I don't see them. (windows 7 x32)

**Comment by agilob** [comment]
It was just a suggestion.

**Comment by PKEv** [comment]
It seems to me that this should then take independent bookmark, because then there will want to link to the repository, licenses, etc.

**Comment by Jookia** [comment]
Technically this violates the GPL by not providing attribution and license notes.

From section 0:

> An interactive user interface displays "Appropriate Legal Notices"
> to the extent that it includes a convenient and prominently visible
> feature that (1) displays an appropriate copyright notice, and (2)
> tells the user that there is no warranty for the work (except to the
> extent that warranties are provided), that licensees may convey the
> work under this License, and how to view a copy of this License.  If
> the interface presents a list of user commands or options, such as a
> menu, a prominent item in the list meets this criterion.
