### ISSUE TITLE
REGRESSION: Cannot change name with single click

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#1364]
Now that clicking your name opens the profile setup, I can no longer edit it with a single click. qTox should, at very least, focus the name field in profile information so you can still keep typing and press enter to change your name, instead of having to click twice.

**Comment by TheLastProject** [comment]
Can we also at least make clicking status open the profile setup too and focusing on status? Because the current behaviour is so horribly inconsistent and annoying.

**Comment by zetok** [comment]
When was the last time that you've changed your nick?

Changing status on the other hand is not a rare thing to do.

**Comment by TheLastProject** [comment]
Completely irrelevant.

Previous behaviour:
- Click name -> Type -> Enter
- Click status -> Type -> Enter

Current behaviour:
- Click name -> Click name again -> Type -> Enter -> Click chat
- Click status -> Type -> Enter

Requested behaviour:
- Click name -> Type -> Enter -> Click chat
- Click status -> Type -> Enter -> Click chat

There is no reason, whatsoever, to not at least focus the name field upon clicking name so you can keep typing if you wanted to change your name. You need to click something else if you want to change that anyway.

**Comment by zetok** [comment]
> Completely irrelevant.

It's not irrelevant, since frequency with which particular features are used determines how quickly accessible they should be.

**Comment by TheLastProject** [comment]
This change makes name changes be one step less, at no loss whatsoever.

**Comment by zetok** [comment]
Idea:
Instead of making `Nick` field editable again, why not just put a focus in `Nick` field in `Profile` page?

I.e. click on name → opens `Profile` with focus on `Nick` field

This way you still get a way to quickly change your nick (click → type → enter), and there is no strange, both edit-able and opening-profile `Nick` field.

![20150311 qtox nick change field](https://cloud.githubusercontent.com/assets/3148759/6596127/28574c92-c7e9-11e4-9693-1bfd4255994a.png)
green - field editable in place of click (stays as is)
red - when clicked on gives focus to blue, rest stays non-editable
blue - gets focus when one clicks on red one

**Comment by TheLastProject** [comment]
> Idea:
> Instead of making Nick field editable again, why not just put a focus in Nick field in Profile page?

That was exactly what I asked... However, for consistency, I want both fields on the top left to act like you suggest nick should act.

**Comment by zetok** [comment]
Sorry, looks like I can't read. :D

> I want both fields on the top left to act like you suggest nick should act.

I don't like having to go to profile to just change status message, and I imagine that other people might feel in the same way about it.
IMHO consistency shouldn't hinder UX…

**Comment by TheLastProject** [comment]
IMHO a lack of consistency directly hinders UX. Two elements that look the same should act the same.

**Comment by DanTheBritish** [comment]
In that case, perhaps they should both take you to the profile page, selecting their respective fields.

That still however adds an extra click to get back to a chat if you're changing a status.

**Comment by TheLastProject** [comment]
@LapFox Maybe we could make pressing enter in the name or status field bring you back to the previous chat? Although I'm not sure if that'd be a nice user-experience, would need some testing.

EDIT: I mean in case you click on name, type something and immediately press Enter. Not if you press Enter after first clicking something else.

**Comment by dubslow** [comment]
I prefer not having the status go directly to the form, however I would implement that (with auto focus) if enough people provide opinions disagreeing with me and zetok.

Having the name focus your name sounds like a good idea to me regardless.
