### ISSUE TITLE
feature request: shared folders

### ISSUE THREAD

**Issue by aaannndddyyy** [qTox/qTox#1374]
A user defines a direcotry on his fs as a shared folder for a given contact (or several).
All data in that directory is synced with the corresponding friend's directory.

**Comment by TheLastProject** [comment]
That seems way out of qTox' scope. It's a Skype replacement, not a Dropbox replacement.

**Comment by aaannndddyyy** [comment]
I don't think so. You know msn Live messenger and Skype merged, and it was a very useful feature of msn messenger. I don't know if current skype has it, but even if not, it should not be overly hard to do that. file transfer is already possible.

**Comment by dubslow** [comment]
You can select multiple files and qtox will transfer all of them as well

**Comment by ProMcTagonist** [comment]
Solid messaging and VOIP first.

**Comment by aaannndddyyy** [comment]
@dubslow yes, but you have to do so manually. and even several times for the same file if it changes. and the receiving side has to accept each time. Here both sides would just define a saving location and a reasonable limit, that's all

**Comment by agilob** [comment]
This is idea for a separate application or a plugin to qTox (do we plan having plugins?)

**Comment by aaannndddyyy** [comment]
plugin sounds good. Doesn't increas core library but still not bound to only one client.

**Comment by srkunze** [comment]
I like that idea; that would make sharing photos much easier.

**Comment by ghost** [comment]
There's already Syncthing for this exact purpose, I believe:
https://github.com/syncthing/syncthing/tree/master

It still lacks NAT traversal, but hopefully it will get there soon. I think there was also a similiar project utilizing toxcore, but I don't remember it's name.

**Comment by ProMcTagonist** [comment]
https://github.com/Astonex/ToxBox

**Comment by srkunze** [comment]
Interesting projects; I would love to see an integration into qTox.

People don't want to install 5 different binaries just to get things done. That is why browsers are so successful: one binary and billions of applications with a single-click installation and execution (so-called hyperlink).

**Comment by agilob** [comment]
This idea is for completely different project. qTox is instant messenger, not file sharing application. I think this should be closed.

**Comment by tux3** [comment]
I agree that this is way out of scope at the moment.
