### ISSUE TITLE
Group chat invite window is broken

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#1376]
Somehow, it just draws an empty window. Pressing Enter to accept and Escape to decline does work, though.
![snapshot21](https://cloud.githubusercontent.com/assets/3148759/6638825/c73de64c-c981-11e4-8d9d-fc024e9678ab.png)

**Comment by dubslow** [comment]
I... doubt there's any client side code that would fix this. OS and Qt version?

**Comment by TheLastProject** [comment]
Trisquel 7, KDE 4.13.3 I believe. However, I just rebooted the device and couldn't reproduce it, so I'm going to assume it was just a very rare glitch in Qt itself, as I never had this before and have been running qTox on it for quite some time. I'll close this until I run into this again, if ever.
