### ISSUE TITLE
Groupchat: :[tab] will autocomplete for all nicks, not only for those starting with `:`

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#1377]

**Comment by kushagrasurana** [comment]
@agilob can you provide a bit more detail. I cant get what you wanted to say.

**Comment by dubslow** [comment]
If the name in question starts with a `:`, tab completion works incorrectly.

**Comment by agilob** [comment]
@kushagrasurana http://webmup.com/V5ewy/vid.webm

**Comment by kushagrasurana** [comment]
@agilob :itsback=kushagrasurana :P
