### ISSUE TITLE
Double click on tray icon (Windows)

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#1379]
window qtox was minimized (minimized in tray) after double click on icon in tray - window do not restore, it only shows in statusbar

**Comment by agilob** [comment]
Did you fix it yourself? Can be closed?

You can close issues with commit like 'closes tux3/qtox#1379'
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by PKEv** [comment]
Yes now it works fine
