### ISSUE TITLE
duplicate of the sender's name

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#1402]
Add the sender's name in the chat window if the interval between messages more than 2 minutes.
It is difficult to understand the message history especially if the sender does not uses a combination of shift + enter

**Comment by dubslow** [comment]
You mean in groupchats...?

**Comment by PKEv** [comment]
No, everywhere.
when communication is not only a dialogue but just reset the links, or one of the users do not otvechat long time (departed).
allows you to separate groups of messages sent to each other

**Comment by tux3** [comment]
Implemented by #1470
