### ISSUE TITLE
Some icons are blurred

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#1405]
![formats7](https://cloud.githubusercontent.com/assets/2544251/6672954/a2840650-cc07-11e4-86cb-5aaf83c75d8f.png)

**Comment by ProMcTagonist** [comment]
Doesn't happen to me.

qTox 42fe29e83df19c2faadeb52d1e06f1ef799ba04a

libqt5*: 5.3.2+dfsg-4+b1

Resolution: 1680x1050

WM: OpenBox

uname -a: Linux hostname 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt4-3 (2015-02-03) x86_64 GNU/Linux

**Comment by PKEv** [comment]
Windows 7 x64
1920x1080
![image](https://cloud.githubusercontent.com/assets/6053197/6688837/86bf759c-ccc7-11e4-8ae5-98a36e085746.png)

**Comment by agilob** [comment]
I don't know if it was fixed, but can't reproduce anymore.
