### ISSUE TITLE
qtox: error while loading shared libraries: libqrencode.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dcharles525** [qTox/qTox#1408]
qTox won't even open on latest updates. Was working before update.

Elementary OS Freya

**Comment by ProMcTagonist** [comment]
Did you install libqrencode and its development files?

**Comment by dcharles525** [comment]
I wasn't aware that updating qTox required I install more files...I will try that!

**Comment by stephen304** [comment]
Encountered missing qrencode.h while building on arch. Installing qrencode fixes it.

Anybody else who stumbles upon this using arch should install qrencode from the official repos.

**Comment by zetok** [comment]
@stqism ↑

@ProMcTagonist For what "development" files are needed?

**Comment by stqism** [comment]
@dcharles525 Resolved the issue a few hours ago, just run `apt-get update && apt-get upgrade` and it'll magically take care of everything.

@dubslow Took care of you being lazy ;), feel free to close the issue.

**Comment by dcharles525** [comment]
@stqism thanks!!

**Comment by mzdunek** [comment]
for fedora rpm you need to add dependency for qrencode-libs
now i have only message:
Pakiety pominięto z powodu problemów z zależnościami: (with mean skipped)
    qtox-1.0-1463.x86_64 z tox

**Comment by dubslow** [comment]
Oops, forgot to update the package dependencies after fixing the build issue...

**Comment by kushagrasurana** [comment]
Install instructions for Windows should be updated.
Theres no mention for qrencode.

**Comment by zetok** [comment]
@kushagrasurana what that has to do with this issue?

**Comment by agilob** [comment]
@Stephen304 i wrote it on Arch, `pacman -Syu qrencode`
