### ISSUE TITLE
Unnecessary writes when Profile page is open

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1409]
Description:
qTox writes to `.ini` and `.tox` on focus switch when `Profile` page is open.
Focus switches that trigger it:
- between input fields (nick and status)
- qTox window (when it gains focus)

I think that it may be a regression, since I don't remember that kind of behaviour before #1364 was closed, although I may be wrong about when it was introduced.

(overwritten = written to)

Info:
OS: Hardened Gentoo Linux x86_64
DE/WM: i3
Qt: 5.4.1
qTox: 42fe29e83df19c2faadeb52d1e06f1ef799ba04a

Reproducible: Always

Steps to reproduce:
qTox window focus:
1. Set your DE/WM to switch window focus on mouse hoover (window gains focus the moment mouse is hoovered over it) ← I'm not sure whether this step is necessary, as I didn't test in other setting
2. Open `Profile` page in qTox
3. Move mouse from qTox onto some other window and back on qTox (qTox loses focus and gains it)
4. `.ini` and `.tox` are overwritten when qTox regains focus.

qTox profile input fields:
1. Open `Profile` page in qTox
2. Click on input field for `Nick` (qTox overwrites `.ini` and `.tox`)
3. Click on input field for `Status` (qTox overwrites `.ini` and `.tox`)

What happened:
Switching focus when in `Profile` page caused qTox to write to `.ini` and `.tox`.

What should happen:
Switching focus shouldn't make qTox write to `.ini` and `.tox` when `Profile` page is open.

Additional info:
https://a.pomf.se/hryohn.webm

**Comment by dubslow** [comment]
The first one is intended (and has been behavior pretty much since the beginning), because focus losing means editing finished, i.e. your username/status changed, so core is updated and save files written. Edit: Wait you mean focusing them at all, not just when they become unfocused?

Just focusing qTox shouldn't be triggering that though...

**Comment by zetok** [comment]
@dubslow what "editing" when content doesn't change?

**Comment by tux3** [comment]
This shouldn't happen anymore, we write on exit/logout and at some other times, but much more rarely.

**Comment by zetok** [comment]
Well, settings aren't being unnecessarily saved any longer, but profile (`.tox`) is still being saved for no reason on 217716184b3f12a4537e5e1a18611e2d0e60d744, thus reopening.

**Comment by tux3** [comment]
Oh right I missed this, sorry!
