### ISSUE TITLE
bootstrap.sh executing rm -rf /

### ISSUE THREAD

**Issue by clashman** [qTox/qTox#141]
When I executed bootstrap.sh, the script executed "rm -rf /" because of some empty variables in:

rm -rf ${BASE_DIR}/${SODIUM_DIR}
rm -rf ${SBASE_DIR}/${TOX_CORE}

Nothing but the slash remained. Not cool.

Checking for errors could have easily prevented this:
The previous command would fail:
mkdir -p ${BASE_DIR}

**Comment by msteinbeck** [comment]
Oh that's not cool. Why are ${BASE_DIR} and ${SODIUM_DIR} empty in your case?

**Comment by clashman** [comment]
the first line of the script fails:
readlink: illegal option -- f

But nevertheless, there should be some sanity checks before doing a rm -rf

I am on osx 10.9 btw.

**Comment by msteinbeck** [comment]
> the first line of the script fails:
> readlink: illegal option -- f

I have no osx, could you fix it please or just give me the right parameter?

> But nevertheless, there should be some sanity checks before doing a rm -rf

Of course. I'm on it

**Comment by clashman** [comment]
It seems there is no parameter to fix this.
From the manpage: "If the given argument is not a symbolic link, readlink will print nothing and exit with an error."

**Comment by msteinbeck** [comment]
Is "realpath" available on osx by default?

**Comment by clashman** [comment]
negative

**Comment by msteinbeck** [comment]
I really don't like Mac OS X :). I'll look for another solution...

**Comment by msteinbeck** [comment]
What is about:

ABSPATH=$( cd $(dirname $0); pwd)/$(basename $0)
echo ${ABSPATH}

Does ${ABSPATH} contain the absolute path inclusive file name? Does it contain the path regardless of the directory you run it from?

**Comment by clashman** [comment]
Jep, this works. It does not resolve symlinks in the path though.

**Comment by msteinbeck** [comment]
> Jep, this works. It does not resolve symlinks in the path though.

This should be fixed by adding -P to pwd:

ABSPATH=$( cd $(dirname $0); pwd -P)/$(basename $0)
echo ${ABSPATH}

**Comment by clashman** [comment]
True. Works as expected now.

**Comment by msteinbeck** [comment]
Should be fixed with #143

**Comment by msteinbeck** [comment]
this issue is now fixed and can be closed

**Comment by tux3** [comment]
Now I'm getting referrals from a Russian tech humor site linking to this issue. Thanks, I guess.
http://strimoid.pl/c/wFY77w/when-i-executed-bootstrapsh-the-script-executed-rm-rf-because-of-some-empty-variables

**Comment by msteinbeck** [comment]
You are welcome, I guess.

**Comment by suhr** [comment]
> Russian

It is Polish, you know.

**Comment by tux3** [comment]
Ah yes, strimoid.pl
My bad.
