### ISSUE TITLE
[Regression] qTox no longer minimizes to tray when clicking on tray

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1411]
Description:
Since recently qTox no longer minimizes to tray when clicking on tray icon.

Info:
OS: Hardened Gentoo Linux x86_64
DE/WM: i3
Qt: 5.4.1
qTox: 42fe29e83df19c2faadeb52d1e06f1ef799ba04a
Tray: `SystemTrayIcon: Using the Qt backend`

Reproducible: Always

Steps to reproduce:
1. Click on qTox's tray icon (perhaps requires i3 ?)

What happened:
Nothing. When clicking quickly multiple times, qTox window instantaneously "blinks" (I think that it disappears and appears again?)

What should happen:
qTox should minimize to tray.

Additional info:
I _suspect_ that e3946b443502abec5f8d795e78fb37c58a4130f9 introduced regression.

**Comment by dubslow** [comment]
Can you run under gdb with debug symbols and execute the following:

```
break widget.cpp:453
run
next
```

Keep hitting enter (which runs the previous cmd, in this case `next`) while the current line number is between 453 and 487 in widget.cpp, then when it's not, copy and paste all the output here.

**Comment by zetok** [comment]
```
Breakpoint 1, Widget::onIconClick (this=0x555555d02e70, reason=QSystemTrayIcon::Trigger) at src/widget/widget.cpp:453
453 src/widget/widget.cpp: No such file or directory.
(gdb) next
468 in src/widget/widget.cpp
(gdb) next
Widget::qt_static_metacall (_o=0x555555d02e70, _c=QMetaObject::InvokeMetaMethod, _id=53, _a=0x7fffffffc560) at moc_widget.cpp:433
433 moc_widget.cpp: No such file or directory.
```

is that it?

**Comment by dubslow** [comment]
Augh, didn't realize you don't have the source available to make a comparison. I guess we'll have to do this the hard way.

Instead set `break widget.cpp:445` and `break widget.cpp:447`, then `run` and click the tray icon. If/when a breakpoint is hit, use `continue` to keep running, and report back if 0, 1 or both break points are hit.

**Comment by zetok** [comment]
@dubslow actually, I think that it should be possible to have source available after compiling. Since you wanted a debug build, you got one.. `;)`

**Comment by dubslow** [comment]
Do you want it to minimize to tray when you click the icon, even if the minimize to tray setting isn't set?

**Comment by zetok** [comment]
@dubslow Oh. Yes, please, especially since qTox unchecks that box **on every** qTox restart.

**Comment by agilob** [comment]
> @dubslow Oh. Yes, please, especially since qTox unchecks that box on every qTox restart.

Can't reproduce.

> [Regression] qTox no longer minimizes to tray when clicking on tray

Can't reproduce.

**Comment by zetok** [comment]
Can't reproduce any longer, closing.
