### ISSUE TITLE
First start no ID

### ISSUE THREAD

**Issue by XDjackieXD** [qTox/qTox#1412]
When I started the qTox client for the first time, the ID field was empty and clicking on the save image button crashed the client (copying the id or the image to clipboard resulted in an empty clipboard).
When I started it the second time, everything worked as expected.

I'm using qTox from the repository in Ubuntu 14.10 64Bit.

**Comment by dubslow** [comment]
That is... very strange.

**Comment by kushagrasurana** [comment]
Same happened with my friend on his mint today.

**Comment by dubslow** [comment]
Possibly related to https://github.com/tux3/qTox/issues/1352

Can either of you guys confirm or deny that issue happening to you?

**Comment by XDjackieXD** [comment]
No this hasn't happened to me

**Comment by kushagrasurana** [comment]
not happening to me too.
Also, after deleting my profile, i was able to reproduce this bug on ubuntu 14.04
