### ISSUE TITLE
OpenAL

### ISSUE THREAD

**Issue by XDjackieXD** [qTox/qTox#1415]
I don't have audio output on my Ubuntu 14.10 pc with qTox from the official repo.
I had the same problem in Toxic but solved it by replacing the ubuntu openal by the latest version.
With qTox this doesn't work (statically linked?) or is it an other issue?

**Comment by dubslow** [comment]
It is statically linked.

@stqism @irungentoo

**Comment by XDjackieXD** [comment]
any chance to get the newest git version of openal bundled in the next version? :P

**Comment by suhr** [comment]
Is this an issue now?

**Comment by zetok** [comment]
closing, since new qTox builds have openal statically linked: https://wiki.tox.chat/binaries#other_linux
