### ISSUE TITLE
PulseAudio output stuck open even when idle

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1416]
qTox keeps the sound output active 100% of the time even when a call's not going. I'm using network output in PA, so it's also adding a constant 1.5MB/s wifi traffic.

**Comment by dubslow** [comment]
@tux3

**Comment by agilob** [comment]
Well, I have different problem, but it might be related, it's probably related to my PA config, qTox always starts muted, happens only with qtox.

**Comment by zetok** [comment]
Perhaps #2094 will help with it.

**Comment by zetok** [comment]
Should be fixed by #2415, thus closing.

If you still have this issue, please comment for reopen.

Note that there is #2435.
