### ISSUE TITLE
Problem with build

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#1417]
problem with lib qrencode build in windows

**Comment by ProMcTagonist** [comment]
@stqism is this fixed now? after what you said in #1408? Or was that only for the Linux binaries?

**Comment by stqism** [comment]
@ProMcTagonist https://github.com/tux3/qTox/issues/1408#issuecomment-82548509

**Comment by PKEv** [comment]
Could not find how to collect qrencode under windows

**Comment by PKEv** [comment]
Maybe add https://code.google.com/p/qrencode-win32/source/checkout "qrencode-win32" fork in reporizitary tux3 for create (correct) script "bootstrap.sh" (build automation).
Especially the news: http://google-opensource.blogspot.com/2015/03/farewell-to-google-code.html
