### ISSUE TITLE
Friends list vertical scroll bar increases width of the list

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#142]
Thus, when the list is long enough to induce the scroll bar, I sometimes scroll horizontally (two finger scrolling on the trackpad), cutting off half of the icons on the right.

[This is a screenshot of the icons being cut off.](http://filesmelt.com/dl/qtox.png) It happends regardless of the actual width of the widget, as demonstrated here (with larger than minimum width).

*width, dammit, I can't edit titles :(

**Comment by F1ynn** [comment]
Fixed in #153.
