### ISSUE TITLE
failed upgrade for missing dep on RPM repo

### ISSUE THREAD

**Issue by bitchecker** [qTox/qTox#1422]
i'm trying to upgrade qtox but it fails!
this is output:

```
Resolution dependencies
-> Running transaction control
---> Package qtox.x86_64 0: 1.0-1455 set to be updated
---> Package qtox.x86_64 0: 1.0-1463 set to be an update
-> Processing dependence: libqrencode for the package: qtox-1.0-1463.x86_64
-> Dependency Resolution completed
Error: Package: qtox-1.0-1463.x86_64 (tox)
             Require: libqrencode
  You can try using --skip-broken to work around the problem
  Try running: rpm -Va --nofiles --nodigest
```

i've made a little search for check correct name of missing lib and this is output:

```
# yum search libqrencode
====================== Found: libqrencode ======================
qrencode.x86_64: Generate QR 2D barcodes
```

**Comment by dubslow** [comment]
And what if you `yum install libqrencode`?

**Comment by bitchecker** [comment]
@dubslow if you try to run your command you get:

```
No package libqrencode available.
Error: Nothing to do
```

**Comment by dubslow** [comment]
Oh I see, I misinterpreted your search command output. The correct name is just `qrencode`, right?

**Comment by bitchecker** [comment]
it seems!

**Comment by dubslow** [comment]
@bitchecker Can you try installing qtox again?

**Comment by bitchecker** [comment]
@dubslow who works on builds must to specify that libqrencode on RPM doesn't exist and change it with qrencode, after that run a new build!

if i remove package but dep is not satisfied i will not able to use qtox!

**Comment by dubslow** [comment]
I did make that change and pushed new packages to the repo. Are you sure it still says libqrencode? Maybe the package deploy process took a few minutes?

**Comment by bitchecker** [comment]
if i run an upgrade it still ask for libqrencode!
there is no way for repair it without remove and re-install application?

**Comment by dubslow** [comment]
First we need to verify whether or not you're getting an up to date package. It sounds like you're not... just in case I told the build system to build all of qtox from scratch again, so give it one more try in like half an hour?

**Comment by bitchecker** [comment]
```
Running transaction (shutdown inhibited)
  Installation: qrencode-3.4.2-4.fc21.x86_64 1/3
  Update: qtox-1.0-1477.x86_64 2/3
  Cleaning: qtox-1.0-1455.x86_64 3/3
  Verifying: qrencode-3.4.2-4.fc21.x86_64 1/3
  Verifying: qtox-1.0-1477.x86_64 2/3
  Verifying: qtox-1.0-1455.x86_64 3/3

Dependence installed:
  qrencode.x86_64 0: 3.4.2-4.fc21

Up To Date:
  qtox.x86_64 0: 1.0-1477

Complete!
```

it works, thanks!

**Comment by dubslow** [comment]
@bitchecker According to stqism the depend is really on `qrencode-libs`, and I had misunderstood him earlier. I've changed the dependency in the package; can you remove qtox, remove qrencode, and then reinstall qtox, and report on if qtox works with only qrencode-libs?

**Comment by bitchecker** [comment]
@dubslow that library was not shown during my research!! °_°

so, this is output when i re-install qtox: https://gist.github.com/bitchecker/dece648cfaac01c676ec

it seems to works!
