### ISSUE TITLE
Peerlist is bolded now

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#1426]
It's ugly and also means that bolding can't be used to show who's broadcasting.

Desired behavior: peerlist is not-bolded, as it used to be

**Comment by agilob** [comment]
+1

**Comment by dubslow** [comment]
Strange. When did it become bold?

**Comment by ProMcTagonist** [comment]
After the name-coloring for self and broadcaster PR was merged, as far as I can tell.

**Comment by zetok** [comment]
@dubslow after your changes.. didn't you explicitly change that?

**Comment by dubslow** [comment]
Nope. I only did `QLabel {color: red}`, though admittedly that overrides the previous style sheet. I guess it's probably an easy fix.
