### ISSUE TITLE
Dark background, bright text theme

### ISSUE THREAD

**Issue by Calinou** [qTox/qTox#1427]
Will there be a theme like that?

**Comment by dubslow** [comment]
@tux3 I've also seen a complaint that it doesn't properly support Qt theming, unlike tox-qt

**Comment by agilob** [comment]
@dubslow:

> it doesn't properly support Qt theming

why?

**Comment by dubslow** [comment]
> <Roukoswarf> how do you even use tox-qt?
> <Roukoswarf> it opens, it makes an id, it drops the id every time it opens
> <Roukoswarf> doesnt seem to connect to anything
> <irungentoo> it's a very old tox client
> <Roukoswarf> ah
> <Roukoswarf> its the only one that does proper qt theming
> <Roukoswarf> bunslow: any plans to not statically theme qtox?
> <bunslow> Roukoswarf: you'd have to ask tux3
> <bunslow> consider making a github issue
> <Roukoswarf> it has a "breeze" option
> <Roukoswarf> but it just... like... changes the ui shapes
> <Roukoswarf> nothing usable to integrate into breezre
> <Roukoswarf> breeze*

**Comment by agilob** [comment]
That's easy, select .css file which contains definitions overriding built-in theme, copy css to .config/tox/ save it as default in qtox.ini, load it on start-up instead the built-in resource.

**Comment by tux3** [comment]
Well, last I checked changing the UI theme worked OK for me, although I had to restart qTox. Although there aren't any special integration features for each theme, it's just a style change.

But otherwise, I agree that changing the CSS would be a nice solution.

**Comment by SkyzohKey** [comment]
I think that make the possibility to make our own themes via _.css/_.qss files and then select it via qTox settings could be a good feature ^^ :+1:

**Comment by agilob** [comment]
I have two styles ready (css only), but there are a lot of changes needed to implement them properly in qtox. widget.cpp must be rewritten and some other classes. I'm currently working on my major project so if anyone wants to finish what I started, let me know. ETA ~4h.
[Screenshots](https://github.com/tux3/qTox/pull/1499#issuecomment-94318122)

**Comment by SkyzohKey** [comment]
Wow, such an amazing job ! Both themes are beautifull, hope you will implement them :smile:

**Comment by sudden6** [comment]
Done by #5558
