### ISSUE TITLE
Drop Down fields overlap

### ISSUE THREAD

**Issue by kirillbobyrev** [qTox/qTox#1428]
The fields of drop down form overlap each other. Platform: Windows 8.1. The form is in the `Settings->Advanced->Chat history`
![2015-03-19 11-58-10 screenshot](https://cloud.githubusercontent.com/assets/3352968/6727100/8e79ae10-ce2f-11e4-9d29-0c5b2f63b2b4.png)
This is how it looks in Arch.
![2015-03-19 12-12-52 arch running - oracle vm virtualbox](https://cloud.githubusercontent.com/assets/3352968/6727242/493efd80-ce31-11e4-8faf-989f99fec971.png)

**Comment by dubslow** [comment]
This is probably an upstream bug...?

**Comment by ProMcTagonist** [comment]
I recall someone complaining about this in the past. They were on windows 8.1, I think, and had a non-english language. I can't find an issue for it.

**Comment by tux3** [comment]
I remember seeing it once before, but then it stopped so I though it was just me.
This is the only combo box that does this, so probably not an upstream bug. Perhaps a problem in the CSS/UI files.

**Comment by NoxNoctium** [comment]
There was a pullrequest which fixed this issue for other dropdown menus such as the smiley and language selection a couple of months ago. Can't find it anymore though.

**Comment by ghost** [comment]
This issue is here on Windows 7 with German language too.

![qtoxdropdownissue](https://cloud.githubusercontent.com/assets/12105354/7671575/f4816a2e-fcd6-11e4-95da-e0ac7cba844c.png)

But only at this dropdown. All others are working fine.

**Comment by ghost** [comment]
And it's also happening with English language:

![qtox_dropdownissueen](https://cloud.githubusercontent.com/assets/12105354/7671760/dd4582d2-fcdb-11e4-8cd6-1f1721fb1993.png)

**Comment by zetok** [comment]
Is this still a problem on newest qTox?

**Comment by NoxNoctium** [comment]
No, I think this was already discussed and closed in another (duplicate) issue.
![xtzus](https://cloud.githubusercontent.com/assets/2098025/9501399/773fc4e4-4c2b-11e5-83cd-1224330fcbdd.png)

**Comment by agilob** [comment]
Could be this a bug in Qt?

Duplicate was closed a few days ago, so closing this one too. If you encounter this problem again, it will be reopened.

**Comment by ghost** [comment]
No it's fixed.
