### ISSUE TITLE
Fetching toxId from namecoin

### ISSUE THREAD

**Issue by ulrichard** [qTox/qTox#1430]
A feature to fetch the toxId of friends from namecoin would be cool. 
PyBitmessage has this feature already implemented.

**Comment by dubslow** [comment]
Please move this to https://github.com/irungentoo/toxcore

**Comment by Nixpower** [comment]
Close, maybe?

**Comment by dubslow** [comment]
If I closed every duplicate and upstream qtox would have half the issues lol

**Comment by Nixpower** [comment]
lol, very true.

**Comment by ulrichard** [comment]
I considered this more a GUI issue than protocol level. Since it's just a very convenient and secure means to get the toxId of someody you know. But I don't know where you draw the line in Tox.
Anyway, I added a comment to https://github.com/irungentoo/toxcore/issues/1005

**Comment by zetok** [comment]
Thanks to recent changes (#2051) one can use arbitrary toxdns services, thus closing.

Anything more is ~out of qTox's scope.
