### ISSUE TITLE
qTox segfaults after a while

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#1437]
Console output:

```
Core::getGroupPeerName: Unknown error
Core::getGroupPeerName: Unknown error
Core::getGroupPeerName: Unknown error
Core::getGroupPeerToxID: Unknown error
zsh: segmentation fault  qtox
```

**Comment by dubslow** [comment]
Supposedly the group split today.

@JFreegman @irungentoo

Still shouldn't cause a crash... I'll probably need a backtrace to track it down though.

**Comment by ProMcTagonist** [comment]
I left my qTox on in groupchat overnight and when I came back in the morning the same error message was waiting for me (except without zsh)

Wasn't running from gdb, sorry.

**Comment by zetok** [comment]
> I left my qTox on in groupchat overnight and when I came back in the morning the same error message was waiting for me

~Exactly what happened.

:3

Backtrace: https://gist.github.com/zetok/c2f5682c8d0c86eb68fe

Perhaps it matters that core was patched to 2-channel audio? (Although it should only matter when sending audio, which wasn't the case, and I doubt that @ProMcTagonist would run modified core..(?))
Core patch: https://gist.github.com/zetok/a326be414c73eb64c48f

**Comment by dubslow** [comment]
This is fundamentally a bug with core not properly firing group peer change callbacks when the split occurred. @irungentoo

Any "fix" would be a horrible hacky mess to attempt to detect when the peerlist was corrupted by core, and I dont think it's worth the effort to fix when a) that was the first split in several months and b) new groupchats inc (and possibly c) new api overhaul inc)

**Comment by zetok** [comment]
Crashed again… it seems like recent regression, since I don't remember qTox constantly crashing just because it's in groupchat and someone disconnected/whatever. Also, didn't you @dubslow recently change the way group peers are displayed?

**Comment by dubslow** [comment]
I changed some of the backend stuff, and that's what's crashing now. I suppose maybe I will have to implement a work around.

**Comment by suhr** [comment]
I can't reproduce this anymore, so I close the issues until someone does it.
