### ISSUE TITLE
New Toxcore API

### ISSUE THREAD

**Issue by urras** [qTox/qTox#1444]
Toxcore has a new API at https://github.com/irungentoo/toxcore/tree/new_api, and it's likely that it will be merged into master in the coming months. @tux3, do you have any plans to port qTox to the new API?

**Comment by zetok** [comment]
@urras but @dubslow said that he works on it..?

**Comment by urras** [comment]
Ah, I was unaware that @dubslow was working on it in [dubslow/qTox](https://github.com/dubslow/qTox/tree/new_api_overhaul). Sorry for the confusion

**Comment by dubslow** [comment]
I've been distracted a bit by GSoC this week, but hope to get more substantial progress done this weekend, especially Sunday. Having said that @tux3 any help is appreciated :)

**Comment by tux3** [comment]
Unfortunately, I'm also incredibly busy this week, so I won't be very active.
