### ISSUE TITLE
Contact and setting loss

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#1445]
A friend just reported to me that suddenly 2 of their 3 contacts disappeared, and their theme colour went back to grey. The OS involved is Windows 7.

He reported to have forcefully rebooted his PC by holding the off button yesterday, so it could be the file got corrupted. At which point we should really try to at least not lose contacts. Perhaps consider making a "backup" file that is only written on adding/removing contacts?

His status message was also reset to one he used previously, but this was a long time ago.

Please notify me if there's any other useful info to help debug this, because this is not supposed to happen, obviously.

**Comment by dubslow** [comment]
Hrm... the files are generally not kept open, only opened, written to, then immediately closed. If qTox was interrupted in the middle of that it could cause corruption, and that's plausible though unlikely.

A backup that's only written on major user-facing changes is perhaps an easily doable idea though.

**Comment by TheLastProject** [comment]
The backup thing is mostly a suggestion. It may not really be too great of an user experience if they lose friend nicknames and the likes. Perhaps making a backup every X changes/time automatically, and an extra one on important changes, would make more sense.

The thing is, even though these kind of events are unlikely, we probably want to recover from them as well as we can, and losing friends is not really a graceful recovery.

**Comment by dubslow** [comment]
Indeed.

**Comment by tux3** [comment]
Strange, I though we had atomic settings file saving already, if not, I'll have to add that.

**Comment by agilob** [comment]
It happens to me occasionally on linux as well. I was never able to collect logs from those "crashes".

**Comment by sudden6** [comment]
> He reported to have forcefully rebooted his PC by holding the off button yesterday

In this case the file probably was only in the filesystem cache and not written to the disk by the OS.

One solution would be to force sync to disk. On Linux this is possible by calling `syncfs(int fd)`.

The drawbacks:
- Can hurt performance
- The data may only get to the HDDs cache, which is also lost on a forced reboot
- Very OS specific

**Comment by sudden6** [comment]
with 9a80950ac6e602494557db1657abe802ba1ab9ff it should very unlikely to corrupt the Tox profile or any settings files under normal circumstances.
This explicitly excludes a hard reset of your pc, because we don't really have control over the various caches of the OS or the HDD.
