### ISSUE TITLE
[Regression] ctrl + c doesn't work

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1448]

**Comment by dubslow** [comment]
Uh... your own bug report rules dude.

**Comment by zetok** [comment]
Description:
Regression in chatform. Copying with `CTRL + C` doesn't work, while copying to middle-click buffer works. Also `CTRL + A` doesn't work.

Info:
OS: Hardened Gentoo Linux x86_64
Qt: 5.4.1
qTox: 9079b334b9dc7a965555114fb377f84f22c23a89

Reproducible: Always

Steps to reproduce:
1. Select text with mouse (selecting with `CTRL + A` doesn't work)
2. Press `CTRL + C`
3. Try to paste it in qTox's finput field with `CTRL + V`

What happened:
"Old" buffer content is pasted.

What should happen:
"New" buffer content should be pasted.

# 

Why there are so many regressions in qTox lately, even though it's not even an API switch?

**Comment by dubslow** [comment]
@krepa098 

zetok when did this start happening? Literally nothing changed in the past few weeks...

**Comment by zetok** [comment]
@dubslow I've reported it as soon as I've noticed.

**Comment by dubslow** [comment]
Is it possible for you to do a `git blame`?

**Comment by Jookia** [comment]
All QShortcuts seem to be broken.

**Comment by zetok** [comment]
@dubslow -.-

```
e940459596d149046340f468c611ddeee9a83412 is the first bad commit
commit e940459596d149046340f468c611ddeee9a83412
Author: PKEv <pkev@yandex.ru>
Date:   Thu Mar 19 22:24:06 2015 +0300

    Correct for Maximized window

:040000 040000 23b9fa4f708b80ee4c8e7c640526df874f24c584 af957ba8f7102289bc03bfe85c0b348baf3a73d5 M  src
```

Reverting it fixes issue.

@PKEv

**Comment by PKEv** [comment]
what should I do?

**Comment by dubslow** [comment]
Figure out why your commit breaks QShortcuts. If I have time today I'll look into it, but I doubt I will.

**Comment by PKEv** [comment]
Sorry, correct.

**Comment by zetok** [comment]
72c45a65fa420459c7e139969c90c83c407f8b5c fixed it for me.
