### ISSUE TITLE
ID is not copied

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#1451]
When copying ID, by the friend's context menu , ID is not fully copied.
is missing at the end of 12 characters

**Comment by ProMcTagonist** [comment]
Upstream.

**Comment by zetok** [comment]
@ProMcTagonist it's not upstream issue. qTox is a fault here, since it tries to do something that isn't supported, and lies to users that it's doable.

**Comment by ProMcTagonist** [comment]
That's true. 

It would be nice if core actually provided it, but I doubt it'll ever happen.

**Comment by zetok** [comment]
@dubslow but it's not an upstream issue?

**Comment by PKEv** [comment]
why don't save friend's adress in settings?

**Comment by zetok** [comment]
@PKEv address is saved in .tox file. Also what "settings" do you have in mind?

**Comment by PKEv** [comment]
in thise code:
QString Core::getFriendAddress(int friendNumber) const
{
    // If we don't know the full address of the client, return just the id, otherwise get the full address
    uint8_t rawid[TOX_PUBLIC_KEY_SIZE];
    tox_get_client_id(tox, friendNumber, rawid);
    QByteArray data((char*)rawid,TOX_PUBLIC_KEY_SIZE);
    QString id = data.toHex().toUpper();

```
QString addr = Settings::getInstance().getFriendAdress(id);
if (addr.size() > id.size())
    return addr;

return id;
```

}

function Settings::getInstance().getFriendAdress(id) always return 0
and this is qtox side how i see

**Comment by PKEv** [comment]
maybe when delete this action from context menu?

**Comment by zetok** [comment]
@PKEv deleting isn't really needed, rewording (#434) it should be sufficient, but… welp, if you're planning to "fix" it, good luck dealing with qTox maintainers.

**Comment by agilob** [comment]
Toxcore issue once again. https://github.com/irungentoo/toxcore/issues/1300
