### ISSUE TITLE
systray under plasma5 should not use GTK, because it uses gtk

### ISSUE THREAD

**Issue by karolherbst** [qTox/qTox#1458]
especially with the breeze Qt theme activated you see, that qtox systray is rendered through gtk, because it uses a different style. Also using gtk in a Qt application for rendering stuff seems kind of wrong.

**Comment by karolherbst** [comment]
usually if you want to do StatusNotifier right (which also applies to the unity stuff) you should take the StatusNotifier dbus API description xml file, let qdbusxml2cpp generate some Qt source files and write against these. This will lead to code drop for specific desktop environments (good) and moves the responsibility for drawing out of qtox into the desktopshell (good), which then lets the menu looks native (good).

**Comment by tux3** [comment]
Unfortunately, StatusNotifier doesn't work on all desktops, so we need several other systray backends.

However, it should definitely use StatusNotifier by default instead of GTK on plasma5, can you post the qtox log ? Did you compile qtox by hand, or did you get it from the repos ?
Also, can you post the output of `echo $XDG_CURRENT_DESKTOP` in a x shell ?

**Comment by karolherbst** [comment]
I am on plasma 5 so it prints KDE. And it uses the StatusNotifier backend from qTox, but this one is gtk based ("SystemTrayIcon: Using Status Notifier backend" in log).

It should be possible to move to the libappindicator API (which would make it possible to merge the unity and plasma5 backends together). At least steam is using it and the steam systray menu also is drawn by the shell.

**Comment by karolherbst** [comment]
I use breeze for Qt and oxygen-gtk for gtk applications, that's why I noticed it in the first place.

**Comment by karolherbst** [comment]
Maybe I could try to investigate, why the unity backend didn't work as expected on plasma5 (I remember it may was an icon path error, not sure though.)

Also I use the gentoo ebuilds from the overlay.

**Comment by tux3** [comment]
The problem with libappindicator is that it doesn't allow to detect right-clicks, and just getting a callback when the menu is opened (so we can show/hide qTox to tray) is a horrible hack.

**Comment by karolherbst** [comment]
I see, I have problems with my libappindicator installation anyway, but it displays a try entry at least (with the unity backend on plasma5)

**Comment by karolherbst** [comment]
yeah with a working libappindicator setup, the left click does nothing and on right-click qtox windows shows up and the systray menu opens. Its qt styled at least.

But I see what you mean, steam also doesn't react to left clicks, but the window won't close into the tray anyway.

**Comment by karolherbst** [comment]
But the status icons do have a really low resolution :/

**Comment by zetok** [comment]
Is it still reproducible with newest qTox?

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.

If issue is still not fixed, please comment for reopen.
