### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by Epictek** [qTox/qTox#146]
./toxgui
    No settings file found, using defaults
    "Error loading translation en"
    Core starting with IPv6 enabled
    ./toxgui: symbol lookup error: ./toxgui: undefined symbol: toxav_register_audio_recv_callback`

OS is Arch Linux

**Comment by F1ynn** [comment]
Is your tox install up to date?

**Comment by Epictek** [comment]
Yes.

**Comment by dubslow** [comment]
I would bet that your tox install is at least [8 days](https://github.com/irungentoo/toxcore/commit/909db029412ddbd499281711a9cd46c3df4fe5a0) old.
