### ISSUE TITLE
Ctrl+PgUP/Down doesn't work for me (linux)

### ISSUE THREAD

**Issue by 4DA** [qTox/qTox#1461]
Okay, i can see these:
    new QShortcut(Qt::CTRL + Qt::Key_PageUp, this, SLOT(previousContact()));
    new QShortcut(Qt::CTRL + Qt::Key_PageDown, this, SLOT(nextContact()));

but they doesn't work

and the slot is likely not called at all.
    void GenericChatForm::nextContact()
    {
        qDebug() << "Nextcontact\n"; <<<<<<<<<<<<<<<<<<<<< not printed.
        parent->nextContact();
    }

any ideas?

**Comment by TheLastProject** [comment]
Would be fixed by #1454

**Comment by agilob** [comment]
not implemented yet, will be soon.

**Comment by tux3** [comment]
Fixed by #1454
