### ISSUE TITLE
[usability] Add 'Exit' button, also exit on Alt-F4

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#1466]
I ran qTox on window manager that doesn't draw the window frame (dwm manager), and found that it is impossible to stop qTox in such environment (except killing it).

Usually Alt-F4 exits, and also it is a good idea to have 'Exit' button somewhere.

**Comment by TheLastProject** [comment]
I really don't understand the necessity of this. If you run something like dwm, you are obviously tech-savvy enough to be able to close windows in it (with `Shift + Mod1 + c`, according to the Arch Wiki) and if you're not tech-savvy, you'll be using a more common setup which has a nice X in the corner, which is a much more consistent and therefore simpler way of closing applications than an exit button.

Again, I really fail to see how a lack of a specific exit button is an usability issue.

**Comment by yurivict** [comment]
Tech-savvy or not is besides the point.

Because all common GUI apps follow Alt-F4 and have Exit button in some form or another. It's like Ctrl+C copies text, Ctrl-V pastes, and Esc closes window. Commonly expected behavior. I can't find one other GUI app that doesn't have Ctrl-F4/Exit.

There is also this extreme situation when WM crashed, and windows are stacked on top of each other, and the only way to close is Alt-F4/Exit button.

**Comment by agilob** [comment]
Uncheck "Close to tray"?

**Comment by tux3** [comment]
Alt-F4 is not something applications are supposed to handle themselves, it's the job of the WM.

**Comment by Zer0-One** [comment]
From dwm.c, the default action for mod+shift+c:

```
void
killclient(const Arg *arg) {
    if(!selmon->sel)
        return;
    if(!sendevent(selmon->sel, wmatom[WMDelete])) {
        XGrabServer(dpy);
        XSetErrorHandler(xerrordummy);
        XSetCloseDownMode(dpy, DestroyAll);
        XKillClient(dpy, selmon->sel->win);
        XSync(dpy, False);
        XSetErrorHandler(xerror);
        XUngrabServer(dpy);
    }
}
```

I don't think that qTox actually handles WM_DELETE_WINDOW events. dwm is my window manager, and whenever I close a window, qTox segfaults because dwm has to call XKillClient().

**Comment by yurivict** [comment]
@Zer0-One -- yes, qTox segfaults on Alt-Shift-s, today I found why. It was (or maybe still is) a bug that variable trayMenu is undefined when tray isn't supported, like in dwm. I fixed  this today, and tried to make PR for that, but found that code changed a great deal in 8 days, and there is even no such variable trayMenu any more :-) So I put this aside until I update qTox next in BSD and will test this again then.

@tux3  You are right, Alt-F4 is the job of WM. But some apps still support it w/out WM, for example chrome. Most others support Ctrl-Q for exit now. I suggest, qTox should also support Ctrl-Q (and not Alt-F4), since this seems to be a standard.

**Comment by agilob** [comment]
Skype and gajim hide to tray on alt+f4

**Comment by ProMcTagonist** [comment]
Alt+f4 is the same as clicking the close button. It closes a single window, like clicking the WM's close button. If you have close to tray enabled, it'll close to the tray.
Ctrl+q is Quit. It quits the application, closing all windows and removing the tray icon.

**Comment by tux3** [comment]
#1477 was merged and will reach master on Monday, CTRL+Q can now be used to quit.
