### ISSUE TITLE
Pseudo-offline messages aren't sent

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#1468]
![notsent](https://cloud.githubusercontent.com/assets/1885159/6831110/903a04d6-d31e-11e4-9ed9-ba4406fd57c9.png)

**Comment by TheLastProject** [comment]
Maybe related to #1441? Although switching away and to the friend didn't cause them to get sent...

**Comment by TheLastProject** [comment]
Actually, seems to be a duplicate of #1098.

**Comment by agilob** [comment]
I didn't have this problem. All my 'faux offline messages' were send correctly.

**Comment by zetok** [comment]
Closing, since it's a duplicate.
