### ISSUE TITLE
Missing smileys

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#1471]
A lot of smiley packs are missing smileys, or at least not displaying them. Here is a lot of all the missing smileys on my system, for each pack I can select that is missing smileys.

Cylgom:
![snapshot150](https://cloud.githubusercontent.com/assets/1885159/6836003/e39d834e-d33e-11e4-9270-1ba93888f519.png)
Missing smileys:
- X.

TwitterEmoji:
![snapshot150](https://cloud.githubusercontent.com/assets/1885159/6836072/5c494d64-d33f-11e4-81ad-bb852062cd8c.png)
(Can't get a list because I can't type the symbols)

ccmathteam.com:
![snapshot150](https://cloud.githubusercontent.com/assets/1885159/6836310/31ed7a5c-d341-11e4-89a6-8e807e4f287d.png)
Missing smileys:
- :-x
- :-[
- O:-)
- :-@

greggman.com:
![snapshot150](https://cloud.githubusercontent.com/assets/1885159/6836366/81008184-d341-11e4-90aa-c2f74b85398d.png)
Missing smileys:
- :-'(
- :-Z
- :-[
- &gt;:-)
- O:-)
- :-@
- :-Q

phpBB:
![snapshot150](https://cloud.githubusercontent.com/assets/1885159/6836418/0ec26a8c-d342-11e4-811d-444e36bc9697.png)
Missing smileys:
- :-Z
- :-X
- :-[
- O:-)
- :-@
- :-Q

RedOnes:
![snapshot150](https://cloud.githubusercontent.com/assets/1885159/6836462/805950de-d342-11e4-9b99-c7cde3ec7148.png)
Missing smileys:
- &gt;:-(
- :-Z
- :-X
- :-[
- &gt;:-)
- :-@
- :-Q

tweakers.net:
![snapshot150](https://cloud.githubusercontent.com/assets/1885159/6836487/bea6c934-d342-11e4-8d0e-91f158b386d5.png)
Missing smileys:
- :-S
- :-X
- :-[
- &gt;:-)
- O:-)
- 8-)
- :-@
- :-Q

**Comment by jessica181920** [comment]
No longer an issue.

**Comment by anthonybilinski** [comment]
I also can't repro and smileys have been changed a decent amount since this was opened. Please comment if you run into it again.
