### ISSUE TITLE
video call problems!

### ISSUE THREAD

**Issue by bitchecker** [qTox/qTox#1473]
I received a video call and the process consumes much processor, after few minutes when the entire computer has become quite unusable, the process has crashed!
when i restarted qtox, there were some network problems, in fact i can't see online contacts and i need to reconnect manually application.

run on Fedora 21 with XFCE

**Comment by bitchecker** [comment]
[update]

high processor and memory usage ( with system load of 6.22 ) come also into audio/video configuration where i never see my cam, thinking that problems was on cam that where not found from operating system, but this one i found my image into screen ( all settings where not to zero but on half value of value bar ) but system load increase rapidly and i've need to kill process!

**Comment by bitchecker** [comment]
[update]

i don't see cam images again!

**Comment by tux3** [comment]
This should be fixed with FFmpeg.
