### ISSUE TITLE
drag and drop dont work

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#1478]
When drag and drop files to the chat history, there is no file transfer (windows 7 x64).
qTox reported that he could not open the file

**Comment by zetok** [comment]
https://github.com/tux3/qTox/wiki/Useful-bug-reports

**Comment by PKEv** [comment]
Info: OS: Win 7

Reproducible: Always 

Steps to reproduce:
1. drag and drop any file to chat log any friend

What happened:
QMessageBox::warning(this, tr("File not read"), tr("qTox wasn't able to open 1").arg(info.fileName()));

What should happen:
transfer file to friend

**Comment by TheLastProject** [comment]
Is this an online file or one that was stored locally on your PC? It may be a duplicate of #1276.

**Comment by PKEv** [comment]
it local file

**Comment by TheLastProject** [comment]
I unfortunately can't reproduce it. Mind giving more exact steps? I can drag an image just fine...

EDIT: Sorry, missed you were on Windows, I couldn't reproduce this on Linux (KDE).

**Comment by PKEv** [comment]
I do not know what to say, this situation has been verified on  work  computer and on home computer.
I've already done that PR would fix it #1482

**Comment by magnetik** [comment]
Confirming it on windows 7 pro. 

When drag and dropping a file from the explorer to a conversation window, error how : "qTox wasn't able to open <name of the file, without path>"

**Comment by tux3** [comment]
Fixed by #1482
