### ISSUE TITLE
Define default font colour

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#148]
![color](https://cloud.githubusercontent.com/assets/2544251/3611250/1d70f758-0d98-11e4-8596-b617ac0ae8ef.png)

Labels take font colour from system defaults, background is defined in the application. Please remove background colour definition or define font colour.

**Comment by agilob** [comment]
@tux3 I fixed it for myself

```
diff --git a/widget/widget.cpp b/widget/widget.cpp
index ea63ee8..96e1bd9 100644
--- a/widget/widget.cpp
+++ b/widget/widget.cpp
@@ -152,6 +152,9 @@ Widget::Widget(QWidget *parent) :
     friendListWidget->setLayoutDirection(Qt::LeftToRight);
     ui->friendList->setWidget(friendListWidget);

+    //set global font color
+    setStyleSheet("color: black");
```

Setting global font colour to black. Not the best solution, but works.

**Comment by neko259** [comment]
Was it resolved?

**Comment by agilob** [comment]
@neko259 I'm unable to compile atm
