### ISSUE TITLE
qTox forgets contact name in history

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#1481]
When scrolling through my history, I noticed qTox forgets which messages were sent by my contact, only showing my nickname in front of things, making it seem like I sent every single message.

**Comment by PKEv** [comment]
fix in #1464

**Comment by ProMcTagonist** [comment]
Still happens to me on latest.

**Comment by PKEv** [comment]
not merget yet..

**Comment by ProMcTagonist** [comment]
Ah. @dubslow's 

> Buddy I already merged your previous PR concerning this issue.

Confused me.

**Comment by TheLastProject** [comment]
Apparently this is fixed in the new branch (as written in duplicate #1536) so I'm closing this.
