### ISSUE TITLE
Suppressed first symbol after input language switch (Linux)

### ISSUE THREAD

**Issue by DaoDezi** [qTox/qTox#1484]
Lubuntu 14.10 64bit
LXDE
Language switching by xkb. 
xkb options:
XKBMODEL="pc105"
XKBLAYOUT="us,ru"
XKBVARIANT=",winkeys"
XKBOPTIONS="grp:ctrl_shift_toggle"

First symbol suppressed on input message after switching input language
Sample:
Need to type "проверка смешанного текста: test message"
I type message on russian: "проверка смешанного текста: " 
I change language layout by Crtl-Shift
And try type: "test message"
Whole message looks: "проверка смешанного текста: est message"

After switching En to Ru same issue

Also Ctrl-V don't work. Shift-Ins only

RU:
После переключения раскладки клавиатуры не печатается первый вводимый символ. Приходится нажимать кнопку первого символа дважды
Так же не работает вставка из буфера обмена по сочетанию Ctrl-V.

**Comment by DaoDezi** [comment]
Seems it was Ubuntu bug
I upgrade Lubuntu to 15.04 and the bug is gone. With Ctrl-V issue.
qtox_1.0-1495

**Comment by tux3** [comment]
Alright, thanks for the heads up.
