### ISSUE TITLE
qTox prevents logout on GNOME 3

### ISSUE THREAD

**Issue by jurf** [qTox/qTox#1485]
GNOME 3.16, Arch Linux. Same happened on 3.14.

When I try to logout while qTox is open in the background, nothing happens, until I close qTox. Extremely confusing, took me about a month to figure out what's wrong.

**Comment by Talkless** [comment]
Same in KDE (Kubuntu 14.04), I get system notification `Logout canceled "/usr/bin/qtox"` (or something like that, actually in my native language).

**Comment by agilob** [comment]
https://trac.transmissionbt.com/attachment/ticket/5206/0001-fix-Qt-tray-icon-causes-logout-cancelled-by-transmis.patch

seems to be related, also prevents on KDE5

apparently this code from widget.cpp can be problematic

```
void Widget::closeEvent(QCloseEvent *event)
{
    if (Settings::getInstance().getShowSystemTray() && Settings::getInstance().getCloseToTray() == true)
    {
        event->ignore();
```
