### ISSUE TITLE
Delete history message after deleting friend

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#1486]
Info: OS: Win

Reproducible: Always

Steps to reproduce:
1. delete friend
2. add friend back

What happened: history of message loaded

What should happen: chat history must be deleted

**Comment by apprb** [comment]
Chat history should not be deleted unless you really want to delete it.

**Comment by PKEv** [comment]
How to do it after removing friend?

**Comment by ProMcTagonist** [comment]
I find it really useful to know if someone I just added is someone I removed before. Also, sometimes people get removed accidentally. I agree with @apprb that chat history shouldn't be deleted unless that specific action (delete chat history) is taken.

**Comment by tux3** [comment]
I'd be in favor of deleting the history, possibly with a confirmation dialog first. 

I'm not sure why it should be expected that deleting someone and subsequently re-adding them would preserve the chat logs.

Removing a friend from your contact list is something significant, and there could be some serious privacy implications if the conversation logs with someone you deleted ages ago are still sitting around on your hard drive. 

I'll be waiting a little before merging #1489 if there aren't any serious counter-arguments. Never deleting the (potentially private) chat logs even after the contact is removed doesn't seem like a great security policy.

**Comment by zetok** [comment]
Why it was merged?

> Removing a friend from your contact list is something significant

Bullshit. You may remove contact accidentally or "in heat of the moment", and you may re-add it minutes / hours later, just to find out that your whole history is gone… It's a shitty behaviour.

> and there could be some serious privacy implications

What privacy implications? If one cares about that, they already use encryption - there is absolutely **no privacy implications**, unless someone doesn't actually care - then it's their problem.

> Never deleting the (potentially private) chat logs even after the contact is removed doesn't seem like a great security policy.

Sorry, but what that has to do with security?

And what's with this "Never deleting" ? If one cares about deleting stuff, there should be provided mechanism to simply delete any part of logs, which functionality qTox doesn't have…

---

So, AFAICS:
- @PKEv proposes changing something that isn't really an issue into something that would cause issues
- 2 people say that history shouldn't be deleted upon contact removal
- you @tux3, give some bullshit reasons, ask for counterarguments and merge patch after short time

…

**Comment by tux3** [comment]
Do you really delete people by mistake so often that it's a problem for you?

> Bullshit. You may remove contact accidentally or "in heat of the moment", and you may re-add it minutes / hours later, just to find out that your whole history is gone… It's a shitty behaviour.

Then that's a different problem and we should probably add a confirmation message.

> What privacy implications? If one cares about that, they already use encryption - there is absolutely no privacy implications, unless someone doesn't actually care - then it's their problem.

It's reasonable to expect that when you delete a contact, it's actually deleted. 

> Sorry, but what that has to do with security?

Keeping logs of all your conversations with people you removed long ago, never deleting those logs?
I don't know if that's a good idea. My question is, why would you keep them? Why not be "better safe than sorry"?

I don't understand why you're so strongly against this. If you want to be able to re-add someone you deleted, maybe we can add a confirmation dialog?

**Comment by zetok** [comment]
> Then that's a different problem and we should probably add a confirmation message.

It's not a different problem. Problem is that default qTox behaviour results in data loss. → shitty behaviour

Confirmation message would help, in a form of asking whether user also wants to remove history related to contact that is being removed.

> It's reasonable to expect that when you delete a contact, it's actually deleted. 

Yes. Contact. `Contact` ≠ `History of talks with that contact`

> Keeping logs of all your conversations with people you removed long ago, never deleting those logs?

Now that is a different problem. If one wants to delete logs, qTox should provide mechanism to do so independently form removing contact.

> Why not be "better safe than sorry"?

You're not being "better safe than sorry" by **silently removing user data**.

**Comment by ProMcTagonist** [comment]
The confirmation dialog would make it loudly remove user data.
