### ISSUE TITLE
AutoUpdater don't work

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#1488]
there were no updates for Windows

From qTox debug view:
.....
AutoUpdater: getUpdateVersion: network error:  "Error downloading https://tux3-dev.tox.im/qtox/win32/version - server replied: Not Found"
...

**Comment by tux3** [comment]
That's intentional, I haven't had the time to fix the Windows builds in quite a lot of time, so the update server is disabled for the moment (to prevent a separate bug with empty updates).
