### ISSUE TITLE
qTox cannot into time change

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1490]
![time change](https://cloud.githubusercontent.com/assets/3148759/6885089/8824a99e-d608-11e4-957c-2fe662384e69.png)
qTox | real time

Please fix.

**Comment by kushagrasurana** [comment]
how to reproduce ?
I get same time when i send a text message.

**Comment by zetok** [comment]
Steps to reproduce:
1. Open qTox
2. Wait for time change
3. System's time changes, time displayed by qTox doesn't change

**Comment by rohilsurana** [comment]
Where is this time that needs to change? I don't think it is timestamp of a message that needs to change. Is this the one in combobox in settings?

**Comment by zetok** [comment]
Actually, it seems to be an issue with my clock, while system clock is fine, the one displaying time in panel isn't…
