### ISSUE TITLE
Can't find my own Tox ID

### ISSUE THREAD

**Issue by griffondor** [qTox/qTox#1494]
dans les parametre de qtox y'a que 4 onglets dans les paramètre "général" "vie privée" "audiovideo" et "avancé" et dans aucun de ces 4 onglets on voit l'id tox apparaitre, c'est normal ça ?
![tox quatre onglets](https://cloud.githubusercontent.com/assets/10903493/6901485/cb02ff4e-d70d-11e4-8e4d-58fcf699eae8.jpg)

**Comment by ArchangeGabriel** [comment]
Tu dois cliquer sur ton pseudo (griffondor) pour y accéder.

You have to click on your nickname to access it.

**Comment by griffondor** [comment]
ok merci , mais je trouve que c'était mieux dans onglet "vie privée"

**Comment by griffondor** [comment]
c'est pas pratique ça, c'est trop cacher, faut que ça soit plus visible
