### ISSUE TITLE
Make toxgui installable

### ISSUE THREAD

**Issue by Ilya87** [qTox/qTox#15]
There's no way to make package (set install path) for distro using current toxgui.pro.

**Comment by tux3** [comment]
Eventually the plan is to only have a single big toxgui in /usr/bin/, and config files generated in ~/.config/Tox/Toxgui/

**Comment by Ilya87** [comment]
And what about localization - .qm files (I hope it'll be)?

**Comment by tux3** [comment]
We can put them in /usr/share/Toxgui.
(And in Program Files on Windows, and in the app folder on Mac)

**Comment by Ilya87** [comment]
That's what I mean.But now command "make install" after "qmake", "make" does nothing.

**Comment by tux3** [comment]
Okay, I'll add it.
But first I need to put all the ressources in a .qrc

**Comment by Ilya87** [comment]
In this case toxgui.desktop for linux should be created and all icons off app (according to their resolution) should be stored in /usr/share/icons/hicolor/{16x16,22x22,24x24,32x32,36x36,48x48,64x64,72x72,96x96,128x128}/apps

**Comment by tux3** [comment]
Okay, all the resource files are now embedded in toxgui.

To install just copy toxgui to /usr/bin and to uninstall rm /usr/bin/toxgui and ~/.config/tox/settings.ini

I'll try to add that to the project directly.
