### ISSUE TITLE
Receiving files doesn't work (if !fopen)

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#151]
```
"Core: Received file request 0 with friend 0"
[New Thread 0x7fffdc815700 (LWP 25521)]
[Thread 0x7fffdc815700 (LWP 25521) exited]
Core::acceptFileRecvRequest: Unable to open file
```

File sent from µTox.

**Comment by zetok** [comment]
My fault with that.

I couldn't save file because I didn't have permissions set right.

qTox should check whether saving in given directory is possible, and if not, should notify user about problem, so user could choose different directory.

**Comment by dubslow** [comment]
This issue is now fixed.
