### ISSUE TITLE
qTox videocalls randomly halt my computer

### ISSUE THREAD

**Issue by unfa** [qTox/qTox#1513]
I'm almost sure that this is some problem with webcam driver, although no other program utilising my webcam halted my whole laptop.

One day when I was using videocalls on qTox, my laptop randomly and violently powered-down two times in an hour. This happened before, but never so frequently.

**The hardware:**
ASUS K52Jc with Intel Core i5 and nVidia 310m

**The software:**
uname -a
Linux unfa-K52Jc 3.13.0-48-lowlatency #80-Ubuntu SMP PREEMPT Thu Mar 12 11:33:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I just updated my kernel to see if that does the trick, but I don't quite want to test this bug too much. It's very frustrating, both to me and my friend on the line.

Let me know how can I help getting this fixed.

**Comment by suhr** [comment]
I believe this is not a qTox issue.

**Comment by tux3** [comment]
This is very surprising.

Could you check your system logs to see if something abnormal happened ?
If any application can cause your computer to shut down, then there's a serious issue somewhere with your system.

**Comment by tux3** [comment]
This is unlikely to be a bug in the qTox code, and there's not enough information to resolve this. Closing for now.
