### ISSUE TITLE
Right-clicking imprecisely with highlighted text unhighlights it so copying is impossible

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#1517]
Desired behavior: right-clicking anywhere when text is highlighted brings up a context menu where Copy is available for selection.

Actual behavior: right clicking anywhere but exactly on the highlighted text dehighlights the text and brings up a useless context menu with copy greyed out.

**Comment by tux3** [comment]
Fixed by #1522

**Comment by ProMcTagonist** [comment]
Thanks :)
