### ISSUE TITLE
qTox needs some help! (Edit: TUX IS BACK :D)

### ISSUE THREAD

**Issue by itsrachelfish** [qTox/qTox#1520]
We haven't been able to contact @tux3 or @dubslow lately and they were the core devs for this project.

Recently some protocol changes happened and qTox can't communicate with clients using the new API (See issues #1469, #1505, #1506). Unfortunately nobody else is active enough or knows how to make these updates and that's why we need :sunglasses:  YOUR HELP. :umbrella: 

Maybe someone out there knows enough C++ and Qt to fix this?

**Comment by hexafluoride** [comment]
I can help ^_^

**Comment by itsrachelfish** [comment]
Wow @hexafluoride that's great! :D

You'll probably want to make your own fork so you can submit a pull request!

Please see the qTox wiki for more information on becoming a developer:
https://github.com/tux3/qTox/blob/master/INSTALL.md
https://github.com/tux3/qTox/wiki#contributing

**Comment by kushagrasurana** [comment]
i will work on :D

**Comment by rohilsurana** [comment]
me too :D

**Comment by saneki** [comment]
@dubslow mentioned in a previous commit (15 days ago) that nothing would be merged until their new_api_overhaul branch was merged (although there has been one minor merge since then).

If you're planning on helping, might want to check out https://github.com/dubslow/qTox/tree/new_api_overhaul

**Comment by tux3** [comment]
I am, in fact, still alive.

I looked at the new_api_overhaul branch, and I think that it should be possible to get it into a working state with a couple hours of hard work. However I haven't pushed any code yet because I was a bit short on time and though someone else was actively working on it! 

I'll be getting things in order again very soon if unless someone else does it before.
As always, any help is greatly appreciated!

(And of course you can always contact me at my public email, which I always answer.)

**Comment by stal888** [comment]
![](https://cloud.githubusercontent.com/assets/774591/7104025/11d385a0-e079-11e4-8bdd-1a5ae8f8f73c.png)

**Comment by landswellsong** [comment]
So this still needs a hero?

**Comment by itsrachelfish** [comment]
@landswellsong Originally @dubslow was working on this because @tux3 didn't have the time to make the changes. Unfortunately while working on the new_api_overhaul branch dubslow ran out of free time as well.

If you're able to fix any of these issues I'm sure tux would appreciate it. :)

**Comment by TheLastProject** [comment]
@landswellsong Yes, really badly. @irungentoo did a quick port on https://github.com/Tox/qTox that "compiles" but obviously can't really do anything, but it may help to use together with the new_api_overhaul branch or whatever fixes this.

**Comment by TheLastProject** [comment]
<+tux3> qTox is now completely ported to the new API, I'll merge it back to master when I'm confident it's ~stable. Feel free to test the new branch in the meantime.

\o/

**Comment by agilob** [comment]
I used the development branch for last cople of days, qtox(linux) <-> qtox/µtox (windows) and everything is OK. Found a bug in notification system, but there is already PR for it.

**Comment by Zer0-One** [comment]
We can probably close this now
