### ISSUE TITLE
qTox sends file to different user than I selected!

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#1533]
I was trying to send a screenshot to zetok, but instead qtox was trying to send it to another user who messaged me:
' I can't save it'

Sending file to @zetok 
![qtox1](https://cloud.githubusercontent.com/assets/2544251/7334041/90de7ab2-eb7d-11e4-812a-261e6dfed0aa.png)

Another users tells me, they received file transfer request:
![qtox2](https://cloud.githubusercontent.com/assets/2544251/7334042/9424eca6-eb7d-11e4-8367-d62c9ba88cbf.png)

I'm using qtox from branch back_in_the_game, pulled and compiled 10minutes ago.

**Comment by tux3** [comment]
@agilob Could it be a dup of #1516?
It's possible that users on the old API will receive spurious file transfer requests.

Howether if zetok didn't receive it, then it's a different bug.

**Comment by agilob** [comment]
I already had fix for #1516, do both sides need that fix?

**Comment by agilob** [comment]
Both zetok and mgro were using old api at the time, so most probably incompatibilities.
