### ISSUE TITLE
Chat widget doesn't load nicks

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#1536]
1. receive message
2. **restart qtox**
3. open chat with the same person
4. only your nick was loaded 

What I see:
![qtox3](https://cloud.githubusercontent.com/assets/2544251/7336361/3b3e46e4-ebf2-11e4-9b45-f5b1818f0247.png)

What zetok sees:
![2015-04-20 stq s second account on github - already removed12](https://cloud.githubusercontent.com/assets/2544251/7336362/46b344ca-ebf2-11e4-8601-e9f8cab54d5e.png)

**Comment by zetok** [comment]
Both clients are on new api

**Comment by tux3** [comment]
Hm, how come you both see a different history?

**Comment by zetok** [comment]
It's not different, it's the same history. qTox simply displays it in a wrong way.

**Comment by tux3** [comment]
Before the new day on agilob's side the last message is at 18:51:25 and on zetok's side the last message is at 18:51:44, and they aren't the same. That's strange?

**Comment by agilob** [comment]
chat widget prints time when a user received a message, not time when the message was sent. zetok was using oldapi at the time, he's using newapi today.

**Comment by tux3** [comment]
Fixed in back_in_the_game
