### ISSUE TITLE
Broken encryption of local content

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#1537]
Whenever I restart the program, it often asks me to use my password to decrypt the local files, then when I do so it tells me that "No Encrypted Chat History file found, or was corrupted, History will be disabled!"

If this error doesn't manifest, then it accepts my password, but nothing is restored. If I go back into settings, the chat history is disabled again by default.

https://www.reddit.com/r/projecttox/comments/33v4d0/qtox_encryption_of_local_content/

**Comment by tux3** [comment]
> Latest stable build Win7 x64

That would be the old API qTox, then. 
I'm not sure if it's fixed in the new API, I haven't ran into that yet but I'll try to repro.

**Comment by tux3** [comment]
I believe this is fixed.
