### ISSUE TITLE
qtox compiles as toxgui

### ISSUE THREAD

**Issue by lehitoskin** [qTox/qTox#154]
Running a fresh clone, /usr/lib/qt5/qmake, make, project still compiles as toxgui. This makes the Portage overlay fail because it expects the binary to be called "qtox", not "toxgui".

**Comment by dubslow** [comment]
There is a pull request waiting to fix this. It wasn't immediately merged because the Tox build system, Jenkins, needed to be updated. However, to the best of my knowledge, that has been completed so we're pretty much just waiting on tux3 to merge the PR.
