### ISSUE TITLE
qTox unusable due to infinitely warnings that the profile is already in use and segfaults.

### ISSUE THREAD

**Issue by madezent** [qTox/qTox#1540]
# Situation

I just compiled qTox on my machine following the [official instructions](https://wiki.tox.im/QTox#Other). I never had tox installed on this machine before. The same issue occurs using the [official binary](https://jenkins.libtoxcore.so/job/qTox-linux-amd64/lastSuccessfulBuild/artifact/qt/qtox.xz).
# Problem

After starting, a warning pops up with title: "Profile already in use" and text: "Your profile is already used by another qTox\nPlease select another profile". Always after clicking OK, the same warning appears again. When I try to set the online status using the status bar icon qTox causes a segmentation fault.
# Console output

$qtox
Gtk-Message: Failed to load module "canberra-gtk-module"
IPC: Our global ID is  15580405818507738954
IPC: Attaching to the global shared memory
No settings file found, using defaults
Settings: Loading from  ":/conf/qtox.ini"
Using embeded bootstrap nodes list
Couldn't open log file!
built on:  19:04:50 Apr 26 2015 ( 1430085842 )
commit:  2fed6724b2fe28356f9e2858952e0eb3b65df6da 

IPC: postEvent  "activate" to 0
Nexus: Starting up
Core: loading Tox from ""
Audio:  "Trying to open output "
Audio: Opening audio output  ""
Audio:  "Trying to open input "
Audio: Opening audio input  ""
Core: Starting up
Profile  ""  is already in use, pick another
SystemTrayIcon: Using GTK backend

(qtox:2616): GdkPixbuf-CRITICAL **: gdk_pixbuf_new_from_data: assertion 'data != NULL' failed
Profile  ""  is already in use, pick another
IPC: Previous owner timed out, taking ownership 2941648667917583582 -> 15580405818507738954
Profile  ""  is already in use, pick another
Profile  ""  is already in use, pick another
Profile  ""  is already in use, pick another
Profile  ""  is already in use, pick another
Profile  ""  is already in use, pick another
Falha de segmentação

**Comment by dcharles525** [comment]
I am getting this on v1.0 as well!

**Comment by tux3** [comment]
It seems that qtox doesn't have write permissions to its config folder (~/.config/tox on Linux). It couldn't create a log file, a settings file, or a profile.

Can you confirm that the config folder exists and is writable?

**Comment by madezent** [comment]
~/.config/tox didn't exist and creating that directory solves the problem.

**Comment by dcharles525** [comment]
Yeah I opened up Toxic and it created a tox folder, after that I had no issues.
