### ISSUE TITLE
Limit file size of avatars to 64kB

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#1543]

**Comment by agilob** [comment]
I successfully changed my avatar to 180MB image from NASA.

**Comment by LittleVulpix** [comment]
:D that is actually somewhat amazing

**Comment by TheLastProject** [comment]
I assume we'll do this sanely and just downscale large images, instead of doing it the uTox way and preventing people from choosing overly large images? Isn't there a STS on avatar sizes?

**Comment by zetok** [comment]
@TheLastProject sadly, due to how STS is (or rather wasn't) managed, it became ~outdated.

there is https://github.com/irungentoo/Tox_Client_Guidelines ..

edit: according to ↑, clients should currently limit avatar size to 64 KB

**Comment by ProMcTagonist** [comment]
> I assume we'll do this sanely and just downscale large images

This is a must.

**Comment by tux3** [comment]
Implemented in 8407bbada909881ba5e823eefd18c144dac4b9a0

If it's not already <64kB we first try to resize to a 256x256 PNG and check if that result is <64kB.
If it's not, we try to resize this one to 128x128, 64x64, and 32x32.
If it's somehow still not <64kB, you get an error message.

The aspect ratio is preserved and we use a high-quality scaling algorithm.
