### ISSUE TITLE
Click a received ToxID to directly add it (like links)

### ISSUE THREAD

**Issue by SkyzohKey** [qTox/qTox#1544]
Hey, like the title said I think it could be fine to make the users able to click ToxID they received via message (just like links) to trigger the add friend window ^^

**Comment by zetok** [comment]
@FishTFM hmm, it doesn't work with
tox:56A1ADE4B65B86BCD51CC73E2CD4E542179F47959FE3E0E21B4B0ACDADE51855D34D34D37CB5
?

**Comment by SkyzohKey** [comment]
I mean in tox ^^
EDIT: Just tried, ok I'm noob :-1:

**Comment by zetok** [comment]
well, if it works, can you close the issue?
