### ISSUE TITLE
Broken contacts sorting?

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#1546]
![sad1](https://cloud.githubusercontent.com/assets/2544251/7359031/1f1b74b4-ed32-11e4-9fe8-699192e9a466.png)

What I think it should be:

```
{ Acontact  | online
{ Bcontact  | online
{ Ccontact  | online
{ A2contact | away
{ C2contact | away
{ A3contact | offline
```

In this case Zian should be above Zetok.

**Comment by Zer0-One** [comment]
@agilob Nope. I implemented it this way on purpose. If Zetok is online, he gets sorted in the same layout as other online contacts. Otherwise, the sorting gets confusing.

**Comment by agilob** [comment]
ok. I just got use to sorting like pidgin/gajim do it, where status is more important. both clients support more statuses. If you planned this, then I think it's ok.
