### ISSUE TITLE
Crash upon starting from cmd

### ISSUE THREAD

**Issue by Draako** [qTox/qTox#1548]
If qTox is started from cmd it crashes.

```
 Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: qtox.exe
  Application Version:  0.0.0.0
  Application Timestamp:    00020000
  Fault Module Name:    libtoxcore-0.dll
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   00000000
  Exception Code:   c0000005
  Exception Offset: 000000000000ecf0
  OS Version:   6.1.7601.2.1.0.256.48
  Locale ID:    2057
  Additional Information 1: 6401
  Additional Information 2: 64012012260663dbd3549aa69170094d
  Additional Information 3: ab78
  Additional Information 4: ab7840377e1380321f3d5f05aeddf113
```

On the other hand if it is running and is started from cmd it switches over to running instance.

**Comment by tux3** [comment]
So, the crash report says it's a segfault at 0xECF0 in libtoxcore.
I'll see if I can reproduce.

**Comment by zetok** [comment]
Is this still reproducible on newest builds?

**Comment by agilob** [comment]
afair all those issue reported by @Draako were related to migration to new toxcore and he had a problem with RW permissions. We fixed issues on chat, but I told him to report it anyway.

**Comment by antis81** [comment]
Seems to start fine on Linux (yeah, I know we have `.so` instead of `.dll`). Thus, I marked this issue for windows. Feel free to correct, if that is wrong.

**Comment by agilob** [comment]
It was related to migration to new toxcore api.

**Comment by antis81** [comment]
@agilob :+1:

**Comment by Draako** [comment]
> Is this still reproducible on newest builds?

It starts fine now.
