### ISSUE TITLE
qTox update bug

### ISSUE THREAD

**Issue by huettenhain** [qTox/qTox#1555]
I am running Windows 2008 Server R2, and the qTox Updater seems to be buggy. It recently told me that there is an update available and asked whether to download and install it. I said "yes". It told me that the update would be installed as soon as qTox is restarted, so I restarted qTox. Every time since then, when I launch qTox, it requests to be elevated to administrator privileges. If I elevate it, it spawns the error "no update found, qTox will restart now". It then starts running under the Administrators account, who does not have a qTox profile. If I deny it the elevation, it will eventually start under the normal user account and tell me that there is an update available again.

**Comment by ovalseven8** [comment]
@tux3: Should be closable now, right?

**Comment by tux3** [comment]
Yep, this is fixed.
