### ISSUE TITLE
Bug with messaging between uTox and qTox

### ISSUE THREAD

**Issue by redmanmale** [qTox/qTox#1556]
I'm using uTox 0.2.p, my colleague qTox 1.0. Systems are Win 8.1 x64 and Win 7 x64 respectively.

Since start chat every incoming message, which my colleague send, shows in my chat many times.
And all messages keep going come every 20 seconds over and over again.

Bug in uTox issues (https://github.com/notsecure/uTox/issues/1001).

**Comment by agilob** [comment]
Does µtox have new API? 
https://github.com/tux3/qTox/issues/1506

**Comment by LittleVulpix** [comment]
0.2.p is the new api uTox, so yes.

**Comment by ghost** [comment]
I had this happen when i updated my client with new api version and my wife still was using old api version. It resulted in message spam as well as in 4 byte prefix of message. Likewise sending msg from new api client to old api resulted in first 4 characters cut off.

**Comment by redmanmale** [comment]
After updating qTox client the problem is gone.

**Comment by agilob** [comment]
@redmanmale close please.
