### ISSUE TITLE
Audio Capture does not Work

### ISSUE THREAD

**Issue by ndbeals** [qTox/qTox#1557]
I have the latest (can't find a version string anywhere) version of Qtox installed on (64 bit windows 7). I installed it last night.

I can hear audio come from tox, whether it is chat notifications or voice from others, but qtox does not have any audio input from me. I have the capture device set the proper device (my sound card mic input) and it does not work. I also tried my motherboard's builtin mic port and it did not work either.

At one point, my microphone worked but audio playback did not. Now microphone doesn't work.

I have tried all sorts of settings changes, and using the different mic ports which leads me to believe this is a bug. I can provide you with more information if need be.

One last thing, similar to how skype has it, it would be very, very, very helpful if Qtox had an input bar in the audio options to show you if the capture device qtox is using is actually capturing anything.

**Comment by ndbeals** [comment]
Here's a the log as requested from the IRC channel. http://puu.sh/hvP4m/94914a2933.log

**Comment by ndbeals** [comment]
Thanks for the exemplary support and quick response times!

**Comment by zetok** [comment]
Does it refuse to work with audio filtering on?

**Comment by ndbeals** [comment]
Audio filtering does not make a difference for me.

**Comment by ghost** [comment]
Just as a note, a friend of mine ran into a similar issue to this today using qTox in Windows. (Only for him, not for the rest of us in the group audio call.) He's not a particularly computer-savvy fellow, so I don't know if I can get him to help much in regards to debugging, but this may be something worth looking into.

**Comment by agilob** [comment]
> Audio filtering does not make a difference for me.

It doesn't work for me too, I thought it's because of my alsa/PA config, but if someone else reports it, then implementation might be buggy.

Opening new issue for this #1565

**Comment by Aralun** [comment]
Fixed with latest update for me. Driver: Conexant SmartAudio HD

**Comment by tux3** [comment]
There were some changes in libfilteraudio, that's probably what fixed it.
