### ISSUE TITLE
qTox doesn't display duplicate groupchat peer names properly

### ISSUE THREAD

**Issue by tsdko** [qTox/qTox#1563]
1 peer named 牀:
![](http://a.pomf.se/wfrquo.png)
2 peers named 牀:
![](http://a.pomf.se/hzxilu.png)
3 peers named 牀:
![](http://a.pomf.se/afxbmm.png)
After one of the 牀 peers left (my name still set to 牀, 2 peers named 牀):
![](http://a.pomf.se/mmfmoz.png)

**Comment by zetok** [comment]
#2013 should partially tackle this issue by adding side view of groupchat peers. Sadly (as of now) it still keeps broken view, and what's worse, it uses it as default one.

**Comment by sudden6** [comment]
Not reproducible on master, closing.
