### ISSUE TITLE
Audio filter doesn't work for all users

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#1565]
I use alsa and PA, changing audio filter to on/off doesn't make an difference. Tested with users and echobot.

@TGiFallen has the same problem on Windows 7.

**Comment by zetok** [comment]
Things most likely should have changed with new versions of filter_audio, testing again may be needed.

**Comment by rugk** [comment]
Duplicate of #2504?

**Comment by agilob** [comment]
No, 2504 is duplicate of this issue, look at dates ;D
