### ISSUE TITLE
Save Groups (persistent groupchats)

### ISSUE THREAD

**Issue by CryptoSiD** [qTox/qTox#1567]
When I close qtox and reopen it all groups I was in dissapear
Having an option to save groups would be cool

**Comment by apprb** [comment]
This feature currently is under development in the toxcore.

**Comment by g4jc** [comment]
I checked upstream and couldn't find the original upstream bug report. Can someone link it here for reference?

I usually group chat with some friends and if someone gets disconnected we have to make a new room everytime and manually re-invite people etc.

**Comment by ProMcTagonist** [comment]
New groupchats will have this feature. 

I don't think there's a PR on the core repo yet for the development fork.

**Comment by zetok** [comment]
> Can someone link it here for reference?

https://github.com/JFreegman/toxcore/tree/new_groupchats

**Comment by CryptoSiD** [comment]
Any eta on this? just reinstalled qTox, it's sure getting better, but still everytime I restart it my groups are all gone

**Comment by Zer0-One** [comment]
@CryptoSiD the functionality for this is going to be merged into toxcore any week now.

**Comment by zetok** [comment]
@Zer0-One do new groupchats even have TCP support, not to mention A/V?

**Comment by fmvin** [comment]
Do you have any updates or plans regarding this long-playing issue? 

It's strange that this basic and important feature for messengers waits to be released about 1 year.

**Comment by g4jc** [comment]
@fmvin it requires changes to toxcore (not qTox). So it's taking some time. You can track the issue here: https://github.com/irungentoo/toxcore/issues/1514

**Comment by zetok** [comment]
Hmm, looks like this issue is a duplicate of #896, thus closing.
