### ISSUE TITLE
libfilteraudio not found in the bootstrap

### ISSUE THREAD

**Issue by Jookia** [qTox/qTox#1568]
Solved by running this from the 'libs' directory:

cp libfilteraudio.so.0.0.0 lib/libfilteraudio.so

**Comment by Jookia** [comment]
Also requires linking lib/libfilteraudio.so to lib/libfilteraudio.so.0

**Comment by Ilya87** [comment]
Does this issue also about
`qtox/libs/lib//libfilteraudio.so: undefined reference to `run_filter_zam'
qtox/libs/lib//libfilteraudio.so: undefined reference to `run_saturator_zam'
qtox/libs/lib//libfilteraudio.so: undefined reference to `init_highpass_filter_zam'`
When linking qTox?

**Comment by suhr** [comment]
Is this still an issue?

**Comment by Jookia** [comment]
On Fri, Aug 21, 2015 at 12:41:30AM -0700, Сухарик wrote:

> Is this still an issue?

Nope, seems to be fixed as of afb355e6 !
