### ISSUE TITLE
On my Kubuntu 15.04 file dialogs are not responsive

### ISSUE THREAD

**Issue by guedressel** [qTox/qTox#1569]
Just upgraded to Kubuntu 15.04 and started qTox the first time.
When I want to export/import a profile or want to set the avatar image the file dialogs open, but are not responsive.
I've to kill qTox and restart it to get rid of those dialog windows.

Version: 1.0-1523

**Comment by wtermini** [comment]
I can confirm this issue on kubuntu 15.04

**Comment by gdressel** [comment]
Just read in the KDE Frameworks 5.10 Release notes something about file dialog. Maybe related?

https://www.kde.org/announcements/kde-frameworks-5.10.0.php
... section "Frameworkintegration"

**Comment by zetok** [comment]
Is this still a problem on newest qTox binaries?

**Comment by ProMcTagonist** [comment]
I've had qTox unpredictably (~10% of the time?) hang and need to be killed after opening the file send dialog OR the avatar selection dialog. I'm not on KDE.

**Comment by zetok** [comment]
qTox now doesn't use native file picker, but the Qt one, so the bug should be fixed.

Could someone test?

**Comment by Diadlo** [comment]
Needed info not provided for over a month, thus closing.
