### ISSUE TITLE
Settings Screen doesn't support high DPI fonts

### ISSUE THREAD

**Issue by guedressel** [qTox/qTox#1570]
When I run my KDE 5 on high dpi fonts setting (120 DPI) the dropdown fields in the settings form are not in shape.

Version: 1.0-1523

Good at 96 DPI:
![kde_96dpi_fonts](https://cloud.githubusercontent.com/assets/1841616/7446286/b91173f2-f1d3-11e4-8f47-937ce00f016e.png)

Bad at 120 DPI:
![kde_120dpi_fonts](https://cloud.githubusercontent.com/assets/1841616/7446285/b90d79b4-f1d3-11e4-9fa6-77e21a1565c6.png)

**Comment by agilob** [comment]
Some people are still opposing compiling qTox with Qt5.1+

**Comment by stqism** [comment]
@agilob You mean 5.2+, qTox doesn't compile with 5.1 and 5.2 is required to work on a lot of well supported recent versions of Ubuntu/etc.

**Comment by mpxc** [comment]
This should do it: https://github.com/tux3/qTox/pull/1576

**Comment by tux3** [comment]
Fixed by #1576
