### ISSUE TITLE
Bug qtox,receiving file unexpected

### ISSUE THREAD

**Issue by Gradom** [qTox/qTox#1571]
![cattura](https://cloud.githubusercontent.com/assets/11159541/7446670/d4934c56-f1e0-11e4-8ae9-c74c18ff049e.JPG)
Hello,are 2 days in which when i launch qtox,i receive a file from a contact, and the only info i see is the size:4GiB; so I try to write to the contact who appears online, but the message is not sent. Qtox run on windows home premium 64bit

**Comment by bitchecker** [comment]
from other side of chat, I receive the same message repeatedly, also if i try to reconnect or restart qtox, always if @TheBlackPanther  is connected!

**Comment by agilob** [comment]
Update qTox to new version 1.0. This happens because you're using old API version.

**Comment by bitchecker** [comment]
@agilob i've update this morning!
( fedora 21 with XFCE )

**Comment by agilob** [comment]
You both need to update, @TheBlackPanther your turn now.

**Comment by Gradom** [comment]
ok i try now to update..thanks @agilob

**Comment by Gradom** [comment]
it seems to work after the update..thanks a lot :)
