### ISSUE TITLE
Faux offline messaging checkbox is covered by groupchats one

### ISSUE THREAD

**Issue by mpxc** [qTox/qTox#1578]
This is what it looks like when I build fresh copy from the master:

![chat-config-runtime](https://cloud.githubusercontent.com/assets/9732486/7452852/0f8d8e70-f263-11e4-90fe-6172eb2d0521.png)

This is a screenshot from QT creator:

![chat-config-devel](https://cloud.githubusercontent.com/assets/9732486/7452869/377387d2-f263-11e4-930d-a655bca6eabb.png)

Moving it one place to the right takes it into the chatSpacer:

![chat-config-devel-moved](https://cloud.githubusercontent.com/assets/9732486/7452903/9873a58a-f263-11e4-8b58-ef9514244a5f.png)

Perhaps it should go below all of the others? Like so:

![chat-config-devel-moved-proper](https://cloud.githubusercontent.com/assets/9732486/7452923/e0d4f252-f263-11e4-8f3d-a4fbb1d1484a.png)

**Comment by tux3** [comment]
Either below all the others, or in a horizontal layout like (show window/focus window/play sound) should work.

**Comment by TheLastProject** [comment]
Personally, I'd say "simply remove the groupchat checkbox", as I've argued before: https://github.com/tux3/qTox/pull/1371#issuecomment-78497008

**Comment by tux3** [comment]
Fixed by #1579
