### ISSUE TITLE
Flood of online/offline status changes

### ISSUE THREAD

**Issue by unfa** [qTox/qTox#1580]
Sometimes I recieve massive amounts of online/offline status changes from my IM pals on qTox.

**Comment by agilob** [comment]
It's most probably fault of their/your connection. qTox prints what toxcore signals.

**Comment by ProMcTagonist** [comment]
I get this too, any time I'm online for any decent length of time. This will be alleviated when toxcore is able to adjust itself to detected connection speeds.

**Comment by tux3** [comment]
A low-pass filter on top of what toxcore tells us should fix that in the meantime.
I.e. only acknowledge what toxcore says if it hasn't changed its mind in the last ~1s.

**Comment by zetok** [comment]
> A low-pass filter on top of what toxcore tells us should fix that in the meantime.
> I.e. only acknowledge what toxcore says if it hasn't changed its mind in the last ~1s.

Um, it probably would be better to make that ~5-10s.

**Comment by sudden6** [comment]
Not a problem in recent builds.
