### ISSUE TITLE
qTox doesn't get build on OX 10.10.3 with Qt 5.4.1

### ISSUE THREAD

**Issue by tucnak** [qTox/qTox#1582]
I followed all your instructions from `INSTALL.md` and fetched prebuilt things to the root of repository, but unfortunely, my build has failed at some point: https://gist.github.com/tucnak/a4bbbcf1fe7fd330de89

Dunno anything about your CI service, but this thing didn't hit the ground here anyway.

**Comment by tux3** [comment]
It seems that you have an outdated toxcore version, please make sure you have the latest version (with the new API) and compile qTox again.

**Comment by tucnak** [comment]
Am I right that you guys don't keep your prebuilt libs up to date?

**Comment by tux3** [comment]
@tucnak
Unfortunately I'm not really up to date on how the OS X build process works. 
I have always hated the idea of those prebuilt libs and knew they'd break eventually, but I'm not the OS X expert. I suppose they are outdated.

In the meantime I'd recommend trying to get the dependencies manually if you know how to, or download a binary if you'd rather trade some control for convenience.

You can try asking @stqism here or on the Tox IRC channels for more info.

**Comment by tucnak** [comment]
Alright, seems legit. Prebuilt stuff = evil. Alright, can you please tell me which particular library do I need to compile&install here? libtoxcore, huh?

**Comment by tux3** [comment]
As described in the table at the top of https://github.com/tux3/qTox/blob/master/INSTALL.md you'll need libtoxcore, Qt, OpenCV, OpenAL, libfilteraudio and libqrencode.

We tend to be on the cutting edge side of things, so you'll want a recent version of all of those.
