### ISSUE TITLE
Hover over label text almost invisible / tooltip unreadable

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1583]
I have found that when hovering over text which makes a yellow label appear with some sort of a description, that I am not able to see the text in the label because it is white on a light yellow background.

Here is an example of what I mean:
![white_on_yellow](https://cloud.githubusercontent.com/assets/11575271/7480784/fa834870-f362-11e4-987d-3d77d44fea6b.png)

**Comment by agilob** [comment]
This is wired. Font in tooltip is white and background is white. Are other tooltips (users status) visible? I can't reproduce it.

**Comment by ghost** [comment]
@agilob Well, actually the background is very light yellow, and the font is white, never the less, it is still barely readable, well I can't read it anyway. It happens with most of the tooltips in the settings, and a bit around other places too, but not in all, for instance if you hover over your profile picture or the little buttons at the bottom left, you get white on black which is as they all should be.

**Comment by vessd** [comment]
![2015-05-18 14 13 54](https://cloud.githubusercontent.com/assets/8783865/7679786/c82968b8-fd68-11e4-853e-77141055b115.png)
![_2015-05-18_14-15-15](https://cloud.githubusercontent.com/assets/8783865/7679791/cd14ad38-fd68-11e4-8dd2-6623cd97f60a.png)
![_2015-05-18_14-14-29](https://cloud.githubusercontent.com/assets/8783865/7679793/d12cfd30-fd68-11e4-8090-b8f24ac2a9ba.png)

**Comment by zetok** [comment]
What OS/DE? Is it still reproducible on newest builds?

**Comment by vessd** [comment]
Archlinux current
Xfce 4.12 (greybird 1.6.1)
qt5-base 5.5.0
qtox-git r3372.7b3ddff-1 (pkg from aur)
![_2015-08-29_11-23-17](https://cloud.githubusercontent.com/assets/8783865/9561112/e288fdbc-4e40-11e5-8347-4bbdb3592f57.png)

**Comment by vessd** [comment]
@agilob maybe you have some ideas about this issue?
I do not have this problem with the binary version (Jenkins builds).

**Comment by agilob** [comment]
I'll be making 3rd approach to styling soon.

**Comment by zetok** [comment]
Is it still reproducible on newest qTox?

**Comment by ghost** [comment]
No, I am unable to reproduce it on the latest version.
