### ISSUE TITLE
Avatar cashing

### ISSUE THREAD

**Issue by Agundur** [qTox/qTox#1584]
qTox uses

getAvatarHash(friendAddr) == QByteArray((char*)fname, fnameLen) 

to check for cashed avatars.
uTox on the other hand sending avatars without name ... which results un the same hash for all avatars.

**Comment by PKEv** [comment]
@Agundur 
ie the uTox no stores hash?

**Comment by agilob** [comment]
I would assume it doesnt use name for hash but content of the image.

**Comment by tux3** [comment]
This should be fixed now
