### ISSUE TITLE
Crash on changing profile

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1585]
I have got my local data files in qTox encrypted so it asks me for a password when I launch it. But if I click "Change Profile", it completely crashes and forces me to force quit it.

This is what I mean by the "Change Profile" button area (for privacy and security reasons I have put a black box over part of my name of my Tox profile):

![qtox_password_prompt](https://cloud.githubusercontent.com/assets/11575271/7520207/f2d98762-f4dc-11e4-9059-5d19579bb899.png)

**Comment by tux3** [comment]
@SeventhSonOfASeventhSon  could you post the qtox.log (redacted if needed) and a backtrace if possible?

It'd help a lot trying to determine what exactly is crashing.

**Comment by SeventhSonOfASeventhSon** [comment]
@tux3 This is the relevant part of the log file:

14:47:51 IPC: postEvent  "activate" to 0 
14:47:52 IPC: Previous owner timed out, taking ownership 13713034225440917639 -> 10653342045010877113 
14:47:53 Nexus: Starting up 
14:47:53 Core: loading Tox from "/home/arthur-dent/.config/tox/qTox User - Paranoid Panda.tox" 
14:47:53 Audio:  "Trying to open output Built-in Audio Analogue Stereo" 
14:47:54 Audio: Opening audio output  "Built-in Audio Analogue Stereo" 
14:47:54 Audio:  "Trying to open input Built-in Audio Analogue Stereo" 
14:47:54 Audio: Opening audio input  "Built-in Audio Analogue Stereo" 
14:47:57 Core: Starting up 
14:47:57 SystemTrayIcon: Using Unity backend 
14:47:57 Core::loadConfiguration: reading from  "/home/arthur-dent/.config/tox/qTox User - Paranoid Panda.tox" 
14:48:05 Settings: Saving in  "/home/arthur-dent/.config/tox/qtox.ini" 
14:48:05 Settings: Loading from  "/home/arthur-dent/.config/tox/qtox.ini" 
14:48:05 Core::loadConfiguration: reading from  "/home/arthur-dent/.config/tox/qTox User - Paranoid Panda.tox"

**Comment by ghost** [comment]
@tux This is the relevant part of the log file (I have replaced part of my profile name qTox with "|user|" and my username for my computer with "|username|"):

14:47:51 IPC: postEvent  "activate" to 0 
14:47:52 IPC: Previous owner timed out, taking ownership 13713034225440917639 -> 10653342045010877113 
14:47:53 Nexus: Starting up 
14:47:53 Core: loading Tox from "/home/|username|/.config/tox/qTox User - |user|.tox" 
14:47:53 Audio:  "Trying to open output Built-in Audio Analogue Stereo" 
14:47:54 Audio: Opening audio output  "Built-in Audio Analogue Stereo" 
14:47:54 Audio:  "Trying to open input Built-in Audio Analogue Stereo" 
14:47:54 Audio: Opening audio input  "Built-in Audio Analogue Stereo" 
14:47:57 Core: Starting up 
14:47:57 SystemTrayIcon: Using Unity backend 
14:47:57 Core::loadConfiguration: reading from  "/home/|username|/.config/tox/qTox User - |user|.tox" 
14:48:05 Settings: Saving in  "/home/|username|/.config/tox/qtox.ini" 
14:48:05 Settings: Loading from  "/home/|username|/.config/tox/qtox.ini" 
14:48:05 Core::loadConfiguration: reading from  "/home/|username|/.config/tox/qTox User - |user|.tox"

**Comment by tux3** [comment]
@SeventhSonOfASeventhSon well, unfortunately that doesn't tell me much.

Do you know how to generate a backtrace?

**Comment by ghost** [comment]
@tux3 No, I do not know how to generate a backtrace, but if you provide me with a guide, or instructions, I am sure that I will be able to do so.

**Comment by zetok** [comment]
@SeventhSonOfASeventhSon https://github.com/tux3/qTox/wiki/Useful-bug-reports

**Comment by ghost** [comment]
@zetok Thank your for the link. @tux3 As soon as I started looking at the link, sod's law, it stopped crashing! So now I can't seem to reproduce the issue! Which is sort of a good thing if it has gone for good and maybe was linked to the state my system was in at the time or something.
