### ISSUE TITLE
regression - hidden user profile

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#1586]
So far a few friends asked me why was user profile peference removed.
It's hidden under avatar, not really user-friendly.

**Comment by tux3** [comment]
I agree that it's not really obvious where the profile settings are hidden, I've seen several confused people too.

It was the consensus at the time and does free up some space in the "main" settings, but I'd love to see new ideas for where we could put it, or how we could improve that situation.

**Comment by zetok** [comment]
@agilob if you have a better solution than reverting to old, broken way, it would be nice to hear about it..

**Comment by agilob** [comment]
what was wrong with the old version?

**Comment by zetok** [comment]
@agilob #1012, #1328

**Comment by agilob** [comment]
#1012  There's no way to quickly get own Tox ID #1012 

Is that easier now? Nope. #1328 is PR that introduced that regression.

**Comment by zetok** [comment]
It is easier and quicker to get Tox ID now

**Comment by zetok** [comment]
@agilob can it be closed now?

**Comment by zetok** [comment]
> @agilob can it be closed now?

Since no response for over than month, closing.

**Comment by ProMcTagonist** [comment]
No need to reopen unless other people comment too. I'd just like to say that if it continues to be a problem, what if clicking on the profile picture simply navigated to the (re-added) Profile settings tab?
