### ISSUE TITLE
osx build

### ISSUE THREAD

**Issue by cjpit** [qTox/qTox#1589]
Hi there is there any news on when osx will start building? 99% of my contacts have upgraded to the new api, but mac users are really stuck since there is no other client available, and it hasn't built since last month (with the old api I think)

**Comment by stqism** [comment]
Where do you get any of your information from? This has been incorrect since the day we announced we pushed the new API clients.

The post: https://blog.tox.im/2015/04/27/new-api-gsoc-2015/#more
Downloads for OS X: https://wiki.tox.im/Binaries#OS_X

**Comment by cjpit** [comment]
I usually direct people to the github page, which has incorrect links for OSX.  I then scoured the jenkins repositories trying to find a build that would work.  It can be confusing at times knowing where is the "correct" place to get it from

Thanks

**Comment by tux3** [comment]
I updated the link on the GitHub page to match the one on tox.im
