### ISSUE TITLE
Wrong colors on friendlist with a scrollbar

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#159]
https://img.bi/#/NRWqmSj!PjnEPKuUCwCHib90XbzdlbehOGU2rajhm2LHZzcc

**Comment by F1ynn** [comment]
This has something to do with leaveEvent() not firing, haven't been able to track it down yet though.

**Comment by zetok** [comment]
I don't see that issue anymore, is anyone still affected by it?

**Comment by tux3** [comment]
I haven't seen this bug in forever, I'm pretty sure it's fixed. As usual, post here if you still have this bug and I'll reopen.
