### ISSUE TITLE
Win32 receive messages error

### ISSUE THREAD

**Issue by sataevr** [qTox/qTox#1592]
Receiving messages is broken in all builds for win32 since 618. Sender get permanent loader (like contact is offline), recipient of the message get it every ~15 seconds with random character at the beginning.

Same problem in 32bit Ubuntu too.

**Comment by zetok** [comment]
you're using outdated qTox, you should update to new version

**Comment by tux3** [comment]
As zetok said, you and your contacts just need to update your clients and the problem will go away.
