### ISSUE TITLE
No way to quit without logging in or ending/killing qTox process

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1596]
I have found, very annoyingly, that if I launch qTox, and then I want to quit out of it, unless I log in (because I have enabled local data encryption so it prompts me for a password when I launch it), I am unable to. So for instance on these windows the little "x" does nothing but close the window and then instantly open it again, and if there is a Cancel button, then it does the same thing:

![qTox Password Prompt](https://cloud.githubusercontent.com/assets/11575271/7550490/a1d0b8a0-f65c-11e4-90d0-43796edb0b9d.png)

![qTox Choose a profile dialog](https://cloud.githubusercontent.com/assets/11575271/7550504/ec5dc9bc-f65c-11e4-9ad9-28e2e1e632dc.png)

And if I click on the qTox icon in the notifications area it just launches a non logged in version of the main window (which also does not want to quit), and the "Quit" button in the icon's pull-down menu also has no impact on anything. The only way I have found to quit out of is to either log in with the correct details, or End/Kill the qTox process.

**Comment by linux-modder** [comment]
This sounds normal for a crypted store of logs as the log / chat store is  semi detached when not actively used / accessed...  also check for close /minimize to tray  settings in advanced are they enabled try again without them if they are.

**Comment by ghost** [comment]
@linux-modder I have checked my settings and they are not enabled. But whatever sounds normal, if a Cancel button is provided and a Quit button and a little red cross, then surely they should actually do something and not just tease?

**Comment by jaceq** [comment]
I think this is a duplicate of my ticket: https://github.com/tux3/qTox/issues/1562
