### ISSUE TITLE
RAM consumption increases with 10mb each time a screenshot is taken

### ISSUE THREAD

**Issue by alexbakker** [qTox/qTox#1597]
I'm using Windows, and the title really says it all.
Each time I click on the screenshot button and take a screenshot or 'Esc' out, the ram consumption of qTox increases by 10mb.

**Comment by linux-modder** [comment]
How big of a increase over previous versions is this ? (not a win user )
how long is the increase?   a few secs is normal with most applications as the screenshooting and saving to a defined folder does require a minimal overhead.   Is this  creating any other artifacts/effects to the native system or just an acute observation?
Lastly  what versions of  qTox & windows are in play?

**Comment by alexbakker** [comment]
Here's a quote from the guy I'm posting this for:

```
<qTox> win 7 64 bit, last version of qTox
<qTox> it does not seem temporary
<qTox> it increases limitlessly
```

**Comment by linux-modder** [comment]
can he confirm  qtox 1.0.1.x   for us ?

Corey W Sheldon
Freelance IT Consultant, Multi-Discipline Tutor
(p) 310.909.7672
G+: https://www.plus.google.com/+CoreySheldon
LinkedIn: https://www.linkedin.com/profile/view?id=70127804
Github: https://www.github.com/linux-modder
Facebook: https://www.facebook.com/corey.sheldon
Several Communities on Stack Exchange https://www.stackexchange.com

http://www.facebook.com/1stclassmobileshine

Tutoring in person or via any of the following platforms:
HackHands https://www.hackhands.com
Wizpert https://www.wizperts.com
FieldNation https://www.fieldnation.com
AirPair https://www.airpair.com
Truelancer http://www.truelancer.com

## {PayPal,Google Wallet/Play store, Apple Pay}

pub  3072D/718BF597
http://pgp.mit.edu/pks/lookup?op=get&search=0xE958C5D6718BF597 2014-12-08
      Key fingerprint = 2930 99EB 083D D332 0752 88C4 E958 C5D6 718B F597

## uid     Corey Sheldon (Fedora Key) sheldon.corey@gmail.com

**Comment by tux3** [comment]
I'm not sure whether or not this is a bug.

Screenshots are sent as file transfers, and we keep a copy of image files in memory so you can preview them when you mouse over the file transfer widget. I could easily see that reach 10MB if you have a high screen resolution.

**Comment by tux3** [comment]
I fixed some memory leaks in the screenshotting code, so I believe this is fixed, but there will still be some extra memory usage with the file transfer thumbnails, by design.
