### ISSUE TITLE
qTox apparently crashing on OSX.

### ISSUE THREAD

**Issue by irungentoo** [qTox/qTox#1598]
https://www.reddit.com/r/projecttox/comments/35e84z/qtox_on_mac_1085_unexpected_error_crash_after/

**Comment by tucnak** [comment]
This report is absolutely useless without any data to investigate. Can't confirm any crashes on startup.

**Comment by cjpit** [comment]
#1635 Same issue I would suspect.

**Comment by tux3** [comment]
This should be fixed in this build: https://wiki.tox.im/OS_X#1.1.19b
