### ISSUE TITLE
Shortcuts in message inputbox problem

### ISSUE THREAD

**Issue by qwad1000** [qTox/qTox#1600]
Description: The problem is I can't use ctrl+c, ctrl+v, ctrl+z and other shortcuts in text box for new messages. 
This problem occurs while I'am using keyboard layout with non-latin letters (for example ukrainian or russian).

Info:
OS: Linux (Kubuntu 14.04 32bit)
Reproducible: Always while using russian or ukrainian keyboard layout.

Steps to reproduce:
1. switch to ru/uk keyboard layout
2. try to paste(for example) text in message input box using shortcut (ctrl+v)

What happened:
'м' letter would be printed

What should happen:
your clipboard text must be pasted.

**Comment by tux3** [comment]
Does this only happen with qTox? Do you know if you have any other Qt based applications to try if it works?

**Comment by qwad1000** [comment]
can't remember any problems with my applications. but most of my apps works on qt 4.8.x (as i'm using kde 4).
note that problem is only in input boxes. i still can copy messages from chat log(for examble) without any problem using any of mine keyboard layout.

UPD: one i remember with qt 5 version. qt creator 3.3 and 3.4 works perfectly in any of keyboard layouts

**Comment by qwad1000** [comment]
I've tested some example applications that comes with Qt 5.4 bundle. There is no problem with them.

**Comment by tux3** [comment]
Ok, then that's an upstream problem. we can keep this issue open until all builds are on Qt 5.4 or if we find a workaround in the meantime.

**Comment by zetok** [comment]
> I've tested some example applications that comes with Qt 5.4 bundle. There is no problem with them.

Currently available builds use Qt 5.5 and 5.4.2, could you check whether it works for you?

**Comment by zetok** [comment]
No answer, assuming that it was fixed, thus closing.
