### ISSUE TITLE
Improve debug output

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#1601]
Currently all that goes to stdout or stderr is some scattered code.
There should be some consistent and formatted output.

I hereby volunteer to implement something better and propose the following format:

```
[timestamp]  path/to/sourcefile:linenumber : errormessage
```

where [timestamp] is in the format: hh:mm:ss.sss

**Comment by tux3** [comment]
I agree with the timestamp, although path/to/sourcefile:linenumber is probably not needed.

We already have some issues with log files getting pretty big since they are currently never deleted, so let's try to not make them bigger.
Some pointless debug messages could be removed, while we're at it.

But thanks, that's a good idea.

**Comment by sudden6** [comment]
Maybe only sourcefile:linenumber is enough? personally I think it's important to know the exact location where the error happened, because if there are duplicate error texts you don't know exactly where the error happened, also it makes searching in the source much easier.

Maybe we should solve the problem of big log files with different debug levels? Or by obviously deleting logfiles sometime...

**Comment by tux3** [comment]
> Maybe only sourcefile:linenumber is enough? personally I think it's important to know the exact location where the error happened, because if there are duplicate error texts you don't know exactly where the error happened, also it makes searching in the source much easier.

Sure, why not.

> Maybe we should solve the problem of big log files with different debug levels? Or by obviously deleting logfiles sometime...

Yes you're right, big log files is a different problem, we can solve that later.

If you want to make a PR, feel free. Otherwise I'll probably implement that later.

**Comment by sudden6** [comment]
I'll work on it, just give me some time ;)
