### ISSUE TITLE
OSX: crash on audio call start

### ISSUE THREAD

**Issue by soredake** [qTox/qTox#1609]
https://gist.github.com/fenque/b1c2c5df987c29066419

**Comment by tux3** [comment]
Well, it's a crash in `toxav_prepare_transmission`, that doesn't seem to be a bug with the qTox code.

Can you reproduce the bug every time? If so, how?

**Comment by tucnak** [comment]
Unfortunately, can't reproduce this. You must've got some outdated libraries or related. I am going to write down the proper workflow for OSX and do some packaging ASAP, by the end of this week, so just hold on.

**Comment by soredake** [comment]
@tux3 
1) Accept call 
2) Crash

**Comment by tux3** [comment]
That crash on start seems to say opencv was built/packaged wrong.

As for the crash when accepting a call, I haven't been able to repro yet but thanks for reporting it.

**Comment by stqism** [comment]
@fenque This might have been fixed, please download the latest and let me know.

If it still crashes shoot your crash report to sean@tox.im asap and I'll setup what I need to in order to reproduce it before the next patch level version release.

**Comment by fenque** [comment]
@stqism I will wait for the binaries, thanks
