### ISSUE TITLE
Keep the log files gzipped

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#1615]
To drive the size down, they can get pretty huge currently.

Since all the log entries are just copies of other lines with a timestamp, this should be pretty effective.

The logs still need to be copy-pastable for bug reports, so we could base64 the gzip'd data.
That's probably easier than creating a proper .gz file w/ header/trailer and asking people to unzip that.

**Comment by sudden6** [comment]
what about putting it in a .zip? everybody could unpack that

**Comment by suhr** [comment]
Everybody can unpack gzip too.

**Comment by tux3** [comment]
On second though I agree that the .zip file is probably better. Gratuitous base64 would probably just confuse people.

**Comment by agilob** [comment]
Why not just keep last 20 files?

**Comment by tucnak** [comment]
Gzip is great, but would it be _that_ effective? Can you please get a huge log file and attempt to compress it with gzip. Imo, if we get at least 3x compression, it's worth implementing.

**Comment by tux3** [comment]
@tucnak I'm pretty sure it'll be that effective. Let's try.
I ran `gzip -9 qtox.log`, it took a second.

qtox.log.gz (https://a.pomf.se/gtvdcf.gz) is 438kB (448275 bytes)
qtox.log is 95MB (98885320 bytes).

That's a 220x smaller file.
Granted, part of those 95MB are probably some debug spam inflating the results, but I invite you to try with your own log file and see what you get. I expect it'll be much better than 3x.

**Comment by tucnak** [comment]
God damn, now I just look silly. Did you just say 220x? I am all in!

**Comment by tux3** [comment]
Well, at least now we have a number. It's always good to test things :)

**Comment by tux3** [comment]
@agilob 
There's only one file, so we need to keep the last X lines or last X kB.
If we truncate on exit, if you never exit qTox the log file can get pretty big. But if we truncate every time you add a new log entry, it's slow and may trash the OS cache and disk.

I think we should do both eventually. Truncate the log file on exit so it's never more than let's say 500kB after compression (that's a _lot_ of logs), and even if you leave qTox open for several weeks since it's zipped it won't get really huge anyways.

It's very cheap and pretty effective to just zip the log, so I think it's a good thing.

**Comment by sudden6** [comment]
Or just keep the last 2 days (or some other timespan) of logs?

**Comment by tux3** [comment]
That's more expensive, we'd have to scan and parse the logs, then truncate.

**Comment by ghost** [comment]
@tucnak Text compresses extraordinarily well, especially well there's (near-)duplicate text such as in a log.

@tux3 Given how computationally cheap zlib is, I think it's a good idea.

Even with 33% overhead via base64, a lot of space would be saved.
