### ISSUE TITLE
qTox not showing in the "Programs and Features" view

### ISSUE THREAD

**Issue by mikalehmann** [qTox/qTox#1620]
On Windows there is the Programs and Features view, where the user can see every installed program. I just installed it and it doesn't show up in there. Is this intended?
For me this view is quite useful, because I get an overview over my programs and can uninstall the ones I don't need anymore. qTox should be in there.

**Comment by tux3** [comment]
It's supposed to show up, if it doesn't that's a bug with the installer.

Can I ask where you downloaded qTox, if you remember seeing the installer, and what version of Windows you have?

**Comment by mikalehmann** [comment]
I think it was https://wiki.tox.im/Binaries, but it could have been the github page, too.
I'm running Windows 8.1 64bit.

**Comment by tux3** [comment]
Thanks, I should be able to fix the installer sometime this week.

**Comment by tux3** [comment]
This should be fixed.
