### ISSUE TITLE
Option to choose a speaker for ringing

### ISSUE THREAD

**Issue by mikalehmann** [qTox/qTox#1622]
Skype has the option that you can choose a different speaker for the ringtone.

**Comment by tux3** [comment]
Do you mean sending the audio for actual calls and the audio for just the ringtone to different speakers/sound cards?

**Comment by mikalehmann** [comment]
Yes. For example, I'm hearing the audio for the call with my headset, but the ringtone gets played by my speakers, in case I'm currently not at the PC. I wouldn't hear the ringtone if it was played by my headset.

**Comment by antis81** [comment]
Duplicate of #2459 -> closing
