### ISSUE TITLE
qTox keeps sending the same message over and over

### ISSUE THREAD

**Issue by d33tah** [qTox/qTox#1626]
`Built: 14:44:57 May 11 2015` from Debian repo

After sending a multi-line message with a few lines starting with ">" (quotes), my girlfriend ended up constantly receiving three last messages I tried to send and on my end they show up undelivered. Screenshot from her end attached.

![zrzut ekranu z 2015-05-11 22 23 00](https://cloud.githubusercontent.com/assets/295322/7574386/3a16aa58-f82d-11e4-8283-4c5454da2dbf.png)

**Comment by tux3** [comment]
Either you or your girlfriend are using a client that is on the old toxcore API.

Please make absolutely sure everyone has an up to date client.

If this is still a problem with the new API, please leave a comment.

**Comment by agilob** [comment]
Your friend needs to update qtox.
