### ISSUE TITLE
Sending ghost files and receiving duplicate messages

### ISSUE THREAD

**Issue by OldMike** [qTox/qTox#1633]
Hello,

Thanks for the hard work.
I have 2 issues:
- Friends report they are receiving 4GB files from me but I don't see anything on my side,
- I sometimes receive multiple duplicates messages. The only way to get rid of it is to remove him from the contacts...
  I already removed/installed it many times, importing my existing profile.

mike@desktop ~ $ apt-show-versions qtox
qtox:amd64/nightly 1.0-1642 uptodate

On his side
![selection_373](https://cloud.githubusercontent.com/assets/2414768/7585008/0d770f9a-f8a2-11e4-999a-e982f182899b.png)

On mine
![selection_372](https://cloud.githubusercontent.com/assets/2414768/7584920/541cd9d0-f8a1-11e4-944d-fb344078cfb7.png)

**Comment by agilob** [comment]
you both need to update qtox to latest version.

**Comment by OldMike** [comment]
Thanks but this mate uses Antox. And I thought I was already uptodate. I used the Linux packages.

**Comment by tux3** [comment]
@OldMike Your version is up to date, but your friend's Antox client is still on the old API and needs to be updated. The old versions and the new versions aren't compatible, by design.

**Comment by agilob** [comment]
@tux3 are you sure? I don't have that problem with Antox from their f-droid repo. https://repo.tox.im/android/

**Comment by tux3** [comment]
@agilob I'm sure that the problem is caused by an old API client talking to a new API client, but I haven't followed what Antox has been doing.

What I know is that this isn't a bug in qTox, so I can't really fix that.
