### ISSUE TITLE
mac osx install

### ISSUE THREAD

**Issue by cjpit** [qTox/qTox#1635]
is missing the png shared library by default in the zip package - hence not working for new users.  Had to manually add to the .app framework folder from a previous version to get it to work..

**Comment by cjpit** [comment]
libpng16.16.dylib

**Comment by tux3** [comment]
Thanks for the report.

@stqism

**Comment by tux3** [comment]
@cjpit this should be fixed in this build: https://wiki.tox.im/OS_X#1.1.19b
