### ISSUE TITLE
Contact "notes"?

### ISSUE THREAD

**Issue by tr37ion** [qTox/qTox#1636]
I would like to suggest adding a small notes input box for contacts. Here you can add some notes on each contact for better remembering them later on. Especially with many pseudonym contacts it will be nice keeping some small notes on each contact somewhere.

**Comment by agilob** [comment]
It's very easy to implement, just follow 'alias' implementation.
Question is, do we really need this? I don't know any IM that supprts that.

**Comment by tux3** [comment]
I'm not convinced we need this. This seems like feature creep to me.

**Comment by tr37ion** [comment]
Well, if you don't store chat history this could be helpful to leave some small notes, too. Just a little undefined space for personal use.

**Comment by TheLastProject** [comment]
Could you explain why the current alias system isn't good enough? Using "Mike@School" or so as alias should work well enough as note.

**Comment by tr37ion** [comment]
I see, you want an example. To be honest, I think there is no _universal example_ of how people would use an added _notes_ field. Its the nature of notes, that people use them like they think they are helpful to them.
Just one more field would not compromise the software imho. Let the people decide, if and how they use it. And who knows, if you can later filter/search the note's content, people may use it for things I can't imagine.

**Comment by zetok** [comment]
> Could you explain why the current alias system isn't good enough? Using "Mike@School" or so as alias should work well enough as note.

Because it's a goddamn **alias**. If you have to work with tons of people, what do you do when you have 2 Mikes? 5? 10? Perhaps 3 of them are from same school? Are you going to call them like `Mike the third` ? And how exactly does that help in telling you who the guy is? Or how much other info can you stuff in 128 character limited alias? Oh, and that comfort of editing this 1-lined field - who could even imagine something better…

For people who deal with a lot of people note feature is a **must**.

> It's very easy to implement, just follow 'alias' implementation.

I wonder though, aren't aliases saved in plain, unencrypted text file?

**Comment by Zer0-One** [comment]
@zetok I'm thinking of adding something that lets you view someone's username history, so that you can track their username changes over time (to avoid the confusion of not knowing who half of your contacts are). Would a feature like that supersede this "notes" feature you're talking about?

**Comment by ProMcTagonist** [comment]
@zetok 

> I wonder though, aren't aliases saved in plain, unencrypted text file?

Awful if true. Good thing I don't use them because you still can't see aliases and users' chosen display names at the same time.

@Zer0-One 

Like in Steam? A dropdown next to their name at the top of the chatform?

**Comment by Zer0-One** [comment]
@ProMcTagonist I could do that. My original thought was to add a context menu option when you click on a user's friend widget that opens up a dialog box with a list of previous usernames.

**Comment by ProMcTagonist** [comment]
@Zer0-One That sounds much more accessible if you're checking many very quickly, which is the most likely use case aside from curiosity or idle fiddling.  +1

EDIT: sorry for drifting off-topic

**Comment by tr37ion** [comment]
@ProMcTagonist @Zer0-One:
Adding an "username history" feature is appreciated. On the other side, please don't let us shift the topic of this proposal. It's about a user editable **notes input field**.

**Comment by zetok** [comment]
> @zetok I'm thinking of adding something that lets you view someone's username history, so that you can track their username changes over time (to avoid the confusion of not knowing who half of your contacts are). Would a feature like that supersede this "notes" feature you're talking about?

@Zer0-One nope, although alias / nick history would be nice to have too (no idea how steam does it though, so…)

**Comment by Zer0-One** [comment]
I'd have to disagree with this being a viable feature. Like @tux3 said, it seems like feature creep.

**Comment by tr37ion** [comment]
@Zer0-One To me naming this "feature creep" is kind of a political term. We already gave some viable arguments why this is helpful. Just because some of you don't need notes doesn't mean others don't, too.

Even looking at it from a developers perspective. One single string variable is way easier to implement and maintain, than adding more and more data entries for eg. "phone, mail, website, skills, projects, tag, ...". 

**Why think so complicated?** It is just one single openly usable string ... Not implementing something like Notes is limiting user's creativity on how to organize contacts themselves. 

It is on you, if you want to limit and dictate users on how they have to use qtox, then we can close this issue here. If you think, people should have more freedom in how they can use qtox and organize themselves, then just add this single string variable.

Btw. Steam is lacking notes in contact list, too. But each contact has a full blown website to provide massive information on each Steam user.

**Comment by ovalseven8** [comment]
Is done.
