### ISSUE TITLE
Dark theme?

### ISSUE THREAD

**Issue by tr37ion** [qTox/qTox#1639]
How can I change the default theme of qtox to something like this?

![qTox dark theme mockup](https://cloud.githubusercontent.com/assets/1538617/7608408/9bf888ee-f969-11e4-8fc1-9cebc98f28e0.png)

**Comment by agilob** [comment]
You can't. That's not even a screenshot.

**Comment by tr37ion** [comment]
> You can't. That's not even a screenshot.

So, I can't change it to a dark theme because I took it from https://tox.im/ as a base for my mockup?

Is it planned to make qtox themable then?
Which source file holds the current color settings?

**Comment by agilob** [comment]
> Is it planned to make qtox themable then?
> Which source file holds the current color settings?

https://github.com/tux3/qTox/pull/1640 
Here this PR provides support for more themes, but it's not ready yet.

Before  Support for user-created skins #1641, my PR must be fully tested and cleaned-up. It will take some time.

That picture you posted it a mockup made in Photoshop or GIMP. it's not a screenshot of existing implementation.

**Comment by tr37ion** [comment]
> #1640
> Here this PR provides support for more themes, but it's not ready yet.

Wow, this looks promising :) Is this qt-theming like qtconfig-qt4 offers?

> Before Support for user-created skins #1641, my PR must be fully tested and cleaned-up. It will take some time.

Sure, take your time. I was just thinking that I may did something wrong or missed something to let qtox look like my other qt applications.

> That picture you posted it a mockup made in Photoshop or GIMP. it's not a screenshot of existing implementation.

Yes, it was just a quick&dirty mockup by taking the one from https://tox.im/ and switch it to dark. I thought, this would be good enough to show what I was looking for. If you need a real one, I can do it if you want.

**Comment by agilob** [comment]
> If you need a real one, I can do it if you want.

I'm bad at CSS so if you know how to improve dark themes in my PR, just do it.

**Comment by tr37ion** [comment]
I cloned your repo and try to run your fork with qtcreator, but I get this:
![Compile error](https://cloud.githubusercontent.com/assets/1538617/7622888/343522e2-f9d4-11e4-9c26-203577db3d2a.png)

**Comment by agilob** [comment]
You tried compiling wrong branch, change branch to "more_themes" `git checkout more_themes`, than `make clean && make -j4`

**Comment by zetok** [comment]
Thanks to @fcore117 from #2478:

# 

Please add simple dark mode to chat window, something like this i dirty improvised with paint filling color.
![capture](https://cloud.githubusercontent.com/assets/1313813/10761377/c39a322e-7cc9-11e5-86ab-9a50747d3009.jpg)

**Comment by fcore117** [comment]
Lets hope creating simple color themes without adding any cost to memory usage or cpu will come.

**Comment by UralZima** [comment]
+1. black bg on contact list and black on message window.

**Comment by UralZima** [comment]
Anything on this? I am still on Toxic because no dark mode in qTox exists

**Comment by Diadlo** [comment]
@UralZima No. Feel free to create it
Currently it's low-priority qTox issue

**Comment by dataphreak1001** [comment]
You would think after 2 years, they'd have made the themes editable by css.

**Comment by sudden6** [comment]
@dataphreak1001 the themes are editable by CSS, you just have to recompile qTox afterwards.

**Comment by tox-user** [comment]
I guess the proper solution would be to allow making theme packs that can be changed without compiling.

**Comment by sudden6** [comment]
One solution could be, if we created a folder e.g. `~/config/qTox/css/` where you can put your own css that overwrites the existing one. Still not a high priority for me to work on.

**Comment by Diadlo** [comment]
AFAIK Qt allow to use custom style to any application with `--style` parameter without recompile

**Comment by tr37ion** [comment]
Is it really that difficult to just switch the background color of one existing theme to #222222 and Text color to #DDDDDD eg.? I opened the issue 2015 and I wonder what might be the issue that changing two color values is that complicated. I possibly miss something ...

**Comment by Chiitoo** [comment]
tr37ion,

Looking at the previous issues, and/or pull requests concerning this, I think no one just wanted to slap something quick together, but actually create a proper theme implementation.

You can always try doing it yourself if you'd like to see what it takes.  :]

I did, though I've only changed the colours of the buttons and things like that, and they're still very much hard-coded.

In the end, I feel the only reason for there being no dark theme still, as an option by default, is that no people with the desire to make it happen (without higher priorities taking their time already) have come around after the previous attempts (which unfortunately didn't get enough attention and get merged).

**Comment by sudden6** [comment]
@tr37ion it's not the problem to add another theme and change the color values, but to make sure the color and is applied in the correct places.

The styling in qTox seems pretty fragmented, with some parts using https://github.com/qTox/qTox/blob/master/src/widget/style.cpp and some applying CSS directly.

EDIT: The styling seems to be in a forgotten corner of the qTox code, I think all the devs that developed it aren't active anymore.

**Comment by tr37ion** [comment]
@sudden6 and @Chiitoo yes, there must be something else stopping a dev implementing this. Maybe it was my fault pasting a mock-up in the first place, which might gave the impression a complete new theme was desired.

Actually, I just thought one theme with an inverted chat room colourization might just do it. Therefore, I thought if devs know where to change those two colours (background-color and font color) it would be an easy 2minute task. I didn't expect it to be that difficult as it seems to be now.

**Comment by pizdjuk** [comment]
Please, do something with dark theme. Because using if qtox in a MATEBlack is impossible, while the fontcolor of chatwindow (where I write) is quite invisible and I dont know where to change it

**Comment by sudden6** [comment]
On master there's now an unofficial way to change the theme:

1. Get the files from https://github.com/qTox/qTox/tree/master/themes/default they are the default theme
2. Copy them to `~/.local/share/qTox/themes/default/`
3. Edit as you wish, restart qTox to apply

We are looking for someone to write a dark theme before creating the user interface for this.

**Comment by dhsdshdhk** [comment]
@sudden6, I can't seem to change the white background in the chat text area, as shown [here](https://cloud.githubusercontent.com/assets/2544251/7608773/931c17e0-f964-11e4-98b1-a3b289f2ed58.png). Is that defined by the css files or by style.cpp?

**Comment by sudden6** [comment]
@dhsdshdhk It seems that some colors are selected by a function in `style.cpp`. IMO this should be converted to a CSS file too. Would make theming a lot easier.

**Comment by dhsdshdhk** [comment]
In case anyone else wants it, I applied [these](https://github.com/tox-user/qTox/commit/c15626030ee6d97585dd3b5777ce521a918c190c) changes to master and got the dark text background I was looking for. The theme is not well adjusted yet, but I'll edit it to make a good match.

**Comment by sudden6** [comment]
Dark theme is done by #5558
