### ISSUE TITLE
Portable mode doesn't work

### ISSUE THREAD

**Issue by jsmith000** [qTox/qTox#1642]
Hello there,

The Portable mode doesn't work on the latest build (Winx64).

Even though I choose Portable mode it won't be checked after a restart although under bin/qtox.ini MakeToxPortable is true.

And of course it also creates the AppData folder when you run it again and it doesn't load the file under bin folder.

Thanks!

**Comment by photonometric** [comment]
mmm isn't this pretty much the same issue as #1883? Portability seems to be working on the newest builds, except for avatars not carrying over ^^

**Comment by zetok** [comment]
Right, if it works, then I'm closing this issue.

A separate issue should be should be opened for avatar potability.
