### ISSUE TITLE
qtox.exe using 28% of my CPU even though it's not open

### ISSUE THREAD

**Issue by mikalehmann** [qTox/qTox#1643]
I used qTox today, but closed it afterwards. I can still see it in the task manager. Is this the updater or did it just fail to close properly?

**Comment by mikalehmann** [comment]
So, I just opened qTox again and it told me that my profile is already in use. It seems the other instance just failed to close.

**Comment by towlie** [comment]
I can confirm this on windows. It sometimes happens here.

**Comment by agilob** [comment]
This is related to problem on linux where qtox prevents logout. https://github.com/tux3/qTox/issues/1485

**Comment by Diadlo** [comment]
Problem may be fixed in 6b00779. Please, test

**Comment by Diadlo** [comment]
No answer in month. Then close
