### ISSUE TITLE
The standard microphone sensitivity seems too low

### ISSUE THREAD

**Issue by mikalehmann** [qTox/qTox#1646]
I just called somebody for the first time, and we could barely hear each other. The microphone sensitivity was at maximum. On Skype the current setting works, but on qTox apparently not.

**Comment by agilob** [comment]
Linux/Windows?
Was audio filter on?

Try adding `echobot@toxme.se` and trying your settings.

**Comment by mikalehmann** [comment]
Windows, audio filter was off. What exactly does the filter do?
I'll give the echobot a call.

**Comment by mikalehmann** [comment]
Just turned filter audio on, and it seems to be louder now. I'll test it with the other person to confirm this.

**Comment by agilob** [comment]
You can test it with echobot before ;)
It repeats what you said with ~1s delay

**Comment by mikalehmann** [comment]
I did it. I still have to confirm that the person I called has the right volume with the audio filter on.

**Comment by agilob** [comment]
@xur86x bump?

**Comment by mikalehmann** [comment]
I'm going to close this, it seems to be working with the audio filter.
