### ISSUE TITLE
qTox opens all sent screenshots after reboot.

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#1648]
I sent ~20 screenshots yesterday to a few people (including tux3), today when I turned on my OS qtox (which is in KDE autostart) opened me all sent screnshots in separate windows.

I can't find those screenshots anywhere, they're not in my user folder, and they're not in .config/tox/

I happened twice today.

**Comment by agilob** [comment]
This was added to my start scripts:

![filetransfer2](https://cloud.githubusercontent.com/assets/2544251/7636003/04344b6c-fa5c-11e4-8d16-1ff08a94a779.png)

**Comment by tux3** [comment]
Do you have a default-download location set for file transfers in qTox?
Maybe it's downloading files in a place your OS thinks is for startup scripts?

**Comment by agilob** [comment]
I sent those pictures, I didn't download them.

**Comment by tux3** [comment]
Ok. The thing is that IIRC the current screenshot code saves the screenshots to a local folder when they are taken so that it can then create a file sender.
That's a bit silly, I think we should make it so the screenshots never hit the disk in the first place, that'd also solve this problem.

**Comment by zetok** [comment]
> local folder

Why this is not documented anywhere?

**Comment by tux3** [comment]
@zetok Because I somehow missed it until very recently. 

It's a stupid workaround for a poor internal interface (file sending requiring actual files) that should never have been added and will be removed as soon as possible.

**Comment by agilob** [comment]
> the screenshots never hit the disk in the first place

I think it should be saved until file transfer is in progress. File should be removed after successfully finishing the transfer.

It happened again, the file was saved in `/home/agilob/.kde4/Autostart` -.-'

**Comment by tux3** [comment]
@agilob There's really no reason to keep it on disk if we're going to remove it at the end of the transfer. We don't have broken file transfer resuming anyways, so that just adds more complexity.

**Comment by sudden6** [comment]
but won't we get broken file transfer resuming in the future?
How will we solve this with offline messaging?

**Comment by tux3** [comment]
> but won't we get broken file transfer resuming in the future?

Eventually, but that's not a priority. The current priority is fixing bugs and getting the video (GUI and backend) in good shape. Will all the TODOs we have, I think it's better to get this fixed and focus on something more pressing.

> How will we solve this with offline messaging?

It's not clear yet how offline messaging will be implemented and how long it will take, we can adapt to that in due time.

**Comment by agilob** [comment]
>  but won't we get broken file transfer resuming in the future?
> 
> Eventually, but that's not a priority.

I started refactoring of file transfers tab as I personally find it important (P1/P2). This is a "mockup", it works, but 1/2 of values are hardcoded. Styles for the table are defined in my awaiting PR. Currently it shows only started and finished transfers and their state (finished/error). I'm planning adding a progress bar for each entry, storing file transfers in a database, so also restarting transfer, resuming and clearing the table.

![qtox1](https://cloud.githubusercontent.com/assets/2544251/7654662/b4ec0b2e-fb16-11e4-9876-124d09210905.png)

**Comment by tux3** [comment]
@agilob That's pretty neat. 

I'm a bit worried about the file transfer database though. 
For each profile we alreay have:
- A toxcore data save file
- A qTox preference file
- A chat history database file
- A cache of friend's avatars
- And now a file transfer DB?

That's not a good situation, especially if we want to support encrypted profiles (we can't just encrypt half the important files and leave the rest out there! Which we currently do!).

It'd be cleaner to keep that user data in a single file instead of scattered all over the place. And of course we still want our toxcore save file to be compatible with other clients.
And on that note here's a new issue :  #1656

**Comment by agilob** [comment]
I can't reproduce on KDE5 and no one else reported it so closing.
