### ISSUE TITLE
New screenshot hover is unintuitive (clicking on thumbnail should open preview)

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#1649]
When holding your mouse over the screenshot feature, it switches to "clickable" state. This is very confusing, as actually clicking the image does nothing.

Either #1608 should be reverted or, even better, clicking the small image preview should open the image in the default image viewer (just like the "open" button on the right top).

**Comment by agilob** [comment]
I couldn't find any more appropriate cursor that would be available on Windows/Linux/OSX. 

http://doc.qt.io/qt-5/qt.html#CursorShape-enum

**Comment by zetok** [comment]
@agilob question is, why does cursor needs to be changed? I.e. why does popup needs to be intuitive?

**Comment by agilob** [comment]
Because no one would ever found it when the preview shows after 1-3second after hovering it?

**Comment by zetok** [comment]
Why anyone _needs_ to find it?

**Comment by agilob** [comment]
Ymm... I think so, how else people would know about it?
I had to explain two friends how to get that preview for transmitted image, they both said it's very user-unfriendly and suggested changing at least cursor.

**Comment by zetok** [comment]
@agilob 

> Ymm... I think so, how else people would know about it?

I still don't get why people _have to know_ about it  `:/`

> I had to explain two friends how to get that preview for transmitted image, they both said it's very user-unfriendly and suggested changing at least cursor.

I see. It would have been nice if you did include that info in your commit message for this change.

@TheLastProject so it would seem that adding `click_to_display` thumbnail is the only proper solution?

**Comment by agilob** [comment]
> I see. It would have been nice if you did include that info in your commit message for this change.

It was included in a discussion about the commit. It's enough for me and apparently it was enough for others. Wake up earlier next time ;)

> I still don't get why people have to know about it 

Should I remove that option since people don't have to know it's there, so they also won't use it?

**Comment by TheLastProject** [comment]
@zetok Yes, I feel making the thumbnail click-to-open is the only sane solution if we're keeping this mouse pointer. For mouseover events, the pointer is simply incorrect (the default pointer should be used, see Firefox for example), it should only be used for clickable things. Making the thumbnail clickable seems to satisfy both sides of the argument, as it'll make the tooltip more discoverable with the pointer, and still use it for its intended purpose.

**Comment by ProMcTagonist** [comment]
@TheLastProject +1

**Comment by zetok** [comment]
> Either #1608 should be reverted or, even better, clicking the small image preview should open the image in the default image viewer (just like the "open" button on the right top).

Clicking on thumbnail now opens image, thus closing.
