### ISSUE TITLE
retuxx's commit fails to compile

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#165]
https://gist.github.com/dubslow/17cfc17f16d30535580d

**Comment by dubslow** [comment]
It would seem I have 5.1 installed, not 5.2, since that's what was in Debian testing at the time of LMDE 16 import. I guess the docs should be updated to require 5.2, not just 5.

**Comment by tux3** [comment]
What docs are you talking about ?

The readme says

> <h3>Compiling</h3>
> 
> Compiling toxgui requires Qt 5.2 with the Qt Multimedia module and a C++11 compatible compiler. It also requires the toxcore and toxav libraries.

**Comment by dubslow** [comment]
Oh.

Well up till this point I guess I assumed that I did in fact have 5.2, since everything worked... obviously that was not the case. Sorry about the bother.

At least now qtox _actually_ requires 5.2 :P
