### ISSUE TITLE
not started without audio output

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#1651]
Windows 7 x64
then i disabled my audio output device
from log file:
[20:44:41.708] src/profilelocker.cpp:56 : Debug: clearAllLocks: Wiping out all lock files
[20:44:41.708] src/nexus.cpp:45 : Debug: Starting up
[20:44:41.708] src/widget/widget.cpp:245 : Debug: Loaded translation "ru"
[20:44:41.708] src/widget/widget.cpp:257 : Debug: System translation not loaded "ru"
[20:44:41.709] src/core/core.cpp:58 : Debug: loading Tox from "C:/Users/xxx/AppData/Roaming/tox/xxx.tox"
[20:44:41.709] src/audio.cpp:177 : Debug: "Trying to open output

this bug tested on "hp probook 4540s"

**Comment by tux3** [comment]
What is the bug? qTox always tries to find an audio output by default.

**Comment by PKEv** [comment]
yes, 
but in this case, it can't find it and terminate process qtox. 
With disabled audio output i can't start qtox.

**Comment by tux3** [comment]
So, if you disable your audio device in Windows, qTox can't start? What happens, does it freeze? Does it crash?

I have no idea what the bug you're having is.

**Comment by PKEv** [comment]
So, if you disable your audio device in Windows, qTox can't start?
yes, log file in 1st message 
process qtox terminate in moment "[20:44:41.709] src/audio.cpp:177 : Debug: "Trying to open output...."

**Comment by tux3** [comment]
Alright, thanks.

**Comment by antis81** [comment]
Closing -> Issue is outdated and no longer valid. @PKEv Feel free to reopen, if you still experience this problem.

**Comment by zetok** [comment]
> @PKEv Feel free to reopen, if you still experience this problem.

@antis81 um, just a note: when one doesn't have write access to repo on github, they can't reopen issue closed by one of maintainers.

**Comment by antis81** [comment]
Ok, thanks. Forgot about that. So… @PKEv If this is still an issue for you, feel free to comment and I will reopen. :)
