### ISSUE TITLE
Default smiley pack 'Twitter EmojiSVG' default size for 120 dpi displays

### ISSUE THREAD

**Issue by An-dy** [qTox/qTox#1652]
Hello,
thank you for this great IM program.
I'm using qtox 1.0-1661 on Linux Mint LMDE 2. 
xrandr: Screen 0:  LVDS1 connected 1280x800   (261mm x 163mm display) = about 120 dpi

Some issues and proposals.
The default size (16 point) of the default smiley pack 'Twitter EmojiSVG' is way to small for 120 dpi. See screen shoot:
![tox emo](https://cloud.githubusercontent.com/assets/12451368/7642661/ff4be728-fae6-11e4-860b-fbae391efeb5.png)
22 to 24 points size would be more appropriate as default size for 120 dpi displays.

**Comment by agilob** [comment]
We're not getting HDPI support quickly, so you can change pixel size of emoticons in settings for now...

![groups2](https://cloud.githubusercontent.com/assets/2544251/7642849/3c623492-fa8c-11e4-8e68-ab0a6666a1d2.png)

**Comment by zetok** [comment]
Due to changes, max size of emoticons is being dynamically calculated based on environment.

I think that the same could be done on the first launch (when there's no profile) for "default" size of emoticons..?

@PKEv ↑ ?

**Comment by PKEv** [comment]
Use large icons when you first start it seems to me not very logical - can scare the user

To install the LARGE icons is only possible if the correct compiler options 
(Qt :: AA_UseHighDpiPixmaps) is set.

**Comment by Getron** [comment]
I'm on Fedora 22 KDE x64 Linux to, but, the default size is 16px (not optimaly or dynamicaly calculated for my 32'' monitor with 2560x1600px).

I think, the 32pix is the optimal view. It fit exaclty on the dark square (or place, where the icons are showed), and it is not to big to scare anyone, but not to small to unrecognize what is what, on big screens.

Try it. I think, the 32px should be the default size on client, not the 16px.

With 32px the smileys looks great, on every screen.

Here an example:
![auswahl_063](https://cloud.githubusercontent.com/assets/5913218/9850474/1f76afc6-5af3-11e5-9a2e-7972fd08125c.png)

**Comment by zetok** [comment]
Is this still an issue on newest qTox?

**Comment by Diadlo** [comment]
Needed info not provided for over a month, thus closing.
