### ISSUE TITLE
Gather all user data in a single file, so we can encrypt and keep track of it

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#1656]
For each profile we currently have:
- A toxcore data save file
- A qTox preference file
- A chat history database file
- A cache of friend's avatars
- And possibly a file transfer DB soon?

That's not a good situation, especially if we want to support encrypted profiles (we can't just encrypt half the important files and leave the rest out there! Which we currently do!).

It'd be cleaner to keep that user data in a single file instead of scattered all over the place. And of course we still want our toxcore save file to be compatible with other clients.

**Comment by agilob** [comment]
Ymm I wanted to add new table in chat history DB. Just one table with 4 or 5 columns. There is already some code for that. Is there any disadvantage of keeping it in one table? 
I see four advantages:
1. file transfer history and chat is encrypted/unencrypted at once
2. less underlying code/classes
3. one database
4. did I say 4?

**Comment by tux3** [comment]
@agilob Where would you store e.g. the screenshots that are in transfer but broken, as a BLOB in the DB?

**Comment by agilob** [comment]
In the same place where profiles are `.config/tox/`+`transfers/`. Screenshot will be removed after transfer is finished successfully.

**Comment by tux3** [comment]
There's still the problem of encryption, then. We have all those files (screenshot, avatar caches, the qtox settings, etc) that sit around unencrypted.

A potential advantage of centralizing the user data in one place and enforcing that is that with this design we could do some sandboxing later on: only allow qTox to write to the current user's data file, and not touch anything else on disk, for security. That's not going to happen in the short term or any time soon, but if we start with the right design I think it'd help. At least with keeping all of a user's profile encrypted, at first.

**Comment by ghost** [comment]
Just a theoretical idea: If you want to encrypt multiple files, why not make a database which includes a list of all files and some random encryption keys for these files and only encrypt this database with the user passphrase?

**Comment by tux3** [comment]
@blobgo That's a way to do it, but it would make the code pretty complicated.

**Comment by zetok** [comment]
It's a bad idea, given that data will be corrupted. AFAICT, when you store more data in one file, chances of data being corrupted increase, along with size of file + depending on FS they may increase further in case where file is being often used (one file for everything is going to be used often).

When you put all that data in 1 encrypted file, wouldn't just one corrupted bit make file unreadable and impossible to recover by normal means?

I mean, as long as user data wouldn't be at stake, I would like idea of stuff being in one file…

> And possibly a file transfer DB soon

Why not store in already existing "history" DB? Which should be rather a "contact DB", where you would store all relevant to contact stuff - alias, history, file transfers (which are IMHO part of history), notes about contact, status changes, when contact went online/offline, etc.. ?

**Comment by tux3** [comment]
> It's a bad idea, given that data will be corrupted. AFAICT, when you store more data in one file, chances of data being corrupted increase

Not really, no. In principle if you consider that bit flips happen at random over the surface of a disk, then technically many files will have more associated FS-level metadata, so slightly more chance of breaking. On the other hand that'd depend on the format but a bit flip in an archive would only corrupt that file in the archive, unless you hit the header (unlikely).
All in all it changes nothing. It's a tradeoff for something extremely unlikely, and both cases are good. If your storage flips bits so often that you lose files regularly, you have bigger problems.

> depending on FS they may increase further in case where file is being often used (one file for everything is going to be used often).

There's no difference between one file being used often and many files being used often. We wouln't rewrite the whole archive file for every change, just the part that changed. The same numbers of bytes have to hit the disk. 

> When you put all that data in 1 encrypted file, wouldn't just one corrupted bit make file unreadable and impossible to recover by normal means?

Only the corrupted part would fail to decrypt. We don't want to encrypt all of it at once, but each parts separately with it's own MAC.

> Why not store in already existing "history" DB? Which should be rather a "contact DB", where you would store all relevant to contact stuff - alias, history, file transfers (which are IMHO part of history), notes about contact, status changes, when contact went online/offline, etc.. ?

Agreed.

**Comment by zetok** [comment]
> something extremely unlikely

Sorry, but it's not something extremely unlikely when millions of people will use qTox. It would be a common occurrence, I would say. Thus qTox should do whatever it can to prevent that from happening, and if it's not possible, then at least preserve as much data as possible.

> > When you put all that data in 1 encrypted file, wouldn't just one corrupted bit make file unreadable and impossible to recover by normal means?
> 
> Only the corrupted part would fail to decrypt. We don't want to encrypt all of it at once, but each parts separately with it's own MAC.

Well, it'll be nice if that'll be the case.

**Comment by tux3** [comment]
> Sorry, but it's not something extremely unlikely when millions of people will use qTox. It would be a common occurrence, I would say.

It still is very unlikely. As in, it's overwhelmingly more likely that your computer will just fail to boot if you start having random bit flips. It's good to try to preserve data, but we need to be pragmatic too. 
And the point remain that both cases are about equaly good.

> Well, it'll be nice if that'll be the case.

That's the idea.

**Comment by PKEv** [comment]
@tux3 
What is the structure of the database to store the information you would like to see?

**Comment by ovalseven8** [comment]
> A toxcore data save file

Should be left alone. Toxcore and client settings should definitely be separated.

Basically, the compatibility with other clients is first priority. And import/export should work easy too. All in all, the structure must be clean and easily understandable.

**Comment by tux3** [comment]
Given how poorly the encrypted database has been working out, I'm thinking of going back the other way and using the filesystem to store all our blobs, keeping the database just for chat and file transfer history.

**Comment by sudden6** [comment]
This has become stale and no changes in the file layout are currently planned.
