### ISSUE TITLE
remove libsodium from bootstrap.sh

### ISSUE THREAD

**Issue by msteinbeck** [qTox/qTox#1657]
As far as I can see libsodium is provided by the package manager of Arch, Debian/Ubuntu, Fedora and OpenSUSE. Thus I think we can remove it from the bootstrap script to make it much faster. So my question is: Do we need libsodium in bootstrap.sh for jenkins or any spacial cases?

**Comment by agilob** [comment]
+1, we can probably remove it, debian has 1.0.1, we compile 1.0.3 from sources, there shouldn't be huge difference I guess.

**Comment by sudden6** [comment]
+1 shouldn't make any problems

**Comment by linux-modder** [comment]
+1  for removing  from bootstrap

**Comment by agilob** [comment]
@tux3 is it safe to remove it completely? Will any build system be broken? I mean jenkins or anything?

**Comment by tux3** [comment]
@agilob Jenkins is completely separate, it's always safe to change those scripts.
