### ISSUE TITLE
Have the updater upgrade win32 -> win64 on win64.

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#1658]
32bit toxcore is exceedingly slow, so we'll want to auto-upgrade 32bit installs on 64bit machines to the correct arch.

Similarly, we could ^C^V the updater code into an online installer that automatically pulls the right offline installer for the correct arch.

**Comment by sudden6** [comment]
With newer builds no slowness of 32bit compared to 64bit has been reported.
