### ISSUE TITLE
About window?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1668]
A simple "issue" but I would really like to see an about window (as a part of the existing one-window-style).
So maybe the advanced settings are something like this - there is at least a license.
However I can't see a version number or something like this anywhere... :expressionless:

**Comment by ghost** [comment]
+1
Is a crucial thing to have. Quite often do I need to make sure that my less tech-savvy contacts are using an updated version of qTox, but there's no way to get that info.

Commit hash as "version number" maybe?

**Comment by ghost** [comment]
> Commit hash as "version number" maybe?

Yes I think this would be good as there is actually no real version number of qTox.

**Comment by Zer0-One** [comment]
@blobgo I'll put this together sometime soon. Expect a PR in the next week or so

**Comment by kiug** [comment]
Maybe is good idea to include information about status of version (alpha/beta/stable) in "about window".

**Comment by zetok** [comment]
@kiug yep, good idea :3

**Comment by ghost** [comment]
Besides the proposed idea, what do you think about a chat command that outputs the same information? So, instead of giving the instructions on where to find it, one could simply say "copy and send me this please /qtox-info".

**Comment by zetok** [comment]
@kehugter 

> Besides the proposed idea, what do you think about a chat command that outputs the same information?

no.

**Comment by Zer0-One** [comment]
@kehugter nah, it's not really necessary.

**Comment by zetok** [comment]
![now I know](https://cloud.githubusercontent.com/assets/3148759/8267031/797ddaca-1747-11e5-81a4-5f0fd80804c5.png)

would be good, if not for 1 thing;

why are you linking to some other repo, when qTox wiki has section too for bug reporting?
