### ISSUE TITLE
Encrypting the chat history fails

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1673]
In my case the following fails:
1. Data file password is mset
2. I activate saving of the chat history
3. I activate encrypting of the chat history
4. I click on "use data file password"
5. After this I close qTox and restart it and enter my password.
6. Then it displays an error message that the chat history can't be decrypted and it will be disabled.
"No encrypted chat history file found, or it was corrupted. History will be disabled!"

The same also happens for other tries to encrypt the chat history. (e.g. if I use an independent password).
Please also keep in mind that this is a nearly fresh installation of qTuy - no contacts added, no chat done.
However I can of course add a empty group and write something there, so that the chat history isn't empty.

OS. Windows 7 x64
Log: https://gist.github.com/blobgo/e8f135241dd2b0662954
The important line seems to be this one:

> [21:14:14.948] src/core/coreencryption.cpp:157 : Warning: can't get salt from "C:/Users/<username>/AppData/Roaming/tox/tox_save.qtox_history.encrypted" header

**Comment by agilob** [comment]
@apprb

**Comment by ghost** [comment]
What about this? I cannot reproduce at as the system has changed and the checkboxes I have to click are not there anymore.

However after the update to https://github.com/tux3/qTox/commit/aed6c25fda02c2aadeeb464cc7be2b79723cc641 my whole chat history was lost, but that's not bad. The new chat history is saved correctly.

So should this issue be closed?

**Comment by zetok** [comment]
@blobgo yep, thanks for re-testing.

**Comment by ghost** [comment]
Well.. I could not test it at all, because the checkboxes aren't there... :smile: 

At least I didn't noticed any errors while saving the history so that can be considered testing.
