### ISSUE TITLE
Inconsistent style of popup windows

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1674]
The "popup windows" which are doing only some small stuff (mostly just an edit/text box) are differently styled.
E.g. the "rename profile" window looks like a HTML-designed one while all password input boxes use system styles.

I think this should be generalized to one style.

**Comment by agilob** [comment]
This issue is very small, so I'm fixing it with the same PR as #1671.

**Comment by ghost** [comment]
Okay :smile:

**Comment by ghost** [comment]
Okay, I think this is fixed now.
