### ISSUE TITLE
Delete encrypted chat history - does it work?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1677]
Following steps to reproduce:
1. Enable saving & encrypting of chat history.
2. Click on the checkbox to disable the encryption.
3. Then qTox will disable a question whether you want to delete your chat history or just decrypt it. (nice idea BTW)
4. Click on delete.
5. Then it will be shown as this: (here with encrypted data file)
![afterdeletingchathistory](https://cloud.githubusercontent.com/assets/12105354/7672270/674165ae-fcec-11e4-9ea7-49eb7ec8b003.png)

So this at first means the settings for saving future chat history (unencrypted) is still enabled, so should this "delete" button in fact mean "Yes delete actual chat history, but save later chat history unencrypted, yeah!"? :open_mouth: 
And the second thing is that in the chat window of qTox all the chat history is still displayed.
So this let me doubt whether the chat history is really deleted in this case, but as far as I tested it it is done...

**Comment by agilob** [comment]
Bug: checkbox should be disabled.

> And the second thing is that in the chat window of qTox all the chat history is still displayed.

Ctrl+shift+l to clear chat log (visible messages, doesn't delete from DB). I think change in settings should NOT impact view (chats) automatically.

**Comment by linux-modder** [comment]
Shouldn't a reload AFTER this clear those "Displayed" messsages ?

Or is the OP indicating a desire to not require this reload?

**Comment by ghost** [comment]
@linux-modder
What? What should reload or not?

**Comment by ghost** [comment]
As new versions of qTox save the chat history automatically encrypted when a password is set and some of the original checkboxes disappeared what about this issue?
Can be consider it solved? (I mean the question shouldn't be displayed at all anymore I assume)

**Comment by zetok** [comment]
@blobgo If you feel that issue was fixed, close the issue `:)`

**Comment by ghost** [comment]
Well... I'm not quite sure, but I think so.
