### ISSUE TITLE
Seach string look bad

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#1681]
when filtering friends, string look bad in moment when selecting group
![default](https://cloud.githubusercontent.com/assets/6053197/7686946/3b5520be-fda2-11e4-9d9b-03e5219659ed.png)
![2](https://cloud.githubusercontent.com/assets/6053197/7686947/4218dc2e-fda2-11e4-99f3-c8f7ab26d2f0.png)

**Comment by agilob** [comment]
This was reported to me on priv. Could you download and compile my this branch https://github.com/tux3/qTox/pull/1640 and test if comoboboxes look 'normally' in there? I tested current CSS on kde, gnome with different colours and themes and it was fine. Do you use Windows?

This should look like this:
![qtox](https://cloud.githubusercontent.com/assets/2544251/7687055/540ea2c0-fd92-11e4-9964-dfc6df62d5e8.png)

**Comment by PKEv** [comment]
yes, i use windows.
i can't compile now, sorry...

**Comment by agilob** [comment]
Ok, so it looks like this is windows-specific.

**Comment by PKEv** [comment]
Cursor in string "nospam" look bad too
![default](https://cloud.githubusercontent.com/assets/6053197/7687866/fb6be4cc-fda8-11e4-8ef2-5999bce71edd.png)

**Comment by agilob** [comment]
That's how input mask for hexadecimal looks like on your system.

**Comment by ProMcTagonist** [comment]
@agilob It's a special field that only lets you type hex? I don't see why that requires a weird cursor. Upstream decision?

**Comment by agilob** [comment]
> It's a special field that only lets you type hex?

Yes, that field doesn't have any cursor settings or hints. Upstream? Yes, MS decided about it. I think qTox should not override cursors, it would be too easy to break something.
