### ISSUE TITLE
"Rounded-corners" avatars look bad with a lot of avatars

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1685]
Description: E.g. black-ish avatars have white lines around them, when they're shown in contact list.

Info:
OS: Hardened Gentoo Linux x86_64

Reproducible: Always

Steps to reproduce:
1. Set black avatar, (e.g. the one from link)
2. It's shown with white lines around it in contact list.

What happened:
Black-ish avatar has white lines around it when shown in contact list.

What should happen:
Black-ish avatar shouldn't have white lines around itself.

Additional info:
![white stuff](https://cloud.githubusercontent.com/assets/3148759/7715316/30fab61a-fe7e-11e4-85df-b2ca067d48ed.png)
![more of it](https://cloud.githubusercontent.com/assets/3148759/7715341/7e61a33c-fe7e-11e4-8900-0593782c690d.png)

Black-ish image (quite big, you may want to not open it with your browser, but get it with wget): [universe.jpg](https://a.pomf.se/xzdvrq.jpg)

**Comment by zetok** [comment]
I think that avatars should not have rounded corners, or they should be better implemented - which is better?

**Comment by Jeeppler** [comment]
@zetok the rounded corners look ugly in combination with the layout of qTox. Another approach could be to use circles like Firefox OS or Google does it.

**Comment by agilob** [comment]
> like Firefox OS or Google does it.

oh god, no pls

**Comment by ProMcTagonist** [comment]
White lines are obviously a bug, and not at all inherent to having rounded avatar corners. That should be fixed.

**Comment by zetok** [comment]
White lines seems to have been fixed and there is no apparent interest in the pointy corners, so I'm closing the issue.

![spectacle lh2985](https://cloud.githubusercontent.com/assets/3148759/20913006/09550e4c-bb6c-11e6-8e3e-943f6d4c81ae.png)
![spectacle ex2985](https://cloud.githubusercontent.com/assets/3148759/20913014/21536a02-bb6c-11e6-8df3-f37b2a5c6ee8.png)
