### ISSUE TITLE
Systray icon is not in systray after screen change (KDE, ubuntu 14.04)

### ISSUE THREAD

**Issue by jaceq** [qTox/qTox#1687]
Hi,

I am running qtox on my laptop (Kubuntu 14.04) and when I open qtox everything is fine, then when I will connect second screen and that will get activated qtox icon is the only one that ends up on top left corner of a screen and not in systray again like all the other ones....
Only way to fix this is to restart qtox.
![image](https://cloud.githubusercontent.com/assets/12188427/7721127/bde03680-fed4-11e4-8cc3-b43733365255.png)

**Comment by ProMcTagonist** [comment]
Related?

https://github.com/tux3/qTox/issues/518

https://github.com/tux3/qTox/issues/1150

**Comment by jaceq** [comment]
Similar but not identical, my qtox doesn't close, nor icon does not vanish, it moves to top left corner of a screen.

**Comment by zetok** [comment]
Are [newest qTox builds](https://wiki.tox.chat/binaries#other_linux) also affected?

**Comment by zetok** [comment]
Now there are also `qtox-unity` builds available;
no answer, assuming that it was fixed, thus closing.
