### ISSUE TITLE
prioritisation voting ?

### ISSUE THREAD

**Issue by An-dy** [qTox/qTox#1688]
Can we introduce prioritisation voting ?
I would love to vote for features/bugs that bother me and my peers when we use qtox and utox on a daily base. The most bothering bug is at the moment a reproduce-able program crash when I plug-in my USB-HD cam and change the video resolution. A How-To how to produce the right crash documentation to enable coder nailing down the bug would be great. 

Andy

**Comment by agilob** [comment]
I doubt it, we don't have enough HR.

**Comment by tux3** [comment]
@An-dy feel free to add a comment or some form of +1 in an issue if it's important to you.

I don't think voting would work particularly well and I can't promise anything, but I do look at every comment in every issue.

> A How-To how to produce the right crash documentation to enable coder nailing down the bug would be great. 

There's some information on the wiki : https://github.com/tux3/qTox/wiki/Useful-bug-reports

**Comment by agilob** [comment]
This would work on gitlab where users can vote on issues, github doesn't support that, and we don't have human resources to follow all whishes (you know, we have our wishes for this project too).
