### ISSUE TITLE
[Regression] when copypasting messages nicks are doubled

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1690]
Description: When selecting whole message, nick is copied twice, once before `:`, and once after `:`.

Info:
OS: Hardened Gentoo Linux x86_64
qTox version: 4306f87df4a0825a19b3a2d0cd4e4b99545acf36

Reproducible: Always

Steps to reproduce:
1. Select whole message
2. Copy it, and paste
3. nick is copied twice

What happened:
After copypasting whole message nick is copied twice.

What should happen:
Nick should be copied only once, before `:`

**Comment by TheLastProject** [comment]
I can confirm this:

Screenshot:
![screensho](https://cloud.githubusercontent.com/assets/1885159/7784717/1601ea82-0170-11e5-8433-20001b18b7a6.png)

Copy:

```
[17:20] Sylvie: Test
[17:20] Groupbot: Groupbot Invalid command. Type help for a list of commands
```

**Comment by PKEv** [comment]
Closed
