### ISSUE TITLE
[Regression] crash opening emoticon selector when emoticon size is set to large value

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1691]
Description: When emoticon size is set to large value, qTox crashes. On my system, values in up to `110` are fine, and values above 128 are causing qTox to crash when opening emoticon picker.

Info:
OS: Hardened Gentoo Linux x86_64
qTox version: 4306f87df4a0825a19b3a2d0cd4e4b99545acf36

Reproducible: Always

Steps to reproduce:
1. Go to settings and set emoticon size to `526`
2. Click on friend and click on emoticon picker
3. qTox should crash

What happened:
qTox crashes when trying to open emoticon picker.

What should happen:
qTox should open emoticon picker without crashing.

Additional info:
Backtrace: https://gist.github.com/zetok/b3019df3342a40b5821f

**Comment by agilob** [comment]
can't reproduce with size 526 and with 1526.

we should actually limit size of emoticons in preview to something like `3 * QFont::size()` ?

**Comment by tux3** [comment]
Can't repro either.

**Comment by agilob** [comment]
@tux3 what do you think about my suggestion?

**Comment by tux3** [comment]
@agilob It sounds good to me. QFont::size() does scale up/down with resolution/DPI, right?

**Comment by agilob** [comment]
> "Returns the logical pixel height of characters in the font if shown on the screen."
> 
> Pixel size depends on the resolution of the screen, thus greater resolutions make pixels bigger too. Thanks to this, when you increase the resolution of your display, all texts scale and seem to remain the same size. On the other hand we have a measurement called a point which does not scale with resolution. It can be easily spotted on webpages. If you increase the font size of the webpage and it really increases, then it is probably set in pixels, but if it stays the same, then it is definitely set in points.

[apparently.](http://www.qtforum.org/article/10502/qfont-size.html)

**Comment by PKEv** [comment]
And what is the maximum size of the emoticon can be placed in chatlog?
Maybe at this value and stop?

**Comment by zetok** [comment]
@PKEv wouldn't that hinder UX in some cases with high-DPI screens?

**Comment by PKEv** [comment]
I mean that the size of pictures that can be inserted into chatlog has a limit, and I think that allows users to select the picture even bigger - it mislead him
