### ISSUE TITLE
Updater just crashed

### ISSUE THREAD

**Issue by mikalehmann** [qTox/qTox#1692]
Sadly, I have no idea how to reproduce this bug and why it even happened. I'll reinstall qTox to make sure everything is working. The updater said something about corrupted files.

**Comment by zetok** [comment]
https://github.com/tux3/qTox/wiki/Useful-bug-reports

**Comment by mikalehmann** [comment]
http://puu.sh/i1i0J/08f184fbee.png
Finally got some more information to provide. This didn't pop up the last time.
Platform is Windows 8.1.
qtox.log http://pastebin.com/LA7sT1S1

**Comment by ovalseven8** [comment]
Still an issue with latest qTox?

**Comment by tux3** [comment]
Corrupt files shouldn't be a problem anymore.
