### ISSUE TITLE
qTox saves screenshots in installation dir

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1696]
Tox saves the screenshots (at least on Windows) in it's installation dir. At least on Windows this is not nice.
At least if we set the default installation dir to %programfiles%\qTox as indicated in #1607 this also causes an error message as the %programfiles% dir is only writeable with admin rights.

So instead of using the dir of the qTux exe it should use the temporary dir or the data dir (%appdata%\Tox on Windows).
Or like it Skype does - in the dir the user choose for "autoaccepting" files.

**Comment by agilob** [comment]
related: https://github.com/tux3/qTox/issues/1648 

question: as temporary solution, should it be saved in the same dir as toxprofile or ask OS for `Pictures` directory like it works on android?

**Comment by zetok** [comment]
> as temporary solution, should it be saved in the same dir as toxprofile

yep, in
`~/.config/tox/screenshots`
