### ISSUE TITLE
Certificates are sent multiple times / long text issue

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1697]
Description:
Often certificates are sent multiple times when pasting them (one time) into the input box and send them.

Info:
OS: Windows 7

Reproducible: Always (if you use the same certificate)

Steps to reproduce:
1. Choose a certificate from the list below or one of your choice
2. Send it using qTox to a contact.

What happened: Often the text is sent multiple times.

What should happen: Send the text one time.

Notes:
- it doesn't happen in an empty group chat

Additional info:
I've tried this with various certificates, also different types, and found no relation - expect that all ones were certificates.

| Name of certificate | Type/Encoding | times sent | Link or info how to get the certificate |
| --- | --- | --- | --- |
|  |  |  | **StartSSL** |
| StartSSL Interm. .crt | DER | 2 times | http://www.startssl.com/certs/sub.class1.client.ca.crt |
| StartSSL Interm. .pem | PEM/Base64 | 3 times | http://www.startssl.com/certs/sub.class1.client.ca.pem |
| StartSSL Interm. .pem (only Base64 part) | Base64 | 2 times | use http://www.startssl.com/certs/sub.class1.client.ca.pem |
| StartSSL Root (?) .cer | DER | 2 times | http://www.startssl.com/certs/ca.cer |
|  |  |  | **Other SSL certificates** |
| github.com certificate | PEM | 3 times | export the cert from an SSL connection to github.com |
|  |  |  | **Some PGP keys** |
| PGP pub key | PEM/Base64 (?) | 7 times | https://keyserver.pgp.com/vkd/DeliverSigningKey.event?rep=4 |
| PGP pub key (only Base64 part) | Base64 | 1 time [OK] | use https://keyserver.pgp.com/vkd/DeliverSigningKey.event?rep=4 |
|  |  |  | **Self-created test PGP Key** |
| PGP pub key | PGP/Base64 | 1 time [OK] | https://gist.github.com/blobgo/1feeee75c5044bc1bb34 |
| PGP priv key | PGP/Base64 | 3 times | https://gist.github.com/blobgo/8ae717b8c695203bbc1b |
| PGP priv key | DEM | 2 times | https://gist.github.com/blobgo/ba68aa3a6aeb84a90369 |
|  |  |  | **qTox Code Signing (Windows 64bit EXE - commit: e25baaa90e09318097e0f6a550f8171f04cd3299)** |
| qTox Code Signing | PEM/Base64 | 2 times | https://gist.github.com/blobgo/dee3f4fa0a11e36aefe0#file-base64-cer |
| qTox Code Signing | DER | 2 times | https://gist.github.com/blobgo/dee3f4fa0a11e36aefe0#file-der-cer |
| qTox Code Signing | P7B | 6 times | https://gist.github.com/blobgo/dee3f4fa0a11e36aefe0#file-qutoxcert-p7b |
|  |  |  | **Other tests** |
| Base64 test | Base64 | 1 time [OK] | https://gist.github.com/blobgo/1c136e7a1612beb62cc2 |
| long text | text | 4 times | https://gist.github.com/blobgo/88e80d9c956953b6c5e2 |

**Comment by agilob** [comment]
Do you mean, when you send a file .pem or content of the file (really long message)?

**Comment by ghost** [comment]
The content of the file.

**Comment by agilob** [comment]
This is known issue, it happens not only with certificates, but with any long message.

**Comment by ghost** [comment]
Okay, maybe the cause is the long text. I've tried [one](https://gist.github.com/blobgo/88e80d9c956953b6c5e2)...

**Comment by ghost** [comment]
Ahh okay I see. So that was the cause...

**Comment by tux3** [comment]
Does that happen with uTox?

**Comment by zetok** [comment]
hmm, looks like duplicate of #1375 (look at screenshots) ?

**Comment by agilob** [comment]
duplicate of https://github.com/tux3/qTox/issues/1703

**Comment by zetok** [comment]
@agilob um, no. If something, #1703 is a duplicate of this issue

**Comment by PKEv** [comment]
closed

**Comment by ghost** [comment]
Okay, it seems it was resolved in https://github.com/tux3/qTox/pull/1738.
