### ISSUE TITLE
Multiple-monitor issues with screenshot feature

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1698]
Description: If I click on the screenshot button on my secondary monitor is just displayed a white screen. (Other things which happen below)

Info:
OS: Windows 7

Reproducible: Always

Steps to reproduce:
1. Plug in a second monitor
2. Click on the screenshot button [1]
3. Choose a part of the screen and send it
3a. Choose a part which includes a part of your secondary monitor and a part of your primary monitor [2]
3b. Choose a part only of your secondary monitor [3]

What happened:
[1] blank (white) screen on my secondary monitor
[2] the image will be clipped so that only the part of your primary monitor is visible
[3] a fullscreen screenshot of your primary monitor will be sent

What should happen: just send the screenshot correctly and don't display a white screen on the secondary monitor

**Comment by agilob** [comment]
Duplicate: https://github.com/tux3/qTox/issues/1595 

I'll try to reproduce it on linux and fix if I can...

**Comment by PKEv** [comment]
Closed
