### ISSUE TITLE
Error displaying large file size when transferring 

### ISSUE THREAD

**Issue by iShift** [qTox/qTox#170]
![2014-07-29 15 41 33](https://cloud.githubusercontent.com/assets/426427/3734331/5f34e268-1715-11e4-8dc8-1aea663aa3d9.png)
file size 1,05 GB

**Comment by krepa098** [comment]
I can't reproduce this. Could you please check if this bug still persists?

**Comment by tux3** [comment]
I can't reproduce either. Closing.
