### ISSUE TITLE
[Feature request] way to paste text as a quote

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1701]
There should be a way (and preferably a shortcut) to paste text as a quote in input field.

I.e. `>` ("arrow" followed by a space) should be put before every line of pasted text when option is used.
- Option should appear in **context menu when r-clicked** in input field:
  - `Paste quote`, located below option `Paste`
- Additionally there should be **shortcut**:
  - `CTRL + SHIFT + V`
# 

Potential problems:
- there is possibility of problem(s) of it not working too well when the will be a need to use text splitting with larger texts - i.e. there's a chance that `>` will be left at the end of one message, while text that was supposed to be treated as quote will be in "next" message, which will cause visual inconsistency.
  - to avoid it, perhaps splitting mechanism should be somehow made aware that `> text.. rawr` shouldn't be split, and if it has to be, then text that was split into next message should be again prepended with `>` before splitting it again? or somehow make splitting mechanism to be more generic, so that it could consider different kind of values when splitting messages? (dunno really)
# 

Probably related issue: #784

**Comment by ProMcTagonist** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by SkyzohKey** [comment]
+1

**Comment by sudden6** [comment]
Implemented in recent builds.
