### ISSUE TITLE
autoaccept in settings doesn't work

### ISSUE THREAD

**Issue by Doom032** [qTox/qTox#1704]
What I did:

1) Check the "Autoaccept and save files" checkbox and select an existant folder(/home/thomas/Downloads)
2) Send a few inline images from my µTox account to my qTox account

What I expected:

It automatically accepts the images and saves them in Downloads

What actually happened:

I see the "Accept to receive this file" prompt a few times, and the file isn't accepted and downloaded automatically.

**Comment by zetok** [comment]
I also am affected by that bug on qTox a841224683116e75852d6d2ebc9a9f1dc70ec957.

**Comment by agilob** [comment]
I use it everyday from Antox to qtox and it always works.

Inline images? We don't support that, I didn't know it's a thing

**Comment by zetok** [comment]
@agilob there isn't such thing as inline images, but some µTox people call screenshots that..

**Comment by Doom032** [comment]
@agilob For clarity, this is about the global Autoaccept setting, not the per-user setting, which does work for me. Not sure if you tested that one.

**Comment by tux3** [comment]
Fixed by #1890
