### ISSUE TITLE
some peers aren't shown in groupchat

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1709]
Description:
Peers `トクスが好きです。` and `æ` weren't displayed in peerlist, even though they were in groupchat. There are some other peers like `{☯}S☠ǚll{☣}` that aren't displayed, even though they are in groupchat. While they're not displayed, nick tab-completion still allows to "type" them.

Info:
OS: Hardened Gentoo Linux x86_64
qTox version: a841224683116e75852d6d2ebc9a9f1dc70ec957

Reproducible: Couldn't reproduce / happens randomly

Steps to reproduce:
1. Be in groupchat for some time (hours?) with qTox's window not being maximized?

What happened:
Some peers are not shown in peerlist while they are in groupchat.

What should happen:
All peers should be shown in peerlist while they are in groupchat.

Additional info:
![no peer](https://cloud.githubusercontent.com/assets/3148759/7784166/ed3bb32e-0153-11e5-8101-dd652f748ac9.png)

Probably related to: #919
Way to fix it: #677

**Comment by zetok** [comment]
Apparently resizing window (increasing width) makes more peers visible. Opposite (decreasing width) hides those peers again.

**Comment by ProMcTagonist** [comment]
So it's only showing two lines?

**Comment by zetok** [comment]
Still reproducible on 99b5b092d964b634ce39cc4f452711602b38d467

**Comment by sudden6** [comment]
Couldn't reproduce on master.
