### ISSUE TITLE
Build in windows (question)

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#1711]
Try build in windows many times after update core. 
ineffectually... 
Who has ever happened assemble?
Can instruction something is missing?

(At the moment, when you try to run bootstrap.bat, make.exe falls out with error)

**Comment by zetok** [comment]
If you don't provide even information with what it fails, it's not really possible to help you in any way…

Please read https://github.com/tux3/qTox/wiki/Useful-bug-reports and include more info.

**Comment by PKEv** [comment]
It is rather a request for someone who collects qTox under Windows configuration program to specify the actual configuration.

**Comment by PKEv** [comment]
Maybe someone will be useful:
Path:
C:\Program Files\SmartGit\git\bin;
C:\Program Files\CMake\bin;
C:\Program Files\GnuWin32\bin;
C:\MinGW\msys\1.0\bin;
c:\Qt\Tools\mingw491_32\bin\;
c:\Qt\Tools\mingw491_32\i686-w64-mingw32\bin\

then install qt: install full version
then install MinGW install only msys (develop)

(Especially the installation due to the fact that MinGV why is not installed version 4.9 and QT only supports her, at the moment)
