### ISSUE TITLE
qTox should support pasting images (as data) into the chat

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1716]
It should be possible to paste image data into the chat, so that you can paste it simply in the chat and maybe it will (like it does Skype) just temporarily saved - like the screenshot should be (#1696) - in a suitable directory.
Then the file can regularly sent.

An alternative way would be to implement inline images so that these are directly sent in the chat - but I think this could be more difficult.

**Comment by PKEv** [comment]
Duplicate #1290

**Comment by ghost** [comment]
No this is not a duplicate of #1290 because I'm not talking about screenshots. I mean it much more generally.
E.g. if you use an alternative screenshot tool which copies to screenshot into the clipboard (before/instead of saving as a file) - the Snipping Tool can e.g. do this.
Or other tools that support this kind of image copying - I don't know if it's the same with browsers, but if you right click on an image in a browser and select "Copy image" (**not** "Copy image path") then this could also be covered by this "image data copying".

**Comment by An-dy** [comment]
+1
I like this feature too. It would also almost solve https://github.com/tux3/qTox/issues/1653
BTW. expect that the inexperienced user will past multi-megapixel photos or even larger pictures.

**Comment by ghost** [comment]
Another old issue - what about implementing this?

**Comment by dcapeletti** [comment]
What is the status of this application?

**Comment by agilob** [comment]
how would that be implemented? detect what's under ctrl+v and if string ends with .jpg|png|bmp sent as file?

**Comment by dcapeletti** [comment]
Telegram PC has implemented this functionality. When the user presses Ctrl+V and clipboard content is an image, it is sent as an image file.

**Comment by agilob** [comment]
maybe it would be better to detect if string is a file, not only for images? if string starts with `file://` start new file transfer?

**Comment by dcapeletti** [comment]
It is good idea to extend files.

**Comment by DanTheBritish** [comment]
If copying an image from the clipboard, does that register as a `file://`? If it doesn't then it must have another identifying factor to indicate its a file not a text string. If that's the case, then it could be possible for pasted files to be embedded into the chat rather than trigger a file transfer which must be saved to disk and opened externally.

**Comment by rugk** [comment]
> detect what's under ctrl+v and if string ends with .jpg|png|bmp sent as file?

That's not what is asked for in this issue, but it's also a nice idea. 

> maybe it would be better to detect if string is a file, not only for images? if string starts with file:// start new file transfer?

Yes, this is the idea. Although I don't know if this really uses some kind of `file://` protocol.
I think at least on Windows this is handled differently.
Maybe have a look at this: 
- https://msdn.microsoft.com/en-us/librarysystem.windows.forms.clipboard.getimage%28v=vs.110%29.aspx
- https://stackoverflow.com/questions/998655/how-can-i-get-an-image-out-of-the-clipboard-without-losing-the-alpha-channel-in

**Comment by zetok** [comment]
> maybe it would be better to detect if string is a file, not only for images? if string starts with `file://` start new file transfer?

IMHO that's not really a good idea.

**Comment by agilob** [comment]
> If it doesn't then it must have another identifying factor to indicate its a file not a text string.

What if image is copied as base64? Should we detect base64 strings, save them as temporary file, send the file and delete after transfer is done?

The thing is, if you have a bitmap in memory, like copied pixels, we must save them as files, send as file transfer and delete.

**Comment by agilob** [comment]
> IMHO that's not really a good idea. 

why?

**Comment by zetok** [comment]
> > IMHO that's not really a good idea. 
> 
> why?

Thing is, one can never be certain that they do have in clipboard what they want - I for one wouldn't want to try to paste text, just to find out that I've actually pasted "link" to `file:///`, which was automatically sent by qTox.

That would be a very annoying thing.

With that being said, I see no reason to not implement it, provided that user would be required to give an interactive consent for sending files.

**Comment by anthonybilinski** [comment]
@sudden6 This (only image pasting from clipboard) was implemented under https://github.com/qTox/qTox/issues/1290 by already merged https://github.com/qTox/qTox/pull/4644, I recommend closing.

I think that there being a confirmation between attaching file or pasting image and sending is a good idea. i.e. paste image, it shows up in chat edit window, then hit send or enter and it sends. If that's the case then I don't think there's a reason not to extend it to files too? If the user accidentally pastes a file they don't want, they just hit backspace or click the "x" next to preview, and nothing gets sent. This would be a much more significant change, I'll open a new proposal ticket discussing just that.
