### ISSUE TITLE
Build error at compiling core.cpp

### ISSUE THREAD

**Issue by depate** [qTox/qTox#1727]
I just tried to install qtox+toxcore via AUR (yaourt) and from source via your installation guide, but both failed at the same step at building qTox. This is the error message that occurs:

``` qt
../src/core/core.cpp: In Elementfunktion »void Core::make_tox(QByteArray)«:
../src/core/core.cpp:183:83: Fehler: »uint8_t* {aka unsigned char*}« kann nicht nach »TOX_ERR_NEW « für Argument »2« nach »Tox* tox_new(const Tox_Options*, TOX_ERR_NEW*)« umgewandelt werden
 8_t*)savedata.data(), savedata.size(), nullptr);
                                               ^
../src/core/core.cpp:189:91: Fehler: »uint8_t* {aka unsigned char*}« kann nicht nach »TOX_ERR_NEW « für Argument »2« nach »Tox* tox_new(const Tox_Options*, TOX_ERR_NEW*)« umgewandelt werden
 8_t*)savedata.data(), savedata.size(), nullptr);
                                               ^
Makefile:3480: die Regel für Ziel „core.o“ scheiterte
make: *** [core.o] Fehler 1
==> FEHLER: Ein Fehler geschah in build().f
```

Excuse me that it's partially in german language.  Additionally I don't have that much knowledge in programming especially in QT at all, but:
It says that some argument can't be changed into some other argument or constant?

I hope that you have a clue on what's going on :)

**Comment by suhr** [comment]
Are you sure the newest toxcore is installed?

**Comment by depate** [comment]
I just reinstalled / recompiled toxcore from the git source as explained in the documentary and rerun the qTox  installation as described. The same error occured. There were no erros while checking the toxcore build or installing toxcore and its dependencies, so far as I can tell.

**Comment by tux3** [comment]
It looks like there was a breaking change in toxcore, we'll need to update qTox.

**Comment by PKEv** [comment]
I compile now and get same error (Pre-running bootstrap.bat):
C:\qTox\src\core\core.cpp:183: error : cannot convert 'uint8_t\* {aka unsigned char_}' to 'TOX_ERR_NEW_' for argument '2' to 'Tox\* tox_new(const Tox_Options_, TOX_ERR_NEW_)'
     tox = tox_new(&toxOptions, (uint8_t*)savedata.data(), savedata.size(), nullptr);
                                                                                   ^

**Comment by tux3** [comment]
@PKEv See #1731, there might be a profile corruption with the new qTox/toxcore so the patch was reverted until this is resolved.

**Comment by PKEv** [comment]
Yes, I saw, My history was gone , too...

**Comment by agilob** [comment]
At least we know one really good reason not to push everything into one file.

:(

**Comment by PKEv** [comment]
Well that all was backup

**Comment by Diadlo** [comment]
Yes. I have the same issue.
Arch Linux

**Comment by xDShot** [comment]
Got same on Manjaro. Can't build qtox-git from AUR too.

**Comment by sammy8806** [comment]
Seems like the API is changed again :(
Manjaro/AUR with qtox-git

**Comment by TapGhoul** [comment]
This was broken at toxcore commit irungentoo/toxcore@8e80ced6cea5c50e628c1931f6b3b764b97efb41 - see toxcore/tox.c:578 (old) vs toxcore/tox.c:613 (new)

**Comment by Ph1r3ph0x** [comment]
Seems as this has been fixed :)

**Comment by Diadlo** [comment]
+
