### ISSUE TITLE
No 2 channel audio support

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#173]
```
"Core: Starting new call with 27 without video"
"Core: AV ringing with 27 without video"
"Core: AV starting from 27 without video"
"Core: preparing call 0"
[New Thread 0x7fffd53c0700 (LWP 8704)]
Got a buffer underflow!
"Core: Audio state is 3"
Got a buffer underflow!
"Core: Audio state is 3"
Got a buffer underflow!
Got a buffer underflow!
Got a buffer underflow!
"Core: Audio state is 3"
Got a buffer underflow!
Got a buffer underflow!
```

Sound is really choppy.

2 channel audio works with µTox and Toxic.

**Comment by tux3** [comment]
This should be fixed. Please comment if you still have this problem and I'll reopen.

**Comment by ghost** [comment]
With the latest git at the time of writing, listening to audiobot is extremely garbled.

**Comment by tux3** [comment]
I'll make a different ticket for the quality being shit.

**Comment by zetok** [comment]
@dewbasaur quality with newest qTox didn't differer from quality with Toxic when I've been listening to audiobot

**Comment by ghost** [comment]
@zetok I just built toxic from git to test if it was my libs. Audio is fine on toxic, but like I said, sounds awful with qTox

**Comment by ghost** [comment]
Something something toxic is a master race...

**Comment by tux3** [comment]
But Toxic doesn't even have ASCII Video!

**Comment by ghost** [comment]
Something something in denial...
