### ISSUE TITLE
Just lost all my profiles

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#1731]
after update today I restarted qtox, my profile was removed. name of the profile was stored, but after each restart qtox creates new toxid. My contacts were also removed.
I can _load_ `agilob` profile but it doesn't change anything, after restart new toxid is created, previous is removed. name of the profile stays the same. It worked in the morning, stopped working in the afternoon after that https://github.com/tux3/qTox/commit/7c8334bca90bf77ac745c484d1485b9e30e5de70 commit

**Comment by tux3** [comment]
I reverted the commit while we investigate.

**Comment by tux3** [comment]
I can't reproduce yet. 

What precisely are the exact steps that lead to losing you profile?

**Comment by agilob** [comment]
1. Update qtox
2. update toxcore
3. restart qtox
4. -100% profit

what I have now in .config/tox is:

```
➜  tox  ls -1
7119F8F3B55FCA07F78CC78003F9F9FCE70B2C0AEF3649F3A84C87EA56BE927F.txt
agilob.ini
agilob.lock
agilob.qtox_history
agilob.tox
agilob.tox.DI1692
agilob.tox.dN1666
agilob.tox.xG2338
avatars
data
qTox User.ini
qTox User.tox
qtox.ini
qtox.log
settings.ini
tox_save
```

none of the files have anything that would be useful. None of .ini files have my list of +20 contacts.
I can't load profiles because somehow there are removed before loading - something prevents profiles with duplicated names.

Files 

```
agilob.tox.DI1692
agilob.tox.dN1666
agilob.tox.xG2338
```

have 0 bytes in total -.-' How fucked am i?

**Comment by tux3** [comment]
Note that the friends are stored in the .tox files, not in the .ini files.

I still can't reproduce. Please make a copy of your ~/.config/tox/ folder asap in the meantime, it should be possible to recover everything.

**Comment by agilob** [comment]
`agilob.tox` is empty too.

**Comment by tux3** [comment]
@agilob can you post the qtox.log, entirely?

Do you have any custom patch to toxcore or qTox?

**Comment by agilob** [comment]
No. I update toxcore from `./bootstrap.sh`. It looks like a problem with toxcore, after removing folder `.config/tox` qtox creates new profiles in `/home/agilob` instead in .config/

qtox.log has only debug messages, nothing that would help -.-'

**Comment by tux3** [comment]
@agilob Do you have "Make qTox portable" enabled in the advanced settings?

**Comment by agilob** [comment]
no

**Comment by tux3** [comment]
Please post the log.

**Comment by agilob** [comment]
https://gist.github.com/agilob/d8c49c60c12a766d69ba

after each restart new profile is created and old removed

**Comment by tux3** [comment]
@agilob It almost looks like you compiled with the old toxcore.

The new qTox MUST ONLY be used with the new toxcore, or old toxcore will not be able to load the profile.

Please make extra sure you have the absolute latest toxcore, and that you're **linking against that**.

**Comment by agilob** [comment]
```
root[19:41:58]1]/home/agilob/Projects/qtox
$./bootstrap.sh 
with tox                    : true
with filter-audio           : true
install into libs : true
keep build files            : false
Cloning into '/home/agilob/Projects/qtox/libs/libtoxcore-latest'...
remote: Counting objects: 185, done.
remote: Compressing objects: 100% (176/176), done.
remote: Total 185 (delta 12), reused 58 (delta 6), pack-reused 0
Receiving objects: 100% (185/185), 429.24 KiB | 0 bytes/s, done.
Resolving deltas: 100% (12/12), done.
Checking connectivity... done.
/home/agilob/Projects/qtox/libs/libtoxcore-latest /home/agilob/Projects/qtox
Running autoreconf -if...
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'configure_aux'.
libtoolize: copying file 'configure_aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.

...

  AR    libfilteraudio.a
mkdir -p /usr/local/lib/pkgconfig
mkdir -p /usr/local/include
Installing libfilteraudio.so.0.0.0
Installing filter_audio.h
Installing filteraudio.pc
Installing libfilteraudio.a
/home/agilob/Projects/qtox
```

http://upload.agilob.net/it/qtox.webm

Both qtox and toxcore are uptodate.

**Comment by tux3** [comment]
I'm 70% sure you're linking against an outdated toxcore.

Please delete all versions of toxcore, in libs/ in /usr/lib in /usr/local/lib, all of them.

Then clone toxcore, compile and install it manually, and let's see if it still breaks.

**Comment by tux3** [comment]
@agilob Can you send me a copy of the qTox you compiled and you're running?

I'd like to run that in a debugger.

**Comment by agilob** [comment]
http://upload.agilob.net/it/qtox

**Comment by tux3** [comment]
@agilob could you make that a Debug build, that'd be easier :)

**Comment by agilob** [comment]
I had to git checkout to previous commit df7480f59c840e5450c47df5b8c935c0403dd161

because of that error in **latest** toxcore (just a proof I have it)

```
src/core/core.cpp: In member function 'void Core::make_tox(QByteArray)':
src/core/core.cpp:183:83: error: cannot convert 'uint8_t* {aka unsigned char*}' to 'TOX_ERR_NEW*' for argument '2' to 'Tox* tox_new(const Tox_Options*, TOX_ERR_NEW*)'
     tox = tox_new(&toxOptions, (uint8_t*)savedata.data(), savedata.size(), nullptr);
                                                                                   ^
src/core/core.cpp:189:91: error: cannot convert 'uint8_t* {aka unsigned char*}' to 'TOX_ERR_NEW*' for argument '2' to 'Tox* tox_new(const Tox_Options*, TOX_ERR_NEW*)'
             tox = tox_new(&toxOptions, (uint8_t*)savedata.data(), savedata.size(), nullptr);
```

http://upload.agilob.net/it/qtox_debug

**Comment by tux3** [comment]
@agilob thanks...but there's an ABI break so I can't start it :/ What version of Qt are you using?

So I have no idea what could be causing this, then. It somehow silently created a new profile instead of loading the existing.
The start of the log you posted says qTox started by importing a profile, did you have a profile on another client that you brought over?

Can anyone else reproduce? I tried a fresh build on 2 different computers but I have nothing so far.

**Comment by zetok** [comment]
I can confirm that qTox df7480f59c840e5450c47df5b8c935c0403dd161 fails to compile on old core.

@agilob https://github.com/Tox/arch-repo-tox has supported PKGBUILDs for Arch, which seem to work much better on Arch than bootstrap.sh..

**Comment by tux3** [comment]
@agilob Does this happen every time you create a new profile and restart?

**Comment by agilob** [comment]
As in the [video above](http://upload.agilob.net/it/qtox.webm), keep looking at toxid in the profile.

I'm currently on 30b3f54202de03f7d37f7ef9a87949e856f1c6d1 and toxcore compiled ~2hs ago and the issue doesn't exists, at least it's not losing profiles after import and restart.

**Comment by tux3** [comment]
@agilob 

> toxcore compiled ~2hs ago

So that's the old toxcore that you compiled this time, not the new?

If you go back to new toxcore and apply the qtox patch, does this still happen if you delete the qtox.ini?
What about if you delete the "imported_XXXXXX.tox" file?

I'm really trying to understand what could possibly lead to that, but this isn't making a lot of sense.

**Comment by agilob** [comment]
I'm using the same toxcore, I didn't install old version -.-'

I don't use anything else to install qtox or toxcore than git. When compiling I'm always on latest changes. Before losing profiles I did:

```
git pull #download tux3/qtox/master
su # to install toxcore as root
./bootstrap.sh
exit # to leave super user
make -j4 # compile qtox with latest toxcore
```

Then I restarted qtox and lost my data. Today I did the same, git pull; su; ./bootstrap.sh; exit; make; My old profile with all contacts is lost, new profile, created today, isnt :<

**Comment by tux3** [comment]
> I'm using the same toxcore, I didn't install old version -.-'
> I don't use anything else to install qtox or toxcore than git. When compiling I'm always on latest changes. 

You're confusing me, again. That's not possible!

There is old toxcore (before breaking change) and new toxcore (latest version).
Unpatched qTox (what we have currently) works with old toxcore and [fails to build with new toxcore](https://github.com/tux3/qTox/issues/1727).
Patched qTox works with new toxcore, and I reverted the patch because you're telling me you lost your profile.

**[You can not build the latest qtox with latest toxcore, this is not possible!](https://github.com/tux3/qTox/issues/1727)**

So I don't know what you're doing, but if you could give me a clear picture of the situation, that would help a lot.

**Comment by quininer** [comment]
I encountered the same problem, lost a lot of friends.
This may remind us, qTox Profile need a backup mechanism.

**Comment by agilob** [comment]
It had to be in toxcore, after todays update (both qtox and toxcore) didn't lose anything...

If anyone wants my new toxid: 11193AD5C97CDDFDBD49C468E35B09BD4BBFBD8AC3EC11E63A0BBC5122A54C49CF90383397A0
