### ISSUE TITLE
qTox segfaults when sending big files

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#174]
https://gist.github.com/zetok/ae3fd0646606505dce3f

**Comment by agilob** [comment]
same problem here, crashes while sending bigger files (+1MB)

**Comment by NicePics13** [comment]
Friend on OS X using qTox tried twice sending me a 6MB picture, I was on Windows (uTox) and got at best ~600kB before his client died

**Comment by tux3** [comment]
This should be fixed, please post if you still have this bug. I sent a 1GB file without problem a couple of times, but I haven't tested on slow connections.
