### ISSUE TITLE
NoLog Mode

### ISSUE THREAD

**Issue by tr37ion** [qTox/qTox#1744]
Well, it just came to my mind. Wouldn't it be nice to avoid chat logging on both ends? 

I see, this may raise some funny feelings in some cases, on the other hand, I can imagine if someone really wants to have a _trusted private chat_ with someone else, this might be of no issue at all - Quite the opposite. It raises the seriousness of the conversation and leverages trust in the conversation.

Sure, this is not important for casual use, but for serious conversations this might be a nice feature other IM chats don't have.

**Comment by TheSpiritXIII** [comment]
I don't think it would make much of a difference. The other party may just simply copy/paste their conversation over and thus could still "log" the chat without your consent.

There are other issues to think about. How is the other party notified of this? What happens when they reject your request?

**Comment by tux3** [comment]
This is impossible by definition. Preventing someone from logging or copying text is essentially a DRM design, and can not be done.

Fundamentally, the other party has eyes and can write down a log with pen and paper if everything else fails. 

If you trust whoever you're talking to, you can just ask them to clear the logs. If you don't trust them, no technical solution can fix that.
This would give a false sense of security, if anything.

**Comment by zetok** [comment]
In short, not doable, please close issue?

**Comment by tr37ion** [comment]
Sure, it is not possible to avoid logging completely, but offering a button to show "Not logging the next following content or the chat" could help to show that the following content should kept private.

It's more a visual hint/switch that the chat is now in "no log" mode on purpose.
- It shows logging is not wanted
- It doesn't log with qTox for all chat members
- All other attempts to log the content are not wanted, but still possible.

**Comment by Zer0-One** [comment]
@tr37ion there's no point. it's not enforceable.

if you're talking to someone you don't trust, you shouldn't say anything that you wouldn't want logged. if you're talking to someone you do trust, you just tell them what you expect of them, like you normally would.

**Comment by tr37ion** [comment]
No worries, it was just an idea for an unique feature :)
