### ISSUE TITLE
screenshot not work in qtox windows 

### ISSUE THREAD

**Issue by call5** [qTox/qTox#1745]
if i try to take screenshot with qtox , i have this issue 

![qtox screenshot](http://i.imgur.com/Bn1qDkh.png)

**Comment by towlie** [comment]
Mabe qtox tries to write into a admin only folder? I see that qtox now saves images into appdata\roaming\screenshots.
@call5 Does it also happen with latest qtox?

**Comment by call5** [comment]
@towlie @tux3 in last release this issue fix :)
