### ISSUE TITLE
Improvements to the log-in screen

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1746]
When I start my qTox, a window tells me to choose a profile from the existing ones, with no (straightforward) way to close the window. Clicking 'X' and 'Cancel does nothing, qTox main window stays in the background. I can think of two cases where this doesn't meet the user's need:
1. The user doesn't want to log-in (possibly because they opened qTox by accident). They have no way to quit qTox from the log-in screen, so they need to end the process manually.
2. The user (possibly on a family computer) wants to make his own profile, but he can't do that without accessing one of existing users' profile, which he probably can't. The user needs assistance of another person who has the access, which they can probably get, but it's not conventional.

Obviously, I'd like to suggest offering a way to quit qTox from the log-in screen and a way to add a new user. While at it, would it be a good and simple enough of an idea to integrate the log-in screen into the main window? I think it might look very good. 

We already have a great-looking sidebar with contacts, so maybe the accounts to log into could be presented in the same way, with option to add a new one at the bottom? (On the left dark side, right bright side, or any of them stretched across the whole window?)

P. S.: Maybe these issues arise from bugs or something. I'm running Parabola GNU/Linux-libre (based on ArchLinux) With KDE Plasma 5.

**Comment by SkyzohKey** [comment]
I think it could be nice to make a real loggin screen, not a simple dialog with a stupid dropdown. 
Something better, like skype for example. qTox **must** focus on providing an easy to use and to understand user interface ;)

I'll propose mockups in sometimes ;)

**Comment by tux3** [comment]
I also like the idea of a real login screen instead of dialog boxes. This would be much more user friendly, and we could put more actions (quit, create new profile, ....) in there.

**Comment by linux-modder** [comment]
While I partially agree @tux3, @FishTFM  this is NOT skype and tbh I use *tox more than skype while I have both up all day everyday ---I personally HATE the skype UI

**Comment by linux-modder** [comment]
@Tirifto,   Ideas on how to do that more in the second case you mention ?  the first case seems more like a documentation issue (or lack of it  ---which I'd gradly help fix up)

**Comment by zetok** [comment]
![20150530 qtox login screen](https://cloud.githubusercontent.com/assets/3148759/7896671/cae509aa-06b8-11e5-8a5c-e8b00c21f6d0.png)
So, mock-up. Horribly done, but it at least gives you some idea how I see it.
- 1st field - login field, a drop-down list of available profiles
- 2nd field - password field - visible only when a password is required to use profile, additionally should have `Password` written on it in grey-coloured letters when there's no password written yet; when password is written, there should be `*` displayed instead of letters
- 3rd "field" - checkbox and associated text - visible only when there is no password set on profile
- `New profile` - opens new window to create profile, in this window there should be:
  - option to set name of profile
  - option to encrypt profile
  - button `Cancel` on the bottom left
  - button `Create` on the bottom right
  - when profile is created by pressing `Create`, window closes and newly created profile is selected in profile drop-down menu
- `Login` - starts qTox with profile selected in 1st field
- this window should have an `X` closing it, and be closeable by typical signals to close window - it should always close when receiving that signal, _even if `Close to tray` is set in settings_

btw, if possible, fields should have a bit rounded corners

(uh, and don't pay too much attention to horribly non-centred fields in my mock-up)

Edit: oh, and it doesn't have to keep that long shape - it's just that I went with that in mock-up

**Comment by linux-modder** [comment]
like the gate-keeper style zetok

**Comment by ghost** [comment]
@zetok I like that! Although for the password, I'd choose not to replace letters with a *, but do it like when you type your password in GNU command line and have no characters shown at all. That way, nobody will see how long your password is. Only benefit I can see is that you can tell if the input is working (one could have NumLock off, for example), but that could be replaced with gentle flashing, or an animated icon.

**Comment by suhr** [comment]
@Tirifto This is pretty misleading: you don't see if have you've typed your password or not. Also, stars are standard de facto.

**Comment by ghost** [comment]
> you don't see if have you've typed your password or not.

Like I said, something can be used as an indicator of key press. That would assure the user that their input works. But of course, something else can be done to represent that some text is present. KDE to use three dots for a letter instead of one, so that's also a fine solution. The field could also be made small, or otherwise show only few characters max. at a time.

**Comment by ProMcTagonist** [comment]
What happened to that GSoC student who made login screens for either qTox or Qt-GUI? Anybody got a link?

EDIT: Found: https://seshagiriprabhu.wordpress.com/2014/04/24/gsoc-proposal-user-profile-file-transfer-support-in-tox-qt-gui/

The main difference is Existing and New being sideways tabs under a Tox lock.

![1](https://raw.githubusercontent.com/seshagiriprabhu/gsoc-1/master/screenshots/new_user.png)

![2](https://raw.githubusercontent.com/seshagiriprabhu/gsoc-1/master/screenshots/login.png)

Just another design to think about.

**Comment by zetok** [comment]
![20150530 qtox login screen with full logo](https://cloud.githubusercontent.com/assets/3148759/7897919/37704890-06e7-11e5-81b3-70be89337d74.png)
uh, actually, I forgot to put logo in previous mock-up >.<

So, about colours:
Colour of "black" fields: same as colour of `avatar / nick / status` field,
Colour of background: same as background colour of contact list
Colour of logo: same as colour of text in contact search field, i.e. RGB: 147, 147, 147

logo from https://github.com/Tox/Tox-Misc/blob/master/Logo_Vector.svg
If anyone wants, I can share .kra of mockup and modified .svg logo.

**Comment by linux-modder** [comment]
@zetok, I would be interested

**Comment by zetok** [comment]
Oh, that's interesting. Looks like due to its license ([CC-BY-NC](https://github.com/Tox/Tox-Misc/blob/master/LICENSE)) logo can't be too freely used in qTox. Too bad.

anyway, logo: https://github.com/zetok/Tox-Misc/blob/gray_logo/Logo_Vector_gray_147.svg
and mock-up: [20150530 qTox login screen with full logo.kra](https://a.pomf.se/svbwkh.kra)

**Comment by SkyzohKey** [comment]
Something like that could be cool
![Preview of Toxic login](http://korben.info/wp-content/uploads/2014/06/tox3.png)

**Comment by PKEv** [comment]
Please make a possibility if a profile already involved, the possibility of activating it and the closing of the second copy of the program

**Comment by PKEv** [comment]
Maybe add an icon encrypted/open near the name?
can more minimalist? it was too big for the two form input fields

**Comment by suhr** [comment]
cast @ItsDuke

**Comment by tux3** [comment]
I went with this for now:

![ss015](https://cloud.githubusercontent.com/assets/5155966/7966626/9b60735c-0a25-11e5-949d-8506bc12965d.jpg)

Yes/no ?

**Comment by agilob** [comment]
what about cancel button on right side of 'create account'?

**Comment by zetok** [comment]
@tux3 needs a second `Repeat password` field, also, what's with `Login` page?

@agilob for what would it be needed?

**Comment by tux3** [comment]
@agilob To cancel what?

@zetok Right, forgot about that. Adding it now.

**Comment by tux3** [comment]
New version:

![ss019](https://cloud.githubusercontent.com/assets/5155966/7967153/b3cc549e-0a28-11e5-93b6-deba67c934cc.jpg)

![ss018](https://cloud.githubusercontent.com/assets/5155966/7967151/b061af2a-0a28-11e5-90f9-df6dad394409.jpg)

**Comment by ProMcTagonist** [comment]
Looking good. That grey should be white like the normal body background, yes?

**Comment by tux3** [comment]
The grey is hardcoded to this particular color, should we change it?

I used the colors in https://raw.githubusercontent.com/seshagiriprabhu/gsoc-1/master/screenshots/new_user.png

**Comment by zetok** [comment]
> The grey is hardcoded to this particular color, should we change it?

Yep.

Also, profile chooser shouldn't have an input field for profile name - drop-down list is needed. Additionally, if chosen profile doesn't need password, password field shouldn't be displayed.

**Comment by tux3** [comment]
> Also, profile chooser shouldn't have an input field for profile name - drop-down list is needed.

Done.

> if chosen profile doesn't need password, password field shouldn't be displayed.

Maybe grey it out/disable it instead of hiding?
It'd be weird if things appear or disappear when you select a user, no?

**Comment by PKEv** [comment]
And if the profile is not encrypted?

**Comment by tux3** [comment]
Then we disable/grey out the password field.
And if you create a profile with an empty password, it's not encrypted.

**Comment by ProMcTagonist** [comment]
@tux3 I think just hiding it would be cleaner.

**Comment by tux3** [comment]
Hiding it is then.

**Comment by PKEv** [comment]
As the profile will be chosen for auto login?

**Comment by tux3** [comment]
We could have a checkbox for auto login, there's be a logout button in the profile form.

**Comment by PKEv** [comment]
Please, alignment cent in input fields

**Comment by SkyzohKey** [comment]
Can i suggest a different way for the register/login screen ? :)
Takes me 1 hour to do x)

## Black version

![Register page black](https://cdn.rawgit.com/FishTFM/Tox-Mockups/master/svg/register.svg)
You can find the `.svg` [by following this link](https://github.com/FishTFM/Tox-Mockups/blob/master/svg/register.svg)
And the RawGit with proper headers [just here](https://rawgit.com/FishTFM/Tox-Mockups/master/svg/register.svg)

## White version

![Register page white](https://rawgit.com/FishTFM/Tox-Mockups/master/svg/register-white.svg)
You can find the `.svg` [by following this link](https://github.com/FishTFM/Tox-Mockups/blob/master/svg/register-white.svg)
And the RawGit with proper headers [just here](https://rawgit.com/FishTFM/Tox-Mockups/master/svg/register-white.svg)

**Comment by ProMcTagonist** [comment]
@tux3 Sounds good.  Should it be checked by default?

**Comment by zetok** [comment]
@ProMcTagonist IMHO it shouldn't be set by default

**Comment by ProMcTagonist** [comment]
Maybe if there's only one profile? I'm thinking that the majority of users will have a single profile they want to get into right away.

**Comment by zetok** [comment]
@ProMcTagonist then they can check that checkbox every time they would launch qTox..

**Comment by SkyzohKey** [comment]
@ProMcTagonist @zetok If there's one profile then login else display the login page ?

**Comment by zetok** [comment]
@FishTFM no.

**Comment by ProMcTagonist** [comment]
@FishTFM 

> disable creating new profiles

no

@zetok okay, yeah, they only have to check it once, makes sense

**Comment by linux-modder** [comment]
Auto login 'by default' is retarded and a potential OPSec fail 

Also auto login would  presumably  pre-empt  the create another acct  feature....multi acct users would be hosed...

**Comment by tux3** [comment]
How do we handle auto-login if the profile is password protected?
Do we just don't allow it and hide the auto-login checkbox?

**Comment by zetok** [comment]
> How do we handle auto-login if the profile is password protected?
> Do we just don't allow it and hide the auto-login checkbox?

Yep
