### ISSUE TITLE
No audio (speech) output with ALSA

### ISSUE THREAD

**Issue by antis81** [qTox/qTox#1750]
This is not an exact bug report, but it might help to figure out what's going on deep down under the hood. I really appreciate the work.

For some reason I cannot hear friends while talking via audio chat (I use ALSA on my end; connected to people with PulseAudio and Apple's CoreAudio on the other end). They can hear me and my audio setup is definitely all good (common setup: laptop with speakers and builtin mic. - didn't check the headphone channels so far).

Not to forget: I can hear the ringtone.

Also tried calling the echo bot. There's a good chance getting it to echo my voice - just like it should be. Sometimes I don't hear the echoed voice though.

Tried also switching filtering on/off - didn't notice any difference.

**Comment by zetok** [comment]
@antis81 could you please supply more info: https://github.com/tux3/qTox/wiki/Useful-bug-reports ?

What you wrote is a good start, but to do something about it, it would be nice to know at least what kind of setup you have there (don't limit yourself to that though).

**Comment by antis81** [comment]
Ok :smile:! Here's some more info:
Hardware: It's a stock old MacBook 2,1 (plastic, late 2007).
OS: (L)ubuntu 15.04

I just realized, that due to some issues with the kernel, I'm currently not running the official linux kernel (3.19-18), but instead the latest 4.1-rc5. The bugs got fixed recently and I'll switch back to stable as soon as the official release is out. However, I didn't notice any sound problems in other applications (onboard `Intel NM10/ICH7`).

Hope the [log file](http://pastebin.com/ZfzGAJVD) helps (file expires end of June 2015).

**Comment by An-dy** [comment]
Try EchoBot to test your setup.
Add this TOX ID:
76518406F6A9F2217E8DC487CC783C25CC16A15EB36FF32E335A235342C48A39218F515C39A6

**Comment by antis81** [comment]
@An-dy As written in the issue description, I tried that already. Works one time, while the next time it doesn't echo anything. During a usual call pretty much nothing can be heard on my side. When cross reading the log, it tells about a  lot of dropped frames. This might be the cause.

**Comment by antis81** [comment]
Just want to let you know, that recently I had a successful call with a friend via the latest qtox 1.0+ development version. I also gave the echo bot another try. It worked on the first call, but after hangup and starting another one, sound was gone. Anyway, I keep trying on this. Unsure though, if this information will ever lead to a "final solution".

**Comment by antis81** [comment]
From a user's perspective, this works :ok: now :+1:. Didn't try a second call so far ... I'd say, close it and reopen or create new one with more details on the topic.

**Comment by towlie** [comment]
@antis81 What you described here sounds like an issue which I had when testing https://github.com/tux3/qTox/pull/2094: It was solved by this hack. The bug always happened on second call if you were the one who cancelled the first call.

**Comment by antis81** [comment]
For me, this happens on first call (always?). Current version is the one from the Debian PPA (about a week old). Didn't see any fix for this one in the meantime. Maybe the current changes from @TheSpiritXIII fix this - don't know yet.

This worked a few weeks ago (old repo from tox.im) and I was happy -> now again I cannot hear the other persons, but they hear me.

Have to pause writing for now. Write you later :) ...

**Comment by zetok** [comment]
@antis81 is this issue still present, given https://github.com/tux3/qTox/pull/2415#issuecomment-149498226 ?

**Comment by agilob** [comment]
Can you reproduce it with echobot?

**Comment by antis81** [comment]
I check it right now… Stay tuned.

**EDIT** Unfortunately echobot is sleeping :frowning: :sleeping:

**Comment by antis81** [comment]
Yep, after echobot is awake again it works -> closing.
