### ISSUE TITLE
Secondary ID grabs profile picture from primary ID

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1754]
The setup
- Host system (Mint Cinnamon 17.1) runs qTox. Primary ID has a profile picture. Secondary ID has no profile picture. Both IDs created with qTox.
- VM (Windows XP) runs a 3rd ID in qTox.

Secondary ID in host adds the VM ID. Everything goes as expected, except that the VM account can see the primary ID's profile picture.

**Comment by zetok** [comment]
Note: IIRC this bug shouldn't affect encrypted profiles.

Does it still count as a bug if it only affects plain profiles? And should we really make data useless to other profiles if it's easily available anyway?

**Comment by ghost** [comment]
The problem is that the profile picture is (was?) mixed between profiles. The VM profile shouldn't have seen any profile picture at all. I don't know if it's still reproducible, will give it a try later today.

**Comment by sudden6** [comment]
Is this still an issue? If not please close.

**Comment by ghost** [comment]
I'm not longer able to reproduce. ~Same setup, host running 2 profiles in 6420dc62ec6cf500ad4f71ed2cfa116160122018, guest running 5d117e6af854de194dc16575f1fe5c95a43741c8. All 3 profiles unencrypted.
