### ISSUE TITLE
Bot or something sending 4GB file and spamming

### ISSUE THREAD

**Issue by lzdg** [qTox/qTox#1760]
So this may be a bit long, and I'm not sure where else to inform the devs about this, but it's an annoying issue.

A friend and I are noticing an issue both on the version before and the latest version where he's constantly spammed with the last number of things I said (all with a seemingly random letter or unicode character at the beginning) and I'm sent a file that has no information aside from that it's 4GB. He says he hasn't even sent me a file. Weirdest part is that it seems to respond to both of us like some weird AI shiz. We've been sending a lot of screencaps back and forth between eachother. Anyway, thought I'd just bring this up since it's been not only really annoying but a little creepy as well.

**Comment by agilob** [comment]
one of you is using OLD toxcore version, update both your tox clients and toxcore.

**Comment by zetok** [comment]
@NanoDG and please close your issue, since it's not a bug, but your friend using outdated version.

**Comment by linux-modder** [comment]
+1 for closing as  a UI mismatch -- update your clients
