### ISSUE TITLE
Cam resolution change produce seg. fault

### ISSUE THREAD

**Issue by An-dy** [qTox/qTox#1762]
Cam resolution change produce seg. fault.
qtox Version: 1.0-1722    BTW. ./qtox --version functionality missing

Info:
OS: Linux Mint LMDE 2 (Betsy) (own generic 4.0.2 kernel with no /dev/mem)
        (Kernel change to default distro kernel changes nothing)
Hardware: 
Dell notebook: 120 dpi display.
Reproducible: Always
Steps to reproduce:
0. Don't use gdb. The seg. fault will not happen when qtox (normal & debug build tested) is run with gdb.
1. Start qtox.
2. Wait until connection to network is established.
3. Plug-in USB cam (ID 046d:0990 Logitech QuickCam Pro 9000)
4. Click settings tab.
5. Click Audio/Video tab.
6. Try to change cam resolution.
-> Seg. fault.

What should happen:
qtox should not select the highest video resolution by default.
1600 x 1200, in my case, is way to much.
The default should be a reasonable resolution for a good user video experience.
320 x 240 or 640 x 480 is my proposal. The experienced user will change it, the inexperienced user will be happy with a fluid video stream. Btw. please mention the extreme useful [EchoBot](https://toxme.se/u/echobot) in the qTox docu/read_me.

qtox should also remember the settings of the last 3 previous used audio/video devices and use them again when they become available by default.
This happens all the time:
- The inexperienced user pull the cam.
- Runs qtox, notice that the cam is missing.
- Plug-in the cam
- Expect that the plugged-in cam get recognised and used in the same way (resolution, audio source) as before.

qtox.log: https://gist.githubusercontent.com/An-dy/7d3568280beeac4dfc6a/raw/a8f11071adb282f83a8833534a037b1d16ec6706/qtox.log

**Comment by tux3** [comment]
This should be fixed when the FFmpeg branch is merged in.
