### ISSUE TITLE
Boring bug with fucking stupid names

### ISSUE THREAD

**Issue by SkyzohKey** [qTox/qTox#1764]
A picture is better than dozen words 
![bug](http://i.imgur.com/tYIww8V.png)

**Comment by Binero** [comment]
I can confirm this.

**Comment by ProMcTagonist** [comment]
Names that are too long or have newlines should be displayed truncated with a "..." in the peerlist.

**Comment by tux3** [comment]
All characters that break the layout like newlines or RTL/LTR overrides should probably be stripped.

**Comment by ProMcTagonist** [comment]
Stripping is meddling and is unnecessary. Just truncate the display.

**Comment by tux3** [comment]
So you would truncate A
A
A
A
A
A
A
into A... instead of AAAAAAAA? 
It's even more meddling, you lose more information.

**Comment by zetok** [comment]
@tux3 no, you wouldn't lose information if it was properly implemented, i.e. nicks would be in a list.

If nick has a newline in it, only first line is displayed (or part of it) followed by `…`, and whole nick is eventually displayed in toolTip when user hovers their mouse over it. This way you don't lose any information, while preserving layout.

**Comment by tux3** [comment]
@zetok Alrighty then, let's truncate nicks.
