### ISSUE TITLE
Allow to change global settings with multiple instances

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#1771]
If multiples instances are running and one instance changes a global setting, other instances will not be aware of the change and will cancel it when saving. We need to sync settings changes across multiple instances somehow, or only allow one instance to change the settings.

The easy fix is only allowing the instance that owns the IPC to change the global settings.
The hard fix is to implement IPC message broadcasting to sync settings changes across instances, and have the master instance do the actual global saving.

**Comment by tux3** [comment]
QFileSystemWatcher would be a better solution. We'd reload the global settings when the file changes.
It's still racy, that shouldn't be visible for a regular user.

**Comment by tox-user** [comment]
This doesn't happen anymore in 1.15.0. Closing.
