### ISSUE TITLE
Add an option to disable the video device

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#1772]
So it looks like this:
Video device:
- Cam 1
- Desktop
- No Device

**Comment by agilob** [comment]
btw. is that possible in toxcore to switch audio->video or video->audio during call?

**Comment by tux3** [comment]
Yes, there just isn't an UI for it yet.

**Comment by towlie** [comment]
https://github.com/tux3/qTox/commit/9c87d5ed2ea7c9ae5821c031eaba6526f9ccd1d6
