### ISSUE TITLE
New windows taskbar status icon does not work always

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#1775]
![lock](https://cloud.githubusercontent.com/assets/6986141/7968956/35177280-0a34-11e5-99e4-d24a466d2129.jpg)

It should look like this 
![pixel](https://cloud.githubusercontent.com/assets/6986141/7969049/accfef1e-0a34-11e5-8f51-0bb2aae8dc04.jpg)

Maybe this is related to : #1774

**Comment by towlie** [comment]
When I disable "Taskbar Button Grouping" then it is displayed as it should. 
![nogroup](https://cloud.githubusercontent.com/assets/6986141/7969452/364ae030-0a37-11e5-9ae8-9457d65a2ebc.jpg)
http://www.sevenforums.com/tutorials/496-taskbar-button-grouping-enable-disable.html

**Comment by tux3** [comment]
This is a "feature" of Windows. 
If you have taskbar grouping on, Windows deliberately uses the fixed lock icon so it can group multiple tox instances in the same taskbar entry.

We can not fix that.

**Comment by towlie** [comment]
Usually Windows should only use this:
![lock](https://cloud.githubusercontent.com/assets/6986141/7969596/354c2616-0a38-11e5-95dd-71518febf1f3.jpg)
on the video call window.

**Comment by towlie** [comment]
Caused by corrupted icon cache.

**Comment by towlie** [comment]
If someone has this issue too than you should
- delete/uninstall qTox 
- run a registry cleaner like CCleaner and clean the registry for your user account. (so without running it as admin)
