### ISSUE TITLE
Rewrite profile management system

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#1776]
Rewriting qTox's profile management system in [a separate branch](https://github.com/tux3/qTox/tree/loginscreen).

TODO:
- [X] Create GUI for new login screen (#1746)
- [x] Implement profile scanning/importing in class Profile for the login screen
- [x] Make Nexus own a single Profile, with get/set
- [x] Make Profile own Core
- [x] Make Core use Profile for loading the tox save
- [x] Add helpers to check the password and load/save a profile to Profile
- [x] Move all the high level profile loading/saving to the Profile class, not Settings
- [x] Only load global Settings on startup, then start Nexus which starts LoginScreen
- [x] Have LoginScreen talk to Nexus to login and start a Widget then close itself
- [x] Update the profile form with just a Logout and Rename/Delete current profile
- [x] Respect `-p` switch - don't launch profile page if profile is specified, unless password needed
- [x] Remove the password/encryption settings in Privacy tab, use profile password for everything
- [x] Reject passwords shorter than 8 characters
- [x] Don't allow overwriting profiles when renaming them
- [x] Implement resetting a Profile's core, for reconnection
- [X] Add button to delete the password
- [x] Add button to change the password
- [X] Test
- [x] Merge back into master

**Comment by zetok** [comment]
- [ ] respect `-p` switch - don't launch profile page if profile is specified, unless password needed

**Comment by tux3** [comment]
Added

**Comment by tux3** [comment]
The new profile system is in a testable state. The login screen shows up on startup and can be used to create/load a profile. The buttons in the profile form aren't currently implemented, so you can't logout/export/rename/delete a profile yet.

Backup your profiles before testing.
