### ISSUE TITLE
- URGENT - ToxCore cannot start. The application will quit.

### ISSUE THREAD

**Issue by SkyzohKey** [qTox/qTox#1780]
Hey.
I was looking a movie at TV, then the movie ended and I then sit on my chair, in order to continue my bot developpement. I saw that my bot crashed without any reason. So i tried to rerun it, then get an error: `/home/thanoss/Developpement/NodeJS/ToxBot/node_modules/toxcore/lib/errors.js:37 throw (new Error('tox_new error: ' + val));`. I guessed that toxcore updated and by the way made node-toxcore outdated. BUT it was not the case. Then i tried to launch qTox with my bot profile. qTox is now displaying a fucking pop-up that close the whole app when I click Ok.

![Screen of the bug](http://i.imgur.com/IWyZ5WI.png)

Now i'm blocked to this screen and cannot switch to my main profile. Please fix, i dunno what is the bug but I saw that my bot profile was damaged.

**EDIT:** I had to change this line `currentProfile=SkyzohKey` in the qTox.ini to "log" on my main profile but still can't access the bot profile.

**Comment by tux3** [comment]
Please post the qTox.log.

I don't how your bot system works, all I can tell you without the log is that toxcore couldn't start for some reason.
