### ISSUE TITLE
Tip: Add video input device

### ISSUE THREAD

**Issue by dcapeletti** [qTox/qTox#1784]
Adding a video input option as it can be the desktop, as has the UTOX client could be very helpful for support.
![desktop](https://cloud.githubusercontent.com/assets/5890886/7994114/3b481d46-0ae1-11e5-8936-42a796b3ebea.png)

**Comment by Zer0-One** [comment]
uh... this is exactly how it works right now.

**Comment by tux3** [comment]
Hi, this is already implemented.
Get the latest version of qTox and look in the A/V settings.
