### ISSUE TITLE
Bug in desktop sharing

### ISSUE THREAD

**Issue by Diadlo** [qTox/qTox#1785]
Hello. Today I tried desktop sharing. When I started it in first time, qTox was crashed. When I tried second time, my friend seen artefacts (screen in attachment). I have active desktop in video device (Linux client), my friend - camera (Windows client). And he seen HIS screen with artefacts.
![diadlo 2015-06-04 11 07 53](https://cloud.githubusercontent.com/assets/6306608/7994311/fd78380a-0b14-11e5-98f8-a3b98e7b12f8.png)

**Comment by tux3** [comment]
I made a fix, but I'm not sure if it'll be enough. 
Please check if it's still a problem if both you and your contact are on the newest qTox.

**Comment by Diadlo** [comment]
You update windows binary files? If yes, the problem remains

**Comment by tux3** [comment]
The new binaries are coming, in 5 minutes.
EDIT: It's ready now!

**Comment by Diadlo** [comment]
May be you should add something like "version" in GUI?

**Comment by tux3** [comment]
Yes, it will be added eventually. Probably in the settings next to the license text.

**Comment by Diadlo** [comment]
Same problem :(

**Comment by tux3** [comment]
Ok

**Comment by Diadlo** [comment]
May be it is due to https://github.com/tux3/qTox/issues/1786 ?
I have multi-display.

**Comment by zetok** [comment]
Is it still reproducible?

**Comment by Diadlo** [comment]
I think, no.
