### ISSUE TITLE
Broken nick encoding in chat log after restart

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#1787]
![whatisthis](https://cloud.githubusercontent.com/assets/2544251/7994591/8005ebb4-0b06-11e5-8ea0-1b22ff297e54.png)

I'm pretty sure it worked last month. 
@FishTFM

**Comment by SkyzohKey** [comment]
It's my name that broked the chat logs ? ô.o

**Comment by agilob** [comment]
it's from your chat

**Comment by tux3** [comment]
I'm not sure what changed between last month and now.

**Comment by agilob** [comment]
![whatisthis2](https://cloud.githubusercontent.com/assets/2544251/7995294/871fb870-0b0c-11e5-90cc-75ac800db169.png)
or maybe I didn't notice that(?). Not sure. @FishTFM could you ask your other friends if they can reproduce it?

**Comment by SkyzohKey** [comment]
I asked about 35 friends, and they don't see that :/
Maybe you are missing some fonts ?

**Comment by agilob** [comment]
![whatisthis6](https://cloud.githubusercontent.com/assets/2544251/8033059/4ee75354-0dd3-11e5-9349-23c0cbd57348.png)

it works before restart

**Comment by dummyacct7** [comment]
Myself and a friend are getting the same problem, both running the 64-bit client on Win7 in Japanese system locale. Names look fine when chatting, but when logs are loaded the encoding is broken for names in old messages. Only the names seem to be broken; the messages themselves appear properly.
Example chat with myself (broken names are from history; last line is from the active session):
![chatlog](https://cloud.githubusercontent.com/assets/12880454/8147930/735a0cc4-1240-11e5-8300-91ea26fe001c.png)

**Comment by agilob** [comment]
@SkyzohKeyx  could you invite me?
A5CB22B35202E91CE49CD2CE07AF036C1410179D47D2E110A1E1D9D7AD59042FF1C7D6685D57
