### ISSUE TITLE
New Login window

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#1790]
1) Please add the ability to log into your profile without any additional  buttons.
2) Lost Association .tox files 
3) start with key "-p<profile >" crash app after load GUI
4) Need a "Cancel" button in Login window

**Comment by tux3** [comment]
1) Planned, with an autologin checkbox
2) What do you mean?
3) Noted
4) To cancel what?

**Comment by PKEv** [comment]
2)Before I could start I needed profile by calling the file "Profile.tox"
Although maybe I thought so because I have only one profile...
4) The presence of button "close" of the window "select  profile" 
Otherwise, will something like #1723

**Comment by tux3** [comment]
2) I'm not sure I understand. You renamed the .tox save files?
4) Why a close button? There is already the window manager's controls. I can add a CTRL+Q shortcut to close/exit if you want, but I wouldn't know where to put a close button.

**Comment by PKEv** [comment]
2) i try now with old version, now then I try load associate file Profile qtox load in memory without a GUI
I don't know when it was associate but probably it costs to fix -> cast a given parameter
4) ok (CTRL+Q)

**Comment by linux-modder** [comment]
@tux3 @PKEv  regarding 2) do you mean that  qtox.tox  is no longer working for you ?  if so did you rename it ?

**Comment by linux-modder** [comment]
@tux3  about the close button maybe in the titlebar or a tiny one to the far left of  login?

**Comment by PKEv** [comment]
2) i don't rename it, but his name look like "profile.tox" (in my case "PKEv.tox")

**Comment by tux3** [comment]
1) Is done with 276f411ad29b493c9e2ea92f188c1981657e6f8f

**Comment by tux3** [comment]
3) I don't have a crash. What exactly are the steps to get a crash? The **detailed** steps.

**Comment by tux3** [comment]
4) Is done by 0923e2b733a645ba4a3744852c9f260a63ab5e09

**Comment by PKEv** [comment]
3) Start by execute command qtox -p"your profile name"

**Comment by tux3** [comment]
3) Works for me, no crash here.

Can you post a backtrace with gdb?

**Comment by agilob** [comment]
3) no crash too.

**Comment by tux3** [comment]
I'm also still not sure what 2) means.

**Comment by tux3** [comment]
@PKEv the screenshot you posted in https://github.com/tux3/qTox/issues/1803 shows an old version, are you sure you're using the latest qTox?

Where did you get qTox?

**Comment by agilob** [comment]
I think he did `qtox -p agilob.tox` instead of `qtox -p agilob`

**Comment by tux3** [comment]
@agilob that wouldn't crash, just say that the profile doesn't exist.

**Comment by agilob** [comment]
He didn't say it crashes on 2). idk.

**Comment by tux3** [comment]
Oh, I though you were talking about 3.
Then ok, 2) isn't a bug.

**Comment by PKEv** [comment]
Sorry, I again tried to repeat the result in an error but nothing happened ...
