### ISSUE TITLE
Video preview disappears when qTox is minimized to tray

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1792]
Description: Video preview of `Desktop` disappears from settings once qTox is minimized and restored from tray. Switching to other settings tab and back "restores" video preview.

Not checked:
- video preview from camera
- whether actual video call is affected

Info:
OS: Gentoo Linux x86_64
Xorg: 1.16.4
FFmpeg: 2.6.3
qTox: 9e65cfde5c6d771742b62fed38217afffe44bd09

Reproducible: Always

Steps to reproduce:
1. Go to `Audio / Video` settings tab and set `Desktop` as video source
2. Minimize qTox to tray
3. Restore qTox from tray

What happened:
After restoring qTox from tray video preview disappeared from `Audio / Video` tab.

What should happen:
After restoring qTox from tray video preview should be still be shown in `Audio / Video` tab.

Additional info:

![video preview gone](https://cloud.githubusercontent.com/assets/3148759/7996794/4b2839a4-0b1c-11e5-9f4c-5c624a771d09.png)

**Comment by tux3** [comment]
Note: Probably due to how we hide the webcam view when the A/V tab is hidden, but we only show it when the tab is switched to (instead of everytime it's shown).
