### ISSUE TITLE
New accessibility feature: Change text size Qtox

### ISSUE THREAD

**Issue by dcapeletti** [qTox/qTox#1797]
![size](https://cloud.githubusercontent.com/assets/5890886/8001088/a5f15f98-0b38-11e5-9e41-b38b7c77bd11.png)
Older people are usually several drawbacks to read the text because the words are very small chat. It would be good to have an option to change the size as it does UTOX

**Comment by zetok** [comment]
Looks like a duplicate of #1166 and perhaps of #530
