### ISSUE TITLE
Delayed file transfer from antox to qtox

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#1802]
I'm not sure if the bug is in qtox or antox so @subliun feel free to comment.

When sending a file from antox, some files are received (by qtox) automatically, some are delayed (sending by antox?)
I have autoaccept for all friends, so I think delayed transmission is caused by antox.
1. send one file (transmission finishes very quickly)
2. send second file (transmission id delayed, status of the transmission is delayed too)

I don't know what to do now, I see text "Accept this file" but the only buttons are pause and cancel. I can pause it and resume, after resuming text 'paused' is still visible, after next 5-10seconds transmission starts. If I do nothing, file transfer starts after 5-10 seconds, it never took longer than 15sec.

![whatisthis3](https://cloud.githubusercontent.com/assets/2544251/8007909/c219866a-0b96-11e5-9953-cb46d96f8ed1.png)
![whatisthis4](https://cloud.githubusercontent.com/assets/2544251/8007915/c4bdbc38-0b96-11e5-99ed-b671436011ea.png)

**Comment by linux-modder** [comment]
using wifi on same network show same lag? e.g . qtox on laptop and antox both using same wifi network..

Could show a network latency not a tox issue or narrow  down which client....

**Comment by agilob** [comment]
I'm using only on the same wifi.

**Comment by linux-modder** [comment]
what android device and version of android ?   starting to think its antox too now

**Comment by agilob** [comment]
s3 4.4.4
