### ISSUE TITLE
qTox should encrypt the per-user settings if the profile is encrypted

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#1810]
We currently save a plaintext .ini file for the per-user settings.

Instead, we should encrypt the .ini file with the profile's password if it has one.

**Comment by Zer0-One** [comment]
Is there any case in which a user might want to edit configuration settings without starting qTox? Because this would break that.

**Comment by tux3** [comment]
A user might want to edit the global settings in qtox.ini, which are not encrypted, but never the personal per-user settings.

The personal settings can and should all be edited from the GUI only.

**Comment by An-dy** [comment]
encrypting anything on program level is the wrong approach.
Please point people to https://veracrypt.codeplex.com/ or https://wiki.archlinux.org/index.php/Disk_encryption

**Comment by tux3** [comment]
@An-dy FDE can not always be used, and it often has very cheap or no authentication, which can be pretty dangerous.

Both approaches are correct. If you don't want to have an encrypted profile, you can simply not set a password.
