### ISSUE TITLE
[Feature request] Add an option to set a default download directory without autoaccept

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#1818]
So you just accept a filetransfer and the rest is done automatically.

**Comment by TheLastProject** [comment]
While we're add it, I think it'd be good to have a default download directory, something like Downloads/Tox, be enabled by default already. You almost always want to save things in the same place anyway, so I feel it is a much nicer default.

**Comment by linux-modder** [comment]
Vote to close on grounds this already exists  with  autoaccept files from
'john doe'   via right click on contact

Corey W Sheldon
Freelance IT Consultant, Multi-Discipline Tutor
(p) 310.909.7672
G+: https://www.plus.google.com/+CoreySheldon
LinkedIn: https://www.linkedin.com/profile/view?id=70127804
Github: https://www.github.com/linux-modder
Facebook: https://www.facebook.com/corey.sheldon
Several Communities on Stack Exchange https://www.stackexchange.com

http://www.facebook.com/1stclassmobileshine

Tutoring in person or via any of the following platforms:
HackHands https://www.hackhands.com
Wizpert https://www.wizperts.com
FieldNation https://www.fieldnation.com
AirPair https://www.airpair.com
Truelancer http://www.truelancer.com

## {PayPal,Google Wallet/Play store, Apple Pay}

pub  3072D/718BF597
http://pgp.mit.edu/pks/lookup?op=get&search=0xE958C5D6718BF597 2014-12-08
      Key fingerprint = 2930 99EB 083D D332 0752 88C4 E958 C5D6 718B F597

## uid     Corey Sheldon (Fedora Key) sheldon.corey@gmail.com

**Comment by TheLastProject** [comment]
You know, @linux-modder, it would be good if you would actually read the title of the bug report to see that it was about being able to set a default download directory WITHOUT autoaccepting files. What would be even greater would be if your signature would not be over 10 times the length of your message.

**Comment by ProMcTagonist** [comment]
I would like a default download directory of Downloads/Tox/%friendname

**Comment by zetok** [comment]
@ProMcTagonist what should be done in case where friend name is composed entirely of characters that can't be used as a file (dir) name?

**Comment by ProMcTagonist** [comment]
@zetok Stripping would be unavoidable. I prefer that to having all the files lumped together in one directory, and the Skype users I've talked to about it agree. Sticking all downloaded files in one place is actually a big complaint. Just an anecdote at the moment, we can do a survey if we need to.

**Comment by ProMcTagonist** [comment]
@zetok ID could be used.
