### ISSUE TITLE
Tray Icon problems on Fedora 22 KDE x64 Linux (Qt 5.5 bug)

### ISSUE THREAD

**Issue by Getron** [qTox/qTox#1820]
The tray icon doesn't change on my Fedora 22 KDE x64 Linux.

The "Light icon" doesn't work.

And the icon not indicate my status to, doesn't work, it is just a black Tox icon, without any indications on it, like green midle dot, or so, nothing.

Can you please check this, and fix it please?

**Comment by zetok** [comment]
@Getron if you could, please include more info: https://github.com/tux3/qTox/wiki/Useful-bug-reports

**Comment by Getron** [comment]
@zetok EchoBot is functional, i'm online on qTox main Window, just the tray icon is not showing if i'm online, and not change the "Light icon" from options.

I think, this could be a problem with the new KDE 5.3, which is included in the new Fedora 22 KDE x64.

Many apps have this icon problems with the new KDE 5.3, but, this is one of the newest improvment of KDE.

I think you should try it on a virtual machine to, and you will see then the problem. On my machine, it is not virtual machine, it is on real hardware installed the system, but, i think, this would happend on virtual Fedora 22 KDE Spin x64 machine to.

On Fedora 20 and 21 KDE, i don't have this problems, but, the 20 and 21 have a KDE 4, and the 22 is ekiped with new KDE 5.3, which has other algorithms for icons, and many other things.

The best way is to check it yourself.

For example, Viber, Teamviewer, NoMachine and Skype has to this problem with tray icon on new KDE 5.3, it doesn't show at all the skype icon. And i'm not alone with this problems.

qTox showa the icon, but, is not functional (graphicaly)

**Comment by tux3** [comment]
@Getron Hi, can you post the content of ~/.config/tox/qtox.log please?

**Comment by Getron** [comment]
2015-06-03 21:00:53 file logger starting
[21:00:53.617] src/core/core.cpp:916 : Warning: The Tox configuration file  ""  was not found 

2015-06-03 21:07:43 file logger starting
[21:09:28.234] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[21:09:30.531] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[21:09:30.641] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[21:09:30.750] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[21:09:30.859] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[21:09:30.960] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[21:09:31.071] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[21:09:31.170] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[21:09:31.267] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[21:09:31.365] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[21:09:31.470] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[21:09:45.586] src/core/core.cpp:916 : Warning: The Tox configuration file  ""  was not found 
[21:09:49.781] src/core/core.cpp:916 : Warning: The Tox configuration file  ""  was not found 
[21:09:52.218] src/core/core.cpp:916 : Warning: The Tox configuration file  ""  was not found 
[21:09:55.268] src/core/core.cpp:916 : Warning: The Tox configuration file  ""  was not found 
[21:09:59.241] src/core/core.cpp:916 : Warning: The Tox configuration file  ""  was not found 
[21:10:00.132] src/core/core.cpp:916 : Warning: The Tox configuration file  ""  was not found 
[21:10:01.101] src/core/core.cpp:916 : Warning: The Tox configuration file  ""  was not found 
[21:10:03.381] src/core/core.cpp:916 : Warning: The Tox configuration file  ""  was not found 
[21:10:09.584] src/core/core.cpp:916 : Warning: The Tox configuration file  ""  was not found 
[21:10:11.260] src/core/core.cpp:916 : Warning: The Tox configuration file  ""  was not found 
[21:10:12.433] src/core/core.cpp:916 : Warning: The Tox configuration file  ""  was not found 
[21:10:15.100] src/core/core.cpp:916 : Warning: The Tox configuration file  ""  was not found 
[21:10:18.773] src/core/core.cpp:916 : Warning: The Tox configuration file  ""  was not found 
[21:10:19.772] src/core/core.cpp:916 : Warning: The Tox configuration file  ""  was not found 
[21:10:21.922] src/core/core.cpp:916 : Warning: The Tox configuration file  ""  was not found 

2015-06-03 21:11:25 file logger starting

2015-06-03 21:12:13 file logger starting
[21:19:15.861] :0 : Warning: QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
[21:19:15.869] :0 : Warning: QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
[21:19:15.869] :0 : Warning: QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
[21:19:15.869] :0 : Warning: QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
[21:19:15.869] :0 : Warning: QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
[21:19:15.869] :0 : Warning: QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
[21:19:15.870] :0 : Warning: QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
[21:19:15.870] :0 : Warning: QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
[21:19:15.870] :0 : Warning: QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
[21:19:15.870] :0 : Warning: QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
[21:19:15.870] :0 : Warning: QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
[21:19:15.870] :0 : Warning: QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
[21:19:15.870] :0 : Warning: QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"

2015-06-03 22:08:02 file logger starting

2015-06-06 15:06:13 file logger starting

2015-06-06 15:32:04 file logger starting
[16:10:53.890] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[16:15:58.535] :0 : Warning: No node found for item that was just removed:  QUrl( "file:///home/getron/.bashrc" ) 
[16:18:29.253] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[16:18:29.692] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[16:30:03.809] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[16:30:03.915] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[16:30:04.310] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[16:30:04.589] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[16:30:07.905] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[16:30:08.047] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile

**Comment by tux3** [comment]
@Getron Is that all there is in the log?

Where did you get qTox?

**Comment by Getron** [comment]
Yes, that's all in this log file, nothing else.

I have it from here (Clicked on the Linux, Packages on your links here in github):

https://jenkins.libtoxcore.so/job/qTox-Linux-pkg/lastSuccessfulBuild/artifact/

the .rpm package for x64:

package qtox-1.0-1737.x86_64

Downloaded, installed.

**Comment by zetok** [comment]
@Getron sadly, that package is outdated..

**Comment by tux3** [comment]
@Getron Those packages are extrememly outdated, they are apparently being updated, but until they are and you have an up to date qTox version there's not much I can do.

**Comment by Getron** [comment]
I don't understand that, you put this here on download, and say is outdated? Why put, or why let you this links here for linux? Why you not put the new one?

https://github.com/tux3/qTox

and then, i go to download Linux, Packages, and i go here:

https://jenkins.libtoxcore.so/job/qTox-Linux-pkg/lastSuccessfulBuild/artifact/

Why you don't provide new link to new packages, if this are outdated? I think, many of user are confused with this. I am. I don't understand where i can download the new rpm now.

And from where i can download the new rpm package?

**Comment by tux3** [comment]
@Getron The problem is that I rely on someone else to make the packages. I put the download here because there is no other download currently, unless you want to compile from the source code.

Currently, there is no up to date RPM package because I don't make them myself, and the repo I was relying on is outdated.

Maybe I should start making the Linux packages myself, but I'm not very good at packaging.

**Comment by Getron** [comment]
@tux3 Aha, ok, now is all clear.

Yes, this will be great if you can make the packages, it would be great if users have the newest Tox. You can learn somthing here:
https://fedoraproject.org/wiki/How_to_create_an_RPM_package

And, look at the Syncthing, this people are awesome building packages, every weekend there are all the packages with the newest changes:

https://github.com/syncthing/syncthing/releases

in fact, this are not packages, just the binaries for every system there.

And the Syncthing itself has an Auto-update system, it apear on Syncthing GUI an update button, and you can update the software with a single click. Or, you can check in options an auto-update (pre-chacked) so, you don't need to do anything, you will allways have the newest, updated version of software. Once installed, forever the become the newest versions automatically. This is awesome.

I wich, Tox, or qTox should have an such update system.

**Comment by Getron** [comment]
I have tryed now to add the Fedora repo file to my fedora 22, and, it still to be the same "extremly outdated" qTox, v1.0-1737, but the other problem, i can't find anywhere on qTox where the version i have is? Like "About", how i see on my qTox, which version i have installed?

This info about qTox, v1.0-1737 i have just from downloaded place, which seems to be aoutdated, but, after install, i can't find the version installed (info, about version)

And, you say, is very outdated, but, look here:
https://jenkins.libtoxcore.so/job/qTox-Linux-pkg/

this version v1.0-1737 seems to be just 4-5 days old??? What is now the new version number? and date?

The other problem is, i can't install all dependencies on fedora 22 required to compiling the qTox.

Self compiling is a terrible problem for most of user out there. You need to have in mind, that not all users, who whant to use qTox is an compiler professional, or programmer.

i whish i could help here, but, i'm more the graphic guy, not a programmer.

So, it would be nice to update the qTox repo and rpm to the newest version (with an version info)

I apreciate your work and thanks in advice.

**Comment by zetok** [comment]
@Getron 

> Yes, this will be great if you can make the packages, it would be great if users have the newest Tox. You can learn somthing here:
> https://fedoraproject.org/wiki/How_to_create_an_RPM_package

No, it's actually a bad thing if @tux3 has to **waste his time** on packaging for Linux distros - it's much better if he can spend it on actually improving qTox.

> And, look at the Syncthing, this people are awesome building packages, every weekend there are all the packages with the newest changes

Lol. If packaging was done properly, and when it worked, qTox has updates ~every day. Additionally, comparing "packaging" of Syncthing to qTox is stupid - i.e. Syncthing is written in Go, which makes it easy to make statically linked builds **that are not packages**, which are unfitting for e.g. inclusion in distros repos.

That being said, if you'll find a way to statically link Qt libs in qTox, please say so, so that qTox could have static builds that would work across all distros. Even then comparing it to Syncthing in that regard would be wrong, since amount of work required to make static builds for either of projects differs by an order of magnitude.

> And the Syncthing itself has an Auto-update system, it apear on Syncthing GUI an update button, and you can update the software with a single click. Or, you can check in options an auto-update (pre-chacked) so, you don't need to do anything, you will allways have the newest, updated version of software. Once installed, forever the become the newest versions automatically. This is awesome.

No, it's not. Syncthing simply goes NIH route here, and instead of relying on package managers for distros it provides its own updater. I'd advise you to ponder on question why using package manager is preferable.. and if you're dissatisfied with how package managers work, or with the fact that most of them make it simply harder to package things for Linux distros - I think that you should bug about it people who are responsible for that stuff. Who knows, perhaps they would even care :D

> this version v1.0-1737 seems to be just 4-5 days old??? What is now the new version number? and date?

Look at latest commit.

> The other problem is, i can't install all dependencies on fedora 22 required to compiling the qTox.

Could you please say what you can't install / what is missing?
Thing is, as long as no one will say **precisely** what doesn't work / is missing, there'll be no way to even start thinking about how it could be worked around / fixed…

@linux-modder was trying to compile qTox on fedora, I don't remember which version exactly, but I think that it was 22. I don't know whether those efforts were successful, since he seemed to struggle with basic things, but if you want, here's the script that may work, **provided that you will have toxcore installed** on your system; **read INSTALL.md** before using it though: https://gist.github.com/zetok/6ca803d370a7532cdbdb .. it actually doesn't have anything in regard to installing FFmpeg stuff so…
If you find this insufficient, please say so, _after making sure that docs don't have an answer for it already_, so that docs could be improved in that regard.

I'm not quite sure about that, but I've heard that fedora doesn't provide FFmpeg… which would make it a lot harder to get FFmpeg, and then compile qTox against it.. But apparently there is provided FFmpeg in RPMFusion? You'll need -dev stuff, or whatever it's named. Blame fedora people for choosing to support broken stuff instead of FFmpeg. (same would go for debian people… but I've heard that opensuse has it in its repo..?)

> So, it would be nice to update the qTox repo and rpm to the newest version (with an version info)

Um, not really. What would be nice though is having people who are interested in packaging stuff for RPM-based distros, and who would do that well.

I hope it helps.

**Comment by Getron** [comment]
@zetok About repository of Syncthing:
http://www.webupd8.org/2015/05/official-syncthing-debian-ubuntu.html

The fact, how the Syncthing is maded, in Go, or other, for me, as user, it is not important. I, as user, i'm proud that i can update it with an click, or less, it pull automaticaly the newest version, without i must ever open it, no matter, what i use for an OS. And this, my friend, is what the users apreciate. Like this, this software will grow.
Ok, i known, syncthing, like other softwares, it has many bugs and problems, but, the important steps are there, and this is, how the user become the newest Version, without learning full programing staff. For me, this is what a user want.

About ffmpeg on fedora (it seems that you have not enough infos about linux distros):
http://rpmfind.net/linux/rpm2html/search.php?query=ffmpeg

even if fedora not suported it on the fresh install, you have a thing calles fedy, and, with a click, you install all the needed staff. The magic word is RpmFusion repo.

About Versions, on comits, if i understand it right, it is the #1837 the latest version? Is this the "Issue" number the version of qTox? Hmm, i need the full class to learn, in fact to even discover what is the nevest version, or build of qTox, and this is problem for many user, i think. Trust me, it is annoying. The users are familiar with go to "Help", or "About" in any software, and there, is the info about Version adn builds. On qTox, it is complicated. Nothing on Client about version.

But, anyway, we are far from the point here.

Unfortunatly, i can't build packages, i'm not so good on this. What i can offer is Hosting, and Web page design for qTox, if is needed. I have my own Servers and hosting in Switzerland, where i living.

We need somebody who can Build packages, and refresh the links here. Anybody?

**Comment by Getron** [comment]
and about compiling on Fedora 22 KDE 5.3, i run this:
sudo dnf group install "Development Tools"

and this is the error i have:

Traceback (most recent call last):
  File "/bin/dnf", line 36, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 185, in user_main
    errcode = main(args)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 84, in main
    return _main(base, args)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 134, in _main
    cli.run()
  File "/usr/lib/python2.7/site-packages/dnf/cli/cli.py", line 1077, in run
    return self.command.run(self.base.extcmds)
  File "/usr/lib/python2.7/site-packages/dnf/cli/commands/group.py", line 385, in run
    return self.base.env_group_install(patterns, types)
  File "/usr/lib/python2.7/site-packages/dnf/base.py", line 1253, in env_group_install
    res.groups, types)
  File "/usr/lib/python2.7/site-packages/dnf/comps.py", line 88, in install_or_skip
    logger.warning("%s, %s", str(e)[:-1], _("skipping."))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xbb' in position 7: ordinal not in range(128)

and that's it. I can't compiling.

dnf is funcional, i update my system with dnf, install softwares, no problems, just here, with dev tools.

Edit:

Ok, i found the problem, you should correct it on the page, it should be for Fedora 22 KDE:

sudo dnf group install "C Development Tools and Libraries"
(working)

and not

sudo dnf group install "Development Tools"
(not working)

**Comment by zetok** [comment]
@Getron no, "version" is here https://github.com/tux3/qTox/commits/master ← latest commit

**Comment by Getron** [comment]
@zetok yes, and this is what i mean, the #1837 is the latest, on 8.6.2015. I'm right?

**Comment by zetok** [comment]
@Getron no

**Comment by Getron** [comment]
What else is there? Sorry, i don't understand.

I wish, you understand me, if Tox want to be derivate like Skype, or in this way, i don't need to go anywhere to see the version of skype, just menu, click "About Skype", and voila - is that great?

You should give to users familiarity, functions, like users are familiar with. Don't try to reafind the circle. It is not good.

Hope you understand me.

I have no idea, how, or where, or what for version of Tox i have installed on my PC. No info about this on Client. And this is not a "user familiar", or user friendly client, at less, for now. Hope, this changes on the near future.

Please, send me a picture, to see, where i can see the latest version? Here:
https://github.com/tux3/qTox/commits/master
but, what indicate there a version? I'm confused.

Thank you, and hope for understanding.

**Comment by FatCache** [comment]
Can confirm similar bug is affecting my machine. 

I'm using qTox on ubuntu 15.04 straight from the PPA. When I receive a message, the icon begins to flash between "Light color tox" and "no-image-" icon. Like it's a place holder image.
![selection_003](https://cloud.githubusercontent.com/assets/8831324/8391531/febf3c54-1cdf-11e5-9b56-9fc16aab759d.png)

I also don't get any sound notification from qTox

**Comment by suhr** [comment]
I can't get light icon too btw. Even when I enable an option, the icon stays dark.

**Comment by FatCache** [comment]
I manage to get the light icon. But when I get the notification. It's
suppose to flash like in Windows. But on Linux it bugs.

I installed mine through the repos.

**Comment by aphirst** [comment]
I'm having this issue too, and was suggested to share my package versions. I'm using Arch Linux x86_64, with raw OpenBox launched by lightdm, and:

```
qt4 4.8.7-1
qt5-base 5.5.0-1
[other qt packages too]
qtox-git r3286.49f7a02-1
```

I also did a rebuilt of qtox-git and tox-git from the PKGBUILDs available in the (other) github repo, to no avail.

If there are any other package versions I should share, just let me know.

**Comment by FatCache** [comment]
I got mine fixed. The problem was with the icon set I was using which in my case was Numix. Reverted back to Ubuntu default, no problem,

**Comment by linux-modder** [comment]
@Getron  @zetok  I have been recompiling with no issues ON Fedora 22, @Getron please remove the  /etc/yum.repos.d/tox.repo and  provide   ls -la ~/path/to/qTox/  please
output like so (below)  should build no issues if not  please  advise which you are having in compile.
http://ur1.ca/n52qn

also  qtox --version   OR   /path/to/qtox ---version ( for me I usually have  /usr/local/bin/qtox and  ~/Git/qTox/qTox  -version once I  confirm ~/Git/.... is  good i replace  /usr/local/bin/qtox

**Comment by minj** [comment]
I have the same problem as @aphirst on Manjaro (openbox, lxdm).

It may have been caused by a recent QT upgrade 5.4.2 -> 5.5.0

**Comment by minj** [comment]
Confirmed. Downgrading to 5.4.2 and rebuilding qtox 'fixes' it

**Comment by linux-modder** [comment]
@minj on Fedora?

**Comment by minj** [comment]
@linux-modder as I've just said I am on Manjaro.

**Comment by aphirst** [comment]
Just wanted to confirm that this is still present, did a rebuild just now.
![screenshot2](https://cloud.githubusercontent.com/assets/1735556/9427994/cc6306a0-4999-11e5-81f9-891f8c304860.png)

**Comment by zetok** [comment]
![qt bug](https://cloud.githubusercontent.com/assets/3148759/9427986/120ff87e-4991-11e5-95a7-d5ab1ac474a0.png)
↑ on the left, icon of qTox compiled against Qt 5.4, on the right, qTox statically linked with Qt 5.5 under i3.

**Comment by suhr** [comment]
Can you actually find the bug on the qt bug tracker?

**Comment by zetok** [comment]
@suhr Qt is terribly broken when it comes to tray - e.g. is seems like they did fix #968 in 5.5, but broke something else, which renders tray icon less useful.

I didn't bother searching on Qt bugtracker, since it's rather quite obvious that it broke in Qt 5.5, since on Qt 5.4 it was slightly less broken.

Screenshot above shows 2 qTox instances running side by side - one is linked to Qt 5.4, other one to Qt 5.5…

**Comment by agilob** [comment]
Why I never can reproduce those tray errors?

**Comment by Getron** [comment]
@agilob Do you use a native Fedora 22 KDE x64 (KDE 5.4)? If not, try to install, and you will see.

Until now, the tray icon stay hidden, or not there on my fedora 22 KDE x64 (now, on KDE 5.4, to)

No one has idea how to solve this for KDE 5.4?

No tray (nor black or white) icon at all on Fedora 22 KDE x64. It doesn't work.

**Comment by linux-modder** [comment]
Seeing as I have  Fedora 22 xfce and  space to bolt on kde I'll see if its  qtox or kde.

**Comment by agilob** [comment]
@Getron I have archlinux with latest Plasma5.
How did you install/compile qtox? from source? which version of qt do you have?

**Comment by linux-modder** [comment]
@Getron, On Fedora 22 (with kde and qt5.5 --the current default when installing  kde desktop) I can not  reproduce your  lack of  color sanity on kde.   See below and if  I have missed something or  you see something glaringly  different  please let me know.

`(with xfce using qt5.5 and light icon)`
![qtox-xfce](https://cloud.githubusercontent.com/assets/5921776/10073444/f1b6b3f0-6296-11e5-8d7b-b72c25bdf969.png)

`(with kde plasma (and qt5.5) with light icon)`
![qtox-kde](https://cloud.githubusercontent.com/assets/5921776/10073445/f1ba3b74-6296-11e5-8ec1-b1eb81e18313.png)

(note:  my build is  git built and  at commit:c7b5337723fe291c5e12f87b74edc6f08523c966

**Comment by agilob** [comment]
@Getron would you be able to test this PR? It changes tray icon backed for KDE5 and GNOME3.
https://github.com/tux3/qTox/pull/2132

**Comment by zetok** [comment]
@agilob why not push that PR to `testing`, since now it doesn't have anything there that wouldn't be in `master` ?

**Comment by agilob** [comment]
it conflicts with current git history and I can't fix conflicts now.

**Comment by zetok** [comment]
![deleted](https://cloud.githubusercontent.com/assets/3148759/10083108/dcdad732-62f4-11e5-8d14-7fe13a4d8faa.png)

Shouldn't conflict now :)

**Comment by zetok** [comment]
@Getron could you test https://build.tox.chat/job/qTox-testing_build_linux_x86-64_release/11/artifact/qTox-testing_build_linux_x86-64_release.tar.xz ?

**Comment by Getron** [comment]
@zetok I have tested this one you sended to me, but, the same, no icon on tray. I have the breeze-dark theme, and breeze-dark icons. Maybe is this problem?

I have tested the newest one qTox, from 28.09.2015, but the same. No icon on tray. The "Light icon" doesn't change anything, no icon.

**Comment by linux-modder** [comment]
I checked with non breeze themes as well same  issue on anything kde Fedora 22

**Comment by Getron** [comment]
I don't compile qTox myself, i just use this version, download from here:
https://build.tox.chat/view/Clients/job/qTox_build_linux_x86-64_release/lastSuccessfulBuild/artifact/qTox_build_linux_x86-64_release.tar.xz

I think, it is the latest one (nightly builds)?

And the reason, why i'm use Fedora 22 Kde, is, that is the only one distro, that add my 2 SSD on Software RAID on Installing Fedora, without be an Expert on Linux, to add the RAID with extremly hard input lines, and so on... I have tested many other distros, but, no one do RAIDs like fedora - easy, one click - done. Many of these, it crash the installer if you try to install on RAID (just software RAID), like Manjaro, for example, it crashed every time on start of instalation...

But, ok, we are not here for distros... just to known, why i'm so focused and sticked on Fedora, and KDE - for modularity.

**Comment by ghost** [comment]
If I use the binaries, there's no tray icon (normal or light, doesn't make a difference). If I compile qTox myself, using the same commit as base (0ef39aa06af177061ab53c259ee9c71de2876264), the tray icon works.

Debian testing, freshly installed `kde-full` package (https://wiki.debian.org/KDE).

qTox 0ef39aa06af177061ab53c259ee9c71de2876264
KDE Plasma 5.4.2
Qt 5.5.1

**Comment by tux3** [comment]
I think this is one of the problems caused by using a static Qt instead of proper packages, hopefully we can start shipping real packages soon.

**Comment by bignaux** [comment]
Same here on LxQT 0.10.0 (tray plugin) / fresh qtox git / QT 5.7_alpha.
No light icon, no icon change on status change. 
CMST (QT5) systray icon works fine (connect/disconnect ...)

**Comment by linux-modder** [comment]
@Getron,
Still having  issue if you run it on F23 ?  https://tinyurl.com/live-respins

@kehugter,  can you try with a  compiled dynamic build?

@bignaux,   LxQT  is still using an ancient  version of  QT (confirmed with a friend) MOST QT things derp on F22 / F23  on LxQT.

**Comment by ghost** [comment]
@linux-modder not right now, I had to delete KDE. Will start a box if I have time today.

**Comment by bignaux** [comment]
@linux-modder : i'm sure i've recompiled all this stuff with Qt 5.7.0_alpha.

**Comment by ghost** [comment]
Tray icon works as it should in a KaOS box with all packages up to date using the latest qTox binaries.

qTox v1.3.0-117-gde48789
commit de4878909d75d9d4312db025f8c0fc30f9f79f39
Qt 5.5.1
Linux 4.4.5-1

**Comment by zetok** [comment]
#3151 was merged, and issue should be now mitigated. Could someone affected re-test with newest qTox?

**Comment by bignaux** [comment]
no issue for me now.

**Comment by zetok** [comment]
Well then, closing.

If someone can still reproduce, please comment for reopen.
