### ISSUE TITLE
Show icon in tray ignored on startup?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1823]
Hello

When I disable 'show icon in system tray', everything works as intended, but when I close qTox and then start it the next time, the tray icon keeps coming back to haunt me (the setting is still disabled in the settings screen). Perhaps the setting is not checked at start up?

Thanks in advance

**Comment by tux3** [comment]
This should be fixed now, make sure you have the latest version of qTox.

If you still have this issue, please leave a comment and post the qTox log.
