### ISSUE TITLE
qTox segfaults when playing with video settings during video call

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1824]
Description:
When one repeatedly changes video settings during a video call qTox segfaults.

Info:
OS: Hardened Gentoo Linux x86_64
Kernel: `4.0.4`
Qt version: `5.4.1`
FFmpeg version: `2.6.3`
qTox: de8eb9c69367de8304252a8850c8bd5a26077506

Reproducible: Always

Steps to reproduce:
1. Have an ongoing video call
2. Go to video settings, and start changing them, do it until qTox will crash

What happened:
qTox crashed

What should happen:
qTox should allow one to change settings, or prevent user from changing them

Additional info:

Backtrace: https://gist.github.com/zetok/d4a96f0f38bf0f471d94

**Comment by tux3** [comment]
Right. 
I spent a lot of time making sure qTox's video code can be multithreaded with minimum locking, and I forgot that FFmpeg isn't thread-safe ...

**Comment by dcapeletti** [comment]
Only I question, why FFmpeg is used instead of libav?.

**Comment by tux3** [comment]
libav doesn't support some of the features we need.

For example on Debian libav's libavdevice.h is practically empty.

**Comment by tux3** [comment]
This is fixed.
