### ISSUE TITLE
[Feature request] Allow "None" camera to be used

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1825]
I.e. user should have a possibility to make qTox not use camera, even if one will be available.

**Comment by Zer0-One** [comment]
+1

**Comment by SkyzohKey** [comment]
And this **must** be the default value. Same for microphone.

**Comment by An-dy** [comment]
+1 with optional broadcast of a static picture as "video source" please.

**Comment by ProMcTagonist** [comment]
+1

@An-dy It would be cool to have a settings box for a dedicated file to play when your camera is set to off, such as your static or an AFK message (think about streamers).

That should probably go in a different issue though.

**Comment by Balloon2mars** [comment]
+1 yes definitely safest feeling from uTox was being able to set audio/video input/outputs to 'none'
please.
