### ISSUE TITLE
[Feature request] Allow user to change video source during video call

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1826]

**Comment by tux3** [comment]
Note to self: Without restarting the call, obviously.

**Comment by linux-modder** [comment]
why would you want to change mid call tho ?   web conference ? like a screen capture  ?

**Comment by ProMcTagonist** [comment]
https://wiki.tox.chat/developers/gsoc/2015/ideas#multimedia_streaming

@linux-modder Users may want to switch webcams, or start streaming their desktop, or start streaming some file they've just finished. They shouldn't have to hang up and/or only choose one.

**Comment by linux-modder** [comment]
- 1 agreed used to have share desktop in utox not sure how hard / if even possible bringing that over to qtox would be....

**Comment by zetok** [comment]
Since it works after #2456 got merged, closing.
