### ISSUE TITLE
the debian packages still depend on opencv

### ISSUE THREAD

**Issue by cebe** [qTox/qTox#1827]
as far as I understood, qTox [does not depend on opencv anymore](https://github.com/tux3/qTox/blob/master/INSTALL.md#dependencies).

The package on the tox debian apt repo however does.

There also seems to be no build after June 3.

> qtox_1.0-1737_i386.deb                             03-Jun-2015 09:15             2324818
> https://repo.tox.im/pool/nightly/main/q/qtox/

**Comment by tux3** [comment]
Unfortunately, I'm not the maintainer of the Debian packages so I can't fix that.

We're aware that the builds are broken, and they should get fixed soon-ish.

**Comment by cebe** [comment]
is there any chance I can help with that? who is managing the repos?

**Comment by tux3** [comment]
That would be @stqism and/or @urras I believe.

**Comment by Ansa89** [comment]
The main problem is that (apparently) debian doesn't have a ffmpeg-dev package which is now required to compile qTox.

BTW this isn't a good reason to keep opencv as dependency.

**Comment by ProMcTagonist** [comment]
I get ffmpeg from deb-multimedia.org.

**Comment by Ansa89** [comment]
@ProMcTagonist: you need ffmpeg to run it, but who compiles qTox needs ffmpeg-dev.
Try `sudo apt-get install ffmpeg-dev` and apt _should_ tell you that there are no packages named ffmpeg-dev.

Does ffmpeg from deb-multimedia.org contain also dev libraries/headers?

**Comment by cebe** [comment]
as far as I see ffmpeg dev files are in the `libav*-dev` packages... e.g. `libavcodec-dev` not sure which of them are needed to compile qTox.

**Comment by cebe** [comment]
seems libav and ffmpeg are the same, some background: http://blog.pkh.me/p/13-the-ffmpeg-libav-situation.html

there are debian packages for ffmpeg in the unstable branch, not sure if they fit for building qTox though: https://packages.debian.org/search?keywords=ffmpeg-dev

**Comment by tux3** [comment]
FFmpeg and libav are not quite the same, qTox will not work with libav because it's missing some features.

On Debian the relevant packages are libav*-ffmpeg-dev, which are still in unstable.

**Comment by ProMcTagonist** [comment]
@Ansa89 the package names are libav*-dev from deb-multimedia.org

**Comment by Ansa89** [comment]
As @tux3 said: libav isn't supported.
For debian you need `libav*-ffmpeg-dev` from sid repos.
For ubuntu you can install `libav*-ffmpeg-dev` packages as of version 15.04.

**Comment by SkyzohKey** [comment]
@Ansa89 ffmpeg-dev doesn't works on Debian. I tried to make it run over 4 hours, without success.

**Comment by Ansa89** [comment]
As I wrote before:

> For debian you need `libav*-ffmpeg-dev` from sid repos.

Please note that "sid repos" means "unstable" and I only reported these information from the web without testing them.
Apart from that I never tried to manually compile ffmpeg on debian.

**Comment by SkyzohKey** [comment]
I tried to compile ffmpeg too, impossible to compile. :/

**Comment by suhr** [comment]
Fixed in pkg.tox.chat repo.

**Comment by zetok** [comment]
It will take some time until proper repos will be available - for time being, qTox binaries for Linux can be used: https://wiki.tox.chat/binaries#other_linux
