### ISSUE TITLE
qTox identified as junkware

### ISSUE THREAD

**Issue by hk1mm2** [qTox/qTox#1830]
Hello,
- It seems that qTox.exe is identified by GData as a junkware : I have sent the file to GData to test.

Thank you.

Regards.

**Comment by hk1mm2** [comment]
qtox.exe (32 bits) on VirusTotal (13/06/2015) : https://www.virustotal.com/fr/file/f628d7feacd86a5bf284be07f213087e2e6a1b1ccf8dafee7907f2b9e945e9f4/analysis/1434218142/

**Comment by zetok** [comment]
@hk1mm2 thanks for checking, I've added those to _The List_: https://wiki.tox.im/Problematic_antivirus_software#List_of_problematic_antiviruses

**Comment by hk1mm2** [comment]
@zetok you're welcome..
No response from GData, then I have resent the file, and reported again a false positive...awaiting...

**Comment by suhr** [comment]
It's not the first time: https://github.com/tux3/qTox/issues/731

**Comment by tux3** [comment]
Virustotal says it's being detected as adware by bad heuristics. I wonder if the AVs are getting suspicious because of UPX or if there's something in particular that trips them here.

**Comment by zetok** [comment]
@suhr thanks for reminding about that, added those too

**Comment by hk1mm2** [comment]
@suhr : "qtox-updater.exe" is no longer detected as a virus by GData. At this time only "qTox.exe" is suspicious by GData.

**Comment by hk1mm2** [comment]
@zetok : "qtox-updater.exe" is no longer detected as a virus by GData. At this time only "qTox.exe" is suspicious by GData. Identified as: Junkware - Gen:Variant.Adware.SMShoax.9 (Motor A).

**Comment by hk1mm2** [comment]
## Hi. qTox.exe is no loger detected as a virus by GData :) ........... Response of GData...........

Dear G DATA Customer,
We have received a response from our SecurityLabs about your virus samples:
"The submitted file is currently not detected by our scanners."

**Comment by agilob** [comment]
close please

**Comment by hk1mm2** [comment]
@Ragilob : The second problem still remain -> qTox is doesn't work as portable mode, it create files under windows user folder.

**Comment by Zer0-One** [comment]
@hk1mm2 In the future, try to make sure to make a seperate bug report for each unrelated set of bugs

**Comment by hk1mm2** [comment]
Hi.
Again, qTox.exe is identified as "Junkware - Gen:Variant.Adware.SMShoax.9 (Motor A)" by GData. I have resent the file with a message to GData !!!

**Comment by hk1mm2** [comment]
Solved.
