### ISSUE TITLE
Asynchronous history saving

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#1831]
Sending simple text messages can be ridiculously slow because of the history being saved to disk in the GUI thread. qTox can spend up to several seconds in disk sleep with the GUI frozen for large messages.

Saving the history asynchronously means there is a small interval right after a message is sent where in the event of a power loss of crash, that message may not be saved in the history. However we'll still use SQLite in synchronous mode, just in another thread, so there is no risk of the history getting corrupted by a crash or loss of power.

This would visibly improve GUI responsiveness on computers wit spinning rust based storage.

**Comment by zetok** [comment]
This was done some time ago, and user is available to choose whatever mode of operation they want through GUI; closing.

**Comment by agilob** [comment]
Do you still have that script that floods someone with thousands messages per second?

**Comment by zetok** [comment]
Well, not thousands (probably), but it should be possible to get hundreds per second: https://github.com/zetok/tox-rust-neurological-warfare-bot 

> Sending start multiple times increases speed at which bot sends spam.

ID of running bot: C7719C6808C14B77348004956D1D98046CE09A34370E7608150EAD74C3815D30C8BA3AB9BEB9

Though with faster speeds, (e.g. x9 in my case) qTox simply hangs, and goes down, crashing & burning, producing backtraces that go in dozens of thousands of stack frames…

For other people (@TheSpiritXIII) even "slowest" speed was causing qTox to hang.
