### ISSUE TITLE
Play sound when call ends

### ISSUE THREAD

**Issue by codedust** [qTox/qTox#1832]
When a call ends due to an error (especially on unreliable internet connections) there is no acoustical feedback of the event. This can be really annoing when an application runs in fullscreen mode and you don't see any visual notifications.

**Comment by zetok** [comment]
Perhaps #2093 / #2094 PRs would help with this issue.

**Comment by ProMcTagonist** [comment]
We really need a sound designer. Skype's noises are instantly recognizable and all very suited to their uses.

**Comment by codedust** [comment]
:+1: Maybe a blog post asking for some help in terms of audio (something like "Is there someone out there who has experience in sound design (designing ringtones, notification sounds) and is willing to participate in the Tox project? (no programming experince needed)") would be helpful.

**Comment by agilob** [comment]
> Maybe a blog post asking for some help in terms of audi

do it now!

**Comment by codedust** [comment]
cast (blog post) @installgen2 @nurupo

**Comment by installgen2** [comment]
I'll work on a blog post soon

**Comment by codedust** [comment]
:+1:

**Comment by zetok** [comment]
> We really need a sound designer.

Update: there is https://github.com/Tox-Clients/Tox-Sounds , thanks to @abique

**Comment by ProMcTagonist** [comment]
Neat. Eagerly awaiting UI sounds. Watched.

**Comment by codedust** [comment]
:+1: nice!

**Comment by abique** [comment]
Hello, I'm happy that you're happy :)
I think it would be helpful to create issues on https://github.com/Tox-Clients/Tox-Sounds to describe which notification you need.

Thank you :)

**Comment by zetok** [comment]
Made the issue https://github.com/Tox-Clients/Tox-Sounds/issues/1 `:)`

**Comment by sudden6** [comment]
This is now implemented.
