### ISSUE TITLE
Friend list is too wide

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#184]
Looks like it tries to show all the status of each friend.

**Comment by zetok** [comment]
Still present on https://github.com/tux3/qTox/commit/18f0e05778a1eb599db3ca7a3bbb504f4f773bce
![2014-08-17 qtox graphical issue](https://cloud.githubusercontent.com/assets/3148759/3944642/73347ddc-2610-11e4-88bd-4dd2c231e796.png)

**Comment by tux3** [comment]
Still broken on i3wm

**Comment by dubslow** [comment]
Still broken for me, and I can't resize the friends list in any way, thinner or wider

**Comment by krepa098** [comment]
I'm pretty sure the minimal size of the side panel currently depends on your own username and status message.

**Comment by dubslow** [comment]
Hmm yes, that appears to be, but... if I have a long status, that just forces the width to be ultra unwieldy... let me test your new commit though.
