### ISSUE TITLE
Message not highlighted when your nick contains emoticons/emojis

### ISSUE THREAD

**Issue by Ansa89** [qTox/qTox#1844]
If your nickname contains at least one emoticon/emoji and someone write your nickname in chat, then the message isn't highlighted.

Tested with tux3/qTox@f0f2776050622982883925bdaad620a20f8eaad3.

**Comment by zetok** [comment]
also doesn't work when name is set to `:3`
qTox ce2c8309a28dc49ec005610791062ee55633ef80

**Comment by zetok** [comment]
Actually, it's a duplicate of #1167, thus closing.
