### ISSUE TITLE
Bugs reported on reddit

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#1845]
https://www.reddit.com/r/projecttox/comments/393m0l/qtox_debian_windows_video_chat_results_in_crash/
My friend and I want to switch over to using qTox for our vidchatting, but we've run into a handful of bugs:
- in the audio/video settings section, it doesn't seem to detect my built-in camera. it will detect my webcam when it's plugged in via USB, though.
- the opposite goes for my friend. when they are using their webcam (same make as mine), tox won't detect it, but will always fall back on their built-in webcam. (there are no settings for switching between video inputs, so it's very hard to tell exactly what tox is doing).
- when I call and they try to answer, it crashes qTox for them. they get an error message and then before they can click OK or Close, qTox and the error window disappear
- when they call and I answer, there is no audio for either of us, among the above problems!

Some of them are duplicates (afair)

**Comment by tux3** [comment]
> (there are no settings for switching between video inputs, so it's very hard to tell exactly what tox is doing

So, they are using an outdated pre-ffmpeg version. This is way too old to be useful, the video code has been completely rewritten (of course there are still probably bugs, but not the same ones).

**Comment by seankhl** [comment]
Hi, I'm the person who made the reddit post.

I am using the current executable in the Debian repository, and my friend got their executable from the Tox downloads page. Is it too old? Should I compile from scratch? What's the best way to install Tox/qTox for Debian?

**Comment by tux3** [comment]
@seanlaguna Hi, the repository is usually the recommended way to install qTox.
However (and I know it's not your fault) the Linux packages are currently seriously outdated, so if you didn't compile from scratch you'll have an older and buggier version.

If you know how to compile from scratch, that's definitely a possibility, but we'll be working on fixing the packages so they're up to date again. I'm not the person maintaining the packages, so unfortunately I can't really give a timeframe for when they'll be working again.

**Comment by seankhl** [comment]
@tux3 thanks for letting me know.

I compiled toxcore and qTox from scratch. I have yet to try to vid again, but do you think the problems on the Windows side of the connection could potentially be resolved just by me fixing my version of qTox? I'll update when I try again this evening and let you know.

I will say I determined that, on Debian Squeeze/Sid, I had to add a dependency (discovered through a failed compilation): `libavdevice-dev`. I'm using deb-multimedia, the non-ffmpeg packages, and they all work just fine it seems.

Finally I failed one toxcore `make check` test but obviously this isn't the place to report that, so I'll report it over in the toxcore repo as well.

The rest of the errors I've gotten (from poking around) are segfaults when my camera is already in use and I'm on the A/V settings page (fairly reasonable circumstance to trigger a segfault, but still not ideal) and when I have an external monitor plugged in, the desktop isn't detected correctly (this could be an issue with screen dimension reporting in Debian and not toxcore/qTox themselves).

Run from the terminal, while changing my video resolution/fps settings, I see messages like this:

```
[swscaler @ 0x34d1560] Warning: data is not aligned! This can lead to a speedloss
...
[video4linux2,v4l2 @ 0x3deab20] The driver changed the time per frame from 1/7 to 2/15
[14:26:59.854] src/video/videoframe.cpp:109 : Critical: None of the frames are valid! Did someone release us?
[video4linux2,v4l2 @ 0x21b2420] The driver changed the time per frame from 1/30 to 1/10
[x11grab @ 0x21adca0] Stream #0: not enough frames to estimate rate; consider increasing probesize
[video4linux2,v4l2 @ 0x2c7b320] The driver changed the time per frame from 1/30 to 1/10
[video4linux2,v4l2 @ 0x18193c0] The driver changed the time per frame from 1/20 to 1/10
[video4linux2,v4l2 @ 0x23ce620] The driver changed the time per frame from 1/15 to 1/10
[video4linux2,v4l2 @ 0x2fd62c0] The driver changed the time per frame from 1/30 to 1/10
[video4linux2,v4l2 @ 0x21aa4c0] The driver changed the time per frame from 1/30 to 1/10
[video4linux2,v4l2 @ 0x25b6120] The driver changed the time per frame from 1/24 to 1/10
[video4linux2,v4l2 @ 0x25b6120] The driver changed the time per frame from 1/20 to 1/10
[video4linux2,v4l2 @ 0x2159300] The driver changed the time per frame from 1/15 to 1/10
[video4linux2,v4l2 @ 0x25b6120] The driver changed the time per frame from 1/30 to 1/10
```

etc.

Let me know anything I can do to help correct/debug these things. Do I need to use the ffmpeg versions of the libav\* development files? Debian doesn't play nicely with ffmpeg as you know but libav\* should be a drop-in replacement.

**Comment by tux3** [comment]
@seanlaguna 

> The rest of the errors I've gotten (from poking around) are segfaults when my camera is already in use and I'm on the A/V settings page

That's a known problem, and we're working to fix this, but it might take some time.

> when I have an external monitor plugged in, the desktop isn't detected correctly (this could be an issue with screen dimension reporting in Debian and not toxcore/qTox themselves).

That's also been an apparently pretty common issue, but I only have one monitor so I haven't been able to do much about that. Can you describe in more details what the problems are with multiple monitors?

> Do I need to use the ffmpeg versions of the libav\* development files? Debian doesn't play nicely with ffmpeg as you know but libav\* should be a drop-in replacement.

FFmpeg would be better, we don't officially support libav so some features may be degraded, not work, etc. On my debian last time I checked qTox didn't compile with libav. Perhaps that changed.

Thanks.

**Comment by seankhl** [comment]
![screenshot of desktop with external monitor](https://cloud.githubusercontent.com/assets/1224201/8072531/c1d2e806-0edc-11e5-9a1f-3a6e7be0d563.png)

This is the image that I see.

Also can you please speak to the Windows version? Does it also need to be compiled from scratch?

I'm confused why you say that the version in the Debian repo is "way too old" when supposedly it is version 1737, which supposedly was compiled on June 3 according to this page: https://jenkins.libtoxcore.so/job/qTox-Linux-pkg/lastSuccessfulBuild/

I'm skeptical that the Windows binary is any different since my friend can't control their video settings either. And they're not exactly a seasoned programmer and as we all know compiling for Windows is a total pain (doing so would require downloading all of qt, which is huge).

If I really have to walk them through compiling on Windows, I will, but I'd like to avoid it at all costs. Let me know what Windows version is the easiest to install that has these bugs fixed.

**Comment by tux3** [comment]
@seanlaguna The Windows version should be up to date.

As for the Linux packages, the package themselves are built, but the qTox source they use is outdated : https://jenkins.libtoxcore.so/job/qTox-linux-i686/

**Comment by agilob** [comment]
bump?
