### ISSUE TITLE
Translated string in search menu is overly truncated

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1849]
Description:
Translated strings aren't displayed in whole available space and are truncated instead, leaving empty space that could be used to fit few more characters in.

Info:
OS: Hardened Gentoo Linux x86_64
qTox f0f2776050622982883925bdaad620a20f8eaad3

Reproducible: Always

Steps to reproduce:
1. Decrease width of your contact list
2. Set language with longer strings, e.g. `Polski` or `Українська`

What happened:
String is truncated more than it needs to be.

What should happen:
String should fill available space.

Additional info:

![truncated](https://cloud.githubusercontent.com/assets/3148759/8078365/3a3b5b8e-0f55-11e5-929f-a4f3630971e1.png) ![trunc](https://cloud.githubusercontent.com/assets/3148759/8078390/7743be9a-0f55-11e5-8b32-717397e49a27.png)

↑ truncated
# 

![actually displayed](https://cloud.githubusercontent.com/assets/3148759/8078367/40e8676a-0f55-11e5-9ea7-6dc3b9528949.png) ![full](https://cloud.githubusercontent.com/assets/3148759/8078406/8c94d6bc-0f55-11e5-95a4-147b1ea93cb5.png)

↑ displayed in full
#

**Comment by Diadlo** [comment]
Fixed
