### ISSUE TITLE
place tox_save and utox_save in .config

### ISSUE THREAD

**Issue by nicokoch** [qTox/qTox#185]
Tested on archlinux.
The tox_save and utox_save files are currently saved in the home directory. They should either be dotfiles or placed somewhere in ~/.config/ .

If theres a command line option to specify the save files to use, please enlighten me.

**Comment by tux3** [comment]
On linux the save files should be in ~/.config, as per <a href="http://qt-project.org/doc/qt-5/qstandardpaths.html#StandardLocation-enum">Qt's documentation</a>
What qTox does is asking Qt to put those files in the user settings path, maybe your system is misconfigured ?

There is also an option to store save files in the working directory, but that's probably not what you want.

**Comment by prurigro** [comment]
I agree that this would be a good change to make. I noticed another Tox client (though can't remember which atm) stores it's settings in ~/.config/tox/client-name.ini; maybe ~/.config/tox/qtox.ini would be a good place?

**Comment by krepa098** [comment]
I guess Kokxx is actually talking about uTox (?). I agree with prurigro though. The config shouldn't just be called settings.ini if there are other clients using that directory.

**Comment by prurigro** [comment]
@krepa098: It's possible @Kokxx is talking about **utox**, but I have this behaviour as well with **qtox** on _Arch Linux_, so I assume he's talking about **qtox**.

I'm currently maintaining the [Arch package in the AUR](https://aur.archlinux.org/packages/qtox-git/) (as well as the [ArchAssault package](https://archassault.org/packages/archassault/x86_64/qtox-git/)), and the `PKGBUILD` (package build script) can be found [here](https://aur.archlinux.org/packages/qt/qtox-git/PKGBUILD). Can anyone see anything that would be incorrectly changing the behaviour from saving `settings.ini` in `~/.config` to saving it in `$PWD/$HOME`? I still think `~/.config/tox/qtox.ini` would be a better location than `~/.config/settings.ini`, but I'd rather have things working the way they're intended if something I'm doing is causing them to behave some other way.

**Note**: If anyone isn't familiar with a `PKGBUILD`, the `prepare()` function is run first, then `build()` followed by `package()`, and everything else is just metadata.

Cheers!

**Comment by krepa098** [comment]
@prurigro: The settings path is given by _QStandardPaths::writableLocation(QStandardPaths::ConfigLocation) + "/tox"_
which should never evaluate to _~/.config_. Your PKGBUILD seems to work just fine on my machine. Everything is stored inside  _~/.config/tox/_.

**Comment by nicokoch** [comment]
Hey guys, in fact I picked the wrong repo. I was having this problem with uTox (sorry for the confusion).

I just installed qTox and everything is fine. So thanks for a superior product ^.^

**Comment by prurigro** [comment]
Sorry about the wait- I had to downgrade toxcore to get qtox to work again and test, but it does seem like the settings are no longer being stored in the home directory for whatever reason, so I'm not sure why my experience was different before (I don't have utox, so it definitely wasn't that)- in any case, thanks for the replies and help sorting all this out!
