### ISSUE TITLE
You still ship opencv binaries in "qTox-win64-upx" and "qTox-win64-nsis"

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#1851]
~~Same counts for 32 bit.~~
Because of this I assume that only a few people run the master branch on windows.

**Comment by towlie** [comment]
I could imagine that there are some issues that are already solved. Like this one: https://github.com/tux3/qTox/issues/1822
He uses the installer which still uses openCV.

**Comment by towlie** [comment]
The 32 bit version is fine.

**Comment by tux3** [comment]
This is fixed.
