### ISSUE TITLE
Question: Submitting translations

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1852]
I have enjoyed qTox very much so far and I'd like to contribute to it in some way. I figured that maybe I could make a translation, so I found [this page](https://github.com/tux3/qTox/wiki/Translating), which (as I believe) led me to use Git and Qt Linguist. 

I somehow managed to clone the code and open the translations, but I got confused pretty quick about Git usage. I'm fairly sure that I'd be able to learn how to use Git, but I'm really just interested in contributing a translation, and it feels like I won't use 90% of experience I'll pick up on the way.

Therefore, I'd like to ask if I can contribute without using git at all, or if there's at least a simple and straightforward guide I can follow without needing to worry about extra things.

**Comment by agilob** [comment]
If you don't want to learn git because you won't use it in the future just paste content of your translated file here and we will merge it.

Do you use windows or linux/mac?

**Comment by ghost** [comment]
@agilob I use GNU/Linux. Should I use Qt Linguist to create the translated file and upload it somewhere?

**Comment by suhr** [comment]
There's a lot of guides into git, including interactive one like https://try.github.io/ or http://pcottle.github.io/learnGitBranching/. You only need to create a new branch, commit you changes there, push it and create a pull request.

**Comment by ghost** [comment]
@suhr What about updates? qTox gets new commits all the time; should I get my branch up-to-date before I make a pull request, or should I not worry about that?

**Comment by suhr** [comment]
You shouldn't worry about it if you create a new branch.
