### ISSUE TITLE
File-open dialogue does not respond on QT 5.4.1

### ISSUE THREAD

**Issue by CthUlhUzzz** [qTox/qTox#1856]
File-open dialogue does not work on QT 5.4.1

**Comment by zetok** [comment]
Works for me.
Please either provide more info → https://github.com/tux3/qTox/wiki/Useful-bug-reports , or close the issue.

**Comment by CthUlhUzzz** [comment]
Not sure, maybe this is a KDE problem. Dialogue opens, but does not respond to clicks. Helps only the forced killing process.
![system](https://cloud.githubusercontent.com/assets/6465228/8129627/b091324e-1113-11e5-840c-434edf5f6817.png)
![qtox](https://cloud.githubusercontent.com/assets/6465228/8129701/7ce6aaa4-1114-11e5-8a31-a5350b3f8958.png)

**Comment by quininer** [comment]
I have the same problem.

**Comment by CthUlhUzzz** [comment]
I checked out a bug on clean systems. On Kubuntu 15.04 reproduced the bug, on Kubuntu 15.10 alpha2 - no. I'm surprised , but I would like to find out what caused this behavior.
![snapshot1](https://cloud.githubusercontent.com/assets/6465228/9040115/95d9f012-3a08-11e5-9ce8-ec32fd63272a.png)

**Comment by CthUlhUzzz** [comment]
The same bug also observed in qTransmission.

**Comment by agilob** [comment]
apparently bug in Qt, I'm not surprised.
