### ISSUE TITLE
qTox crashed due to rapid joins/leaves in groupchat

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1858]
Description:
qTox crashed when someone was changing their nick, rapidly joining and leaving groupchat.

Info:
OS: Hardened Gentoo Linux x86_64

Reproducible: ~~Rarely~~ Sometimes

Steps to reproduce:
1. Be in groupchat
2. Rapid nick changes, joins and leaves..?
3. ???
4. Crash

What happened:
qTox crashed.

What should happen:
qTox shouldn't crash.

Additional info:
Backtrace: https://gist.github.com/zetok/3c1c242f4af955b640a2

Also some other people crashed too, and my bot crashed.

**Comment by ghost** [comment]
+1
my qTox also crashes under these same circumstances, using qTox from Tox repo

**Comment by Balloon2mars** [comment]
Windows 7 x64 qTox crashed once at the beginning of this type of spamming.
Manjaro (Arch) x64 qTox crashed 2 times during this type of spamming (the first time might have been after 50 or so of those spam messages, and the second time might have been after several intervals of 30-60 messages.)

**Comment by zetok** [comment]
Apparently bot crashed due to bug in rstox, now fixed: https://github.com/suhr/rstox/commit/ab645038ef387893ce670a1dd220deb294872425

**Comment by linux-modder** [comment]
mine  crashed (qtox) this morning as well shortly after this (close enough in time to believe not caused by some other trigger )   Fedora 22 (x64) using the repo build  willing to  drop logs  if needed.

**Comment by zetok** [comment]
Ok, it's really reproducible. 2 qTox instances crashed again. One few days old (this one survived earlier events), and the other one, which was brand-new. I've updated backtrace with more stuff.. Which doesn't seem useful, but…

**Comment by zetok** [comment]
so, qTox crashed again, this time after MMO bot war over groupchat title. Even then it was due to problems with unknown entities in groupchat:

```
[22:21:24.423] src/core/core.cpp:575 : Debug: "Group namelist change 1:3 1"
[22:21:46.122] src/core/corefile.cpp:276 : Debug: "Received avatar request 48:65536, and we have it in cache"
[22:24:29.056] src/core/core.cpp:991 : Warning: getGroupPeerName: Unknown error
[22:24:29.072] src/core/core.cpp:991 : Warning: getGroupPeerName: Unknown error
[22:24:29.072] src/core/core.cpp:991 : Warning: getGroupPeerName: Unknown error
[22:24:29.072] src/core/core.cpp:1006 : Warning: getGroupPeerToxId: Unknown error
[22:24:29.072] global/qglobal.cpp:2876 : Fatal: ASSERT failure in QList<T>::operator[]: "index out of range", file /usr/include/qt5/QtCore/qlist.h, line 486
```

What was different, is that qTox hanged for several minutes at 100% CPU usage, and that allowed to get some flamegraph: https://d.maxfile.ro/xyvocsfvms.svg

**Comment by Balloon2mars** [comment]
Actually during this recent spam-fest, I tried to leave groupchat in order to clear it for a while and then come back in, so I waited 2 or 3 minutes after leaving groupchat and then when trying to join back in that's another time qTox crashed for me, in addition to crashing from the spamming.

**Comment by zetok** [comment]
Still happens on 1758928b4fe0720cb7b07e59ab1a2ecf40255262 + patched with dbb6d0d2cea60e1ddb4f4a97cc36de6dbf809121

This time though rather than SIGABRT, there was SIGSEGV

backtrace: https://gist.github.com/zetok/6a14d47e66be62209a51

**Comment by zetok** [comment]
still happens on 965f871d0c88eac6752a9a84833c77d92922715a

**Comment by sudden6** [comment]
Closing since #5113 is probably fixing this, please open a new issue if this is still an issue.
