### ISSUE TITLE
Audio device is kept open even when not in use which causes uneeded CPU usage

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#1862]
Make use of this http://kcat.strangesoft.net/openal-extensions/SOFT_pause_device.txt

**Comment by tux3** [comment]
The link you posted is only for the output device, we can do that. For the input device there's a bug in OpenAL soft where after stopping the capture it can't be restarted, I can't really fix that until the OpenAL fix trickles down.

**Comment by towlie** [comment]
@tux3 It would be already good if you do that for output devices because it decreases CPU usage on windows at least.
As qTox behaves now it causes the windows audio service to waste CPU time (5 % usage).

**Comment by towlie** [comment]
Oh and I tested this function on uTox and it solved the CPU problem if you only resume the device when needed.

**Comment by zetok** [comment]
#2094 contains some hack that most likely would help with (close?)  this issue.

**Comment by towlie** [comment]
@zetok Yes, this will fix the issue. The hack only fixes an openAL bug.

**Comment by towlie** [comment]
Until now this issue will not be solved by https://github.com/tux3/qTox/issues/2415 see https://github.com/tux3/qTox/pull/2415#issuecomment-149213985

**Comment by towlie** [comment]
This is not fully solved. Successor:https://github.com/tux3/qTox/issues/2435
