### ISSUE TITLE
uTox to qTox video call can DoS the PC that runs qTox [Windows 7]

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#1863]
- Run qTox and uTox 
- make a video call
- Disable the video stream on uTox so it only sends audio in this video call (clicking the red video call button)
- close qTox (right click the tray and quit)

After closing I hear my HDD going wild (it writes something to pagefile.sys) and qTox slowly eats all RAM it can find.
You have two choices now: 
Kill the process instantly or click some taskbar icon so your screen will turn black forever.

**Comment by iamunknown2** [comment]
~~The beauty of Windows~~ When you mean close qTox, do you mean minimize it to the system tray, or do you mean completely quitting it?

**Comment by towlie** [comment]
With close I mean completely quitting it. But it will stay as dead process.

**Comment by tux3** [comment]
I can't reproduce, does it still happen for you with the latest qTox?

For me qTox just quits cleanly on a freshly compiled version.

**Comment by towlie** [comment]
I cannot reproduce it anymore. Maybe your fixed it with your latest av changes?

**Comment by tux3** [comment]
I also just completely got rid of UPX for Windows builds, this seems to have magically fixed a lot of Windows only bugs.

**Comment by towlie** [comment]
I never used these upx builds. Do you have some example issues?

**Comment by tux3** [comment]
The Desktop and None video options weren't showing the settings for some unfathomable reason, there were strange crashes using video code at the most random times, closing qTox while there was a video call on would block qTox, deadlocked using 100% CPU, waiting for a thread to terminate, in a state where most debuggers were somehow not able to attach to it. And there was the unexplained extra memory usage. 

I usually test qTox on Windows with my IDE's builds, not Jenkins' UPX'd builds, so I didn't notice just how bad an effect UPX had until now.
