### ISSUE TITLE
Windows version vs Linux version

### ISSUE THREAD

**Issue by iamunknown2** [qTox/qTox#1864]
When I installed qTox on my Linux laptop, there was no signing up for a "Tox account" (there were Tox IDs instead). On the other hand, the Windows version of qTox requires you to set up an account with a **password** - if you didn't set one up, you wouldn't be able to use qTox. I am aware that the Windows version was a nightly build. Was it a change in toxcore that required you to set up an account with a password?

As I'm pretty sure that toxcore doesn't require a password to encrypt your chat, I'm sure that the password is for LOCAL data encryption (encrypt data file/chat history). I don't see the point of forcing Windows users **exclusively** (Linux version doesn't force you to create a profile) to use an account system **with passwords**.

**Comment by ProMcTagonist** [comment]
Linux builds are broken and outdated

**Comment by iamunknown2** [comment]
Not for me. qTox runs just fine (well, haven't tested it out with others yet). Also, could you provide some sources about Linux versions being outdated? Windows versions, according to the Tox wiki, are nightly (more unstable than alpha) builds.

**Comment by ghost** [comment]
> sources about Linux versions being outdated

https://github.com/tux3/qTox/issues/1845#issuecomment-110454466
among others. There are often comments about it at IRC too.
The packages are about one week old.

> nightly

I think it was also mentioned many times that in Tox related things, nightly is _stable_ (Tox is alpha anyway). Anything older than a few days (or a few commits) is outdated.

**Comment by iamunknown2** [comment]
K. Issue closed.
