### ISSUE TITLE
Can't reopen video window after closing (without restarting call)

### ISSUE THREAD

**Issue by iamunknown2** [qTox/qTox#1865]
How to replicate issue:
1. Start a video call
2. Accept the call, and close the window with the video in it.
3. You can't get the video back unless you hang up and start the video call again!
What it should've done: Provide an option to open the video window again.

**Comment by zetok** [comment]
ce2c8309a28dc49ec005610791062ee55633ef80 is also affected

**Comment by tux3** [comment]
This is essentially just not implemented, the current video GUI is more or less temporary, the pan was to redesign it properly and fix all those glaring flaws at the same time.

I'd like to get rid of the floating video windows if possible, maybe integrate the video feed in the main GUI like Skype does?

**Comment by zetok** [comment]
> I'd like to get rid of the floating video windows if possible, maybe integrate the video feed in the main GUI like Skype does?

I don't know about other people, but I for one am not quite a fan of what skype does in regard to that.. (note that skype allows to have "separate" windows for video)
With that being said, I don't know about better way to handle it.

I think that @TheSpiritXIII is working on something that could be at least ~related to this?

**Comment by iamunknown2** [comment]
Perhaps we should do something like this:
![qtox](https://cloud.githubusercontent.com/assets/11188939/8267109/7ce89454-1786-11e5-9676-ad73af89bed3.png)
And/or maybe show the same thing above from the system tray...

**Comment by TheSpiritXIII** [comment]
Yes, I will be adding an option to embed the video feed into the chat in a few weeks.

@iamunknown2 That doesn't seem too bad, provided it comes with an expand button and a popout button. Closing a popout video can make it move there, perhaps. As for the system tray, I'm not sure how feasible that would be. It requires knowing where the system tray is. No doubt, this would reqiure some platform specific code.

**Comment by ProMcTagonist** [comment]
Video should be embedded between the chat form and the friend's status / group topic bar. You should also be able to pop out the video into its own window with call controls along the bottom of the frame.

**Comment by zetok** [comment]
Issue is no longer reproducible, given that now video is embedded in chat window, thus closing.
