### ISSUE TITLE
qTox doesn't compile with Qt version 5.6

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#1868]
Build log: http://lpaste.net/8177627979375968256
Qt version: 5.6

**Comment by agilob** [comment]
cant reproduce with 5.4.2

have you tried `make clean && rm Makefile && qmake && make`?

**Comment by suhr** [comment]
I use portage to install qTox.

> cant reproduce with 5.4.2

Compiled before with Qt 5.5. Probably this issue related to Qt version 5.6.
Anyway, it should be fixed.
