### ISSUE TITLE
update not completing at restart

### ISSUE THREAD

**Issue by qw3ry** [qTox/qTox#1870]
It seems to me that the updater is not properly completing the update if I restart my machine:
1. qTox prompts me for an update download, I confirm
2. I do not notice qTox telling me anything anymore
3. I shut down my machine when I finished working
4. I restart my machine, qTox requests to install the update
5. When the updater has finished, qTox prompts me for an update to download
6. repeat

I am on Win8.1, 64bit
As I do not know how to check the installed version I do not know when the update really occures.
If I leave out steps 3 and 4 and only restart qTox the update works fine.

**Comment by qw3ry** [comment]
#1715 would resolve this as well, I guess.

**Comment by tux3** [comment]
This should be fixed now, and the new updater will go online very soon.
