### ISSUE TITLE
[Regression] No way to import profile

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1872]
Since new login window was introduced, qTox doesn't allow importing profiles any longer.

I think that `Import profile` should be added as an option in login window, above `New profile`. Or perhaps below it?

When selected, it should:
- allow for importing profile through `drag & drop` - i.e. drag profile file into designated for that rectangle in login window to import profile
- allow for importing profile file through file picker

About `drag & drop` - something like img.bi has, but with `Drop profile here or just click` and `Import`? (and obviously colour scheme fitting qTox):
![e.g. img.bi](https://cloud.githubusercontent.com/assets/3148759/8162414/f22edf9a-1374-11e5-84a6-716b1c2abe86.png)

**Comment by tux3** [comment]
We currently auto-import profiles that are in the Tox config dir. 
So importing/exporting profiles is a bit unintuitive right now, since profiles are split into several files.

So that button would essentially accept any kind of profile file (.tox, .qtox_history, .ini, ...), copy paste anything that looks related in the config dir and try to import it?

**Comment by zetok** [comment]
> So that button would essentially accept any kind of profile file (.tox, .qtox_history, .ini, ...), copy paste anything that looks related in the config dir and try to import it?

Um, no. It should currently accept only `.tox` files, and eventually that could be extended to accept other kind of file, that would be a `qTox profile` containing all the data, i.e. `.tox`, `.ini`, `.qtox_history`. Until there will be some specification on how that "bundle" should be done (preferably in STS, so that other clients could adhere to it too) accepting only `.tox` files sounds like sanest available choice to me…

**Comment by Zer0-One** [comment]
The STS should specify an "export" format for tox profiles. Probably some type of archive. Once that's put into writing, you can just write something to process the one file.

**Comment by ByteCommander** [comment]
So how does exporting and importing profiles now work manually, as it's still not implemented?
Which files do I need to copy in order to replicate my profile on another device? May I rename files during the transfer?

**Comment by zetok** [comment]
Note:
- part that should be implemented is importing via file picker
- there was a PR that seemed to do the job: #2140

# 
- drag & drop way of importing possibly needs more discussion or that idea needs to be discarded
