### ISSUE TITLE
flat emoticons

### ISSUE THREAD

**Issue by nullgemm** [qTox/qTox#1873]
I just released a flat version of my emoticons pack. Download it [here](http://www.mediafire.com/download/89u793awkcwcwo4/toxic_clones_v2_flat.zip), and see [here](http://cylgom.net/projects_details.php?id=11) for details & preview.
I also made [a github repo](https://github.com/cylgom/toxic-clones) in case I remember to update them...

**Comment by sudden6** [comment]
We now use emojiOne, which provides a much bigger set of flat emoticons.
