### ISSUE TITLE
Cleanup the settings interface

### ISSUE THREAD

**Issue by markwinter** [qTox/qTox#1877]
The settings interface needs to be cleaned up so it feels less claustrophobic. It also needs to have less lines and boxes to better match the contacts pane.

Here's a quick design to show something I think would be better, http://i.imgur.com/zvHJVMH.png - This is a bit too plain and white but hopefully you understand what I mean

In the bottom left the tabs also don't line up to the edges (both the cog wheel, and the add contact) but it would look better if they did

**Comment by agilob** [comment]
I started working on [this](https://github.com/tux3/qTox/pull/1640)  (screenshots are not uptodate) today, there are plenty of git conflicts in the code. If you know how to implement it, send ma a diff/patch or commit.

**Comment by ProMcTagonist** [comment]
+1 for big tabs without pointless header

**Comment by agilob** [comment]
@ProMcTagonist done in https://github.com/tux3/qTox/pull/1882

![light1](https://cloud.githubusercontent.com/assets/2544251/8228577/ceac5fea-15a7-11e5-89fa-cecf9464c0f2.png)

**Comment by ProMcTagonist** [comment]
@agilob is that the new default style?

**Comment by agilob** [comment]
`light` is the new default one, you can choose `wombat` and `darkblue`.

**Comment by TheNain38** [comment]
Could it be closed? #2386 was merged
