### ISSUE TITLE
No DnD to send file on Windows

### ISSUE THREAD

**Issue by minj** [qTox/qTox#1878]
This seems to be _the_ defining feature that deters my acquaintances who use Windows.

Dragging a file from explorer to the chat screen produces a no action cursor: ![](https://cloud.githubusercontent.com/assets/1035523/8195303/6b34c5a6-148a-11e5-9540-5a9c00250d7b.png)

Tested the latest build on Win7 64bit.

Works fine for me on linux.

**Comment by towlie** [comment]
Strange, it works here on Win7 x64. Did you try some other files? What was the file name?

**Comment by ghost** [comment]
Working fine on a Win XP x86 VM. Invalid files produced the popup warning, not the _no action_ cursor. The only way I saw it was hovering the contact list while dragging the files. The cursor changes to normal after leaving that area tho.

**Comment by minj** [comment]
I haven't tested it on a VM and I don't own a windows machine atm.

I tried dragging only one file when I visited my contact in person. It was a chapter from an audiobook. Anyway, it does not seem to be file dependent as the contact has had this problem for a while and tried sending some small files like screenshots etc to me before.

I'll try more experimenting when I visit next time or do a teamviewer session. The contact owns two win7 machines. I wonder if both are affected. Though in all honesty, I don't know how to debug this aside from watching the behavior.

P.S. not sure if that could possibly be relevant but that was a Win7 **home premium** machine

**Comment by sudden6** [comment]
Maybe some DRM thing with the audiobook?
I don't know if windows supports this, just a guess.

**Comment by ghost** [comment]
Windows explorer most likely can't manage DMR.

Tested again (same Win XP VM) using extremely long paths and file names, non-Latin characters, modified permissions. Still couldn't reproduce.

**Comment by zetok** [comment]
@kehugter I don't know about what windows explorer can or cannot do, but I'd like to point out that your "test" is more or less invalid when it comes to DRM - windows xp simply doesn't have mechanisms for DRM that were build into later versions of windows.

@minj have your friend tried to e.g. just create a new text file and send it?
Also, would you mind to elaborate on "sending screenshots" ? i.e. was it done by clicking on button to make screenshot, which should be sent automatically, or was it done by drag & dropping already existing screenshots from hdd?

What could be useful, are logs, stored in `%appdata%\tox\`, named `qtox.log`, if you can, please put those logs somewhere.

**Comment by ghost** [comment]
@zetok I didn't test any DMRd file. I was just commenting on sudden6's question.

**Comment by tux3** [comment]
@minj Are you sure you're using the latest version?

I'll take a look at it again, but I have it working here, in a VM and on the metal. Home premium shouldn't be a problem, either.

**Comment by minj** [comment]
Sorry guys, it seems to have been a glitch. I tested it out yesterday and everything seems to work fine. All kinds of files from all kinds of folder locations. No problem with that audiobook either.

Perhaps it was a weird first-run glitch after installing over an older build. I'll let you know if it reproduces itself again.
