### ISSUE TITLE
Offline messaging

### ISSUE THREAD

**Issue by dcapeletti** [qTox/qTox#1886]
It would be interesting to be able to leave a message for a friend who is offline or offline. When the friend enters Qtox, the message even when another friend has been closed is sent. As an analogy, it would seem to system emails.
For example, the friend xx1 send a message to xx2 that is offline.
The friend xx1 turn off your computer.
xx2 friend, later, turn on your computer and read messages sent by your friend xx1.

**Comment by agilob** [comment]
It's not possible in tox.

**Comment by ProMcTagonist** [comment]
It's being worked on.

**Comment by quininer** [comment]
https://www.google-melange.com/gsoc/project/details/google/gsoc2015/drakefish/5707702298738688
