### ISSUE TITLE
Arabic/Perso-Arabic text coming up blank

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1887]
I'm sending myself messages in perso-arabic, but none of the text shows up in qtox. Here's a screenshot:
![untitled](https://cloud.githubusercontent.com/assets/3895638/8230548/20158ab4-1576-11e5-9c32-b308345e4569.png)

the text that should be displayed is:
ثیس اس تِکست
(it's nonsense, btw)

**Comment by zetok** [comment]
yep, doesn't work for me too on ce2c8309a28dc49ec005610791062ee55633ef80

**Comment by Doneganai7** [comment]
I find that Esperanto accents work perfectly, and so do Japanese Kanji, but Kana show up as blank boxes.

I am using qTox on a 64 bit Linux Mint machine. I have also confirmed that while kana does not show properly on my computer, it does show correctly on Windows and Mac computers.

![qtox-problem](https://cloud.githubusercontent.com/assets/8411025/8638995/b7e45d76-2899-11e5-84e5-14502a41061c.png)

The Japanese with blank kana boxes should read これは日本語です。

**Comment by Chiitoo** [comment]
The ثیس اس تِکست at first didn't come out here either, but I noticed that it might have something to do with being aligned to the right; right-to-left (just a guess without looking into anything deeper).

It will show up for example if either of the two conditions shown below are met:

![qtox_font_issue_1887_01](https://cloud.githubusercontent.com/assets/9367616/8655215/712f8bbc-2998-11e5-81a9-6bbae5b486bc.png)

After 'asd' the text will show up (left-to-right).  After that, there are a couple of lines of blank again (test-input), but once there is enough to new line(?), it will show up again.

In fact, it will show up with just the ثیس اس تِکست as long as the line becomes long enough (width of chat window seems to affect it somewhat).

As for Katakana and Hiragana, those show up fine here:

![qtox_font_issue_1887_02](https://cloud.githubusercontent.com/assets/9367616/8655216/7137789a-2998-11e5-9a52-85569bdfc069.png)

That might be a different issue (could qTox be using a weird font there for some reason?).

I'm using Gentoo Linux with all sorts of fonts and CJK support.

qTox was built is from: https://github.com/TheSpiritXIII/qTox/commit/4c040cacfc6b63d17b4c3cc57213a0b510cca707

(Not as a patch, but directly from that branch.)

**Comment by zetok** [comment]
From #2315 thanks to @shake031:

# 

Issue:
Unicode based languages does now prints in output window, one can see fine when one type but it sends an empty line to other person. Check following video
https://www.youtube.com/watch?v=8ZJ-qH9t2v0
How to reproduce:
Open any chat window and type any Arabic script language (Arabic, Persian, Urdu, Daari, Pastho etc)
for example you can copy paste my name
امجد شیخ
u can see it correctly where u paste it, but once u send it u just see an empty like. ok but if u add a normal Assci chartar infornt of it, like H or S, and then send it. then it will show it. Please check the video for more details.

**Comment by ZIEXED** [comment]
This problem existing for a year?
Any progress here?
