### ISSUE TITLE
Link with a correct RPATH for dependencies in exotic places

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#1899]
Some of our dependencies may be installed in places where the loader won't find them.

E.g. toxcore installs itself in /usr/local/lib/, but some distributions (Fedora) don't have it in the default search path.

We should (somehow) instruct the linker to add to the RPATH when a library that was dynamically linked with isn't in the loader's search path.

A couple of unanswered questions: 
- Is there a better way? 
- Is it too hard to be done? 
- Would this break on exotic systems? 
- Would it be dangerous to add too much things to the RPATH (.so hijacking) in a release build?

**Comment by zetok** [comment]
It's better not to. The best way to handle what fedora does is to just add instructions to INSTALL.md

**Comment by tux3** [comment]
The thing is that the only way to fix it both permanently and without affecting the whole system is to change the RPATH.

If we tell every Fedora user to add /usr/local/lib to the ldconfig search path, it works but it might break something and it'll stay even if they uninstall qTox. Individual applications shouldn't mess with global system settings like the loader search paths. 

We can either fix our own RPATH, get our dependencies to install in a default search path (so, proper packages), or link with dependencies statically. The RPATH seems like the least bad solution to me.

**Comment by Zer0-One** [comment]
It sounds messy, but you could write a wrapper that shoves `LD_LIBRARY_PATH` into the process environment

EDIT: I don't see a problem with modifying our own `DT_RPATH` or `DT_RUNPATH`, it does seem to be the least messy solution.

**Comment by zetok** [comment]
Well, I don't think that this is an issue any longer, given that there are now static qTox builds; closing.
