### ISSUE TITLE
Can't build qtox

### ISSUE THREAD

**Issue by qwad1000** [qTox/qTox#1901]
I'am trying to build qTox but got error:
/usr/bin/ld: //usr/local/lib/libavdevice.a(xcbgrab.o): невизначене посилання на символ (unknown reference to symbol)«xcb_setup_pixmap_formats_length»
//usr/local/lib/libxcb.so.1: error adding symbols: DSO missing from command line

Building up and installing libxcb from latest (1.11) release doesn't make any difference.

Enviroment: Kubuntu 14.04 LTS. ffmpeg was build up from latest release.

The latest log part before an error is next:

``` bash
g++ -m64 -Wl,-O1 -o qtox audiofilterer.o timer_osx.o timer_win.o timer_x11.o autorun_win.o autorun_xdg.o autorun_osx.o closures.o enums.o statusnotifier.o addfriendform.o settingswidget.o generalform.o privacyform.o avform.o profileform.o filesform.o chattextedit.o friendrequestdialog.o widget.o netcamview.o friendlistwidget.o adjustingscrollarea.o loadhistorydialog.o setpassworddialog.o tabcompleter.o flowlayout.o ipc.o autoupdate.o callconfirmwidget.o systemtrayicon.o groupwidget.o friendwidget.o chatform.o groupchatform.o genericchatform.o friend.o friendlist.o group.o grouplist.o smileypack.o emoticonswidget.o style.o croppinglabel.o maskablepixmapwidget.o videosurface.o toxuri.o toxdns.o toxsave.o serialize.o chatlog.o chatline.o chatlinecontent.o chatlinecontentproxy.o text.o spinner.o filetransferwidget.o chatmessage.o image.o customtextdocument.o aboutform.o advancedform.o notificationicon.o timestamp.o documentcache.o pixmapcache.o offlinemsgengine.o qrwidget.o genericchatroomwidget.o loginscreen.o v4l2.o audio.o historykeeper.o main.o nexus.o cdata.o cstring.o settings.o genericddinterface.o plaindb.o encrypteddb.o videoframe.o gui.o toxme.o core.o coreav.o coreencryption.o corefile.o corestructs.o profilelocker.o avatarbroadcaster.o screenshotgrabber.o screengrabberchooserrectitem.o screengrabberoverlayitem.o toolboxgraphicsitem.o flyoutoverlaywidget.o verticalonlyscroller.o cameradevice.o camerasource.o corevideosource.o toxid.o profile.o translator.o settingsserializer.o qrc_res.o qrc_smileys.o moc_friend.o moc_group.o moc_smileypack.o moc_emoticonswidget.o moc_croppinglabel.o moc_maskablepixmapwidget.o moc_videosurface.o moc_toxuri.o moc_toxdns.o moc_chatlog.o moc_spinner.o moc_filetransferwidget.o moc_customtextdocument.o moc_aboutform.o moc_advancedform.o moc_notificationicon.o moc_offlinemsgengine.o moc_addfriendform.o moc_chatform.o moc_groupchatform.o moc_settingswidget.o moc_genericsettings.o moc_generalform.o moc_privacyform.o moc_avform.o moc_filesform.o moc_profileform.o moc_chattextedit.o moc_friendrequestdialog.o moc_friendwidget.o moc_groupwidget.o moc_widget.o moc_netcamview.o moc_friendlistwidget.o moc_genericchatroomwidget.o moc_genericchatform.o moc_adjustingscrollarea.o moc_loadhistorydialog.o moc_setpassworddialog.o moc_tabcompleter.o moc_ipc.o moc_callconfirmwidget.o moc_systemtrayicon.o moc_qrwidget.o moc_loginscreen.o moc_audio.o moc_core.o moc_nexus.o moc_settings.o moc_videosource.o moc_gui.o moc_screenshotgrabber.o moc_screengrabberchooserrectitem.o moc_screengrabberoverlayitem.o moc_toolboxgraphicsitem.o moc_flyoutoverlaywidget.o moc_verticalonlyscroller.o moc_camerasource.o moc_corevideosource.o   -L/usr/X11R6/lib64 -L/home/qwad1000/workspace/qt/qTox/libs/lib/ -ltoxcore -ltoxav -ltoxencryptsave -ltoxdns -lvpx -lsodium -lopenal -lavformat -lavdevice -lavcodec -lavutil -lswscale -lqrencode -lX11 -lXss -lfilteraudio -lglib-2.0 -lgdk_pixbuf-2.0 -lgio-2.0 -lcairo -lgtk-x11-2.0 -lgdk-x11-2.0 -lgobject-2.0 -lQt5Svg -L/usr/lib/x86_64-linux-gnu -lQt5OpenGL -lQt5Widgets -lQt5Sql -lQt5Xml -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread 
```

**Comment by qwad1000** [comment]
The latest log part before an error is next:
g++ -m64 -Wl,-O1 -o qtox audiofilterer.o timer_osx.o timer_win.o timer_x11.o autorun_win.o autorun_xdg.o autorun_osx.o closures.o enums.o statusnotifier.o addfriendform.o settingswidget.o generalform.o privacyform.o avform.o profileform.o filesform.o chattextedit.o friendrequestdialog.o widget.o netcamview.o friendlistwidget.o adjustingscrollarea.o loadhistorydialog.o setpassworddialog.o tabcompleter.o flowlayout.o ipc.o autoupdate.o callconfirmwidget.o systemtrayicon.o groupwidget.o friendwidget.o chatform.o groupchatform.o genericchatform.o friend.o friendlist.o group.o grouplist.o smileypack.o emoticonswidget.o style.o croppinglabel.o maskablepixmapwidget.o videosurface.o toxuri.o toxdns.o toxsave.o serialize.o chatlog.o chatline.o chatlinecontent.o chatlinecontentproxy.o text.o spinner.o filetransferwidget.o chatmessage.o image.o customtextdocument.o aboutform.o advancedform.o notificationicon.o timestamp.o documentcache.o pixmapcache.o offlinemsgengine.o qrwidget.o genericchatroomwidget.o loginscreen.o v4l2.o audio.o historykeeper.o main.o nexus.o cdata.o cstring.o settings.o genericddinterface.o plaindb.o encrypteddb.o videoframe.o gui.o toxme.o core.o coreav.o coreencryption.o corefile.o corestructs.o profilelocker.o avatarbroadcaster.o screenshotgrabber.o screengrabberchooserrectitem.o screengrabberoverlayitem.o toolboxgraphicsitem.o flyoutoverlaywidget.o verticalonlyscroller.o cameradevice.o camerasource.o corevideosource.o toxid.o profile.o translator.o settingsserializer.o qrc_res.o qrc_smileys.o moc_friend.o moc_group.o moc_smileypack.o moc_emoticonswidget.o moc_croppinglabel.o moc_maskablepixmapwidget.o moc_videosurface.o moc_toxuri.o moc_toxdns.o moc_chatlog.o moc_spinner.o moc_filetransferwidget.o moc_customtextdocument.o moc_aboutform.o moc_advancedform.o moc_notificationicon.o moc_offlinemsgengine.o moc_addfriendform.o moc_chatform.o moc_groupchatform.o moc_settingswidget.o moc_genericsettings.o moc_generalform.o moc_privacyform.o moc_avform.o moc_filesform.o moc_profileform.o moc_chattextedit.o moc_friendrequestdialog.o moc_friendwidget.o moc_groupwidget.o moc_widget.o moc_netcamview.o moc_friendlistwidget.o moc_genericchatroomwidget.o moc_genericchatform.o moc_adjustingscrollarea.o moc_loadhistorydialog.o moc_setpassworddialog.o moc_tabcompleter.o moc_ipc.o moc_callconfirmwidget.o moc_systemtrayicon.o moc_qrwidget.o moc_loginscreen.o moc_audio.o moc_core.o moc_nexus.o moc_settings.o moc_videosource.o moc_gui.o moc_screenshotgrabber.o moc_screengrabberchooserrectitem.o moc_screengrabberoverlayitem.o moc_toolboxgraphicsitem.o moc_flyoutoverlaywidget.o moc_verticalonlyscroller.o moc_camerasource.o moc_corevideosource.o   -L/usr/X11R6/lib64 -L/home/qwad1000/workspace/qt/qTox/libs/lib/ -ltoxcore -ltoxav -ltoxencryptsave -ltoxdns -lvpx -lsodium -lopenal -lavformat -lavdevice -lavcodec -lavutil -lswscale -lqrencode -lX11 -lXss -lfilteraudio -lglib-2.0 -lgdk_pixbuf-2.0 -lgio-2.0 -lcairo -lgtk-x11-2.0 -lgdk-x11-2.0 -lgobject-2.0 -lQt5Svg -L/usr/lib/x86_64-linux-gnu -lQt5OpenGL -lQt5Widgets -lQt5Sql -lQt5Xml -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread

**Comment by zetok** [comment]
do you have `libxcb1` installed?

also, why is `/usr/local` being used?

**Comment by tux3** [comment]
@qwad1000 It seems that ffmpeg was built incorrectly, the undefined reference you're getting is in libavdevice.
You may want to grab a prebuilt binary from some Linux distribution if you have trouble compiling FFmpeg.

**Comment by qwad1000** [comment]
@zetok `ibxcb1` is installed (as mentioned above - from latest release)
`usr/local` is used because libs are installed with `make install`

**Comment by qwad1000** [comment]
any workarounds?

**Comment by SkyzohKey** [comment]
Same error as u:

``` console
-ltoxcore -ltoxav -ltoxencryptsave -ltoxdns -lvpx -lsodium -lopenal -lavformat -lavdevice -lavcodec -lavutil -lswscale -lqrencode -lX11 -lXss -lfilteraudio -lglib-2.0 -lgdk_pixbuf-2.0 -lgio-2.0 -lcairo -lgtk-x11-2.0 -lgdk-x11-2.0 -lgobject-2.0 -lQt5Svg -L/usr/lib/x86_64-linux-gnu -lQt5OpenGL -lQt5Widgets -lQt5Sql -lQt5Xml -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread 
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libavdevice.a(xcbgrab.o): undefined reference to symbol 'xcb_setup_pixmap_formats_length'
//usr/lib/x86_64-linux-gnu/libxcb.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [qtox] Error 1
```

**Comment by SkyzohKey** [comment]
It seem that a workaround could be to add `-lz` to  `GCCFLAGS` in the `Makefile` and re-run `./simple_make.sh`

**EDIT**: don't work. e.e

**Comment by zetok** [comment]
Are instructions in updated INSTALL.md still insufficient?

**Comment by zetok** [comment]
No answer, assuming that it was answered, thus closing.
