### ISSUE TITLE
[Feature request] make links 'onebox'

### ISSUE THREAD

**Issue by blade1989** [qTox/qTox#1903]
I am a big fan of the chat rooms over at stackexchange, and I would love to see QTox with a similar feature, named onebox, 

All it needs to do is get all the metadata, such as `<meta name=""` and the title tag, and display it in a 'fancy' matter:

>  `<title>WhatsApp Desktop, Unofficial Desktop Client Released - EuroBytes</title>`
>    `<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">`
>    `<meta name="description" content="WhatsApp Desktop A free and Open Source unofficial desktop client for Mac, Windows and linux has been released. And it works beautifully.">`
>    `<meta name="keywords" content="WhatsApp, Messaging, desktop">`
>    `<meta name="author" content="Imri Paloja">`

this is what happens if you post a link to wiki page:

![wikipedia](https://cloud.githubusercontent.com/assets/3373458/8315083/3d77200a-19ee-11e5-9c29-72130d706395.png)

There chat onebox many site such as YouTube:

![youtube](https://cloud.githubusercontent.com/assets/3373458/8315100/68e75d40-19ee-11e5-8dae-9073eac61d79.png)

And XKCD:

![xkcd](https://cloud.githubusercontent.com/assets/3373458/8315181/f9a07aa6-19ee-11e5-9ebd-28483010fd9e.png)

That is just a link, but it got the image and previews it.

Is there a way that QTox could have this too? 
It is a features that would make many users happy.

P.S. I posted the images - and you guys can test it out - in the:
[Ask Ubuntu General Room | chat.stackexchange.com](https://chat.stackexchange.com/rooms/201/ask-ubuntu-general-room)

**Comment by mateosalta** [comment]
:thumbsup:

**Comment by TheSpiritXIII** [comment]
One possible issue is see is some dumb friend posting NSFW links. There needs to be settings for disabling this feature, per-friend maybe.

**Comment by ByteCommander** [comment]
It does not only onebox xkcd comics but all common image formats. Anyway: +1

**Comment by blade1989** [comment]
@TheSpiritXIII we could have a `-` sign to turn links into a regular link? And a `+` when we want that particular link to onebox. And maybe settings option:

**OneBox**:

> [x] enable oneboxing of links.

**OneBoxing links**:

> [x] Show the `+`/`-` sign to choose which link to not onebox

Sounds like an idea?

**Comment by ProMcTagonist** [comment]
I would support this if the link metadata collection was done sender-side.

**Comment by tux3** [comment]
@ProMcTagonist So then it'd have to be done as some kind of special file transfer?

**Comment by ProMcTagonist** [comment]
I've been thinking more about it. If someone is consistently sending you links that would be harmful for your qTox to automatically visit (how to make rice cooker bombs and kill the president, etc), it's a social problem and you should remove them. And just one visit to anything shouldn't get anyone vanned, right? Even with CP they typically go after producers and distributors over link-clickers.

Still, auto-visiting urls makes me a bit nervous. A malevolent friend can already see the same IP a server from a malevolent link would, but maybe an uninformed friend could spread tox-user-tracking links or something.

And if you're in public groupchats you're essentially letting anyone visit websites (and potentially cache images) on your IP's behalf.

I think it would be a more acceptable default in a secure messenger to have only specific sites get oneboxed, not just anything.

EDIT: @tux3, I recant my statement concerning sender-side as long as only a whitelist of sites are oneboxed.

**Comment by blade1989** [comment]
@ProMcTagonist Agreed! I think that the stackexchange developers did this also for the same reason. +1!

**Comment by mateosalta** [comment]
yeah, so what I was thinking is expand a link, only if you specifically turn the function on for limited sites.
- Send links like normal by default
- If user wants expanded "oneboxed" links, can turn them on
- limited to youtube, wikipedia, ect. with option to select only the desired sites / aka remove sites from whitelist

**Comment by blade1989** [comment]
Any progress on this?

**Comment by Jeeppler** [comment]
First of all, I would make this optional per friend and in general. Secondly I would resolve all TCP/HTTPS by using the TOR network and allow only HTTPS sites. 

@ProMcTagonist I like his idea of providing a whitelist of sites like wikipedia, stackoverflow and other useful sites. The qTox user can then add more sites to his whitelist or turn off the white list.

**Comment by ProMcTagonist** [comment]
A user-editable whitelist sounds like it solves all the security and privacy concerns. Oneboxing would definitely add to the wow factor during an initial encounter with a Tox chat :)

**Comment by agilob** [comment]
> A user-editable whitelist sounds like it solves all the security and privacy concerns

No because qtox connects to 3rd party network with weak encryption and exposes additional metadata.

**Comment by ProMcTagonist** [comment]
@agilob Could you elaborate? The whitelist I'm talking about is receiver-side, meaning users' devices only visit domains they've deemed acceptable. 

It's true that a user could disagree with the default shipped whitelist and find out it exists the hard way. How could we fix that?

**Comment by Jeeppler** [comment]
first of all this feature should be disabled, if you enable that the user should be able to decide if he wants to use the qTox whitelist or modify it. 

Another option could be, that every link which is in the whitelist gets a small icon at the bottom-end which allow to activate the metadata onebox thing for this link. This means the user can enable the metadata link to get the medatadata for this specific link or can enable this feature for every link he gets for everybody or this specific friend. But the user should still be able to decide to modify the default whitelist or not.

**Comment by zetok** [comment]
> How could we fix that?

By not introducing the problem in the first place. Best, quickest fix that exists out there.

**Comment by agilob** [comment]
> @agilob Could you elaborate? The whitelist I'm talking about is receiver-side, meaning users' devices only visit domains they've deemed acceptable. 

qTox opens connection to network with weaker encryption, by sniffing network traffic and looking at metadata like URL context of ongoing conversation can be exposed. I'm against this feature in any form. Maybe in a future we could create a simple API to allow writing plugins.

**Comment by Jeeppler** [comment]
+1

**Comment by Vastrix** [comment]
+1 :+1:

**Comment by aaannndddyyy** [comment]
should be/have
- per friend
- option to disable it
- option to resolve links via tor even if tox communication is not going through tor
- on first run, ask the user whether this feature should be on or off for all friends
- no whitelist (user sends link of his new home page, which is not whitelisted and so does not show  -> bad ux

Sendr-side fetching of the data also sounds nice, however, you wouldn't want to download the whole youtube viedo and then transfer it to your contact, would you?

**Comment by ProMcTagonist** [comment]
> on first run, ask the user whether this feature should be on or off for all friends

Disagree, Tox is configurationless on first run. If you have to ask permission, ask for permission when you need it.
http://techcrunch.com/2014/04/04/the-right-way-to-ask-users-for-ios-permissions/

Concerning whitelist issues... Would it be annoying to have every new domain be a non-oneboxed link, with a little button saying to automatically preview from this site in the future, and build the whitelist up opt-in that way?

Privacy + pretty features is hard.

**Comment by aaannndddyyy** [comment]
the first run question was in order not to decide between on by default or off by default. 
on by default has privacy concerns against it, off by default means many users won't even know the feature exixsts.

tox is not totally questionless, i mean on first run you have to provide a user name already and decide whether or not to encrypt the profile. a simple checkbox could be enough or a single pop up question. 
but there should never be more than 2-3 checkboxes on the initial screen, in order not to confuse people, be hard, look ugly.

The opt-in whitelist with a button on every single non-oneboxed domain would be viable. I am not opposed to it, though personally i would prefer having a global setting to switch oneboxing on or off.
In case there is no first-run question or checkbox, onebox should be off by default or the whitelist be absolutely empty at start and onebox on.

**Comment by Vastrix** [comment]
> Privacy + pretty features is hard.

I think that if anything it should be "Security + pretty features = hard" (In this case anyway)

Unless it's an ip logging link (and onebox tries to load it) or the web admin is "compromised", privacy doesn't seem to be a huge concern in this case..?

Security on the other hand.. Onebox carelessly dling/loading data from a site.. that smells dangerous.. :s

**Comment by ProMcTagonist** [comment]
@aaannndddyyy 

> the first run question was in order not to decide between on by default or off by default.
> on by default has privacy concerns against it, off by default means many users won't even know the feature exixsts.

The point was that they can be prompted for that when they're first sent a link instead of cluttering up the first run. It makes the question relevant and not annoying. The link I posted explains. Sorry for seeming confusing by bringing up whitelist prompting right afterward, though.

> The opt-in whitelist with a button on every single non-oneboxed domain would be viable. I am not opposed to it, though personally i would prefer having a global setting to switch oneboxing on or off.

They're not mutually exclusive. There should definitely be a setting to toggle on or off oneboxing globally, and/or edit/clear the whitelist, just like cookie management in a browser.

There should also be little warning text by each button reminding that oneboxing automatically visits all links from that domain and your ISP/others can see if you're not using Tor

@vastrix 
Outsiders seeing what links my friends send me during a conversation violates my privacy. Security is privacy.

**Comment by Jeeppler** [comment]
I still think this feature should be disabled by default and you have to unlock it if you want. 
There could be a small icon on every link, which requires a click to load the preview. This question should appear on the first link the user get's, than he can enable or disable the feature completely. 

This feature is not important enough to bug the user during account creation.

**Comment by TheNain38** [comment]
Or it could be enabled by default and in the settings you could have an option to desactivate the thing on the links which ask if you want to enable oneboxing for this site

**Comment by blade1989** [comment]
I think all the ideas for this feature here as been set. enable/disable in settings, etc. Is there a release date for this feature?

**Comment by zetok** [comment]
> Is there a release date for this feature?

Err. I really don't think that this should be something that qTox should do..

If there was some way of "embedding" a real browser (not just the engine), and telling it to open given URL, then this feature could possibly be done as a qTox extension, when extensions will be possible in qTox.

I.e. optional extension in qTox → it detects URL and opens a real browser window, which displays page content. (if needed, it might open that window within qTox window)

This way it wouldn't be that much of a problem for qTox, and instead it would be pushed onto some web browser, given that it's web browser's job to do that thing well. Extension being optional (i.e. not turned on by default) would further lessen the chances of bad things.

Would have to support both Chromium and Firefox, and shouldn't be a hard dependency for qTox - in case where browser isn't present at all, qTox should run (and compile) just fine, and let the user know that there's no browser that it could use.

Now,

> If there was some way of "embedding" a real browser

Given that there's no easy way of doing that (or doing that at all), I don't think that this feature will go anywhere.

AFAICS, the only reason why this issue isn't closed is that there's apparently rather big interest in the feature, and perhaps there will be someone who will have a good idea how to do it + there will be a good implementation.

If I'm wrong, please correct me.

**Comment by sudden6** [comment]
This presents a big security risk and is not planned in the near future.
