### ISSUE TITLE
Add a checkbox to prohibit multiple instances of qTox from running at the same time

### ISSUE THREAD

**Issue by LittleVulpix** [qTox/qTox#1906]
Problem:

1) New user installs and launches qtox, uses it, closes it to tray
2) user then clicks the desktop icon or start icon or taskbar icon to bring up the qtox interface
3) new instance of qtox is launched and user is confused about having to create a new profile

Solution:
Similarly to "make qtox portable", add a checkbox that will prohibit qtox from starting a second instance of itself; and instead, launching a second instance will merely bring up the qtox ui (like in uTox/skype).

Additionally, should I make a separate issue to prompt the user that his/her profile is locked/in use when qtox finds out that that is the case? Just so the user knows to close another program(s) that might be using the profile, such as uTox (consider the following scenario - user installs qtox after using uTox and forgets to close uTox prior to starting newly-installed qTox; qTox then asks the user to make a new profile and the user is confused about having to re-add all of his/her contacts. If a warning was shown that the profile is being used by another application, the user would likely realize to close them and retry the operation).

**Comment by tux3** [comment]
> consider the following scenario - user installs qtox after using uTox and forgets to close uTox prior to starting newly-installed qTox;

Then qTox will not warn because it doesn't know that uTox is running, so there's not much we can do about this.

**Comment by LittleVulpix** [comment]
@tux3 Oh, you are right (my bad). Thought it locked the file but it doesn't.

**Comment by ProMcTagonist** [comment]
The default behavior should really be to bring back the current instance. Starting with a new profile is a very niche use-case and this is about avoiding confusion for most users.

**Comment by zetok** [comment]
> The default behavior should really be to bring back the current instance. Starting with a new profile is a very niche use-case and this is about avoiding confusion for most users. 

That's the current behaviour.

> Similarly to "make qtox portable", add a checkbox that will prohibit qtox from starting a second instance of itself; and instead, launching a second instance will merely bring up the qtox ui (like in uTox/skype).

Being able to have open multiple qTox instances by "power users" through `qtox -p $profile` switch is a feature and is not going to be removed.

Thus, closing.
