### ISSUE TITLE
Translation warning in pluralised string

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1909]
In this string

https://github.com/tux3/qTox/blob/80ea94bcd3b123c9f028c016631e11f499fd8845/src/widget/notificationedgewidget.cpp#L54

Linguist warns that the `Translation does not contain the necessary %n place marker`. It seems to be a known limitation of qt's translation system:

https://bugreports.qt.io/browse/QTBUG-5928

I guess that one should just ignore the warning then?

**Comment by TheSpiritXIII** [comment]
That translation is something I added for [this request](https://github.com/tux3/qTox/pull/1843#issuecomment-110587713).

I don't see it as a big problem. However, the given bug report has users calling it an "abuse" of the translation system. As an alternative, we can show the number of unread messages (this number there would represent the number of friends whose messages you did not read). I wouldn't mind the alternative but I don't know if it would look weird.

**Comment by ghost** [comment]
> show the number of unread messages

No need to do that only to bypass a linguist warning. I just wanted to let you know that it was happening.
