### ISSUE TITLE
After switching locale first letter was not appeared

### ISSUE THREAD

**Issue by gEndelf** [qTox/qTox#1911]
After switching locale first letter was not appeared

---
### ENV

**qtox Built**: 20:19:24 Jun  2 2015
**OS**:
- Linux mint
  - RELEASE=17
  - CODENAME=qiana
  - EDITION="Xfce 64-bit"
  - DESCRIPTION="Linux Mint 17 Qiana"
  - DESKTOP=Xfce
  - TOOLKIT=GTK
### How to reproduce (chat window)
- type "123" in default locale (for example EN)
- switch locale to let's say - RU
- type "456"
- symbol "4" is not typed

**Comment by zetok** [comment]
Can't reproduce. Is this still reproducible on newest qTox builds?

**Comment by gEndelf** [comment]
yes

**Comment by zetok** [comment]
How do you switch locale?

**Comment by Diadlo** [comment]
Needed info not provided for over a month, thus closing.
