### ISSUE TITLE
Mac OS  10.10.2 , QT 5.4 build error 

### ISSUE THREAD

**Issue by ablegao** [qTox/qTox#1915]
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -stdlib=libc++ -mmacosx-version-min=10.7 -Wl,-rpath,/usr/local/Cellar/qt5/5.4.2/lib -o qtox.app/Contents/MacOS/qtox audiofilterer.o timer_osx.o timer_win.o timer_x11.o autorun_win.o autorun_xdg.o autorun_osx.o addfriendform.o settingswidget.o generalform.o privacyform.o avform.o profileform.o filesform.o chattextedit.o friendrequestdialog.o widget.o netcamview.o friendlistwidget.o adjustingscrollarea.o loadhistorydialog.o setpassworddialog.o tabcompleter.o flowlayout.o ipc.o autoupdate.o callconfirmwidget.o systemtrayicon.o groupwidget.o friendwidget.o chatform.o groupchatform.o genericchatform.o friend.o friendlist.o group.o grouplist.o smileypack.o emoticonswidget.o style.o croppinglabel.o maskablepixmapwidget.o videosurface.o toxuri.o toxdns.o toxsave.o serialize.o chatlog.o chatline.o chatlinecontent.o chatlinecontentproxy.o text.o spinner.o filetransferwidget.o chatmessage.o image.o customtextdocument.o aboutform.o advancedform.o notificationicon.o timestamp.o documentcache.o pixmapcache.o offlinemsgengine.o qrwidget.o genericchatroomwidget.o loginscreen.o install_osx.o audio.o historykeeper.o main.o nexus.o cdata.o cstring.o settings.o genericddinterface.o plaindb.o encrypteddb.o videoframe.o gui.o toxme.o core.o coreav.o coreencryption.o corefile.o corestructs.o profilelocker.o avatarbroadcaster.o screenshotgrabber.o screengrabberchooserrectitem.o screengrabberoverlayitem.o toolboxgraphicsitem.o flyoutoverlaywidget.o verticalonlyscroller.o cameradevice.o camerasource.o corevideosource.o toxid.o profile.o translator.o settingsserializer.o notificationscrollarea.o notificationedgewidget.o circlewidget.o genericchatitemwidget.o friendlistlayout.o genericchatitemlayout.o categorywidget.o qrc_res.o qrc_smileys.o moc_friend.o moc_group.o moc_smileypack.o moc_emoticonswidget.o moc_croppinglabel.o moc_maskablepixmapwidget.o moc_videosurface.o moc_toxuri.o moc_toxdns.o moc_chatlog.o moc_spinner.o moc_filetransferwidget.o moc_customtextdocument.o moc_aboutform.o moc_advancedform.o moc_notificationicon.o moc_offlinemsgengine.o moc_addfriendform.o moc_chatform.o moc_groupchatform.o moc_settingswidget.o moc_genericsettings.o moc_generalform.o moc_privacyform.o moc_avform.o moc_filesform.o moc_profileform.o moc_chattextedit.o moc_friendrequestdialog.o moc_friendwidget.o moc_groupwidget.o moc_widget.o moc_netcamview.o moc_friendlistwidget.o moc_genericchatroomwidget.o moc_genericchatform.o moc_adjustingscrollarea.o moc_loadhistorydialog.o moc_setpassworddialog.o moc_tabcompleter.o moc_ipc.o moc_callconfirmwidget.o moc_systemtrayicon.o moc_qrwidget.o moc_loginscreen.o moc_audio.o moc_core.o moc_nexus.o moc_settings.o moc_videosource.o moc_gui.o moc_screenshotgrabber.o moc_screengrabberchooserrectitem.o moc_screengrabberoverlayitem.o moc_toolboxgraphicsitem.o moc_flyoutoverlaywidget.o moc_verticalonlyscroller.o moc_camerasource.o moc_corevideosource.o moc_notificationedgewidget.o moc_circlewidget.o moc_genericchatitemwidget.o moc_friendlistlayout.o moc_categorywidget.o   -F/usr/local/Cellar/qt5/5.4.2/lib -L/Users/gao/code/qTox/libs/lib/ -ltoxcore -ltoxav -ltoxencryptsave -ltoxdns -lsodium -lvpx -lopus -framework OpenAL -lavformat -lavdevice -lavcodec -lavutil -lswscale -mmacosx-version-min=10.7 -lqrencode -framework IOKit -framework CoreFoundation -lfilteraudio -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework QtSvg -framework QtNetwork -framework QtXml -framework QtSql -framework OpenGL -framework AGL 
Undefined symbols for architecture x86_64:
  "___cxa_deleted_virtual", referenced from:
      vtable for ChatForm in moc_chatform.o
      vtable for GroupChatForm in moc_groupchatform.o
      vtable for ProfileForm in moc_profileform.o
      vtable for GenericChatForm in moc_genericchatform.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tux3** [comment]
Some build options where changed, try cleaning the build directory and recompiling.

You can probably do that from Xcode, or `make distclean` from a terminal.

**Comment by ablegao** [comment]
I can run make distclean , but problem is still there.

 CoreFoundation -lfilteraudio -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework QtSvg -framework QtNetwork -framework QtXml -framework QtSql -framework OpenGL -framework AGL 
Undefined symbols for architecture x86_64:
  "___cxa_deleted_virtual", referenced from:
      vtable for ChatForm in moc_chatform.o
      vtable for GroupChatForm in moc_groupchatform.o
      vtable for ProfileForm in moc_profileform.o
      vtable for GenericChatForm in moc_genericchatform.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [qtox.app/Contents/MacOS/qtox] Error 1

**Comment by ablegao** [comment]
sorry , this' other version : 

clang -v
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix

 make -v 
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

**Comment by ablegao** [comment]
qmake -v
QMake version 3.0
Using Qt version 5.4.2 in /usr/local/Cellar/qt5/5.4.2/lib

**Comment by soredake** [comment]
https://github.com/tux3/qTox/issues/1866 same error

**Comment by agilob** [comment]
I added 

```
QMAKE_CC=clang
QMAKE_CXX=clang
```

to qtox.pro and can't reproduce on linux 64:

```
➜  ~  clang -v
clang version 3.6.1 (tags/RELEASE_361/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix

➜  ~  make -v 
GNU Make 4.1
Built for x86_64-unknown-linux-gnu

➜  ~  qmake -v 
QMake version 3.0
Using Qt version 5.4.2 in /usr/lib
```

Compilation was successful.

**Comment by tux3** [comment]
I suppose we could define a __cxa_deleted_virtual that just aborts on Mac, but the C++ runtime should already provide this.

**Comment by ablegao** [comment]
I added 
QMAKE_CC=clang
QMAKE_CXX=clang 

to my qtox.pro , and i  can run make distclean , but problem is still there...
