### ISSUE TITLE
qTox crashes when GLX is missing on Linux after entering "Audio/Video" tab

### ISSUE THREAD

**Issue by dev-mb-zz** [qTox/qTox#1918]
Hi!
After clicking the "Audio/Video" tab in settings. qTox crashes reproduibly with the following message:

  Xlib:  extension "GLX" missing on display ":0".
  Xlib:  extension "GLX" missing on display ":0".
  [10:06:56.722] qglxintegration.cpp:297 : Fatal: Could not initialize GLX
  Aborted

I think it should just throw an exception instead of dying.

My system Debian Jessie with  qt 4.8.6
I am using the latest nitghtly version 1.0-1751  from https://repo.tox.im/

**Comment by tux3** [comment]
That's a problem with Qt.

**Comment by zetok** [comment]
@dev-mb are current builds affected too https://wiki.tox.chat/binaries#other_linux ?

**Comment by dev-mb-zz** [comment]
It seems to be fixed. No crash with the current nightly on Debian 64bit with the generic linux binary from https://wiki.tox.chat/binaries#other_linux 
Thanks a lot.
