### ISSUE TITLE
Compiling error from avform.cpp

### ISSUE THREAD

**Issue by SkyzohKey** [qTox/qTox#1919]
Here's the backtrace: 

``` console
src/widget/form/settings/avform.cpp: In constructor ‘AVForm::AVForm()’:
src/widget/form/settings/avform.cpp:45:65: error: invalid initialization of non-const reference of type ‘CameraSource&’ from an rvalue of type ‘<brace-enclosed initializer list>’
     camVideoSurface{nullptr}, camera{CameraSource::getInstance()}
                                                                 ^
make: *** [avform.o] Error 1
```

I have ffmpeg installed (compiled myself from the official website).
I DuckDuck'ed the error and found this: http://stackoverflow.com/a/8294009/3855007

**Comment by tux3** [comment]
You need a C++11 compiler.

**Comment by SkyzohKey** [comment]
apt-get install gcc:
`gcc is already the newest version.`

gcc -v
`gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)`

**Comment by tux3** [comment]
Does it build if you replace the { } by ( ) ?

**Comment by SkyzohKey** [comment]
I didn't tried, I'll test

**Comment by SkyzohKey** [comment]
Hmm, now it say : 

``` console
src/video/videoframe.cpp:24:32: fatal error: libavcodec/avcodec.h: No such file or directory
 #include <libavcodec/avcodec.h>
                                ^
compilation terminated.
make: *** [videoframe.o] Error 1
```

._.

**Comment by tux3** [comment]
Now you need to install libavcodec, it's part of FFmpeg.

**Comment by SkyzohKey** [comment]
I already have ffmpeg. I compiled it from ffmpeg official website.

**Comment by tux3** [comment]
It must not be installed correctly if qmake can't find it.

Try copying the headers in "./libs/include/" in the qTox directory maybe.
