### ISSUE TITLE
BUG  - Duplicate circles

### ISSUE THREAD

**Issue by SkyzohKey** [qTox/qTox#1922]
![bug](http://i.imgur.com/zhaYalB.png)

**How to reproduce:**
- Click your avatar
- Click on the Logout button.
- Reconnect to your account.

**What happens:** Circles got duplicated by empty circles.
**What should happens:** Circles are not duplicated.

**Comment by tux3** [comment]
Fixed by 62d298462b396e9e43ee3ecdaf03f15b6c549060 5 hours before you posted it :)
