### ISSUE TITLE
qTox doesn't support `tox:ID` URI

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1925]
Clicking on an example ↓

```
<a href="tox:581A49A38D3EEA6DC4A3725C3DF9C93692B7B54A3644404132712CFE6A16CF5703FE7DAEA0BC">CLICKBAIT</a>
```

should result in qTox client being opened in FR "window".

https://github.com/Tox/Tox-STS/blob/master/STS.md#tox-uri-scheme

**Comment by tux3** [comment]
On what OS, with what web browser?

 Do you have the qTox.desktop file installed?

**Comment by zetok** [comment]
yep, I have qTox.desktop installed on my Gentoo.

Dunno how it is supposed to work, but it `just works™` with µTox…

Also, I heard that it doesn't work on windows.

**Comment by PhilHypnox** [comment]
Doesn't work on W7 x64 qTox, Firefox Nightly, as well as Internet Explorer. And yes, desktop file installed.

**Comment by tux3** [comment]
Okay, I see why it doesn't work on Windows, but it seems to work on my Linux here.

@zetok where is the .desktop file installed, and what browser are you using?

**Comment by zetok** [comment]
```
/usr/share/applications/qTox.desktop
ff browser
```

It's not only an issue with browsers - i.e. when I've clicked on `tox:` in qTox, qTox opened `xdg-open`, which, in turn, opened µTox…

**Comment by tux3** [comment]
@zetok does it work if you rename it to `/usr/share/applications/qtox.desktop`, with proper capitalization?

**Comment by zetok** [comment]
@tux3 err, rename to what? `ff browser` is not a part of name

**Comment by tux3** [comment]
@zetok Rename `/usr/share/applications/qTox.desktop` to `/usr/share/applications/qtox.desktop`

**Comment by zetok** [comment]
@tux3 but there are other applications, e.g. `qBittorrent.desktop`, which do react for e.g. torrent magnet links?

**Comment by zetok** [comment]
anyway, after renaming to `qtox.desktop`:

```
[New Thread 0x7fffc98b6700 (LWP 9973)]
START /usr/bin/utox  tox:581A49A38D3EEA6DC4A3725C3DF9C93692B7B54A3644404132712CFE6A16CF5703FE7DAEA0BC
/usr/bin/xdg-open: line 583:   365 Segmentation fault      (core dumped) /usr/bin/utox tox:581A49A38D3EEA6DC4A3725C3DF9C93692B7B54A3644404132712CFE6A16CF5703FE7DAEA0BC
```

Which is the same as it was, i.e. qTox still tries to open `tox:` URI with µTox

**Comment by tux3** [comment]
So that's not a problem with qTox. 

You have two handlers for the `tox:` URI scheme, uTox and qTox. Your browser picked uTox and I'm not goign to make it a war of overriding over clients' handlers.

And you might want to report that utox segfault on their bug tracker :)

**Comment by zetok** [comment]
actually, my browser now is able to open `tox:` with qTox.. problem still exists for opening links from within qTox.

Edit: after I've removed µTox, now `tox:` is opened by qTox with Toxic...

**Comment by PKEv** [comment]
It seems to me that the more logical trap links within qtox something like "linkactivated(QString)" otherwise it is not clear how it should work when running multiple accounts

**Comment by zetok** [comment]
on qTox 1.8.1 it still doesn't work, although it results in error message: `<tox id> is not a valid Toxme address.`
