### ISSUE TITLE
qTox insane CPU & RAM usage due to starting new processes from clicking on tox: links

### ISSUE THREAD

**Issue by PhilHypnox** [qTox/qTox#1926]
Running qTox, I noticed a significant slow-down in everything CPU-intensive that I do (playing movies suddenly became impossible in even 720p). This is the task manager screenshot:

![uirh171](https://cloud.githubusercontent.com/assets/3148759/9689929/2d94ac08-5331-11e5-9eb1-5674fb6e6a1a.png)

Why is qTox eating up that much RAM & CPU?

I'm W7 x64.

**Comment by tux3** [comment]
Did you intentionally open 6 different qTox instances?

**Comment by PhilHypnox** [comment]
Nope. I just had it running for... about 7 to 9 days. I don't shut down my PC at all in general. Can't imagine it being on my side, unless these instances were started in issue 1925 while I was testing, and didn't shut down.

Which I really doubt.

**Comment by tux3** [comment]
Alright, I'll take a look at it, thanks.

Can you post the log (in folder %APPDATA%/tox/qtox.log), please?

**Comment by towlie** [comment]
@PhilHypnox Did you use video calls in these 7 to 9 days? If yes, did some of your contacts use utox?

**Comment by zetok** [comment]
Reason - qTox cannot handle clicking on `tox:` URI well:
![*click* *click*](https://cloud.githubusercontent.com/assets/3148759/8398076/21d4e4d2-1dda-11e5-9b1a-9d9f49f92e57.png)

**Comment by PhilHypnox** [comment]
http://pastebin.com/9Rs0Tkt3

the log. And yes, it does appear to be the case. It only goes back to normal once all instances of qTox are closed.

**Comment by tux3** [comment]
@PhilHypnox 

Thanks, I have a good idea of what the problem is now.

Although a big part of the log is qTox not being able to connect to the network, is that a problem you had with qTox, or just spotty internet?

**Comment by PhilHypnox** [comment]
Spotty connection, yes.

**Comment by suhr** [comment]
Add tag l-slow.

**Comment by zetok** [comment]
From #2271, it would appear that `tox:` links don't work on windows - since example provided in that issue didn't have correct ID, could this be checked with correct ID in "link", that will have 76 hexadecimal characters, e.g. `tox:90F4C2558794EDC54C62585541DC7105583D9E20B5B29F0034B5032A15F4CE3CEC4927D6D779` ?

**Comment by PKEv** [comment]
and new users can't use this link because link "tox:...." was registered by nsis setup
how this mechanism will work in multiple application starts (different accounts)?

**Comment by sudden6** [comment]
More logs and steps to reproduce: https://github.com/tux3/qTox/issues/3167

**Comment by zetok** [comment]
on 1.8.1 bug is still present, although it results in 100% CPU usage only until one loads a profile
