### ISSUE TITLE
Can't connect to groupchat

### ISSUE THREAD

**Issue by Shura0** [qTox/qTox#193]
qTox receives invite to groupchat, but I see nothing. In the same time in a console:

"Core: Group invite by 3" 
"Trying to join groupchat invite by friend 3" 
Widget::onGroupInviteReceived: Unable to accept invitation

**Comment by tux3** [comment]
The workaround for the time being is to simply try again a couple of times and it should work.

**Comment by zetok** [comment]
That's probably due to current group chats being broken, they don't work over TCP.
Not really a qTox issue.

Hopefully rewritten group chats will arrive soon in core.

**Comment by tux3** [comment]
I'll add a workaround that automatically retries a couple of times if it doesn't work.

**Comment by tux3** [comment]
I actually won't add this workaround since it doesn't seem to help. This is a core issue and I there's no easy workaround as far as I can tell, closing.
