### ISSUE TITLE
qTox deleted my circles

### ISSUE THREAD

**Issue by SkyzohKey** [qTox/qTox#1931]
I don't know why, I don't know how but I closed qTox before to sleep and when I logged this morning my circles were gone :/

**Comment by TheSpiritXIII** [comment]
I have had my circles deleted when I switched branches or used an older qTox version. This is possibly because the setting files were incompatible. Maybe this could be the reason?

**Comment by zetok** [comment]
Is this still reproducible?

**Comment by zetok** [comment]
No answer, assuming that it was fixed, thus closing.
