### ISSUE TITLE
qTox repository unmaintained

### ISSUE THREAD

**Issue by iamunknown2** [qTox/qTox#1934]
Perhaps someone should start maintaining the deb repositories for qTox, as (assuming that) many people prefer adding a repository over building from source, as apt sports auto-updating, compared to having to build from source over and over again.

Although this could be workaroundable by simply including self-updating features in the application, it is generally good practice to provide updates via the package manager (if available).

**Comment by tux3** [comment]
The deb repositories are maintained again, you can find instructions here:

https://github.com/tux3/qTox/blob/master/INSTALL.md#debian
