### ISSUE TITLE
Tooltips unreadable

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#1936]
http://fs2.directupload.net/images/150629/2yponpgz.png

**Comment by agilob** [comment]
Duplicate.
Solved in new style.
![snapshot2](https://cloud.githubusercontent.com/assets/2544251/8411126/2b68b3f2-1e7a-11e5-8139-da790b283d7a.png)

**Comment by zetok** [comment]
Duplicate of #1583, closing.
