### ISSUE TITLE
Update files have big size

### ISSUE THREAD

**Issue by Bargest** [qTox/qTox#1939]
When auto-updating on Windows, qtox saves downloaded update files in .../update/ folder. Original qTox files are packed with UPX, but updates are not. It takes a lot of traffic to download them.
Here are two ideas to beat this:
1) Pack updates with UPX. But it's not a very good idea - all packers like UPX look suspicious for me.
2) Pack the whole update with zip/7-zip/gzip and downlowad as one file. It's much better.

**Comment by tux3** [comment]
We just got rid of UPX and there are good reasons to not add it back, but compressing update files is definitely something we should do.

**Comment by fcore117** [comment]
I like too that UPX was removed from qTox binaries.

**Comment by zetok** [comment]
Now that qTox is being build as static binary, I wonder how doable is further decrease of binary size.

**Comment by Bargest** [comment]
Does qTox pack the update now? 7z can compress new executable to 10 Mb from original 32 Mb. I'm sure gzip will have good pack results too.
If it packs already, I see no chance to decrease size further.

**Comment by zetok** [comment]
Well, currently there's no updates for windows yet, just binaries. And yep, they are compressed.

**Comment by sudden6** [comment]
No autoupdater anymore, so closing.
