### ISSUE TITLE
The names from the history are not loaded correctly

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#1943]
Reproducible: Always

Steps to reproduce:
1. setup name with unicode characters
2. send message
  on friend side:
1. close qtox after receiving mess
2. start qtox
![qtox-screenshot-joem4048](https://cloud.githubusercontent.com/assets/6053197/8426198/90abf624-1f16-11e5-918b-da61f0b6ba47.png)

Observed Behavior:
The names from the history are not loaded correctly

**Comment by agilob** [comment]
https://github.com/tux3/qTox/issues/1787
