### ISSUE TITLE
"Commit hash: built without git" on apt package

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1946]
![screencap](http://i.imgur.com/3W3CAr9.png)

Is there a chance to keep the commit hash?

**Comment by SkyzohKey** [comment]
Same issue as you. :x

**Comment by zetok** [comment]
This should be fixed in newest builds available: https://wiki.tox.chat/binaries#other_linux
(note that those builds aren't in a repo (yet?))

If problem still appears, please comment for reopen.
