### ISSUE TITLE
[Feature request] Better visualisation for drag & drop effects

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1947]
Dragging & dropping does different stuff when file is dragged to chat or to text input field.
To show visual difference between those actions, something like that could be used:
![20150630 qtox drag drop files to send](https://cloud.githubusercontent.com/assets/3148759/8441303/42b69ab0-1f6f-11e5-8525-ae93a7c2b988.png)

Those black-ish fields would be shown only when file is being dragged into qTox, and should be partially transparent.

**Comment by SkyzohKey** [comment]
Something like imgur when u drop a file over could be nice

**Comment by codedust** [comment]
Do we really need the option to paste the path by drag & drop? Wouldn't it be better to send the file in both cases?

**Comment by ghost** [comment]
+1 to codedust
I can hardly think of any scenario where you have to send a full path to someone else. Pasting the path could be hidden in a key combination, like dropping with CTRL pressed.

**Comment by PKEv** [comment]
@codedust  This is a very handy feature for specifying files when working in a local network

**Comment by Zer0-One** [comment]
+1 to @zetok , I like the idea.

**Comment by codedust** [comment]
+1 to @kehugter
I really like the 'CTRL idea'. For most users, the current behaviour is very confusing/unintuitive.

**Comment by ghost** [comment]
> specifying files when working in a local network

Is a small percentage of users to sacrifice simplicity imo.

**Comment by zetok** [comment]
> Pasting the path could be hidden in a key combination, like dropping with CTRL pressed.

Probably the best solution. Question is whether `CTRL` is the best key for it? Anything other that could be used?

**Comment by ghost** [comment]
`SHIFT` is as a bad as `CTRL` I think. And that's about it.

**Comment by PKEv** [comment]
@kehugter It sounds good if you're not in the percentage ...

**Comment by zetok** [comment]
Well, given that now the whole chatform area including input can be used for sending files by drag & drop, original proposal is kinda ~moot, thus closing.

For those interested in using `CTRL` for sending file paths instead of files - please open a new issue, and perhaps link to it here.

**Comment by Talkless** [comment]
@PKEv this should work by holding Ctrl anywhere in chat window, or only on text input widget?

**Comment by PKEv** [comment]
In view of the fact that sending a file path is quite a specific thing and very few people use this - it will be enough only on text input widget
