### ISSUE TITLE
crash with sorting "by activity" 

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#1948]
Today found
When you select the sorting "by activity", qTox falls

win7 x32

**Comment by PKEv** [comment]
Most likely it is due to damage to the ini file..

**Comment by ghost** [comment]
Can reproduce using tux3's updated apt package (x64) - segmentation fault. Can this be because none of my contacts have been active since I updated to qTox having support to sort by activity?

**Comment by TheSpiritXIII** [comment]
The reason why is interesting. It's because the last 7 days is not this month, so "This Month" does not get created, making the system get the wrong index for the "Unknown" activity (it goes 1 too far).
