### ISSUE TITLE
No way to know profile's name

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#1951]
as the user name does not always coincide with the name of the profile that it would be convenient to the profile name displayed somewhere in the profile settings
+
Maybe add the name of the user in the window title - useful when you have multiple copies running qTox?

**Comment by zetok** [comment]
> Maybe add the name of the user in the window title - useful when you have multiple copies running qTox?

Not really. Probably best solution would be to just put that info where it belongs - i.e. on `Profile` page.

**Comment by ProMcTagonist** [comment]
+1 for profile page displaying the current profile name
