### ISSUE TITLE
[Feature request] Use KDE filepicker in KDE

### ISSUE THREAD

**Issue by Myppomeu** [qTox/qTox#1954]
In KDE 4 qTox using something like GTK filepicker.

**Comment by ProMcTagonist** [comment]
The filepicker is awful, and it's definitely not the GTK one that everything else on my system uses (which has a helpful Recent section).

**Comment by agilob** [comment]
qtox uses plasma5 file picker on my machine, kde 5.13.

**Comment by ProMcTagonist** [comment]
@agilob can I make that happen without installing and using all of KDE?

**Comment by zetok** [comment]
@ProMcTagonist you mean, use KDE file picker without installing whole KDE?

No idea how it's in other distros, but if you use Hardened Gentoo, then answer would be - probably yes. It would depend on how you would configure things.

With binary distros though.. probably no, although you would have to check yourself.

If you want a different file picker for qTox that would be distro agnostic, then you probably should open a new issue.

**Comment by agilob** [comment]
@ProMcTagonist I don't think so.

@zetok 

> No idea how it's in other distros, but if you use Hardened Gentoo, then answer would be - probably yes.

I had kubuntu once, then I switched to gnome, removed kde at all, some applications (firefox, skype) where still 'fallbacking' to kde file picker.
