### ISSUE TITLE
New feature: send the image from the clipboard

### ISSUE THREAD

**Issue by dcapeletti** [qTox/qTox#1965]
When a user makes a screenshot and press the button "copy to clipboard" and then paste the capture in the chat tox, send it to the user.
![captura de pantalla de 2015-07-05 20 00 01](https://cloud.githubusercontent.com/assets/5890886/8513834/28f7814e-2351-11e5-87e9-a07fa0e86abf.png)

**Comment by PKEv** [comment]
#1290

**Comment by zetok** [comment]
closing, since it's a duplicate.
