### ISSUE TITLE
unable to compile on haiku

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1966]
Hi devs
I'm trying to compile qtox on haiku using qt4-4.8.7 and gcc-4.8.4 but i'm getting a bunch errors for which i don't have a clue where to look for answers.
can anyone please give me some guidance where to look?
Here are the errors

In file included from ../../../system/develop/headers/QtGui/QLineEdit:1:0,
                 from src/widget/form/addfriendform.h:20,
                 from src/widget/form/addfriendform.cpp:15:
../../../system/develop/headers/QtGui/qlineedit.h: In constructor 'AddFriendForm::AddFriendForm()':
../../../system/develop/headers/QtGui/qlineedit.h:198:10: error: 'void QLineEdit::returnPressed()' is protected
     void returnPressed();
          ^
src/widget/form/addfriendform.cpp:50:32: error: within this context
     connect(&toxId,&QLineEdit::returnPressed, this, &AddFriendForm::onSendTriggered);
                                ^
src/widget/form/addfriendform.cpp:50:84: error: no matching function for call to 'AddFriendForm::connect(QLineEdit_, void (QLineEdit::_)(), AddFriendForm\* const, void (AddFriendForm::_)())'
     connect(&toxId,&QLineEdit::returnPressed, this, &AddFriendForm::onSendTriggered);
                                                                                    ^
src/widget/form/addfriendform.cpp:50:84: note: candidates are:
In file included from /boot/system/develop/headers/QtGui/qlayout.h:45:0,
                 from ../../../system/develop/headers/QtGui/qboxlayout.h:45,
                 from ../../../system/develop/headers/QtGui/QVBoxLayout:1,
                 from src/widget/form/addfriendform.h:18,
                 from src/widget/form/addfriendform.cpp:15:
/boot/system/develop/headers/QtCore/qobject.h:204:17: note: static bool QObject::connect(const QObject_, const char_, const QObject_, const char_, Qt::ConnectionType)
     static bool connect(const QObject *sender, const char *signal,
                 ^
/boot/system/develop/headers/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from 'void (QLineEdit::_)()' to 'const char_'
/boot/system/develop/headers/QtCore/qobject.h:217:17: note: static bool QObject::connect(const QObject_, const QMetaMethod&, const QObject_, const QMetaMethod&, Qt::ConnectionType)
     static bool connect(const QObject *sender, const QMetaMethod &signal,
                 ^
/boot/system/develop/headers/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from 'void (QLineEdit::_)()' to 'const QMetaMethod&'
/boot/system/develop/headers/QtCore/qobject.h:337:13: note: bool QObject::connect(const QObject_, const char_, const char_, Qt::ConnectionType) const
 inline bool QObject::connect(const QObject *asender, const char *asignal,
             ^
/boot/system/develop/headers/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from 'void (QLineEdit::_)()' to 'const char_'
In file included from src/widget/form/addfriendform.cpp:24:0:
./src/core/core.h:179:10: error: 'void Core::usernameSet(const QString&)' is protected
     void usernameSet(const QString& username);
          ^
src/widget/form/addfriendform.cpp:52:38: error: within this context
     connect(Nexus::getCore(), &Core::usernameSet, this, &AddFriendForm::onUsernameSet);
                                      ^
src/widget/form/addfriendform.cpp:52:86: error: no matching function for call to 'AddFriendForm::connect(Core_, void (Core::_)(const QString&), AddFriendForm_ const, void (AddFriendForm::_)(const QString&))'
     connect(Nexus::getCore(), &Core::usernameSet, this, &AddFriendForm::onUsernameSet);
                                                                                      ^
src/widget/form/addfriendform.cpp:52:86: note: candidates are:
In file included from /boot/system/develop/headers/QtGui/qlayout.h:45:0,
                 from ../../../system/develop/headers/QtGui/qboxlayout.h:45,
                 from ../../../system/develop/headers/QtGui/QVBoxLayout:1,
                 from src/widget/form/addfriendform.h:18,
                 from src/widget/form/addfriendform.cpp:15:
/boot/system/develop/headers/QtCore/qobject.h:204:17: note: static bool QObject::connect(const QObject_, const char_, const QObject_, const char_, Qt::ConnectionType)
     static bool connect(const QObject *sender, const char *signal,
                 ^
/boot/system/develop/headers/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from 'void (Core::_)(const QString&)' to 'const char_'
/boot/system/develop/headers/QtCore/qobject.h:217:17: note: static bool QObject::connect(const QObject_, const QMetaMethod&, const QObject_, const QMetaMethod&, Qt::ConnectionType)
     static bool connect(const QObject *sender, const QMetaMethod &signal,
                 ^
/boot/system/develop/headers/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from 'void (Core::_)(const QString&)' to 'const QMetaMethod&'
/boot/system/develop/headers/QtCore/qobject.h:337:13: note: bool QObject::connect(const QObject_, const char_, const char_, Qt::ConnectionType) const
 inline bool QObject::connect(const QObject *asender, const char *asignal,
             ^
/boot/system/develop/headers/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from 'void (Core::_)(const QString&)' to 'const char_'
src/widget/form/addfriendform.cpp: In member function 'QString AddFriendForm::getMessage() const':
src/widget/form/addfriendform.cpp:77:43: error: 'const class QTextEdit' has no member named 'placeholderText'
     return !msg.isEmpty() ? msg : message.placeholderText();
                                           ^
src/widget/form/addfriendform.cpp: In member function 'void AddFriendForm::retranslateUi()':
src/widget/form/addfriendform.cpp:145:13: error: 'class QTextEdit' has no member named 'setPlaceholderText'
     message.setPlaceholderText(tr("%1 here! Tox me maybe?",
             ^
src/widget/form/addfriendform.cpp: In member function 'QString AddFriendForm::getMessage() const':
src/widget/form/addfriendform.cpp:78:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *_\* [addfriendform.o] Error 1
~/Desktop/qTox-master> 
for the info i haven't yet patched any source file,i am just starting,except for the qtox.pro to get haiku 
a recognized platform.
This is what i added to it.

} else {
    macx {
        BUNDLEID = im.tox.qtox
        ICON = img/icons/qtox.icns
        QMAKE_INFO_PLIST = osx/info.plist
        QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.7
        LIBS += -L$$PWD/libs/lib/ -ltoxcore -ltoxav -ltoxencryptsave -ltoxdns -lsodium -lvpx -lopus -framework OpenAL -lavformat -lavdevice -lavcodec -lavutil -lswscale -mmacosx-version-min=10.7
        LIBS += -lqrencode
        contains(DEFINES, QTOX_PLATFORM_EXT) { LIBS += -framework IOKit -framework CoreFoundation }
        contains(DEFINES, QTOX_FILTER_AUDIO) { LIBS += -lfilteraudio }
    } else {
        haiku {
            DISABLE_PLATFORM_EXT=YES
            QMAKE_CXXFLAGS += -std=c++11
            LIBS += -lroot -lnetwork
            LIBS += -ltoxcore -ltoxav -ltoxencryptsave -ltoxdns
            LIBS += -lavformat -lavdevice -lavcodec -lavutil -lswscale
            LIBS += -lopus -lvpx -lsodium -lopenal
            LIBS += -lfilteraudio
     } else {
 I hope to get some answers from you guys.
Thanks

**Comment by stqism** [comment]
qTox doesn't support Qt 4.8, it depends on 5.2+

**Comment by ghost** [comment]
Too bad, i was hoping it might compile with Qt 4.8, ok thanks for responding.

**Comment by stqism** [comment]
Np, I was looking in to getting it working on Haiku with a couple of their maintainers but we didn't really make a ton of progress.

**Comment by agilob** [comment]
https://github.com/tux3/qTox/blob/master/INSTALL.md

This issue gave me a good laugh :D

**Comment by ghost** [comment]
Le ن 6 يول 2015 à 11:23, agilob notifications@github.com a 
écrit :

> https://github.com/tux3/qTox/blob/master/INSTALL.md
> 
> This issue gave me a good laugh :D
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> You actually took the time to write a sarcastic reply?

Now that's a laugh!

**Comment by agilob** [comment]
it wasn't sarcastic.
