### ISSUE TITLE
qTox sends NameChange("") to a removed friend

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#1967]
Let Alice and Bob are friends in Tox. Because of reasons, Alice removes Bob from her contact list.

The Tox FAQ says about this:

> **What happens when I remove someone?**
> If you remove someone, they will see you go offline, as if you closed client normally. They can't communicate with you any longer until you add them to your friend list again.

**What actually happens:**
In Bob's contact list Alice's name is blank now. So, Bob can suppose that he was removed from Alice's contact list.

**Desired behaviour:**
In Bob's contact list will be the last name Alice used.

EDIT: example from https://github.com/tux3/qTox/issues/2229 is used.

**Comment by ovalseven8** [comment]
For me it's 'P-medium'

**Comment by ProMcTagonist** [comment]
Wow, that's a big deal. When did that get introduced?

**Comment by tux3** [comment]
That's a bug in toxcore.

qTox correctly calls `tox_friend_delete` when removing a friend, which correctly sends a 25 PACKET_ID_OFFLINE message to the other client before cleaning up.

The toxcore on the other side receives and handles the 25 PACKET_ID_OFFLINE, and because of a missing `break;` in a switch _also_ handles it as a 48 PACKET_ID_NICKNAME with no data, blanking the nickname...

**Comment by zetok** [comment]
> closed

huh, since it wasn't merged in toxcore yet, reopening

**Comment by tux3** [comment]
The strange part is that this only happens when someone removes you. If that's the only time this packet is received, it means people with a patched client could still detect when they get removed even with this bug fixed..

**Comment by ovalseven8** [comment]
> The strange part is that this only happens when someone removes you. If that's the only time this packet is received, it means people with a patched client could still detect when they get removed even with this bug fixed..

Is there a better solution possible? @tux3

**Comment by agilob** [comment]
if(name is empty string) 
break; // dont update name

that is not a real solution as would work only for qtox (I assume from the description of the bug).

**Comment by zetok** [comment]
Since toxcore PR was merged, closing.
