### ISSUE TITLE
Desktop sharing memory leak and bug

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#1970]
Enable "desktop" as video device start a video call and stop it.

--> RAM usage will go up to 120 MB and will stay there

After this call my mouse flickers the whole time which only happens when watching the preview in Audio/Video settings tab. This will only stop when I close qTox

--> It seems that qtox is still capturing my desktop even if the call is disabled

**Comment by towlie** [comment]
Maybe you have to repdroduce this https://github.com/tux3/qTox/issues/1971 to make this happen. (Is it related?)

**Comment by zetok** [comment]
Can reproduce on my Gentoo.
Ram usage from initial 140MB increased to ~167MB when entered settings and set desktop as input device. When making first video call memory usage jumped to ~260MB and after ending call it stayed at that level.

Subsequent calls increased RAM usage by ~5MB each time.

**Comment by suhr** [comment]
+I-perf-memory

**Comment by towlie** [comment]
Looks like it is fixed. (Mouse doesn't flicker and memory usage is reduced on close)
