### ISSUE TITLE
Video call only works if you watched the preview in the Audio/Video settings tab

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#1971]
Otherwise the receiver will only see a black screen.

Example case:
- Start qtox with already set Video Device
- start video call (receiver only sees black screen)
- go to av settings tab 
- the receiver will now see the video input

Tested on windows.

**Comment by towlie** [comment]
This also happens with webcams.

**Comment by suhr** [comment]
Happens on linux with i3wm too.
