### ISSUE TITLE
Tox icon on the top

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#1972]
Hello,

if I am starting qTox, the Tox symbol is on the top of the window and doesn't disappear.
So, it's not possible/harder to close Tox or other programs.

Would be great if someone could fix it.
Thanks.

Screenshot: ![2hqvwbb jpg](https://cloud.githubusercontent.com/assets/3148759/9566723/212dbfae-4f08-11e5-8cb8-3ef34d294501.png)

Platform: Ubuntu Unity 14.04

**Comment by ovalseven8** [comment]
Played in the settings:
It's because 'Show system tray icon' is on by default.

Nonetheless, it's a bug for me.

**Comment by ProMcTagonist** [comment]
I think this is a known problem with Unity and Qt 5 systrays. There's supposed to be a Unity backend that stops this. Where did you get qTox from?

**Comment by agilob** [comment]
There is Unity backend for that. What version of qtox is that?

**Comment by zetok** [comment]
Is this still a problem on newest qTox?
If it still is, perhaps #2132 would help with it.

**Comment by ovalseven8** [comment]
Have just tested it. 
The issue seems to be solved, so we can close it.

When it occurs again, we can create a new issue, then.

**Comment by sudden6** [comment]
This just happened to me at https://github.com/tux3/qTox/commit/631c37aef18a70c4c4b7d72570c22816b0f1f278 with openSUSE Tumbleweed (20160321) (x86_64)

Edit:
Further testing showed that if qTox is built against Qt 5.3.0 systray doesn't work and if qTox is built against Qt 5.5.1 it works as expected. So this is probably a Qt issue.
