### ISSUE TITLE
Resize username column

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#1974]
Hello,

only a suggestion:
For some people it would be great, I think, if they could resize the username column. Especially, if people in Groupchats are using long usernames, it really could make sense if there would be more place for the names.

Screenshot: http://oi58.tinypic.com/984pba.jpg
(I shaded the column I am speaking about in yellow)

**Comment by TheSpiritXIII** [comment]
It's already possible in my chatform branch. This will come soon.

**Comment by Diadlo** [comment]
Seems, duplicate of #1190, so it will be closed. Please comment if it isn't
