### ISSUE TITLE
Emoticons/Characters aren't visible

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#1975]
Hello,

some emoticons/characters aren't visible.
Screenshot: 
![282e61y jpg](https://cloud.githubusercontent.com/assets/3148759/9566736/c55fd990-4f08-11e5-8e4e-87cf417be15e.png)

The other issue: Does qTox really need so many emoticons? ;-)

**Comment by suhr** [comment]
> Does qTox really need so many emoticons?

Yes. Though they order may be not optimal.

**Comment by zetok** [comment]
Is this still an issue on newest builds?

**Comment by ovalseven8** [comment]
Yes, still an issue.

**Comment by agilob** [comment]
what pack is that?

**Comment by ovalseven8** [comment]
- One emoticon in 'cylgom' -> but seems that emoticon is defect at all
- Rest all in 'TwitterEmojiSimple' and 'TwitterEmojiSVG'
