### ISSUE TITLE
Save and copy QR code image not possible

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#1976]
Hello,

I am not sure if this is already known. But to play it safe - here the issue:

In the user profile there are two buttons.
'Save image' and 'Copy image'.

But if you're clicking, nothing happens.
Perhaps you can fix it. Thanks.

**Comment by SkyzohKey** [comment]
It could be nice to precise your OS and the qTox version

**Comment by ovalseven8** [comment]
OS: Ubuntu Unity 14.04
qTox version: Latest version from pkg.tox.chat

**Comment by linux-modder** [comment]
clicking your avator  it  presents that  option then correct?   Try launching from terminal and repeat   any  interesting dialog from stdout would be helpful.

**Comment by agilob** [comment]
Pointless talking, slot isn't connected.
