### ISSUE TITLE
'built without git' link doesn't exist

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#1977]
Hello,

I installed qTox from the pkg.tox.chat repository.

In 'About' there is a link to [https://github.com/tux3/qTox/commit/built without git](https://github.com/tux3/qTox/commit/built without git).
This URL doesn't exist.

Screenshot: http://oi57.tinypic.com/4g5el0.jpg

**Comment by ghost** [comment]
#1946

**Comment by zetok** [comment]
as @kehugter pointed out, this issue is a duplicate of #1946, closing.

On a side note, this is fixed in newest builds available: https://wiki.tox.chat/binaries#other_linux
