### ISSUE TITLE
[Feature request] show in groupchat inviter

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1984]
in similar way to how topic change is shown?

would be helpful with #1982, but not only

**Comment by ProMcTagonist** [comment]
Just like how freshly added friends have a little action at the top? I like it.

**Comment by zetok** [comment]
> Just like how freshly added friends have a little action at the top? I like it.

no, not really. what you're referring to seems to be a bug…

**Comment by ProMcTagonist** [comment]
Oh. "<name> offers friendship" seemed very deliberate

**Comment by zetok** [comment]
@ProMcTagonist sorry, I should have made it more clear - the way it's done is broken, aka bug, not "feature" itself

I.e. action message shouldn't be sent to your friend after you add them with what you've sent in FR message…

**Comment by sudden6** [comment]
Seems to be implemented in recent builds.
