### ISSUE TITLE
[Regression] message notification sound is not being played

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1990]
Brief Description:
Since quite some time new message notification is not being played when one receives a message.

Operating System: Hardened Gentoo Linux 

Reproducible: Always

Steps to reproduce:
1. Receive a message

Observed Behavior:
Sound is not being played

Expected Behavior:
Sound should be played

Additional info:
I do have `Play sound` checked in settings

**Comment by ProMcTagonist** [comment]
I haven't experienced this. Could it have something to do with focus problems with i3?

**Comment by zetok** [comment]
@ProMcTagonist "focus problem" ?

**Comment by zetok** [comment]
Seems to work aaf0774f356786a183c1ca48b9a1fc14586d9554, closing.

Still no idea why it didn't work.
