### ISSUE TITLE
[Feature Request] DHT Connection & Bandwidth Info/Graph

### ISSUE THREAD

**Issue by thiras** [qTox/qTox#1992]
As topic says, some graphs and info would be really good about current DHT status and bandwidth.

**Comment by zetok** [comment]
not doable, since toxcore doesn't provide that info

**Comment by An-dy** [comment]
If  toxcore does really not provide bandwidth and DHT status than this is clearly a bug.
How should an application adapt to changing bandwidth without this information ?
How do an application know when it has to ask the user what to do (plan B if automatic fails) if tox can't penetrate a firewall to the Internet ?

**Comment by zetok** [comment]
> If toxcore does really not provide bandwidth and DHT status than this is clearly a bug.

No, not really.

> How should an application adapt to changing bandwidth without this information ?

It shouldn't bother to do it - i.e. toxcore should handle that transparently, and eventually provide info to the client in cases where it needs some feedback, e.g. for adaptive bitrate in a/v calls, which toxav does in new A/V API.

> How do an application know when it has to ask the user what to do (plan B if automatic fails) if tox can't penetrate a firewall to the Internet ?

It shouldn't have to - toxcore should handle it transparently.

**Comment by agilob** [comment]
qtox is not a network monitor.
