### ISSUE TITLE
Packages held back because of Tox in Debian

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1993]
The following packages have been kept back: libgnutls-deb0-28 librtmp1

apt-cache policy libgnutls-deb0-28 librtmp1
[output is this](https://gist.github.com/Seeq/e09fcc604616f0abfc52_)
I only have qTox installed so I posted this here, let me know if this should be in the toxcore repo instead.

**Comment by Zer0-One** [comment]
@Seeq `apt-get dist-upgrade`

**Comment by ghost** [comment]
`dist-upgrade` doesn't do anything, the packages are not upgraded when I do that. I asked in #debian and it's due to tox/qtox holding the packages as shown by `apt-cache policy`

**Comment by ProMcTagonist** [comment]
You should remove qTox and the qTox repo if it's from tox.im or libtoxcore.so

**Comment by ghost** [comment]
I learned of the domain change soon after it happened and have changed my repos to the correct ones at  `deb https://pkg.tox.chat/ nightly main` once I became aware of the issue. I made doubly sure that it wasn't because of the old repository, which is why I'm reporting it.

**Comment by zetok** [comment]
Closing, since this is no longer a problem.

@Seeq you should remove that repo, and for time being use binaries, until new repo will be functioning.
