### ISSUE TITLE
When outgoing ACTION messages, nick in the HTML tags will be parse.

### ISSUE THREAD

**Issue by quininer** [qTox/qTox#1999]
![snapshot86](https://cloud.githubusercontent.com/assets/6286761/8641897/cbd8f7aa-294e-11e5-80e2-dd08c994db0c.png)
![snapshot85](https://cloud.githubusercontent.com/assets/6286761/8641899/d0c2f2d4-294e-11e5-8d35-706196b320b6.png)

I think this and the previous title as parsing HTML is a need to fix the "feature"?

**Comment by zetok** [comment]
Can reproduce.

**Comment by agilob** [comment]
It's impossible to fix it as chat messages are printed using html, what we can do it to strip html tags from username.

**Comment by ProMcTagonist** [comment]
There's no way to escape them before printing?

**Comment by agilob** [comment]
I'll take a deeper look at this issue when rewriting themes...

**Comment by TheNain38** [comment]
You could use `QString QString::toHtmlEscaped() const` http://doc.qt.io/qt-5/qstring.html#toHtmlEscaped before printing, so it would just escape them, not strip them
