### ISSUE TITLE
Word wrapping fails on long words (like friend ID's)

### ISSUE THREAD

**Issue by ctrlcctrlv** [qTox/qTox#20]
16667dbaa8ef72eeece08ca574911049ce5d42ff did not take into account very long words.
![screenshot - 06282014 - 02 04 49 pm](https://cloud.githubusercontent.com/assets/838783/3421458/c5aa79d4-feee-11e3-863a-01b99ae2eaeb.png)

**Comment by tux3** [comment]
Qt is in charge of word wrapping, I didn't implement it myself.
I'll see if I can force long words to wrap anyway.

**Comment by tux3** [comment]
Fixed by new chat form.
