### ISSUE TITLE
Bug of Mac os 

### ISSUE THREAD

**Issue by ablegao** [qTox/qTox#2000]
When i'm select  'Start in tray ' and 'Minimize to tray'   , Friend List will not be able to click. Some time , unable to recover from a minimized state.

Mac OS 10.10.3.
QT 5.4

**Comment by zetok** [comment]
Could be improved with a851a5b18da8c295fba441c817920cf65db2cdbb, mind testing?

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.

If issue is still not fixed, please comment for reopen.
