### ISSUE TITLE
Port over  Binary links to  tox.chat 

### ISSUE THREAD

**Issue by linux-modder** [qTox/qTox#2007]
Windows Binaries are  still statically  linked to  dev.tox.im which 502's out

**Comment by linux-modder** [comment]
bump..

**Comment by ProMcTagonist** [comment]
I'm forced to install Toxy on new converts' computers for now.

**Comment by Don42** [comment]
Plus the certificate is expired. Probably should just remove the links for the time being.

**Comment by zetok** [comment]
Fixed, thus closing.
