### ISSUE TITLE
Webcam frame rate slow compared to muTox

### ISSUE THREAD

**Issue by bricky149** [qTox/qTox#201]
I use both muTox and qTox on occasion and I've noticed after changing my webcam exposure to -4 in Skype (which Tox can't adjust, will open a new issue) the frame rate increases in Skype and muTox but qTox remains on a lower frame rate.

**Comment by tux3** [comment]
That's probably because I'm rolling my own video functions, I have plans to switch to a "real" video library eventually.

**Comment by tux3** [comment]
Fixed by using OpenCV.

**Comment by bricky149** [comment]
Requesting this to be reopened. I'm at home using qTox and webcams are still choppy.

**Comment by cebe** [comment]
Am I right that this is hardcoded [here](https://github.com/tux3/qTox/blob/master/src/video/cameraworker.cpp#L36) to a rate of 60Hz? How should a fix to this look like? configuration option for the value that is passed to setInterval()?

**Comment by bricky149** [comment]
On Windows it's held in lpDevMode->dmDisplayFrequency but I wouldn't know how to port that into a Qt call.

**Comment by tux3** [comment]
This is fixed, you can now choose a framerate supported by your camera and qTox will use it.
