### ISSUE TITLE
Audio crash when logging in and out

### ISSUE THREAD

**Issue by TheSpiritXIII** [qTox/qTox#2012]
To reproduce:
Log in. Log out. Log in. Crash.

Operating System:
OS X

[Backtrace](https://gist.github.com/TheSpiritXIII/ee3d662abb2321484c7e)

EDIT: Another user reports that it happens to them when they try to create a new user.

**Comment by antis81** [comment]
Closing -> this issue is outdated no longer valid. A lot has changed in audio handling. @TheSpiritXIII If you still experience problems here, feel free to reopen.
