### ISSUE TITLE
[Feature request] add button to clear search field

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#2015]
One should be able to quickly clear search field just by pressing a button.

**Comment by karanchahal** [comment]
Where is the file where I can see where the search bar is?

**Comment by agilob** [comment]
Do you mean search contacts?

**Comment by SkyzohKey** [comment]
http://doc.qt.io/qt-5/qlineedit.html#clearButtonEnabled-prop ← Just set this at true for the QLineEdit that is used to search contacts. :)

**Comment by karanchahal** [comment]
Yeah search contacts .just tell me where I can find that and then I'll
figure something out

**Comment by karanchahal** [comment]
Thank you :)

**Comment by zetok** [comment]
Since #2376 is now merged, closing.
