### ISSUE TITLE
[Feature request] Auto-accept group chat invites

### ISSUE THREAD

**Issue by thiras** [qTox/qTox#2016]
I think It would be good if there was a option to auto-accept groupchat invites.

**Comment by linux-modder** [comment]
+1

**Comment by quininer** [comment]
https://github.com/JFreegman/toxcore/tree/new_groupchats
New Groupcht will achieve lasting group chat.

https://github.com/irungentoo/toxcore/issues/1377

**Comment by zetok** [comment]
@thiras please close, since it's a duplicate of #1982

@quininer those aren't really what this issue is about
