### ISSUE TITLE
Bluish video in qtox

### ISSUE THREAD

**Issue by somniumAeternam** [qTox/qTox#2018]
Hallo. I did a video call between a Windows 8.1 and a Arch Linux version of qTox. Each version is up to date (from git). The video at both clients is bluish. On Linux I use a Microsoft LifeCam VX-2000.

**Comment by sudden6** [comment]
Do other programs that use your webcam also show bluish video?
Did you try to adjust the camera settings with a tool like qv4l2 or guvcview?

**Comment by somniumAeternam** [comment]
I tried Skype and the video was OK. I haven't tried qv4l2 or guvcview, but I will in the next days.

**Comment by somniumAeternam** [comment]
guvcview also shows the correct colors, as well as qtox itself in the settings. But during the video call the video is bluish on the qtox windows client.

**Comment by sudden6** [comment]
If qTox shows the correct colors in the settings then it seems to be a problem with either the video encoding or the recieving client.
Can you try a windows to windows call and a linux to linux call, to see if it's a platform problem?
And can you please post the logfiles of both clients?

**Comment by zetok** [comment]
Is this still reproducible on newest qTox?

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.

If issue is still not fixed, please comment for reopen.
