### ISSUE TITLE
High delay (> 2 seconds) on high speed and low latency connections.

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2021]
Hello

Sorry if this is the wrong place to report it, but I'm noticing a strange issue when talking to a friend of mine: the delay for VoIP is higher than two seconds. This is strange as we're only a couple of blocks away. Both of us have a very low latency and high throughput connection and we've been using other applications such as Mumble with very low latency without issues up until now. This also does not happen with someone in the same house (presumably because it remains local).

Is this a known issue (with qTox or perhaps Tox itself) and if not, is there anything I can do to debug this issue? I'm not very familiar with the internals of Tox, but is the voice traffic perhaps relayed through other peers after the connection has been established (and, if so, is there any way to turn this off, in order to maintain low latency)?

Thanks in advance

**Comment by agilob** [comment]
this is a toxcore issue please report to https://github.com/irungentoo/toxcore/issues

**Comment by ghost** [comment]
Thanks for the reply, it was perhaps kind of silly to expect this was a qTox issue, but you never know. As you can see I've chimed in in an issue on toxcore [1] and it seems they hope it will be fixed together with the new A/V API that will be merged soon. If you like you can close this issue (or, if you prefer, leave it open for others to find).

[1] https://github.com/irungentoo/toxcore/issues/925

**Comment by agilob** [comment]
I'm this will be closed when tux3 is back, no one else has admin rights in this repo.

**Comment by agilob** [comment]
please report to https://github.com/irungentoo/toxcore if it's still an issue
