### ISSUE TITLE
Poor, hard to see text colour on opening splash with a dark theme

### ISSUE THREAD

**Issue by DylanFrese** [qTox/qTox#2023]
![qtox1](https://cloud.githubusercontent.com/assets/11223986/8792594/4b80100e-2f37-11e5-9b45-27fbed5acffa.png)

The colour of text on the profile selection dialogue is wrong if the user is using a dark system theme.

I am using the "Obsidian Coast" theme that comes with KDE.

**Comment by sudden6** [comment]
This doesn't seem to happen on current builds anymore.
