### ISSUE TITLE
Possibly re-work the INSTALL.md  for clarity

### ISSUE THREAD

**Issue by linux-modder** [qTox/qTox#2025]
I offer  the following  gist  I  did up for a fellow  first-timer that had  compile issues as a template 

https://gist.github.com/linux-modder/8fa5bbac30cf83b8e252

**Comment by linux-modder** [comment]
The major things here  are   less linking  needed and  a  $PWD awareness, possibly a   "lookaside"  could work as well.  use  pr2026 for more  reference.

**Comment by antis81** [comment]
WIP: PR #2026

**Comment by zetok** [comment]
Closing, since INSTALL.md was reworked.
