### ISSUE TITLE
Scrollbar weird under Breeze theme

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2028]
![snapshot1](https://cloud.githubusercontent.com/assets/12797095/8812759/ffec06ba-2ff5-11e5-9f11-6837253d0d44.png)

When changing the theme to "Breeze" under plasma 5, qtox's scrollbar will look weird. As can be seen in the above image, the scrollbar backround is black. 

Should the scrollbar match the system theme scrollbar or should it be a custom qtox scrollbar?

**Comment by agilob** [comment]
I can't reproduce it, could you provide steps how to do it?

**Comment by ghost** [comment]
Changing the theme from "Fusion" (or any other theme) to "Breeze" makes the scrollbar look like that. That's really the only step. 
Running latest Manjaro with latest KDE/Plasma, will be trying this on other DEs to see if possible to reproduce.

**Comment by agilob** [comment]
I'm running arch linux, so that's the same version of plasma as manjaro. I just tried that. I use dark theme so it should be visible better. I've tried reproducing again, still nothing. There are some part of qtox that are redrawn but everything looks normal. I'll take a look at it anyway.

**Comment by agilob** [comment]
Ok, I identified the issue by disabling desktop effects compositor.

**Comment by sudden6** [comment]
duplicate of  #698
