### ISSUE TITLE
Trying to change a profile picture crashes the program.

### ISSUE THREAD

**Issue by kode167** [qTox/qTox#2029]
Brief Description: Trying to change a profile picture crashes the program.

Operating System: Gentoo GNU/Linux 
Version: It's a rolling release
Hardware: Laptop

Reproducible: Always

Steps to reproduce:
1. Go to my user profile page by clicking on my profile picture.
2. Click on the profile picture to change it.
3. Qtox crashes.

Observed Behavior: I cannot interact with the gui anymore, and the application kill shortcut built into my wm (i3) cannot close it using the "wm_delete" protocol. I have to go to a different workspace and run "pkill qtox" in a terminal to close the application.

Expected Behavior: Bringing up a profile picture changing interface; not crashing.

Additional info:
qtox.log: https://bpaste.net/show/4fd0942b99b2
Commit hash: b13cf301f98337c92856d6222abf2c93ec9b6e37
Backtrace: Doesn't work. I get to step 3 and it returns:

Starting program: /home/anon/qtox 
/bin/bash: /home/anon/qtox: Permission denied
/bin/bash: line 0: exec: /home/anon/qtox: cannot execute: Permission denied
During startup program exited with code 126.

Even when running as root.
I downloaded this from the tox overlay for Gentoo last night. I have never set a profile picture, and this happens 100% of the time.

**Comment by zetok** [comment]
@kode167 you probably need to run `gdb $(which qtox)`, although for me just `gdb qtox` works.

Also, if you could, please re-emerge qTox with

```
CFLAGS="-ggdb -O0 -pipe -Wall -Wextra -pedantic -Wformat -Wformat-security" CXXFLAGS="${CFLAGS}" FEATURES="${FEATURES} installsources splitdebug compressdebug" emerge -1 net-libs/tox net-im/qtox
```

before getting backtrace

**Comment by kode167** [comment]
That fixed the problem! Do you still want me to run the backtrack? It seems like you already have a good grasp of the issue! Thanks for the help.

**Comment by zetok** [comment]
Well, closing the issue, since you don't seem any longer affected..
(no idea though what the issue really is/was)
