### ISSUE TITLE
qTox drops call after a while, makes static noise

### ISSUE THREAD

**Issue by bricky149** [qTox/qTox#203]
I just tried to have a call with a friend of mine over qTox when suddenly the call stopped after getting quieter. When we tried to call each other again it made a horrible static noise.

The only conditions I can think of for reproduction is that I have a good connection while the other person's isn't as good and can dropout occasionally.

**Comment by tux3** [comment]
Fixed, please comment if you're still affected with the latest version and I'll reopen.

Note that the official Jenkins builds will probably be a little late due to some internal changes. If you can't compile the source code, please wait a couple of days for a new up-to-date official build.
