### ISSUE TITLE
tox.im has been offline for like a month

### ISSUE THREAD

**Issue by coty-crg** [qTox/qTox#2033]
This means no downloading qtox osx builds, basically.

**Comment by linux-modder** [comment]
Refer to  https://blog.tox.chat ..... *.tox.im has  been abandoned for reasons stated there.

**Comment by ProMcTagonist** [comment]
The domain you mentioned has been seized by a rogue third party and should be avoided. It is no longer associated with the Tox project. Please make sure to tell your friends, as well, that the new site is:

https://tox.chat

Thank you.

The TODO at https://wiki.tox.chat/infrastructure/roadmap shows that progress on getting qTox builds going again is moving along (it's the most recently updated article at the time of this comment).

All we can do is wait, or provide Jenkins slaves.

**Comment by linux-modder** [comment]
Jenkins slaves would require what on our part exactly?

**Comment by coty-crg** [comment]
If it doesn't already, qtox's github readme should direct users towards the new domain. If it already does, perhaps make it more clear.

I've been trying to show friends and co workers about it for awhile now and just haven't been able to. Thanks for keeping the project going though, guys!

**Comment by ProMcTagonist** [comment]
@linux-modder I believe @Zer0-One is involved in managing the new sites, and @zetok has the most recent edit on that article.

**Comment by ghost** [comment]
Oh, wired situation.
Is there also an issue in toxcore about this? And what's with the social media channels? (Twitter and so on...) Are they safe?
And (maybe what's much more important) - what's with the auto update feature of qTox? Where does it download it's information from? Is it safe?

**Comment by ProMcTagonist** [comment]
You should reinstall qTox from tox.chat once the new Jenkins builder is functioning.
