### ISSUE TITLE
Segfault when closing qtox while the audio/video settings tab is open

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#2037]
https://gist.github.com/towlie/a7a00960fe812b522410

**Comment by antis81** [comment]
@zetok Perhaps this explains why segfault is gone after rebaseing #2415 … ;)

**Comment by zetok** [comment]
Yeah, most likely - though it's really strange that I couldn't reproduce that problem until I've started testing audio PR.

**Comment by antis81** [comment]
It sits on top of Agilob's changes and merges fine with them now… :)
