### ISSUE TITLE
segfault on video call hang up

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#2038]
https://gist.github.com/towlie/284e4225444a111b359e
bt full
https://gist.github.com/towlie/5d33832fd021c4a3cd7d

This happens to me when the other side stops the call. The one who hangs up doesn't get the segfault

**Comment by towlie** [comment]
This is what I get with qt5.5
https://gist.github.com/towlie/75a01c3bb8597f51b4e9
bt full
https://gist.github.com/towlie/83f583366fe22360d49a

**Comment by towlie** [comment]
Fixed somehow at an unknown time.

**Comment by agilob** [comment]
:+1: my favourite response.
