### ISSUE TITLE
None adaptive audio/video bit rate

### ISSUE THREAD

**Issue by An-dy** [qTox/qTox#2039]
Adaptive bitrate is the killer feature of Skype over qTox.
Nobody will switch to tox when the audio/video quality is not at least 90% of what you get with skype. The user experience with qtox/tox audio and video quality is bad compared with skype's full adaptive audio/video bit rate.

I had a chat with the tox core developer.
The new API of the tox core allows to utilise the adaptive bit rate future of the OPUS lib.
https://wiki.xiph.org/OpusFAQ#In_what_ways_is_Opus_optimized_for_the_Internet.3F
Opus scales from about 6 kb/s to 512 kb/s, in increments of 0.4 kb/s.

The libvpx (VP8) has also no bit rate restriction.

So what is holding qtox back from ongoing bandwith/quality/drop rate measurement and adapt constantly to it for best possible audio & video ?
Discussion: http://redd.it/3eposk

**Comment by An-dy** [comment]
btw. what A/V layout is tox/qtox using and why? (can't find white papers for it)
1. Muxed and Non-Chunked
2. Muxed and Chunked
3. Non-Muxed and Non-Chunked
4. Non-Muxed and Chunked
See http://wiki.webmproject.org/adaptive-streaming/webm-vod-baseline-format

**Comment by sudden6** [comment]
since the whole audio/video encoding is done in toxcore and qTox just supplies frames, I think the issue belongs to this repository https://github.com/irungentoo/toxcore

**Comment by TheSpiritXIII** [comment]
Work is being done on this. Pull request 1375 of toxcore adds support for this. This pull request will be merged once all of the major clients implemented. I started implementing the new API and will add adaptive bit rates once I find out the best method for it.

**Comment by An-dy** [comment]
The toxcore has now changed the OPUS mode.
https://www.reddit.com/r/projecttox/comments/3eposk/tox_vs_skype_user_experience/ctow0s5
Give it a try!

**Comment by agilob** [comment]
you just need to recompile toxcore and qtox. repositories will be updated soon.
