### ISSUE TITLE
When connecting the pkg repository.tox.chat replaced Debian system libraries.

### ISSUE THREAD

**Issue by torvn77** [qTox/qTox#2044]
translate.yandex.ru:
Hello dear tux3!
I am writing to you to complain about that after adding the repository pkg.tox.chat I have updated the system libraries.
And he qtox I had not set.
Actually it comes in four packages:
apt list --upgradable
Listing...
libgnutls-deb0-28/nightly 3.3.15-7 amd64 [upgradable from: 3.3.8-6+deb8u1]
libopenjpeg5/nightly 1:1.5.2-3.1 amd64 [upgradable from: 1:1.5.2-3]
librtmp1/nightly 2.4+20150115.gita107cef-1+b2 amd64 [upgradable from: 2.4+20150115.gita107cef-1]
libwebp5/nightly 0.4.3-1.3 amd64 [upgradable from: 0.4.1-1.2+b2]

So one LOR anonymous wrote the following:
"Library, which is unstable ABI, or are frequently absent in plants distribution or linkui statically, or deliver with the application and upload using LD_LIBRARY_PATH using a wrapper script."
Can you make something like this?
And Debian Jessie will be still long enough to live, and it would not be good if you replace the system libraries, their computers will be hacked.
That's like my PC is hacked.Not the fact that qtox, but the hole that the rewriting system libraries that turned out.
In this case, there is also the risk that with the new libraries of the installed programs will stop working.

Original text:
Здраствуйте уважаемый tux3!
Пишу я вам для того, чтобы пожаловаться о том, что после добавления репозитория pkg.tox.chat у меня обновлялись системные библиотеки.
Причём сам qtox я ещё не ставил.
Собственно  речь идёт о четырёх пакетах:
apt list --upgradable
Listing...
libgnutls-deb0-28/nightly 3.3.15-7 amd64 [upgradable from: 3.3.8-6+deb8u1]
libopenjpeg5/nightly 1:1.5.2-3.1 amd64 [upgradable from: 1:1.5.2-3]
librtmp1/nightly 2.4+20150115.gita107cef-1+b2 amd64 [upgradable from: 2.4+20150115.gita107cef-1]
libwebp5/nightly 0.4.3-1.3 amd64 [upgradable from: 0.4.1-1.2+b2]

Так вот на лор один анонимус написал следующее:
Библиотеки, у которых нестабильный ABI, или которые часто отсутсвуют в установках дистрибутива или линкуй статически, или поставляй с приложением и загружай с помощью LD_LIBRARY_PATH через враппер-скрипт.
Может вам сделать чтонибудь такое?
Да и Debian Jessie будет ещё достаточно долго жить, и будет не очень хорошо, если из-за того, что вы заменяете системные библиотеки их компьютеры будут взламывать.
Вот например мой ПК взломали.Не факт что из-за qtox, но дыра то переписыванием системных библиотек то получилась.
При этом есть ещё и риск того, что с новыми библиотеками часть установленных программ просто перестанет работать.

**Comment by linux-modder** [comment]
torvn77,

echo '/usr/local/lib/' | sudo tee -a /etc/ld.so.conf.d/locallib.conf
sudo ldconfig

then  finish the compile, if  no locallibs.conf  exists  either use
/etc/ld.so.conf  or  create it  with that line in it.

Corey W Sheldon
Freelance IT Consultant, Multi-Discipline Tutor
Ameridea LLC, Co-Founder, CTO
(p) +1 (310) 909-7672

```
"Have no way as way, no limitation as limitation. One must never
```

underestimate the power of boredom...from which creativity and laziness are
borne, which can spark great works of chaos and genius."

Find Me  on any of the sites  I teach /frequent:

## https://gist.github.com/linux-modder/ac5dc6fa211315c633c9

Tox:
corey84@toxme.se
9357BC6A5944A08AFC7D1EFFD61F6A73B9EABF8B2FB84ACF1DAC9A1A4D0A4705FFCCD0E5499B
PGP: 718BF597
http://pgp.mit.edu/pks/lookup?op=get&search=0xE958C5D6718BF597 FP: 2930

## 99EB 083D D332 0752 88C4 E958 C5D6 718B F597

2015-07-30 8:54 GMT-04:00 torvn77 notifications@github.com:

**Comment by zetok** [comment]
No longer an issue, since qTox binaries are now static.
