### ISSUE TITLE
[tox.chat migration] ppa hangs apt update

### ISSUE THREAD

**Issue by antis81** [qTox/qTox#2054]
I am aware of the fact, that the PPA is currently unmaintained - unfortunately. It should be deactivated until the situation is clear. Maybe I can help out ...

However: The current PPA hangs `apt-get update` on my setup (Lubuntu 15.04). This is an absolute no go. 

Output says:

``` bash
Ign https://repo.tox.im nightly InRelease                                               
Ign https://repo.tox.im nightly Release.gpg
Ign https://repo.tox.im nightly Release
Ign https://repo.tox.im nightly/main amd64 Packages/DiffIndex
Ign https://repo.tox.im nightly/main i386 Packages/DiffIndex
100% [Wird verarbeitet]  # ---> translates to "Being processed"

# at this point, the process hangs and never returns

```

Btw.: What does the "Ign" mean? Why is the qTox package marked ignored?

**Comment by sudden6** [comment]
The tox project has moved to the domain https://tox.chat/ I think the repository there is maintained.
Read more at https://blog.tox.chat/
If this solves your problem please close this issue.

**Comment by antis81** [comment]
Thanks for the info! Just chatting on [Tox IRC](https://webchat.freenode.net/?channels=tox) about that topic. The website seems still to exist on https://www.tox.im. Maybe redirect to https://www.tox.chat?

**Comment by ghost** [comment]
No timeout sounds like a problem at your end.

> Ing

http://askubuntu.com/a/294532

> Maybe redirect to https://www.tox.chat?

Not possible because

> he [...] continues to hold some of our infrastructure “hostage”. This includes the tox.im, toxme.se, and libtoxcore.so domains.

**Comment by antis81** [comment]
@kehugter Nope. It's exactly what @sudden6 wrote. After migration, everything works fine.

About the URL redirect: Yes, I read the blogpost from July, 11th at https://blog.tox.chat. Totally understood. I'm just writing a SH script (in German language), usable without any knowledge about APT, SH or the keys.

**Comment by antis81** [comment]
Wrote a little script, that automates the migration task on Ubuntu/Debian platforms (**in German language**). The script explains itself and provides additional info where to find more info.

EDIT: pushed [script](https://github.com/antis81/qtox-scripts/blob/master/debian/migrate-to-tox.chat.sh) to my [new repo](https://github.com/antis81/qtox-scripts).

Further we need to setup a Github organisation, where the main dev repos are placed and several maintainers have write access. All reviewed dev. contributions would go there!

**Comment by sudden6** [comment]
@antis81 I made a pull request with the English translation of your script.

**Comment by suhr** [comment]
@agilob Can be closed?

**Comment by antis81** [comment]
@sudden6 I made version with `gnu gettext`. Doesn't work 100%, but it's not as bad as one might think. I'll open PR on my own repo at https://github.com/antis81/qtox-scripts ... :)
