### ISSUE TITLE
No builds for windows availabe

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#2055]
See also: https://github.com/tux3/qTox/issues/2047

While @Impyy have his own [jenkins](https://jenkins.impy.me/), help with building is required.

cast @PKEv @r-ku @TheSpiritXIII.

**Comment by sudden6** [comment]
can windows builds be compiled with a linux machine?

**Comment by agilob** [comment]
nope

**Comment by suhr** [comment]
Why not?
http://mxe.cc/

**Comment by ghost** [comment]
It wont be as easy and straightforward. But sure they can.

**Comment by agilob** [comment]
It won't change anything, we still must wait for tux3 to come back (merge PR and setup old jenkins).

**Comment by linux-modder** [comment]
the 2  big issues as I understand them is  (mostly this ) -> 1) cross compile  with  tux3  keys  (which are  not hosted on the common builder   2) tux3  signs his binaries (win )  requiring  local control of them  leading to #1 personally I  have no issue with this  except the  lead time its created.

**Comment by ghost** [comment]
Made PR for fixing windows bootstrap script, in case anyone wants it: https://github.com/tux3/qTox/pull/2057

**Comment by sigmap** [comment]
@agilob Is tux3 absent?

**Comment by agilob** [comment]
yes, on holidays afaik.

**Comment by agilob** [comment]
@zetok  how is it going?

**Comment by zetok** [comment]
There are binaries for windows available: https://wiki.tox.chat/binaries

And their jobs on jenkins:
- https://build.tox.chat/view/Clients/job/qTox_build_windows_x86-64_release/
- https://build.tox.chat/view/Clients/job/qTox_build_windows_x86_release/

**Comment by NoxNoctium** [comment]
Do we still need installer packages? Because now qTox is basically distributed as a single executable without any shared dlls.

**Comment by suhr** [comment]
@markus1540 Yes. Making user to put the binary somewhere manually and to manually create file shortcuts will be unpleasant.
