### ISSUE TITLE
certificate expired

### ISSUE THREAD

**Issue by schmel** [qTox/qTox#2056]
I cannot download qtox for windows. Your ssl sertificate has expired.

**Comment by ProMcTagonist** [comment]
The domain you attempted to use has been seized by a rogue third party and is NOT affiliated with the Tox project or its developers. The real Tox website is https://tox.chat, and Windows downloads will be available shortly. You can watch the progress at https://wiki.tox.chat/infrastructure/roadmap.

Please make sure to remind your friends that the real website is [Tox.chat](https://tox.chat) now. Thanks :)

**Comment by sigmap** [comment]
That doesn't do anything about being unable to download qtox.

**Comment by ProMcTagonist** [comment]
> Windows downloads will be available shortly. You can watch the progress at https://wiki.tox.chat/infrastructure/roadmap.

**Comment by suhr** [comment]
Should be closed in favour of #2055.
