### ISSUE TITLE
Switching to 'Audio/Video' settings tab is blocked on camera initialisation

### ISSUE THREAD

**Issue by koobs** [qTox/qTox#2058]
_Audio/Video_ tab content display is blocked (and waits) on the thread that initialises the camera (and/or microphone) in any situation when that tab is made active. Examples:
- Switching from any other settings tab **to** the _Audio/Video_ tab
- Entering settings (via Gear icon) if the _Audio/Video_ tab was the last active tab

Camera initialisation should be made non-blocking and/or in a separate thread, such that the contents of the _Audio/Video_ tab can be displayed before the camera/microphone device has been enumerated and initialised.

While camera initialisation takes place, the camera preview area could be made:
- Empty (minimum)
- Empty with a user message "Waiting for camera initialisation ..."
- Empty with a progress animation "Initialising ..."

If the progress of initialization is known (definite), then the code could update the progress bar or message accordingly:
1. Searching devices
2. Identifying resolutions
3. Initializing camera

Or whatever the process/steps may be.

Environment:
- **OS Name**: Microsoft Windows 7 Ultimate (x86_64, amd64, 64-bit)
- **OS Version**: 6.1.7601 Service Pack 1 Build 7601
- **Processor**: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz, 3401 Mhz, 4 Core(s) +HT
- **Physical Memory**: 16.0 GB
- **Camera**: Logitech HD Pro Webcam C920
- **Hardware ID**: USB\VID_046D&PID_082D
- **Driver Provider**: Microsoft
- **Driver Version**: 6.1.7601.18208 (12/07/2013) (UVC)
- **qTox Version**: https://github.com/tux3/qTox/commit/f10b4eaee7072bb9fbad5490be016455ba934bcf

**Comment by zetok** [comment]
Based on what you wrote in other issue, I take that you use

> (…) Logitech C920 using Native UVC driver (not Logitech Webcam Software)

?

Your OS is ..?

Is issue reproducible on newest qTox builds https://wiki.tox.chat/binaries (if they're available for your OS) ?

**Comment by koobs** [comment]
Also reproducible with latest qTox (Windows 64-bit) build: https://github.com/tux3/qTox/commit/aed6c25fda02c2aadeeb464cc7be2b79723cc641

**Comment by zetok** [comment]
#2467 should help with it.
