### ISSUE TITLE
"Chat history" drop-down control values render weirdly

### ISSUE THREAD

**Issue by koobs** [qTox/qTox#2059]
The drop down control for "Chat history" renders "weirdly", possibly related to line-height or pixel/dpi sizing.

![qtox](https://butt.githubusercontent.com/assets/1011612/9103380/0c6c6afe-3c41-11e5-95dc-6270dafa48f5.png)

In the unlikely case it's relevant:
- Windows 7 Ultimate Service Pack 1 (All updates)
- AMD Radeon 7950, Catalyst 15.7.1 (latest at time of writing)
- qTox Version: https://github.com/tux3/qTox/commit/f10b4eaee7072bb9fbad5490be016455ba934bcf

**Comment by agilob** [comment]
we had this issue a few times already, but no one was able to reproduce, let's hope this is fixed in styling PR.

**Comment by koobs** [comment]
Rendering now appears normal in build: https://github.com/tux3/qTox/commit/aed6c25fda02c2aadeeb464cc7be2b79723cc641

![20150822 134830-qtox - settings](https://cloud.githubusercontent.com/assets/1011612/9422379/abc11894-48d4-11e5-8ae6-9e30c36de430.png)

**Comment by zetok** [comment]
Since seems to be fixed(?), closing.
