### ISSUE TITLE
Login screen scales incorrectly on i3

### ISSUE THREAD

**Issue by rrooij** [qTox/qTox#2061]
This is how the screen looks:

![toxusername](https://cloud.githubusercontent.com/assets/4800201/9135881/1b265af6-3d12-11e5-924e-bfcf82dd5184.png)

The issue is that the items aren't properly scaled. The login and register window should be a regular dialog instead of a window in my opinion.

**Comment by agilob** [comment]
fixed by https://github.com/tux3/qTox/pull/2052

**Comment by rrooij** [comment]
@agilob 
Nice. The only thing I'd change if I were you is make the commit header and message clear. I'll close the issue if the change gets merged.

**Comment by agilob** [comment]
Yes, commit messages should tell more, but I dont bother writing PR messages for such small fixes, there's nothing to explain, two lines of code are self-explanatory.

**Comment by antis81** [comment]
@agilob Can be closed, right?
