### ISSUE TITLE
qtox-unity much older than qtox package

### ISSUE THREAD

**Issue by nazar-pc** [qTox/qTox#2064]
1.0-1311 vs 1.0-1751 currently

**Comment by nazar-pc** [comment]
Well, new repository doesn't seem to contain this package at all...

**Comment by zetok** [comment]
Closing, since unity version is not being currently build.

**Comment by nazar-pc** [comment]
@zetok Any chance that it will? Otherwise it is extremely inconvinient to use qTox.
