### ISSUE TITLE
New mockup for a better UI/UX ;)

### ISSUE THREAD

**Issue by SkyzohKey** [qTox/qTox#2065]
Hey, I'm currently working on a new mockup to make qTox more user-friendly. So I made a simple mockup that i'll continue to work on until I have made a complete mockup for **all** the qTox interface :)

![http://i.imgur.com/n12cYH3.png](http://i.imgur.com/n12cYH3.png)
[Get this as PSD](http://rghost.net/8BwPhKLsq)

This is currently a work in progress so feel free to tell me what looks bad for you and how I can improve this ;)

**Comment by linux-modder** [comment]
possible to get a  screen grab  of  'compact mode'   also what  is the  point of the  dual icons on second contact in  screen grab (Zetok)

**Comment by SkyzohKey** [comment]
I'll make a compact mode preview (but should be the same as right now), the two icons are (in order) : Delete this contact, Block this contact :)

**Comment by agilob** [comment]
we don't have even one css developer...

**Comment by SkyzohKey** [comment]
I'm a css developper too x)

**Comment by agilob** [comment]
Please read [the thread](https://github.com/tux3/qTox/pull/1882) and contribute!

fell free to contact me A5CB22B35202E91CE49CD2CE07AF036C1410179D47D2E110A1E1D9D7AD59042FF1C7D6685D57

**Comment by SkyzohKey** [comment]
I just uploaded the .psd file of this mockup if someone want to make some edits :)
http://rghost.net/8BwPhKLsq

**Comment by tr37ion** [comment]
@SkyzohKeyx Could you save it as SVG eg.? PSD files are kind of closed source ;)

**Comment by antis81** [comment]
> @SkyzohKeyx Could you save it as SVG eg.? PSD files are kind of closed source ;)

I guess XCF (Gimp) would also be ok and easier to handle (should keep document structure alive).

**Comment by zetok** [comment]
IMHO that mock-up is bad.

**Comment by ProMcTagonist** [comment]
Cluttered, dark, confusing, notifications replacing the titlebar (????) and claiming the close button (???) with right-clicking performing some action instead of bringing up a menu.

Not good.

**Comment by ntninja** [comment]
IMHO the mock-up looks nice, but, as others have pointed out, the title bar should not be replaced (especially not with a "do you want to add X as a friend?"-message).

Aside from using CSD (client side decorations): :+1:

(BTW: The .psd file is not openable in GIMP)

**Comment by antis81** [comment]
> (BTW: The .psd file is not openable in GIMP)

Yep ... please use XCF or SVG.

**Comment by Jeeppler** [comment]
I like the user avatar, it looks better than in the current qTox

**Comment by SkyzohKey** [comment]
This isn't the title bar that is replaced. I don't added a frame to the mockup but the FR widget should act as a "popup" over the "avatar-name-status-buttons" bar (this: http://i.imgur.com/E3aKl2M.png). The "close" button is only here to dismiss the Friend Request notification, not closing the window :)

**Comment by Jeeppler** [comment]
@SkyzohKeyx can you put a simplified window manager border thing around your mockup? Would make things more clear. It does not have to be from an real OS, just make sure that you have the normal "minimize", "maximize" and "close" button in it.

**Comment by Jeeppler** [comment]
What font did you use? The font in qTox looks always blurry in linux. uTox uses a better font, which looks more clear.

**Comment by Jeeppler** [comment]
what is under "Recent"? Have you done a mockup about that?

The "people" + the "plus" sign icon is more clear than the current "plus" sign.

**Comment by Jeeppler** [comment]
Having Accept and Decline in a colored font is maybe not a good idea, because of people with a red-green color blindness.

**Comment by Jeeppler** [comment]
What is about the other icons at the bottom? Like "create groupchat", "finished file transfers" and "settings". Do you want to remove them?

**Comment by ntninja** [comment]
@Jeeppler Making the Accept and Decline buttons colored is fine, what is important (with regards to color blindness) is that all text is still readable when viewing it in grayscale ([which it not really the case either](http://storage.xmine128.tk/s/Qmc6IqFUCb6Fp2n)).

@SkyzohKeyx Maybe add a darker background for the "button area" of the notification popup and make the button text color somewhat lighter?

**Comment by ghost** [comment]
@SkyzohKey now has a client for the mockup -> https://github.com/RicinApp/Ricin
Close?

**Comment by zetok** [comment]
Right. Since @SkyzohKey develops client with that UI, I guess that this issue can be closed?

**Comment by antis81** [comment]
Closing as the concept is incomplete…
