### ISSUE TITLE
Save friend requests for future consideration

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#2066]
It should be possible to save friend request for later, aka. "ignore now", which should let you accept it later, even after restart.

I'm not sure if it is supported by core(?)

**Comment by linux-modder** [comment]
+1 for a feature set

**Comment by agilob** [comment]
+1 doesnt work on github

**Comment by ProMcTagonist** [comment]
:+1: for implementing @itsDuke's friend request mockup

**Comment by zetok** [comment]
> I'm not sure if it is supported by core(?)

Nope, not supported.

Edit: looks like it will be closable with #2092 merged.

**Comment by ph-One** [comment]
:zap:, but I don't know that I'd want someone just sitting on my invite. Can we set an expiration?

**Comment by zetok** [comment]
> :zap:, but I don't know that I'd want someone just sitting on my invite. Can we set an expiration?

Not really..

**Comment by zetok** [comment]
#2092 was merged, closing.

**Comment by zetok** [comment]
Reopening, since merged changes were reverted due to bugs (crashes) that #2092 introduced.

**Comment by sudden6** [comment]
#2092 was fixed an merged
