### ISSUE TITLE
TOX development status and QTOX.

### ISSUE THREAD

**Issue by dcapeletti** [qTox/qTox#2068]
Hello,
I'm intrigued about the development of TOX and QTOX. While they do not receive updates and there are some bugs when transferring files. What is the development status? How long it will be stable?

**Comment by suhr** [comment]
We all are waiting until @tux3 returns.

**Comment by antis81** [comment]
> We all are waiting until @tux3 returns.

That's a bit rude. Better say, development status is totally active, but a bit delayed for 2-3 weeks due to organisational reasons. :smile:

**Comment by suhr** [comment]
I believe this can be closed.

**Comment by ProMcTagonist** [comment]
@dcapeletti This issue has been closed because active development in the main repository has resumed. We shouldn't have any more pauses like this because there are more developers who can write to this repo :)
