### ISSUE TITLE
Command line options

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#207]
Basically, like Toxic and Venom 

https://img.bi/#/WpzHYKR!BjebnxxQL9NeUXPiNe7bkwUTbgU0IK5Q4pTVPsDd

<blockquote><pre>
~ venom --help
Usage:
venom [OPTION...]
 
Help Options:
-h, --help Show help options
 
Application Options:
-f, --file=<file> Set the location of the tox data file
-l, --loglevel=<loglevel> Set level of messages to log
--offline Start in offline mode
--textview Use textview to display messages
-V, --version Display version number
</pre></blockquote>

**Comment by suhr** [comment]
- `-h` and `--help` should show usage
- `-v` and `--version` should show version
- `qtox ‹garbage›` should show an error
- Consider adding `qtox -p` for profile selecting
- For proxy selection there's http_proxy. No need to have a cli opt for
