### ISSUE TITLE
proxy settings can not be set before the login

### ISSUE THREAD

**Issue by boza111** [qTox/qTox#2070]
proxy settings can be set only after logging in ....

**Comment by agilob** [comment]
Interesting, how would you like it to be implemented?

**Comment by zetok** [comment]
it probably doesn't have to be implemented - what is needed though, is a way to launch qTox in an "offline" mode, where it doesn't connect to the network.

It could be implemented as command like switch.

With that, one could start qTox in offline mode, set proxy, and restart qTox.

**Comment by NoxNoctium** [comment]
another option would be to add this setting to the already proposed "first run" tour.
zetoks idea would also fit as a status chooser shown on the login screen, one could also choose to sign in already marked as busy or away then.
WLM did it like this:
![WLM](http://qs.lc/4b0ko)

**Comment by agilob** [comment]
@markus1540 that one is doable.

**Comment by agilob** [comment]
Uppss! thing is we don't support going offline at all!

**Comment by ovalseven8** [comment]
Important security issue especially for people who would like to use Tor. 

A solution is needed.

**Comment by ghost** [comment]
> Uppss! thing is we don't support going offline at all!

Yes you're right. (Never really saw this)
So this need to be implemented.

**Comment by agilob** [comment]
Hmm... this can be added to import profile widget, it's nearly empty now.

**Comment by ProMcTagonist** [comment]
Perhaps Import could be renamed to More or Options and have importing, proxy settings, etc.

**Comment by ovalseven8** [comment]
Offline-mode would be more user-friendly, I think.

**Comment by ovalseven8** [comment]
@tux3 
Don't know how much work implementing offline mode is. Do you think you'll have time soon? It would be a very nice feature and is also important for Tor users.

**Comment by kradan** [comment]
Currently (3d2d0e6a63894b1c36163ea0eddcf7e6fad2ec07) it is not possible to register a tox account via tor. It would be great to fix this for this guide to work: https://askubuntu.com/questions/700081/how-to-tunnel-tox-through-tor
```
$ torify ./qtox                                                                                
1531816378 WARNING torsocks[15192]: [syscall] Unsupported syscall number 383. Denying the call (in tsocks_syscal() at syscall.c:488)                                                                                             
[08:33:09.828 UTC] persistence/settings.cpp:129 : Debug: No settings file found, using defaults                  
[08:33:10.028 UTC] persistence/settings.cpp:133 : Debug: "Loading settings from :/conf/qtox.ini"                 
[08:33:10.297 UTC] ipc.cpp:61 : Debug: Our global IPC ID is  1908096692443842401
[08:33:10.534 UTC] main.cpp:262 : Debug: commit:  3d2d0e6a63894b1c36163ea0eddcf7e6fad2ec07
[08:41:26.073 UTC] persistence/profile.cpp:214 : Warning: Failed to lock profile  "
```

**Comment by anthonybilinski** [comment]
This is effecting deployment on Whonix, since qTox cannot be run with Torsocks on a new profile, due to UDP mode. I'll bump priority to high and pull this into the 1.17.0 milestone in place of #5619.
