### ISSUE TITLE
Can you update README.md please?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2071]
Hi there! I am looking for qtox for windows for my friend (Toxy is too old). Download links on README.md (tux3-dev.tox.im domain) seems to be obsolete (ssl cert failure).

So... can you update it please?

**Comment by suhr** [comment]
See https://github.com/tux3/qTox/pull/2035. We're waiting for @tux3 to merge it.

**Comment by quininer** [comment]
They moved to here, although there is no qtox.
https://build.tox.chat/
https://jenkins.impy.me/

**Comment by ghost** [comment]
I know about these resources, tnx a lot.

But I need qtox... :(

**Comment by rugk** [comment]
> See #2035. We're waiting for @tux3 to merge it.

Why doesn't one of the official contributors do this?

**Comment by suhr** [comment]
@rugk For now only @tux3 have write access.

**Comment by agilob** [comment]
merged.
