### ISSUE TITLE
status icons pixelated

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#2072]
![firefox2](https://cloud.githubusercontent.com/assets/2544251/9236544/62012a30-413d-11e5-9193-1bc6f9f57fbc.png)

**Comment by antis81** [comment]
How about using SVG's?

**Comment by antis81** [comment]
@zetok @tux3 Missing an `appearance` label. Can you please add one? What does the `l`prefix (e.g. l-bug) stand for?

**Comment by zetok** [comment]
@antis81 `I` stands for what kind of `Issue` it is

**Comment by antis81** [comment]
@zetok Thanks! I read an `l` instead of `I` - no problem.

**Comment by antis81** [comment]
This is likely related to #1075, #1927 and maybe fixed, since #1774 is closed.

**Comment by agilob** [comment]
@antis81 how to fix it? qt.pro includes svg module.

**Comment by ghost** [comment]
Seems fixed?

![screenshot from 2015-11-12 11-57-41](https://cloud.githubusercontent.com/assets/6382342/11116740/d0422d7a-8934-11e5-9fe1-0e25e2280742.png)

**Comment by ProMcTagonist** [comment]
They shouldn't be gigantic like that.
