### ISSUE TITLE
Tox repo and hosted server doesn't works!

### ISSUE THREAD

**Issue by bitchecker** [qTox/qTox#2073]
When i try to run an update on my Fedora 22 with XFCE, I see this error from tox repository:

```
Synchronization cache for repo 'tox' from 'https://repo.tox.im/x86_64': Can not download repomd.xml: Can not download repodata / repomd.xml: All mirrors were tried failed, disabling underway. 
```

I tried to go on `https://wiki.tox.im/Binaries` to see if tox.repo was changed but i see that also website is offline as we can see from attached image:
![istantanea_2015-08-14_17-44-11](https://cloud.githubusercontent.com/assets/11056930/9277697/200d0098-42ac-11e5-8ad7-5551dcffd253.png)

**Comment by linux-modder** [comment]
that  domain has been dead for  long time now, see http://blog.tox.chat and issue 2054
 [issue 2054](https://github.com/tux3/qTox/issues/2054)

**Comment by ProMcTagonist** [comment]
The domain you tried to use has been seized by a rogue third party. It is NOT associated with the Tox project or its developers. The real website of the Tox project is https://tox.chat.

You should definitely remove the old repo, and then follow the instructions on https://wiki.tox.chat/binaries#gnulinux which tell you how to add the new authentic one.

Please remember to use the [real website](https://tox.chat), and to tell your friends so we can avoid confusion.

Thanks for using Tox :)

**Comment by bitchecker** [comment]
@ProMcTagonist so now doesn't exist an RPM repo!!

**Comment by suhr** [comment]
@zetok Can be closed.
