### ISSUE TITLE
Fedora 22 build issues

### ISSUE THREAD

**Issue by pollend** [qTox/qTox#2074]
I don't appear to have tox/toxav.h. 

g++ -c -pipe -fno-exceptions -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DGIT_VERSION="\"74b771373d9f367a48f8cf7d175dd34cd10e0b67\"" -DTIMESTAMP=1439608216 -DLOG_TO_FILE -DQT_MESSAGELOGCONTEXT -DQTOX_PLATFORM_EXT -DQTOX_FILTER_AUDIO -DENABLE_SYSTRAY_STATUSNOTIFIER_BACKEND -DENABLE_SYSTRAY_GTK_BACKEND -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I. -Ilibs/include -isystem /usr/include/glib-2.0 -isystem /usr/include/gtk-2.0 -isystem /usr/include/atk-1.0 -isystem /usr/include/cairo -isystem /usr/include/ffmpeg -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/pango-1.0 -I/usr/lib64/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib64/gtk-2.0/include -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -isystem /usr/include/glib-2.0 -isystem /usr/include/gtk-2.0 -isystem /usr/include/atk-1.0 -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/cairo -isystem /usr/include/pango-1.0 -I/usr/lib64/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib64/gtk-2.0/include -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtOpenGL -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o addfriendform.o src/widget/form/addfriendform.cpp
In file included from ./src/core/core.h:32:0,
                 from src/widget/form/addfriendform.cpp:29:
./src/core/coreav.h:25:23: fatal error: tox/toxav.h: No such file or directory

**Comment by linux-modder** [comment]
Builds fine  on my fedora 22 instance please  fpaste  the  output of  ls -la /path/to/qtox

**Comment by pollend** [comment]
drwxrwxr-x. 20 michaelp michaelp   4096 Aug 14 20:48 .
drwx------. 50 michaelp michaelp   4096 Aug 14 19:45 ..
drwxrwxr-x.  4 michaelp michaelp   4096 Aug 14 19:42 android
-rw-rw-r--.  1 michaelp michaelp    343 Aug 14 19:42 android.qrc
drwxrwxr-x.  2 michaelp michaelp   4096 Aug 14 19:42 audio
-rw-rw-r--.  1 michaelp michaelp  12000 Aug 14 19:51 audiofilterer.o
-rw-rw-r--.  1 michaelp michaelp   1368 Aug 14 19:51 autorun_osx.o
-rw-rw-r--.  1 michaelp michaelp  30552 Aug 14 19:51 autorun_win.o
-rw-rw-r--.  1 michaelp michaelp 396760 Aug 14 19:51 autorun_xdg.o
-rw-rw-r--.  1 michaelp michaelp     34 Aug 14 19:42 bootstrap.bat
-rw-rw-r--.  1 michaelp michaelp   1537 Aug 14 19:42 bootstrap-osx.sh
-rwxrwxr-x.  1 michaelp michaelp   5615 Aug 14 19:42 bootstrap.sh
-rw-rw-r--.  1 michaelp michaelp  11168 Aug 14 20:07 closures.o
drwxrwxr-x.  3 michaelp michaelp   4096 Aug 14 19:42 debian
-rw-rw-r--.  1 michaelp michaelp     58 Aug 14 19:42 dialogs.ini
-rw-rw-r--.  1 michaelp michaelp  16488 Aug 14 20:08 enums.o
drwxrwxr-x. 10 michaelp michaelp   4096 Aug 14 20:42 filter_audio
drwxrwxr-x.  8 michaelp michaelp   4096 Aug 14 19:42 .git
-rw-rw-r--.  1 michaelp michaelp    173 Aug 14 19:42 .gitattributes
-rw-rw-r--.  1 michaelp michaelp    103 Aug 14 19:42 .gitignore
drwxrwxr-x.  7 michaelp michaelp   4096 Aug 14 19:42 img
-rw-rw-r--.  1 michaelp michaelp  12434 Aug 14 19:42 INSTALL.md
drwxrwxr-x.  3 michaelp michaelp   4096 Aug 14 20:48 libs
drwxrwxr-x. 12 michaelp michaelp   4096 Aug 14 20:45 libsodium
-rw-rw-r--.  1 michaelp michaelp  35147 Aug 14 19:42 LICENSE
-rw-rw-r--.  1 michaelp michaelp 216482 Aug 14 20:42 Makefile
drwxrwxr-x.  3 michaelp michaelp   4096 Aug 14 19:42 osx
-rw-rw-r--.  1 michaelp michaelp    304 Aug 14 19:42 qTox.desktop
-rw-rw-r--.  1 michaelp michaelp  19374 Aug 14 19:42 qtox.pro
-rw-rw-r--.  1 michaelp michaelp   1934 Aug 14 19:42 README.md
drwxrwxr-x.  3 michaelp michaelp   4096 Aug 14 19:42 res
-rw-rw-r--.  1 michaelp michaelp   5806 Aug 14 19:42 res.qrc
-rwxrwxr-x.  1 michaelp michaelp    884 Aug 14 19:42 simple_make.sh
drwxrwxr-x.  6 michaelp michaelp   4096 Aug 14 19:42 smileys
drwxrwxr-x. 10 michaelp michaelp   4096 Aug 14 19:42 src
-rw-rw-r--.  1 michaelp michaelp 157424 Aug 14 20:10 statusnotifier.o
-rw-rw-r--.  1 michaelp michaelp  28512 Aug 14 19:51 timer_osx.o
-rw-rw-r--.  1 michaelp michaelp  28512 Aug 14 19:51 timer_win.o
-rw-rw-r--.  1 michaelp michaelp 313272 Aug 14 19:51 timer_x11.o
drwxrwxr-x.  3 michaelp michaelp   4096 Aug 14 19:42 tools
drwxrwxr-x. 16 michaelp michaelp   4096 Aug 14 20:47 toxcore
drwxrwxr-x.  2 michaelp michaelp   4096 Aug 14 19:50 translations
drwxrwxr-x. 22 michaelp michaelp   4096 Aug 14 19:42 ui
-rw-rw-r--.  1 michaelp michaelp  11876 Aug 14 19:51 ui_aboutsettings.h
-rw-rw-r--.  1 michaelp michaelp   6344 Aug 14 19:51 ui_advancedsettings.h
-rw-rw-r--.  1 michaelp michaelp   8493 Aug 14 19:51 ui_android.h
-rw-rw-r--.  1 michaelp michaelp  11300 Aug 14 19:51 ui_avsettings.h
-rw-rw-r--.  1 michaelp michaelp  10693 Aug 14 19:51 ui_filetransferwidget.h
-rw-rw-r--.  1 michaelp michaelp  32639 Aug 14 19:51 ui_generalsettings.h
-rw-rw-r--.  1 michaelp michaelp   2789 Aug 14 19:51 ui_loadhistorydialog.h
-rw-rw-r--.  1 michaelp michaelp  19150 Aug 14 19:51 ui_loginscreen.h
-rw-rw-r--.  1 michaelp michaelp  28652 Aug 14 19:51 ui_mainwindow.h
-rw-rw-r--.  1 michaelp michaelp   6088 Aug 14 19:51 ui_privacysettings.h
-rw-rw-r--.  1 michaelp michaelp  12243 Aug 14 19:51 ui_profileform.h
-rw-rw-r--.  1 michaelp michaelp   4840 Aug 14 19:51 ui_setpassworddialog.h
drwxrwxr-x.  4 michaelp michaelp   4096 Aug 14 19:42 updater
drwxrwxr-x.  2 michaelp michaelp   4096 Aug 14 19:42 windows

**Comment by pollend** [comment]
i think these two devel packages were missing from the fedora install page for the toxcore section under fedora opus-devel libvpx-devel. but now im getting this error ibavcodec/avcodec.h: No such file or directory

looks like i also don't have the ffmpeg libraries. you might want to add these to the installer instructions

**Comment by agilob** [comment]
> ./src/core/coreav.h:25:23: fatal error: tox/toxav.h: No such file or directory

How did you acquire source code?
