### ISSUE TITLE
Links to tox.im on pkg.tox.chat

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2075]
Hello,

on pkg.tox.chat there are links to the old website.
Please fix it.

For example here: http://pkg.tox.chat/dists/nightly/main/binary-amd64/Packages

> Homepage: https://tox.im
> License: GPLv3+

**Comment by suhr** [comment]
See https://github.com/tux3/qTox/issues/2073. We're waiting for @tux3 return.

**Comment by linux-modder** [comment]
Removing the  mention shouldn't take  tux3's return  if  so  please explain why.

**Comment by suhr** [comment]
> if so please explain why

Only @tux3 have the write access.

**Comment by zetok** [comment]
Currently, I would suggest to use binaries from https://wiki.tox.chat/binaries#other_linux until repo stuff will get sorted out. I think that this issue can be closed..

(currently there's no ETA of when repo will get sorted out)
