### ISSUE TITLE
website certificate

### ISSUE THREAD

**Issue by pollend** [qTox/qTox#2076]
tux3-dev.tox.im has an invalid certificate.

**Comment by suhr** [comment]
See https://github.com/tux3/qTox/issues/2075 to see https://github.com/tux3/qTox/issues/2073 to see https://github.com/tux3/qTox/issues/2054 to see...

**Comment by ProMcTagonist** [comment]
Hi, @pollend. The domain you tried to use has been seized by a rogue third party. It is NOT associated with the Tox project or its developers. The real website of the Tox project is https://tox.chat.

You should remove the old repo, and then follow the instructions on https://wiki.tox.chat/binaries#gnulinux which tell you how to add the new authentic one.

Please remember to use the real website, [tox.chat](https://tox.chat), and to tell your friends so we can avoid confusion.

Thanks for using Tox :)

**Comment by pollend** [comment]
I don't need to worry about that, I build the binary's from source.

**Comment by suhr** [comment]
@zetok Can be closed.
