### ISSUE TITLE
Copied friends id is different than in their profile

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#2079]
I tried sharing XXs id with Antox client...
1. Right click on friend -> copy ID
2. send to another client
3. try adding new contact with that ID
4. ID invalid

When I asked friend to copy me their ID from their profile it was longer - it contained NoSpam appendix. Copying ID should copy NoSpam part or should be removed at all. Now it's a completely pointless feature.

**Comment by PKEv** [comment]
look: https://github.com/irungentoo/toxcore/issues/1300
and 
https://github.com/irungentoo/toxcore/issues/1350

**Comment by agilob** [comment]
;/
closing here as it's core issue. it's 100% bug or dysfunction.
