### ISSUE TITLE
Display toxcore version

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2086]
Additionally to your own version number (or hash) you should also display the toxcore version in the About window as i suggested in https://github.com/irungentoo/toxcore/issues/1395 for the core.

**Comment by ph-One** [comment]
:zap:

**Comment by blobgo** [comment]
@ph-One What should this mean?

**Comment by agilob** [comment]
This is still not implemented in toxcore...

**Comment by suhr** [comment]
Indeed. Toxcore doesn't even have unstable versions.

**Comment by agilob** [comment]
This was fixed with #2137. but currently toxcore doesn't support versioning, so toxcore version label is hidden in about tab. Show it when we migrate to new toxcore api.
