### ISSUE TITLE
Copy QR code image doesn't work

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2089]
Hello,

if I want to copy the QR code image in qTox (latest build) on Ubuntu Unity, it doesn't work.
Although the Tox ID is copied.

**Comment by zetok** [comment]
I could reproduce. I've clicked to copy image in qTox, and I've tried to make a new image in krita from clipboard.

Krita didn't detect any image in clipboard.

Krita works just fin with images copied to clipboard from ksnapshot.
