### ISSUE TITLE
Some windows/buttons are not translateable

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2090]
Hello,

unfortunately, many windows/buttons are not translateable.
I think this should be fixed.

A few examples:
https://i.imgur.com/l1zjPHW.png | 'Yes' and 'No'
https://i.imgur.com/La1OK6p.png | 'Cancel'
https://i.imgur.com/qwmv3WR.png | 'Save' and 'Cancel'

Note: That are only some examples, there are many dialogues with these problems.

**Comment by PKEv** [comment]
duplicate #1720
