### ISSUE TITLE
Resume transfers when a peer goes back online.

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#210]

**Comment by ghost** [comment]
May want to also automatically restart audio/video calls if the other user is disconnected for less than X seconds. Users of mobile clients may have intermittent but momentary connectivity issues.

Additionally audiobotze tends to randomly die for only ~2s. Toxic re-starts file transfers and re-calls it when it comes back online quickly.

**Comment by dubslow** [comment]
This can be closerino cappucino
