### ISSUE TITLE
Focus management during initial setup

### ISSUE THREAD

**Issue by tyrylu** [qTox/qTox#2100]
When an user creates a new account, the settings window is likely opened (inferred from the title), but the keyboard focus is on the main window elements. After tabbing a while, the user reaches some edit control which can't be left using the keyboard. I have no idea if the NVDA screen reader messes that somehow. Tried on the latest windows build from the tox wiki, 64-bit version.

**Comment by Diadlo** [comment]
What will be better change default focus position or change title on `qtox`?

**Comment by tyrylu** [comment]
Depends on the state of the settings widget. If it's opened, it probably should have focus, otherwise, the title should be changed.

**Comment by zetok** [comment]
>After tabbing a while, the user reaches some edit control which can't be left using the keyboard.

Note: the edit field is the friend request message in `addfriendform`.

One can go back from it by `shift + tab`, but not move forward.

I wonder if `tab` could be disabled in it.. or something.

**Comment by tyrylu** [comment]
This one can probably be closed, correct. But, unfortunately, some others will follow.
