### ISSUE TITLE
Edit control labels not read by screen readers

### ISSUE THREAD

**Issue by tyrylu** [qTox/qTox#2101]
The labels for the edit controls (for example the nick and password boxes in initial setup after first launch) have no screen reader associated labels. Calling setAccessibleDescription/setAccessibleName could help, but i am not exactly sure which of those is appropriate there.

**Comment by agilob** [comment]
How can I reproduce it? Do I need a dedicated screen reader?

**Comment by tyrylu** [comment]
It would be best, because nowadays there are so many accessibility APIs on Windows (Iaccessible/Iaccessible2, UIA etc), that i am not aware of any testing tool and it's always good to know how the issue is presenting itself.
I would suggest testing with NVDA (http://www.nvda-project.org). Same applies to the previous issue, where you should avoid mouse usage as long as possible.
