### ISSUE TITLE
ability to hide the window during a screenshot

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#2103]
when you send a screenshot by qtox that sometimes you would like that application window is minimized automatically as it takes a lot of space on your screen

**Comment by ProMcTagonist** [comment]
I find myself wanting this sometimes, but other times I want to screenshot something in the qTox window.

**Comment by zetok** [comment]
Probably should be implemented as a option in r-click menu when clicking on screenshot button.. or is there a better way to do it?

**Comment by ProMcTagonist** [comment]
If it's not too cluttered, a button or keybind in the screenshot overlay mode itself to hide/unhide the qTox window would be nice, and preferable to a right-click menu.

**Comment by ProMcTagonist** [comment]
Currently it only hides. It should toggle.

**Comment by zetok** [comment]
> Currently it only hides. It should toggle.

yep, made #2139
