### ISSUE TITLE
When updating via the terminal there is an error

### ISSUE THREAD

**Issue by korvalol** [qTox/qTox#2111]
How to fix the error?

W: Could not get https://pkg.tox.chat/dists/nightly/main/binary-amd64/Packages HttpError404

W: Could not get https://pkg.tox.chat/dists/nightly/main/binary-i386/Packages HttpError404

E: Some index files failed to download. They were ignored and instead were used older versions.

**Comment by dcapeletti** [comment]
Me too feel the same. I downloaded the binary from https://github.com/tux3/qTox/ where it says Linux.

**Comment by zetok** [comment]
Currently repo is not being maintained - you can instead download binaries.

Closing, since none of qTox maintainers have an access to that repo to fix it.
