### ISSUE TITLE
Separation between history and current conversation?

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2113]
Hello,

at the moment there is no separation between the history and the current conversation if you're talking to somebody.
I think it would be clearer if there was a labeling or something. Any ideas?

Screenshot with example:
https://i.imgur.com/U0tG3zi.png
(Added a black border, but perhaps there are more beautiful alternatives)

**Comment by suhr** [comment]
Maybe slightly different font size or color?

**Comment by zetok** [comment]
#2013 should fix it - i.e. there's always shown date of when given conversation had taken place, and new dates are appended as time passes, so even when running qTox for longer periods than day it won't be confusing.

I'm not quite sure whether my description is really helpful - it would be best if you could test it yourself.

Issue seems to be closable after #2013 gets merged.

**Comment by ovalseven8** [comment]
Built qTox with the new chatform branch.
You're right, this issue should be closable after it gets merged.

**Comment by sudden6** [comment]
Dates are now shown between messages
