### ISSUE TITLE
Highlighting on empty aliases

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2119]
Hello,

if you've an empty alias and you're in a groupchat:
Every message somebody writes is highlighted in orange.

I think the better solution would be if no message or only messages with the alias you got, while joining the groupchat, will be highlighted.

**Comment by sudden6** [comment]
Still happens on 76c4cf7d390ece3d0ec57b771fb9aaa21f7337f7 if username is empty every message containing a character from [a-zA-z0-9] triggers the highlighting.
