### ISSUE TITLE
Use KDE file selection dialog

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#212]
Under KDE, qTox uses the Qt file selection dialog rather than KDE's native file picker.

**Comment by tux3** [comment]
I'd rather not write platform-specific code.

**Comment by ghost** [comment]
According to QFileDialog's documentation, it should automatically use native file selection dialogs. For me it does this under GNOME but not under KDE.

**Comment by tux3** [comment]
I'll see what I can do

**Comment by zetok** [comment]
Hm, under i3wm it also uses horrible file selection dialog.

**Comment by dubslow** [comment]
The Cinnamon dialog aint too pretty either -- I'm not sure there's a lot we can do, short of maybe filing complaints against Qt.

**Comment by krepa098** [comment]
Could be due to the fact that KDE4 is based on Qt4. None of my Qt5 applications uses of the KDE file picker.

**Comment by msteinbeck** [comment]
Xfce also uses the Qt file dialog

**Comment by lbeltrame** [comment]
If the user has KDE Frameworks 5 (KF5; Qt5 based) and the relevant QPA plugin provided by them (it's the "frameworkintegration" framework), it should be picked up automatically.

Reference: http://api.kde.org/frameworks-api/frameworks5-apidocs/frameworkintegration/html/index.html

**Comment by tux3** [comment]
QFileDialog tries to use a native dialog whenever possible, if it fails we can't easily fix that from the qTox source code. Although installing platform plugins might work.
