### ISSUE TITLE
Two keys on keyboard don't work with qTox

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2122]
Hello,

on my (German) keyboard, two keys don't work:

![Key 1](https://i.imgur.com/6eCqNBw.gif)
The '°'-char is working, but '^' doesn't work

![Key 2](https://i.imgur.com/bfBxIae.gif)
This key doesn't work at all

Perhaps someone can test it again.

**Comment by zetok** [comment]
Can someone else reproduce?

qTox itself doesn't really have any limitations on input text, so I suspect that it's an upstream (Qt) issue.

**Comment by ghost** [comment]
Noticed it too with binaries from ~3 days ago.
Maybe relevant: I upgraded Mint from 17.1 to 17.2 shortly before the problem started.

**Comment by sudden6** [comment]
works on my system
openSUSE Tumbleweed

![grc-graph1](https://cloud.githubusercontent.com/assets/5585762/9522074/d266c5a0-4cd2-11e5-8fe9-579644606650.png)

built from:
git b02cf2dbc7ad97af3e8429ff454124ba986837d9

Have you tried entering "^^" and for example "´a" and "`b" ?
Because I think this is how the keys normally work, they must be used in combination with letters.

**Comment by ghost** [comment]
@sudden6 yes, no variant works.

Tested again with the latest build bae8a0d0c868d77ca083556c66575e63e4cbcc48

QMake 3.0
Qt 5.2.1

**Comment by sudden6** [comment]
@ovalseven8 @kehugter may you please add your OS version?

I highly suspect a qt/OS misconfiguration.

**Comment by ovalseven8** [comment]
Tested with Lubuntu 14.04; Commit-Hash https://github.com/tux3/qTox/commit/395aeb12b2b533aebc8b2cf290a5aec50bed1839;

**Comment by ghost** [comment]
Mint Cinnamon 17.2

**Comment by agilob** [comment]
SO both Mint Cinnamon 17.2 and Lubuntu 14.04 are affected? I can't reproduce on arch with plasma.

**Comment by ovalseven8** [comment]
@agilob: Ubuntu Unity 14.04.3 and Lubuntu 15.04 are also affected.

**Comment by agilob** [comment]
which version of qt do you have?

**Comment by noerw** [comment]
Also having this issue on ubuntu gnome 14.04, German keyboard layout.

It's  dependend on the keyboard layout:
Not having this issue with English (programmer dvorak) nor English (US) layout.

edit: not having this issue on windows 7 x64 with german keyboard layout

**Comment by ghost** [comment]
I ~can reproduce what @noerw describes. I can write the problematic symbols, but it seems that they only look the same, but are different ones. For example, I can't put them over a character (eg. `´` + `a`), they are printed immediately on their own.

Also, unlike in #2158, you can paste the problematic symbols in the input area.

**Comment by sudden6** [comment]
I think I solved this mystery, it is not a qTox problem.
@ovalseven8 uses a keyboard config without the `nodeadkeys` option, therefore cannot enter these symbols, while @kehugter uses the `nodeadkeys` option and cannot write `à` in a single symbol.
https://en.wikipedia.org/wiki/Dead_key
https://wiki.ubuntuusers.de/Sonderzeichen

**Comment by ovalseven8** [comment]
@sudden6: It is actually a qTox problem. Every program works, only qTox doesn't. Without the `nodeadkeys` option, the char should appear after pressing the key a second time. But it doesn't in qTox.

**Comment by sudden6** [comment]
@ovalseven8 I did some further research in a Lubuntu 14.04 vm and found something strange.
It looks like lxde is setting the keyboard layout in a very weird way.

When I set it with `localectl set-x11-keymap de nodeadkeys` (which is probably what setup does) it isn't applied correctly and qtox shows the behavior described by you.

But if I instead set the keyboard layout with `setxkbmap de nodeadkeys` everything works fine. Of course the setting doesn't persist, but you could try this: https://wiki.archlinux.org/index.php/KDM#Keyboard_maps

As a conclusion, this is most probably not an issue with qtox, but some lxde/openbox/qt weirdness.

**Comment by ovalseven8** [comment]
@sudden6: But why every program else works fine?

**Comment by sudden6** [comment]
@ovalseven8 have you tried another qt program or just gtk based ones?

**Comment by ovalseven8** [comment]
@sudden6: Yes, all programs are working fine so far. Seems it has another background...

**Comment by ghost** [comment]
Also, it used to work in qTox not long ago.

**Comment by zetok** [comment]
@kehugter on old, outdated builds?

**Comment by noerw** [comment]
I just compiled qTox myself (54fc35e714bdf03e13d21e3d2d6c2bddfd37baca), and it suddenly works as expected.
The build from the apt repo still has the issue.

[This was a Qt bug prior to v5.1](http://wiki.qt.io/Qt_5.0.2_Known_Issues#Linux). Does the build server run the latest Qt version?

**Comment by zetok** [comment]
@noerw against which Qt you've compiled it?

Also, which version from repo are you using?
`qtox` (using Qt 5.5) or `qtox-qt5.4.2` ?

Edit: if you use `qtox`, could you check how `qtox-qt5.4.2` works?

**Comment by ovalseven8** [comment]
@zetok: Did some further testing:
qTox (Qt 5.5.0) and qTox (Qt 5.4.2) from https://wiki.tox.chat/binaries aren't working.

A compiled qTox in contrast is working well.

Environment: Lubuntu 15.04

**Comment by ovalseven8** [comment]
Did further testing:
Latest qTox (Qt 5.5.0 and Qt 5.4.2) from https://wiki.tox.chat/binaries isn't still working.

Another strange experience, in contrast to @noerw:
Compiled with Lubuntu 15.04:

-> https://github.com/tux3/qTox/commit/9b572da5c41ea729324e311c4526a2c636f8128c (Latest version)
==> :x: doesn't work
-> https://github.com/tux3/qTox/commit/dffeb7d6d67d0eaff2f1215f3bebdee7be497aaf (Commit from about 17 days ago)
==> :white_check_mark: works

**Edit:** No, wrong! -> https://github.com/tux3/qTox/issues/2122#issuecomment-140429569

**Comment by zetok** [comment]
@ovalseven8 could you `git bisect` it?
https://github.com/tux3/qTox/wiki/Testing#regression-testing ← should be helpful, if you encounter problems, please say so

**Comment by ovalseven8** [comment]
@zetok: My post above seems to be false.
After `git bisect` and further testing, I am really confused. Sometimes it worked after a few time, somtimes it didn't work at all. Independet from the qTox-version. I don't know what is going on.

The only what I can say: The binaries from the Wiki haven't never worked.

**Comment by noerw** [comment]
@zetok: From the repo both versions don't work.
The compiled build that works uses Qt v.5.2.1, at least that's the output of `qmake --version`, and is the latest lib in the ubuntu 14.04 repositories.

How would I ideally install a newer Qt version?

**Comment by aaannndddyyy** [comment]
I can confirm it for Trisquel Gnu/Linuxlibre
Latest binary from tox.chat.
Both keys not working: ^ and é è

I tried explicitly other qt programs and they have no problem  with.

It has to do with the libraries used.
I do not have that problem with the launchpad version (kytv) of qTox.

**Comment by agilob** [comment]
#2564
