### ISSUE TITLE
SIGSEGV when trying to video call someone

### ISSUE THREAD

**Issue by roberdorfer** [qTox/qTox#2123]
Is soon as he accepts my call, my client crashes.

Arch linux 64 bit.

**Comment by agilob** [comment]
Version of qtox? What client and version second user has? We need more info.

**Comment by roberdorfer** [comment]
r3155.ce2c830-1 this is my version. The other guy has qtox as well, but no idea about the version, maybe I can find out.

**Comment by zetok** [comment]
@RoBi89 that's terribly outdated. Closing; if you will be able to reproduce with newest qTox, please comment for reopen.
