### ISSUE TITLE
Own voice as echo while both users are using headset

### ISSUE THREAD

**Issue by zen2** [qTox/qTox#2126]
Brief Description:
I hear my own voice as echo while my contact and me are using headset !
I've test it:
- with/without "+20db" switch of my sound card
- with/without "Filter audio" switch
- with a contact on macosx and another on linux

Notes:
- if my contact raise the general volume, the echo volume raise too.
- no specific additional echo but expected one with EchoBot
- my contacts don't have the problem.

Operating System Specs:
- Linux gentoo 64bits (multilib)
- Alsa with dmix 
- Driver SND_VIRTUOSO

Software:
- media-libs/openal-1.16
- media-video/ffmpeg-2.7.2
- media-libs/libfilteraudio (upstream)
- net-libs/tox (upstream)
- net-im/qtox (nightly build: Commit hash: b02cf2dbc7ad97af3e8429ff454124ba986837d9)

Hardware:
- Intel Core i7 990x + X58
- soundcard AV200 - Xonar STX (Asus Virtuoso 100)
- Headset

Reproducible: Always.

**Comment by agilob** [comment]
Just for reference: https://github.com/tux3/qTox/issues/1655 https://github.com/tux3/qTox/issues/820

First implementation: https://github.com/tux3/qTox/pull/875

**Comment by zetok** [comment]
um.. if that's a duplicate, shouldn't it be closed?

**Comment by agilob** [comment]
keeping open because different issue provide different information...

**Comment by antis81** [comment]
Should be fixed now by a sane input gain implementation. Thus, closing.
