### ISSUE TITLE
Screenshot function: Few words cut off

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2127]
Hello,

the 'Escape'-word is cut off with the new 'Hide qTox window'-function.

Reproduce:
1. Click the screenshot button
2. Make a selection
3. Then the following is displayed:
![bildschirmfoto 2015-08-28 10 28 33](https://cloud.githubusercontent.com/assets/8258609/9542313/f0341108-4d6f-11e5-82e9-92997df625dc.png)

Environment: Ubuntu Unity 14.04.3
Commit-Hash: https://github.com/tux3/qTox/commit/bae8a0d0c868d77ca083556c66575e63e4cbcc48

**Comment by zetok** [comment]
Can't reproduce on Gentoo under i3wm

**Comment by agilob** [comment]
What is your screen resolution?

**Comment by ovalseven8** [comment]
Don't think that it has something to do with the screen resolution. Did some further testings:
On the same machine with Lubuntu 15.04 I also couldn't reproduce it.

Perhaps only a Ubuntu Unity issue? Would be good if more people test it...

**Comment by agilob** [comment]
We can shorten this text to something like "Press Esc to quit, Spacebar to hide qTox window and Enter to capture image"

**Comment by zetok** [comment]
> What is your screen resolution?

1920x1080

**Comment by ghost** [comment]
Works fine before and after making a selection on
Mint Cinnamon 17.2
Commit hash 97f61863084e8098e435ab05fedb80e3615610ed
1680x1050 and 1366x768

**Comment by ovalseven8** [comment]
Actually, not only 'Escape' is cut off, but:
`repeat region selection. Press <b>Escape</b>`
