### ISSUE TITLE
Webcam is no longer detected in latest build

### ISSUE THREAD

**Issue by DanTheBritish** [qTox/qTox#2129]
OS: Xubuntu 15.04
Kernel: 4.1.4-040104-generic
qTox commit: 7a8512e5d4a4f9b4fbbe4d1e980424387bbd65ae

```
priseth@urban-menace:~/tox/qTox$ for I in /sys/class/video4linux/*; do cat $I/name; done
Integrated Camera
priseth@urban-menace:~/tox/qTox$ v4l2-ctl --list-devices
Integrated Camera (usb-0000:00:1a.0-1.6):
    /dev/video0
```

![Screenshot](http://imgur.com/fqqlHFBl.png)

**Comment by agilob** [comment]
> qTox commit: 7a8512e5d4a4f9b4fbbe4d1e980424387bbd65ae

No such commit ;)

Anyway, this might be dependent on ffmpeg. Did you upgrade it recently?

**Comment by ghost** [comment]
In my case, the camera was only not automatically detected. I had to select the camera from the drop-down list. With older builds (~1 month) it was automatic.

**Comment by agilob** [comment]
Did we recently add anything that modified video devices? I can't recall it...

**Comment by zetok** [comment]
@kehugter was there earlier a way to set up `None` camera input?

**Comment by agilob** [comment]
There always was.

**Comment by antis81** [comment]
Same here ... no webcam (builtin iSight).

**EDIT:** Oh wait ... I can now select "builtin iSight" from the menu (default: none), but qTox directly "stalls/hangs".

**Comment by zetok** [comment]
> There always was.

Actually, that's not the case. For a long time there was no `None` "camera - first there was switch to ffmpeg, and desktop streaming was added, and after that, @tux3 added `None` as input device.

**Comment by ghost** [comment]
@zetok I couldn't tell. I never had to select anything, so I never looked at the list. I know that it was still auto-selected after the ffmpeg branch was merged tho.

**Comment by antis81** [comment]
@zetok Probably this is a good case to test the `git bisect` tool. Never used it by myself though.

**Comment by zetok** [comment]
@antis81 https://github.com/tux3/qTox/wiki/Testing#regression-testing `:)`

**Comment by ghost** [comment]
Could it be a one time thing? Tested again, freshly downloaded binary (0c6c28bfbb71f7f3cd452283565eacac11f6f1a1), existing and newly created profile. In all cases my camera was automatically selected from the list.

**Comment by agilob** [comment]
As said before, I don't think this was anyhow related to qtox. If you could check if you had update from ffmpeg or linux-kernel or v4l2 that would help us ;)

Another scenario: camera device was locked when you turned qtox on, so it wasn't loaded on the list and preview couldn't be shown.

**Comment by zetok** [comment]
@agilob well, if @kehugter is using qTox binary from jenkins, then static ffmpeg 2.7.2 is used.

**Comment by ghost** [comment]
@agilob I only have this month's log to search in, I hope it's enough

**ffmpeg**
2015-08-03 upgrade ffmpeg:amd64 7:2.7.2+git~trusty 7:2.7.2+git1~trusty
2015-08-14 upgrade ffmpeg:amd64 7:2.7.2+git1~trusty 7:2.7.2+git2~trusty
2015-08-23 upgrade ffmpeg:amd64 7:2.7.2+git2~trusty 7:2.7.2+git3~trusty

**linux-kernel**
2015-08-21 upgrade linux-kernel-generic:all 3.13.0-37 3.16.0-38

**v4l2**
not in my system, at least under that name

**Comment by DanTheBritish** [comment]
@agilob 

> No such commit ;)

Sorry, was a merge commit on my branch. Still occurs on clean master aaf0774f356786a183c1ca48b9a1fc14586d9554

Also, output of `ffmpeg`:

```
priseth@urban-menace:~/tox/qTox$ ffmpeg
ffmpeg version N-72815-gde3a7ef Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.2 (Ubuntu 4.9.2-10ubuntu13)
  configuration: --prefix=/home/priseth/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/priseth/ffmpeg_build/include --extra-ldflags=-L/home/priseth/ffmpeg_build/lib --bindir=/home/priseth/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
Hyper fast Audio and Video encoder
```

**Comment by zetok** [comment]
@LapFox doesn't ubuntu 15.04 have ffmpeg in repos?

If so, is there a particular reason to use custom-build ffmpeg?

**Comment by antis81** [comment]
@zetok (L)ubuntu 15.04 has ffmpeg in repos - and more important 14.04 LTS has also.

**Comment by DanTheBritish** [comment]
Removed my compiled ffmpeg, installed pre-built from the repo.

```
priseth@urban-menace:~/tox/qTox$ ffmpeg
ffmpeg version 2.5.8-0ubuntu0.15.04.1 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.2 (Ubuntu 4.9.2-10ubuntu13)
  configuration: --prefix=/usr --extra-version=0ubuntu0.15.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --shlibdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --enable-shared --disable-stripping --enable-avresample --enable-avisynth --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libshine --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libwavpack --enable-libwebp --enable-libxvid --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzvbi --enable-libzmq --enable-frei0r --enable-libvpx --enable-libx264 --enable-libsoxr --enable-gnutls --enable-openal --enable-libopencv --enable-librtmp --enable-libx265
  libavutil      54. 15.100 / 54. 15.100
  libavcodec     56. 13.100 / 56. 13.100
  libavformat    56. 15.102 / 56. 15.102
  libavdevice    56.  3.100 / 56.  3.100
  libavfilter     5.  2.103 /  5.  2.103
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Hyper fast Audio and Video encoder
```

Recompiled qTox, but same result, webcam is not in qTox dropdown.

**Comment by DanTheBritish** [comment]
Still occurring on 1fc703c2815470235765e3cd48587a411046f743 with above version of ffmpeg and same kernel version as OP.

**Comment by tux3** [comment]
@LapFox Could you post the output of the following commands in a pastebin (on your current kernel, with the webcam powered on)?

```
lsusb
lsusb -s 1:6 -v # Replace 1:6 by the correct bus/devnum of the webcam if necessary
v4l2-ctl --list-devices
v4l2-ctl --list-formats-ext
ffmpeg -f v4l2 -list_formats all -i /dev/video0
```

Thanks.

**Comment by tristan-k** [comment]
I'm running the mac os x build from https://github.com/RowenStipe/qTox-OSX and I can confirm the issue. My camera is working fine in other applications.

```
 $ tail -f /Users/tristank/Library/Preferences/tox/qtox.log
 [14:52:30.055] ../qTox/src/video/cameradevice.cpp:236 : Warning: avdevice_list_devices failed
 [14:52:30.055] ../qTox/src/video/cameradevice.cpp:310 : Warning: Video mode listing not implemented for input  avfoundation
```

![ishot-1](https://cloud.githubusercontent.com/assets/732025/10710521/8752de82-7a5e-11e5-850f-c6f632c12b92.jpg)

**Comment by RowenStipe** [comment]
The camera function wasn't working when I put the package out I can confirm on my system.

**Comment by DanTheBritish** [comment]
Can no longer reproduce on latest commit (94a6df47ccdeb7dd331be1478dbbf0bf1087dab0) at the time of writing, closing as such.

@RowenStipe @tristan-k Try and confirm.
