### ISSUE TITLE
qTox documentation - Faux offline messages

### ISSUE THREAD

**Issue by Jeeppler** [qTox/qTox#2131]
Is there any qTox documentation which explains what Faux offline messages are and how it works?
Or can somebody explain that to me?

**Comment by ProMcTagonist** [comment]
Your friend receives them when they come online IF you are online at the same time.

**Comment by agilob** [comment]
I guess this can be closed?

**Comment by zetok** [comment]
> I guess this can be closed?

Not quite - there should be some documentation for qTox users provided (I'm not sure in what form exactly though, any ideas?)

**Comment by Jeeppler** [comment]
### Faux offline messages

Your friend receives them when they come online IF you are online at the same time. 

---

At least the main features should have an description. The user documentation should be in HTML (github pages). I would use a static site generator (Jekyll, Nanoc, Octopress etc.) to generate the the user documentation from markdown files. 
The user documentation could be similar to the gimp documentation: http://docs.gimp.org/2.8/en/gimp-tool-rotate.html. The gimp documentation provides information, some pictures and how to use it, but in a simple way!
