### ISSUE TITLE
List of features supported by toxcore, but not supported by qTox

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#2134]
- [x] **migration to [new A/V API](https://github.com/irungentoo/toxcore/pull/1375)**
- [ ] Switching between audio/video without restarting calls (#1930)
- [ ] resuming file transfers (also across client restarts) (#1532) https://github.com/irungentoo/Tox_Client_Guidelines/blob/master/Important/File_Transfers.md
- [ ] automatic bitrate management provided from A/V API

**Comment by agilob** [comment]
@zetok what about migration to the new A/V API?

**Comment by zetok** [comment]
yeah, added

**Comment by aaannndddyyy** [comment]
first and last are most important, imho.
Across restarts would be nice, but at leats durin one session is really needed.
I often have to switch to utox for filetransfers.

**Comment by ProMcTagonist** [comment]
New AV is merged in core

**Comment by ovalseven8** [comment]
Just for information:
What's still missing is (automatically) bitrate management provided from A/V API.

**Comment by ovalseven8** [comment]
Please uncheck bitrate management because it was removed from qTox due to buggy TovAV: https://github.com/tux3/qTox/commit/db52ef6e6a843faa8543b4726a5c281b8f1e1d97

**Comment by tux3** [comment]
I unchecked "automatic bitrate management provided from A/V API" in the OP.

**Comment by agilob** [comment]
I guess list of things dont make any sense, so closing this one, as points are covered by more specific issues.
