### ISSUE TITLE
Background colors / images of chat area

### ISSUE THREAD

**Issue by Redee** [qTox/qTox#2138]
Only white very bad for eyes.
Add background colors / images to chat area.

qTox for Windows latest version >>
![d21a5fbc-4e67-11e5-931b-f17b7fc635bd 1](https://cloud.githubusercontent.com/assets/2652667/9566113/949dc47a-4efe-11e5-905a-43be07ae288c.jpg)

**Comment by agilob** [comment]
duplicate of https://github.com/tux3/qTox/issues/1307
