### ISSUE TITLE
Segmentation fault after unplugging external monitor

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2144]
Steps:
- external monitor plugged
- start qTox. Login screen or already logged in, doesn't make a difference
- Maximised, minimised or closed to tray doesn't make a difference either
- unplug external monitor

Segmentation fault happens either instantly, after clicking the active window or after clicking the tray icon. I haven't discovered a clear pattern. When the active window survives (crashes only after clicking the tray icon), it doesn't work properly. The right column stays frozen, no matter what's clicked on the left one (contacts, add friend, settings, etc). The window title gets updated, though.

Sometimes, the following warning is displayed right before the segmentation fault
`:0 : Warning: nativeResourceForScreen: null screen`

No issues when the external monitor is plugged in while qTox is running. No other Qt 5 program I use crashes this way.
#518 may be related, but it also has issued plugging in a second monitor, and there are no mentions of segmentation fault right after unplugging.

---

qTox 0c6c28bfbb71f7f3cd452283565eacac11f6f1a1
Mint Cinnamon 17.2 x64
Cinnamon 2.6.13
Qt 5.2.1

---

Edit: md format

**Comment by sudden6** [comment]
Probably fixed in Qt 5.5 according to #3065 links.

**Comment by ghost** [comment]
Yes, I'm not able to reproduce in Qt `5.6.1` running qTox 2b0fbae44b2576df7abdec4566ce6d21b60d8685.
