### ISSUE TITLE
Ubuntu - Unity system tray issues

### ISSUE THREAD

**Issue by raver119** [qTox/qTox#2153]
1. Under Ubuntu all you have is quiet sound, and sidebar icon blinking for a second. If you've missed that - you've missed message. Some kind of long-living notification is more then welcome.
2. Minimize to tray/Close to tray/Start to tray - all these options are efficiently hiding qTox from user forever. Since qTox is incompatible with Unity system tray, such minimized app cant be restored.

So, basically, qTox lacks Ubuntu system tray support, and some improvements on tray icon statuses, since even under Windows, tray icon doesnt really explains that i have unread messages.

**Comment by zetok** [comment]
I've added builds with support for unity, could you test and if it works for you, could you close this issue?
https://wiki.tox.chat/binaries#other_linux

**Comment by raver119** [comment]
./qtox 
./qtox: error while loading shared libraries: libappindicator.so.1: cannot open shared object file: No such file or directory

So, i guess libappindicator should be added as dependency in .dep.

Besides that - works great!
Thank you very much!

**Comment by agilob** [comment]
`sudo apt-get install libappindicator1 indicator-application` and try again?

**Comment by raver119** [comment]
I've done that before wroting first answer, and as i've wrote - works great

**Comment by raver119** [comment]
I did that before posting comment, and as i've wrote - everything works great now.

**Comment by agilob** [comment]
ahh, sorry I misunderstood your comment!

**Comment by agilob** [comment]
Could you specify where those packages should be added in our instructions?

**Comment by raver119** [comment]
Since you have debian/ubuntu PPA repository, you could just include it as dependency, and APT will do the rest, if needed

**Comment by agilob** [comment]
>Since you have debian/ubuntu PPA repository, you could just include it as dependency

I don't think we do? @zetok?

**Comment by zetok** [comment]
> > Since you have debian/ubuntu PPA repository, you could just include it as dependency
> 
> I don't think we do? @zetok?

_We_ don't really.

There is a repo provided by Tox project, to which job configured on jenkins can push qTox debs.

And it wouldn't be as simple as just adding dependency - there would have to be added new package that would conflict with "standard" `qtox` package, and "standard" `qtox` package would need to have added conflict against new `qtox-unity` package.

Not that it would be tremendously hard for someone knowing what they're doing, but so far I didn't have the pleasure of packaging anything for distros (except for Gentoo, but that's not really as ~~reta~~ um, troublesome as packaging).

@stal888 kindly set up current qTox `.deb` packages, and I hope that he could also help with setting up `qtox-unity` packages.

If not.. I'm afraid that it's a bit low on my personal TODO list (given that I would have to spend time learning about packaging).

**Comment by zetok** [comment]
> If not.. I'm afraid that it's a bit low on my personal TODO list (given that I would have to spend time learning about packaging).

Actually, scratch that.

Are `libappindicator1 indicator-application` both required, or would `libappindicator1` alone as dependency be enough?

**Comment by raver119** [comment]
It should be enough, since libappindicator1 has own dependencies, and they are managed by apt

**Comment by zetok** [comment]
> It should be enough, since libappindicator1 has own dependencies, and they are managed by apt

Ok, then I will set up package `qtox-unity` without `indicator-application`, and I will need someone to test that.

**Comment by raver119** [comment]
I'm still here, i have few 64 bit ubuntu 14.04 LTS around me to play with.

**Comment by zetok** [comment]
https://build.tox.chat/view/packages/job/qTox-unity_pkg_linux_deb_x86-64_nightly_release/

↑ `.deb` is ready, not sure when it will propagate to repo though.

**Comment by raver119** [comment]
Installation fails:

Lintian check results for /tmp/qtox-unity-amd64-4-3b4f8c5.deb:
E: qtox-unity: control-file-has-bad-owner md5sums jenkins/jenkins != root/root
E: qtox-unity: wrong-file-owner-uid-or-gid usr/ 1002/1002
E: qtox-unity: wrong-file-owner-uid-or-gid usr/bin/ 1002/1002
E: qtox-unity: wrong-file-owner-uid-or-gid usr/bin/qtox 1002/1002

**Comment by zetok** [comment]
That's weird, I've just basically copied job https://build.tox.chat/view/packages/job/qTox_pkg_linux_deb_x86-64_nightly_release/ , added dependency, changed name, and added conflict against `qtox` package, none of which should have resulted in this…

Is the `.deb` from the job from where I've copied things working for you?

**Comment by raver119** [comment]
Nope, the same error:

Lintian check results for /tmp/qtox-amd64-68-3b4f8c5.deb:
E: qtox: control-file-has-bad-owner md5sums jenkins/jenkins != root/root
E: qtox: wrong-file-owner-uid-or-gid usr/ 1002/1002
E: qtox: wrong-file-owner-uid-or-gid usr/bin/ 1002/1002
E: qtox: wrong-file-owner-uid-or-gid usr/bin/qtox 1002/1002

**Comment by stal888** [comment]
see if build #2 works

**Comment by raver119** [comment]
Build number 2 works perfectly, libappidinicator1 and  nested dependency libindicator7 were installed automatically

**Comment by stal888** [comment]
We did it reddit :mushroom:

**Comment by raver119** [comment]
Just one detail is missing, from my another request - .desktop file for unity/gnome dashboard :)

**Comment by zetok** [comment]
> Just one detail is missing, from my another request - .desktop file for unity/gnome dashboard :)

#2154 is about it, thus closing this issue.

**Comment by FatCache** [comment]
Please view my comment here, https://github.com/tux3/qTox/issues/2154
