### ISSUE TITLE
Typing notifications should be on by default

### ISSUE THREAD

**Issue by subliun** [qTox/qTox#2155]
they really should

**Comment by agilob** [comment]
I think saving chat should be on by default, but we decided to go 'privacy first'.

**Comment by zetok** [comment]
> I think saving chat should be on by default, but we decided to go 'privacy first'.

Err, no.
Saving chats was off by default at first because it was still unstable. If that's still off, then it should be changed.

As for privacy, there's encryption for those who need it.

**Comment by subliun** [comment]
If saving chat is off by default that's crazy. Change that first, then fix the typing notifications.

**Comment by agilob** [comment]
merge PR.
