### ISSUE TITLE
Stress sign (diacritic mark) is stripped in pasted text

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#2158]
I tried to paste the word "коне́чно", but the mark gets stripped.

**Comment by agilob** [comment]
Can't reproduce?

![snapshot15](https://cloud.githubusercontent.com/assets/2544251/9590496/f1d6a2e0-502c-11e5-9ab2-9094e6428ba5.png)

**Comment by yurivict** [comment]
Sorry, must be a font issue. I just couldn't believe that there are still fonts around that don't show diacritics.

**Comment by zetok** [comment]
I could reproduce, reopening.
![that notification.](https://cloud.githubusercontent.com/assets/3148759/9605713/3d7deed0-50b7-11e5-8e6d-9e92186f528d.png)

And I did receive from @agilob something that in chatform was shown without diacritic, whereas in new message notification from PR #2082 was shown with it.

**Comment by ghost** [comment]
#2122 related?

**Comment by ghost** [comment]
^ probably not. If I paste "**коне́чно**" in qTox, It turns to "**конечно**", as described. Note that the stress sign is not stripped, just hidden: If you copy the string back from qTox, it's displayed as before.

On the other hand, "**´`áéíòù^âîô**" is correctly displayed in qTox (you just can't type it in).

**Comment by zetok** [comment]
With #3449 merged chatform font can changed – is it still reproducible after changing font?

**Comment by zetok** [comment]
Note: it's a default font issue – it's gone when I've switched to other font in settings.
![spectacle db1145](https://cloud.githubusercontent.com/assets/3148759/18608719/00c60d2e-7ce9-11e6-9599-d322a9238645.png)
First one is using font `Hack`, second one is default qTox font, `DejaVu Sans`.

**Comment by sudden6** [comment]
Sorry, this got somehow closed by the PR automatically.

The font https://raw.githubusercontent.com/dejavu-fonts/dejavu-fonts/master/status.txt definitely contains als the stuff needed to display this.

However when using the KDE font viewer for some font size the stress sign is very tiny, maybe it gets invisible somehow?

![grafik](https://cloud.githubusercontent.com/assets/5585762/23343217/29fd6058-fc68-11e6-9356-e08029669e46.png)

EDIT: I just tested changing the font size, it doesn't change anything :/

**Comment by sudden6** [comment]
This doesn't seem to be a problem in recent builds anymore.
