### ISSUE TITLE
ToxDNS must not be centralized

### ISSUE THREAD

**Issue by penny64** [qTox/qTox#2159]
This is the most popular client, you cannot make it only support whitelisted domains for lookups. That's insane, you've centralized what's supposed to be a federated part of Tox

**Comment by ovalseven8** [comment]
Think so too.
If qTox is using ToxDNS, every user should be able to (at least) add his own ToxDNS service easily.

When there is not the possibility to implement it in a easy to use and userfriendly way, ToxDNS is just broken.

**Comment by Jeeppler** [comment]
@witheld9 your issue title is misleading, because the Tox ID is not broken, but the Tox ID resolution is not federated. The issue should be about the ToxDNS not about the Tox ID itself. 
But else I agree with you!

**Comment by suhr** [comment]
Change the title to “ToxDNS must not be centralized”.

**Comment by Jeeppler** [comment]
@suhr much better :+1:

**Comment by zetok** [comment]
> This is the most popular client, you cannot make it only support whitelisted domains for lookups. That's insane, you've centralized what's supposed to be a federated part of Tox

Which ToxDNS service doesn't work for you with latest qTox?

**Comment by Jeeppler** [comment]
@zetok ToxDNS works fine. His (@witheld9) issue is about the centralized character of ToxDNS.

**Comment by ProMcTagonist** [comment]
Isn't someone working on pinning so it's safer to add any service you want from the control panel? Was that installgen2?

**Comment by penny64** [comment]
@zetok Any I run, for instance. And sr.ht despite being a list. But why is there a list, why does user@arbitrary.domain not work?

**Comment by suhr** [comment]
`P-medium` actually.

**Comment by zetok** [comment]
As it was planned, ToxDNS support was removed, and given that ToxMe support is not centralized, closing.

**Comment by penny64** [comment]
ToxDNS support was removed, ToxMe?
