### ISSUE TITLE
[Chat History] chat history is not encrypted

### ISSUE THREAD

**Issue by Jeeppler** [qTox/qTox#2160]
qTox saves the chat history in a SQLite database. The problem about that is, everybody who has access to the hard drive disk can access an manipulate the chat history between Alice and Bob easily. 
This is a big problem under all platforms.

**Comment by zetok** [comment]
If encryption is used, chat history is encrypted.

**Comment by Jeeppler** [comment]
@zetok how can I enable the encryption?

**Comment by agilob** [comment]
set password on your profile.
Profile -> Change password

**Comment by Jeeppler** [comment]
thanks :+1:

**Comment by Jeeppler** [comment]
How is the encryption implemented? Does qTox encrypt the whole sqlite database? And if yes, which extension do you use for that?

**Comment by agilob** [comment]
check coreencryption.cpp and encrypteddb.cpp for details. Author of that functionality is far afk.
