### ISSUE TITLE
qTox erases profile when no space left on a device (Wrong password error on profile that was not encrypted)

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#2161]
I upgraded a very old Windows installation of qTox yesterday with a new binary from wiki.tox.chat. It worked great for a while, but now upon logging in it throws up a Wrong Password dialog. 
The profile never had any password. There's also not even a box to enter the password in the login window.

Desired behavior: qTox does not spontaneously encrypt profiles with unknown passwords

Observed behavior: qTox spontaneously encrypts profiles with unknown passwords

**Comment by zetok** [comment]
I've tried to reproduce with profiles from 2015-02-03 and 2014-12-22 with qTox aaf0774f356786a183c1ca48b9a1fc14586d9554, in both cases I didn't encounter this problem.

The way in which I've tried to reproduce:
1. Copy old `profile.tox`, `profile.qtox_history`, `profile.ini` and `qtox.ini` to `~/.config/tox/`
2. Launch qTox with `qtox -p profile`
3. Wait until it bootstraps, wait for groupbot to come online and send message `ping` to it to make sure that something will be saved in history.
4. R-click on icon in tray and `Quit` qTox.
5. Launch qTox again with same command.     ← this probably "shouldn't" work

Though I'm using Gentoo, whereas issue seems to be affecting windows, perhaps that matters.

Could you specify more exact steps, and how old that profile was?

**Comment by zetok** [comment]
Anything?

There was no response for over a month, but I don't want to close this, given how severe repercussions of that happening again are.

Were you able to reproduce it?
Or anyone else for that matter?

**Comment by ProMcTagonist** [comment]
Sorry for not responding earlier. It happened again a couple times, each time after making a new profile and using that for a bit (the user only had two contacts, luckily).

I'm now pretty sure it's the result of corruption due to there being not enough space left on C:\ because
1) there's not enough space on C:\, and 
2) two new profiles appeared, with the same name.tox but with extra characters at the end, like this:

```
normalprofile.tox
normalprofile.tox.De3524
normalprofile.tox.Ql2928
```

And the actual profile was suddenly zero kilobytes.

These changes always take between quitting qTox and opening it again.

Everything is working fine now with qTox in portable mode on D:.

**Comment by zetok** [comment]
> And the actual profile was suddenly zero kilobytes.

Uh, that would mean that data is not being encrypted, but rather erased, and qTox (toxcore?) interprets it as encrypted profile…

steps to reproduce error about wrong password when profile was erased:
1. erase contents of qTox profile

``` bash
> ~/.config/tox/$profile_to_erase.tox
```

\2. try to load $profile_to_erase → qTox shows error message `Wrong password.`

# 

Since it is qTox itself that erases profile, bumping priority to highest.
