### ISSUE TITLE
[Feature] See your self during video call

### ISSUE THREAD

**Issue by Jeeppler** [qTox/qTox#2162]
During a Skype chat you can see yourself and the other person during the talk. 
This is an important feature, because you always feel weird if you don't know how you are seen by the other person. 

The second view should be smaller and should be visible in the same window. This feature should be optional, but it is indeed a important feature for many people.

**Comment by agilob** [comment]
already implemented in https://github.com/tux3/qTox/pull/2093.

**Comment by Jeeppler** [comment]
nice :+1:
