### ISSUE TITLE
old tox1 protocol to access DNS record?

### ISSUE THREAD

**Issue by Jeeppler** [qTox/qTox#2163]
I got this message:

```
It appears that qTox has to use the old tox1 protocol to access DNS record of your friend's Tox ID.
Unfortunately tox1 is not secure, and you are at risk of someone hijacking what is sent between you and ToxDNS service.
Should tox1 be used anyway?
If unsure, press “No”, so that request to ToxDNS service will not be made using unsecure protocol.
```

The Tox ID was generated by uTox.

Why exactly is the Tox ID bound on specific DNS protocols?

**Comment by zetok** [comment]
It's not, and what you have there is not a Tox ID - if it was, no DNS would be involved.

**Comment by Jeeppler** [comment]
@zetok intersting, than it is just a wrong error message and an unexpected behaviour of qTox.

**Comment by zetok** [comment]
#2167 should help with an unexpected behaviour.
