### ISSUE TITLE
qTox should check if string in "Add friend" input field is 64 chars long

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#2167]
If it is, qTox needs to check whether it seems to be a public key (A-Z0-9), and if so, inform the user that this is not a Tox ID, since it's not 76 chars long.

**Comment by PKEv** [comment]
I thought that such an address must also be supported ???
tox:user@doman.com

**Comment by zetok** [comment]
Yes - this is though about input that doesn't have `@` in it, and is a pubkey - people often try to use pubkey to add friend, which doesn't work.

**Comment by PKEv** [comment]
What do you mean by input validation?
filtering of input characters?

**Comment by zetok** [comment]
> qTox should check if string in "Add friend" input field is 64 chars long. If it is, qTox needs to check whether it seems to be a public key (A-Z0-9), and if so, inform the user that this is not a Tox ID, since it's not 76 chars long.

**Comment by zetok** [comment]
@PKEv thing is, users often try to add friend by PK (64 chars) - since qTox only adds valid IDs (76 chars) or toxdns entries - when user inputs 64 character long string, they think that they are supplying an ID, and when qTox parses input, user gets some cryptic message about toxdns not working.

This isn't good - user should be informed that what they supplied isn't a Tox ID.

For that, input must be checked for PK resemblance, and if it seems to be one (64 char long, A-F0-9 characters) user should get a proper warning.

**Comment by BiTOk** [comment]
I'll do this.
