### ISSUE TITLE
minimize to tray is irrevertible

### ISSUE THREAD

**Issue by aaannndddyyy** [qTox/qTox#2169]
I have enabled the minimize to tray option.
Then I minimize qtox window.
I still have the tray icon. 
I cannot gt the window back.
All I can do is close qtox altogether or change the online state.

**Comment by agilob** [comment]
Operating system, desktop env, version, version of Qt please.

**Comment by zetok** [comment]
@aaannndddyyy if you could, please read https://github.com/tux3/qTox/wiki/Writing-Useful-Bug-Reports

**Comment by aaannndddyyy** [comment]
@agilob: Trisquel Gnu/Linux, LXDE, qt version no idea

**Comment by zetok** [comment]
Can you open qTox by trying to run it again without turning it off?

**Comment by aaannndddyyy** [comment]
@zetok: expected behaviour: Double clicking the tray icon brings back thwe window, or alternatively right click on tray icon gives a "restore" option

**Comment by aaannndddyyy** [comment]
@zetok: yes, that i do as a workaround. I close qtox. then I go to my menuy, choose internet, there qtox, and then I have it open again

**Comment by zetok** [comment]
@aaannndddyyy that's qTox from repo?
Could you try binary with Qt 5.4.2 instead https://wiki.tox.chat/binaries#other_linux ?

**Comment by aaannndddyyy** [comment]
with the binary you linked to it works as expected

**Comment by zetok** [comment]
I see, I'll make default qTox `.deb` use Qt 5.4.2

**Comment by zetok** [comment]
Ok, 
https://build.tox.chat/view/packages/job/qTox_pkg_linux_deb_x86-64_nightly_release/39/
and 
https://build.tox.chat/view/packages/job/qTox_pkg_linux_deb_x86_nightly_release/31/
should be fixed, can you see whether it works for you?

**Comment by aaannndddyyy** [comment]
thx for fixing
