### ISSUE TITLE
Panda free antivirus detects qTox as suspect software

### ISSUE THREAD

**Issue by Deleetdk** [qTox/qTox#2170]
I am running Windows 8.1, 64bit.
Panda Free Antivirus 16.0.1.
qTox build https://github.com/tux3/qTox/commit/05fece4fab8bf829ac713da02f882fe2f5e699e5

Presumably a false positive, but worth looking into in case there was a recent pull from a 3rd party. Not necessarily caused by something qTox is doing wrong. However, it may be that if Panda detects it, some of the other antivirus programs will too.

**Comment by zetok** [comment]
Could it be added to https://wiki.tox.chat/users/problematic_antivirus_software ?

**Comment by tux3** [comment]
I swear I'm going to write a packer just to keep the cheap AVs at bay.

**Comment by zetok** [comment]
@Deleetdk or could you at least provide info as what kind of "threat" qTox was identified, so that I could add it to the wiki?

**Comment by Deleetdk** [comment]
@zetok I wanted to, but since I added the program file to the exclusion list, it removed the detection from the history, so I can no longer see what it said specifically. It did not mention a particular virus, just "suspicious program" or something of that sort.

**Comment by sudden6** [comment]
probably because off the p2p software part in toxcore...

**Comment by zetok** [comment]
I see.
I've added to wiki what I could - if someone has more info, please add it to the wiki.

@Deleetdk could you contact panda about it, so that they could fix their software?

**Comment by Deleetdk** [comment]
@zetok 

Done. http://support.pandasecurity.com/forum/viewtopic.php?f=83&t=4898&sid=561924a952fef361e49362fa9b6e0b99

**Comment by zetok** [comment]
Ok, thanks.
Since not much can be done about it, closing the issue.
