### ISSUE TITLE
Drag and Drop File doesn't work on Unity

### ISSUE THREAD

**Issue by FatCache** [qTox/qTox#2174]
/title

On Ubuntu 15.04 64bit. Tried on both binaries, nightly and qtox-unity-tray.

Dragging only brings the file address location. Tried on XFCE DE and it works fine on it. Unity specific issue.

**Comment by zetok** [comment]
Where were you dropping file?
Edit: as in, in which place exactly in qTox window

**Comment by FatCache** [comment]
Into the text area.

**Comment by ProMcTagonist** [comment]
That's desired behavior.

**Comment by zetok** [comment]
As @ProMcTagonist wrote, dropping file into text area is supposed to paste "link" to it there.
If you want to send file, drop it into chatform.
Closing, since currently it's an expected behaviour.
You may be interested in commenting on #1947.
