### ISSUE TITLE
Can't create new user with qTox on ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by rpasta42** [qTox/qTox#2175]
When trying to sign up new user with qTox, I get the following error in terminal:

[14:03:52.273] src/persistence/profile.cpp:147 : Warning: Failed to lock profile  "mahUsername"

I also get a GUI popup: Couldn't create a new profile, Unknown error: Couldn't create a new profile. If you encounter this error, please report it.

[14:03:29.982] src/main.cpp:141 : Debug: built on:  09:18:34 Sep  4 2015 ( 1441372543 )
[14:03:29.982] src/main.cpp:142 : Debug: commit:  7796421f73b8be293817fa126e55be5af94e4048

**Comment by rpasta42** [comment]
I dag around source code, and it seems like qTox tried to create QLockFile which already existed. I had to delete ~/.config/tox and it runs again!

I probably didn't exit cleanly because I usually use ctrl+c to exit applications.

**Comment by sudden6** [comment]
I don't think ctrl+c is the way to close gui applications cleanly. Please comment if it's still an issue.

**Comment by anthonybilinski** [comment]
Since posix signal handling was added in 32b97cb9, I've used ctrl+c to close qTox probably thousands of times and haven't seen this. @zetok was the re-open just for handling ctrl+c? Safe to close now?

**Comment by sudden6** [comment]
@anthonybilinski I think it's safe to close, if it's still a problem there's probably a different root cause.
