### ISSUE TITLE
Avatars too small

### ISSUE THREAD

**Issue by aaannndddyyy** [qTox/qTox#2187]
Both in the contact list and in the actual chat, avatars should (optionally) be noticeably bigger than now.
In fact, I'd like their size in the contact list to be the size they currently have in the chat, and the chat avatar be bigger as those in the contact list in the same relation it is now.

**Comment by Getron** [comment]
+1

Or maybe, to let the user to decide how big would be the avatars. Maybe, a scrolling line on bottom , or on top, to decide the size of avatars. The same for own avatar should be to.

**Comment by agilob** [comment]
Personally I think the avatars are too big right now.

**Comment by Getron** [comment]
@agilob I don't known, if on my Fedora it is a bug, or not, but, look at this what for avatars i see on my qTox, they are extremly, not recognisable avatars, right now.

![auswahl_064](https://cloud.githubusercontent.com/assets/5913218/10180659/6dff155c-670f-11e5-8245-9bd107e2073b.png)

And this is the version from yesterday, nightly build of qTox

And, if you, like me, have an 32'' Monitor, and resolution of 2560x1600, ohh...

And, in addition, maybe my proposal #2191 would help here

**Comment by SkyzohKey** [comment]
[**@Getron**](https://github.com/Getron) commented on [30 Sep 2015, 01:06 GMT+2](https://github.com/tux3/qTox/issues/2187#issuecomment-144216549):

> [@agilob](https://github.com/agilob) I don't known, if on my Fedora it is a bug, or not, but, look at this what for avatars i see on my qTox, they are extremly, not recognisable avatars, right now.
> 
> [![auswahl_064](https://cloud.githubusercontent.com/assets/5913218/10180659/6dff155c-670f-11e5-8245-9bd107e2073b.png)](https://cloud.githubusercontent.com/assets/5913218/10180659/6dff155c-670f-11e5-8245-9bd107e2073b.png)
> 
> And this is the version from yesterday, nightly build of qTox
> 
> And, if you, like me, have an 32'' Monitor, and resolution of 2560x1600, ohh...

You just enabled the Compact mode in settings, disable it and you'll have normal contacts item (so normal avatar sizes).

**Comment by ProMcTagonist** [comment]
Compact mode is on by default now.

**Comment by SkyzohKey** [comment]
o.o Looks stupid but...

**Comment by agilob** [comment]
Uncheck 'Compact contact list'

**Comment by TheNain38** [comment]
Maybe it shouldn't be checked by default?

**Comment by agilob** [comment]
I agreed with @zetok  to set it by default on, we decided it looks better. When I show qTox to new people they usually ask me how to make contacts smaller. We still don't know if it's the issue.

> Both in the contact list and in the actual chat, avatars should (optionally) be noticeably bigger than now.

This one is about compact list.

> In fact, I'd like their size in the contact list to be the size they currently have in the chat

This is a feature request, because making the avatars that big would be huge waste of space.

> and the chat avatar be bigger as those in the contact list in the same relation it is now.

Make it even bigger? It's already huge and size of the avatar is breaking layout of chat header.

**Comment by sudden6** [comment]
Closing as it seems this was only Compact contact list enabled.
