### ISSUE TITLE
allow to copy link by right click

### ISSUE THREAD

**Issue by aaannndddyyy** [qTox/qTox#2188]
Sometime I don't want to leftclick a link and have the defult browser opne it straight away. 
Almost every chat application and brwoser recognizes links and allow to copy the link by clicking "copy link" in context menu of right click. Would be nice to have it.
thx

**Comment by zetok** [comment]
Duplicate of #1236, thus closing.

**Comment by aaannndddyyy** [comment]
Hadn't seen it. Sorry n thx.
