### ISSUE TITLE
dateformat dddd, d. MMMM yyyy missing

### ISSUE THREAD

**Issue by aaannndddyyy** [qTox/qTox#2189]
there are several options for the date format.
but the complete one is only available in American order (mothn before day) and be translateable, such that it also allows for: Samstag, 5. September 2015

(low priority)

**Comment by ghost** [comment]
In fact, could we have a configurable date format? À la [strftime](http://man7.org/linux/man-pages/man3/strftime.3.html)?

**Comment by ProMcTagonist** [comment]
@kehugter 
+1 if it's exposed after the user chooses Custom from the existing dropdown.

**Comment by antis81** [comment]
Hm … I'll setup a PR (my first :)) for this one with the correct formats.

Btw. I am actually able to select the format as you can see in the following screenshot:
![qtox-date-time-format](https://cloud.githubusercontent.com/assets/440517/9830951/5b00428e-5943-11e5-94a6-40bd9007de24.png)

qTox adds the formats provided by the system's locale (independent of qTox's country/language settings). The default formats are hardcoded and thus we see wrong date formats like e.g. `dd-MM-yyyy (12-09-2015)`. I'm going to change that … :smile:

**Comment by antis81** [comment]
@tux3 @zetok :warning: :exclamation: **IMORTANT NOTE**: Damn, I pushed directly to `master` by mistake, while I actually wanted to open PR for review. As it is latest commit currently, I force-pushed `master` to remove it from history. Really sorry for that. Should not happen again!

The single abandoned commit is 15c4f73.

**Comment by aaannndddyyy** [comment]
oh, ok. I didn't know it gets them from default locale. I'm using different machines with totally different locales, and when i looked at it and made this issue, I was in fact not on a de locale. So, if it is there when you are on that locale, then I'm happy and this can be closed. However, if you do have PR's that further improve the behaviour, fine. :)

**Comment by antis81** [comment]
Setting the date format string should actually be optional. By default, qTox should use the (short?) format as provided by the system locale (see `Qt::DateFormat`).

Instead of using a format string for the conversion, the enum should be used to get the right format for the current system. Transfer of timestamps should always happen in `ISO 8601` format or an equivalent international standard.

**Comment by agilob** [comment]
Could you do the same for timestamps to make it look more consistent?
