### ISSUE TITLE
qTox and Antox on same LAN status connection problems

### ISSUE THREAD

**Issue by Getron** [qTox/qTox#2195]
I have the newest qTox on my Fedora 22 KDE, and the same profile exported to my Android Note 3 on the newest Antox. Both are fresh installed, from 09.09.2015.

The problem is, on my qTox, my status is going crazy, if i connect with the same profile on the same LAN on my Antox.
It connect, and disconnect on every 2-5 seconds on my Desktop instantly (it goes online, and after couple seconds, offline, then couple second online, then offline, and so on...).

If i logout on Antox, it is stable again.

I think, this is a conflict, or bug somwhere, if the same profile on both devices.

**Comment by agilob** [comment]
> the same profile exported to my Android Note 3 on the newest Antox.

You can't use the same profile on two devices, it's how tox protocol works. That behaviour is expected.

**Comment by zetok** [comment]
@Getron that's a toxcore thing - support for multiple devices is not yet done, and when it will be, it won't require you to manually export/import profiles `:)`

**Comment by Getron** [comment]
Aha, ok, i understand now. But, this is expectation of every user out there, which will use the Tox, like any other messenger, Skype, Viber, ICQ, Yahoo, Google Hangouts, ... Every of this has this option, to use the same profile on all devices. This is a need.

Why then i have the profile import, export there, if i can't use the same profile on devices (or, use it on same time)?

Hope you guys do a great work, and implement this on the core as soon as possible. This would be an option more to compete the big messengers out there.

Thanks for explications. Great work.

**Comment by zetok** [comment]
> Why then i have the profile import, export there, if i can't use the same profile on devices (or, use it on same time)?

You can't use same profile on multiple devices simultaneously.

**Comment by Getron** [comment]
Any work on this until now?

Do we can expect now the multiple device on tox core?

**Comment by agilob** [comment]
@Getron feel free to go to any still open or already closed issue on toxcore to suggest it. This issue belongs to toxcore not qtox.
https://github.com/irungentoo/toxcore/issues/843
https://github.com/irungentoo/toxcore/issues/1100
https://github.com/irungentoo/toxcore/issues/1016
https://github.com/irungentoo/toxcore/issues/1393

**Comment by ProMcTagonist** [comment]
@Getron Multi-device is "sort-of" working in a developer preview branch right now, and will be coming to qTox soon.
