### ISSUE TITLE
Option to change outgoing voice in qTox

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2197]
Hello,

would like to suggest something for the future:
Because the purpose of Tox is to provide security and privacy, it could be a nice feature, especially for people like whistleblowers:

The option in the qTox settings to change the outgoing voice in audio/video calls. Of course, it is possible already with some other programs, but it's absolutely not user-friendly and hard to realize.

So, a simple menu in the settings, like the following would be enough:
[x] Normal voice
[-] High voice
[-] Deep voice

What do you think?
Some voice changes are pretty clear: https://www.youtube.com/watch?v=13t69RVq1YY

**Comment by agilob** [comment]
https://github.com/jart/asterisk-voicechanger - GPLv2, last update 3 years ago, we could just copy the source code.

**Comment by zetok** [comment]
There was (is?) a way of modifying audio using `filter_audio` - @zamaudio would know more.

@zamaudio care to comment on that?

**Comment by zamaudio** [comment]
I wrote some filters that were merged into <code>filter_audio</code> to make the voice more clear.  I also have an experimental branch that has alien/girl/boy voice mods.   It basically alters the pitch of the voice by different amounts.  I haven't made them selectable, only hardcoded, but it makes more sense to include them in filter_audio and provide routines to select them in the lib, no?  Thing is, filter_audio is permissively licenced not GPL.

**Comment by zetok** [comment]
> I haven't made them selectable, only hardcoded, but it makes more sense to include them in filter_audio and provide routines to select them in the lib, no?

It would be awesome if that was available.

**Comment by zamaudio** [comment]
It kindof is already available if someone wants to take it here:
https://github.com/zamaudio/filter_audio/blob/funvoice/filter_audio.c#L67

**Comment by ghost** [comment]
> for people like whistleblowers

In such a delicate case, I'd suggest that the audio filter needs some verified research data backing up its anonymization strength. Otherwise, it should be properly labelled as a neat feature that doesn't offer real security.

**Comment by ovalseven8** [comment]
> In such a delicate case, I'd suggest that the audio filter needs some verified research data backing up its anonymization strength. Otherwise, it should be properly labelled as a neat feature that doesn't offer real security.

You're right.

**Comment by ProMcTagonist** [comment]
Addon material.

**Comment by aaannndddyyy** [comment]
simply altering the pitch a fixed amount does not provide any protection, it is just a fun setting.
That applies to anything that uses an injective mapping.

You'd want something indeterministic at the very least.
Or alternatively a combined voice to text && text to speech approach.  That one is safe as far as voice is concerned.
Profiling based on choice of words and sentence patterns are definitely beyond the scope for qTox.

**Comment by ProMcTagonist** [comment]
Off-topic, but RE:profiling via style, see: https://github.com/psal/anonymouth/blob/master/README.md

**Comment by agilob** [comment]
> simply altering the pitch a fixed amount does not provide any protection, it is just a fun setting.

This is very strong argument, I think the issue can be closed unless someone has better idea how to improve it.

**Comment by ghost** [comment]
> better idea how to improve it

Sounds like something for a couple of PhD theses.

**Comment by aaannndddyyy** [comment]
It all depends what you want this option for. If you want this option to anonymize your voice reliably, then close this issue and make a new one about researching the matter.
But if the intention is simply to have some fun settings for changing your vouce and entertaining your friends, then this is perfectly legit too. Just make ir clear it is no reliable obfuscation.

agilob notifications@github.com hat geschrieben:

simply altering the pitch a fixed amount does not provide any protection, it is just a fun setting.

This is very strong argument, I think the issue can be closed unless someone has better idea how to improve it.

**Comment by zetok** [comment]
> But if the intention is simply to have some fun settings for changing your vouce and entertaining your friends, then this is perfectly legit too. Just make ir clear it is no reliable obfuscation. 

Yeah, this is what this issue is about.

**Comment by agilob** [comment]
"Fun settings" should be done as plugins. I think this can be closed as original idea was to:

> provide security and privacy, it could be a nice feature, especially for people like whistleblowers:

**Comment by zetok** [comment]
@agilob there's no reason to close it just because qTox doesn't have resources to do it - even if "security" is not achievable, qTox could be still improved, by providing something that people would want to use.

As for getting security - who knows, perhaps in the future there will be resources to pull off something like that.

> "Fun settings" should be done as plugins.

As soon as there will actually be a plugin interface. Also, why something that makes it "fun" to use qTox should not be included by default?

Thus, reopening.

Edit: what you probably would want to do, is to remove `P-low`

**Comment by zamaudio** [comment]
Guess what, they open sourced Steven Hawkins' voice thing, maybe we could use that?

**Comment by agilob** [comment]
Shouldn't it be a audio_filter (that one from toxcore) feature?

**Comment by ProMcTagonist** [comment]
This should not be included with qTox. 
1) It's definitely well into the scope of addons/plugins/extensions
2) It's irresponsible to include with qTox by default because people WILL think it'll give them extra security, and we KNOW that. We should be making it harder to expose yourself, not easier.

**Comment by LuccoJ** [comment]
I think if anything, qTox should include the option to pass the audio through some standard filter and plugin system (like LADSPA / LV2, which despite the name, aren't limited to just Linux). There are plenty of such filters designed to change pitch and voices, and they can do it a lot better than a rushed implementation inside of qTox itself could.

**Comment by SkyzohKey** [comment]
https://github.com/RicinApp/Ricin/issues/31

**Comment by ProMcTagonist** [comment]
@LuccoJ isn't that OS-level on the sender's side?

**Comment by sudden6** [comment]
This is out of scope for qTox.
