### ISSUE TITLE
"forgetting" online state

### ISSUE THREAD

**Issue by aaannndddyyy** [qTox/qTox#2199]
Sometimes qtox "forgets" the correct online state of a peer after a long time. 
Say, Bob has set his status to "away", I see that here as a yellow half-filled circle. 
After some hours (with BOB not touching his qtox because he is away), Bob's status changes to online and stays that way.
Once I reconnect, I get the correct status from him again.

**Comment by ElLamparto** [comment]
Confirmed. I have the same problem.

**Comment by zetok** [comment]
Update: still happens on v1.7.0, toxcore 0.1.2

**Comment by anthonybilinski** [comment]
I'm pretty sure this isn't still happening, but have no idea when it was fixed in the few years. Is anyone still seeing this issue?
