### ISSUE TITLE
Bad font rendering under GNOME

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#220]
Try tweaking AA and hinting.

**Comment by tux3** [comment]
Can't repro on Gnome3. Is this still an issue ? 
Can I get a screenshot, please ?

**Comment by agilob** [comment]
What? You wrote that issue.

**Comment by tux3** [comment]
Someone else reported it, on IRC iirc.
I made the issue with the intent to reproduce and fix it later, but I still can't reproduce.

**Comment by zetok** [comment]
If no one confirmed it, then it probably should be closed?

**Comment by jurf** [comment]
Gnome 3.14 here, and the fonts look a bit fuzzier, like the Gnome fonts were before I changed grayscale font smoothing to RGB and font hinting from none to slight. You should view the screen at 1:1 to see the difference.

![tox-fonts](https://cloud.githubusercontent.com/assets/7472425/6091423/5189c9d4-aeab-11e4-90e9-7adc6e507056.png)

**Comment by zetok** [comment]
I think that it's how generally font is shown?
![font](https://cloud.githubusercontent.com/assets/3148759/6091551/a64147ce-aea9-11e4-95c6-e57f8270c401.png)

That being said, doesn't font looks simply ugly compared to font used in nautilus?

**Comment by jurf** [comment]
I don't know, your qTox looks much nicer...

**Comment by tux3** [comment]
Okay, that's more of a Qt/GNOME integration issue, the best we can do is run with sane defaults and rely on Qt to do the right thing.
On some systems it comes out fine, on some not quite perfect, but it's not something we can fix from the qTox code either way.
