### ISSUE TITLE
download dialog broken

### ISSUE THREAD

**Issue by plus13** [qTox/qTox#2205]
System: Arch-Linux with Awesome-Windowmanager

When someone sends me a file and I klick on the check mark to download, a new window appers. This window is just black with a blue bar above saying "QT". That's it.

**Comment by zetok** [comment]
From #2215, thanks to @Zer0-One:

# 

@GrayHatter sent me a screenshot from uTox, and upon clicking the Accept button I ended up with this:

![2015-09-12-222549_1366x768_scrot](https://cloud.githubusercontent.com/assets/1117820/9834950/d8283828-5986-11e5-9db8-7652a3d9a0f4.png)

It's the file-save dialog, but it's minimum size, blacked-out, and I can't click anything; the UI appears to become totally non-responsive until I exit the window with the Esc key.

I'm on Gentoo with a 4.1.6-hardened kernel. The log doesn't mention anything obvious except for a few chunks matching the following:

[22:50:10.236] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[22:50:10.236] :0 : Warning: libpng warning: iCCP: cHRM chunk does not match sRGB
[22:50:10.330] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[22:50:10.330] :0 : Warning: libpng warning: iCCP: cHRM chunk does not match sRGB

**Comment by zetok** [comment]
Looks like issue affects only awesome users?

Or is someone else also able to reproduce?
(can't reproduce on i3)

**Comment by zetok** [comment]
Regression possibly introduced by #2150 - could you build qTox 54c837a03e933fb164fb94647d36bb53fb58eb3a and see if it will work?

**Comment by Zer0-One** [comment]
I'm on dwm, not awesome

**Comment by antis81** [comment]
Reproducible here as well…

**Comment by antis81** [comment]
@agilob @zetok Found the reason - yay! Like expected, the problem is the faulty parented `QFileDialog` (the parent points to the FileTransferWidget, which is embedded into a QGraphicsProxyWidget). The correct parent is the applications main window!

In the meantime to fix the issue, we can set the parent to `parentWidget()` - if no parent is set, this equals 0. In code:

``` c++
            QString path = QFileDialog::getSaveFileName(parentWidget(),
                                                        tr("Save a file", "Title of the file saving dialog"),
                                                        Settings::getInstance().getGlobalAutoAcceptDir() + "/" + fileInfo.fileName);
```
