### ISSUE TITLE
qTox can't load profile named ` ` (space)

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#2207]
Description: `$ qtox -p` doesn't load profile named `` `` (space).

OS: Hardened Gentoo Linux x86_64
qTox: 99b5b092d964b634ce39cc4f452711602b38d467

Reproducible: Always

Steps to reproduce:
1. Create profile with name `` `
2. Close qTox
3. Try to open qTox profile with`qtox -p  ``

Observed Behavior:
Profile is not being opened.

Expected Behavior:
qTox should open a profile, or sanitize profile names.

Additional info:

```
$ qtox -p  
[18:09:33.897] src/persistence/settings.cpp:119 : Debug: "Loading settings from /home/zetok/.config/tox/qtox.ini"
[18:09:33.901] src/persistence/settings.cpp:240 : Debug: Using embeded bootstrap nodes list
Missing value after '-p'.
```

**Comment by suhr** [comment]
Try `qtox -p ' '`.

**Comment by zetok** [comment]
Oh well, that works.
