### ISSUE TITLE
Can't connect to DHT on Mac OSX

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#221]

**Comment by tux3** [comment]
Can't reproduce / Works On My Machine™ / Not enough information

https://i.imgur.com/MINKYlY.png

**Comment by tux3** [comment]
Reopening since more people are affected.

**Comment by tux3** [comment]
Log : http://pastebin.com/LsqBUBPF

**Comment by tux3** [comment]
Fails even with IPv6 on.

**Comment by mouseym** [comment]
I have managed to bootstrap off a node (eventually) on OSX 10.9, no idea what version of qTox (its one made after these changes were made).

**Comment by tux3** [comment]
Ok. qTox was trying to bootstrap way too many nodes at once, now it's a bit more gentle.
