### ISSUE TITLE
Detached windows should have qTox icon in taskbar

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#2210]
Description:
Detached windows don't have qTox icon shown in taskbar.

OS: Lubuntu (15.04?)

Reproducible: Always

Additional info:
![fubqfsl](https://cloud.githubusercontent.com/assets/3148759/9833387/9cf11756-598c-11e5-94a9-2e4cb648c37c.png)

First reported by @ovalseven8 in https://github.com/tux3/qTox/pull/1938#issuecomment-134951140

**Comment by ovalseven8** [comment]
Thanks for the creation of the issue, @zetok 

What I want to add:
I got a new message in the above screenshot in the minimized window WITHOUT the qTox icon. The wanted behaviour would be that only the window is blinking for what I got the message. So, the 'not having blue...'-window should blink with a Tox icon in the screenshot. :)

**Comment by PKEv** [comment]
closed?

**Comment by ovalseven8** [comment]
> closed?

No, if you use 'Multiple windows mode' the problem is still there.

**Comment by PKEv** [comment]
in Win:
![default](https://cloud.githubusercontent.com/assets/6053197/10465478/c14572b8-71f7-11e5-82e7-734ecefdfa1e.png)

**Comment by ovalseven8** [comment]
Oh, I see. But the icon looks a little bit pixelated, anyway. ;-)
Then it's only a problem for Linux and perhaps MacOS.

**Comment by antis81** [comment]
There's no such thing with multiple icons on OS X (see the one and only Dock)… :)

**Comment by ghost** [comment]
No icon in Cinnamon either

![screenshot from 2015-11-12 11-45-44](https://cloud.githubusercontent.com/assets/6382342/11116487/38b2db9a-8933-11e5-8878-c5cf709342eb.png)

> But the icon looks a little bit pixelated, anyway. ;-)

Probably the same icon that's being used for `alt`+`tab` in Cinnamon? (#1927 may be related too)

![screenshot from 2015-11-12 11-41-03](https://cloud.githubusercontent.com/assets/6382342/11116533/868d7a96-8933-11e5-9b90-5a5a8a93b5e5.png)

**Comment by kehugter** [comment]
#1927 probably related too.

**Comment by agilob** [comment]
@kehugter all your issues should be solved now.

**Comment by ghost** [comment]
> all

No, the pixelated icons are still there (including the new status ones on `Alt` + `tab`). But that's not part of this issue, and I'm quite sure there was an open one about that already.
