### ISSUE TITLE
Incoming message sound volume is too low

### ISSUE THREAD

**Issue by raver119** [qTox/qTox#2216]
Incoming message sound volume is too low,  and there's no real way to increase it.

It would be nice, if there will be some option to increase volume.

Especially on linux.

**Comment by antis81** [comment]
@raver119 Is this still valid? Because volume control improved in qTox and to me it is loud enough.

@zetok Is the recording of the sounds normalized?

**Comment by zetok** [comment]
> @zetok Is the recording of the sounds normalized?

Probably not.

> Because volume control improved in qTox and to me it is loud enough.

Notification sound seems to be now louder, but it's still not loud enough in some cases. The use case is hearing notification sound even when e.g. music is playing – with quieter tracks I can hear notification sound quite well, but there are tracks during which I don't hear notification sound at all.

E.g. with https://www.youtube.com/watch?v=kIF-Qectwfs I can't hear notification sound.

With that in mind, there's a problem with bug #2631 that renders sound notification ~useless, given that qTox starts with `None` audio output selected.

**Comment by antis81** [comment]
> … renders sound notification ~useless, given that qTox starts with None audio output selected.

Which leads us directly to #2459 … ^^

IOW: Selecting the "none" audio device disables audio output for both notification sounds and calls - and this messes everything up. We need to strictly separate en-/disable audio output and the available devices. Btw. OpenAL automatically falls back to the system's default device, when opening a _null_ device. You probably want to have a look at my latest PR #3175, where I changed the combo box `currentIndexChanged` handlers to index-based. I.e. `items[1] == default device`.

**Comment by zetok** [comment]
From #5076 by @hchr:

> ##### Brief Description
> 
> I think the notification sound is to low. On this laptop I have to turn up the sound volume to hear the notifications. This however make all other sounds annoying loud.
> Please make the build in sound louder.
> 
> OS: Linux Manjaro
> qTox version: untagged-c311d4df4007cd97cd2a
> toxcore: 0.2.1
> Qt: 5.10.1
> Hardware: Laptop
> …
> 
> Reproducible: Always
> ##### Additional Info
> 
> Buildin sound level:
> ![Soundlevel](https://user-images.githubusercontent.com/6417330/38668101-a29430e6-3e43-11e8-8c1d-45d9c7a02418.png)
> If I increase the level to:
> ![New level](https://user-images.githubusercontent.com/6417330/38668181-d5ab2ab6-3e43-11e8-9abe-d6a6aead2eb2.png)
> 
> EDIT: This is not true, this only works in test sound with my notification.pcm. With it there's no notification sound at all:
> And use that as
> notification.pcm
> and compile it's much better.
> 
> This is the notification.pcm I made:
> [notification.pcm.zip](https://github.com/qTox/qTox/files/1902361/notification.pcm.zip)

**Comment by sudden6** [comment]
Should be fixed by #5305

**Comment by zetok** [comment]
5d65ab387631cf76adfc36f3f0bf356ec7fd6f7b should have improved situation with too quiet notification sound, which makes me wonder if an option to change loudness of notification sound in qTox is needed at all.

The option at most could lower the volume of notification, as current sound is already at the "max" value.

The original proposal is about introducing an option to increase volume of the notification, which is the opposite of what an option could do, and the commit mentioned above brought sound to the maximum volume already.

If the sound is still not audible enough (it seems to be audible enough for me), the only remaining thing that could be done in qTox would be to change notification sound to a more audible one, but for that a separate issue should be made.

Hence, I think that the issue can be closed as fixed.

**Comment by sudden6** [comment]
I agree, if we want to introduce more fine grained volume controls this would be a different proposal.
