### ISSUE TITLE
Crash on file accept

### ISSUE THREAD

**Issue by Jumbt** [qTox/qTox#2224]
qTox, version: 693e8d84438712eb96c807d0c38a8f8de6cf47fc Built: 16:32:12 Sep 12 2015
Debian Stretch

To Reproduce: Send file to Qtox and accept transfer (tried from utox and antox) - result black error box 'Save a file' with qt error warning box underneath. Qtox becomes unresponsive and must be restarted.

**Comment by antis81** [comment]
@Jumbt What you see is not an error box, but the save dialog (see issue #2205). This just got fixed a few hours ago. Workaround: Press `Escape` key to abort or `Enter` to accept and save file at current location (most probably $HOME).
