### ISSUE TITLE
Broken save file dialog

### ISSUE THREAD

**Issue by wiiaam** [qTox/qTox#2226]
When I try saving a file a separate window opens in front of the Qt file dialog. If you move the black window the file dialog will move with it 

I'm on openbox btw

<img src="https://sr.ht/_gt1.png" />

**Comment by suhr** [comment]
Duplicate of https://github.com/tux3/qTox/issues/2205.

**Comment by wiiaam** [comment]
I tried a search for any duplicates, must've missed that
