### ISSUE TITLE
First qTox start: Friendlist column too wide

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2228]
Hello,

a small issue:
If you start qTox the first time, the proportions aren't perfect.
The friendlist column is too wide to my mind.

Reproduce:
1. Remove Tox folder in your .config-directory (Linux) if you've one already
2. Start qTox
3. Create new profile and login

Environment: Lubuntu 14.04
Commit hash: 346c2c64db811dec7ffdd21e0152e65733204533
Screenshot: ![qTox](https://cloud.githubusercontent.com/assets/8258609/9845838/4cebe6b2-5ace-11e5-8376-39a7bfe9151d.png)

**Comment by zetok** [comment]
So, apparently this is a regression introduced with merge of #1938.

**Comment by zetok** [comment]
git bisect with
good commit: 60c18d07a675759d3ef6f0ca451f31b2bb300729
bad commit: 346c2c64db811dec7ffdd21e0152e65733204533

points to:

```
$ git bisect bad
22fcc3f7a0b854fa9c14090e7b529134046dcfeb is the first bad commit
commit 22fcc3f7a0b854fa9c14090e7b529134046dcfeb
Author: TheSpiritXIII <thespiritxiii@gmail.com>
Date:   Tue Jun 16 14:25:19 2015 -0400

    Multi-window capabilities for all chats and menus

    :100644 100644 3eec7904d248a2d7696fb63353b58c67c5ea2648 7b895882aa7920052291728af28e76397bd9a6ee M  qtox.pro
    :040000 040000 c538ee11553cc1802a249b832a59eeaa8a682fdd 6eca0385554082958a9852275e5f487901d9b5f1 M  src
```

**Comment by tux3** [comment]
Link to the bad commit: 22fcc3f7a0b854fa9c14090e7b529134046dcfeb
