### ISSUE TITLE
move profile location?

### ISSUE THREAD

**Issue by CaptainSkywave** [qTox/qTox#2230]
Current profile location: C:/Users/xxx/AppData/Roaming/tox

How do I move/point to another location like: D:/TOX

**Comment by agilob** [comment]
use portable mode.

**Comment by CaptainSkywave** [comment]
thx

**Comment by CaptainSkywave** [comment]
@agilob - OK I found out that I can tick Make Tox portable - but not sure how to then define a new profile location?

**Comment by zetok** [comment]
@CaptainSkywave I've made https://github.com/tux3/qTox/wiki/Profile - hopefully it has needed info?

**Comment by CaptainSkywave** [comment]
@zetok
Thank you very much - now I finally understand it :)

**Comment by zetok** [comment]
Since question appears to be answered, and there was created wiki entry about it, closing.
