### ISSUE TITLE
Not displayed user name in the dialog remove friend

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#2234]
![default](https://cloud.githubusercontent.com/assets/6053197/9870744/549bed2a-5b97-11e5-9cf5-c969694987c2.png)

**Comment by zetok** [comment]
I couldn't reproduce with english version:
![shows_en](https://cloud.githubusercontent.com/assets/3148759/9875942/2edbe366-5baa-11e5-91dd-58f34f3f382f.png)

but with russian one:
![nope_ru](https://cloud.githubusercontent.com/assets/3148759/9876043/f39b8864-5baa-11e5-9556-a257c91ab613.png)

So it looks like a problem when strings are translated.

**Comment by PKEv** [comment]
Yes, this is a mistake of translation:

```
<source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Are you sure you want to remove 
&lt;span style=&quot; font-weight:600;&quot;&gt;&amp;lt;name
&amp;gt;&lt;/span&gt; from your contacts list?
&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
<translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Вы действительно хотите удалить 
&lt;span style=&quot; font-weight:600;&quot;&gt;&amp;lt;имя
&amp;gt;&lt;/span&gt; из вашего списка контактов?
&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
```
