### ISSUE TITLE
Add audio/video device selections

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#224]

**Comment by agilob** [comment]
introduced a few days ago? At least it works on Linux, but doesn't save selected device, settings are reset after closing qTox.

**Comment by tux3** [comment]
It's only done for audio at the moment, but the selected device should be saved and restored correctly, it does work for me on Linux. 
Open a separate issue for that bug ?

**Comment by agilob** [comment]
Hm interesting, I just noticed I have one microphone connected but I have two on the list:
![menu2](https://cloud.githubusercontent.com/assets/2544251/4910305/e766b1ce-647d-11e4-9d6d-80d379a9b462.png)

I have on playback device and one is listed.

Skype does the same with input devices, so it might me PA related or my configuration, the second device is... what is that?

**Comment by tux3** [comment]
The monitor is the "Stereo Mix"/"What-U-Hear" input of the sound card.
It basically sends the output back into the input. So you can use whatever is playing through the speakers as a sound source, as if it was coming from a microphone.

**Comment by agilob** [comment]
Oh that's cool \o/

and I tested it again now, and saving works...

**Comment by zetok** [comment]
@dubslow it's still not closable, since there's still no video device selection, AFAICT

**Comment by tux3** [comment]
This is now done.
