### ISSUE TITLE
The "multi-window" branch merge made qtox look ugly for new users (strange default values)

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#2240]
This is how it looks like when you start it the first time:
![das](https://cloud.githubusercontent.com/assets/6986141/9892282/a45a7144-5c0d-11e5-95c5-561ea888a8c1.jpg)

**Comment by zetok** [comment]
Could reproduce.

**Comment by PKEv** [comment]
duplicate #2228

**Comment by zetok** [comment]
Since it's a duplicate, closing.
