### ISSUE TITLE
Video does not work

### ISSUE THREAD

**Issue by ElLamparto** [qTox/qTox#2245]
Win7 32bit + Debian Jessie 32bit.
Black video windows on both sides. Audio ok. Video preview ok on both sides.
After conversation finished, the camera rest active - qTox restart required.

Win version updated today, Debian version updated yesterday.

**Comment by agilob** [comment]
duplicate of and #1971 will be closed by #2093

**Comment by ElLamparto** [comment]
Ok, but the trick of going to AV settings does not work in my case. Still no video.

**Comment by agilob** [comment]
It doesn't work always, for me it worked after 30seconds after visiting a/v settings tab. #2120. The fix is in `work in progress` branch, but apparently work has been suspended :<
