### ISSUE TITLE
Green "unread messages" notification stays forever.

### ISSUE THREAD

**Issue by ElLamparto** [qTox/qTox#2247]
After qTox start and then reception of an offline message, green "unread messages" notification stays on the bottom-left side, even after the message is read. It should dissapear then...

**Comment by zetok** [comment]
Could reproduce.

Notification finally disappears when scrolling down, but not when clicking on it (it should then).

That's a regression, and seems to have appeared after ~~new groupchats~~ detached windows were merged. If needed, I could do `git bisect`, if no one else will want to do it.

**Comment by Diadlo** [comment]
@zetok Can't reproduce now. Or I do something wrong

**Comment by zetok** [comment]
Welp, I can't reproduce too. I don't even get the unread messages notification anymore, which is a regression…

**Comment by Diadlo** [comment]
@zetok  Hm.. It is strange. I still get unread notification.

**Comment by zetok** [comment]
Huh. In any case, I've made an issue for it: #3193

**Comment by zetok** [comment]
Can ~reproduce with multiple windows mode:
[qtox.webm.zip](https://github.com/tux3/qTox/files/243745/qtox.webm.zip)
