### ISSUE TITLE
Missing "smoking" emoticon in the impressive collection of qTox

### ISSUE THREAD

**Issue by ElLamparto** [qTox/qTox#2248]
as above...

**Comment by agilob** [comment]
Which collection? We actually provide only 3 (or 2?) packages of emoticons.
And by `we` I mean it's a 3rd party dependency.

**Comment by suhr** [comment]
Do you mean the “🚬” emoticon?

**Comment by ElLamparto** [comment]
@suhr , yes I do

**Comment by sudden6** [comment]
Should be fixed by using EmojiOne now.
