### ISSUE TITLE
rename detach option

### ISSUE THREAD

**Issue by aaannndddyyy** [qTox/qTox#2249]
The option "Open chats in separate window" is wrongly named.
Not only chats are ooened in a separate window. And if you have more than one chat they don't get a separate window each, but share one, unless another option is cheked. 
This leads to confusion.

Actually this very text or "Open each chat in an individual window" should be used for the option underneath it, now called "Don't group chat windows". The latter is not wrong, but harder to understand. People may under tsnad that chat windows are groupo by some criterion, which is not the case. Actually what's meant is that all chat windows are luped together into one group if this option is not ticked. So if it is ticked, each chat gets its individual separate chat window
see #2238

**Comment by zetok** [comment]
Since #2250 was merged, closing.
