### ISSUE TITLE
Combo box next to "Theme Color:" isn't translated

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#2257]
![capture](https://cloud.githubusercontent.com/assets/13149763/9964181/32f4ede4-5e2f-11e5-8c60-e6c554b2e5e0.PNG)

It is in the "fr.ts" translation file but it isn't translated.
Even after a restart.

**Comment by zetok** [comment]
Yeah
https://github.com/tux3/qTox/blob/f8352d63ff17bbb551fc575252b747ac95208b99/src/widget/style.cpp#L74,L75

IIRC there was another issue like that, but about date format(?).

**Comment by TheNain38** [comment]
Maybe translation file is loaded after `Style::themeColorNames` is created.
Anyway it should also be translated dynamically.

**Comment by BiTOk** [comment]
Can someone assign this bug to me?

**Comment by zetok** [comment]
Since #2363 got merged, closing.
