### ISSUE TITLE
Automate and speedup translation process by adding qTox to weblate

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#2263]
https://hosted.weblate.org/ all opensource projects are welcome there.

Weblate would have to be added as collaborator to github repository so bot can push directly to selected branch.

**Comment by suhr** [comment]
Is this really necessary?

**Comment by agilob** [comment]
No, you can still add translations by standard PR or use FOSS webservice which synchronises translations and commits. It's easier and faster.

**Comment by suhr** [comment]
> It's easier and faster.

It's rather more “user-friendly”. Anyway, if strandard PR are allowed, I'm ok with this.

**Comment by zetok** [comment]
> Weblate would have to be added as collaborator to github repository so bot can push directly to selected branch.

I'm not sure whether I like that part, but otherwise it sounds good.

**Comment by agilob** [comment]
It's better than opening new PR every time for minor translations like we are flooded with recently. Weblate is hooded to commits, if new strings appears or original translation was changed you can get email about it, you can subscribe to translations in your language.

![weblate](https://cloud.githubusercontent.com/assets/2544251/9975387/e72fccf6-5eb2-11e5-8a7e-95c1ec2dbf3b.png)

After user finishes translating weblate automatically commits changes.

**Comment by zetok** [comment]
With 7474da16b66550f35efb900581e88982c48274da there are pointers to weblate.
Earlier commits pulled changes from weblate & updated files for weblate to use.
Also, now translations will be pulled from weblate in timely & regular manner, thus closing.
