### ISSUE TITLE
screenshot mode note's transparency is ugly

### ISSUE THREAD

**Issue by aaannndddyyy** [qTox/qTox#2267]
The little yellow note informing about the options is rather transparent.
This looks bad as it is directly over the qTox title or any maximized window's title.
It does not get into the screenshot, but it looks not nice.

**Comment by agilob** [comment]
This issue is completely meaningless. Suggestions or patches are welcome...

**Comment by aaannndddyyy** [comment]
it's not meaninless. It means I as a user of qTox do not lilke it.
You can of course have a differing opinion on the aesthetics of it. 
But to me, different texts fused into one another look bad.

Suggestion1: make it non-transparent
Sugesstion2: if you love it the way it is leave it the way it is
Suggestion3: if you need to see what's underneath it and you cannot see it when non-transparent, hide the message after a certain time or a certain user action (h for hide)

**Comment by agilob** [comment]
> it's not meaninless. It means I as a user of qTox do not lilke it.
> But I dont know what I am supposed to do with this information.
> 
> You can of course have a differing opinion on the aesthetics of it. 

I don't mind it, I 80% like it.

@PKEv could you take that issue?

**Comment by zetok** [comment]
> Suggestion3: if you need to see what's underneath it and you cannot see it when non-transparent, hide the message after a certain time or a certain user action (h for hide)

If possible, I think that it should be hidden on mouse hoover over it.

**Comment by TheNain38** [comment]
I like zetok's idea.
