### ISSUE TITLE
No "X" button to exit in gnome after enabling multiple windows

### ISSUE THREAD

**Issue by RadJaz** [qTox/qTox#2270]
There isn't an "X" button in the top right corner when I enable multiple windows. I am running gnome and it looks like this
![screenshot from 2015-09-20 12-03-52](https://cloud.githubusercontent.com/assets/10097860/9981993/5fd9021e-5f92-11e5-971c-f996d2d90de7.png)

This does have a workaround however, if i put my mouse in the top-left corner of the screen, i can close it from there, like this:
![screenshot from 2015-09-20 12-10-40](https://cloud.githubusercontent.com/assets/10097860/9981996/86130e34-5f92-11e5-91b6-e0c4255c9f89.png)

**Comment by ghost** [comment]
FYI: no issues in Cinnamon 2.6.13.

**Comment by zetok** [comment]
@kehugter um, from what has been said on IRC, I understood that @RadJaz uses qTox under wayland - do you have similar setup with Cinnamon?

**Comment by ghost** [comment]
Nope, X.

**Comment by antis81** [comment]
Cannot reproduce on `OpenBox` (X env.) also.

Had a look into the code and found, that the "forms" (SettingsForm, GenericChatForm, …) inherit directly from `QWidget`. If you have a look at the QWidget defaults, you'll find, those widgets are not marked as a `Qt::Window` (Qt::Dialog probably?). This might hint the WM to render a window frame, but without the buttons we "usually" expect.

@RadJaz Could you please check set the flags in the constructors of `GenericChatForm` and `SettingsForm`? Like this…

``` c++
GenericChatForm::GenericChatForm(QWidget *parent)
  : QWidget(parent, Qt::Window)
…
{
…
}
```

(…and the same to SettingsForm) - Thanks!

This should not cause any problems in "un-windowed" mode.

**Comment by RadJaz** [comment]
You're correct in that I am running gnome on wayland. I guess I should've mentioned it in the original post. But I'm not quite understanding what you're asking for me to check. If you could give me more detailed instructions, I'd be happy to, though. I apologize for my lack of knowledge.

**Comment by antis81** [comment]
@RadJaz No problem. Unfortunately I don't have a Wayland environment for testing available here. So… I cannot actually check this and ask you to compile it. I guess you do not have a build environment set up, right? I'll setup a pull request (branch) with the required changes to test this until evening (well… hopefully the plane lands on time :smile:). Feel free to Tox me `C52DA9FE98B86AF01178CB605DA2585919B2BA72DF1968B97932DE7155EC354320A65105E357`.

@tux3 @agilob Anyone else able to check this one for Wayland?

**Comment by zetok** [comment]
@RadJaz well, basically @antis81 asked you to recompile source after you change source code a bit - I guess that's not something that you're familiar with.

> I apologize for my lack of knowledge.

Don't, no one knows everything `:)`

Generally, you should get source, apply patch ↓, build qTox, and run it.

``` diff
diff --git a/src/widget/form/genericchatform.cpp b/src/widget/form/genericchatform.cpp
index 21c9f0c..ec86c03 100644
--- a/src/widget/form/genericchatform.cpp
+++ b/src/widget/form/genericchatform.cpp
@@ -46,7 +46,7 @@
 #include <QPushButton>

 GenericChatForm::GenericChatForm(QWidget *parent)
-  : QWidget(parent)
+  : QWidget(parent, Qt::Window)
   , audioInputFlag(false)
   , audioOutputFlag(false)
 {
diff --git a/src/widget/form/settingswidget.cpp b/src/widget/form/settingswidget.cpp
index c44b948..1ba9be0 100644
--- a/src/widget/form/settingswidget.cpp
+++ b/src/widget/form/settingswidget.cpp
@@ -32,7 +32,7 @@
 #include <QWindow>

 SettingsWidget::SettingsWidget(QWidget* parent)
-    : QWidget(parent)
+    : QWidget(parent, Qt::Window)
 {
     body = new QWidget();
     QVBoxLayout* bodyLayout = new QVBoxLayout();
```

(that is, if I got correctly what @antis81 wrote about)

@antis81 btw, since I don't think that people in general will be able to test things like that, I set on jenkins job to build things pushed to branch `testing`.

If you could, push to `testing` branch, and https://build.tox.chat/view/Sources/job/qtox-testing_src/ will be triggered, which will trigger build of static binaries, which @RadJaz could test.

# 

On a side note, `testing` branch could be used also for other things as well, not only this issue `:)`

**Comment by antis81** [comment]
@zetok Yep! :+1: :smile:

**Comment by agilob** [comment]
please dont ask users to apply patches, it's not what they are for ;)

**Comment by antis81** [comment]
@agilob No users were harmed during the testing of this issue! :smile: -> See zetok's comment above.

**Comment by agilob** [comment]
We have nice jenkins setup which can build branches and commits from forks, so I guess it would be easier for everyone to use it than send patch files (you still had to write that code, extract patch and post patch, so you could commit and push).

**Comment by antis81** [comment]
@agilob Thanks! I didn't know about that. Will it "automagically" pull the fork? Otherwise I'll put the info inside the PR.

**Comment by agilob** [comment]
I think first time a branch is build @zetok must add it manually to jenkins.

I wish we were using gitlab and gitlab-ci where this happens automatically for all branches, commits and merge requests.

**Comment by zetok** [comment]
> We have nice jenkins setup which can build branches and commits from forks

Actually, no, jenkins currently only tracks `master` branch of `tux3/qTox` - I just added to it tracking of `testing` branch on `tux3/qTox` - for any changes to be build as a binary that users could test, they must be currently pushed to either `master` or `testing` branch.

> I wish we were using gitlab and gitlab-ci where this happens automatically for all branches, commits and merge requests.

Currently travis builds all branches & PRs.

@antis81 could you push that change to `testing` branch?

**Comment by RadJaz** [comment]
When a testing binary is available, I will gladly test it on my setup.

**Comment by agilob** [comment]
> I wish we were using gitlab and gitlab-ci where this happens automatically for all branches, commits and merge requests.
> 
> Currently travis builds all branches & PRs.

yes, but travis doesn't publish built binary files.

**Comment by zetok** [comment]
@agilob AFAIK it can be made to do that, but it's not a good idea anyway.

**Comment by zetok** [comment]
Actually, I'll just push to `testing` branch.

**Comment by zetok** [comment]
@RadJaz ok, in <15 min "Downstream Projects" of https://build.tox.chat/view/Sources/job/qtox-testing_src/ should build, which you could test `:)`

**Comment by zetok** [comment]
@RadJaz does https://build.tox.chat/view/Sources/job/qTox-testing-qt5.4.2_build_linux_x86-64_release/lastSuccessfulBuild/artifact/qTox-testing-qt5.4.2_build_linux_x86-64_release.tar.xz improve things for you?

**Comment by RadJaz** [comment]
It appears not
![screenshot from 2015-09-23 15-32-30](https://cloud.githubusercontent.com/assets/10097860/10057936/65ef59e6-6208-11e5-9907-619a23cb46b4.png)

**Comment by antis81** [comment]
Thanks @zetok! Somebody with a Wayland environment should better go on and fix this one.

@RadJaz This might be also controlled by a setting in Gnome WM. My environment shows three buttons (_ - x) on the friend list window as well.

**Comment by agilob** [comment]
Wrong, issue isn't fixed @antis81

**Comment by antis81** [comment]
@agilob Yeah, I cannot check it cause I don't have Gnome/Wayland installed. Guess we require somebody running this environment who is able to check it.

**Comment by agilob** [comment]
I have Gnome3, do you have any suggestion what I could try?

**Comment by ghost** [comment]
If you use VMware, you could run [Maui](http://www.maui-project.org/download/). Virtualbox doesn't support Wayland yet.

**Comment by agilob** [comment]
I can switch to wayland, kde5 supports it.

**Comment by sudden6** [comment]
Is this still an issue? If not please close.

**Comment by project9501** [comment]
I'm having this issue.  When in multiple window mode, there's no window control buttons on the "Settings" window; have to close using taskbar context menu.

OS: Antergos (running as VM guest but I don't imagine that's relevant)
WM: Cinnamon 3.4.0
qTox: 1.10.1
Qt: 5.8.0

**Comment by RadJaz** [comment]
I am no longer experiencing this issue. I am on Ubuntu Gnome (with Wayland) 17.04 with Qtox 1.6.0.

![screenshot from 2017-05-19 17-18-27](https://cloud.githubusercontent.com/assets/10097860/26269134/b2af705e-3cb8-11e7-8147-70824464eed1.png)

**Comment by sudden6** [comment]
@project9501 can you retest with the newest master? #4421 maybe fixed the issue

**Comment by Diadlo** [comment]
Needed info not provided for over a month, thus closing.
