### ISSUE TITLE
[Proposal] change of blinking icon on new message

### ISSUE THREAD

**Issue by azlux** [qTox/qTox#2273]
hi all,
I've try some Tox client on different OS.
On windows, i cannot see new messages because the icon change (green to orange) is not so easy to notice.
When i look at µTox we have real changes to catch the new message (+notification), the icon become red, and that is easy to see.
![sans titre 1](https://cloud.githubusercontent.com/assets/11210117/9989327/c41e3e7c-6057-11e5-8d59-c54a7e007e03.png)

I think It will be better to do the same.

**Comment by zetok** [comment]
So, basically, what you're asking for are 2 things:
1. Notifications in qTox (duplicate of #483)
2. Change of blinking icon.

Since there's already an issue for notifications open, this one could be used only for discussion related to change of blinking icon.

**Comment by azlux** [comment]
Indeed, the blinking icon on new message is the topic of this discussion !

**Comment by ProMcTagonist** [comment]
I think I would like a Tox Orange body better than a red one like what utox uses.
<img src="https://cloud.githubusercontent.com/assets/4358079/10011843/6f69f782-60b5-11e5-9c76-58aee310da52.gif" width="30">

<img src="https://cloud.githubusercontent.com/assets/4358079/10011866/a99fe8a8-60b5-11e5-99fa-ebebeca17e63.gif" width="30">

**Comment by zetok** [comment]
I like orange one more too.

**Comment by azlux** [comment]
The orange icon is good. Do you want to keep it blinking ? It's may be too aggressive into the taskbar, no ?

**Comment by zetok** [comment]
Probably isn't: https://d.maxfile.ro/wlyrvixwhi.webm

**Comment by agilob** [comment]
is orange and green color-blind friendly? i'm not sure about it.

**Comment by suhr** [comment]
It's a bit ugly.

**Comment by zetok** [comment]
@suhr well, that's due to poor quality of .webm; also there's lack of improvements from #2132 which, IIRC, were helping with how icon looked.

https://github.com/tux3/qTox/blob/2bdb6339a529702a495859bdc792127f2a26cc73/img/taskbar/dark/taskbar_event.svg ← that's how it is supposed to look(?)

If you're talking about generally "whole" icon in orange looking bad - I'm not sure what could be done about this, given that current way in which notifications are working isn't good enough, since often I manage to not notice new messages for more than 30min… which means that it needs to be changed.

**Comment by agilob** [comment]
What about blinking white-black icon? We have both already in repo. That would a couple of lines to implement it.

**Comment by ProMcTagonist** [comment]
Maybe we can change up the shape more?

![exclaim](https://cloud.githubusercontent.com/assets/4358079/10024719/69f38da6-610d-11e5-86f8-dc8d6d9384c4.gif)

**Comment by ghost** [comment]
> It's a bit ugly.

:+1: 
Couldn't it instead mimic the dots in the friends list when you receive a new message? A "glowing" effect could be added to make it more noticeable.

**Comment by src386** [comment]
Hi,
Yeah this is a real problem.
I often receive messages but I don't notice because it's just not visible.
Blinking icon AND window list (I'm on Xfce) would be great !

**Comment by Jeeppler** [comment]
orange-green is not really nice. What's about just having a colourized exclamation mark, but static? Like not a blinking thing, it should be something calm but noticeable like github notifications (just a blue dot)
