### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sytolk** [qTox/qTox#2274]
Thanks for the free Skype :+1: 
do you have a plan to support SIP or IAX2 protocols ?

**Comment by zetok** [comment]
> Thanks for the free Skype :+1: 

You're welcome `;)`

> do you have a plan to support SIP or IAX2 protocols ?

No, qTox uses **secure** protocol - adding support of some other, **insecure** by nature protocols would only harm qTox.

With that being said, it should be possible to make bridges `Tox ↔ IAX2` / `Tox ↔ SIP` - although this wouldn't be secure, and wouldn't be directly a part of the qTox, it may be possible.

What would be needed though, is probably support in `toxcore`, and services that would provide bridges from Tox to other, insecure means of communicating.

As things are, it should be already possible with current toxcore functionality to provide functionality needed to make a bridge, although probably in a bit cumbersome way..

If that answers your question, please close the issue.

**Comment by agilob** [comment]
> do you have a plan to support SIP or IAX2 protocols ?

To do so, you would have to create centralised bridge (which is what tox tried to avoid) that translates one protocol into another, it's not a qTox issue. qTox is just a client based on toxcore library/protocol.

**Comment by sytolk** [comment]
As I understand in the feature will be not possible to make a phone call from IAX2 trunk to qTox client? 
Maybe this question is for https://github.com/irungentoo/toxcore project but qTox is just a client and can use toxcore protocol for tox users and some IAX2 library to connect tox users with IAX2 user. I think that qTox or Antox.. applications can be this bridge for open source connection.

**Comment by ProMcTagonist** [comment]
No. qTox will not promote insecure protocols. You can use Miranda or Weechat if you'd like a multiprotocol messenger.
