### ISSUE TITLE
Default font is too small

### ISSUE THREAD

**Issue by subliun** [qTox/qTox#2280]
It's just too small for no reason. I can't read any name in my contacts list.

**Comment by alexbakker** [comment]
Looks fine on my machine.
<img src="https://impy.me/i/15efdb.png"/>

Where is the font too small, specifically?

**Comment by ElLamparto** [comment]
Probably you have to uncheck option Compact contact list (Settings/General)

**Comment by DanTheBritish** [comment]
That doesn't increase font size, only the spacing around the contacts.

**Comment by agilob** [comment]
@subliun could you provide screenshot?

**Comment by zetok** [comment]
@subliun so, basically this issue is about **default** font being too small? If so, could you change title to `Default font size is too small` ?

related issues: #672, #1025

**Comment by subliun** [comment]
![small font](https://cloud.githubusercontent.com/assets/2082980/10562068/049c0202-7590-11e5-9637-f19a8e80af8b.png)
It's much worse on Windows

**Comment by sudden6** [comment]
Still a problem at 76c4cf7d390ece3d0ec57b771fb9aaa21f7337f7 since chat font size is changeable now, but the rest isn't.

**Comment by ElLamparto** [comment]
Chat font size is changeable in the chat form only. In the edit field where you type your messages it is not. And it should be same as in the chat form.
