### ISSUE TITLE
You have to type "YES" to remove a friend.

### ISSUE THREAD

**Issue by subliun** [qTox/qTox#2281]
![capture](https://cloud.githubusercontent.com/assets/2082980/10045584/f1b095c8-6242-11e5-8356-c9177dc522b9.PNG)

I mean, really?

**Comment by tsdko** [comment]
What's wrong with that?

**Comment by subliun** [comment]
Everything. Everything is wrong with that.

I thought it was some sort of bizarre joke/bug at first.

**Comment by zetok** [comment]
What is the problem?

**Comment by subliun** [comment]
@zetok I had to type "YES" to delete my friend.

**Comment by zetok** [comment]
@subliun and what is the problem with it?

**Comment by subliun** [comment]
I'm Chinese/Russian/Arabic/Indian/Japanese and I can't delete my friend.

**Comment by zetok** [comment]
@subliun why wouldn't you be able to?

**Comment by subliun** [comment]
I don't have an ascii keyboard.

**Comment by subliun** [comment]
Think, zetok

**Comment by agilob** [comment]
This string is translatable. In Polish you write "TAK".

**Comment by zetok** [comment]
I see. Closing as invalid. 
![tfw no ascii](https://cloud.githubusercontent.com/assets/3148759/10045857/8a534bc2-61fd-11e5-990a-652f84e61470.png)

**Comment by subliun** [comment]
Okay. This is still just silly though.

**Comment by subliun** [comment]
What if someone speaks a language that qTox doesn't have a translation for?

**Comment by zetok** [comment]
> What if someone speaks a language that qTox doesn't have a translation for?

Then they know english, since without that they wouldn't be able to use qTox anyway..

**Comment by subliun** [comment]
@agilob surely you can see why this is terrible UX?

**Comment by wiiaam** [comment]
A delete/cancel dialog would suffice
Make the default cancel though in case my cat walks on my keyboard or something

**Comment by subliun** [comment]
I encourage devs to do some reading.
http://ux.stackexchange.com/questions/74/the-must-read-user-interface-book

**Comment by DanTheBritish** [comment]
GitHub forces you to enter the name of a repository when deleting.

**Comment by tux3** [comment]
I also think that having to type "YES" is really annoying, a confirmation dialog would probably be enough.

**Comment by ProMcTagonist** [comment]
Any obstacle you put in the way of a destructive task, the user will automate with muscle memory if they do it enough. That's why you have to make destructive actions recoverable, not just try to make them harder. A "Recently Removed" list would be better than making users type on deletion.
