### ISSUE TITLE
qtox bypasses proxy if not available

### ISSUE THREAD

**Issue by src386** [qTox/qTox#2287]
Hi,
I have a SOCKS proxy.
I have set that proxy in qtox and it's working.
But when the proxy is offline, qtox is still available to connect, that's weird.
So I'm not sure it really uses the SOCKS proxy...

**Comment by agilob** [comment]
Isn't it a toxcore issue? We just set proxy settings in toxcore setup.

**Comment by src386** [comment]
So I should create an issue at toxcore github ?

**Comment by agilob** [comment]
I'm not sure but I think so. @zetok?

**Comment by zetok** [comment]
https://github.com/tux3/qTox/blob/6229e045f2b40fbb9ab32e38b3f92ae403ee130b/src/core/core.cpp#L219,L225

@src386 ↑ if you don't see in log `bad proxy` or `proxy not found`, then it's a toxcore issue, and issue should be opened on it.

toxcore's documentation on `TOX_ERR_NEW_PROXY_NOT_FOUND` says only:

```
The proxy address passed could not be resolved.
```

So, it does look like a toxcore problem, given that proxy name could be resolved, even if proxy is down…

**Comment by ovalseven8** [comment]
That's what irungentoo wrote in the toxcore-issue:

> Toxcore only uses the proxy for TCP and not UDP. If you want to use the proxy for anonimization purposes (and not for connecting better purposes) you need to disable UDP. Your client should have a 'force proxy' option that does this.
> 
> That's what I think the issue is in this case.

Would change the priority to 'High'.

**Comment by ovalseven8** [comment]
For me the proxy should be enforced by default, right?

**Comment by zetok** [comment]
> For me the proxy should be enforced by default, right?

IMHO rather than enforcing proxy by default, there should be an option to tick `Enforce proxy`, which would make sure that qTox connects only via proxy (disabled UDP & toxdns support)

**Comment by ProMcTagonist** [comment]
If a user has entered a proxy, I think it's incredibly likely that they need and expect it to be used.

**Comment by ovalseven8** [comment]
Just tested with `Proxy: 127.0.0.1 and Port 9150` and Tor was not running.
Seems qTox didn't bypass proxy, I never got online. Of course, UDP was deactivated.

@src386: Did you deactivate UDP?
@tux3: What should be the desired behaviour? Do we need force proxy option or should it already work with UDP disabled? 

Everyone: Could you test it with some proxies?

**Comment by TheNain38** [comment]
Tor default proxy is port 9050 not 9150 and by desactivating udp and ipv6 I got online

**Comment by ovalseven8** [comment]
@TheNain38: You're right, but I used the Tor Browser, which is using Port 9150.

**Comment by TheNain38** [comment]
Ok, if Tor isn't running then I don't have any connexion he was referring that if UDP is enabled then it didn't used the socks proxy

**Comment by zetok** [comment]
Should be fixed on newest qTox, thus closing.

If you still can reproduce, please comment for reopen.
