### ISSUE TITLE
qTox segfaults

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#229]
Long story short:

```
% qtox 
zsh: segmentation fault  qtox
```

**Comment by zetok** [comment]
Could you run it under gdb?
And provide more info?

**Comment by suhr** [comment]
```
(gdb) run
Starting program: /usr/bin/qtox 
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000003224a09e20 in _GLOBAL__sub_I_qtestcase.cpp () from /usr/lib64/qt4/libQtTest.so.4
```

**Comment by tux3** [comment]
You're running Qt4 apparently. qTox requires Qt5.
Did you compile it from source ?

**Comment by suhr** [comment]
Yes, I've used the gentoo overlay.

**Comment by tux3** [comment]
Well, make sure you have Qt5 and compiled qTox with it ? I don't maintain or use the gentoo overlay, so I'm not sure what the problem is.
If it still fails, please post the output of <code>ldd qtox</code>

**Comment by suhr** [comment]
```
    libQt5Widgets.so.5 => /usr/lib64/libQt5Widgets.so.5 (0x0000003228200000)
    libQt5Xml.so.5 => /usr/lib64/libQt5Xml.so.5 (0x0000003229000000)
    libQt5Network.so.5 => /usr/lib64/libQt5Network.so.5 (0x0000003227600000)
    libQt5Gui.so.5 => /usr/lib64/libQt5Gui.so.5 (0x0000003226600000)
    libQt5Core.so.5 => /usr/lib64/libQt5Core.so.5 (0x0000003226e00000)
...
    libQtOpenGL.so.4 => /usr/lib64/qt4/libQtOpenGL.so.4 (0x000000321f000000)
    libQtGui.so.4 => /usr/lib64/qt4/libQtGui.so.4 (0x0000003220a00000)
    libQtTest.so.4 => /usr/lib64/qt4/libQtTest.so.4 (0x0000003224a00000)
    libQtCore.so.4 => /usr/lib64/qt4/libQtCore.so.4 (0x000000321f800000)
```

For the reason I don't know it links with both Qt5 and Qt4 libraries.

**Comment by tux3** [comment]
Yeah, something is really wrong. That's probably an error in the gentoo overlay or in your build environnent.

Make sure your run qmake and not qmake-qt4 when building, make sure your Qt5 SDK is installed correctly (can you build and run a simple Qt5 exemple?), and check if anything else is tinkering with the linker's argument (only qmake should).

**Comment by suhr** [comment]
OpenCV uses qt4! Well, now I know how to fix it.

Also, make OpenCV optional.
