### ISSUE TITLE
Screenshot: When pressing space to hide qTox sometimes it is in proccess of reappearing

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#2290]
![qtox-screenshot-thcnm944](https://cloud.githubusercontent.com/assets/13149763/10079336/bbd48a7a-62e9-11e5-9b67-4d726818e9ae.png)
I took this screenshot with qTox to show what I mean.

Windows 8.1 64-bits
commit: eb1d70176d9d752b3ade7738e15984c40fb332c4

**Comment by linux-modder** [comment]
Do you have any  transparency settings with non fully opaque  transitional states ? Being a linux guy mostly I can remember where it is  on Win 8.1... But to clarify you can have opacity for  types of  windows e.g. inactive,popup,etc also may be something graphics related (graphics card attempting to  redraw and  creating that `artifact` appearance

**Comment by agilob** [comment]
I'm not sure what happened? Did you take a screenshot of that white grid?

**Comment by zetok** [comment]
@agilob hiding & restoring window simply is made by letting some time "flow" when window is being hidden/restored (100ms)

**Comment by agilob** [comment]
So there should be added a delay (100ms?) before showing/hiding qtox window?

**Comment by zetok** [comment]
> So there should be added a delay (100ms?) before showing/hiding qtox window?

um, no, that's what currently happens.. 
https://github.com/tux3/qTox/blob/45db1dff9184b509c72fe167664c9a7694385ab9/src/widget/tool/screenshotgrabber.cpp#L99
Actually, it would seem to be 200ms.

**Comment by TheNain38** [comment]
No this didn't happened before #2254 was merged this is because of restoring window.
It should wait a little more before being restored.
