### ISSUE TITLE
Add silent setting to change Blinkenlights

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#2291]
https://github.com/tux3/qTox/pull/2276

**Comment by sudden6** [comment]
No idea what this means.

**Comment by anthonybilinski** [comment]
I'm guessing this is referencing that currently with "busy" status, audio notifications are silenced, but desktop notifications + blinking icon are not. This means if you're busy and want qTox to be neither seen nor heard, you have to go to settings and uncheck "Notify".

I'm not sure of a good way to address this - I don't think "busy" generally means "no notifications at all". I'll leave close for now unless someone has a good idea.
