### ISSUE TITLE
[Regression] qTox lost all my sent messages from few last days

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#2292]
qTox 1673b43e26c853f6446f228fec083af166cbf446 , has happened also on some earlier version.

I don't have any of my sent sent messages in my history after restarting qTox (all received messages are still shown), for past 8 days.

Seems like a recent regression, I'll try to track it down later with bisect.

**Comment by zetok** [comment]
So. I could reproduce that with only 1 profile. Weird.

I've checked out to 47c4fab08bcecf31278cad9e78870a1161a618d0 and apparently things worked, whereas master (42c29c8b8fa5e719c9c78c15f109b358c9225c0c) didn't work.

I've used those points for bisect.

```
564b32eb7c196b39016dfd67c5c4260fb78b8fca is the first bad commit
commit 564b32eb7c196b39016dfd67c5c4260fb78b8fca
Author: PKEv <pkev@yandex.ru>
Date:   Fri Aug 28 00:07:24 2015 +0300

    save alias

:040000 040000 1196607a9e8b65efc52c9173df7bb392c01111bf 615e6e3a8011634624495e40030d088164825706 M  src
```

After reverting 564b32eb7c196b39016dfd67c5c4260fb78b8fca things work correctly.

@PKEv could you fix that? I think that problem exists when own nick ends with null character.

**Comment by PKEv** [comment]
What nickname was used? So I can repeat at itself

**Comment by zetok** [comment]
`Zetok\0`
\0 - null char

**Comment by zetok** [comment]
@PKEv ok, I've appended null char to my spambot's nick - now you can use it for testing:
`C7719C6808C14B77348004956D1D98046CE09A34370E7608150EAD74C3815D30C8BA3AB9BEB9`

I think that there also might be a related history bug, where history that contains some special chars isn't saved.

https://github.com/zetok/tox-rust-neurological-warfare-bot#friend-commands ← bot commands

**Comment by PKEv** [comment]
![qtox-screenshot-gilf4704](https://cloud.githubusercontent.com/assets/6053197/10291403/4657af6c-6bb2-11e5-9c54-f206c4a9a5e9.png)
Probably not yet done?
I do not see the problems of history loaded

**Comment by zetok** [comment]
@PKEv did you restart qTox after receiving the message?

**Comment by PKEv** [comment]
Yes, and checked database entry
![qtox-screenshot-scvfw948](https://cloud.githubusercontent.com/assets/6053197/10292093/f75849e0-6bb5-11e5-9d80-12dce69b0355.png)

**Comment by zetok** [comment]
~~Actually, nevermind, I too can't reproduce it with bot - though I'm not sure why, since bot has null character at the end.~~

~~I wonder - perhaps it has something do do with the fact that friend names are being saved as alias and that alias is being displayed - could null char be stripped from friend names?~~

**Comment by PKEv** [comment]
need time to look

**Comment by zetok** [comment]
> Actually, nevermind, I too can't reproduce it with bot - though I'm not sure why, since bot has null character at the end.

Actually, nevermind that - I forgot that I was using patched version, with commit that was causing regression reverted.

On build from jenkins **it's totally reproducible**. (with bot)

**Comment by antis81** [comment]
Just a guess: Looks like some `QString::fromUtf8()` or it's counterpart `QString::toUtf8()` is missing. Btw. We can (and should) forbid implicit cast from `char*` by setting `QT_NO_CAST_FROM_ASCII`, but someone would need to walk all the strings in qTox and change `QString(text);` to `QString::fromUtf8(text)`. Probably requires rebasing some of the open PR's, but it is worth the work.

**Comment by tux3** [comment]
Repro:
- Talk to THIS. IS. TOX. bot with unencrypted history enabled
- Wait a couple seconds/minutes
- Restart qTox
- History should be gone

**Comment by PKEv** [comment]
History is not reset, but written not all
![qtox_screenshot_2015-10-08 23-51-47 495](https://cloud.githubusercontent.com/assets/6053197/10379942/c585ee8e-6e19-11e5-8926-bfe9b9d24c55.png)

**Comment by agilob** [comment]
what a useful bot

> someone would need to walk all the strings in qTox and change QString(text); to QString::fromUtf8(text)

could be done with sed

**Comment by SlugFiller** [comment]
Fix me if this is related or not, because I don't know if to open a new issue: I've had a power break while qTox was running, and upon coming back, my whole chat history was gone, including pending fake offline messages. I've tried right clicking and loading chat history, but nothing.

To be clear, this was not shortly after receiving messages, but rather, several hours later, so I reasonably expected for the messages to have already been "saved and flushed".
For comparison, Skype was also running at the same time, and experienced zero data loss.

I've only been using Tox for a couple of days, so the biggest loss was the fake offline messages. But I'd rather have some guarantee that this won't repeat in the future, after I've accumulated a larger history.

**Comment by agilob** [comment]
@SlugFiller your issue is related to (the same as?) #2362

**Comment by SlugFiller** [comment]
No, because, like I've said, it wasn't 5 seconds after, or even 5 minutes after. It was hours after, and all my contacts were offline anyway. So there's no reason for it to not be already flushed, or for it to have been corrupted.

**Comment by zetok** [comment]
> I've only been using Tox for a couple of days, so the biggest loss was the fake offline messages. But I'd rather have some guarantee that this won't repeat in the future, after I've accumulated a larger history.

Well.. qTox is still in alpha, so no guarantees (yet). That being said, bugs about data loss should have highest possible priority..

**Comment by SlugFiller** [comment]
Update: I've re-tested, and simply restarting qTox normally killed my history. So a power break is not required. It seems history currently isn't saved at all between runs. So it's probably this bug.

In case it matters, I'm running in portable mode.

**Comment by zetok** [comment]
Uh.

@SlugFiller I guess that I'll make qTox build with 564b32eb7c196b39016dfd67c5c4260fb78b8fca reverted, and if it'll work for you, I'll push that to master.

**Comment by SlugFiller** [comment]
On second thought, never mind. It seems to be related to #2142. I've removed the password from the account, and it works perfectly now. It seems qTox has some issue reading its own encrypted history (And silently deletes it instead of issuing a visible warning).

**Comment by ProMcTagonist** [comment]
This happens to me on every single qTox start.

```
[11:59:36.858] src/core/core.cpp:262 : Debug: Loading user profile
[11:59:36.858] src/persistence/profile.cpp:238 : Debug: Loading tox save  "/home/user/.config/tox/main.tox"
[11:59:36.859] src/widget/systemtrayicon.cpp:130 : Debug: Using the Qt backend
[11:59:36.970] src/core/core.cpp:151 : Debug: Core starting with IPv6 enabled
[11:59:37.208] src/core/coreencryption.cpp:83 : Warning: Decryption failed
[11:59:37.208] src/persistence/db/encrypteddb.cpp:104 : Warning: pullFileContent: Encrypted history log is corrupted: can't decrypt, will be deleted
```

**Comment by zetok** [comment]
@ProMcTagonist that's most likely #2142
