### ISSUE TITLE
'Light icon' should be able to be checked even when 'Show system tray icon' is unchecked

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#2293]
![capture2](https://cloud.githubusercontent.com/assets/13149763/10087198/c7b7d954-6312-11e5-9179-219ad0fb1dce.PNG)

**Comment by ProMcTagonist** [comment]
If that's the case, because the icon is still used for the general purpose icon, 'Light Icon' shouldn't be in the System tray section at all

**Comment by zetok** [comment]
Since #2386 is merged, closing.
