### ISSUE TITLE
When closing qTox and you were AFK and your status switch to 'Away' if you close qTox and reopen it your status is away

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#2301]
It happens since #2298 was merged.
Reproduce:
- Set your status to 'Online'
- Wait for qTox to think you're AFK, so it sets your status to 'Away'
- Close qTox without moving mouse, use Alt+F4
- Reopen qTox and your status is set as if you set it to 'Away'

Expected behaviour:
qTox should load your status as if you were 'Online'

What happens:
qTox load the 'Away' status

**Comment by agilob** [comment]
What's the problem actually?

**Comment by zetok** [comment]
@agilob status not changing from `Away` back to `Online`

**Comment by antis81** [comment]
@agilob :+1:

qTox saves the status and reloads it on next start correctly. So there's no problem!

**Comment by TheNain38** [comment]
Yes, but if you were 'Online' and qTox set status to 'Away' because you were AFK, if you close and reopen it it loads status 'Away' even though you were 'Online' before

**Comment by zetok** [comment]
> @agilob status not changing from `Away` back to `Online`

Or rather, the real problem is that qTox doesn't detect activity properly - i.e. it's probably about qTox not detecting activity before being closed, which causes status to be saved as `Away`, even though just before closing it should have been changed to `Online`, since there was an activity.

**Comment by TheNain38** [comment]
It takes one second to detect activity. Also it could be made to change to 'Online' if you were AFK previously when closing it so it would save the good status?

**Comment by antis81** [comment]
In this case, this also relates to #2300.

**Comment by ProMcTagonist** [comment]
> Also it could be made to change to 'Online' if you were AFK previously when closing it so it would save the good status?

This is the solution.
