### ISSUE TITLE
If you invite someone to a group multiple times he receive multiple dialog asking if he wants to join

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#2305]
Reproduce:
- Setup:
  - Create 2 profiles
  - Make them friends
- Create a group chat with one profile
- Then invite multiple times the friend
- The friend receive multiple times the dialog to join

Expected behaviour:
He receive only one dialog.

What happens:
He receive multiple times the same dialog

**Comment by sudden6** [comment]
I can confirm this and want to add the following:

If someone doesn't want to join a groupchat now, but maybe later, there is currently no way of doing that.
I would suggest a list of recieved groupchat invites where you can later join or delete the request permanently.

**Comment by zetok** [comment]
> If someone doesn't want to join a groupchat now, but maybe later, there is currently no way of doing that.
> I would suggest a list of recieved groupchat invites where you can later join or delete the request permanently.

I wonder how doable is that..

**Comment by sudden6** [comment]
Maybe we could add another tab to the filetransfer history, like "Groupchat Requests".
I don't know if this is even supported by toxcore, I'm just delivering ideas :)

**Comment by subliun** [comment]
In Antox group invites act like friend requests. I'm not sure if they expire though, so it might not actually be doable.
