### ISSUE TITLE
Proposal: qTox could be made to detect email address and create a 'mailto:' link

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#2306]

**Comment by NoxNoctium** [comment]
would probably heavily conflict with toxdns services.

**Comment by agilob** [comment]
we don't modify user input/output!

**Comment by TheNain38** [comment]
@agilob And if you write mailto:example@example.com explicitly?

**Comment by agilob** [comment]
Personally, I don't think qtox should detect several most common protocols, currently @PKEv  was working on this.

**Comment by PKEv** [comment]
The support can be made
but the user is unlikely to be handed typing "mailto:example@example.com"

**Comment by TheNain38** [comment]
@PKEv Yes, I didn't think of that, but it would be cool. And for 'tox:' do they think to type it and create a link?

**Comment by PKEv** [comment]
you're right, but I still doubt that this demand
Make is not difficult.
Thus it is necessary to add something to the subject of the message (like I use the qTox ;) ) ?

**Comment by TheNain38** [comment]
It could be written somewhere that they can create link using 'tox:' and 'mailto:' If 'mailto:' support would be added, evantualy.

**Comment by suhr** [comment]
@agilob Reopen this please (“mailto links support”).

**Comment by zetok** [comment]
@suhr if it's about supporting `mailto:` links without modifying user input, then I think that making a new issue would be better
