### ISSUE TITLE
Memory leak after closing main window

### ISSUE THREAD

**Issue by SmoothDude** [qTox/qTox#2308]
To reproduce this issue:
- Open your favourite task manager (to watch memory leak)
- In qTox's General settings enable these: Show system tray icon, Close to tray | Minimize to tray
- Now close main window
- Open it from system tray again
- Repeat last 2 steps above until you'll notice that memory leaks

Maybe related with: #2217

**Comment by empirebuilder1** [comment]
Can confirm in Jenkins build 144 (Revision 14235c5a19fbd3c8484ec16068ea33a72d64ff0a). Closing and opening the program steadily increases memory usage by about 400-800k each time. However, if left idle and closed for about two minutes, memory usage drops to normal.
