### ISSUE TITLE
qTox refuses to start on Windows 8.1

### ISSUE THREAD

**Issue by empirebuilder1** [qTox/qTox#2310]
Attempted to start the pre-built binary suppled by the Jenkins repo (https://build.tox.chat/view/Clients/job/qTox_build_windows_x86-64_release/), build 141. qTox starts to the profile selection page, and gets no farther. I attempted to create a new profile named "Testing123", but the program never loads, and the process disappears about 10 seconds later. Log, although it doesn't say much: http://pastebin.com/NVwSuqsr

**Comment by TheNain38** [comment]
It is because of #2309 I think, also crashes on Windows 7 64-bits

**Comment by empirebuilder1** [comment]
Thanks, latest build (144 on Jenkins) fixed the problem. It now starts as normal.
