### ISSUE TITLE
fcitx not working in qTox (from pkg.tox.chat).

### ISSUE THREAD

**Issue by quininer** [qTox/qTox#2326]
qTox (from pkg.tox.chat ) static compiled Qt, leading to fcitx-qt5 not working.
I recommend to provide a non-static compiled qTox, as well as independent toxcore package.

Non-static compiled qTox available to the user need to use input method, independent toxcore package can facilitate the use on the server, without having to compile it yourself.

I know it's not a qTox issue, but I can not find on pkg.tox.chat feedback methods.

**Comment by zetok** [comment]
@quininer from what I understood, only Qt has to be a shared lib?

**Comment by zetok** [comment]
welp, only @nurupo can make shared Qt libs builds, so right now I can't do anything.

**Comment by quininer** [comment]
Arch AUR: http://p.vim-cn.com/cchf
Debian pkg.tox.chat: http://paste.ubuntu.org.cn/3494528

**Comment by nurupo** [comment]
Well, we want our clients to work out of the box on as many distributions as possible. Some currently used distribution versions don't have Qt5 in their package repository, or they do, but it's too old for qTox, or different deb-based distributions use different dependency names for Qt5 packages, so we wouldn't be able to use the same .deb package on these distributions, we would have to make distribution-specific packages.

I guess we  could provide "qtox-shared" package, which might not always work, based on distribution and it's version, while "qtox" package will be static and work in most of the cases.

**Comment by quininer** [comment]
@nurupo  Maybe we can fcitx-qt5 static compiled into qtox.

**Comment by nurupo** [comment]
@quininer that's for qTox folks to decide whether they want to build qTox with fcitx-qt5 compiled into it.

**Comment by quininer** [comment]
ok.

**Comment by zetok** [comment]
@quininer why closing?

**Comment by quininer** [comment]
@zetok I believe they have found a solution, I should open it?

**Comment by zetok** [comment]
Well, until issue gets fixed, it should be open

**Comment by zetok** [comment]
@nurupo so what about those shared Qt builds?

**Comment by nurupo** [comment]
@zetok see https://github.com/tux3/qTox/issues/2326#issuecomment-144775975

I still haven't got any response whether the "qTox-shared" binary idea is fine with you.

It also doesn't seem right that some 3rd party input method software would work on a software dynamically linked to Qt5, but won't work on a software statically linked to it -- not even sure what is the issue with fcitx-qt5 in the first place.

**Comment by agilob** [comment]
@quininer what was your solution?

**Comment by quininer** [comment]
@agilob I propose to provide a `qTox-shared` binary.

**Comment by tux3** [comment]
We're starting to provide real Ubuntu and Debian packages, so this should be fixed Soon™

**Comment by zetok** [comment]
https://github.com/tux3/qTox/blob/deeb9b2308290e0404198a38a5d4c456ac39b328/INSTALL.md#community-builds ← could you check if it works for you?

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.

**Comment by linux0ne** [comment]
@quininer 我的系统也是14.04   现在更新到了最新版本的qtox，结果还是没有办法使用上fcitx输入法。
不知道你现在有没有解决的方案呢？可以分享一下么？

**Comment by quininer** [comment]
@linuxOne see https://github.com/tux3/qTox/issues/2326#issuecomment-215685237

**Comment by linux0ne** [comment]
@quininer 朋友，能不能用中文简章地说一下如何解决，我的英文能力很差，更多的时候，我只是linux的一名使用者而已。谢谢

**Comment by quininer** [comment]
@linuxOne http://www.mintos.org/skill/new-build-qtox.html

**Comment by linux0ne** [comment]
@quininer 
我还真不知道还有一个opensuse社区的编译版本。
它们和下面地址处的有区别么？  （这是qtox项目主页上推荐的ubuntu系统安装方式，我是按这个安装的，14.04上还是未果）
https://software.opensuse.org/download.html?project=home%3Aantonbatenev%3Atox&package=qtox

**Comment by Puzzle5** [comment]
This is still very much an issue, and I don't see why these kinds of issues get closed when it's still ongoing.

**Comment by sudden6** [comment]
@Puzzle5 We do not provide any builds via `pkg.tox.chat` so your issue is probably at least slightly different, so please open a new issue describing the problem you have now.
