### ISSUE TITLE
[Regression] When busy, qTox will not show new message circles

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#2328]
qTox used to be quiet when a message arrived when busy, and still is, which is fine.

However, somehow, qTox started to not even change to the "unread messages" circle in the friend list when receiving a new message for a conversation, making it impossible to know anyone messaged you at all when busy, even when looking straight at qTox.

**Comment by pizzamaker** [comment]
I'm having the same issue, could you please increase the priority over this?

**Comment by zetok** [comment]
Mind doing https://github.com/tux3/qTox/wiki/Testing#regression-testing ?

**Comment by zetok** [comment]
Bisect with 

bad commit:  da9157f1007dea75e6b6022c657a65d387f7d55c
good commit: 60c18d07a675759d3ef6f0ca451f31b2bb300729

points to 7bcf654c72bf3019b96284922a0428c87558efeb: 

```
7bcf654c72bf3019b96284922a0428c87558efeb is the first bad commit
commit 7bcf654c72bf3019b96284922a0428c87558efeb
Author: TheSpiritXIII <thespiritxiii@gmail.com>
Date:   Tue Jun 23 12:54:00 2015 -0400

    Multi-window: Add drag/drop friends to windows, fix call confirm widget

:040000 040000 3f2894a3f8ade15a02157cbe070fe35c1e3d4f86 51421e02c9cd6569b2ee2bd90e18cc6f1c935fd6 M  src
```

**Comment by tux3** [comment]
This is fixed, since we now don't treat busy mode any differently.
