### ISSUE TITLE
[BUG] Start with computer ineffective on LXDE/Lubuntu

### ISSUE THREAD

**Issue by hedjour** [qTox/qTox#2332]
Hi,
I have installed today qTox from the depot on a Lubuntu.
When I check the restart with computer case and reboot the computer qTox stay close.
The LXDE parameters allow autostart for application.
Have you any path to fix this problem ?
Thanks

**Comment by agilob** [comment]
It's probably better on Linux to add application manually to autostart as different desktop environment have different specification of how to auto-start application. It might be also misconfiguration of your DE not to work with "standard" .config/autostart. Anyway, thanks for reporting.

When checking 'Autostart' in settings, new file should be created in `.config/autostart`, just tried it, and for me it worked on KDE, new file was called `qTox - agilob.desktop` and it's content is correct:

```
➜  autostart  cat qTox\ -\ agilob.desktop 
[Desktop Entry]
Type=Application
Name=qTox
Exec="/home/agilob/Projects/qtox/qtox" -p "agilob"
```

Could you check if you enable autostart, the file is created under `.config/autostart`

**Comment by ovalseven8** [comment]
Just tested it with Lubuntu 14.04 and everything works for me.

**Comment by antis81** [comment]
@agilob The .desktop file will also help with integrating qTox into alternate panel (task bar) solutions like `docky` or `cairo-dock`.
