### ISSUE TITLE
Pale buttons on login window using Windows 10

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2333]
Hello,

when I used qTox on Windows 10, the buttons on the login window are pale. So it seems you aren't able to press the 'Load' or 'Create Profile' button, but actually it is possible what is also the desired behaviour.

Screenshot: 
![qtox](https://cloud.githubusercontent.com/assets/8258609/10263713/416e7fd2-69f8-11e5-9117-974ca4e7c193.PNG)

**Comment by ovalseven8** [comment]
When I look at the Screenshot with my Linux system that I'm using normally, everything seems OK. So, the display/lightness on Windows 10 is very unfavorable by default, eventually. Perhaps someone else with Windows 10 can check it and if it is too pale we should change the color a little. If everything is OK, we can close the issue and it's only a 'problem' of my specific hardware-Windows-10-interaction.

**Comment by agilob** [comment]
Can you switch to that button using Tab?

**Comment by towlie** [comment]
Doesn't it always look like this? (on windows at least)
![login](https://cloud.githubusercontent.com/assets/6986141/10276960/040ce726-6b53-11e5-97c1-e6b03b1df48f.jpg)
Your picture looks like mine.

**Comment by agilob** [comment]
Yea, that could be a bit darker green.

**Comment by ovalseven8** [comment]
> Yea, that could be a bit darker green.

Yep, we should make buttons like the above a bit darker green to avoid misunderstandings.
