### ISSUE TITLE
[Regression] Starting a second instance of qTox takes a long time (IPC needs overhaul)

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#2334]
I've noticed that recently starting a second instance of qTox is taking a long time to launch than before

**Comment by zetok** [comment]
Could you elaborate on what "long time" means?

What's the change compared to earlier versions?

Difference in seconds / minutes?

Could you do https://github.com/tux3/qTox/wiki/Testing#regression-testing ?

**Comment by tux3** [comment]
The problem could be that qTox stalls for n*5 seconds while the IPC is timing out trying to deal with the first instance.

The IPC in qTox is currently horribly broken and only "works" by pure coincidence. But that's not really new, so if you only noticed recently your problem is probably something else.

**Comment by TheNain38** [comment]
@tux3 Maybe it's just me that didn't see that earlier, and that's not a regression? Because it takes about 7 seconds

**Comment by tux3** [comment]
@TheNain38 I can't really tell without more info. Could you start a second qTox instance in a profiler or debugger and interrupt it while it's stalling so we know where exactly the problem is?

**Comment by TheNain38** [comment]
@tux3 for me with a debugger, it is waiting in
- https://github.com/tux3/qTox/blob/42659aefe8f7fd6f2299defec2edd1767cad8292/src/main.cpp#L241
- https://github.com/tux3/qTox/blob/42659aefe8f7fd6f2299defec2edd1767cad8292/src/ipc.cpp#L191

And also there is a blank window
![Blank window](https://cloud.githubusercontent.com/assets/13149763/10372233/248a24e6-6de7-11e5-8440-8a53eee1b902.PNG)

And when closing the second instance and then the first, the first proccess is not stopped because of that blank window and when closing qTox first instance, it segfault

```
[18:03:01.016] :0 : Warning: QSharedMemory::lock: already locked
[18:03:01.017] ../qTox/src/ipc.cpp:271 : Debug: Processing event:  "activate" : 1444320180 = false
[18:03:01.020] ../qTox/src/widget/translator.cpp:53 : Debug: Loaded translation "fr"
[18:03:01.020] ../qTox/src/widget/translator.cpp:61 : Debug: System translation loaded "fr"
Erreur de segmentation (core dumped)
```

**Comment by tux3** [comment]
No surprise, the IPC code is going to need just a _teeny tiny_ bit of an overhaul.

**Comment by TheNain38** [comment]
@tux3 So, this isn't a regression? It's just me that didn't see that earlier?

**Comment by tux3** [comment]
It's been this way for a couple months, at least.

**Comment by tux3** [comment]
Oh wait, found the problem.

![snapshot36](https://cloud.githubusercontent.com/assets/5155966/10374909/f79faf8c-6df5-11e5-9cdd-3b33922f0021.png)

It's just sleeping a thousand times too long because of a typo...

**Comment by benwaffle** [comment]
:laughing:
