### ISSUE TITLE
Bug, when receiving an action message, when reloading history, the sender name is displyed twice

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#2336]
Reproduce:
- Create two profile
- Send an action message to the other
- Close and reopen receiver's qTox
- See that there is the sender's name twice

**Comment by ovalseven8** [comment]
Can reproduce.

**Comment by zetok** [comment]
Can't reproduce on ef5c094417b15db67b1b8736b5153a3cd221f488, thus closing.

If it's still reproducible with newest qTox, please comment for reopen.
