### ISSUE TITLE
Implement functionality to remove avatar

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2339]
At the moment there is no functionality to remove the avatar.

Just deleted my avatar for testing purposes directly in my .config/tox/avatars.
Worked, _but_ the friends can still see my old avatar. Only if they restart qTox it is updated. How should qtox handle it? Update immediately or after restart is enough?

**Comment by agilob** [comment]
Does toxcore allow nulling avatars?

**Comment by zetok** [comment]
Well, since toxcore treats avatars as file transfers, it's up to clients to do that, so if they comply with STS, they would remove it: https://github.com/Tox/Tox-STS/blob/master/STS.md#avatars
