### ISSUE TITLE
ID is obscured

### ISSUE THREAD

**Issue by mouseym** [qTox/qTox#234]
The ID box is partially obscured, resizing the window in either direction does nothing.

![qtox](https://cloud.githubusercontent.com/assets/5054853/4171500/d2255708-353d-11e4-9e69-61d2c9cbbed2.png)

**Comment by tracker1** [comment]
On a similar note, what does one need top copy to have the same ID on more than one system?

**Comment by tux3** [comment]
@tracker1 You need to copy a file called "data", it's in a folder called "tox" but I don't remember where exactly it is on OSX.

You could try typing "locate tox/data" in a terminal to get the exact path.
