### ISSUE TITLE
Tox disapears after logout and login again on ubuntu with all ticks set in system tray section

### ISSUE THREAD

**Issue by programizer** [qTox/qTox#2342]
If I have all ticks set in the system tray settings section.
Then I click the my profile name.
Scroll down to log out.
Log in again.

-> There's no way to see tox window, because neither left nor top-right corner a symbol anymore.
-> Have to kill process and restart.

**Comment by zetok** [comment]
Which DE are you using? Unity?
If so, are you using `qtox-unity` ?

**Comment by agilob** [comment]
Do I understand it? when you logout, qtox process should be killed, when you login, it shouldn't start unless you have autostart enabled. Could you reproduce it and give us log from starting qtox after logout? This might be related to  #1485 or something new.

**Comment by zetok** [comment]
@agilob I think that @programizer meant "Logging out" in qTox via profile page

**Comment by programizer** [comment]
@zetok Yes, I am using qtox-unity. (And yes I meant logging out via profile page.)
I think, what's really going on (the real problem) is the following:  
- After logging out the qtox **symbol disappears from the ubuntu system tray**.
- After logging in it **doesn't reappear** again as it should.

**Comment by sudden6** [comment]
Is this still an issue?

**Comment by sudden6** [comment]
No response, closing.
