### ISSUE TITLE
No tray icon in Plasma 5

### ISSUE THREAD

**Issue by Jacobtey** [qTox/qTox#2347]
There isn't qtox icon in system tray in Plasma 5.

**Comment by zetok** [comment]
@Jacobtey mind supplying more info about your environment, since issue seems to affect only you (i.e. other plasma 5 users didn't have this issue so far)?

If you could, please refer to https://github.com/tux3/qTox/wiki/Writing-Useful-Bug-Reports

Also, are you sure that you have enabled tray icon?

**Comment by Jacobtey** [comment]
Yes, I'm sure. I've used qtox and qtox-qt5.4.2 packages. No tray icon both black and white. I've tried them in kubuntu vivid vervet than upgraded it to wily beta2. No effect as well. Now I've got Kubuntu 15.10 beta2: plasma 5.4.2 qt 5.4.2 kde framework 5.14.0. Everything works correctly except qtox tray icon. What info else should I give?

**Comment by agilob** [comment]
@zetok can he test this? https://github.com/tux3/qTox/pull/2132#issuecomment-143035753

@Jacobtey you're probably missing statusnotifier now, the PR above removes SN dependency for KDE.

**Comment by Jacobtey** [comment]
Ok, what should I do? Is there tutorial? Starting qtox in konsole gets "Warning: No system tray detected!"
If "in KDE5 qTox will use Qt backend instead buggy status-notifier" why missing statusnotifier is a problem for me?

**Comment by zetok** [comment]
@agilob yep

@Jacobtey could you test 
https://build.tox.chat/job/qTox-testing_build_linux_x86-64_release/13/artifact/qTox-testing_build_linux_x86-64_release.tar.xz
and
https://build.tox.chat/job/qTox-testing-qt5.4.2_build_linux_x86-64_release/15/artifact/qTox-testing-qt5.4.2_build_linux_x86-64_release.tar.xz
?

**Comment by Jacobtey** [comment]
@zetok I'll try to package them tonight and give U feedback later. Thanx

**Comment by zetok** [comment]
@Jacobtey you don't need to package anything - just unpack and run it

**Comment by Jacobtey** [comment]
[19:58:10.666] src/widget/widget.cpp:1720 : Warning: No system tray detected!

**Comment by agilob** [comment]
Did you get this from the first archive?

**Comment by Jacobtey** [comment]
From both.

**Comment by agilob** [comment]
What is your distribution, version of plasma?

**Comment by zetok** [comment]
> What is your distribution, version of plasma?

um.

> Now I've got Kubuntu 15.10 beta2: plasma 5.4.2 qt 5.4.2 kde framework 5.14.0.

**Comment by agilob** [comment]
Ym... could you try `./simple_make.sh` from qtox directory?

**Comment by Jacobtey** [comment]
From qtox directory? Where is it?

**Comment by agilob** [comment]
```
git clone git@github.com:tux3/qTox.git
cd qTox
./simple_make.sh
```

**Comment by Jacobtey** [comment]
jacobtey@jacobtey-laptop:~$ git clone git@github.com:tux3/qTox.git
Клонирование в «qTox»…  
The authenticity of host 'github.com (192.30.252.130)' can't be established.  
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.  
Are you sure you want to continue connecting (yes/no)? yes  
Warning: Permanently added 'github.com,192.30.252.130' (RSA) to the list of known hosts.  
Permission denied (publickey).  
fatal: Could not read from remote repository.                                                                                                                                         

Please make sure you have the correct access rights  
and the repository exists.

**Comment by agilob** [comment]
Ymm ok, you must:
1. add you ssh publick key to your github account or 
2. `git clone https://github.com/tux3/qTox.git`

**Comment by zetok** [comment]
heh, so I did remember correctly that there was an issue about it, and that this is a duplicate → #1353

Since it's a dup, closing.

@Jacobtey um, could you give reply about what @agilob asked in #1353 ?
