### ISSUE TITLE
Copy friend ID no worky properly

### ISSUE THREAD

**Issue by mouseym** [qTox/qTox#235]
Audiobotze's ID according to toxme.se:  BF9A09F70D6C0C3424472B740E9F70878A72CECCB30AC396D60D8160BB6C2E22E6EA2917FFE2

Audiobotze's ID according to copy friend ID: 
BF9A09F70D6C0C3424472B740E9F70878A72CECCB30AC396D60D8160BB6C2E22

**Comment by tux3** [comment]
The problem is that Toxcore doesn't remember the full address (ID+Nospam+Checksum), just the ID, so I have to build a separate database of friend IDs instead of just the tox_save.

Note that you'll need to re-add your friends so that Copy Friend ID can learn their full address. If the full address isn't found, it'll just give you the id (like it does now).

Since that's the second time someone reports that, I'll fix it right now. Expect a fix in ~15 minutes.

**Comment by zetok** [comment]
I don't see what it "fixes".

@mouseym You realize that what qTox gave is correct public key?

Perhaps it's a bit wrongly named, but nonetheless it is a correct public key of audiobotze.

Clients are **supposed** to offer a way of changing `nospam`, and there is no way, nor will be, to announce changed `nospam` to to friends.

It means, that if you'll save anything except for public key from Tox ID, and your friend changes `nospam`, currently you'll only get not working, 76 long string of characters.

@tux3 Be prepered for users' question regarding why they have this long string of chraracters, and how come so that it doesn't work, and why only part of it is valid.

Anyway, whole "idea" of being able to just "copy" friend's Tox ID to add it in other Tox instance is dumb and won't work.

**Comment by tux3** [comment]
@zetok I agree with you, except that people seem to be expecting it to work this way. And if someone changes it's nospam on purpose, then maybe it's his job to explain to his friends while they can't add him anymore ?
I'm not seeing a better solution that doesn't involve removing the "copy friend id" feature completely.

**Comment by zetok** [comment]
> I'm not seeing a better solution that doesn't involve removing the "copy friend id" feature completely.

Um, that's what I would like to suggest :3

Thing is, user shouldn't be really encouraged to copy Tox ID from client to client, but there should be a way for user to check friends' public key.

IMHO best approach would be to morph `Copy ID` into `Show public key`, and after clicking `Show public key` there would be pop-up window with public key, and something like question mark somewhere, which would lead to explanation of how things are supposed to work, and why copying public key from client to client isn't supposed to work.

As things are now, being able to "copy" only seems to confuse users, and create problems.

So real solution would be to either fully remove that functionality, or to morph it into `Show public key`

Disclaimer: it actually should be thought of really carefully, and what is more important, properly designed.

What I'm trying to point out is that currently qTox encourages misleading, incorrect and simply broken way of doing things for users, and that's the real issue that should be addressed ASAP, so they don't get used to broken way of doing things and won't be expecting broken way to actually work (as they already do).
I.e., please, don't provide horrible UX.
Furthermore, please don't actually fix "problems" that users have with broken way of doing things, but rather address thing that encourages wrong way of doing things.

**Comment by msteinbeck** [comment]
+1

**Comment by tux3** [comment]
I like the Show pubkey popup. I'm not sure if we should remove the ability to remember the nospam+checksum, maybe a warning that "this is the last known key but your contact could have changed it" or something ? Changing the nospam isn't something I'd expect people to do often, I doubt many people will try to spam friend requests. But I could be wrong, of course.

Or a lengthy explanation of how pubkeys and nospams work ?

Or just the pubkey, like before, and rename "Copy Friend "ID to "Copy public key" ?

**Comment by zetok** [comment]
One of main things that make it a problem is word "copy". It in itself implies that you can reuse what you're copying for something else, whereas "show" doesn't necessarily imply that.

> this is the last known key but your contact could have changed it

Still leads to confusion (why it simply doesn't show correct one, is it broken?).

I'm afraid that changing nospam may be the only way of actually fighting against real **spam** friend requests, where some entities would dig through DNS records for Tox IDs, and them spam those with friend requests to advertise Viagra, or something equally desired by Tox users. It wouldn't be people spamming other people, but simply bots.

So.. expect it to happen often.

About "explanation part" I thought of making something like:
* after clicking on `?`/`halp` button in "Show Public Key" window *

```
Why can't I just copy it to other client?
Tox ID isn't just a Public Key, in fact:
Tox ID = Public Key + Nospam + Checksum
  76   =     64     +    8   +    4
Only Public Key doesn't change and is needed to communicate.
Nospam and Checksum can be changed by your friend at any time, and since they're used to prevent spam friend requests, there's no way to know what is their current value.
```

Perhaps adding to ↑ :
If you **need** to have your friend's current Tox ID, you can always ask for it, or bug your friend to update entry on toxme.se if (s)he doesn't have it updated.

Regarding "additional" part, client integration with toxme.se should allow to offer an option to automatically update Tox ID after user changes nospam, so it shouldn't be a problem.

**Comment by tux3** [comment]
Perhaps when adding someone with a toxme.se address, this function should return the toxme address instead of the Tox ID for convenience.

**Comment by zetok** [comment]
Currently there is no way of telling if what toxme.se returns is still a correct (actual) Tox ID, nor will it be possible in the future, so.. it still seems to me like "Copy Tox ID" is a bad thing.

**Comment by mouseym** [comment]
how about an option to export a contact? 
write it to a simple json file with three different values, id, id + nospam + checksum and toxme?

actually, it would be nice if all clients could import/export in this sort of format and then they can choose which value to import

**Comment by tux3** [comment]
Yeah, but it's still the same probblem. The ID itself is useless, the nospam isn't guaranteed to be good,  and the toxme.se could be wrong too.

But I agree that Contact Import/Export would be nice.

**Comment by msteinbeck** [comment]
In most cases the expected ID should be the current ID.

**Comment by msteinbeck** [comment]
I think this one can be closed?!?!

**Comment by zetok** [comment]
@retuxx ? why?

**Comment by msteinbeck** [comment]
As I can see the copy Tox-ID button returns the current public key with the expected no-spam value. By concept of toxcore there is no other solution for this.

**Comment by zetok** [comment]
@retuxx Yes. It returns **public key**. Not **Tox ID**.

**Comment by msteinbeck** [comment]
Maybe I misunderstand you, but when I copy the "ID" of (for example) Groupbot, I'm able to re-add him with this ID. The copied ID has 76 digits which is the size of a regular tox ID.

**Comment by zetok** [comment]
@retuxx try to copy from friend that sent you FR, not the other way around

**Comment by msteinbeck** [comment]
Ok, thats something I didn't notice. But there is no solution for this. Contact export/import is just another step for updating the tox.me entry or to resend the ID itself.

**Comment by agilob** [comment]
Toxcore issue. https://github.com/irungentoo/toxcore/issues/1300

**Comment by zetok** [comment]
@agilob actually, this is not a toxcore issue. It's an issue with qTox providing broken functionality.

Thing is, toxcore is not going to provide IDs of friends, and it's like that purposely.

It's up to qTox to not provide broken things that are not going to work. → reopening.

**Comment by ovalseven8** [comment]
https://github.com/tux3/qTox/pull/434

**Comment by ovalseven8** [comment]
Would also change the naming -> https://github.com/tux3/qTox/pull/434

**Comment by ovalseven8** [comment]
Well, I like @zetok's suggestion: https://github.com/tux3/qTox/issues/235#issuecomment-54132957
In my mind, it would be enough and no additional toxcore implementation is needed.

So, a '**Show** public key'-window with further explanations how the things work were fine.

**Comment by zetok** [comment]
Since it was removed in 21ab9088b3bb31ec2a6ea7f02ab395f94b20f929, closing.

Showing / copying PK of friend is a separate issue → #2236
