### ISSUE TITLE
Webcam doesn't switch off after ending a videocall

### ISSUE THREAD

**Issue by Jacobtey** [qTox/qTox#2351]
Windows 10 ASUS K43S
Kubuntu 15.10 Acer Aspire 4720Z
1. Start qTox
2. Open tab "Audio/Video"
3. Choose Video device - Webcam LED lights
4. Out from tab "Audio/Video" - Webcam LED goes out
5. Start videocall - Webcam LED lights - Webcam works
6. End videocall - Webcam LED still lights - Webcam window is out

**Comment by ovalseven8** [comment]
Priority 'medium' at least.
But perhaps closable when https://github.com/tux3/qTox/pull/2093 gets merged?

**Comment by zetok** [comment]
It's partially a toxcore problem - some of it was qTox fault, and is fixed in #2370, rest will depend on new A/V API PR: https://github.com/irungentoo/toxcore/pull/1375

**Comment by mannol** [comment]
toxcore has nothing to do with webcam.

**Comment by agilob** [comment]
@Jacobtey  please test current version and tell us it that can be closed, if not, which client was used on the other side?

**Comment by Jacobtey** [comment]
@agilob , should I compile it from git or upgrade from ppa?

**Comment by zetok** [comment]
@Jacobtey not sure how quickly new builds propagate to the repo, but you it shouldn't take longer than a day for it.

btw, it's not a PPA `:)`

**Comment by Jacobtey** [comment]
Tried Jenkins' nightly build for windows. Webcam works only if webcam settings tab is open.
Linux version will be tried tonight

**Comment by agilob** [comment]
Still an issue?

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.
