### ISSUE TITLE
show the last correspondence history

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#2352]
Now history is displayed in the last 7 days, 
I think it would be useful if there is no history in the last 7 days of the show At least the last 5 posts (or the number selected by the user)

**Comment by zetok** [comment]
Yeah, 5 last messages being shown if there were no messages in last 7 days sounds good to me.

**Comment by ovalseven8** [comment]
@TheSpiritXIII's PR will change the current behaviour, anyway.

https://github.com/tux3/qTox/pull/2013:

> Chats always load with some history no matter how far back it was (previously, it would load history up to 7 days back). History is loaded by amount instead of days so it never loads too much or too little.

**Comment by zetok** [comment]
oh, right

**Comment by sudden6** [comment]
This is implemented now.
