### ISSUE TITLE
There are 2 emoticons in TwitterEmojiSVG that use `^_^` - which one should keep it?

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#2358]
https://github.com/tux3/qTox/blob/3e75fd4dbc5dc623553ba255fed17c8f98258693/smileys/TwitterEmojiSVG/emoticons.xml#L25,L27
and
https://github.com/tux3/qTox/blob/3e75fd4dbc5dc623553ba255fed17c8f98258693/smileys/TwitterEmojiSVG/emoticons.xml#L51,L53

Those are very similar - anyone, any thoughts on this?

**Comment by ghost** [comment]
#L51,L53 is more like it.

**Comment by agilob** [comment]
Which one is used now then you type the emoticon? I think we should stay with the one which is printed now.

**Comment by zetok** [comment]
![currently used](https://cloud.githubusercontent.com/assets/3148759/10363909/56dbf1e6-6daf-11e5-8224-822b97c626b6.png)
