### ISSUE TITLE
File transfer crash. Zetok.

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#236]
https://gist.github.com/zetok/8b2373d81f52b5243f48

**Comment by tux3** [comment]
I have no idea what's happenning but here are some possibilities:
- Bug in Qt. Unlikely, but if that's the problem, I'm wasting my time
- malloc failed, perhaps the stars weren't aligned, or we were spamming allocations of 1371B without enough freeing, and memory fragmentation killed us. Still unlikely, especially the fragmentation part, if all the chunks are 1371B, then fragmentation from ourselves wouldn't be a problem, it's a perfect fit, and I doubt others are spamming chunks smaller than 1371B.
- Malloc failed silently and gave us a bad pointer because the heap was corrupted and nobody noticed. Unlikely as fuck, surely someone would have noticed and reported a corrupted heap when we malloc'd the data, not in the memcpy
- read failing, perhaps the QFile was corrupted in such a way that we managed to seek(), and get to this point, but read would crash. Still unlikely as fuck.
- Multithreading fail : We're not reentrant and not even thread safe, if someone decided to tinker with the file in another thread, this could have killed us. This is the best I can come up with, and it's consistent with the fact that nobody can reproduce, this is a rare race condition.

**Comment by tux3** [comment]
I still can't reproduce.

**Comment by zetok** [comment]
Probably should be closed, and if ever reproduced, could be reopened.
