### ISSUE TITLE
Can't start a second instance

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#2360]
@tux3 Why waiting less make qTox not able to start a second instance? 59e06920692a5966645bf60baa8753f440842651

Is the timeout too low?
https://github.com/tux3/qTox/blob/59e06920692a5966645bf60baa8753f440842651/src/ipc.cpp#L192

**Comment by agilob** [comment]
you can start second instance with `./qtox -p profile`

toxcore isn't designed to handle two the same IDs in the network.

**Comment by TheNain38** [comment]
@agilob Yes, because it doesn't use IPC when qTox is started like that, but the other one is.

**Comment by agilob** [comment]
Well, than it works for me. I am able to start two profiles without any problem.

**Comment by TheNain38** [comment]
@agilob Well on my case it doesn't work with Virtualbox with guest O.S. lunbuntu, I will test on my second machine when I have access

**Comment by tux3** [comment]
@TheNain38 It should still work the same way, it's sleeping in a loop so how long it sleeps shouldn't matter.

If it's freezing, can you take a backtrace of where it's stuck and post the log?

**Comment by TheNain38** [comment]
First I start one qTox instance and then a second, the second terminates and then a blank window is open.
- Here is the backtrace when first qTox instance receive a `SIGSEV` because I close the blank window: https://gist.github.com/TheNain38/7e29f062713834af0ed8#file-backtrace-virtualbox-lunbuntu
- And here is the call stack: https://gist.github.com/TheNain38/b24c17fff8d1853e94ae#file-call-stack

**Comment by zetok** [comment]
Can reproduce with:

``` bash
mkdir new_home && \
cd new_home && \
HOME="$PWD" qtox
```

`git bisect` with
bad commit: b0647b0b4bcda0ff4ebd01017ab2261b0b9ad24a
good commit: 9a47a88125bc9ebb7054dcbff6e391ae6514579c

points to 59e06920692a5966645bf60baa8753f440842651

```
59e06920692a5966645bf60baa8753f440842651 is the first bad commit
commit 59e06920692a5966645bf60baa8753f440842651
Author: tux3 <barrdetwix@gmail.com>
Date:   Thu Oct 8 19:53:44 2015 +0200

    Sleep 10ms in IPC wait loop, not 10 SECONDS!

    Fixes #2334

:040000 040000 d5f4df647075ac39981087bb5c8a1aaa8c906d26 99735362a84cbeaba68fcf3fe864d725f9b06f75 M  src
```

**Comment by zetok** [comment]
And reverting 59e06920692a5966645bf60baa8753f440842651 fixes this issue.

**Comment by antis81** [comment]
@zetok, @tux3 Could you check with #2383? This PR will not fix the issue directly, but fixes some major problems in IPC class.

**Comment by zetok** [comment]
#2383 didn't fix it for me

**Comment by antis81** [comment]
@zetok Like I said, it will not fix this issue, but put things into place. The problem with `-p $profile` parameter is a different one. Could you please check, if that works with the **10 seconds** sleep in line 192 -> `QThread::sleep(10)`? If so, I'll look up the real problem and fix it as well.

**Comment by TheNain38** [comment]
@antis81 With `QThread::sleep(10);` it works

**Comment by antis81** [comment]
Thanks @TheNain38! I'll look up the problem and fix it.

**Comment by TheNain38** [comment]
Please reopen, for me it works but only when a profile is loaded if you try to open two instances with the first one on the login screen then it segfault and the second terminates with error code `0`

**Comment by antis81** [comment]
Yeah, I've noticed this behaviour. It's not the same thing though. The issue discussed here is solved. Feel free to open new one.
