### ISSUE TITLE
qTox doesn't save received messages when they're received <5s before closing qTox

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#2362]
OS: Hardened Gentoo Linux x86_64
FS: ext4
sqlite: `3.8.10.2`
qTox 6e0c0d1210847b0e767e8a01f8d3a4903f238244

Steps to reproduce:
1. Start qTox
2. Add spambot - `C7719C6808C14B77348004956D1D98046CE09A34370E7608150EAD74C3815D30C8BA3AB9BEB9`
3. wait for spambot to come online
4. send a message and close qTox <5s (spambot will send back message, just before closing qTox you should receive it)

Reproducible: Always

This has been the case the for quite some time - _IIRC_ from testing, qTox even right after switch to ffmpeg was affected by it. I'm not sure whether this is a regression or not.

**Comment by agilob** [comment]
![weblate10](https://cloud.githubusercontent.com/assets/2544251/10387241/bead7788-6e57-11e5-8bd9-b67c3d127069.png)

**Comment by zetok** [comment]
Yes.

**Comment by agilob** [comment]
Does that mean that SQLite decides when to commit data to file? If so, DB should be committed before closing qtox on every logger level.

**Comment by tux3** [comment]
Fixed by the new SQLCipher database code in master.
