### ISSUE TITLE
Gdk: (No space left on device)

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#2366]
```
(qtox:1270): Gdk-WARNING **: shmget failed: error 28 (No space left on device)
```

I have 10GB on / and 45Gb on /home left.

**Comment by Zer0-One** [comment]
@agilob shmget() acquires shared volatile memory. your filesystems probably don't have any bearing here.

**Comment by zetok** [comment]
> shmget failed

So it tried to use shared memory - i.e. probably either `/tmp` (which is mounted by systemd as tmpfs) or /dev/shm ..

Could you see which one of your mounted fs has no ~~memory~~ space left?

**Comment by agilob** [comment]
`/tmp` is under `/`, I have two partitions.
![weblate11](https://cloud.githubusercontent.com/assets/2544251/10410025/ac8165bc-6f2c-11e5-96e0-0cbaa99dcde3.png)

**Comment by zetok** [comment]
> `/tmp` is under `/`, I have two partitions.

Yes, and since you're using Arch, which uses systemd, `/tmp` is mounted automatically as tmpfs - unless you explicitly disabled that, which I assume is not the case?

**Comment by agilob** [comment]
ok, I didn't know that.
