### ISSUE TITLE
OS X not working (not connecting to DHT)

### ISSUE THREAD

**Issue by Tamriel** [qTox/qTox#237]
After adding a friend, nothing happens. He is shown offline, although he is online. Can anybody confirm qTox is working on OS X right now?

**Comment by tux3** [comment]
Are you shown online ? (is the dot near your name green and not red ?)

**Comment by Tamriel** [comment]
On startup, it's red, but then I click on it to go online. Then it's green.

**Comment by tux3** [comment]
You shouldn't do that. There is no "safeguard" in qTox yet, but when you do that it doesn't actually do anything. It should become green on it's own, or else it means your computer couldn't connect to the Tox network.

If you try restarting and not touching the red circle, does it go green eventually ?

**Comment by Tamriel** [comment]
I waited 10 minutes, it did not turn green.

**Comment by tux3** [comment]
Ok, I'll be working on a fix. Thanks for reporting the bug.

**Comment by dubslow** [comment]
@Tamriel, it's probably worth trying again after that commit -- but you'll need to delete your settings.ini file for the change to take effect.

I can't say for sure if it will help or not, but I believe it will.

**Comment by Tamriel** [comment]
I can't find that settings.ini file.

**Comment by dubslow** [comment]
I believe it's in $HOME/.config/tox.

**Comment by Tamriel** [comment]
It's not :/

**Comment by mouseym** [comment]
Looks like this bug is being reported more and more often.

It certainly works for me on 10.9.4, initially it took a long time to connect but after that one time it now connects immediately each time i start qTox.

**Comment by davydotcom** [comment]
We had a one direction connection issue. I sent a request, It was received but user was not shown as online nor could we communicate. We dropped the request and he requested me. He got a "Error while looking up DNS" error. Then finally it just kicked in.

**Comment by tux3** [comment]
This should be fixed in the latest qTox.

**Comment by mouseym** [comment]
connects almost immediately now, can't seem to successfully add groupbot or audiobotze however, groupbot is reported to be online by others...

Edit: no longer connects to the network... :(

**Comment by zetok** [comment]
@mouseym audiobotze was mostly offline due to constant crashes, sorry

**Comment by Tamriel** [comment]
Any progress on this? 
I still can't find my settings.ini.

**Comment by tux3** [comment]
The settings.ini should be in "~/Library/Preferences/Tox"

**Comment by Tamriel** [comment]
Thanks! I deleted that folder. Tox still does not connect for me (version of today).

**Comment by mouseym** [comment]
Still an issue alright.

Note - Won't connect on either my home connection or tethered off my phone, both worked fine before.

**Comment by zl4bv** [comment]
I am running the binary from Jenkins build 163 (ToxGUI OS X) and it is failing to connect to DHT. The red circle appears next to my name and has done for the past hour (after restarting my Mac too). Is it possible I'm experiencing an issue with NAT?

Is there a logging function in qTox I can enable to find more info?

**Comment by dubslow** [comment]
Unfortunately, qTox doesn't have logging-to-file capability yet. If you start it with a Terminal, there are some messages logged to stdout/stderr, but I doubt you'd see anything we don't already know (which unfortunately, isn't much). Having said that, it certainly wouldn't hurt if you posted what qTox spits to terminal.

At this point, none of us really knows why DHT doesn't work on OS X, but it does work on Linux (but much slower than previously). The most helpful thing would be if somebody could step through it with a debugger...

**Comment by zl4bv** [comment]
Here's the stdout/stderr when I run it:

```
$ ./qtox.app/Contents/MacOS/qtox 
Settings: Loading from  "/Users/ben/Library/Preferences/tox/settings.ini"
Using embeded bootstrap nodes list
"Error loading translation en"
Core starting with IPv6 disabled. LAN discovery may not work properly.
Core: Connecting to the DHT ...
"Core: Bootstraping from aitjcize, addr 54.199.139.199, port 33445"
"Core: Bootstraping from astonex, addr 37.59.102.176, port 33445"
"Adding friend with id <redacted>"
"Adding friend with id <redacted>"
Core: Connecting to the DHT ...
"Core: Bootstraping from nurupo, addr 192.210.149.121, port 33445"
"Core: Bootstraping from mousey, addr 37.187.46.132, port 33445"
Core: We're having trouble connecting to the DHT, slowing down
"Core: Bootstraping from Proplex, addr 107.161.17.51, port 33445"
Core: We're having trouble connecting to the DHT, slowing down
"Core: Bootstraping from SylvieLorxu, addr 178.21.112.187, port 33445"
```

I still suspect a NAT issue with toxcore. When I did a packet capture and started qTox I could see outgoing UDP traffic to bootstrap nodes but responses never came back in.

**Comment by mouseym** [comment]
Yeah, it does seem like a toxcore issue, i'll try Venom tonight and see if that connects.

**Comment by dubslow** [comment]
Excellent. Though stdout proved as useless as I assumed, no one's gotten around to packet sniffing... hopefully we can get this resolved soon, this is the first lead we've had.

**Comment by tux3** [comment]
Ipv6 being disabled is strange too, it only does that on osx afaik.

**Comment by zl4bv** [comment]
I manually disabled IPv6 when I was trying to get it working. Not aware of it disabling IPv6 by itself.

**Comment by tux3** [comment]
If someone could upload a .pcap of qTox failing to connect to the DHT, it would help a lot.
Unfortunately I can't reproduce this bug on any of my computers.

**Comment by mouseym** [comment]
i updated my toxcore just now, installed it, booted up venom

it connected instantly and i was able to add groupbot as a friend fairly quickly, looks like it's not a core issue

**Comment by mouseym** [comment]
here is what i've filtered out from Wireshark
please no hack

http://vps48388.ovh.net/tox/qTox.pcapng

**Comment by tux3** [comment]
> please no hack

Well, I won't try anything funny, but you just posted it publicly on the internet. If you were doing something sensitive like connecting to your bank account at the same time you might want to remove that file.

**Comment by mouseym** [comment]
it's filtered :)

**Comment by tux3** [comment]
There are only 10 packets in that pcap, in 10 seconds !

Are you sure you filtered it correctly ?

It tries to connect to aitjcize (54.199.139.199) on the wrong port (42370 instead of 33445) over TCP and fails hard, then tries two different IPs over both TCP and UDP once, also on the wrong ports (42370 instead of 33445).

Also noteworthy is that for UDP, the source port is 33445 (that should be the dest port!), so either that's intended or source and dest ports are somehow inverted.

**Comment by mouseym** [comment]
those are the filtered packets (filtering on TCP/UDP port 33445)
yes, it seems to be connecting on some random ports (42370) being one of them

**Comment by tux3** [comment]
42370 is 33445 with the endianness inverted.

Could you fitler to include both 33445 and 42370 ?

**Comment by mouseym** [comment]
i'll upload the packet capture for qtox and venom, these are both over the same time period roughly, there is a large difference in packets received between the two (again, filtering on 33445)

**Comment by mouseym** [comment]
http://vps48388.ovh.net/tox/

Venom's packet capture was left a couple of seconds longer (5 or so).

**Comment by mouseym** [comment]
sorry, i didnt read your other comment, i'll include 42370

**Comment by tux3** [comment]
I'm trying something, please test the following commit.

It does something really stupid, but maybe it'll help.

**Comment by mouseym** [comment]
http://vps48388.ovh.net/tox/qTox2.pcapng

**Comment by tux3** [comment]
Is that from the latest commit ?

**Comment by mouseym** [comment]
nope, waiting on jenkins, will let you know in a bit

**Comment by dubslow** [comment]
This is the issue 

https://github.com/irungentoo/toxcore/commit/7557b92fc9699e0c762e627f97b4d997506ddedf

**Comment by tux3** [comment]
I FUCKING KNEW IT

**Comment by dubslow** [comment]
lol

**Comment by tux3** [comment]
I can't believe it worked with the ports in the wrong order ! And it's been working like this for the past month!

**Comment by mouseym** [comment]
it werks, hurrah!

**Comment by dubslow** [comment]
https://github.com/tux3/qTox/commit/18f0e05778a1eb599db3ca7a3bbb504f4f773bce

Should have read the upstream patch notes more closely :)

**Comment by zl4bv** [comment]
Thanks, folks! I can confirm it is working :)
