### ISSUE TITLE
Why does prefixing a message with '>' turn it green?

### ISSUE THREAD

**Issue by Aralun** [qTox/qTox#2372]
When I send a message prefixed with `>` it turns green.

```
> For example, this will be green.
```

Why is that? Is there any other pretty colours shortcuts out there? I've tried a bunch of other prefixes :

```
&"#'{([)]-|`_\\^^$ù*µ%£¨€,;:!§/? 
```

to no avail.

**Comment by zetok** [comment]
It's quoting.

**Comment by agilob** [comment]
tox is (was?) a 4chan project.

**Comment by zetok** [comment]
> tox is (was?) a 4chan project.

Was.

**Comment by zetok** [comment]
@Aralun if that answers your question, could you close the issue?

**Comment by Aralun** [comment]
It perfectly does, thanks!
