### ISSUE TITLE
Should be able to load chat history by date range, and search through whole history (not loaded).

### ISSUE THREAD

**Issue by dimgel** [qTox/qTox#2377]
Hi. Currently qTox looks all great except history view.

If I don't remember the day (or month, or even year) conversation happend on, I would never find it - loading history day by day is hell. Skype/linux, for example, can load history for last day/week/month/year or whole into memory, but it would be more convenient to allow user specify both boundary dates of loaded range. For example, if whole history is too large to fit into RAM but I need to find some ancient conversation, I may load it year by year to look through.

There should be ability to search through loaded history (case-insensitively, or with case sensivity option). Also, it would be absolutely fantastic to be able to search through whole history (or date range) without loading it into RAM.

**Comment by zetok** [comment]
Searching loaded history is implemented in #2013.

Thus, issue is about:
- ability to load history by date range
- ability to search through whole history

**Comment by dimgel** [comment]
Weird, nothing happens for me when I press Ctrl+F in chat window (non-empty, containing some messages) or anywhere. Also didn't find any clue about it; there should be some button or context menu item.

gentoo/amd64

**Comment by zetok** [comment]
> Weird, nothing happens for me when I press Ctrl+F

Well, #2013 is not merged yet

**Comment by dimgel** [comment]
Ah, sorry. :)

**Comment by sudden6** [comment]
Search is implemented, second issue moved to:  #5501
