### ISSUE TITLE
After 'Multiple window mode' -> Contact list too wide

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2378]
Reproduce:
1. Go to the settings
2. Activate 'Multiple windows mode'
3. Deactivate 'Multiple window mode'
4. Maximize window
   => Contact list is too wide

![Screenshot](https://cloud.githubusercontent.com/assets/8258609/10416194/14a532ec-700c-11e5-9d40-b82f60bc6c78.png)

**Comment by ghost** [comment]
Can reproduce in Cinnamon. The modified friend list width is noticeable even before maximising.

**Comment by zetok** [comment]
Can't reproduce on 7b90ed1abba3023c2ead1e596a053f11b4ed8fd8 any longer, thus closing.

If it's still reproducible, please comment for reopen.

**Comment by ghost** [comment]
Nope, still there in 7b90ed1abba3023c2ead1e596a053f11b4ed8fd8 for me.

**Comment by alexeysvrv** [comment]
And me

**Comment by sudden6** [comment]
still an issue at 76c4cf7d390ece3d0ec57b771fb9aaa21f7337f7

**Comment by Diadlo** [comment]
For someone, who want to start from this issue:
1. Try to find settings, related with multiple window mode
2. Find notify signal for this settings
3. Find slots subscribed to this signal
4. Find place, where splitter state is loaded
5. Move/copy splitter loading to the slot

Also, better create different settings to window geometry of splitter window and non-splitted

If you have any question, you can write ask here
