### ISSUE TITLE
Singular form '1 minute' instead of '1 minutes'

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2379]
Just a small issue:

At the moment there is only the plural form:
![Screenshot](https://cloud.githubusercontent.com/assets/8258609/10416199/76c1b8e2-700c-11e5-8be8-98f8eb31dc26.png)

~~1 minutes~~
**1 minute**

**Comment by agilob** [comment]
Won't fix because in Polish that would be:

1 minuta
2 minuty
3 minuty
4 minuty
5 minut
6 minut
... minut
22 minuty
30 minut

that would require a library or something bigger just to operate on one word.

**Comment by ProMcTagonist** [comment]
The only option seems to be minutes. So take the word out of the box and put it before the colon. That's acceptable in English:

`Auto away after (0 to disable) minutes: 1`

Is that acceptable in other languages too?

**Comment by agilob** [comment]
We had `x min` before but someone else complained about it.

**Comment by ProMcTagonist** [comment]
Why?

**Comment by TheNain38** [comment]
@agilob I think `x min` is better because it doesn't need any translation and is universal. What was the complaint?

**Comment by ProMcTagonist** [comment]
> doesn't need any translation

Even in non-latin languages?

**Comment by TheNain38** [comment]
@ProMcTagonist Err... I don't know, but the [**SI**](https://en.wikipedia.org/wiki/International_System_of_Units) symbol of `minute` is `min`

**Comment by TheNain38** [comment]
@ProMcTagonist Yes, they don't need any translation even in [non-latin languages](https://en.wikipedia.org/wiki/International_System_of_Units#Chinese_and_Japanese),
I think this issue should be reopened and renamed to `Use 'min' instead of 'minutes' in settings`, and using `x min` would fix this issue.

**Comment by ProMcTagonist** [comment]
+1 for x min

**Comment by TheNain38** [comment]
Done a pull request to fix that
