### ISSUE TITLE
Use indentation in qTox Settings

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2380]
Hello,

another minor issue:
Use identation in the qTox Settings to improve readability and clarity.

So, I would indent 'Open each chat in an individual window' because it is a subitem of 'Multiple windows mode'. 
![Screenshot](https://cloud.githubusercontent.com/assets/8258609/10416218/75201078-700d-11e5-8ad5-71f28da78027.png)

**Comment by zetok** [comment]
Since #2386 is merged, closing.
