### ISSUE TITLE
One style, two names in General Settings

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2381]
In the General Settings, there are three different styles:
- None
- Windows
- Fusion

'None' and 'Fusion' are the same for me. Are there any differences?
If not, it doesn't make sense to have the same styles with two different names in the settings.

Furthermore, the style that is used by default should be called 'Standard' or 'Default' instead of 'None'.

**Comment by agilob** [comment]
Those are built-in qt styles, can't do anything about it.

**Comment by ovalseven8** [comment]
@agilob: Why shouldn't it be possible to change names or to remove a style?

**Comment by agilob** [comment]
Styles are loaded from your Qt configuration, we don't have any impact on this. It works on Linux and (afaik) OSX.

**Comment by ovalseven8** [comment]
Well, please reopen.
I think there is a better solution, anyway. 'None' and 'Fusion' are the same and especially 'None' looks ugly.

**Comment by agilob** [comment]
All we could possibly do is to set it default to Fusion, but if someone doesn't have Fusion, then it will fallback to none, and user would lose possibility to change it to anything else. For me none and fusion aren't the same.

> 'None' looks ugly.

Well... just don't select None.

ArchLinux with Gnome3 and KDE5 installed:
![weblate13](https://cloud.githubusercontent.com/assets/2544251/10417931/ef236f46-7044-11e5-8f51-008ed27017f4.png)

I can open this, mark as wontfix, upstream and issue will be left open. Pointless.

**Comment by ovalseven8** [comment]
@agilob: On my device 'None' is automatically the same as 'Fusion'. Wouldn't it be possible to remove 'None' from the list, so that it is just called 'Fusion' by default?

**Comment by agilob** [comment]
We do not modify or add or remove those styles, all you have on the list is referenced from Qt.
http://blog.qt.io/blog/2012/10/30/cleaning-up-styles-in-qt5-and-adding-fusion/
http://doc.qt.io/qt-5/gallery-fusion.html

If those styles look the same, it's problem with Qt or your operating system.

**Comment by SkyzohKey** [comment]
Selecting GTK+ on Fedora23 with Arc-Dark theme activated:
![Uglyness of qTox](http://i.imgur.com/vZ4mMYK.png)
