### ISSUE TITLE
Rename Smiley Packs

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2382]
Hello,

I'm not really happy with the current names of the Smiley Packs.

In my mind, we should choose names the people can imagine what it is about. Or what are the differences between them.

Current names:
- cylgom
- krepa098
- TwitterEmojiSimple
- TwitterEmojiSVG

Additionally, I can't see any difference between 'TwitterEmojiSimple' and 'TwitterEmojiSVG'. It could be confusing for people, so if it's the same, let's remove one of it from the list.

Are there any name suggestions already? 

Examples from me:
- ~~cylgom~~ **Basic**
- ~~krepa098~~ **Classic**
- ~~TwitterEmojiSimple~~ **Universe**

**Comment by zetok** [comment]
> Additionally, I can't see any difference between 'TwitterEmojiSimple' and 'TwitterEmojiSVG'. It could be confusing for people, so if it's the same, let's remove one of it from the list.

It's not the same.

**Comment by ovalseven8** [comment]
> Additionally, I can't see any difference between 'TwitterEmojiSimple' and 'TwitterEmojiSVG'. It could be confusing for people, so if it's the same, let's remove one of it from the list.
> 
> > It's not the same.

I see, thanks. What are the differences? Couldn't see at first sight.

**Comment by zetok** [comment]
"Simple" doesn't change text emotions to images, e.g. `:|` would not be changed.

**Comment by ovalseven8** [comment]
Thank you!

To be honest, it's confusing and an oxymoron. If emoticons are enabled, also `:)` should be one. I don't see the need for that Smiley Pack - would prefer to follow the KISS principle.
But if you absolutely must have this function, then it should be clear what are the differences. And, of course, let's rename the Smiley Packs. ;)

**Comment by suhr** [comment]
> If emoticons are enabled, also :) should be one.

I disagree. Emoticons should be separated from ASCII. And yes, “Simple” is confusing.

**Comment by ghost** [comment]
+1 to descriptive names for the emoticon packs. The current ones, if needed, can be displayed as tooltips.

The samples below the list could also be better. For example, the first 3 may parse the same symbol for all packs (`:)`, `>:(` and `:P` for instance) to make it easier to compare between them, and the last 2 could be something "special" in that particular pack. That'd also help people notice the "difference between 'TwitterEmojiSimple' and 'TwitterEmojiSVG'".

**Comment by ProMcTagonist** [comment]
It would be nice if they had text descriptions, but that would be extending the KDE emoticons spec, I think

**Comment by ovalseven8** [comment]
So, what do you think?
- ~~cylgom~~ **Basic**
- ~~krepa098~~ **Classic**
- ~~TwitterEmojiSimple~~ **Universe [with text emoticons, like _:)_, available]**
- ~~TwitterEmojiSVG~~ **Universe [without text emoticons]**

**Comment by agilob** [comment]
If at some point emoticons will be (were they?) adopted by other tox clients - antox or µtox they will have to rename them as well.
