### ISSUE TITLE
Bug: Unchecking "compact mode" makes qTox segfault.

### ISSUE THREAD

**Issue by SkyzohKey** [qTox/qTox#2385]
OS: Fedora 23 64 bits.
Gnome 3.18.0

When unchecking the "compact mode" checkbox in settings qTox segfaults.

``` bash
(qtox:4124): GdkPixbuf-CRITICAL **: gdk_pixbuf_new_from_data: assertion 'data != NULL' failed
Segmentation fault (core dumped)
```

**Comment by zetok** [comment]
Which qTox version?

**Comment by SkyzohKey** [comment]
> Commit hash: built without git

**Comment by zetok** [comment]
You seem to be using something terribly outdated - get recent version, and if you'll be able to reproduce, comment for reopen.
