### ISSUE TITLE
Can't build with qmake-qt5 on Fedora

### ISSUE THREAD

**Issue by 2bdkid** [qTox/qTox#2396]
The compiling instructions mentions qmake-qt5 will freak out in Fedora but doesn't mention how to get around it.

```
[brady@fedoradvm qTox]$ qmake-qt5
sh: /usr/lib64/qt5/bin/lrelease: No such file or directory
RCC: Error in 'res.qrc': Cannot find file 'translations/bg.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/cs.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/de.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/es.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/fi.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/fr.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/hr.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/hu.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/it.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/nl.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/no_nb.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/lt.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/pl.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/pt.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/ru.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/sl.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/sv.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/uk.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/zh.qm'
[brady@fedoradvm qTox]$ make
/usr/lib64/qt5/bin/lrelease translations/es.ts -qm translations/es.qm
make: /usr/lib64/qt5/bin/lrelease: Command not found
Makefile:927: recipe for target 'translations/es.qm' failed
make: *** [translations/es.qm] Error 127
```

**Comment by zetok** [comment]
> `sh: /usr/lib64/qt5/bin/lrelease: No such file or directory`

You need that to make things work, and also `lupdate` tool - dunno how package with them is called on fedora.. though, I thought that INSTALL.md has specified all deps for Fedora?

https://github.com/tux3/qTox/blob/master/INSTALL.md#fedora-1 ← could you check whether you have those depds installed, and if that's not the case, see whether installing them would help?

**Comment by zetok** [comment]
> Note to Fedora users: check qt5 version before building default is 4.8 on fedora 21 / 22, everything up until qmake-qt5 will build fine but then qmake-qt5 will freak out.

Well, that's unrelated to this problem - this note is about problem when one would try to build qTox against qt4 instead of qt5, which wouldn't work. Problem here is that you don't have installed a package with `lupdate` and `lrelease` tools.

**Comment by linux-modder** [comment]
qt5  is  normal now on 22 (the svg,linguist,and their  devel parts however are not)   Have  made a PR adding the needed deps for  the translation bits (PR#2397)

**Comment by 2bdkid** [comment]
The only qtlinguist package in Fedora is qt5-linguist.
qt5-qtlinguist and qt5-qtlinguist-devel are not available packages.
