### ISSUE TITLE
Missing dependencies in Fedora

### ISSUE THREAD

**Issue by 2bdkid** [qTox/qTox#2399]
The compile instructions says to install qt5-qtlinguist qt5-qtlinguist-devel but these are not valid packages, but qt5-linguist works.

gtk2-devel is also needed for gdk/gdk.h. It also pulls in gdk-pixbuf2-devel which is also needed.

It's also worth mentioning ffmpeg-devel can come from RPMfusion

**Comment by zetok** [comment]
Ok, thanks.
