### ISSUE TITLE
We hit 100 contributors!

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#2402]
https://github.com/tux3/qTox/graphs/contributors

and 200 forks!

![untitled](https://cloud.githubusercontent.com/assets/2544251/10512783/df836e4e-733a-11e5-9b72-e68ed51dceb5.png)

**Comment by ovalseven8** [comment]
The new 'Bikeshedding' label is unnecessary.

**Comment by suhr** [comment]
+meta

**Comment by antis81** [comment]
Nice! We keep moving forward :walking: :+1:
