### ISSUE TITLE
qTox fails to compile with Qt 5.2

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#2407]
reported by @abbat,

https://github.com/tux3/qTox/commit/073d4f0ad329511dd0cf3211e18b60dd3d6f2d32#diff-6891a8673df6107b3f58a72f73bd7006R114 ← this line breaks it, since it's available only in Qt >=5.4
@antis81 

So, the question is, how long qTox is supposed to support Qt <5.4 ?

AFAIK there are reasons to bump minimal Qt version to 5.4, e.g. [accessibility support](https://github.com/tux3/qTox/milestones/Accessibility%20support), bugfixes, etc.

Now, the only reason against it, AFAICS is to support "easy" way of compiling qTox on some older distros, e.g. debian 8.

**Comment by abbat** [comment]
Pay attention what Qt < 5.4 is at least in these active (not EOL) distros:
- Debian 7 (Qt 5.3.2)
- Debian 8 (Qt 5.3.2)
- Ubuntu 14.04 LTS (Qt 5.2.1)
- Fedora 21 (Qt 5.3.2)
