### ISSUE TITLE
Add friend message box lacks right and bottom edge

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#241]
![screenshot from 2014-09-01 01 12 01](https://cloud.githubusercontent.com/assets/6127392/4105045/3b4f5e7e-319f-11e4-8679-41933807d5c3.png)

**Comment by msteinbeck** [comment]
Does this bug still exist?

**Comment by dubslow** [comment]
Yes

**Comment by tux3** [comment]
Does it still exist ? Is it on GNOME 3 (judging by the decorations) ?

**Comment by dubslow** [comment]
Apparently not, I see the border now.

It is Cinnamon 2.0, which... is related to Gnome 3, I'm not sure how closely though.
