### ISSUE TITLE
input / output audio device selection is being reset to default one upon visiting a/v settings tab

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#2419]

**Comment by antis81** [comment]
Should be fixed by #2415. @zetok Can you test please?

**Comment by zetok** [comment]
Yeah, seems to be fixed on b7cf4df13f741a0eb812531ab39a8c0b7195610a.

**Comment by antis81** [comment]
> Yeah, seems to be fixed on b7cf4df.

Thanks! That's good news. :+1:

Oops, wrong issue -> moved following text to PR:
~~Unfortunately there's yet another problem (bug) to be solved. When opening A/V settings tab now, I get lots of "AL: ... resource busy" errors. This depends on how the input device is opened. Actually I'm not happy with current solution as we mix in-/outputs. @agilob @BiTOk I will need your help. Can you please review latest code? Maybe you find something I overlooked.~~

~~Further I switched `red->yellow->green` gradient to `green->yellow->red`. Thus, the higher the input gain is, the more it becomes red. Think this comes more natural. (will push change later today).~~

**Comment by antis81** [comment]
@zetok Should be fixed by #2415 -> closing.
