### ISSUE TITLE
Crashes at launch on CPU's without SSE2 support [win32]

### ISSUE THREAD

**Issue by UC3829** [qTox/qTox#2421]
Problem signature:

  Problem Event Name:   APPCRASH
  Application Name: qtox.exe
  Application Version:  0.0.0.0

  Fault Module Name:    Qt5Gui.dll
  Fault Module Version: 5.3.2.0

  Exception Code:   c000001d
  Exception Offset: 0032c9fe

---

Related information:

https://stackoverflow.com/questions/21256792/write-access-violation-on-read-instruction
http://zone.ni.com/reference/en-XX/help/371361H-01/lvconcepts/sse2_caution/
https://msdn.microsoft.com/en-us/library/7t5yh4fd.aspx
https://duckduckgo.com/?q=c000001d+sse2
https://en.wikipedia.org/wiki/SSE2

**Comment by tux3** [comment]
SSE2 is a 10-15 years old technology, hardware that old is going to really struggle running Tox.
Disabling it would slow things down significantly for everyone. 

We could create a special qTox build without SSE2 for really old hardware, but I'm not sure if it's worth it.

**Comment by UC3829** [comment]
If you have to maintain a separate build then I understand why it would not be worth the trouble.  Just thought it might be a convenient way to repurpose old laptops as a dedicated text messaging terminal.  By the way, uTox seems to work, but I also wanted to mention these similar projects for the benefit of the community:

https://ricochet.im
https://blog.torproject.org/blog/tor-messenger-beta-chat-over-tor-easily

**Comment by agilob** [comment]
Recently I was contacted by people coming from tor messenger to qtox :) They said they prefer qtox/µtox :) It's good they are alternatives, bad they're not compatible with each other :<

µtox uses different technologies, Qt is more "modern" and you will find qTox more bloated and resources-hungry, for old devices I would stick with µtox.

**Comment by zetok** [comment]
Seeing as it's not going anywhere, closing the issue.
@tux3 please reopen if you do want to make separate builds.

# 

> Just thought it might be a convenient way to repurpose old laptops as a dedicated text messaging terminal.

You probably don't want to be running windows for that, and compiling qTox on Linux for whatever supported CPU features you have there should be relatively easy – if not, feel free to open an issue :)
