### ISSUE TITLE
feature request: voice messages

### ISSUE THREAD

**Issue by aaannndddyyy** [qTox/qTox#2426]
would be a nice feature to be able to send voice clips just like in whatsapp and other apps.

why voice clips and not a call?
because the other peer may be afk and I simply want to leave a message in voice format.
or I simply don't want a full-scale call.

compatible with other clients,
https://github.com/GrayHatter/uTox/issues/19
https://github.com/subliun/Antox/issues/191

and sendable as pseudo-offline message too.

**Comment by agilob** [comment]
Duplicate: https://github.com/tux3/qTox/issues/1804

**Comment by aaannndddyyy** [comment]
right. Closing it as dup

**Comment by agilob** [comment]
in qtox it would be actually possible to detect file type of transferred file and allow playing it the same way we show tooltip of transferred image, since we link ffmpeg anyway.
