### ISSUE TITLE
Stuck on avatars importing

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#2428]
From https://github.com/irungentoo/toxcore/issues/1458, thanks to @StSav012:
# 

qTox (both qtox and qtox-unity) doesn't load. The last thing writes to the terminal is,
`[time_stamp] src/persistence/historykeeper.cpp:178 : Debug: "Try import avatar for: UID."`
Then doesn't respond anything.
Neither any of my contacts, nor me have avatars loaded.

I'm running Ubuntu 14.04 LTS 64 bit, qtox-unity has just been updated to 117-c07aee1, qtox has just been installed for checking.

_update_: After I put a picture for the avatar, I got another message:
`[time_stamp] src/persistence/historykeeper.cpp:184 : Debug: "Import avatar for: UID."`
For further actions, though.
# 

@PKEv

**Comment by zetok** [comment]
@StSav012 I can't reproduce with both new profile, and older profiles.

Could you provide steps to reproduce?

**Comment by zetok** [comment]
Ok, to reproduce encrypted profile is needed - unencrypted profiles aren't affected.
1. `HOME=$PWD qtox`
2. make an encrypted profile
3. qTox hangs

**Comment by zetok** [comment]
according to bisect - 20d0eb06f6d8180b1d37645f93d8bb6606c3115b

```
20d0eb06f6d8180b1d37645f93d8bb6606c3115b is the first bad commit
commit 20d0eb06f6d8180b1d37645f93d8bb6606c3115b
Author: PKEv <pkev@yandex.ru>
Date:   Sun Oct 18 20:04:37 2015 +0300

    add multithreaded

:040000 040000 565e8ad4d2f9498fdec6f4e3d470811d84ea8d35 37df2f73d9096eadbae2a1621407b427a8f096e5 M  src
```

**Comment by StSav012** [comment]
Thanks a lot! I've been at work, and couldn't reply.

**Comment by PKEv** [comment]
Sorry, my bug....
Only saw was at work.
