### ISSUE TITLE
Only turn on audio when a certain volume is hit

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2431]
Mumble has the functionality that the microphone only turns on when a certain volume is hit.
I think it would perhaps be a good idea for qTox as well.

Especially, for suppressing background noise.

```
<mannol> toxic had that feature
<mannol> it was in toxav for a while before i removed it
<mannol> its easy to make
<reselver> OK. Why was it removed?
<mannol> filter audio was introduced IIRC
<reselver> mannol: So, it should be implemented in client, right?
<mannol> yes
<reselver> mannol: Didn't test it in toxic - had it some positive effects?
<mannol> yeah
<mannol> like not using bandwidth when you are not talking and etc
```

**Comment by agilob** [comment]
Related to push to talk?

**Comment by mannol** [comment]
like push to talk but automatic

**Comment by mannol** [comment]
It can easily be done. I can show you how if you are interested.

**Comment by ProMcTagonist** [comment]
+1, especially if it really does save bandwidth. We need as much of that conserved as possible.

**Comment by An-dy** [comment]
+1 (as a option when it not enable easy crypto analysis based on word length (silence "no" silence and silence "yes" silence need to be indistinguishable)).

**Comment by sudden6** [comment]
Implemented by https://github.com/qTox/qTox/pull/4790
