### ISSUE TITLE
Overloaded operator issue with historykeeper.cpp

### ISSUE THREAD

**Issue by RowenStipe** [qTox/qTox#2433]
On line 527 the '!=' operator get's flagged as an error with:
../qTox/src/persistence/historykeeper.cpp:527:62: error: use of overloaded operator '!=' is ambiguous (with operand types 'QByteArray' and 'long')
    if (sqlAnswer.first() && sqlAnswer.value(0).toByteArray()!=NULL)

I'm not even 60% sure what's going on here exactly, new to dealing with QT, but from what I could understand both sqlAnswer.first() and sqlAnswer.value(0) are calling the same result from the SQL query above (L:526) which might be the issue.

**Comment by zetok** [comment]
@PKEv

**Comment by PKEv** [comment]
Close
