### ISSUE TITLE
Output device isn't paused/closed after playing a ringtone/message beep

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#2435]
@antis81 
https://github.com/tux3/qTox/pull/2415#issuecomment-149213985

**Comment by agilob** [comment]
Similarly, number of subscribed devices is 1 (should be 0) after video call, might be related.

**Comment by antis81** [comment]
Should be fixed with #2509. Anyway, the audio in-/output device is still kept open in other situations, but no longer on this one (well, unless someone else is still subscribed… :)).

**Comment by towlie** [comment]
Nice. Thats why I saw this behaviour when I tested this PR. Except that it could'nt close the device after a message beep when the device was already open.
