### ISSUE TITLE
[Regression] messages with NULL are truncated after it when writing to DB

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#2439]
When message contains `NULL` character, everything after it is truncated.

qTox d2aa9441bfaa1145afc6a8790debd12be3a85c1c

Related:
#2292
#2364

Edit: I think that the same might apply to the nick (i.e. part after null in nick might be truncated), but I haven't tested.

Edit2: for testing use [spambot](https://github.com/zetok/tox-rust-neurological-warfare-bot) - it sends random stuff, including NULL chars.

**Comment by agilob** [comment]
Test it now, I merged code from @RowenStipe 

> When message contains NULL character,
> 
> P-very-high

-.-'

**Comment by zetok** [comment]
> >    P-very-high
> 
> -.-'

Well, I was told by @tux3 to tag issues that result in data loss as `P-very-high`.

And yes, normal users can encounter this bug, given that some clients do copy NULL at the end of someone's nick when doing tab-completion.

**Comment by suhr** [comment]
> someone's nick

I wonder...

**Comment by zetok** [comment]
@agilob reproducible on 8185893ab56a01350a6b72a81e6d782f7624f6d2
