### ISSUE TITLE
Audio feedback widget lags and freezes for short times

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2443]
Hello,

because the audio improvements were merged now, here the issue:
The audio feedback widget lags and during a call it is also freezing for short times.

**Comment by antis81** [comment]
@ovalseven8 FYI Just merged #2509 - the new feedback widget is still WIP. Anyway, overall user experience is improved concerning this issue. Leaving it open though as not completely solved…

**Comment by ovalseven8** [comment]
Just tried. 
Yeah, it's not solved yet.

**Comment by antis81** [comment]
Closing -> The input level metering widget no longer exists.
