### ISSUE TITLE
Feedback widget is not refreshed properly

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2444]
The feedback widget isn't refreshed when I choose another capture device. I have to click to another tab and then to 'Audio/Video' again to let it work.

**Comment by zetok** [comment]
I can't reproduce it.

I do have some strange freezes though when switching between cam and desktop.

**Comment by ovalseven8** [comment]
Works now. :+1:

**Comment by zetok** [comment]
If it works, close the issue?

**Comment by ovalseven8** [comment]
Yep, you can close it.
