### ISSUE TITLE
Changing input/output devices during call don't have any effect

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2445]
I can't change (input/output) devices during a call. Well, of course I can - but it doesn't have any effects. Don't think that it's desired behaviour.

**Comment by tux3** [comment]
Should be fixed by new AV #2456

**Comment by zetok** [comment]
Since it should be fixed now, closing.

If you can still reproduce it on new AV, please comment for reopen.

**Comment by ovalseven8** [comment]
Works. :+1:
