### ISSUE TITLE
Focus effect even if you're not clicking on buttons

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2446]
Hello,

the new focus effect in the login window doesn't work perfectly yet.

Way to reproduce:
1. Go with computer mouse over the button in login window
2. Click and during the click go away from button
3. If you are no longer on the button, you can skip/drop the mouse button
4. => Button is in focus status even if you're not clicking at the moment:
![Screenshot](https://cloud.githubusercontent.com/assets/8258609/10672365/e6733080-78ef-11e5-987a-c75a546f636c.png)

**Comment by antis81** [comment]
@zetok Please have a look into `loginScreen.css` and remove the `:focus` roles someone merged. ;)

For explanation: These buttons are marked as `default` (react on "enter" key) -> they are actually focused. Don't know why this got merged though…

**Comment by ovalseven8** [comment]
It's this PR: https://github.com/tux3/qTox/pull/2430

**Comment by zetok** [comment]
@antis81 ok, done in #2455
