### ISSUE TITLE
Messages getting dropped if peer is unavailable.

### ISSUE THREAD

**Issue by vi** [qTox/qTox#2448]
If qTox knows that the peer is offline, it remembers the message for eventual delivery and shows "in progress" indicator instead of timestamp.

But if qTox doesn't yet know that the peer is gone, messages disappear entirely. Such disappeared message look exactly like a successfully delivered message.

| Message | qTox's knowledge about peer | Peer actual status |
| --- | --- | --- |
| msg1 | Online | Online |
| msg2 | Online | offline |
| msg3 | offline | offline |
| msg4 | offline | Online |
| msg5 | Online | Online |

I expect all five messages to be delivered, including msg2.

I remember manually typing sequence numbers in IRC and ICQ messages to make reliable communication over unreliable network and don't want to do the same anymore with modern instant messengers.

**Comment by vi** [comment]
Update: not reproducible if peer is qTox. Reproducible if peer is Toxic.

If Toxic does not support some required part of protocol needed for this, qTox should put, for example, question mark near the delivery time to tell user that reliably delivery don't work now.

**Comment by vi** [comment]
Update 2: re-tested with qTox + toxic again, can't reproduce... Strange, I remember setting timestamp appearing instantly even though peer was terminated by `kill -9`...

Tested yet again - there was a small sub-second window where message got lost to Toxic.

**Comment by zetok** [comment]
> If Toxic does not support some required part of protocol needed for this, qTox should put, for example, question mark near the delivery time to tell user that reliably delivery don't work now.

Nah, that's not the case. Confirmation of message delivery is done on ~toxcore level.

It's a qTox issue - it doesn't correctly mark messages as "try to send" when peer appears to be online. _Edit: i.e. qTox incorrectly marks message as `delivered` without actually getting the delivery confirmation_

Thanks for extensive testing `:)`

**Comment by agilob** [comment]
> It's a qTox issue - it doesn't correctly mark messages as "try to send" when peer appears to be online. 

do you have more info about it? It's annoying me personally I thought it was antox bug -.-' Let me know what you know about it so I can try fixing it over the weekend.

**Comment by vi** [comment]
I've seen the state where the peer's indicator is still green, but the message has rotating circle instead of timestamp.

(I'd shown the peer indicator as yellow instead of green until the delivery notification finally arrives if it lasts for more than two seconds).

**Comment by zetok** [comment]
> do you have more info about it? It's annoying me personally I thought it was antox bug -.-' Let me know what you know about it so I can try fixing it over the weekend.

Well.. Antox also has bugs with that, at least on version that I have, so there's that.

I haven't really tested it, but quite often (always?) qTox fails to send faux offline message to a peer that it still "thinks" that is online, but the friend went offline (i.e. toxcore didn't get to the point where it signals that friend timed out).

I guess that the way to reproduce it would be to write message from peer1 to peer2, where at least one of peers (or 2) are connected via Tor, to guarantee that there's sufficient latency between them.

Or perhaps using https://github.com/tylertreat/comcast `:)`

**Comment by vi** [comment]
I expect the chat logs to eventually include the same messages on both peers regardless of comcast settings.

**Comment by anthonybilinski** [comment]
>It's a qTox issue - it doesn't correctly mark messages as "try to send" when peer appears to be online. Edit: i.e. qTox incorrectly marks message as delivered without actually getting the delivery confirmation

I know this was from over 2 years ago, but this doesn't occur since https://github.com/qTox/qTox/pull/4607, now a message is only marked as "delivered" when it's both added to history and the ack has been received. Feel free to re-open if someone can repro.

>I expect the chat logs to eventually include the same messages on both peers regardless of comcast settings.

Currently we can't enforce order on both ends, but other than that all messages will arrive on both ends ASAP. Enforcing order part is a duplicate of https://github.com/qTox/qTox/issues/4228

**Comment by sunglaze** [comment]
man i'm finding this tox very difficult to use  cant find my code amy help
greatly appreciated

**Comment by tox-user** [comment]
@sunglaze what do you mean? What code?
