### ISSUE TITLE
qtox jenkins configs

### ISSUE THREAD

**Issue by optimumtact** [qTox/qTox#2450]
@zetok you popped off irc before I could link them to you, can you contact me on irc or over tox

toxid:7931471B37E3429B0C2DBCC3A457799C4302CF66AEBEB6D7048EF9551F8F7F55B53368E4F2AC

or via my email (should be listed in my profile)

**Comment by zetok** [comment]
@optimumtact yep, thanks - I went afk, and my net got borked, but at least I did receive & accept your FR `:)`
