### ISSUE TITLE
[newav_final] microphone volume slider doesn't work

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#2452]
I've set it to 0, and I still could hear microphone/music (in fact, volume of sound (AFACT) did not change at all) on 7d9eb98bfdee63b090e279c28077316c83c0da22

I've set it to `0` during a video call, but even after turning it off and starting an audio call sound was still the same.

Playback volume slider in settings works.

Actually.

In client that was receiving sound, setting microphone slider to `0` muted the received sound.

**Comment by tux3** [comment]
On newav_final_for_realsies the microphone slider ~works for me, it changes the loudness of the captured sound, the only problm is that at 0 it's still somewhat audible.

**Comment by zetok** [comment]
Well, it doesn't work for me, just makes call quality **really bad**. (sound like some sort of static interference?)

**Comment by tux3** [comment]
Found the problem, we were only adjusting the volume on the first audio channels.
