### ISSUE TITLE
[newav_final] received video is shown in place of the video preview

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#2453]
on 7d9eb98bfdee63b090e279c28077316c83c0da22:

![misplaced](https://cloud.githubusercontent.com/assets/3148759/10693959/7cecc4ec-7993-11e5-8a7c-665c8bfd7c08.png)
↑ instead of avatars, there should be received desktop shown.

**Comment by tux3** [comment]
Fixed in toxav.
