### ISSUE TITLE
[newav_final_for_realsies] qTox crashes on exit

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#2457]
Reproducible: Always

steps to reproduce:
1. turn qTox on with a profile (`qtox -p $profilename`)
2. turn qTox off

https://gist.github.com/zetok/9501616e51a487ee385f

**Comment by tux3** [comment]
Norepro, but I think the problem is just that the CoreAV timer is deleted from the wrong thread.

**Comment by zetok** [comment]
1f758efc2f19fd4e9a9847c517e57ad021364c0f: https://gist.github.com/zetok/b8f91c73aacbc83d9513

**Comment by zetok** [comment]
Seems to be fixed on 8d2ae07c9fea211ac86b831d6e3a73b33701bf9d
