### ISSUE TITLE
OSX Tray missing quit button

### ISSUE THREAD

**Issue by RowenStipe** [qTox/qTox#2458]
As of 636bb918983f8d2c25e57a6a61479054271f8167 in OSX the tray icon menu list is missing the `Quit` option evidenced here: ![](http://i.imgur.com/2UZnIlL.png)

**Comment by agilob** [comment]
> It also suffers a bug where qTox minimizes if it's already open and vise versa when you click the tray icon to access the menus. (Apple just hates more than one button on a mouse)

known.

on KDE5 we have two ;)

![snapshot1](https://cloud.githubusercontent.com/assets/2544251/10701098/d0e7bd2e-79b9-11e5-8e68-b012aa4b369c.png)

**Comment by RowenStipe** [comment]
Removed from report and updated the report title then.

**Comment by antis81** [comment]
Problem is in `widget.cpp`, where `Ctrl+Q` is registered with `Qt::WidgetContext` (the default). Every class inheriting Widget will get its own Ctrl+Q shortcut (friendlistwidget, chatform, etc.):
1. Ctrl+Q contrext needs to be set to `Qt::ApplicationContext`.
2. It's an (application-)global shortcut -> move to `main()`.

**Comment by antis81** [comment]
Relates to #1723.

**Comment by briskycat** [comment]
This issue has nothing to do with shortcut contexts. The menu item is not shown because QAction::QuitRole is set on the corresponding action during construction: actionQuit->setMenuRole(QAction::QuitRole); (widget.cpp:147).
