### ISSUE TITLE
"Ligth icon" is grayed out because when qTox is starting I didn't have "Show system tray icon" checked

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#2460]
If I have "Show sytem tray icon" checked, then when qTox would start "Light icon" wouldn't be grayed out

**Comment by zetok** [comment]
Can reproduce:
![greyed out](https://cloud.githubusercontent.com/assets/3148759/10711529/10882812-7a76-11e5-94bb-f20b4689f352.png)

**Comment by agilob** [comment]
I'm pretty sure I was fixing this when adding indents...

**Comment by TheNain38** [comment]
I added a fix

**Comment by agilob** [comment]
I just did it too ;)
