### ISSUE TITLE
Proxy settings shouldn't be global

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2465]
Hello,

I am not sure if there is already a PR for this.

Would prefer that there is a qtox.ini for every profile.
For example if I have two profiles, Alice and Bob, and Alice would like to connect via Proxy and Bob wouldn't like, I have a problem. Because it's saved globally in qtox.ini.

**Comment by agilob** [comment]
> What's the purpose of Alice.ini and Bob.ini?

I don't have it?
