### ISSUE TITLE
Automatically adjusts the microphone level

### ISSUE THREAD

**Issue by alexeysvrv** [qTox/qTox#2469]
In the main branch in the program setting level microphone is not connected to a level in the microphone system. I would like to automatically adjust the level of the microphone, depending on the volume of your voice. This can be done?

**Comment by antis81** [comment]
I'll see what I can do. Working on volume control currently in #2768.

**Comment by antis81** [comment]
Duplicate of #2422. @alexeysvrv Btw. input gain can now manually be controlled via digital amplifier from -30 to 30dB in latest qTox version - no automatic normalization, but far better than before.
