### ISSUE TITLE
Tray support

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#247]
Show/hide qTox window by tray icon click.

**Comment by zetok** [comment]
Also there should be an option to minimize qTox by clicking on "X" button

**Comment by dubslow** [comment]
This can also be closed

**Comment by zetok** [comment]
> This can also be closed

Nope.

On 4e9d802d1fa622890ead911a861bd3e7f2b2955c there's still no tray support under i3wm.

Edit: From log:

```
No system tray detected!
```

That's strange, since gtk applications apparently have no problem with using tray..

Edit2: and qBittorrent also supports tray.

Edit3: oh wait, qbt is compiled against qt4

**Comment by agilob** [comment]
@zetok could you try [this patch](http://cr.i3wm.org/patch/295)?

At least error handling is implemented properly :D

**Comment by zetok** [comment]
@agilob doesn't seem to apply cleanly on i3 4.7.2

**Comment by zetok** [comment]
After upgrading Qt to 5.3.2 qTox suddenly gained tray support \o/

**Comment by dubslow** [comment]
Twas never our fault :D

**Comment by agilob** [comment]
can be closed \o/

**Comment by zetok** [comment]
Apparently there's no tray support under MATE

**Comment by agilob** [comment]
https://bugreports.qt-project.org/browse/QTBUG-34364

**Comment by kjcole** [comment]
I've just installed qTox under Ubuntu Trusty, and don't see it in the system tray (after telling it to minimizeToTray / autostartInTray).  After setting those, it became impossible to use, because it would start and immeditately hide itself somewhere. Editing settings.ini and setting them back to false at least lets me use qtox.

**Comment by tux3** [comment]
There's an issue for the tray icon not showing or showing incorrectly, see #541 

But apparently it's a bug with Qt and Ubuntu.
