### ISSUE TITLE
No qtox icon in Cinnamon menu

### ISSUE THREAD

**Issue by ivanbistrovic** [qTox/qTox#2471]
I use Debian 8 with Cinnamon desktop. I can't access qtox from menus because there is no icon and it can't be found by searching, only by invoking qtox through terminal. Tested with qtox and qtox-qt5.4.2, same thing happens. Some other clients work fine. What did I do wrong? :D

**Comment by agilob** [comment]
do you mean tray icon or after installing application?

**Comment by ivanbistrovic** [comment]
After installing an application. qtox works fine, I just can't access it through desktop environment because there are no menu entries.

**Comment by ghost** [comment]
If you copied the binaries in your path (or is there an unofficial .deb?), there's no package creating the necessary entries for the menu. To add a custom entry graphically, either open the menu configuration and then go to "menu editor", or create a new launcher  anywhere (can be deleted afterwards) and select "also add a menu entry" after clicking ok.

**Comment by ivanbistrovic** [comment]
I installed it with package manager using Tox repository. Yes, manual adding of menu entry was simple but I was just asking maybe it can be fixed at the source. Thanks.

**Comment by zetok** [comment]
It's up to @Zer0-One to fix it, given that I no longer have access to jenkins.

**Comment by Zer0-One** [comment]
I'll look into it and report back here with any updates.

**Comment by antis81** [comment]
@Zer0-One Guess the `.desktop` file is missing -> also no panel-menu entry in Lubuntu 14.04. This would also allow for integration with "3rd-party" panel replacements like glx-dock, docky, etc. right?

**Comment by NicoHood** [comment]
I have the same problem with elementary OS here. (Based on Ubuntu and Gnome3).

I tried to create the entry myself, but the icon (picture) is still missing. I also tried to reinstall (via apt-get) but that didnt help.

Solution for now: `/usr/share/application/qtox.desktop`

```
[Desktop Entry]
Version=1.0
Name=qTox
Comment=A New Kind of Instant Messaging
GenericName=Internet Messenger
Keywords=Chat;qTox;Tox;secure;Messanger
Exec=/usr/bin/qtox
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=qtox
Categories=Network;InstantMessaging;

X-MessagingMenu-UsesChatSection=true
```

**Comment by zetok** [comment]
https://github.com/tux3/qTox/blob/deeb9b2308290e0404198a38a5d4c456ac39b328/INSTALL.md#community-builds ← could you check if it works for you?

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.

**Comment by NicoHood** [comment]
I think I missed that. The issue is fixed now (on new installations, not my current install), thanks.
