### ISSUE TITLE
Program is recording audio at all time

### ISSUE THREAD

**Issue by muchweb** [qTox/qTox#2472]
qTox is always showing in PulseAudio 'Recording' device list. Which means that it is constantly recording my audio.

This is trust and security issue. User will need to mute recording manually to make sure it's not snooping by accident.

Instead, it should behave same as other programs like Ekiga, Pidgin, Empathy, that only start recording once audio call is initialized.

---

qTox 7afeb41b1e51a396cd9d21981f9d488b17a9e1ca and PulseAudio 7.0 on GNU Operating System.

**Comment by agilob** [comment]
Duplicate of #1862 #1416 #1880 which we marked as closed a few days ago @antis81 @zetok ?

**Comment by muchweb** [comment]
@agilob, thanks. I'll give it a try on a new version.

**Comment by muchweb** [comment]
Is fixed in 3a3be50c643b904ceb7c3b1948783bdfe4890275 build.

**Comment by agilob** [comment]
:+1:
