### ISSUE TITLE
qTox doesn't turn off camera after selecting it in preferences.

### ISSUE THREAD

**Issue by CM3PTb** [qTox/qTox#2474]
If you select a web cam in prefs, it turns it on, and doesn't turn it off.  it should be off after selecting in prefs, until you make a video call.
<Impyy> same issue with utox

**Comment by zetok** [comment]
Possibly affected by #2456, should be checked again when it gets merged.

**Comment by ghost** [comment]
Can't reproduce in 0ef39aa06af177061ab53c259ee9c71de2876264. 
@CM3PTb

**Comment by tux3** [comment]
This is fixed by the new AV API.
