### ISSUE TITLE
updater don't work

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#2475]
can make it as a separate project, and if the automatic update is not working to make it even be a reminder that there is already a newer version

**Comment by rugk** [comment]
There were already some issues about this: https://github.com/tux3/qTox/issues/2085 https://github.com/tux3/qTox/issues/1488

If you want to create an updater this would be nice IMHO.

**Comment by agilob** [comment]
https://github.com/tux3/qTox/issues/2389

**Comment by rugk** [comment]
This issue can be closed.
