### ISSUE TITLE
Audio works only once after qTox start up.

### ISSUE THREAD

**Issue by ElLamparto** [qTox/qTox#2477]
qTox version with the "VU meter" and picture-in-picture, downloaded 26 Oct.

It seems that audio works correctly after qTox start up, but in the following calls there is no audio or sometimes only one way audio.

When both parties switch to µTox, there is no problem. Therefore I suppose the bug is in qTox (clean up after audio session?).

Video seems to work always (often without audio) - but I haven't made many video calls, so I cant' be sure.

**Comment by ovalseven8** [comment]
There will be an update soon. Then, the issue should be closable.

**Comment by zetok** [comment]
Fixed in #2456, to be closed when PR gets merged.

**Comment by towlie** [comment]
Duplicate https://github.com/tux3/qTox/issues/2434

**Comment by zetok** [comment]
Closing, since it's a duplicate.
