### ISSUE TITLE
Simple dark mode

### ISSUE THREAD

**Issue by fcore117** [qTox/qTox#2478]
Please add simple dark mode to chat window, something like this i dirty improvised with paint filling color.
![capture](https://cloud.githubusercontent.com/assets/1313813/10761377/c39a322e-7cc9-11e5-86ab-9a50747d3009.jpg)

**Comment by ProMcTagonist** [comment]
@agilob whatever happened to your themes branch?

**Comment by agilob** [comment]
no one could make a code review and test it for ~2months so it's full of code conflicts and development was stopped.

**Comment by fcore117** [comment]
Maybe something simpler is possible? themes branch may take ages but simple dark mode is most wanted to avoid eyeburn and is meant for night.

**Comment by agilob** [comment]
it's impossible to change colour scheme without fundamental changes in qtox.

**Comment by zetok** [comment]
Duplicate of #1639, thus closing.
