### ISSUE TITLE
How to view the history?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2481]
I have:
- User with password
- $HOME/.config/tox/${USER}.qtox_history.encrypted
- Conversation with some contact

The problem: `Right click -> Load chat history` doesn't work (I'm choosing the correct day in calendar). Sometimes the history is loaded automatically for a specific day (not necessarily current)...

**Comment by ghost** [comment]
Really. Apparently, history just is not saved. The table on the screen - for example - no message at the 27th day. I am sure that the history file would not yield to any changes from outside.
![View history using `sqlitebrowser`](http://i.imgur.com/Y17iCeG.png)

**Comment by ghost** [comment]
There is something new on this issue?

**Comment by JacobHenner** [comment]
So is the issue /only/ that qTox isn't saving a history of messages, or are there issues with both saving history and displaying it?

**Comment by ghost** [comment]
Two weeks ago (could be wrong) I installed (the git commit below) and now it (message history is now saved and is displayed normally) worked as expected. I. e. issue can be closed. Thank you.

git commit: `0ef39aa06af177061ab53c259ee9c71de2876264`.
