### ISSUE TITLE
qTox doesn't work with alternative keyboard layouts

### ISSUE THREAD

**Issue by Doom032** [qTox/qTox#2483]
My default keyboard layout is us-altgr-intl ( https://zuttobenkyou.wordpress.com/2011/08/24/xorg-using-the-us-international-altgr-intl-variant-keyboard-layout/ ). It makes characters like ", ' and ~ regular keys instead of dead ones. Instead of typing ' and then e to type é, it allows you to type é with altgr+' and then e. It also adds keys not available in the regular international keyboard, like ˇ and ˙, which can be combined with characters to make for example ǔ, ė, ǚ, etc.

Anyway, for some reason this doesn't work at all in qTox. Pressing altgr+' and then e, for example, just prints a regular e. Special characters like ˇ don't get printed at all.

The more serious issue is probably in my other layout: Chinese Pinyin. It doesn't work on qTox at all, instead my keyboard acts like it's in regular US international when using it. It's impossible for me to type Chinese characters in qTox! I have to type them somewhere else and copypaste them.

Likely the same issue as https://github.com/tux3/qTox/issues/2122

Maybe this is something in Qt? I've never had issues with my alternative layouts in programs like Firefox, Thunderbird, LibreOffice, any of my terminals, GVim etc, but none of them use Qt.

**Comment by agilob** [comment]
Any other Qt application you could compile with the same version of Qt and test?

**Comment by Doom032** [comment]
Hm, I can't even compile qTox right now, because I don't have the time to do that and compile ffmpeg and all that's needed. I can tell that the bug is present on both my laptop (Linux Mint 17.1) and my home PC (Xubuntu 14.04), both based on the latest Ubuntu LTS.

Okular uses Qt, right? It doesn't have the issue on either OS. But of course my version of Qt might be different from the one that qTox was built with.

**Comment by agilob** [comment]
Where did you get qtox from? @zetok should know the Qt version of your build.

Maybe we should add Qt version in about page?

**Comment by zetok** [comment]
> Okular uses Qt, right?

It uses  Qt 4 on those distros.

**Comment by antis81** [comment]
Qt version should be Qt 5.3.2, right?

**Comment by agilob** [comment]
5.5.1?

**Comment by antis81** [comment]
~~Checked it: The packaged Qt version on Ubuntu 14.04 is **5.2.1**.~~

**Comment by agilob** [comment]
We need version of Qt which was used to build his qTox package. He didn't build it himself.

**Comment by antis81** [comment]
Ok, I understand. Put this into a terminal of your choice:

`apt-cache rdepends qtox`

Output:

```
qtox
Reverse Depends:
  qtox-unity:i386
  qtox-qt5.4.2:i386
  qtox:i386
  qtox-unity
  qtox-qt5.4.2
```

And the winner is… **Qt 5.4.2** :smile:

**Comment by zetok** [comment]
@antis81 not really.

**Comment by antis81** [comment]
#2493 will solve the Qt version riddle :)

**Comment by Doom032** [comment]
I tried to compile it on my Xubuntu 14.04.3 (LTS) but failed on the following error: http://pastebin.com/zWvzCWE9

It's probably a Qt version mismatch, because the current Qt version in compiled qTox is 5.5.1 (t. #2493), and the version on my distro is 5.2.1+dfsg-1ubuntu14 (t. apt-cache)

Anyway, I doubt getting my qTox compiled is gonna help with finding the cause of this issue. I see many issues in the tracker which are probably the same as mine(ex. #2122, #2501, #2326) which leads me the believe this problem is universal. At least among statically compiled qTox builds.

**Comment by aaannndddyyy** [comment]
dead keys working fine for me with kytv*'s unofficial version, but not with the binary from your website.
I tried the characters from above and they work.
But it does not work with ibus either. 
Reason is probably that my ibus is qt4-only while qtox uses qt5.

*) kytv is a volunteer building unofficial debian and *buntu packages of tox and making them freely and transparently available. His build scripts are all public too. He is not part of the official Tox Foundation but a member of I2P and TAILS dev groups.

**Comment by tux3** [comment]
So I suspect this is broken because the version we ship is statically compiled instead of linking dynamically to the system's Qt installation. The versions I compile on my system also work just fine with dead keys ËûÀ, unicode input★ and the compose key™ 
It would be great if we started building "real" packages like kytv does, but that's more work.

**Comment by aaannndddyyy** [comment]
@tux3 Re more work: he only does so for Debian and Ubuntu derivatives. I think even for Raspberry…  But you are free to take his work and use it. Build scripts are free open source too. But this will not help you with other systems.
He's got utox, qtox, ratox, weechat-tox, toxcore, toxic, pidgin-tox (now defunct due to no versioning in toxcore), . . .
You are free to use his work for building it on your own servers, but he does probably not have the time to become an official part of the project.
