### ISSUE TITLE
'tox user' instead of user nickname in group users list

### ISSUE THREAD

**Issue by Haarolean** [qTox/qTox#2485]
There's 'tox user' instead of my nickname colored green. No idea how that happened.
![rqhbukc](https://cloud.githubusercontent.com/assets/1494347/10823734/6a6a726e-7e76-11e5-9431-44df9ec1a542.png)

**Comment by agilob** [comment]
What's your profile name?

**Comment by ovalseven8** [comment]
Yep, that's qTox bug.

**Comment by antis81** [comment]
@agilob Obviously the profile name is `Tox User` (the default) -> see right side of screenshot. :)

**Comment by ghost** [comment]
No, it happens with other profile names too. Confirmed using the latest binaries where profile name and alias != "Tox User".

In uTox I see the right alias for both the loaded uTox profile and the user in qTox.

**Comment by zetok** [comment]
@antis81 as @kehugter said, it's a qTox bug.

**Comment by ghost** [comment]
I don't know if it helps to the solution, but at some point testing #2600 qTox "knew" the right alias and deleted the string instead of assigning `Tox User`. It doesn't happen always tho... most of the times when I enter the group and the alias is `Tox User`, even though there are duplicates in the user list.

**Comment by sudden6** [comment]
Is this still an issue? If not please close.

**Comment by Haarolean** [comment]
Same on 1.9.0-104-g5...

**Comment by tox-user** [comment]
I'm pretty sure this is a toxcore bug related to https://github.com/TokTok/c-toxcore/issues/768.

**Comment by sudden6** [comment]
Probably not an issue anymore, please open a new issue if this is still a problem.
