### ISSUE TITLE
openSUSE compilation error

### ISSUE THREAD

**Issue by GitHub-devel** [qTox/qTox#2486]
## I'm trying to compile recent source and get the following error for any openSUSE (13.1, 13.2, Tumbleweed) :

[ 266s] src/audio/audiofilterer.cpp: In member function 'bool AudioFilterer::enableDisableFilters(int, int, int, int)':
[  266s] src/audio/audiofilterer.cpp:49:80: error: too many arguments to function 'int enable_disable_filters(Filter_Audio_, int, int, int)'
[  266s]      return filter &amp;&amp; 0 == enable_disable_filters(filter, echo, noise, gain, vad);
[  266s]                                                                                 ^
[  266s] In file included from src/audio/audiofilterer.cpp:25:0:
[  266s] /usr/include/filter_audio.h:17:5: note: declared here
[  266s]  int enable_disable_filters(Filter_Audio *f_a, int echo, int noise, int gain);
[  266s]      ^
[  266s] Makefile:2421: recipe for target 'audiofilterer.o' failed
[  266s] make: *_\* [audiofilterer.o] Error 1
[  266s] make: **\* Waiting for unfinished jobs....
[  271s] error: Bad exit status from /var/tmp/rpm-tmp.pTjgYD (%build)

**Comment by zetok** [comment]
You don't have recent filter_audio, update it.
