### ISSUE TITLE
Problems with the history and encryption of the files

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2492]
Hello, i'm having a issue while trying to load chat history that seems not working.
That's what i found in the logs (.config/tox/qtox.log):
src/core/coreencryption.cpp:83 : Warning: Decryption failed
src/persistence/db/encrypteddb.cpp:104 : Warning: pullFileContent: Encrypted history log is corrupted: can't decrypt, will be deleted

I'm using Debian Jessie - 3.16.0-4-amd64

Commit hash:  3a3be50c643b904ceb7c3b1948783bdfe4890275

**Comment by ghost** [comment]
The problem is that: if you put a wrong the password the first time it can't decrypt the file so it delete all history logs.
If you put the right password the first time it does the work perfectly and the chat history is still there.

**Comment by tux3** [comment]
I seriously need to rewrite the whole encrypted database code, it's incredibly fragile and kludgy. If you lost your history log, then that is a problem. Data loss isn't acceptable.

**Comment by tux3** [comment]
Fixed by the new SQLCipher database code in master.
