### ISSUE TITLE
Remove Exit action from tray menu if user is on kde5

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#2495]

**Comment by zetok** [comment]
@agilob um, will you be working on it, or should `help wanted` label be added?

**Comment by agilob** [comment]
antis made a custom icon for logout, so I will make those two changes in on PR. Just didn't have much time in the last few days.

**Comment by tux3** [comment]
I think the issue is more complicated than just removing it on KDE5, because I only have one Exit action on Kubuntu KDE5, so you can't just remove this one.

**Comment by agilob** [comment]
Hmm I will investigate it! I have one Exit which is "ours" and one which is automatically added by KDE to any Qt application - qtox, qbittorrent, skype, clementine...
