### ISSUE TITLE
"No system tray detected!" | ElementaryOS 0.3.1 Freya (32-bit)

### ISSUE THREAD

**Issue by WinterDOS** [qTox/qTox#2496]
Then i minimize window it disappears.

ERROR
[17:19:33.372] src/widget/widget.cpp:1746 : Warning: No system tray detected!

Elementary OS 0.3.1 Freya (32-bit)
Built on Ubuntu 14.04

Hardware
Processor: Dual-Core Intel® Atom™ CPU N450   @ 1.66GHz
Memory: 990.9MiB
Graphics: Intel Corporation Atom Processor D4xx/D5xx/N4xx/N5xx Integrated Graphics Controller

**Comment by tux3** [comment]
We could try always compiling packages with libappindicator support, but loading libappindicator at runtime and falling back graciously if it's unavailable. So we just need to add libappindicator as a recommended package instead of a dependency.
This way it should just work for everyone.

**Comment by ProMcTagonist** [comment]
Searching reveals some Elementary users are using this:

https://launchpad.net/sni-qt

from:

https://support.insynchq.com/t/elementary-os-app-icon-in-status-bar-not-showing/1610/7

**Comment by ProMcTagonist** [comment]
From that forum link:

> roth, ipugoy.. if it's already installed remove both sin-qt and insync - then you must reboot
> once you reboot Elementary os , from the terminal .. sudo apt-get install sni-qt insync
> then sudo reboot .. i've tried this with an existing install and a fresh one Twice each.. use terminal not the gui to install it and it works everytime

**Comment by agilob** [comment]
btw. Plasma 5.5 reverted changes, they no longer need SN.

**Comment by zetok** [comment]
Is this still reproducible on newest qTox & new repo?

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.

If issue is still not fixed, please comment for reopen.
