### ISSUE TITLE
Markdown for messaging

### ISSUE THREAD

**Issue by rugk** [qTox/qTox#2497]
I think it would be a nice thing to be able to use some basic markdown to format your messages.
I think you all like it and it is very easy to use too. :)

E.g. Skype also allows simple formatting like `**bold**`, `__underlined__`, ... if I remember correctly. That's similar to markdown, but I think for (q)Tox real markdown should be used of course.
You can also see how nice this is in Discourse forums.

**Comment by ovalseven8** [comment]
Personally, I don't necessarily need it.
Additionally, it's more complicated in Tox compared to Skype or internet forums because of the compatibility between the different clients.

**Comment by agilob** [comment]
3 weeks ago there was html and people complained!

**Comment by rugk** [comment]
Html(!)?

So you could send `<a href="tox.chat">my link</a>`?
Also `<script type="text/javascript">alert("Hi!");</script>`? 😉
In this case I would also have complained about this...

---

The cross-compatible issue is true - however markdown was designed to (also) look good when displaying the plain text, so it won't look so bad.
Additionally I can of course also ask this on toxcore so that this possibly will be adopted by the tox core.

**Comment by ProMcTagonist** [comment]
> markdown was designed to (also) look good when displaying the plain text, so it won't look so bad.

Agreed, lots of people **already*\* emphasize like this.

Markdown gracefully degrades and shouldn't cause problems for anyone.

**Comment by agilob** [comment]
This is not a toxcore issue but µtox, antox, toxic and other clients.

**Comment by zetok** [comment]
@rugk

> The cross-compatible issue is true - however markdown was designed to (also) look good when displaying the plain text, so it won't look so bad.

No.

There was an issue on STS on how to do it properly - if you're interested in why, you may want to go to there and read it.

@agilob

> This is not a toxcore issue but µtox, antox, toxic and other clients.

Eh, not quite. This ~is partially a toxcore issue, given how toxcore API works and what it is supposed to do.
But yes, it's also a client issue.

**Comment by quininer** [comment]
It is a good idea, I want to have a tag no longer make qTox eat my code indentation. ;)

**Comment by zetok** [comment]
> I want to have a tag no longer make qTox eat my code indentation. ;)

Well, this is a bug that is fixed in #2013 - I kinda wonder when remaining issues with it could be fixed, so that it could be merged.

**Comment by TheNain38** [comment]
This is a very good idea, markdown's design makes it looks good even when in plain text, so I think this would be cool to implement :)

**Comment by An-dy** [comment]
+1

**Comment by anoadragon453** [comment]
+1

**Comment by SkyzohKey** [comment]
It's fairly easy to implement, doesn't need most of the actual stuff markdown parsers provides so i wrote some little regexes to do the job. Should be simple to add in qTox.

> Ricin now supports **bolded**, _italicized_, <ins>underlined</ins> and ~~striked~~ messages. 
> See the [wip/chatform](https://github.com/RicinApp/Ricin/tree/wip/chatform)@[2e7d6a0](https://github.com/RicinApp/Ricin/commit/2e7d6a0895aa75200a3bd63f19999cf0fcc404d1) commit for more infos.

**You even doesn't need to change ToxCore:**

Ricin (with Markdown lite support):
![Current Ricin's Markdown support](http://i.imgur.com/fS0KB1p.png)

µTox (with no Markdown support):
![Current µTox Markdown support: null](http://i.imgur.com/rTPelaW.png)

**Comment by xenohunter** [comment]
It would be very cool if qTox could support code highlighting, or at least monospace and indentation. So, +1.

**Comment by rugk** [comment]
[**@zetok**](https://github.com/zetok) commented on [6. Nov. 2015, 11:51 MEZ](https://github.com/tux3/qTox/issues/2497#issuecomment-154378066):

> [@rugk](https://github.com/rugk)
> 
> > The cross-compatible issue is true - however markdown was designed to (also) look good when displaying the plain text, so it won't look so bad.
> 
> No.
> 
> There was an issue on STS on how to do it properly - if you're interested in why, you may want to go to there and read it.

Can you give me a link?

**Comment by zetok** [comment]
@rugk https://github.com/Tox/Tox-STS/issues/74

**Comment by rugk** [comment]
[**@zetok**](https://github.com/zetok) commented on [29. Dez. 2015, 19:32 MEZ](https://github.com/tux3/qTox/issues/2497#issuecomment-167849292):

> [@rugk](https://github.com/rugk) [Tox-Archive/Tox-STS#74](https://github.com/Tox-Archive/Tox-STS/issues/74)

Thanks. However I only see [some complains](https://github.com/Tox-Archive/Tox-STS/issues/74#issuecomment-140727273) when you use markdown tables and code highlighting, which is _really_ markdown and I think this is not necessary. Things like **bold**, ~~strike-through~~ and so on would be enough IMO.

And to have separate types for such a simple thing is really unnecessary and just complicates the whole thing too much, so that the greatest advantage of markdown gets lost (which is simpleness).

And as the Ricin client shows there is already a client with Markdown support and based on this fact I think it would not hurt other clients to implement this too.

BTW it seems the discussion continued here: **https://github.com/Tox/Tox-Client-Standard/issues/19**
**So if anyone wants Markdown support for all clients I'd suggest to upvote this issue.**

**Comment by zetok** [comment]
> And to have separate types for such a simple thing is really unnecessary and just complicates the whole thing too much, so that the greatest advantage of markdown gets lost (which is simpleness).

Simple for users, and given that it should work for them transparently, it will be simple for them.

**Comment by rugk** [comment]
> Simple for users, and given that it should work for them transparently, it will be simple for them.

Well... if the client automatically detects that the entered text is markdown then you can do this, yes.
But I just do not want a switch "normal text"/"markdown".

**Comment by zetok** [comment]
> Well... if the client automatically detects that the entered text is markdown then you can do this (…)

IMHO client should always use "markdown-mode" when possible (i.e. other client also supports it), while presenting user an ability to override it and just use plain text.

**Comment by rugk** [comment]
> IMHO client should always use "markdown-mode" when possible (i.e. other client also supports it), while presenting user an ability to override it and just use plain text.

Yes, this is a good idea.

**Comment by zetok** [comment]
Basic markdown support was merged in #2832, thus closing this issue.

For additional features/improvements for current implementation new issues should be opened if needed.
