### ISSUE TITLE
Toxcore version is 0.0.0

### ISSUE THREAD

**Issue by uxname** [qTox/qTox#2498]
Toxcore version is 0.0.0 always:
![2015-11-05_155405](https://cloud.githubusercontent.com/assets/2634142/10968887/99a1f85e-83d5-11e5-8dcc-567c84a2fa2f.png)

**Comment by ovalseven8** [comment]
There is no version for toxcore at the moment.
It's more like a placeholder.

**Comment by agilob** [comment]
Version is taken directly from toxcore, current "version" doesn't have... version.

Sorry for confusion, we hope to fix it this week by merging new AV API @tux3 ?
