### ISSUE TITLE
Segfault when video-calling Echobot

### ISSUE THREAD

**Issue by Zer0-One** [qTox/qTox#2503]
When video-calling the audio-only echobot, I get a segfault. I ran it through valgrind and got the following trace: https://gist.github.com/Zer0-One/19b6c2c39b205564d634

If I run it through gdb, a backtrace gives me garbage: https://gist.github.com/Zer0-One/f567fabdc3b512901b60

I can reproduce this every time. This issue existed before the new a/v stuff was merged, so it isn't related to any changes that were made there.

I'm on Gentoo, with a 4.1.7-hardened-r1 kernel.

**Comment by tux3** [comment]
This is a nullptr dereference inside FFmpeg code and it doesn't crash with a static build, so your system's FFmpeg version is bad, closing.
