### ISSUE TITLE
qTox crashes when changing Audio call to Video call

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2505]
Hello,

Reproduce:
1. Use one qTox instance and one uTox instance
2. Make an audio call
3. Change in uTox audio chat to video chat during the audio call (in qTox you can't change it during a call?)
=> qTox crashes

**Comment by zetok** [comment]
I think that there was an issue like that already, but I can't find it.

**Comment by tux3** [comment]
I can repro.
