### ISSUE TITLE
qTox crashes when resizing the 'user area' in a group a/v chat

### ISSUE THREAD

**Issue by Balloon2mars** [qTox/qTox#2506]

**Comment by agilob** [comment]
Can anyone reproduce?

**Comment by zetok** [comment]
Nope, can't reproduce.

**Comment by NicoHood** [comment]
Got the same problem.

**Comment by zetok** [comment]
@NicoHood what OS/DE?

**Comment by NicoHood** [comment]
elementary os, based on ubuntu 14.04 x64

**Comment by zetok** [comment]
@NicoHood could you perhaps provide a backtrace if issue still exists?

Edit: https://github.com/tux3/qTox/wiki/Writing-Useful-Bug-Reports#providing-backtraces

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.
