### ISSUE TITLE
Chatform glitch

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#2508]
I don't know how to reproduce. And I forgot to check if it disappears when I end the call.
![chatform](https://cloud.githubusercontent.com/assets/6986141/11001518/cdab8e1c-84a7-11e5-95eb-36949fd05037.jpg)
![chatform2](https://cloud.githubusercontent.com/assets/6986141/11001521/d1256482-84a7-11e5-8425-fae953a683eb.jpg)

**Comment by towlie** [comment]
For me it looks like the invisible border, which should be above the text input field, moved down a bit.

**Comment by TheNain38** [comment]
When it does this glitch if you hover the sendfile icon with your mouse the button to send a screenshot appears in the video...

**Comment by zetok** [comment]
Is it still reproducible after #3453 got merged?

**Comment by towlie** [comment]
I cannot check this because it happened randomly and I don't have the time.

**Comment by zetok** [comment]
Closing then. If it's still reproducible, comment for reopen.
