### ISSUE TITLE
Opening A/V tab on Linux can cut system audio for a second

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#2523]
> <cisc> I noticed with the new AV and Linux with Pulse Audio, when, in qtox, you click on the Audio/Video tab when in settings, if you have an audio stream playing through PA there is a second's silence when clicking on that tab
> <cisc> so it cuts your audio for other streams for a split second

**Comment by agilob** [comment]
can't reproduce

**Comment by antis81** [comment]
Probably be fixed by #2509. @tux3 Can you check please?

**Comment by tux3** [comment]
I can't reproduce, that's a report from IRC. If nobody can repro, this is closeable.

**Comment by agilob** [comment]
Tried that during L4D2 game and music on, can't reproduce.

**Comment by tux3** [comment]
If someone can repro, leave a comment.
