### ISSUE TITLE
Message when group is no longer available

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2525]
Hello,

just a small issue:
1. Alice invites Bob to a group
2. Alice removes the group
3. Bob accepts the group invitation

**Now, there should be a message for Bob saying that the group is no longer available.**
Otherwise, it could be confusing for the user.

**Comment by agilob** [comment]
It's how toxcore works.

**Comment by ProMcTagonist** [comment]
+1

**Comment by zetok** [comment]
Not doable, thus closing.

You may want to inquire a in an issue on toxcore whether this would be possible to make toxcore work like that.. but I have doubts that it is.

**Comment by ovalseven8** [comment]
Well, the old groupchat is history soon, hopefully.

Will it be possible with the new one, @JFreegman?

**Comment by JFreegman** [comment]
In the new groupchats, if you can't connect to a group you'll just get a timeout error.

Also this would probably be doable in the current groups, though not worth the effort at this point.

**Comment by ProMcTagonist** [comment]
Issue should be held open for new groups.

**Comment by ovalseven8** [comment]
@JFreegman:
I see. But definitely something for the future. Would also keep it open as reminder.
