### ISSUE TITLE
Provide opencv and openal-soft for Windows

### ISSUE THREAD

**Issue by msteinbeck** [qTox/qTox#253]
Unfortunately it's not easy to get a precompiled mingw version of opencv for Windows. Currently you have to build it on your own which requires CMake, Codeblocks, etc. To make things easier for developers and jenkins I would like to provide opencv (at least core and highgui) and openal-soft. I just compiled these libs and could give a zip to @tux3. If you upload it I'll extend the bootstrap.bat script to download it.

**Comment by tux3** [comment]
> I just compiled these libs and could give a zip to @tux3

But how do I know that you're not secretely a NASA agent trying to plant a backdoor in qTox ?

**Comment by ghost** [comment]
^ legit concern

**Comment by msteinbeck** [comment]
> But how do I know that you're not secretely a NASA agent trying to plant a backdoor in qTox ?

Thats a good point. I think we have three options here:
1. You simply trust me and upload it. Users/Developers can still decide to use the precompiled libs or provide their own.
2. We leave everything as it is, but that is really annoying for Windows users.
3. You compile the libs by your own and if needed I give you a tutorial how to. Since you are the initiator of this project you are a more trustworthy person than me.

It's up to you, but I dislike option 2.

**Comment by tux3** [comment]
Including a binary blob even when you're trying to compile from source isn't a sane default imo, especially when it's software supposed to protect your privacy. Anyone with rw access to this repo and my or your computer would have an opportunity to compromise qTox in a hard-to-detect way. 

Perhaps a script that fetches and builds a minimal release of opencv and openal would be acceptable ? I don't strongly object to providing a zip of some dependencies somewhere to save some time, but I'd rather not recommand it, and certainly not on Jenkins.

The ideal imo would be Jenkins providing clean and trusted builds from source for most everyone, and a verifiable script (maybe python for portability?) or set of simple steps for people who have to do it the hard way.

I'm not sure what to do, but a .zip full of libs is not something I want.

**Comment by msteinbeck** [comment]
> Perhaps a script that fetches and builds a minimal release of opencv and openal would be acceptable 

I think that is not easy, because you have to ensure some things (is CMake installed, is make, g++ etc. in system path...). Providing a tutorial for compiling and installing these dependencies would be more practical. On the other side this makes the bootstrap.bat script obsolete because the effort of installing toxcore is minimal compared with opencv/openal and a user may ask himself why this easy, last step is done with a script which uses itself precompiled binaries (wget, unzip and dlls). 

> The ideal imo would be Jenkins providing clean and trusted builds from source for most everyone

I'm right there with you. At the end of the day most (windows) users will use your precompiled version of qTox, because most of them are consumers and not developers of this software. To not provide a precompiled package of opencv/openal is no option (in my mind) for this usecase. Thus you nevertheless will have a zip/tar.gz of opencv/openal which could also be used for developers.

UPDATE:

>  or set of simple steps for people who have to do it the hard way

This should be done in any case. I'll work on this task

**Comment by msteinbeck** [comment]
I think this issue can be closed. The docu gives a step by step guide. As far as I can see we will never have a jenkins build of openal and opencv.
