### ISSUE TITLE
Feedback on the latest qTox

### ISSUE THREAD

**Issue by darkman088** [qTox/qTox#2534]
Hello dear friends,

I haven't been active here for quite some time and I have been using one version of the product which works just fine, so I have decided to check what's new on the project and what has happened during my absence.
The original link which I have saved for downloading the latest versions of qTox:

https://github.com/tux3/qTox/releases

Seems to not be containing anything pre-compiled. So I just went to tox.chat and I downloaded the latest version which I found there. It is labeled Qt version 5.5.1.
Unfortunately, one of the things to notice, was that an option that I was delighted about, named Copy Friend ID has now vanished !!! I am very very disappointed!
Furthermore, other innovations, which I have been proposing, like adding the option to change the text size in chat windows are still not implemented.
Furthermore, I didn't see any option about the ringtone - for example to switch it off or to set a custom ringtone.
I still have to check the options about rejecting a call and a call waiting to pickup duration, as my contacts are currently not available. I really hope. that those will be still working fine!

I really hope, that you are going to pay attention to my post and work toward fixing this! qTox seemed to be the leading product in the tox protocol for an extended period of time, but I see that other clients seem to be advancing faster. Come on, guys, you can do better :-) I do really count on you! Keep up the good work!

**Comment by darkman088** [comment]
Trying to call and be called from a contact, using uTox 0.2r doesn't work at all !!
The called party is not being informed of any incoming call !! Chatting works flawlessly though...
Maybe there has been some change in the protocol. Calls from uTox 0.2r to uTox 0.4.2 don't work either, so I believe that this is not a qTox problem

**Comment by agilob** [comment]
> uTox 0.2r 

I guess it's time to start updating your software. You are using out of date version, it's your fault.

**Comment by darkman088** [comment]
Yes but this will not bring the missing 'Copy Friend ID' feature back :-)

**Comment by agilob** [comment]
> Yes but this will not bring the missing 'Copy Friend ID' feature back :-)

It was broken from toxcore, not our fault, if you would you it, you would see it didn't work anyway.

I will be closing this issue as irrelevant and useless complaining, if you want to fill a bug procesd to: [Writing Useful Bug Reports](https://github.com/tux3/qTox/wiki/Writing-Useful-Bug-Reports)

Patches are welcome...

**Comment by darkman088** [comment]
Hi agilob,

well, it was working from the beginning. Then I came to know, that there was some major change in the protocol / toxcore, everybody was busy implementing it. I guess that it has been isolated from the core back then. Can I write them and ask for it again ?
Thanks in advance and sorry for bothering...

**Comment by ProMcTagonist** [comment]
It was never supported by core. qTox just saved IDs of friends that you had added by pasting in their ID. If you had tried to get the ID of a friend that you had never initially already had the ID of, it would have failed and given you only their public key.

This feature may eventually come back with some work done outside of core. A client issue you can watch concerning this is https://github.com/subliun/Antox/issues/134. The Antox developer is going to create this feature, so that other clients can implement it as well, but it may take some time, as work is focused on new groups and improving AV at the moment.

Happy toxing :)

**Comment by darkman088** [comment]
Yes, I think that saving the ID is a good idea! Honestly, I don't know how you might not have had the ID of a friend ? You need the ID to add him to the contact list! Or am I wrong ?
Additionally, one more hiccup which I found is, that it's not possible to manually sort the contacts - when I try to drag a contact in order to move him up or down the list, nothing happens.
I don't want to say bad words about the developer of Antox, but I have been waiting for almost 2 years for him to implement audio calls...

Thanks for your answers and advices!

**Comment by ProMcTagonist** [comment]
> You need the ID to add him to the contact list! Or am I wrong ?

Someone can send you a friend request by adding you with your ID, and all you have to do is accept, in which case you never get their full ID.

> it's not possible to manually sort the contacts

Right now it's in discussion whether dragging contacts should be used for sorting, creating groups, or something else. Related issues are https://github.com/tux3/qTox/issues/645 and https://github.com/tux3/qTox/issues/2269.

> I have been waiting for almost 2 years for him to implement audio calls...

I believe he has working AV in another branch. He may be waiting on new groups to merge, or might have been waiting on the new AV API in core. 

> Thanks for your answers and advices!

:)

**Comment by agilob** [comment]
> I have been waiting for almost 2 years for him to implement audio calls...

This is a community driven, free of charge project that people work on in their **spare time**, we are not paid by anyone, we don't even expect donations, we run our servers from our money, we maintain the code and servers ourself. Everything in tox ecosysystem is out of good will... If you urge to get a feature more quickly, you can start a paid bounty for it. Bigger issues take more time to develop, test, fix, review, maintain, developer come and leave, someone have to keep this mess together. Recently we gained more developers and better access to qtox repository and I think things are moving forward faster on our side.

**Comment by TheNain38** [comment]
I think it should be better to save the Tox ID you used to add your friend, and if you added them by accepting a friend request it would just save the PK, and you should have the ability yourself to add the NoSpam value if you get it from this friend and it would save it.
This issue subliun/Antox#134 partially defeat the purpose of having a NoSpam in the Tox ID... Even if you changed your NoSpam because you're receiving Spam, one of your friend could be reposting the new NoSpam value somewhere on the internet and you would again receive Spam... indefinitly...

**Comment by ProMcTagonist** [comment]
there would be a way to opt out, @TheNain38

**Comment by TheNain38** [comment]
@ProMcTagonist Then it **shouldn't** be checked by default, never it should be.

**Comment by darkman088** [comment]
@agilob - yes, I fully understand this. But exactly this "uncommercial" side of the project is what makes it so attractive. Otherwise some known organizations will start a paid bounty for ways to decrypt conversations or to inject harmful code, which will leak conversations and so on. It is obvious that features and issues need time to be developed and fixed, but it is enough to just have some up to date statement, like "currently this feature is expacted to be available by Q2 2016" and nobody will get angry if in Q1 2016 it says Q3 or Q4 2016. Everybody calms down when he sees an estimated (never meant a deadline here) date. Otherwise, people like me are only asking themselves: "OK, is this project still alive ? Will this feature ever be coded ?" And this requires just a few minutes per... month... or even per quarter...
But don't take my words here negatively - I am ONLY trying to help! When I am satisfied with something, I am using BIG words of praise and encouragement. When I am disappointed, I am just honest.
Thanks for your understanding and thanks for all your work! I really appreciate that!
