### ISSUE TITLE
Doesn't reconnect.

### ISSUE THREAD

**Issue by Dalamar6** [qTox/qTox#2542]
Windows 10 64 bit, Commit hash: a8746e68571edb051d10688de2de14cd7f1e3909

Several versions of tox have been showing people offline, presumably not reconnecting or something.

My ISP's legendary badness and refusal to investigate my 8-11pm disconnections/timeouts results in a massive amount of disconnections - or long periods of no throughput that aren't recognized as disconnects - is probably the culprit.

Last nights issues weren't recognized as actual disconnects, for example, no filezilla transfers got marked as failed last night, but I definitely saw the browsers and torrents stalling out for seconds at a time. Tox does seem to behave at other times of the day when I don't have issues, so it's probably a network code issue..

I woke up this morning, and tox didn't see anyone til I restarted it..

**Comment by agilob** [comment]
toxcore?

**Comment by tux3** [comment]
This looks like a toxcore networking problem, you should try with other Tox clients, if they all have the same problem, this is a bug you need to report against [toxcore](https://github.com/irungentoo/toxcore)

**Comment by suhr** [comment]
See also: https://github.com/tux3/qTox/issues/1560

**Comment by zetok** [comment]
https://github.com/irungentoo/toxcore/issues/1349 might be related.

**Comment by shalnoff** [comment]
Confirmed. As well as after hibernation. 
qTox has "reconnect" button hidden in the settings, that I use for reconnection after hibernation. However it would be great to implement auto-reconnect feature.

**Comment by tux3** [comment]
I'll mark this as dup of #2820 since it will share the same fix.
