### ISSUE TITLE
Add audio redirection from system audio output

### ISSUE THREAD

**Issue by rugk** [qTox/qTox#2545]
It would be nice to be easily able to "redirect" the audio output from the whole system into a call.
That's a system which is missing Skype, but which is a common one used with various additional tools by many users who like to send (aka "stream") the sound/music they are currently playing to the other conversation partners.

**Comment by agilob** [comment]
Select "Monitor of XXX" in your audio-video tab, works for me.

**Comment by rugk** [comment]
Ah this also redirects the sound?

However maybe I'll just want to share the _sound_ and not my whole screen...

BTW I forgot to add an important thing: Obviously the normal sound from my microphone should still be transmitted.

**Comment by agilob** [comment]
Do you want to share a single source of source, like clementine/foobar?

**Comment by rugk** [comment]
Did not thought about that, but this would also be nice of course. (very nice indeed as this would be a quite unique feature of qTox)
But I think at first just sharing the whole system sound (without sharing the screen) should be enough.

**Comment by ElLamparto** [comment]
It would be great and unique feature!
I think that the audio streaming should function as a separate option, independent on voice calls.
In other words, I could listen to someone's music without interferences from his microphone.

**Comment by TheNain38** [comment]
@ElLamparto it would need toxcore support for multiple audio streams, these issues #2548, #2102 for example, needs multiple video streams and toxcore don't support that.

See https://wiki.tox.chat/developers/gsoc/2015/ideas#multimedia_streaming

**Comment by CalcProgrammer1** [comment]
Monitor of X is a PulseAudio thing.  On Windows the only way I've found to do this is WASAPI loopback which means writing platform specific audio code.

**Comment by antis81** [comment]
@CalcProgrammer1 We use platform independent `OpenAL` for audio monitoring. Maybe you want to have a look at #2509. If audio sources would be tracked reliable in the `Audio` class, this issue is definitely possible to do. It's just the messed up non-working stuff, that has a priority.

**Comment by sudden6** [comment]
Closing as there are external tools available that can do that better.
