### ISSUE TITLE
Problem with profile image

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2546]
Hello, i'm having some problems when i change my profile image.
Basicly when i change my image,after some time i quit from the client and i enter again in qTox and my profile image has not been saved and it shows my previously pic.

OS: Debian Jessie, 3.16.0-4-amd64
Commit Hash: be967e88a3760cc963f7b498eb0d82af30b51696

**Comment by agilob** [comment]
Just tried 3 times and cannot reproduce.

**Comment by tux3** [comment]
@Androide909 Does your account have a password? We currently have some issues with how avatars are encrypted when you use a password.

**Comment by ghost** [comment]
Neither me. Tried exiting normally, breaking in the terminal an `kill`ing it, even less than a second after changing the image.

Note after tux3's comment: I used a password-less test account.

**Comment by ghost** [comment]
yes, i'm using a password

**Comment by ghost** [comment]
Yup, can reproduce with a password-protected profile.

**Comment by quininer** [comment]
I have the same problem. The new avatar will not be saved, either their own or friend.

**Comment by zetok** [comment]
@PKEv it's not fixed in #2468, right?

**Comment by PKEv** [comment]
yes, @tux3 say that  look it.
