### ISSUE TITLE
Graphical glitches with small window

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#255]
http://a.pomf.se/eygigm.webm
with i3wm

**Comment by dubslow** [comment]
Hmm, that looks exactly like what I meant here https://github.com/tux3/qTox/issues/184#issuecomment-54019484

**Comment by zetok** [comment]
It still happens on newest qTox

**Comment by tux3** [comment]
Fixed by 4f639a4dcff76d35a84dfc3977106178aee3e6b1
