### ISSUE TITLE
coredump by chance after entering password

### ISSUE THREAD

**Issue by farseerfc** [qTox/qTox#2550]
Hi, I am using qtox building from git (8a3c9d1)  on archlinux.

I noticed that qtox will core dump when I entered my password, by chance.

I managed to get 2 backtrace when it core dump:

https://cfp.vim-cn.com/cclK
https://cfp.vim-cn.com/cclM

It seems to be failing at the same position.

**Comment by towlie** [comment]
Probably the same issue: https://github.com/tux3/qTox/issues/2541
@farseerfc Update to latest qtox and see if it is fixed.

**Comment by farseerfc** [comment]
Wow, sorry for dup report.
I can confirm that the bug no longer appears in 3c51928 , thank you!
