### ISSUE TITLE
[Proposal]: Add possibilty to add someone using only the public key

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#2551]
You would need to warn the user that it will not send a friend request.
And you will add the contact using

``` c
uint32_t tox_friend_add_norequest(Tox *tox, const uint8_t *public_key, TOX_ERR_FRIEND_ADD *error);
```

**Comment by zetok** [comment]
IMHO this would only mislead users.

Do you have a **good** use case for it _and_ UI that would not lead user to misunderstanding about what it does / supposed to do?

This seems like something outside of qTox scope, that can be implemented in a separate tool..

**Comment by TheNain38** [comment]
@zetok I know it could possibly mislead users. I know it could be useful. For example: If you exchange each other public key out-of-band with another guy, if they used I2P to be anonymous, then the guy sending the request would not want the request use the onion routing you provide for adding someone. They would have used I2P. For the UI, I'm no good UI designer but you could:
- have another tab, there would only be the field for the PK and the button written: "Add contact without sending friend request" or something like that.

OR
- Have a checkbox, written "Add only using public key", which when checked would make the ID field only accept 64 characters long string, disable the message field and change the text button to "Add contact without sending friend request" or "Add contact", instead of "Send friend request".

OR
- Have a checkbox in advanced settings, enable using only PK to add someone, and in this case, you could combine with either one methods I mentioned before.

Thanks, if you add that. It would be useful for me and some others I think of.

**Comment by ProMcTagonist** [comment]
should be buried in advanced settings in its entirety

**Comment by TheNain38** [comment]
@ProMcTagonist I was just suggesting activating it in the advanced settings, so users who activate it could also use that feature using the usual way of adding a contact (e.g. using the "+" button)

**Comment by tux3** [comment]
This is something non-technical users will never use. I could imagine allowing this through a command line command, but we can't justify spending valuable GUI screen real estate on this feature.

Normal users shouldn't have to understand the difference between sending a friend request and only adding a friend's public key, this would be a nightmare to explain to a beginner.

**Comment by TheNain38** [comment]
@tux3 Even if it is activated by marking a checkbox in the settings or whatever?

**Comment by ovalseven8** [comment]
Yes, if ever it should be a command line command.

**Comment by zetok** [comment]
> Yes, if ever it should be a command line command. 

And if it has to be that, it doesn't even have to be a part of qTox..

**Comment by TheNain38** [comment]
I've implemented this in #2570

**Comment by TheNain38** [comment]
@tux3 Even if qTox is for non-technical users, technical users should still have access to advanced feature, even if they are the only one to use these. For example: the setting which let you choose the sync type of the database, do you think many user change that?

**Comment by tux3** [comment]
@TheNain38 The database sync type was causing real performance problems on some systems, you're proposing a new feature, that's a very different situation.
I'll be happy to discuss whether the database sync option should be removed, there have been some internal performance improvements and it might not be needed anymore.

You're proposing a new option that I really can't imagine explaining to non-technical users and that seems to be only needed in complex, convoluted scenarios. Your use case mentions I2P users that want to not send a friend request to avoid onion routing, I very much doubt this is a use case common enough or serious enough to justify a new option.

A lot of people have one killer feature they really like, but it's a different feature for everyone. We can't have them all, so show me that many actual users need this and I'll be happy to merge it.

**Comment by zetok** [comment]
> Your use case mentions I2P users that want to not send a friend request to avoid onion routing, I very much doubt this is a use case common enough or serious enough to justify a new option.

Note - toxcore currently doesn't even support i2p, so this isn't even a use case.

**Comment by TheNain38** [comment]
@tux3 For example: Two people have discussed in a groupchat and they want to be friends, they don't want to send their Tox ID in the groupchat because anyone in would also get his Tox ID. But they have that friendship: First people <-> friend <-> me <-> Second people. Then I give the second people the first people's public key and my friend gives the second people's public key. They don't use a single Tox ID because the first people have trust in my friend but not in me and the second people have trust in me but not in my friend to deliver the Tox ID without changing it. So by doing this they have trust in on of the two people to deliver it correctly. And to add it they have to enter random numbers to have a valid Tox ID so they can be friends together.

**Comment by TheNain38** [comment]
@tux3 and in this case this isn't a big GUI change, it just adds a new checkbox in the advanced settings, which are for "advanced" users.

**Comment by ovalseven8** [comment]
> Two people have discussed in a groupchat and they want to be friends, they don't want to send their Tox ID in the groupchat because anyone in would also get his Tox ID.

You could send a private message to the person in the groupchat. Will be possible with new groupchats.

**Comment by TheNain38** [comment]
@ovalseven8 But it's not possible right now

**Comment by NoxNoctium** [comment]
PR #2547 adds the actual public key of a friend back to the ui, why not allow practical use of it then?

**Comment by tux3** [comment]
@TheNain38 That still sounds like a very convoluted scenario to me.

Adding features and options to the GUI has a real cost. First in code complexity, because we have to maintain those features, fix bugs, make sure it interacts well with other options. 
And second in usability, because there's only so much space on a screen and so many UI elements new users can take in at the same time without feeling overwhelmed.

We can't add everyone's feature and everyone's "just one checkbox", or qTox will turn into a giant mess.
Again, show me that many actual users need this and I'll be happy to merge it.
I haven't seen that at all so far. We have thousand of users, we can't have thousand of options.

**Comment by TheNain38** [comment]
@tux3 I have another example which happened to me and other friends I know of: I had saved the Tox ID of my friends in a file because toxcore can't save them, and my little brother removed some of my contacts as a joke, and I couldn't add some of them back because they had changed their NoSpam. So I had to contact them IRL to be able to communicate again with them using Tox...

**Comment by tux3** [comment]
@TheNain38 Several of your friends changed their NoSpam without telling you? Did they understand what they were doing, or was it a confusion?
You can always reject friend requests and people who made the request will be none the wiser, the NoSpam is supposed to be used if you get spammed with requests. In practice it's more of a deterrent than anything, it makes request spam useless just by existing so request spam should be really rare in practice, and I'd be surprised if many people regularly changed their NoSpam. 

I'm afraid I keep repeating myself but I'm still skeptical of how many people will share your use cases, and at this point I'm really just looking to see if there is significant support for this feature, or if it's more of a neat idea that people wouldn't actually use.
It looks like you keep posting reasons **you** migth want this, but my point is about what **other users** need and don't need.

**Comment by TheNain38** [comment]
@tux3 We could just wait and see if people would like to have it or not

**Comment by tux3** [comment]
@TheNain38 Absolutely, that would be fine.

**Comment by zetok** [comment]
Well, here's the tool: https://github.com/zetok/tox-add-pubkey

**Comment by ProMcTagonist** [comment]
@zetok nice utility, will use :)

**Comment by TheNain38** [comment]
How do I use it if I'm on Windows ?

**Comment by zetok** [comment]
@TheNain38 Well, it would need to be compiled for Windows. Now, the "hard" part is having toxcore in your system, in a way that would allow Rust to automatically link against it - dunno what needs to be done in order to get that. (I guess that can be googled?) As for the Rust part, once you get toxcore "installed", instructions shouldn't differ at all - if something won't work, then it's most likely a bug, and should be reported against rstox (Rust binding to toxcore) or this tool.

Edit: as for usage per se, you would need to use it via `cmd.exe` (AFAIK).

**Comment by zetok** [comment]
Closing, since no good use case was provided.
