### ISSUE TITLE
README.md should say that on FreeBSD qTox is installed by the port net-im/qTox or the package qTox

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#2554]
It has been available for over a year.

**Comment by zetok** [comment]
@yurivict could you make a PR to add in README.md link to subsection in INSTALL.md about installing qTox on FreeBSD?

**Comment by JacobHenner** [comment]
I'll confirm the package is still current, and then add it to the README

**Comment by JacobHenner** [comment]
@yurivict What is the timeline between new qTox github commits and updated ports? The current port is at version db52ef6?

**Comment by yurivict** [comment]
@JacobHenner qTox port is updated periodically. I try to keep it the period no longer than a month.
