### ISSUE TITLE
All incoming messages as repeated stack

### ISSUE THREAD

**Issue by itscz-org** [qTox/qTox#2557]
I am a new tox user and installed the linked Win x64 version today on Win7x64.

On my first conversation all incoming messages have been displayed repeatly. I kept alle the default settings. The conversion partner is an experienced tox user that never had this problem. What's wrong here?

Regards,
Chris

![image](https://cloud.githubusercontent.com/assets/10709999/11101476/580f89f6-88b7-11e5-8507-d02a4d5c45c3.png)

**Comment by ProMcTagonist** [comment]
Has happened to me too when talking to someone using qTox on Windows.

**Comment by zetok** [comment]
@it-solutions-zehaczek your friend seems to use very outdated Toxic. They should update it.
