### ISSUE TITLE
OS X El Capitan — built-in camera isn't detected.

### ISSUE THREAD

**Issue by kakserpom** [qTox/qTox#2558]
Video Device: none
Commit hash: c568a4db051762c3ec084415194df9335b4b1d55
OS: latest El Capitan
MBP 2015

**Comment by tux3** [comment]
Webcam support on OS X is not yet implemented!

**Comment by briskycat** [comment]
Hi! I'd like to try to tackle this issue. What is the proper way to implement camera support on OS X?
From the code I can see that you use v4l2 on linux and DirectShow on Windows. So I guess using Qt Multimedia is not the right way to go?

**Comment by tux3** [comment]
@briskycat Hi, we're using FFmpeg instead of Qt for the video part, so you'll want to use FFmpeg with the AVFoundation or QTKit backend on OS X, not QtMultimedia

**Comment by TheNain38** [comment]
@tux3 Should be fixed?
