### ISSUE TITLE
Audio notifications "crackle"

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#256]

**Comment by krepa098** [comment]
Well the crackling is the result of putting an entire .wav file into an audio buffer (file header included). 

So basically we have 3 possibilities:
- switch back to QAudio (QAudio gets some fixes in the upcoming Qt 5.3.2)
- use an additional library for reading audio files (like libsndfile)
- convert notification.wav into notification.pcm (ie. use raw audio to store our notification sound, easiest solution)

**Comment by tux3** [comment]
> Well the crackling is the result of putting an entire .wav file into an audio buffer (file header included). 

Did I really just do that ? Dammit. I should sleep before writing code.

> switch back to QAudio (QAudio gets some fixes in the upcoming Qt 5.3.2)

Not happenning, I had too much pain trying to get Qt's audio working. It's not just a couple of bugs, all of it is bad.

> use an additional library for reading audio files (like libsndfile)

I'd rather not, but that's a solution.

> convert notification.wav into notification.pcm (ie. use raw audio to store our notification sound, easiest solution)

And that's what I'd do. We don't actually need a wav in this case, we can require that this file will always have the same format.
