### ISSUE TITLE
Feature Request: Right-Click to Copy Hyperlink

### ISSUE THREAD

**Issue by photonometric** [qTox/qTox#2560]
A fairly basic request. Most modern programs from shareware to MS Office offer the option to copy a hyperlink to the clipboard when you right-click on it. 

The practical advantage of this is being able to copy more quickly than if selecting the text manually, and also because hyperlinks can be easy to click accidentally when trying to select.

This awkwardness is compounded in qTox because of the full-line select; one either clicks and selects the whole line, which then cannot be manipulated, or must find the precise point between the "white space" and the hyperlink click space.

**Comment by ProMcTagonist** [comment]
+1, important ease-of-use feature that it's very jarring to lack

**Comment by ghost** [comment]
#1236 #2188

**Comment by zetok** [comment]
Duplicate of #1236, thus closing.
