### ISSUE TITLE
Are debug builds broken?

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#2562]
Is it normal that https://build.tox.chat/job/qTox_build_windows_x86-64_debug/ have this much of broken build that aren't broken in release?

**Comment by tux3** [comment]
This is a bad case of ODR violation depending on the #include order, so here only the Windows debug build is affected.
The serialization code needs to be tidied up a little.

**Comment by TheNain38** [comment]
@tux3 Also, I think release builds should be build before debug builds.

**Comment by tux3** [comment]
We don't really provide official debug builds at this point, there might be some on Jenkins but they aren't supported.
