### ISSUE TITLE
Rescan video devices

### ISSUE THREAD

**Issue by unode** [qTox/qTox#2572]
qTox already has a "Rescan audio devices" button.

In some situations, specially when using v4l2loopback interfaces the video device disappears from the list and restarting qTox is the only way to fix it.

Would it be possible to expand the functionality of the existing button to "Rescan audio/video devices"?

**Comment by sudden6** [comment]
I'll fix this

**Comment by sudden6** [comment]
@Unode can you please test my branch if it's working?
https://github.com/sudden6/qTox

**Comment by unode** [comment]
@sudden6 Sorry I don't have the libraries to compile it from source. I've been using the automated builds.

Since your code changes are rather small and clear. Can you simply turn it into a pull request?
I'd be happy to confirm the behaviour afterwards.

**Comment by sudden6** [comment]
i made a pull request, let's see if it will get merged.
Anyway if you want to compile from source, just use the instructions here https://github.com/tux3/qTox/blob/master/INSTALL.md
it is pretty straight forward.

**Comment by tux3** [comment]
This is fixed by the pull request that was merged.
