### ISSUE TITLE
Microphone device name is cut

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#2573]
![name of microphone](https://cloud.githubusercontent.com/assets/13149763/11168687/871584d6-8b9a-11e5-9c4c-9df7da5b0393.PNG)
I don't have this problem anywhere else

**Comment by antis81** [comment]
Could you check with #2509, please?

**Comment by TheNain38** [comment]
How do you merge the changes of a pull request to test it?

**Comment by antis81** [comment]
@TheNain38 Simple: Don't merge :smile:

Fetch the branch like this:
`git fetch antis81 newav_audio_cleanup:newav_audio_cleanup`

(you need to be on another branch)

**Comment by TheNain38** [comment]
Thanks. I didn't used git before. I will say if it has resolved my issue.

**Comment by TheNain38** [comment]
Problem is, on linux this problem isn't happening, but on windows it is... How do I cross compile it?

**Comment by antis81** [comment]
@TheNain38 Crosscompiling for Windows is not a piece of cake. You'll need Wine (and a lot of coffee… :)).

@zetok Does the `testing` branch compile for Windows? If so, I'll push to that branch and @TheNain38 can download the package.

**Comment by zetok** [comment]
@antis81 it did when I set it up on jenkins, dunno though if that's still the case.

**Comment by TheNain38** [comment]
I can't reproduce anymore... I think it was because I plugged the headset in the virtual machine and then I unplugged it from the virtual machine

**Comment by TheNain38** [comment]
I did reproduce it but I don't know how to reproduce it easly

**Comment by zetok** [comment]
> I did reproduce it but I don't know how to reproduce it easly

Well, can it be reproduced reliably, and if so, what are the steps?

**Comment by TheNain38** [comment]
@zetok Well I can't reproduce it reliably

**Comment by TheNain38** [comment]
I again got the same problem recently, and audio wasn't working after that problem, but I still don't have steps to reproduce... I just saw that it only happens when using audio, or messing with settings while it's running, or something like that...

**Comment by TheNain38** [comment]
So, I got to reproduce it 4 times. Steps to reproduce it reliably:
- open two instance (I'll be calling them `1`, and `2`), make a call from `1` to `2`
- unplug the currently used device (for me it's the same for output, and for input) and immediatly after that, stop the call on `1`
- plug the device you unplugged, and immediately make a call from `2` to `1`
- go to the audio settings of `2` or `1`, normally the microphone should be set to `None`, and all input audio devices should have their name cut, and also, audio input of this instance shouldn't be working when it's not in the audio settings

**Comment by antis81** [comment]
This is a typical `char* to QString` conversion error and roughly relates to #3125. There's 3 code paths that need to be checked, to fix the actual problem behind it:
1. Audio::inDeviceNames / outDeviceNames
2. Audio::initInput / initOutput
3. AVForm::getAudioInDevices / getAudioOutDevices

It is a (very) good idea to work with `char*` inside the `Audio` class (which you can consider as a "driver") and provide `QStringList` / `QString` to the API. Further OpenAL automatically selects the correct default device by passing `nullptr` as the device name. Code needs to be simplified here as well.

**Comment by TheNain38** [comment]
@antis81 I don't think it is in `AVForm::getAudioInDevices`, I looked at the code, and I see nothing anomalous, the while loop code is good... I think the problem is either in `Audio::inDeviceNames`, or in `Audio::initInput`.

Just one thing strange I noticed (but I don't think it's related), OpenAL returns a `const ALChar *`, and in `Audio::inDeviceNames` the signature of this function says that it returns a [`const char *`](https://github.com/tux3/qTox/blob/master/src/audio/audio.cpp#L538), and in `Audio::initInput` you declare a type [`const ALChar *`](https://github.com/tux3/qTox/blob/master/src/audio/audio.cpp#L239)...
And there is the same thing for the output devices: In [`Audio::initOutput`](https://github.com/tux3/qTox/blob/master/src/audio/audio.cpp#L278) you declare a `const ALChar *` but the function [`Audio::outDevicesNames`](https://github.com/tux3/qTox/blob/master/src/audio/audio.cpp#L527) returns a `const char *`
But these things are just a little inconsistency, it's not what's causing the problem...

One important thing that I think is important to note, is that the device I'm unplugging is my default audio output and input device.

**Comment by antis81** [comment]
@TheNain38 Thanks for your quick reply. Yes, it looks like the while loop works - yet it is misplaced and I took some minutes for fixing that. Please have a look over to PR #3175. Names will still be wrong, but with the cleanup this is now a bit easier to track down. Looks strongly like a unicode conversion problem on Windows (we require utf-8 conformity). In pre windows 10 era, the magic spell was `QString::fromLocal8bit` instead of the standard `QString::fromUtf8` - the latter works on any modern setup.

> Just one thing strange I noticed (but I don't think it's related), OpenAL returns a const ALChar *…

Both are exactly the same (ALchar just declares as `typedef char ALchar;`). However this should - **no must** :) - never be transported outside the Audio class. Such a misusage can be effectively prevented by implementing a private class. Unfortunately some people simply don't seem to understand the purpose of that and reverted it.

**Comment by Diadlo** [comment]
Is it still an issue?
