### ISSUE TITLE
No camera image is determined

### ISSUE THREAD

**Issue by alexeysvrv** [qTox/qTox#2576]
No camera image is determined when you run the program and click the tab, Audio / Video. The camera is listed in the drop-down list, but in the preview video shows an empty unspecified avatar (black silhouette on a white background). To enable the preview have to switch to a screen capture, and only then to the camera.
Build b4083f
Ubuntu 14.04.3 Kernel 4.2
Before, everything was ok

**Comment by sudden6** [comment]
Is this still an issue? If not please close.
