### ISSUE TITLE
[swscaler @ ] Warning: data is not aligned! This can lead to a speedloss

### ISSUE THREAD

**Issue by igpg** [qTox/qTox#2577]
I'm using
community/toxcore 3645-1 / arch linux and
aur/qtox-git r2712.2fed672-2 installed: r3871.db52ef6-1 (99)
Powerful Tox client written in C++/Qt that follows the Tox design
guidelines.

today's build which compiled correctly, of course all the dependencies were installed but when an audio call is established an extremely I mean extremely metalic voice is "heard" meaning you can't understand a thing from it.

The error looks like a problem in sync as I found similar issues with ffmpeg however the result is not working.

**Comment by tux3** [comment]
So, the title is actually a video performance debug message, nothing to do with the audio!
Are you using the "Filter Audio" option in the settings?

**Comment by igpg** [comment]
Well that's even weirder than, I didn't use the video at all on those tests it was just a direct call to a laptop on the same network.
Yes I used filter audio on both of them, however no joy. I also checked the logs for other "helpful" information but was the only warning I saw, maybe should check the other system as well.

**Comment by tux3** [comment]
Okay, I fixed filter audio today so this shouldn't be a problem anymore. The log message might still be there but it's not an issue.
