### ISSUE TITLE
Video kills audio

### ISSUE THREAD

**Issue by ElLamparto** [qTox/qTox#2578]
Audio alone: works fine.

Audio + video: video works fine, but audio works only one way (the quality is good) or not at all (just some cracks are produced). Chat messages are accepted with a delay (as if the chat field had no focus for a number of seconds).

Debian Jessie 32bit connects to Win7 64 bit or Win7 32bit.
Decent Internet connection.

µTox has identical problem (except the chat delay - I did not test), so could it be a toxcore issue?

**Comment by ghost** [comment]
Commit hash of both clients?

**Comment by ElLamparto** [comment]
Upgraded on Sunday, 15th Nov

**Comment by antis81** [comment]
Could someone please check against #2509. Should be better.

**Comment by antis81** [comment]
@ElLamparto Do you have possibility to compile and check against PR #2509? This actually might be fixed, but I cannot verify.

**Comment by ElLamparto** [comment]
Fixed in a version released a week ago. Good work!
