### ISSUE TITLE
Timestamp misalignment

### ISSUE THREAD

**Issue by mannol** [qTox/qTox#2579]
This happens:

![misaligned](https://cloud.githubusercontent.com/assets/13100554/11244291/18148738-8e0d-11e5-8ae3-17406e5dad21.png)
You can see how misaligned timestamps are.

**Comment by ProMcTagonist** [comment]
Does anything specific cause it?

**Comment by mannol** [comment]
No, just straight out opened new conversation.

**Comment by ghost** [comment]
Scrolling misaligned timestamps out of view and back makes them align again.

**Comment by zetok** [comment]
Still reproducible on ef5c094417b15db67b1b8736b5153a3cd221f488.

**Comment by sudden6** [comment]
Fixed in  #5489
