### ISSUE TITLE
Bad layout

### ISSUE THREAD

**Issue by dblsaiko** [qTox/qTox#2587]
It may just be a mistake on my part, but suddenly qTox looks like this:
![image](https://cloud.githubusercontent.com/assets/6306608/23334482/d3cebc0c-fbb0-11e6-8fd9-97b1dd11e2cf.png)

I wouldn't mind the layout but the white part in the middle is completely unoccupied and I can't seem to change it.

Using qTox db52ef6e6a843faa8543b4726a5c281b8f1e1d97
ArchLinux
KDE 5.4.3

**Comment by ProMcTagonist** [comment]
That is definitely a bug.

**Comment by dblsaiko** [comment]
This did not get fixed by recompiling, and is annoying as f***. I'd fix it myself if I knew C++, but I don't.
Could someone look into this? Does anyone else have this problem?

**Comment by g4jc** [comment]
I've never had this problem, but some ideas...
Remove /home/user/.config/tox/ and start a fresh.

If you're still having problems, there's a pre-compiled qtox available to test.

**Comment by dblsaiko** [comment]
Is the config directory containing my profile?

**Comment by tux3** [comment]
Yes, the config directory contains your profile, don't remove the whole folder.
Try removing just ~/.config/tox/<yourname>.ini and ~/.config/tox/qtox.ini to reset the settings

I've never heard of this bug before, do you know what you were doing when it happened?

**Comment by dblsaiko** [comment]
No, it just happened, I don't recall doing anything specific.

EDIT: Yep, removing those two files fixed it. Thanks :+1:

**Comment by ovalseven8** [comment]
```
Part of qtox.ini - With Error:
+++++++++++++++++++++++
[State]
dialogGeometry=@ByteArray()
dialogSettingsGeometry=@ByteArray()
dialogSplitterState=@ByteArray()
splitterState=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\0\0\x5\x15KH\0\x5\x15KH\x7f)
windowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x1v\0\0\0\xcd\0\0\x2?\0\0\x1N\0\0\x1w\0\0\0\xe7\0\0\x2>\0\0\x1J\0\0\0\0\0\0\0\0\x5V)
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

Part of qtox.ini - Without Error:
+++++++++++++++++++++++
[State]
dialogGeometry=@ByteArray()
dialogSettingsGeometry=@ByteArray()
dialogSplitterState=@ByteArray()
splitterState=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0\xff\0\0\x2\b\0\0\0\0\x6\x1\0\0\0\x1\0)
windowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\0\0\0\0\0\0\0\0\x3\b\0\0\x1\xc1\0\0\0\x1\0\0\0\x1a\0\0\x3\a\0\0\x1\xbd\0\0\0\0\0\0\0\0\x5V)
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x3\a\0\0\x1\xa4\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)
```

**Comment by zetok** [comment]
image from imgur:
![imgur](https://i.imgur.com/0V2Jd7P.png)
