### ISSUE TITLE
Spell checker - feature request

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2588]
I think that a really good feature for qTox would be a spell checker, starting probably in English US and UK, but later on including other languages.

**Comment by DanTheBritish** [comment]
That would mean that qTox would need to ship with a dictionary file, inflating the filesize.

It means that qTox would need to read the message input box, something that a privacy focused chat client probably shouldn't do.

Also, this is a duplicate:
#1301

**Comment by ghost** [comment]
Well, not necessarily, it could just be an optional feature, so it would allow you to download the dictionary file through the interface and it wouldn't come with the package.

Some users, as you say, may not want this due to privacy concerns, however for those who do, I think that it would be good to at least provide an optional option which is not activated by default.

**Comment by zetok** [comment]
Closing, since it's a duplicate of #1301.
