### ISSUE TITLE
System tray backend on cinnamon 2.8.5

### ISSUE THREAD

**Issue by BrunoMSantos** [qTox/qTox#2589]
At least since version 2.8.5 Qt backend doesn't work well.
Passing XDG_CURRENT_DESKTOP="GNOME" triggers the use of the GTK backend and works correctly.

This should be the default in upcoming releases.

This page also needs updating: https://github.com/tux3/qTox/wiki/Tray-icon

**Comment by sudden6** [comment]
can you please post the output of

```
echo $XDG_CURRENT_DESKTOP
```

**Comment by BrunoMSantos** [comment]
X-Cinnamon
