### ISSUE TITLE
[OSX/Bug] Scrollbar overlaps contact images after resizing window

### ISSUE THREAD

**Issue by anoadragon453** [qTox/qTox#2591]
Reproducible in the latest qTox experimental build, based off 4d54f5c.

Increasing the window height until the scrollbar disappears and then bringing it back until it reappears causes this.

<img width="261" alt="screen shot 2015-11-25 at 2 41 11 am" src="https://cloud.githubusercontent.com/assets/1342360/11395141/2a8424bc-931e-11e5-896c-6aad870498db.png">

**Comment by zetok** [comment]
I wonder if it's not an upstream (Qt) bug - I couldn't reproduce under i3 on Gentoo.

**Comment by ProMcTagonist** [comment]
Can it be reproduced under OS X?

**Comment by anoadragon453** [comment]
@ProMcTagonist
I've only observed this in OS X. Works fine on my Arch Linux machine.

It seems as if the application is still compensating for the scrollbar, but in the opposite of how it should be doing it. By this I mean when I extend the window so there is no scrollbar, the contacts move over to the right, as if to compensate for it. When I shorten the window, the contacts move under the scrollbar, as if it wasn't there. It's essentially backwards, probably just a small fix somewhere.

AKA Need to compensate for Apple's backwards behaviors.

**Comment by RowenStipe** [comment]
... It's almost depressing to admit I can't reproduce this cause I don't have enough friends to make the scrollbar appear.

**Comment by anoadragon453** [comment]
Add group chats lol.

**Comment by RowenStipe** [comment]
Attempts to reproduce unsuccessful using 10.10.5 OSX with current `PATCH-1.0.1.2` build ![](http://i.imgur.com/ZgTRB8q.gif)

**Comment by anoadragon453** [comment]
The VM represented the same behavior from your Gif, in which the contact images do not shift left or right depending on whether the scroll bar is being shown or not. However on my actual Mac - with the latest version - they still seems to exhibit this behavior. 

![cavernousexhaustedkakapo](https://cloud.githubusercontent.com/assets/1342360/11577963/48555ccc-99d6-11e5-8bc5-94470ff45e31.gif)

**Comment by RowenStipe** [comment]
So it's possibly some 10.11 weirdness then. Oh joy!

I'll look into it and see what I can find out.

**Comment by anoadragon453** [comment]
Keep in mind the VM was 10.11, and it wasn't exhibiting the same behavior. Hmm... the VM is running in 800x600 mode though, not sure if that would change anything.

**Comment by sudden6** [comment]
Is this still an issue?

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.

If issue is still not fixed, please comment for reopen.
