### ISSUE TITLE
Autostart works most of the time, but not always

### ISSUE THREAD

**Issue by mikalehmann** [qTox/qTox#2594]
I have two options to make qTox start automatically when I login.
I use the system settings to start it. This method works all the time.
I tick the autostart box in the qTox settings. This method works most of the time, but not always.

I deactivated the autostart in the system settings and ticked the box, but apparently qTox's autostart is not reliable. Now I deactivated the box and activated the autostart in the system settings again.

What exactly is happening when checking the autostart box in qTox on Ubuntu systems?

OS is Kubuntu 15.10.

**Comment by mikalehmann** [comment]
Okay, since both settings are using the same method to autostart the program, I am confused as to where the issue is coming from.
Before I deactivated qTox in the system settings, qTox was sometimes starting twice. That's where my confusion comes from.

**Comment by zetok** [comment]
On a77afca1ec8f86cda68fe7ba853f7e4d854c346f doesn't work for me under i3wm on Gentoo.

**Comment by ilovelinux** [comment]
I use AwesomeWM and no login manager. After tty login, I start Xorg server with `startx`. Autostart never worked for me. How autostart is supposed to work?

**Comment by Diadlo** [comment]
@ilovelinux For autostart on Linux qTox uses xdg

**Comment by ilovelinux** [comment]
https://wiki.archlinux.org/index.php/XDG_Autostart
Unfortunatelly AwesomeWM doesn't support XDG, but here's a manual way to do that: https://wiki.archlinux.org/index.php/Awesome#Autostart

**Comment by sudden6** [comment]
Original issue is ancient and 2nd issue seems fixed, closing.
