### ISSUE TITLE
filetransferwidget: Move buttons side-by-side.

### ISSUE THREAD

**Issue by Chiitoo** [qTox/qTox#2597]
Here's something I made for my builds:

![qtox_filetransferwidget_buttons_changed_01](https://cloud.githubusercontent.com/assets/9367616/11448122/b31d67dc-955a-11e5-9723-d155d08a6a36.png)

The background to this is that, due to the widget moving upwards after me sending more messages after a file, a friend often clicked 'cancel' when they wanted to 'accept'.

As it is, it might break the layout a bit, looking a bit odd, and it definitely doesn't need to be like in the picture above.  The point is to have the buttons side-by-side.  If nothing else, this does give a bit more room for the file-name and friends above.  ^^

That said, I was going to make the top-left corner of the left button rounded (pause in the image), so it would sort of play along with the 'Send a screenshot/Send file(s)' combo, but didn't get to it yet!

Thoughts?

**Comment by ProMcTagonist** [comment]
> due to the widget moving upwards after me sending more messages after a file, a friend often clicked 'cancel' when they wanted to 'accept'.

This has happened to me. Alternate possible solution: Maybe if you're moused over a filetransfer widget the chat shouldn't move on its own.

**Comment by SkyzohKey** [comment]
This widget waste space :x 
I personally found a workaround to have something more cool and modern on Ricin, maybe u could inspirate urself from this :)

![Ricin's file transfers demo](http://i.imgur.com/C3Bi9RD.png)

**Comment by ProMcTagonist** [comment]
Then you can't have thumbnails.

**Comment by linux-modder** [comment]
That client ui looks like crap to me but  honestly like the transfer widget
look even if it is  a bit larger

Corey W Sheldon
Freelance IT Consultant, Multi-Discipline Tutor
Ameridea LLC, Founder, CTO

## https://gist.github.com/linux-modder/ac5dc6fa211315c633c9

```
"Have no way as way, no limitation as limitation. One must never
```

underestimate the power of boredom...from which creativity and laziness are

## borne, which can spark great works of chaos and genius."

PGP: 0xe958c5d6718bf597 FP = 2930 99EB 083D D332 0752 88C4 E958 C5D6 718B
F597 linuxmodder@keybase.io
Tox: Corey84 || Linux-modder
9357BC6A5944A08AFC7D1EFFD61F6A73B9EABF8B2FB84ACF1DAC9A1A4D0A4705FFCCD0E5499B

**Comment by SkyzohKey** [comment]
[**@ProMcTagonist**](https://github.com/ProMcTagonist) commented on [28 Nov 2015, 02:05 GMT+1](https://github.com/tux3/qTox/issues/2597#issuecomment-160232604):

> Then you can't have thumbnails.

I also have thumbnails for inline images, it's just a different widget.

**Comment by zetok** [comment]
> The background to this is that, due to the widget moving upwards after me sending more messages after a file, a friend often clicked 'cancel' when they wanted to 'accept'.

Or you could just switch the position of those 2 buttons. i.e. to have `cancel` at the top, and `pause` on the bottom.

**Comment by agilob** [comment]
Please make a PR.

**Comment by Chiitoo** [comment]
Thanks for the comments!

I'll have to clean up a bunch of stuff before I'm able to, but will try to get into the request-making soon.

Switching their places would definitely be the least work, but it would open the possibility for accidentally accepting files, although it should certainly be less frequent of an occurrence.

**Comment by zetok** [comment]
@Chiitoo any update on this?

**Comment by Chiitoo** [comment]
Not yet, but I haven't forgotten about it!

I started playing around with the margins all over the client, and was going to look into this again after/together with that, but them margins are doing some pretty weird things, and as such, I haven't been able to fully make them do what I want yet.

That said, when I have the time and energy again, I think I'll look into this next.  There are some adjustments I will be wanting to make for it before I can consider a pull request out of it.
