### ISSUE TITLE
No longer get pictures for punctuation that should become emoticon

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2598]
I recently changed my "Theme" settings (I changed the size, the colour, and the smiley pack - though I changed the last two I listed back to their original values) and now that I have done so there seems to nothing I can do to make it so that when I type punctuation such as ":D" it becomes a picture of a smiley face. Though the menu which allows you to pick these different emoticons still works and I am able to send someone the picture of the emoticon like that, but if I send punctuation it does nothing and just stays as it is.

---

**OS Information:**

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:   wily
Flavour: GNOME
GNOME Version: 3.18
```

**Package Information:**

```
qtox:
  Installed: 259-db52ef6
  Candidate: 259-db52ef6
  Version table:
 *** 259-db52ef6 0
        500 https://pkg.tox.chat/debian/ nightly/release amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by ghost** [comment]
There are some icon packs that don't parse those symbols, see https://github.com/tux3/qTox/issues/2382#issuecomment-147190829

> Package Information

Could you post the commit hash (`Settings` -> `About`) and the icon packs you used instead, to see if others can reproduce.

**Comment by ghost** [comment]
This is the commit hash: `db52ef6e6a843faa8543b4726a5c281b8f1e1d97`

And the icon pack is "TwitterEmojiSimple", which in fact was the default (which seemed to make ":D" into an image), and although I did change it, I then changed it back, so other than the size settings, all of the other Theme settings such as the icon pack are what they were by default.

**Comment by ghost** [comment]
~~The commit doesn't seem to be part of this repo. Did you try with the official binaries?~~ You can just paste the hash string without format, that will link it to the commit.

Edit:

> when I type punctuation such as ":D" it becomes a picture of a smiley face

You mean in _your_ input area? I don't remember them being parsed before the message was sent.

**Comment by ghost** [comment]
All I know is that I've run this code to install qTox:

```
sudo sh -c 'echo "deb https://pkg.tox.chat/debian nightly release" | sudo tee /etc/apt/sources.list.d/tox.list'
wget -qO - https://pkg.tox.chat/debian/pkg.gpg.key | sudo apt-key add -
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install qtox
```

And I do regular checks for updates to my system and I have the latest version of qTox available to me through this medium.

**Comment by ProMcTagonist** [comment]
They don't become images inside the text box before you send them, as @kehugter said. 

Also, are you sure you're using a pack that shows images for text smilies? Which pack are you using?

**Comment by ghost** [comment]
I know that, I'm not meaning in my input area. I mean when they are sent, and this was working before with the same smiley pack. As I said before I am using the default smiley pack "TwitterEmojiSimple" which I changed to another pack but then changed back to, and since then, the smiley made of punctuation that I type have not worked.

**Comment by ghost** [comment]
Could you

> $ wget https://build.tox.chat/view/Clients/job/qTox_build_linux_x86-64_release/lastSuccessfulBuild/artifact/qTox_build_linux_x86-64_release.tar.xz
> $ tar xf qTox_build_linux_x86-64_release.tar.xz
> $ ./qtox

to see if the latests binaries solve the problem?

**Comment by ProMcTagonist** [comment]
TwitterEmojiSimple doesn't skin text smilies. That's why it's the simple version. TwitterEmojiSVG skins text emoticons. Switch to TwitterEmojiSVG if you want to skin text emoticons.

**Comment by ghost** [comment]
Well, it was what it was set on by default and it was producing them from punctuation... So perhaps the bug is instead that it displays "TwitterEmojiSimple" as the default when in fact it is a different pack which is selected?

**Comment by ghost** [comment]
> displays "TwitterEmojiSimple" [...] in fact it is a different pack which is selected

Can't reproduce.

**Comment by ghost** [comment]
Well, I'm not sure about this so much any more... But I reinstalled and the issue doesn't seem to be present any longer. So I am closing this issue, but if somebody is able to reproduce it again please do reopen it.
