### ISSUE TITLE
qTox needs a build maintainer on jenkins 

### ISSUE THREAD

**Issue by subliun** [qTox/qTox#2599]
@antis81 maybe you could do it?

**Comment by Zer0-One** [comment]
@antis81 interested?

**Comment by antis81** [comment]
Hope I have some more time tomorrow for reply…

**Comment by towlie** [comment]
Did something happen? Or why are you calling for it?

**Comment by agilob** [comment]
@subliun what are responsibilities? What do I need to do? Who manages deb packages for *buntu/debian?

**Comment by tux3** [comment]
I'm maintaining the builds for now so things can move forward, if someone wants to help, please leave a comment.

**Comment by antis81** [comment]
Thanks @tux3 :+1: - If there's some topics that concern building the deb packages I gladly help, but not maintain the whole thing.
