### ISSUE TITLE
Missing username in group chat

### ISSUE THREAD

**Issue by Vort** [qTox/qTox#2600]
I have encountered strange behavior while entered #tox-main-groupchat:
Nickname for one of the users was displayed incorrectly:
![qtox_missing_username](https://cloud.githubusercontent.com/assets/1242858/11452373/76004c04-95ee-11e5-8884-bfb675563f70.png)
This is not an empty name, as it is alphabetically preceded by "Andrew".
Also this name was not available with Tab-cycling.

**Comment by ghost** [comment]
Yup, you can't see those in uTox. They are not users with empty aliases, those are labelled as `Tox User`.

**Comment by Vort** [comment]
If this is a 'Tox User', why he is placed between 'A' and 'D'?

**Comment by ghost** [comment]
No, I meat it's _not_ a `Tox User`.

The problem is repeated aliases. In that snapshot there were 2 `Andrew`s. Here I duplicated `nintendo` twice

![snapshot2](https://cloud.githubusercontent.com/assets/6382342/11456733/f6cdafda-9692-11e5-97a5-77981a894cbc.png)

**Comment by ProMcTagonist** [comment]
So the bug is that repeated identical names aren't displayed?

**Comment by kehugter** [comment]
That's right.

**Comment by ghost** [comment]
That's right.
