### ISSUE TITLE
The ability to view the Tox IDs of your contacts - feature request

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2604]
I think that it would be really good if you could view the Tox IDs of your already made contacts.

**Comment by ghost** [comment]
Public key will be accessible again in #2547.

You're not supposed to retrieve the full Tox ID, because it changes over time. For a more detailed explanation see https://github.com/tux3/qTox/issues/235#issuecomment-54116176, among many others (https://github.com/irungentoo/toxcore/issues/1300).

**Comment by agilob** [comment]
Should we close it?

**Comment by tux3** [comment]
Since there's no resolution in sight for the full ID, and since we now show the public key, I think that's the best we can do for now.
