### ISSUE TITLE
The avatars of most of my contacts don't load for me most of the time

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2607]
I have recently noticed that the avatars for most of my contacts don't load most of the time, even though they are online, they can see their avatar, and most of them don't use encrypted profiles and thus don't have #2583.

---

**OS Information:**

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:   wily
Flavour: GNOME
GNOME Version: 3.18
```

**Package Information:**

```
qtox:
  Installed: 268-0ef39aa
  Candidate: 268-0ef39aa
  Version table:
 *** 268-0ef39aa 0
        500 https://pkg.tox.chat/debian/ nightly/release amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by agilob** [comment]
@tux3 was that fixed two days ago?

**Comment by tux3** [comment]
This should be fixed, if you still have this bug with you and your contacts on the latest qTox, please leave a comment.

**Comment by ghost** [comment]
With the latest update of qTox (402-f61332b) this bug is back. And I have asked a few people and they are getting this again too.

**Comment by hg8** [comment]
I am affected with this issue as well.

**Comment by ghost** [comment]
Since one of the latest updates, I no longer experience this issue, does anybody else experience this issue or can we close this now again?

**Comment by zetok** [comment]
From what I witnessed, some qTox versions were stripping my own profile avatar (#2583). Now I see it again, but only in my own qTox instance - the other one doesn't have it.
![muh avatar](https://cloud.githubusercontent.com/assets/3148759/12063925/03f8c336-afaf-11e5-9423-22525c21e220.png)

qTox 552155bd1f5824c536dd6d1bbc8d293f3f1d8499

I guess it should stay open?

**Comment by zetok** [comment]
Ok, here's an interesting thing on 26019c20e20ff6a9f1177bd56b665543126fed26:

`q1` instance didn't seem to have an avatar set (qTox removed it somewhere along the way), so I've set it again.

`q2` instance which didn't see the avatar (just the default image) upon receiving avatar from `q1`:

```
[15:54:12.344] src/core/corefile.cpp:285 : Debug: "Received avatar request 26:65536, reject, since we have it in cache."
```

↑ with that, `q2` still doesn't show avatar of `q1`, even though now `q1` has avatar set back.

**Comment by sudden6** [comment]
This seems not to be a problem anymore.
