### ISSUE TITLE
Why does qTox produce so much traffic?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2612]
I haven't compared it with other Tox clients, and it may just be a thing with Tox and not specifically the qTox client, but I was just wondering why there is always so much traffic being sent from my qTox client to loads of other domains and IP address and receiving roughly the same amount from all of them? Because I mean it's not like I have that many contacts, and most of them aren't even online... I'm not even talking to them or anything when all this traffic is going in and out... It is just doing it the whole time that qTox is on... So I am wondering why it needs to do this because I haven't seen this with other IM programs such as Skype, but maybe they don't work the same way?

I am running Ubuntu GNOME 15.10 with GNOME 3.18 and the commit hash of `268-0ef39aa` for qTox.

**Comment by suhr** [comment]
I believe this is a toxcore issue.
https://github.com/irungentoo/toxcore/issues/1251
