### ISSUE TITLE
Create .desktop file on install on Linux-based OSs - feature request

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2616]
I think that it would be really good if upon install on Linux-based OSs for a `.desktop` file to be created in the appropriate place for qTox so that one doesn't have to create it manually. And to do similar things for other OSs if needed if it is not already done for them.

**Comment by ghost** [comment]
#2530

**Comment by tux3** [comment]
I'm going to mark it as dup because #2530 will have the same resolution.
