### ISSUE TITLE
"Call duration" after one full hour is wrong

### ISSUE THREAD

**Issue by CydNoxzed** [qTox/qTox#2617]
If the call duration hits the one hour mark, the string shows just the seconds. After hitting the one hour and one minute mark, the call duration shows the hour/minute/seconds as expected.

Seen everytime on both sides of an video chat between: 
Windows 10: https://build.tox.chat/view/Clients/job/qTox_build_windows_x86-64_release/lastSuccessfulBuild/artifact/qTox_build_windows_x86-64_release.zip (download at sunday 2015-11-29; I'm hope that helps a bit)
Arch Linux 64bit: aur/qtox-git (commit 6a74799…)

Can someone verify this behaviour?

**Comment by RowenStipe** [comment]
Testing this now, will report back with results.

**Comment by RowenStipe** [comment]
I can verify this behaviour is present in https://github.com/tux3/qTox/commit/6a7479912ee3666e988f45f043a1b7f057512a96 codebase 

Video:
https://youtu.be/p1_9qpKVe04 - When it becomes 1hour long
https://youtu.be/p1_9qpKVe04?t=59 - When it becomes 1 hour and 1 minute long
