### ISSUE TITLE
Is message deletion supposed to work?

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#2618]
I have sent the message from Antox to qTox. Antox allows to delete the message, but qTox still sees it after it was deleted.

Is message deletion supposed to be working? If not, then this might be a bug in Antox that it offers this. But I would rather prefer to have the deletion and editing features, like Skype has.

**Comment by RowenStipe** [comment]
It's wracking my brain a bit where I got this information so I could source but editing a message is a limitation in Toxcore and currently isn't a feature in it and might not be for some time.

As for deleting a message I believe it's only on your side that the messages get deleted. I'm not 100% on the inner workings, but it would be like deleting a log file on your machine but your friend still has his own log of your conversations. 

If you're running both on the same machine and sending messages between the two then it's likely Antox is deleting it's copy of the message while qTox keeps it's own copy of the message.

I could be wrong and what I just said is completely inaccurate in which case someone correct me please.

**Comment by tux3** [comment]
Nope, it's not supposed to work. qTox won't delete messages after receiving them.
