### ISSUE TITLE
Group Chat Bugs: Not sure if bugs or me breaking things honestly

### ISSUE THREAD

**Issue by RowenStipe** [qTox/qTox#2619]
This was done on OSX 10.10.5 using a single qTox application on commit https://github.com/tux3/qTox/commit/6a7479912ee3666e988f45f043a1b7f057512a96 with -p to launch multiple profiles.

Across three terminals:

``` bash
~/qToxdir/qTox.app/Contents/MacOSqtox -p rowenstipe
~/qToxdir/qTox.app/Contents/MacOSqtox -p testingmctesterson
~/qToxdir/qTox.app/Contents/MacOSqtox -p testtest
```

Odd behavior noted
- User call list not updated when new user joins group call.
- User name randomly changed to Tox User in group chat locally after leaving a call.
- **User leaves group when they close qTox** - Noted that this happens even if I'm not running 3 users at once.
- User names not properly displayed in group calls.

Okay, I'll try to explain this one as best as I can.
1. `testtest` calls group `Test Chat!`
2. `testingmctesterson` joins the call and the call list is updated as expected.
3. `Rowen Stipe` joins call but is not updated on either `testtest` or `testingmctesterson`
   
   Both `testtest` and `testingmctesterson` can hear `Rowen Stipe` but their screens look like
   ![](http://imgur.com/xbwU8dk.png)
   _`testingmctesterson` showing `Rowen Stipes` profile pic when `Rowen Stipe` talks_
4. When `testingmctesterson` leaves and rejoins the conversation his conversation list is updated but doesn't list `Rowen Stipe` properly according to the display picture.
   ![](http://imgur.com/DWVoMXX.png)
   _AND get's their name on their side changed to `Tox User` in the group list_

`testtest` Doesn't see any of these changes happening, while `Rowen Stipe` sees everything like this.
![](http://imgur.com/DDHVao7.png)

**Comment by sudden6** [comment]
I can confirm this behavior.

**Comment by sudden6** [comment]
Group chats have changed a lot, probably not relevant anymore.

**Comment by anthonybilinski** [comment]
Of the 4 issues, not that
> User leaves group when they close qTox - Noted that this happens even if I'm not running 3 users at once.

Is still expected behaviour. Previously (at time of this report) closing qTox made you quit the group as Tox did not have persistent groups. Currently groups are saved, but still users appear to quit the group when they close qTox and re-join the group when they open it, because group members can not tell the difference between a peer going offline or quitting the group.

The other 3 issues I have not seen on current builds with fairly high usage of audio groups.
