### ISSUE TITLE
fix avatar issues with encrypted profiles

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2629]
Works but the encrypted avatar is still there if you unencrypt the profile. Why not remove it?
Same with all the avatars if you change the password.

And if encrypting unencrypted profile there are still the unencrypted avatars.

**Comment by tux3** [comment]
When changing our password, we should iterate over all our friends and ourselves, and save the avatars with the new password, then delete the old avatars if they were encrypted.

**Comment by JacobHenner** [comment]
While trying to investigate this, I ran into #2683. However, at one point after I changed the password I was prompted to enter the password for my logs, which was the original password, not the new one.

**Comment by JacobHenner** [comment]
So far I have fixed the password changing operation -- now changing the proper behaviour for resaving when the profile is set to not use a password. Ran into #2686, though.

**Comment by JacobHenner** [comment]
b1c8042 should fix the issue with re-encrypting the images when the password changes, but, it will not delete the old encrypted avatars if the user decrypts their profile, since the encrypted avatar can (currently, see #2686)  be shared with another profile.
