### ISSUE TITLE
auto update for OS X

### ISSUE THREAD

**Issue by iShift** [qTox/qTox#263]
On windows, every time your start uTox updater check for new version, many we can do same function in qTox for OS X ? (we can check version from github)

**Comment by dubslow** [comment]
Do Macs come with Python by default?

**Comment by tux3** [comment]
I'm pretty sure they do, although IIRC it's python2.X

**Comment by tux3** [comment]
I've started working on an auto-updater, for all platforms.
Although win32 first, since that's the only thing I have on my Jenkins.

**Comment by tux3** [comment]
Done.
