### ISSUE TITLE
Italian translation fix

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#2630]
English                                     Italian
"The passwords"                             "Le password"
"Autoaccept files from this friend"         "Accetta automaticamente i file inviati da questo contatto"
"Show details"                              "Mostra dettagli"
"Public Key"                                "Chiave Pubblica"
"Cut"                                       "Taglia"
"Copy"                                      "Copia"
"Paste"                                     "Incolla"
"Delete"                                    "Cancella"
"Select All"                                "Seleziona Tutto"
"Autoaccept files"                          "Accetta automaticamente i file"
"Open window"                               "Apri la finestra"

**Comment by ghost** [comment]
@tux3  What's the problem?

**Comment by tux3** [comment]
Sorry, I kind of dumped this into an issue without any explanation! Someone on IRC suggested these fixes to the Italian translation. I was going to apply them later if there's no objection.
I don't speak Italian, so don't take my word for it.

**Comment by ghost** [comment]
Everything is right, apply them.
