### ISSUE TITLE
Sound although Playback device is set to 'None'

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2632]
Hello,

Reproduce:
1. Download or compile latest qTox
2. Clear your ~/.config/tox directory so that the settings get reset to the default
3. Start qTox and create a new profile 'Alice' (do nothing else)
4. Start a second qTox instance and create a new profile 'Bob' (do nothing else)
5. Make friends (do nothing else)
6. Send a message from Alice to Bob or Bob to Alice
=> You should hear a sound notification because you got a new message although the playback and capture devices are set to 'None' (https://github.com/tux3/qTox/issues/2631).

Bizarrely, it goes away if you click around in qTox and you can't hear sound notifications anymore. But something is wrong here.

**Comment by JacobHenner** [comment]
Cannot reproduce after merging #2633, since qtox will now default to the first available audio device. The aforementioned behavior did not recur when both client playback devices were set to "None"
