### ISSUE TITLE
Exit and Quit options in Plasma 5 tray

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2634]
The tray icon menu in Plasma (5.4.2) displays a ~repeated action: qTox native "Exit" and the DE's "Quit".

I guess that it doesn't need to be so tho. For example, qBittorrent has a single quit entry both in Cinnamon and Plasma (qB's native one).

Is it necessary to have both? @agilob you mentioned it in https://github.com/tux3/qTox/pull/2524#issuecomment-154719994, but you don't seem to bothered.

**Comment by agilob** [comment]
> but you don't seem to bothered.

Not every KDE5 is affected. eg. @tux3 isn't. Don't know how to fix it. They do different things.

**Comment by ghost** [comment]
> They do different things.

Plasma's `Quit` is like a SIG _SOMETHING_ ?
The method of different, but the result is the same: qTox exits graciously.

**Comment by agilob** [comment]
No longer appears since yesterday on arch.

**Comment by sudden6** [comment]
doesn't seem to be a problem anymore

**Comment by ghost** [comment]
Had to remove KDE, can't confirm.
