### ISSUE TITLE
qTox Fails To Start

### ISSUE THREAD

**Issue by gitgud-software** [qTox/qTox#2635]
Error Message Reads:

qtox: error while loading shared libraries: libxcb-render-util.so.0: cannot open shared object file: No such file or directory

I'm installing the 32-bit qTox nightly (277-89def77) available through the apt repository on a Debian Jessie installation (#!++). Nightly version 265-1874c0c was working, this is the first time I've encountered this problem.

Seems a shared library moved or became incompatible?

**Comment by agilob** [comment]
Could you try `./simple_make.sh` ?

**Comment by tux3** [comment]
@gitgud-software Post the content of your APT sources.list please

**Comment by dcharles525** [comment]
Same error on eOS, only happened after update!

qtox: error while loading shared libraries: libxcb-render-util.so.0: cannot open shared object file: No such file or directory.

**Comment by g4bb4j03** [comment]
Hi,
I had the same issue on my xubuntu 14.0.4.03 LTS. After I start with the missing libcb-render-util.so.0 It turns out that some more libxcb- packages where missing. After some tries I installed the following packages to get qtox starting again:
libxcb-render-util0 libxcb-image0 libxcb-icccm4 libxcb-randr0 libxcb-keysyms1 libxcb-xkb1 libxkbcommon-x11-0

My qTox version:

```
Name                                       Version                    Architecture               Description
qtox                                       310-cb8b9dc                amd64                      The best Tox client.
```

My apt sources:

```
cat /etc/apt/sources.list.d/tox.list
deb https://pkg.tox.chat/debian nightly release
```

Cheers!

**Comment by tux3** [comment]
I updated those packages, they should have the libxcb dependencies now. Please try again and report if it works.

**Comment by g4bb4j03** [comment]
Hmm no new package available in the repo as soon as the repo got update I will report.

**Comment by g4bb4j03** [comment]
the new package has now the correct dependences:

```
dpkg-query -s qtox
Package: qtox
Status: install ok installed
Priority: extra
Section: default
Installed-Size: 35447
Maintainer: Project Tox <support@tox.chat>
Architecture: amd64
Version: 357-d6473d6
Depends: libx11-xcb1, libsm6, libice6, libxcb1, libglib2.0-0, libstdc++6, libxcb-render-util0, libxcb-image0, libxcb-icccm4, libxcb-randr0, libxcb-keysyms1, libxcb-xkb1, libxkbcommon-x11-0
Conflicts: qtox-unity, qtox-qt5.4.2
Description: The best Tox client.
License: GPLv3+
Vendor: Project Tox
Homepage: https://tox.chat
```
