### ISSUE TITLE
Avatar don't load

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#2638]
in new build (b618316271b9bdaf529f8a37b21ea09cfb8d863c)
some avatars are not loaded

in old build all avatar loaded correctly (5b42b9984b52fb5ec19a8c144086c19b9061e7b6)

**Comment by tux3** [comment]
Whose avatars, yours or a contact?
Is it on an encrypted profile?
Can you post the log?

**Comment by PKEv** [comment]
lost avatar one of contact
profile not encrypted 
log file don't have any comment about this situation

When reloading an older version, contact the avatar is downloaded correctly from the database

**Comment by PKEv** [comment]
in bd avatar and hash:
![default](https://cloud.githubusercontent.com/assets/6053197/11666669/b165f588-9dfe-11e5-864f-a3d87baa114c.png)

**Comment by PKEv** [comment]
Avatars are not currently read from the database?

then - No automatic loading avatar
1. Remove all avatars in the folder 
2. when you connect to the contact - avatar not loading 
from log:

```
 src/core/corefile.cpp:337 : Debug: onFileControlCallback: Received pause for file  1 : 0
```

**Comment by agilob** [comment]
@PKEv I had the same problem a few days ago (~3), could you try recompiling toxcore?

In my case I installed toxcore from running `./bootstrap.sh` as sudoer.

**Comment by PKEv** [comment]
I build in win 7 32x

I can try but not before the weekend

**Comment by tux3** [comment]
@PKEv What client is your friend using?

**Comment by PKEv** [comment]
qTox, too

**Comment by tux3** [comment]
This should be fixed now, but both you and your friend need to update to make sure it works. Please leave a comment if you still have this bug with both you and your contact on qTox.

**Comment by PKEv** [comment]
@tux3 
Why rejected the idea of storing avatars in the database?
It plans to implement a single repository?

**Comment by tux3** [comment]
@PKEv The database isn't meant to store large blobs of data. The filesystem is much better at this, and this allows us to share cached avatars with other clients.

**Comment by PKEv** [comment]
open ID friends are not good...
avatars can rename randomly so as not to keep them open

**Comment by tux3** [comment]
We hash the name of avatars and encrypt them if you have an encrypted profile, so it's not really open

**Comment by PKEv** [comment]
And the picture itself? suddenly there Photo...
As I understood after attempts to encrypt a database - the current encryption algorithm can not handle blob 
Maybe better:
It can use third-party library to work with the database such as SQLCipher
( https://github.com/sqlcipher/sqlcipher )

**Comment by tux3** [comment]
The picture itself is encrypted if the profile is encrypted.
SQLCipher is what I'm going to use, but the first priority was making avatars _actually work_.
