### ISSUE TITLE
Change qTox versioning

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2644]
Hello,

I would like to suggest a change in the qTox versioning concept.
The latest version is currently qTox 1.2 -> https://github.com/tux3/qTox/releases

For me, qTox isn't stable yet. There are a lot of open issues, some with security problems and instability. And toxcore isn't stable as well.
I think there are a lot of people who could think that qTox is stable and proven when they look at the version '1.2'.

So my suggestion is to use something like 0.1.2 at the moment. 
The first stable release should be 1.0.0.

Any thoughts about it?

**Comment by agilob** [comment]
A lot of (most?) issues are "I would like qtox to", which will not be resolved in near future. Critical and UI/UX bugs go first. Also a lot of issues are duplicates which weren't closed. Like this one, versioning was suggested somewhere...

**Comment by ghost** [comment]
Do those releases even mean something?

**Comment by agilob** [comment]
afair I was introduces when toxcore was announced to be stable soon... It doesn't.

**Comment by ovalseven8** [comment]
My suggestion is something like this:

Version `x.y.z`

`x` -> Major release with big changes or even API changes
`y` -> For new features or other small but important changes
`z` -> Bug fixes, patches and other small changes

From now on let's make **qTox 0.1.0**.
The first stable version should be **qTox 1.0.0** then.

But the stable version shouldn't be used before:
- qTox is almost feature complete (perhaps after the new groupchats are done and implemented)
- All open security/anonymity issues are done
- All other important issues are done (labelled with 'high' and 'very-high' or some with 'medium')
- qTox is running stable in general and software distribution for Linux, Windows and MacOS is reliable

> In the closed-source world, Version 1.0 means "Don't touch this if you're prudent."; in the open-source world it reads something more like "The developers are willing to bet their reputations on this."

from http://catb.org/~esr/writings/homesteading/homesteading/ar01s13.html

**Comment by tux3** [comment]
Note that jumping backwards in version would break some things, like the packages, and be super confusing when we reach the same versions again later on.

**Comment by ghost** [comment]
What does versioning accomplish that commit hashes don't at this stage of development? Should almost every commit be `z++`? Will there be a table of conversion to know which commit to look for when a user reports a bug in version `0.1.2134`?

**Comment by tux3** [comment]
Versions are tags attached to a particular commit, you can always see [here](https://github.com/tux3/qTox/releases) or directly on git what commit the versions correspond to.

What the versions accomplish is that I can merge all kinds of things in master, but only release a new version when there's a well-tested non-buggy change ready to be released to the world.

For example we're at 1.2 now, when we merge #2509 it's possible we'll discover a couple new bugs and regressions that we'll have to fix, but once that's done it'll bring plenty of fixes and we can tag that 1.2.1.

qTox has bugs being fixed and created all the time, the versionned releases will help make sure people only see bugs being fixed, not being created.

**Comment by ghost** [comment]
I see, thanks for the explanation. I just didn't see any gain in versions, because users are encouraged to use nightly anyway.

**Comment by tux3** [comment]
Users are encouraged to use stable versions now :)
The links all point to the stable installer and the updates are all stable. If you want nighlies, you can still get them but you have to go look on Jenkins.

**Comment by ovalseven8** [comment]
> The links all point to the stable installer and the updates are all stable. If you want nighlies, you can still get them but you have to go look on Jenkins.

That's a great improvement. I like it that the users don't get nightlies anymore. Moreover, I think it's enough that nightlies are only available via Jenkins.

> Note that jumping backwards in version would break some things, like the packages, and be super confusing when we reach the same versions again later on.

Another reason why we should change the versioning system as soon as possible. ;)
If we do it now, it will work. But if we do it later, we'll have much more problems...

**Comment by rugk** [comment]
> If we do it now, it will work. But if we do it later, we'll have much more problems...

The problem is already there, so you cannot change it now.

Usually you should always keep to **[semantically versioning](http://semver.org/)**. Just keep to it and do not invent other strange versioning systems.
However as this was already broken when the [Windows version was released](https://github.com/tux3/qTox/issues/2085) it is not advisable to go backwards with the version numbers.
The only thing I'd suggest is keeping to semantically versioning _now_ and release all further versions in this way.

**Comment by ovalseven8** [comment]
Well, you would have to fix some issues. But it would be possible.

In need, I could get to like something like **1.2.1-alpha**. That should definitely be possible.

**Comment by rugk** [comment]
> In need, I could get to like something like 1.2.1-alpha. That should definitely possible.

Yes in semantically versioning you can label pre-release versions like this. See `11.` in their spec.

**Comment by ovalseven8** [comment]
Well, no. 1.2.1-alpha is a bad idea because it seems like 1.2.1 will be released later.

So, 0.y.z is the best solution...

**Comment by rugk** [comment]
1.2.1 [is already released](https://github.com/tux3/qTox/releases/tag/v1.2.1). :smiley:

**Comment by ovalseven8** [comment]
Yes, of course. I mean if we would change it to 1.2.1-alpha.
