### ISSUE TITLE
Add zipped portable qTox version

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#2650]
If I want to install it on a usb key, it is annoying because it create a start menu entry, it also create an entry so it can be uninstalled in windows thingy. And if it was zipped it would be more convenient to "install".

**Comment by sudden6** [comment]
You can just extract the two files from the setup file with 7zip. Although it shouldn't be hard to also provide a zip on the servers.

**Comment by tux3** [comment]
I could add a portable qTox .zip with everything included, how does that sound?

**Comment by TheNain38** [comment]
@tux3 This is what I asked, thanks.
You could also add a config file with already the portable option checked?

**Comment by tux3** [comment]
Good idea

**Comment by rugk** [comment]
So can anyone rename this issue to "Add zipped portable qTox version"? I think this is essentially what this issue is about. :smiley:

**Comment by sudden6** [comment]
zip files for qTox are provided in newer builds.

**Comment by anthonybilinski** [comment]
re: the general issue of portable builds, duplicate of #4916
