### ISSUE TITLE
"qtox-updater.exe": When qTox is launching qtox-updater.exe it says my computer don't have "libgcc_s_seh-1.dll" on my system

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#2652]
And now, I can't start qtox... I need to reinstall

**Comment by towlie** [comment]
@tux3 You can solve this by using the static link commands used by the qtox build.

**Comment by tux3** [comment]
I solved it by shipping the DLL with the installer instead

**Comment by TheNain38** [comment]
@tux3 Why it isn't better to link it statically? So you have only two file?

**Comment by tux3** [comment]
Since qtox.exe and qtox-updater.exe use the same libraries, if we link them statically they both have a copy of everything. This makes everything bigger than it needs to be.
I'd like to go back to dynamic linking when possible.

**Comment by TheNain38** [comment]
Ah, they use the same libraries? Ok, I didn't know that...

**Comment by tux3** [comment]
Ok, this should be fixed now.

**Comment by TheNain38** [comment]
It is fixed indeed
