### ISSUE TITLE
Ugly qTox icon on Windows

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2654]
Hello,

just installed qTox on Windows 10 and saw that there is that ugly icon and without any changes if you change your status (online, away, ...).
![Screenshot](https://cloud.githubusercontent.com/assets/8258609/11761350/be431ace-a0bf-11e5-8e03-162fb98c2ce1.png)

The one small icon (top left) if you hover the qTox icon is fine and also with any changes (new message, status changes, ...)
![Screenshot 2](https://cloud.githubusercontent.com/assets/8258609/11761388/19ab077c-a0c1-11e5-9700-653ecadd5de9.png)

**Comment by NoxNoctium** [comment]
agilob wanted to fix this behavior, as the other issue is labeled P-low I guess he didn't have the time to do it yet.
also related to the discussion in https://github.com/tux3/qTox/issues/2246 imo.

**Comment by agilob** [comment]
@markus1540 we didn't get SVG and I don't have windows

**Comment by NoxNoctium** [comment]
The issue he describes isn't related to the icon as it worked properly for some time, if you pin the icon once to the taskbar and unpin it again the correct icon is shown, including the status indicator.

**Comment by ghost** [comment]
#1927
#2210 some comments related

**Comment by tux3** [comment]
This is actually a dup of #1927 and I'll be deploying a fix very soon.
