### ISSUE TITLE
qTox updater: it should verify that the "new" version is really the more up to date version, not an older one that is already installed

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#2656]

**Comment by tux3** [comment]
No, that's by design. The updater will always bring you to the last stable release, even if you're on a nighly or even a release you compiled yourself.
If you want to use nightlies, you should disable the "Check for updates" option since we don't ship nightly updates.

**Comment by TheNain38** [comment]
That's ok, I was thinking that was intended to bring to the latest stable release.
