### ISSUE TITLE
qTox lacks a User Guide

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#2657]
qtox currently doesn't have any form of userguide documenting it's features and functions. Although I think qTox is pretty intuitive to use in the basic features like chat, voicechat and videochat, many great and unique features are unknown due to the lack of documentation.

To solve this problem, write a:
- **very short (1 page) intro, covering how to:**
  - add someone as a friend
  - make a call
  - make a videocall
  - send files
  - change audio and video devices

targeted at my grandma ;)
- **full explanation of**
  - all the settings
  - list of shortcuts
  - multi-window mode
  - using profile encryption
  - importing exporting profiles
  - groupchats

targeted at power users but non programmers

and ship them as html file or webpage.

**Comment by suhr** [comment]
A user guide doesn't fix broken UX and is almost useless with a proper one.

**Comment by ovalseven8** [comment]
I don't think that qTox's UX is broken. But at my point of view, we should wait until qTox is more stable before creating a User Guide. Otherwise, we would have to change the Guide very often and that's duplicate work then.

But yes, we definitely need an User Guide eventually.

**Comment by suhr** [comment]
> I don't think that qTox's UX is broken.

But it is. For example, settings are completely mess.

**Comment by sudden6** [comment]
> I don't think that qTox's UX is broken. But at my point of view, we should wait until qTox is more stable before creating a User Guide. Otherwise, we would have to change the Guide very often and that's duplicate work then.

I think it's time to start now, because else we create a chicken egg problem: features of qtox are not tested, because they are unknown, qtox never gets stable, because it's untested.

> But it is. For example, settings are completely mess.

I don't think just cleaning up the settings will help anyone to understand them.

**Comment by tux3** [comment]
A guide is a nice idea, people don't really bother to read guides for all the software they have, but it's always nice to have.

Would it be helpful if we had some in-app animated tour that shows you the basic features, like Firefox does from times to times? 
These things generally annoy me because I already know how the features work, but it could help people get started with the basics. For example many people never found you can click your avatar to go to your profile page! That's bad UX.

**Comment by sudden6** [comment]
> people don't really bother to read guides for all the software they have

I fully agree with this, but a guide would serve as a base to spread knowledge by mouth i.e. users telling users about "The cool new stuff".

> Would it be helpful if we had some in-app animated tour that shows you the basic features, like Firefox does from times to times?
> These things generally annoy me because I already know how the features work, but it could help people get started with the basics.

I don't like them too and I think they are almost as often ignored by the users as manuals are.

Maybe a short video tutorial on the download page would be helpful?

**Comment by ghost** [comment]
> in-app animated tour

I like that idea. If it's hard to implement, there are plenty of JS libraries for tours. The tour could be on still or animated qTox snapshots. That has also the advantage of displaying the client before the user has to download anything.

http://github.hubspot.com/shepherd/docs/welcome/
http://bootstraptour.com/
https://easelinc.github.io/tourist/
etc

**Comment by sudden6** [comment]
Since there were basically no objections, I went ahead and started a user guide for advanced users here https://github.com/sudden6/qTox/tree/usermanual/doc .

I want to get it in a usable form over the next few weeks and then submit a pull request.

Everybody is happily invited to join and enhance the guide. It's just plain html and the formatting should be very clear.

**Comment by Zer0-One** [comment]
@sudden6 have you considered using [Gitbook](https://www.gitbook.com/)?

**Comment by sudden6** [comment]
@Zer0-One no, never heard of it. As far as I can tell this uses markdown.

The reason for plain html was, that nearly every device can display html properly, markdown not so much.

**Comment by zetok** [comment]
@sudden6 The problem with HTML is that it's hard to edit and read for someone who doesn't really know it. (i.e. users)

Markdown should be easier to edit.. and AFAIK, if you want, you can generate html pages from markdown.
E.g. that's how Rust docs are made: https://github.com/rust-lang/rust/tree/master/src/doc → https://doc.rust-lang.org/stable/book/

Easy markdown for editing, HTML that can be displayed ~everywhere, and no reliance on proprietary gitbook.

As for the docs - it's really great that you've started `:)`

**Comment by sudden6** [comment]
@zetok 
I don't think HTML is that much harder to edit. Also it is easily possible to see how the formatting turns out, if you open a browser in a second window.

That said, if the majority wants markdown, I will switch to it, but for now my focus is on the content, not on the styling.

**Comment by zetok** [comment]
> I don't think HTML is that much harder to edit.

Hard enough to e.g. discourage me from contributing to guide.

Just saying.

**Comment by antis81** [comment]
> That said, if the majority wants markdown, I will switch to it, but for now my focus is on the content, not on the styling.

That's actually the strongest argument to use markdown, because it is focused on content, not style. :)

**Comment by sudden6** [comment]
> > but for now my focus is on the content
> 
> That's actually the strongest argument to use markdown, because it is focused on content, not style. :)

@antis81 my emphasis was on _for now_, but I think that wasn't noticeable :)

From my point of view Markdown has only disadvantages over HTML:
- it needs an extra program to view not everybody has
- basic HTML syntax is as easy as MD

**Comment by suhr** [comment]
@sudden6 
Markdown have some advantages:
- It's easy to read, just like plaintext
- It's easy to edit without having EMACS installed

**Comment by antis81** [comment]
@sudden6 Did you ever try to write more than 3 lines of documentation with HTML?

You really think, that this…

``` html
<html>
<header/>
<body>

<ul>
<li>Item 1<li>Subitem 1</li></li>
<li>Item 2</li>
</ul>

<table>
<th><td>This is</td><td>a simple table</td></th>
<tr><td>with just one header</td><td>and two columns</td></tr>
</table>

</body>
</html>
```

… is easier or better to write and edit than this?…

``` markdown
* Item 1
    * Subitem 1
* Item 2

This is | a simple table
---- | ----
with just one header | and two columns
```

The rendered result both looks like this:
- Item 1
  - Subitem 1
- Item 2

| This is | a simple table |
| --- | --- |
| with just one header | and two columns |

---

Note:
This is just a 3 items list and a little table with just a header and a single row. Feel free to write a paragraph and some documentation text to get a feeling.

And the best thing is: **You will get HTML as a result!**

All you will need to edit markdown files is a modern text editor. Create `myfile.md` files in a folder structure and just start off writing.

I recommend setting up a Wiki like [DokuWiki](https://www.dokuwiki.org/dokuwiki#), which also supports markdown.

Another solution, that is probably even suited better for our needs is [Jekyll](http://jekyllrb.com), which is a static webpage generator written in :gem: Ruby. Both solutions will render HTML as output, but you never have to touch it.

Good luck :)

**Comment by sudden6** [comment]
I still don't like markdown, but since the majority wants it, I reformatted it to markdown.
https://github.com/sudden6/qTox/tree/usermanual2

There are A LOT of TODOs in it, so please help me removing them.

**Comment by antis81** [comment]
@sudden6 :+1: Do you have a PR?

**Comment by sudden6** [comment]
I will do one, but under [WIP] tag, because there are some TODOs where I don't know the answer of.

**Comment by Diadlo** [comment]
What you think about using echobot for teach first four points?
- add someone as a friend
- make a call
- make a videocall
- send files

**Comment by zetok** [comment]
> What you think about using echobot for teach first four points?

I don't think that this is a good idea.

**Comment by Diadlo** [comment]
> I don't think that this is a good idea

Have you any reasons?

**Comment by zetok** [comment]
If network is going to be involved, then it should scale, and be reliable, neither of which echobot provides.
