### ISSUE TITLE
Use hosted.weblate.org as translation service

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#2661]
What do you think about it? weblate makes it very easy to translate any application, they host if for free for you if project is opensource.

It supports discussion about translations, automated translations for common strings, feedback about changes and email notification if text changes in source code.

**Comment by tux3** [comment]
Why not, if it makes things easier for translators I'm all for it.

**Comment by agilob** [comment]
It makes translations much easier, I used it for a few months now, it's very easy, comfortable to work with as translator and PM

**Comment by tux3** [comment]
@agilob Do you know how to set it up?

**Comment by agilob** [comment]
You tux3, make an account, make a project request, where you provide license, link, and path to translation files. They add your project in less than 3 days. Then [instructions for github are here](https://docs.weblate.org/en/latest/admin/continuous.html#pushing-changes-to-github-as-pull-request), I used gitlab. User @weblate will make PR to qtox, you can see how many project are already there.

**Comment by tux3** [comment]
I sent a request.

**Comment by agilob** [comment]
:+1:

**Comment by tux3** [comment]
We're now at : https://hosted.weblate.org/projects/tox/qtox/

**Comment by ghost** [comment]
How _official_ is this? ie, do we stop sending PRs for translations immediately or will both methods be accepted during a transition phase?

In the first case, the wiki should be updated asap.

**Comment by agilob** [comment]
> How official is this? ie, do we stop sending PRs for translations immediately or will both methods be accepted during a transition phase?

Both are totally fine. weblate receives signals when you edit translations files in repo and commits when you finish translating.

I finished Polish translation, there are some wired strings in context files... 'Lorem'? 'NASA manager'?

**Comment by tux3** [comment]
> there are some wired strings in context files... 'Lorem'? 'NASA manager'?

Ahh, ignore that, it's the abandoned Android GUI using placeholder text...
