### ISSUE TITLE
qTox is stable: Display error

### ISSUE THREAD

**Issue by rugk** [qTox/qTox#2668]
In https://github.com/tux3/qTox/issues/2644 [**@tux3**](https://github.com/tux3) commented on [12. Dez. 2015, 16:37 MEZ](https://github.com/tux3/qTox/issues/2644#issuecomment-164161844):

> Users are encouraged to use stable versions now :)  
> 
> The links all point to the stable installer and the updates are all stable. If you want nighlies, you can still get them but you have to go look on Jenkins.

Oh, thanks for telling this _along the way_. :dizzy_face: 

But, seriously, if this is the case you should at least display the version correctly and not state any more that this is a alpha version:
![qtoxstable](https://cloud.githubusercontent.com/assets/11966684/11767017/515a6616-a19f-11e5-9fdd-2162f1e40b6c.PNG)

**Comment by tux3** [comment]
@rugk Where did you download qTox to get this version?

**Comment by rugk** [comment]
The installer. Where else?

**Comment by rugk** [comment]
Now installing it again (setup-qtox.exe: `f1ef6ae060b8d5f0055cbb570a6f3af7cc0cf5076e521e8125c280a53f7bec2a`) and it looks better:
![abitnicer](https://cloud.githubusercontent.com/assets/11966684/11767049/a3aaa1e6-a1a0-11e5-9d97-7e66322881da.PNG)

However at the first start I got another update message (although this obviously should be the latest version). After I clicked "Yes" to download the update it was downloaded in a few seconds (I doubt that it really downloaded something) and after a qTox restart I got the message that `qtox-updater.exe` crashed (the usual Windows message: `qtox-updater.exe must be closed` and the offering to use the compatibility mode afterwards).

**Comment by rugk** [comment]
As the updater has nothing to do with this issue, I've created a new one: https://github.com/tux3/qTox/issues/2669

**Comment by tux3** [comment]
Okay, you must have had an old installer, because the new ones always show the right version now.
