### ISSUE TITLE
qTox updater is unstable

### ISSUE THREAD

**Issue by rugk** [qTox/qTox#2669]
Continuing from https://github.com/tux3/qTox/issues/2668#issuecomment-164255433:

> However at the first start I got another update message (although this obviously should be the latest version). After I clicked "Yes" to download the update it was downloaded in a few seconds (I doubt that it really downloaded something) and after a qTox restart I got the message that `qtox-updater.exe` crashed (the usual Windows message: `qtox-updater.exe must be closed` and the offering to use the compatibility mode afterwards).

qTox v1.2.1

**Comment by DeerSpotter** [comment]
i can confirm on Windows that this also happens to me. What i found that worked is update it 2 times force restart update, restart, update, restart, press no to update, restart and walla.

**Comment by zetok** [comment]
@DeerSpotter same qTox (updater) version, or..?

**Comment by zetok** [comment]
It might be fixed in newest 1.4.1 release, care to re-test?

**Comment by rugk** [comment]
It is working now.
