### ISSUE TITLE
Windows: Icons in file properties displayed incorrectly and too less sizes

### ISSUE THREAD

**Issue by rugk** [qTox/qTox#2671]
Just right-click on `qtox.exe` or `qtox-updater.exe` and choose `Properties`:
![propertiesicons](https://cloud.githubusercontent.com/assets/11966684/11767100/7ad32cbe-a1a2-11e5-8d53-1c2cbcbbceef.PNG)

This grey part does not look nice. :smile: 

v1.2.1

**Comment by rugk** [comment]
I also see what causes this issue: You only include the 64x64 px icon.
![qtox icon](https://cloud.githubusercontent.com/assets/11966684/11767107/b2a85808-a1a2-11e5-9dc2-f42578efe756.PNG)

This is not good and I'd recommend you to include all usual icons sizes\* from 16x16px to 256x256px.

If you want you could also add icons for different colour depths (8bit color and so on). As the tox icon does not have so many colours there should be no problem. :wink: 

*which means: 16x16, 24x24, 32x32, 48x48, 128x128 and 256x256

**Comment by NoxNoctium** [comment]
so yeah uh, it's a try.
![pic](https://i.imgur.com/1grAng3.png)
combined it with the ideas from https://github.com/tux3/qTox/issues/2246 and added a seperate updater icon.
the outline doesn't scale too 'pretty' though, opinions?

ico files here: https://docs.google.com/uc?id=0B4hJgknPmitzdDBPLVV1cUZQZHM

**Comment by rugk** [comment]
Okay, the downloader icon looks nice. :smiley:

**Comment by rugk** [comment]
@tux3 BTW: Is this really only Windows? I mean I only tested it on Windows, but how are the icons for other OSes added?

**Comment by NoxNoctium** [comment]
OSX uses it's own proprietary format, linux usually supports svg, so yeah.
Usually the icon is replaced by one with a status indicator, that behavior is currently broken in windows.
Included icon sizes and color depths are the same as in the Windows 10 explorer.exe, would also need feedback there.

**Comment by agilob** [comment]
> OSX uses it's own proprietary format, linux usually supports svg, so yeah.

I love that "usually" :D I spent 5 hours experimenting with SVGs as tray icon :D
