### ISSUE TITLE
Provide option to enable TCP-relay

### ISSUE THREAD

**Issue by Zer0-One** [qTox/qTox#2681]
qTox should expose an option to enable toxcore's TCP-relay functionality.

**Comment by tux3** [comment]
A long time ago, IIRC the consensus was that random clients were potentially too unstable and low bandwith to be relays, did that change?

If we ship settings for complicated sounding toxcore-specific technical details, people will probably not use them as intended.

A command line flag to start as a TCP relay, maybe.

**Comment by gitbugged** [comment]
Bumping this old bug since I was about to open a ticket for it. I would like to help grow the tox network as well to prevent centralization. The option should obviously be optional, but since I leave the computer running all the time it could help the network a lot. It could be under "Advanced". 👍 @zetok ?

**Comment by jessica181920** [comment]
I was under the impression that by being connected to the network I was helping the network by being a relay/node. A low bandwidth one, but a minor volunteer nonetheless. I don't know enough about the tox network to know if it would somehow be more harm than good, but I don't see how this would be a bad addition.

**Comment by JFreegman** [comment]
> I was under the impression that by being connected to the network I was helping the network by being a relay/node. A low bandwidth one, but a minor volunteer nonetheless. I don't know enough about the tox network to know if it would somehow be more harm than good, but I don't see how this would be a bad addition.

Your client defaults as a node in the DHT network, but not a TCP relay, which is much more bandwidth heavy and not suitable for average users.
