### ISSUE TITLE
Distinct profiles store avatars using same filename but different encryption key.

### ISSUE THREAD

**Issue by JacobHenner** [qTox/qTox#2686]
If the user is running multiple qTox instances on different profiles with different passwords, the avatars for mutual contacts will be stored using the same filename, which is generated in profile.cpp by `crypto_generichash((uint8_t*)hash.data(), hashSize, (uint8_t*)idData.data(), idData.size(), nullptr, 0);`. 

However, since each image is encrypted for the individual user, only one will be able to successfully open the avatar, and the other instances will emit `[22:11:49.024] src/core/coreencryption.cpp:88 : Warning: Decryption failed` and attempt to reobtain the image.

**Comment by JacobHenner** [comment]
I can change the call which generates the hash to include a key based on the user, but that would invalidate all current avatars (and they would not be automatically deleted). Is that alright? @tux3

**Comment by tux3** [comment]
> I can change the call which generates the hash to include a key based on the user, but that would invalidate all current avatars (and they would not be automatically deleted). Is that alright?

Sounds good to me.
