### ISSUE TITLE
Reconnect button cancels contact list filtering

### ISSUE THREAD

**Issue by LittleVulpix** [qTox/qTox#2692]
Latest qtox ( 3717b5c98d97e95b64590263204e5e403829568b )

Replicate issue:
1) Go online->select "show only online contacts"->only online contacts are visible.
2) Go to options-> general -> connection settings -> click "reconnect"
3) contact list is populated as if no filter was selected, but filter selection is still displayed up top. Selecting the same option as you had previously will reapply contact list filtering

Expected:
Contact list filtering/sorting is preserved throughout reconnection.

**Comment by sudden6** [comment]
Doesn't seem to happen in https://github.com/qTox/qTox/commit/bdbf2b461bd2fde5c2cc00fca364f76e5b448356 anymore.
