### ISSUE TITLE
Change or remove advanced settings

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2696]
Hello,

since the merge of the new database and history code a few hours ago, the database sync options in the advanced settings have been removed. Good decision!

Nonetheless, we have to change the advanced settings now or remove it. 
It looks quite forsaken. The important note and 'Reset to default settings' are useless, now.

My suggestion is to move the connection settings from 'General' to 'Advanced'. So, the General tab gets a little bit more lightweight and connection settings are actually advanced settings.

![2015-12-19-110811_1366x768_scrot](https://cloud.githubusercontent.com/assets/8258609/11912539/23bffbd4-a641-11e5-9288-4c5e3eaffdfe.png)

**Comment by sudden6** [comment]
I suggest splitting up the General tab a little more would also be useful. Move "Chat" and "Theme" to their own tabs, "Connection Settings" to "Advanced". Then remove the "General Settings" headline.

**Comment by suhr** [comment]
> "Connection Settings" to "Advanced"

Better “Connection Settings” → “Network”.

**Comment by zetok** [comment]
Related issue: #1069

**Comment by Diadlo** [comment]
Changed in #3457
