### ISSUE TITLE
"login automatically" doesn't work

### ISSUE THREAD

**Issue by ryzhikgagarin** [qTox/qTox#2698]
"Login automatically" doesn't work. 
Every time I boot my system I have to login qtox manually. 

qTox version v1.2-87-g3b82e73.
Ubuntu 14.04.03 lts

**Comment by ovalseven8** [comment]
Has your profile a password?
Because the feature is just working if you haven't set a password.

**Comment by ryzhikgagarin** [comment]
Thanks. Yes, it has. 
How to turn off my password?

**Comment by ovalseven8** [comment]
Click on your avatar on the top left corner. Now, scroll down and you should see a button called 'Remove password'.
