### ISSUE TITLE
qTox is creating useless text file(s) in /avatars

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2699]
Hello,

Reproduce:
1. Clear your ~/.config/tox
2. Create a new profile (without password)
3. Set a password
4. Now, in the /avatar directory, there's a text file.

or:
1. Clear your ~/.config/tox
2. Create a new profile (with password)
3. Remove the password
4. Now, in the /avatar directory, there's a text file

**Comment by tux3** [comment]
Fixed by 40ddf81fd1773b0d823d4028bd5ae4f2a13871cf

Those files shouldn't be created anymore. Note that the existing empty "text files" will only disappear when you open the qTox profile responsible for them.

**Comment by ovalseven8** [comment]
Please reopen.
It's not fixed yet.
