### ISSUE TITLE
Getting error when running on Linux

### ISSUE THREAD

**Issue by dcharles525** [qTox/qTox#270]
error while loading shared libraries: libopencv_core.so.2.3: cannot open shared object file: No such file or directory

**Comment by dubslow** [comment]
Where did you get your executable?

If you got it from Jenkins, then you'll probably need to install the "libopencv-core" package with your package manager. (On my system, the specific package is "libopencv-core2.4".)

**Comment by tux3** [comment]
That's a problem with Jenkins, I can't fix it unfortunately.

Try installing OpenCV 2.3 with your package manager. You could also try compiling qTox from source (see the INSTALL.md), or try yelling at NikolaiToryzin on #tox-dev @ irc.freenode.net

**Comment by dcharles525** [comment]
@dubslow I already have it installed apparently. 

@tux3 I brought the issue to NikolaiToryzin's attention, not sure if hes gonna do anything about it, keep up the good work

**Comment by dubslow** [comment]
I just recalled that when I tried the Jenkins version, I had the same issue, but it refused to use the 2.4 .so -- and my package manager doesn't have 2.3... I told NT that sometimes Debian stable can be too old, lol

**Comment by Frowny** [comment]
still not working :broken_heart: :anger:

**Comment by tux3** [comment]
Sorry.
