### ISSUE TITLE
FFmpeg crash when opening some USB webcams

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#2702]
We crash in the A/V settings tab when opening some USB webcams, at least on Windows.
For example with device 046d:08cb.

**Comment by antis81** [comment]
I'm also experiencing this with the builtin isight of old macbook 2007 (2,1)

**Comment by NoxNoctium** [comment]
I tried it again and it doesn't _crash_, after 80 seconds the tab becomes responsive again and displays the default avatar as video input. 
But this stalling is still a problem, as soon as you try to interact with the unresponsive application Windows tries to trouble-shoot and kills the process before it becomes responsive again.

**Comment by Zibri** [comment]
same here... ffmpeg/ffplay crashes when opening the embedded webcam...

ffplay -f dshow -i video="BisonCam, NB Pro"

ffplay version N-81045-g450cf40 Copyright (c) 2003-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)

**Comment by zetok** [comment]
@Zibri that should be reported to ffmpeg

**Comment by Zibri** [comment]
Now it works... I think it has to do with windows 10 permissions... I gave ffmpeg administrator rights and it now works.. maybe this info is useful to others.

**Comment by zetok** [comment]
@Zibri sounds like (something related to?) #3612

**Comment by Zibri** [comment]
@zetok not at all related. At least not the filter vs filter_complex speed... 

with two different cameras I get the same results and both camera work with ffmpeg...

**Comment by sudden6** [comment]
Seems to be fixed, so closing.
