### ISSUE TITLE
New audio: When going in the audio/video settings 1/2 times, the audio feedback doesn't work

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#2703]
The first time you go in the audio/video settings, the feedback works, when you click on another setting and go back to audio/video settings the feedback doesn't work anymore. And if you repeat this step, it works again...

**Comment by tux3** [comment]
@antis81

**Comment by antis81** [comment]
Yep -> relates to #2705

**Comment by antis81** [comment]
Closing, as it is actually a duplicate of #2705.
