### ISSUE TITLE
Set capture and playback devices back to default when I unplug device that was used before

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2711]
Hello,

when I start qTox, it automatically choose my intern audio devices in the A/V settings and when I plug-in my USB headset, I am able to choose the headset as capture and playback device. Everything fine.

But the problem is: If I unplug my USB headset, qTox doesn't go back to my intern audio devices. Instead, the playback and capture devices are set to 'None' now.

Probably it's the same with the webcam.

**Comment by antis81** [comment]
@JacobHenner Interested in fixing this?

**Comment by JacobHenner** [comment]
Yep, @antis81 I'll take a look.
