### ISSUE TITLE
qtox updater crashes after launching qtox

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#2720]
Seems to mostly affect jenkins binaries
- tux3 thinks there might be something wrong with the un-elevation code which runs qtox as non admin user (not freeing COM objects right?)
- maybe qtox updater is just terminated in a wrong way?

**Comment by sysfu** [comment]
Same issue here with v 1.2.4. Settings  => About tab shows v1.2.4 already in use yet app constantly prompts to 'update', and updater crashes everytime app is relaunched, even though updater progress meter reaches 100%.

**Comment by tux3** [comment]
The auto-updater currently doesn't update itself, I'd recommend re-installing qTox (of course you'll keep your profile and settings) to be sure you have the latest updater version.

**Comment by sysfu** [comment]
That did the trick, thank you.

**Comment by zetok** [comment]
@towlie might be fixed in newest 1.4.1 release, could you re-test?

@sysfu fixed in newest 1.4.1. Update & enjoy :)

**Comment by towlie** [comment]
Fixed.
