### ISSUE TITLE
No emoticons and unable to access emoticon panel

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2722]
I have recently noticed that since the last update of qTox (402-f61332b) that there are no emoticons. What I mean by that (and my emoticon pack is set up properly and was working before) is that when I type some punctuation which is meant to turn into an emoticon image (such as ":D") it just stays as text, and also I am unable to launch the little emoticon list panel thing, because when I click on this nothing happens (I have put the button which I am talking about in a red box):

![qtox_emoticon_panel](https://cloud.githubusercontent.com/assets/11575271/11954704/71b33834-a8a2-11e5-9867-79c009596340.png)

**Comment by agilob** [comment]
#2707 introduced that... @ovalseven8

**Comment by ovalseven8** [comment]
Yeah, the reason is that the names of the smiley packs have changed.

@SeventhSonOfASeventhSon: Just go to the settings and chose the smiley pack you would like to use.

**Comment by ghost** [comment]
Right, I still think that in the next update though that one of those smiley packs should be set as default.

**Comment by ghost** [comment]
Can I close this issue now? Has it been made so that in new updates and new installations that the smiley pack field is not empty and it is set by default to a smiley pack?

**Comment by ovalseven8** [comment]
There's an open PR that will help: https://github.com/tux3/qTox/pull/2736

But independently from that PR and the name changes, if there's an invalid smiley pack in the qtox.ini file, qTox doesn't automatically change it to the default one. Then, you have to change it manually via the qTox settings. It's not a big problem but nonetheless improvable.

**Comment by antis81** [comment]
@SeventhSonOfASeventhSon Fixed.
