### ISSUE TITLE
The ability to see when the other person has read your message - feature request

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2723]
I think that it would be nice like on FaceBook and Skype for qTox to have the ability to show the other person with whom you are talking when you have read their messages, and also show the time at which you read them (though the time thing would also be optional).

Of course this would be a feature that one could turn off like they can turn off the feature which shows when they are typing.

**Comment by agilob** [comment]
This requires changes in tox protocol, is invasion of privacy and not supported by core.

**Comment by ghost** [comment]
Then being able to see when another person is typing is also an invasion of privacy.

Plus, the idea is for this feature to be turned off by default, so if the user doesn't mind and wants it they can enable it for themselves.

**Comment by ghost** [comment]
Is there any use in this "feature"? I have the impression that its only purpose is to create anxiety and force people to use the service as often as possible, because their friends can spy on them. Next thing you know is that smilies have a "sincerity" tag, based on info from the camera.

> Then being able to see when another person is typing is also an invasion of privacy.

Not completely true. A contact can't ping you trough typing notifications (or your online status).

**Comment by ghost** [comment]
@kehugter, But this would be an optional feature which would be off by default, if a user wanted for other people to be able to see when they had read their messages, then they could turn it on. It would only be if you wanted it to be, so I don't see how it would be forcing anything on anybody.

**Comment by ProMcTagonist** [comment]
read receipts are core issue

**Comment by ElLamparto** [comment]
This feature is useful for offline messaging systems (like email for example). In case of Tox - totally useless imho.

Further: how would you know that a message has been read? The other party may have Tox window open and read your message without touching the window.

**Comment by ghost** [comment]
Well, you can't tell absolutely for sure, but when the window is selected it does seem to select the text box and that's what other services do such as FaceBook and Skype, they just assume you've read it once you've clicked in the box. It's really the best you can do and actually works rather well.

**Comment by yurivict** [comment]
+1

**Comment by zetok** [comment]
Duplicate of #1083, thus closing.
