### ISSUE TITLE
The ability to cancel a message which is still sending - feature request

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2724]
Sometimes I might send a message to someone who is not online, but then I decide that actually I want to take my message back, and as they have not actually received the message yet and it is still trying to send on my end, I think that i should have the ability to at least cancel it so that it stops trying to send.

**Comment by ovalseven8** [comment]
=> https://github.com/tux3/qTox/issues/1306

**Comment by zetok** [comment]
Duplicate of #1306, thus closing.
