### ISSUE TITLE
Updated on Debian sid, now crashes when sending messages

### ISSUE THREAD

**Issue by Recharged** [qTox/qTox#2728]
I recently updated qTox on Debian sid and, whenever I start it, it states, "qTox couldn't open your chat logs, they will be disabled." Which I would assume means that qTox chat history has been fixed (perhaps my Tox ID is corrupted). However, whenever I try to send a message, qTox immediately crashes, and sometimes crashes on its own after awhile.

I created a new account and it seems to work fine, even chat history, but I manually attempted to copy-paste all of my friend's tox IDs by right-clicking their names and only 64 out of 72 characters are included in the dialog box.

**Comment by ghost** [comment]
> copy-paste all of my friend's tox IDs

#2079 #1451 etc

**Comment by agilob** [comment]
> However, whenever I try to send a message, qTox immediately crashes, and sometimes crashes on its own after awhile

Could you get some logs for this? or stacktrace?

**Comment by Recharged** [comment]
Here's the debug log: http://pastebin.com/QYei76MQ

However, I fixed the issue. Someone on Tox IRC helped out another person with the same issue, and his instructions were to: 1) Backup the Tox folder in /.config/tox, 2) Delete contents of the folder, 3) Re-add Tox IDs to the folder. After that, my issue was fixed and chat history works as well.

**Comment by wdbm** [comment]
@Recharged Hey, what do you mean when you say  "Re-add Tox IDs to the folder"? Should certain files be added from the backup?

**Comment by ghost** [comment]
@wdbm I think he meant profiles, not IDs. ie, put the backup back in the config directory.

**Comment by Recharged** [comment]
@wdbm Sorry for the really late reply, I never get emails about notifications anymore. Yeah, what kehugter said is what I meant. Move your own Tox ID profile(s) back into the config directory.
