### ISSUE TITLE
Does tox work when only when both of the users are online?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2732]
I use qtox to communicate with a friend who uses antox. We receive each others messages only when we both are online at the same time. Otherwise we never receive messages.

Is this by design or am I the only one facing this type of problem?

**Comment by ProMcTagonist** [comment]
This is due to the current structure of Tox. Because it is direct P2P, there are no servers in between storing messages to relay later if someone is offline at the moment. 

Offline messaging is being worked on, though.

**Comment by yurivict** [comment]
Where will offline messaging store them?

**Comment by zetok** [comment]
@yurivict 

> Where will offline messaging store them?

Last time I've heard ideas about how it should be done, focus seemed to be directed on making it work in a federated way, using servers for storage.

@kashish110393 if that answers your question, please close the issue `:)`
