### ISSUE TITLE
Upgrade on Debian Jessie - dependency problem

### ISSUE THREAD

**Issue by ElLamparto** [qTox/qTox#2735]
![dependency](https://cloud.githubusercontent.com/assets/9163437/11994339/de994f42-aa3c-11e5-9af1-1d45dacdb173.png)

**Comment by agilob** [comment]
Do you have backports enabled?

Could you try doing:
sudo apt-get install libsqlcipher-dev
or
sudo apt-get install sqlcipher

**Comment by ElLamparto** [comment]
Installing sqlcipher from Backports solved the problem. Thanks a lot!
