### ISSUE TITLE
Styling support - feature request

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2737]
I think that there should be some sort of styling support (of course you will be able to turn off though if you want to just see the raw text) so that if one puts some text in `*`s it becomes _italic_, `**`s for **bold**, and `***`s for **_bold-italic**_. As well as being able to put `s around the text to make the stars as just stars and not have any styling effect.

**Comment by agilob** [comment]
https://github.com/tux3/qTox/issues/2497
