### ISSUE TITLE
The procedure entry point CreateProcessWithTokenW could not be located in the dynamic link library ADVAPI32.dll

### ISSUE THREAD

**Issue by Granitoid** [qTox/qTox#2738]
Error on run "c:\Program Files\qTox\bin\qtox.exe" (v1.2.2)
Windows XP SP3
File "c:\WINDOWS\system32\advapi32.dll" exists (v5.1.2600.5755 xpsp_sp3_qfe.090206-1316)
[advapi32.zip](https://github.com/tux3/qTox/files/72637/advapi32.zip)

**Comment by zetok** [comment]
Hmm, windows xp is not really supported.. Is it reproducible on any later version?

**Comment by tux3** [comment]
CreateProcessWithTokenW is only used in the updater to do some UAC shenanigans in Vista and later, so this function of course doesn't exist on XP.

If that's the only thing that prevents XP support, it should be easy to fix by doing a LoadLibraryA/GetProcAddress dance before trying to use this function.

**Comment by Granitoid** [comment]
Thanks for answer.
I have only Windows XP and I want use qTox. My friends use Windows XP too.
qTox worked one day and on next day show this error on startup.
What I can do to fix this problem? What to do? :(

**Comment by Granitoid** [comment]
Re: [qTox] The procedure entry point CreateProcessWithTokenW could not be located in the dynamic link library ADVAPI32.dll (#2738)



Hi.

Thanks for answer.
What I can do to fix this problem?


Thursday, December 31, 2015, 2:21:34 PM, you wrote:





CreateProcessWithTokenW is only used in the updater to do some UAC shenanigans in Vista and later, so this function of course doesn't exist on XP.
If that's the only thing that prevents XP support, it should be easy to fix by doing a LoadLibrary/GetProcAddress dance.
—
Reply to this email directly or view it on GitHub.




--  
  Alexei 
  alex@pvtmail.ru

**Comment by tux3** [comment]
I'm going to fix this problem and release an update pretty soon.

**Comment by Granitoid** [comment]
Thank you!

**Comment by Granitoid** [comment]
Write please version packages on page https://wiki.tox.chat/Binaries#windows

**Comment by Granitoid** [comment]
When you will fix this problem?

**Comment by tux3** [comment]
Sorry, I started working on this but I got side-tracked a little. I'll try to finish the fix today.

**Comment by tux3** [comment]
This should be fixed by this commit : https://github.com/tux3/qTox/commit/3645e39b89739c76b0202799d399b707d2132677

This update will be shipped in the next qTox stable release.
