### ISSUE TITLE
[OSX] Chat area dropping keystrokes

### ISSUE THREAD

**Issue by anoadragon453** [qTox/qTox#2742]
Not experiencing this on any other platform so I'm filing the issue here. For whatever reason random subsets of 2-3 letters that I type are being deleted at random. 

It's slightly irritating as there is no spellcheck in the chat bar and each message requires a manual read-through.

I am running qTox v1.1-880-g634ca9d on OSX.

**Comment by anoadragon453** [comment]
Specifically the t,y,u keys. Also seems to only happen after alt-tabbing back into qTox. No issues after typing for a while. No issues in any other application either...

**Comment by zetok** [comment]
Hmm, `v1.1-880-g634ca9d` seems a bit dated, given that there's `1.2.2` tag. Mind updating?

**Comment by anoadragon453** [comment]
Latest build from experimental OSX repo :/

Edit: Forgive the multiple notifications. Email client acting up.

**Comment by anoadragon453** [comment]
Latest build from the Experimental OSX repo :/

On December 31, 2015 3:21:43 AM PST, zetok <notifications@github.com> wrote:
>Hmm, `v1.1-880-g634ca9d` seems a bit dated, given that there's `1.2.2`
>tag. Mind updating?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/tux3/qTox/issues/2742#issuecomment-168175979

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by anoadragon453** [comment]
Latest build from the Experimental OSX repo :/

On December 31, 2015 3:21:43 AM PST, zetok <notifications@github.com> wrote:
>Hmm, `v1.1-880-g634ca9d` seems a bit dated, given that there's `1.2.2`
>tag. Mind updating?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/tux3/qTox/issues/2742#issuecomment-168175979

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by anoadragon453** [comment]
Latest build from the Experimental OSX repo :/

On December 31, 2015 3:21:43 AM PST, zetok <notifications@github.com> wrote:
>Hmm, `v1.1-880-g634ca9d` seems a bit dated, given that there's `1.2.2`
>tag. Mind updating?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/tux3/qTox/issues/2742#issuecomment-168175979

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by anoadragon453** [comment]
Latest build from the Experimental OSX repo :/

On December 31, 2015 3:21:43 AM PST, zetok <notifications@github.com> wrote:
>Hmm, `v1.1-880-g634ca9d` seems a bit dated, given that there's `1.2.2`
>tag. Mind updating?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/tux3/qTox/issues/2742#issuecomment-168175979

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by anoadragon453** [comment]
Latest build from the Experimental OSX repo :/

On December 31, 2015 3:21:43 AM PST, zetok <notifications@github.com> wrote:
>Hmm, `v1.1-880-g634ca9d` seems a bit dated, given that there's `1.2.2`
>tag. Mind updating?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/tux3/qTox/issues/2742#issuecomment-168175979

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tux3** [comment]
Unfortunately that sounds like an upstream Qt problem, so there's not much I can do to fix it in qTox. 
@RowenStipe can you reproduce this? Could you try with a different Qt version in your builds maybe?

**Comment by RowenStipe** [comment]
My attempts to recreate this bug have been unsuccessful on my machine with any build, with or without a n externally connected keyboard.

**Comment by anoadragon453** [comment]
No longer using OSX as primary OS, and not reproducible on Linux. Closing.

**Comment by ProMcTagonist** [comment]
Note that this is closable because Rowen can't repro, not because a developer stopped using the target platform

**Comment by RonnieTiger** [comment]
I'm still having this issue, it's very annoying.

**Comment by gardners** [comment]
I'm also having this problem on OSX El Capitan. Happy to help test any fixes, try different builds / QT builds etc. For me, it is not restricted to any single key, but rather as I type, it will fairly often miss one or more characters.  SPACE is perhaps more affected than other keys, but that is only a feeling.

**Comment by RonnieTiger** [comment]
I'm not 100% sure but when i caught it cutting keystroked while i was typing and looking at the screen, it almost looked as if the letter was there briefly then deleted, like it had picked up a backspace from somewhere. my most affected keys seem to be D, Y and M, but more often than not it's completely random, and comes and goes in spouts. Only way to re-produce I would say is just continued normal use. as of yet i've not found any particular trigger.
