### ISSUE TITLE
Lost qTox "libwayland-cursor0" dependency in .deb (qtox: error while loading shared libraries: libwayland-cursor.so.0: cannot open shared object file: No such file or directory)

### ISSUE THREAD

**Issue by Aalexeey** [qTox/qTox#2747]
There is "libwayland-cursor0" dependency lost, at least for Debian Wheezy. qTox will not start without it. Taken from Mepis experimental. 265 for i386 and 278 for amd64, are last well working qTox'es in Wheezy, without lots extra dependencies.
Debian Wheezy MATE Desktop

**Comment by zetok** [comment]
https://github.com/tux3/qTox/blob/deeb9b2308290e0404198a38a5d4c456ac39b328/INSTALL.md#community-builds ← could you check if it works for you?

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.
