### ISSUE TITLE
qTox (PTT) Push To Talk doesn't work

### ISSUE THREAD

**Issue by dardevelin** [qTox/qTox#2749]
I was in a call and decided to try the PTT feature.
muted the microphone and then pressed CTRL+P, also tried right control to see if there was any difference. The end result was the other side was simply no able to hear.

the shortcut was obtained from the wiki entry https://github.com/tux3/qTox/wiki/Keyboard-shortcuts

Thank you

**Comment by zetok** [comment]
Reproducible on 552155bd1f5824c536dd6d1bbc8d293f3f1d8499

**Comment by agilob** [comment]
@zetok Was that ever implemented? Why is that in the table?

**Comment by dardevelin** [comment]
I did some inspection and it seems that groupchat has some code for it, but single calls don't. And i am guessing the documentation mentions it because of this.
