### ISSUE TITLE
Empty username is confusing in group chat

### ISSUE THREAD

**Issue by alexlehm** [qTox/qTox#2754]
When a user has an empty username (which is allowed, I assume), the list of messages is a bit confusing since repeat messages from a user is also suppressing the username. It would be better if the empty username somehow indicated that the msg is not by the same user as the previous line.

```
User1:1 (by user1)
     :2 (by user1)
     :3 (by empty)
```

in this list it looks like 3 was sent by User1 as well

**Comment by ovalseven8** [comment]
Yeah, there're many bugs in qTox concerning the group chats at the moment.
Hopefully, the new group chat is coming soon. Then, a rewrite in qTox is necessary anyway.

=> https://github.com/tux3/qTox/issues/2600

**Comment by zetok** [comment]
Perhaps adding in front of nick some symbol (e.g. `•`) would "fix" that issue?

I.e. `•` should be added only if given user writes for the first time after previous user wrote something.

E.g.

```
• User1:1 (by user1)
       :2 (by user1)
•      :3 (by empty)
       :4 (by empty)
```

I thought of using colours, but I don't know whether they would work for colourblind people.

**Comment by alexlehm** [comment]
@zetok I think an indicator when the user changes would be good (like a dot), or it would be possible to group the msg belonging to one user by changing the background to gray alternately.

![issue 2754 tux3_qtox](https://cloud.githubusercontent.com/assets/156144/12064546/f97b5dee-afc5-11e5-9403-85c44032f5c0.png)

**Comment by sudden6** [comment]
+1 for the idea of @alexlehm

**Comment by ProMcTagonist** [comment]
+1 @alexlehm

**Comment by sudden6** [comment]
The public key is now displayed instead of an empty username.
