### ISSUE TITLE
qtox - 406-7f34290 - horrible echo on audio / video call

### ISSUE THREAD

**Issue by jaceq** [qTox/qTox#2756]
Hello,

I am doing some test calls between 2 laptops (in different rooms) and audio is not usable...
Echo is truly horrible, disabling one of microphones breaks the loop. Both clients use latest qtox with 'Filter audio' ON (which doesn't seem to work). Video is OK.

I see nothing special in log:

```
[14:39:16.096] src/core/coreav.cpp:142 : Debug: "answering call 0"
[14:39:16.107] src/widget/form/chatform.cpp:305 : Debug: onAvStart
[14:39:16.107] src/widget/form/chatform.cpp:511 : Debug: disableCallButtons
[14:39:16.112] src/widget/form/chatform.cpp:621 : Debug: creating netcam
[14:39:16.113] src/video/netcamview.cpp:91 : Debug: SIZER QSize(640, 480)
[14:39:18.707] src/audio/audio.cpp:550 : Debug: Audio output not closed -> there are pending subscriptions.
[14:39:23.437] src/video/camerasource.cpp:209 : Debug: Opening device  "/dev/video0"
[14:41:42.343] src/widget/form/chatform.cpp:420 : Debug: onHangupCallTriggered
[14:41:42.343] src/core/coreav.cpp:211 : Debug: "Cancelling call with 0"
[14:41:42.343] src/audio/audio.cpp:402 : Debug: Unsubscribed from audio input device [ 0 subscriptions left ]
[14:41:42.343] src/audio/audio.cpp:666 : Debug: stopping audio capture
[14:41:42.343] src/audio/audio.cpp:670 : Debug: Closing audio input
[14:41:42.344] src/audio/audio.cpp:768 : Debug: Audio source 2 deleted. Sources active: 0
[14:41:42.344] src/audio/audio.cpp:688 : Debug: Closing audio output
[14:41:42.346] src/widget/form/chatform.cpp:491 : Debug: enableCallButtons
[14:41:42.346] src/widget/form/chatform.cpp:511 : Debug: disableCallButtons
[14:41:42.347] src/widget/form/chatform.cpp:504 : Debug: timer started!!
[14:41:42.379] src/video/camerasource.cpp:282 : Debug: Closing device  "/dev/video0"
[14:41:43.922] src/widget/form/chatform.cpp:542 : Debug: onEnableCallButtons
```

Also, when calling there is a long delay after pressing answer until call is actually initiated, I can see this here:

```
[14:39:18.707] src/audio/audio.cpp:550 : Debug: Audio output not closed -> there are pending subscriptions.
[14:39:23.437] src/video/camerasource.cpp:209 : Debug: Opening device  "/dev/video0"
```

It's a 5 second gap for... I don't know what, there were no other tasks for qtox.

And both clients are on ubuntu one 14.04 and one 15.04

**Comment by tux3** [comment]
@antis81 any idea?

**Comment by jaceq** [comment]
One more note, I've lowered volumes (in qtox settings) microphone to 25 and output to 80 but problem still occurred. 
If helpful (and I've seen this in some other ticket) I can try to record this and upload somewhere if reproducing is a problem.

**Comment by Diadlo** [comment]
Have you tried to call somebody else?
Echobot, for exampe 76518406F6A9F2217E8DC487CC783C25CC16A15EB36FF32E335A235342C48A39218F515C39A6

**Comment by jaceq** [comment]
Hi,

Yes, I have this problem with 2 people, also had the same with echo bot you suggested...
Recorded this with a phone and uploaded: http://vocaroo.com/i/s1E6gL2xRVKV

**Comment by Diadlo** [comment]
Other application, which use microphone, work normal?

**Comment by jaceq** [comment]
Ok, so made interesting discovery, my second laptop with echobot doesn't produce this effect...

But still, other apps on affected laptop work fine (skype / hangouts even utox...) I'm confused what is going on a bit.

**Comment by Diadlo** [comment]
Audio device in setting are correct?

**Comment by antis81** [comment]
> Echo is truly horrible, disabling one of microphones breaks the loop.

It helps to understand, that all these "bugs" come from a real world thing (not software :smile:) called feedback. That means: The microphone records audio from the **same** laptop's speakers or a nearby audio source. If there wouldn't be latencies and other effects you would hear the well known much more horrible **beeeeeeeeeep**… :)

The audio volume controls in qTox are still giving us pretty rough control over gain/volume settings. Those should be bound to the system's audio settings in the future… Anyone who wants, feel free to setup a PR to implement a concept.

> One more note, I've lowered volumes (in qtox settings) microphone to 25 and output to 80 but problem still occurred. 

Same thing… You can pretty much ignore qTox audio settings for the moment (set them to some fixed value at ~80% or something similar ) and **only** control volume via system settings -> lower the input volume there and you will definitely get better results. Oh, almost forgot: **disable audio filter in qTox**

``` text
[14:39:18.707] src/audio/audio.cpp:550 : Debug: Audio output not closed -> there are pending subscriptions.
[14:39:23.437] src/video/camerasource.cpp:209 : Debug: Opening device  "/dev/video0"
```

> It's a 5 second gap for... I don't know what, there were no other tasks for qtox.

@agilob Here's one for you :). I looked into the code and looks like `CameraDevice::getDefaultDeviceName()` (called in `CameraSource::open()`) is causing this. No need to fix it, just to explain what's happening.

I just called a friend ~100km away (both Lubuntu) and it works with the above said settings. @tux3 You should be aware, that this behaviour has been there for as long as I am using qTox (~1 year). So no bug introduced here, but the new a/v concepts are still WIP.

This being said: **Time to start celebrating and look forward for another year to come…** :fireworks: :smile: :cocktail: :rainbow:

**Comment by jaceq** [comment]
So.. I disabled audio filtering but still have this problem... I need to have mic VERY low to avoid, but then other side cannot hear me (or can VERY quietly). Also I found another issue, if during video call I will try to go to audio / video settings qtox pretty much freezes, I mean it's non-clickable , video freezes but voice works... 

And I agree, let's start celebrations for today :)

**Comment by jaceq** [comment]
I was thinking about this, maybe a skype like approach might help a bit here?
So as we probably know, skype can adjust mic volume on it's own, would this be hard to implement?
Major thing I see here is the fact that skype uses pulse audio settings directly and qtox has it's own...

More info: I just did (really) remote call (distance 800-1000km) and while video is very nice, audio is not. Echo is really intensive, it's much worse than on skype / hangouts (same clients / hardware etc), also I think utox cuts this out... I tried without 'filter audio' on both sides as advised above. Obviously both sides were without headphones, as then echo problem wouldn't exist.

**Comment by antis81** [comment]
@jaceq Are you able to compile qTox and check a PR? I'd be glad, if you could help with #2768.

**Comment by jaceq** [comment]
Hi,

@antis81 I can but as I didn't let me know or direct me to repo / branch to use and steps to compile.

**Comment by antis81** [comment]
@jaceq
Sorry for the delay. If you're interested in helping out to review and test the audio code I'd be more than happy. Depending on your git knowledge you have two options:
1. clone my repo from `git://github.com/antis81/qtox.git` (or https, if git protocol doesn't work for you)
2. add my repo as remote `git remote add antis81 git://github.com/antis81/qtox.git` and then `git fetch antis81 audio/volume`. This will fetch only the required branch, that syncs with #2768.

In both cases you should know how to compile qTox for your system (especially ffmpeg, if you're on Ubuntu 14.04 or the like) -> see [Compiling qTox](https://github.com/tux3/qTox/blob/master/INSTALL.md#compile-qtox) section in INSTALL.md file.

**Comment by CGM-games** [comment]
I was about to report this issue until I noticed it was already reported. I wanted to quit using Skype, then I found Tox. I started a video call with a friend, and I was sadly disappointed that the audio was doing exactly as described here. Echoing, sounding bad, and it was so bad, I had no choice but to use Skype. :(

**Comment by antis81** [comment]
@CGM-games Did you adjust the "gain" for your microphone (in qTox settings)? Please connect to the Tox Echobot and test it before calling a friend. Actually there is two places to check, which is your system audio input (mic) gain settings and qTox gain. The feedback occurs when the level of input signal is too high. This can also occur when using a headset.

**Comment by CGM-games** [comment]
Ah. Thanks for the help!
