### ISSUE TITLE
[UI] grey out proxy address and port if no proxy selected

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#2760]
grey out the fields "address" and "port" in general settings / proxy settings, if proxy type is set to "none" to make it clear that the user isn't expected to enter anything here.

But still save an already entered address if the user switches to type "none".

**Comment by ezavod** [comment]
@sudden6  I think this issue could be closed since #4356 has been merged.

**Comment by sudden6** [comment]
Thanks for the reminder

**Comment by zetok** [comment]
@ezavod btw, https://help.github.com/articles/closing-issues-via-commit-messages/
