### ISSUE TITLE
Missing Icon on Xubuntu

### ISSUE THREAD

**Issue by Gullumluvl** [qTox/qTox#2763]
Hi, I am using xfce desktop environment, and after installing qtox (from the ppa), there is no default icon available in the menus. I am trying to add one manually but it would be interesting to have it automatically. Thanks!

**Comment by agilob** [comment]
This is a packing problem we are aware of, afair @tux3 is investigating it?

**Comment by tux3** [comment]
It's missing a .desktop file I think.

**Comment by agilob** [comment]
There is qTox.desktop in repo.

**Comment by zetok** [comment]
> There is qTox.desktop in repo.

Yeah, but unless something has changed, it's not being used by packages.
