### ISSUE TITLE
Can't open app after adding password to profile

### ISSUE THREAD

**Issue by grunichev** [qTox/qTox#2773]
I had a profile without password than I enabled password and quit qtox. Now it can't load profile:
[00:11:45.323] ../qTox/src/core/coreencryption.cpp:94 : Warning: file "/Users/alexey/Library/Preferences/tox/A_.qtox_history.encrypted" doesn't exist
Segmentation fault: 11
and indeed there is only old A_.qtox_history 
Is it somehow possible to fix it?

**Comment by antis81** [comment]
Interesting… just an idea, but maybe you can copy the file to `/Users/alexey/Library/Preferences/tox/A_.qtox_history.encrypted`. It might be still crashing though (because of missing encryption I guess).

**Comment by tux3** [comment]
@grunichev You should update qTox, the qtox_history.encrypted file is created by the old history system, it has been replaced by something much more reliable some time ago.
