### ISSUE TITLE
Client freezes after attempt to start group audio

### ISSUE THREAD

**Issue by SmoothDude** [qTox/qTox#2774]
When you try to start audio transmission in qTox group chat, client freezes.
To reproduce this issue:
- Start qTox client.
- Ask friend to create group chat with audio support for you
- Accept invite to this group chat
- Ask friend to start audio
- Start audio yourself
- Client freezes
# 

Version: v1.2-164-gdefae04
Commit hash: defae042279f7ed28ca2550f314411a77fce56e0
Qt: 5.5.1
OS: Arch

**Comment by antis81** [comment]
What do you mean by "start audio" - pick up the phone?

Tried a group call by myself on local hardware (2 instances) and there isn't even a call indicated (no ringtone and phone icon is green) on the other side, but lots of these in the logfile:

```
[22:56:10.671] ../../src/core/coreav.cpp:432 : Debug: toxav_group_send_audio error
```

@tux3 Probably an upgrade to new toxcore audio api helps?

**Comment by antis81** [comment]
Btw.: The first calling client doesn't freeze, but when they try to call each other, one qTox instance freezes.
