### ISSUE TITLE
utox wont go online

### ISSUE THREAD

**Issue by nymda** [qTox/qTox#2775]
when i open utox the red circle next to my name will not go green and none of my contacts appear online. ive changed my network settings but nothing works.

im using the newest version of utox. i am also on a public network.

![help](https://cloud.githubusercontent.com/assets/16545187/12112452/84c354de-b394-11e5-85b3-d05fc3f552b0.PNG)

**Comment by zetok** [comment]
This is a qTox repo. You should file an issue on [µTox repo](https://github.com/GrayHatter/uTox). Though, given that you're on a "public" network, chances are that Tox clients are simply blocked.
