### ISSUE TITLE
[UI] White pixels at the outer tabs in the settings

### ISSUE THREAD

**Issue by mikalehmann** [qTox/qTox#2779]
![ui bug](https://cloud.githubusercontent.com/assets/8298953/12203098/7ac838c8-b62d-11e5-9539-d671b3be4853.png)
This picture sums it up. Just a minor thing, but doesn't look very good.

**Comment by agilob** [comment]
Please include image in the post, dont use 3rd party services.

**Comment by sudden6** [comment]
Fixed in newer builds.
