### ISSUE TITLE
debian jessie repo dependency error

### ISSUE THREAD

**Issue by mova** [qTox/qTox#2781]
using `deb https://pkg.tox.chat/debian nightly jessie`  when installing qtox gives:
`qtox : [Depends on]: libvpx1 (>= 1.0.0) [but is no installable].
        [Depends on]: qtbase-abi-5-3-2 which is a virtual package and is not provided by any available package.`
using `deb https://pkg.tox.chat/debian nightly release` fixes that.

**Comment by tux3** [comment]
Hi, you need to use the jessie-backports repo for now to use qTox on Jessie. We'll be working on fixing that on our end.

**Comment by zetok** [comment]
https://github.com/tux3/qTox/blob/deeb9b2308290e0404198a38a5d4c456ac39b328/INSTALL.md#community-builds ← could you check if it works for you?

**Comment by zetok** [comment]
Community builds work on Debian 8, thus closing.
