### ISSUE TITLE
GTK style segfault

### ISSUE THREAD

**Issue by gmscs** [qTox/qTox#2786]
Switching style to GTK  and moving/resizing the window a bit ends with the following segmentation fault:

(qtox:8887): Gtk-CRITICAL **: gtk_style_finalize: assertion 'style->attach_count == 0' failed

(qtox:8887): Gtk-CRITICAL **: IA__gtk_style_attach: assertion 'GTK_IS_STYLE (style)' failed
Segmentation fault

**Comment by ghost** [comment]
I get some `CRITICAL`s but no segfault:

> (qtox:10333): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
> 
> (qtox:10333): Gtk-CRITICAL **: IA__gtk_style_attach: assertion 'GTK_IS_STYLE (style)' failed
> 
> (qtox:10333): Gtk-CRITICAL **: IA__gtk_style_set_background: assertion 'GTK_IS_STYLE (style)' failed
> 
> (qtox:10333): Gtk-CRITICAL **: IA__gtk_paint_flat_box: assertion 'GTK_IS_STYLE (style)' failed
> 
> (qtox:10333): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
> 
> (qtox:10333): Gtk-CRITICAL **: IA__gtk_style_attach: assertion 'GTK_IS_STYLE (style)' failed
> 
> (qtox:10333): Gtk-CRITICAL **: IA__gtk_style_set_background: assertion 'GTK_IS_STYLE (style)' failed
> 
> (qtox:10333): Gtk-CRITICAL **: IA__gtk_paint_flat_box: assertion 'GTK_IS_STYLE (style)' failed
> 
> (qtox:10333): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
> 
> (qtox:10333): Gtk-CRITICAL **: IA__gtk_style_attach: assertion 'GTK_IS_STYLE (style)' failed
> 
> (qtox:10333): Gtk-CRITICAL **: IA__gtk_style_set_background: assertion 'GTK_IS_STYLE (style)' failed
> 
> (qtox:10333): Gtk-CRITICAL **: IA__gtk_paint_flat_box: assertion 'GTK_IS_STYLE (style)' failed

Nothing else logged after resizing the window.

05162a63b93aaa046567920a37fd64e9edfa05d4
Debian testing
Qt 5.5.1
libgtk2.0-0: 2.24.29-1
libgtk-3-0: 3.18.6-1

**Comment by tux3** [comment]
Okay, that looks like a bug with the Qt/GTK integration, we don't make any of those GTK calls directly so unfortunately there's not much we can do about it from the qTox code.

**Comment by zetok** [comment]
Is it still reproducible?

**Comment by Diadlo** [comment]
Needed info not provided for over a month, thus closing.
