### ISSUE TITLE
Does not update to v1.2.2

### ISSUE THREAD

**Issue by rugk** [qTox/qTox#2796]
Current qTox version: v1.2.1 on Windows 7 (installed with the installer)

As I now see [v1.2.2](https://github.com/tux3/qTox/releases/tag/v1.2.2) was already released. Obviously the updater did not noticed this release, although it was released some time ago.

**Comment by ElLamparto** [comment]
Confirmed on XP 32 bit & Win 7 64bit.

**Comment by rugk** [comment]
So what's the issue?

**Comment by ElLamparto** [comment]
@rugk, the issue is that the updater does not update. It does not see new version available.

**Comment by rugk** [comment]
That far I could also thought...

But the updater is a thing which should never break... at least not in a stable version of the software how **qTox is called**. Based on issues as this it does **not really look stable**, because the updater is really the last thing which should break here.
I'm sure many users will trust the updater and not look for new releases manually and as this is a security-relevant software it should always get updates as you can find vulnerabilities at any time.

**Comment by tux3** [comment]
Hi, I tested the updater yesterday on Win 7 64bit and I couldn't reproduce.
Are you sure the "Check updates on startup" option is enabled? 
Can one of you post the qTox log?
And finally what's the exact commit hash and version in the settings?

**Comment by ovalseven8** [comment]
> Based on issues as this it does not really look stable, because the updater is really the last thing which should break here.

qTox isn't stable. There is much to do to reach this goal.
But the "stable" releases make sense because we can prevent distributing broken software as a result of bad PRs for example.

**Comment by rugk** [comment]
> qTox isn't stable. [...] "stable" releases

So what? I also see https://github.com/tux3/qTox/issues/2808 now where you indicate that qTox is not stable. On the other hand you publish "stable releases" (:confused:) and in [your wiki](https://wiki.tox.chat/binaries) you also call it "release". I have to say I [requested](https://github.com/tux3/qTox/issues/2672) the latter as I thought qTox would be stable.

This assumption was [based on this commend](https://github.com/tux3/qTox/issues/2644#issuecomment-164161844):

> Users are encouraged to use **stable versions** now[...]
> [There is a] **stable installer** and the updates are all **stable**.

Stable, stable, stable...
And now I hear that qTox is not stable. So can you please decide whether it is stable or not?

The versioning already confuses enough, so you do not have to tell that qTox is stable and say at the same time that it is not. A software can only be stable (x)**or** beta/alpha/whatever.
You may say you publish regular (alpha/beta) releases, but these releases are _not stable_.

---

So I'd suggest changing the "release" in the wiki to "alpha release" or "beta release", so you know it is no stable release.

> as a result of bad PRs for example.

Bad PRs should not get into master at all... :stuck_out_tongue:
But I understand the meaning of these releases, and if they have been `0.x` releases everything would be clear...
`0.x` is unstable and `1.x` is stable. And theoretically you should still be with `0.x` and therefore you cannot call this "stable". You just **cannot** make **stable releases with unstable software** - that's contradictory.

---

I hope you get my point...

**Comment by rugk** [comment]
So as for the update issue...

> Are you sure the "Check updates on startup" option is enabled?

Obviously yes...

> Can one of you post the qTox log?

This is the first part of one day when qTox started with the old version (now I've upgraded manually):

```
2016-01-14 15:29:40 qTox file logger starting
[15:29:40.456] src/main.cpp:143 : Debug: built on:  13:25:10 Dec 12 2015 ( 1449944629 )
[15:29:40.466] src/main.cpp:144 : Debug: commit:  a4af80fbcc35911df6c9c44bc49d15fd8c6fca72 

[15:29:40.466] src/main.cpp:171 : Debug: Setting profile to "tox_save"
[15:29:40.476] src/nexus.cpp:82 : Debug: Starting up
[15:29:46.791] src/persistence/profile.cpp:77 : Debug: Loading tox save  "[...]AppData/Roaming/tox\\tox_save.tox"
[15:29:46.916] src/persistence/settings.cpp:346 : Debug: "Saving global settings at [...]AppData/Roaming/tox\\qtox.ini"
[15:29:46.994] src/persistence/settings.cpp:287 : Debug: Loading personnal settings from "[...]AppData/Roaming/tox/tox_save.ini"
[15:29:47.056] src/widget/translator.cpp:53 : Debug: Loaded translation
```

As you see nothing update the update is logged and I also could not found any other information about the update in the log.

> And finally what's the exact commit hash and version in the settings?

For the hash see the log (it's a4af80fbcc35911df6c9c44bc49d15fd8c6fca72) and I already told the version number.

**Comment by tux3** [comment]
I've tested again with a freshly installed Win XP SP3 32bit in a VM and I can't reproduce.
It's possible the problem was fixed in 1.2.2 and doesn't exist anymore.

**Comment by ElLamparto** [comment]
So let's keep this ticket open until the next update and see if it works.

**Comment by tux3** [comment]
I think I found the bug, it was a problem with a path check.
To get the fix, you will need to either update manually to 1.2.4 or start qTox from the folder it's installed in (probably in Program Files) to get the update.

**Comment by rugk** [comment]
> or start qTox from the folder it's installed in (probably in Program Files) to get the update.

I tried this with qTox v1.2.2 and indeed it worked. :smiley: 
Thanks for the tip.
