### ISSUE TITLE
Video quality

### ISSUE THREAD

**Issue by Diadlo** [qTox/qTox#2797]
Sometimes I have very bad video quality. It depend of qtox session. If I restart qTox I may have normal quality. If I set webcam resolution more smaller, I may have normal quality (but not necessarily)
![screenshot_20160114_123328](https://cloud.githubusercontent.com/assets/6306608/12320932/7d15911e-babc-11e5-8cb1-1e2580cd2084.png)

**Comment by agilob** [comment]
Try decreasing resolution instead of restarting, your internet connection might be too slow for it?

**Comment by ElLamparto** [comment]
It looks like a great modern art!
Sometimes I have the same problem which is surely connection quality related (the picture returns to normal when the transmission improves).

I set resolution 640x480 and I would not recommend any higher.

**Comment by Diadlo** [comment]
1) In damn skype i have normal quality
2) WHY after restart qTox sometimes it work fine with max resolution?
3) When I do video-call to my friend (uTox) he never seen normal video (even if I set minimal resolution about 140x160 and 5fps)

**Comment by TheNain38** [comment]
irungentoo/toxcore#1479

**Comment by Diadlo** [comment]
> I set resolution 640x480 and I would not recommend any higher.

May be we should set it by default? Or add note in UI, that it is recomended

**Comment by Diadlo** [comment]
If it is problem of tox-core, I close issue

**Comment by ElLamparto** [comment]
@Diadlo, utox and qtox do not understand each other well. Chat and audio work fine. But video does not.

**Comment by ghost** [comment]
Is it possible to set settings for codec?
