### ISSUE TITLE
memory leak 1.5GB (20 hours of idle)

### ISSUE THREAD

**Issue by shalnoff** [qTox/qTox#2798]
Hi guys, I just found that my qTox taken 1.5GB (!!!) of memory being stayed idle for 20 hours. The laptop was in standby mode for 12 hours. Version v1.2-176-ge952d1a.

**Comment by tux3** [comment]
@shalnoff Hi, is this on Windows? Was qTox on the chat page, on the video page, in the settings, something else?

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.

If issue is still not fixed, please comment for reopen.
