### ISSUE TITLE
Error while loading library libxcb-render-util.so.0

### ISSUE THREAD

**Issue by dcapeletti** [qTox/qTox#2800]
Hello, I downloaded a precompiled binary for GNU / Linux 32-bit and I can not open it. From the console I get "Error while loading library libxcb-render-util.so.0"

Please help. Thank you

**Comment by tux3** [comment]
Try apt-get install libxcb-render-util0

**Comment by dcapeletti** [comment]
I also had to install:

sudo apt-get install libxcb-image0
 sudo apt-get install libxcb-icccm4
 sudo apt-get install libxcb-randr0
 sudo apt-get install libxcb-xkb1
 sudo apt-get install libxcb-keysyms1
 sudo apt-get install libxkbcommon-x11-0

Otherwise unbootable.
Would not it be better an installer for this?

**Comment by tux3** [comment]
I think I will make an installer, qTox is way too hard to install on Linux and I don't see a better way.
