### ISSUE TITLE
Name and status changes should be rate limited

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#2803]
qTox does allow arbitrary fast name and status changes, this combined with simple scripting, can lead to the comeback of `<marque>` and `<blink>`.

This would be very annoying to the user, so limit the possible changes to 1 per minute on the receiving and sending side.

**Comment by tux3** [comment]
I think we should assume good faith and not impose arbitrary restrictions on users. This looks like a technical solution to a non-technical problem :)

If your friends are being annoying, you should nicely ask them to stop. If your friends are malicious, there are worse things they can do to annoy you than script their names and status.

**Comment by zetok** [comment]
> If your friends are malicious

One should be able to block them - #1120 :)

@sudden6 dunno, as @tux3 said, it sounds like it's not an issue that one should try to solve at a technical level.

I.e. you talk to the annoying person, if they refuse to reconsider their behaviour, you block the ... .

Close the issue?
