### ISSUE TITLE
Personnal - Where do you get this word?

### ISSUE THREAD

**Issue by rugk** [qTox/qTox#2810]
`personnal` e.g. appears in the logs...
But as it seems [this is not the only place](https://github.com/tux3/qTox/search?utf8=%E2%9C%93&q=personnal+).

The issue is that this word [does not exists](http://www.onelook.com/?w=personnal&ls=a) - at least not in English.
Only one dictionary on onelook shows it and even there this may only be misspellings/typos where they got it from.

Probably you meant [personal](http://www.onelook.com/?w=personal&ls=a) - just compare the search results here. :smiley:

**Comment by zetok** [comment]
@rugk care to make a PR to fix it? :)

**Comment by tux3** [comment]
Yep, good catch, that's a typo!
@zetok I'll just search and replace it.

**Comment by rugk** [comment]
At least the one who made the typo was very consistent... :laughing:
