### ISSUE TITLE
Find & remove trailing whitespace in user manual

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#2813]
_Task_: There's a trailing whitespace somewhere in [user manual](https://github.com/tux3/qTox/blob/master/doc/user_manual_en.md). Search & destroy it.

If you would want to start contributing, but you're not sure how/what is the workflow, you might want to use this occasion to try in practice :)

Read [CONTRIBUTING.md](https://github.com/tux3/qTox/blob/master/CONTRIBUTING.md) - it includes tips that you will find helpful when making a pull request with a fix.
# 

If you know how to use git/github, but you still want to start with something easy, you probably should look at other [easy issues](https://github.com/tux3/qTox/issues?q=is%3Aopen+is%3Aissue+label%3AE-easy).

**Comment by ProMcTagonist** [comment]
I think this was supposed to help people sitting on the fence start contributing

**Comment by tux3** [comment]
@ProMcTagonist I think it did, look at #2815

**Comment by ProMcTagonist** [comment]
disregard me i suck cocks

**Comment by LittleVulpix** [comment]
:D you know what the worst part is though? Github seems to be putting a trailing whitespace after every wrapped line that precedes a sublist item. It's not in the raw code - it's just in the rendered page. I.e. if a line is so long that it gets wrapped, and if that line also has a sublist item, the end of the wrapped line will have a whitespace in the rendered page.

It's hard to explain but you can see it happen for lines 54 (at the end of "for details.", there is a whitespace) and 61 (at the end of "(#multi-window-mode)." ). It's heavy OCD  levels of frustration but hey :p 

Also, have https://github.com/tux3/qTox/pull/2819 @tux3 @zetok
