### ISSUE TITLE
The setting of "Autostart" is disabled on OS X

### ISSUE THREAD

**Issue by ddobrev** [qTox/qTox#2814]
If it's disabled by mistake, please fix it. If not, please add auto-starting on OS X, it's an extremely useful setting for chat applications.

**Comment by linux-modder** [comment]
Even on my fedora install the FIRST time I compiled it was disabled --which makes sense  autostarting a newly  first time install makes no sense to me.  If this is  post  initial launch  what  OSX version |  Mac model?

**Comment by ddobrev** [comment]
The machine I tested on is MacBook Pro early 2009 with OS X 10.11 "El Capitan".

**Comment by ddobrev** [comment]
The setting is now enabled but not persisted so it still cannot be used.
