### ISSUE TITLE
The same message may be sent multiple times

### ISSUE THREAD

**Issue by ddobrev** [qTox/qTox#2816]
I was on Windows (7 64-bit) using the 64-bit version v1.2-231-gf27214f. A friend was on OS X using version v1.2-184-gad3326b. I sent him a message and he received it 3 times (he sent me a screen-shot) with different times, about 10 seconds difference between each two successive messages.

**Comment by ProMcTagonist** [comment]
I'm on the receiving end of this a few times a week. Nothing unusual appears in either side's logs.

**Comment by azlux** [comment]
Same for me, the version is 1.2.2 for both computer on win10 (64bits).

**Comment by zetok** [comment]
Looks like it's a duplicate of #2726, thus closing.
