### ISSUE TITLE
No password on startup

### ISSUE THREAD

**Issue by Granitoid** [qTox/qTox#2817]
The Function of autosave password was very useful.
![2016-01-18_13-09-15](https://cloud.githubusercontent.com/assets/16450834/12388577/bd7e298e-bde4-11e5-9a33-47d6aa96ee46.jpg)

**Comment by zetok** [comment]
Saving password is not doable, given that it's used for encryption.

**Comment by agilob** [comment]
Click on your avatar and disable encrypted profile.
