### ISSUE TITLE
Network traffic too big

### ISSUE THREAD

**Issue by Granitoid** [qTox/qTox#2827]
I have 2 contacts, no talking, only stay online.
For passed 9 hours network traffic per hour average: incoming 10Gb, outgoing 8Gb.
It is normal? I thik it is too big.
How to reduce network traffic?
Windows XP SP3.

**Comment by tux3** [comment]
That corresponds to roughly 2*36kB/s of idle traffic (in and out), which is huge, I agree.
Unfortunately this is an issue with toxcore and there isn't much qTox can do to reduce this.

You should try opening an issue on the toxcore repo, and you can try unchecking the "Enable UDP" option in the settings to see if it helps in the meantime.

**Comment by LuccoJ** [comment]
There are already two issues on toxcore about the matter, although one of them was closed:
https://github.com/irungentoo/toxcore/issues/1251
https://github.com/irungentoo/toxcore/issues/1501

**Comment by Granitoid** [comment]
I am unchecked the "Enable UDP", results:
For passed 5 hours network traffic per hour average: incoming 6Mb, outgoing 13Mb.
Not ideal, but much better.
Thanks everybody.
