### ISSUE TITLE
qTox crashing (closing) when trying to video chat with user that does not have video.

### ISSUE THREAD

**Issue by phd21** [qTox/qTox#2831]
Hi tux3, 

Nice chatting with you earlier (user69 on chat). Thanks again for a wonderful program "qTox".

Issue: Okay, I have two computer systems both running Linux Mint KDE 17.3. One has a webcam with a microphone (phd21@toxme.io), and the other has no webcam (no video, just microphone)  (floridaphil21@toxme.io).  When I try to make a video call from the computer with a webcam to the computer without a webcam or video source, my qTox client with the webcam just closes (crashes). When I bring it back up and just do an an "audio call", it works great,  even had to lower the mic volume. 

I wanted my computer without a webcam to still be able to audio chat, and see the video feed from the other user's computer that does have a webcam, or visa-versa. I am still a "newbie" regarding using the qTox client, but a very experienced computer user (ex software developer). I noticed there are buttons, or status icons, for microphone and speaker, next to where you make an audio or video call, are they functional, or for status only? it would also be nice to have a toggle button to turn off video temporarily, if wanted, and to turn it back on when wanted.

Below are the instructions I used to install the "qTox" client.  It would also be nice to have an easy to install ".deb" file, and to have this really nice program available in the repositories.

echo "deb https://pkg.tox.chat/debian nightly release" | sudo tee /etc/apt/sources.list.d/tox.list
wget -qO - https://pkg.tox.chat/debian/pkg.gpg.key | sudo apt-key add -
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install qtox

I was glad to hear that you are working on a more secure and easier way to transfer ToxID to other users, "friends", and or improving "toxme.io", and to be able to register at "toxme.io" from within the "qTox Client" which would be extremely convenient (maybe even an auto-register option?).

Thanks again, feel free to contact me. 
Phil 
Linux Mint forum user: phd21

**Comment by sudden6** [comment]
This doesn't seem to be an issue anymore, can you please retest with the newest qTox version?

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.
