### ISSUE TITLE
qTox crash on windows 7 (32bit and 64bit) after logout

### ISSUE THREAD

**Issue by nikitasius** [qTox/qTox#2833]
Hello!

When you click "Logout" tox restarting itself and... login form becoming white and windows telling you about errors and offering to close it.

Doesn't matter how much copies you run, single or multiple. It was in december version, and exists in latest too.

**Comment by nikitasius** [comment]
![qtox_logout_fail_01](https://cloud.githubusercontent.com/assets/3670331/12482726/843593aa-c051-11e5-86a9-852496dac29b.PNG)

**Comment by zetok** [comment]
Is it still reproducible on newest (1.4.1) version?

**Comment by zetok** [comment]
Looks like a duplicate of #2480, thus closing.
