### ISSUE TITLE
Add ability to remember friend's ToxID in friend list

### ISSUE THREAD

**Issue by nikitasius** [qTox/qTox#2844]
Hello!

Now here is only public keys. So everytime when i add my friend, im adding his ID in comments, to be able to add in another client/account.

Can you add feature that qtox will remember client's tox ID from the moment when new client was added in friend list?

Thanks!

**Comment by ghost** [comment]
#2604

**Comment by zetok** [comment]
Duplicate of #2604, thus closing.

**Comment by nikitasius** [comment]
But show public key have no value, 'cause i can't add my friend on another account using it.

**Comment by ghost** [comment]
See links in the second comment of the linked issue.
