### ISSUE TITLE
Translation of the web Spanish uncompleted

### ISSUE THREAD

**Issue by dcapeletti** [qTox/qTox#2845]
Hello, when I show people that tox is, those who speak and read Spanish, I generally share the https://tox.chat/ site but I see that the Spanish translation is incomplete. How do we fix it?

**Comment by sudden6** [comment]
A new website is underway here https://github.com/Tox/tox.chat
Also this isn't a qTox issue, please close.

**Comment by dcapeletti** [comment]
Thank you
