### ISSUE TITLE
Windows: When qTox is already portable, qTox-updater still search for updates in AppData

### ISSUE THREAD

**Issue by DX37** [qTox/qTox#2849]
This does not apply to versions of qTox, because the problem is in the **qTox-Updater**. When she lies next to **qtox.exe** in the folder of the **portable** client, the client also downloads the updates in the _update_ folder near them, but after restarting it is looking for the _update_ folder in AppData and reports that it can't find the update.

**OS version:** Windows 10. I think this occurs on all supported versions of Windows. In normal client mode the qTox-Updater is working properly.

**Comment by DX37** [comment]
Steps to reproduce:
1. Download any zipped version of qTox (except current stable - v1.2.4)
2. Make it portable in _Settings_ and exit.
3. Download qtox-updater.exe and put in the client folder.
4. Run qTox again and accept the proposal to update the client. Then restart.
After that qTox-updater.exe start looking for _update_ folder in AppData, when qTox in portable mode downloading updates into _update_ folder of client folder. In the end qTox-updater.exe will report an error and will not do anything.

**Comment by ddobrev** [comment]
I reproduced it too. Also, I think it would be very convenient to just include qtox-updater.exe in the portable archive. It would be even more convenient if it does not require administrative privileges in the portable version they are then unnecessary. I understand it would most probably require different builds of qtox-updater.exe for the installer and for the archive but still, it would remove an annoyance.

**Comment by DX37** [comment]
I agree, perhaps. But nevertheless I'm interested in the answer of the developer.
UPD: Maybe it can all be simplified by adding in the current _qtox-updater.exe_ checking for the portability of the client and adding the necessary actions to handle the updates to the code.
It's sad that I do not know how to do that. I would have suggested changes in the source code :)

**Comment by tux3** [comment]
Making the updater not require admin privileges when not necessary would be nice, but harder to implement, and the priority is more on fixing bugs at the moment :)

I'll add code to the updater to check if qTox is in portable mode. (And maybe we should have a dynamic library for managing settings so we don't need duplicate code).

**Comment by DX37** [comment]
That would be cool :)

**Comment by ddobrev** [comment]
@tux3 please update the Windows release when you've fixed this. I want to recommend qTox to friends but I want this fixed first so that they can get updates properly if they decide to go portable. I was also waiting for https://github.com/tux3/qTox/issues/2840 to be included but you said it has never been a problem on Windows to begin with so it's fine. Just this one is a must to me before I urge them to join.

**Comment by DX37** [comment]
Just tested qtox-updater.exe with nightly qTox. Upgrade to v1.3.0 is done! It works!
Thanks, @tux3!
