### ISSUE TITLE
Video tests doesn't work sometimes.

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#285]
Shows a garbled mostly black and white still image.

**Comment by tux3** [comment]
I like watching the heap change.

<img src="http://i.imgur.com/BGG1AXJ.png" />

**Comment by tux3** [comment]
Likely to be a problem with my own computer / v4l / opencv.

**Comment by dubslow** [comment]
Oooohhh baby... that's such a nice heap you've got there...
