### ISSUE TITLE
Regression: emoticons on Windows gone with the latest Windows build

### ISSUE THREAD

**Issue by ddobrev** [qTox/qTox#2850]
They do not appear n the messages (history or new ones) and clicking the button for adding emoticons does nothing. I guess there's a problem loading them.

**Comment by DX37** [comment]
Look in _Settings_ at _Smiley Pack_ option. Maybe pack is not selected. You should choose _Universe_ pack, if you are using nightly build.

**Comment by ddobrev** [comment]
@DX37 it does work, they just changed the names of the packages in comparison to the previous version and my stored settings could not find a match. Thank you.

**Comment by zetok** [comment]
This actually (not selecting new emoticon pack name automatically if no valid name is set) also was fixed, although looks like "stable" version is really dated, and doesn't have that code. :/

@tux3 It would seem that next release is needed? (preferably ~soon?)

**Comment by tux3** [comment]
@zetok Soon™, but I'm not shipping audio-next before it's actually stable.
