### ISSUE TITLE
Upside down video with UVC Webcam

### ISSUE THREAD

**Issue by Aleksandra13** [qTox/qTox#2852]
Hello, I found a problem with UVC Webcam on linux client of qTox, the video is captured upside down.
It is a known issue, and there is a common fix for that described here : http://ubuntuforums.org/showthread.php?t=838210&page=28
But when I tried the same (LD_PRELOAD=/usr/lib/i386-linux-gnu/libv4l/v4l2convert.so qtox) I got  following error:
[19:29:36.023] src/video/camerasource.cpp:209 : Debug: Opening device  "/dev/video0"
[video4linux2,v4l2 @ 0x4d1c9e0] Cannot find a proper format for codec 'mjpeg' (id 8), pixel format 'none' (id -1)
Assertion *codec_id != AV_CODEC_ID_NONE failed at libavdevice/v4l2.c:821
Is there any solution for that ? 
I have nightly build of qtox Tox Git commit: e93c35062114ba741f9d3831f6e1a57f55904f72.
Thanks, Aleksandra

**Comment by zetok** [comment]
@Aleksandra13 you probably will want to read https://github.com/tux3/qTox/wiki/Video, it has instructions on how to vertically flip camera output.

If that "works" for you, feel free to close the issue.

In a case where instructions there may not be clear enough, could you point out problematic parts, so that they could be improved?

**Comment by tux3** [comment]
> [video4linux2,v4l2 @ 0x4d1c9e0] Cannot find a proper format for codec 'mjpeg' (id 8), pixel format 'none' (id -1)

That looks like a fallout of the fix to #2826, turns out v4l will not fallback to an alternative if it can't provide what we ask. So we should try again without asking for a specific codec if mjpeg fails.

**Comment by Aleksandra13** [comment]
Thank you! That helped. It would be nice to have such feature integrated int client.
