### ISSUE TITLE
Groupchat invite flooding ratelimit

### ISSUE THREAD

**Issue by xor-gate** [qTox/qTox#2853]
A friend of mine was able to flood 10x a groupchat window into my client. 
I had to confirm in the order they where received. Probably what we want is
to have only one outstanding invite window.

You are using qTox version v1.2-307-g26e7bde on OSX
Commit hash: 26e7bde991a5dba14d9ab5e3215187f98372f5d1

See screenshot:
<img width="1146" alt="screen shot 2016-01-24 at 20 47 39" src="https://cloud.githubusercontent.com/assets/1050166/12538537/1aed6c50-c2dc-11e5-82af-3f5a1c8eeff1.png">

**Comment by rikvdh** [comment]
@rikvdh, would that be me?

**Comment by zetok** [comment]
IIRC that kind of thing was supposed to be mitigated by #2092.

**Comment by xor-gate** [comment]
I think my report is related to this issue: https://github.com/tux3/qTox/issues/2305. As suggested in #2305 the invite could be much more clean by having a extra "notification tab" and not spawning confirm dialog boxes like crazy.

**Comment by zetok** [comment]
Right, thanks for finding that issue, this one is actually a duplicate, thus closing.
