### ISSUE TITLE
Mentorship in GSoC for qTox

### ISSUE THREAD

**Issue by thelastpolaris** [qTox/qTox#2855]
Google Summer of Code 2016 is about to open and on 8th of February mentoring organisations can start to submit their applications. Are there any contributors of qTox that want to take part in GSoC as mentors? I don't have any particular ideas about GSoC project for qTox right now but as zetok has suggested me on IRC, I can make a list of the issues or good ideas from community and implement them within my project. Of course you can bring your own idea of how we can make qTox better application.
Is there anyone that want to become GSoC mentor from qTox?
Link to GSoC 2016 FAQ page https://developers.google.com/open-source/gsoc/faq

**Comment by ovalseven8** [comment]
The most important at the moment would be fixing bugs/issues, I guess.
But does the qTox Project not have to be an organization to apply for GSoC 2016?

**Comment by thelastpolaris** [comment]
I think that qTox can participate in GSoC as a part of Tox project
Here you can find ideas for GSoC 2015 for qTox https://wiki.tox.chat/developers/gsoc/2015/ideas and one of this ideas for qTox was implemented during GSoC 2015

**Comment by agilob** [comment]
Android port. Like 8-10months ago qTox worked much better on my nexus 7 than Antox works now...

**Comment by tux3** [comment]
@agilob Antox must be in bad shape, because qTox Android is pretty much just a blank screen that connects to the Tox network at the moment! It "works" but it completely lacks a GUI.

**Comment by ovalseven8** [comment]
I also think that it doesn't have any priority to work on qTox for Android. Goal should be to provide a nice client for Windows, Linux and OSX.

**Comment by sudden6** [comment]
@ovalseven8 +1

**Comment by thelastpolaris** [comment]
@agilob At first I also thought about android port, but zetok said me that Android port is not the highest priority of qTox right now.
If someone from qTox is going to be a mentor for GSoC I can make a list of improvements and issues and work with them within GSoC project for qTox. GSoC is a great opportunity for qTox to raise some money and get a new contributor :)

**Comment by ProMcTagonist** [comment]
Multimedia streaming would be fantastic and very impressive to users.

**Comment by Zer0-One** [comment]
qTox can indeed participate in GSoC under The Tox Project, as long as you can provide a dedicated mentor. Project ideas can be added here: https://wiki.tox.chat/developers/gsoc/2016/ideas

**Comment by zetok** [comment]
@thelastpolaris 

> @agilob At first I also thought about android port, but zetok said me that Android port is not the highest priority of qTox right now.

Err, I didn't really say anything about android port - it was @ProMcTagonist who said

```
[07:45:48] <vindelschtuffen> I really don't think qTox on android has or should have a future
[07:45:58] <vindelschtuffen> waste of dev time and energy
[07:46:06] <vindelschtuffen> non-native mobile clients suck
[07:46:11] <vindelschtuffen> focus on being a good desktop client
```

I simply don't know about that - if it's feasible to make a working qTox for android client and you want to do it, then you probably should go for it :)

# 

@ovalseven8 , @ProMcTagonist 

> I also think that it doesn't have any priority to work on qTox for Android. Goal should be to provide a nice client for Windows, Linux and OSX.

Thing is, when it comes to FOSS you can't really make people work on something. Very often it's either that those people will want to work on doing something that is important to them, or just would like to try to make something work, and if they can't, they won't bother to do anything at all.

While you're right that there's "little priority" for android port, it doesn't mean that someone shouldn't work on that. The only valid case to say "no" is when someone is working on something that has no chances of being accepted in qTox - which is clearly not the case here.

In any case, whether someone would work on general improvements & bugfixes for desktop qTox, or work on a port to android - it's an improvement anyway.

**Comment by thelastpolaris** [comment]
@zetok 
Sorry for mess in my memory :)
So now I have 3 directions:
1. Make Android version of qTox better.
2. Work with current issues and try to make qTox better client for desktops.
3. Multimedia streaming (btw. this idea was already presented in the last year but nobody took it https://wiki.tox.chat/developers/gsoc/2015/ideas)
It would be great if we could find a mentor for at least one of this projects.

**Comment by ProMcTagonist** [comment]
@zetok 

qTox on android is a fun project but not a particularly useful or high-priority one, which would be fine, except this is about GSoC. I agree that you can't control what people work on in FOSS, and in fact I often get annoyed when people bring up interesting side projects and get mad at toxcore for "allowing" it &ndash; they don't understand that that freedom is core to how FOSS works. 

But this isn't about FOSS, this is about what we specifically choose to encourage &ndash; and when we're getting an opportunity to 100% complete a given feature/project/whatever with funding and support through GSoC, we should choose something prioritized that users need, not just something fun or interesting.

That's the difference I see.

**Comment by zetok** [comment]
@ProMcTagonist 

> But this isn't about FOSS, this is about what we specifically choose to encourage – and when we're getting an opportunity to 100% complete a given feature/project/whatever with funding and support through GSoC, we should choose something prioritized that users need, not just something fun or interesting.

Well, GSoC is kinda an extension to FOSS - i.e. there's no way of making student to work on a particular project during GSoC - they might be interested in working on something in particular, or nothing at all. This is probably not the case with @thelastpolaris, but.. This issue is about getting a mentor.

# 

So, I kinda wonder - @agilob, since you've suggested android port, would you be interested in being a mentor for it?

**Comment by Zer0-One** [comment]
@agilob any interest in GSoC mentoring for qTox? AFAIK, you're the only candidate left. Everyone else is too busy. If not, is there anyone else who could step up?

**Comment by agilob** [comment]
> @agilob any interest in GSoC mentoring for qTox? AFAIK, you're the only candidate left. Everyone else is too busy. If not, is there anyone else who could step up?

Sorry, but no, I'm running out of energy and motivation to keep myself in OSS.

**Comment by ovalseven8** [comment]
Closable.
