### ISSUE TITLE
The following packages have unmet dependencies libavcodec-ffmpeg56...

### ISSUE THREAD

**Issue by Nurmagoz** [qTox/qTox#2856]
hi there , i wanted to install qtox inside debian following these instructions:-

https://wiki.tox.chat/binaries#gnulinux

`echo "deb https://pkg.tox.chat/debian nightly jessie | sudo tee /etc/apt/sources.list.d/tox.list
wget -qO - https://pkg.tox.chat/debian/pkg.gpg.key | sudo apt-key add -
sudo apt-get install apt-transport-https
sudo apt-get update`

now when i want to install qtox , here is the error:- 

> user@me:~$ sudo apt-get install qtox
> Reading package lists... Done
> Building dependency tree  
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  qtox : Depends: libavcodec-ffmpeg56 (>= 7:2.4) but it is not installable or
>                  libavcodec-ffmpeg-extra56 (>= 7:2.4) but it is not installable
>         Depends: libavdevice-ffmpeg56 (>= 7:2.4) but it is not installable
>         Depends: libavformat-ffmpeg56 (>= 7:2.4) but it is not installable
>         Depends: libavutil-ffmpeg54 (>= 7:2.4) but it is not installable
>         Depends: libsqlcipher0 (>= 1.1.9) but it is not installable
>         Depends: libswscale-ffmpeg3 (>= 7:2.4) but it is not installable
> E: Unable to correct problems, you have held broken packages.

so how to install these dependencies if they r not installable?!

**Comment by tux3** [comment]
Hi, you currently need to add the jessie-backports repository in your sources.list because Jessie otherwise doesn't have some of our dependencies.
We're trying to find a solution to this, maybe by importing those missing packages into the Tox repo.

**Comment by Nurmagoz** [comment]
yeah perfect, as u have said it needs just jessie-backports

solution:- (for users)

`sudo nano /etc/apt/sources.list`

add this by copy/paste (if u r jessie):- 

`deb http://http.debian.net/debian jessie-backports main`

then press 

> Ctrl+x 
> y

then hit "Enter"

after that:- 
`sudo  apt-get update`
`sudo apt-get install qtox`

= done.

if u r not jessie , please check here:- 

http://backports.debian.org/Instructions/

> We're trying to find a solution to this, maybe by importing those missing packages into the Tox repo.

yeah why not.

thnx for the fast reply (f).

**Comment by Nurmagoz** [comment]
btw , till now u cant install qtox from the installation tutorial which is mentioned in Tox website. 

u must add debian-backport , so i wonder why dont u mention this in Tox website.

**Comment by zetok** [comment]
https://github.com/tux3/qTox/blob/deeb9b2308290e0404198a38a5d4c456ac39b328/INSTALL.md#community-builds ← could you check if it works for you?

**Comment by zetok** [comment]
Community builds work on Debian 8, thus closing.

**Comment by Nurmagoz** [comment]
@zetok , sorry for the 2 late. that link is working , but this is not the problem. 

the problem when u add tox repo and u want to install qtox without adding debian backports = thats the problem (explained above how to fix it).

**Comment by zetok** [comment]
@TNTBOMBOM

> the problem when u add tox repo and u want to install qtox without adding debian backports = thats the problem (explained above how to fix it).

Yeah, those repos are being deprecated.

**Comment by sanguis** [comment]
so the problem is that the dependencies of the codec can not be installed

libx265-59
This package does not exist even in the back ports.

How ever I did a manual download and install of the package for ubuntu's wily repo 
http://packages.ubuntu.com/wily/amd64/libx265-59/download

I was able to install qtoc not problem after that.

(Mint LMDE Betsy based on Debian Jessie)

**Comment by Nurmagoz** [comment]
this problem still persisting so i wonder if u open it again @zetok

**Comment by zetok** [comment]
@TNTBOMBOM did you try what was asked?

**Comment by Nurmagoz** [comment]
@zetok yeah i did , but the point is still the same which = we need to use the BACKPORTS repo in order to install qTox. 

if u look at this link:- https://github.com/qTox/qTox/blob/deeb9b2308290e0404198a38a5d4c456ac39b328/INSTALL.md#community-builds

it mention the same thing:- 

> if you use stable, you have to add backports to your sources.list for FFmpeg and others. Instructions here: http://backports.debian.org/Instructions/

so we back to the same point that the instructions mentioned here to install qtox:- 

https://software.opensuse.org/download.html?project=home%3Aantonbatenev%3Atox&package=qtox

are not enough to make that happens , unless we add backports to debian repo. or u adding the missing packages to qTox repo.
