### ISSUE TITLE
Arabic keyboard/language doesnt show up

### ISSUE THREAD

**Issue by Nurmagoz** [qTox/qTox#2857]
hi there , im trying to use arabic keyboard inside qtox but the words doesnt show up when i type:- 
(zoom-in to c the photos clearly)

![qtoxprobwqe11111111111](https://cloud.githubusercontent.com/assets/11895339/12557619/bf99a64c-c359-11e5-99db-5584324e5b30.png)

also when the arabic language going to be implemented inside qtox ? because as per:- 

https://github.com/tux3/qTox/pull/2851

the translation done&merged if im not mistaking, but stil not there:- 

![qtoxprob22222222222222222222](https://cloud.githubusercontent.com/assets/11895339/12557760/587a0d84-c35a-11e5-9054-2a1b4598e08d.png)

thnx

**Comment by sudden6** [comment]
About the words not showing up, the last time this happened it was an issue with qt and not a qtox issue.

The language will show up in the next release. You can build it from source if you need it sooner.

**Comment by Nurmagoz** [comment]
> About the words not showing up, the last time this happened it was an issue with qt and not a qtox issue.

hmm well not sure i got u there , what do u mean by qt? 

> The language will show up in the next release. You can build it from source if you need it sooner.

very appreciated.

**Comment by sudden6** [comment]
> > About the words not showing up, the last time this happened it was an issue with qt and not a qtox issue.
> 
> hmm well not sure i got u there , what do u mean by qt? 

Qt is framework (set of libraries) we use to develop qTox. See the following bugreport for possible workarounds.

https://github.com/tux3/qTox/issues/2564

**Comment by zetok** [comment]
> also when the arabic language going to be implemented inside qtox ? because as per:-
> 
> #2851
> 
> the translation done&merged if im not mistaking, but stil not there:- 

You should contact about getting current qTox version the maintainer of `[Debian-qtox-i2p]`.

Aside from that, it looks like this issue is a duplicate of #2564, thus closing.

**Comment by tux3** [comment]
@zetok This looks like Qubes OS so I think [Debian-qtox-i2p] is just the name of the VM.

**Comment by Nurmagoz** [comment]
> @zetok This looks like Qubes OS so I think [Debian-qtox-i2p] is just the name of the VM.

thats correct. i was using Qubes OS. nice guessing @tux3 ;)

**Comment by zetok** [comment]
> @zetok This looks like Qubes OS so I think [Debian-qtox-i2p] is just the name of the VM.
> 
> thats correct. i was using Qubes OS. nice guessing @tux3 ;)

Oh, good to know.

There are some qTox .deb packages made by i2p dev, and I thought that this is from where you've got qTox.
