### ISSUE TITLE
Message timestamps should indicate initial message send time rather than the time it was recieved

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2863]
For instance, last night I said goodnight to someone on qTox, however they had already gone offline by the time I sent the message, I then went to bed and quit qTox, then the next day (today) when I logged onto qTox the other person was already online, and qTox sent them the message which it had not been able to send them yesterday as they had gone offline before I tried to send it.
Though there was one slight confusing thing, the message timestamp on both ends seems to show the successful delivery time rather than the first send time, so then the goodnight that I sent yesterday, looks like I sent it when I first signed in today which is very confusing...

So rather than this I think when I first send the message regardless of whether they are online or not, it should also send the first send time with the message so that when it is finally received it indicates the correct time when the message was intended to be sent.

I am running Ubuntu GNOME 15.10 with GNOME 3.18 and qTox version `469-c82e41f`.

**Comment by tux3** [comment]
This isn't part of the protocol, so toxcore would need to implement it.
Note that it would probably allow people to forge arbitrary dates on messages by having their client pretend to have failed to send it earlier.
