### ISSUE TITLE
built-in voice changer (suggestion)

### ISSUE THREAD

**Issue by Nurmagoz** [qTox/qTox#2864]
hi , i was wondering if we can implement voice changer inside qtox instead of using an outside app/program. and by this feature someone can be anonymous through typing & voice speaking, 

we can put for example , "The Anonymous" voice inside it or any voices that r possible (even normal voices). i think this is very unique design/feature which no app has at all (according to my information). 

(i know someone would say: the FBI have tools to filter the voices so this is useless feature , well the FBI have tools for stylometry analysis so is that mean we should stop typing?)

also staying anonymous doesnt mean the person should have problems witha police it is just freedom.

**Comment by ovalseven8** [comment]
Duplicate -> https://github.com/tux3/qTox/issues/2197
