### ISSUE TITLE
&quot; is displayed instead of "" in tooltips

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2868]
I have recently noticed that in the tooltips for user statuses it replaces any `"`s with `&quot;`. And I don't know if it does the same for any other characters as this is the only thing I've seen it for, though I haven't seen that many characters like this used in statuses or tooltips.

---

**OS Information:**

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:   wily
Flavour: GNOME
GNOME Version: 3.18
```

**Package Information:**

```
qtox:
  Installed: 469-c82e41f
  Candidate: 469-c82e41f
  Version table:
 *** 469-c82e41f 0
        500 https://pkg.tox.chat/debian/ nightly/release amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by ghost** [comment]
Oh, it seems also to do with for `'`s, and probably other special characters too.

**Comment by DeerSpotter** [comment]
utox client did a amazing job at notifications in the win10 environment. but the qtox version doesnt have any notifications. So strange.

**Comment by SeventhSonOfASeventhSon** [comment]
@DeerSpotter, I'm sorry, but what has that got to do with this bug report?

**Comment by DeerSpotter** [comment]
removed useless comment.
