### ISSUE TITLE
There should be a log out button

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2869]
Currently if one wants to log out they have to quit qTox, and this is something which can be rather annoying if a user wants only to, say, switch users, so it would be much better if that was also a "Log out" button.

**Comment by tux3** [comment]
Click on your avatar to go to the profile page, you'll find a logout button there.
I agree that the profile page is hard to find, but we don't have a better design at the moment.

**Comment by agilob** [comment]
Right click on tray icon has logout action...

**Comment by ghost** [comment]
Ok, it would be useful if it could also be in the menu in the top bar for the application which currently only has the "Quit" option.

**Comment by LuccoJ** [comment]
That top bar menu is a GNOME and GTK-specific thing that Qt apps generally know nothing about, and which is not available outside of GNOME.
With programs that are not topbar-aware (everything except some modern GNOME 3 programs), GNOME Shell simply creates a default menu with only "Quit" in it.

**Comment by ghost** [comment]
Well, there is also a similar thing in Unity. But basically I think the best thing would be to put a big colourful (I'm sort of joking about the colourful) button at the top next to where the profile picture and user status is. Or maybe at the bottom with the options to go to different sections such as the "Options" section. I don't know, but the log out button really needs to become more obvious...
