### ISSUE TITLE
"Load automatically" button greyed out on login screen

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2870]
On the login screen as you can see here the `Load automatically` button is greyed out (I have put a black box over my username as I wish to keep that private):

![qtox_load-automatically_greyed_out](https://cloud.githubusercontent.com/assets/11575271/12594886/35391a24-c470-11e5-8c96-716f0478826b.png)

This has been the case since one of the last updates, now, I don't know if this is meant to be the case for some reason which I have not yet discovered, but either some clarification is needed on how to use this feature, or this is a bug.

---

**OS Information:**

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:   wily
Flavour: GNOME
GNOME Version: 3.18
```

**Package Information:**

```
qtox:
  Installed: 469-c82e41f
  Candidate: 469-c82e41f
  Version table:
 *** 469-c82e41f 0
        500 https://pkg.tox.chat/debian/ nightly/release amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by agilob** [comment]
Should be gray only for encrypted profiles? Is your profile encrypted? Mouse hover shows you tooltip.

**Comment by tux3** [comment]
This is not a bug, it's a feature™!
If you mouse over the grayed out option, it'll explain that this is only available for profiles that don't have a password.

When a password is set, qTox will use strong encryption to protect the profile data, so it's impossible to load the profile without knowing the password. 
The "load automatically" option for password-protected profiles would have to force qTox to write down your password in a file to work, and this would be worse than not using a password at all! 
So the option is grayed out when you have a password. If your password annoys you, you can remove it or change it at any time in your profile page (click on your avatar).

**Comment by ghost** [comment]
Ah, I see yes, I use an encrypted profile!
