### ISSUE TITLE
Until you have renamed a Circle there is no divisory line

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2873]
I have recently found that if one creates a Circle:

![circle_no_line](https://cloud.githubusercontent.com/assets/11575271/12616920/472dd23e-c505-11e5-8207-c6e69ceeb664.png)

That until it is renamed, the divisory line does not appear fully:

![circle_with_line](https://cloud.githubusercontent.com/assets/11575271/12616945/64c4f318-c505-11e5-835a-3aac4c9cfa48.png)

---

**OS Information:**

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:   wily
Flavour: GNOME
GNOME Version: 3.18
```

**Package Information:**

```
qtox:
  Installed: 471-a3802bd
  Candidate: 471-a3802bd
  Version table:
 *** 471-a3802bd 0
        500 https://pkg.tox.chat/debian/ nightly/release amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by zetok** [comment]
Actually, it can be made to disappear also when circle has been renamed, but yeah.
![disappeared in renamed](https://cloud.githubusercontent.com/assets/3148759/12617909/8de63532-c509-11e5-88d1-edd4499afaf6.png)

**Comment by ghost** [comment]
Oh, well I haven't come across what you describe yet there... But anyway, it's a bug.

**Comment by PKEv** [comment]
can't repeat (Debian GNU/Linux 8.4 (jessie) )

**Comment by jessica181920** [comment]
appears to no longer be an issue, line is there for both renamed and non-renamed circles

**Comment by anthonybilinski** [comment]
Agreed, closing.
