### ISSUE TITLE
Clicking off should also save new Circle title

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2874]
Currently when one renames a Circle one has to press enter in order to save the changes to the name, I think there should at least be an optional ability to also make it so that it saves the changes made to the Circle title when the field is clicked off (this is the case in most programs).

**Comment by michals** [comment]
Please find related pull request here: https://github.com/tux3/qTox/pull/2982 
I apologize for missing '#' in [commit title](https://github.com/michals/qTox/commit/04b3276b0f7245a8b588a67d70311f7778566b0b).

**Comment by tux3** [comment]
Fixed by #2982, thanks @michals !
