### ISSUE TITLE
You should be able to make sub-Circles in Circles

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2875]
Currently you can categorise contacts into "Circles", and this is useful, however I think that it would also be good if you could make "sub-Circles" and "sub-sub-Circles" of those etc.

**Comment by zetok** [comment]
Well, the design decision was to not have sub-circles. If you think that this isn't right, you should read through #1125, other related issues and PR that implemented this idea, and provide arguments that counter arguments that were used to support this decision.

Closing for now - if you will decide to post here those arguments, I, or someone else will reopen the issue.
