### ISSUE TITLE
You should be able to have more than one conversation with someone

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2877]
Currently the only hope of having two or more places where I can chat with the same person is to create a group chat, however it would be very useful if one could set up more than one chat with a contact at the same time so that both of the chats are separate and their history is kept separately too. So maybe then I could have a chat with that user on one topic in one place with its own history, and another separate one on another topic with its own separate history. Maybe there would be a little pull-down menu from each contact that has more than one chat with them so that one may choose which to go to, but have it all under the same contact otherwise it will get confusing.

**Comment by zetok** [comment]
That sounds like overcomplicating things. I mean, the way you describe it, it kinda sound nice for a specific use case, but at the same it would make qTox's interface more complex, and thus complicated for all other use cases, and users who wouldn't have a need for it. Not to mention making qTox code even more complicated.

Also, what you've described is only a small part of UI that would need to be put in place, and prior to that planned & designed.

**Comment by n1trux** [comment]
I'm against it because no other chat system does it and honestly even as power user I never felt the need. If you still ened it, create a PR ;)

**Comment by ghost** [comment]
@zetok, I still think that it would be a good and useful feature though, and it could be something optional so it wouldn't have to be there in the UI initially (not until the user turns the feature on anyway). Because it is sometimes necessary to have separate conversations with one or more people which have different chat histories. For instance one could have several projects with someone and they might want to have each one of them having a different chat, and then personal conversations to have their own chat too.

**Comment by sudden6** [comment]
I'm with zetok and n1trux, this sounds like a very complcated thing, used only by a handful of people.

@SeventhSonOfASeventhSon If you really need multiple chats with the same person at the same time, you can already create more than one profile and use them simultanously. With this way you get a seperate history for each profile.

**Comment by ghost** [comment]
@sudden6, Who wants the hassle of having to create lots of accounts for this sort of thing? It would be much better for the client just to accommodate users' needs, plus you don't know how many people would use it, you haven't done a poll.

**Comment by ghost** [comment]
It could at least be left as an open issue which could be dealt with in the future, but just asking users to create lots of different accounts for different purposes is not acceptable.

**Comment by TheNain38** [comment]
For me, I wouldn't need this. Also, this will make code harder to maintain

**Comment by ghost** [comment]
@TheNain38, But you can't speak for everyone, and we could just strip down all the futures of the client so that one can only send and view one message at a time with no history, I'm user that that would also make the code much easier to maintain.

**Comment by agilob** [comment]
It would be really hard to implement and I would consider this a bug, since chat with one contact should be kept in one history to be consistent in regards of code base and... chat history. I would suggest you creating more tox profiles to achieve the same effect without messing database and history keeper.
