### ISSUE TITLE
Why can you not send files in group chat?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2878]
I see that currently the option to send files is greyed out in group chat, why is this?

I am running Ubuntu GNOME 15.10 with GNOME 3.18 with qTox version `471-a3802bd`.

**Comment by zetok** [comment]
toxcore doesn't support it.

**Comment by zetok** [comment]
Actually, it's not even known whether toxcore will ever support it, thus closing this issue.

If toxcore will ever support that, qTox should have support for it.
