### ISSUE TITLE
If one or more users are offline in a group chat messages fail to send

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2879]
I have not quite figured out yet whether the issue is here if a user is not online in a group chat but has actually joined and then users send messages there, but this is basically what just happened to me:

I created a group chat, I invited a friend there, we spoke a bit, I then invited another friend there who is currently offline and was offline when I sent the request so they haven't accepted the request yet, but now when I try to send a message in group chat I just get this:

![message_failed_to_send](https://cloud.githubusercontent.com/assets/11575271/12619534/5614b82a-c510-11e5-8678-d9208685fe69.png)

And the other person in the group chat who is online says that they did not receive my messages. They also tried sending messages to me there and though it told them that they sent it without error and it now shows up in their message history, I did not receive it, and as I am talking with them in the normal direct chat as opposed to the group chat, I know that the issue is with the group chat and not with the internet connection or something.

---

**OS Information:**

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:   wily
Flavour: GNOME
GNOME Version: 3.18
```

**Package Information:**

```
qtox:
  Installed: 471-a3802bd
  Candidate: 471-a3802bd
  Version table:
 *** 471-a3802bd 0
        500 https://pkg.tox.chat/debian/ nightly/release amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by zetok** [comment]
That's how toxcore works - nothing can be done about it with current groupchats, thus closing this issue. 

AFAIK once new groupchats will get TCP & audio support and get merged into toxcore, that kind of problems shouldn't occur any longer. No idea when that might happen, but it's probable that it will take years to get there.

Sorry about that.

**Comment by ghost** [comment]
I don't think it's really acceptable to leave such a big issue and not fix it for years. Is it worth me even reporting this on toxcore?

**Comment by zetok** [comment]
> Is it worth me even reporting this on toxcore?

Those are known issues - the reasons why new groupchats are being developed. About time - if there was more people working on it this would be done faster. So, reporting that is kinda a waste of time.

**Comment by ghost** [comment]
@zetok, Ok, well I don't see how it can hurt anyone (me reporting it on toxcore too) so I think I'll do that just to keep track of the issue as this is obviously not a client-side issue.
