### ISSUE TITLE
Better controls for the user who created the group chat

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2880]
If one accidentally sends a request to one of their contacts to join a group chat they are unable to cancel that request, I think that you should be able to have this ability because you could be having a very private conversation with some people and then you might accidentally add someone and then not be able to do anything about it. I also think that the user who created the group chat should have better control over it so they are be able to do things like remove or ban (meaning that nobody can add them unless they get unbanned) a user from it.

**Comment by ovalseven8** [comment]
Things like banning is coming with the new groupchat. :)

To cancel a group invitation isn't supported by toxcore as far as I know and probably won't. 
So, nothing qTox can do about this.

**Comment by ghost** [comment]
@ovalseven8, And when exactly is the new group chat coming?

**Comment by ovalseven8** [comment]
@SeventhSonOfASeventhSon: Nobody really knows. In general, the new group chat code is done for a few months, but toxcore would need some modifications for it. Unfortunately, nobody has worked on it yet. :(

**Comment by ghost** [comment]
@ovalseven8, Should I perhaps create an issue on toxcore to track it?

**Comment by agilob** [comment]
Yes, please.

**Comment by ghost** [comment]
Ok, I have posted the issue [here](https://github.com/irungentoo/toxcore/issues/1514).

**Comment by ghost** [comment]
I don't know how they're going to take to me trying to organise them by asking for them to post updates there, they might just close it saying they don't want me to order them around... But it's worth a try!
