### ISSUE TITLE
When will qTox start having proper "*.*.*" version numbers?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2886]
Currently qTox doesn't have a proper version number and only the commit hash is used, so when exactly is it planned for qTox to start using proper "_._.*" version numbers rather than commit hashes? I assume that it is after a certain milestone that this is planned, but it would be nice to know which one, and if this is not planned, then when it probably will happen.

**Comment by tux3** [comment]
We're at [v1.2.4](https://github.com/tux3/qTox/releases) at the moment.
You've been creating a _lot_ of invalid or duplicate issues, please try to do a minimum of research.

**Comment by ghost** [comment]
@tux3, Really? I was told a little while ago that there weren't any proper version numbers, well, it's not very clear, if we are now using proper version numbers why is that not reflected in the `About` section of qTox where only the commit hash is given and also when there is an update I always see something like this as the version number, why is this `472-3307855` displayed rather than the actual version number?

**Comment by ghost** [comment]
Oh, sorry, I didn't notice that it was already in the `About` section, however why is it not given as the package's version, because when I update it through `apt-get` in Terminal, it always gives me that commit hash rather than the version number?

**Comment by agilob** [comment]
We are not responsible for packages, please contact package maintainer.

**Comment by ghost** [comment]
@agilob, And how exactly do I do that? Who exactly is the package maintainer anyway?

**Comment by optimumtact** [comment]
as far as I'm aware tux3 manages the qtox packages

**Comment by tux3** [comment]
I manage the Debian/Ubuntu pbuilder packages (but not the static/generic/rpm packages).

**Comment by optimumtact** [comment]
I think what @SeventhSonOfASeventhSon is interested in is stable packages that have a fixed version, rather than the nightly releases with the git describe version tags

I explained in my email that the nightly releases are versioned this way so developers can identify exactly which commit the nightly release was built off.

**Comment by agilob** [comment]
> I explained in my email that the nightly releases are versioned this way so developers can identify exactly which commit the nightly release was built off.

We have commit hash built-in in about page.
