### ISSUE TITLE
A ToxID can be an email address?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2888]
Sorry if toxcore would be a better place for this, it's just that I haven't seen this in any other Tox client I've used (not that I've used that many other than qTox), so I thought I'd ask here.

My confusion stems from the fact that here it seems to suggest that instead of the standard ToxID one can give what appears to be an email address:

![add_friend_qtox](https://cloud.githubusercontent.com/assets/11575271/12659742/425f4392-c608-11e5-94d9-c0b7da684961.png)

What is this about? I assume it's not email, but what exactly is it? How do you add people that way?

**Comment by ghost** [comment]
https://wiki.tox.chat/users/toxdns

**Comment by tux3** [comment]
It's not an email address, it's a toxdns address. You have to register on a toxdns server to get an address, see @kehugter's link for more info.

**Comment by ghost** [comment]
@tux3, I would suggest then perhaps that it should be made a link in the client that one can click in order to learn more about it and how to get one, otherwise it's just going to confuse people because it is not clear what it is.

**Comment by tux3** [comment]
@SeventhSonOfASeventhSon We could do something like that, yes. There are also proposals for doing a proper user manual or even a first-use-tour-of-features that could be taken into consideration.

And I'm @tux3, @tux is someone else that is probably sick of getting notified all the time :)

**Comment by ghost** [comment]
@tux3, Yes, something like that would be good because it's not immediately obvious, and it will just confuse people, and then they will ask here.

Oh, sorry, I did mean to put the `3` at the end... :D

**Comment by username1565** [comment]
Is there something, like https://toxme.io/ 
![22a4ea89e9fa145ed2ca433e5c33bc7b_1296_m](https://user-images.githubusercontent.com/39200328/76250551-3dade880-624e-11ea-81a5-18980c7b854c.png)
???

**Comment by anthonybilinski** [comment]
https://toxme.io was taken offline a few months ago, and I'm not aware of another widespread similar service. qTox has removed support in https://github.com/qTox/qTox/pull/5898 for that reason.
