### ISSUE TITLE
[Regression] notification sound isn't being suppressed when status is being set to `busy`

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#2893]
Description:
When user status is set to `busy`, qTox should suppress notification sound for the new message. Probably due to a fix to the #2328 it doesn't do that any longer.

qTox: 67620f96617312ccbb27c721c2c3090f036d52e3

Reproducible: Always

Steps to reproduce:
1. Set status to `Busy`
2. Make sure that `Play sound` is checked in settings
3. Receive a message when qTox is minimized to tray

What happens:
qTox plays notification sound for a new message.

What should happen:
qTox should should not play the notification sound on a new message.

**Comment by tux3** [comment]
That's A Feature™ if I remember correctly. People on IRC lobbied for busy status having notification sounds which led to that fix to #2328

**Comment by zetok** [comment]
Dunno about "people on IRC", but there's  #1091, and it's a clear regression, which makes `Busy` ~useless.

**Comment by TheNain38** [comment]
I'm with @zetok's opinion, because for now, `Busy` is a little bit useless.

**Comment by tux3** [comment]
Fine by me if that's the consensus
