### ISSUE TITLE
Lack libwayland-cursor0

### ISSUE THREAD

**Issue by dcapeletti** [qTox/qTox#2895]
Hello, I have a GNU/Linux distribution 32-bit but I can not find the libwayland-cursor0 package is required to run qtox. What can I do?

**Comment by sudden6** [comment]
What is the name of the distribution?

**Comment by zetok** [comment]
@dcapeletti https://github.com/tux3/qTox/blob/master/CONTRIBUTING.md#must-read ?

**Comment by dcapeletti** [comment]
**sudo lsb_release -a**
 No LSB modules are available. 
Distributor ID: Debian 
Description: Debian GNU/Linux 7.5 (wheezy)
 Release: 7.5 
Codename: wheezy

**sudo uname -a**
Linux huayra 3.13.0-3-686-huayra #1 SMP Fri Jan 31 12:49:54 ART 2014 i686 GNU/Linux

**Comment by zetok** [comment]
Sorry, Debian 7 is not supported, you should update to 8 for qTox to work.

**Comment by agilob** [comment]
We also should drop 32bits...

**Comment by zetok** [comment]
Well, about 32 bits - there's still a lot of hardware that people use that doesn't support x86_64. It's not necessarily even an old hardware, given that x86-only hardware was still being released(!) by e.g. intel not so long ago as 2010...

**Comment by sudden6** [comment]
what would dropping 32bits improve?

**Comment by ProMcTagonist** [comment]
we aren't dropping 32-bit builds
