### ISSUE TITLE
qTox inserts unknown characters when copy-pasting PGP keys

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2897]
When trying to copy-paste the text from a text file containing a public PGP key, qTox inserts a number of random unknown characters that makes they key invalid.

**Comment by tux3** [comment]
I can't reproduce, could you post a screenshot of the unknown characters and a copy of the source file?
Note that Tox also has a file transfer feature if you want to send some data.

**Comment by ghost** [comment]
For some strange reason it's also no longer reproducible here on our computers. We had the issue yesterday when attempting to share a public key between 2 computers. But today it works fine. Only issue is qTox splitting up the key at message_maxlength. But there are no longer any random characters being inserted so I'm closing the issue.
Thank you for the quick response
