### ISSUE TITLE
shared library not found

### ISSUE THREAD

**Issue by qqtop** [qTox/qTox#2898]
./qtox: error while loading shared libraries: libxkbcommon-x11.so.0: cannot open shared object file: No such file or directory

/usr/lib64/libxkbcommon-x11-0.4.3.so  is available

OS: opensuse13.2 , opensuseLeap42.1

**Comment by optimumtact** [comment]
There is no specific package for qtox on opensuse, did you use the release binary? It probably doesn't have libxkbcommon statically compiled in, you may have to manually build qtox, or try these community provided packages

```
https://build.opensuse.org/package/show/home:antonbatenev:tox/qtox
```

**Comment by zetok** [comment]
@qqtop it has been added to INSTALL.md: https://github.com/tux3/qTox/blob/deeb9b2308290e0404198a38a5d4c456ac39b328/INSTALL.md#community-builds ← could you check if it works for you?

**Comment by qqtop** [comment]
Tested , it works ... thank you for following up.

**Comment by zetok** [comment]
Well, since it works, closing.

Thanks for testing :)
