### ISSUE TITLE
Messages are not aligned with users' names

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#290]
At least for the first messages of the user(s).

http://a.pomf.se/uwvavx.png

**Comment by tux3** [comment]
Actually, I can reproduce. I just hadn't noticed that it was only for groupchats.

**Comment by tux3** [comment]
Aaaand I can't reproduce anymore.

**Comment by dubslow** [comment]
At least you can join group chats... I haven't successfully joined GroupBot in more than 2 weeks...

**Comment by mouseym** [comment]
to add to this, there isn't a clear separator between a user's name and the message they send..

**Comment by tux3** [comment]
@mouseym I totally agree, but I have no idea how to fix this. Maybe making the names really bold or underlined ? Or just some extra spaces at the end ?

**Comment by dubslow** [comment]
Bold seems like a simple and effective idea

**Comment by mouseym** [comment]
bold, uppercase and flashing text seem appropriate

**Comment by apprb** [comment]
Can be closed.
