### ISSUE TITLE
make install should install icon files

### ISSUE THREAD

**Issue by farseerfc** [qTox/qTox#2903]
Currently `make install` will not install any icon files.

I tried to install them manually, but if I put them iunder /usr/share/icons/hicolor/$size/apps/qtox.png 
The systray icon will not change when message is coming.
If I rename them to qTox.png (the upper case T), the .desktop file is not referring to the right icon.

**Comment by ovalseven8** [comment]
Agree.

Shouldn't https://github.com/tux3/qTox/blob/master/qtox.pro#L182 do it?

**Comment by zetok** [comment]
> If I rename them to qTox.png (the upper case T), the .desktop file is not referring to the right icon.

Why rename then?

Also `qtox.svg` is being installed for me. Is `.svg` not enough for icons?

**Comment by farseerfc** [comment]
If the icon is named qtox.\* , systray icon will not reflect state changes. (Didn't find a bug here related to this)
See: https://bugs.archlinux.org/task/47910
I don't see any line in the generated Makefile by qmake that installed `qtox.svg`. Did I miss something?

**Comment by zetok** [comment]
> I don't see any line in the generated Makefile by qmake that installed qtox.svg. Did I miss something?

No, sorry about that - looks like it's not being installed by qTox after all.

**Comment by jurf** [comment]
So uh, is it going to install it then?

**Comment by vith** [comment]
Sorry about the "referenced" spam, didn't realize it would find the mentions in my fork repo.

If that PR is accepted the icon renaming workaround at arch linux shouldn't be necessary anymore and you'll be able to simplify the PKGBUILD similarly to this one I've been testing with https://gist.github.com/vith/97e3ccea15f53e0048f95d43daea6d74

**Comment by zetok** [comment]
> Sorry about the "referenced" spam, didn't realize it would find the mentions in my fork repo.

No problem – after all that doesn't get sent in mails anywhere :)
