### ISSUE TITLE
qTox should only show recent chat history, but should provide buttons in order to load older history

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2906]
If one has been using qTox for a long time without clearing their chat history (because perhaps they don't want to), then for performance reasons I think that it would be better if (and if this would also be configurable) only chat history from the last 24 hours or something was displayed at first, but if a user scrolled right up to the top it would either automatically load older stuff, or allow you to click a button which would do so. This would be then similar to how Skype handles this.

**Comment by zetok** [comment]
There is "button" for it.

Edit: as for automatically loaded history, there's an issue for it somewhere.

**Comment by ProMcTagonist** [comment]
new chatform with load recent + load more on scrollback was #2013 and got split up into smaller commits and issues from there

**Comment by ghost** [comment]
@zetok, That's strange, because I definitely don't get the button... So maybe it's a bug?

**Comment by ProMcTagonist** [comment]
right click on the chat form
