### ISSUE TITLE
[Request future] Share desktop

### ISSUE THREAD

**Issue by SergeyDjam** [qTox/qTox#2910]
Hello! Phanks this program. 
Please add sharing desktop and/or sharing only window open on desktop. May be this will be goot addition

**Comment by sudden6** [comment]
Sharing the whole desktop is already supported. In Settings | Audio/Video set your video device to "desktop".
Please close if this is what you needed.

**Comment by SergeyDjam** [comment]
Oh, sorry, i'dnt this viewiing

**Comment by SergeyDjam** [comment]
Phanks

**Comment by SergeyDjam** [comment]
But this can not only window, can not parallel video and desktop/windows different user call :(

**Comment by sudden6** [comment]
If I understood you correctly you mean there should be parallel webcam video and desktop streaming?
There already is a feature request for this, but it is very low priority.

**Comment by SergeyDjam** [comment]
I'm no first... Ok, i will wait
