### ISSUE TITLE
Build qTox for Android

### ISSUE THREAD

**Issue by SergeyDjam** [qTox/qTox#2911]
I view source for Android. How i can build this for Android, or may be precompiled qtox.apk testing?

**Comment by zetok** [comment]
There's no real port of qTox to android that would have any usable functionality - are you perhaps interested in helping make it become functional under android?

**Comment by SergeyDjam** [comment]
I doubt that I can fully support this port. However, it could perform simple tasks such as assembly and testing of the package.I could localize into Russian

**Comment by tux3** [comment]
Currently qTox for Android is unusable, it's not ready for release, packaging or testing.

**Comment by mika-nl** [comment]
Any news for a android version ?

**Comment by anthonybilinski** [comment]
No progress towards that for qTox. Still a long way off if someone was working on it, as it would require a total UI overhaul.

There are compatible mobile tox clients though, check out aTox: https://github.com/evilcorpltd/aTox and TRiFA: https://github.com/zoff99/ToxAndroidRefImpl
