### ISSUE TITLE
Input methods don't work on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#2912]
Never saw them work, though virtually all other apps use input methods fine.

**Comment by zetok** [comment]
Are those other apps using Qt5 ?

**Comment by zetok** [comment]
might be related: #2564

**Comment by yurivict** [comment]
Yes, other apps are qt5

Input method is ignored. Latin letters are typed instead.

**Comment by agilob** [comment]
Could you provide more details? I don't have any problems with qtox on fbsd

**Comment by yurivict** [comment]
What details for example?

**Comment by zetok** [comment]
> What details for example?

Your setup - given that @agilob can't reproduce, it would seem that there's come configuration required, or something. In other words, steps to reproduce, preferably with a startpoint at standard, fresh FreeBSD install.

**Comment by yurivict** [comment]
qTox is installed from the port. No special configuration of any kind.
Input methods are switched with ibus.
Other qt5 apps work with input methods fine, just not qTox.

**Comment by yurivict** [comment]
Now when I test more I see that IM works when qtox is started from the terminal, or from the kde start menu using the executable path, but it doesn't work when it is started from the kde start menu using the qTox.desktop file. I don't know why desktop file would prevent IM from working.

**Comment by agilob** [comment]
I also have qTox installed from ports, I use xfce4 and have no problems what you described I can paste emojis and input Polish special chars from keyboard. Do you have correct lang, keybindings setup?

**Comment by yurivict** [comment]
LANG=en_US.UTF-8
keybindings do switch input methods fine.

I think this is some kde4 bug, because I observe the same with djview4. IM fail when started through the desktop item.

**Comment by agilob** [comment]
Interesting, could this be related to #2564?

**Comment by yurivict** [comment]
It might be that environment is modified when run through the desktop file, particularly QT_IM_MODULE=ibus.
