### ISSUE TITLE
Drop-down list and its elements are on different monitors.

### ISSUE THREAD

**Issue by torvn77** [qTox/qTox#2913]
![screenshot](https://pp.vk.me/c629314/v629314199/3541b/Pr8trN7YG_E.jpg)

**Comment by sudden6** [comment]
I can not reproduce
qTox version: 1f03ed11ad40af511719d2157b88c9d6028dc984
Qt version: 5.5.1
KDE: 5.18.0

**Comment by tux3** [comment]
That looks like a Qt problem, so unfortunately we can't really fix this in qTox

**Comment by zetok** [comment]
@torvn77 which Qt version do you have, and which distro? That looks like Mint - is it 17, based on ubuntu 14.04 ?

In case you're using binaries from repo, and given that @sudden6 can't reproduce on 5.5.1, it might be packaging.

**Comment by torvn77** [comment]
> @torvn77 which Qt version do you have, and which distro?

Debian jessie 
 // I removed a few screens long list of installed packages, ~agilob

**Comment by sudden6** [comment]
Is this still an issue? If not please close.

**Comment by sudden6** [comment]
Closed because needed information was not provided.
