### ISSUE TITLE
Received double messages

### ISSUE THREAD

**Issue by anoadragon453** [qTox/qTox#2915]
Occasionally I get double messages from a friend with pretty slow internet (~500Kbps). Happens fairly rarely. I don't experience this issue with any other user, but do experience it with them across multiple profiles.

They and I are both on commit `552155bd1f5824c536dd6d1bbc8d293f3f1d8499`.

Really nothing interesting in the [log](https://gist.github.com/anoadragon453/d32c6769b2cfe8c5e51c).

**Comment by tux3** [comment]
This looks like a duplicate of #2899.
