### ISSUE TITLE
Contacts not accurately portraying online status

### ISSUE THREAD

**Issue by DeerSpotter** [qTox/qTox#2916]
![desktop](https://cloud.githubusercontent.com/assets/16710090/12721420/c211c430-c8cd-11e5-8125-79c8299c8142.JPG)

It keeps jumping the contacts on the screen of the tox application. The away and online presence is not working correctly. Also the notifications are not being sent. it just opens up the window and we have to search for the circle. which in my list you can see can be difficult.

**Comment by ProMcTagonist** [comment]
he went offline to you, changed his status to away, and came back online, so you detected him as "online" as soon as you reconnected and then he sent his away status to you within the same second, I'm guessing

the going-off-and-online is related to toxcore networking stability and adaptivity which is being worked on

**Comment by zetok** [comment]
@ProMcTagonist 

> he went offline to you, changed his status to away, and came back online, so you detected him as "online" as soon as you reconnected and then he sent his away status to you within the same second, I'm guessing

Um, no.

There appears to be some mishandling done by qTox.
e.g. what one sees when
- friend sets status to `Away`
- friend disconnects and connects again

```
2016-02-01 18:03:03.483416104 UTC: Event: FriendStatus(24, Away)
2016-02-01 18:03:09.687916326 UTC: Event: FriendConnectionStatus(24, None)

2016-02-01 18:03:31.974729732 UTC: Event: FriendConnectionStatus(24, Udp)
2016-02-01 18:03:31.975162902 UTC: Event: FriendName(24, "kotez")
2016-02-01 18:03:31.975390424 UTC: Event: FriendStatusMessage(24, ":3")
2016-02-01 18:03:31.975818189 UTC: Event: FriendStatus(24, Away)
```

↑ note the ~1.1ms of delay between toxcore informing about friend coming online (`FriendConnectionStatus`), and toxcore informing that friend's status is `Away` (`FriendStatus`). Plenty of time for qTox to do something.

My guess is that qTox on `tox_friend_connection_status_cb` sets friend status to something (which it shouldn't do).

**Comment by DeerSpotter** [comment]
looking at this in depth, un-checking UDP in connection settings and pressing reconnect stops the contacts jumping around and accurately portrays online status. can somebody else try to test and see if same thing? 

Keeping only UDP checked and not IPv6 makes everything go crazy... it could be just coincidence.

**Comment by DeerSpotter** [comment]
okay so unckecking anything and pressing reconnect makes the issue go away, ill monitor further to see how this conducts itself.

**Comment by zetok** [comment]
on qTox 1eb68542df922f2080e85c403dc3f866ef881e54:
![status](https://cloud.githubusercontent.com/assets/3148759/13599672/29245d12-e51c-11e5-99ab-0b8a28095ab9.png)

Second client was just launched (the one with a green orb), for a moment showed yellow orb, but then it changed to a green one.

**Comment by LittleVulpix** [comment]
I have the same issue (I think). qtox (1.3.0) shows my other client as "online" every time after startup (of qtox), even though the other client is actually away. Only by switching the other client to online and then back to away, qtox registers the actual away status.

edit: by other client I mean a separate client on a separate tox id.

**Comment by LittleVulpix** [comment]
Possibly related to: https://github.com/tux3/qTox/issues/2199

**Comment by LordVladneutral** [comment]
In my case, it's the busy status that works weirdly :
If I'm putting it and then someone connects, I will show as permanently connected (green) while I will see myself as (red)
The only way to solve that is to change my status to connected, then busy again.

**Comment by sudden6** [comment]
Assuming this is fixed since I didn't encounter this behavior in a recent qTox versions. If it's still an issue, please open a new one.
