### ISSUE TITLE
UI gets frozen when user hits 'Export' button (in Profile section) and then 'Ok' or 'Cancel'

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#2919]
Version 1.2.2 from port on FreeBSD-10.3 with kde4.

CPU isn't 100%. But mouse clicks don't work. Can't exit. Have to kill the process.

Profile doesn't get saved in case of 'Ok'.

**Comment by zetok** [comment]
Update your qTox. It's really outdated.

**Comment by agilob** [comment]
FBSD ports are out of date...

**Comment by yurivict** [comment]
I submitted an update to 1.2.4.
And the problem is indeed gone.
