### ISSUE TITLE
Add fullscreen mode in videocalls

### ISSUE THREAD

**Issue by azymohliad** [qTox/qTox#2922]
I think it would be very usefull feature. Especially for small screens.

**Comment by ElLamparto** [comment]
Agreed 100%!

**Comment by I60R** [comment]
+1, I need this feature for screen sharing

**Comment by ProMcTagonist** [comment]
semitransparent fullscreen icon overlaid on the bottom of the video window with other controls please

**Comment by Getron** [comment]
+1, would be great to have this to, double click on video, should change the full screen or normal.

**Comment by ElLamparto** [comment]
+1
