### ISSUE TITLE
Crash using version above qtox_389-1757dfb_i386.deb

### ISSUE THREAD

**Issue by Aalexeey** [qTox/qTox#2925]
The video camera is looks like a reason, the Audio/Video tab is crushing when camera is choosen.

**Comment by zetok** [comment]
@Aalexeey could you provide more info about the hardware you have?

**Comment by Aalexeey** [comment]
Samsung SyncMaster 963uw monitor integrated audio/web-camera  (Samsung UC Audio Analog stereo/Vega USB 2.0 Camera.).

**Comment by antis81** [comment]
@Aalexeey Does qTox crash or does it "hang" after you chose a video device? I'm asking because I had this behavior with a certain camera device. Current version (1.4+) works for me.

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.

If issue is still not fixed, please comment for reopen.
