### ISSUE TITLE
Need to display the date better in the conversation history

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#2927]
I am looking at the conversation history from few days ago, and can't easily tell what date was that.

Timestamp rolled over from PM to AM, and no new date was printed. Need to always print the date line, even if user only goes online/offline. qTox should only skip the date when nothing happened at all.

Additionally, I suggest the date should be printed with the gray horizontal line having a bold text in the middle of the line for easier visual recognition. Currently it is just a bold text and a green "i" in a circle.

**Comment by zetok** [comment]
Was supposed to be done in chatform #2013

**Comment by yurivict** [comment]
Observing in qTox-1.2.4

**Comment by sudden6** [comment]
Dates are now printed on every changed day.
