### ISSUE TITLE
qTox allows messages which appear empty to be sent

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2931]
I have recently noticed that if I press <kbd>SPACE</kbd> in a message, so that there is a space there, it counts that as a message and allows me to send it, most IM programs don't allow the sending of blank messages, or at least, ones that are only populated by space(s) and appear blank. So I don't think that qTox should either.

**Comment by agilob** [comment]
qTox does not modify user input or output, if you decide to send space, it's your will.

**Comment by ghost** [comment]
It's probably a good practice not in modify user input or output as a privacy conscious program in general, but not even preventing spaces from being sent is a little over the top, I mean, how could anyone abuse that? And sending spaces would probably be just a form of easy spamming...

**Comment by TheNain38** [comment]
@SeventhSonOfASeventhSon If I wanted to spam you, I would use a bot. Also, you can't prevent people from spamming on the sender side

**Comment by ghost** [comment]
@TheNain38, I suppose not, but it just feels strange to me that it allows me to send spaces...

**Comment by TheNain38** [comment]
@SeventhSonOfASeventhSon Anyone can modify the code and then recompile qTox. You don't implement protections on the sender side, you implement protections on the receiver side. Else, it's a useless protection

**Comment by LuccoJ** [comment]
I'd call _doing_ this a bit over the top. How could you damage anyone by sending spaces (any more than you could by spamming any other message type)?
On the other hand, implementing this could have unintended _drawbacks_, like breaking the formatting of things that are actually meant to only contain spaces. People often send "code-like" things as copied-and-pasted messages, even when maybe they should send as files instead.

I find it worrying that people are starting to find it "strange" when software actually allows them to do what they tell it to... these days, it almost seems like it's software that gets to decide what the user must do. Well, hopefully open software like Tox is different.

**Comment by ghost** [comment]
@LuccoJ, If there are other characters which are not invisible in the message, then the spaces wherever they may be would stay intact, I'm just saying if the message only has spaces for it not to be sent.

**Comment by LuccoJ** [comment]
@SeventhSonOfASeventhSon I understood what you said, but still there could be cases where a line made entirely of spaces is meaningful to, say, a programming language or other code (it's meaningful in MediaWiki markup, just to make a random example), and stripping it out would create problems for people trying to paste that, without any obvious advantage.

How can "I find it strange that it allows me to do this" be a good reason to add a restrictive feature?
