### ISSUE TITLE
Refactoring: move Qt generated files into subdirectory

### ISSUE THREAD

**Issue by Talkless** [qTox/qTox#2932]
When compiling qTox _not_ in "shadow build" mode (Qt Creator), root project dir gets filled with ui*.h, moc*.cpp and *.o files, which is annoying.

I have prepared patch to use qmake's MOC_DIR, UI_DIR and others to move these generated files into tmp subdirectory.

**Comment by Talkless** [comment]
#2933

**Comment by tux3** [comment]
Closing, since the PR was rejected.
