### ISSUE TITLE
focus on new message

### ISSUE THREAD

**Issue by azlux** [qTox/qTox#2937]
Hi,
With the option "close to tray", when a new message is coming, even with the option "On new message : Focus windows" disable, the window appear on the screen and not only on the taskbar .
I think this option will be better is the windows will not focus if we minimize or close the windows. 
What do you think ?

qTox version v1.2.4.
Commit hash: d550aa08a2aa7cb644692031684f43209440a1d5
windows 10.

Thank for your works !

**Comment by ovalseven8** [comment]
> With the option "close to tray", when a new message is coming, even with the option "On new message : Focus windows" disable, the window appear on the screen and not only on the taskbar .

Yep, that's a known bug -> https://github.com/tux3/qTox/issues/1985

**Comment by zetok** [comment]
Since it's a duplicate of #1985, closing.
