### ISSUE TITLE
Have an "About me" section where users can put what they want

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2940]
Though not all will have a use for this, for some this will just be something nice to have, but for others this will be something rather useful in some ways to put information that there aren't other fields for that they want their contacts to know without having to message each one about it. So I think that an "About me" section would be very useful (it would probably be located in the "Profile" section where one can set their username and status).

**Comment by agilob** [comment]
Not supported by toxcore.

**Comment by ghost** [comment]
According to [this guy](https://github.com/irungentoo/toxcore/issues/1526#issuecomment-181970354) it is possible:

> It should be possible to do this using custom packets (defined in the TCS).

**Comment by zetok** [comment]
> According to this guy it is possible:
> 
> > It should be possible to do this using custom packets (defined in the TCS).

Which is pretty much "not supported by toxcore".

**Comment by ghost** [comment]
@zetok, Well, look, the guy [here](https://github.com/irungentoo/toxcore/issues/1526#issuecomment-183489398) says that it's possible, so, isn't?

> you can already implement something like this inside a client with the custom packet api that already exists [on client connect you can send arbitrary data/updates for this section]

**Comment by zetok** [comment]
@SeventhSonOfASeventhSon 

> @zetok, Well, look, the guy here says that it's possible, so, isn't?

Feel free to do it, if you think that it should be done like that.
