### ISSUE TITLE
Remove “Filter audio” option from the settings

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#2942]
Remove “Filter audio” option from the settings or make it inactive.

**Rationale:** At the present time (February 2016) filter_audio is badly broken. The purpose of filter_audio is improving audio quality, that means not only normalization&compression but also echo cancellation. But instead of removing echo it actually _adds_ it. Added echo is so loud, so it even causes a feedback effect with the Echobot. But though the only thing filter_audio does is ruining audio quality, this option still available in the settings.

**Advantages:** UX improvment (no more a confusing option to damage quality)

**Disadvantages:** None.

**Unresolved questions:** Can we have a reasonable alternative to filter_audio?

See also: https://github.com/tux3/qTox/issues/1655, https://github.com/tux3/qTox/issues/2126, https://github.com/tux3/qTox/issues/2756 and many other issues.

**Comment by ovalseven8** [comment]
:+1:

**Comment by sudden6** [comment]
Can't we just disable the echo cancelation algorithm of filter_audio?

Also I read on IRC that filter_audio works, if the input latency is set correctly, maybe add a slider in the ui?
Of course this will only be useful for power users and we should find a proper solution for this problem.

**Comment by ProMcTagonist** [comment]
> if the input latency is set correctly

Why is it being set incorrectly? Is filter_audio broken or is qTox using it wrong? How does uTox use it?

**Comment by zetok** [comment]
Well, IMHO until it gets fixed it should be disabled.

# 

@sudden6 

> Can't we just disable the echo cancelation algorithm of filter_audio?

Isn't that, like the only thing filter_audio is supposed to do?

**Comment by sudden6** [comment]
@zetok 

quoting @suhr 

> The purpose of filter_audio is improving audio quality, that means not only normalization&compression,...

It seems to have other capabilities, altough I didn't check if they can be separately enabled/disabled.
EDIT: It seems to be possible, to only disable echo cancellation.

**Comment by antis81** [comment]
Unfortunately I don't have the time to look deeper into that topic in near future. However, I had a quick look into code and it looks like the filter is not initialized correctly and as a consequence, it is used wrong by qTox.

If you're interested in fixing this issue, have a look at this function (and related code):

``` c++
bool AudioFilterer::enableDisableFilters(int echo, int noise, int gain, int vad)
```

I couldn't find any method making use of that. Initializing this will most likely remove the confusion. However, I highly recommend documenting the filter (doxygen and a tooltip or something) and what it is actually supposed to do.

**Comment by ovalseven8** [comment]
Possible that qTox is using it wrong.
But it's a known thing that the filter audio feature isn't matured yet in general. So, I definitely support the suggestion to completely remove the function at the moment.

**Comment by TheNain38** [comment]
We could just as well add a tooltip saying it isn't "finished"

**Comment by agilob** [comment]
> However, I highly recommend documenting the filter (doxygen and a tooltip or something)

and the whole toxcore...

**Comment by anoadragon453** [comment]
I agree with removing it, it makes the audio sound terrible but is very tempting to check. I was fooled by it for a good few months, thinking Tox's audio was just terrible until a friend tried turning it off. Fixed it immediately.

**Comment by sudden6** [comment]
After further testing I come to conclusion, that filter audio off gives better audio quality, but makes it harder to adjust the input gain of the microphone.
filter audio on, on the otherside does a very good job at normalizing the volume and suppressing background noise, but if the input gain is very high, it creates feedback, even while I'm using a headset, which is very annoying.

I did my tests with a cheap logitech h340 headset and the changes to audio filtering in my qTox repo.

Overall I think the experience was better without audio filtering.
