### ISSUE TITLE
Should those editing displayed text also update translation files?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2943]
If I am to edit some text which is displayed in the qTox UI, should I also update translation files before making a pull request or can you guys deal with that? I assume that you will just deal with translations because you can't expect all the people here who want to make pull requests to know all the languages...

**Comment by agilob** [comment]
Please make them as two pull requests, one with source code changes, one with translations. Translator edit their translations independently.

**Comment by ghost** [comment]
So if I edited some text to make it the same as elsewhere, could I just submit that as a pull request and not have to worry about the translation files?

**Comment by agilob** [comment]
yes
