### ISSUE TITLE
Quick answer on voice or video incoming calls

### ISSUE THREAD

**Issue by Granitoid** [qTox/qTox#2947]
When someone calls me a voice or video, I do not  know who is it.
I have to open the qtox and look in the contact list.
It would be convenient to have a small pop-up window with the avatar, nickname and press "accept / decline". Also this button bind to hotkeys, for example: Ctrl+Alt+PageUp and Ctrl+Alt+PageDown

![qtox-incoming](https://cloud.githubusercontent.com/assets/16450834/12919990/ba1f8376-cf57-11e5-9a7b-883253b8f346.jpg)
.

**Comment by agilob** [comment]
I'm working on notifications and it was suggested too many times to even start looking for duplicates.
Interesting concept of notification but implementing it on more than one platform would be horrible coding experience.
