### ISSUE TITLE
Status icons in the popup menu in xfce became huge with 1.2.4 update

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#2949]
Icons look fine in the same menu in kde4.
Observed on FreeBSD.

![screenshotqtoxicons](https://cloud.githubusercontent.com/assets/2544251/12976595/3779f75a-d0bd-11e5-95c7-f4bb8287258e.png)

// please attach screenshots to issues, ~agilob

**Comment by zetok** [comment]
Are they still huge?

Edit: on newest qTox, that is, 1.3.0 or current master.

**Comment by yurivict** [comment]
@enodata Do you know by any chance if this is still a problem with 1.3.0?

**Comment by dmgk** [comment]
@yurivict No, the issue went away some time ago after one of the updates.

**Comment by zetok** [comment]
Well then, closing since it appears to be fixed.
