### ISSUE TITLE
After a successfull build on haiku qtox won't start

### ISSUE THREAD

**Issue by khallebal** [qTox/qTox#2950]
I should mention that i built it with "DISABLE_PLATFORM_EXT=YES" option, because i kept getting autorun compilation errors " setautorun , getsetautorun... Not declared in this scope.

**Comment by khallebal** [comment]
EDIT:it look like it's got nothing to do with fact that it's built with "DISABLE_PLATFORM_EXT=YES" option,i rebuilt it with this option enabled, and i get the exact same crash at the first start and all the times there after.
From the output it looks a known "IPC" issue but i couln't find a fix for it.

https://gist.github.com/khallebal/f13d90f3639409a0fe7a#file-crash-after-a-successfull-compilation-on-haiku
Anyone knows a fix for this?

**Comment by ProMcTagonist** [comment]
Solved?

**Comment by khallebal** [comment]
Nope, gave up.
