### ISSUE TITLE
Downloaded file preview label has hand cursor, but cannot be actually clicked

### ISSUE THREAD

**Issue by Talkless** [qTox/qTox#2952]
When file is downloaded and you hover mouse over preview label, you can see kinda hint that it can be clicked:
![qtox_hand_cursor](https://cloud.githubusercontent.com/assets/292191/13029653/c716fc8a-d29a-11e5-886d-6f4eb9c18497.png)

But clicking it does nothing.

I could implement a patch, either subclassing QLabel into ClickableLabel, or maybe simply changing it into button as other two widgets.

But I need a blessing.

**Comment by zetok** [comment]
@agilob I told you that people would think that it's a bug.

@Talkless I guess that you could implement opening image also when one clicks on the thumbnail.
