### ISSUE TITLE
Unable to type accented characters (é è ê)

### ISSUE THREAD

**Issue by Lesik** [qTox/qTox#2956]
Running Trisquel 7, I am not able to type any accented characters like é. They just appear as normal characters (e).

My keyboard layout it de (with dead keys).

I asked a Tox friend to try if he had the same problem, he confirmed.

I am using qTox version v1.2-164-gdefae04

**Comment by sudden6** [comment]
duplicate of #2564

**Comment by Lesik** [comment]
Oh sorry, I only searched for "accent" and found nothing. The title of #2564 isn't too descriptive.
