### ISSUE TITLE
Try to prevent homograph attacks

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2960]
Hello,

homograph attacks are also possible with qTox and some other Tox clients.
So, it's possible that a user's IP address can be disclosed.

Although it's hard to prevent, we should discuss about it, I think.

More information: https://en.wikipedia.org/wiki/IDN_homograph_attack

**Comment by SkyzohKey** [comment]
From wikipedia:

> The simplest defense is for web browsers not to support IDNA or other similar mechanisms, or for users to turn off whatever support their browsers have. That could mean blocking access to IDNA sites, but generally browsers permit access and just display IDNs in Punycode. Either way, this amounts to abandoning non-ASCII domain names.
> 
> Opera displays punycode for IDNs unless the top-level domain (for example TLDs such as .ac or .museum) prevents homograph attacks by restricting which characters can be used in domain names.[6] It also allows users to manually add TLDs to the allowed list.[7]
> 
> Since version 22 (2013), Firefox displays IDNs if either the TLD prevents homograph attacks by restricting which characters can be used in domain names or labels do not mix scripts for different languages. Otherwise IDNs are displayed in punycode.[8][9]
> 
> Internet Explorer 7 allows IDNs except for labels that mix scripts for different languages. Labels that mix scripts are displayed in punycode. There are exceptions to locales where ASCII characters are commonly mixed with localized scripts.[10]
> 
> As an additional defense, Internet Explorer 7, Firefox 2.0 and above, and Opera 9.10 include phishing filters that attempt to alert users when they visit malicious websites.[11][12][13]
> 
> Starting with version 7, Internet Explorer was capable of using IDNs, but it imposes restrictions on displaying non-ASCII domain names based on a user-defined list of allowed languages and provides an anti-phishing filter that checks suspicious Web sites against a remote database of known phishing sites.[citation needed]
> 
> Safari's approach is to render problematic character sets as Punycode. This can be changed by altering the settings in Mac OS X's system files.[14]
> 
> Google Chrome displays an IDN only if all of its characters belong to one (and only one) of the user's preferred languages.[15]
> 
> Some internationalized country code top-level domains are restricted in a way that hinders homographic attacks. For example, the Russian TLD .рф only accepts Cyrillic names, forbidding a mix with Latin or Greek characters. However the problem in .com and other gTLDs remains open.
> 
> ICANN has implemented a policy prohibiting any potential internationalized TLD from choosing letters that could resemble an existing Latin TLD and thus be used for homograph attacks. Proposed IDN TLDs .бг (Bulgaria), .укр (Ukraine) and .ελ (Greece) have been rejected or stalled because of their perceived resemblance to Latin letters (however, Serbian .срб was accepted, despite its resemblance to the Latin alphanumeric cp6).
> 
> These methods of defense only extend to within a browser. Homographic URLs that house malicious software can still be distributed, without being displayed as Punycode, through e-mail, social networking or other Web sites without being detected until the user actually clicks the link. While the fake link will show in Punycode when it is clicked, by this point the page has already begun loading into the browser and the malicious software may have already been downloaded onto the computer. Television station KBOI-TV raised these concerns when an unknown source (registering under the name "Completely Anonymous") registered a domain name homographic to its own to spread an April Fool's Day joke regarding the Governor of Idaho issuing a supposed ban on the sale of music by Justin Bieber.
> 
> ```
> ```

**Comment by zetok** [comment]
Which part of the qTox?

**Comment by sudden6** [comment]
I asume you are talking about friend request here.

I agree that this is possible, but only at the nickname level, because the ToxID can only contain 0-9 and A-F where I don't know a homograph. Also the ToxID isn't really a thing the attacker can choose.

Since the nickname isn't considered "verified" information (two users can have the same nick and be perfectly fine), technically we have no problem. You can also set your own aliases for people with the same nick in qTox. But I think very few users actually know this, so we have a problem again...

An idea could be, to generate some sort of picture to a ToxID, which makes it easily distinguishable from other ToxIDs.

> So, it's possible that a user's IP address can be disclosed.

First, if you absolutely have to have your IP protected, use TOR or any other proxy with a dedicated router, everything else will fail at some point.

Second, I would compare accepting random friend request with opening random emails. If it automatically loads a 1px picture, you also have disclosed your IP.

**Comment by rugk** [comment]
> to generate some sort of picture to a ToxID, which makes it easily distinguishable from other ToxIDs.

What about using [Identicons](http://identicon.net/)?

**Comment by ProMcTagonist** [comment]
https://github.com/tux3/qTox/issues/711
