### ISSUE TITLE
Option to select network interface

### ISSUE THREAD

**Issue by Hasshu** [qTox/qTox#2965]
Proposal: add an option to select network interface (to prevent possible leaks).

Some background: I have a set of firewall rules to block qTox in case my VPN connection fails. But recently I noticed that qTox occasionally tries to reach something through the main network interface even when I'm connected to a VPN. Needless to say, that looks rather unsettling.

qTox: v1.2.4 (IPv6 disabled; UDP enabled)
Commit hash: d550aa08a2aa7cb644692031684f43209440a1d5
toxcore: v0.0.0
Qt: v5.5.1
OS: Windows 7 Ultimate, SP1 (64-bit)

**Comment by ProMcTagonist** [comment]
Priority critical if it's not a duplicate (I don't think this is quite the same as proxies).

How can you tell it's trying to reach things through the main interface?

**Comment by Hasshu** [comment]
I noticed that in the firewall logs (Comodo Firewall).

Every now and then qTox would try to connect to some address in the private network range of my ISP (10.0.0.0/8); the address doesn't belong to the gateway. Port 33445, UDP - the usual. Incidentally, I use no routers or modems.

**Comment by sudden6** [comment]
This could be the local peer detection of toxcore? Since 10.0.0.0/8 would normally be a private IP.

**Comment by ProMcTagonist** [comment]
If someone is on a VPN, they may not want anyone in their local network to realize they're using Tox.

**Comment by zetok** [comment]
@Hasshu 
Not doable in qTox, since toxcore takes care of that, thus closing.

# 

On a side note..

> Some background: I have a set of firewall rules to block qTox in case my VPN connection fails.
> 
> OS: Windows 7 Ultimate, SP1 (64-bit)

You may not be aware, but if you're using windows there's no way to block something from using internet.

If you want to use system that is capable of doing that, I'd suggest to use Linux.

# 

@ProMcTagonist 

> If someone is on a VPN, they may not want anyone in their local network to realize they're using Tox.

If they really wouldn't want that, they'd just setup vpn/firewall in a way that would prevent it. This is not a qTox issue. Neither a toxcore one, if we're at that.

**Comment by Hasshu** [comment]
@zetok

> You may not be aware, but if you're using windows there's no way to block something from using internet.

If it weren't for vidya, I would have got rid of Windows a long time ago.

> If they really wouldn't want that, they'd just setup vpn/firewall in a way that would prevent it. This is not a qTox issue. Neither a toxcore one, if we're at that.

And that's exactly what I did. That said, Tox claims to be an _easy-to-use software_, which would mean it targets the non-techy crowd as well. And, as you may know, most of the commoners have no idea what a firewall is - let alone how to set it up.

What I see here is a feature that not only cannot be disabled, but also can (and, for many people, will) result in a leak. And I shouldn't need third-party software to plug a security hole created by Tox.

Now onto the toxcore repo...

**Comment by zetok** [comment]
@Hasshu 

> And that's exactly what I did. That said, Tox claims to be an easy-to-use software, which would mean it targets the non-techy crowd as well. And, as you may know, most of the commoners have no idea what a firewall is - let alone how to set it up.

And neither they know what is a vpn. Tox is supposed to provide privacy and it does that.

> What I see here is a feature that not only cannot be disabled, but also can (and, for many people, will) result in a leak. And I shouldn't need third-party software to plug a security hole created by Tox.

Err, considering that most people don't know what vpn is, they wouldn't have anything to "leak" in the first place.

In other words, you're creating a problem, and then expecting software that is not being made for this precise workload to work exactly in a way you would want it to work, even though that "feature" could possibly hinder experience/usability for lots of other people.

**Comment by LuccoJ** [comment]
@zetok my bet is that most users who care about privacy in any more than an abstract way (i.e. without really understanding what it entails, and why/how Tox provides any of it, for instance) have definitely heard about VPNs.

My belief is also that if a piece of software should be reasonably expected to only communicate through a given network interface in a given situation, failing to do so is a bug.

**Comment by zetok** [comment]
@LuccoJ 

> My belief is also that if a piece of software should be reasonably expected to only communicate through a given network interface in a given situation, failing to do so is a bug.

Yes, I agree with that. With that being said, Tox is not expected to do that at all. What is expected, is Tox connecting to the network in whatever way that it is possible - this includes trying to use every network interface possible.

**Comment by ProMcTagonist** [comment]
> Tox is not expected to do that at all. What is expected, is Tox connecting to the network in whatever way that it is possible - this includes trying to use every network interface possible.

what

**Comment by Hasshu** [comment]
@LuccoJ

> my bet is that most users who care about privacy in any more than an abstract way (i.e. without really understanding what it entails, and why/how Tox provides any of it, for instance) have definitely heard about VPNs.

Exactly.

Likewise, many people can (and do) use computers, even though few of them know how computers actually work.

@zetok

> In other words, you're creating a problem, and then expecting software that is not being made for this precise workload to work exactly in a way you would want it to work

I'm merely expecting Tox not to leak.

> even though that "feature" could possibly hinder experience/usability for lots of other people.

Frankly, I'm not sure how having an _option_ could possibly hinder experience and/or usability for lots of other people.

> What is expected, is Tox connecting to the network in whatever way that it is possible - this includes trying to use every network interface possible.

Might as well just use Skype...

Jokes aside, why so belligerent? It's not like I came here to pick at Tox - quite the opposite. I _encountered_ a problem, so I decided to let the others know, and propose a possible solution.

**Comment by zetok** [comment]
> Jokes aside, why so belligerent? It's not like I came here to pick at Tox - quite the opposite. I _encountered_ a problem, so I decided to let the others know, and propose a possible solution.

I know ;)
Thing is, if there is something about idea that strikes me as "problematic", I want to get feedback on that, and find out whether potential benefits from it outgrow downsides.

In this case

> Frankly, I'm not sure how having an _option_ could possibly hinder experience and/or usability for lots of other people.

An option would make whole Tox design, from the lowest level to top more complex – and that's a bad thing. For variety of reasons, which lead to UX/usability. Note that making base more complex ~leads to complications at higher level.

As it is now, I'm still not convinced that little of benefit can justify additional complexity.

With that being said, given that there's data on the subject available (this discussion) other people might read upon it, and see for themselves whether they agree with conclusions I've came to, or if they see it in different light :)

**Comment by Hasshu** [comment]
@zetok Okay, I see your point.

I'm a proponent of "less is more" myself, so I hope there is a way to do something about this issue without bloating the software.

**Comment by nurupo** [comment]
@zetok toxcore provides an option to enable/disable LAN discovery, which is what this privage ip range scanning is. Can't qTox add an option in its settings to be able to disable it?

**Comment by nurupo** [comment]
Ok, apparently I can't find such an option in the API, was pretty sure there was one since I have it in the bootstrap daemon. Will ask iru to provide it then.

**Comment by Hasshu** [comment]
@nurupo

> toxcore provides an option to enable/disable LAN discovery, which is what this privage ip range scanning is. Can't qTox add an option in its settings to be able to disable it?

Sounds like a fair compromise. I second that.

**Comment by nurupo** [comment]
@Hasshu 

> Ok, apparently I can't find such an option in the API, was pretty sure there was one since I have it in the bootstrap daemon. Will ask iru to provide it then.

**Comment by Hasshu** [comment]
@nurupo Yes, I know how to read - just expressed my opinion on the matter.

Incidentally, is it normal for them to take so long to respond?

**Comment by dolohow** [comment]
Since it was implemented in c-toxcore can we add a switch to qTox in order to disable local peer detection/lan discovery feature?

**Comment by zetok** [comment]
>Since it was implemented in c-toxcore can we add a switch to qTox in order to disable local peer detection/lan discovery feature?

Sure. Someone would have to do this though.

**Comment by Hasshu** [comment]
@dolohow See #4074.
