### ISSUE TITLE
apt-get update... W: Failed to fetch https://pkg.tox.chat/debian/dists/nightly/InRelease  Unable to find expected entry 'rafaela/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

### ISSUE THREAD

**Issue by TheNotary** [qTox/qTox#2968]
I'm just starting out, following along with the consumption docs at [tox.chat](https://tox.chat/download.html#gnulinux).  I'm on Linux Mint, that close derivative to Ubuntu.  I'm hitting the below error.  

```
$ sudo apt-get update
...
W: Failed to fetch https://pkg.tox.chat/debian/dists/nightly/InRelease  Unable to find expected entry 'rafaela/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)
```

(/etc/apt/sources.list.d/tox.list)

```
deb https://pkg.tox.chat/debian nightly rafaela
```

Thanks all for working on this important tool!

**Comment by optimumtact** [comment]
Qtox is packaged for the following distribution releases, jessie, sid, stretch, vivid and wily, if your distribution is not one of those, you should use the "release" codename which contains a statically compiled binary that will work on many distributions
your sources.list.d/tox.list will look like

```
deb https://pkg.tox.chat/debian nightly release
```

If after that you still have issues, you will need to manually compile the software.

**Comment by zetok** [comment]
Well, since it looks like user error, closing.

If that's not the case, please comment for reopen.

**Comment by optimumtact** [comment]
Apologies by the way, our website wording is incredibly bad and needs to be updated.
