### ISSUE TITLE
problem with compiling qTox

### ISSUE THREAD

**Issue by dougy1971** [qTox/qTox#2969]
Can not compile qTox in Debien (jessie)...
Keep getting this....

rc/widget/form/addfriendform.cpp
src/widget/form/addfriendform.cpp:28:21: fatal error: /usr/local/include/tox/tox.h: Permission denied
 #include <tox/tox.h>
                     ^
compilation terminated.
Makefile:2334: recipe for target 'addfriendform.o' failed
make: **\* [addfriendform.o] Error 1

Can any one help please....

**Comment by zetok** [comment]
That's a problem with your system - i.e. wrong permissions, which result in qTox being unable to access files it needs to compile.

You should fix your system.
