### ISSUE TITLE
Compiling sqlcipher(needed for qtox) in fedora

### ISSUE THREAD

**Issue by hethkar** [qTox/qTox#2970]
Here: 
There were instructions for fedora as : Note that sqlcipher is not included in Fedora(!).
This means that you have to compile sqlcipher yourself, otherwise compiling qTox will fail.
https://github.com/tux3/qTox/blob/master/INSTALL.md#sqlcipher

But at sqlcipher https://github.com/sqlcipher/sqlcipher the compiling instructions say : 

> Building SQLCipher is almost the same as compiling a regular version of SQLite with two small exceptions:  
> 1. You must define SQLITE_HAS_CODEC and SQLITE_TEMP_STORE=2 when building sqlcipher.
> 2.     You need to link against a OpenSSL's libcrypto

These instructions are not included at https://github.com/tux3/qTox/blob/master/INSTALL.md#sqlcipher So my question is which one to follow and why ? And which method is needed for compiling qtox in fedora ?

**Comment by ghost** [comment]
@linux-modder I guess this one is for you (b998dba3738b8994bb43c8fa43eee0165b91efaa)

**Comment by linux-modder** [comment]
@suknight,  I need to add that to the INSTALL.md,  but use the make flags shown on sqlcipher for compiling sqlcipher, without it the not-so0new anymore  profile securities will fail.

The pertinent parts are whether you statically link or  dynamically  link.

Static: 
cd sqlcipher
./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" \
    LDFLAGS="/opt/local/lib/libcrypto.a"
make
sudo make install 

OR 

dynamic:
cd sqlcipher
./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" \
    LDFLAGS="-lcrypto"
make
sudo make install

**Comment by hethkar** [comment]
@linux-modder got it thank you.

**Comment by zetok** [comment]
`INSTALL.md` has been corrected, thus closing.
