### ISSUE TITLE
After waking PC up - only user left in group chat.

### ISSUE THREAD

**Issue by idanoo** [qTox/qTox#2972]
Had a look through issues and couldn't find it anywhere. Will try include screencaps / more testing later.

qTox: 1.2.4
Commit hash: d550aa08a2aa7cb644692031684f43209440a1d5 
toxcore: 0.0.0 (??)
Qt: 5.5.1
OS version: Win 10 Home

I put my PC to sleep, woke it up after a few hours and it was just me in the group chat. Had to leave and rejoin for it to work fine.

**Comment by sudden6** [comment]
This is because groupchats are not permanent (yet). Whenever you loose the connection (by suspending your pc for example), you have to rejoin.

This is a known limitation of toxcore at this time, so it can probably be closed.

**Comment by idanoo** [comment]
Ah okay, Thanks for that.

I was thinking have some small notification at the end of the chat log saying:
 -Disconnected from group chat-

Just as a confirmation that all of your friends haven't ditched you, and you sit there talking to yourself for 5 minutes like I did. :)

**Comment by sudden6** [comment]
> I was thinking have some small notification at the end of the chat log saying:
> -Disconnected from group chat-

I think this would actually be a great idea and shouldn't be too hard to implement.

**Comment by idanoo** [comment]
I'm just setting up my build env then I'll have a go at it. Thank!
