### ISSUE TITLE
Notification sounds do not work.

### ISSUE THREAD

**Issue by dongmaster** [qTox/qTox#2973]
qTox: v1.2-353-gef5b9b8
Commit hash: ef5b9b8c1e1a934d200743fbdc4ff0ed02cde023
toxcore: 0.0.0
Qt: 5.5.1
OS version: Windows 7 Enterprise SP1

I upgraded qTox recently. Everything worked just fine but after I recieved a few messages, I stopped getting notification sounds whenever anyone sent me a message or file.
Before you ask, yes, notification sounds are enabled in the settings. I have also tried turning off notification sounds and turning them on but that did nothing.

Steps to reproduce:
1. Update to (latest?) version v1.2-353-gef5b9b8 of qTox.
2. Recieve a few messages (10-20 or so maybe. Have someone spam you a bit with messages).
3. Listen for notification sounds.
4. If you can't hear them, congratulations, you have replicated my problem.

Also, the blinking notifiction on Windows (where the qTox icon blinks in the bottom bar where all the program icons are) when you get new messages only blink for a few seconds, not indefinitely. It would be nice to have an option to make the qTox icon blink indefinitely.

**Comment by zetok** [comment]
> Also, the blinking notifiction on Windows (where the qTox icon blinks in the bottom bar where all the program icons are) when you get new messages only blink for a few seconds, not indefinitely. It would be nice to have an option to make the qTox icon blink indefinitely.

Actually, that's another bug - not sure if it's not something windows-specific, given that on Linux it just keeps blinking until one opens qTox.

**Comment by SergeyDjam** [comment]
Yes, my qTox on Linux sound notification don't work too

**Comment by dongmaster** [comment]
Yeah I know it's another bug. Should I just create another issue for it? (The icon not blinking long enough bug)

**Comment by zetok** [comment]
Well, it was blinking for me for >3 minutes after receiving message.

Can you check whether you still have issue with ~following settings:
![settings](https://cloud.githubusercontent.com/assets/3148759/13312560/91c4a70a-db8f-11e5-9a78-513faf67cc04.png)

And if not, how much your settings have to be ~altered in order for sound notifications & blinking to work?

# 

Edit: I _think_ that those (blinking & sound) are related, so there's no need (yet) to open a separate issue.

**Comment by dongmaster** [comment]
I used the same settings as you and could not hear a notification sound when someone sent me a message. The blinking of the qTox icon persisted for about 10-12 seconds. Here's a video of the blinking in action: https://my.mixtape.moe/jgbnbj.mp4 The blinking just stops after a while.

**Comment by sudden6** [comment]
seems like stopping the flashing after some time is a "feature" of qt on windows.

see https://github.com/tux3/qTox/blob/master/src/widget/widget.cpp#L1234

https://doc.qt.io/qt-5/qapplication.html#alert

> On Windows, this causes the window's taskbar entry to flash for a time. If msec is zero, the flashing will stop and the taskbar entry will turn a different color (currently orange).

tough it should stay orange afterwards...

**Comment by cepauskas** [comment]
same issue on Ubuntu 15.10

**Comment by sudden6** [comment]
@cepauskas which one? not blinking long enough or no notification sounds?

**Comment by Hasshu** [comment]
@dongmaster Just in case: do you have an actual playback device selected under the Audio/Video tab in the settings?

**Comment by dongmaster** [comment]
@Hasshu Yes.

**Comment by sudden6** [comment]
@dongmaster @SergeyDjam @cepauskas  does this still happen with the latest release? I couldn't reproduce this at https://github.com/tux3/qTox/commit/252c9c8fae35f0258381537fee444b5eb02a9d7c with Linux.

**Comment by cepauskas** [comment]
I can hear sounds now - thanks.

**Comment by dongmaster** [comment]
@sudden6 I have notification sounds now. The commit hash is b69042ec407c30b27ce3e56bb6daf14300facc8e 
Thanks for fixing it.
