### ISSUE TITLE
Stores non-config data in ~/.config/tox: screenshots, log

### ISSUE THREAD

**Issue by roman-yepishev** [qTox/qTox#2976]
qTox: v1.2-353-gef5b9b8
Commit hash: ef5b9b8c1e1a934d200743fbdc4ff0ed02cde023
toxcore: 72b1a17cc28c9a5a653823336bf0a495f6f271b1
Qt: 5.5.1
OS version: Fedora 23 x86_64

As per https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html,

> There is a single base directory relative to which user-specific configuration files should be written. This directory is defined by the environment variable $XDG_CONFIG_HOME.
> ...
> There is a single base directory relative to which user-specific non-essential (cached) data should be written. This directory is defined by the environment variable $XDG_CACHE_HOME. 

As of today qTox creates the following files in ~/.config/tox:

```
qtox.ini
qtox.log
screenshots/qTox_Screenshot*.png
```

The log and screenshots are not configuration data, so they should be moved to `XDG_CACHE_DIR` or `QStandardPaths::CacheLocation`.

**Comment by sudden6** [comment]
> user-specific non-essential (cached) data

Do we consider the screenshots non-essential? I understand "cached data" as data which can be deleted every reboot, without causing problems. What if a screenshot isn't yet send (faux offline messaging) and the cache is wiped?

**Comment by roman-yepishev** [comment]
For data that is not config, but should be persistent, `XDG_DATA_DIRS` - `~/.local/share` is provided - this is what `QStandardPaths::AppLocalDataLocation` is pointing to.
