### ISSUE TITLE
Sending and receiving calls no longer works at all

### ISSUE THREAD

**Issue by j0euk** [qTox/qTox#2984]
When clicking on the green phone button to send a call, the button turns yellow as expected.
However, when the other end answers, the call button immediately turns grey as if the call has ended.

When clicking on the "answer" button to receive a call, the same things happens: both buttons immediately just turn grey for a bit, before turning green.

---

The following lines output by the terminal may be of relevance:

**When sending a call:**

```
[18:21:54.960] src/core/coreav.cpp:545 : Warning: Call with friend 0 died of unnatural causes!
```

**When receiving a call:**

```
[18:22:19.110] src/core/coreav.cpp:152 : Warning: Failed to answer call with error 2
```

---

Entire terminal log can be found [here](http://pastebin.com/TWwcAViH)

**Comment by zetok** [comment]
Update your qTox.

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.
