### ISSUE TITLE
Remove hardcoded include paths in qtox.pro

### ISSUE THREAD

**Issue by OrangeShark** [qTox/qTox#2988]
I am currently working on packaging qTox for [GNU Guix](http://www.gnu.org/software/guix/) and one thing I noticed was this project hard codes the path for several libraries in qtox.pro. qmake has a [configuration feature](http://doc.qt.io/qt-5/qmake-project-files.html#configuration-features) to use [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/) to find installed libraries and provides all the flags necessary. I already fixed it locally to allow me to build using guix and if there is no objections I am willing to fix the rest of the project file and test building it on different computers to make sure it works and then contribute it to qTox.

**Comment by antis81** [comment]
Sounds great, really! Would you mind to setup a PR onto current master Branch fixing the pro file?
