### ISSUE TITLE
windows phone client

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2991]
Hi,

are there any plans to implement a native windows phone client?

**Comment by ProMcTagonist** [comment]
Hi! This repo is only for the desktop Tox client qTox, not for Tox in general.

I think you could get a better sample of answers by asking in #tox-dev on Freenode.

To my knowledge, there's an in-development Universal Windows Platform client [here](https://github.com/uruk/OneTox). I don't know much about Windows Phone, is that the same thing?

**Comment by ghost** [comment]
Sorry for my mistake. But thanks for your answer, that's what i wanted to know. According to the README there are plans to support Windows Phone, sometime :-).

Thank you

**Comment by ProMcTagonist** [comment]
No problem, thank you for your interest. Happy Toxing :)
