### ISSUE TITLE
Markdown settings are not translateable

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#3002]
This section is not translateable:
- **Markdown:**
  - Plaintext
  - Show Formatting Characters
  - Don't Show Formatting Characters

**Comment by anoadragon453** [comment]
Anyone know how we mark strings as translatable?

**Comment by zetok** [comment]
`tr("string")`, but it won't work inside QStringList

**Comment by anoadragon453** [comment]
Can we translate it outside of the list and then use that as input for it?

**Comment by zetok** [comment]
If it will work, why not.

**Comment by anoadragon453** [comment]
How exactly do I check if a string is translating properly? Is there a file or dictionary with each translation?

Edit: It's probably in the translations folder, huh?

**Comment by zetok** [comment]
https://github.com/tux3/qTox/wiki/Translating#remove-obsolete-strings ← basically just this for some language, add translation for e.g. `Plaintext`, compile & check whether switching language brings translation during runtime.

**Comment by Diadlo** [comment]
Fixed in #3293
