### ISSUE TITLE
Load history dynamically when scrolling up

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#3003]
Hello,

it would be very convenient if the history is loading dynamically when scrolling up.

Old and unmerged PR's, but perhaps helpful:
https://github.com/TheSpiritXIII/qTox/commit/5b9d9cc7fbaf104f73bea48f59e9c93ea4ec54d8
https://github.com/TheSpiritXIII/qTox/commit/e9f702edd7cc0643c25e4100426e71946f3426d2

**Comment by zetok** [comment]
Duplicate of #1198, thus closing.
