### ISSUE TITLE
qtox-unity is missing on nightly wily

### ISSUE THREAD

**Issue by dolohow** [qTox/qTox#3009]
I am using the following entry for apt for fetching qtox:

```
deb http://pkg.tox.chat/debian nightly wily
```

However, the package qtox-unity is missing there.

Related to #2153

**Comment by zetok** [comment]
cc @nurupo

**Comment by nurupo** [comment]
cc @tux3

**Comment by tux3** [comment]
Since this is a package specifically for Ubuntu Wily, there is no unity/non-unity split, the qtox-unity package will just be called qtox.
But you're right that it's not currently done, the package build script needs to be updated.

**Comment by dolohow** [comment]
You can have KDE on Ubuntu as well, so not sure if it is a good idea to provide only one package qtox instead of qtox and qtox-unity.

**Comment by zetok** [comment]
`qtox` in community builds (https://github.com/tux3/qTox/blob/e797bf958279ea9eaa858bd377532b22de79bef7/INSTALL.md#community-builds) works on Ubuntu 16.04, thus closing.

**Comment by dolohow** [comment]
> qtox in community builds (https://github.com/tux3/qTox/blob/e797bf958279ea9eaa858bd377532b22de79bef7/INSTALL.md#community-builds) works on Ubuntu 16.04, thus closing.

OK, but this bug report is not about working is about qtox-unity package.

**Comment by zetok** [comment]
> OK, but this bug report is not about working is about qtox-unity package.

Which no one maintains – what is maintained, is the community repo.

**Comment by dolohow** [comment]
I'll check if icon in systray works as expected on Unity and I will report back.
