### ISSUE TITLE
Formatting lost when message copied to clipboard

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3015]
For instance when someone sends me some code, and it is important for it to stay in the multi-line and indented format it is in (especially with languages such as Python), I find that the contest copied to the clipboard of a message is squished onto one line and all formatting is lost.

I am running Ubuntu GNOME 15.10 with GNOME 3.18 and have qTox version `1.3.0-38-ga48c422-1` installed.

**Comment by zetok** [comment]
Duplicate of #902, thus closing.
