### ISSUE TITLE
Provide automatic builds for OS X

### ISSUE THREAD

**Issue by ddobrev** [qTox/qTox#3019]
Please provide automatic builds for OS X as you have for Windows and Linux. At the moment we rely on @RowenStipe for those but he needs to manually do it at each release and he doesn't always have the time - as evident by my request (https://github.com/RowenStipe/qTox-OSX/issues/7) from a work week ago which doesn't even have a reply. https://travis-ci.org/ offers free OS X builds for open source projects and while it doesn't upload the complete binaries by default, it can be configured to do so using "artefacts".

**Comment by zetok** [comment]
> https://travis-ci.org/ offers free OS X builds for open source projects and while it doesn't upload the complete binaries by default, it can be configured to do so using "artefacts".

So, AFAIK it would require:
- travis build set up in a way that would produce standalone build - that seems to be easy part, feel free to make PR that would do it
- automatic uploading it $somewhere - with this part, it could be either uploaded automatically to releases on GH, which would require @tux3 to add deployment GH token to travis, and make travis automate creating new tags & uploading releases under them. This would be tricky, and produce a lot of useless noise & tags on repo, given that it would be deployed on every push to master. Perhaps it can be done differently, in which case it would be nice to know how.

In a case where build would be uploaded somewhere else than GH, a server would be needed. And again, @tux3 also would be required to set some things up.

**Comment by optimumtact** [comment]
You can also use something like bintray for artefacts - it's free for OSS
https://bintray.com/

**Comment by ddobrev** [comment]
I asked @RowenStipe for a new OS X release a month ago at https://github.com/RowenStipe/qTox-OSX/issues/8. He hasn't even replied, including to the superseding issue of https://github.com/RowenStipe/qTox-OSX/issues/9. Apparently the fellow is too busy and can unfortunately not be relied upon for regular OS X releases. So I would like to ask for a little more consideration about this issue.

**Comment by RowenStipe** [comment]
@ddobrev I know I utterly failed as a package maintainer, yesterday was the first time in a month or so I've been able to sit down and go over everything that I've missed. (As much as I could) As well as planning out how to get Travis to build the OS X releases so I don't have to keep doing it as manually as I have been doing.

**Comment by ddobrev** [comment]
@RowenStipe thank you for your understanding, especially since I might have sounded a little rude. I am looking forward to the automated solution which will definitely be best both to you and to users (such as myself).

**Comment by ddobrev** [comment]
@RowenStipe would you mind making one (hopefully) last manual release so that all OS X users have the latest version available while the automatic builds for OS X are worked on?

**Comment by ddobrev** [comment]
Fellows, you have my gratitude for the automatic builds for OS X. Now that they have been merged, please close this issue.
