### ISSUE TITLE
Ridiculously big CPU and RAM usage when video calling mode is being used

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3021]
Brief description:

Operating System: Parabola GNU/Linux-libre
qTox version: [1.2.4](https://www.parabola.nu/packages/community/x86_64/qtox/)
Hardware:
Motherboard model: GA-78LMT-USB3 6.0
CPU model: AMD FX(tm)-4130 Quad-Core Processor
CPU speed: 3800 MHz
RAM memory type: DDR3
RAM speed: 1333 MHz
RAM size: 4Gb
Video model: Geforce 9800 GT
Video RAM memory type: GDDR3
Video RAM size: 512Mb
…

Reproducible: Always

**Steps to reproduce:**  
1.  Open qTox
2.  Start video call to any contact
3.  Use video calling mode from a long time (more of 10 minutes)
…

**Observed Behavior:**  
After some minutes of video calling, qTox will use 100% of CPU and RAM usage.

**Expected Behavior:**  
qTox shouldn't use big CPU and RAM usage (4 Gb of RAM) since it's a Tox client written in C++/Qt

**Additional info:**  
Note: Parabola's qTox package comes from [Arch](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/qtox)

---

**Comment by zetok** [comment]
Update your qTox, you have old version.

**Comment by sudden6** [comment]
Please also post your webcam settings, you are probably trying to use a very high resolution and framrate.

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.
