### ISSUE TITLE
Messages sent to other users while they are offline do not get through if message history is disabled on the sending side

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3022]
I have recently observed the following behaviour:

**When history is on:**

When the history is on all works fine with offline messages, I am able to send and receive them and all works as expected.

**When history is off:**

When history is turned off however things do not work quite as they should, if I turn off the history I find that if I send a message to someone while they are offline, instead of getting the spinning circle I just get the time that I sent them even though the user is offline and couldn't possibly have received them. When the user comes online again, they also do not receive my offline messages.

Though they are able to send me messages when my history is off as long as theirs is on (I've had others test this issue too and they are able to reproduce it).

Turning history on fixes this issue (every time I change this setting I also restart qTox, I don't know if this is absolutely necessary but I haven't tested it this far).

---

This issue is present in the latest version of `qtox` and `qtox-unity` (though note that these are the only clients that I and my contacts have tested this issue in). And it also didn't used to be present.

I am running Ubuntu GNOME 15.10 with GNOME 3.18, and the person with whom I have tested it is running Ubuntu 15.10.

**Comment by SeventhSonOfASeventhSon** [comment]
We have tested it though and when I send a message while they are offline, when they come online again and it tells me that they have received it, they do actually receive it. We will have to do further testing if it is to do with the qTox normal version talking to the Unity version because it is strange that it doesn't do it both ways, or at least, hasn't yet.

**Comment by sudden6** [comment]
Can you retest this with latest master? 76d8e19320d2f15aeb019f72ecaaac2d6a23feab should at least reduce this behaviour.

**Comment by SeventhSonOfASeventhSon** [comment]
@sudden6, Ok, but we should just note that it may not be my side that has the problem because I'm pretty sure it's only been not working with one contact... Or at least, it seems to be working fine with one of my other contacts (I have only tested this though with two contacts, and I will have to confirm about it working with my other contact).

**Comment by SeventhSonOfASeventhSon** [comment]
@sudden6, Also, that commit is to do with reducing the chances of a message being sent and displayed twice, what has it got to do with this issue? I don't see how it could help this...

**Comment by sudden6** [comment]
It generally increases the timeout to resend messages. This may also improve/change things for this bug.

**Comment by zetok** [comment]
@SeventhSonOfASeventhSon 

> @sudden6, Ok, but we should just note that it may not be my side that has the problem because I'm pretty sure it's only been not working with one contact... Or at least, it seems to be working fine with one of my other contacts (I have only tested this though with two contacts, and I will have to confirm about it working with my other contact).

That sounds like a problem with the client of that contact - are they using qTox?

**Comment by SeventhSonOfASeventhSon** [comment]
@zetok, Well, they are using `qtox-unity`.

**Comment by SeventhSonOfASeventhSon** [comment]
We should also note that though that offline messaging is working for all of their other contacts so if they send a message to one of their contacts while they are offline it does get successfully delivered when both people become online, unless they're sending it to me...

**Comment by SeventhSonOfASeventhSon** [comment]
@zetok, Ok, got an update on this issue, my contact tried it with another one of his contacts (who also uses `qtox-unity`) and found that the issue is also present there going in the same direction. My contact is unable to get offline messages to them, though it works the other way round.

**Comment by SeventhSonOfASeventhSon** [comment]
I have also updated the initial description with this information to make it less confusing.

**Comment by SeventhSonOfASeventhSon** [comment]
We are going to do some further testing. I will let you know of the results when I have them.

**Comment by SeventhSonOfASeventhSon** [comment]
@zetok, I have updated the initial description with more information. It also seems that I misunderstood something and got something slightly inaccurate which might be rather important to this so please read the whole post again.

**Comment by SeventhSonOfASeventhSon** [comment]
@zetok, Ok, sorry, it seems that I was right with the circles originally, but I have updated my post with more information...

**Comment by SeventhSonOfASeventhSon** [comment]
@zetok, Sorry for all the confusion, turns out I was misunderstand a lot of things about the circles... I have now been able to reproduce the issue myself and have figured out what it is caused by. I will update the initial description, clean up these comments, and then hopefully it will all become clear.

**Comment by ghost** [comment]
@zetok, I have figured out what the issue is and updated my initial description (as well as removing my comments which just confused and clogged things up).

**Comment by zetok** [comment]
I see. Just so you know, it's better to not remove messages, and if you want, just edit them to

```
<strike>
comment
</strike>
```

Now, I'm not quite sure whether trying to keep some user data should actually happen when user explicitly disables option to keep that..

But yeah, qTox shouldn't inform that message was delivered when it simply failed to send it.

It probably should have a red `X` there if delivery was failed.

**Comment by ghost** [comment]
@zetok, I think that a good solution to this would be to provide another option in the settings which means that even if users disable history, they can check an option which means that offline messages will still be kept and get through until that is you are online, they get through, and then you quit qTox.

But it's not just like I send a message to someone while they are offline when history is disabled, I then restart qTox and the message with the history is gone, it is like this whether I do that or I just send it when they are offline, in the next few minutes they come online, and then the message is not delivered, I would not expect it to fail because history is disabled in this way at least.

If you do keep it mostly the way it is though you should at least make it very clear that the disabling history also disables offline messaging, but I think that you should add some sort of option or exception for offline messaging.

**Comment by ghost** [comment]
@zetok, I really think that history and offline messaging are different things in this respect though... The offline messages should at least be kept until they have properly been sent off... And if you say that all messages including offline ones will not be kept after a restart or whatever, then that does not explain them not getting through when I send them, the user comes online in a few minutes, and I haven't done this restart which would delete them...

**Comment by zetok** [comment]
> But it's not just like I send a message to someone while they are offline when history is disabled, I then restart qTox and the message with the history is gone, it is like this whether I do that or I just send it when they are offline, in the next few minutes they come online, and then the message is not delivered, I would not expect it to fail because history is disabled in this way at least.

Yeah, that's a bug too.

**Comment by ghost** [comment]
@zetok, Just to mention it though, the tooltip for the `Faux offline messaging` does say `Messages you are trying to send to your friends when they are not online will be sent to them when they appear online to you.`, so I think what should be done is that when you disable history it should ask you if you also want to disable the `Faux offline messaging`, otherwise offline messaging should be separate from history and should work like so: You send a message to someone while they are offline, it gets put in a queue and shows after a restart, when the messages are delivered successfully and you do a restart they are no longer shown to you.

Perhaps there should be some settings allowing one to customize this a little more, but basically I think that this is how it should work, because then the tooltip for the offline messaging really does not make sense, and the history and the offline messaging really are two separate things, one should really not break the other without notice.
So I really think that there should be some way of configuring it so that history is not kept, but offline messaging still works.
And there's no problem with giving users more choice if you provide all the options.

**Comment by FabrizioMarana** [comment]
Affected too!

**Comment by ghost** [comment]
Chat history is kept until qTox is closed when history is disabled, so at the very least it should keep waiting to send a message until qTox is closed, so that needs fixing.

As for what to do with pending messages when qTox is closed and history disabled, perhaps put an option for keeping them pending in the privacy tab under "Keep chat history"?

**Comment by ghost** [comment]
Looks like the offline messaging while not saving chat history bug has been fixed in 1.13.0!  Messages now enter into pending state properly when a user isn't online!

Messages pending to be sent still appear to be wiped out upon restarting qTox, but you can argue that is an intended behavior.  An option to allow for that might be a nice new feature? 🐺

**Comment by sudden6** [comment]
I think permanently storing the pending messages is against the idea of turning of the chat history.

**Comment by ghost** [comment]
That's why I suggested an option for that in my above post, otherwise not saving should be the default when no-history mode.

**Comment by tox-user** [comment]
The original issue described here is not relevant anymore. @Swiftpaw maybe you could create a new issue with a request for this feature and this one should be closed? I think such feature might have its use if it's optional. It's like destroying a message after it has been sent, but locally.

**Comment by ghost** [comment]
Yes fully agreed, this bug should be closed as fixed!  A feature request for not deleting pending messages until they are sent when in no-history mode might be a good feature!

I have seen a weird issue where no-history-mode users are re-sending the same messages after qtox app recycles were done (when starting qtox a day later for example, and seeing other users online), but that's a different bug.  It's also very rare and I think happens to users with chat history, too, it's just more concerning for those users without it since those messages should have never been saved.

**Comment by sudden6** [comment]
> Yes fully agreed, this bug should be closed as fixed!

Closing
