### ISSUE TITLE
Error when trying to install on Debian

### ISSUE THREAD

**Issue by rugk** [qTox/qTox#3030]
Brief description: Wrong entry in sources.list; could not find "debian/binary-amd64/Packages" in release file.

Operating System: Linux Mint Debian Edition 2.0
qTox version: /

Reproducible: Always

**Steps to reproduce:**
1. Follow the instructions at https://tox.chat/download.html#gnulinux for Debian/Ubuntu

**Observed Behavior:**
Literally:

> W: Fehlschlag beim Holen von https://pkg.tox.chat/debian/dists/nightly/InRelease  Erwarteter Eintrag »debian/binary-amd64/Packages« konnte in Release-Datei nicht gefunden werden (falscher Eintrag in sources.list oder missgebildete Datei).

(German version)

**Expected Behavior:**
Install qTox.

**Additional info:**
May be related to https://github.com/tux3/qTox/issues/2968

**Comment by zetok** [comment]
> Follow the instructions at https://tox.chat/download.html#gnulinux for Debian/Ubuntu

No.

If you have problem(s) with those instructions, you should report that to the people who actually maintain them.

**Comment by rugk** [comment]
And who are that?
I mean as this are instructions for your piece of software you should also make sure they are correct...

**Comment by zetok** [comment]
> And who are that?

No idea, and I don't really care.

> I mean as this are instructions for your piece of software you should also make sure they are correct...

Instructions are in [INSTALL.md](https://github.com/tux3/qTox/blob/d1446ae56f99357c188e83f09749a90ed8f3da1a/INSTALL.md#generic), and AFAIK they are correct. If not, please open an issue about it.

**Comment by nurupo** [comment]
> And who are that?

The qTox author, @tux3, maintains the qTox packages. Also, if the instructions on the website aren't correct, [everyone is willing to get them fixed](https://github.com/Tox/tox.chat/issues/84).

@rugk could you paste the sources.list file in here (the single line with `pkg.tox.chat` in it would do), I would like to check something.

**Comment by zetok** [comment]
> The qTox author, @tux3, maintains the qTox packages.

From what I see, the problem is about wrong instructions on your website, not about packages.

> Also, if the instructions on the website aren't correct, everyone is willing to get them fixed.

Sure, do that. Not a qTox issue.

**Comment by rugk** [comment]
> @rugk could you paste the sources.list file in here (the single line with pkg.tox.chat in it would do), I would like to check something.

It is the original line as mentioned in the instructions.

**Comment by nurupo** [comment]
Could you still paste it please? The line in instructions has `lsb_release -cs` call which gets replaced with your distro's release name, so the line can't be the same as in the instructions.

Also, as @zetok has mentioned, this is not qTox application issue but the issue on the website, so it might be better to open an issue in https://github.com/Tox/tox.chat/issues/ repository and continue the discussion there, before @zetok gets mad for us continuing discussing it here.

**Comment by nurupo** [comment]
Oh, sorry, just noticed that you have created the issue in the website repo.
