### ISSUE TITLE
Allow 2-step-verification - feature request

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3035]
I think there should be an optional option which allows one to enable 2-step-verification so that when they try to log in a code is sent to their phone or email or whatever they want it to be sent which they then have to enter before it allows them to continue to log in.

**Comment by TheNain38** [comment]
@SeventhSonOfASeventhSon This isn't an account on a distant server, this is a profile, which is a file, when you setup a password, it encrypts the file with this password, so you can't have 2-step-verification...

**Comment by ghost** [comment]
Amen.

Interesting related read: http://sakurity.com/blog/2015/07/18/2fa.html

**Comment by ghost** [comment]
@TheNain38, I understand this but there could be ways of getting round this so that the way of it contacting you to give you the code is not actually encrypted, or is encrypted but is decrypted with your password, but then the code is needed to decrypt the rest in connection with the password or something... I'm sure there is some way of getting round this.

**Comment by TheNain38** [comment]
@SeventhSonOfASeventhSon You can't... If I grab your .tox, then I get home, I just try to bruteforce it and your 2-step-verification is useless...

**Comment by SkyzohKey** [comment]
Related. https://github.com/RicinApp/Ricin/issues/51

**Comment by ghost** [comment]
@TheNain38, I don't know, is there anyway to have it encrypt it all with the code too and have that somehow also encrypted and sent to you? So that each time you close qTox or something it re-encrypts everything using the code as well... I don't know, maybe that wouldn't be possible, but just a thought of something similar...

**Comment by ghost** [comment]
Fractal-recursive-distributed-encryption? That should work.
