### ISSUE TITLE
[Regression] Missing emoticons

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#304]
On latest qTox I'm unable to access emoticons when clicking on emoticon button in chat, nor emoticons are displayed when sending message like `:-)`

I'm unable to set any emoticons bundle in settings.

Was like that earlier, then it was fixed, and now it's broken again, thus it's a regression.

**Comment by krepa098** [comment]
Please provide more information on your setup (OS and desktop environment). Currently smileys have to be stored in any of the following directories:
- "./smileys (relative to the qtox executable)
- "/usr/share/qtox/smileys"
- "/usr/share/emoticons"

on KDE
- "~/.kde4/share/emoticons"
- "~/.kde/share/emoticons"

**Comment by zetok** [comment]
Gentoo; i3wm.

There's no `/usr/share/qtox` and `/usr/share/emoticons` directories.

**Comment by dubslow** [comment]
Aren't the default smileys embedded in the executable?

**Comment by tux3** [comment]
Last time I checked, they weren't. There's a smiley/ folder in the repo but it's not embedded.

**Comment by krepa098** [comment]
@dubslow No, they're not embedded (although it's feasible).

@zetok Seems like your qtox package doesn't include smileys. Copying_./smileys_ to _/usr/share/qtox_ should do the trick. Don't worry about _/usr/share/emoticons_, it's a KDE thing.

**Comment by dubslow** [comment]
I only ever run qtox from the build directory, and I still have emoticons because of that. I would therefore propose embedding the default pack. (Or somehow we need to distribute it in such a way as to install the pack to /usr/share/qtox, but that requires root... what about ~/.local/share? Not to mention that getting Jenkins to cooperate will be nigh on impossible.)

**Comment by zetok** [comment]
@dubslow Why would you propose using `~/.local/share` for stuff that should be under `/usr/share`?

> Or somehow we need to distribute it in such a way as to install the pack to /usr/share/qtox, but that requires root...

What is wrong with requiring root to install stuff?

@krepa098 
I don't see point in manually copying something that should be done by qTox build.

**Comment by dubslow** [comment]
If you are doing a global install, then sure /usr/share is fine. If not, then ~/.local/share is preferred. Note that installing new packs to /usr/share would require root privilages too, and we should minimize the use of root where ever possible.
