### ISSUE TITLE
Whitespace is not preserved in preformatted messages

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#3041]
Brief description:
whitespace is not preserved in preformatted messages

Operating System: Debian Jessie
qTox version: v1.3.0-66-ga770b9b
Hardware: computer

Reproducible: Always

**Steps to reproduce:**  
1.  update qTox to latest
2. send a message with multiple spaces inside ``    

**Observed Behavior:**  
whitespace is not preserved

**Expected Behavior:**  
whitespace is preserved

**Additional info:**  
![nonpreserved whitespace](https://cloud.githubusercontent.com/assets/4358079/13994825/d42d63a2-f0e3-11e5-8ed5-d74ba2f52b74.png)

**Comment by anoadragon453** [comment]
You're referring to the extra space added in front, correct?

**Comment by zetok** [comment]
Nope, other whitespaces

**Comment by zetok** [comment]
Actually, I wonder whether that would be fixed by #2994

**Comment by ProMcTagonist** [comment]
what I sent, with numbers as spaces, was:

```
`1t1e2s3t4`
```

Those spaces were stripped.

**Comment by anoadragon453** [comment]
Not sure about the tab situation, messages are `trimmed()` and markdown assumes surrounding spaces. Together these work quite nicely but I can try and see if that's causing the issues.

**Comment by zetok** [comment]
Since #2994 that fixes this issue was merged, closing.
