### ISSUE TITLE
[Feature Request] Keep emoticon option open until manually deselect

### ISSUE THREAD

**Issue by Bujiraso** [qTox/qTox#3043]
Brief description: I and some of the people I chat with enjoy fooling around with streams of emoticons/emojis in lieu of actual text. To make this fun more easy, it would be nice to have the dialog remain open so I can spam a whole bunch to my buddy instead of having to open the dialog and find the page I was on again.

Operating System: Arch Linux (Linux 4.4.5-1)  
toxcore (pacman package) version: 3747-1 
qTox (pacman package) version: 1.3.0-1
Qt version: 5.5.1
Hardware: HP G61 laptop
AMD Athlon(tm) II Dual-Core M300 × 2 
Gallium 0.4 on AMD RS880 (DRM 2.43.0, LLVM 3.7.1)

Reproducible: Always

**Steps to reproduce:**  
1.  Click smiley face beside the text window to open emoticon dialog
2.  Click any icon

**Observed Behavior:**  
Emoticon dialog closes and emoticon is pasted into the text window 

**Expected (Desired) Behavior:**  
Emoticon dialog remains open, and the selected emoticon is pasted into the text window

**Additional info:**  
This is the default functionality in Skype, and makes it quite fun to play around with the emoticons. Currently, the emoticon dialog can be deselected by clicking outside of it, so there is already an escape from the potential "problem" posed by keeping the dialog open implemented.

**Comment by anoadragon453** [comment]
Ran into this same issue yesterday when I was trying to write mean things to friends in emoji letters.

**Comment by zetok** [comment]
Note: **needed** (from https://github.com/tux3/qTox/pull/3045#issuecomment-201702396)

Emoticon option should disappear if any key is being pressed, without catching they key - i.e. whatever key would be pressed, emoticon selector would close, and the key press would be forwarded to the input field.

**Comment by anoadragon453** [comment]
That would make things easier. I'll implement this weekend.
