### ISSUE TITLE
qTox closing vncviewer window on display

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#3061]
---

**Report from user `dingdong` in IRC:**

---

```
Operating System: Linux 15.04 64-bit Lubuntu
qTox version: nightly
Hardware: Intel Core 2 Duo, 4 GB ram, 200+ GB HDD
```

Reproducible: Always
Used program: TightVNC 1.3.10

**Steps to reproduce:**  
1.  launch vncviewer
2.  launch qTox
3.  qTox closes vncviewer
4.  vncviewer doesn't close qTox in return when re-launched

**Observed Behavior:**  
Observed terminal output when vncviewer window terminates:
CleanupXtErrorHandler called
Error: Event with wrong window

**Expected Behavior:**  
vncviewer to not be affected by launching another process, in this case qTox

**Comment by zetok** [comment]
This sounds like a bug in TightVNC.

I.e. if it was qTox that crashed, it would be a qTox problem..

**Comment by ovalseven8** [comment]
Well, I don't know. But if it works for other programs it has something to do with qTox probably.

**Comment by zetok** [comment]
Yes, qTox grabs desktop as video input.

Which leads to the other program having to handle situation where qTox uses it – and it doesn't seem to be able to handle it.

**Comment by ProMcTagonist** [comment]
What other programs grab the desktop as video input? How do they affect TightVNC?

**Comment by sagg629** [comment]
Hi.
I don't know if this is a right place to put my issue, but I do have issues with TightVNC in Ubuntu 20.04 (KDE Plasma).
The remote window closes suddenly when I open certain programs, like Dolphin or Kate.

This error appears in the console:

```
CleanupXtErrorHandler called
Error: Event with wrong window
```
