### ISSUE TITLE
qTox crashes after screen turned off

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#3065]
---

**Report from user `dingdong` in IRC:**

---

Brief description: qTox crashes on user logon from idle screen off

Operating System: Linux 15.04 64-bit Lubuntu + PCManFM
qTox version: (shown on `About` page in settings)  nightly
Hardware: Intel Core 2 Duo, 4 GB ram, 200+ GB HDD

Reproducible: Always

**Steps to reproduce:**  
1.  computer idles with qTox and other apps running
2.  screen turns off after preset time
3.  login prompt
4.  qTox crashes at less than one second after login

**Observed Behavior:**  
qTox crashes, possibly due to desktop grab for video input

**Expected Behavior:**  
qTox should not crash on system resume

**Additional info:**  
n/a

**Comment by zetok** [comment]
It would be good to get a backtrace if someone can reproduce.

**Comment by ghost** [comment]
#2640? The issue is gone for me, but may be affecting other systems.

Another crash related to the screen I got: #2144.

I think more info is needed... I reproduce the same steps several times daily and qTox doesn't crash.

**Comment by zetok** [comment]
From #qtox:

[17:42:21] <tux3> Welp: https://bugreports.qt.io/browse/QTBUG-42985 https://bugs.launchpad.net/ubuntu/+source/qtdeclarative-opensource-src/+bug/1450137 https://bugs.kde.org/show_bug.cgi?id=340267
[17:42:27] <tux3> It's a known upstream bug apparently

**Comment by sudden6** [comment]
Since the upstream bug was closed long ago, I'll also close this one.
