### ISSUE TITLE
Update friend request list after you have added the contact manually

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#3066]
**Brief description:**
Assume Alice got a friend request from Bob. At the `Friend requests` tab you can see this and "Accept" or "Reject" the request. Everything fine so far.
But now, if Alice is adding Bob to her contact list manually via the `Add a friend` tab, you can still see the friend request from Bob in the `Friend requests` tab.

**Expected Behavior:**
Remove the friend request from the list because it was accepted when you manually added the person to your contact list.

**Comment by Diadlo** [comment]
It seems, like we can't detect which request read and which unread. And it means, that we can't easily select decrement unread counter or not. Should we save Set with unread markers? Or change type of friend requests from list of pair `toxId : request message` on list of structure with bool field `read`?

**Comment by SkyzohKey** [comment]
@Diadlo Simply iterate over the friend requests list when you add the contact manualy. If a ToxID match the one that got added, remove it from the list. Simple as fuck. :)

**Comment by Diadlo** [comment]
@SkyzohKey. Nope. Sorry for my bad english, I try again. Problem not with friends requests. Problem with "unreadFriendsRequests" it is counter which show how many requests are unread. 
1) In fact requst may be read and unread.
2) Amount of unread messages saved in unreadFriendsRequests field of Settings.
3) Amount of unread messages are displayed on top of friend list.
4) When we delete request we don't know read it or not => we don't know, should we decrement counter, or not.
