### ISSUE TITLE
Feature request: add support for tray icon in Elementary OS 'wingpanel'

### ISSUE THREAD

**Issue by sysfu** [qTox/qTox#3072]
Brief description: add support for tray icon in the Elementary OS [wingpanel](https://launchpad.net/wingpanel) (top menu bar notification area)

Operating System: elementary OS 0.3.2 Freya (32-bit)
qTox version:  v1.3.0-117-gde48789
Hardware: mid-2007 MacMini Core2Duo
…

Reproducible: Always

**Steps to reproduce:**  
1.  Launch qtox
2.  Navigate to settings => general tab => check 'show system tray icon' box

**Observed Behavior:**  
No qtox icon appears in wing panel

**Expected Behavior:**  
Icon should appear in wing panel

---

More information on how to write good bug reports in the wiki: https://github.com/tux3/qTox/wiki/Writing-Useful-Bug-Reports

**Comment by zetok** [comment]
And what kind of foul sorcery does eOS require for tray to work?

Current tray implementation is able to work on most of DEs available, just not eOS.. which makes me wonder if it's not just simply a bug in eOS.

https://github.com/tux3/qTox/wiki/Tray-icon

**Comment by sysfu** [comment]
That's a good question, I have not dug into it myself and I'm not even sure that tray icon support for wingpanel has been documented yet.

Let me touch base with the elementary devs and see what they say.

**Comment by dessalines** [comment]
How did you even install qTox on elementary OS, I can't seem to do it from the instructions using `$(lsb_release)`.

**Comment by sysfu** [comment]
The trick is to edit /etc/apt/sources.list.d/tox.list to read: 'deb https://pkg.tox.chat/debian nightly release'

Took me some digging to figure it out too.

**Comment by sysfu** [comment]
Also just as a point of comparison, I've noticed that the https://justgetflux.com/ and https://www.enpass.io apps successfully place 'tray' icons in the wingpanel, so it can be done. I've written the EOS devs and am waiting to hear back.

**Comment by sysfu** [comment]
[Here's a thread](https://elementaryos.stackexchange.com/questions/4574/spotify-icon-tray) discussing how support for a Spotify icon in the wingpanel 'tray' area was added.

Does that help?

**Comment by sysfu** [comment]
@codygarver Can you please comment on this issue if you have a minute or two? I sent yourself and Daniel an email the other week, but maybe it got sent to the bitbucket.

**Comment by sysfu** [comment]
@zetok Let me know if/when a fix is pushed and I'll be happy to test it.

**Comment by zetok** [comment]
But.. docs?

**Comment by sysfu** [comment]
Was the earlier thread I linked to in comment above regarding how they did it for Spotify not of any help? No response from the EOS devs so far and have not been able to locate the documentation on my own.

**Comment by ProMcTagonist** [comment]
http://elementaryos.stackexchange.com/questions/4226/how-can-i-get-applications-to-display-a-system-tray-icon

That's Daniel Fore.

HIG:

https://elementary.io/docs/human-interface-guidelines#system-indicators

> You do not need an indicator if:
> 
> The application is for IM, IRC, e-mail, news-reading, or music playback. Instead, integrate the application with the existing messaging or sound menus.

The System Tray as a concept isn't in elementary OS' vision.

**Comment by zetok** [comment]
@sysfu well, that's not docs.

@ProMcTagonist thanks :)

Looks like this issue can be closed?

**Comment by sysfu** [comment]
Yes, looks like it's a dead end request with regards to Elementary OS, thanks @ProMcTagonist for digging up the relevant stack exchange post.

**Comment by sysfu** [comment]
On the current build, the tray icon is now showing up in the wingpanel notification area. 

You cannot restore the application once minimized or closed to the tray icon, however you can set online status and logout/exit.

**Comment by zetok** [comment]
> You cannot restore the application once minimized or closed to the tray icon, however you can set online status and logout/exit.

User now should be able to work-around this DE bug with `Show` tray button – https://github.com/tux3/qTox/commit/a851a5b18da8c295fba441c817920cf65db2cdbb

**Comment by sysfu** [comment]
Tested and confirmed Show tray button now works on Elementary OS. A recent update gave it a purdy lookin' icon too. 

![fancy icon](https://i.imgur.com/S0X0Yec.png)
