### ISSUE TITLE
Detached chat windows remain open after disabling multi-window mode

### ISSUE THREAD

**Issue by smc2000** [qTox/qTox#3078]
Brief description: The title already does a good job at describing what happens.

Operating System: Linux Mint 17.2 XFCE 64bit
qTox version: v1.3.0-127-g https://github.com/tux3/qTox/commit/791d871737dc27371434386ca9b5c4def4d7a67a

Reproducible: Always

**Steps to reproduce:**  
1.  Start with qTox in single window mode.
2.  Enable multiple windows mode.
3.  Click a friend or group chat to open a detached chat window.
4.  Disable multiple windows mode.

**Observed Behavior:**  
The detached chat window remains open. Clicking the chat's entry in the friend list puts focus on the floating chat window.

**Expected Behavior:**  
Close all extra windows upon disabling multi windows mode.

**Additional info:**  
Messages written in the floating chat window correctly appear in the unified qTox window once I close the floating chat to carry on the conversation in single window mode.

**Comment by zetok** [comment]
> Close all extra windows upon disabling multi windows mode.

In a "single window mode" you still can open detached windows, it's just not a "default" action.

So why would you expect them to be closed once option for just the behaviour gets changed?

**Comment by smc2000** [comment]
When you right click a friend in single window mode to open a chat in a new window, that is a very direct action that is clearly described by the option on the right click menu. The resulting action is therefore expected from the user's perspective. On the other hand, if a user wants to return qTox to single window mode by disabling the multi window option, I think it makes most sense that the user expects all open qTox windows to merge together into one and that would mean closing the detached chats so that the conversation can continue in one window. After all, "not multiwindow == single window".

**Comment by zetok** [comment]
> if a user wants to return qTox to single window mode by disabling the multi window option

Except that it's not a switch on/off, but a switch for a default behaviour, which user can "override" without touching the option.

I.e. option doesn't change qTox's capabilities, but merely its default behaviour.

Thus,

> After all, "not multiwindow == single window".

`no multiwindow by default ≠ single window` would be correct.

**Comment by zetok** [comment]
Needed info not provided for over a month, thus closing.
