### ISSUE TITLE
qTox crashed on tab AV preference (1.3.0)

### ISSUE THREAD

**Issue by SergeyDjam** [qTox/qTox#3086]
uname -a 
Linux nb 4.1.19-nrj-desktop-2rosa-x86_64 #1 SMP PREEMPT Fri Mar 11 17:31:47 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/release 
ROSA Desktop Fresh R7 release 2014.1 for x86_64

qmake-qt5 --version
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib64

rpm -qa | grep qtox
qtox-1.3.0-1-rosa2014.1.x86_64

rpm -qa | grep toxcore
toxcore-debuginfo-0.0.1-0.20150107-rosa2014.1.x86_64
lib64toxcore0-0.0.1-0.20160220.2-rosa2014.1.x86_64
lib64toxcore-devel-0.0.1-0.20160220.2-rosa2014.1.x86_64
toxcore-devel-0.0.1-0.20160220.2-rosa2014.1.x86_64

qtox -> preferens -> AV -> crash

[18:22:20.885] src/video/camerasource.cpp:209 : Debug: Opening device  "/dev/video0"
[video4linux2,v4l2 @ 0x2b1b880] Cannot find a proper format for codec 'mjpeg' (id 8), pixel format 'none' (id -1)
Assertion *codec_id != AV_CODEC_ID_NONE failed at libavdevice/v4l2.c:821
Аварийный останов (слепок снят)

rpm -qa | grep mjpeg
lib64mjpegtools2.0_0-2.0.0-7-rosa2014.1.x86_64
lib64mjpegtools-devel-2.0.0-7-rosa2014.1.x86_64

And no problem on qTox 1.2.4 version

Brief description:

Operating System: Windows / OS X / Linux (include version and/or distro)  
qTox version: (shown on `About` page in settings)  
Hardware: 
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

**Steps to reproduce:**  
1.  
2.  
3.  
…

**Observed Behavior:**  

**Expected Behavior:**  

**Additional info:**  
(links, images, etc go here)

---

More information on how to write good bug reports in the wiki: https://github.com/tux3/qTox/wiki/Writing-Useful-Bug-Reports

**Comment by zetok** [comment]
It's most likely fixed on newest master. Care to re-test?

**Comment by SergeyDjam** [comment]
Rebuild master fix this problem. Thanks
