### ISSUE TITLE
OS X: Public key truncated in Show Details dialog

### ISSUE THREAD

**Issue by fmvin** [qTox/qTox#3088]
Brief description: For any contact in contact list a public key in "show details" dialog is truncated on several bytes. So adding new friend using public key is not possible. In the same time I cannot extract friend's ToxID from qTox.

Operating System: OS X 10.11.4
qTox version: v1.3.0-38-xxxx
Hardware: MacBook
…

Reproducible: Always

**Steps to reproduce:**  
1. Select "Show details" for a user in contact list  
2.  Copy public key to buffer
3.  Paste in any text window or qtox chat
4. Public key is truncated on 6 bytes
…

**Observed Behavior:**  

**Expected Behavior:**  
Copied public key should be the same for this contact

**Additional info:**  
(links, images, etc go here)

---

More information on how to write good bug reports in the wiki: https://github.com/tux3/qTox/wiki/Writing-Useful-Bug-Reports

**Comment by TheNain38** [comment]
When you say Public Key, you're talking about the ToxID, or really about the Public Key? Because the ToxID is 6 bytes longer than the PK because it contains, PK+NoSpam+Checksum, NoSpam is 4 bytes and Checksum is 2 bytes which adds up to 6 bytes

**Comment by fmvin** [comment]
The issue comes from that I would like share ToxID of my friend to another friend from my contact list. In qTox I found only "Public key" available on "Show details" dialog. If I send any public key to my friend then he cannot add a friend using this public key.

**Comment by ghost** [comment]
#2604

**Comment by fmvin** [comment]
Thats great. And how can I share contacts between friends in my contact list?
Only one solution I see here its to request ToxID from friend #1 and send it to friend #2 (extremely user friendly solution).

**Comment by ghost** [comment]
Yes, that, or use a DNS. More interesting discussion related to this issue in #235 and about sending IDs between friends in https://github.com/irungentoo/toxcore/issues/1350.

**Comment by zetok** [comment]
> Only one solution I see here its to request ToxID from friend #1 and send it to friend #2 (extremely user friendly solution).

Indeed.
What you would want, is an automated way of doing that, i.e. you clicking once or twice, and qTox & toxcore handling the stuff. In a case where both of your friends would accept "request", they would be added to each other.
For that though there's required toxcore support.

Closing, since currently it's not doable, and it's an upstream issue. When upstream implements required functionality, qTox should support it.

**Comment by ProMcTagonist** [comment]
How many duplicates have their been about sending friends to each other?

**Comment by zetok** [comment]
@ProMcTagonist #2604 has like 2 ATM.
