### ISSUE TITLE
Please officially select an edgy codename and update the repo

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#31]
It's becoming a distraction and an impairment to toxgui's becoming the new best client. Favorites tux3 has mentioned are Plague and Mercury.

**Comment by lehitoskin** [comment]
Plague++

**Comment by suhr** [comment]
Plague.

**Comment by tux3** [comment]
I'm sticking with toxgui with the moment since it seems to have some momentum, but I'll keep those suggestions in mind for later.

Closing and wontfixing, but I might reopen later.
