### ISSUE TITLE
Binary blobs in tools/

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#3103]
Are they needed? And if so, is it a good idea to use things >2 years old?

https://github.com/tux3/qTox/tree/20a61e4cc34815a6ffb5bf950cee3c710e8bb89e/tools

In either case, I'd propose to remove them, and if there's need, use something more appropriate, e.g. just make scripts that would allow for getting/compiling required stuff.

**Comment by tux3** [comment]
Seconded. The binaries should be removed, some of the source code in there is still used though.
