### ISSUE TITLE
One blank character too much if text in group chat is highlighted

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#3106]
![2016-04-06-194416_1366x768_scrot](https://cloud.githubusercontent.com/assets/8258609/14326899/3928f7c4-fc30-11e5-96af-6458d7d6bc12.png)

![2016-04-06-194409_1366x768_scrot](https://cloud.githubusercontent.com/assets/8258609/14326896/364839ac-fc30-11e5-8b32-6c4b684fc725.png)

**Comment by ezavod** [comment]
Seems to be fixed. Can not reproduce in versions since qTox 1.6.0 on Linux at least.
