### ISSUE TITLE
qtox-git from AUR compiles latest 1.2 version instead of 1.3

### ISSUE THREAD

**Issue by DX37** [qTox/qTox#3108]
Brief description:
When I build qtox-git from AUR repo, it builds 1.2 version.

Operating System: Linux (updated Arch Linux)  
Reproducible: Always

**Steps to reproduce:**  
1.  Type `yaourt -S qtox-git`
2.  Wait for compile
3.  Look into version info - it's 1.2-**\* version

I've got a latest 1.3 git version, when I change 1.2 to 1.3 in qtox-git PKGBUILD.

**Comment by ProMcTagonist** [comment]
can we have an arch tag

**Comment by zetok** [comment]
That's a problem with arch.

**Comment by DX37** [comment]
Sorry, but after updating package from AUR, it compiles 1.3 version by default. Without changing default downloaded PKGBUILD.
