### ISSUE TITLE
Undefined symbol with Qt 5.3 on Kubuntu 15.10

### ISSUE THREAD

**Issue by Talkless** [qTox/qTox#3119]
##### Brief Description

OS: Kubuntu 15.10 amd64
qTox version: master
toxcore:  master
Qt:  5.3.2
Hardware:  VirtualBox

Reproducible: Always
##### Steps to reproduce
1. Build with Qt 5.3 on Kubuntu 15.10
2. Get image from other tox user
3. Click on image to open
##### Observed Behavior

Image did not open. 
Output: 

```
kde-open5: symbol lookup error: /usr/lib/x86_64-linux-gnu/libKF5ItemViews.so.5: undefined symbol: _ZNK19QAbstractProxyModel15canDropMimeDataEPK9QMimeDataN2Qt10DropActionEiiRK11QModelIndex
```
##### Expected Behavior

Image should open with default image viewer.
##### Additional Info

[INSTALL.md](https://github.com/tux3/qTox/blob/master/INSTALL.md) States that minimal Qt version is 5.3, so I am using exactly that.

[doc.qt.io](https://doc.qt.io/qt-5/qabstractproxymodel.html#canDropMimeData) states that `QAbstractProxyModel::canDropMimeData` method is added in Qt 5.4. If qTox is built with Qt 5.4.1 it works as expected.

So looks like there is need to bump minimal Qt version?

**Comment by zetok** [comment]
~~That looks like a problem with your system not being able to open the file.~~

Edit: sorry, nvm that ↑

**Comment by zetok** [comment]
> So looks like there is need to bump minimal Qt version?

The main "problem" with it is that current Debian 8 (stable) would not be supported with Qt >5.3.

**Comment by Talkless** [comment]
If I install it from `https://pkg.tox.chat/debian/ nightly/wily` it works OK. I guess it's built with system Qt, which is 5.4 right?

So to recap, one has to build with >=5.4 to run on Kubuntu >= 15.10. If developer uses system Qt -dev packages on that system, there will be no problem.

I guess hint in INSTALL.md should be enough?

**Comment by Talkless** [comment]
Closing old irrelevant bug report.
