### ISSUE TITLE
Have to Press Shut Down While qTox is Running in Xubuntu 15.04/15.10

### ISSUE THREAD

**Issue by curlyfriess** [qTox/qTox#3120]
##### Brief Description

OS: Windows / OS X / Linux (include version and/or distro)  : Xubuntu 15.04/10
qTox version: (version numbers in menu `Settings → About`)  1.3.0-158-gd58922c
Commit hash:  d58922c667d023cf17cc22f2a761783088493e73
toxcore:  0.0.0
Qt:  5.5.1
Hardware:  
…

Reproducible: Always
##### Steps to reproduce
1. Start qTox on logon. 
2. Try to shut down Xubuntu. 
##### Observed Behavior

When running qTox I have to press shut down twice quickly from the power down menu to shut down the PC. If I wait too long it will not work. This only happens when qTox is running. The command ran by the shut down menu to shut down the computer is xfce4-session-logout --halt. I recreated the same thing from the terminal, I had to run the same command twice within a short period of time to successfully shut down the PC. 
##### Expected Behavior

Only having to press shut down once. 
##### Additional Info

(links, images, etc go here)

---

More information on how to write good bug reports in the wiki: https://github.com/tux3/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by zetok** [comment]
What happens when you do `sudo systemctl poweroff` ?

**Comment by zetok** [comment]
From #3126, thanks to @dolohow; on KDE5:

---

Logs:

```
kwi 11 22:59:25 [HOSTNAME] ksmserver[1226]: ksmserver: Client  "/usr/bin/qtox"  ( 10c4c79895000146036067500000007290009 ) canceled shutdown.
```

**Comment by zetok** [comment]
So, the question is whether qTox can close itself when DM demands without any data loss..?

**Comment by dolohow** [comment]
I guess it should handle the signal and sync configuration, history etc. to the disk

**Comment by zetok** [comment]
Not reproducible on debian 8 mate.

Not sure though if that doesn't result in possibility of data loss, given how systemd handles closing stuff.

**Comment by sudden6** [comment]
@curlyfriess could you retest with 077a84446129076537b34d9f3b5d7143d7019b0f ? this should contain a fix for your issue.

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.

If issue is still not fixed, please comment for reopen.
