### ISSUE TITLE
User online/offline messages stopped working

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3123]
All of a sudden qTox doesn't show these messages any more. Same version, same config files. Normally it always showed that user went online/offline, and now not any more. I think this is some intermittent problem. "Keep chat history" is "on", and I don't see any other options that might affect this.

qTox-1.3.0

**Comment by zetok** [comment]
Do you have `Show contacts' status changes` set?
![setting](https://cloud.githubusercontent.com/assets/3148759/14439935/92824ab6-0025-11e6-90de-25337e17df7d.png)

**Comment by yurivict** [comment]
"Show contacts" is "on"

**Comment by zetok** [comment]
Can't reproduce on newest (0a2f54194569e626ef8501c610647219887505d4) qTox. Steps?

**Comment by yurivict** [comment]
No steps. Happened suddenly, without any obvious reason.

History of past communications is also gone.

**Comment by zetok** [comment]
> No steps. Happened suddenly, without any obvious reason.
> 
> History of past communications is also gone.

Ok. Can you at least describe how things were, and at which point (after what) it stopped working?

**Comment by zetok** [comment]
As for history – r-clicking in chatform → `Load chat history` doesn't help?

**Comment by yurivict** [comment]
After the other user sent me some message online/offline notifications work again with this user.

> Ok. Can you at least describe how things were, and at which point (after what) it stopped working?

It was working fine up to an hour ago. I exited the qTox instance and immediately restarted it again, and didn't see the online/offline notifcations any more.

> As for history – r-clicking in chatform → Load chat history doesn't help?

Yes, history problem was due to this, sorry. It came back.

But notifications are a problem.

**Comment by yurivict** [comment]
So in short: Notifications stop working without an obvious reason. They work again after message exchange with the user. Something isn't clean somewhere.

**Comment by zetok** [comment]
> It was working fine up to an hour ago. I exited the qTox instance and immediately restarted it again, and didn't see the online/offline notifcations any more.

Well, those notifications aren't (yet) saved, so after restarting qTox you don't see "old" notifications.

> After the other user sent me some message online/offline notifications work again with this user.

**Notifications not working unless there's some message shown in chatform** – this is a bug.
