### ISSUE TITLE
[feature suggestion] Always load the chat history for a certain period of time

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3124]
Currently qTox starts without the history. The user needs to use "Load chat history" command.

My suggestion is to have an option "Show chat history for" + combobox with the choices. When selected, this will load the history for a certain period of time set by the user.

Reason: with many other IM clients doing this, users expect to see the history after the program is restarted.

**Comment by zetok** [comment]
Last 7 days should be already be loaded – is that not the case?

Aside from that, there are #3004 and #1198.

**Comment by yurivict** [comment]
Yes, last 7 days are the silent default.

So I am asking to make it a user option.

**Comment by ProMcTagonist** [comment]
Would prefer always loading a certain number of messages, not by time as it is currently. #2013 was going to do this + more on scrollup.

**Comment by yurivict** [comment]
qTox can have both as a user choice.

**Comment by zetok** [comment]
> qTox can have both as a user choice.

Nah. Currently it is supposed to load last 7 days of history, and if it doesn't do that, then it's a bug. Target though, if someone is adapting #2013, is loading up to `#N` last messages, and from there dynamically, as user will scroll up.
