### ISSUE TITLE
Device name in config qTox is not correct....

### ISSUE THREAD

**Issue by borrougagnou** [qTox/qTox#3125]
OS: MAC OS X 10.9.5
qTox version: v1.3.0-38-ga48c422
…
Why the name of Audio Device is "weird"?
![capture d ecran 2016-04-11 a 22 30 05](https://cloud.githubusercontent.com/assets/10796546/14441629/07991f22-0036-11e6-8551-3963ced377c4.png)

Before, no name of device:
![capture d ecran 2016-04-11 a 22 46 15](https://cloud.githubusercontent.com/assets/10796546/14441881/53b7d0e6-0037-11e6-8365-09f64e7b884f.png)

but the really name in mac:
Legend: NAME --> TYPE
## Input:

Internal Microphone --> Built-in
Line In --> Audio line-in-port
--- OPTIONAL ---
Digital In --> Optical digital-in port
NAME OF DEVICE --> USB

---
## Output:

Internal Speakers --> Built-in
Line In --> Audio line-in-port
--- OPTIONAL ---
NAME OF DEVICE --> USB
NAME OF DEVICE --> HDMI
Apple TV --> AirPlay

Regards,
Boris.

**Comment by zetok** [comment]
What is the problem?

**Comment by borrougagnou** [comment]
what is this strange name in the latest version of qTox?
(name of device in the first picture)

The input / output (in the end of post) is a real name of device

**Comment by zetok** [comment]
No idea. I'd assume that it's something from your system.

**Comment by borrougagnou** [comment]
I search but I don't find the strange name in my computer x.X sorry
![capture d ecran 2016-04-12 a 00 24 59](https://cloud.githubusercontent.com/assets/10796546/14444371/49d17f6a-0045-11e6-85ba-e2111a1dda51.png)
![capture d ecran 2016-04-12 a 00 23 07](https://cloud.githubusercontent.com/assets/10796546/14444382/57349584-0045-11e6-8c2f-2e96a1d79983.png)
![capture d ecran 2016-04-12 a 00 27 52](https://cloud.githubusercontent.com/assets/10796546/14444388/693c3232-0045-11e6-95d2-9414999ed768.png)

**Comment by Chiitoo** [comment]
It seems there are Swedish and French translations mingling together for some reason...

**Comment by ghost** [comment]
But that's not part of the translations afaik. I get the string in English, always.

**Comment by antis81** [comment]
The audio device name list was changed in a PR somewhere late 2015 (if required, I'll lookup the commit later). This is wrong behavior -> the default behavior of OpenAL does the right thing and selects the "Default Input/Output Device" when passing `nullptr` as the device name. What we see here, is some hybrid state and this is never a good thing… :)

**Comment by antis81** [comment]
@borrougagnou Changed title to what this issue is about. Can you please provide some feedback, if device names are still in another language for you?

**Comment by borrougagnou** [comment]
sorry for long response time, it's difficult for me this month.
I have always the same problem...
In qTox 1.4.1.1:
![capture d ecran 2016-06-26 a 13 30 48](https://cloud.githubusercontent.com/assets/10796546/16362003/456c00ec-3ba2-11e6-9aca-bfcac29b3fe2.png)

**Comment by antis81** [comment]
@borrougagnou Thanks. No need to post the same screenshot over and over… :)

I had a look into the code some weeks ago. There's two scenarios, which can lead to your situtation:
1. You actually switched language at some point and qTox thought to save the text in the other language (is it swedish?).
   - qTox does not translate audio device names. The names are taken "as is" from OpenAL. But…
   - … qTox saves the device names in the user settings file. If you copy that file… well, you may see a french name on an indian laptop… :smile:
2. OpenAL actually retrieves those device names from the system and thinks your computer is swedish (or whatever that language is).

Further I have some questions:
1. Can you hear anything, when making a call?
2. What does the list in qTox settings show? -> Screenshot, please… either one of the input/output list will be fine.
3. After you select another device -> is it still the same?

FYI: We plan for switching audio API to one, that better fits our needs in qTox. Anyway I made a PR #3175, which is WIP and probably not being merged for this reason. Unfortunately I have very limited time on qTox as well. So I won't make any promise on when that's going to be implemented.

**Comment by borrougagnou** [comment]
I waiting update :3
but actually I do not know why, I don't receive update and nothing information for know if I have a latest version or not...

**Comment by zetok** [comment]
> but actually I do not know why, I don't receive update and nothing information for know if I have a latest version or not...

Yeah, currently only Linux / windows get real updates. It's mentioned in README.md:

> Builds other than installer/packages don't receive updates automatically, so make sure you get back to this site and regularly download the latest version of qTox.

**Comment by sudden6** [comment]
@borrougagnou does this problem still exist?

**Comment by borrougagnou** [comment]
Sorry for my late answer, I'm busy atm

and, no... I have "Core audio" anywhere now + difficult to click in "Disable" option

**Comment by sudden6** [comment]
Not an issue anymore
