### ISSUE TITLE
Cannot add users to group chat

### ISSUE THREAD

**Issue by cbeams** [qTox/qTox#313]
I can create a new group chat via qTox, but I see no way to actually add contacts to it. A friend is using uTox, and he is able to create a group chat and drag contacts into it. So this appears to simply be functionality missing at the UI level in qTox. Am I missing something?

**Comment by dubslow** [comment]
Right click on your friend, one of the options should be to invite to group chats

**Comment by cbeams** [comment]
Strange. Was sure I'd tried that previously and to no avail. Just tried again now, and I see the "Invite in group" menu item. Thanks.

**Comment by dubslow** [comment]
Heh, in the intervening hour, a pull request has been submitted that adds the drag and drop support you were looking for :)

**Comment by cbeams** [comment]
> Heh, in the intervening hour, a pull request has been submitted that adds the drag and drop support you were looking for :)

Nice. #316 for reference.
