### ISSUE TITLE
Add documentation about Markdown "code" tags

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#3136]
The code tags are currently missing in the usermanual.

Edit: With "code tags" the Mardown `code` formatting in qTox chat messages is meant.

**Comment by zetok** [comment]
e.g.
![code example](https://cloud.githubusercontent.com/assets/3148759/14731796/6c474a20-084c-11e6-966e-cfce8eea7e59.png)

Edit: it should be noted that current iffy support of markdown codeblocks is only a ~temporary thing, and at some point in time it will be replaced by a proper markdown codeblocks.

**Comment by zetok** [comment]
~~https://github.com/tux3/qTox/blob/5045c460d7dd4d2459f695507137a4239fb2c72a/doc/user_manual_en.md#message-styling ?~~

Edit: nvm, I've read it again

**Comment by zetok** [comment]
Fixed in 108cb32ce73fe06c4a3d72b078eff4cafb82a988, thus closing.
