### ISSUE TITLE
Icon blinking after reading message

### ISSUE THREAD

**Issue by Diadlo** [qTox/qTox#3139]
##### Brief Description

OS: Arch Linux
qTox version: v1.2.2-444-g0a2f541
Commit hash:  0a2f54194569e626ef8501c610647219887505d4
toxcore: 0.0.0
Qt:  5.6.0 
…

Reproducible: Always
##### Steps to reproduce
1. Go to multi window mode
2. Collapse chat window
3. Get message
4. Expand chat window
##### Observed Behavior

Contacts icon will blink
##### Expected Behavior

Stop blinking icon

**Comment by zetok** [comment]
> Collapse chat window

Collapse where? To taskbar?

**Comment by Diadlo** [comment]
@zetok yes, to taskbar

**Comment by zetok** [comment]
What DE?

**Comment by Diadlo** [comment]
@zetok KDE 5
