### ISSUE TITLE
 Error processing the executable file

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#3140]
OS: Windows 
qTox version: 1.3

Reproducible: Always 
##### Steps to reproduce
1. it is necessary to obtain the executable file (or send it to someone)
2. call it for execution
##### Observed Behavior

reference (*.lnk) runs with a warning but is not execute correctly (not open)

The file reference contains a pointer to a remote share

**Comment by zetok** [comment]
> it is necessary to obtain the executable file (or send it to someone)

AFAIK currently there's no standalone executables – i.e. they need some libs to be also included in order to work.

> The file reference contains a pointer to a remote share

Could you provide more info on that?

**Comment by zetok** [comment]
Could you perhaps see if putting affected files in `.zip` and attaching here is possible?

**Comment by PKEv** [comment]
A link file contain address to shared folder, like "//192.168.1.10/box/mail/"

**Comment by zetok** [comment]
> > it is necessary to obtain the executable file (or send it to someone)
> 
> AFAIK currently there's no standalone executables – i.e. they need some libs to be also included in order to work.

Hm, looks like I've misunderstood – i.e. it's not about qTox executable, but any at all, right?

> call it for execution
> reference (*.lnk) runs with a warning but is not execute correctly (not open)

If you call `.exe` from qTox by clicking on its file transfer, it should be launched, rather than some `.lnk` file.
Is the issue about qTox launching a `.lnk` even though it received/sent an `.exe`?

If not, I think that I'm not seeing the issue.

**Comment by PKEv** [comment]
Yes, about qTox launching a .lnk file

**Comment by BiTOk** [comment]
I take it.
