### ISSUE TITLE
 Overlay fields when sending files

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#3141]
##### Brief Description

OS: Windows 
qTox version: v1.3.0-152-g983c4ff.
Commit hash:  983c4ff6887d956e9aac27070e8e43b4c27dc149

Reproducible: Sometimes 

![qtox_screenshot_2016-04-14 15-02-01 702](https://cloud.githubusercontent.com/assets/6053197/14527467/e7e7bf0c-0252-11e6-8502-5cc422fa274f.png)

**Comment by ghost** [comment]
#2227 #2268

**Comment by sudden6** [comment]
duplicate of #2227 thus closing
