### ISSUE TITLE
Inconsistency when two computers have qTox running with the same profile

### ISSUE THREAD

**Issue by ddobrev** [qTox/qTox#3143]
A friend uses qTox on Windows and OS X simultaneously. When I send him a message, he sometimes only receives it on one computer, sometimes only on the other, and sometimes on both.

Please note that while this one could be annoying, I am only sending it for the record. It's not nearly as important as https://github.com/tux3/qTox/issues/2820, https://github.com/tux3/qTox/issues/2726, https://github.com/tux3/qTox/pull/2771 or the still unreleased https://github.com/tux3/qTox/issues/2920.

**Comment by sudden6** [comment]
Just to clarify, he is trying to use the same ToxID on two computers?
Because that's not supported in Tox at the moment.

**Comment by ddobrev** [comment]
Yes, the same ToxID. He created his profile once and then copied it to his other OS. Just as I have but I do not use two OS-es at the same time.

**Comment by sudden6** [comment]
Using the same ToxID on more than one computer **at the same time** is unsupported in Tox.

**Comment by zetok** [comment]
> at the same time is unsupported in Tox.

At least for time being, until multiple devices are supported.

**Comment by ddobrev** [comment]
I understand. Thank you for the information. We can do without this one as long as the 4 others I have mentioned are fixed.
