### ISSUE TITLE
"*** Error in `qtox': free(): invalid pointer: 0x000000000245b040 ***" on normal exit

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3144]
Since the most recent update of qTox (`1.3.0-177-g1d6f32c-1`) I have noticed that this is the output in Terminal:

> [[19:57:00.168] src/persistence/settings.cpp:121 : Debug: "Loading settings from /home/boghog/.config/tox/qtox.ini"
> [19:57:00.169] src/ipc.cpp:46 : Debug: Our global IPC ID is  3993560339317860218
> [19:57:00.169] src/ipc.cpp:64 : Debug: Attaching to the global shared memory
> [19:57:00.169] src/ipc.cpp:259 : Debug: Previous owner timed out, taking ownership 14014811563473618655 -> 3993560339317860218
> [19:57:00.169] src/main.cpp:196 : Debug: built on:  21:43:31 Apr 13 2016 ( 1460583550 )
> [19:57:00.169] src/main.cpp:197 : Debug: commit:  built without git 
> 
> [19:57:00.170] src/nexus.cpp:81 : Debug: Starting up
> [19:57:07.358] src/persistence/profile.cpp:86 : Debug: Loading tox save  "/home/boghog/.config/tox/遊牧民.tox"
> [19:57:07.581] src/persistence/settings.cpp:371 : Debug: "Saving global settings at /home/boghog/.config/tox/qtox.ini"
> [19:57:07.691] src/persistence/settings.cpp:296 : Debug: Loading personal settings from "/home/boghog/.config/tox/遊牧民.ini"
> [19:57:08.814] src/core/core.cpp:236 : Debug: Loading user profile
> [19:57:08.814] src/persistence/profile.cpp:249 : Debug: Loading tox save  "/home/boghog/.config/tox/遊牧民.tox"
> [19:57:08.815] src/widget/systemtrayicon.cpp:65 : Debug: Using GTK backend
> 
> (qtox:5982): GLib-GObject-CRITICAL *_: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
> [19:57:08.951] src/core/core.cpp:132 : Debug: Core starting with IPv6 enabled
> [19:57:12.208] src/core/core.cpp:407 : Debug: "Connecting to 178.62.250.138:33445 (Impyy)"
> [19:57:12.209] src/core/core.cpp:407 : Debug: "Connecting to 130.133.110.14:33445 (Manolis)"
> [19:57:16.706] src/core/core.cpp:407 : Debug: "Connecting to 104.167.101.29:33445 (noisykeyboard)"
> [19:57:16.707] src/core/core.cpp:407 : Debug: "Connecting to 205.185.116.116:33445 (Busindre)"
> [19:57:20.171] src/core/core.cpp:374 : Debug: Connected to the DHT
> [19:57:20.171] src/persistence/profile.cpp:314 : Debug: Saving tox save to  "/home/boghog/.config/tox/遊牧民.tox"
> *_\* Error in `qtox': free(): invalid pointer: 0x000000000245b040 ***
> Aborted (core dumped)

The error occurs when I quit in the normal way, I don't do anything special.

I am running Ubuntu GNOME 15.10 with GNOME 3.18. I am sorry, due to some issues I am unable to provide the core dump, so either someone else with the issue will have to provide theirs or you will have to wait for a few days for me to get mine...

**Comment by sudden6** [comment]
can you provide the backtrace?

**Comment by zetok** [comment]
> src/widget/systemtrayicon.cpp:65 : Debug: Using GTK backend

That probably can be used to reproduce.

**Comment by ghost** [comment]
@Zetok, So do you need any more information from me?

**Comment by ghost** [comment]
I can no longer compile as usual at abcfbe9f92136c787723683b7e4c4aeee2eb0dd5 because

> Project ERROR: gtk+-2.0 development package not found

0a2f54194569e626ef8501c610647219887505d4 was still working fine. Maybe related?

**Comment by zetok** [comment]
@kehugter can you do `git bisect` ?

https://github.com/tux3/qTox/wiki/Testing#regression-testing

**Comment by ghost** [comment]
Yes, give me a minute to learn how it works.

**Comment by zetok** [comment]
@SeventhSonOfASeventhSon no, that would be it, thanks, I was able to reproduce :)

@sudden6 
With:

``` bash
export XDG_CURRENT_DESKTOP="GNOME"
```

bt: https://gist.github.com/zetok/563e9fde5ee2cf8d790bfdfd7f2afbb0

**Comment by ghost** [comment]
It was before I thought, the bad commit is be2f9501f85597c1877c2eed7d191d5523789f66.

**Comment by ghost** [comment]
@zetok, Oh, that's good!

**Comment by sudden6** [comment]
The problematic commit is cbb7eeca62f9ec8ad2047b41a7cb914b27d6c618 from @Diadlo maybe it's best to just revert it, because qTox also works without it.

@kehugter your problem doesn't seem to have anything to do with this, maybe move it to another issue?

**Comment by ghost** [comment]
@sudden6 Yep.

**Comment by ghost** [comment]
Ok, seems as though you released an update, I have upgraded to the latest version and no longer encounter the issue!
