### ISSUE TITLE
qmake fails in Debian. Missing gtk+-2.0 development package

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3145]
##### Brief Description

OS: Debian stretch
qTox version: -
Commit hash:  abcfbe9f92136c787723683b7e4c4aeee2eb0dd5
toxcore:  -
Qt:  5.5.1

Reproducible: Always
##### Steps to reproduce
1. run `qmake`
##### Observed Behavior

`qmake` fails with error

```
Project ERROR: gtk+-2.0 development package not found
```
##### Expected Behavior

No errors (dependencies for Debian in `INSTALL.md` haven't changed since December).
##### Additional Info

`git bisect` says that the bad commit is be2f9501f85597c1877c2eed7d191d5523789f66. `gtk+-2.0` is first introduced in this line https://github.com/tux3/qTox/commit/be2f9501f85597c1877c2eed7d191d5523789f66#diff-6a074c693ab3fcda2a48f60a4ef75bd5R228 and 2 more times later, it wasn't part of the file before.

CC: @OrangeShark

**Comment by OrangeShark** [comment]
`gtk+-2.0` should be available by pkg-config when you install `libgtk2.0-dev`, it is installed by one of the commands in `INSTALL.md` for debian [here](https://github.com/tux3/qTox/blob/master/INSTALL.md#debian-1).

**Comment by sudden6** [comment]
do you have pkg-config installed?

**Comment by ghost** [comment]
@sudden6 

`pkg-config` is installed.

```
Package: pkg-config
Status: install ok installed
Section: devel
Architecture: amd64
Version: 0.29-3
```

@OrangeShark 

`libgtk2.0-dev` is installed too

```
Package: libgtk2.0-dev
Status: install ok installed
Section: libdevel
Architecture: amd64
Source: gtk+2.0
Version: 2.24.30-1.1
```

**Comment by OrangeShark** [comment]
@kehugter 
I installed Debian Testing and was able to confirm that `gtk+-2.0` is available when you install `libgtk2.0-dev`. Possible it didn't install correctly? Can you run `pkg-config --list-all | grep gtk`?

**Comment by ghost** [comment]
@OrangeShark is listed there

```
$ pkg-config --list-all | grep gtk
gtk+-unix-print-2.0            GTK+ - GTK+ Unix print support
gtk+-2.0                       GTK+ - GTK+ Graphical UI Library (x11 target)
gtk+-x11-2.0                   GTK+ - GTK+ Graphical UI Library (x11 target)
```

but `qmake` still fails.

**Comment by sudden6** [comment]
I just successfully built qTox on a fresh install of Debian stretch using `simple_make.sh` so I highly suspect the issue is with your installation.

**Comment by ghost** [comment]
`simple_make.sh` mixes Debian and Ubuntu packages, but installing `libpng-dev` and `libpng-tools` (which removed `libpng12-dev` among others from my system) from that list seem to have fixed the problem. I have no idea why that worked.
