### ISSUE TITLE
Error compiling 

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#3146]
OS:  Linux debian
qTox version: v1.3.0-179-g8fa40d5
Commit hash:  8fa40d5c4f7ec06eeb060446ade5a1a635f5e96b
Qt:  5.6
Reproducible: Always

error : 

```
...../qTox/src/widget/form/settings/aboutform.cpp:59: error: 'class Ui::AboutSettings' has no member named 'knownIssues'
     bodyUI->knownIssues->setText(
             ^
```

**Comment by zetok** [comment]
Is it the same after `make clean && git checkout -f` ?

**Comment by PKEv** [comment]
yes

**Comment by zetok** [comment]
cc: @kehugter

**Comment by ghost** [comment]
Can't check 8fa40d5c4f7ec06eeb060446ade5a1a635f5e96b right now because of #3145, but the line seems OK in that commit: https://github.com/tux3/qTox/blob/8fa40d5c4f7ec06eeb060446ade5a1a635f5e96b/src/widget/form/settings/aboutsettings.ui#L310

I compiled #2983 in my machine several times without errors.

**Comment by PKEv** [comment]
line L310 is Ok.

Where must be defined "knownIssues"?

**Comment by zetok** [comment]
Not on debian, but I too can't reproduce. Also, it seems to compile just fine on travis.

@PKEv could you post steps to reproduce?

**Comment by PKEv** [comment]
no steps - just pull
I don't see "knownIssues" in "UI_ABOUTSETTINGS.H" (and the compiler too)

**Comment by initramfs** [comment]
Not on Debian but checking out 8fa40d5, I see "knownissues" declared in ui_aboutsettings.h on line 52 and defined in the same file on line 217 under Qt 5.6. This is the same under the latest revision too. Perhaps try rerunning qmake?

**Comment by PKEv** [comment]
manual clean help
