### ISSUE TITLE
 windows/bootstrap.sh requires tools/unzip that is missing

### ISSUE THREAD

**Issue by Talkless** [qTox/qTox#3153]
##### Brief Description

OS: Windows 10
qTox version: HEAD
Qt:  5.6
Hardware:  VirtualBox

Reproducible: Always
##### Steps to reproduce

Launch bootstrap.bat on Windows
##### Observed Behavior

cmd.exe printed that `../tools/unzip` (something like that) command not found during compilation.
##### Additional Info

Here's reference to unzip in windows/bootstrap.sh (https://github.com/tux3/qTox/blob/master/windows/bootstrap.sh#L28):

```
if [ ! -d "include/tox" ]; then
    $QTOX_DIR/tools/unzip -o libtoxcore_build_windows_x86_shared_release.zip -d ./
fi
```

Build is still running as I am writing (using one core instead of eight... :-/ ) so not sure how it affects build.

I am not sure what was original idea was - having binary inside repository? Maybe INSTALL.md should have instruction to install http://gnuwin32.sourceforge.net/packages/unzip.htm ?

**Comment by sudden6** [comment]
@zetok seems to be an issue with https://github.com/tux3/qTox/pull/3104

**Comment by zetok** [comment]
Yeah.

I think that the right "solution" would be to wget from somewhere `unzip.exe` in the script..?

Or is there a better way to do it?

(doesn't windows, like, already supports `zip` format? can't that be used?)

**Comment by sudden6** [comment]
we could directly download it from http://www.info-zip.org/UnZip.html#Downloads but I don't see why this should be better than it was before.

**Comment by zetok** [comment]
https://stackoverflow.com/questions/30211/can-windows-built-in-zip-compression-be-scripted

**Comment by sudden6** [comment]
It would still be easier to read unzip.exe

**Comment by Talkless** [comment]
If there is already need to download wGet and what not manually, I see no problem to also ask to download and install http://gnuwin32.sourceforge.net/packages/unzip.htm or that info-zip or whatever.
