### ISSUE TITLE
setup-qtox.exe doesn't work at all in Windows 10

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#3156]
`setup-qtox.exe` isn't working at all

OS: Windows 10
qTox version: v1.3.0
Commit hash: b69042ec407c30b27ce3e56bb6daf14300facc8e
toxcore: 0.0.0
Qt: 5.5.1

Reproducible: Always
##### Steps to reproduce
1. Launch `setup-qtox.exe`
##### Observed Behavior

`setup-qtox.exe` can't be launched, and if you try to delete it, it shows that: "The action can't be completed because the file is opened in `System`"
##### Expected Behavior

`setup-qtox.exe` launch and is able to install qTox

**Comment by zetok** [comment]
Could you see if it's still reproducible with newest (1.4.1) version?

**Comment by tux3** [comment]
NSIS – our installer – started to support Windows 10 in their August 2015 3.0 beta, and they released a 3.0 RC1 on April 3rd 2016. We're currently using version 2.5x.
Given their changelog and release schedule, the RC1 is probably stable enough to use, so we should start a transition to NSIS 3, that should fix this issue.

**Comment by ovalseven8** [comment]
Windows 10 is almost one year old now. Frankly speaking, let's switch to another installer because if NSIS doesn't support Windows 10 yet in a stable version, that's really poor for such a program.

Furthermore, there were/are some security problems related to NSIS apparently:
http://seclists.org/fulldisclosure/2015/Dec/32
http://seclists.org/fulldisclosure/2015/Oct/109
http://seclists.org/fulldisclosure/2015/Dec/74
http://seclists.org/fulldisclosure/2015/Dec/75

The alternative [Inno Setup](http://jrsoftware.org/isinfo.php) looks good to me. Supports Windows 10, with native look & feel and has a better reputation than NSIS as far as I know.

**Comment by zetok** [comment]
@ovalseven8 hmm, I don't see info about compiling that on Linux?

**Comment by ovalseven8** [comment]
Seems like Inno Setup is Windows-only.

**Comment by tux3** [comment]
As I understand it (according to their changelog at least) NSIS has fixed their DLL search hijacking issues a while ago in its 3.0 version, the main problem seems to be their very relaxed release schedule. 
I'm not opposed to moving to Inno Setup or another solution, assuming we can get it working on a real build server (so, Linux :>) and someone can take the time to rewrite the install script.

That said right now upgrading NSIS looks like the simplest effective solution to me, unless it's still vulnerable in its latest version.

**Comment by BiTOk** [comment]
1.4.1 was normally installed to windows 10 x64. Is this bug already fixed?

**Comment by zetok** [comment]
@BiTOk From what I remember, issue exists on "clean" win10 install, while things worked just fine on win7 → win10 upgraded system. (or maybe it was the other way around? I don't really remember :s )

**Comment by BiTOk** [comment]
@zetok No, it works on clean win10 install. I'll try it soon on several other win10.

**Comment by ovalseven8** [comment]
@tux3 
New stable NSIS release with Windows 10 support is out now!

**Comment by Diadlo** [comment]
@BiTOk said that all works fine. Can anyone else confirm?

**Comment by ezavod** [comment]
> Can anyone else confirm?

Does not seem to be an issue anymore. Latest `setup-qtox64-1.8.1.exe` works good for me on Win10 x64. Had no problems with installing on Win10 x64 at least since summer 2016.
