### ISSUE TITLE
One of my contacts is unable to see my status

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3160]
I recently found out that one of my contacts who is using `qtox-unity` does not see my status message even when I update it. My contact only sees blank as though I have not set a status message. Though I do not have this problem either way with any of my other contacts, nor does the contact who does not see my status message have any similar problems with any of their contacts. I can also see the status message of the contact who cannot see my own.

I am running Ubuntu GNOME 15.10 with GNOME 3.18 and `qtox` version `1.3.0-218-gb883d07-1`.

**Comment by zetok** [comment]
Steps to reproduce?

**Comment by ghost** [comment]
@zetok, I will have to ask my friend for more information when they come online, but all I really know is that they can't see my status message though I think they used to be able to see it... I'm sorry, but I don't know any more than that, I don't think I've done anything special lately.

**Comment by ghost** [comment]
It appears as though this issue has gone away all on its own after my friend restart qTox even though I was not online at this time (so my status must have been cached in his client and just not shown for some reason)...

**Comment by zetok** [comment]
I see. Sadly, there's not enough info to reproduce, which would be needed in order to fix, thus closing this issue.

If there'll be enough info to reproduce, please comment for reopen.
