### ISSUE TITLE
Can't see white icon in tray (add contrasting (black?) line around white icon)

### ISSUE THREAD

**Issue by meamuri** [qTox/qTox#3161]
##### Brief Description

OS: Windows 
qTox version: v1.3.0.
Commit hash: b69042ec407c30b27ce3e56bb6daf14300facc8e  
toxcore:  0.0.0.
Qt: 5.5.1. 

Reproducible: Always 
##### Steps to reproduce
1. Open settings
2. Set light icon
3. Open "show hide icons" in tray. 
##### Observed Behavior

Can't see white icon on default white background color
##### Expected Behavior

Make black border
##### Additional Info

![tox](https://cloud.githubusercontent.com/assets/15677472/14636524/a7bed45c-0634-11e6-8f32-0b95eabb4575.jpg)

**Comment by sudden6** [comment]
Isn't that exactly why we have a dark icon?

**Comment by zetok** [comment]
> Isn't that exactly why we have a dark icon?

Kinda. On the other hand, the reasoning here is that someone wants to have _white_ icon, but still wants it to be visible on white background.
Same (in reverse) could be applied to dark icon.

**Comment by ProMcTagonist** [comment]
The cloud and flag icons are white but can still be seen. I don't think it's unreasonable to expect the same of the white tox icon.

**Comment by agilob** [comment]
![screenshot_20160426_213418](https://cloud.githubusercontent.com/assets/2544251/14833334/a6a9c65e-0bf6-11e6-8a3b-2a22f5558d5f.png)

Change it in settings to dark icon?

**Comment by Diadlo** [comment]
@agilob I think both icons (light and dark) should be possible to showing on any background

**Comment by sudden6** [comment]
It seems this is not possible to do without making the icon look bad, see: https://github.com/qTox/qTox/pull/3336
