### ISSUE TITLE
Error when "accepting" friend request from someone you made a friend by sending them a request back

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3166]
If I have two qtox clients, A and B, if A sends a request to B, and instead of accepting the friend request, B simply sends another back, for A that will be the same as would happen if B had just accepted the request in the usual way, and the same for B too as both will be displayed in each other's contact lists as if they were contacts.
However, B will still have the green thing above their contact list telling them that they have a new friend request, and if they go to the list of pending friend requests the friend whom they have really already accepted, though not through the usual method, will be there. Now this is not a too larger issue though I think some corners could be polished in terms of the friend request system.

But the real issue comes not when they press the "Reject" button which now does nothing, but instead when they press the "Accept" button after they have already accepted the friend, just in a different way, and get this error:

![could_not_request_friendship_qtox_error](https://cloud.githubusercontent.com/assets/11575271/14690050/1415b310-0742-11e6-971b-74cbd0dde666.png)

You can have a play around with what happens when you send contact requests etc in different non necessarily expected ways, but I think that this should all be avoided, perhaps when sending a request to someone who has already sent you a request which is still pending it should just automatically accept it and remove it from the pending list? I am running Ubuntu GNOME 15.10 with GNOME 3.18 and `qtox` version `1.3.0-221-ged9ccbe-1`.

Here is the log output for A:

> [21:40:39.579] src/persistence/settings.cpp:121 : Debug: "Loading settings from /home/tester/.config/tox/qtox.ini"
> [21:40:39.582] src/ipc.cpp:46 : Debug: Our global IPC ID is  15969295485485358574
> [21:40:39.583] src/main.cpp:196 : Debug: built on:  17:16:56 Apr 19 2016 ( 1461085967 )
> [21:40:39.583] src/main.cpp:197 : Debug: commit:  built without git 
> 
> [21:40:39.584] src/nexus.cpp:81 : Debug: Starting up
> [21:40:42.351] src/persistence/profile.cpp:86 : Debug: Loading tox save  "/home/tester/.config/tox/panda.tox"
> [21:40:42.766] src/persistence/settings.cpp:378 : Debug: "Saving global settings at /home/tester/.config/tox/qtox.ini"
> [21:40:43.046] src/persistence/settings.cpp:296 : Debug: Loading personal settings from "/home/tester/.config/tox/panda.ini"
> [21:40:45.294] src/core/core.cpp:236 : Debug: Loading user profile
> [21:40:45.294] src/persistence/profile.cpp:249 : Debug: Loading tox save  "/home/tester/.config/tox/panda.tox"
> [21:40:45.301] src/widget/systemtrayicon.cpp:65 : Debug: Using GTK backend
> 
> (qtox:9917): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
> [21:40:45.586] src/core/core.cpp:132 : Debug: Core starting with IPv6 enabled
> [21:40:45.590] src/core/core.cpp:305 : Debug: Self avatar not found, will broadcast empty avatar to friends
> [21:40:47.116] src/core/core.cpp:407 : Debug: "Connecting to 194.249.212.109:33445 (fluke571)"
> [21:40:47.120] src/core/core.cpp:407 : Debug: "Connecting to 185.25.116.107:33445 (MAH69K)"
> [21:40:51.925] src/core/core.cpp:407 : Debug: "Connecting to 144.76.60.215:33445 (sonOfRa)"
> [21:40:51.929] src/core/core.cpp:407 : Debug: "Connecting to 23.226.230.47:33445 (stal)"
> [21:40:53.724] src/core/core.cpp:374 : Debug: Connected to the DHT
> [21:40:53.726] src/persistence/profile.cpp:314 : Debug: Saving tox save to  "/home/tester/.config/tox/panda.tox"
> [21:42:07.274] src/core/core.cpp:585 : Debug: Requested friendship of  0
> [21:42:07.275] src/persistence/profile.cpp:314 : Debug: Saving tox save to  "/home/tester/.config/tox/panda.tox"
> [21:42:37.952] src/core/corefile.cpp:285 : Debug: "Received avatar request 0:65536, reject, since we have it in cache."
> [21:53:54.071] src/persistence/profile.cpp:314 : Debug: Saving tox save to  "/home/tester/.config/tox/panda.tox"
> [21:53:54.394] src/persistence/settings.cpp:505 : Debug: Saving personal settings at  "/home/tester/.config/tox/panda.ini"
> [21:53:54.727] src/persistence/settings.cpp:378 : Debug: "Saving global settings at /home/tester/.config/tox/qtox.ini"
> [21:53:54.744] src/main.cpp:294 : Debug: Clean exit with status 0

And for B:

> [21:40:08.533] src/persistence/settings.cpp:121 : Debug: "Loading settings from /home/boghog/.config/tox/qtox.ini"
> [21:40:08.535] src/ipc.cpp:46 : Debug: Our global IPC ID is  17625569954701159888
> [21:40:08.536] src/main.cpp:196 : Debug: built on:  17:16:56 Apr 19 2016 ( 1461085967 )
> [21:40:08.536] src/main.cpp:197 : Debug: commit:  built without git 
> 
> [21:40:08.536] src/nexus.cpp:81 : Debug: Starting up
> [21:40:22.959] src/persistence/profile.cpp:86 : Debug: Loading tox save  "/home/boghog/.config/tox/遊牧民.tox"
> [21:40:23.444] src/persistence/settings.cpp:378 : Debug: "Saving global settings at /home/boghog/.config/tox/qtox.ini"
> [21:40:23.679] src/persistence/settings.cpp:296 : Debug: Loading personal settings from "/home/boghog/.config/tox/遊牧民.ini"
> [21:40:25.991] src/core/core.cpp:236 : Debug: Loading user profile
> [21:40:25.995] src/widget/systemtrayicon.cpp:65 : Debug: Using GTK backend
> [21:40:26.021] src/persistence/profile.cpp:249 : Debug: Loading tox save  "/home/boghog/.config/tox/遊牧民.tox"
> 
> (qtox:13543): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
> [21:40:26.264] src/core/core.cpp:132 : Debug: Core starting with IPv6 enabled
> [21:40:31.676] src/core/core.cpp:407 : Debug: "Connecting to 144.76.60.215:33445 (sonOfRa)"
> [21:40:31.678] src/core/core.cpp:407 : Debug: "Connecting to 23.226.230.47:33445 (stal)"
> [21:40:36.176] src/core/core.cpp:407 : Debug: "Connecting to 192.99.168.140:33445 (WIeschie)"
> [21:40:36.177] src/core/core.cpp:407 : Debug: "Connecting to 198.46.138.44:33445 (nurupo)"
> [21:40:38.844] src/core/core.cpp:374 : Debug: Connected to the DHT
> [21:40:38.845] src/persistence/profile.cpp:314 : Debug: Saving tox save to  "/home/boghog/.config/tox/遊牧民.tox"
> [21:42:09.777] src/audio/audio.cpp:267 : Debug: Opening audio output "Built-in Audio Analogue Stereo"
> [21:42:09.851] src/audio/audio.cpp:292 : Debug: Opened audio output "Built-in Audio Analogue Stereo"
> [21:42:31.452] src/core/core.cpp:585 : Debug: Requested friendship of  8
> [21:42:31.453] src/persistence/profile.cpp:314 : Debug: Saving tox save to  "/home/boghog/.config/tox/遊牧民.tox"
> [21:42:37.626] src/core/corefile.cpp:271 : Debug: "Received empty avatar request 8:65536"
> [21:50:38.274] src/persistence/settings.cpp:505 : Debug: Saving personal settings at  "/home/boghog/.config/tox/遊牧民.ini"
> [21:50:41.806] src/persistence/settings.cpp:505 : Debug: Saving personal settings at  "/home/boghog/.config/tox/遊牧民.ini"
> [21:54:09.769] src/persistence/profile.cpp:314 : Debug: Saving tox save to  "/home/boghog/.config/tox/遊牧民.tox"
> [21:54:12.039] src/persistence/profile.cpp:314 : Debug: Saving tox save to  "/home/boghog/.config/tox/遊牧民.tox"
> [21:54:12.352] src/persistence/settings.cpp:505 : Debug: Saving personal settings at  "/home/boghog/.config/tox/遊牧民.ini"
> [21:54:12.665] src/persistence/settings.cpp:378 : Debug: "Saving global settings at /home/boghog/.config/tox/qtox.ini"
> [21:54:12.719] src/main.cpp:294 : Debug: Clean exit with status 0
> [21:54:12.765] src/audio/audio.cpp:455 : Debug: Closing audio output

**Comment by zetok** [comment]
@SeventhSonOfASeventhSon could you use the template provided for issues? Without it, it's harder to read the bug reports.
