### ISSUE TITLE
remove Android code

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#3168]
- It's unmaintained
- Probably doesn't even work
- There are dedicated Android clients for Tox

I suggest to better modularize qTox instead, so additional platforms are easier to support in the future.
Paging @tux3 @zetok

**Comment by zetok** [comment]
Well, removing is easy, but on the other hand, modularizing won't be.

Just wanted to note that.

**Comment by tux3** [comment]
Fine by me, the Android code wasn't really going anywhere.
