### ISSUE TITLE
Unable to show up the main window once minimized/closed

### ISSUE THREAD

**Issue by mhow2** [qTox/qTox#3177]
Hi,
##### Brief Description

Linux (Ubuntu Wily)  
qTox version: (Nightly)  
Commit hash:  built without git
toxcore:  0.0.0
Qt:   5.4.2
Running Unity

Reproducible: Always
##### Steps to reproduce
1.  Start qtox with option to close/minimize in tray enable
2.  Close/minimize qtox
3.  qtox appears as an indicator in the tray : now, how do I show the main window up again ?
##### Observed Behavior

Unable / no option to show up the main window once minimized/closed as icon tray
##### Expected Behavior

Something to bring up the main window

**Comment by Diadlo** [comment]
What DE?

**Comment by mhow2** [comment]
DE ?

**Comment by mhow2** [comment]
I wrote "Running Unity" in my initial request so indeed, it's Unity ;)

**Comment by Diadlo** [comment]
Sorry. I didn't see it

Have you try http://www.howtogeek.com/68119/how-to-bring-app-icons-back-into-unitys-system-tray/ ?

**Comment by mhow2** [comment]
That's not the issue. Qtox Icon appears in the tray, but clicking/double click on it does not suggest a way to bring back the main window.

**Comment by sudden6** [comment]
have you tried "right click" ?

**Comment by mhow2** [comment]
@sudden6 : yes it shows up the same menu as left click, "online, away, busy / logout, exit"

**Comment by sudden6** [comment]
To summarize, the menu on shows up normaly on left/right click, but provides no way of showing the qTox window?

**Comment by zetok** [comment]
@mhow2 That sounds like an issue with your DE.

**Comment by zetok** [comment]
@mhow2 could you provide log? From `~/.cache/Tox/qTox/`

**Comment by mhow2** [comment]
@sudden6  : exactly
@zetok : here it is :
_edited by @zetok: moved paste to gist:_
https://gist.github.com/zetok/f933cde96681528c1caeeda9e71faa8d

**Comment by ghost** [comment]
I get the same on Ubuntu GNOME 15.10 with GNOME 3.18.

**Comment by ByteCommander** [comment]
Had the same issue with the latest version for Ubuntu 15.10 (Unity). Now I upgraded to 16.04 and use qTox version v1.4.0-14-g5045c46 and the entire indicator icon is gone...

**Comment by mhow2** [comment]
Where to start to solve this issue ?

**Comment by zetok** [comment]
> Where to start to solve this issue ?

My guess would to to just use distro/DE/wm that is not broken..

Debian 8 Mate works.

**Comment by sudden6** [comment]
I did some testing with a fresh Ubuntu 16.04 Release (Unity) and the tray icon works as expected there.

**Comment by zetok** [comment]
With a851a5b18da8c295fba441c817920cf65db2cdbb it should be possible for users to work-around what their shitty DE provides, could you test?

**Comment by zetok** [comment]
#3423

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.

If issue is still not fixed, please comment for reopen.
