### ISSUE TITLE
Where OS X homebrew instructions are gone?

### ISSUE THREAD

**Issue by ReDetection** [qTox/qTox#318]
Some time ago there are easy OS X install instructions #198. Where they are now? If they were deleted, can I ask you why?

**Comment by msteinbeck** [comment]
I think this is my fault. Somehow I missed to add the OS X instructions in INSTALL.md while writing the howto.

**Comment by mouseym** [comment]
We will need these back since jenkins is no longer doing OSX builds.

**Comment by dubslow** [comment]
Wait really? I thought qTox was the official client for OS X...

**Comment by mouseym** [comment]
All OSX builds have been offline since the 21st. tux3 supposedly has a build script that jenkins uses, could use that to do some manual builds.
