### ISSUE TITLE
Make qTox packages for Ubuntu 16.04

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3184]
I have found that on Ubuntu 16.04 (Xenial Xerus) if one adds the official repository that there are no packages in the xenial section, I have contacted the package maintainers and they say that this is because they have not yet been provided with packages built for xenial, what is the status on this?

Because I am actually holding back the Ubuntu upgrade from 15.10 because of this, and many of my contacts who are now running 16.04 are unable to get qTox the normal way and most don't want to compile from source so are stuck for the time being without it. I do hope that packages for xenial are put up on the repository soon.

**Comment by clnetbox** [comment]
Error when trying to install qtox from repository deb https://pkg.tox.chat/debian nightly xenial : 

sudo apt-get install qtox
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qtox : Depends: libsodium13 (>= 0.6.1) but it is not installable
        Depends: libtoxav0 but it is not going to be installed
        Depends: libtoxcore0 but it is not going to be installed
        Depends: libtoxdns0 but it is not going to be installed
        Depends: libtoxencryptsave0 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Old qtox versions are available from repository deb https://pkg.tox.chat/debian nightly release : 

apt-cache policy qtox
qtox:
  Installed: (none)
  Candidate: 580-6dd1cd0
  Version table:
     580-6dd1cd0 500
        500 https://pkg.tox.chat/debian nightly/release amd64 Packages

apt-cache policy qtox-unity
qtox-unity:
  Installed: (none)
  Candidate: 462-da2f892
  Version table:
     462-da2f892 500
        500 https://pkg.tox.chat/debian nightly/release amd64 Packages

**Comment by clnetbox** [comment]
Additional information about results from various approaches to install qtox in Ubuntu 16.04 : 

No qtox versions are available from repository deb https://pkg.tox.chat/debian nightly xenial :

apt-cache policy qtox
N: Unable to locate package qtox

apt-cache policy qtox-unity
N: Unable to locate package qtox-unity

A new qtox version is available from repository deb https://pkg.tox.chat/debian nightly wily :

apt-cache policy qtox
qtox:
Installed: (none)
Candidate: 1.3.0-248-g6dd1cd0-1
Version table:
1.3.0-248-g6dd1cd0-1 500
500 https://pkg.tox.chat/debian nightly/wily amd64 Packages

apt-cache policy qtox-unity
N: Unable to locate package qtox-unity

Error when trying to install qtox from repository deb https://pkg.tox.chat/debian nightly wily :

sudo apt-get install qtox
Reading package lists... Done
Building dependency tree

Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
qtox : Depends: libsodium13 (>= 0.6.1) but it is not installable
Depends: libtoxav0 but it is not going to be installed
Depends: libtoxcore0 but it is not going to be installed
Depends: libtoxdns0 but it is not going to be installed
Depends: libtoxencryptsave0 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Old qtox versions are available from repository deb https://pkg.tox.chat/debian nightly release :

apt-cache policy qtox
qtox:
Installed: (none)
Candidate: 580-6dd1cd0
Version table:
580-6dd1cd0 500
500 https://pkg.tox.chat/debian nightly/release amd64 Packages

apt-cache policy qtox-unity
qtox-unity:
Installed: (none)
Candidate: 462-da2f892
Version table:
462-da2f892 500
500 https://pkg.tox.chat/debian nightly/release amd64 Packages

**Comment by abbat** [comment]
@SeventhSonOfASeventhSon, @clnetbox you can temporary [use community builds](https://software.opensuse.org/download.html?project=home%3Aantonbatenev%3Atox&package=qtox) for Xenial.

**Comment by zetok** [comment]
Has been added to INSTALL.md: https://github.com/tux3/qTox/blob/deeb9b2308290e0404198a38a5d4c456ac39b328/INSTALL.md#community-builds ← could you check if it works for you?

**Comment by clnetbox** [comment]
@zetok : downloaded - extracted - executed - qtox v1.4.0-23-gdeeb9b2 seems to work properly so far ... :)

**Comment by ByteCommander** [comment]
Added the repository mentioned in the link and it works as well, although the warning that the package is not trusted did not go away even after adding the GPG key... But the qtox build is fine.

**Comment by zetok** [comment]
Since it works, closing.

**Comment by clnetbox** [comment]
@zetok You must have misunderstood something - manually downloading and using qtox is working properly, but qtox still is not available in the xenial repository : 

echo "deb https://pkg.tox.chat/debian nightly $(lsb_release -cs)" | sudo tee /etc/apt/sources.list.d/tox.list

deb https://pkg.tox.chat/debian nightly xenial

wget -qO - https://pkg.tox.chat/debian/pkg.gpg.key | sudo apt-key add -

OK

sudo apt-get update

apt-cache policy qtox

N: Unable to locate package qtox

**Comment by zetok** [comment]
@clnetbox no, there's no point in having open issues for tox.chat repo here. At least not when there's a working, better alternative.

**Comment by severustux** [comment]
@zetok no! Its is a real issue. The alternatives you are talking about are 

1) Using portable qtox, where there is no **indicator icon** & we need to manually check for updates and download it.

2) Method mentioned in your link. That is:
> `sudo apt-get install git`
> `git clone https://github.com/tux3/qTox.git ~/qTox`
> `sudo apt-get install build-essential qt5-qmake qt5-default qttools5-dev-tools libqt5opengl5-dev libqt5svg5-dev libopenal-dev libxss-dev qrencode libqrencode-dev libavutil-dev libswresample-dev libavcodec-dev libswscale-dev libavfilter-dev libavdevice-dev libglib2.0-dev libgdk-pixbuf2.0-dev libgtk2.0-dev libsqlcipher-dev`
> `sudo apt-get install libtool autotools-dev automake checkinstall check \
libopus-dev libvpx-dev libsodium-dev`
> `./bootstrap.sh`   
 Etc....


Tell me which is easier ?? 

`wget -q -O - https://pkg.tox.chat/debian/pkg.gpg.key | sudo apt-key add - 
sudo add-apt-repository "deb https://pkg.tox.chat/debian nightly release" 
sudo apt-get install qtox-unity`

OR 

(This whole 1 hour process)[https://github.com/tux3/qTox/blob/deeb9b2308290e0404198a38a5d4c456ac39b328/INSTALL.md#community-builds) ??

Providing an official repository would help a lot of users in installing qtox.

**Comment by ghost** [comment]
@zetok no! Its is a real issue. The alternatives you are talking about are 

1) Using portable qtox, where there is no **indicator icon** & we need to manually check for updates and download it.

2) Method mentioned in your link. That is:
`sudo apt-get install git`
`git clone https://github.com/tux3/qTox.git ~/qTox`
`sudo apt-get install build-essential qt5-qmake qt5-default qttools5-dev-tools libqt5opengl5-dev libqt5svg5-dev libopenal-dev libxss-dev qrencode libqrencode-dev libavutil-dev libswresample-dev libavcodec-dev libswscale-dev libavfilter-dev libavdevice-dev libglib2.0-dev libgdk-pixbuf2.0-dev libgtk2.0-dev libsqlcipher-dev`
`sudo apt-get install libtool autotools-dev automake checkinstall check \
libopus-dev libvpx-dev libsodium-dev`
`./bootstrap.sh`  
 Etc....

Tell me which is easier ?? 

`wget -q -O - https://pkg.tox.chat/debian/pkg.gpg.key | sudo apt-key add -`
`sudo add-apt-repository "deb https://pkg.tox.chat/debian nightly release"`
`sudo apt-get install qtox-unity`

OR 

[This whole 1 hour process](https://github.com/tux3/qTox/blob/deeb9b2308290e0404198a38a5d4c456ac39b328/INSTALL.md#community-builds) ??

Providing an official repository would help a lot of users in installing qtox.

**Comment by zetok** [comment]
@severustux 

> [This whole 1 hour process](https://github.com/tux3/qTox/blob/deeb9b2308290e0404198a38a5d4c456ac39b328/INSTALL.md#community-builds) ??

Have you **actually read** thing you're linking to?

**Comment by ghost** [comment]
Not the downloading portable qtox and running in single double click

Below it

**Comment by ghost** [comment]
I just want to say its a **working** but _**not a better**_ alternative

**Comment by zetok** [comment]
Here you go, read this part:

![zoom](https://cloud.githubusercontent.com/assets/3148759/15183441/fa0c2754-1788-11e6-8f15-e9ba3ccb6aa3.png)

**Comment by ghost** [comment]
This is always a third party repository, 

"The owner of the key may distribute updates, packages and repositories that your system will trust"

and also:
![screenshot from 2016-05-11 19-38-16](https://cloud.githubusercontent.com/assets/16937765/15183726/0303f838-17b0-11e6-9641-fcee508a9ece.png)

**Comment by zetok** [comment]
Have you followed instructions about adding the key?

**Comment by ghost** [comment]
I **did** add the key
You try once

**Comment by ghost** [comment]
@zetok, Wait, I'm not sure that I fully understand, is qTox not going to be made available to download through the official Tox repository? If so, then that's going to annoy people a lot if they have to manually upgrade it every day, if qTox is supported by the package manager you should really be using it if you don't have a built-in update system.

I mean, maybe I am misunderstanding this, but if you are not making it available in the official repositories for Xenial then that's just removing useful functionality, and for what reason? You seem to be suggesting the use of a non-official third-party repository, but I don't really see the point in this either (and could be a security risk), is this just a temporary solution until qTox is made available in the official Tox repository? I guess that would be fine, but will qTox go into the proper repositories at some point? And you just short of people who can build it for the official one or something?

**Comment by ghost** [comment]
Simple issue : The **official xenial** qtox repository is empty
Simple **solution** _(not alternative)_ : Please update the repositories and maintain.

Thats all!!

**Comment by ghost** [comment]
@severustux, Well, from my understanding of it either the developers are so extremely busy that they don't have the time to build the Xenial ones, or have just gone completely mad... Maybe a bit of both, anyway, if they do force the use of community builds and no longer put qTox in the official repositories for some silly reason I will seriously consider moving to a different Tox client.

I mean, if they don't have enough builders then they should just ask people to come in and help, even I would be happy to do it for them if they just don't have enough people... But just dropping all this support in favour of the easy option for them isn't really acceptable in my opinion.

I mean, maybe I have misunderstood something and am overreacting, but this isn't all sounding good...

**Comment by clnetbox** [comment]
@zetok : some clarification - here is how users are advised to install qtox when they visit the tox website https://tox.chat/download.html#gnulinux ->

![qtox](https://cloud.githubusercontent.com/assets/18641531/15185116/1b5cefb0-1798-11e6-9cf4-e9ba2ad218a2.png)

Then happens what I described (see my comments above) -> Unable to locate package qtox ... so the main problem seems to be the maintaining of the repositories. As it worked before in wily, it should be possible to get it working in xenial too, right ? :)

**Comment by zetok** [comment]
@SeventhSonOfASeventhSon 

> @zetok, Wait, I'm not sure that I fully understand, is qTox not going to be made available to download through the official Tox repository?

If you have a problem with what _Tox repo_ has or doesn't have, I'd suggest to open an issue on repo for it. qTox repo is not the one.

> If so, then that's going to annoy people a lot if they have to manually upgrade it every day, if qTox is supported by the package manager you should really be using it if you don't have a built-in update system.

Anyone who insists on using OS that makes it overly hard to get software can use community builds. If for some stupid reason they decide that they don't want to do that, that's their problem.

> I mean, maybe I am misunderstanding this, but if you are not making it available in the official repositories for Xenial then that's just removing useful functionality, and for what reason?

Those are Tox "official" repos. And please, don't make me look like I'm associated with that shit.

> I mean, if they don't have enough builders then they should just ask people to come in and help, even I would be happy to do it for them if they just don't have enough people... But just dropping all this support in favour of the easy option for them isn't really acceptable in my opinion.

Lol. Not with their attitude. Unless you're interested in doing the work, and then being thrown out.

Feel free to read:
https://lists.tox.chat/pipermail/general/2016-May/000073.html

@clnetbox
That's a problem with tox.chat – there's a repo to report problems with it: https://github.com/Tox/tox.chat

**Comment by zetok** [comment]
@severustux 

> I did add the key
> You try once

Seems to work for me just fine on Debian 8 – are you sure that it's not a problem with your system?

Edit: can someone else reproduce?

**Comment by ghost** [comment]
@zetok, Well, if you are going to move in this direction, I think that you should at least provide automated updates through the interface of qTox for all OSs like is done on Windows.

**Comment by ulrichard** [comment]
Why not provide a package for the official debian repo? Then it will be merged to ubuntu automatically. And nobody would have to add 3rd party repos and keys.

**Comment by zetok** [comment]
@ulrichard gist of it: https://github.com/qTox/qtox-irc-logs/blob/4af3db8f369e17ba6d28a266628af71894a0661d/2016/07/%23qtox_20160710.log.txt#L51,L58

**Comment by StSav012** [comment]
@abbat, why have you removed the repo?

**Comment by anthonybilinski** [comment]
@StSav012 see https://github.com/qTox/qTox/issues/4816. The repo had not been updated for many months, we're currently bringing it back online to be maintained under the qTox org.

**Comment by ghost** [comment]
Why not use flatpak and release once for all Linux distros?

https://flatpak.org/

Has automatic updates just like repos provide, is integrated with new distros including Mint 18.3, Fedora, and others...sounds like the perfect solution to this mess!

Could even host qtox on flathub: https://flathub.org
