### ISSUE TITLE
filter_audio is unmaintained 

### ISSUE THREAD

**Issue by ShalokShalom** [qTox/qTox#3194]
hi there, i am very new to this project, so understand my naivety.

filter_audio aka libfilteraudio seems to be unmaintained and grayhatter means, 
that it requires your audio card delay be EXACTLY the same as irungentoo's

Is it still the default and only one way for qtox?

**Comment by antis81** [comment]
Hey @ShalokShalom, welcome to the project. Do I understand you right, that you like to contribute and look for a topic to start with? The [HowTo contribute](https://github.com/tux3/qTox/blob/master/CONTRIBUTING.md) is a good place to start.

The filter_audio library caused quite some trouble to users and now is deactivated (like deprecated) in qTox by default. Yet the reference is still there and there are probably some leftover artefacts in the code. We still need to improve overall audio quality and there's a lot of questions to clear concerning this.

Further, the audio API (OpenAL) we currently use is outdated and not suits our requirements well, which are:
- "Real-Time" capture and transmit of audio data (p2p phone & video chat)
- The same with multiple participants (group chats -> i.e. conference broadcast calls with some push-to-talk mechanism).
- Filter silence and noise to optimize data transfer.

There's two alternatives to OpenAL we discussed so far, which is PortAudio and RTAudio, where the latter seems to provide the more matured API (just had a look at that yesterday). Unlike OpenAL, both libs focus on audio capture & playback without abilities to setup a 3D sound environment. This would be a neat additional feature to actually virtualize a conference room like environment in group chats. But, one step at a time… :)

**Comment by alexeysvrv** [comment]
@antis81 I propose to use instead OpenAl - Speex. This codec was developed by the GNU Projects. It uses the free license and provides high sound quality speech. It is specifically optimized for voice transmission. https://en.wikipedia.org/wiki/Speex

**Comment by antis81** [comment]
@alexeysvrv Speex homepage refers to the Opus codec - which is actually already linked in qTox. The codec itself cannot replace OpenAL, as it doesn't handle audio devices. Similar to filter_audio it solely operates on the data buffers. This points to the right direction anyway, because in conjunction with RtAudio, it looks like an excellent deal.

**Comment by alexeysvrv** [comment]
@antis81 RTAudio- proprietary technology. This is not a free alternative to OpenAL. It has created a Microsoft

**Comment by alexeysvrv** [comment]
@antis81 What are the other options?

**Comment by antis81** [comment]
> RTAudio- proprietary technology.

Looks like there's two similar libs. What I'm talking about is [RtAudio](https://www.music.mcgill.ca/~gary/rtaudio/) and it is not a codec, but an API for managing and streaming to audio devices. This is completely open source with an MIT derivative (you find source and license linked on their website). The codec OTOH is required, to be able to process audio buffers (compression, echo compensation, etc.). The Opus codec seems to fulfil our requirements well. Thus, the two make just the right combination.

**Comment by alexeysvrv** [comment]
@antis81 I understood. Thank you for the explanation) When to start implementing?
