### ISSUE TITLE
What's the difference between this and uTox?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3195]
https://github.com/GrayHatter/uTox

**Comment by ghost** [comment]
BTW, qTox is running nice here, compared to https://github.com/GrayHatter/uTox/issues/259 - no offense.
I just hope qTox doesn't make suspicios connection(sorry but I'm paranoid :-) ).

**Comment by zetok** [comment]
The general difference is that qTox is simply better.
From top to bottom, starting from UX, features, etc for user, and ending on maintainers for developers :)

**Comment by nurupo** [comment]
@verycrypt https://wiki.tox.chat/clients#features

**Comment by tux3** [comment]
uTox generally tries to be more lightweight, while we try to be more full-featured and configurable. 
You should try both and see whichever you like most.
