### ISSUE TITLE
Add an option to disable logging.

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3196]
##### Brief Description

OS: Windows 7
qTox version: v1.4.0-2-g24a7f4d
Commit hash:  (isn't this hash value a privacy?)
toxcore:  0.0.0
Qt:  5.5.1
Hardware:  ?
…

Reproducible: Always
##### Steps to reproduce
1. Launch qTox.
##### Observed Behavior

qTox start writing many lines to "qTox.log".
##### Expected Behavior

qTox doesn't write anything.

Let the user disable logging by adding another setting to settings.
Advanced -> [X] Enable Logging (when turned off, never create/write logs)

---

**Comment by zetok** [comment]
> Commit hash: (isn't this hash value a privacy?)

No.

> Add an option to disable logging.

What is the use case?

**Comment by ghost** [comment]
> What is the use case?

Writing any log to the disk(not memory) is bad for security and privacy.
"Debug log" is useful only for developers, not for normal users.
If I need support/want to help, I will enable debug log to know what's going on.
There's no reason to enable logging as a default.
Am I clear?

> Commit hash: No.

So, what's your hash? (just to make sure you're using same as mine)

**Comment by ghost** [comment]
Another example: if I moved my qTox to USB disk, I want qTox to write less.
(USB stick has limited read/write counts)

**Comment by zetok** [comment]
> So, what's your hash? (just to make sure you're using same as mine)

Here you go: https://github.com/tux3/qTox/commits/master ← on the right

> Writing any log to the disk(not memory) is bad for security and privacy.

If you care about stuff like that, you wouldn't use windows in the first place, and on top of that you'd configure your system to allow writes only to tmpfs, with other partitions mounted RO. Furthermore, you'd use FDE. Just in case.

I'm asking about the actual reasons, not some keywords.

> Another example: if I moved my qTox to USB disk, I want qTox to write less.

And that would be a valid reason. Not really good enough, given that one could configure things to mount `~/.cache` / `$HOME` directory as tmpfs, which would result in 0 writes to your persistent memory, regardless of whether that would be from qTox, or other software. And it's not qTox's job to do that.

Also, given the great durability & ~low cost of pendrives these days, it's not a real issue even when there is a bit of writes from qTox.

# 

So far, 1 weak use case, which is solved by using other tools, available on any Linux distro. If your OS doesn't support that, I'd suggest to get some better OS.

And if there is a good reason, I would like to hear about it :)

# 

On a side note..

> "Debug log" is useful only for developers, not for normal users.

Everyone can become a "developer" :)
And you don't even really need to be one anyway to be able to use/understand logs.

**Comment by ghost** [comment]
Ok... I know Linux is great and I'm also a developer. So I understand your arguments.
However, I still don't get why you don't just "add a simple checkbox", and "let user to control logging level".

Is there any specific reason why you don't want to do this?

**Comment by ghost** [comment]
For example, "Tor" can set a logging level on user side.

> Log minSeverity[-maxSeverity] stderr|stdout|syslog

usage:
Log debug file /path/to/log.txt
Log warn file /path/to/log2.txt

Also:

> AvoidDiskWrites 0|1
> If non-zero, try to write to disk less frequently than we would otherwise.
> This is useful when running on flash memory or other media that support only a limited number of writes.

**Comment by ghost** [comment]
found this on "qtox.pro" file:

> DEFINES += TIMESTAMP=$$TIMESTAMP
> DEFINES += LOG_TO_FILE <------
> DEFINES += QT_MESSAGELOGCONTEXT

yes, qTox's logging system is "hardcoded"...

```
Line 48: #ifdef LOG_TO_FILE
Line 85: #ifdef LOG_TO_FILE
Line 159: #ifdef LOG_TO_FILE
Line 300: #ifdef LOG_TO_FILE
```

If Logging is already hardcoded, what's the point if "ifdef"?

**Comment by zetok** [comment]
> Is there any specific reason why you don't want to do this?

Yes, there are already too many options in settings. All of them "necessary". With more options, UX gets worse. → #1069

With that in mind, this option proposal doesn't provide rationale good enough to worsen UX.

**Comment by SkyzohKey** [comment]
@zetok 

> With more options, UX gets worse.

I absolutly disagree with that. Giving the user ability to configure an app the way they want it to be permits to give it more liberty about how it'll use that app. qTox doesn't have too many options in settings, your settings view is simply badly designed.

Take a look at how I designed the `Interface` tab for Ricin, their is ~many options but the UI doesn't looks cluttered.
![](http://i.imgur.com/kjEF8sW.png)

> just "add a simple checkbox", and "let user to control logging level".

Note that this would take only 5 lines of code and would permits users to not have undesirable files written on their disk. Same thing for useless `.ini` files that qTox create for every profiles, even if you never used them with qTox. An average user could see this as a privacy intrusion.

**Comment by zetok** [comment]
> (…) your settings view is simply badly designed.

Can't argue with that :D

Now, if there is someone interested in improving it – by all means, please do so. Until then, I'm opting for not making mess worse than it already is, unless there's a good reason to do so.

> Same thing for useless `.ini` files that qTox create for every profiles, even if you never used them with qTox.

`.ini` are used.

> An average user could see this as a privacy intrusion.

Sure. Average user might be terrified at the idea that Tox doesn't encrypt their IP.

**Comment by SkyzohKey** [comment]
Nah, what I mean is that when you have multiple profiles, loading 1 in qTox will result in qTox creating a .ini for each profiles availables. And this is bad.

**Comment by zetok** [comment]
> Nah, what I mean is that when you have multiple profiles, loading 1 in qTox will result in qTox creating a .ini for each profiles availables. And this is bad.

Make an issue, instead of hijacking this one. :)

**Comment by ghost** [comment]
Look, let's just stay calm. I don't want to start a flame war here.

> Average user might be terrified at the idea that Tox doesn't encrypt their IP.

That's why I use Tox with Tor. DHT Network did not hide original IP, it's torrent technology and I know that.

**Comment by SkyzohKey** [comment]
> That's why I use Tox with Tor. DHT Network did not hide original IP, it's torrent technology and I know that.

The Tox DHT hides your IP from peoples you didn't accepted as friends, once you accept someone it can probably grab your IP (even if their is no tool for all these skid that uses "Skype resolvers"). So, if you only accept people that you trust, their is no risks.

**Comment by ZIEXED** [comment]
@zetok  I saw many stupid comments, but yours is diffrent in many levels... if you know what I mean

**Comment by zetok** [comment]
@ZIEXED not really, care to elaborate?

If you disagree with my point that it's not qTox's job to do it – I'd like to hear about that.

Note that log shouldn't contain any sensitive info – nothing that an "attacker" wouldn't know already if they had an access to the FS. The primary thing that an option for disabling it would actually achieve, is making things harder for the developer.

**Comment by ZIEXED** [comment]
There are many reasons to disable logging and the most important of them is ME
I don't want it so I should be able to disable it
That's enough reason
I don't need any GARBAGE on my HD
https://msdn.microsoft.com/en-us/library/windows/desktop/dd371723%28v=vs.85%29.aspx

> I'd suggest to get some better OS.

Don't make another stupid comment.

**Comment by zetok** [comment]
Needed info not provided for over a month, thus closing.
