### ISSUE TITLE
GUI: Split Window in 2 windows.

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3197]
##### Brief Description

OS: Windows 8.1
qTox version: v1.4.0-2-g24a7f4d
Commit hash:  -
toxcore:  0.0.0
Qt:  5.5.1
…

Reproducible: Always
##### Steps to reproduce
1. Run qTox.
##### Observed Behavior

qTox's GUI is always one big screen.
##### Expected Behavior

Split this window into 1-2.

One(main):
Left side. Only show friends list.

Second(sub-window, sometime appear):
For Settings, chat window.

Have you ever tried "Pidgin"? Yes, I want you to split qTox's window like Pidgin.

**Comment by zetok** [comment]
[Already ~possible](https://github.com/tux3/qTox/blob/24a7f4d51960a73cb7234cec9a4a2811e9175c6c/doc/user_manual_en.md#chat), thus closing.

**Comment by ghost** [comment]
Damn... my bad XD

> Multiple windows mode: If enabled, the qTox user interface will be split into multiple independent windows. For details see Multi Window Mode.
