### ISSUE TITLE
Current qTox version should be displayed along side other version numbers in About section

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3200]
In the About section the version number for toxcore and Qt is given, however the version number for qTox itself can only seemingly be found when asking one's package manager what it is (or however you find out on your system), but I think that it would be rather useful if the version number of the package was also given in the About section.

So for the version we have now it would say `qTox version: 1.4.0-2-g24a7f4d-1`.

This is what it currently says for me:

![qtox_version_information](https://cloud.githubusercontent.com/assets/11575271/14788626/b0a1782e-0b00-11e6-9dff-4566b1418913.png)

**Comment by zetok** [comment]
That's an issue with packages from tox.chat – if you'd compile yourself, it would just work™:
![version works](https://cloud.githubusercontent.com/assets/3148759/14788408/990ea1f6-0aff-11e6-92f3-626ab5da5351.png)

**Comment by zetok** [comment]
https://github.com/tux3/qTox/blob/deeb9b2308290e0404198a38a5d4c456ac39b328/INSTALL.md#community-builds ← could you check if it works for you?

**Comment by zetok** [comment]
Community builds aren't affected, thus closing.
