### ISSUE TITLE
Let the user select notification sound.

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3206]
##### Brief Description

OS: Windows 8.1
qTox version: v1.4.0-2-g24a7f4d
Commit hash: 24a7f
toxcore: 0.0.0
Qt: 5.5.1
…

Reproducible: Always
##### Steps to reproduce
1. Receive a chat message from a friend.
##### Observed Behavior

The notification sound is too short and too small to caught my attention.
The volume is 100% of course.
##### Expected Behavior

Add the option to change notification sound.
For example, in Thunderbird:
[X] Play Sound
(_) Default notification sound
(O) Use this sound file: [ mysound.wav ][ Browse... ]

**Comment by zetok** [comment]
Related: #2440

**Comment by Diadlo** [comment]
Implemented

**Comment by Diadlo** [comment]
Seems, duplicate of #2639, so it will be closed. Please comment if it isn't
