### ISSUE TITLE
Friend's Tox ID is shortened when copied to clipboard

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3207]
##### Brief Description

OS: Windows 8.1
qTox version: v1.4.0-2-g24a7f4d
Commit hash:   24a7f
toxcore:  0.0.0
Qt:  5.5.1
…

Reproducible: Always
##### Steps to reproduce
1. In the main friends list, right-click friend and click "Show details".
2. Look at "Public key:" field.
3. Select Public key by clicking it, Press CTRL+A, Press CTRL+C.
4. Paste it to other place(such as notepad, mail,...)
##### Observed Behavior

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXY
##### Expected Behavior

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXYXXXXXXXXXXXX

**Comment by ProMcTagonist** [comment]
That's the public key, not the tox ID

**Comment by zetok** [comment]
#84, #235
