### ISSUE TITLE
Corrupted .tox profile file disables the ability to remove profile

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3209]
I have recently found that if I create a Tox profile and then I go into the actual ".tox" file and edit some of the data such as the name, the name is changed but as qTox doesn't seem to recognise the file when I log in and press the "Delete" button it claims to have deleted it, but it hasn't because when I go back to the login screen I am able to load that profile again.
Though I understand that this is something a user is not meant to do, and you could just say to people not to do it like it's not an upstream bug if you edit the code and make a bug. However this shows that if a Tox profile got corrupted qTox may not allow its removal through the GUI so there really should be something in place that means I can delete it through the GUI even if the entire ".tox" file has been replaced with something else.

I am running Ubuntu GNOME 15.10 with GNOME 3.18 and qTox version `1.4.0-14-g5045c46-1`.

**Comment by initramfs** [comment]
I've looked through the file delete code and it looks fine (paths check out too). Except for a missing delete directive for chat history, everything seems to check out. I would like to actually test this but I've been having a hard time "editing fields" in the .tox file (how are you editing it?) and getting it prompt an invalid profile. I'm happy to submit a PR that outlines some basic changes (check if the file was actually deleted, delete chat history, and so forth) but it'd be nice to fix this issue as well.

If possible, could you send a zipped dummy corrupted profile (.ini, .db and .tox) such that I can reliably get it to ask me to delete the profile?

**Comment by ghost** [comment]
@initramfs, If you just create a new Tox profile called "Testing", then once you have done so (and make sure that you leave it as an unencrypted one) edit the file (I use `vim` but most text editors should do) and change the value "Testing" wherever it is (should be one near the top of the file) to "Corrupted", then save the file and load it with the Tox GUI. Then try and delete it using the "Delete" button on the profile page in the Tox GUI.
It shouldn't be too hard to do...

**Comment by initramfs** [comment]
I've carried out the above procedure and found that:
1. Tox loads the new profile without issue (the name actually changes to "Corrupt" (or whatever value I changed it to)
2. The delete function works as intended, deleting the profile files as appropriate.
3. Tested on both v1.4.0 (19d3ca0) and the commit in question (5045c46)

Can you make sure that only one instance of tox is running and that tox has the appropriate write permissions to the file?

**Comment by ghost** [comment]
@initramfs, Yes, I can confirm both of these things. But for me no matter how many times I order it to delete, nothing happens, would you like me to perhaps include a screencast of exactly what I am doing so that we can just make sure that we are not doing anything different anywhere?

**Comment by initramfs** [comment]
Sure, that'd be helpful.

**Comment by ghost** [comment]
Strange... I am now no longer able to reproduce the issue... I will reopen though if I do manage to reproduce it... How strange...
