### ISSUE TITLE
Port the notification widget to qt5

### ISSUE THREAD

**Issue by ShalokShalom** [qTox/qTox#3210]
The current version of the qtox notification widget for our systrays use gtk2 and since qtox is an qt5 app itself, might a port to QSystemTrayIcon be senseful.

**Comment by ShalokShalom** [comment]
This here can help: https://github.com/CDrummond/cantata/blob/master/gui/trayitem.cpp

**Comment by zetok** [comment]
@ShalokShalom do you mean https://github.com/tux3/qTox/wiki/Tray-icon ?

**Comment by demmm** [comment]
There is no issue with a Qt only build/system tray support, all is working correct.  That this request was opened was my fault, didn't check fully.
Sorry for the noise.  Report can be closed.
