### ISSUE TITLE
Have option to make settings not global and to travel with Tox profile

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3211]
I have found that if I change the settings in qTox, export my profile, and then import it elsewhere the settings don't travel with the profile, but I think that there should be an option at least which means that settings are written to the qTox profile (though obviously only another installation of qTox would be able to import the settings) and one can set it so that the profiles have their own settings for all the things in the settings area so that the settings are not global.

I would at least like these things as options even if they are not enabled by default because there are certain settings which one would want to go with them wherever they go, but some might also not want the settings to be non-global, so I think that more customization should be enabled in this area.

**Comment by zetok** [comment]
Option is not going to happen.

Instead, #1656.

**Comment by ghost** [comment]
@zetok, Yes, that looks better... I just brought it up because I want to be able to have it so that I can export my settings or similar so that certain customizations I have made in the settings come with me, and if I have more than one person on my qTox installation, and they prefer different settings to me, it would be nice if they weren't all global.

**Comment by zetok** [comment]
Yes, that would be nice, but again, this shouldn't be an option.
