### ISSUE TITLE
Open a chat window if the user receive message.

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3212]
##### Brief Description

OS: Windows7
qTox version:v1.4.0-2-g24a7f4d
toxcore:  0.0.0
Qt:  5.5.1
…

Reproducible: Always
##### Steps to reproduce
1. In Settings, make sure you select "Multiple windows mode" and "Open each chat in an...".
2. Close all window. qTox in running only in right-bottom tray.
3. Send a message from friend to this PC.
##### Observed Behavior

qTox doesn't open chat Window.
##### Expected Behavior

qTox should open chat Window("Friend (Online) - MyName").
Pidgin and Yahoo Messenger open chat window when received a new message.

**Comment by zetok** [comment]
Do you have option set?
![option](https://cloud.githubusercontent.com/assets/3148759/14853919/6f0038c0-0c85-11e6-96b2-115c81e6c8e9.png)

**Comment by Chiitoo** [comment]
**zetok**,

Said option actually opens the main window, not the chat window (when using multiple windows-mode).

Been meaning to report that... but yeah.  ^^;

**Comment by ghost** [comment]
@zetok
yeah.

On new message:
[X] Play Sound
[X] Open window
- [_] Focus window

---

And please consider writing the actual text like me, instead of posting an image.
