### ISSUE TITLE
Add an option to clear window when closed/opened.

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3216]
##### Brief Description

OS: Windows 7
qTox version: v1.4.0-2-g24a7f4d.
Commit hash:  24a7f4d51960a73cb7234cec9a4a2811e9175c6c
toxcore:  0.0.0
Qt:  5.5.1
…

Reproducible: Always
##### Steps to reproduce
1. Use Tox for a few days. (A is on my friends list and I don't contact him yet)
2. Open my friend A by clicking "A" from the friends list.
##### Observed Behavior

A's chat window is filled by:
    A is offline
    A is now online
messages.
##### Expected Behavior

Don't show anything at all.

When I open a new chat window, I expect _nothing inside_(including recent chat log).
When I click "X" to close chat window, I expect all chats I talked was disappeared.
(I don't log anything, but qTox logs everything for you.)

If Tox is really secure messenger, this is important.
"Off the record". "Do not record anything". "Destroy after I or he close the conversation".

Also, "A is online/offline" is not important to me.
I can see current status on friends list (green dot or red dot).

**Comment by ghost** [comment]
"Faux offline messaging" checkbox is off 
because "offline message" = "someone keep my message" = insecure.

**Comment by Chiitoo** [comment]
**verycrypt**,

The status changes should be gone if the “Show contacts' status changes” option is disabled.

A note on “Faux offline messaging”: as far as I know, the “someone” keeping the messages is the local client, meaning the messages are only sent when both, the sender and receiver are on-line, and unless “Keep chat history” is enabled, they will be lost when terminating the client (though I haven't tested that in a while).

**Comment by zetok** [comment]
> If Tox is really secure messenger, this is important.

Please stop with the bullshit reasons. This has ~nothing to do with security.

Closing, since (like @Chiitoo pointed out) there is an option for it.
