### ISSUE TITLE
query for updates also every $time_period, not only when starting qTox

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3218]
Settings - General -
[X] Check for updates _on startup_.

"On startup only"? No daily update check?
If so, how about adding manual "Check Update" button in "Settings" - "about"?

Also, do you send any information to update server?
Would you pinpoint me to the source code?

---

(Other software's story)
1. http://bad.soft/updatecheck?username=anon&computername=wtf&macid=AA...
2. I sent an email to bad.soft, starting with "Hey, your software is sending too many identifiable info!"
3. Convinced them to give up spying. This took about 2 months.
4. Now the use http://bad.soft/updatecheck only. Simple as that.

**Comment by zetok** [comment]
Why would it be needed?

**Comment by SkyzohKey** [comment]
> Why would it be needed?

Out-of-date software can be dangerous. Also, update system should be better, something like OTA on Android. When a stable release is available, the build server would send some sort of notifications to all the qTox users, informing them that a new update is available, showing a changelog. Then user could simply update or keep the current version.

**Comment by zetok** [comment]
@SkyzohKey 

> Also, update system should be better, something like OTA on Android. When a stable release is available, the build server would send some sort of notifications to all the qTox users, informing them that a new update is available, showing a changelog. Then user could simply update or keep the current version.

AFAIK OTA on android doesn't work like that – device simply queries server for update every $time_period. Unless you mean the proprietary solution by google…

Current way doesn't differ in qTox much, except that instead of $time_period check for updates is performed every start.

I'm asking what benefits there are to checking for updates every $time_period instead of checking on start.

**Comment by SkyzohKey** [comment]
> I'm asking what benefits there are to checking for updates every $time_period instead of checking on start.

If like me you never close your client, then you never receive updates. :x

**Comment by ghost** [comment]
> what benefits there are to checking for updates every $time_period instead of checking on start.

Because I don't close qTox client.
Same as @SkyzohKey said, I want qTox to notify me when the new updates are available.

**Comment by zetok** [comment]
**Proposal**:
- query for updates also every $time_period, not only when starting qTox

**Comment by ghost** [comment]
Actually, not every $time_period.
It should be "$time_period + mt_rand(1,99999)" (random timer) to prevent watering hole attack.

And, the notification server should publish update details using GPG or something
so the client can verify who signed the document/files.

**Comment by sudden6** [comment]
Update mechanism was completely reworked, if it's still a problem please open a new issue.

**Comment by anthonybilinski** [comment]
The new update check, which simply links to the latest release if one exists, does check for update both on open and once per day, following the idea of this issue.
