### ISSUE TITLE
No way to unset avatars

### ISSUE THREAD

**Issue by JFreegman** [qTox/qTox#322]
When you call tox_set_avatar() with the format TOX_AVATAR_FORMAT_NONE it clears the avatar data in the core, and this should be paralleled in the client. However in qTox the avatar is not cleared. I tried this with Toxy and it behaved correctly.

**Comment by tux3** [comment]
Indeed, I totally forgot to handle that case!
Note that there is still no way to just straight up remove your own avatar in qTox because I'm honestly not convinced this is actually a thing that people want to do, but if others remove their avatar, it's a bug to keep displaying it.

**Comment by tux3** [comment]
I can't actually test if the bug is fixed, since I can't install Toxy, so if you can still reproduce please comment and I'll reopen.

**Comment by JFreegman** [comment]
I get a compile error now:

> core.cpp:463:19: error: ‘TOX_AVATARFORMAT_NONE’ was not declared in this scope if (format == TOX_AVATARFORMAT_NONE)

The define was recently changed to TOX_AVATAR_FORMAT_NONE. The fix does seem to work though.
