### ISSUE TITLE
About some translating

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3223]
I think I can help with translating, but https://github.com/tux3/qTox/wiki/Translating is hard to read.
I'm using Windows(I use Linux only for servers and nothing more).

In other project which is not hosted on github, I contributed to them by these steps:
1. Ask them for a single file.
2. They give a "single file" to me(e.g., "en_US.xml" "lang_1033.dll.source")
Other project example (language files are single, and can be opened by Notepadd++)

```
goodapp.exe
|-lang
|-------en_US.xml
|-------pt_BR.xml
```

en_US.xml example:
    APP_NAME(tab)Good App
    APP_TEXT_HELLO01(tab)Guten morgen!
1. I edit the file, and send it back.

**Comment by zetok** [comment]
Which language(s?) would you want to help with?

I've thought a bit about it, and I think that providing those files in an automated way would be possible (regenerating them on every push to master), provided that @tux3 would help.

**Comment by verycrypt** [comment]
> Which language(s?) would you want to help with?

I learned some Japanese while working with some people.
Japanese care their privacy very seriously, and translate (q|)Tox into it may gather some attention from them.

So, if you make the translation step simple(single file), I'll do it.

**Comment by verycrypt** [comment]
I also can translate Russian and German, but I'm not confident to translate them perfectly.

**Comment by zetok** [comment]
`日本語` is correct name, right?

Also, it should be located between `Nederlands` and `Norsk Bokmål`, right? (at least wikipedia does that):
![wikipedia sorting](https://cloud.githubusercontent.com/assets/3148759/14910378/a0533d5e-0de4-11e6-8a97-32ab9b2c2433.png)

To translate: [ja.zip](https://github.com/tux3/qTox/files/241919/ja.zip)

And yeah, it kinda does suck to add languages according to instructions on wiki.
(I've edited it to point to opening an issue requesting file to translate for now)

**Comment by ghost** [comment]
> 日本語 is correct name, right?

Yep.

> it should be located between Nederlands and Norsk Bokmål, right?

I don't think so; let's just call it "Japanese (Nihongo)" or "Japanese (日本語)".
And sort other languages in alphabetic order; I like a-z sorting.

e.g.,

Chinese ('add chinese word here')
Japanese (日本語)
Korean ('add korean language here')
Nederlands
Norsk Bokmal

And hey, got a ja.ts file.

> <message>
> <location filename="../src/widget/form/settings/avform.cpp" line="225"/>
> <source>%1p</source>
> <translation type="unfinished"></translation>
> </message>
> <message>
> <location filename="../src/widget/form/settings/avform.cpp" line="227"/>
> <location filename="../src/widget/form/settings/avform.cpp" line="231"/>
> <source>Default resolution</source>
> <translation type="unfinished"></translation>
> </message>

So all I have to do is:

> <translation type="unfinished"></translation>
> ---> <translation>%1p</translation>
> and
> <translation type="unfinished"></translation>
> ---> <translation>ウィンドウの解像度（既定値）</translation>

right? Please confirm so I can start this.

**Comment by verycrypt** [comment]
...damn github, stop editing my post.

before: translation type="unfinished" /translation
after: translation SOMETHING_GOES_HERE /translation

**Comment by verycrypt** [comment]
I found a possible duplicate; I'll continue translating them anyway, but just in case.
Line 105 and Line 194.

**Comment by zetok** [comment]
> %1p → %1p

Yep.

> Default resolution → ウィンドウの解像度（既定値）

I guess? Dunno, I don't know Japanese :)

You might also want to look at how it's done in other translations if you're not sure: https://github.com/tux3/qTox/blob/master/translations/de.ts

**Comment by verycrypt** [comment]
<context>
    <name>Android</name>
    <message>

Reached Line 398, and I found this.
Do you need this section? Because I read you're going to delete "Android codes" in other issue.

**Comment by verycrypt** [comment]
<context>
   <name>Android</name>
   <message>

Reached Line 398, and I found this.
Do you need this section? Because I read you're going to delete "Android codes" in other issue.

(skipping & continue.)

**Comment by ghost** [comment]
Actually, there more:
    Line 184:         <source>&lt;html&gt;&
    Line 194:         <source>&lt;html&gt;&l
    Line 389:         <source>&lt;html&gt;
    Line 2603:         <source>&lt;html&gt;&

and I've done it. Please merge it into your git.
https://gist.github.com/verycrypt/59ee564cb0341797c383541fccb0cd7f

Well, there's many duplicates, so chainging all texts to "define()" and eliminate duplicates
will speed up future translation.

**Comment by ghost** [comment]
oops. forgot to remove all 'type="unfinished"'. That's all.

**Comment by ghost** [comment]
@zetok thanks for merging, but I really forget to remove ' type="unfinished"'.
"blob/master/translations/de.ts" doesn't have it.
