### ISSUE TITLE
https://qtox-win.pkg.tox.chat is not available

### ISSUE THREAD

**Issue by soredake** [qTox/qTox#3225]

**Comment by zetok** [comment]
~~What are your default DNS providers?~~

~~Have you tried with different DNS provider? E.g. google's `8.8.8.8`, `8.8.4.4` ?~~

cc @zer0-one @nurupo

**Comment by zetok** [comment]
```
--- tox.chat ping statistics ---
41 packets transmitted, 0 received, 100% packet loss, time 40012ms
```

Oh well.

**Comment by nurupo** [comment]
@zetok ping is firewalled.

When @zero-one was transferring domain to @irungentoo a month ago, he accidentally wiped out all DNS records the domain had, so it might be the case that everyone forgot that there was qtox-win.pkg.tox.chat and no one restored the DNS record for it. Just tell @irungentoo to make qtox-win.pkg.tox.chat point to the IP you want. oranges should know the IP, as I think he is the one hosting tux3's update server, if I'm not mistaking.

**Comment by optimumtact** [comment]
45.79.166.124 

plus my apologies, as I had intended to bring this up with gentoo but forgot.

**Comment by optimumtact** [comment]
@zetok zero-one is no longer involved in the project in sysadmin or administrative related fashion by the way

**Comment by zetok** [comment]
@optimumtact 
![sure](https://cloud.githubusercontent.com/assets/3148759/14901198/274ab566-0d8c-11e6-86f2-d519ee2171ca.png)
Sure.

**Comment by nurupo** [comment]
@zetok

https://github.com/Tox/tox.chat/pull/100

Sure.

**Comment by irungentoo** [comment]
qtox-win.pkg.tox.chat is back

**Comment by zetok** [comment]
Thanks @irungentoo :)
