### ISSUE TITLE
RSA keys break text (name/date shouldn't word wrap)

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#323]
Went to send my ssh pubkey to someone over Tox and discovered this sort of thing occurs:

http://a.pomf.se/ysuciy.png

**Comment by tux3** [comment]
This looks like a regression, the name and date columns should never word wrap.

**Comment by dubslow** [comment]
@apprb

**Comment by apprb** [comment]
Time stamps have almost similar width, therefore for time stamps it has been fixed in #328 by fixing column width. For names I did the same thing, I know it is not perfect solution, but at least in the worst case names will be word wrapped in more good-looking way.
To be refixed tomorrow.

**Comment by dubslow** [comment]
I believe this can be closed
