### ISSUE TITLE
Running autoreconf -if... error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL

### ISSUE THREAD

**Issue by wisekaa03** [qTox/qTox#3235]
##### Brief Description

OS: Linux (fedora 23)  
##### Observed Behavior

...
~/qTox/libs/libtoxcore-latest ~/qTox
Running autoreconf -if...
configure.ac:292: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:293: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: /usr/bin/autoconf failed with exit status: 1
...
##### Expected Behavior

not compiling

**Comment by zetok** [comment]
Works for me, which makes it look like a problem with your system.

Also, if it's a bug, it would be a [toxcore](https://github.com/irungentoo/toxcore) issue.
