### ISSUE TITLE
qTox hangs with 100% CPU when the other side disconnects during the video call

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3237]
When I try to make a video call to an Android app Antox, Antox crashes and qTox freezes with 100% CPU and camera "on". Have to kill it to continue.

Abrupt shutdown of the remote peer shouldn't cause qTox to freeze.

qTox-1.4.0 on FreeBSD-10.3

**Comment by zetok** [comment]
> qTox freezes with 100% CPU and camera "on".

How long have you waited before killing it? Was it more than 5 min?

# 

Note: this most likely will be fixed by #3185 – you might want to test with this PR applied.
(`git fetch upstream pull/3185/head:3185 && git checkout 3185`)

**Comment by yurivict** [comment]
About 1 minute.

**Comment by zetok** [comment]
Should be fixed on newest qTox, thus closing.

If you still can reproduce, please comment for reopen.
