### ISSUE TITLE
[Feature] Local peer detection (semi-online network)

### ISSUE THREAD

**Issue by nakadashi** [qTox/qTox#3239]
Like "Bittorrent sync"[1], it will be nice if Tox have this option.
In the future, qTox works "without Internet".
If user check-on "local peer detection" checkbox, qTox will scan local network like Bittorrent does.
This will save the Internet bandwidth if the company decided to install qTox on all ther computers,
replacing Skype.

[internet]
|
|
|
[Firewall] <--- only allow packets from DMZ, dropping else
|
[DMZ Server] <--- install qTox
|
[HUB]
|
[Computers] <--- install qTox

ping @irungentoo

1 https://www.getsync.com/features

**Comment by zetok** [comment]
> In the future, qTox works "without Internet".

No. qTox is already supposed to work on intranet, thus closing. If it doesn't work, fill an issue against toxcore/qTox.
