### ISSUE TITLE
File transfer widget looks bad when file name is long

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#324]
![2014-09-10 qtox long messages not displayed correctly](https://cloud.githubusercontent.com/assets/3148759/4430710/b276bf32-4640-11e4-82fd-e7b17d64f525.png)

As a bonus, there's problem with timestamp (#323).

**Comment by dubslow** [comment]
also closeable

**Comment by zetok** [comment]
Still present on newest qTox when picture is received (3rd file transfer), also causes scroll bar to appear and "hide" timestamp:
![2014-10-01 steam borderlands 3 pucharse](https://cloud.githubusercontent.com/assets/3148759/4514853/1675276e-4b94-11e4-82e5-9459fe6541f3.png)

**Comment by apprb** [comment]
Problem from issue #372

**Comment by zetok** [comment]
Seems to be now fine, except for missing image miniature
