### ISSUE TITLE
Disable qtox.log - HOW?

### ISSUE THREAD

**Issue by nakadashi** [qTox/qTox#3240]
How can I stop "qtox.log" logging?
I'm no Linux, so linking it to /dev/null is not the answer

**Comment by nakadashi** [comment]
Close qTox, set it to read-only, start qTox does prevent logging, but it would be nice
if you just disable this logging. (and don't patch "read-only-counter" because I really hate loggin)

**Comment by zetok** [comment]
Duplicate of #3196, thus closing.
