### ISSUE TITLE
Don't link the domain name

### ISSUE THREAD

**Issue by JohnMkainne** [qTox/qTox#3242]
##### Brief Description

OS: Windows7
qTox version: v1.4.0-29-g08263e9.
toxcore:  0.0.0
Qt:  5.5.1
…

Reproducible: Always
##### Steps to reproduce
1. Open chat window.
2. Say "www.domain.com" without quotes
3. Say "check out www.usa.gov"
##### Observed Behavior

qTox put a underline into it automatically.
Recepient will also see underline - aka hyperlink.
##### Expected Behavior

Don't link www.domain.com. Honor "Text formatting" setting.
"Plaintext" is just TEXT, not hyperlink.

**Comment by zetok** [comment]
Markdown setting is supposed to only affect which characters are, or are not displayed, and whether to use ~markdown. Setting probably should be renamed from `Plaintext` (since it apparently causes confusion) to `No Markdown`.

What is the use-case for not having links?

**Comment by JohnMkainne** [comment]
1. I use plaintext because I just want to trasfer pure TEXT, not MODIFIED text.
2. Clicking by mistake will open a browser on some PCs. And I want to prevent it.

If it's a 'no markdown', why not add 'plaintext'? Pretty plz?

**Comment by zetok** [comment]
> I use plaintext because I just want to trasfer pure TEXT, not MODIFIED text.

Links don't modify text.

> Clicking by mistake will open a browser on some PCs. And I want to prevent it.

Preventing one from clicking & opening a link is not qTox's job – it works as expected.

> If it's a 'no markdown', why not add 'plaintext'? Pretty plz?

Disabling markdown formatting allows to have unformatted text, which can increase readability. There's no reason good enough to add option to disable detecting links.

**Comment by Chiitoo** [comment]
I, for one, would like an option that would disable parsing URLs, but I don't really have a strong reasoning for it...  I do somewhat often copy only a part of an URL, or I just want to copy it, which can currently be a bit tricky (there is at least one issue open (#2891) that touches upon copying URLs).

Then again, I'm very much a supporter of more options (I know many are against them).  ^^;

As an example about “plaintext” and URLs, Thunderbird does parse links as well, even when displaying a message body in plain text, so linking it in with that option probably wouldn't be entirely appropriate.

**Comment by ghost** [comment]
> There's no reason good enough to add option to disable detecting links.

Ok, so how about adding this option then?

[v] When link is clicked, copy it instead of opening a browser.

(I prefer copying URLs rather than click it directly)

**Comment by zetok** [comment]
> [v] When link is clicked, copy it instead of opening a browser.

#1236

**Comment by ghost** [comment]
I'm using "Tor Browser". When I click the URL link, I expect qTox to open a link with TBB.
Or, "when I left-click it, copy the URL string to clipboard", so I can paste it to TBB.

**Comment by SkyzohKey** [comment]
Plain text should **NEVER** parse chat messages, only display what was received/send, nothing less nothing more. That's probably the definition of plain text.

**Comment by ProMcTagonist** [comment]
@qasmoke 

> I'm using "Tor Browser". When I click the URL link, I expect qTox to open a link with TBB.

If this isn't happening, your operating system is misconfigured.

**Comment by ghost** [comment]
@ProMcTagonist
have you ever used TBB? Because I can't set TBB as default.
about:preferences --> Make default button

**Comment by ProMcTagonist** [comment]
@qasmoke this isn't the issue tracker for TBB or your OS settings manager

**Comment by zetok** [comment]
Needed info not provided for over a month, thus closing.
