### ISSUE TITLE
checkbox to "Don't collect user chat log"

### ISSUE THREAD

**Issue by JohnMkainne** [qTox/qTox#3243]
##### Brief Description

OS: Windows 8
qTox version: v1.4.0-29-g08263e9.
Qt:  5.5.1
…

Reproducible: Always
##### Steps to reproduce
1. Left click friend in contact list
2. Click "show details"
##### Observed Behavior

N/A
##### Expected Behavior

Add [X] Never record any history" to disable chat history completely
to protect privacy and prying eyes.
Your Tox messenger does not support OTR aka Off the record messaging
and this is critical for privacy.

**Comment by zetok** [comment]
Already supported, thus closing.
