### ISSUE TITLE
Copyable string to describe details!

### ISSUE THREAD

**Issue by JohnMkainne** [qTox/qTox#3244]
OS: Windows / OS X / Linux (include version and/or distro)  
qTox version: (version numbers in menu `Settings → About`)  
Commit hash:  
toxcore:  
Qt:  

Just merge them to string like HTTP Useragent like this.

---
## Windows7-32/qTvv1.4.0-29-g08263e9./0cc63e9cc45e543eacc0b16ac4fefc7963baf7cc/toxcore_0.0.0/QtV5.5.1

and put it to textarea box so the lazy user can copy and paste it

**Comment by zetok** [comment]
Is there a use-case for copying manually, instead of using automatically generated link with that info?

**Comment by JohnMkainne** [comment]
I disabled link-to-open associate settings for security.

e.g.,
Start > Run > "http://nsa.gov/"
open NSA website using browser (bad for security because any app can open http:// or https:// without consent)
doesn't open anything; some app will show "can't open link warning" (good for security)

**Comment by zetok** [comment]
> I disabled link-to-open associate settings for security.

And?

![copy link](https://cloud.githubusercontent.com/assets/3148759/14959096/a81d2358-1085-11e6-860e-354707df98ee.png)

**Comment by zetok** [comment]
Needed info not provided for over a month, thus closing.
