### ISSUE TITLE
Built-in update mechanism for qTox installed on OSs which do not have a currently supported package manager

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3247]
I believe that there should be a built-in update mechanism in qTox which will:
- Allow it to check for new updates to qTox
- Allow it to download (either automatically or at user request - there could be options to configure this) new updates and verify their integrity and authenticity probably via the means of checking that they were signed by the correct authorised person
- Allow it to install new updates

I don't think that this would be too hard to do and would either be not shipped in or disabled if it was installed on a system through the package manager which is a supported package manager which will keep it up-to-date.
This would be useful for those that run OSs which either do not have a package manager or ones running a package manager which is not supported by qTox yet so that they don't have to keep manually updating.

**Comment by tux3** [comment]
The good news is that we already have a working update mechanism, currently in use on Windows. 
"All" that's needed to make it work on other platforms is 1) Create new stable builds for that platform 2) Add the builds on an update server 3) Add the new signing key/update server to qTox.

We don't currently try to detect package managers, but what could be done instead is allow packagers to not compile the updater at all, so it wouldn't be an option if you install from your package manager.

**Comment by ghost** [comment]
@tux3:

> We don't currently try to detect package managers, but what could be done instead is allow packagers to not compile the updater at all, so it wouldn't be an option if you install from your package manager.

Yes, something like that would be good.

**Comment by tux3** [comment]
@SeventhSonOfASeventhSon Is there a specific platform you had in mind for the updates? Linux? Mac? BSD?

**Comment by zetok** [comment]
osx → could make some use
FreeBSD → packaged
Linux → packaged

**Comment by ghost** [comment]
@tux3, Well, in my specific case I have a friend running Fedora who has great hassle manually upgrading his qTox due to issues with compiling it from source. I also have a Mac in the house that I would like to load qTox on, but I don't like the fact that I have to keep on manually compiling it from source there and a built-in update system would be much better.

A lot of my friends actually running qTox are running Linux distros such as Fedora and Kali and simply don't run very up-to-date versions of qTox due to the fact that they don't want to manually compile from source almost every day.

**Comment by zetok** [comment]
There are repos for Fedora: https://github.com/tux3/qTox/blob/master/INSTALL.md#community-builds

**Comment by tux3** [comment]
Auto-updates for linux would be fairly easy, but as zetok said there are repos for most distros so that would probably be easier.
For OS X we sadly still lack a build machine, so we have no way to produce builds for the update server.

**Comment by ghost** [comment]
As you no longer provide the repos with qTox updates, this built-in updates mechanism is needed more than ever for Linux. To make the updates easier anyway.

**Comment by sudden6** [comment]
We switched to an update notifier system, where you are notified for new updates but have to download and install manually, so this should no longer be an issue.
