### ISSUE TITLE
[Regression] Unable to pause file transfer

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#325]
I'm not sure what causes it, but from time to time I'm not able to pause file transfer.
![2014-09-10 qtox long messages not displayed correctly](https://cloud.githubusercontent.com/assets/3148759/4430728/d61f9066-4641-11e4-8e36-5f5ba8d19443.png)

**Comment by tux3** [comment]
Isn't that supposed to happen when the person at the other end pause it ?

**Comment by zetok** [comment]
I'm pretty sure that audiobot didn't pause file transfer

**Comment by dubslow** [comment]
@apprb

**Comment by apprb** [comment]
I'll try to reproduce it tomorrow. But between qTox and qTox and qTox and uTox file transfer works pretty well (except resume broken, which still isn't implemented).

**Comment by dubslow** [comment]
I just ran into this, it seemed to only affect outgoing transfers.

**Comment by dubslow** [comment]
GUI issue fixed by new chatform, comment for reopen
