### ISSUE TITLE
Stable branch should be fast-forwarded to v1.4.0

### ISSUE THREAD

**Issue by initramfs** [qTox/qTox#3250]
##### Brief Description

Given that v1.4.0 releases have already been tagged, packaged and released, the stable branch should be fast-forwarded to the commit specified by the `v1.4.0` tag.
##### Observed Behavior

The head of the stable branch is current at tag `v1.3.0`.
##### Expected Behavior

The head should be fast-forwarded to tag `v1.4.0`.

**Comment by zetok** [comment]
@tux3 yesterday bumped version to `1.4`.

If updates still don't include `1.4` that would be a bug in the updater.

**Comment by initramfs** [comment]
Oh wow, my bad... My browser somehow cached the old `v1.3.0` page on GitHub... Closing issue.
