### ISSUE TITLE
Can't use Group Calls...

### ISSUE THREAD

**Issue by Rodabaugh** [qTox/qTox#3251]
##### Brief Description

OS: Linux Mint Mate x64
qTox version: v1.4.0-37-g4432ab6.
Commit hash:  4432ab6398aa4c9cdc222cf46170b820b9e33fa0
toxcore:  0.0.0
Qt:  5.5.1
Hardware: My laptop has a Intel Core i7-4700MQ CPU @ 2.40Ghz, a Nvidia GeForce GT 745M with 2GB memory, an Intel HD Graphics 460, 8GB RAM, and a 1TB HDD.
…

Reproducible: Always
##### Steps to reproduce
1. Call Group.
2. Tox Freezes.
3. Tox Crashes.
##### Observed Behavior

I can't make group calls. 

I could not find a log located in `~/.config/Tox/qTox/`... I did not have that folder. I do have a '`/.config/tox' folder, but no qTox folder, or any logs.
##### Extra

My friend is on Windows 8.1, and could not call the group at all. He said the call button was grayed out.

**Comment by zetok** [comment]
> I could not find a log located in `~/.config/Tox/qTox/`

It's actually `~/.cache/Tox/qTox/`

**Comment by Rodabaugh** [comment]
[qtox.txt](https://github.com/tux3/qTox/files/249890/qtox.txt)
After some more testing, it did not crash for me. It just won't work for my friend. I will have him submit a report as well. Here is my log file.

**Comment by Rodabaugh** [comment]
Here is my friend's issue report: https://github.com/tux3/qTox/issues/3254

**Comment by antis81** [comment]
@ErikRoda Your friend's qTox version is 1.3, which doesn't support group calls. Please upgrade to 1.4.

**Comment by antis81** [comment]
Closing this one, as the valid report is #3254.
