### ISSUE TITLE
32bit ONLY(!) qTox crashes and reverts after update to 1.4.0 (from 1.3.0 or 1.4.0 (yep..))

### ISSUE THREAD

**Issue by LittleVulpix** [qTox/qTox#3255]
##### Brief Description

OS: Windows 7 x64 / 10 x64 / 7 x86 / 10 x86 (all same behavior)
qTox version: 1.3.0 / 1.4.0, both 32bit!
Commit hash:  1.3.0 - b69042ec407c30b27ce3e56bb6daf14300facc8e / 1.4.0 - whatever is on the tox.chat download right now

Reproducible: Always
##### Steps to reproduce
1. Start qTox
2. Accept upgrade prompt
3. Restart qtox
##### Observed Behavior

Qtox starts updating, crashes and next launch it's in version it was in before
##### Expected Behavior

Qtox updates properly
##### Additional Info

![Imgur](http://i.imgur.com/x0LrpYB.gif)

**Comment by LittleVulpix** [comment]
I checked - it doesn't happen with 64bit qtox. It happens with 32bit qtox on 32bit system or 32bit qtox on 64bit (windows)system.

**Comment by tux3** [comment]
@LittleVulpix 
It seems like the updater didn't give a UAC prompt when you launched it, did you change the UAC settings on your system?
If the updater ran without admin privileges, then it would probably have gotten UAC-virtualised, which would explain why qTox can't see the updater's changes, and why there's a crash message saying "Program Files" instead of "Program Files (x86)" and not finding the pre-update files...

Do you see a qTox folder in "%LOCALAPPDATA%\VirtualStore\Program Files\", and does it contain qTox files ?

**Comment by LittleVulpix** [comment]
@tux3 , this happened on windows 7 with UAC turned off. Unlike w8/10, w7 actually does turn UAC off completely.

The recording of the error was done by me on windows 10 x86 where no program files (x86) folder exists (my bad, I forgot to update the description of the bug..), also with UAC turned off - but to top it off I also tried to set admin rights to just about all the executables there to rule that out. It was just to check whether this is bound to the platform of the OS or to that of the installer - and it seems it is the installer. 64bit qtox updates just fine on 64bit system. 32bit qtox fails on any system

**Comment by LittleVulpix** [comment]
See below on w7 x86 with UAC off.

![Imgur](http://i.imgur.com/vwZnxwY.gif)

**Comment by LittleVulpix** [comment]
Alright, so for some reason, when trying to make a webm capture, I found out I am unable to reproduce it on w7. It just won't happen anymore. It makes no sense because I used a VM and I had a snapshot, so nothing changed on my side. Apparently only some translation came out which shouldn't fix anything.

On W10, it still happens. UAC ON / OFF, doesn't matter. But, if I let qtox download the update and then run qtox-updater manually, it updates and works as expected. I wanted to see if it would work if I set qtox-updater to run as admin all the time, but I found out that the updater does not have compatibility options, i.e. I can't set it to run as admin. I used the trick with the compatibility troubleshooter but - if it worked - the updater still failed with the same error if I run qtox normally after the update is downloaded.

So... not sure what's going on. I'll have to try my father's W7 where the issue came from to see if he still has it or if it's fixed for him too.

**Comment by tux3** [comment]
This turns out to be a path issue, qTox starts the updater in its current working directory, instead of using its module path, this causes the updater to install files in the wrong place if qTox's working directory is not the module path, which can happen with desktop shortcuts.
