### ISSUE TITLE
Notifications in Multiple windows mode

### ISSUE THREAD

**Issue by gabrielcramer** [qTox/qTox#3261]
##### Brief Description

OS: Linux (Ubuntu 14.04)
qTox version: v1.3.0-38-ga48c422.
Commit hash:  a48c4225938834db0d4406cff54a07378e9636f4

…

Reproducible: Always 
##### Steps to reproduce
1.  Go to Settings>General>Chat and check **Multiple windows mode** and **Open each chat in an inidividual window**
2.  Minimize the main window and leave only a chat window.
##### Observed Behavior

When you receive a message the tray icon keeps blinking until you focus the main window.
##### Expected Behavior

Tray icon should stop blinking after I focus the chat window where I received the message.

**Comment by zetok** [comment]
Update your qTox. Should be fixed on latest version. (IIRC)

**Comment by gabrielcramer** [comment]
Yes, you were right, but now it doesn't blink anymore when Focus window is checked. Thanks for your quick reply.

**Comment by zetok** [comment]
Since it works, closing.

For the other issue there's #3262.
