### ISSUE TITLE
With `Focus window` qTox doesn't get highlighted window

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#3262]
##### Brief Description

When `Focus window` is set, qTox doesn't highlight window receiving the message.

OS: Gentoo GNU/Linux x86_64
qTox version: v1.4.0-37-g4432ab6
Commit hash: 4432ab6398aa4c9cdc222cf46170b820b9e33fa0
toxcore: 0.0.0
Qt: 5.5.1

Reproducible: Always
##### Steps to reproduce
1. Set `Focus window`
2. Move qTox to other workspace → make sure that your DE/WM doesn't move window back to your current workspace once it's focused
3. Receive a message
4. No highlighted window
##### Observed Behavior

qTox instance on other workspace doesn't get highlighted.
##### Expected Behavior

qTox on the other workspace should get highlighted.
##### Additional Info

![focused](https://cloud.githubusercontent.com/assets/3148759/15091922/71fb2e4e-1451-11e6-8444-23296c0997fe.png)

First reported in https://github.com/tux3/qTox/issues/3261#issuecomment-217629083 by @0merta

**Comment by anthonybilinski** [comment]
Focus window was removed in 91bdd40f10aa8731e5a3a1ee7d14682e142cc8f5, which is present in v1.17.0 forward.
