### ISSUE TITLE
Other programs will know your 'friends'.

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3272]
By looking at "./avatars/" folder, any app can know user's friends.

(xxxx).PNG
where xxxx is Friend's ID.
1. Crypt it using one-way hash(file name), and also, change image format using ROT13 or something(data)
   so other app can't know who your friends are.

**Comment by ghost** [comment]
This can be a security issue because it's leaking user's friends list into open, allowing hostile app to gather information about user.

**Comment by sudden6** [comment]
Hashing the ToxID in the filename might be a good idea, ROT13 is useless tough. 

Also I think there was already an issue about encrypting more stuff.

**Comment by tux3** [comment]
If you use an encrypted profile (a profile with a password), then we already use hashed IDs to prevent exactly this problem. For example two different encrypted profiles will write the avatars under different unpredictable names, so there is no way to gain any information.
We also, of course, encrypt the content of the image with your password so only you can open them.

If you profile is not encrypted, then anyone could just open your profile and directly look at your contact list, so there's nothing we can do in this case.
