### ISSUE TITLE
ability to upload multiple files at once

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3274]
##### Brief Description

OS: Windows 7 64
qTox version: v1.4.0-29-g08263e9
Qt:  5.5.1
…

Reproducible: Always
##### Steps to reproduce
1. I am Alice.
2. I clicked Bob, and send some messages.
3. I select some files(e.g., a.exe, b.zip, c.docx, d.zip), and drag them from explorer to qTox's chat window.
##### Observed Behavior

qTox start sending only "a.exe". I have to drag-drop each files at a time.
##### Expected Behavior

When I drop multiple files, just start uploading them.

**Comment by zetok** [comment]
Hmm, actually, it works this way on Linux.

**Comment by tux3** [comment]
That's a toxcore issue, the behavior changed a while ago.  I think there was some discussion about this on the stickers proposals, but I haven't heard anything new since, you should try reporting the issue to the toxcore repository.

**Comment by zetok** [comment]
@tux3 err, no, this isn't a toxcore issue. The problem that @qasmoke seems to have is that _qTox_ doesn't add all files to _queue_ on windows – seems to add just the first file – something that does work on Linux.

**Comment by tux3** [comment]
@zetok We've always treated file transfers the same way on Linux and Windows, and unless I missed a new change, toxcore did use to send files one after the other instead of all at the same time. To be clear, it does send files simultaneously for you on Linux?

**Comment by zetok** [comment]
> To be clear, it does send files simultaneously for you on Linux?

No, it adds all of files to the queue, and starts sending first one.

There are differences between how `drag & drop filetransfer` are treated on Linux and windows – e.g. #2847: works on Linux, but doesn't on windows.

**Comment by ghost** [comment]
(comment) Uh, if I have linux PC, I'll test it straight away. (/comment)

**Comment by tux3** [comment]
Oh I think I get it now, so it's drag and drop not working and not file transfers then.

**Comment by Diadlo** [comment]
Fixed now
