### ISSUE TITLE
Add an ability to auto-input password

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3276]
Looks like I should use a "password" to "encrypt" data from other app.
However, some people(not me but I know some) don't want to input password.

So, please consider adding "automatic input password"(or "remember password").

e.g.,
Thunderbird: "remember this password"
Windows auto-logon
Veracrypt: "--password" commandline args

**Comment by zetok** [comment]
Not doable in a safe way. If you don't want protection, simply remove password.
