### ISSUE TITLE
Incoming file transfer says "Accept to receive" without the "confirm" button

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3284]
The source is the Android app. This happened after the previous transfer failed.
The box only has "pause" and "cancel" buttons, but no "accept" button, so there is no way to accept.

This user isn't auto-accept.
After making this user auto-accept this situation repeats: it asks to accept again. So auto-accept is also broken.

**Comment by zetok** [comment]
Could you use the template? https://github.com/tux3/qTox/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by yurivict** [comment]
Sorry, here is a template:

Brief Description

OS: FreeBSD from ports
qTox version: 1.4.0
toxcore: 0.151112_2
Qt: 1.4.0

Reproducible: Always 

Steps:
1. Send a file from the android app and cancel it
2. Send another file
3. Observe the problem, as described above. No "accept" button

In fact, not even one file completed.

**Comment by zetok** [comment]
Related: #1875

**Comment by sudden6** [comment]
Closing because this is >2 years old and a lot in that code changed. If it's still an issue, please open a new one.
