### ISSUE TITLE
Add ping option to friend context menu

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#329]
So that the user can force retry to connect to e.g. offline friends

**Comment by tux3** [comment]
I'm not sure I like this idea.

The core should be good enough that this Just Works©. Users shouldn't need to manually ping people. This would never have a chance of being a thing in Skype.

**Comment by dubslow** [comment]
I ask because in one of my many restarts over the last few hours, audiobotze came online when I connected, but GroupBot took a few minutes, and I'm more inclined to believe it was a connection issue than GroupBot being down...

**Comment by tux3** [comment]
Yes, it's very annoying, but I'm not sure if it's a good idea to add that in the clients.

Imo this should be fixed in core. I tried to fix it some time ago, but gave up.

**Comment by zetok** [comment]
Hm, how easy would it be to make that as somewhat "debug" option that would show only if compiled with option for it, or by checking checkbox in settings "Show advanced debugging stuff" ?

**Comment by tux3** [comment]
The thing is that there's no "official" ping function in the toxcore API.
Doing this would imply awful hacks, calling probably-defined-but-undeclared functions, or building it on top of tox_send_lossy_packet API.

So, nope.
