### ISSUE TITLE
[Security] qTox should ask current password before removing it

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3299]
##### Brief Description

OS: Windows 7 32
qTox version: v1.4.0-68-g8d225a8
Commit hash:  8d225a8c97a36838092b325ca830c14546f3a0c6
Qt:  5.5.1
…

Reproducible: Always
##### Steps to reproduce
1. Your qTox profile is encrypted.
2. Attacker open profile window by clicking usericon when he/she is away from computer.
3. In "Profile", click "Remove password".
##### Observed Behavior

qTox ask for confirmation. If selected yes or something(I forgot), qTox silently remove password from profile.
##### Expected Behavior

qTox _must_ ask for current password before proceeding!

**Comment by zetok** [comment]
Actually, it's a duplicate of #2337, thus closing.
