### ISSUE TITLE
Desktop sharing, area selection

### ISSUE THREAD

**Issue by Balloon2mars** [qTox/qTox#3303]
Instead of desktop sharing being full screen only (breaking things for people with dual monitors), implement the same area selection tool as with screenshotting.

**Comment by zetok** [comment]
Related: #1786, #2102, #3092

**Comment by alugarius** [comment]
uTox has this feature, qTox uses ffmpeg I guess?

**Comment by Diadlo** [comment]
Fixed by #3392.
Close may be?
