### ISSUE TITLE
One friend's name and status are bugged and cropped

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#331]
![glitch](https://cloud.githubusercontent.com/assets/6127392/4432547/5ffed1f4-469a-11e4-99e1-276ee17d69d5.png)

**Comment by tux3** [comment]
Is there by chance a newline character in that name ?

It still has an old tox string terminator apparently.

**Comment by dubslow** [comment]
Also the extra space between avatars and border, as compared to between status light and border, drives me nuts.

**Comment by dubslow** [comment]
I don't know, I'll ask

**Comment by tux3** [comment]
> the extra space between avatars and border, as compared to between status light and borde

You mean the space where the sroll bar appears ?

**Comment by dubslow** [comment]
// moved to new issue

**Comment by tux3** [comment]
Right. Should make a separate issue for that.

**Comment by krepa098** [comment]
I can reproduce this by adding a line-break to my username.

**Comment by dubslow** [comment]
This particular one was a '\0' character, but still
