### ISSUE TITLE
[change icon suggestion] Turn :) from the red cheeks into a :grinning: closed mouth smile

### ISSUE THREAD

**Issue by mqds** [qTox/qTox#3315]
Let's face it, the current : ) or : - ) smiley icon in qTox looks almost embarrassed with those red cheeks and closed eyes. 

Even the ^ _ ^ icon has that 'joyful in frosty weather' type look with all that red.

I'd prefer to see the : ) smiley be made into a "more standard" looking smileyface _without_ the red cheeks. Something like the :grinning: icon for example, but with a closed mouth smile. 

Thank you.

+1 if you concur. :beer:

**Comment by sudden6** [comment]
+1 I was always confused by this

**Comment by sudden6** [comment]
I looked into this, and it seems that the emoticon pack we use doesn't provide a "closed mouth smiley", most similar I could get was https://github.com/tux3/qTox/blob/master/smileys/Universe/1f600.svg which I think is better, but also no quite right IMHO.

Any ideas on this?

**Comment by ProMcTagonist** [comment]
Switch to [Emojione](http://emojione.com/developers/)?

I extracted their svg download into a folder, added the emoticons.xml from Universe, and it just werked.

![emojione](https://cloud.githubusercontent.com/assets/4358079/15808671/a16a2f70-2b32-11e6-9d2f-a09a23098c45.png)

There's a closed-mouth smiley, and their cat is also much cuter than Twitter's abomination that's currently in use, which is important (cough @zetok)

**Comment by sudden6** [comment]
@ProMcTagonist They indeed seem to look better, I'll look into into them.
