### ISSUE TITLE
Extra space between avatars and left border

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#332]
Regardless of the scroll bar.
![without](https://cloud.githubusercontent.com/assets/6127392/4432568/6dd219f6-469c-11e4-825e-e2f20b74490d.png)
![with](https://cloud.githubusercontent.com/assets/6127392/4432569/70d98882-469c-11e4-821c-517f7e545155.png)

**Comment by krepa098** [comment]
Unfortunately this introduces another ugliness
![snapshot10](https://cloud.githubusercontent.com/assets/4587853/4433784/e69ce9e0-46ee-11e4-9aa6-fef22db44316.png)
![snapshot11](https://cloud.githubusercontent.com/assets/4587853/4433785/e7f58914-46ee-11e4-8b04-d3d71f04f2dd.png)

I don't know how to solve that yet. :/

**Comment by tux3** [comment]
Unfixed after reverting part of 87c9bbf1e6f7565bcf8aba7cb1f61dea004912e9
