### ISSUE TITLE
Do not log "xxx is now offline/online" if the target window is not opened.

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3321]
##### Brief Description

OS: Windows 7 x64/32
qTox version: v1.4.0-68-g8d225a8
Commit hash: 8d225
toxcore: 0.0.0
Qt: 5.5.1
…

Reproducible: Always
##### Steps to reproduce
1. Close all qTox window.
2. Run it several days.
3. Click your friend in contact list.
##### Observed Behavior

Nothing, clean chat window.
##### Expected Behavior

FILLED WITH
xxxx is now offline
xxxx is now online

**Comment by zetok** [comment]
Do you have `Show contacts' status changes` set?
![setting](https://cloud.githubusercontent.com/assets/3148759/14439935/92824ab6-0025-11e6-90de-25337e17df7d.png)

If so, it looks like a continuation of #3123.

Note: 8d225a8 has dcb8c3f included.

**Comment by zetok** [comment]
Works for me on 5cb271b0c0ce2d3a1700d05559c7a0a3ce34af25 with settings:
![settings](https://cloud.githubusercontent.com/assets/3148759/15425139/465889f8-1e7e-11e6-87a9-1975223755c0.png)

**Comment by sudden6** [comment]
@qasmoke please explain further, in the title you suggest to not log every status change, but in your problem description you seem to want to see every status change?

**Comment by zetok** [comment]
@sudden6 probably `s/^Do/Does/`

**Comment by ghost** [comment]
> Do you have Show contacts' status changes set?

Yes.

And oops, my mistake.

Expected Behavior = Nothing, clean chat window. (when opening chat window)
Observed(Actual) Behavior = Filled with Online/Offline status messages.

**Comment by ghost** [comment]
> if (Show contacts' status changes set === true) then
> if (ChatWindow.User.isOpened()) then
> ShowStatusLog();
> fi
> fi

**Comment by ghost** [comment]
Can reproduce(still logging this messages) on version v1.4.0-101-g2cd35e1, 2cd35e.

**Comment by zetok** [comment]
> And oops, my mistake.
> 
> Expected Behavior = Nothing, clean chat window. (when opening chat window)
> Observed(Actual) Behavior = Filled with Online/Offline status messages.

If you don't want to see status changes, then simply tick off an option for it.
Expected behaviour, thus closing.

**Comment by ProMcTagonist** [comment]
Just noting that online/offline spam is a problem and is either core's fault or qtox should change the timing on counting somebody as offline

**Comment by zetok** [comment]
> Just noting that online/offline spam is a problem and is either core's fault or qtox should change the timing on counting somebody as offline 

Actually, it's kinda both. Toxcore notifies about status changes, and qTox gives to user notification about status change.

I don't really remember whether qTox uses some sort of "buffer" for that - i.e. waiting like 10/15 s before notifying user about some friend going offline. If toxcore were to notify that peer came back online before 10/15 s since going offline, qTox wouldn't show notification.

IIRC that's not being done.

An issue for it would be good, provided that qTox doesn't wait a bit before passing to user notification received from toxcore.
