### ISSUE TITLE
[Security Enhance] Use Computer's Machine ID as a salt

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3322]
1. Add this checkbox, which is DISABLED by default;
   [_] Simply encrypt all your profile by using your machine ID.
2. When checked, ask for confirmation;
   "Enabing this will encrypt your profile with this machine ID. Decryption is not possible. R U sure?" Y/N

? WHAT
a. If the user change his computer, he can't use his tox profile anymore.
b. If the user re-install OS, same as "a".
c. User don't have to use "Profile password" because qtox encrypts their profiles by default!
(e.g., Automated login is now possible. Many lazy Americans will start using qTox like Skype.)

? HOW THIS WORKS
a. qTox will read PC's license key(mostly unique) AND computer name.
b. hash it: sha512(KEY.NAME);
c. use it for simple encryption.

? DESIGN

> result=simple_encrypt(KEY,profile_encrypt(get_data(_FILE_)));
> 1. profile_encrypt ... qTox's normal password encryption, if exist
> 2. simple_encrypt ... Machine ID encryption, if exist
> 3. = result

**Comment by ghost** [comment]
If the user need to use qTox on different PCs, he should use "Portable mode".
If he selected P mode, "Simply encrypt all your profile by using your machine ID." checkbox must be grayed out/disabled.

**Comment by zetok** [comment]
It all sounds like a bad idea.

> qTox will read PC's license key(mostly unique) AND computer name.

There's no license key to read. 

Reading something that is readily available is the ~same as using plaintext `.txt` to store password. There's no point.

> (e.g., Automated login is now possible. Many lazy Americans will start using qTox like Skype.)

If they aren't interested in security, they simply don't have to use password.

So, do you have a good use-case for this seemingly useless feature that will make users lose their data?

**Comment by ghost** [comment]
> It all sounds like a bad idea.

Of couse "strong password" is always the best, but many people(who you(I mean, developers) can't
ignore) want to use simple software.
They don't want to input loooooong password each time qTox starts.

What will happen if you don't encrypt qTox with password? Someone can become "you"
and stole your conversation(I reported this issue a few weeks ago), and more bad things will happen.

With my idea, anyone who don't want to use password can have a little confort
about security; their profiles are encrypted by machine ID(explain later), so if the attacker steals it,
there's no way to unlock it(well, there's no 100% but this will make real hard).

> qTox will read PC's license key(mostly unique) AND computer name.
> There's no license key to read. 

I don't know about Linux deeply, but on Windows, you can use "Windows Product ID" and
"Windows User Account".

Please take a look at this.
http://keepass.info/help/base/keys.html  - "Windows User Account" section

This software allow user to use:
1. Key file as password,
2. Password,
3. And Windows User Account(no need 1 or 2, just activate and forget it(autologin)).

**Comment by ghost** [comment]
another example: veracrypt(VC)
(Allowing "Key file as password" and "Password" method. Also supporting /command line, make many
people use VC easily. e.g., vc /p "MyStrooooongPaaasword")

> If they aren't interested in security, they simply don't have to use password.

I'm interested in security, and I use password.
I just want qTox to have many ways to enforce login security.

A: Why your qTox is not encrypted?
B: Why do I have to input password everytime I start it? Skype has "Remember me" checkbox.
A: Let's not hope someone stole your qTox files then.
B: If I could use qTox with command lines, I'll encrypt qTox...

qtox.exe /insecure-allowed /password "sssssssss"

**Comment by zetok** [comment]
@qasmoke 

> With my idea, anyone who don't want to use password can have a little confort
> about security; their profiles are encrypted by machine ID(explain later), so if the attacker steals it,
> there's no way to unlock it(well, there's no 100% but this will make real hard).

Bullshit. "Attacker" can easily steal all of that stuff, and thus they've got all of your data and are capable of decrypting it.

> > If they aren't interested in security, they simply don't have to use password.
> 
> I'm interested in security, and I use password.
> I just want qTox to have many ways to enforce login security.

This proposal is about is not security, but a pretence of it. By adding more ways to nullify security you're not helping to improve it..

> B: Why do I have to input password everytime I start it? Skype has "Remember me" checkbox.

Yes, you don't have security with skype.

Support for a keyfile is a good idea, and it would be an improvement – mind opening an issue for it?
Support for supplying password via command line also sounds like an improvement, so you might want to open an issue for it.
