### ISSUE TITLE
Why I'm not getting update notification?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3323]
1.
I'm using qTox portable.
Current version is v1.4.0-68-g8d225a8.
1. "Ceck for updates on startup" is checked.
   Close/Open qTox every day. No news. Good news?
2. Downloaded https://build.tox.chat/job/qTox_build_windows_x86-64_release/lastSuccessfulBuild/artifact/qTox_build_windows_x86-64_release.zip
   today. Unpacked it to my qtox and overwrite them.
3. Start qTox and the version is
   v1.4.0-101-g2cd35e1

Why?

Also, please consider adding "silent update" checkbox.
[X] Update qTox if the user is AFK about 1 hour.

if selected,
download latest qTox in background(save as qtox.tmp.zip)
copy qtox.exe to qtox-updater.exe
run qtox-updater.exe
kill qtox.exe
unpack qtox.tmp.zip
run qtox.exe
qtox.exe--->kill qtox-updater.exe
end

**Comment by zetok** [comment]
Updating `v1.4.0-68-g8d225a8 → v1.4.0-101-g2cd35e1` via updater is not supported, since it tracks only stable updates, and not nightly.

Though from what @tux3 described, updater should "update" `v1.4.0 → v1.4.1`.

**Comment by newnym** [comment]
> updater should "update" v1.4.0 → v1.4.1.

Same here, still v1.4.0.
Any updates?

**Comment by zetok** [comment]
> Any updates?

Yes, you should manually install 1.4.1 for updater to start working properly.
