### ISSUE TITLE
[Debian] I can't install qTox via APT

### ISSUE THREAD

**Issue by Stemby** [qTox/qTox#3326]
##### Brief Description

OS: Debian 8.4 (stable)
Hardware:  Virtualbox
…

Reproducible: Always
##### Steps to reproduce

```
# apt-get install qtox 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qtox : Depends: libavcodec-ffmpeg56 (>= 7:2.4) but it is not installable or
                 libavcodec-ffmpeg-extra56 (>= 7:2.4) but it is not installable
        Depends: libavdevice-ffmpeg56 (>= 7:2.4) but it is not installable
        Depends: libavformat-ffmpeg56 (>= 7:2.4) but it is not installable
        Depends: libavutil-ffmpeg54 (>= 7:2.4) but it is not installable
        Depends: libsqlcipher0 (>= 1.1.9) but it is not installable
        Depends: libswscale-ffmpeg3 (>= 7:2.4) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

---

**Comment by zetok** [comment]
Works for me. Are you sure that you've tried with the right repo?
https://software.opensuse.org/download.html?project=home%3Aantonbatenev%3Atox&package=qtox

**Comment by Stemby** [comment]
OK, that repo works fine.

I found the issue by following this documentation:

https://tox.chat/download.html#gnulinux

(the broken repo is https://pkg.tox.chat/debian)

Thank you!

**Comment by zetok** [comment]
> (the broken repo is https://pkg.tox.chat/debian)

It's actually deprecated. More info in https://lists.tox.chat/pipermail/qtox-dev/2016-May/000001.html

Since repo works, closing.

If packages in deprecated repo stopped working after yesterday's changelog addition, it might be something that @tux3 could want to look into.
