### ISSUE TITLE
[Idea] Supply password and/or keyfile via command line for easy login.

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3330]
https://github.com/tux3/qTox/issues/3322

https://github.com/veracrypt/veracrypt/ 's PDF guide will help you understand commandline use.

e.g.,
/q "Password With Space." /k C:/My/Sel/Fie.jpg ...... password and one file
/kF C:/Selfies/ ...... scan all files inside this folder

**Comment by zetok** [comment]
@vith um, IIRC you've said that supplying password via CLI isn't really that good – mind linking to something on the topic?

**Comment by vith** [comment]
https://unix.stackexchange.com/questions/78734/why-shouldnt-someone-use-passwords-in-the-command-line

**Comment by vith** [comment]
Using a secure system keychain to log in might be a better option if it's really necessary to reduce interactive key entry. https://github.com/frankosterfeld/qtkeychain

The idea is, you unlock the keychain once per OS desktop session with a master password and it can then provide key storage to other apps. Some keychain implementations may relock the keychain automatically after a timeout and/or when the system goes to sleep.

Note, I haven't used or reviewed that library at all. Found it just now to use as an example of what could be possibly done in a cross-platform way.

**Comment by zetok** [comment]
Supplying password via command line doesn't sound like the best way to go, instead a keychain should be used.

#4136 supersedes this issue, thus closing.
