### ISSUE TITLE
Add "Auto accept video call"

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3331]
? SUMMARY
I want "Auto accept video call" checkbox for contacts.
This should not added in global settings because this is a security risk.

? POSSIBLE USE
For work: Employee can use qTox to connect their lab - to see their plants status.
For your pet: https://www.indiegogo.com/projects/furbo-world-s-first-treat-tossing-dog-camera/ (I don't trust its security)

'If'
I have 1 notebook and 1 smartphone.
I installed qTox on notebook, and connect USB Video camera.
I installed Antox on smartphone.
My employer forced us to work late(zangyo). I'm worried about my pet.
With this latest update, I can always see and talk to my pet - remotely, and securely.

? HOW
In friends list, right-click contact and click "Show details".
Enable "Auto accept video call".
[X] Auto accept video call
| [_] Play a notification sound before automatic accept (optional)

**Comment by ghost** [comment]
and a youtube vid: http://youtubeinmp4.com/youtube.php?video=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DjZbYEaVQG90

**Comment by zetok** [comment]
Done in #3442, thus closing.

**Comment by rakis1** [comment]
Thanks ghost for the tip: Enable "Auto accept video call" it was very helpful.
