### ISSUE TITLE
Feature request: Add "Show qTox" to qtox indicator menu

### ISSUE THREAD

**Issue by swiftgeek** [qTox/qTox#3337]
Please add "Show qTox" to indicator menu as to my knowledge there is no other way to interact with indicator that would be described in any public spec (like those in freedesktop.org)

EDIT: After 15 minutes of more googling, this is issue is only happening with indicator implementations, while SNI have Activate/SecondaryActivate (missing in indicator)

**Comment by zetok** [comment]
Some other applications that support hiding to tray also have this kind of option in their tray drop-down lists, e.g. Hexchat, qBittorrent.
1. Position of `Show` button – between `Busy` and `Logout` ?
   ![position](https://cloud.githubusercontent.com/assets/3148759/15606453/49b50a0a-2404-11e6-8553-feeb7bda990e.png)
   
   qBt and Hexchat have it on top of the list, dunno if that's better?
2. There most likely should be also a `Hide` button, shown when qTox window isn't minimized to tray.

Note: while this wouldn't be a fix, it could possibly help some users to work around things like #3177.

**Comment by sudden6** [comment]
I would place it on top of the list, minimized the chance to accidentially click "Logout" or "Exit".
Also I think we shouldn't activate this globally, since at least for KDE the normal way to open programs from the tray is a single left click.

**Comment by zetok** [comment]
Done in a851a5b18da8c295fba441c817920cf65db2cdbb, thus closing.
