### ISSUE TITLE
Unable to load sym linked profile

### ISSUE THREAD

**Issue by 0xC4N1** [qTox/qTox#3339]
##### Brief Description

OS: Windows 10
qTox version: 1.4.1
Commit hash: d8d26abead835576cea7de481acd7ef31be6cf4a
toxcore: 0.0.0
Qt: 5.5.1
…

Reproducible: Always
##### Steps to reproduce
1. Run command line with administrator privileges
2. Create symlink with mklink %appdata%\Tox\profile.tox profile.tox
3. Start qTox
##### Observed Behavior

No password field for symlinked profiles. On load, it says wrong password.
The file is password protected.
##### Expected Behavior

Display the password field and let me login.
##### Hint in log file

The log file indicates, that qTox uses a wrong file path with two backslashes for sym links.

```
[19:44:55.513] src/persistence/settings.cpp:121 : Debug: "Loading settings from C:/Users/user/AppData/Roaming/tox/qtox.ini"
[19:44:55.513] src/ipc.cpp:46 : Debug: Our global IPC ID is  3169903406987816468
[19:44:55.513] src/main.cpp:200 : Debug: built on:  12:16:59 May  9 2016 ( 1462810479 )
[19:44:55.513] src/main.cpp:201 : Debug: commit:  d8d26abead835576cea7de481acd7ef31be6cf4a 

[19:44:55.513] src/persistence/profile.cpp:476 : Warning: Couldn't open tox save  "C:/Users/user/AppData/Roaming/tox\\profile.tox"
[19:44:55.528] src/persistence/profile.cpp:86 : Debug: Loading tox save  "C:/Users/user/AppData/Roaming/tox\\profile.tox"
[19:44:55.528] src/persistence/profile.cpp:97 : Critical: The tox save file  "C:/Users/user/AppData/Roaming/tox\\profile.tox"  couldn't' be opened
[19:44:55.528] src/nexus.cpp:81 : Debug: Starting up
[19:44:55.544] src/persistence/profile.cpp:476 : Warning: Couldn't open tox save  "C:/Users/user/AppData/Roaming/tox\\profile.tox"
[19:44:55.560] src/persistence/profile.cpp:476 : Warning: Couldn't open tox save  "C:/Users/user/AppData/Roaming/tox\\profile.tox"
```

**Comment by agilob** [comment]
Could you go to directory `cd C:/Users/user/AppData/Roaming` and list files there with `dir` command?

**Comment by tux3** [comment]
> Create symlink with mklink %appdata%\Tox\profile.tox profile.tox

Note that it's "tox" and not "Tox". It's wildly inconsistent when Windows paths are case-sensitive or not, but please try with the correct path.

And seconding what @agilob said.

**Comment by 0xC4N1** [comment]
Sorry for the delay. Didn't notice the first reply.

> Note that it's "tox" and not "Tox"

Didn't think of that since Windows paths are not case-sensitive and the profile was found at the login page. I will give it a try when I get home and paste the result of the dir command here if it doesn't help.

**Comment by 0xC4N1** [comment]
Alright I've checked the Tox folder in %appdata% and it actually is capitalized. I've tried to rename it and create the sym link again in lower case but that didn't change anything in behavior. The log file isn't different either so I've reverted the changes. 

I've also tried to create the sym link with a new name so qTox created another ini file when it was started. There have been even more backslashes in the corresponding line of the log file.

```
[21:01:08.521] src/persistence/settings.cpp:1774 : Debug: Creating new profile settings in  "C:/Users/user/AppData/Roaming/tox\\\\profile2.ini"
```

Here is the result of dir:

```
03.06.2016  21:01    <DIR>          .
03.06.2016  21:01    <DIR>          ..
01.06.2016  18:55    <DIR>          avatars
03.06.2016  21:01                26 profile.ini
03.06.2016  21:01    <SYMLINK>      profile.tox [O:\ownCloud\tox\profile.tox]
03.06.2016  21:01             4.040 qtox.ini
03.06.2016  21:01           572.191 qtox.log
09.11.2015  21:08    <DIR>          screenshots
21.08.2015  14:56                84 utox_save
```

**Comment by agilob** [comment]
What if you do:

```
cd %appdata%\Tox
mklink profile.tox O:\ownCloud\tox\profile.tox
```

It looks like something is unable to handle the slash in directory.

Anyway, the bug mentioned in source code is fixed now in Qt 5.5.0:
https://bugreports.qt.io/browse/QTBUG-38845
so the hack around QDir::cleanPath should be fixed.

Can't reproduce on Linux.

**Comment by 0xC4N1** [comment]
> What if you do:
> 
> ```
> cd %appdata%\Tox
> mklink profile.tox O:\ownCloud\tox\profile.tox
> ```

same result. 

> the bug mentioned in source code is fixed now in Qt 5.5.0

qTox says it's using Qt 5.5.1

**Comment by 0xC4N1** [comment]
I've done the last step that agilob suggested again with a different file. This time I could sign in with it.

**Comment by agilob** [comment]
> qTox says it's using Qt 5.5.1

But there is a hack around the fixed bug, and apparently the hack is buggy, but it's safe to remove the hack now and use standard Qt implementation.

**Comment by anthonybilinski** [comment]
https://bugreports.qt.io/browse/QTBUG-38845 being fixed doesn't seem to remove our need for custom behaviour per platform. The idea of GenericConfigLocation + "/orgname/appname" for all platforms doesn't keep the paths the same as we have now. For Windows for example, that path is `"C:/Users/user/AppData/Local` instead of `"C:/Users/user/AppData/Roaming` so would break backwards compatibility. I unfortunately don't see any [QStandardPath](https://doc.qt.io/qt-5/qstandardpaths.html) that keeps all of our paths the same as they are now, so keeping the arch specific ifdefs seems required.

I still found a fix for symlinks not working in windows. PR incoming.

**Comment by anthonybilinski** [comment]
I was (finally) getting my change ready for PR, but I can't repro this issue any more on tip, or all the way back to v1.15.0 when we have our oldest windows builds on github. Maybe something changed a while ago about how we handle paths, or maybe there was some Windows change in path handling. There's a path handling refactor going on that can handle the underlying messyness of adding together strings with both backslash and forward slash, so I think it's fair to consider this fixed.
