### ISSUE TITLE
[Regression] "Default" avatars look disgusting

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#334]
Current ones:
![2014-09-28 hexafluoride bully](https://cloud.githubusercontent.com/assets/3148759/4433983/89f5ef3c-46fa-11e4-9db3-f1ac3ccb738d.png)

Previous:
![2014-09-28 hexafluoride bully](https://cloud.githubusercontent.com/assets/3148759/4433984/a7af360a-46fa-11e4-8d2d-a152a48a3161.png)

**Comment by zetok** [comment]
![2014-09-28 hexafluoride bully](https://cloud.githubusercontent.com/assets/3148759/4434036/66621a3e-46fd-11e4-9d6e-fd061f872aa6.png)
![2014-09-28 hexafluoride bully](https://cloud.githubusercontent.com/assets/3148759/4434040/725d9638-46fd-11e4-9207-9429b8cf1179.png)

**Comment by dubslow** [comment]
closearooni macroni

**Comment by zetok** [comment]
Is it me, or it looks even worse on fd36b6cfaadd8126faffa3f32a4ad0c404bb2014 ?
![2014-09-28 hexafluoride bully](https://cloud.githubusercontent.com/assets/3148759/4435303/253df8fc-473e-11e4-857d-706ac7068fd2.png)

**Comment by dubslow** [comment]
It doesn't look worse, but I did notice that audiobotze, which doesn't have an avatar, now has the white square instead of what is supposed to be the default image. The chatarea picture is still the default, but its friends list image is the square of pure white. Edit: This isn't always the case, but it shouldn't be able to happen at all...

This should be temporarily reopened.

**Comment by dubslow** [comment]
It happened to another friend, I think maybe it's second on friend's list? But still not consistently... hopefully @krepa098 knows what's up...

**Comment by krepa098** [comment]
Seems like something went wrong during the merge. Can you please apply the patch above and give it a shot? I can't seem to add audiobotze.

**Comment by tux3** [comment]
I cherry-picked your patch in 67ffbfcb6ef6f3c52103f8fbdabbf35f21fb9d2c

**Comment by zetok** [comment]
Group chats are still visually inconsistent:
![2014-09-28 hexafluoride bully](https://cloud.githubusercontent.com/assets/3148759/4449627/a66b884c-481d-11e4-93f6-4bcc6d216622.png)

**Comment by krepa098** [comment]
I agree, although that's how it's done in the mockup (see https://github.com/ItsDuke/Tox-UI)
So either:
a) we remove the background from the user's default avatar
b) or we add it to the groupchats. 
I'm slightly in favor of b) for consistency with custom avatars.

**Comment by dubslow** [comment]
I'm in favor of a). We don't need a background for avatars, just the same surrounding gray.

**Comment by tux3** [comment]
I'm also slightly in favor of a) for what it's worth. Imo the 'way it was before' with a dark and a white version was ok.

**Comment by zetok** [comment]
If changed to way it was before (aka a), IMHO this issue could be closed.

**Comment by dubslow** [comment]
I'm still not a fan, why should the background depend on the avatar? For instance, hptqx on irc has a spongebob pic, and that now has a blue background.

I want the background to simply be whatever background is around the avatar -- in the friend's list gray, and in the chat window, white. This is how I interpreted a), though perhaps that was wrong.

**Comment by krepa098** [comment]
Well different clients have different backgrounds. So black avatars (see Groupbot) may look great on other clients but they are barely visible on qTox. The same applies to white avatars, so you have to apply some kind of background to ensure a good visibility. You can still have a more pleasing background by simply putting it in your picture.

**Comment by dubslow** [comment]
Eh.... I think I prefer
![stallman](https://cloud.githubusercontent.com/assets/6127392/4480832/a7a84474-499a-11e4-9106-83e020086801.png) 
to 
![spngebob](https://cloud.githubusercontent.com/assets/6127392/4480910/320847ea-499b-11e4-9f81-817fd3ca8df8.png)

And besides, in any active chatroom the background is white anyways. I doubt other clients treat white-background avatars special.

Besides, the huge vast majority of avatars will have their own background, rendering our choice moot.

https://github.com/dubslow/qTox/commit/f157582d3273250d5729b5536f12fbbbaa5761d3

**Comment by krepa098** [comment]
Counterexample:
![snapshot15](https://cloud.githubusercontent.com/assets/4587853/4481162/6c55e9a0-499d-11e4-9472-4c99c1bc350e.png)

> And besides, in any active chatroom the background is white anyways. I doubt other clients treat white-background avatars special.

I don't know how it's done on other clients. I'ill do some tests tomorrow.

> Besides, the huge vast majority of avatars will have their own background, rendering our choice moot.

Yes, but png allows transparency so that's a case we should handle.
@tux3

**Comment by zetok** [comment]
There's still small problem with default avatars:
1. Select offline peer without an avatar
2. wait until comes online

In given scenario avatar of selected peer changes from black to white when peer comes online, which is pretty bad, since selection and background are white..

**Comment by zetok** [comment]
Looks like 7100fb707be698e71a9e63d709ac08334c09899e fixed it
