### ISSUE TITLE
"Wrong password" dialogue opens regularly on Windows 7 64bit

### ISSUE THREAD

**Issue by TheMadman** [qTox/qTox#3344]
##### Brief Description

I have installed qTox in Windows. Running it once and creating a new profile with a password works. After quitting and re-opening qTox, it asks me for a password for the profile I just created.

Using the correct password at this point very frequently pops up an error dialogue that reads, "Wrong password." After closing that dialogue and re-submitting the same password multiple times, qTox eventually grants me access.

OS: Windows 7 64bit
qTox version: 1.4.1
Commit hash:  d8d26abead835576cea7de481acd7ef31be6cf4a
toxcore: qTox -> Settings -> About shows, "toxcore version: 0.0.0".
Qt:  5.5.1

Reproducible: Almost Always
##### Steps to reproduce
1. Using a clean configuration (e.g. by moving the AppData/Roaming/tox directory to tox~), launch qTox and type in an arbitrary username. Copy a password to the clipboard, or keep it in a notepad instance or similar, then copy it to the Password and Confirm fields.
2. Hit Enter to create the profile. qTox should successfully load up, showing the "Add Friends" interface.
3. Quit qTox, either by closing the main window or from the system tray icon.
4. Load qTox again. It should show your previous profile in the drop-down menu.
5. Paste your password into the password field. If the password isn't in your clipboard anymore, copy it from your notepad instance and paste it into the password field.
6. Hit Enter or press the Load button.
##### Observed Behavior

see QMessageBox::critical(..., "Couldn't load this profile", "Wrong password.");
from widget/loginscreen.cpp:227
##### Expected Behavior

Log in to the selected profile successfully.
##### Additional Info

Attempting to log in multiple times with the password pasted (e.g. by holding the Enter button to close the dialogue box automatically) will eventually grant access.

[qtox-log.txt attachment](https://github.com/tux3/qTox/files/291072/qtox-log.txt)

**Comment by LittleVulpix** [comment]
This sounds to me like something is keeping the profile file opened in write mode, so that the new qtox instance is unable to do so. This causes it to not be able to write any data which in turn blocks opening the profile.

Happens on slower laptops or if you use more than one antivirus system - because due to I/O activity on the file, the antivirus keeps it locked for a few seconds after you quit qtox. In some cases it is qtox itself as it takes a few more seconds to close after the GUI disappears (usually due to the same reason - slower computer (hard disk mostly) or an antivirus system).

**Comment by TheMadman** [comment]
I am using Immunet 3.0 antivirus on Windows. That may be the issue. It may also be that the disk had been busy for some other reason - this is my gaming desktop, which means Steam regularly automatically updates games in the background.

The hardware is as follows:
Intel Core i7 3770K
AMD Radeon R9 280
WD Green 4TB Hard Drive

If there is a hardware bottleneck it is almost certainly the hard drive.

**Comment by LittleVulpix** [comment]
Try reproducing it but after quitting qtox, wait, say, 20 seconds (to rule out anything, even slow disks). See if it still happens. I would imagine it doesn't, if it's the issue I suspect.

**Comment by TheMadman** [comment]
I can't reproduce it now. It may have been something specific my computer was doing yesterday.

Perhaps we should close this for now and, if I'm able to reproduce it, I'll re-open it.

**Comment by LittleVulpix** [comment]
+1 close it :) And if it starts reproducing, check your disk utilization. It's usually the culprit.

**Comment by zetok** [comment]
> +1 close it :) And if it starts reproducing, check your disk utilization. It's usually the culprit.

Even if disk speed is the problem, qTox should try to handle that.
