### ISSUE TITLE
Popup a info window on call to desktop, with name of client and sort of call

### ISSUE THREAD

**Issue by Getron** [qTox/qTox#3346]
If a call is incoming, a litle popup window should give an info about who is calling, and what sort, audio-video icons. Somthing, like Skype do.

Ok, i known, there is a option to popup entire qTox client on call, but, it doesn't work optimal, because, it popup, but, i must see, where is calling, and search for a little (green)circle somwhere in my many contacts. It is just not fun, if you have 20 or more contacts...

Or maybe a systray popup info, and from there, to able directly to accept the call, and then should the main qTox window popup, if i accepted the call.

**Comment by sudden6** [comment]
this basically comes down to #2921
