### ISSUE TITLE
sqlcipher Makefile:673: recipe for target 'sqlite3.lo' failed make: *** [sqlite3.lo] Error 1 

### ISSUE THREAD

**Issue by Yetoo1** [qTox/qTox#3347]
I am trying to build sqlcipher from source using the instructions and I get the error:
Makefile:673: recipe for target 'sqlite3.lo' failed
make: **\* [sqlite3.lo] Error 1
When I make it. I've read that it is an openssl issue, but I need more information. I tried to make this with Debian jesse 8.4.

To reproduce this...
1. Have my distribution 
2. follow the instructions 
3. see how the make doesn't work
I'm not sure if this is reproducible, but I would like more information about it.

For whom it concerns the entire make log can be found here: http://pastebin.com/mV4XtTjY
Not all of the make output is there but it is a good portion.

**Comment by zetok** [comment]
Can't reproduce, given that instructions state to add backports, in which sqlcipher is provided..?

Is there a reason to manually compile sqlcipher on Debian?
If so, wouldn't that be a sqlcipher issue?

**Comment by BiTOk** [comment]
@Yetoo1 What version of openssl do you use? Please, attach full build log.

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.

If issue is still not fixed, please comment for reopen.

**Comment by wallisonalves** [comment]
I have this same problem when trying to compile on an orange pi prime with ubuntu 16.04

config.log: https://gist.github.com/wallisonalves/1a5da6d98229c5d9bbc5c37e181466ec
make error:  https://gist.github.com/wallisonalves/8c50d6823d2366ec8d10ea2060441f43

**Comment by audiomason** [comment]
Try adding `-ansi` to `CFLAGS` when running the `configure` script.

`./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC -ansi" LDFLAGS="-lcrypto"`
