### ISSUE TITLE
qTox self-contained (portable) Like The Tor Browser

### ISSUE THREAD

**Issue by alugarius** [qTox/qTox#3349]
Discussion about making qTox portable again! --Tronald Dump

Static binary isn't working. Finding solution or alternative! ( example software that doesn't need installation, to inspire: Blender.org, ricin.im, uTox.org, and TorBrowser. www.torproject.org/projects/torbrowser.html.en

Today common software is easy to run for a reason: more normal users are using Ubuntu and Co...  they never used a Terminal before (my mother for example). For example, TorBrowser, I only need to doubleclick the .desktop file!

This should be possible for qTox.

**Comment by tux3** [comment]
Hello, we're working on getting the static portable builds of qTox working again.

You can download the latest experimental builds here:
Linux 64-bit: https://build.tox.chat/view/qtox/job/qTox_build_linux_x86-64_release/lastSuccessfulBuild/artifact/qTox_build_linux_x86-64_release.tar.xz
Linux 32-bit: https://build.tox.chat/view/qtox/job/qTox_build_linux_x86_release/lastSuccessfulBuild/artifact/qTox_build_linux_x86_release.tar.xz

**Comment by alugarius** [comment]
How about trying other methods, it don't have to be in one file, like uTox, it can also use appimage or be like blender ( blender only needs the glib and has python and other stuff in a data folders/ the binaries are next to the folders ).

**Comment by alugarius** [comment]
I'll test the bin if my phone is charged, ....the socket needs a home

**Comment by alugarius** [comment]
![utox runns](https://cloud.githubusercontent.com/assets/16763352/15791190/172f2494-29d6-11e6-920f-23367ab03a14.png)

uTox<(They see me workin' they hatin'!)  
wayland says nope

**Comment by alugarius** [comment]
libwayland-egl.so.1 is it called ,
@tux3 do u want to fix ore want to keep going ? ^^

well, it got much better! It works perfect on ubuntu class systems ( fedora, suse should work, this tests come later! to prove)

**Comment by tux3** [comment]
@alugarius If you don't have wayland support installed, it sounds like a bug with your distribution. I could try removing wayland support, but then it would break for people who use wayland...

Do you have the libwayland-egl1-mesa package installed?

Using AppImage or something similar could work yes, that's not a bad idea at this point.

**Comment by SkyzohKey** [comment]
@tux3 if you want to build app images for each commit, here's the script AppImage's creator made for Ricin → https://github.com/RicinApp/Ricin/blob/master/appimage.sh

It shouldn't be hard to modify to fit qTox i guess, else you'll have to ping [probonopd](https://github.com/probonopd).

**Comment by alugarius** [comment]
@RazZziel can also help, he is an pro in adding software to appimage!
He made portablelinuxgames.org and I worked with him years ago!

**Comment by alugarius** [comment]
@SkyzohKey ,Thanks for helping! We need to work together, all client developers!
I don't have Wayland installed, I tested it on Slacko Puppy Live. It has nothing to do with Wayland!

I have no issues on ubuntu! Apropos, could qTox or uTox work on ubuntu phone (desktop mode?)

even Qt itself is downloadable as an offline installer (self contained) there HAVE to be a way, else i cant really use it!
And without portable qTox / how should i use the "make tox portable" option? this is only an awesome feature if i have an portable client! 

here is an screenshot of q- and uTox's folder in portable mode! qTox should make an subfolder too, it looks on an flashstick nicer!
![bildschirmfoto vom 2016-06-04 23-25-35](https://cloud.githubusercontent.com/assets/16763352/15802224/c2b8b890-2aab-11e6-9255-061b5e05b42e.png)

**Comment by RowenStipe** [comment]
As someone who has used OS X's `.app` application format and and recently discovered [`.appimage`](http://appimage.org/) (further reading [here](https://github.com/probonopd/AppImageKit/wiki) ) I really like @SkyzohKey 's idea of creating such a format so that someone could potentially load qTox onto a USB drive in portable mode and use it across multiple different Linux distributions. And as such I find such an idea very attractive for a packaging proposal.

**Comment by alugarius** [comment]
@RowenStipe 
An automatic script that compiles qTox with all depencies and packs it to appimage! Thanks to simple_make.sh its possible!

**Comment by alugarius** [comment]
QTox works on suse, I could not test fedora . It crashes in vm with gnome blue screen (open source windows?)
Whatever. No other problems with qTox portable so far.

**Comment by alugarius** [comment]
If the qTox binary continiue the work like it does now, I could replace uTox

**Comment by alugarius** [comment]
I wanted to bring on the snap solution again, if it fits in ya time read this 
http://www.omgubuntu.co.uk/2016/06/snap-to-be-universal-linux-package-format

**Comment by vatterspun** [comment]
**Possible workaround** (at least in Windows): Run qTox in concert with [Advanced Onion Router](http://www.te-home.net/?do=work&id=advor).  Both programs are portable and can be run self-contained.

That said, it would be nice to integrate them just so you can set clear expectations about image and file transfers: tor transfers are going to be considerably slower than other connections.

**Comment by Serkan-devel** [comment]
Any updates on appimage support?
