### ISSUE TITLE
simple_make.sh

### ISSUE THREAD

**Issue by alugarius** [qTox/qTox#3354]
APT:
on Ubuntu 16.04 the command for installing is normaly "sudo apt install <package>" ( this is the new APT, it runns faster(and looks nicer) )
it still supports "sudo apt-get install <package>" but i suggest to change this script to lookup if "apt" is there and uses this and if not then "apt-get"
![apt](https://cloud.githubusercontent.com/assets/16763352/15806280/517fd72c-2b40-11e6-9b50-cac4ea7f2754.png)

> > > I am thinking about an offline compile (for emergency)<<<

**Comment by ProMcTagonist** [comment]
No. Apt is not for scripting.

```
man apt
```

> ```
> DESCRIPTION
>    apt provides a high-level commandline interface for the package management system. It is
>    intended as an end user interface and enables some options better suited for interactive usage
>    by default compared to more specialized APT tools like apt-get(8) and apt-cache(8).
> 
> 
> The apt(8) commandline is designed as an end-user tool and it may change behavior between
>    versions. While it tries not to break backward compatibility this is not guaranteed either if
>    a change seems beneficial for interactive use.
> 
> All features of apt(8) are available in dedicated APT tools like apt-get(8) and apt-cache(8)
>    as well.  apt(8) just changes the default value of some options (see apt.conf(5) and
>    specifically the Binary scope). So you should prefer using these commands (potentially with
>    some additional options enabled) in your scripts as they keep backward compatibility as much
>    as possible.
> ```
