### ISSUE TITLE
CXXABI_1.3.8 not found

### ISSUE THREAD

**Issue by siejan** [qTox/qTox#3358]
> $ qtox
> qtox: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by qtox)

OSs Tried:
- Linux Mint 17.1 x64 (Ubuntu 14.04.1 LTS, jessie/sid)
- Linux Mint 17.3 x64 (Ubuntu 14.04.3 LTS, jessie/sid)

Last few 'qtox' nightly releases (latest I tried was 644-792103f) from pkg.tox.chat/debian have this problem for me. qtox-qt5.4.2 package works. Anyone else have this problem?

**Comment by zetok** [comment]
> pkg.tox.chat/debian

Use the right repo: https://software.opensuse.org/download.html?project=home%3Aantonbatenev%3Atox&package=qtox

**Comment by siejan** [comment]
Might need to update the wiki and the site:
https://wiki.tox.chat/Binaries#debianubuntu
https://tox.chat/download.html#gnulinux

**Comment by zetok** [comment]
@siejan that's a tox.chat wiki and website, you might want to ask them to update their stuff. I would have updated their wiki, but they have removed my account long time ago…

And qTox has its own website: https://qtox.github.io/ – it does point to the right repo ;)

**Comment by siejan** [comment]
I didn't realise there had been a divergence. Is there any outstanding security issues for those who have been using pkg.tox.chat? I only ask due to the other issues that occured earlier this year.

**Comment by zetok** [comment]
> I didn't realise there had been a divergence. Is there any outstanding security issues for those who have been using pkg.tox.chat? I only ask due to the other issues that occured earlier this year.

Nah, it's just that packages on tox.chat lack proper maintenance, so they don't work. In addition, getting useful info for debugging from tox.chat packages is not something easily doable.

Also tox.chat lies to people that there are no qTox builds for osx and some *buntu versions, which is rather annoying, but oh well.

The point about *buntu packages [might be fixed in a few weeks](https://github.com/qTox/qtox-irc-logs/blob/75d829a2da7d3aad55a12f4e4c2e50ce6bf162f6/2016/06/%23qtox_20160606.log.txt#L8,L9)…
 (really, **weeks** to fix that!)

**Comment by d-damien** [comment]
@siejan : I just installed package qtox-qt5.4.2 on Linuxmint 17.1 and it seems to work fine.

**Comment by TheNotary** [comment]
I noticed this problem today (I don't use qtox too regularly).  I installed a long time ago via this source list...

(/etc/apt/sources.list.d/old_tox.list)

```
deb https://pkg.tox.chat/debian nightly release
```

To solve this problem I did `apt-get remove qtox` and then from the [advice](https://software.opensuse.org/download.html?project=home%3Aantonbatenev%3Atox&package=qtox) discussed above, updated my package source to be

(/etc/apt/sources.list.d/old_tox.list)

```
deb http://download.opensuse.org/repositories/home:/antonbatenev:/tox/xUbuntu_14.04/ /
```

The final page is to setup the keys (check the advice page for platform specific advice).  

```
wget http://download.opensuse.org/repositories/home:antonbatenev:tox/xUbuntu_14.04/Release.key
sudo apt-key add - < Release.key  
```

Worked after `apt-get update; apt-get install qtox`

I guess there's no way to set a console message in the old repo that says "You're trying to download from an outdated packages source, please update your sources list from URL"?  Anyway, thanks all for tracking this!
