### ISSUE TITLE
qTox updater on windows behaves strangely

### ISSUE THREAD

**Issue by LittleVulpix** [qTox/qTox#3362]
##### Brief Description

OS: Windows (any version)
qTox version: 1.3.0 -> 1.4.0 / 1.4.1

Reproducible: Always
##### Steps to reproduce
1. Have qTox 1.3.0. Desktop icon (created by the installer) looks like this:
   ![Imgur](http://i.imgur.com/aqb946B.png)
2. Start qTox (using the desktop icon), it'll prompt for update to 1.4.1. Accept it, wait for it to download
   The qTox folder looks like this (left side just qtox, right side the bin subfolder):
   ![Imgur](http://i.imgur.com/YWgNhLI.png)
3. Exit qTox and then start it again (again using the desktop icon), qTox will update
   The qTox folder now looks like this (same view as above, notice the update installed itself into the base qtox folder and the bin folder remains unaffected)
   ![Imgur](http://i.imgur.com/CGtcmif.png)
4. The qTox started by the updater after the update is the one from the qTox base folder and is indeed version 1.4.1
5. Exit qTox and start it again by clicking on the desktop icon
6. Obviously you just started the un-updated qtox from the bin subfolder and once again it prompts you to update.... and this happens every time.
##### Expected Behavior

qTox updates the proper folder.
##### Additional notes:

Related to https://github.com/tux3/qTox/pull/3279

**Comment by DX37** [comment]
Maybe it's old _qtox-updater.exe_ version? I think it builds separately from original qTox binary.
UPD: And if user updating to new qTox version, I think we need to update _qtox-updater.exe_ too.

**Comment by zetok** [comment]
```
[18:17:22] <LittleVulpix> Fox, 08.06.2016 19:14:55:
[18:17:22] <LittleVulpix> Oh my god. Since I had qTox I had this new version download prompt every time I turned the app on. And it was finally gone two weeks ago. And now it prompts me to a new version again. Meh. Skype is less annoying than this I swear.
[18:17:26] <LittleVulpix> :<
[18:17:30] <LittleVulpix> <- my friend
```

**Comment by LittleVulpix** [comment]
Any idea on when this could  be fixed? I pretty much turned autoupdate off for all of my friends that use qtox, some of which were starting to get really annoyed.

**Comment by tux3** [comment]
This is a known and fixed bug, you need to update to the latest qTox version to resolve it, this can be done by running the installer.
A workaround for the bug is to change the shortcut to start in "C:\Program Files\qTox\bin" instead of "C:\Program Files\qTox"
