### ISSUE TITLE
"Quote selected text": Problems with different time zones

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#3369]
First of all thanks to @fazotron for the cool new feature, well done! :+1: 

However, I have something to add.
I am not sure if I really like the automatic quote with timestamps because of the following reason:
If you are writing with a person from a different time zone the time is just wrong for the person who gets the quoted message.

There are two possible solutions how to "solve" this:
- When you quote the whole message with the timestamp change the time to UTC:
  `> [09:43:57 UTC] Groupbot: Invalid command. Type help for a list of commands`
- Remove the timestamp completely

What do you think?

**Comment by ProMcTagonist** [comment]
You're copying the message you received, which includes the time you received it.

I don't see the problem for normal conversation. My conversational partners aren't thrown off by knowing I'm in a different time zone. And most people don't know how to read UTC.

Sometimes I clear timestamps for privacy but that's a separate thing.

**Comment by fazotron** [comment]
Thanks for testing new feature @ovalseven8!

The problem you have described is common for any groupchats.
About your proposed solutions:

> When you quote the whole message with the timestamp change the time to UTC

As for me, it will be a little bit weird and uncomfortable to convert from UTC to local time in mind every time I read somebody's quote.

> Remove the timestamp completely

However, there is ability to quote text without timestamp now - just don't select a timestamp. Yes, in this case username will not be quoted too.
