### ISSUE TITLE
Groupchat invites doesn't work on master toxcore

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#337]
Subj.

**Comment by tux3** [comment]
Well, seems like a core problem to me, then.

**Comment by dcharles525** [comment]
Did irungentoo not just push new groupchat stuff the last couple of days? https://github.com/irungentoo/toxcore/commits/master

**Comment by suhr** [comment]
Ok, reposted to toxcore.

**Comment by dubslow** [comment]
fixed

**Comment by suhr** [comment]
Indeed fixed.
