### ISSUE TITLE
Remove auto-underlining of text surrounded by dashes

### ISSUE THREAD

**Issue by ddobrev** [qTox/qTox#3373]
##### Brief Description

Many natural languages - including English - use pieces of text surrounded by dashes ('-') to indicate additional information, or emphasis. qTox automatically underlines text between dashes which makes the sent message look unnatural.

OS: Windows / OS X / Linux
qTox version: v1.4.1-1-g06d78dc
Commit hash: 06d78dcdee7bfe9a320fe91662f34227d74c3916
toxcore: 0.0.0
Qt: 5.5.1

Reproducible: Always
##### Steps to reproduce
1. Type a message surrounded by dashes ('-');
2. Send it to a contact.
##### Observed Behavior

The text between the dashes appears underlined.
##### Expected Behavior

The text between the dashes appears as typed.
##### Additional Info

I understand this is part of the capabilities for text formatting qTox has, in order make underlined, bold and italic text. However, you should use characters not normally used in regular text, such as \* which you use for italic text. For example, you could replace the symbol you use to mark the text to underline with '_' (underscore).
In case you disagree, please at least provide an option to turn auto-formatting off. In case you already have, I couldn't find it.

**Comment by DX37** [comment]
> In case you disagree, please at least provide an option to turn auto-formatting off. In case you already have, I couldn't find it.

It's exist here:
![2016-06-10_16-29-37](https://cloud.githubusercontent.com/assets/12829428/15961803/b1943946-2f28-11e6-9535-7d4c9ca818f2.png).

**Comment by ddobrev** [comment]
@DX37 thank you, it works. I had seen the setting but I could not immediately understand what it's for.

**Comment by zetok** [comment]
@ddobrev https://github.com/tux3/qTox/blob/76239aa8906d478a59b29eeed764ca4e4f662444/doc/user_manual_en.md#message-styling :P

**Comment by ddobrev** [comment]
@zetok Thanks. :) Still, I think it would be nice if some other character was used for underlining. For example, making bold and italic could only work with \* so that _ is free to use for underlining (it's an "under"score, after all :) ). This way people would be able to use formatting while still retaining the proper function of the basic punctuation mark the dash is.

**Comment by ProMcTagonist** [comment]
The current characters are annoying, we should use @Skyzohkey's which are intuitive

**Comment by zetok** [comment]
> The current characters are annoying, we should use @Skyzohkey's which are intuitive

If you say so.

The only issue I see is that doing something that is not markdown would be venturing outside of what little standards there are.. Are we sure that it's worth it?

![standards xkcd](http://imgs.xkcd.com/comics/standards.png)

**Comment by Chiitoo** [comment]
I'm not sure why, perhaps due to IRC, but I've come to terms with /slashes/ being italic, *asterisk* bold, and _underscores_ underlining.  I have no idea if it's part of any standard,  I imagine this practice mostly came to be in e-mail and such.

I've never bumped into the (github flavoured or not) markdown syntax before qTox, really, and it feels very “wrong” and unintuitive.  That may simply be because I learned the other ways first.

I don't really mind it being there, since I can turn it off, but I would definitely prefer the ways I mentioned here.

**Comment by ProMcTagonist** [comment]
@zetok 
The vast majority of tox's target audience have never used markdown before except in the informal way which @Chiitoo is describing. That system is incredibly common across texting, emails, and even Facebook messaging, anecdotally.

In our case it's going along with the standard to use the markup that our users are most likely already used to from their previous experience.
