### ISSUE TITLE
can't build from git on debian

### ISSUE THREAD

**Issue by felix-salfelder** [qTox/qTox#3374]
i am trying to build from git. it seems the dependency checking is broken (bug?). here's the details.

``````
$ git branch
* master
$ git log -1
commit 76239aa8906d478a59b29eeed764ca4e4f662444
[...]

$ grep \#\ Compile\ qTox INSTALL.md -A10
### Compile qTox
**Make sure that all the dependencies are installed.**  If you experience
problems with compiling, it's most likely due to missing dependencies, so please
make sure that you did install *all of them*.

Run in qTox directory to compile:
```bash
qmake
make
```
``````

i get

```
$ qmake
Project ERROR: gtk+-2.0 development package not found
```

this does not seem right. i have

```
$ qmake --version
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu
```

and

```
$ dpkg -l |grep gtk.*-dev
ii  libgtk2.0-dev      2.24.30-2         amd64        development files for the GTK+ library
```

now, although this might be a qmake issue... i can not figure out what qmake is actually looking for. or, to put it differently, i have no idea, what "all of them [dependencies]" means, expecting that qmake should tell me...

can sb give a hint please?

**Comment by sudden6** [comment]
qmake uses pkconfig to look for dependencies, maybe it's missing? What version of debian are you running?

**Comment by felix-salfelder** [comment]
thanks! indeed, qmake runs `pkg-config --exists gtk+-2.0`. maybe i should have used the verbose switch (but I could not find any) `:/`.

updating pkg-config...

```
Unpacking pkg-config (0.29-4) over (0.28-1) ...
```

still no luck with qmake, then

```
$ pkg-config --list-all |grep gtk
gtk+-unix-print-2.0         GTK+ - GTK+ Unix print support
gtkgl-2.0                   GtkGLArea - an OpenGL widget for GTK+
gtk+-2.0                    GTK+ - GTK+ Graphical UI Library (x11 target)
gtk+-x11-2.0                GTK+ - GTK+ Graphical UI Library (x11 target)
```

and

```
$ pkg-config --exists gtk+-2.0
$ echo $?
1
```

for other packages, pkg-config works better... i will figure that out.

FTR, qmake _does_ tell me what's wrong, but only if i knew in advance:

```
$ qmake -d |& grep pkg-config -C1 | tail -n2
DEBUG 1: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:340: calling built-in system("pkg-config 2> /dev/null 2> /dev/null --exists gtk+-2.0")
DEBUG 1: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:340: test function returned false
```

(not a qTox problem)

**Comment by felix-salfelder** [comment]
> What version of debian are you running?

interesting question. i don't really care, but apparently one with a bug in libgtk2.0+-dev.

digging deeper, i found that qmake is hiding this:

```
$ pkg-config --print-errors --exists gtk+-2.0
Package 'xrandr' requires 'randrproto >= 1.5' but version of randrproto is 1.4.0
```

which _might_ be a bug in qTox (not telling qmake to error out properly). but i'm not a qmake user (lucky me), and i don't know if this is even possible. will be back with a PR, as soon as I know.

anyway, after an upgrade

```
x11proto-randr-dev (1.5.0-1) over (1.4.0-2) ...
```

the command `pkg-config --exists gtk+-2.0` is working as expected.

thanks again for your help @sudden6.

**Comment by ProMcTagonist** [comment]
This was affecting me as well. Lucky I stumbled on this issue.

```
 sudo apt install x11proto-randr-dev
```

Got qTox to compile again for me.

I'm running an old version of Debian testing, with mostly Jessie packages.

Thanks @felix-salfelder for discovering the solution.
