### ISSUE TITLE
Qtox crashing at Audio/Video options

### ISSUE THREAD

**Issue by Fred-Barclay** [qTox/qTox#3391]
##### Brief Description

OS: Linux LMDE 2 "Betsy" 64-bit w/ MATE (based on Debian Jessie)
qTox version: Nightly
Commit hash:  built without git
toxcore:  0.0.0
Qt:  5.3.2
Hardware:  https://gist.github.com/Fred-Barclay/6fa531933e1d583457903103c7e1eaa7

Reproducible: Always 
##### Steps to reproduce
1. Start qtox
2. Go to Settings >> Audio/Video
##### Observed Behavior

The qtox window immediately exits and crashes.
##### Expected Behavior

Whatever normal behavior is! :smile: 
##### Additional Info

Behaves identically to #1414. At first glance the gdb traces are different, though.

gdb trace: https://gist.github.com/Fred-Barclay/6c18019c26cbc271636e608e74d12969

No log file or qtox directory in ~/.config/tox

webcam info: https://gist.github.com/Fred-Barclay/97338d546d162d4928c243d2ee4967ef

Used apt-get and "deb https://pkg.tox.chat/debian nightly jessie" as the repo.

Thanks mates. :)
Fred

**Comment by zetok** [comment]
Could you try with https://software.opensuse.org/download.html?project=home%3Aantonbatenev%3Atox&package=qtox ?

IIRC repo should also have package for debugging symbols, you'd want to install it & then get backtrace – it should contain more useful info.

**Comment by zetok** [comment]
Oh, and btw, you'd want to do

```
t a a bt
t a a bt full
```

before `quit` in gdb.

**Comment by Fred-Barclay** [comment]
Thanks zetok. 
I completely removed the old build, added the repo, removed the config and cache file in my /home, and installed and started qtox. I got the same result (a sudden crash) when going to Audio/Video. Would you like me to run it inside gdb and post the output here?

**Comment by zetok** [comment]
> Would you like me to run it inside gdb and post the output here?

Yep, along with version info.

**Comment by Fred-Barclay** [comment]
qTox version: eb743b4-obs
Commit hash: eb743b43ff10a86288259792c1f950dca045c8ef
toxcore version: 0.0.0
Qt version: 5.5.1

I also installed the debug symbols you mentioned. 

Here's the gdb trace: https://gist.github.com/Fred-Barclay/64c93619964e8edc73e31bdd309395cc

`t a a bt` and `t a a bt full` run this time. I guess you can tell I don't normally use gdb? :)

**Comment by Fred-Barclay** [comment]
Well, qTox version v1.4.0-228-g9694d6b-obs isn't crashing any more, and I can change my audio and video options. 
I'll give it a few days and if it stays stable I'll close this.

Thanks @zetok and cheers!
Fred

**Comment by Fred-Barclay** [comment]
It's the weirdest thing... qtox will crash about half the time when I go to the Audio/Video option, but when I run it in firejail it hasn't crashed at all... yet. :smile:

**Comment by Fred-Barclay** [comment]
Qtox has been stable for about a week now, firejail or no firejail, so I think this can be closed for now. Thanks @zetok!
