### ISSUE TITLE
Option for disabling "emotifying" of text-smilies

### ISSUE THREAD

**Issue by ananace** [qTox/qTox#3398]
I've noticed that qTox applies emoticons to more than just the unicode emoticon glyphs, replacing text-smilies as well - things like `:)`.

I'd appreciate if an option for disabling matching of text-based smileys could be added, so that emoticon packs only beautify the regular unicode glyphs - perhaps the text representations of those emoticons as well (`:eggplant:` etc.)

**Comment by ProMcTagonist** [comment]
Two things: 

This would be working if we had replaced the twitter emoji with the emojione set entirely, in all three packs.

And the pack that leaves text alone should have a better name to indicate that, probably.

**Comment by ananace** [comment]
Why have a specific pack for it though? Why not extend the pack specification slightly to note main matches and extra matches, something like;

```
...
    <emoticon file="263a">
        <string>☺</string>
        <string shortcut="1">:-)</string>
        <string shortcut="1">:)</string>
        <string>:smile:</string>
    </emoticon>
...
```

Then a simple option could be added that would let you select if you want the pack to also match text-smilies.

**Comment by zetok** [comment]
> And the pack that leaves text alone should have a better name to indicate that, probably.

Probably would be good to make a new issue for it – care to do it (short text with what should be changed to what would suffice)?
