### ISSUE TITLE
Proposed new logo

### ISSUE THREAD

**Issue by XHawk87** [qTox/qTox#3400]
A not-entirely-serious suggestion for a better logo/icon.

[Suggested Logo](http://irocandrew.deviantart.com/art/Docile-Ox-270787284)

Perfect, right?

**Comment by antis81** [comment]
If you want to put it this way:
Nah, qTox is doing good to grow up. It is more like 4th grade primary school, maybe beginning of middle school now. In German school system, it would take at least 6 more years get the 10th grade. :smile:

If you like to get an idea on where qTox stands and the way it has to go to become a matured wholistic system, feel free to attend the sturdays staff meetings.

Or else:
Please make your point, what bothers you about qTox most and we will actually do anything possible to improve situation.

**Comment by XHawk87** [comment]
Embrace the cute ox logo for qTox!

Who can say no to that face?

**Comment by ghost** [comment]
No. It doesn't fit at all.

> Perfect, right?
> You have to explain:
> 1. Why you think this icon is perfect for qTox.
> 2. What is the problem of current qTox logo.
> 3. Who is the author of that icon and do you have permission to use it.

**Comment by XHawk87** [comment]
@proxifier Well if you insist on taking this seriously...
1. It is perfect for qTox because it is a pun, more specifically a homophone (qTox = cute ox). It gives the application a more friendly image that will be popular with the younger and female demographics.
2. There is no problem with the current logo. You're just missing an opportunity to make a funny. 
3. As it clearly displays on the page, the author is irocandrew and the license is Creative Commons Attribution-Noncommercial-Share Alike 3.0 License, which is compatible with GPLv3. Not that I recommend this image specifically, just the concept of using a friendly/humourous logo.

**Comment by zetok** [comment]
> (…) Creative Commons Attribution-Noncommercial-Share Alike 3.0 License, which is compatible with GPLv3.

Err, no, `Noncommercial` is not compatible with GPL.

**Comment by zetok** [comment]
Since there has been no new logo that could be used proposed, closing.

If you would want to propose a logo (preferably a mascot) that could be used, feel free to open a new issue, perhaps linking to this one.
