### ISSUE TITLE
"Public key" (Tox ID) viewed only 64 symbols in "show details", why not 74?

### ISSUE THREAD

**Issue by Granitoid** [qTox/qTox#3401]
##### Brief Description

OS: Windows XP 32bit SP3
qTox version: v1.4.1-1-g06d78dc
Commit hash:  06d78dcdee7bfe9a320fe91662f34227d74c3916
toxcore:  0.0.0
Qt:  5.5.1
Hardware:  Intel Core Duo E8400, 4Gb RAM

Reproducible: Always
##### Steps to reproduce
1. Contacts list, right mouse button on any user
2. Show details
##### Observed Behavior

Field "Tox ID" displeed only 64 symbols
##### Expected Behavior

Why not 74 symblos?
Why field Tox ID so short? Please move below and do it broader.
##### Additional Info

![tox_err01](https://cloud.githubusercontent.com/assets/16450834/16113510/387a7416-33c5-11e6-9b9a-81dd57deaf67.gif)

**Comment by TheNain38** [comment]
Public Key, and Tox ID aren't the same, the Tox ID contains: "Public Key + NoSpam + Checksum"
So, here it displays only the Public Key

**Comment by Granitoid** [comment]
Ok.
How to send contact from my list to enother user? :)
I try send to my friend "Public Key" (64 symbols) and what to do next?
For add new usr through from "Add friend" field "Tox ID" requires 74 symbols.

**Comment by zetok** [comment]
> How to send contact from my list to enother user?

You don't really.

What you might want to do, is to ask the friend whom ID you want to send for their ID, and forward that ID to your other friend.

If that answers your question, feel free to close the issue.

**Comment by Granitoid** [comment]
Too much actions for simple sending contact - uncomfortably.

**Comment by SkyzohKey** [comment]
:+1: @Granitoid

**Comment by zetok** [comment]
> Too much actions for simple sending contact - uncomfortably.

Right. I thought that there's already an issue for it, but it doesn't look like there's one → made #3405, thus closing.

**Comment by Granitoid** [comment]
Ok.
When what i can do with "Public key", why its displayed in "Show details" ? :)
Field "Public key" uselessly if it is not "ToxID".
So easy: Drug&drop contacts to chat window or/and context menu "Send contact to..." and receives with chekbox. ;)
Request generated automatically later if receives pressed "Add new friend".

**Comment by zetok** [comment]
> When what i can do with "Public key", why its displayed in "Show details" ? :)

You can verify that it belongs to your friend.

**Comment by Granitoid** [comment]
Hmmmm, without "NoSpam + Checksum"?
Ok,  it will be very often useful :)

**Comment by zetok** [comment]
`NoSpam` and `Checksum` are changeable parts ~~or~~ of ID, so they're ~useless when it comes to verifiability.

**Comment by methaqualon** [comment]
Once upon a time it happens in the future too.
Python3:
`calculate = bytearray(b'\x00\x00')`
`b = "" #paste your 64 and add 8 random antispam symbols`
`bb = bytearray.fromhex(b)[0:36]`
`for i in range(0, 36):`
 `    calculate[i%2] = calculate[i%2] ^ bb[i]`
`print(bytes(calculate).hex()) #it calculates what you need to add to b to add friend after it
`
