### ISSUE TITLE
change marks for text formatting for more "natural" & familiar ones

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#3404]
##### Brief Description

Current text formatting (markdown) is far from being familiar / natural to people who would want to use it.

Thus, it would be good to change it to something that lots of people already are familiar with, and if they're not, they could organically learn about it.

Pointed out & proposed in #3373, to use same marks that Ricin uses.

Thanks to @SkyzohKey:
![what ricin uses](https://i.imgur.com/RxfliqE.png)

cc interested parties from #3373:
@ddobrev, @DX37, @ProMcTagonist, @Chiitoo

Does anyone think that there are good reasons to not switch over?

**Comment by Chiitoo** [comment]
Looks pretty good!

I'm not too keen on ~tilde~ making the strikethrough, but I can likely live with that.  :]

I don't really have a suggestion for any better alternative for that either.  Only things that come in mind are <s> and [s], but those don't quite fit in with the rest.

**Comment by zetok** [comment]
> I'm not too keen on ~tilde~ making the strikethrough, but I can likely live with that.

Yeah, I'm not too happy about it myself, so I was wondering whether it would be acceptable to have only double tilde (i.e. `~~strikethrough~~`) as strikethrough.

**Comment by Chiitoo** [comment]
Methinks I for one would be OK with double tilde.

**Comment by yurivict** [comment]
Please add the markup explanation in a tooltip over the edit area.

**Comment by ddobrev** [comment]
The last suggestion is not a good idea, this tool-tip will get in the way each time someone wants to write a message.

**Comment by yurivict** [comment]
Code is also commonly marked up with triple-backquotes.

**Comment by sudden6** [comment]
I think ~strikethrough~ would be still better than ~~strikethrough~~, since it fit's the style of the rest in a better way.

**Comment by DX37** [comment]
Syntax proposed by @SkyzohKey seems more intuitive than Markdown. I think maybe even doesn't make sense to add an alternative form of syntax. Or vice versa is best to use an alternative syntax instead of the original. But it will be a bit cumbersome.

**Comment by anoadragon453** [comment]
I wrote the code for the markdown interpretation in qTox. I agree it doesn't exactly line up with other applications and have heard complaints about it before. I'm open to changing the syntax as changes are quite easy to make, though I would like a formal discussion on it where most people are in agreement before we make the change. 

Unfortunately one can't please everybody, short of creating a view where people can create their own custom markdown syntax, but I believe that solution would be too cumbersome for qTox, which markets itself as a simplified, easy-to-use messenger.

[Current qTox markdown styling guide](https://github.com/tux3/qTox/blob/master/doc/user_manual_en.md#message-styling) if anyone wants to compare.

**Comment by ddobrev** [comment]
I agree, settings for this would be way too cumbersome. Let's just pick any syntax which does not use dashes or other common punctuation marks. @SkyzohKey's suggestion is just fine.

**Comment by zetok** [comment]
I think that it would be good to switch to proposed syntax. So if no one has any bigger concerns → accepted.

**Comment by anoadragon453** [comment]
I will go ahead and change it to @SkyzohKey's syntax and create a PR.
