### ISSUE TITLE
timestamp over file accepting button

### ISSUE THREAD

**Issue by Saaaam** [qTox/qTox#3409]
When the chat window has a little width (chosen by the user) and a file is sent, the hour goes over the "accept file" button.

![qtox_issue_file_acception](https://cloud.githubusercontent.com/assets/19937009/16152937/625c9aae-34a4-11e6-9e28-87905249c888.jpg)

Two possible solutions : the gray/green block is resized smaller, or the main window can't be minimized so far.

**Comment by LittleVulpix** [comment]
You should probably change the title from "hour" to "timestamp"

**Comment by Diadlo** [comment]
Not the same with #2227?

**Comment by zetok** [comment]
@Diadlo 

> Not the same with #2227? 

It is, thanks – closing this issue.
