### ISSUE TITLE
When editing one's username or status, font color changes to match the background

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#341]
Making it almost impossible to see what you're typing

**Comment by dubslow** [comment]
Hmm, this should be changed to the font color changes on editing, which it shouldn't.

**Comment by tux3** [comment]
What OS / WM were you using to reproduce ?

**Comment by dubslow** [comment]
I still have this issue on LMDE/Cinnamon 2.0

**Comment by tux3** [comment]
I can't repro on Debian sid/Cinnamon 2.2.16

![image3](https://cloud.githubusercontent.com/assets/5155966/4877116/afa7be78-62dd-11e4-965f-1facf2edd7ff.jpg)

Is this still an issue ?

**Comment by dubslow** [comment]
Yes, but maybe it's a Cinnamon 2.0 thing

**Comment by agilob** [comment]
I'm sure it's related to system theme. Looks like this on my dark theme:
![status](https://cloud.githubusercontent.com/assets/2544251/4877362/a3028ee8-62e5-11e4-99c5-65e7a6800636.png)

Will fix in a second.
