### ISSUE TITLE
Feature request: ability to avoid qTox opening when clicking tray icon

### ISSUE THREAD

**Issue by nazar-pc** [qTox/qTox#3419]
##### Brief Description

OS: Ubuntu 16.10 x64 (Unity)
qTox version: v1.3.0-103-gda2f892
Commit hash: da2f892d63704d845457eeb0f0beb12592e0fc12
toxcore: 0.0.0
Qt: 5.5.1

Reproducible: Always
##### Steps to reproduce
1. Have qTox minimized to tray
2. Click tray icon
##### Observed Behavior

Tray menu is opened, also qTox window is opened
##### Expected Behavior

Tray menu is opened only. This is a default behavior in Unity DE for every other icon I have there (Skype, ownCloud, Dropbox, Slack, cpufreq-indicator, network-manager indicator, bluetooth indicator, audio, date-time).

**Comment by zetok** [comment]
> Tray menu is opened only. This is a default behavior in Unity DE for every other icon I have there

It's a problem with your DE.

**Comment by zetok** [comment]
Also, that qTox version is old, mind testing newer one?

**Comment by nazar-pc** [comment]
I'm always happy to test latest versions, this is why I have nightly version of `qtox-unity` package from https://pkg.tox.chat/debian
But I also see now that there is `qtox-qt5.4.2` with newer version and `qtox` with even newer version.
Any idea why nightly package is so old?

**Comment by zetok** [comment]
> Any idea why nightly package is so old?

Use the right repo, it has newest qTox: https://software.opensuse.org/download.html?project=home%3Aantonbatenev%3Atox&package=qtox

**Comment by nazar-pc** [comment]
What about `qtox-unity`, or it is not needed anymore?
BTW, would be nice to see old repo to be shut down, this will let people know that there is another repository now:)

**Comment by nazar-pc** [comment]
I've installed v1.4.0-189-gfd2e585 and as expected - no tray icon. And this can not be called DE problem, since Ubuntu with Unity is one of the most popular Linux DE and bunch of other apps show icon correctly (like ownCloud, which uses Qt 5.5.1). This was the reason `qtox-unity` package existed, but it is not present in new repository.

**Comment by zetok** [comment]
Huh, I thought that there was support for Unity tray..

cc @abbat ?

**Comment by abbat** [comment]
@nazar-pc You have to full uninstall previous version. qTox from OBS repo (software.opensuse.org) has version like fd2e585-**obs** (obs-postfix).

**Comment by nazar-pc** [comment]
Unfortunately, I can't, see #3422

**Comment by abbat** [comment]
@nazar-pc Ahhh, Yakkety not released yet (Oct 2016) and it switched to ffmpeg package :(
Would you try to install qTox from Trusty (14.04) or Precise (12.04) repo (it compiled with static ffmpeg)? I will try to think about workaround for Yakkety later.

**Comment by nazar-pc** [comment]
With 14.04 package:

```
The following packages have unmet dependencies:
 qtox : Depends: libicu52 (>= 52~m1-1~) but it is not installable
        Depends: libvpx1 (>= 1.0.0) but it is not installable
```

With 12.04 package there is only i386 build, and it fails with huge list of dependency conflicts.

I've installed manually dependencies from 16.04 and with `v1.4.0-192-g279225c-obs` I still have exactly the same behavior. There is `Show` menu item now, but qTox itself is immediately opened anyway.

**Comment by nazar-pc** [comment]
Just got new nightly build, now behavior is fixed, thanks!

**Comment by nazar-pc** [comment]
Looks like fix was reverted, since bug returned (I have v1.4.0-206-g8ac47bf-obs, 8ac47bf06b038cd7decf62a114347579488559a7 build currently)

**Comment by abbat** [comment]
Sorry, I forget to commit patch in build script. Fixed now.

**Comment by nazar-pc** [comment]
Thanks, it is good again.
