### ISSUE TITLE
Yakkety build?

### ISSUE THREAD

**Issue by nazar-pc** [qTox/qTox#3422]
qTox for Ubuntu Xenial (16.04) can't be installed on Ubuntu Yakkety (16.10) because of dependencies conflicts. Is it possible to configure nightly builds for Yakkety?

```
nazar-pc@nazar-pc ~>  env LANG=C sudo apt-get install qtox
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qtox : Depends: libavcodec-ffmpeg56 (>= 7:2.4) but it is not installable or
                 libavcodec-ffmpeg-extra56 (>= 7:2.4) but it is not installable
        Depends: libavdevice-ffmpeg56 (>= 7:2.4) but it is not installable
        Depends: libavformat-ffmpeg56 (>= 7:2.4) but it is not installable
        Depends: libavutil-ffmpeg54 (>= 7:2.4) but it is not installable
        Depends: libswscale-ffmpeg3 (>= 7:2.4) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by nazar-pc** [comment]
Workaround is to install manually following packages from [Xenial](https://launchpad.net/ubuntu/+source/ffmpeg/7:2.8.6-1ubuntu2/+build/9350516):
- libavcodec-ffmpeg56_2.8.6-1ubuntu2_amd64.deb
- libavcodec-ffmpeg-extra56_2.8.6-1ubuntu2_amd64.deb
- libavdevice-ffmpeg56_2.8.6-1ubuntu2_amd64.deb
- libavfilter-ffmpeg5_2.8.6-1ubuntu2_amd64.deb
- libavformat-ffmpeg56_2.8.6-1ubuntu2_amd64.deb
- libavresample-ffmpeg2_2.8.6-1ubuntu2_amd64.deb
- libavutil-ffmpeg54_2.8.6-1ubuntu2_amd64.deb
- libpostproc-ffmpeg53_2.8.6-1ubuntu2_amd64.deb
- libswresample-ffmpeg1_2.8.6-1ubuntu2_amd64.deb
- libswscale-ffmpeg3_2.8.6-1ubuntu2_amd64.deb

**Comment by abbat** [comment]
Still Ubuntu Yakkety not released, temporary PPA is [abbat/tox-yakkety](https://launchpad.net/~abbat/+archive/ubuntu/tox-yakkety):

```
deb http://ppa.launchpad.net/abbat/tox-yakkety/ubuntu yakkety main 
deb-src http://ppa.launchpad.net/abbat/tox-yakkety/ubuntu yakkety main 
```

After release date (Oct 2016) it will be moved to openSUSE build service (OBS)

**Comment by nazar-pc** [comment]
Didn't expect it to be done so fast. Thanks, works for me!

**Comment by zetok** [comment]
Since there's now PPA, closing.

**Comment by nazar-pc** [comment]
I'm not getting new builds from that repository since 10th of August. Also Yakkety was released recently.
Can 16.10 builds be added in not very far future?

**Comment by abbat** [comment]
See #3470. `qtox` package is stable build and not updated after release (Aug 10). `qtox-alpha` is upstream build and updated at 2016-10-16 in Yakkety repo.

**Comment by nazar-pc** [comment]
Thanks, I've explored ppa and installed it already)
