### ISSUE TITLE
Add PGP signatures and authenticode signing

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3427]
When obtaining qTox setup, we currently rely on HTTPS for the download from the tox webpage. We have no guarantee that the binary is exactly the binary that the developer uploaded - it can be modified by, for example, a different disgruntled developer who has access to the tox webpage.

The solution to this problem is to include PGP signatures for the setup files, portable package, and source code tarballs. This makes it possible for us to verify the files come from the developer. This solution does not cost any money to implement.

On Windows, the setup files and binaries should additionally be authenticode signed. This provides an additional benefit of Windows SmartScreen filter not interfering with installation or execution of qTox. On older Windows systems, such as Windows 7, it also removes the red/yellow warning screen when installing, instead showing a pleasant blue information screen instead. This solution requires purchase of a signing certificate, which can cost ~70$ per year or less if you look around, and there are also some ways of obtaining it for free if the software is classified as FOSS.

This is important for security focused tools, and to security minded people.

**Comment by zetok** [comment]
Note: due to cost, and reasons, authenticode will not be used.
