### ISSUE TITLE
Formatting symbols not removed but replaced by spaces

### ISSUE THREAD

**Issue by GoldsteinE** [qTox/qTox#3429]
##### Brief Description

OS: Windows 10
qTox version: v1.4.1-1-g06d78dc
Commit hash:  06d78dcdee7bfe9a320fe91662f34227d74c3916
toxcore:  0.0.0 (I don't know, but it shows that)
Qt:  5.5.1
…

Reproducible: Always
##### Steps to reproduce
1. Switch 'Markdown' to 'Don't Show Formatting Characters' in Settings.
2. Send message `"_test_"` (without "") to anyone.
##### Observed Behavior

Symbols '_' are substituted by space.
##### Expected Behavior

Symbols '_' should be removed.
##### Additional Info

![default](https://cloud.githubusercontent.com/assets/12019211/16312402/49c42ee8-397d-11e6-80a8-464f9388f400.PNG)

**Comment by zetok** [comment]
@Artom-Kozincev edited your post to preserve formatting characters.

**Comment by zetok** [comment]
Fixed in https://github.com/tux3/qTox/pull/3434/commits/fca5f15532ddbc21d70e6295d0742218cbc6fe1e, thus closing.
