### ISSUE TITLE
qTox segfault (with backtrace)

### ISSUE THREAD

**Issue by DanielFragaBR** [qTox/qTox#343]
I compiled qtox and it segfaults:

No settings file found, using defaults
Settings: Loading from  ":/conf/settings.ini"
Using embeded bootstrap nodes list
"Loaded translation en"
[New Thread 0x7fffda0ff700 (LWP 17842)]
[Thread 0x7fffda0ff700 (LWP 17842) exited]
[New Thread 0x7fffda0ff700 (LWP 17846)]
[New Thread 0x7fffd56f0700 (LWP 17847)]
[New Thread 0x7fffd55ef700 (LWP 17848)]
[New Thread 0x7fffd4dee700 (LWP 17849)]
Core starting with IPv6 enabled

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd4dee700 (LWP 17849)]
0x00007ffff79ba18a in kill_messenger () from /usr/local/lib/libtoxcore.so.0
(gdb) bt
#0  0x00007ffff79ba18a in kill_messenger () from /usr/local/lib/libtoxcore.so.0
#1  0x00007ffff79bbdf1 in tox_new () from /usr/local/lib/libtoxcore.so.0
#2  0x000000000043fa8f in Core::start() ()
#3  0x00007ffff50f42fe in QMetaObject::activate(QObject_, int, int, void_*) () from /usr/local/Qt-5.3.2/lib/libQt5Core.so.5
#4  0x00007ffff4e994c6 in ?? () from /usr/local/Qt-5.3.2/lib/libQt5Core.so.5
#5  0x00007ffff4be8003 in start_thread () from /lib64/libpthread.so.0
#6  0x00007ffff40fcf2d in clone () from /lib64/libc.so.6

Any hints?

**Comment by dubslow** [comment]
toxcore is what segfaulted here...

~~Can you recompile toxcore with debugging symbols and repost the trace?~~

Should be fixed by https://github.com/irungentoo/toxcore/commit/ad804855f9b70a6bab88e9ba6362f0f613f6d019. Can you recompile and test?

**Comment by tux3** [comment]
I believe this is fixed, please leave a comment if you still have a crash with the latest toxcore and I'll reopen.

**Comment by DanielFragaBR** [comment]
Yes, it is fixed and now everything is fine. Thank you very much!
