### ISSUE TITLE
Group call not working properly, Group not saving

### ISSUE THREAD

**Issue by Onepamopa** [qTox/qTox#3430]
##### Brief Description

OS: Windows 10 build 10586
qTox version: latest (currently)

3 people in group voice call sucks (robot voice).
Same group, 2 people in the call - perfect.

Groups not saving, no auto-rejoining group.

**Comment by zetok** [comment]
Duplicate of #896, thus closing.

**Comment by Onepamopa** [comment]
"Duplicate of #896, thus closing." opened .... a few years ago and still not fixed ?

**Comment by zetok** [comment]
Yep.

Also, #3359
