### ISSUE TITLE
Log file error "Critical: Unable to move logs"

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#3440]
OS: Windows 7
qTox version: (version numbers in menu `Settings → About`)  
Commit hash:  8d225a8c97a36838092b325ca830c14546f3a0c6 and newer
toxcore:  
Qt:  5.4.2
Hardware:  
…
https://gist.github.com/towlie/9419eea500e99bb95a4a9804d89dd880
Logging itself still works.

**Comment by anoadragon453** [comment]
Code responsible is

```
if(!dir.rename(logFileDir + "qtox.log", logFileDir + "qtox.log.1"))
    qCritical() << "Unable to move logs";
```

Can someone verify the syntax for the rename command works on Windows?

@towlie Do you have any weird permission settings on your qtox.log file? Is there a qtox.log.1 already in the folder? 

Logs should be located on your computer at `C:/Users/noob/AppData/Roaming/tox\qpudge.tox`

**Comment by towlie** [comment]
~~If you mean something like "write protection", there is no such thing.~~ Permissions are fine.
There is no other qtox log file:
![da](https://cloud.githubusercontent.com/assets/6986141/16361803/a5b3fb96-3b9b-11e6-918f-766a3fc6f9f0.jpg)

**Comment by Diadlo** [comment]
@towlie Could you please check value of `logFileDir + "qtox.log"` and `logFileDir + "qtox.log.1"` ?
Will be better to add these two values to error message?

**Comment by towlie** [comment]
There it is:
[18:04:42.791] ../src/main.cpp:180 : Critical: "C:/Users/noob/AppData/Roaming/tox\qtox.log"
[18:04:42.791] ../src/main.cpp:181 : Critical: "C:/Users/noob/AppData/Roaming/tox\qtox.log.1"
I assume it is the mix of / and \ .

**Comment by Diadlo** [comment]
@towlie Hmm... Could you try this?

src/persistenct/settings.cpp:630 change on

```
QString path = QStandardPaths::writableLocation(QStandardPaths::HomeLocation) + "/AppData/Roaming/tox";
return QDir::toNativeSeparators(QDir::cleanPath(path) + QDir::separator());
```

**Comment by towlie** [comment]
No, that doesn't work. Maybe / is right when using qt?? What does it use to create other files and folders?
[18:35:08.703] ../src/main.cpp:169 : Debug: Log file over 1MB, rotating...
[18:35:08.703] ../src/main.cpp:177 : Warning: Unable to remove old log file
[18:35:08.711] ../src/main.cpp:180 : Critical: "C:\Users\noob\AppData\Roaming\tox\qtox.log"
[18:35:08.711] ../src/main.cpp:181 : Critical: "C:\Users\noob\AppData\Roaming\tox\qtox.log.1"
[18:35:08.711] ../src/main.cpp:182 : Critical: Unable to move logs

**Comment by Diadlo** [comment]
@towlie I don't think so. But let's try to add debug `path` value to src/widget/form/chatform.cpp:195
And send some file.

**Added**:
Did you try delete this file manually?

**Comment by towlie** [comment]
I can delete it manually.

**Comment by towlie** [comment]
It doesn't have anything todo with / and \ : 

```
[19:02:23.353] ../src/persistence/settings.cpp:378 : Debug: "Saving global settings at C:/Users/noob/AppData/Roaming/tox\qtox.ini"
```

**Comment by anoadragon453** [comment]
Can you try changing qtox.log.1 to qtox.log.2 in the code and see if that completed successfully?
