### ISSUE TITLE
American Fuzzy Lop (AFL)

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3448]
Try to run qTox with AFL, it will reveal a bunch of interesting crash cases that can be related to security.

http://lcamtuf.coredump.cx/afl/

**Comment by sudden6** [comment]
I don't really know if AFL can be easily used with qTox, since many crashes are triggered by user interaction with the GUI and AFL can't simulate that AFAIK.

**Comment by iphydf** [comment]
@tecithedid I'll ask the same thing here as on your toxcore issue: what interesting crash cases will it reveal? Since you said it _will_ reveal crash cases, you must know at least some of them already. Can you point at one of them?

**Comment by zetok** [comment]
Needed info not provided for over a month, thus closing.
