### ISSUE TITLE
qTox crash on Logout

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3451]
OS: Windows 7 x64
qTox version: qTox version v1.4.1.1-g06d78dc

Reproducible: Always
##### Steps to reproduce

1) Download the 64bit installer for qTox.

2) Install qTox.

3) Start qTox.

4) Create profile.

5) Right click tray icon of qTox and select logout.

6) qTox has crashed.

**Comment by ovalseven8** [comment]
=> #2480

**Comment by ovalseven8** [comment]
There is already an issue => #2480

**Comment by zetok** [comment]
Oh, right. Thanks, closing.
