### ISSUE TITLE
Address space layout randomization

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3452]
OS: Windows 7 x64
qTox version: qTox version v1.4.1.1-g06d78dc

Reproducible: Always

qTox does not appear to be using ASLR (Address space layout randomization) https://en.wikipedia.org/wiki/Address_space_layout_randomization on Windows. I checked this using Process Explorer.

ASLR helps improve security of a program.

**Comment by ghost** [comment]
Perhaps some useful links:
https://developer.pidgin.im/ticket/15290
https://stackoverflow.com/questions/24283918/how-can-i-enable-aslr-dep-and-safeseh-on-an-exe-in-codeblocks-using-mingw
https://security.stackexchange.com/questions/24444/what-is-the-most-hardened-set-of-options-for-gcc-compiling-c-c
https://stackoverflow.com/questions/9398046/useful-gcc-flags-to-improve-security-of-your-programs
https://trac.torproject.org/projects/tor/ticket/10065

**Comment by anoadragon453** [comment]
Would this be necessary with the addition of selfrando as described in #3426?

**Comment by ghost** [comment]
selfrando works in addition to ASLR. However, adding ASLR is easy, adding selfrando is not well tested yet.

**Comment by ghost** [comment]
Any progress? ASLR is an important security feature.

**Comment by zetok** [comment]
There is now #3976, which should help on windows, but before it could get merged someone would need to test whether it doesn't break windows builds.
