### ISSUE TITLE
":0 : Warning: QFont::setPixelSize: Pixel size <= 0 (0)" messages on startup

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3459]
I have just noticed that after launching the latest version of qTox (`1.4.0-228-g9694d6b-1`) that I get these warning messages:

> [12:32:45.768] :0 : Warning: QFont::setPixelSize: Pixel size <= 0 (0)
> [12:32:45.768] :0 : Warning: QFont::setPixelSize: Pixel size <= 0 (0)

This is the full output:

> [12:32:34.978] src/persistence/settings.cpp:122 : Debug: "Loading settings from /home/user/.config/tox/qtox.ini"
> [12:32:35.156] src/ipc.cpp:46 : Debug: Our global IPC ID is  14474784268914767629
> [12:32:35.157] src/main.cpp:197 : Debug: built on:  09:15:50 Jul  1 2016 ( 1467364516 )
> [12:32:35.186] src/main.cpp:198 : Debug: commit:  built without git 
> 
> [12:32:35.186] src/nexus.cpp:71 : Debug: Starting up
> [12:32:44.500] src/persistence/profile.cpp:86 : Debug: Loading tox save  "/home/user/.config/tox/toxUsername.tox"
> [12:32:44.771] src/persistence/settings.cpp:387 : Debug: "Saving global settings at /home/user/.config/tox/qtox.ini"
> [12:32:45.122] src/persistence/settings.cpp:305 : Debug: Loading personal settings from "/home/user/.config/tox/toxUsername.ini"
> [12:32:45.768] :0 : Warning: QFont::setPixelSize: Pixel size <= 0 (0)
> [12:32:45.768] :0 : Warning: QFont::setPixelSize: Pixel size <= 0 (0)
> [12:32:47.045] src/core/core.cpp:232 : Debug: Loading user profile
> [12:32:47.045] src/persistence/profile.cpp:243 : Debug: Loading tox save  "/home/user/.config/tox/toxUsername.tox"
> [12:32:47.048] src/widget/systemtrayicon.cpp:65 : Debug: Using GTK backend
> [12:32:47.164] src/core/core.cpp:128 : Debug: Core starting with IPv6 enabled
> [12:32:50.636] src/core/core.cpp:403 : Debug: "Connecting to 194.249.212.109:33445 (fluke571)"
> [12:32:50.637] src/core/core.cpp:403 : Debug: "Connecting to 185.25.116.107:33445 (MAH69K)"
> [12:32:55.136] src/core/core.cpp:403 : Debug: "Connecting to 144.76.60.215:33445 (sonOfRa)"
> [12:32:55.137] src/core/core.cpp:403 : Debug: "Connecting to 23.226.230.47:33445 (stal)"
> [12:32:58.949] src/core/core.cpp:370 : Debug: Connected to the DHT
> [12:32:58.950] src/persistence/profile.cpp:308 : Debug: Saving tox save to  "/home/user/.config/tox/toxUsername.tox"
> [12:35:58.683] src/widget/systemtrayicon.cpp:99 : Debug: Deleting SystemTrayIcon
> [12:35:58.730] src/persistence/profile.cpp:308 : Debug: Saving tox save to  "/home/user/.config/tox/toxUsername.tox"
> [12:35:58.968] src/persistence/settings.cpp:522 : Debug: Saving personal settings at  "/home/user/.config/tox/toxUsername.ini"
> [12:35:59.224] src/persistence/settings.cpp:387 : Debug: "Saving global settings at /home/user/.config/tox/qtox.ini"
> [12:35:59.282] src/main.cpp:299 : Debug: Clean exit with status 0

I am running Ubuntu GNOME 16.04 with GNOME 3.20.

**Comment by sudden6** [comment]
@antis81 could that have anything to do with your recent PR?

**Comment by antis81** [comment]
Thanks for reporting!

Yeah, this is very likely a problem with the singleton instances `Style` & `Settings`. Not a big deal. Qt just falls back to a default font in this case. Looking into that later today. Anyway, it's a bug.
