### ISSUE TITLE
64 bit and 32 bit installers ... change the name of setup file

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3460]
Setup file name for 64 and 32 bit versions is the same - **setup-qtox.exe**

OS: Windows

**Comment by zetok** [comment]
That would break links. Is there a **good** reason for it?

**Comment by ghost** [comment]
No good reason for it ... please, find out a way to identify 64bit setup file and 32bit one. For example, release zip versions of both installers to be downloaded. In one folder, there is no way to keep both installers due to the same file name. There is no any mark in setuped qtox for 64 or 32bit version either. Nothing in "about" section, nor in window's title. Thank you for your attention to this issue.

**Comment by ghost** [comment]
In portable versions is the same thing ... no any marks for 64bit and 32bit qTox

**Comment by tux3** [comment]
Why would you download both installers, though?
You only need the one corresponding to your hardware, or the 32bit one if you're not sure.

**Comment by ghost** [comment]
thank you for the answer ... anyway I'm only download binaries ... what is not make sense for the coders ....

**Comment by ghost** [comment]
Other software such as OpenVPN has clear filename: name_x64.exe.
It's best to add _x86 and _x64.

I'll download both because I have both OSes.

**Comment by ghost** [comment]
setup-qtox_x86.exe
setup-qtox_x64.exe

**Comment by initramfs** [comment]
This isn't a strong argument but I prefer to differentiate between the 32-bit and 64-bit installers. Names like "setup-qtox.exe" and "setup-qtox64.exe" would fit well with the established ecosystem of "installer naming" in Windows (at least, from what I have seen).

**Comment by zetok** [comment]
@initramfs is the preference important enough to break all links?

**Comment by zetok** [comment]
Hmm, alternatively we could keep both links..

@tux3 could you add `ln -s` for ~~64 bit~~ installers?

**Comment by initramfs** [comment]
@zetok Hence me saying "not a strong arugment". If it will break links, don't bother. But if the same links can be retargetted, I don't see why not.

**Comment by sudden6** [comment]
I also support the idea of providing differently named files. For not breaking links, maybe we could redirect to 32bit by default, because it will run everywhere.

**Comment by tux3** [comment]
Done, since we also have version numbers the installers are named like setup-qtox64-1.8.1.exe and setup-qtox32-1.8.1.exe
