### ISSUE TITLE
[Windows] Signature files for 64 bit and 32 bit installers are not found

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3461]
> Not Found
> 
> The  requested URL /qtox/win64/setup-qtox.exe.asc was not found on this server.
> 
> Not Found
> 
> The  requested URL /qtox/win32/setup-qtox.exe.asc was not found on this server.

OS: Windows

**Comment by tux3** [comment]
Our update server script was accidentally cleaning up and deleting the signature files periodically, we're working on a solution.

**Comment by tux3** [comment]
This has been fixed by updating the maintenance scripts.
