### ISSUE TITLE
OBS should provide stable releases

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#3470]
At the moment, @abbat is updating the packages for qTox when he has enough time (2 - 3 times per week).

I guess, it would be a good thing if OBS would also provide packages with the stable releases because they has been created for a good reason (to provide releases with less bugs for the normal users).

So, my suggestion:
The default should be -> using the stable releases
For more advanced users -> They can use the upstream releases (the releases @abbat already provides)

**Comment by zetok** [comment]
> For more advanced users -> They can use the upstream releases

What "upstream releases" ?

**Comment by ovalseven8** [comment]
> For more advanced users -> They can use the upstream releases
> 
> > What "upstream releases" ?

I should have said latest commit

**Comment by zetok** [comment]
> I should have said latest commit

And how would they get it?

**Comment by abbat** [comment]
Resume from IRC:
- Next stable release freezes in "**qtox**" package;
- Upstream releases moved to "**qtox-alpha**" package (not "nightly" because it is not automatic nightly release).

Correct me if I'm wrong.

**Comment by zetok** [comment]
@abbat if you could, comment here when things on OBS will be done, so that issue could be closed :)

**Comment by abbat** [comment]
Done.
