### ISSUE TITLE
Desktop sharing doesn't work when there's no camera attached

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#3476]
##### Brief Description

Desktop sharing doesn't work when there's no camera attached.

OS: Linux
Commit hash:  a01293f81e58409436f7bab897cc6c2fa2a66f63
Qt:  5.6.1

Reproducible: Always
##### Steps to reproduce
1. Start qTox on system that has no camera attached, and didn't have one attached
2. Go to settings in order to try to use `Desktop` as video device
##### Observed Behavior

Even though device seems to be selected, there's no screen in screen preview, and logs don't show info about screen size.
##### Expected Behavior

Video preview should be shown
##### Additional Info

Note: I've tried to reproduce that after detaching camera without restarting OS, but I wasn't able to.

**Comment by abbat** [comment]
Steps to reproduce:
- Attach camera (or run qTox with attached camera);
- Switch to camera in preview tab;
- Change tab;
- Detach camera;
- Return to settings tab and try to switch to Desktop camera;

**Comment by BiTOk** [comment]
I take it.
