### ISSUE TITLE
Buttons translation bug

### ISSUE THREAD

**Issue by a68366** [qTox/qTox#3479]
##### Brief Description

OS: xUbuntu 16.04
qTox version: v1.4.0-233-g4872eb3-obs
Commit hash:  4872eb3cc365e8cfea648a764f4d5c1d496cac65
toxcore:  0.0.0
Qt:  5.5.1

Reproducible: Always
##### Steps to reproduce
1. Receive an executable file
2. Change qTox language (e.g. to Japanese 日本語)
3. Try to open the file from the chat & see the warning (in Japanese, OK)
4. Change qTox language to English
5. Try to open the file again & see that the buttons in the message are not translated (still in Japanese)

You can now go to profile page and try to add/remove profile password. Buttons are in Japanese too.
##### Observed Behavior

Buttons translation is wrong
##### Expected Behavior

Correct translation
##### Additional Info

The bug may be present in other dialogs too.
On step 4 translation seems to be correct when changing to language other than English

![buttons](https://cloud.githubusercontent.com/assets/12549653/16585605/b8613f04-42d2-11e6-997d-8c84c41bf691.png)
![buttons2](https://cloud.githubusercontent.com/assets/12549653/16585849/da6855a0-42d3-11e6-9992-0a8b3f9b7acd.png)

**Comment by Diadlo** [comment]
OS: Arch linux
Qt: 5.7.0

For me these buttons are always translated on system language
