### ISSUE TITLE
[regression] non-markdown text formatting is broken

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#3496]
##### Brief Description

`/me action` should be blue
`> quote` should be green

qTox version: qTox version v1.4.0-246-g2d06b99
Commit hash:  2d06b9960c60f1fc886ae04c595bd9a921cff316
toxcore:  0.0.0
Qt:  5.5.1

Reproducible: Always
##### Steps to reproduce
1. type `/me action` or `> quote`
##### Observed Behavior

Text is not in color.
##### Expected Behavior

Text should be colored.
##### Additional Info

![no color](https://cloud.githubusercontent.com/assets/3148759/16671890/349d161a-449a-11e6-82db-ff12cb1c438a.png)

what was before:
![quote](https://cloud.githubusercontent.com/assets/3247291/15835404/dcae6e20-2c40-11e6-9190-62a4a2799271.gif)
![quote and action](https://cloud.githubusercontent.com/assets/3148759/7788222/14d8592e-022a-11e5-86b2-887df0727e69.png)

**Comment by zetok** [comment]
cc @antis81 ?

**Comment by a68366** [comment]
Introduced in 67136e29ed0027fe8942033032bda437ecdc0e0b

**Comment by antis81** [comment]
@a68366 Thanks for analysis! Looks like the base stylesheet requires a bit of extension…
