### ISSUE TITLE
Audio calls can cause memory corruption

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#35]

**Comment by dubslow** [comment]
How well do you have this tracked down? I can throw a full blown debugging run at it...

**Comment by tux3** [comment]
Barely. It's pretty hard to track down.

**Comment by msteinbeck** [comment]
The new Audiobuffer based on a non locking circular ringbuffer will be ready soon.

**Comment by tux3** [comment]
I just found out that I'm completely retarded and my QTimers and other call objects are happilly living in the wrong thread. 
This could explain the corruption and/or pulseaudio crashes since this is not even supposed to work and explicitely forbidden by Qt.

**Comment by tux3** [comment]
Actually, I might just have fixed the memory corruption with 6ba8be350395f93dca53a0745213396cadcdb2fb

I've had an audio call last 10 minutes (and still going) without crashing on Windows.

If nobody can reproduce anymore, I'll close this bug.

**Comment by msteinbeck** [comment]
This commit fixes some bugs I had some problems with for the ringbuffer, very nice!

**Comment by tux3** [comment]
It seems to be fixed. Finally.
