### ISSUE TITLE
Desktop capture not work with NVIDIA discrete video card

### ISSUE THREAD

**Issue by VaginAY** [qTox/qTox#3500]
##### Brief Description

OS: Linux Debian 8
qTox version: Nightly
Commit hash:  -
toxcore:   0.0.0
Qt:  5.6.1
Hardware:  Nvidia Quadro k600

Reproducible: Always
##### Steps to reproduce
1. Run qtox.
2. Go to Audio/Video.
3. Set video device : Desktop
##### Observed Behavior

Don't see desktop, only avatar in preview window
and in videocall.
##### Expected Behavior

Want to see desktop in preview window
and in videocall.
##### Additional Info

In debug mode (running from terminal) when
I set desktop as video device, see next information:
[12:11:25.724] src/video/camerasource.cpp:209 : Debug: Opening device  "x11grab#:0"
Invalid MIT-MAGIC-COOKIE-1 key[x11grab @ 0x1c86f80] Cannot open display :0, error 1.
In log file see next information:
[12:04:00.560] src/video/camerasource.cpp:209 : Debug: Opening device  "x11grab#:0"
[12:04:00.562] src/video/camerasource.cpp:225 : Warning: Failed to open device!

my $DISPLAY:
$ echo $DISPLAY
:1

On other computer with integrated video card 
$ echo $DISPLAY
:0.0
And all works.

**Comment by sudden6** [comment]
I guess you are using the Nvidia propertary driver?

Anyway, we shouldn't depend on the display beeing :0

**Comment by b4n** [comment]
This probably has indeed nothing to do with the hardware but on x11grab opening the wrong display.

**Comment by VaginAY** [comment]
Good day!
Thank you for fast reply.
1. Yes, i use propertary driver, installed through debian apt system 
   (nvidia-driver, nvidia-dkms). 
2. Today (2016-07-13) i get nightly update and behavior changed.
   There is no desktop in preview window and in videocall, 
   but in log and in properties i see another information.
   -  In properies, when i setup desktop, added 3 new options:
     Screen 1, Screen 2 and Select Region.
   - In log :

```
 #  Select Screen 1:
[09:40:29.225] src/video/camerasource.cpp:218 : Debug: Opening device  "x11grab#:0"
Invalid MIT-MAGIC-COOKIE-1 key[x11grab @ 0x3176320] Cannot open display :0+0,0, error 1.
[09:40:29.225] src/video/camerasource.cpp:232 : Warning: Failed to open device!
[09:40:53.314] src/video/camerasource.cpp:300 : Debug: Closing device  "x11grab#:0"
#  Select Screen 2:
[09:40:53.314] src/video/camerasource.cpp:218 : Debug: Opening device  "x11grab#:0"
Invalid MIT-MAGIC-COOKIE-1 key[x11grab @ 0x32889c0] Cannot open display :0+1920,0, error 1.
[09:40:53.314] src/video/camerasource.cpp:232 : Warning: Failed to open device!
[09:40:57.443] src/video/camerasource.cpp:300 : Debug: Closing device  "x11grab#:0"
# Select Region:
[09:41:12.238] src/video/camerasource.cpp:218 : Debug: Opening device  "x11grab#:0"
Invalid MIT-MAGIC-COOKIE-1 key[x11grab @ 0x3156d00] Cannot open display :0+12,418, error 1.
[09:41:12.238] src/video/camerasource.cpp:232 : Warning: Failed to open device!
[09:41:28.173] src/video/camerasource.cpp:300 : Debug: Closing device  "x11grab#:0"
```

I have two monitors on my PC, they configured through xorg.conf:

```
# nvidia-settings: X configuration file generated by nvidia-settings
# nvidia-settings:  version 319.82  (pbuilder@cake)  Mon Feb 10 11:38:38 UTC 2014

Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "Screen0" 0 0
    InputDevice    "Keyboard0" "CoreKeyboard"
    InputDevice    "Mouse0" "CorePointer"
    Option         "Xinerama" "0"
EndSection

Section "Files"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Mouse0"
    Driver         "mouse"
    Option         "Protocol" "auto"
    Option         "Device" "/dev/psaux"
    Option         "Emulate3Buttons" "no"
    Option         "ZAxisMapping" "4 5"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Keyboard0"
    Driver         "kbd"
EndSection

Section "Monitor"
    # HorizSync source: edid, VertRefresh source: edid
    Identifier     "Monitor0"
    VendorName     "Unknown"
    ModelName      "HP LP2475w"
    HorizSync       30.0 - 94.0
    VertRefresh     48.0 - 85.0
    Option         "DPMS"
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce GTX 560"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    Option         "Stereo" "0"
    Option         "nvidiaXineramaInfoOrder" "DFP-0"
    Option         "metamodes" "DFP-0: nvidia-auto-select +0+0, DFP-2: nvidia-auto-select +1920+0"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection
```

One of monitors rotated by 90 degrees
I think, that :0+1920,0 and :0+0,0 in log very similar with
+1920+0 and :0+0 in metamodes in xorg.conf.
My xorg.conf was created by nvidia-settings.

**Comment by sudden6** [comment]
@VaginAY 

@b4n already developed a fix for this, can you test https://github.com/tux3/qTox/pull/3505 ?

**Comment by VaginAY** [comment]
After last update (2016-07-17) all works great!
Thank you.
