### ISSUE TITLE
Suboptimal positioning of abort button in filetransferwidget

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#3508]
##### Brief Description

Someone sending you a message while you are about to click accept on a filetransfer can lead to clicking abort instead.

Commit hash:  https://github.com/tux3/qTox/commit/939c97a0e9d2e4ff2d26a52f8ccfcef9b8a6bbf3

Reproducible: Always 
##### Steps to reproduce
1.  Alice sends Bob a file
2. Bob wants to click "Accept" in the filetransferwidget
3. Alice sends a new message
4. Because of the new message Bob's filetransferwidget shifts upwards and Bob clicks "Cancel"

Maybe the filetransferwidget can be redesigned so the accept and cancel buttons are side by side instead of above each other so this mistake will be prevented.

**Comment by zetok** [comment]
Related: #2597

**Comment by zetok** [comment]
Hmm, now that I look at it, isn't it just a duplicate of #2597 ?

**Comment by ProMcTagonist** [comment]
yes

**Comment by sudden6** [comment]
yes
