### ISSUE TITLE
File transfers exceed physical limitations

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#351]
When receiving file from older µTox version:
![2014-09-28 hexafluoride bully](https://cloud.githubusercontent.com/assets/3148759/4462671/f0712f76-48c4-11e4-9609-03dc22300462.png)
![2014-09-28 hexafluoride bully](https://cloud.githubusercontent.com/assets/3148759/4462672/f224e5b0-48c4-11e4-81dd-f3d49b3a0452.png)

It speed up to over 1.5 GB/s...

**Comment by dubslow** [comment]
My bad, I can't debug right now but I'll get around to it within a day hopefully

**Comment by apprb** [comment]
I'll do it.

**Comment by dubslow** [comment]
Twas https://github.com/tux3/qTox/commit/a4d42a713621344a58b1cd2aad02aface0dd422d

**Comment by zetok** [comment]
There's still similar behaviour after resuming file transfer
