### ISSUE TITLE
No qTox icon in cairo-dock (and taskbar menu)

### ISSUE THREAD

**Issue by antis81** [qTox/qTox#3510]
##### Brief Description

Missing qTox icon in taskbar within certain (official) desktop environments.

OS: Linux (Lubuntu 16.04)  
qTox version: v1.4.0-245-g99ce719  
Commit hash: 99ce719b800b5fedeb47eb848268976dcbf96fc7
toxcore: 0.0.0
Qt: 5.5.1
Hardware: MacBook 2.1 (late 2007)
…

Reproducible: Always
##### Steps to reproduce
1. Start system and…
2. …login to desktop environment.
##### Observed Behavior

This issue exists probably since qTox itself was born. On linux systems, the XDG "requirements" are not met and no entry is made in the "start menu", after installing qTox. Also, when adding a qTox starter to some task bar (in my case cairo-dock), the icon it not visible until qTox is started. Then the correct icon shows up (see screenshots).
##### Expected Behavior

qTox icon always visible.
##### Additional Info
1. Appearance when qTox is not running (running with just main widget visible)
   ![qtox-no-icon](https://cloud.githubusercontent.com/assets/440517/16835754/689e9ea0-49ba-11e6-8e6f-669881d26378.png)
2. Appearance, when qTox is running and a subwidget (e.g. dialog) is opened
   ![qtox-with-icons](https://cloud.githubusercontent.com/assets/440517/16835912/3ea0a3e0-49bb-11e6-8498-cc851e1c032e.png)

**Comment by zetok** [comment]
> On linux systems, the XDG "requirements" are not met and no entry is made in the "start menu", after installing qTox. Also

Err. It seems to be added just fine on MATE DE?

Is the binary a compiled one, or from repo?

> Also, when adding a qTox starter to some task bar (in my case cairo-dock), the icon it not visible until qTox is started. Then the correct icon shows up (see screenshots).

Dunno about that – is cairo-dock even using the .desktop entry according to XDG standard?

**Comment by antis81** [comment]
> Is the binary a compiled one, or from repo?

From repo of course :)

> Dunno about that – is cairo-dock even using the .desktop entry according to XDG standard?

Yes, it does.

**Comment by zetok** [comment]
> From repo pf course :)

Are you using the right repo?

**Comment by antis81** [comment]
> Are you using the right repo?

Not sure, using `nightly` repo. Here's what `apt install` says:  

``` bash
sudo apt install --reinstall qtox
[sudo] password for nils: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 15.0 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://pkg.tox.chat/debian nightly/release amd64 qtox amd64 694-99ce719 [15.0 MB]
Fetched 15.0 MB in 15s (947 kB/s)                                                                                                                            
(Reading database ... 294965 files and directories currently installed.)
Preparing to unpack .../qtox_694-99ce719_amd64.deb ...
Unpacking qtox (694-99ce719) over (694-99ce719) ...
Setting up qtox (694-99ce719) ...
```

To me it looks, like trigger for menu is missing.

**Comment by zetok** [comment]
Yeah, you're not using the right repo.

https://software.opensuse.org/download.html?project=home%3Aantonbatenev%3Atox&package=qtox

**Comment by antis81** [comment]
Hm ok, thanks. I'll switch that. I have two questions then:
1. Is the nightly repo invalid now?
2. Is there a way we can "automagically migrate" for existing users? At least we should tell them to change that. This is the second time now I have to do it within just 1 year time period. I have several test installs running on commuters of "non-developer" friends and if they would get a message in this case, they could do it by themselves.

**Comment by zetok** [comment]
> Is the nightly repo invalid now?

It's deprecated.

> Is there a way we can "automagically migrate" for existing users?

Well, it could be done via script that would run when qTox is installed that would add new repo and its key.

> At least we should tell them to change that.

This was supposed to be done via changelog message that users would get when updating to newer qTox version on deprecated repo. Aside from that, users could get also some GUI pop-up, also done via script that would notify them about the change.

# 

I've heard that @Encrypt is now "maintaining" those packages.
@Encrypt mind doing that stuff?

**Comment by antis81** [comment]
After repo change, looks like it works (need to verify), but apt install now correctly states:

``` bash
sudo apt install qtox
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  qtox
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
Need to get 4,467 kB of archives.
After this operation, 6,189 kB of additional disk space will be used.
Get:1 http://download.opensuse.org/repositories/home:/antonbatenev:/tox/xUbuntu_16.04  qtox 201607141019~2a420b8 [4,467 kB]
Fetched 4,467 kB in 2s (1,659 kB/s)
Selecting previously unselected package qtox.
(Reading database ... 294964 files and directories currently installed.)
Preparing to unpack .../qtox_201607141019~2a420b8_amd64.deb ...
Unpacking qtox (201607141019~2a420b8) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Setting up qtox (201607141019~2a420b8) ...
```

Btw. I changed locale to English… :)

**Comment by antis81** [comment]
Yeah, works finally! Thanks!

![qtox-icon-visible](https://cloud.githubusercontent.com/assets/440517/16838199/58c3473e-49c8-11e6-9d68-be97fa628416.png)

Feel free to close.
