### ISSUE TITLE
Deprecation of the old repo & prompt users to move to the new one

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#3517]
##### Brief Description

Since repo @ tox.chat is deprecated, users should be informed about this.

Should be done via changelog, and interactive GUI pop-up when users update to newer qTox version using the old repo. Both GUI & changelog should contain instructions on how to move to the new repo.

`<tux3> Hm, I could probably have qtox depend on "zenity | kdialog" and have the postinst script pick either`

@Encrypt when this can be expected to be done?

**Comment by ghost** [comment]
I am still receiving updates from there in their Wily section (even though I'm on Xenial), so does this mean that that supply of updates will be cut off soon though users will be given a notification through qTox of this? Or...? Also, I see you say "on how to move to the new repo", where is this repo and how does one add it? Or perhaps I don't understand you correctly?

**Comment by zetok** [comment]
> I am still receiving updates from there in their Wily section (even though I'm on Xenial), so does this mean that that supply of updates will be cut off soon though users will be given a notification through qTox of this? Or...?

The plan is to just notify about deprecation of repo every time qTox package is updated, until people will move on to the new repo.

> Also, I see you say "on how to move to the new repo", where is this repo and how does one add it? Or perhaps I don't understand you correctly?

Have you tried looking at [README.md](https://github.com/tux3/qTox/blob/3822511ddefdfb5a29641823fcd04b4e805244f7/README.md#qtox) ?

**Comment by ElLamparto** [comment]
What is the new repo? I believe that on the tox.chat download page / Debian, there is still the @ tox.chat repo defined.

**Comment by zetok** [comment]
> I believe that on the tox.chat download page / Debian, there is still the @ tox.chat repo defined.

Yes, nothing can be done about tox.chat website being broken.

**Comment by zetok** [comment]
@ElLamparto the same question – have you tried looking at readme.md? Also, qTox has its own website, which does point to the right repo: https://qtox.github.io/

---

Status update: apparently @Encrypt doesn't have access to the stuff that needs to be changed, so @tux3 will need to do it.

**Comment by Encrypt** [comment]
Indeed.

As I told @zetok on IRC:
- @tux3 is the one packaging qTox on build.tox.chat, and
- @nurupo is the one who has the keys of build.tox.chat & pkg.tox.chat

Therefore, I can not do much, I'm afraid ¯_(ツ)_/¯

**Comment by sudden6** [comment]
Most users probably have already migrated.
