### ISSUE TITLE
osx building script fails

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#3520]
##### Brief Description

Something with toxcore, perhaps libsodium (or some other dep?) get bumped in brew(?)

OS: OS X

Reproducible: Always

https://travis-ci.org/tux3/qTox/jobs/145272353

cc @RowenStipe

**Comment by sudden6** [comment]
Seems like sed is missing or changed paths:

`/usr/local/bin/glibtoolize: line 401: /usr/local/Library/ENV/4.3/sed: No such file or directory`

**Comment by Diadlo** [comment]
May be disable osx builds in travis, until not fixed? It will help to avoid of many "broken" builds

**Comment by zetok** [comment]
Could someone check if building qTox on osx works locally?

If it does, then it's a problem with travis, and it needs to be reported to them.

**Comment by zetok** [comment]
I was told that building toxcore locally on osx works, so I've filled an issue https://github.com/travis-ci/travis-ci/issues/6352

**Comment by zetok** [comment]
Fixed in #3584, thus closing.
