### ISSUE TITLE
[Regression] Reset call buttons after swich on other friend

### ISSUE THREAD

**Issue by Diadlo** [qTox/qTox#3521]
##### Brief Description

OS: Linux
qTox version: v1.4.0-319-gf970bb5.
Commit hash: f970bb5eaca45c5500b1723ff82116e5ffb0a878
Qt: 5.7.0

Reproducible: Always
##### Steps to reproduce
1. Start call to friend A (call buttons change colors).
2. Open dialog with friend B.
3. Return to dialog with friend A.
##### Observed Behavior

All buttons are green (like, call stoped).
##### Expected Behavior

Red call button.
##### Additional Info

![spectacle lh3712](https://cloud.githubusercontent.com/assets/6306608/16899651/8b70464a-4c1c-11e6-9175-4bbefbc97143.png)

**Comment by zetok** [comment]
bbefe0119d405cf7bcc0e7a90571b1c18b993817
