### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by farseerfc** [qTox/qTox#3523]
It's more than 2 month since the last release. (1.4.1.1 is just fixing build issue for macOS thus not a new release). I can see many new features and bug fixes go into the master branch, but distributions cannot make a stable package without a fixed release (at least it is hard to).
So please release a new stable version. Thanks.

**Comment by zetok** [comment]
There are now milestones for releases, which contain bare minimum required for new version release.

Next release: https://github.com/tux3/qTox/milestone/3

v1.6.0 is also "planned", so releases hopefully will happen more frequently.

Aside from the bare minimum set in release milestone, anything that is ready in between releases for merge also gets in for next release.

**Comment by farseerfc** [comment]
Wow, thanks for the explanation. Waiting for v1.5.
But bug-fixing releases like 1.4.2 should be helpful, provided you have time to tag that.
It is only my suggestion, take your time.

**Comment by farseerfc** [comment]
Thanks for v1.5.0 again!
