### ISSUE TITLE
Contact online status keeps changing many times in seconds (on/off)

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3525]
I see this happen the first time ever. The contact keeps going online/offline 1-2 times per second. His green light is blinking.

This is a critical bug, and also a very unexpected and surprising behavior.
Not sure if this is in toxcore.

 Brief Description

```
OS: Windows / OS X / Linux (include version and/or distro)  
qTox version: 1.4.1
toxcore: toxcore-0.151112_2 
Qt:  5.5.1
OS: FreeBSD 10.3
```

**Comment by dongmaster** [comment]
Is the person you're talking about logged into the same profile on multiple devices at the same time?

**Comment by yurivict** [comment]
This might well be the case.

**Comment by yurivict** [comment]
Tox should fail duplicate account registrations, like Tor does when the same hidden services are attempted to be registered from multiple hosts.

**Comment by yurivict** [comment]
Made a feature suggestion for the toxcore, closing this bug.

**Comment by zetok** [comment]
> Tox should fail duplicate account registrations, like Tor does when the same hidden services are attempted to be registered from multiple hosts.

Not doable.

> This might well be the case. I know he does alternatively use the same account on different OSes.

And this is not supported, and is going to cause problems – closing as invalid.
