### ISSUE TITLE
Stable version builds

### ISSUE THREAD

**Issue by dolohow** [qTox/qTox#3541]
I can't find stable version of qTox in any repository or as a binary package.  Only nightly is buggy.

**Comment by zetok** [comment]
#3470

Aside from that, distros that package qTox properly do have stable – Arch and Gentoo. Also I hear that FreeBSD has stable.

**Comment by zetok** [comment]
Since 1.5 has been released, closing.

**Comment by dolohow** [comment]
Does it mean that you provide stable builds since 1.5?

**Comment by zetok** [comment]
Should be available on OBS.
