### ISSUE TITLE
Remove profile button

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3546]
Hello!

At the moment it is not possible to remove profile via qtox interface.

It can be usefully to have a possibility to remove profile from the qtox.

Thank you!

**Comment by zetok** [comment]
![profile removal](https://cloud.githubusercontent.com/assets/3148759/17083421/0fd8ea1a-5198-11e6-9eef-63ca1e427525.png)

It is possible. You might be interested in reading https://github.com/tux3/qTox/blob/eb1e0091c420caec8f8e3492b6abb78400cf348b/doc/user_manual_en.md.
