### ISSUE TITLE
qtox profile data folder location in Windows XP

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3548]
##### Brief Description

qtox create profile data folder in Windows XP using path like in Windows Vista and above.

OS: Windows XP
qTox version: v1.4.0-332-geb1e009  
Commit hash: eb1e0091c420caec8f8e3492b6abb78400cf348b 
toxcore: 0.0.0
Qt: 5.5.1

Reproducible: Always
##### Steps to reproduce
1.  Download https://build.tox.chat/job/qTox_build_windows_x86_release/lastSuccessfulBuild/artifact/qTox_build_windows_x86_release.zip
2. Unpack it.
3. Run qtox.exe
4. Create new profile.
5. See `Current profile location`.
##### Observed Behavior
1. qtox create profile in _c:\Documents and Settings\%username%\AppData\Roaming\tox_.
##### Expected Behavior
1. qtox should create profile in _c:\Documents and Settings\%username%\Application Data\tox_.  
   Windows XP:
   <pre>
   echo %APPDATA%
   </pre>
   <pre>
   C:\Documents and Settings\Administrator\Application Data
   </pre>

Windows Vista and above:

<pre>
echo %APPDATA%
</pre>

<pre>
C:\Users\Administrator\AppData\Roaming
</pre>

Thank you!

**Comment by Diadlo** [comment]
AFAIK, Windows XP official unsupported by Microsoft

**Comment by zetok** [comment]
Not going to be changed, since XP is long since not supported, current way works, and change would either break stuff for all the people who still are using qTox on XP, or result in additional code for XP to maintain, for no good reason.
