### ISSUE TITLE
Fault connections in log

### ISSUE THREAD

**Issue by BiTOk** [qTox/qTox#3553]
##### Brief Description

OS: Windows 10 x64
qTox version: (version numbers in menu `Settings → About`)  
Commit hash:  e6e666fa8ce36cd3792d4536a59ab2b65fd5b546
toxcore:  0.0.0
Qt:  5.5.1
Hardware:  standard
…

Reproducible: Always 
##### Steps to reproduce
1. Start qTox
2. See log file
##### Observed Behavior

Each start I see those lines:
`
src/core/core.cpp:128 : Debug: Core starting with IPv6 enabled
src/core/core.cpp:301 : Debug: Self avatar not found, will broadcast empty avatar to friends
:0 : Warning: QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
src/widget/systemtrayicon.cpp:90 : Debug: Using the Qt backend
:0 : Warning: QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
`

What's wrong with those connections?

**Comment by sudden6** [comment]
I don't get these on Linux, maybe Windows specific?

Also these messages seem to come from inside qt, so maybe upstream issue?

**Comment by Diadlo** [comment]
https://bugreports.qt.io/browse/QTBUG-49174
Seems upstream problem.

**Comment by sudden6** [comment]
According to the bugreport this doesn't cause any issues besides the messages, thus closing.
