### ISSUE TITLE
Remove timezone from logs

### ISSUE THREAD

**Issue by BiTOk** [qTox/qTox#3554]
For some people timezone is personal information. May be better use in log time from start application?

**Comment by sudden6** [comment]
Are you meaning the logs for debugging or chatlogs?

**Comment by BiTOk** [comment]
Of course, I'm about debugging logs.

**Comment by zetok** [comment]
> May be better use in log time from start application?

No. What should be used, is UTC.

**Comment by sudden6** [comment]
Yep, UTC should be used.

**Comment by Diadlo** [comment]
Should we mark in log, that time in UTC? If yes, where we should write it?
