### ISSUE TITLE
qTox_build_windows_x86-64_release.zip - no qtox.exe file

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3557]
**qTox_build_windows_x86-64_release.zip**  archive # 744 contains no **qtox.exe**. Maybe it's more missing files in thise package, I do not check all of the rest.
OS: Windows

**Comment by nurupo** [comment]
Is the issue fixed now?

**Comment by sudden6** [comment]
Doesn't seem to be relevant for current builds, please reopen if it's still happening for you.
