### ISSUE TITLE
[regression] Linux: No Picture From Webcam In AV Settings / Video Call

### ISSUE THREAD

**Issue by ElLamparto** [qTox/qTox#3562]
##### Brief Description

OS: Linux , Debian Jessie 32 bit  
qTox version v1.4.0-339-ge6e666f-obs

Reproducible: Always
##### Steps to reproduce
1. Start qTox
2. Go to AV Settings
3. The video parameters are correct, but no picture. No video in a video call.

Full log attached:
[qToxNoVideo.txt](https://github.com/tux3/qTox/files/391883/qToxNoVideo.txt)

[14:45:58.461] src/video/camerasource.cpp:219 : Debug: Opening device  "/dev/video0"
[video4linux2,v4l2 @ 0xc9b4d20] No such input format: .
[14:45:58.500] src/video/camerasource.cpp:233 : Warning: Failed to open device!
##### Additional Info

Not long ago it worked correctly.

**Comment by ghost** [comment]
Works as usual for me.

qTox a556762c54de5f4acbcf2f37c84cd7bb7b3b1afa
Debian testing
Linux 4.6.0-1-amd64

**Comment by ElLamparto** [comment]
I have this:
![selection_003](https://cloud.githubusercontent.com/assets/9163437/17272729/7a0c7e14-569e-11e6-8f70-fb5d78e8ff6d.png)

**Comment by ghost** [comment]
I have the same issue on version 1.4.0-339-ge6e666f-obs

```
v4l2-ctl --list-formats-ext

ioctl: VIDIOC_ENUM_FMT
Index: 0
Type: Video Capture
Pixel format: 'YUYV'
Name: YUV 4:2:2 (YUYV)
    Size: Discrete 640x480
        Interval: Discrete 0.033s (30.000 fps)
        Interval: Discrete 0.067s (15.000 fps)
    Size: Discrete 320x240
        Interval: Discrete 0.033s (30.000 fps)
        Interval: Discrete 0.067s (15.000 fps)
    Size: Discrete 160x120
        Interval: Discrete 0.033s (30.000 fps)
        Interval: Discrete 0.067s (15.000 fps)
```

**Comment by antis81** [comment]
As a workaround, switch the video device and you will see the preview.

**Comment by agilob** [comment]
I'm sure I didn't PR somewhere to fix it and it was rejected... I was something like 'click on preview to activate, second click to disable'. Wrote it to prevent camera starting automatically when going to settings.

**Comment by ProMcTagonist** [comment]
@agilob It should just work without workarounds.

**Comment by agilob** [comment]
But... but... I made the PR to fix this issue!

**Comment by ElLamparto** [comment]
@antis81, your workaround does not work in my case - still no picture (but thanks :). utox and toxic both get the video correctly.

**Comment by ghost** [comment]
Tested at commit 59352ae797be37a1d51821df4d06ef07e9b870bb and indeed the same problem remains.

**Comment by wiz21b** [comment]
I confirm I have the same issue on Debian 8, stable, 32 bits. qTox version v1.5.2-175-g9dfdd4e-obs (according to About Box). I got my build from the opensuse repo.

WebCam is properly recognized by qTox, it even works fine as a microphone. But no video shows up. I see the same error as the other post in this thread :+1: 

```
[19:50:48.166 UTC] video/camerasource.cpp:269 : Debug: Opening device  "/dev/video0"
[video4linux2,v4l2 @ 0xb624c00] No such input format: .
[19:50:48.167 UTC] video/camerasource.cpp:283 : Warning: Failed to open device!
```

For a test, I ran qv4l2 (Video4Linux qt test bench) and it runs fine. Gnome cheese works fine too.
I also tested (a bit) utox 0.10.1 and it sees the webcam and is able to display the preview.

Ultra dirty work around : I run qv42l to have a window showing my web cam, then in qTox, I use the "desktop" as a video device. Dirty, but works.

**Comment by ElLamparto** [comment]
@wiz21b, while waiting for a fix, you can use µTox (it is compatible with qTox, uses the same config and AV works perfectly).

**Comment by TheOuterLinux** [comment]
My web cam doesn't show up in the list at all for me, but I'm running a custom made distro from SuseStudio on an old Macbook, so who knows (iSight nonsense); I can get Desktop mirroring to work though. My distro is 32-bit OpenSUSE 13.2 based. If you can get the webcam to work with a screen recorder and then use that with JACK for audio, it may be a crude but temporary fix for now.

Could you edit ~/.config/tox/qtox.ini video section some how?

**Comment by sudden6** [comment]
Does this problem still occur with a recent version of qTox?

**Comment by ghost** [comment]
Not sure but I'm compiling the latest version and will try out the video.

**Comment by ghost** [comment]
Tested on the latest commit on Debian 9 and it looks like video is working.

**Comment by sudden6** [comment]
I'll close this then.
