### ISSUE TITLE
Message sender doesn't printed if first message is incoming file

### ISSUE THREAD

**Issue by BiTOk** [qTox/qTox#3567]
##### Brief Description

OS: Windows 10 x64
Commit hash:  a556762c54de5f4acbcf2f37c84cd7bb7b3b1afa
toxcore:  0.0.0
Qt:  5.5.0

Reproducible: Always
##### Steps to reproduce
1. Write message to anybody
2. Anybody send file to me
3. Anybody write message to me
##### Observed Behavior

Incoming file and message looks like my messages.
##### Expected Behavior

Near incoming file should be Anybody nick.

**Comment by Chiitoo** [comment]
I believe this might have been fixed some time ago already.

While I remember seeing it happen myself, I can't do so any longer.

**Comment by anthonybilinski** [comment]
Confirmed no longer producible on d19ae1ead0db730a800af1e24a7683ca5a08bd79
![image](https://user-images.githubusercontent.com/10469203/154741774-39b4b50a-ef33-4be2-bf16-155823310e4e.png)

Closing.
