### ISSUE TITLE
[regression] action messages have duplicated name

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#3568]
##### Brief Description

Action messages have duplicated name. 

This is a fairly ~recent regression.

OS: Linux
qTox version: v1.4.0-339-ge6e666f
Commit hash: e6e666fa8ce36cd3792d4536a59ab2b65fd5b546
toxcore: 0.0.0
Qt: 5.5.1

Reproducible: Always
##### Steps to reproduce
1. send an action message to some contact, e.g. `/me tests`
##### Observed Behavior

Name is duplicated
##### Expected Behavior

First occurrence of the name should be replaced with an asterisk `*`
##### Additional Info

![name, name everywhere](https://cloud.githubusercontent.com/assets/3148759/17273110/49eaa716-56a2-11e6-98d2-a277cc58466d.png)

**Comment by Diadlo** [comment]
b99a9e494a68f4952a00bbbf8d4624eb0be28e17
