### ISSUE TITLE
Can't open qtox.xz

### ISSUE THREAD

**Issue by Xylemon** [qTox/qTox#360]
Hello, perhaps I'm missing something because when I enter "tar -xJf qtox.xz" to extract the qtox archive it spits out:

tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

Xarchiver seems to open the xz archive but won't extract it. I'm on Slackware 14.1, any ideas?

**Comment by tux3** [comment]
I don't remember ever distributing any xz archives, where did you download that archive from ?

EDIT: Oh, you got it from Tox's Jenkins, I'll see what I can do

**Comment by tux3** [comment]
Okay, this isn't actually a tar.xz archive, it's just a xz archive.

Extract it with "unxz qtox.xz"

**Comment by Xylemon** [comment]
Thank you, unxz was the correct command! I don't know where people on Ask Ubuntu get these incredibly wrong answers.

On a different note, I am unable to launch qtox because I am missing libopencv_core.so.2.3, where should I get this dependency?

**Comment by tux3** [comment]
I would recommand against using the official Tox Project's Jenkins to download qTox, unless you use OS X. Try to use the release here instead https://github.com/tux3/qTox/releases for the time being, such as https://github.com/tux3/qTox/releases/download/qtox-linux-1412174508.44/qtox-linux.tgz

The package you downloaded is known to be "broken". If you want to use it anyway you should be able to download libopencv_core.so.2.3 from Debian's servers : https://packages.debian.org/wheezy/libopencv-core2.3 but it might conflict with other packages on your system.

**Comment by Xylemon** [comment]
Thanks for the info, I'm trying to open the latest Github release but this happens in Xarchiver and terminal: 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by tux3** [comment]
I just tried downloading https://github.com/tux3/qTox/releases/download/qtox-linux-1412175690.8/qtox-linux.tgz and extracting it with "tar xvf qtox-linux.tgz", it seemed to work.

What command did you use ?

**Comment by Xylemon** [comment]
I tried "tar xvzf" earlier and it didn't work, however "tar xvf" did work. It's also weird how it didn't work with Xarchiver. Thanks again, now I'm gonna extract these deb files and make a Slackware package.

**Comment by Xylemon** [comment]
Ok so I had to get Opus and libvpx for Slackware, and after that I still got:

"libopencv_core.so.2.4"

And this is the Github release.

**Comment by tux3** [comment]
I have not tested the .rpm packages since I run debian, but if you tried installing the packages, it should have installed OpenCV 2.4 already since it's in the dependencies. If it didn't then I'll see if I can find the problem.

Otherwise the package you need should be called something like libopencv-core2.4
OpenCV 2.4 is available since 2012, before that it was OpenCV 2.3

**Comment by Xylemon** [comment]
I'm sorry for the confusion, I'm running Slackware so I extracted the Debian archive and installed the dependencies I thought it needed. I did not know OpenCV was a dependency, so therefore the error above. I'm compiling OpenCV right now to fix this, and when I do get qTox running I'll post a list of all the dependencies I needed to get it running on Slackware 14.1

**Comment by Xylemon** [comment]
Also I did find out what's needed to get qTox running on Slackware. If you want, I can add it to the GitHub wiki.

**Comment by dubslow** [comment]
Please do. Might it be worthy of a PR?

**Comment by Xylemon** [comment]
Do you have to go through a PR for a wiki change?

**Comment by dubslow** [comment]
I have no idea lol

**Comment by Xylemon** [comment]
See #899
