### ISSUE TITLE
Code formatting using clang-format & potential switch to established code style

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#3601]
Current qTox code formatting is ~lax, not verified, and not really enforced.

`clang-format` could be used to both format qTox code, and as a checker of whether code has been actually formatted, verified on travis.

If it were to be used as a check, travis would do equivalent of running `clang-format && git diff --exit-code` which would result in travis passing only if code has been formatted & there are no differences after running `clang-format`. If there would be differences, they would be printed, build would fail early & there would be info in travis log about requiring `clang-format` to be run.

As @initramfs said in https://github.com/qTox/qTox/pull/3589#issuecomment-238103043:

> Perhaps a scheme can be created for a source code formatter as well (for example, something like ClangFormat, which can be integrated into QtCreator through a plugin).
# 

The other part is coding style. It's far from being even good, and it seems to reinvent the wheel when there's no need to.

There are already several coding styles out there with guidelines easily available, and they could be used by qTox. Even if not as a perfect drop-in solution, slight adjustments to one of them that is closest to qTox would be less bothersome than reinventing the wheel.

Of course it would be preferable to just use one of styles as drop-in, since it would help assure consistency of the coding style with other projects out there that are already using one of the styles, which most likely would help people to either be already familiar with the style when they want to contribute to qTox, or at least they would have a good reason to get to know coding style, since it's used in other projects as well.

Would be good to use one of those styles:
- [LLVM](http://llvm.org/docs/CodingStandards.html)
- [Google](https://google.github.io/styleguide/cppguide.html)
- [Chromium](http://www.chromium.org/developers/coding-style)
- [Mozilla](https://developer.mozilla.org/en-US/docs/Developer_Guide/Coding_Style)
- [WebKit](https://webkit.org/code-style-guidelines/)

One of those would be nice, since `clang-format` has support for them. And if we decide that none of those is good enough as-is, then even with a slight deviation configuring clang-format would be easier.
# 

Scope of this issue:
- decision whether `clang-format` should be used
  - at all
  - as code style consistency check
    - if check is to be put in place, follow-up on getting it to work on travis
- decision on which coding style among the popular ones would fit qTox needs
  - if none of available ones would be acceptable as-is, specify what needs adjustments in one that is closest to what qTox needs and adjusting it

**Comment by zetok** [comment]
From #3820: change code guidelines to always use curly brackets (`{}`) in `if`s

**Comment by Diadlo** [comment]
Same for `for` statements
