### ISSUE TITLE
All static builds on Jenkins failures lately

### ISSUE THREAD

**Issue by alexeysvrv** [qTox/qTox#3609]
##### Brief Description

OS: Ubuntu 14.04
qTox version: last
Commit hash:  last
toxcore:  last
Qt:  -
Hardware:  AMD X3 450, RAM 4GB
…

Reproducible: Always
##### Steps to reproduce
1. Just to Jenkins last static build all fail. It is necessary to fix it. With these assemblies formed Deb packages for Ubuntu 14.04. Thank you

**Comment by zetok** [comment]
qTox builds for Linux on jenkins are deprecated, use OBS repo instead: https://software.opensuse.org/download.html?project=home%3Aantonbatenev%3Atox&package=qtox

**Comment by alexeysvrv** [comment]
@zetok Thank you for the explanation. Please declare a repository to change somewhere. And why it changed the way?

**Comment by zetok** [comment]
> Please declare a repository to change somewhere. And why it changed the way?

Right, there will be a blog post on https://qtox.github.io/blog that will touch on the topic; basically OBS is used since it works.
