### ISSUE TITLE
qTox complains about the qwindows.dll platform plugin

### ISSUE THREAD

**Issue by bricky149** [qTox/qTox#361]
tux3 has written a script to publish new releases on GitHub with every commit however right now the builds don't run because the Qt runtime complains of an issue running the qwindows platform plugin.

**Comment by tux3** [comment]
Please leave a comment if you still experience this bug and I'll reopen.

Note that the new windows version will probably take 10-15 minutes to compile.

**Comment by bricky149** [comment]
A new build came out with the commit in it (supposedly) but I still get the same problem. I've noticed the date modified stamps were indifferent between the last release and this one. Is that also an issue?

**Comment by tux3** [comment]
I think I found the problem, a fixed Windows build should be ready in a couple of minutes.

**Comment by bricky149** [comment]
Cheers, tux. Best client is finally coming back.

**Comment by bricky149** [comment]
Confirmed resolved. Thanks again!

**Comment by tux3** [comment]
No problem, I'm glad you like qTox !
