### ISSUE TITLE
autoupdate don't work

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#3611]
##### Brief Description

OS: Windows
qTox version: 1.5.0-2-gf05b7e0.
Commit hash:   f05b7e040a073c7afadaf763dda5beaf130c6dbd
toxcore:  0.0.0
Qt:  5.5.1

Reproducible: Always 

There was no automatic update program, although recently there is a new version 1.5.0

**Comment by ovalseven8** [comment]
The update is not available yet for Windows.
