### ISSUE TITLE
abs isn't declared

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3613]
On FreeBSD:

```
src/video/videomode.cpp:66:12: error: use of undeclared identifier 'abs'
    return abs(this->width-other.width) + abs(this->height-other.height);
```

I have to patch it, add `#include <stdlib.h>`.

**Comment by sudden6** [comment]
Could you open a PR with that fix?

**Comment by antis81** [comment]
@yurivict You can actually use `qAbs()` which doesn't require such patches. :)
