### ISSUE TITLE
no indicator in groups that there's an ongoing call when user didn't "call" the group

### ISSUE THREAD

**Issue by wojciechowskid** [qTox/qTox#3618]
##### Brief Description

OS: Windows 10 / Linux (Debian Jessie, Debian Stretch)  
qTox version: Nightly 
Commit hash: built without git
toxcore: 0.0.0
Qt:  5.3.2/5.6.1 (for debians)
Hardware: HP ProBook4530s (this is a laptop of the call initiator)

Reproducible: Always
##### Steps to reproduce
1. Create a group and add memebrs (overall 3 members with qtox on Debian Stretch, Debian Jessie, Windows 10)
2. Start group call
##### Observed Behavior
1. The caller sees that a group call is initiated, corresponding buttons appear (stop call, etc.)
2. The members of the group have no any notifications about group call
3. Regular and video calls to individual users work correctly
##### Expected Behavior

The members of the group received a notification and successfully joined the call.

[qtox_log.txt](https://github.com/qTox/qTox/files/412657/qtox_log.txt)

**Comment by DX37** [comment]
Similar to https://github.com/qTox/qTox/issues/3359, I guess.

**Comment by wojciechowskid** [comment]
In my case group calls won't work at all :(

**Comment by zetok** [comment]
> qTox version: Nightly
> Commit hash: built without git

Could you get the version at least for Debian builds? Note that if you're not using the right repo, there would be no version shown.

**Comment by zetok** [comment]
> [06:15:36.030 UTC] src/main.cpp:199 : Debug: built on:  19:28:31 May 21 2016 ( 1470781615 )

Yeah, no, use the right repo and try again.

Some explanation re: repo: https://github.com/qTox/blog/pull/1

**Comment by wojciechowskid** [comment]
Hi
we all updated the qtox: "You are using qTox version Nightly". 

The `apt-cache show qtox` command gives the following:

```
Package: qtox
Version: 1.5.1-12-gd66a981-1
Architecture: amd64
Maintainer: tux3 <barrdetwix@gmail.com>
Installed-Size: 5893
Depends: libatk1.0-0 (>= 1.12.4), libavcodec57 (>= 7:3.0) | libavcodec-extra57 (>= 7:3.0), libavdevice57 (>= 7:3.0), libavformat57 (>= 7:3.0), libavutil55 (>= 7:3.0), libc6 (>= 2.14), libcairo2 (>= 1.2.4), libfontconfig1 (>= 2.11), libfreetype6 (>= 2.2.1), libgcc1 (>= 1:3.0), libgdk-pixbuf2.0-0 (>= 2.22.0), libgl1-mesa-glx | libgl1, libglib2.0-0 (>= 2.37.3), libgtk2.0-0 (>= 2.16.0), libopenal1 (>= 1.14), libpango-1.0-0 (>= 1.14.0), libpangocairo-1.0-0 (>= 1.14.0), libpangoft2-1.0-0 (>= 1.14.0), libqrencode3 (>= 3.2.0), libqt5core5a (>= 5.6.0~beta), libqt5gui5 (>= 5.3.0), libqt5network5 (>= 5.2.0), libqt5opengl5 (>= 5.2.0), libqt5sql5 (>= 5.2.0), libqt5svg5 (>= 5.6.0~beta), libqt5widgets5 (>= 5.3.0), libqt5xml5 (>= 5.2.0), libsodium18 (>= 0.6.1), libsqlcipher0 (>= 1.1.9), libstdc++6 (>= 5.2), libswscale4 (>= 7:3.0), libtoxav0, libtoxcore0, libtoxdns0, libtoxencryptsave0, libvpx3 (>= 1.5.0), libx11-6, libxss1
Homepage: https://utoxisfinished.info
Priority: optional
Section: net
Filename: pool/stretch/q/qtox/qtox_1.5.1-12-gd66a981-1_amd64.deb
Size: 4407184
SHA256: bfb6fde687294284cc7ca64f3f0e3a3d03f084b781d24f76cfe9e7f980badc87
SHA1: dbfe3376bbb365834c652ce8e04b11720d31246f
MD5sum: 981f4bcc1d19f0542d05e495f399f391
Description: Tox client
 Powerful Tox client that follows the Tox design guidelines.
Description-md5: de54c19ac1db264baa5517cc9cd02447
```

What we have noticed now... If I start group call, my mates won't get any notifications. But if they click the call button in the group chat, they've joined to the group call

[qtox_2016.08.12.txt](https://github.com/qTox/qTox/files/415225/qtox_2016.08.12.txt)

**Comment by sudden6** [comment]
So to clarify, you can talk to your friends, but it is confusing that there is no notification when someone enters audio groupchat?

**Comment by wojciechowskid** [comment]
Exactly. When i start the call, group members have no idea about that. But when they click call button in the group, they connect to call and can talk

**Comment by anthonybilinski** [comment]
v1.16.3 has avatars for friends appear in the netcam view, as well as the users names become bold in the member list when you're receiving audio from them. Current master tip removed the netcam view in groups, but still shows the bold names.
