### ISSUE TITLE
No window "Invitations to groups"

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#3620]
##### Steps to reproduce
1.  tipe "invite" in Groupbot
2. A window will open "Invitation to group" with buttons to "Join" and "reject"
3. If you switch to another tab page or contact in this moment, you can't return again to this window
##### Expected Behavior

Need another bookmark in the "Add friends "Invitations to groups"
##### Additional Info

![default](https://cloud.githubusercontent.com/assets/6053197/17621310/042e7c22-609b-11e6-9b44-23c1d9b279b6.PNG)

**Comment by zetok** [comment]
Wait, there's no tab there.
![spectacle kn4437](https://cloud.githubusercontent.com/assets/3148759/17621765/7ec92a94-608d-11e6-967c-52aedf70f842.png)
↑ you need to press on the second button, for groups, not for friend requests.

**Comment by PKEv** [comment]
Thank you
