### ISSUE TITLE
Incorrect group name in the invitation

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#3621]
##### Brief Description

OS: Windows 
qTox version: v1.5.0-2-gf05b7e0.
Commit hash:  f05b7e040a073c7afadaf763dda5beaf130c6dbd
Qt:  5,5,1

Reproducible: Always 
##### Steps to reproduce
1. invite in group 1 and invite in group 2 (Groupbot and Kalina)
2. go to group's page with invites
3. Both invitations will be from the same group (same name)
##### Additional Info

![default](https://cloud.githubusercontent.com/assets/6053197/17621992/3108ef66-60a0-11e6-873d-6f1ac5f10d5c.PNG)

**Comment by ProMcTagonist** [comment]
I've noticed this too.
