### ISSUE TITLE
Audio stream remains open after leaving Audio/Video settings

### ISSUE THREAD

**Issue by akhilman** [qTox/qTox#3625]
qTox leaves audio playback stream open after leaving Audio/Video settings

OS: Debian GNU/Linux Sid
qTox version:  v1.4.0-245-g99ce719
Commit hash:  99ce719b800b5fedeb47eb848268976dcbf96fc7
toxcore:  0.0.0
Qt:  5.5.1
…

Reproducible: Always 
##### Steps to reproduce
1. Go to Settings
2. Select Audio/Video settings tab
3. Go back to chat or to another settings tab
##### Observed Behavior

qTox leaves pulseaudio playback stream open forever
##### Expected Behavior

qTox should close playback stream just after leaving Audio/Video settings tab

**Comment by zetok** [comment]
Could you re-test with newest qTox?

**Comment by akhilman** [comment]
Reproducible in current master 
qTox version v1.5.1-13-ge4398c7
commit hash: e4398c7894f16ef02a7302149790f4ab760923cc

**Comment by zetok** [comment]
Most likely will be fixed by #3524
