### ISSUE TITLE
Audio stream remains open after message notification

### ISSUE THREAD

**Issue by akhilman** [qTox/qTox#3626]
qTox leaves audio playback stream open after message notification sound.

OS: Debian GNU/Linux Sid
qTox version:  v1.4.0-245-g99ce719
Commit hash:  99ce719b800b5fedeb47eb848268976dcbf96fc7
toxcore:  0.0.0
Qt:  5.5.1
…

Reproducible: Always 
##### Steps to reproduce
1. Turn on sound notification
2. Minimize qTox to tray
3. Tell to friend to send some text message
4. Listen sound notification
##### Observed Behavior

qTox leaves pulseaudio playback stream open forever
##### Expected Behavior

qTox should close playback stream after notification sound playback or with some delay

**Comment by zetok** [comment]
Could you re-test with newest qTox?

**Comment by akhilman** [comment]
Reproducible in current master 
qTox version v1.5.1-13-ge4398c7
commit hash: e4398c7894f16ef02a7302149790f4ab760923cc

**Comment by zetok** [comment]
Most likely will be fixed by #3524

**Comment by sudden6** [comment]
Doesn't happen on recent versions anymore.
