### ISSUE TITLE
JPEG files cannot be used as avatars

### ISSUE THREAD

**Issue by bricky149** [qTox/qTox#363]
qTox throws an error when you try and use a JPEG, PNGs work fine.

**Comment by ghost** [comment]
PNG's are the only allowed format atm.

**Comment by tux3** [comment]
Again ? 

qTox converts images on the fly to PNG, so you should be able to use any image you want.
I'll fix this soon, sorry.

**Comment by bricky149** [comment]
I've been following the commits and, as tux said, it should convert them on the fly. I just have a lot of JPEGs that I can't use right now. :P

**Comment by tux3** [comment]
Hm, I can't reproduce.

Are you perhaps using an old version ?
What is the error you get ?

**Comment by bricky149** [comment]
Nope, I used the absolute latest build. I can't use the older builds because they didn't run.

**Comment by tux3** [comment]
Are you using the windows build ?

**Comment by bricky149** [comment]
Yes since I'm currently at work.

**Comment by tux3** [comment]
This will be fixed in the next release, in 10 minutes.

qTox can now open the following formats on Windows : PNG, JPG, BMP, TIFF, SVG, GIF, ICO and WEBP
