### ISSUE TITLE
I see a green flickering screen when trying to video chat on qtox

### ISSUE THREAD

**Issue by TheNotary** [qTox/qTox#3632]
##### Brief Description

OS: Linux Mint 17.2
qTox version: Qt version: 5.6.1
Commit hash:  Commit hash: f05b7e040a073c7afadaf763dda5beaf130c6dbd
toxcore:  0.0.0
Qt:  3ish?
Hardware:  AlienWare Laptop (graphics, Radeon HD 7970)
…

Reproducible: Always
##### Steps to reproduce
1. I start a video chat session with someone on qTox
##### Observed Behavior

I see a mostly green screen in the video output, though there's a 'band' towards the top where I can somewhat see the other person's hair.  The green screen flickers.  
##### Expected Behavior

It should work just like video chat software works where I see the other person's face.  
##### Additional Info

I've tried with multiple other people so I think the problem is with my machine.  After googling, I'm under the impression that I need to try disabling 'hardware acceleration' but don't know how to do that.  (https://productforums.google.com/forum/#!topic/youtube/6MZf1aUtJ18)
##### Emotional Impression this Issue has Made on me

😦

**Comment by sudden6** [comment]
paging @initramfs because he redid most of the video stuff.

First of all, disabling hardware acceleration probably won't help, since I think qTox doesn't use it.

What would probably help us in solving the problem, are your log files, could you please upload them? They should be in `~/.cache/Tox/qTox/` .

**Comment by initramfs** [comment]
By "green flickering screen" do you mean the video you receive is green (i.e. when chatting with someone else, you see them as a green screen)? Also, if you go into the A/V settings page and preview yourself, does the output look normal or it is green too?

Finally, could you try an older version of qTox (e.g. v1.4.1.1) to check if this is an regression? Thanks.

**Comment by zetok** [comment]
@TheNotary are your friends using qTox?

**Comment by TheNotary** [comment]
Yes qTox is being used on both ends.  I don't know how to use v1.4.1.1... but I just now got in touch with my friend and it's working fine now so I can't give you screenshots as planned...  grrr.... I guess I'll reopen this if the problem comes back.  If the error comes back, maybe that indicates something weird with my horrible hardware.  

Regards, and keep up the good work.
