### ISSUE TITLE
Laggy voices in group calls with 3 or more people

### ISSUE THREAD

**Issue by Kron4ek** [qTox/qTox#3647]
##### Brief Description

OS: Arch Linux, Linux 4.7.1-1-ARCH (the problem also occurs on Windows).
qTox version: 1.5.1
toxcore: 3747
Qt:  5.7.0

Reproducible: Always
##### Steps to reproduce
1. Invite at least 2 people (in addition to yourself) to a group
2. Start group call

If invite one person to one group and another to another group and start this two group calls at the same time, the problem is not observed. Also if you just call at the same time two people (without inviting them into group) the problem may not occur or may occur (it is not clear on what it depends).
##### Observed Behavior

The voices becomes laggy, like a robot speech.

**Comment by Diadlo** [comment]
Seems same with #3359
If not, please, reopen

**Comment by zetok** [comment]
@Diadlo um, if maintainer closes the issue, non-maintainer can't reopen it.

**Comment by Diadlo** [comment]
@zetok Sorry. I will know
