### ISSUE TITLE
.deb fails to install

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#365]
Refuses installation with this error message:

> Error:
> Dependency is not satisfiable: libopus0 (>= 1.1)

Note that this version is higher than what is in debian/control. What system are you building the packages with?

**Comment by tux3** [comment]
I'm building with a debian stable chroot that pulls Qt and opencv from the debian testing repos.
I must have updated opus to 1.1 without meaning to.

**Comment by dubslow** [comment]
I'm running Mint Debian, which is roughly Debian testing from around 6 months ago (except also with Cinammon 2.0).

**Comment by Frowny** [comment]
Dependency is not satisfiable: libqt5core5a (>= 5.3.0)

**Comment by tux3** [comment]
I updated the build system, the packages should depend on qt >= 5.2 and libopus0 >= 1.0  from now on.
Note that the packages are still experimental and will likely not work on many systems just yet.

**Comment by dubslow** [comment]
@tux3 It installs now (hooray!) but I get this when I try to run it:

https://gist.github.com/dubslow/50c560a04341a0bb5166

It also doesn't use/install the desktop file from the repository.

**Comment by tux3** [comment]
Yes, linking libav statically is Hell, so you'll need to install it until I find a better way. I'll add it to the dependencies.

After that it'll probably complain that you don't have librtmp0, I still need to fix that.

**Comment by dubslow** [comment]
Funnily enough (not really surprising though) I have both of these libraries in my steam runtime. A proper fix would be nice though :)

**Comment by dubslow** [comment]
Closing, since stqism got his packages working. Testing+ works now, stable should be working by tomorrow.

**Comment by tux3** [comment]
> stqism got his packages working. Testing+ works now, stable should be working by tomorrow.

That's great news, I'm really bad at packaging. In hindsight trying to make a single package that'd work on both stable and unstable was not a good idea.

**Comment by dubslow** [comment]
> That's great news, I'm really bad at packaging. In hindsight trying to make a single package that'd work on both stable and unstable was not a good idea.

Well that's what he's doing. He's waiting on an opencv2.4 package from Proplex for the deb to support stable as well.

**Comment by tux3** [comment]
opencv2.4 for stable, how is that going to work if it's not in the official repos ?
Simply asking people to install both packages ?

**Comment by dubslow** [comment]
statically linked, like qt5

**Comment by tux3** [comment]
I'm afraid I don't follow. Right now I'm seeing both opencv2.4 and qt5 dynamically linked in the amd64 deb package.

Statically linking opencv is what I tried to do, but then you have to pull in things like ffmpeg statically and it gets a bit messy.
