### ISSUE TITLE
UI: don't just grey out auto-login checkbox, don't show it (or show why it is not accessible)

### ISSUE THREAD

**Issue by toxlover** [qTox/qTox#3651]
There's a bit of a UI improvement possibility. By greying out the auto-login checkbox in the case of an encrypted profile, you give the idea that auto-login is POSSIBLE but somehow not working. Either simply do not show this in the case of an encrypted profile, or explain there in as few words as possible, why it doesn't work i.e.

"Auto-login is not possible with encrypted profiles"

OS: All
qTox version: All

**Comment by sudden6** [comment]
fixed with b5efc2bb7124ccbbd256792c524ffffdd02fab3f
