### ISSUE TITLE
Send recipient original time stamp when message is sent "offline"

### ISSUE THREAD

**Issue by toxlover** [qTox/qTox#3652]
It happens occasionally that I send a message to someone who is online or who disconnects. The spinner goes next to the message, and that all makes sense.

The problem is: When the other person reconnects, it can be any amount of time later, but it appears to them that the message was freshly sent. This creates awkward situations.

The solution is to include the time stamp so that it appears correctly on both sides.

**Comment by Diadlo** [comment]
Same with https://github.com/qTox/qTox/issues/3306
