### ISSUE TITLE
Feature request: Optional pop-up notifications and pop-ups to answer calls

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3659]
In this section I'd like to request two more features, I merged them because they both have to do with pop-ups:

Optional (so a user could choose in settings):
- to have pop-up notifications with message previews
- to have pop-up call notification that allows user to accept or dismiss a call

Best regards and keep the great work!

**Comment by Diadlo** [comment]
Duplicate of https://github.com/qTox/qTox/issues/483
