### ISSUE TITLE
Crash on Profile Import: Assertion `Nexus::getDesktopGUI()' failed.

### ISSUE THREAD

**Issue by CaptainKraft** [qTox/qTox#3660]
##### Brief Description

OS: Arch Linux, 64bit
qTox version: v1.5.1-63-gfcfac15
Commit hash: fcfac15c785f6cca5a38b9aa4f915fb805aec161
toxcore: 0.0.0
Qt: 5.7.0

Reproducible: Always
##### Steps to reproduce
1. Try to import .tox profile
##### Observed Behavior

Immediate crash with this console output:

qtox: ../src/widget/gui.cpp:50: GUI::GUI(QObject*): Assertion `Nexus::getDesktopGUI()' failed.
[1]    3590 abort (core dumped)  qtox
##### Expected Behavior

Import profile data and not crash.

[qtox.txt](https://github.com/qTox/qTox/files/440408/qtox.txt)

**Comment by sudden6** [comment]
Log shows nothing unusual. Does this happen only with some specific .tox file or with any file?

**Comment by CaptainKraft** [comment]
I've tried multiple tox files with the same results. I also checked the logs immediately after the crash and there is nothing there at all.

It might be worth noting that if I simply copy the tox file into ~/.config/tox/, it seems to load the profile just fine.

**Comment by sudden6** [comment]
Ok, I can confirm.

**Comment by sudden6** [comment]
Offending PR could be https://github.com/qTox/qTox/pull/3560 @Diadlo could you take a look?

**Comment by Diadlo** [comment]
Confirm. Will be fixed soon (hope today)

**Comment by Diadlo** [comment]
In my time I had today :)
