### ISSUE TITLE
qTox not establishing connection

### ISSUE THREAD

**Issue by darkman088** [qTox/qTox#367]
Hello,

yesterday I have downloaded the latest build of qTox for Windows.
I have put it on 2 PCs - directly connected to the internet. No proxies, nothing...
On each of the PCs, the own user gets a green point, but we can't see eachother
online. There remains a red circle next to the chat partner, we are trying to write
messages to each other and nothing is coming through...
Everything else works fine - other chat programs, web browsing, etc...

**Comment by dubslow** [comment]
Can you add groupbot@toxme.se?

Can you maybe post console output?

Are you sure you copied the whole friend address? It's possible to get enough of the friend address to get qTox to add it to the list, but not enough to actually connect to each other...

**Comment by darkman088** [comment]
Hello, sorry but i don't understand what do you mean by adding groupbot...
I don't know how to post the console output either...
I didn't copy any addresses, I migrated the contacts from uTox as you
can find in my thread here in github.

**Comment by dubslow** [comment]
Hmm.

When I say add "groupbot@toxme.se", I mean put that into the add-friend box (instead of the long hex string that you otherwise might add). Once you add GroupBot, do you see it online?

**Comment by darkman088** [comment]
Hello, thanks for your suggestion! Yes, I have added it as a contact and I see it online.

**Comment by dubslow** [comment]
...then qTox is connected, and there's some other issue. You still don't see your friend online?

**Comment by darkman088** [comment]
I have checked again - my contact is not coming online, checking it remotely now. His qTox turns green only if I select it from the menu... What does that mean ?
I have checked on the firewall - qtox.exe is allowed... What do you suggest ?

**Comment by dubslow** [comment]
That means his client isn't connecting to the DHT. Can you confirm that he can't add groupbot either?

If not, then is UDP not allowed by the firewall perchance?

**Comment by darkman088** [comment]
Yeah, I thought I have with my previous message... What to do now... ??
Like... not that he can't add it, it is getting added, but no green point next to the Tox ID, just a red circle...

**Comment by dubslow** [comment]
So you confirmed you can add GroupBot, so you are connecting fine, but it seems that your friend can not add GroupBot, and in all other forms still appears to be disconnected.

Does your friend have UDP blocked in some way? Currently that will render qTox unable to connect. If not, then I'm afraid I'm out of ideas short of setting up a version with debugging symbols that can be stepped through...

**Comment by darkman088** [comment]
Hello and thanks, well he might have UDP blocked, but how to find it out ?

**Comment by darkman088** [comment]
Hello, not that anyone answered...
But now I am not able to connect either! I have both clients - qTox and uTox.
I tried uTox and it connects very fast, but I can't connect with qTox !!
I have checked again the settings on my firewall! qtox.exe is allowed, protocol: any.
I am now trying with a second contact - he can't come online either (he is using a different security suite!). So I think that when I am able to connect with uTox, there is definitely some issue with qTox.

**Comment by dubslow** [comment]
Hmm, that is strange indeed, and certainly a bug. Unfortunately I don't know what could be causing it...

**Comment by darkman088** [comment]
OK, let's hope that someone else will check this and fix this bug. Unfortunately I can't use tox in this case - uTox is not making ANY sounds when there is an incoming call and with qTox it is not possible to connect! Sorry, but I need to give up at this point and switch my attempts to another program... :-(

**Comment by dubslow** [comment]
Keep in mind that everything at this point is still alpha, and undergoing active development. Please do try again some time in the future :) and of course we'll let you know here if we fix something related to not connecting.

**Comment by darkman088** [comment]
Yes, I know, I like you, guys, and this is the reason I am opening all these threads and trying to test your software and sharing my needs and ideas...
So, sharing again: I am now checking - qTox has connected on the computer of my first contact !!! And for me, it is still not connecting !! So, it is somehow a random thing - qTox: "I will connect only if I am in a good mood today!" :-)
At least this is a confirmation that it is no port or firewall issue!

**Comment by dubslow** [comment]
I think I know the issue here, I'm willing to bet you downloaded qTox from the official "Binaries" page... sadly, that's a month out of date, and has an issue regarding the endianess of the port number of the bootstrap nodes... that bug took a while to iron out, but it has been ironed out.

Please try [this](https://github.com/tux3/qTox/releases/tag/qtox-windows-1412632557.41) or whatever the most recent version [here](https://github.com/tux3/qTox/releases) is.

I found this thanks to chatting with another Windows user -- hopefully you can enjoy a month's worth of bugfixes and features :)

**Comment by darkman088** [comment]
Hey man, thanks a lot!! I will definitely give it a try, before I give up on tox! I have also rejected another program, because it stores the chat logs in plain text files and they have no option to turn off chat logging! Under these circumstances, this is no security at all...

**Comment by darkman088** [comment]
Hello dubslow !! Now I have checked it !! And first, I would like to thank you for showing me the correct
download. So, I am both amazed how much changed just in 1 month and at the same time I am very disappointed...
I've thrown so many negatives on tox, so I feel obliged to start with the amazing stuff !!
THIS REALLY LOOKS like a software now !!! You've made major improvements on the interface !!!
The connection problem is SOLVED !! It connects nearly instantaneously!
I also see all my other buddies online briefly after they connect!
So, now the negatives... Yes, qTox does make sounds! But unfortunately, ONLY on chats and ONLY when the window is not on focus. I have tried to be called - no ringtone at all.
And the tone on chat events seems to be somehow hard-coded. What I liked more about the non-working version - there was an audio folder with notification.wav. Replacing this .wav file with a custom file would be a very easy way to change the ringtone! Now I have tried to create this folder on the new qTox and put a file notification.wav there, but nothing changed, to my big disappointment...
Another thing - when I am chatting with one contact and being called by another - AT LEAST there is a bigger green point shown, so there is at least some way to identify an incoming call, which was not the case before. Though making the entire contact name field blink or reverse its color would provide better visibility. On the other hand - if the contact list is so long, that it needs scrolling, it will be impossible to chat with a contact at the top of the list and identify an incoming call from a contact at the bottom of the list. I think that there should be a separate area for visually notifying about incoming calls, that would always be visible... Or pop a window on top of everything... Just trying to throw fresh ideas here!
And now - back to my MAIN question - what can we PLEASE PLEASE PLEASE do, in order to have qTox ring a tone when there is an incoming call, regardless whether the qTox window is on focus or not ???
And one last note - when calling somebody, the "line" keeps ringing just for a few seconds, before it closes automatically. I think that this period should be longer... Just my personal opinion...
And one more question - does qTox store chat logs ? I hope NOT :-)

THANK YOU !!!

**Comment by darkman088** [comment]
Maybe not the right place, BUT a brief feedback:
- audio call is fine, the quality is very good
- video call - just an empty window opens up, without any video in it. The audio is very choppy (will be hopefully improved in newer versions...)

**Comment by dubslow** [comment]
Indeed, there are a large number of usability issues that qTox needs work on. Ringing time I _believe_ is set by the core at 10 seconds, though I may be wrong.

As for the audio choppiness, yes I know but I myself don't really know how the audio and video work. It certainly would be nice if Tox could trade quality for choppiness like Skype does. (That is, instead of becoming choppy, the quality just drops, but at least there isn't the popping sound of randomly dropping frames.)

Video not working has been reported once before, and again, I myself can't really do anything about it.

A quick question for you: are you able to be invited to group chats, e.g. via GroupBot? We've had some reports of that not working on Windows, and I want to know if that's _every_ Windows client or something more flaky.

I'll try and whip up something quick regarding the ringtone, but no guarantees. It certainly is one of the most glaring usability issues.

As for the .wav, when the dependencies changed a month or so ago, we also lost the ability to play anything but raw audio, like .pcm currently in use. I also believe that it's embedded into the binary (but I could be wrong).

Finally, would you please close this issue? :)

**Comment by darkman088** [comment]
Hello,
1. Yes, I would love to support you all with whatever I can. So, YES, you can invite me to group chats. Let me know how to organize it and how to exchange IDs.
2. Yes, PLEASE do something about the ringtone! It is the most urgent feature that is missing!
3. A .pcm file is not an issue, I think I can convert audio files to .pcm. Just kindly let me know where the file needs to be placed and how it should be named.
4. OK, closing the issue, many thanks to you again!

**Comment by dubslow** [comment]
1) This is issue #394, and I meant, do the following, after updating (you'll see in that thread that tux3 just made a new Windows release with a potential fix):
   a) add groupbot@toxme.se
   b) send it this message: "invite"
   c) if it works correctly, you'll see a groupchat in your friends list, or if it didn't, you won't see anything.

Please let me know which outcome occurs.

3) The sound is embedded in the binary, and does not search your file system. Sorry :P

**Comment by darkman088** [comment]
Hello dubslow,

1) You already have the groupbot in my contact list, you suggested this earlier in order to test the online status. In the evening I will download the latest qTox and I will try what you described, then I will update you with the result.

2) What about a ringtone ? Are you on it, please ? :-P

3) That is a pity - is it possible to have customization options for the sounds in the future ?

4) What about my question - does qTox store chat logs ?

**Comment by apprb** [comment]
> 3) That is a pity - is it possible to have customization options for the sounds in the future ?

Sure, but for now there are so many things to do beside this.

> 4) What about my question - does qTox store chat logs ?

Will be implemented soon (C)

**Comment by darkman088** [comment]
3) That's perfectly fine for me. I most urgently need a ringtone when a contact is calling me, I can wait for the customization options.

4) This topic is VERY sensitive. As tox is built to be secure by design, I am strongly convinced, that this option (if present), should be turned off by default). Also, if chat logs are being stored on the local disk, they MUST be encrypted using some very strong algorithm, otherwise there is simply no security.
I have been criticizing Jitsi, that they store the chat logs by default and they do it in plain text files!
As stated above, I have quit using another program, because they also store logs in plain text files, but contrary to Jitsi, this can't even be turned off !!! So, PLEASE PLEASE keep this program secure!
And I think that putting the encryption in the responsibility of the users is not fair! I am using Windows, due to several technical and historical reasons. I cannot consider whole disk encryption, because of the very high performance penalty.

**Comment by dubslow** [comment]
I can make an adjustment to allow for password encryption of arbitrary data -- such as chat logs. Don't expect anything in the near future -- only Soon™.

**Comment by darkman088** [comment]
Hi dubslow. IMHO encryption of chat logs should come along with the possibility to store them.
I only expect the ringtone in the nearest future :-) Everything else can wait B-)

Thanks to all of you, guys! If I can help you with something else - go ahead and ask me :-)

**Comment by darkman088** [comment]
Hello guys,

I have tried what you asked me for - I have typed invite to the GroupBot, but unfortunately nothing happened... If I can do something else for you - just let me know !!

**Comment by dubslow** [comment]
That's unfortunate... I don't suppose you can run qTox from terminal so we can see the log messages?

Actually, let's move this conversation to #394

**Comment by darkman088** [comment]
Hello, despite of the fact, that this conversation has been closed, I would like to kindly ask again what is the status with the ringtone ? Many other users are missing this functionality as well... Shall I open a new thread/issue/bug report ?

**Comment by dubslow** [comment]
No I added a not-well-done-but-it-works version a day or two after we talked about it, and it's been in the master branch since. Obviously however, we've had packaging problems. Try the latest Windows release at your leisure, it should have it.

**Comment by darkman088** [comment]
COOL !! I'll do it and then I'll report back! MANY THANKS!!!

**Comment by darkman088** [comment]
Hello dubslow,
I have downloaded the latest version from the link you sent me. It says released 4 hours ago...
Unfortunately, I am not able to start qTox, because right when I launch qTox.exe, I am getting the following error:

The procedure entry point U16_to_bytes could not be located in the dynamic link library libtoxcore-0.dll

Kindly fix the issue and let me know when I can make some tests again... Thank you!

**Comment by dubslow** [comment]
@darkman088 there are multiple issues about that, and in the most recent tux3 said he would update his libtoxcore (which at this point is nearly a month old) that is used in the binaries sometime this weekend.

**Comment by darkman088** [comment]
Ok, thanks for your feedback! Shall I wait for an OK from you, or I can go ahead and test it on sunday evening or monday evening ? Thanks !!

**Comment by dubslow** [comment]
The latter.

**Comment by moh26000** [comment]
![Capture](https://user-images.githubusercontent.com/55385827/65703847-5bf7a180-e07d-11e9-9ec5-7916a4734c18.PNG)
Qtox has stopped working

**Comment by moh26000** [comment]
He stopped since yesterday

**Comment by anthonybilinski** [comment]
@moh26000 could you please open a new issue, and include qTox logs from settings -> advanced, and also check your connection settings in settings -> advanced and make sure that "Enable UDP" is checked, and "Proxy Type" is "None".

**Comment by moh26000** [comment]
Thank you
It was done with success
