### ISSUE TITLE
Portable mode broken due to replacement of makeToxPortable option

### ISSUE THREAD

**Issue by DX37** [qTox/qTox#3681]
##### Brief Description

In latest nightly, portable mode only works when in `qtox.ini` option `makeToxPortable=true` is set in `General` and `Advanced` sections. After exiting, option is disappears from `General` section and portability brokes.

OS: All?
qTox version: v1.5.1-66-gb7d1222
Commit hash: b7d1222

Reproducible: Always
##### Steps to reproduce
1. Run qTox with `makeToxPortable=true` in `General` section in `qtox.ini`.
2. Got non portable qTox.
3. Copy option from `General` to `Advanced`.
4. Run qTox and log in. Got portable mode working, but option disappears from `General` section.
5. Exit. At next run portability brokes.

**Comment by zetok** [comment]
cc @Diadlo

**Comment by Diadlo** [comment]
Can't reproduse
Are you remember, that `qtox.ini` file in portable mode will be moved in application directory?

**Comment by DX37** [comment]
> Can't reproduse

To reproduce you need to have `qtox.ini` with writed options in it, inside directory with `qtox.exe`.

> Are you remember, that qtox.ini file in portable mode will be moved in application directory?

Nothing moves from AppData to application directory or vice versa. qTox just creating new `qtox.ini`, if it not found.

**Comment by Diadlo** [comment]
> Nothing moves from AppData to application directory or vice versa.

Wrong? https://github.com/qTox/qTox/blob/master/src/persistence/settings.cpp#L748:L749
@zetok

**Comment by DX37** [comment]
> Wrong? https://github.com/qTox/qTox/blob/master/src/persistence/settings.cpp#L748:L749

Okay, it moves `qtox.ini` and, for example, `qwerty` profile, fine. But after starting qTox again it uses `qwerty` profile from AppData and not from app directory.

**Comment by Diadlo** [comment]
@DX37 Hm... qTox prefers config in qTox app directory, if it's exist. If you found, that not, it's another issue

**Comment by DX37** [comment]
Maybe [**video**](https://youtu.be/eAeUtKMQlRg) can tell you more, @Diadlo?

**Comment by Diadlo** [comment]
@DX37 Thanks for video. Now I understand. Will be fixed soon

**Comment by ghost** [comment]
Hello @Diadlo!

Thank you for fix!

It seems that issue still persist in v.1.5.1-83-g7a98ea3. Commit hash 7a98ea337bba2d5b2a32645631f0786ad12c7731.

**Comment by Diadlo** [comment]
@st38 It's because fix not merged yet. Please, try #3691

**Comment by DX37** [comment]
Fixed. Thank you :smiley:
