### ISSUE TITLE
Custom Smileys for Windows version

### ISSUE THREAD

**Issue by mdswamp** [qTox/qTox#3682]
OS: Windows
qTox version: v1.5.1-8-gfd04a28

Hi guys..
how can I add custom smileys like yahoo, etc to windows qtox... I can't find any guidance, thanks.

**Comment by sudden6** [comment]
Currently smileys are statically included in the qTox binary and cannot be changed after compiling.

**Comment by ezavod** [comment]
This question could be closed since [Emoji Packs](https://github.com/qTox/qTox/blob/master/doc/user_manual_en.md#emoji-packs) are implemented in newer versions.
