### ISSUE TITLE
Wrong message notification sound

### ISSUE THREAD

**Issue by Kron4ek** [qTox/qTox#3689]
##### Brief Description

OS: Arch Linux (also occurs on Windows)
qTox version: 1.5.1
toxcore:  3747
Qt:  5.7.0

Reproducible: Sometimes
##### Steps to reproduce
1. Make two parallel calls to any two people (they should accept call)
2. Send message to any of these people
##### Observed Behavior

Message notification will change to the sound of an incoming call. Sometimes it does not change.

**Comment by Kron4ek** [comment]
I recorded a video with a demonstration of a bug.

[Vid.zip](https://github.com/qTox/qTox/files/456264/Vid.zip)

**Comment by AliceGrey** [comment]
@Kron4ek @zetok I'm able to reproduce this with the current git build without having to do parallel calls.

**Steps to reproduce**
1. Call client1 from client2
2. Accept call
3. Minimize client1
4. Send message from client2 to client1
