### ISSUE TITLE
Long words cause strange wrapping

### ISSUE THREAD

**Issue by bricky149** [qTox/qTox#369]
If the window's too small, and say you posted someone's ID, this happens: https://i.imgur.com/9xuDFIv.png

**Comment by dubslow** [comment]
This issue has been reported and supposedly fixed; how recent is your qTox?

**Comment by bricky149** [comment]
Forgot to look through the closed ones. Build's from tonight, Windows.

**Comment by dubslow** [comment]
@apprb

**Comment by apprb** [comment]
OK, I'll look it this evening.

**Comment by apprb** [comment]
Can't reproduce under *nix (Arch):
![png](https://cloud.githubusercontent.com/assets/6405341/4506594/498d2948-4b04-11e4-89ce-9927de4f1104.png)
Have no Windows system nearest now to test under.

**Comment by dubslow** [comment]
I think it is a windows bug... 

@sergeevabc reports http://i4.minus.com/iNlHsGXDauJQA.png

while I see 
![qtox-bug](https://cloud.githubusercontent.com/assets/6127392/4537406/73d66974-4ddb-11e4-9655-eb77e1aaa6b9.png)

**Comment by tux3** [comment]
I can't reproduce on Windows or Linux anymore, if this is still a problem, please comment and I'll reopen.
