### ISSUE TITLE
Minimize and Show close the application

### ISSUE THREAD

**Issue by x44** [qTox/qTox#3699]
##### Brief Description

OS: Windows 7
qTox version: v1.5.1-83-g7a98ea3.
Commit hash:  7a98ea337bba2d5b2a32645631f0786ad12c7731
toxcore:  0.0.0
Qt: 5.6.1 

Reproducible: Always
##### Steps to reproduce
1. Uncheck "Close to tray"
2. a) Minimize qTox OR
3. b) Press Win+D OR
4. c) Select "Show" from the tray popup
##### Observed Behavior

qTox exits.
##### Expected Behavior

Should minimize.
##### Additional Info

(links, images, etc go here)

---

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by zetok** [comment]
cc @Talkless

**Comment by Talkless** [comment]
I was afraid that PR #3687 could regress for Windows. Looks like Windows needs ignoring QCloseEvent after all?  

Could someone share cross-compiling hints how to build for Windows with MinGW on Linux? Is there a script for that, how Windows qTox binaries are actually produced? bootstrap.sh still with problems in #3372

**Comment by zetok** [comment]
@Talkless it's not a windows-only regression, it's reproducible on Linux.

**Comment by sudden6** [comment]
@Talkless would also be good if you mention your fear of breaking something, so we could better test.

**Comment by Talkless** [comment]
> it's not a windows-only regression, it's reproducible on Linux.

Oh damn... I failed to find regressions when testing on Linux. I'll get on that this weekend!

> would also be good if you mention your fear of breaking something, so we could better test.

Yes, I guess I should have mentioned that I could not test on Mac and Windows. "Happy" to hear it's for Linux too. 

Sorry for regression.

**Comment by b4n** [comment]
On my MATE GNU/Linux desktop reproducing is as easy as switching virtual desktop: as soon as the active desktop changes from the one where qTox window is, qTox quits.  #3702 fixes this.
