### ISSUE TITLE
Errors when trying out video on Gentoo

### ISSUE THREAD

**Issue by sonOfRa** [qTox/qTox#37]
(toxgui:4421): GStreamer-CRITICAL **: gst_caps_unref: assertion 'caps != NULL' failed

*\* (toxgui:4421): CRITICAL **: gst_missing_encoder_message_new: assertion '!gst_caps_is_any (encode_caps)' failed

(toxgui:4421): GStreamer-CRITICAL **: gst_element_post_message: assertion 'message != NULL' failed
CameraBin error: "Ihrer Installation von GStreamer fehlt ein Plugin." 

translation:"Your installation of GStreamer is missing a plugin"

Camera works fine in browser applications that use flash to access it.

**Comment by tux3** [comment]
It seems like a problem with runtime support, not the toxgui code.
Have you tried installing libgstreamer-plugins-\* ?

**Comment by tux3** [comment]
Fix : "just +ffmpeg +v4l on -meta"
