### ISSUE TITLE
Groupchat issues

### ISSUE THREAD

**Issue by bricky149** [qTox/qTox#370]
Mainly 2 issues I found:
1. I cannot invite people into groupchats
2. Sending messages fail every time

To do with core updates, maybe?

**Comment by dubslow** [comment]
Yes, this is 99.99% likely a core problem. The API at least hasn't changed except once, and that was a very simple change.

**Comment by dubslow** [comment]
Note that there is one small issue fixed by a waiting PR, see if that helps

**Comment by suhr** [comment]
Yes, it is core problem. Also, https://github.com/tux3/qTox/issues/337.

**Comment by bricky149** [comment]
I assume #373 was the fix? I can't test yet as I'm at work (I'm not using my VPN connection).

**Comment by suhr** [comment]
Works with recent toxcore. Fixed?

**Comment by bricky149** [comment]
Sorry, I forgot about this. Is #394 related to this? I haven't had the chance to verify.

**Comment by agilob** [comment]
We tested it yesterday with @dubslow, he was able to invite me and I invited him successfully.

**Comment by tux3** [comment]
I'm closing this for now since it seems to work, if someone runs into this bug again we can reopen, but it sounds like a toxcore issue.
