### ISSUE TITLE
[Regression] stopped to show a mark of the day change

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#3705]
##### Brief Description

qTox version: 1.5.1-97
previous version was 1.5.0
##### Steps to reproduce
1. send a message
##### Observed Behavior

there is no mark about the date change
##### Expected Behavior

if you change the date the new message must be separated from the previous one
##### Additional Info

![default](https://cloud.githubusercontent.com/assets/6053197/18464283/b98a2998-7998-11e6-9860-43098111e127.PNG)

**Comment by PKEv** [comment]
May be due to the lack of settings the date format when upgrading from versions which did not have this settings, please check.

**Comment by Diadlo** [comment]
Can you share your current settings file (with broken date format)?

**Comment by PKEv** [comment]
no, i save settings and problem disappeared

**Comment by PKEv** [comment]
The problem was apparently that no settings with values assigned and not default values .

**Comment by sudden6** [comment]
So a duplicate of https://github.com/qTox/qTox/issues/3707 ?

**Comment by PKEv** [comment]
Different sides of the same problem

**Comment by PKEv** [comment]
closed via #3713
