### ISSUE TITLE
Not displayed date format

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#3707]
##### Brief Description

OS: Windows
qTox version: 1,5,1-97
##### Observed Behavior

After updating the setting "date Format" is not selected any one value from the list
##### Expected Behavior

Must be selected the first value from the list

**Comment by Diadlo** [comment]
Can you write previous version and new? And same to the other 2 your issues

**Comment by PKEv** [comment]
previous version was 1.5.0
