### ISSUE TITLE
Fonts are messed up somehow

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#372]
Chat fonts are no longer black like they're supposed to be, they're a painful-to-read gray; additionally, friend's list text is now also gray, making it hard to read in all circumstances.

@krepa098

**Comment by krepa098** [comment]
Can I get a screenshot please? I can't seem to have this issue.

**Comment by apprb** [comment]
![png](https://cloud.githubusercontent.com/assets/6405341/4506305/3b865d7c-4b01-11e4-8853-1c8f0c20c329.png)
Something like this. The black font in msgEdit much better than gray one.

**Comment by apprb** [comment]
Probably problem is in using of 11 size font instead of 12.

**Comment by krepa098** [comment]
![snapshot16](https://cloud.githubusercontent.com/assets/4587853/4506764/1510414e-4b06-11e4-83ee-6d039ddd572d.png)

That's how it should look like...

> Probably problem is in using of 11 size font instead of 12.

It's using

```
font: @big;
```

which means 12px.

**Comment by apprb** [comment]
For me the problem lays in commit daf5be96b51133f00c0c95beafceb65cdb9e6a85 (Style: font size doesn't take px suffix, fixes fonts not applying). 
Left one with this commit reverted, right one current master (0184205)
![png](https://cloud.githubusercontent.com/assets/6405341/4506826/ce0276d6-4b06-11e4-874e-208791426756.png)
If this not only for me, mentioned commit should be reverted.

**Comment by krepa098** [comment]
Thanks, i'll have a look at it.

**Comment by JFreegman** [comment]
This issue isn't fixed for me. fonts still look like picture 2 (in all of qtox, not just the download widget)

**Comment by dubslow** [comment]
That's because @krepa098 hasn't submitted a PR with the fixes yet... actually, upon reviewing his master, it looks like he has a bunch of tweaks lined up and is waiting to complete them all before submitting.
