### ISSUE TITLE
src/video/camerasource.cpp:295:42: warning: ‘AVStream::codec’ is deprecated

### ISSUE THREAD

**Issue by iphydf** [qTox/qTox#3727]
Always reproducible on all systems.

**Comment by sudden6** [comment]
Only valid for ffmpeg versions > 3.1, since the lowest supported version is 2.6 we will have to do something in the future when ffmpeg removes the `codec` field and replaces it with `codecpar`.
First deprecated in 3.1 https://ffmpeg.org/doxygen/3.1/avformat_8h_source.html#l00877

**Comment by frankcash** [comment]
How would one go about helping to fix this?

**Comment by Diadlo** [comment]
@frankcash It can't be fixed in qTox before we upgrade minimum required ffmpeg version to 3.1. AFAIK, it will be ~when the stable version of Debian will support ffmpeg 3.1

But localy you can read `codecpar` docs and replace `codec`

**Comment by sudden6** [comment]
Closed in https://github.com/qTox/qTox/pull/4266
