### ISSUE TITLE
Small Screen Resizing and PocketChip ./simple_make.sh needs ffmpeg git-compile

### ISSUE THREAD

**Issue by eaterjolly** [qTox/qTox#3728]
## ./simple_make.sh compatibility with [CHIP-linux](https://github.com/NextThingCo/CHIP-linux)
- Needs to git-compile FFmpeg, because the repos are slightly depreciated for debian-jessie-arm it seems and won't install the latest. Compiling is smooth but lengthy (hours), so I would set it to only download it if make produces an unable-to-locate-libswscale error. 
- Also, Chip for some god-awful reason segfaults on the recipe for qrc_smiley, so killing unnecessary user processes becomes necessary to succeed with the compile. Not sure why smileys take up more memory to compile than ffmpeg itself, possible leak in there. Noticed my shell cursor blink asynchronously a little too when compiling that particular file. 
### Locating the resizing files in source; screensize detection would be nice!

   I already tried ./src/mainwindow.ui, and managed to compile it so that the contacts section fits, but over all it's too wide and chat section is still too tall. We need it to fit in a 4.3" screen with a resolution of 480 x 272. There are a lot .ui files and it's hard to tell what ratio the values need to take to and what's relative to what with out analyzing them all side by side. A script that could do this would be really helpful. 

~Thanks to any and all who take an interest in this :tongue:

**Comment by sudden6** [comment]
1. I don't think you'll need to compile ffmpeg from git, just enable backports-jessie for your distribution
2. Qt compiles all the smileys into the binary, this causes gcc to eat a lot of RAM, to make it compile successfully you need at least 0.5 - 1GB free RAM, use Swap if you can't provide enough physical RAM.
3. Your resolution target will be quite a challenge, if I read the code correctly, qTox uses a minimum size of 755x420 and it is set in `src/mainwindow.ui`, just use qtcreator to to edit the files.

**Comment by zetok** [comment]
Regarding target resolution; wouldn't a "mobile" UI do better, rather than trying to re-use the desktop UI?

**Comment by eaterjolly** [comment]
> Regarding target resolution; wouldn't a "mobile" UI do better, rather than trying to re-use the desktop UI?

Optimally chip would like an expandable ui, simply because it runs a modified version of x and is designed to run standard x window systen when plugged into a bigger screen through its aux.

> 1. Your resolution target will be quite a challenge, if I read the code correctly, qTox uses a minimum size of 755x420 and it is set in src/mainwindow.ui, just use qtcreator to to edit the files.

I actually did that to little avail in a standard text editor, as it shrunk only part the ui. instead I modified all instances of that exact minimum size to fit pocketchip's screen. The ratio of difference was slightly above three fourth's, so any lesser minimum or fixed size value characteristics across all found instances were reduced by three fourth's rounded up. Mostly this entailed all .ui files, font sizes specified in some .css files, and certain figure-able .cpp files such as widget.cpp and main.cpp. However the margins in the chat area are still an absurd percentage of the screen and I am having much difficulty finding were the margins are generally specified in the source, however every thing on the app fits the screen with scroll bars only for the settings and the tox id which is cut off slightly despite scroll bars but still copies fine. Anyways the app is clearly usable and package-able for this distribution. Since this is primarily desktop linux, compiling antox would come with its own host of problems I imagine including lacking support for ctrl-q shutdown of the app which is the only elegant way of closing apps open in tiny screen pocket-chip.

Also, I tried the backports and apt found no updates for ffmpeg. I'm facing similar issues with the cmake version debian distributes for arm, though I haven't tried the backports for that one.

It has enough ram, if I kill the home gui fortunately the home-button reinitializes it so I hadn't got locked into the terminal.

**Comment by eaterjolly** [comment]
It would be nice if the were a way to disable smileys without breaking the source, ie deleting qrc_smiley.cpp.

**Comment by sudden6** [comment]
ok, then I also don't know where to look for these margins... My last idea would be to try to use DPI environment variables from QT.

hmm, https://packages.debian.org/jessie-backports/ffmpeg lists a recent enough version of ffmpeg for armhf and armel, are you not using a pure debian build?

There's definitely a way to remove some smiles to reduce RAM usage during compilation. Just remove all but one smileypack from the `smileys.qrc` file. I recommend using `emojione` or `Universe` since they are the most complete.

**Comment by eaterjolly** [comment]
I greatly appreciate the mention of qtcreator, as I'm not familiar with qt. I completely over looked that the first time reading through your comment. I will probably do that the next time I get around to trying to compile this!

**Comment by sudden6** [comment]
Is this still a problem?

**Comment by eaterjolly** [comment]
I left the device in another city. 
I've always planned to return for my little... 
"if Peter Pan had a detonator, that'd look like this" device. 

I should check, next chance I get.
