### ISSUE TITLE
Missing package "qtbase-abi-5-3-2"

### ISSUE THREAD

**Issue by MarcManhart** [qTox/qTox#3732]
##### Brief Description

OS: Linux Debian with kernel 4.6.0-1-amd64 (debian 'stretch')
##### Steps to reproduce
1. Execute: echo 'deb http://download.opensuse.org/repositories/home:/antonbatenev:/tox/Debian_8.0/ /' >> /etc/apt/sources.list.d/qtox.list 
2. Added: repository key
3. Tryed to install via: sudo apt-get install -t testing qtox
##### Behavior

APT can't install because of the dependency to "qtbase-abi-5-3-2"
(My OS is in German-Language thus Ill try to translate the error message)
"Problems can not be corrected, you have retained or broken packages."

What should I do? Even a "apt-get install -t testing -f" won't fix that error.

**Comment by zetok** [comment]
> What should I do? Even a "apt-get install -t testing -f" won't fix that error.

Use Debian stable?

@abbat it's not possible to build packages for Debian 9 on OBS until it gets stabilized, right?

**Comment by abbat** [comment]
@zetok, Yes, OBS does not support testing / unstable Debian.
@MarcManhart, Would you try to install qtox(-alpha) for Debian 7? It is statically linked with Qt and FFmpeg package.

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.

If issue is still not fixed, please comment for reopen.

**Comment by najamelan** [comment]
Still can't install on debian testing, even though I have `libqt5core5a` which provides `qtbase-abi-5-7-1`. Maybe it's more appropriate to depend on  `libqt5core5a`, since `qtbase-abi-5-3-2` is a virtual package that can't be resolved by apt?

**Comment by najamelan** [comment]
I solved it by [overriding the dependency manually](https://serverfault.com/a/383958/68729).

**Comment by tonyl9109** [comment]
i have solved this by removing and reinstalling libqt5core5a, i'm on debian 9 stretch

**Comment by tox-user** [comment]
@tonyl9109 what repository did you use?

**Comment by tonyl9109** [comment]
@tox-user i'm Cuba so i'm using this one -> http://humanos.uci.cu/repositorios/debian/, the stable one

**Comment by anthonybilinski** [comment]
@najamelan @tonyl9109 where are you guys installing qTox from? The repo listed by OP in this issue 404's and has been unmaintained for about a year. Unfortunately, the only currently supported install method for Linux is installing from source using https://github.com/qTox/qTox/blob/master/INSTALL.md
Do you still have issues following these instructions? If so, please open a new issue.
