### ISSUE TITLE
Bluetooth device couldn't be used simultaneously as input and output

### ISSUE THREAD

**Issue by Susurrus** [qTox/qTox#3733]
##### Brief Description

OS: Fedora Linux 24
qTox version: 1.5.1-obs
Commit hash:  f05b7e040a073c7afadaf763dda5beaf130c6dbd
toxcore:  0.0.0
Qt:  5.6
Hardware:  Dell XPS 13 9343
…

Reproducible: Always
##### Steps to reproduce
1. Select a bluetooth headset as both an audio output and input
2. Place a call
##### Observed Behavior

Audio input doesn't work (but audio output does)
##### Expected Behavior

Audio input and output should go through the bluetooth headset
##### Additional Info

I did this because the microphone doesn't work on this Dell in Fedora yet, so I just switched the output to the built-in speakers and that worked. So if you have the microphone working as the input device, without also using it as an output, and then add it as an output, the microphone stops working.

> E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA\tox\`.
> To include it, rename it from `.log` to `.txt`, or zip it.

This didn't exist on my system? Was this file moved somewhere else?

**Comment by zetok** [comment]
> Audio input doesn't work (but audio output does)

Have you tried to check with different program whether your audio input is working?

**Comment by sudden6** [comment]
I suppose Fedora comes with `pavucontrol` if so, could you check that the qTox audio input actually receives a signal with sufficient volume?

Did you verify the audio input with echobot?

**Comment by Susurrus** [comment]
So I fired up things today with echobot to see if I could reproduce the issue and I couldn't. If I select the "PLT Voyager" headset as my input and output, things worked. Note that I did have a second device listed that I could select as an input, the "Monitor of PLT Voyager", which didn't seem to work. Maybe I should file a bug against having all these "Monitor of ..." entries? But I think this issue is resolved.

**Comment by zetok** [comment]
> Note that I did have a second device listed that I could select as an input, the "Monitor of PLT Voyager", which didn't seem to work. Maybe I should file a bug against having all these "Monitor of ..." entries?

`Monitor` is not your input device, but just a monitor of your output device – i.e. by selecting `Monitor` you're using your output device as input.

**Comment by Susurrus** [comment]
@zetok - Thanks and sorry about the noise.
