### ISSUE TITLE
No public key for the xUbuntu 16.04 repo 

### ISSUE THREAD

**Issue by cyian-1756** [qTox/qTox#3746]
##### Brief Description

OS: Linux (Ubuntu Mate 16.04)  
qTox version: NA 
Commit hash:  NA
toxcore:  NA
Qt:  NA
Hardware:  NA
…

Reproducible: Always 
##### Steps to reproduce

Run `sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/antonbatenev:/tox/xUbuntu_16.04/ /' >> /etc/apt/sources.list.d/qtox.list"`

Then run `sudo apt-get update`
##### Observed Behavior

sudo apt-get update outputs

W: GPG error: http://download.opensuse.org/repositories/home:/antonbatenev:/tox/xUbuntu_16.04  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F2AA0B1E5EF8303B
W: The repository 'http://download.opensuse.org/repositories/home:/antonbatenev:/tox/xUbuntu_16.04  Release' is not signed.
##### Expected Behavior

The public key is fetched and the repo is verified

**Comment by zetok** [comment]
You should actually read & follow the instructions on https://software.opensuse.org/download.html?project=home%3Aantonbatenev%3Atox&package=qtox ; closing the issue since it's invalid.
