### ISSUE TITLE
undefined symbol error on ubuntu 14.04

### ISSUE THREAD

**Issue by alexis-mignon** [qTox/qTox#375]
When installing qtox from the repository and trying to launch it i get:

```
qtox: symbol lookup error: qtox: undefined symbol: z_inflateInit_
```

got the same message when using the binary downloaded from the jenkins server

**Comment by dubslow** [comment]
Unfortunately, the devs here aren't the ones who package it for the repo.

@stqism is the one who does it, I'll ping him on IRC

**Comment by stqism** [comment]
The qTox packages are currently under development, that issue is because of how we statically linked Qt5. 

We're currently working on resolving it.

**Comment by dubslow** [comment]
Should be fixed, please try https://jenkins.libtoxcore.so/job/qTox-Linux-pkg/

**Comment by dcharles525** [comment]
@dubslow 

well it opens up and crashes on Linux Mint 17 with this error:
qtox: symbol lookup error: qtox: undefined symbol: _ZN7QString15toLatin1_helperERKS_

Also crashes on Elementary OS, only different error:
./qtox: symbol lookup error: ./qtox: undefined symbol: _ZN9QTextEdit18setPlaceholderTextERK7QString

**Comment by dubslow** [comment]
Someone else reported `_ZN7QString15toLatin1_helperERKS_` as well on Ubuntu 14.04... man this is strange. @stqism

**Comment by dubslow** [comment]
@dcharles525 give this a try, the other user reporting symbol issues said this fixed it.

https://jenkins.libtoxcore.so/job/qTox-Linux-pkg/70/

**Comment by dcharles525** [comment]
@dubslow I just tested it on Linux Mint 17 and it works (hooray!). I will test on Elementary OS later today.

**Comment by dcharles525** [comment]
@dubslow Well looks like I still have a opencv2.4 issue on Elementary OS :/ but looks like that issue has been solved on Mint!

**Comment by dubslow** [comment]
Could you be more specific? How so? ldd error, or missing symbol, or...?

**Comment by dcharles525** [comment]
@dubslow check out issue #493 wanted to move it too another issue to avoid so much noise

**Comment by dubslow** [comment]
Right just saw that, was going through my notifications lol
