### ISSUE TITLE
Don't compile emoji into the binary for packages

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#3753]
Currently all emoticons are statically compiled into the qTox binary. I think this was done because first it's easy and second because it makes the binary portable.
### What this proposal is about:
- Removing the smileys from the binary and putting them into the appropriate folders for the platform
- mainly about Linux and Mac

What this proposal isn't about:
- Changing the portable builds 
### Why?
- Smileys don't change that often, no need to compile and update them with the binary
- It's common practice to separate data from the binary (at least in the *NIX based world)
- reduce resource usage during compile
- packagers could choose not to ship the default emoji packs to optimize resource usage for a given distribution
- ideally (IMHO) qTox wouldn't ship any smileys and could use already installed smiley packs -> probably utopic for now
- on Linux if the emoji are installed to `/usr/share/emoticons/<emoji-pack>` KDE applications could use them too -> unified look
### Steps
1. Allow compiling without emoticons -> WIP in #3737
2. Package emoji so that they are placed in either `$XDG_DATA_DIR/emoticons` or `$XDG_DATA_DIR/qtox/emoticons`
3. Disable compiling with emoticons for packages implementing the above
### Alternatives
- Don't change anything -> well...
- Instead of the raw emoji files it would also be possible to compile and compress them into a `*.qrc` file and use this to dynamically load smiley packs. Advantage would be probably better loading times, but the emoji would be qTox only.

EDIT: paging @abbat because you do the packaging on OBS and have experience

**Comment by zetok** [comment]
> Package emoji so that they are placed in either `$XDG_DATA_DIR/emoticons` or `$XDG_DATA_DIR/qtox/emoticons`

That's wrong – packaging doesn't touch user dirs, where those vars point to.

Emoticons should be installed to `/usr/share/emoticons`

**Comment by sudden6** [comment]
Sorry I misread the [spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and thought this variable is also valid.

I actually meant `/usr/share/emoticons`

**Comment by sudden6** [comment]
Closing this, since nobody thinks splitting the emoji from the binary is a good idea.
Additionally emoji packs are already possible since #3737 was merged.
