### ISSUE TITLE
qTox crashes on Windows when camera settings are changed

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3757]
The Windows user reported that qTox.exe crashes when camera settings are changed.

Anybody uses Windows to troubleshoot this?
##### Brief Description

OS: Windows
qTox version: latest

**Comment by zetok** [comment]
Does it work with on qTox 1.5.2 ?

**Comment by yurivict** [comment]
The problem was originally observed with 1.5.2.

**Comment by zetok** [comment]
Which camera settings were changed, and what camera hardware it is?

**Comment by yurivict** [comment]
I wouldn't know. But someone with Windows should test it and report the results.

Given the nature of the project, I suspect not many/no devs use Windows. But to make it really successful there should be a certain degree of penetration into the Windows user base.

**Comment by zetok** [comment]
> I wouldn't know. But someone with Windows should test it and report the results.

This issue isn't about the case where qTox crashes with every camera device – that was #3612, and in 1.5.2 windows making qTox crash should be fixed.

This issue isn't reproducible by everyone, and e.g. for @initramfs it doesn't crash. So additional info might be needed to fix it, and without it issue might not be useful.

Also would be good to know if #3645 would help here.

**Comment by yurivict** [comment]
I probably won't be able to get any useful particulars from this user. But in order to say that qTox works well on Windows there should be a large number of diverse users who don't complain. I am not sure if this is the case for Windows. I got one user install it, and he saw it crash.

**Comment by sudden6** [comment]
Is this still a problem with recent versions?

**Comment by yurivict** [comment]
Let's assume it isn't a problem for now, until proven wrong.
