### ISSUE TITLE
[feature suggestion] Show QR codes for the contact ToxIDs, not only for user's own ToxID

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3758]
I wanted to add the same user to Antox, but Antox fails to accept the text (messaged and pasted) ToxID due to some bug. It would have been possible to scan it from the screen, but qTox doesn't show QR codes for the contacts ToxIDs.

I think qTox should show QR codes for contacts for flexibility.

**Comment by zetok** [comment]
qTox doesn't have Tox IDs of your contacts, so generating QR codes is out of the question. Thus closing this issue.

Now, what qTox could do, is to offer a right-click option on a `tox:…` link in chatform to show a QR code for the received ID. Or just show QR code automatically in a tooltip when user holds mouse over `tox:…`

If you think that it would be a good thing, open an issue with this, or comment here and I'll open a new issue for it later.

**Comment by yurivict** [comment]
So does this mean that the public key is different from the ToxID? Can I actually add the connected contact to my other device without asking him?

**Comment by antis81** [comment]
> So does this mean that the public key is different from the ToxID?

@yurivict The public key is part of the ToxID -> so yes `pub-key != ToxID`.

> Can I actually add the connected contact to my other device without asking him?

Uhm, what do you mean? AFAIK you need the ToxID to add the friend (just like you need his/her phone number… :smile:).

**Comment by zetok** [comment]
@yurivict 

> Can I actually add the connected contact to my other device without asking him?

Technically, you [can add PK](https://github.com/zetok/tox-add-pubkey) to other profile, but your other profile wouldn't be able to connect to your friend unless your friend also has added your other PK.

**Comment by yurivict** [comment]
If ToxID is > public key, then the answer is no, I can't send this user the friend request without asking him.

If this is true, this is a serious limitation though.

It a friend can be added using only the pubkey, why then this can't be done through the QR code? This seems confusing.

**Comment by antis81** [comment]
> If ToxID is > public key, then the answer is no, I can't send this user the friend request without asking him.

First, the ToxID **is** the public key plus some additional information. Thus you **can** technically extract it. ^^

> If this is true, this is a serious limitation though.

Well, key exchange is always a limitation as somehow you need to get your public key to the other end. And like every transmission, this is a challenging and dangerous journey. :smile:

Before you read on, be sure to check [Tox FAQ - "How to add a friend"](https://tox.chat/faq.html#how-add-friend)

The basic concept of Tox is, to **only** talk with your friends. Thus, hiding the public to the public and just sharing with your friends makes sense finally does it? If you want to share your key, allowing people to look it up similar to a phone book, then you can use [ToxMe](https://toxme.io) lookup service for example. Visibility depends completely on user's decisions -- completely support the idea.

**The question is: What is a ToxID?** Couldn't quickly find an answer on that -> @zetok @tux3 Maybe a little more transparency would be valuable to Tox on this side. For example I am also not a security expert and thus always only "scratching the surface".

**Comment by zetok** [comment]
@antis81 made a nice ascii:
https://github.com/qTox/qTox/blob/abaa41eaeeee77f4663a8223998fe1a582b80be7/src/core/toxid.cpp#L42,L46

@yurivict 

> It a friend can be added using only the pubkey, why then this can't be done through the QR code?

One can add PK. Adding PK doesn't mean that friend will be added. To add a friend, you need whole Tox ID, or you and your friend need to exchange PKs manually.

**Comment by initramfs** [comment]
@yurivict The Tox ID and the public key differs in that the Tox ID has additional information like the nospam code and a checksum. The very idea of attaching a nospam code is such that friend requests can only be made to you by having a valid, up-to-date tox ID. Without such a construct, if your public key actually gets out (goes _public_), you could be faced with a torrent of friend requests that you can't stop (you can ignore them, but you can't stop them coming in). As such, the best way I understand it, is that the nospam code is there to work as a blocking filter, in which unsolicited friend requests are simply dropped. The checksum itself is pretty trivial, it's basically there to validate data entry before submitting into toxcore.

If you look at the usecase of having the ability to "add" a friend at any time (despite already have traded PKs) this is usually limited to having tox running multiple different accounts (on potentially multiple devices). In the first case where tox is running on multiple accounts on the same host, the idea is to provide exclusion between each account (you shouldn't be able to tie one account to another). As such, there would have been no way to add a friend via PK alone on your second account. In the case of having a single alias for multiple devices, this is currently being worked on in a separate issue in which IIRC you will only have one tox ID between all devices and friends/messages may be automatically syned across approved devices, eliminating the manual process of "readding" a friend.
