### ISSUE TITLE
[feature suggestion] Audio/Video settings page should visualize the microphone signal

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3759]
Currently the user can't tell is the microphone is actually working.

I suggest to show the visual indicator on top of the "Gain" slider. It will move left to right, and will have the rainbow-like coloring (redder to the right).

http://www.ese-web.com/images/215.jpg

**Comment by zetok** [comment]
Note: depends on #2705 
Related to #223

**Comment by tox-user** [comment]
@yurivict, @zetok this has been implemented by: https://github.com/qTox/qTox/pull/4790.
