### ISSUE TITLE
[Regression] File transfer widget doesn't show status of transfer

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#376]
Speed is 0, ETA is 0 and there's no progress on bar shown on newest qTox, even though file is successfully transferred. After file transfer has been completed it changes to how successful file transfer should look like.

Tested between newest qTox and µTox.

qTox 018420599c34500a114c4f29a7e7837c3e4c5117

**Comment by dubslow** [comment]
I just received a file from Antox, everything was fine

**Comment by zetok** [comment]
Right, I forgot to mention that I was sending files from qTox

**Comment by apprb** [comment]
Is this problem still exist? At least for me everything works fine.

**Comment by zetok** [comment]
I don't think so; I wasn't able to reproduce it on newest qTox

**Comment by agilob** [comment]
I was able, but I'm not sure if the bug is in Antox or qTox, to reproduce bug, send 250MB+ file from Antox to qTox, nothing happens, can't reproduce with 50MB files.

Calling @Astonex

**Comment by dubslow** [comment]
I got this just now; sent one file to audiobot, no status until complete; second file, however, did show status just fine.

Edit: Several restarts later, I just sent three files to audiobot; none of them showed progress until complete. Maybe over the weekend I'll have time to walk through with a debugger.

**Comment by dubslow** [comment]
I'm thinking this is concurrent with not being able to pause transfers

**Comment by tux3** [comment]
I suggest changing "#define TOX_FILE_INTERVAL 0" to "#define TOX_FILE_INTERVAL 1" in coredefines.h

It could be that we're spamming the event queue so much with file transfers we don't have time to update the UI

**Comment by zetok** [comment]
I still managed to bump into that with qTox 902b13c486f3656eab74d9c318bce9be62336b40 when sending file to audiobotze.

It's really confusing, since it looked like it was waiting for file transfer to be accepted.

![no file transfer](https://cloud.githubusercontent.com/assets/3148759/5198521/f477c02e-7549-11e4-963d-83a840d78dc2.png)

**Comment by dubslow** [comment]
I wouldn't worry about it too much until new chatform.

**Comment by dubslow** [comment]
GUI issue fixed by new chatform, comment for reopen
