### ISSUE TITLE
[Linux] Icon spacing is incorrect with custom session

### ISSUE THREAD

**Issue by nazar-pc** [qTox/qTox#3761]
##### Brief Description

OS: Ubuntu 16.10 x4
qTox version: v1.5.1-obs
Commit hash:  f05b7e040a073c7afadaf763dda5beaf130c6dbd
toxcore: 0.0.0
Qt: 5.6.1

Reproducible: Always
##### Steps to reproduce
1. Execute `XDG_CURRENT_DESKTOP=Custom qtox`
2. Stop qTox
3. Execute `XDG_CURRENT_DESKTOP=GNOME qtox`
##### Observed Behavior

Spacing in 1 on left and right sides is much bigger than normal in 3
##### Expected Behavior

Spacing in 1 should be the same as in 3
##### Additional Info

Demo: https://owncloud.mokrynskyi.com/index.php/s/ZQxSuIv5hw5rlpr

It feels dependent on `XDG_CURRENT_DESKTOP`, however, I have ownCloud and qBittorent compiled with Qt 5.5.1 (not sure what version Slack and Ghetto Skype are using) and they work fine.

Is it something about Qt 5.6 or this a qTox problem?

**Comment by zetok** [comment]
> It feels dependent on `XDG_CURRENT_DESKTOP`

It does.

> Is it something about Qt 5.6 or this a qTox problem?

No, it's a problem with DEs – they cannot into standard tray support, so qTox implements several of them to make sure that things work.

https://github.com/qTox/qTox/wiki/Tray-icon

Use the tray backed that works best for you. If you really want to get it fixed, you'd need to make sure that all DEs that people are using do correctly support Qt tray backend.

**Comment by nazar-pc** [comment]
Thanks for the details, it would be difficult to fix everywhere, but anyway, I've reported upstream: https://github.com/solus-project/budgie-desktop/issues/629
