### ISSUE TITLE
qTox leaves the camera "on" after the call

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3762]
The sequence of actions:
1. The contact called with audio only
2. While talking, I switched to the audio/video test screen (camera went "on")
3. Left audio/video test screen finished the call
4. Observed the camera stayed "on"

I think "video" bit is confused somewhere. If video is only required for the test screen, it should strictly be on during the test screen. There should be no interaction with the unrelated audio call.

version 1.5.1, FreeBSD

**Comment by sudden6** [comment]
Is this still an issue? If not please close.

**Comment by yurivict** [comment]
qTox-1.9.0 with toxcore-0.1.8 doesn't have the problem any more.
