### ISSUE TITLE
Playback Device Volume Always Reverts to 0%

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3764]
##### Brief Description

OS: openSUSE Leap 42.2 Beta 2
qTox version: v1.5.1-obs
Commit hash:  https://github.com/qTox/qTox/commit/f05b7e040a073c7afadaf763dda5beaf130c6dbd
toxcore:  0.0.0
Qt:  5.6.1

I was able to reproduce an issue using the qTox [OBS package](https://build.opensuse.org/package/binaries/home:antonbatenev:tox/qtox?repository=openSUSE_Leap_42.2) on two different machines running openSUSE Leap 42.2 Beta 2. What occurs is when the user navigates into the Audio/Video tab, the Playback device volume slider will be to the furthermost left, at 0%. If the user connects a call and subsequently drags the slider up to 100% it makes no change in the output volume, still staying at 0% volume even though the slider is all the way to the right. If the user exits out of the Audio/Video tab after dragging the slider up to maximum volume, the slider always defaults back to 0%.

I also tested to see if the other party could hear me talking over my microphone, and the result was that they couldn't hear anything even though the capture device was properly chosen. I have tested the openSUSE Tumbleweed [OBS package](https://build.opensuse.org/package/binaries/home:antonbatenev:tox/qtox?repository=openSUSE_Tumbleweed) on the latest openSUSE Tumbleweed snapshot and neither of these two issues occur, meaning calls work as normal.

**Comment by zetok** [comment]
Sounds like an upstream problem.

**Comment by Getron** [comment]
+1 
The same here on Linux Manjaro 16.08 KDE 5.7 Rolling Release.

And one more problem there, every time i switch the tabs, and if i come back to aurio-video tab, the playback device is none selected.

I select it every time, but after moving to other tabs, and switch back to audio-video tab, the playback device is set to none (or empty), i must select itm every time.

i see, that, if i switch the same tabs, for example, switch from audio-video to privacy tab, and then switch back to audio-video tab, the playback device it stay selected.

But, if i switch randomisly the tabs, the playback device disapear, none selected, or is selected, and so one, every time, swtching the tabs the playback device shows none, or selected device.

Somthing is wrong there. Please check it. Try switching tabs randomisly, and you will see the problem with playback device selection.

Just see now, the capture device to, it make the same problem, apear, disapear.

Here i added a quick screen recorded video, that you can see the problems.
[2016-10-03_20-11-47.zip](https://github.com/qTox/qTox/files/506884/2016-10-03_20-11-47.zip)

**Comment by yatsenkoanton** [comment]
Had this problem before, seems to be fixed for me in v1.5.2-175-g9dfdd4e-obs. (Ubuntu 16.04)

**Comment by sudden6** [comment]
Is this still an issue? If not please close.
