### ISSUE TITLE
qTox portable 1.5.2 not working in portable mode

### ISSUE THREAD

**Issue by david-camden** [qTox/qTox#3768]
##### Brief Description

OS: Windows  
qTox version: v1.5.2-131-gabaa41e  
Commit hash:  abaa41eaeeee77f4663a8223998fe1a582b80be7
toxcore:  0.0.0
Qt:  5.6.1
Hardware:  PC, AMD AM2 Phenom X4, 4GB Ram
…

Reproducible: Always
##### Steps to reproduce
1. start qtox in portable folder
2. try to login to portable profile
##### Observed Behavior

does not open the portable qtox.ini in the folder but uses the non portable qtox.ini in userfiles/.../tox with the profile stored there.
ignores the qtox.ini and the profile.tox in the portable folder
##### Expected Behavior

use the qtox.ini and the profile.tox in the portable folder and ignore the other qtox.ini and profile.tox in the installer folder at userfiles/appdata/roaming/tox.

**Comment by zetok** [comment]
Did it work with `1.5.1` ?

**Comment by david-camden** [comment]
yes. there it worked.
qTox v1.5.1-8-gfd04a28 is the version where it works. just got it sent by a friend so he rescued me for now. had it overwritten before without backup.

wanted to have the new version where the general and user interface menu are separated. but that started the trouble, there does portable mode not work.
ignores the qtox.ini in the program folder but uses the one in the appdata folder.

**Comment by DX37** [comment]
v1.5.2-144-gbbdd4f0, bbdd4f0. Portable mode works for me. Have `makeToxPortable=true` option in `[Advanced]` section of qtox.ini file. Maybe in your case this option is in `[General]` section?

**Comment by zetok** [comment]
Looks like another problem with lack of backward compatibility for settings :/

**Comment by DX37** [comment]
Wait-wait-wait, I forgot to post here what that issue seems resolved. I will check right now with latest nightly.

**Comment by DX37** [comment]
Yep, portable mode works on latest nightly (v1.6.0-56 917812d).
But it creates %APPDATA%/tox directory, which remains empty. Should I create another issue, or rename current?

**Comment by zetok** [comment]
>But it creates %APPDATA%/tox directory, which remains empty. Should I create another issue, or rename current?

A new issue would be good. Could you link to this one from it?

Since it seems to be fixed, closing this one.
