### ISSUE TITLE
Unable to uninstall on Windows

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3769]
In the Windows 7 VM, uninstall.exe makes screen to become gray and stay this way. Nothing is happening, machine became unresponsive. Need to reboot.

**Comment by sudden6** [comment]
Is this still a problem or can it be closed?

**Comment by yurivict** [comment]
I don't have Windows, somebody else did.

**Comment by anthonybilinski** [comment]
I just ran uninstall.exe in a Windows 10 VM and it properly opened the wizard and completed successfully.
