### ISSUE TITLE
qTox crashes on Windows right after the account creation, and after start

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3770]
I am trying qTox in the Windows 7 VM. I get a lot of crashes few seconds after start. It seems that this happens during the new version check.

**Comment by yurivict** [comment]
This is a show stopper bug. The fresh latest install spontaneously crashes after several seconds.

**Comment by Talkless** [comment]
I'm currently working on `windows/bootstrap.sh`, made actual build on Windows, and I too started to get crashes few days back. Thought it was something with libraries, build process or whatever, but seems it's not only my problem.

Crash, at least i my case, is in [tox.c, tox_bootstrap(), line 291](https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.c#L291):

```
if (info->ai_socktype && info->ai_socktype != SOCK_DGRAM) {
```

It makes some loops successfully and then crashes. `info` pointer value is `0xababab00` (in debug build) which is kinda strange.

**Comment by zetok** [comment]
@Talkless perhaps toxcore before e6af3a7825e8307a501bc7c3e7b1ff323f081870 wouldn't crash?

**Comment by Talkless** [comment]
No, previous commit `1fa5887fee6016318d02911f78f3610dd0e0dc7f` still crashes.

**Comment by Talkless** [comment]
Binary version v1.5.2-8-gfd04a28 does not crash on my Windows 10 virtual machine, only compiled-one on that machine does. I am not sure if this crash is actually the same as OP's...

**Comment by Talkless** [comment]
@zetok please remove upstream tag.
In my crash case was simply bad mix of MinGW compilers. It was simply timing coincidence with OP's post.

**Comment by Diadlo** [comment]
@yurivict Can you provide more information about errors? Text/log?

**Comment by sudden6** [comment]
Closed because this affects an ancient version of qTox.
