### ISSUE TITLE
qTox on Windows keeps asking to update even though there has been no new release

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3771]
Freshly installed qTox always asks to upgrade it. There has been no new release recently, so it shouldn't ask to upgrade.

It looks like the version for download is out of sync with the version that it checks in runtime. It also possibly tries to always update to the latest build, which it shouldn't do.

**Comment by yurivict** [comment]
Actually, the problem is that the latest version isn't linked to github. It asks for 1.5.2 released 3 days ago.

**Comment by zetok** [comment]
According to #4093 it's still reproducible on 1.7.0

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/4306334/34320544-9b49e402-e80d-11e7-9ad2-eb28dca3cac5.png)

And it never updates...

**Comment by sudden6** [comment]
Auto update has been discontinued in favor of an update notification.
