### ISSUE TITLE
markdown

### ISSUE THREAD

**Issue by aaannndddyyy** [qTox/qTox#3775]
Am using latest nightly of qtox
and am having issues with mark down.
It does not adhere to the official md standards nor to github's md standards. 
Would be nice if qtox used a standard:
##### Brief Description

OS: Linux
qTox version:  v1.4.0-245-g99ce719.
Commit hash: 99ce719b800b5fedeb47eb848268976dcbf96fc7 
toxcore:  0.0.0
Qt:  5.5.0
Hardware:  PC
…

Reproducible: Always /
##### Steps to reproduce
1. write - hello - and write _foo_
2. hit enter
3. …
##### Observed Behavior

hello is underlined
foo is italicized whereas my contact (using ubuntu and qtox) sees it underlined.
##### Expected Behavior

a normal hello with dashes or hyphens 
foo should be the same across both qtox clients

**Comment by zetok** [comment]
Yep, was changed: https://github.com/qTox/qTox/blob/14c97da7d5e5d9bb14f23d84460c0aa160142d25/CHANGELOG.md#breaking-changes

#3404 

Why should qTox default to formatting that most of people are unfamiliar with and is not intuitive?

**Comment by aaannndddyyy** [comment]
because current behaviour is unintuitive and invasive.
why do two underlines make it bold, that is not intuitive and one of the reasons I filed this issue. But it seems that in the source this was already changed, so I must wait for jenkins to catch up.

However, it should NOT change the syntax of a message, but only change the layout.
So '-'+' '+'foo'+' '+'-' is hunderlined, but should NOT have ANY layout effect.

**Comment by sudden6** [comment]
@aaannndddyyy the builds on Jenkins are quite outdated, user OBS qtox-alpha packages for ~nightly experience

**Comment by zetok** [comment]
> But it seems that in the source this was already changed, so I must wait for jenkins to catch up.

Jenkins won't catch up.

**Comment by aaannndddyyy** [comment]
oh. :(
I took it from the wiki. 
Where can I find a nightly of a plain binary , not a .deb or .rpm?

**Comment by zetok** [comment]
> Where can I find a nightly of a plain binary , not a .deb or .rpm?

There won't be one, AFAIK, given that things start to fail to build and no one is going to fix them on jenkins.

**Comment by zetok** [comment]
Needed info not provided for over a month, thus closing.
