### ISSUE TITLE
smileys in menu too small

### ISSUE THREAD

**Issue by aaannndddyyy** [qTox/qTox#3777]
##### Brief Description

OS: Linux 
qTox version: v1.4.0-245-g99ce719
Commit hash:  99ce719b800b5fedeb47eb848268976dcbf96fc7
toxcore:  0.0.0
Qt:  5.5.0
Hardware:  PC
…

Reproducible: Always
##### Steps to reproduce
1. boot the computer
2. log in
3. start qtox
4. click on the smiling face
   ##### Observed Behavior
   a menu with diminute smileys opens up
##### Expected Behavior

a menu with clearly visible and intelligible smileys opens up

**Comment by zetok** [comment]
Can't reproduce on dc10309a82f19cc42e0e46670192e9ea2071af08. Note that emoticon size is adjustable in settings.

Try with newer qTox/Qt, if still reproducible, comment for reopen.

**Comment by aaannndddyyy** [comment]
true. i thought it only affects the size in the chat. so upping default size is definitely a good choice wrt usability. But yes, I can confirm, changing the size in settings effects their size in menu too. 
re newer version: here i cannot compile, so i can only always use the latest nightly build, which I am already
