### ISSUE TITLE
When SOCKS5 proxy is chosen, UDP shouldn't be recommended and "on" by default

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3779]
The problem is that while SOCKS5 protocol nominally supports UDP, many important implementations don't support UDP. Particularly, Tor doesn't support UDP.

qTox probably needs to move 'Enable UDP' under the proxy selector, and not say 'UDP (recommended)' when SOCKS5 is in use. It should default to "off" for SOCKS5. Maybe maintain separate boolean useUDP per proxy, with different defaults and recommendation bits?

Ideally, Tox should test SOCKS5 port for UDP support, and recommend it accordingly. But this would be the toxcore function.

**Comment by zetok** [comment]
> Particularly, Tor doesn't support UDP.

Tor isn't supported in particular, it's just something that works due to SOCKS5 support.

> qTox probably needs to move 'Enable UDP' under the proxy selector, and not say 'UDP (recommended)' when SOCKS5 is in use. It should default to "off" for SOCKS5.

No. Is there any other use-case than Tor support?

With that in mind, user manual probably could benefit from having info about how qTox should be configured for Tor usage. Would you mind making a PR?

**Comment by ghost** [comment]
In my experience, some(but many) VPN/Company's SOCKS5 proxy only accept TCP, not UDP.
So it's safe to assume SOCKS5 = No UDP.

**Comment by yurivict** [comment]
To me this is primarily a security problem. UDP is checked, I know that the proxy doesn't support UDP. The natural question is "Where is UDP sent? Is it even sent?" Tox should be more proactive answering such questions. Otherwise how do I know UDP isn't sent into the clearnet?

**Comment by zetok** [comment]
> Otherwise how do I know UDP isn't sent into the clearnet?

Err. Given the nature of Tor, things (TCP) are being transmitted through "clearnet" anyway. So if you're using it in hope that things don't go through "clearnet", you're using the wrong tool. I'd suggest looking into i2p.

> To me this is primarily a security problem. UDP is checked, I know that the proxy doesn't support UDP. The natural question is "Where is UDP sent? Is it even sent?" Tox should be more proactive answering such questions.

When it comes to security, as a general rule of thumb you should assume the worst-case scenario.

**Comment by x368** [comment]
To clear up some misunderstandings:

One specific protection is explicitly missing in Tox, one's ip number is exposed to the observers.
The leak of this particular information can be very sensitive and ruin the privacy of the communication.

Fortunately routing Tox traffic via Tor adds the ip protection.
Unfortunately sending UDP to clearnet would reveal the ip number to the observers and fully break this additional protection, defeating the very purpose of using Tor.

This is why this issue report makes a lot of sense.
UDP as the default for SOCKS hardly offers a noticeable gain, given the practical limitations of many SOCKS gateways. At the same time it may be breaking the user effort to remain safe.

Another detail about Tor: even though this is not relevant in the context of Tox (where Tor protects the location information, not the traffic), it is incorrect to assume that Tor necessarily sends traffic over clearnet (for a deeper explanation look up "hidden services").

**Comment by yurivict** [comment]
Ideally, Tox should register the hidden service using the Tor control port to enable Tor-only connections. But this is also besides the point of this bug report.

**Comment by zetok** [comment]
Note: if any type of proxy is set, `Use UDP (recommended)` should change to `Do not use UDP (recommended)`, with a tooltip `It is not recommended to use UDP with proxy for privacy purposes.`

Or something like that.

**Comment by sudden6** [comment]
The discussion on IRC revealed that even if a proxy is selected an activated and UDP is selected toxcore tries to use the non-proxied network for UDP and only uses the proxy for TCP.

**Comment by yurivict** [comment]
^^^ This is the security violation. This is the whole point of this bug to guard against such things.

**Comment by anthonybilinski** [comment]
This was fixed by https://github.com/qTox/qTox/pull/5189 (qTox UI blocks proxy and UDP from being enabled at the same time, enabling proxy disables UDP.) The change is present in v1.16.0 or later.

**Comment by yurivict** [comment]
Thanks!
