### ISSUE TITLE
error while loading shared libraries: libopencv_core.so.2.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dcharles525** [qTox/qTox#378]
qTox use to work, now the latest version wont let me run it :(

**Comment by dubslow** [comment]
What distro are you using?

How did you get the previous versions that used to work? Did you compile them yourself, or from Jenkins, or...?

**Comment by dcharles525** [comment]
@dubslow I am running Elementary OS, I tried on my laptop as well which is running Linux Mint. I get the packages from Jenkins, I follow the link from the readme.

**Comment by dubslow** [comment]
Okay, what do you get when you run `apt-cache search libopencv-core2.3` and `apt-cache search libopencv-core2.4`? I'm going to guess that the latter produces nothing while the former shows packages...

**Comment by dubslow** [comment]
@stqism, isn't Jenkins supposed to be on Debian stable with 2.3?

@tux3, this is why we still need to support cv2.3...

**Comment by dcharles525** [comment]
2.3 = libopencv-core2.3 - computer vision core library
2.4 = nothing

It use to work perfectly with no problems.

**Comment by stqism** [comment]
@duslow: For some odd reason it isn't statically linking opencv2, we might have to provide packages for that + Qt5 as well for stable.

**Comment by dcharles525** [comment]
So this is finally going to be solved?

**Comment by tux3** [comment]
qTox is now statically linking OpenCV, although some dependencies of opencv are now dynamically linked. This issue is technically solved, but the packages might still not work.

**Comment by noisesfromspace** [comment]
Still having the troubles with the deb from the repository. Compiling from source did the trick for anyone reading this.

**Comment by dubslow** [comment]
Could you try one more time with build [#109](https://jenkins.libtoxcore.so/job/qTox-linux-pkg/) plus? (Preferably the latest of course.) The packager claims he fixed a related issue starting with 109.

**Comment by dcharles525** [comment]
@dubslow seems to be fixed only I get another error when installing .deb :( 
![screenshot from 2014-10-22 20 27 36](https://cloud.githubusercontent.com/assets/4961680/4746586/78e8b4fe-5a4b-11e4-9c54-eb38ce5c9acb.png)

**Comment by noisesfromspace** [comment]
Nope still not working

```
#sudo apt-get update
Ign http://repo.tox.im testing/main Translation-en_US                          
Ign http://deb.torproject.org jessie/main Translation-en             
Ign http://repo.tox.im testing/main Translation-en    

sudo apt-get install qtox                                              !3224
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qtox : Depends: libopencv2.4-core but it is not installable
        Depends: libopencv2.4-highgui but it is not installable
E: Unable to correct problems, you have held broken packages.

```

**Comment by dubslow** [comment]
@stqism

**Comment by tux3** [comment]
This should be fixed.
