### ISSUE TITLE
UI should reflect that connection is made through UDP and TCP

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3787]
Based on this comment, the callback notifying of TCP/UDP being in use is available:
https://github.com/irungentoo/toxcore/issues/1619#issuecomment-251862556

qTox should show the sign next to the "Enable UDP" checkbox when it is checked, but the actual protocol is TCP.

TCP/UDP symbol could also be displayed near the status icon.

**Comment by zetok** [comment]
> Based on this comment, the callback notifying of TCP/UDP being in use is available:
> https://github.com/irungentoo/toxcore/issues/1619#issuecomment-251862556

Yes, for separate connections to each online peer.

> qTox should show the sign next to the "Enable UDP" checkbox when it is checked, but the actual protocol is TCP.

Not doable. toxcore always tries to connect with UDP if UDP is not turned off.
