### ISSUE TITLE
Groupchats self name doesn't work properly

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#379]
Symptoms: On initial join, messages display your own name fine. However, on peer change, your own messages are displayed as "<Unknown>", and on further peer changes sometimes your own name appears in the list of connected peers, while your own messages still appear as "<Unknown>".

This is _likely_ an issue with how qTox handles the peer list, but it might also be a core issue or maybe a misunderstanding of how core handles peers. Edit: See chat log:

> <bunslow> irungentoo: qtox looks up all group message authors in the peer list
> <bunslow> and it appears that one's self isn't in the peer list
> <bunslow> except currently i also see myself in the list of other people connected that qtox shows
> <bunslow> so im not entirely sure if qtox is mishandling peers or core is mishandling its self peer number
> <bunslow> _probably_ qtox, but i'd have to dig deeper
> <Jfreegman> just compare it to toxic
> <irungentoo> utox uses tox_group_peername()
> <irungentoo> every time it receives a group message
> <Jfreegman> toxic keeps track of people who enter and leave
> <irungentoo> I might have accidentaly messed up something in the tox_callback_group_namelist_change callback
> <bunslow> hmm, qtox has its own peerlist
> <bunslow> interesting
> <bunslow> at any rate, i need to go for now

**Comment by krepa098** [comment]
This should fix it but I haven't done any serious tests yet.

**Comment by dubslow** [comment]
Damn dude, you have a bunch of branches with a bunch of stuff, e.g. what's up with https://github.com/krepa098/qTox/commits/core? Will any of these branches be merged?

**Comment by krepa098** [comment]
core will probably never be merged as the current code works good enough (although it's dirt ugly :P). Well, maybe I'ill pick it up sometime in the future...

**Comment by dubslow** [comment]
Hmm nope, I just got an unknown for myself just now. I vote we simply just go to tox_group_peername() as irungentoo said.

Edit: Oh wait that fix didn't make it into your PR lol, nevermind
