### ISSUE TITLE
Update noptification icon properly

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3795]
Stupid Github doesn't let me upload an image file.
http://expirebox.com/download/277c38163de6bc3e92ed601611df48f6.html

**Comment by zetok** [comment]
image from link:
![1922d177de47318d55087e8fc853affa](https://cloud.githubusercontent.com/assets/3148759/19211458/b4c74fee-8d34-11e6-85ba-cf80ae406989.jpg)

**Comment by AliceGrey** [comment]
@zetok @GitHubHatesTor I am unable to reproduce this issue. I told qtox to connect to a proxy that was down and this is what rendered.
Edit: The icon still displays properly with ipv6 enabled. I just usually leave it off and double checked with it on.
![notification bar](http://i.imgur.com/MRZGeVJ.png)

**Comment by zetok** [comment]
@AliceGrey Right.

Steps:
1. Connect to working proxy
2. Take proxy down
3. ![spectacle ea7954](https://cloud.githubusercontent.com/assets/3148759/19229254/18da7e26-8ec4-11e6-86ac-14a56fae4389.png)

**Comment by AliceGrey** [comment]
@zetok Should this be closed since it's not reproducible and the creator hasn't responded?

**Comment by zetok** [comment]
@AliceGrey err? It's reproducible, I've posted the steps.

**Comment by AliceGrey** [comment]
@zetok You said > Right. I thought you meant you weren't able to reproduce it.

**Comment by zetok** [comment]
Sorry, I should have been more verbose. What I meant was "Oh, so it's not obvious what the steps are. Right. Here are the steps"

**Comment by AliceGrey** [comment]
@zetok No worries, I'll see what I can do to get this one fixed.

**Comment by AliceGrey** [comment]
@zetok I've done some poking around in my free time and it looks like after being disconnected from the proxy and DHT `updateIcons()` never gets called. It does get called when it connects though.

**Comment by AliceGrey** [comment]
@zetok From what I've read in the code, `updateIcons()` gets called by `onStatusSet()` which is connected to `Core::statusSet`. 

Where I get lost is when DHT gets disconnected when you take down the proxy, `emit disconnected();` gets called which then calls `onDisconnected` which  does `emit statusSet(Status::Offline);` which should trigger `onStatusSet()` and call `updateIcons()` but for some reason it never gets to `updateIcons()`

**Comment by AliceGrey** [comment]
@zetok After A LOT of digging and debugging I found the culprate. I'll submit a PR :+1:

**Comment by Diadlo** [comment]
@AliceGrey 

> but for some reason it never gets to 

Becouse `Offline` status [here](https://github.com/qTox/qTox/blob/master/src/core/core.cpp#L879:L880) leads to the `default` case and return without `emit statusSet(status);`
