### ISSUE TITLE
About Disconnection bug: implement TorID - support multiple(Tox and Tor) protocol

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3796]
Tox:
Use Tox protocol with looooooong ID

TorChat/Ricochet:
Use Tor and it's xxxxxxxxxxxxxx.onion name.

https://github.com/ricochet-im/ricochet

**Comment by zetok** [comment]
Could you elaborate what the proposal is about?

**Comment by ghost** [comment]
I mean, will it be possible to chat with "Ricochet" user with "qTox+Tor Proxy"?
Ricochet/TorChat are just using Tor Hidden Service.

**Comment by zetok** [comment]
No, that's not possible and will not be possible.

I've added FAQ entry that explains things in more detail: https://github.com/qTox/qTox/wiki/FAQ#support-for-other-instant-messaging-protocols
