### ISSUE TITLE
Test sound button should be red if disabled

### ISSUE THREAD

**Issue by Diadlo** [qTox/qTox#3800]
##### Brief Description

OS: Any
qTox version: v1.5.2-73-g894b47a.
Commit hash: 894b47ad7794a808e63f6234bec3a3af26107b12

Reproducible: Always 
##### Steps to reproduce
1. Open AV settings tab
2. Click on green `play a test sound` button
##### Observed Behavior

Appear/disappear shadow around button
##### Expected Behavior

Changing color of button on red/green

**Comment by zetok** [comment]
Color is not intuitive for colorblind

**Comment by Diadlo** [comment]
@zetok Tiny shadow line is not intuitive for everyone. But you are right. Also it can show/hide speaker or sound waves

**Comment by AliceGrey** [comment]
@Diadlo  Considering the icon is green already I can see the expectation of it being red when disabled. But as @zetok mentioned color isn't intuitive for colorblind people. What if we had a red or grey icon that was crossed out?

**Comment by Diadlo** [comment]
@AliceGrey What problem with changing color + speaker icon? For me it seems more intuitive

**Comment by AliceGrey** [comment]
@Diadlo [https://en.wikipedia.org/wiki/Color_blindness#Red.E2.80.93green_color_blindness](url)

**Comment by Diadlo** [comment]
@AliceGrey I understand. That's a reason why I suggest using icon changing too

**Comment by AliceGrey** [comment]
@Diadlo Oh my bad, I misunderstood what you meant. I agree we should change the icon.

**Comment by AliceGrey** [comment]
@Diadlo @zetok What about something like this when disabled? (I should note I didn't make these icons and they might not be open source, just something I found on google) 
![sound icon](https://cdn3.iconfinder.com/data/icons/pyconic-icons-1-2/512/volume-minus-64.png)

Or another idea:
Off
![sound off](https://cdn1.iconfinder.com/data/icons/material-audio-video/16/volume-mute-64.png)

On
![sound on](https://cdn4.iconfinder.com/data/icons/geomicons/32/672411-speaker-volume-64.png)

**Comment by zetok** [comment]
> What if we had a red or grey icon that was crossed out?

Crossed out icon sounds good to me.

Not sure about `speaker -` icon, since the minus suggest just decrease instead of turning off.

**Comment by AliceGrey** [comment]
@zetok @Diadlo Something like this?
Off
![sound on](https://cdn1.iconfinder.com/data/icons/material-audio-video/19/volume-off-64.png)
On
![sound on](https://cdn1.iconfinder.com/data/icons/material-audio-video/18/volume-up-64.png)

**Comment by Diadlo** [comment]
@AliceGrey Icons LGTM. And maybe replace unintuitive button on checkbox?)
Because button with on/off state can be interpreted as on/off sound

**Comment by AliceGrey** [comment]
@zetok What do you think about having a checkbox instead?

**Comment by zetok** [comment]
@AliceGrey Whatever works.

Checkbox is more clear than an icon, but might not look as good.

**Comment by AliceGrey** [comment]
@Diadlo @zetok 
I made some quick builds with different ideas. Let me know which one you like best.

Checkbox v1 
![checkbox1](http://imgur.com/gpnrqtk.png)

Checkbox v2 
![checkbox2](http://imgur.com/78bjQZ2.png)

Icon v1 
![icon1](http://imgur.com/qfTGdOZ.png)

**Comment by zetok** [comment]
@AliceGrey `checkbox v1` is probably the best.
