### ISSUE TITLE
test sound after logout & load is active even though button is in `off` position

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#3809]
##### Brief Description

Test sound button (![spectacle fv7076](https://cloud.githubusercontent.com/assets/3148759/19272351/2dcab8f8-8fc0-11e6-8f78-04b8b9d12d19.png)) in A/V tab after logout & load is not set, but sound is still produced.

OS: Gentoo Linux amd64
qTox version: v1.5.2-175-g9dfdd4e
Commit hash: 9dfdd4ef4bf9bcd863a2371ced3f2861aa7de5a7
toxcore: 0.0.0
Qt: 5.6.1

Reproducible: Always
##### Steps to reproduce
1. Set button in `on` position (click)
2. Logout
3. Load profile
4. Go to settings and change volume
##### Observed Behavior

Button is in `off` position, sound is produced.
##### Expected Behavior

Button should reflect reality, i.e. be in `on` position.
##### Additional Info

Aside from `master`, #3808 is also affected.

**Comment by sudden6** [comment]
Closed with https://github.com/qTox/qTox/pull/3808
