### ISSUE TITLE
No system tray detected!

### ISSUE THREAD

**Issue by StSav012** [qTox/qTox#3816]
##### Brief Description

OS: Ubuntu 16.04.1 LTS 64bit with GNOME Flashback (Metacity) running
qTox version: v1.4.0-245-g99ce719
built on:  05:39:06 Jul  6 2016 ( 1467797925 )
Commit hash:  99ce719b800b5fedeb47eb848268976dcbf96fc7
toxcore: 0.0.0
Qt: 5.5.1

Reproducible: Always
##### Steps to reproduce
1. Launch qTox.
2. Set **Start in tray** option in **Settings**.
3. Restart qTox.
##### Observed Behavior

qTox starts with its window displayed.
##### Expected Behavior

qTox starts hidden in tray.
##### Additional Info

qTox apparently hides into the system tray after minimizing it manually. Option **Minimize to tray** should be enabled for that to work.

That's the application output to stdout:

```
src/persistence/settings.cpp:122 : Debug: "Loading settings from /home/stsav012/.config/tox/qtox.ini"
src/ipc.cpp:46 : Debug: Our global IPC ID is  12457686047708636504
src/main.cpp:197 : Debug: built on:  05:39:06 Jul  6 2016 ( 1467797925 )
src/main.cpp:198 : Debug: commit:  99ce719b800b5fedeb47eb848268976dcbf96fc7 

src/persistence/profile.cpp:86 : Debug: Loading tox save  "/home/stsav012/.config/tox/StSav012.tox"
src/persistence/settings.cpp:387 : Debug: "Saving global settings at /home/stsav012/.config/tox/qtox.ini"
src/persistence/settings.cpp:305 : Debug: Loading personal settings from "/home/stsav012/.config/tox/StSav012.ini"
src/nexus.cpp:71 : Debug: Starting up
src/core/core.cpp:232 : Debug: Loading user profile
src/persistence/profile.cpp:243 : Debug: Loading tox save  "/home/stsav012/.config/tox/StSav012.tox"
src/core/core.cpp:128 : Debug: Core starting with IPv6 enabled
src/core/core.cpp:301 : Debug: Self avatar not found, will broadcast empty avatar to friends
src/core/core.cpp:403 : Debug: "Connecting to %ip%:33445 (%username%)"
src/core/core.cpp:403 : Debug: "Connecting to %ip%:33445 (%username%)"
src/core/core.cpp:403 : Debug: "Connecting to %ip%:33445 (%username%)"
src/core/core.cpp:403 : Debug: "Connecting to %ip%:33445 (%username%)"
src/core/core.cpp:370 : Debug: Connected to the DHT
src/persistence/profile.cpp:308 : Debug: Saving tox save to  "/home/stsav012/.config/tox/StSav012.tox"
src/widget/widget.cpp:1830 : Warning: No system tray detected!
```

Do please excuse me if the bug has already been reported.

**Comment by zetok** [comment]
Use the OSB repo and check if it's fixed with newer qTox.

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.

If issue is still not fixed, please comment for reopen.

**Comment by StSav012** [comment]
Well, I've got my own problems then. It turned out that my tray was not displayed whatever I tried to place there. Now I think that the problem was not in qTox itself but in the desktop. Having no solution found, I have switched to xfce. Now it works as designed. Thanks.
