### ISSUE TITLE
Graphical glitches with groupchats

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#382]
Groupchat with a lot of peers, steps similar to those in #255 except for small window.

That's how qTox window looks under i3:
![2014-10-01 steam borderlands 3 pucharse](https://cloud.githubusercontent.com/assets/3148759/4519593/4d292718-4cc2-11e4-8fb6-8e60caa7c2b7.png)

I think that proper solution would be to put nicks in separate column, since design taken from µTox with nicks on top is obviously broken..

**Comment by ghost** [comment]
I can confirm also here is a video showing how to reproduce the issue 
http://www.mediafire.com/download/cwnsadbl7dl20my/vokoscreen-2014-10-10_22-02-30.mkv

**Comment by tux3** [comment]
Fixed by using a flow layout, and setting an appropriate minimum size for the friendlist so it doesn't disappear randomly.
