### ISSUE TITLE
lost position of the window

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#3821]
##### Brief Description

OS: Linux Debian
qTox version: v1.5.2-191-g0669bce
…

Reproducible: ? 
##### Steps to reproduce
1. qtox window in normal state
2.   hide
3. restore
   ##### Observed Behavior
   lost position of the window
##### Expected Behavior

restore in previous coordinates
##### Additional Info

(links, images, etc go here)

---

UPD: Reproducible only with first build

**Comment by sudden6** [comment]
Can you explain "Reproducible only with first build" in more detail please?

**Comment by sudden6** [comment]
Closed, because needed information was not provided
