### ISSUE TITLE
libnetcdf.so.12

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3824]
netcdf update broke it.
qtox will not open.

**Comment by zetok** [comment]
Are you sure? qTox has nothing to do with this lib.

How exactly did you verify that updating netcdf broke qTox?
Steps to reproduce?
Etc?
There's an issue template for a reason.

**Comment by ghost** [comment]
sorry.

os: Antergos Linux
kernel: x86_64 linux 4.8.2-1ARCH
nvidia 330m and i7

it was working fine before arch released an update for netcdf. looked in the release and they went back to libnetcdf.so.11

`qtox: error while loading shared libraries: libnetcdf.so.12: cannot open shared object file: No such file or directory
`

**Comment by Diadlo** [comment]
@solus667 I think, rebuild (or reinstall) can help you

**Comment by zetok** [comment]
@solus667 which qTox version, and how did you get it?

**Comment by Kron4ek** [comment]
Already fixed in Arch, so also fixed in Antergos.
