### ISSUE TITLE
Debian Repo release key invalid

### ISSUE THREAD

**Issue by naortega** [qTox/qTox#3874]
#### Basic Description
I get an invalid key warning when adding the qTox repo to my `sources.list.d/qtox.list`.

OS: Debian GNU/Linux Stretch (Testing) 
qTox version: N/A
Commit hash: N/A
toxcore: N/A
Qt: N/A
Hardware: amd64
…

Reproducible: Always

##### Steps to reproduce
Follow the 
1. Follow the Debian installation instructions for OpenSUSE
2. Add the key
3. It breaks.

##### Observed Behavior
It tells me this when I run `apt-get update`:
```
W: GPG error: http://download.opensuse.org/repositories/home:/antonbatenev:/tox/Debian_7.0  Release: The following signatures were invalid: EXPKEYSIG F2AA0B1E5EF8303B home:antonbatenev OBS Project <home:antonbatenev@build.opensuse.org>
W: The repository 'http://download.opensuse.org/repositories/home:/antonbatenev:/tox/Debian_7.0  Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

##### Expected Behavior
I should see nothing.

##### Additional Info
I made sure to run the usual commands, like `apt-get clean` and `apt-get update` and such. The key keeps saying it's invalid (I got the same result for both oldstable and stable).

This is not something that should be different just because I'm running testing instead of Stable/OldStable, since a signature verification is a signature verification.

@abbat, I was told on the qtox IRC to mention you.

**Comment by abbat** [comment]
Seems temporary problems with OBS (not qtox only affected).

**Comment by abbat** [comment]
My fault, key really expired. You have to update key:

```
$ wget -O - http://download.opensuse.org/repositories/home:antonbatenev:tox/Debian_Stretch/Release.key
 | sudo apt-key add -
```

or

```
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0xF2AA0B1E5EF8303B
```

**Comment by naortega** [comment]
Alright, it's all working now. I also appreciate the Stretch repo :wink: 
Thanks!
