### ISSUE TITLE
Important note is untranslated

### ISSUE THREAD

**Issue by Diadlo** [qTox/qTox#3875]
##### Brief Description

OS: Linux
qTox version: v1.5.2-238-gfb45aa4
Commit hash: fb45aa4929e5dbc83a4e3e304afa87222c995e5f
toxcore: 0.0.0
Qt: 5.7.0

Reproducible: Always

##### Steps to reproduce

1. Select any language
2. Goto `Advanced tab`

##### Observed Behavior
Important note is untranslated

##### Expected Behavior
Translated important note

**Comment by sudden6** [comment]
Hmm, there's a translation for that String available on weblate, but not applied.

**Comment by Diadlo** [comment]
@sudden6 I think, it's doesn't updates in `retranslateUI`

**Comment by sudden6** [comment]
Has been fixed somewhere on the way to https://github.com/qTox/qTox/commit/4bcb8f65926504d9202bdc6dfdff19c0fa0d7885

**Comment by Diadlo** [comment]
It isn't
![spectacle i20894](https://cloud.githubusercontent.com/assets/6306608/23340425/21c5a84e-fc47-11e6-9017-a43ec237570d.png)

**Comment by sudden6** [comment]
It is in German

![grafik](https://cloud.githubusercontent.com/assets/5585762/23340627/eb223efe-fc39-11e6-97a3-0b97a0f1f78c.png)

Maybe russian translation is wrong/missing? look for an error in qTox console output.

**Comment by Diadlo** [comment]
Are you sure, that you not relogin/restart after language change?

**Comment by sudden6** [comment]
Ah, so you mean the real problem is it's not translated immediately?

**Comment by Diadlo** [comment]
Yes

**Comment by Diadlo** [comment]
Sorry, duplicate of #1695, so it will be closed
