### ISSUE TITLE
Provide a binary installer of 1.6.0 for macOS 

### ISSUE THREAD

**Issue by ddobrev** [qTox/qTox#3883]
qTox 1.6.0 is finally out but there's no installer for macOS, please provide one.

**Comment by zetok** [comment]
Due to #3747 it wouldn't really work.

So right now build instructions should be followed to get qTox on OSX: https://github.com/qTox/qTox/blob/master/INSTALL.md#os-x

**If** there will be a patch that will make things work again merged long before the 1.7 release, patch release 1.6.1 with it will be made.

**Comment by ddobrev** [comment]
What does it take to fix #3747 ? As far as I understand, unless it's fixed, we macOS users (the overwhelming majority of who can't or won't compile qTox themselves) are stuck with 1.4.1 which is months old.

**Comment by zetok** [comment]
> What does it take to fix #3747 ?

It seems to be fixed in https://github.com/TokTok/qTox , so someone would need to port back the improvements. Will be done at some point, but might not be quick. As always, additional help would speed things up.

> (…) macOS users (the overwhelming majority of who can't or won't compile qTox themselves) (…)

Is there any reason why someone on osx wouldn't be able to compile qTox, aside from lack of will? There are instructions on how to use the script that does all the work.

**Comment by ddobrev** [comment]
_someone_ might. The majority of users won't, especially each time a new version is released. If there actually is a fix, could you ask the author to create a pull request for you? I assume you have regular talks with her anyway since she is the new maintainer of Tox.

**Comment by zetok** [comment]
> If there actually is a fix, could you ask the author to create a pull request for you?

https://github.com/qTox/qtox-irc-logs/blob/45396c79d266351e39ab99e58afb49a582e9c5a5/2016/11/%23qtox_20161108.log.txt#L153,L163

**Comment by ddobrev** [comment]
@zetok @iphydf it's been a month. Do you plan to actually combine your efforts and fix this one instead of blaming each other, or should we all consider qTox for macOS dead?

**Comment by Diadlo** [comment]
Migration to CMake (#3913) will be merged after Toktok migration (#3736). Be patient, please :)
@iphydf said, that his version of CMake works correct on OSX

**Comment by ddobrev** [comment]
@Diadlo thank you very much, finally the productive answer I've been searching for. I look forward to the restored qTox for macOS.

**Comment by iphydf** [comment]
@ddobrev clearly we have combined our efforts. @Diadlo has been leading the merge, and I've been answering questions regarding the cmake stuff I made.

**Comment by ddobrev** [comment]
@iphydf I was extremely happy to hear it being totally unaware before. Thank you for your work.

**Comment by zetok** [comment]
@ddobrev 
>@zetok @iphydf it's been a month. Do you plan to actually combine your efforts and fix this one instead of blaming each other, or should we all consider qTox for macOS dead?

Do you plan on doing anything else than producing useless comments? Like actually helping?

>@Diadlo thank you very much, finally the productive answer I've been searching for. I look forward to the restored qTox for macOS.

Too bad that for all the searching of an answer done you couldn't even find out how to help.

If you want osx support help with it. That's about it.

And if you want to blame someone for osx support dying, how about starting from yourself? After all, you are the one who has that os and can test/fix things under it.

**Comment by ddobrev** [comment]
Useless? That's a good one. I have reported 14 issues and given my vote you for many others, almost all of them universal - to little avail. Whatever, I have already made my peace with the fact that qTox is not going to be useful to the general public any time soon. I'll just keep using it with a few other technical people who can put up with it and keep Skype for all the rest.

**Comment by zetok** [comment]
>Useless? That's a good one. I have reported 14 issues and given my vote you for many others, almost all of them universal - to little avail.

Reporting issues is great. Producing passive-aggressive comments that have little or nothing to do with those issues is not.

**Comment by ddobrev** [comment]
Superseded by https://github.com/qTox/qTox/issues/4063.
