### ISSUE TITLE
User marked as talking when there's no groupchat participants

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#3886]
##### Brief Description
While in groupchat, user is marked as talking while there are no other people in groupchat, and there is no audio.

OS: Gentoo amd64
qTox version: v1.5.2-243-gdcfbdf8
Commit hash: dcfbdf8f95c865c8336ed5ffbc094b91fb2315b2
toxcore: 0.0.0
Qt: 5.6.1

Reproducible: Always

##### Steps to reproduce

1. Start new groupchat and invite a contact
2. Both start audio chat
3. invited contact leaves groupchat
4. own instance is still marked as talking

##### Observed Behavior
User is still marked as talking, even though according to log audio was turned off.

##### Expected Behavior
User should not be marked as talking.

##### Additional Info
![spectacle tq8032](https://cloud.githubusercontent.com/assets/3148759/20341715/40ddb194-abdf-11e6-97f2-e07a87bc8eee.png)

**Comment by antis81** [comment]
Could it be a misinterpretation of the status bar? If I get it right, the group chat's status bar doesn't mark a user as "talking", but only being part of the group - which is correct. In reality a group disappears and is closed, if the "member count" drops to 0.

**Comment by zetok** [comment]
> Could it be a misinterpretation of the status bar? If I get it right, the group chat's status bar doesn't mark a user as "talking", but only being part of the group - which is correct.

No.

**Comment by sudden6** [comment]
@antis81 no, there's functionality to mark a user as "talking" but IIRC it's not working/disabled.
@zetok The green highlighting is marking "your" username, IIRC again speaking was red.

**Comment by zetok** [comment]
@sudden6 oh, right. Sorry, I forgot about that.

**Comment by antis81** [comment]
@zetok @sudden6

Ah ok, you talk about AV features. With the current implementation in `master` the call status (friend or group) simply cannot be reflected correctly and is actually guessed in certain places. And so the call buttons may or may not show a correct status. This core feature set is added and **completely solved** for friend calls in #3639 and targeted for group calls as well (works a bit different there). There's some really interesting WIP available now in #3676, which from today starts to support group chats (at least invitations work again :stuck_out_tongue:). Anyway there's quite some TODO's, which highly break existing features from a user's viewpoint. Therefore I see two possible (sane) ways to solve this situation:
1. We should consider declaring that branch as an "integration branch", which encapsulates hot development tasks from the more or less stable master branch. That means all current open PR's switch from master to `ui/redesign` and the whole milestone is merged, when everything's done here.
2. Make use of the recent workflow and merge into master **right now**, which is basically the same, only that the unfinished/breaking stuff is released as "alpha" and it makes no sense at all to create user issues for that.

Whatever we decide. Those changes are needed to further move away from that "playground project" image, which highly frustrates both users and contributors. Thus, I highly appreciate your recent efforts to create a release schedule etc. which definitely is a step into the right direction again.

**Comment by zetok** [comment]
@antis81 there's 3rd option, something that @Diadlo already started doing.

 Merge in small chunks what works, that's the only way this thing is going to get merged. Otherwise the amount of regressions from PR will stop progress, and ongoing changes on master will cause increased load of conflicts to solve.

What goes on master works.
