### ISSUE TITLE
Problem import profile

### ISSUE THREAD

**Issue by Potracheno** [qTox/qTox#3887]
##### Brief Description

Ubuntu 14.04.5 LTS 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
qTox v1.5.1-obs.  
Commit hash:  f05b7e040a073c7afadaf763dda5beaf130c6dbd
toxcore:  0.0.0
Qt:  5.6.1
Hardware:  Lenovo b590
…

Reproducible: Almost Always

##### Steps to reproduce

1. Start qtox
2. Try import profile 

##### Observed Behavior
System stuck
High load of hdd
Only hard reset help

##### Expected Behavior
Navigate folder for choose profile

`(qtox:2660): Gtk-CRITICAL **: IA__gtk_widget_style_get: assertion 'GTK_IS_WIDGET (widget)' failed
[10:03:27.477 UTC] :0 : Warning: QXcbShmImage: shmget() failed (22: Invalid argument) for size 1073610756 (16383x16383)

(qtox:2660): Gtk-CRITICAL **: IA__gtk_widget_style_get: assertion 'GTK_IS_WIDGET (widget)' failed`

Almost the same when I try to change Default directory to save file

`(qtox:2988): Gtk-CRITICAL **: IA__gtk_widget_style_get: assertion 'GTK_IS_WIDGET (widget)' failed
[10:17:48.150 UTC] :0 : Warning: QXcbShmImage: shmget() failed (22: Invalid argument) for size 1073610756 (16383x16383)
`

**Comment by sudden6** [comment]
Probably a problem with the folder browser dialog. Does it happen before you click "OK" after you have selected the profile?

**Comment by Potracheno** [comment]
I can't choose nothing. I click on import button then see transparent window of the folder browser dialog and system freeze.
I can try to make video but it slightly difficult because of system freeze.

**Comment by zetok** [comment]
#3447 was supposed to fix this.

@VoteForNavalny do those lines in log appear after you click on the button?
What DE are you using?

**Comment by Potracheno** [comment]
Yes.
Unity (Installed by default).

**Comment by anthonybilinski** [comment]
Issue it not reproducible on 9cd9da4a5360028bab32bb7f04d95e67e895cc0d. Likely has been fixed since originally reported, closing.
