### ISSUE TITLE
built opencv2.4, now more errors

### ISSUE THREAD

**Issue by dcharles525** [qTox/qTox#389]
symbol lookup error: ./qtox: undefined symbol: z_inflateInit_

**Comment by dcharles525** [comment]
full error if needed

":/conf/settings.ini"
Using embeded bootstrap nodes list
"Loaded translation en"
./qtox: symbol lookup error: ./qtox: undefined symbol: z_inflateInit_

**Comment by dubslow** [comment]
Sounds like a duplicate of https://github.com/tux3/qTox/issues/375

I take it you're still attempting to use the Jenkins binaries?

**Comment by dcharles525** [comment]
@dubslow yes, i just don't understand why it stopped working all the sudden!

**Comment by dubslow** [comment]
Sadly, packaging qTox is proving to be very difficult, mostly because Debian stable is so old it doesn't have qt5...

**Comment by dubslow** [comment]
The opencv dependency was introduced around ~September 1st, if that's what you mean... dependencies haven't changed since then.

**Comment by dcharles525** [comment]
I guess I will just close this and compile it myself, I hope these things can be resolved! qTox is the future! Thanks @dubslow.
