### ISSUE TITLE
qTox couldn't open your chat logs, they will be disabled.

### ISSUE THREAD

**Issue by phd21** [qTox/qTox#3892]
Hi Everyone,

Problem: "qTox couldn't open your chat logs, they will be disabled."

I have been running "qTox" for awhile on Linux Mint KDE 17.3 and it runs well. I have also been testing Linux Mint 18 KDE, and so I installed "qTox in that, then I copied my "tox" folder to that, so I did not have to redo adding friends and re-authenticating them. But, every time I start "qTox", I always get this error. "qTox" runs fine, but I have no chat logs, and I want them.

OS: Linux Mint KDE version 18 (based on Ubuntu 16.04) 32-bit 
qTox version: v1.5.2-obs
Commit hash: f05b7e040a073c7afadaf763dda5beaf130c6dbd
toxcore: 0.0.0
Qt: 5.6.1
Hardware:  Ibm Netvista 
Machine:   System: IBM product: 8305G7U                                                                                                                                               
           Mobo: IBM model: IBM Bios: IBM v: 24KT55AUS date: 05/10/2005                                                                                                               
CPU:       Single core Intel Pentium 4 (-UP-) cache: 512 KB                                                                                                                           
           flags: (pae sse sse2) bmips: 4784 speed: 2392 MHz (max)                                                                                                                    
Graphics:  Card: Advanced Micro Devices [AMD/ATI] RV100 [Radeon 7000 / Radeon VE] bus-ID: 01:00.0
           Display Server: X.Org 1.18.4 drivers: ati,radeon (unloaded: fbdev,vesa) Resolution: 1440x900@59.89hz
           GLX Renderer: Gallium 0.4 on llvmpipe (LLVM 3.8, 128 bits)
           GLX Version: 3.0 Mesa 11.2.0 Direct Rendering: Yes
Audio:     Card-1 Intel 82801DB/DBL/DBM (ICH4/ICH4-L/ICH4-M) AC'97 Audio Controller
           driver: snd_intel8x0 ports: 1c00 18c0 bus-ID: 00:1f.5
           Card-2 Logitech Webcam C270 driver: USB Audio usb-ID: 001-006
…

Reproducible: Always

##### Steps to reproduce

1.  Every time I start "qTox"
2. 
3. …

##### Observed Behavior
same

##### Expected Behavior
For "qTox" to start without this error message, and have access to my chat logs, and to create new chat logs.

##### Additional Info
(links, images, etc go here)
![qtox_startup_error1](https://cloud.githubusercontent.com/assets/6324548/20412185/2c91fb36-acf3-11e6-8dd4-f92a10510012.jpg)

![qtox_startup_error2](https://cloud.githubusercontent.com/assets/6324548/20412186/2c940be2-acf3-11e6-88c8-1df039521c59.jpg)

Zetok: This has the debug messages from running "qTox" from the console terminal prompt. I thought it might have something to do with sqlite, so I made sure everything related to that was installed, re-installed qtox, and I still have the same problem.

[1-qTox_startup_error1.txt](https://github.com/qTox/qTox/files/598702/1-qTox_startup_error1.txt)

Thank you in advance for your help on this everyone.

**Comment by Diadlo** [comment]
Can you reproduse it with new account? Or only on current?
When did the error? Maybe after some OS crash?
Also, can you post here output of `cat ~/.config/tox/phd21.db | hexdump | head` and `du -h ~/.config/tox/phd21.db`?

**Comment by phd21** [comment]
Hi Everyone,

Thanks for the replies...

I think I resolved this issue.  But none of my chat friends are currently available to test it with.

I had read somewhere that you could copy your "tox" configuration folder to your new system, and that should work. But when I did that from Linux Mint 17.3 to Linux Mint 18, that is when I started getting the chat log errors.

Today, I decided to use a common Linux technique to basically reset an application's settings, and I renamed my "tox" configuration folder (/home/user69/.config/**tox**/) to "tox-old" (I could have deleted it as well), then restarted "qTox", and selected import to import my "phd21.tox" profile file, and "qTox" came up without any errors.  I have yet to test it with anyone to see if the chat logs are working, but when I can, I will post the results.

Apparently, copying the entire "tox" configuration folder to a newer operating system is not a good idea, when all you need is your ".tox" profile file.

**Comment by zetok** [comment]
> I have yet to test it with anyone to see if the chat logs are working, but when I can, I will post the results.

You won't have your old chat logs. And btw, when they're available, you can load your old chat logs.

**Comment by phd21** [comment]
Hi zetok, and everyone else,

I just tested "qTox" and all is working well again, including the chat logs.  :)

Zetok: Could you elaborate on your last comment. I know I don't have my old chat logs. What do you mean by "And btw, when they're available, you can load your old chat logs"? What file(s) are they stored in the ".db" file? Or, are you referring to some new update and or feature for handling chat logs?

Thanks ...
Phil

**Comment by zetok** [comment]
It's not a new feature:
![spectacle lx8235](https://cloud.githubusercontent.com/assets/3148759/20445978/4e650348-adcf-11e6-9ad4-f63a292394a4.png)

**Comment by sudden6** [comment]
@zetok haha, not even I knew about this, care to add it to the user manual?

**Comment by zetok** [comment]
@sudden6 yeah, I've been meaning to somehow describe functionality of chatform for both variants (single contact, and groupchat), but I'm not quite sure how to get started with that thing :s

**Comment by Potracheno** [comment]
Same here and same conditions but Ubuntu 16.04 tried with qTox 1.7.0 release and  04c280f702bf7287d99bf951e1ddef20dfe0672a

**Comment by weakish** [comment]
After migrating tox configuration file to a new system,
I encountered the same problem.
I guess this is caused by database schema changing.

Removing `username.db` and `username.db.bak` fix this problem.
Note: this workaround will **discard all previous chat logs**.

If you want to preserve old chat logs,
you need to move the database somewhere else,
and later import the records to the newly created chat log database manually via `sqlite`

**Comment by sudden6** [comment]
@weakish it should upgrade the database if you don't jump over the intermediate versions.

**Comment by weakish** [comment]
@sudden6 I did jumped intermediate versions.

If qTox does not want to bloat its code base to include migration code for all previous versions,
maybe a separated helper tool can be made to support migration from arbitrary previous versions?

**Comment by jl44** [comment]
Profile > Clear Profile Password
Restart
Profile > Set Profile Password
Restart
=> Warning: chat logs disabled

**Comment by jl44** [comment]
Sorry for above. Turned out to be not a qtox related issue, but a debian stretch sqlcipher issue.
It core dumps when converting (encoding/decoding)  the db. I didn't realize this, since I expected that qtox just terminated after the conversion.

Debian stretch:


```
user@debian:~/builds/qtox/test$ ll
total 8
drwxr-xr-x 2 user user 4096 Oct  6 22:24 .
drwxr-xr-x 5 user user 4096 Oct  6 22:27 ..
user@debian:~/builds/qtox/test$ sqlcipher nn.db
SQLCipher version 3.8.6 2014-08-15 11:46:33
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> create table test (xx int);
sqlite> .dump
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE test (xx int);
COMMIT;
sqlite> ATTACH DATABASE 'enc.db' AS enc KEY 'pwd';
sqlite> SELECT sqlcipher_export('enc');
**Segmentation fault**
```

Debian buster:

```
user@debian:~/builds/qtox/test$ sqlcipher nn.db
SQLCipher version 3.15.2 2016-11-28 19:13:37
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> create table test (xx int);
sqlite> .dump
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE test (xx int);
COMMIT;
sqlite> ATTACH DATABASE 'enc.db' AS enc KEY 'pwd';
sqlite> SELECT sqlcipher_export('enc');

sqlite> DETACH DATABASE enc;
sqlite> .exit
user@debian:~/builds/qtox/test$ sqlcipher enc.db
SQLCipher version 3.15.2 2016-11-28 19:13:37
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> PRAGMA key = 'pwd';
sqlite> .dump
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE test (xx int);
COMMIT;
sqlite> .exit
```

**Comment by sudden6** [comment]
@jl44 your issue is handled in https://github.com/qTox/qTox/issues/4054

**Comment by sudden6** [comment]
Closing as all issues seem to be resolved.
