### ISSUE TITLE
Link to contributors doesn't show all qTox contributors

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#3898]
##### Brief Description
Even though description of the link in qTox claims to show all contributors, only 100 contributors with most commits are shown, due to link pointing to a github page.

qTox version: v1.6.0  

Reproducible: Always

##### Steps to reproduce
1. Settings → About → click on the `contributors` link

##### Observed Behavior
Only top 100 contributors are shown

##### Expected Behavior
All contributors should be shown

##### Additional Info
![spectacle kn1572](https://cloud.githubusercontent.com/assets/3148759/20462400/06dd59b6-af15-11e6-85bf-e3d33c32bf0c.png)

There seem to be 3 ways of dealing with that:

* make a list of contributors in `AUTHORS.txt/md` like Linux kernel does
* change the text in qTox to say `top 100 contributors`
* remove the text from qTox

**Comment by sudden6** [comment]
I would prefer changing the text to the "top 100 contributors". Removing the text from qTox would be disrespectful to everybody who contributed IMO. Making a list of authors, would probably be the most portable solution, but is also the most resource consuming one I think. Because the list has to be updated for at least every release. But maybe this could be automated with the GH api.

**Comment by zetok** [comment]
> But maybe this could be automated with the GH api.

Why would you depend on gh api when you don't need to?

Also, list can't be 100% automated, given that automation wouldn't give all contributors.

**Comment by zetok** [comment]
> Also, list can't be 100% automated, given that automation wouldn't give all contributors.

No, wait, scratch that, it could be automated, just not the first version of it.

**Comment by sudden6** [comment]
@zetok also the first version could be automated, see https://developer.github.com/v3/repos/statistics/

**Comment by zetok** [comment]
@sudden6 nope, regardless of what the docs claim.
