### ISSUE TITLE
Getting closer! qTox fails to compile!

### ISSUE THREAD

**Issue by dcharles525** [qTox/qTox#390]
In file included from ./ui_mainwindow.h:28:0,
                 from widget/form/addfriendform.cpp:22:
./widget/adjustingscrollarea.h:28:46: error: expected ‘;’ at end of member declaration
./widget/adjustingscrollarea.h:28:48: error: ‘override’ does not name a type
./widget/adjustingscrollarea.h:29:30: error: expected ‘;’ at end of member declaration
./widget/adjustingscrollarea.h:29:36: error: ‘override’ does not name a type
widget/form/addfriendform.cpp: In constructor ‘AddFriendForm::AddFriendForm()’:
widget/form/addfriendform.cpp:40:13: error: ‘class QTextEdit’ has no member named ‘setPlaceholderText’
widget/form/addfriendform.cpp: In member function ‘bool AddFriendForm::isToxId(const QString&) const’:
widget/form/addfriendform.cpp:72:39: error: variable ‘const QRegularExpression hexRegExp’ has initializer but incomplete type
widget/form/addfriendform.cpp: In member function ‘QString AddFriendForm::getMessage() const’:
widget/form/addfriendform.cpp:88:43: error: ‘const class QTextEdit’ has no member named ‘placeholderText’
widget/form/addfriendform.cpp:89:1: warning: control reaches end of non-void function [-Wreturn-type]
widget/form/addfriendform.cpp: In member function ‘bool AddFriendForm::isToxId(const QString&) const’:
widget/form/addfriendform.cpp:74:1: warning: control reaches end of non-void function [-Wreturn-type]
make: **\* [addfriendform.o] Error 1

**Comment by dubslow** [comment]
Huh, this is strange. What distro?

At a glance, that looks like you have the wrong Qt version. You need 5.2+. `qmake --version` will tell you what version of Qt is in use.

http://qt-project.org/doc/qt-5/qtextedit.html#placeholderText-prop

> This property was introduced in Qt 5.2.

**Comment by dcharles525** [comment]
QMake version 3.0
Using Qt version 5.0.2 in /usr/lib/x86_64-linux-gnu

I do have 5.3 installed though (sorry for being so noob) but it doesn't seem to be registering that.

Oh and eOS

**Comment by dubslow** [comment]
Hmm, some how you need to override 5.0.2 with 5.3.

`ls -l $(which qmake)`, and viewing the help on the linked-to file, suggests that 

`export QT_SELECT=5.3 qmake` should do the job, at least once... I dunno about making 5.3 the default. Google?

**Comment by dcharles525** [comment]
Eh, I keep getting errors no matter what I do, I will just wait until the packages are fixed! Thanks!

**Comment by NicoHood** [comment]
I also have the problem on ubuntu 14.04

**Comment by tux3** [comment]
@NicoHood Ubuntu 14.04 is probably too old to compile qTox unless you manually install up to date dependencies, make sure you have everything at a recent enough version.

**Comment by zetok** [comment]
> Ubuntu 14.04 is probably too old to compile qTox

Huh, that made me realize that even though Qt version was bumped in INSTALL.md, there are still bits and pieces that are about compiling on 14.04, even though Qt version that it supplies is too old to compile qTox.

I'm going to make a PR removing parts of INSTALL.md that are about 14.04.
