### ISSUE TITLE
Fails to open audio output "OSS Default", and pcm2:play:dsp2

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3904]
qTox fails to open the OSS Default device. The system trace log is like this:
```
[17:16:52.159 UTC] src/audio/audio.cpp:386 : Debug: Opening audio output "OSS Default"
 4626: write(2,"[17:16:52.159 UTC] src/audio/aud"...,87) = 87 (0x57)
 4626: write(18,"[17:16:52.159 UTC] src/audio/aud"...,87) = 87 (0x57)
[17:16:52.159 UTC] src/audio/audio.cpp:396 : Warning: Cannot open output audio device "OSS Default"
```

This means qtox didn't even try to open the device and printed this message.

It also fails to open pcm2:play:dsp2:
```
[17:25:52.101 UTC] src/audio/audio.cpp:386 : Debug: Opening audio output "pcm2:play:dsp2"
[17:25:52.101 UTC] src/audio/audio.cpp:396 : Warning: Cannot open output audio device "pcm2:play:dsp2"
[17:25:52.101 UTC] src/audio/audio.cpp:345 : Debug: Opening audio input "OSS Default"
```

qTox-1.5.2
FreeBSD 11

**Comment by zetok** [comment]
Does your OpenAL support your OSS?

**Comment by yurivict** [comment]
It did work when I updated to qTox-1.5.2, and also few days ago. Now I am trying to figure out what changed. It depends on something.

**Comment by yurivict** [comment]
But I also got the user report that audio in qTox doesn't work: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=214393

**Comment by yurivict** [comment]
Now I know what happened with me: openal-soft only works with pulseaudio on my system. PULSEAUDIO turned to "off" by the system upgrade, because "off" is a default, and it broke it for me.

So I suspect openal is broken either on FreeBSD in general, or with my card/some cards in particular.

**Comment by yurivict** [comment]
I think this is in the FreeBSD OpenAL port, closing.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=214710

**Comment by yurivict** [comment]
It turned out that there is a memory corruption due to the use of the temporary object. Please apply the following patch:
```
--- src/audio/audio.cpp.orig    2016-12-02 04:06:35 UTC
+++ src/audio/audio.cpp
@@ -352,10 +352,10 @@ bool Audio::initInput(const QString& dev
     const uint32_t chnls = AUDIO_CHANNELS;
     const ALCsizei bufSize = (frameDuration * sampleRate * 4) / 1000 * chnls;
 
-    const ALchar* tmpDevName = deviceName.isEmpty()
-                               ? nullptr
-                               : deviceName.toUtf8().constData();
-    alInDev = alcCaptureOpenDevice(tmpDevName, sampleRate, stereoFlag, bufSize);
+    alInDev = alcCaptureOpenDevice(deviceName.isEmpty()
+                                   ? nullptr
+                                   : deviceName.toUtf8().constData(),
+                                   sampleRate, stereoFlag, bufSize);
  
     // Restart the capture if necessary
     if (!alInDev)
@@ -386,11 +386,9 @@ bool Audio::initOutput(const QString& de
     qDebug() << "Opening audio output" << deviceName;
     assert(!alOutDev);
 
-    const ALchar* tmpDevName = deviceName.isEmpty()
-                               ? nullptr
-                               : deviceName.toUtf8().constData();
-    alOutDev = alcOpenDevice(tmpDevName);
-
+    alOutDev = alcOpenDevice(deviceName.isEmpty()
+                             ? nullptr
+                             : deviceName.toUtf8().constData());
     if (!alOutDev)
     {
         qWarning() << "Cannot open output audio device" << deviceName;
```

I verified, this fixes the problem.

**Comment by sudden6** [comment]
IIRC this temporary object was introduced to fix a memory leak, but I'm not 100% sure. @antis81 can you remember?

**Comment by antis81** [comment]
@sudden6 This is so simple. Looks like someone removed the fix. Both lines in the patch are simply wrong!

`QString::toUtf8()` returns a constructed (temporary) QByteArray. Now if we store the pointer, it will segfault:

```c++
QString s = QStringLiteral("This is the text.");

// This shows the mistake, that easily happens while coding carelessly…
const char* invalidPtr = s.toUtf8().constData();
// invalidPtr is now dangling
printf("I want to output the text: %s", inavlidPtr); // <--- segfault!


// Here's how to do it right:
QByteArray tmp = s.toUtf8();

// now we can safely use the const pointer to the array
someMethod(tmp.isEmpty() ? nullptr : tmp.constData());
someOtherMethod(tmp.isEmpty() ? nullptr : tmp.constData());
```

All clear? ^^

**Comment by sudden6** [comment]
@antis81 I think I got it, but why does the patch above then "fix" the problem?

I'll prepare a PR with the fix and will assign it to you.

EDIT: Seems like it's already fixed on master https://github.com/qTox/qTox/blob/master/src/audio/audio.cpp#L369

@yurivict please update to the latest release, it should be fixed there. I'll close this issue then, please comment if you want it reopened.

EDIT2: After IRC discussion I'll leave this open until @yurivict verifies that the problem is fixed on the latest release.

**Comment by yurivict** [comment]
It's fixed in the latest release 1.6.0.

Thanks!

**Comment by GitAClue** [comment]
yurivict's patch was the correct solution. There is no need for any temporary variable, much less TWO!

The problem is the temporary QByteArray goes away after the assignment to that tmpDevName. If the entire construct is within the function call, as in yurivict's solution, then the temporary QByteArray exists for the duration of the function call, the exact time period during which the pointer must be valid.

This slop should be replaced by the simple solution lest it be broken again.

**Comment by yurivict** [comment]
In the latest version QByteArray objects are temporary, so it works now. I also think temporary objects aren't needed at all. Maybe some style considerations dictate such objects?
