### ISSUE TITLE
Would it be possible to get a status light in the ui->head area?

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#391]
Cause a new guy from #tox was chatting with me, and he changed client a couple of times and I didn't notice he was off because I didn't look at the friend's list to notice he wasn't at the top...

**Comment by agilob** [comment]
I wanted to display call duration in headArea and place status changes could as messages in chat. What do you think about it? That how it works in Gajim and Pidgin (afair). That solution would require additional setting "Show status changes as messages".

**Comment by dubslow** [comment]
Hmm, for now you could just leave it on by default (use the SystemAction class should make it easy). The option would be nice I guess.

**Comment by agilob** [comment]
Yup, I'll use SystemAction.

Will be soon.
