### ISSUE TITLE
Wrong translation selected in connection menu

### ISSUE THREAD

**Issue by n0lz** [qTox/qTox#3919]
##### Brief Description

OS: Windows 10 x64  
qTox version: 1.6.0  
Commit hash: 5648106b34fc7dc3ad4e169651a0cbbd0139170a
toxcore: 0.0.0
Qt: 5.5.1

Reproducible: Always

##### Steps to reproduce

1. open qTox
2. go to settings
3. switch language to german
4. go to advanced

##### Observed Behavior
Default selection of "Kein Videogerät ausgewählt" in "Proxy-Typ" drop-down

##### Expected Behavior
No entry "Kein Videogerät ausgewählt" in drop-down "Proxy-Typ"

##### Additional Info

![qtox translation bug](https://cloud.githubusercontent.com/assets/12564049/20622130/abfd7828-b301-11e6-960d-2d61cf60d8be.jpg)

----

**Comment by zetok** [comment]
Would you mind correcting `None` to the right translation?

**Comment by n0lz** [comment]
Corrected this one an the same issue under 'Theme' -> 'Style'

**Comment by zetok** [comment]
Should be fixed in #3923, thus closing.
