### ISSUE TITLE
qTox Win10 freezes on Invite

### ISSUE THREAD

**Issue by SebastianBrings** [qTox/qTox#3920]
##### Brief Description

OS: Windows 10 anniversary edition with all automatic updates
qTox version: v1.5.2-8-gfd04a28.
Commit hash:  Commit hash: fd04a2832aa885d260ded4e476eefcddd49237b3
toxcore:  oxcore version: 0.0.0
Qt:  5.5.1
Hardware:  Intel NUC Celeron
…

Reproducible: Happened once, now the messenger is unusable
##### Steps to reproduce

1. Got invitation by some stranger who contacted me in a chatroom and told he added me (my hash is visible in my profile, so that seemed ok)
2.  qTox was running, not showing the invitation but "(Not Responding") in title bar.
3. forcefully stopping and restarting qTox lead to about 20 seconds runtime, then freezing again
4 all further restarts give same result, qTox is working shortly, then freezing

Freezing: Mouse pointer turns into rotating circle when in application focus. Window title bar shows "(Not Responding)", clicking the "X" top right to close window gives options menue "not responding, close program or wait for response"

**Comment by zetok** [comment]
Could you provide [log](https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports)?
Also, could you manually install newest qTox version to see whether it still happens on it? There's a problem with automatic updates.

**Comment by SebastianBrings** [comment]
Hi,
it meanwhile seems it was not qTox related as also Skype froze in a similar way, I only noticed that later. As network connectivity was functional all the time, it could be rleated to A/V peripherals. I will keep an eye on this, in the meantime feel free to close this.
