### ISSUE TITLE
qTox creates in portable mode empty directory "tox" in %APPDATA%

### ISSUE THREAD

**Issue by DX37** [qTox/qTox#3929]
Some security issue, I guess.

OS: Windows 10.
qTox Build: v1.6.0-56 917812d.

Like I said in [this post](https://github.com/qTox/qTox/issues/3768#issuecomment-264444829) (#3768):

> But it creates %APPDATA%/tox directory, which remains empty.

**Comment by vatterspun** [comment]
According to Portablefreeware: 

>Windows 8: Empty folder written to \AppData\Roaming\tox
>Windows 7: Duplicate user files saved to \AppData\Roaming\tox

https://www.portablefreeware.com/index.php?id=2755

Related: #5354

**Comment by ghost** [comment]
same here.
v1.6.0-78-ge9778e8

**Comment by sergeevabc** [comment]
Minor issue, but troublesome.
Half a year passed since initial report, could we have it fixed at last, please?

**Comment by emkei-cz** [comment]
The current version of the same problem!
I don't understand why it is not possible to download the portable ".zip" version of the program...
