### ISSUE TITLE
Installing newer qTox is crashing my Linux Mint 17.3 KDE desktop!

### ISSUE THREAD

**Issue by phd21** [qTox/qTox#3932]
Hi Everyone at "qTox",

I have something strange to report.

Installing newer qTox is crashing my Linux Mint 17.3 KDE desktop! 

Works fine on my Linux Mint 18 KDE on my testing partition ???

See screenshots.

OS: Linux Mint 17.3 KDE based on Ubuntu 14.04 Trusty
qTox version: Not sure, I think from 1.5.2 - 1.6.x
Commit hash:  
toxcore:  
Qt:  
Hardware: 
Machine:   System: IBM product: 8305G7U
           Mobo: IBM model: IBM Bios: IBM v: 24KT55AUS date: 05/10/2005
CPU:       Single core Intel Pentium 4 (-UP-) cache: 512 KB
           flags: (pae sse sse2) bmips: 4784 speed: 2392 MHz (max)
Graphics:  Card: Advanced Micro Devices [AMD/ATI] RV100 [Radeon 7000 / Radeon VE] bus-ID: 01:00.0
           Display Server: X.Org 1.18.4 drivers: ati,radeon (unloaded: fbdev,vesa)
           Resolution: 1440x900@59.89hz
           GLX Renderer: Gallium 0.4 on llvmpipe (LLVM 3.8, 128 bits)
           GLX Version: 3.0 Mesa 11.2.0 Direct Rendering: Yes

Reproducible: Always

Steps to reproduce

1.  Download ".deb" from 
http://download.opensuse.org/repositories/home:/antonbatenev:/tox/xUbuntu_14.04/i386/qtox_201611180121~v1.6.0_i386.deb
2.  Run the installer, it shows "Requires installation of 48 additional packages"?
3. If I install it, it will crash my graphical desktop. See screenshots. It wants to remove everything that is "xserver" and "xorg" ???

##### Observed Behavior
I have never had a problem with installing "qTox" before, in either Linux Mint 17.x or Linux Mint 18. I could not figure out what happened to my system, because I am always installing and trying out various software for Linux Mint forum members and myself, it took awhile to figure out what was happening. I narrowed it down to "qTox", and I think from version 1.5.2 thru current version 1.6.x

##### Expected Behavior
Not to trash my system.

##### Additional Info

![qtox_deb_install_problem3](https://cloud.githubusercontent.com/assets/6324548/20844822/bd06bb6e-b88f-11e6-9da0-45f7ef63e11e.jpg)

![qtox_deb_install_problem4](https://cloud.githubusercontent.com/assets/6324548/20844823/bd06d31a-b88f-11e6-9df0-d7284378b905.jpg)

**Comment by zetok** [comment]
cc @abbat ?

**Comment by abbat** [comment]
Linux Mint 17.3 uses Ubuntu Vivid’s Xorg/MESA stack. Probably you have to downgrade (or upgrade) *-vivid packages to default (without *-vivid) versions.

**Comment by zetok** [comment]
@phd21 since looks like an issue with what Mint is doing (making a frankenbuntu or some other kind of an abomnation), there's not much (nothing?) that can be done about that.

In other words, your distro seems to be intentionally breaking things just because they cannot figure out how to recompile a few packages. Or figure out that mixing packages from different releases is not a good idea.

Since it works for you on Mint 18, that's what you probably should use (if you really can't switch away from Mint).
