### ISSUE TITLE
No paste with middle mouse button from selection in the message history

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3933]
When some text in the message history is selected, it doesn't get into the primary clipboard (XA_PRIMARY) and doesn't get pasted on middle click as it is supposed to.

1.6.0 on FreeBSD 11.

**Comment by Talkless** [comment]
Works fine for me on FreeBSD 12 TrueOS, Debian 9 and on Kubuntu 16.04.

Could you try again? Maybe that's Qt issue with desktop environment your are using?

**Comment by zetok** [comment]
Also works for me on Gentoo.

 @yurivict can you see if it's still reproducible?

**Comment by yurivict** [comment]
It works for me now with the current code.
