### ISSUE TITLE
after system upgrade qtox is removed from package manager

### ISSUE THREAD

**Issue by bitchecker** [qTox/qTox#3934]
I've upgraded my system from Fedora 24 to Fedora 25 and qTox was removed from DNF package manager.

if i try to re-install it, i see this error message:

```
# dnf install qtox.x86_64
Error: nothing provides libvpx.so.3()(64bit) needed by qtox-201611180121~v1.6.0-6.2.x86_64
```

**Comment by zetok** [comment]
Do you have added repo for the F25?

**Comment by bitchecker** [comment]
system upgrade tool provides to update repositories...but not for qtox.

package installed after manual repo-file mod.
