### ISSUE TITLE
"  p, li { white-space: pre-wrap; }" gets copied along with message from the messagebox

### ISSUE THREAD

**Issue by nicolasmaia** [qTox/qTox#3939]
##### Brief Description

OS: GNU/Linux (Parabola [an Arch variant])  
qTox version: v1.6.0
Commit hash: 5648106b34fc7dc3ad4e169651a0cbbd0139170a
toxcore: 0.0.0
Qt: 5.7.0
Hardware:  https://h-node.org/notebooks/view/en/1640/Samsung-ATIV-Book-2-NP270E4E-KD2BR

Reproducible: Yes

##### Steps to reproduce

1. Type something in the message box, but don't send.
2. Copy that message and paste somewhere else (in my case I pasted on Pidgin)

##### Observed Behavior
"      p, li { white-space: pre-wrap; }" appears prepended to the text.

**Comment by zetok** [comment]
Can't reproduce when copying to leafpad.

Can you supply a text sample?
Does pasting somewhere else change anything?

**Comment by nicolasmaia** [comment]
I just tried pasting to other places. Interestingly, this only seems to happen when I paste to a Pidgin conversation. Perhaps it's a bug on their end?

**Comment by zetok** [comment]
>I just tried pasting to other places. Interestingly, this only seems to happen when I paste to a Pidgin conversation. Perhaps it's a bug on their end?

Possibly.

**Comment by Diadlo** [comment]
Seems not qTox issue. Thus closing

**Comment by ghost** [comment]
See https://issues.imfreedom.org/issue/PIDGIN-16746 for the Pidgin issue (including a workaround).
