### ISSUE TITLE
Switching video device from None to a valid choice doesn't immediately show the video

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3943]
On the Audio/Video page switching {None}->{Valid choice} doesn't immediately show the video. The video appears only when I switch to some other tab and back. This isn't right, can confuse users.

1.6.0 on FreeBSD 11

**Comment by zetok** [comment]
Can't reproduce on feaedeed841f419a8eb5b7f40a14e27ef1e104cb on Gentoo Linux amd64

**Comment by zetok** [comment]
Logs?

**Comment by anoadragon453** [comment]
Cannot reproduce on latest master, suggest closing.
