### ISSUE TITLE
Autologin it's not works ?

### ISSUE THREAD

**Issue by DjDiabolik** [qTox/qTox#3945]
##### Brief Description

OS: Windows 10 Home
qTox version: 1.6.0

Reproducible: Always 

##### Steps to reproduce

1. Autologin it's not appears... i need every time to put my password...

How i can use the autologin ? On qtox.ini i have put:
[Login]
autoLogin=true

But apparently there's no working.......

**Comment by zetok** [comment]
https://github.com/qTox/qTox/wiki/FAQ#can-a-profile-be-automatically-loaded-if-its-password-protected

**Comment by DjDiabolik** [comment]
Oh ok..... and if i have a "old" profile created whit utox how i can use on qtox ?

**Comment by zetok** [comment]
You can import it. If it's already in `~/.config/tox` qTox should autodetect it.

**Comment by zetok** [comment]
https://github.com/qTox/qTox/wiki/Profile actually, for windows there's a different dir
