### ISSUE TITLE
cross compiling for windows!

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3963]
##### How to Cross compile for windows ?

the current instruction for building on windows is broken.

I've tried this fork https://github.com/Talkless/qTox/tree/windows-bootstrap compiles but final qtox.exe crash with sig. fault ( i think caused by `Warning: resolving _getaddrinfo by linking to _getaddrinfo@16` )

so how to build using a linux box, i tried to follow jenkins console log but failed.

Help ?

**Comment by optimumtact** [comment]
Here's the configured settings for the qtox windows x64 build on the tox jenkins
```
mkdir -p prefix
cd "$WORKSPACE/libs"
for l in *.zip ; do
    unzip -o $l
    rm $l
done
cd bin
cp OpenAL32.dll ssleay32.dll libeay32.dll Qt5Core.dll Qt5Gui.dll \
   Qt5Network.dll Qt5Sql.dll Qt5Svg.dll Qt5Widgets.dll Qt5Xml.dll "$WORKSPACE"/prefix
cd "$WORKSPACE"
cp -r libs/plugins/imageformats libs/plugins/platforms libs/plugins/sqldrivers \
      libs/plugins/iconengines "$WORKSPACE"/prefix
cp /usr/lib/gcc/x86_64-w64-mingw32/4.9-posix/libgcc_s_seh-1.dll $WORKSPACE/prefix
cp /usr/lib/gcc/x86_64-w64-mingw32/4.9-posix/libstdc++-6.dll $WORKSPACE/prefix
cp /usr/x86_64-w64-mingw32/lib/libwinpthread-1.dll $WORKSPACE/prefix
./qtox-build-script_src.sh
cd $WORKSPACE
cp qtox/version .
```

The build script is sourced from another job and can be viewed here:https://build.tox.chat/view/qtox/job/qtox-build-script_src/lastSuccessfulBuild/artifact/qtox-build-script_src.sh/*view*/

It's responsible for doing a lot of the configuration of the build system for the crosscompilation depending on the job it's being called in

Note that this doesn't include configs for the other lib builds, such as qt and the audio/video/tox libraries, although I can pull them on request and unfortunately all the instructions may not apply outside of jenkins.

I have no actual experience with building qtox for windows, other than being tangentially involved as the jenkins build admin.

@nurupo may be able to assist more as he developed a lot of the jenkins config for the crossbuilding of qtox

**Comment by AliceGrey** [comment]
@nurupo @zetok @tux3 Any update on this? I think being able to cross-compile is an important issue to fix. Especially considering there are quite a few issues relating to windows open right now. It would be really helpful to be able to cross-compile so we could work on the windows bugs easily.

**Comment by Diadlo** [comment]
@AliceGrey AFAIK qtox already cross compiled in [jenkins](https://build.tox.chat/view/qtox/job/qTox-cmake_build_windows_x86-64_release/) with cmake
cc @sudden6

**Comment by AliceGrey** [comment]
@Diadlo It does cross compile in jenkins but individual contributors can't current;y cross-compile on their own linux PC.

**Comment by optimumtact** [comment]
I don't know if anyone even knows how at this point

**Comment by nurupo** [comment]
You can cross-compile it on your system, it's just a bit non-trivial as you have to cross-compile every qTox dependency and dependencies of those dependencies: Qt, sqlcipher, openssl, vpx, opus, sodium, toxcore, ffmpeg, qrencode, etc.

**Comment by Diadlo** [comment]
Also it's [problem](https://github.com/sqlcipher/sqlcipher/issues/176) to cross compile sqlcipher

**Comment by AliceGrey** [comment]
@nurupo Could you update the instructions in the docs if you're able to get it working? Also would it be possible to update the cmake build scripts to cross compile?

**Comment by nurupo** [comment]
Don't think I alone would be able to cross-compile it, I only know how to cross-compile qTox dependencies, not qTox itself. Maybe if @sudden6 helps, he is improving the cross-compilation of qTox given the dependencies. I could provide a bash script for cross-compiling qTox dependencies for 32-bit or 64-bit qTox on Ubuntu 16.04 LTS (you could presumably run it in docker if your distro is not Ubuntu 16.04, or just adjust a few commands to work on your distro).
