### ISSUE TITLE
crash on macOS Sierra 10.12.2

### ISSUE THREAD

**Issue by Ivan97** [qTox/qTox#3966]
##### Brief Description

OS: version OS X
qTox version:1.5.1
toxcore:  
Qt:  
Hardware:  Macbook pro late 2016

Reproducible: Always
##### Steps to reproduce

just cannot run the application.

here is the log.

[qtox_crash.txt](https://github.com/qTox/qTox/files/651745/qtox_crash.txt)

**Comment by sudden6** [comment]
Seems like ffmpeg is not properly installed. Idk, is it supposed to be in the image?

**Comment by zetok** [comment]
Duplicate of #3610, thus closing.
