### ISSUE TITLE
Video call buttons remain red after end of call

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#3969]
##### Brief Description
If video call ends while chatform is not visible, buttons remain red instead of returning to green.

OS: Gentoo Linux amd64
qTox version: v1.6.0-76-g5455680
Commit hash: 54556803d1918f86e7422d32358d8bb2c919fe56
toxcore: 0.0.0
Qt: 5.6.2

Reproducible: Always

##### Steps to reproduce

1. Start video call
2. Go to settings
3. Video call ends

##### Observed Behavior
Call buttons remain red.

##### Expected Behavior
Buttons should switch back to green.

##### Additional Info
![spectacle juo589](https://cloud.githubusercontent.com/assets/3148759/21236889/a0903f72-c2f4-11e6-887b-2e8e617ba372.png)

**Comment by Diadlo** [comment]
Can't reproduse on 9c3256386d0b28b5f9a24b2a3979f7326722970a

**Comment by zetok** [comment]
@Diadlo right, the instructions weren't very correct, sorry about that.

Improved ones:

1. Start video call
2. Go to settings
3. The other side ends video abnormally, e.g. due to `^C` in gdb
4. Wait in settings until peer is shown as offline
5. Open friend's chatform page, buttons are red.

Perhaps it matters that the open settings page was `Audio/Video`

**Comment by sudden6** [comment]
Is this still an issue? If not please close.

**Comment by zetok** [comment]
I can't test right now because of #4385.

**Comment by Diadlo** [comment]
@zetok #4385 Fixed. Can you retest?

**Comment by zetok** [comment]
Yep, seems to be fixed.
