### ISSUE TITLE
Switch to c-toxcore

### ISSUE THREAD

**Issue by NicoHood** [qTox/qTox#3980]
Hi,
will this project switch to c-toxcore as it is the new upstream toxcore source now? Every other tox client switches to c-toxcore over time now and it would be essential for you to do so too if people want to use tuntox in their linux distribution.

**Comment by sudden6** [comment]
It's nearly done, see https://github.com/qTox/qTox/pull/3736 for more info.

**Comment by zetok** [comment]
#3736 with migration to TokTok has been merged, thus closing.

**Comment by NicoHood** [comment]
Thanks for the information. It would be nice if you can tag a new version if possible, so we can rebuild all tox clients with the new toxcore. Please also sign the release. Thanks a lot again :)

**Comment by sudden6** [comment]
@NicoHood The next release is planned for 2016-12-25, I also sent out an email to https://lists.tox.chat/pipermail/qtox-dev/ prewarning packagers for the change.

**Comment by NicoHood** [comment]
@sudden6 Thanks. Could you please sign the release? #3912
