### ISSUE TITLE
SSH Control over TOX

### ISSUE THREAD

**Issue by dcapeletti** [qTox/qTox#3990]
Hello,
Many times I have the need to open a ssh session with the PC of a friend who does not know how to configure a NAT on your router or even know your public IP. Is it possible to use TOX to make a client server program for ssh control?

**Comment by dcapeletti** [comment]
I know it is not the right place, but if it is a feasible proposal, it would be interesting to share it in case someone wants to implement it.

**Comment by sudden6** [comment]
You may want to take a look at https://github.com/gjedeer/tuntox

qTox will probably never implement this.

**Comment by Diadlo** [comment]
I think, sudden6 answered on your question. Thus I am closing it. 
Also, you can contat with us in [freenode#qtox](https://webchat.freenode.net/?channels=qtox)

**Comment by dcapeletti** [comment]
Thanks
