### ISSUE TITLE
[feature suggestion] Have a F11 shortcut to make qTox full screen

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3991]
The full screen feature allows the user to focus on the app better when he is involved in a conversation. All major browsers do this. There is also a line of thinking that users use computer to use apps, not to see the desktop, so individual apps should be able to occupy desktop 100%.

**Comment by zetok** [comment]
Note: fullscreen is already possible when one uses proper window manager.

**Comment by sudden6** [comment]
IMO at least for Linux, it's not qTox's responsibility to remove the window borders. Most windowmanagers already have global shortcuts for this.

**Comment by yurivict** [comment]
Same can be said for browsers. Some popular all WMs don't support this feature.

**Comment by yurivict** [comment]
Closed via PR: https://github.com/qTox/qTox/pull/4141
