### ISSUE TITLE
Can't build latest qTox from git

### ISSUE THREAD

**Issue by DX37** [qTox/qTox#3993]
For this moment qTox can't be built, because of this error: http://pastebin.com/43m6rw79.
And last 4 Windows nightly builds can't be built. Almost same error happens on your build server.

**Comment by zetok** [comment]
cc @Encrypt @tux3

**Comment by DX37** [comment]
@zetok wait wait wait, this error is on Linux too. I just forgot to say it...

**Comment by nurupo** [comment]
@DX37 do you use https://github.com/TokTok/c-toxcore?

**Comment by nurupo** [comment]
The Windows builds fail because they use https://github.com/irungentoo/toxcore. irungentoo toxcore uses TOX_PASS_KEY for the struct name, while TokTok uses Tox_Pass_Key, which are different names in C.

**Comment by DX37** [comment]
> do you use https://github.com/TokTok/c-toxcore?

I building qTox on Linux from AUR (ArchLinux User Repository). Maybe it's PKGBUILD need to be updated now, if you are using TokTok c-toxcore now. And switch to it for Windows builds, of course.

I think I should mail to contributors to replace 'toxcore' dependency to 'toxcore-toktok-git' or 'c-toxcore'. Or to clone 'c-toxcore' repo in qtox-git PKGBUILD.

**Comment by DX37** [comment]
Oh... Right. There is 'c-toxcore' package in official Arch repos.

**Comment by DX37** [comment]
Just one question - why did you switch to 'c-toxcore' ?

**Comment by zetok** [comment]
>Just one question - why did you switch to 'c-toxcore' ?

Why wouldn't we?

**Comment by DX37** [comment]
> Why wouldn't we?

I'm not against. I'm just curious 😄

**Comment by nurupo** [comment]
@DX37 
- [... Toxcore fork ...](https://blog.tox.chat/2016/08/update-new-client-xenial-packages-tox-in-google-play-toxcore-fork-and-more/)
- [First Stable Release of TokTok Toxcore](https://blog.tox.chat/2016/12/first-stable-release-of-toktok-toxcore/)

**Comment by DX37** [comment]
Ah, now I understand. Thanks, @nurupo.

**Comment by DX37** [comment]
Ok, I'm fine with building qTox on Linux. But nightlies from build.tox.chat still can't be built because of linking error. You know that? @zetok

**Comment by zetok** [comment]
Yeah.

**Comment by nurupo** [comment]
I notified @tux3, but you know, holidays happened, so it might take some time before he gets to look into it.

**Comment by nurupo** [comment]
I tried to fix it myself, but couldn't really figure out what was the issue.

**Comment by DX37** [comment]
Ok, windows nightlies starting now. Thanks to @tux3.
But I met new bug - my avatar and contacts are gone. And, I think, I can't add new contacts.
Logs don't say anything.

**Comment by zetok** [comment]
>But I met new bug - my avatar and contacts are gone. And, I think, I can't add new contacts.
Logs don't say anything.

That's a separate issue (a new one should be opened), closing this one.
