### ISSUE TITLE
Issues in crypto implementation

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3995]
Google released a project that can test crypto library implementations against known attacks. This should be interesting to use on tox and clients like qTox.

https://github.com/google/wycheproof

**Comment by zetok** [comment]
Doesn't seem to be applicable?

**Comment by sudden6** [comment]
qTox isn't a crypto library and doesn't implement any cryptographic functions itself, this is eventually applicable to the crypto library toxcore uses, which is libsodium.

**Comment by yurivict** [comment]
wycheproof seems to be Java only. It applies to Java implementations of their common cryptographic interface which is a standard there. It doesn't seem to apply to Tox at all.
