### ISSUE TITLE
helt QT GUI

### ISSUE THREAD

**Issue by fcore117** [qTox/qTox#4]
Instead of making new you shoult help QT GUI project to speed up development. 
https://github.com/nurupo/ProjectTox-Qt-GUI

**Comment by tux3** [comment]
I actually started by reusing a lot of code from nurupo/ProjectTox-Qt-GUI, so most of the features I add are actually pretty much "compatible" with his code.

He could for example easily import features from my repo if he wanted and I could from his (I already did!).

**Comment by fcore117** [comment]
nice to hear, lets hope combination of your and his code can speed up QT client or clients development.
