### ISSUE TITLE
[Regression] Commits and merges aren't GPG signed

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#400]

**Comment by tux3** [comment]
Alright, guess I'll make all my merges from the command line from now on.

That said I won't force others to sign their commits (though it would always be appreciated), I'll sign the merge commits/cherry-picks instead.

**Comment by zetok** [comment]
298aa1eb00f1ecca4dcb3d55f2fb57fad5f2e78a is not signed

**Comment by apprb** [comment]
@tux3, how your public singing key can be retrieved?

**Comment by tux3** [comment]
@zetok dammit. Old habits die hard.

I guess I can rewrite history and sign it, this shouldn't break anything.

EDIT: Actually I might have just broke everything..
EDIT2: Or maybe not, git is smart

**Comment by tux3** [comment]
@apprb I don't know how to do that so have a base64 copy of my public key 
Use base64 -d and gpg --import to retrieve it I guess.

mQINBFQTVK8BEADdywWBirFzspfeOGvTd2bJfgANtxMTK2GAToZAOfnPiylk12Jw7bvguQ8xnEs8
4H/0zOFBpHlJqcCNSmzLFKuAvDJZf96WyvefJUEIWagrWP5aAGjx6vgOpSLjMyi1Ic5RBFxzrw13
2zSq8M0k7F/GY8ayEwRcpRQ9y99yXcWz8zU99kV5WQfgFwC9aroOl1s26NkxAMykb2jJSiotGn/8
hWb3u+szrDgLWWdAtw9ODo61LrtbgQ7GoCrEjKZ/Xq0Ch6RSDTeG0Gri9+P4NWx7wfkMw3DpyOkl
Qn144cgj3WBI5bfGK6XHgqVI4M0PYmmzJsmRGoP9TYEetLHYnxUnRjYDo47Rb4tOVS4G2VpFfeh/
OjvQDQA6qYa5cnLb5OA4a3OyBwsHIjeFkvRAmFu854b2sRtoeRZVtAhUhMJTExh6UaRstMsob9oe
s8CVzWPYcIpoZvBs1FG+QoPDjpHYrEmSQ7plPjIjF60j32iphPmNBIcsaJWf1XLrkmzh/1C6R6hZ
DNXH2i14rVDQLuPS4rGLHqyR6p4YKFcVbgLfsmtDzGhxifR+LTm+3eNTBk5LHlRWKUYT0P98IXr4
5UpDofPMTr+MRAufKRDFRhU3ZnBJf7c3TPkW9FSEj3L1c5KOolcShQfejzLIiKn11FTfi2kkuI54
UwNLQLGRxq/DAwARAQABtC10dXgzL21sa2ogKEpvaG4gU21pdGgpIDxiYXJyZGV0d2l4QGdtYWls
LmNvbT6JAjgEEwECACIFAlQTVK8CGwMGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJEH4IbdZh
JjJkcwIP/3pDwDrv2HkIKxP/cfS3+AJ1R7x5sAJ4AUPiYlR0BsYjGi5AwdYjk4WHBSZ+tacKYbwx
XjMeXXpIdpd1Sp9R/+rANZwxLUgXLi2NFBkN90kl7GAjm5YF8+6MwzsHwK4MIe0I0kvfJ8LXwzNL
YIt+iP8ZyCz0RjmBfGCJlxU/wFN6euyjLp1vguaeF9MN/+6CTO8YaWhMrTcYhUOwA6pFR0LtqrgR
16FhCP2sV2jDu9k+eVd2gZZoya6b33GK1aak4tkajz8hNKtR8OaXhnlsRE6cZo1Hb/O9YdRCu+jZ
82DTeCsrFfQ/PajSn7ESY68tyd5+VOZdgoueDFJjPIQYBuD5R3Bc0cMMUBC7a3/OT0EqBZHJOtAU
7ZTXi0Hr0xFXnVBhRooOfZdF+htRVG4mZSy3t3q/cUqdV62G5c10q8T/iWU3EP4Icc6AJfcf5Z8b
7wPpLsHoKVkeIHPdbHB8f/dX56WjFUUoiBukq+MMReBdU97KGCN8q57IgVKi1mwC1Su4whUZq3yM
IJ9vMUXp1x4+HHwRvoiXWLw487Q9yuhAqUt4C22A5GJjj+FhXkpoqdRQtAY1ijTHnA8bymjyzbGq
Cqy20w6dLMMB7zBwpGd0heS3v1/Gv4ztUWN2Gfqo1Ly/n+/bTIhq8OkuXq8DDkIpjsqbDEGFPT95
A0thlaIIuQINBFQTVK8BEACrxUnUwF0ZHynGdslItcXD1YeH3rwr/XNx/L7JaaJ8a1CiUHDHvy3L
vLSd3kon/89Hj8olRaGVor5/a1cJ0RHQ6cA867RVHWFKsPQ1ZJ6xnDKiE6HJNx34Jk6vJLrFZxQT
TThy1GJ1XDmB6xl65acR5u4GBBXkSVX7frNOgYxdTIZ1pBSmafnGmH2NWG1Trds/av8+L+6dudUX
RKX00SlfcWcbxDf9evYzfPLT3WSvy8g25mNmKeTCntQ9avGQFo/MpRtj485/xA0EF7tTLW1VYEIL
aS7eufEJrL8CjRR1q82MdPPsZTy9WwZkNwRoNCkaJJMk+kF7PBbCrFdqSr5m92DRgHeHtvXbILPK
0q7miQo5dGZ69LpIu/nj7Yzi0fzKPufwLkMvzepOjlPEpwUiFsoKQ8P3e360jew62odTfdxH3Okd
6Oc9KXtq4THaBORnfqfYj4csAzTbCwLKpZq4iYV4JdfLNI/Wr5B2rY8iViL9jiDY76PS8yLy26FX
eiyVAn3rdcm6+R9mAYmONv/diWyIxpUffyG9AihL7YPoEtILCoy8y08aGibB5Vnls60fAhTE5x+0
BxltQlWI7B59oYYZn2afUh8eWta027vs2Suh+JZ/sBXHhH3ikRZFe7qjrFYJpt3j4XJueIcbtHjq
XSeLW3U8vt2xz/itOVx8eQARAQABiQIfBBgBAgAJBQJUE1SvAhsMAAoJEH4IbdZhJjJkDioQAJeT
Vuea2y7xCq1cSePwkT4DZBmFVnuZzevS/3+336d+ggsw0dZwavW57Yv7ajcwmNrCwYMElZI9CtVp
wTPKbg69yQjdzlCugf+l3HMAcXYEGea6/uq+b6Zqr2yVnvFKn4WNLcxXxTVbWZJfERYzcsbeVB5b
i3mkk3TRZ4OLqh5l7fuQ0kJrskqh6HOnfA85RUEVtO1utFlinH4IBQIAdKD6AvYM6hRI68UCulcl
NmZ2s7hyhw1RKQCSdzEaaubVCWmqdGNBlmz0r29UbV7ORDZTPNk50ql5/tcYQFEa3dhyfFankNdz
j5lPqbx5I3GMouTs5LRKl5gDYma9BoqdzBibqQcYlqOGtlk9MqHqXAAsCFTLtJkqFHurXUUxBwYU
0VtzTcmaqbaFljgh8aSQUAbVP25E2GS0g8XmnPSm+jPggMDJYKEm+UKlcr1gtLThtM+yE7grsoC6
Ag/iSmS24GIMEQeqtMHTnm1lw/EJZVkmxb03sJdESpANzaqaPTO6WmDRs7qfjqhuZ7x325xnKRBg
3O9mJfwlHU3yFiL6MY53nXIGutI+s2NsUwC9u62Uohiz7K6CtAZq2BCYSt+UiJMKSQ7Bc+x6wWDX
JdIXn02CmGXuzeKGx/OSGykye2Pj4yGw3Wt3ySwvmvMtGVsBsyBzmiYWyuEVmwI9tsCdHf6x

**Comment by zetok** [comment]
@tux3 `gpg --export -a` and put that into https://pgp.mit.edu/

and paste here your key id

**Comment by apprb** [comment]
`gpg --send-keys [key id]` is easier

**Comment by tux3** [comment]
@apprb done

@zetok  https://pgp.mit.edu/ won't accept my key
It says <blockquote>Key block added to key server database. New public keys added:
1 key(s) added successfully.</blockquote> but ignores my key everytime.
Edit: Ah wait, I think it works, the search box just doesn't take key IDs

**Comment by zetok** [comment]
20f2dac7558d83f15492e0aa30e1146e585f718b is not signed

**Comment by agilob** [comment]
@zetok how do you check if it's signed (on github)?

**Comment by zetok** [comment]
@agilob `git log --show-signature`

Edit: Oh wait, on github.. gitthub doesn't do that.

**Comment by dubslow** [comment]
@tux3: `alias commit='git commit -S'` ? Edit: I guess -S, doesn't really matter to me

**Comment by agilob** [comment]
Should we do `-S` or `-s`?

`-S` will leave less "noise" in commit message.

**Comment by apprb** [comment]
`-S`.
`-s` do completely different thing.

**Comment by tux3** [comment]
I'm confident I won't forget to sign commits again, so I'll close this for now, but if I do forget please yell at me and I'll reopen.
