### ISSUE TITLE
No Shortcut for kiss smiley

### ISSUE THREAD

**Issue by NicoHood** [qTox/qTox#4000]
Normally if you type a short `:D` the characters ar translated into a smiley. This does not apply for the kiss smiley. It would be nice to write kiss smileys like `:*` or `:-*`.

**Comment by sudden6** [comment]
The definition for this smiley is just missing in the "Universe" smileypack, if you switch to "EmojiOne" it's there.
Fixing this would need to add the definition in `emoticon.xml`

Maybe you could submit a PR?

**Comment by sudden6** [comment]
closed by af711c0527048a64ee74e58979217e49d4f39a64
