### ISSUE TITLE
Incorrect display and behaviour of call buttons

### ISSUE THREAD

**Issue by initramfs** [qTox/qTox#4004]
##### Brief Description

OS: Arch Linux  
qTox version: master 
Commit hash:  af711c0527048a64ee74e58979217e49d4f39a64
toxcore:  0.1.1
Qt:  5.7.1 

Reproducible: Always

##### Observed Behavior

A regression introduced as part of 917812da has caused incorrect appearance of call related buttons in the chat form, as seen below:

![Compressed buttons and incorrect call button colors](http://i.imgur.com/PiZWtxd.png)

Not only are the mute call and mute microphone buttons compessed, when initiating an audio call, the video call button remains green and clickable but non-functional.

##### Expected Behavior

Screenshot of a very similar call taken from the v1.6.0 tag:

![Correct button apperance](http://i.imgur.com/IohSqXi.png)

##### Additional Info

Compressed buttons seem to be fixable by reverting the removal of hard-coded heights and widths in the css files for buttons, though the incorrect video call button may require more in depth analysis to fix.

I am using a HIDPI display.

**Comment by initramfs** [comment]
@Diadlo @sudden6 @antis81 I'm hoping this can be fixed for the 1.7.0 release, I can't debug it myself since I'm getting on an airplane in a few hours.

**Comment by antis81** [comment]
@initramfs @sudden6 -> #3935

**Comment by Diadlo** [comment]
@antis81 #3935 doesn't fix it
