### ISSUE TITLE
Clipped mike/speaker icons

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4009]
1.7.0 has this problem.
![qtox-clipped-audio-icons](https://cloud.githubusercontent.com/assets/271906/21472769/abb40b94-ca9d-11e6-8c7c-949d54e80105.png)

kde4.

**Comment by sudden6** [comment]
@Diadlo this looks like a similar problem like we had in https://github.com/qTox/qTox/pull/3935

@yurivict are you using any special DPI settings or a HiDPI Display?

**Comment by yurivict** [comment]
79x78 dots per inch
