### ISSUE TITLE
[Regression] Russian letters in profiles names

### ISSUE THREAD

**Issue by VVD** [qTox/qTox#4012]
##### Brief Description

OS: FreeBSD 11.0
qTox version: 1.6.0  
Commit hash:  
toxcore:  0.160924
Qt:  5.6.2
Hardware:  i386 and amd64

Reproducible: Always

##### Steps to reproduce

1. Install qTox 1.5
2. Create profile with russian letters
3. Update qTox to 1.6

1. Install qTox 1.6
2. Create profile with russian letters

##### Observed Behavior
Don't show russian letters in profiles names.
Profiles created in qTox 1.6 look in the file system like "????.db".

##### Expected Behavior
Show russian letters! And create files with correct names in file system like was with qTox 1.5.

##### Additional Info
http://217.26.10.138/vvd/qtox160_russian.png

$ qtox 
[22:32:23.944 UTC] persistence/settings.cpp:137 : Debug: "Loading settings from /home/vvd/.config/tox/qtox.ini"
[22:32:24.051 UTC] widget/translator.cpp:56 : Debug: Loaded translation "ru"
[22:32:24.051 UTC] widget/translator.cpp:69 : Debug: System translation not loaded "ru"
[22:32:24.052 UTC] ipc.cpp:59 : Debug: Our global IPC ID is  16264608118004039845
[22:32:24.055 UTC] main.cpp:210 : Debug: built on:  00:29:57 Dec 26 2016 ( 1482701312 )
[22:32:24.055 UTC] main.cpp:211 : Debug: commit:  n/a 

[22:32:24.055 UTC] nexus.cpp:85 : Debug: Starting up
[22:32:28.006 UTC] persistence/profile.cpp:624 : Warning: Couldn't open tox save  "/home/vvd/.config/tox/��������������1.tox"
[22:32:30.179 UTC] persistence/profile.cpp:117 : Debug: Loading tox save  "/home/vvd/.config/tox/��������������1.tox"
[22:32:30.179 UTC] persistence/profile.cpp:121 : Warning: The tox save file  "/home/vvd/.config/tox/��������������1.tox"  was not found

The name of this profile is "Русский1".

**Comment by VVD** [comment]
Tested on 1.7.0 - all same.

**Comment by VVD** [comment]
Tested on 1.5.2 - all work fine with russian letters: open and import profiles.
Support of russian (all unicode?) letters was broken from 1.5.2 to 1.6.0.

**Comment by VVD** [comment]
$ git bisect good
29da2210c98a2f1bf2dcaf6af18ba818ceef5d2c is the first bad commit
commit 29da2210c98a2f1bf2dcaf6af18ba818ceef5d2c
Author: sudden6 <sudden6@gmx.at>
Date:   Fri Sep 23 00:12:40 2016 +0200

    feat(smileys): try to load smileys from XDG_DATA_DIR directories
    
    This provides a location where users can store custom smiley packs

:040000 040000 fb3e0273179cbdab15cd3ed37e8ffcf43d8d82ab 47b533b457d3be80ba5429ef8bf5e243346ede1c M      src

**Comment by sudden6** [comment]
```
[01:43] <sudden6> VVD: can you revert the commit on 1.7.0?
[01:43] <sudden6> git revert 29da2210c98a2f1bf2dcaf6af18ba818ceef5d2c
[01:44] <VVD> how?
[01:44] <VVD> manually?
[01:44] <sudden6> nope
[01:44] <VVD> ah
[01:44] <VVD> see
[01:55] <VVD> sudden6, work fine!
[01:55] <VVD> 1.7.0 without this commit
```

@Diadlo can you help me with this? I'm pretty puzzled why it breaks things...

**Comment by Diadlo** [comment]
@sudden6 I'm too :/
Can't reproduce the issue and have no idea, how it can change this behavior.
@VVD are you sure, that you revert this commit when you was on 1.7.0? AFAIR `git bisect` doesn't reset HEAD to the master automaticaly

**Comment by VVD** [comment]
@Diadlo> Can't reproduce the issue and have no idea, how it can change this behavior.
Did you try with same environment - FreeBSD 11 and etc.?

@Diadlo> are you sure, that you revert this commit when you was on 1.7.0?
Ofc I'm sure. I did "./test-pr.sh 4013" before "git revert 29da2210c98a2f1bf2dcaf6af18ba818ceef5d2c" and qTox show version 1.7.0 in about window.

This error is same on 2 different hosts: 1st is i386 (home) and 2nd is amd64 (work), both are FreeBSD 11.0.

**Comment by sudden6** [comment]
The only thing that IMO could have an effect is `#include <QStandardPaths>`, but I looked into the [source of qt](https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/io?h=5.6) and couldn't spot anything interesting

**Comment by Diadlo** [comment]
@VVD Nope. Only on Arch linux. I haven't FreeBSD

**Comment by sudden6** [comment]
See https://bugreports.qt.io/browse/QTBUG-57820

**Comment by VVD** [comment]
qTox 1.7.1 affected, bug not fixed.

This workaround work for me:
```
--- src/persistence/smileypack.cpp.orig 2017-01-20 05:14:40.356081000 +0300
+++ src/persistence/smileypack.cpp      2017-01-20 05:15:02.265506000 +0300
@@ -40,6 +40,7 @@
 #include <QStandardPaths>
 #include <QStringBuilder>
 #include <QtConcurrent/QtConcurrentRun>
+#include <locale.h>
 
 #define EMOTICONS_SUB_DIR QStringLiteral("emoticons")
 
@@ -84,6 +85,7 @@
 
 QStringList SmileyPack::loadDefaultPaths()
 {
+    setlocale(LC_ALL, "");
     QStringList paths = QStringList{":/smileys", "~/.kde4/share/emoticons", "~/.kde/share/emoticons"};
     // qTox should find emoticons next to the binary
     paths.append('.' + QDir::separator() + EMOTICONS_SUB_DIR);
```

More information here:
http://bugs.icu-project.org/trac/ticket/12886
https://bugreports.qt.io/browse/QTBUG-57522
