### ISSUE TITLE
[Regression] unable to cancel audio call before it starts

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#4016]
##### Brief Description
qTox is unable to cancel audio call before it starts (when call button is yellow). It was possible on v1.6.0.

OS: Gentoo Linux amd64
qTox version: v1.7.0-5-gb4c4569
Commit hash: b4c4569299d734d8056e48a6d6dd62f4df2ae86f
toxcore: 0.1.2
Qt: 5.6.2

Reproducible: Always

##### Steps to reproduce

1. Press call button
2. Once it turns yellow, press it again to cancel audio call

##### Observed Behavior
Nothing happens. There's only a warning in the stdout:
```
core/coreav.cpp:257 : Debug: "Starting call with 7"
core/coreav.cpp:260 : Warning: "Can't start call with 7, we're already in this call!"
```

##### Expected Behavior
Audio call should be canceled.

##### Additional Info
`git bisect` with 
git bisect good v1.6.0
git bisect bad f5011cdb2feb2da042e373b4e4094e967bde8120

917812daaabc8b8118526691e67a3f6e2dd8fcb2 is the first bad commit
```
commit 917812daaabc8b8118526691e67a3f6e2dd8fcb2
Author: Nils Fenner <nilsfenner@web.de>
Date:   Mon Aug 29 09:07:23 2016 +0200

    fix: Status reflection for friend calls

:040000 040000 05af1848378a084330cf091d7f7f3218f7ad8f8b adcc966bbb1669a94fbef5cc53c2404f07881abd M	src
:040000 040000 1310dd21e85a5b5472fe35134385857ddc1a2a74 1c92acb8e15a02c40b6f94744e13729213e8e067 M	ui
```

cc @Diadlo @antis81

**Comment by antis81** [comment]
-> #3935

**Comment by zetok** [comment]
@antis81 no, #3935 doesn't fix it.
