### ISSUE TITLE
Own tox id gets auto added to add friend tox id field

### ISSUE THREAD

**Issue by AliceGrey** [qTox/qTox#4024]
##### Brief Description

OS: Arch Linux 4.4.39
qTox version: v1.7.0-13-gb9c1d59a
Commit hash:  b9c1d59a074a86c3f9b92e7f27f206de03b0fe01
toxcore: 0.1.2
Qt:  5.7.0

Reproducible: Always

##### Steps to reproduce

1. Click your user photo to open your profile
2. Click tox id to copy tox id to cliboard
3. Click add friend button

##### Observed Behavior

Your tox id gets automatically copied to the toxid field

##### Expected Behavior

The toxid field to be blank

**Comment by zetok** [comment]
git bisect with
```
git bisect good v1.6.0
git bisect bad f5011cdb2feb2da042e373b4e4094e967bde8120
```
points to the
2a88e5c0696fe5e2c0d8600febe09374994525b9 is the first bad commit
```
commit 2a88e5c0696fe5e2c0d8600febe09374994525b9
Author: Diadlo <polsha3@gmail.com>
Date:   Wed Nov 9 00:21:08 2016 +0300

    refactor(toxid): Removed Core dependency from ToxId
    
    It's needed to make ToxId just data structure

:040000 040000 6bf5fad5823b67c4c0e61ce778ccea27890d9fe4 c3578057c9af55e1fc547f06665aa4007cd0b13e M	src
```
