### ISSUE TITLE
the first four characters have not received.I-bug

### ISSUE THREAD

**Issue by abcd99** [qTox/qTox#4033]
##### Brief Description

OS: Windows / OS X / Linux (include version and/or distro)
qTox version: v1.5.2-8-gfd04a28
Commit hash: fd04a2832aa885d260ded4e476eefcddd49237b3
toxcore: 0.0.0
Qt: 5.5.1
Hardware:  
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. Qtox sends a message to the phone's antox, for example the string "abcde", but the phone can only receive the string "e", the first four characters "abcd" have not received.
2. 
3. …

##### Observed Behavior
the first four characters "abcd" have not received.

##### Expected Behavior
All characters, that is, "abcde" can be received without any missing characters.

##### Additional Info
(links, images, etc go here)

----

More information on how to write good bug reports in the wiki: https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by zetok** [comment]
Can't reproduce. Is your Antox up-to-date ?

**Comment by zetok** [comment]
Caused by a very old Antox version (#4035), thus closing.
