### ISSUE TITLE
I am in China. I report a very serious bug

### ISSUE THREAD

**Issue by abcd99** [qTox/qTox#4035]
##### Brief Description

OS: android 4.4.2
tox version: Antox 0.14.1 
Commit hash:  
toxcore:  
Qt:  
Hardware:  
…

Reproducible: Always 

##### Steps to reproduce

1. in my phone there is an antox, click the settings menu, do not check the "WI-FI Only", antox immediately become offline, can not send and receive messages. My cell phone signal is very good, why it becomes offline? I am in China, the government to prevent the connection tox, is this the reason?
2. 
3. …

##### Observed Behavior
Antox become offline.

##### Expected Behavior
Antox should be online.

##### Additional Info
(links, images, etc go here)

----

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by zetok** [comment]
>Antox 0.14.1

That's a very old Antox version, you should update. Currently there's 0.24.427.

If issue is still reproducible on newest Antox, you should report it to https://github.com/Antox/Antox.

**Comment by zetok** [comment]
>My cell phone signal is very good, why it becomes offline? I am in China, the government to prevent the connection tox, is this the reason?

Um, it's just probably a bug in Antox.
