### ISSUE TITLE
Please provide source signature for 1.7.1

### ISSUE THREAD

**Issue by farseerfc** [qTox/qTox#4045]
I see a new release 1.7.1 is tagged. Please sign the released source tar.
Thanks!

**Comment by zetok** [comment]
Is there a script that automates that?

**Comment by farseerfc** [comment]
NicoHood wrote a script as well as some documentation for that https://github.com/NicoHood/gpgithub#43-sign-the-sources
See also: https://github.com/qTox/qTox/issues/3912
We will download and verify each released tarball during packaging.

In the future, it will be very helpful for us if the project leader can publish a list of fingerprints of trusted GPG keys to somewhere trustworthy (e.g. project homepage) so that everyone can verify that the keys are trusted by the project. And please sign the releases only with these keys.

For now, I just need a `qTox-1.7.1.tar.gz.asc` file that can be created by:
```
gpg --armor --detach-sign qTox-1.7.1.tar.gz
```
with one of the developper's key.

Thanks

**Comment by zetok** [comment]
@farseerfc
>NicoHood wrote a script as well as some documentation for that https://github.com/NicoHood/gpgithub#43-sign-the-sources

Yeah, I've looked at that repo before making a comment. I haven't seen any docs on ~automated usage, only manual steps. Some of those steps are a bit misleading (e.g. `xz` for release tarballs, not a good format for archives).

The script in the repo probably does the job, but before using it I'd need to make sure that it really does what it should and nothing else. It has over 300 lines of bash. No docs on what it is supposed to do and how. And if I'm reading it right, it doesn't automate whole process (no upload of signatures).

>In the future, it will be very helpful for us if the project leader can publish a list of fingerprints of trusted GPG keys to somewhere trustworthy (e.g. project homepage) so that everyone can verify that the keys are trusted by the project. And please sign the releases only with these keys.

Good idea. I think that it's worth to mention though that webtiste, just like the repo is hosted by github.

Right now website doesn't have a place to put GPG keys in. Would putting that info in README.md be sufficient? qTox repo is mirrored on gitlab: https://gitlab.com/qTox/qTox_mirror

**Comment by farseerfc** [comment]
Sorry I don't know any methods exists for automating the whole process. I don't know how qTox developers create releases currently, and how to integrate the signature part with the current process.
But the signing process itself is simple enough, that you just need to upload an asc file created by `gpg --detach-sign --armor` with every release.
If you use [GitHub API](https://developer.github.com/v3/repos/releases/#create-a-release) for automatically creating releases, you can [append a signature as asset with the same API](https://developer.github.com/v3/repos/releases/#upload-a-release-asset). But I think the signature will be created manually and locally, as you need to fully trust the environment that stores your key.

Having a list of fingerprints in README.md will be sufficient for us, although it's up to you to decide whether to fully trust GitHub or GitLab (that these hosting services will not modify the fingerprints without your notice).

**Comment by zetok** [comment]
>I don't know how qTox developers create releases currently, and how to integrate the signature part with the current process.

Well, it's a simple `git tag -s $tagname && git push $tagname`, rest of the stuff (tarball, zip) is automatically provided by github.

**Comment by farseerfc** [comment]
Thanks for the clarification. I will work with @NicoHood to make the scripts usable and understandable.

**Comment by NicoHood** [comment]
@zetok The script is currently under development. The readme gives you all information for manual usage and it is really **super simple**. Also you dont need to use the .xz, its just a suggestion. Thanks for the note though, I will read through it. Please sign the new release, otherwise we cannot update the package.

@farseerfc If you want to help, join me on tox, I am working with someone else to improve the english in the readme.

**Comment by zetok** [comment]
Made a release with signed tarball, thus closing.

**Comment by farseerfc** [comment]
Please also sign v1.10.2 release, thanks a lot.

**Comment by NicoHood** [comment]
@farseerfc https://github.com/qTox/qTox/releases/download/v1.10.2/v1.10.2.tar.lz.asc

**Comment by farseerfc** [comment]
@NicoHood wow, thanks
