### ISSUE TITLE
9ffa1df5cb introduces UI regressions

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#406]
9ffa1df5cb

My buttons and ComboBoxes are now fugly Windows 98 style.

![reg0](https://cloud.githubusercontent.com/assets/6127392/4554081/f01770de-4ea6-11e4-9aaa-0d9d6c71d98b.png)
![reg1](https://cloud.githubusercontent.com/assets/6127392/4554082/f365a666-4ea6-11e4-91de-2bbf900542ef.png)
![reg2](https://cloud.githubusercontent.com/assets/6127392/4554084/f696f74a-4ea6-11e4-8539-3c2b355649a5.png)

(I can do before pictures if you really want)

**Comment by agilob** [comment]
I am not sure what is wrong with it, QComboBox has now mixed style, I defined only background colour, rest of the style should be taken from native theme. I found this [bug in Qt](https://bugreports.qt-project.org/browse/QTBUG-33537?attachmentOrder=desc), it might be related. What I can do before end of this (work)week is implement theme selector in qTox, it would be a combobox list which has detected by Qt system styles. I have only 3 installed on my system: 

```
 qDebug() << QStyleFactory::keys();
 ("Windows", "GTK+", "Fusion")
```

I tested it and mixed custom style with QStyleFactory works properly:
Fusion:
![qtox-fusion](https://cloud.githubusercontent.com/assets/2544251/4565247/3d4f8d6a-4f1e-11e4-9e50-0c566292e0ed.png)
GTK+
![qtox-gtk](https://cloud.githubusercontent.com/assets/2544251/4565248/3da87fa6-4f1e-11e4-9905-ab368394ee67.png)
Windows:
![qtox-windows](https://cloud.githubusercontent.com/assets/2544251/4565249/3dacc660-4f1e-11e4-8049-f78bda30321c.png)

No style (on my KDE settings)
![my kde](https://i.imgur.com/XJ0mbpi.png)

I see you're using gnome/MATE so you will have more styles installed. I think it will be a walk-around solution, but this feature can be implemented anyway, so if you want it, I'll do it. Unfortunately I know nothing about CSS, so I can't fix it with custom style now.

**Comment by dubslow** [comment]
I have Cinnamon 2.0, which is forked from Gnome 3 (I think, not real sure of the details).

**Comment by agilob** [comment]
Ok, I'll write that theme selector in the next couple of days, maybe it will fix the problem for you. 

@tux3 I think it would be a good idea to move "Connection settings" to another tab.

---

EDITED by @tux3 on october 17th : Fix @ mention to me

**Comment by krepa098** [comment]
Seems like a limitation of Qt's GTK+ theme as it works fine using native themes. So yes a theme selector might help.

**Comment by agilob** [comment]
I'll test it on Mint with Cinnamon tomorrow and make a PR.
https://github.com/agilob/qTox/commit/c716b615c82ece3c3471f50a1cd79fd4fbb6eaa2

**Comment by apprb** [comment]
Additional small issue: inactive control elements look exactly the same as active ones.

**Comment by agilob** [comment]
@apprb  this should be fixed by style selector: https://github.com/agilob/qTox/commit/c716b615c82ece3c3471f50a1cd79fd4fbb6eaa2, [PR is awaiting](https://github.com/tux3/qTox/pull/421).
