### ISSUE TITLE
[Feature Request] Force qTox to use specific internet connection

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#4061]
##### Brief Description

OS: Windows
qTox version: You are using qTox version v1.7.0.

##### Steps to change connection

1. Settings --> Connections (Make a new tab)
2. Drop down box of list of adapters for internet (Bluetooth, Fiber, VPN, etc.)
3. Click the one you want (and reboot?)

I wasn't sure how to request this and I think this would be a really useful feature for me, and many others. Thank you.

I dont know how to add a proposal tag, sorry!!

**Comment by Hasshu** [comment]
Seems to be infeasible on Windows (see qTox/qTox#2965 and irungentoo/toxcore#1530).

**Comment by ghost** [comment]
Ah, well I can use qTox in a VM if i have to. Thanks anyways.

😢

**Comment by zetok** [comment]
Since it doesn't seem doable, closing.
