### ISSUE TITLE
Video: stuttered. Audio only: Ok. What is the minimum internet speed for video?

### ISSUE THREAD

**Issue by gustavklopp** [qTox/qTox#4062]
My friend lives in a quite remote area with low speed internet.
Each time I try to connect by webcam, the video stuttered a lot, and even audio itself is very choppy, with background hiss sound.

Connected by audio only, the sound is good.

What are the internet speed requirements for video in fact? 
By the way, connected by Apple Facetime (which I honestly don't want to use), even on his bad connection, the video is smooth.

**Comment by zetok** [comment]
>What are the internet speed requirements for video in fact?

That depends on the resolution of video used in the call. The higher the resolution, the higher bandwidth requirements.

Have you tried to set the webcam resolution to lowest possible value in qTox on both ends?

**Comment by Diadlo** [comment]
Also, small bandwidth with [this toxcore issue](https://github.com/TokTok/c-toxcore/issues/235) can provide ugly video stream

**Comment by Diadlo** [comment]
Closing, since question is answered
