### ISSUE TITLE
Provide a binary installer of 1.7.1 for macOS

### ISSUE THREAD

**Issue by ddobrev** [qTox/qTox#4063]
qTox 1.7.1 is out but there's no installer for macOS, please provide one.

This issue supersedes https://github.com/qTox/qTox/issues/3883.

**Comment by BigElectricCat** [comment]
`$ ./osx/qTox-Mac-Deployer-ULTIMATE.sh -b`\

`Starting qmake ... `
...
`compiling ../qTox/src/platform/timer_osx.cpp`
`clang: warning: argument unused during compilation: '-pie'`
`compiling ../qTox/src/platform/timer_win.cpp`
`clang: warning: argument unused during compilation: '-pie'`
`compiling ../qTox/src/platform/timer_x11.cpp`
`clang: warning: argument unused during compilation: '-pie'`
`compiling ../qTox/src/platform/autorun_win.cpp`
`clang: warning: argument unused during compilation: '-pie'`
`compiling ../qTox/src/platform/autorun_xdg.cpp`
`clang: warning: argument unused during compilation: '-pie'`
`compiling ../qTox/src/platform/autorun_osx.cpp`
`clang: warning: argument unused during compilation: '-pie'`
`compiling ../qTox/src/platform/capslock_win.cpp`
`clang: warning: argument unused during compilation: '-pie'`
`compiling ../qTox/src/platform/capslock_x11.cpp`
`clang: warning: argument unused during compilation: '-pie'`
`compiling ../qTox/src/platform/capslock_osx.cpp`
`clang: warning: argument unused during compilation: '-pie'`
`compiling ../qTox/src/platform/install_osx.cpp`
`clang: warning: argument unused during compilation: '-pie'`
`compiling ../qTox/src/audio/audio.cpp`
`clang: warning: argument unused during compilation: '-pie'`
`In file included from ../qTox/src/audio/audio.cpp:22:`
`In file included from ../qTox/src/core/coreav.h:27:`
`../qTox/src/core/toxcall.h:10:10: fatal error: 'tox/toxav.h' file not found`
`#include <tox/toxav.h>`
`         ^`
`1 error generated.`
`make: *** [audio.o] Error 1`

Where to look [tox/toxav.h]?

**Comment by zetok** [comment]
@BigElectricCat did you follow https://github.com/qTox/qTox/blob/master/INSTALL.md#first-run--install ?

**Comment by BigElectricCat** [comment]
Yes, I did. During the execution of the script error occurs. This error interrupted the operation of the script (the directory already exists). If you delete or rename the directories, the script is completed successfully.
I solved the problem by using the manual "git clone" for the desired directory (toxcore and qtox). Performing "./qTox-Mac-Deployer-ULTIMATE.sh -u" renewed well.

Sorry for my English.

**Comment by ddobrev** [comment]
@BigElectricCat I attempted to run the script myself and got various errors, I don't have the time to try any more. So may I ask you for a favour? If you manage to build qTox and it does work, could you please upload the DMG (or app) somewhere (GitHub, DropBox, wherever if feels comfortable) so that I can try it too?

**Comment by BigElectricCat** [comment]
Ok, when i compile qtox, i will place it on mega.nz (or other file host).
Links are provided in this discussion.

**Comment by ddobrev** [comment]
@BigElectricCat hello, how is your compilation going? I would really love for qTox to work again on macOS. The last version that does is 1.4.1 and it's almost unbearable because of https://github.com/qTox/qTox/issues/3158.

**Comment by ddobrev** [comment]
@iphydf could you please build a DMG for testing using the script? #3158 makes qTox horrible on macOS.

**Comment by ddobrev** [comment]
Well, congratulations. qTox is officially useless on macOS because of its constantly starting character-eating. My only remaining friend to use qTox regularly and I have just decided to temporarily go back to Skype until you at least produce a binary release for the Mac. Given how quickly you fix basic bugs, this temporarily is going to last forever. I've been waiting for almost a year now for you to pull yourself together. You didn't. In particular for macOS, you kept complaining it was because you didn't have Macs. Well, somebody with a Mac appeared and nothing changed. Not to mention having a free Travis build for macOS would've solved the problem regardless of how many of you own Apple machines. You did nothing there either. Well, have fun with your project because apparently your fun is all it's good for.

**Comment by zetok** [comment]
@BigElectricCat could you make a separate issue for the errors that `./qTox-Mac-Deployer-ULTIMATE.sh` produces?

**Comment by zetok** [comment]
Done in https://github.com/qTox/qTox/releases/tag/v1.8.1, thus closing.
