### ISSUE TITLE
Windows night builds again can't compile

### ISSUE THREAD

**Issue by DX37** [qTox/qTox#4068]
On build.tox.chat last nightlies can't compile.
Some errors from output:

> src/chatlog/chatlinecontentproxy.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^

and

> linking release/qtox.exe
/usr/bin/i686-w64-mingw32-ld: cannot find dynamicbase: No such file or directory
/usr/bin/i686-w64-mingw32-ld: cannot find nxcompat: No such file or directory
collect2: error: ld returned 1 exit status

Seems like linker trying to link flags xD

**Comment by sudden6** [comment]
Could be https://github.com/qTox/qTox/commit/5928413b28f94764bf4fddfbd6a131d5bebbc46a

@zetok can you take a look?

**Comment by ghost** [comment]
Fix https://github.com/qTox/qTox/pull/4069

**Comment by zetok** [comment]
#4069 was merged, thus closing. If it's still not fixed, comment for reopen.
