### ISSUE TITLE
Still no option to disable local peer discovery in the settings?

### ISSUE THREAD

**Issue by Hasshu** [qTox/qTox#4074]
OS: Windows 7 Ultimate, SP1 (64-bit)
qTox: v1.7.0
Commit hash: 12c21b21d2d62a27b0002c1add7e4d7faa0d018d
toxcore: v0.1.3
Qt: v5.5.1

Disabling local peer discovery should have been [possible](/TokTok/c-toxcore/pull/306) since v0.1.1 of c-toxcore, but it seems that qTox still doesn't provide a way to do that via the settings.

**Comment by zetok** [comment]
Yeah, no one implemented support for it yet.

**Comment by Hasshu** [comment]
Some suggestions: "Enable Local Peer Discovery" could be a checkbox under **Advanced** -> **Connection Settings**, below "Enable UDP (recommended)"; its tooltip could consist of a general description of the feature, followed by a warning about VPN leaks being a possible side effect.

<s>Incidentally, could it be done by v1.8.0?</s>

**Comment by Hasshu** [comment]
Any ETA?

This here is a gaping security hole.

**Comment by zetok** [comment]
> Any ETA?

No. `help wanted` label means that help is wanted with this one. Perhaps `up for grabs` would be more clear?

>This here is a gaping security hole.

Not quite. Current tox security model only really covers privacy, and not anonymity.

**Comment by Hasshu** [comment]
@zetok

> Perhaps `up for grabs` would be more clear?

Actually...

(☞ﾟヮﾟ)☞

Do it!

**Comment by Hasshu** [comment]
Lol, GJ.

`</ot>`

**Comment by Hasshu** [comment]
Bump.

Also, this probably should be labeled as `E-easy` and `I-ui`.

**Comment by ghost** [comment]
I have a similar issue. I'd like to see an option to *enable* LAN discovery, as a separate thing from UDP. So one could have UDP disabled and not leak IP address when using proxy, but still have the benefit of LAN discovery. TRIfA is one client that does this.

**Comment by anthonybilinski** [comment]
It looks like in toxcore, LAN discovery packets aren't sent when UDP is disabled, even if local_discovery_enabled is true, which means it's currently out of qTox's hands. Going to investigate this and create an upstream issue if needed.

EDIT: well, "disable local peer discovery" is totally within our hands. PR for that. Just force enabling when UDP is disabled is not possible for now.
