### ISSUE TITLE
Rename zh translation to "zh_cn", and create "zh_tw"

### ISSUE THREAD

**Issue by Artoria2e5** [qTox/qTox#4080]
* qTox version: HEAD/482757e
* Reproducible: Always

The Chinese language is commonly written in two different scripts, Simplified and Traditional. The former is what is used in CN, MA, and SG, while the latter is used in TW, HK, and MO. Since the two scripts can look pretty different, most software projects include at least two variants, CN and TW. Additional HK support is usually preferred -- there are many people in HK, and their vocabulary is quite different from TW's.

Current qTox Chinese naming is broken from the beginning (#3234). By observation, most translators write it in zh_cn, so it should make sense to make it the "CN" translation.

**Comment by zetok** [comment]
Rename done in #4082. I wonder if the string in https://github.com/qTox/qTox/blob/482757e6a2ab74410f33fca364af1b69f2695ae4/src/widget/form/settings/generalform.cpp#L107 also needs to be changed?

To create new translation via Weblate:
![spectacle ad9725](https://cloud.githubusercontent.com/assets/3148759/22030149/a9dfaadc-dcd4-11e6-8a4b-96084abc623a.png)

**Comment by Artoria2e5** [comment]
> I wonder if the string in https://github.com/qTox/qTox/blob/482757e6a2ab74410f33fca364af1b69f2695ae4/src/widget/form/settings/generalform.cpp#L107 also needs to be changed?

Funny that it already says "Simplified Chinese". Although I would prefer "中文（中国）" to correspond better with zh_*CN* instead of zh_*Hans*……

**Comment by Artoria2e5** [comment]
Hmm, I guess I should also suggest some fallback scheme across `zh` variants by [loading multiple translations in an instance](https://doc.qt.io/qt-5/qtranslator.html#using-multiple-translations). For a sensible default fallback order, try Ubuntu's [language-selector data](https://bazaar.launchpad.net/~ubuntu-branches/ubuntu/vivid/language-selector/vivid/view/head:/data/languagelist) (use `langlist` column).

**Comment by zetok** [comment]
>Hmm, I guess I should also suggest some fallback scheme across `zh` variants by [loading multiple translations in an instance](https://doc.qt.io/qt-5/qtranslator.html#using-multiple-translations). For a sensible default fallback order, try Ubuntu's [language-selector data](https://bazaar.launchpad.net/~ubuntu-branches/ubuntu/vivid/language-selector/vivid/view/head:/data/languagelist) (use `langlist` column).

Would be good to make a separate issue for that.
