### ISSUE TITLE
qTox randomly forgets text size setting in text input area

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#4085]
##### Brief Description

OS: Windows 7 x64 English UI, fully updated
qTox version: v1.7.0
Commit hash:  12c21b21d2d62a27b0002c1add7e4d7faa0d018d
toxcore:  0.1.2
Qt:  5.5.1
Hardware:  4K monitor, 3840 × 2160 resolution
High DPI setting in Windows.

Reproducible: Almost Always

##### Steps to reproduce

1. Start qTox.
2. Change Base font size in settings to 48px or some high number.
3. Observe that the text size in the text input area (the one that says "Type your message here...") is correctly as large as the text sent and received.
4. Randomly the text size in the text input area becomes much smaller (likely some default value). The sent and received text size remains correctly large.

Closing and starting qTox makes the font size in text input area correctly respect the large size for a while, and then it again randomly goes to small size.

**Comment by ghost** [comment]
After further testing, this bug is triggered when I press BACKSPACE.

In other words, I start qTox, text size is large when I type. The moment I press BACKSPACE, any further text becomes small and remains that way until I restart qTox.

**Comment by yurivict** [comment]
This is fixed in the master, please close this bug.
