### ISSUE TITLE
Error message when trying to add friend: "couldn'"

### ISSUE THREAD

**Issue by zoff99** [qTox/qTox#4086]
##### Brief Description

OS: Windows
qTox version: v1.7.0-79-gf15888b
Commit hash: f15888bad1f04522de31762fcbdc00db0cba6c2f
toxcore: 0.1.4
Qt: 5.6.2
Hardware: 
…

Reproducible: Always

##### Steps to reproduce

1. press "+" sign
2. enter toxID of friend
3. press "Enter" or "send friend request"

##### Observed Behavior
a small window with this error pops up every time

##### Expected Behavior
friend should be added

##### add. comments
the same friend could be added with the same ToxID on a different node

**Comment by sudden6** [comment]
can you upload the log output when this is happening? Which language are you using?

**Comment by zoff99** [comment]
there is no indication of any error in the log. with the stabe 32 bit version on the same windows machine it works fine.

**Comment by sudden6** [comment]
Can you resize the error message text to read the full message? Also, are you using English as language in qTox?

**Comment by sudden6** [comment]
Ok, I now why this happens and have a fix for it. This seems to prevent everybody to add someone by ToxID so I marked it as very high priority.
