### ISSUE TITLE
Gui icons in windows 10

### ISSUE THREAD

**Issue by shinodem** [qTox/qTox#4087]
OS: Windows 10 1607 x64
qTox version: All versions
Commit hash:  all versions
toxcore:  0.1.4
Qt:  5.6.2

Reproducible: Always

##### Steps to reproduce

I always have icons like this 
![2atwfn](https://cloud.githubusercontent.com/assets/8992581/22150512/61977d6a-df2a-11e6-8d32-fec7111f43cd.jpg)

**Comment by Diadlo** [comment]
Duplicate of #4009
