### ISSUE TITLE
A lot of warnings from clang compiler: argument unused during compilation: '-pie'

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4101]
```
c++: warning: argument unused during compilation: '-pie'
```

I think you need to use ```-Wl,-pie``` as per https://www.redhat.com/archives/libvir-list/2013-November/msg00877.html

**Comment by zetok** [comment]
@yurivict would you mind making a PR?

**Comment by yurivict** [comment]
What is the purpose of -pie and -fPIE in qTox?

**Comment by zetok** [comment]
Hardening. #3452

**Comment by yurivict** [comment]
Now it appears that ```-Wl,-pie``` is a wrong solution. I will consult FreeBSD compiler experts why ```-pic``` isn't supported.

**Comment by yurivict** [comment]
The original commit #3452 is wrong. ```-fPIE```  is a compilation flag, ```-pie``` is a link flag. They should be added to the respective variables, and not bunched together. #3452 needs to be fixed, this will resolve this problem.
