### ISSUE TITLE
qtox.svg is corrupted

### ISSUE THREAD

**Issue by Vort** [qTox/qTox#4114]
[qtox.svg](https://github.com/qTox/qTox/blob/master/img/icons/qtox.svg) logo differs in shape from [qtox.png](https://github.com/qTox/qTox/blob/master/img/icons/256x256/qtox.png)
Here is the difference visualization:
![qtox_diff](https://cloud.githubusercontent.com/assets/1242858/22506407/dd439220-e888-11e6-93b6-b364d34e8909.png)

**Comment by antis81** [comment]
I'd rather say "png is corrupted" in this case… :smile:

**Comment by zetok** [comment]
@Vort would you be interested in fixing it?

**Comment by Vort** [comment]
@zetok, I don't really know which version should be preferred and why they are different.
My first thought was that asymmetry is a mistake, but it is better to find out what exactly happened here.

**Comment by antis81** [comment]
@Vort When looking at the pattern it might come down to an applied antialiasing "filter" or something like that. It might even be a bug inside the rendering engine… nothing to be worried about too much, but interesting to investigate… have fun :+1:

**Comment by Vort** [comment]
@antis81, the one-pixel differences are not a problem, look at the middle of keyhole.

**Comment by Vort** [comment]
Screenshot from Inkscape:
![qtox_key](https://cloud.githubusercontent.com/assets/1242858/22517584/4ded7b7a-e8b2-11e6-8c16-840e88b9c81f.png)

**Comment by antis81** [comment]
Ok, just wanted to answer, but you been quicker. You know how to use inkscape?

1. Convert the corner "dot" on the right into… well… a corner (like on the lefft).
2. Probably align the new corner on the right vertically to the one on the left.

So you are right the SVG is "broken" and just has not been exported. Congrats! :+1: :100:

**Comment by Vort** [comment]
I have found the source of problem: [this](https://github.com/notsecure/uTox/commit/559c5d94488fd9f6c0658760a4d55bee439cb441#diff-43cf970883fd690a6653ffa2488e5a72) optimization was done not carefully enough.
