### ISSUE TITLE
Move 'Connection settings' to another tab

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#412]
Icon needed.

**Comment by dubslow** [comment]
Maybe replace the privacy tab? Since we have nothing for it...

**Comment by agilob** [comment]
https://github.com/apprb/qTox/commit/5c1e3360fe813d7dab868ed243569cb3051bbfa2

@apprb have something for Privacy tab.

**Comment by msteinbeck** [comment]
Privacy was added for "typing notification", "chat history", "profile password" etc.

**Comment by dubslow** [comment]
Oh.

Edit: I should really get my profiles branch finished...

**Comment by agilob** [comment]
Can be closed?
