### ISSUE TITLE
multiple enter/quit groupchat make chat history to be in the wrong groupchat subwindow

### ISSUE THREAD

**Issue by grinapo** [qTox/qTox#4129]
I have joined a few groupchats. I have left some, fallen out of others. I was reinvited into some.

Right now I have a groupchat which is Chat#2 (member set 2), but its subwindow shows the history of Chat#1 (and the stuff said by member set 1, who are not there and never been).

I can't reproduce it for you, but maybe you can still realise where the bug lies.

**Comment by sudden6** [comment]
So the title of the chat window is wrong, or the title in the contact list?
Which OS and window manager do you use?

**Comment by grinapo** [comment]
1) header is correct (group name, members)
2) the whole content below the header belongs to a different, already closed (and later rejoined) group

This is Debian/sid, xfce4, but it's not in a separate window but in the something you use which is like a tab content or whatever you call it. :-) Doesn't feel like an X problem, I can switch between the group chats and the content stays there just the same.

**Comment by sudden6** [comment]
Is this still an issue?

**Comment by grinapo** [comment]
Since I wasn't able to reproduce initially I really doubt I could answer this question. Usually it's pointless to keep issues where you can't even tell whether it's still valid or not. Thanks for trying!
