### ISSUE TITLE
Config port in settings window

### ISSUE THREAD

**Issue by 13ilya-old** [qTox/qTox#4133]
OS: Linux/openSUSE  
qTox version: (v1.6.0-obs)  
Commit hash:  5648106b34fc7dc3ad4e169651a0cbbd0139170a
toxcore:  0.0.0
Qt:  5.7.1

The user should be able to specify the tcp/udp port in the Setup window, through which the client will work and which will be opened by the administrator in iptables.

**Comment by Diadlo** [comment]
Duplicate of #2581
