### ISSUE TITLE
[enhancement] Export full chat history to plaintext without listing it in the client

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#4143]
As of now, when you want to export chat history, you first have to ask the client to list it, and then either choose to save the chat log from there, or copy and paste it into a text file. Listing it in the client can take a while if you have a lot of chat history since it has to wrap all the lines to fit into the window, and as can be seen in issue #4134 this can lead to qTox crashing.

Therefore, a function to simply export the chat log without having to list it in the client first would be a nice feature.

**Comment by zetok** [comment]
Related: #3138

**Comment by ghost** [comment]
Log export is fine in good weather, but think about two-party consent and security.

Bob may want to chat with Alice, yet NOT for her to keep a log. Bob's reasons might pertain to the chat subject, Alice the person (human threat model), OR her computer security (technical threat model). There's little point in crypto chatting to a compromised box suffering nightly data exfiltration, whether legal (nation-state actors, local police) or illegal (hackers, private investigators).

You can actually find vendors selling unloggable network comm tools, e.g. https://www.vaporstream.com and note it's common practice in business and law for people to say "call me" for such reasons. In short, there is a big market for non-consent to recordings.

Disallow logging absent explicit two-party consent. Each side must allow the other to keep a log for logging to work at all. Make the default "yes" but the GUI obvious. It should indicate both local and remote log permission setting.

Any log file at all should be encrypted. The log export dialog should warn that clear text will be written to disk. And suggest saving it to an encrypted disk or container file (e.g. tomb).

I realize dedicated computer nerds can probably work around such restrictions, but don't make their life easy. Bob probably doesn't want to chat with someone who refuses to respect his wishes in this matter.

**Comment by zetok** [comment]
@nixitixin 
> Bob probably doesn't want to chat with someone who refuses to respect his wishes in this matter.

Since no one is forcing Bob to do that then what's the problem? I mean, aside from you hijacking the issue and asking for something that is not doable?

Anyway, as far as logging goes:

* you can disable logging on your side
* you can ask other side to disable logging
* regardless of marketing bs logging is always possible and fairly easy to do – this point applies to everything, not just qTox
