### ISSUE TITLE
Can't see the other person in video calls

### ISSUE THREAD

**Issue by pems21** [qTox/qTox#4147]
##### Brief Description

OS: ArchLinux and Windows 7
qTox version: v1.7.1
Commit hash: 6f155d4db806a664d76457d42a20246ffbd5d1ac
toxcore: 0.1.5
Qt: 5.7.1

Reproducible: Always

##### Steps to reproduce

1. Initiate a videocall with someone from qTox 1.7.0 on Windows

##### Observed Behavior

Can only see myself during a videocall. The other person can see both cameras. 

##### Expected Behavior

See both me and my peer.

##### Additional Info
(links, images, etc go here)

Different resolutions tried, no success.
Logs here:

https://gist.github.com/pems21/6dcbbe824d02b023b0f94a24510aa9a2

**Comment by zetok** [comment]
Does the other party use qTox as well?

**Comment by pems21** [comment]
Yes, version 1.7.0 of qTox por Windows 64-bits

**Comment by Diadlo** [comment]
If I understand correct, this problem can be related with small bandwidth

**Comment by zetok** [comment]
@pems21 what is your upload bandwidth?

**Comment by sudden6** [comment]
Closed because needed information was not provided
