### ISSUE TITLE
Compiling on macOS does not work.

### ISSUE THREAD

**Issue by Mattel88** [qTox/qTox#4148]
> Last login: Mon Feb  6 10:02:15 on ttys000
> Chibi:~ Chibi$ git clone https://github.com/qTox/qTox.git
> Cloning into 'qTox'...
> remote: Counting objects: 36910, done.
> remote: Total 36910 (delta 0), reused 0 (delta 0), pack-reused 36910
> Receiving objects: 100% (36910/36910), 24.26 MiB | 2.75 MiB/s, done.
> Resolving deltas: 100% (26410/26410), done.
> Chibi:~ Chibi$ clear
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> Chibi:~ Chibi$ /Users/Chibi/qTox/osx/qTox-Mac-Deployer-ULTIMATE.sh -i
> 
> ==============================
> 
> This script will install the necessary applications and libraries needed to compile qTox properly.
> 
> Note that this is not a 100 percent automated install it just helps simplify the process for less experienced or lazy users.
> Press any key to continue or Ctrl+C to exit...
> 
> Homebrew already installed!
> 
> Updating brew formulas ...
> Already up-to-date.
> 
> Getting home brew formulas ...
> Warning: git-2.11.1 already installed
> Warning: wget-1.18 already installed
> Warning: libtool-2.4.6_1 already installed
> Warning: autoconf-2.69 already installed
> Warning: automake-1.15 already installed
> Warning: pkg-config-0.29.1_2 already installed
> Warning: check-0.10.0 already installed
> Warning: libvpx-1.6.1 already installed
> Warning: opus-1.1.4 already installed
> Warning: libsodium-1.0.11 already installed
> 
> Starting git repo checks ...
> 
> Cloning Toxcore git ... 
> Cloning into '/Users/Chibi/toxcore'...
> remote: Counting objects: 260, done.
> remote: Compressing objects: 100% (251/251), done.
> remote: Total 260 (delta 14), reused 81 (delta 4), pack-reused 0
> Receiving objects: 100% (260/260), 498.75 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (14/14), done.
> Note: checking out '7d2f2e4607080ebf5155b43050c62af4f14b9c88'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
>   git checkout -b <new-branch-name>
> 
> 
> qTox git repo already in place !
> Already up-to-date.
> 
> If all went well you should now have all the tools needed to compile qTox!
> Would you like to install toxcore now? [y/N] y
> Starting Toxcore build and install
> Now working in: /Users/Chibi/toxcore
> glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'configure_aux'.
> glibtoolize: copying file 'configure_aux/ltmain.sh'
> glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
> glibtoolize: copying file 'm4/libtool.m4'
> glibtoolize: copying file 'm4/ltoptions.m4'
> glibtoolize: copying file 'm4/ltsugar.m4'
> glibtoolize: copying file 'm4/ltversion.m4'
> glibtoolize: copying file 'm4/lt~obsolete.m4'
> configure.ac:287: installing 'configure_aux/ar-lib'
> configure.ac:208: installing 'configure_aux/compile'
> configure.ac:288: installing 'configure_aux/config.guess'
> configure.ac:288: installing 'configure_aux/config.sub'
> configure.ac:9: installing 'configure_aux/install-sh'
> configure.ac:9: installing 'configure_aux/missing'
> build/Makefile.am: installing 'configure_aux/depcomp'
> parallel-tests: installing 'configure_aux/test-driver'
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... configure_aux/install-sh -c -d
> checking for gawk... no
> checking for mawk... no
> checking for nawk... no
> checking for awk... awk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking whether UID '501' is supported by ustar format... yes
> checking whether GID '20' is supported by ustar format... yes
> checking how to create a ustar tar archive... gnutar
> checking whether make supports nested variables... (cached) yes
> checking for pkg-config... /usr/local/bin/pkg-config
> checking pkg-config is at least version 0.9.0... yes
> checking for style of include used by make... GNU
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc understands -c and -o together... yes
> checking dependency style of gcc... gcc3
> checking how to run the C preprocessor... gcc -E
> checking for grep that handles long lines and -e... /usr/bin/grep
> checking for egrep... /usr/bin/grep -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking linux/version.h usability... no
> checking linux/version.h presence... no
> checking for linux/version.h... no
> checking for Linux epoll(7) interface... no
> configure: will search for libsodium header files in /usr/local/Cellar/libsodium//1.0.11/include/
> configure: will search for libsodium libraries in /usr/local/Cellar/libsodium//1.0.11/lib/
> checking for gcc... (cached) gcc
> checking whether we are using the GNU C compiler... (cached) yes
> checking whether gcc accepts -g... (cached) yes
> checking for gcc option to accept ISO C89... (cached) none needed
> checking whether gcc understands -c and -o together... (cached) yes
> checking dependency style of gcc... (cached) gcc3
> checking for ar... ar
> checking the archiver (ar) interface... ar
> checking build system type... x86_64-apple-darwin16.4.0
> checking host system type... x86_64-apple-darwin16.4.0
> checking how to print strings... printf
> checking for a sed that does not truncate output... /usr/bin/sed
> checking for fgrep... /usr/bin/grep -F
> checking for ld used by gcc... /Library/Developer/CommandLineTools/usr/bin/ld
> checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
> checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
> checking the name lister (/usr/bin/nm -B) interface... BSD nm
> checking whether ln -s works... yes
> checking the maximum length of command line arguments... 196608
> checking how to convert x86_64-apple-darwin16.4.0 file names to x86_64-apple-darwin16.4.0 format... func_convert_file_noop
> checking how to convert x86_64-apple-darwin16.4.0 file names to toolchain format... func_convert_file_noop
> checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
> checking for objdump... objdump
> checking how to recognize dependent libraries... pass_all
> checking for dlltool... dlltool
> checking how to associate runtime and link libraries... printf %s\n
> checking for archiver @FILE support... no
> checking for strip... strip
> checking for ranlib... ranlib
> checking command to parse /usr/bin/nm -B output from gcc object... ok
> checking for sysroot... no
> checking for a working dd... /bin/dd
> checking how to truncate binary pipes... /bin/dd bs=4096 count=1
> checking for mt... no
> checking if : is a manifest tool... no
> checking for dsymutil... dsymutil
> checking for nmedit... nmedit
> checking for lipo... lipo
> checking for otool... otool
> checking for otool64... no
> checking for -single_module linker flag... yes
> checking for -exported_symbols_list linker flag... yes
> checking for -force_load linker flag... yes
> checking for dlfcn.h... yes
> checking for objdir... .libs
> checking if gcc supports -fno-rtti -fno-exceptions... yes
> checking for gcc option to produce PIC... -fno-common -DPIC
> checking if gcc PIC flag -fno-common -DPIC works... yes
> checking if gcc static flag -static works... no
> checking if gcc supports -c -o file.o... yes
> checking if gcc supports -c -o file.o... (cached) yes
> checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
> checking dynamic linker characteristics... darwin16.4.0 dyld
> checking how to hardcode library paths into programs... immediate
> checking whether stripping libraries is possible... yes
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... yes
> checking whether to build static libraries... yes
> checking for LIBSODIUM... yes
> checking arpa/inet.h usability... yes
> checking arpa/inet.h presence... yes
> checking for arpa/inet.h... yes
> checking fcntl.h usability... yes
> checking fcntl.h presence... yes
> checking for fcntl.h... yes
> checking netdb.h usability... yes
> checking netdb.h presence... yes
> checking for netdb.h... yes
> checking netinet/in.h usability... yes
> checking netinet/in.h presence... yes
> checking for netinet/in.h... yes
> checking for stdint.h... (cached) yes
> checking for stdlib.h... (cached) yes
> checking for string.h... (cached) yes
> checking sys/socket.h usability... yes
> checking sys/socket.h presence... yes
> checking for sys/socket.h... yes
> checking sys/time.h usability... yes
> checking sys/time.h presence... yes
> checking for sys/time.h... yes
> checking for unistd.h... (cached) yes
> checking for stdbool.h that conforms to C99... yes
> checking for _Bool... yes
> checking for int16_t... yes
> checking for int32_t... yes
> checking for pid_t... yes
> checking for size_t... yes
> checking for uint16_t... yes
> checking for uint32_t... yes
> checking for uint64_t... yes
> checking for uint8_t... yes
> checking whether byte ordering is bigendian... no
> checking vfork.h usability... no
> checking vfork.h presence... no
> checking for vfork.h... no
> checking for fork... yes
> checking for vfork... yes
> checking for working fork... yes
> checking for working vfork... (cached) yes
> checking for gettimeofday... yes
> checking for memset... yes
> checking for socket... yes
> checking for strchr... yes
> checking for malloc... yes
> checking whether pthreads work with -pthread... yes
> checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
> checking if more special flags are required for pthreads... -D_THREAD_SAFE
> checking for PTHREAD_PRIO_INHERIT... yes
> checking for pthread_self in -lpthread... yes
> checking for OPUS... yes
> checking for VPX... yes
> checking for CHECK... yes
> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating build/Makefile
> config.status: creating libtoxcore.pc
> config.status: creating tox.spec
> config.status: creating libtoxav.pc
> config.status: creating config.h
> config.status: executing depfiles commands
> config.status: executing libtool commands
> 
> Compiling toxcore.
> ../toxcore/Messenger.c:2214:28: warning: comparison of constant 256 with
>       expression of type 'uint8_t' (aka 'unsigned char') is always false
>       [-Wtautological-constant-out-of-range-compare]
>             if (filenumber >= MAX_CONCURRENT_FILE_PIPES) {
>                 ~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~
> ../toxcore/Messenger.c:2274:28: warning: comparison of constant 256 with
>       expression of type 'uint8_t' (aka 'unsigned char') is always false
>       [-Wtautological-constant-out-of-range-compare]
>             if (filenumber >= MAX_CONCURRENT_FILE_PIPES) {
>                 ~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~
> ../toxcore/Messenger.c:2292:28: warning: comparison of constant 256 with
>       expression of type 'uint8_t' (aka 'unsigned char') is always false
>       [-Wtautological-constant-out-of-range-compare]
>             if (filenumber >= MAX_CONCURRENT_FILE_PIPES) {
>                 ~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~
> 3 warnings generated.
> clang: warning: argument unused during compilation: '-pthread'
> clang: warning: argument unused during compilation: '-pthread'
> clang: warning: argument unused during compilation: '-pthread'
> clang: warning: argument unused during compilation: '-pthread'
> clang: warning: argument unused during compilation: '-pthread'
> clang: warning: argument unused during compilation: '-pthread'
> clang: warning: argument unused during compilation: '-pthread'
> clang: warning: argument unused during compilation: '-pthread'
> clang: warning: argument unused during compilation: '-pthread'
> clang: warning: argument unused during compilation: '-pthread'
> clang: warning: argument unused during compilation: '-pthread'
> clang: warning: argument unused during compilation: '-pthread'
> clang: warning: argument unused during compilation: '-pthread'
> clang: warning: argument unused during compilation: '-pthread'
> clang: warning: argument unused during compilation: '-pthread'
> 
> Installing toxcore.
> Warning: cmake-3.7.2 already installed
> Warning: ffmpeg-3.2.2 already installed
> Warning: qrencode-3.4.4 already installed
> Warning: qt5 is a keg-only and another version is linked to opt.
> Use `brew install --force` if you want to install this version
> Warning: sqlcipher-3.4.0 already installed
> Password:
> Creating directories…
> Copying libraries…
> /usr/local/lib/libsodium.18.dylib -> libs/lib/libsodium.18.dylib
> /usr/local/lib/libsodium.a -> libs/lib/libsodium.a
> /usr/local/lib/libsodium.dylib -> libs/lib/libsodium.dylib
> /usr/local/lib/libvpx.a -> libs/lib/libvpx.a
> /usr/local/lib/libopus.0.dylib -> libs/lib/libopus.0.dylib
> /usr/local/lib/libopus.a -> libs/lib/libopus.a
> /usr/local/lib/libopus.dylib -> libs/lib/libopus.dylib
> /usr/local/lib/libavcodec.57.64.101.dylib -> libs/lib/libavcodec.57.64.101.dylib
> /usr/local/lib/libavcodec.57.dylib -> libs/lib/libavcodec.57.dylib
> /usr/local/lib/libavcodec.a -> libs/lib/libavcodec.a
> /usr/local/lib/libavcodec.dylib -> libs/lib/libavcodec.dylib
> /usr/local/lib/libavdevice.57.1.100.dylib -> libs/lib/libavdevice.57.1.100.dylib
> /usr/local/lib/libavdevice.57.dylib -> libs/lib/libavdevice.57.dylib
> /usr/local/lib/libavdevice.a -> libs/lib/libavdevice.a
> /usr/local/lib/libavdevice.dylib -> libs/lib/libavdevice.dylib
> /usr/local/lib/libavfilter.6.65.100.dylib -> libs/lib/libavfilter.6.65.100.dylib
> /usr/local/lib/libavfilter.6.dylib -> libs/lib/libavfilter.6.dylib
> /usr/local/lib/libavfilter.a -> libs/lib/libavfilter.a
> /usr/local/lib/libavfilter.dylib -> libs/lib/libavfilter.dylib
> /usr/local/lib/libavformat.57.56.100.dylib -> libs/lib/libavformat.57.56.100.dylib
> /usr/local/lib/libavformat.57.dylib -> libs/lib/libavformat.57.dylib
> /usr/local/lib/libavformat.a -> libs/lib/libavformat.a
> /usr/local/lib/libavformat.dylib -> libs/lib/libavformat.dylib
> /usr/local/lib/libavresample.3.1.0.dylib -> libs/lib/libavresample.3.1.0.dylib
> /usr/local/lib/libavresample.3.dylib -> libs/lib/libavresample.3.dylib
> /usr/local/lib/libavresample.a -> libs/lib/libavresample.a
> /usr/local/lib/libavresample.dylib -> libs/lib/libavresample.dylib
> /usr/local/lib/libavutil.55.34.100.dylib -> libs/lib/libavutil.55.34.100.dylib
> /usr/local/lib/libavutil.55.dylib -> libs/lib/libavutil.55.dylib
> /usr/local/lib/libavutil.a -> libs/lib/libavutil.a
> /usr/local/lib/libavutil.dylib -> libs/lib/libavutil.dylib
> /usr/local/lib/libswscale.4.2.100.dylib -> libs/lib/libswscale.4.2.100.dylib
> /usr/local/lib/libswscale.4.dylib -> libs/lib/libswscale.4.dylib
> /usr/local/lib/libswscale.a -> libs/lib/libswscale.a
> /usr/local/lib/libswscale.dylib -> libs/lib/libswscale.dylib
> /usr/local/lib/libqrencode.3.dylib -> libs/lib/libqrencode.3.dylib
> /usr/local/lib/libqrencode.dylib -> libs/lib/libqrencode.dylib
> /usr/local/lib/libsqlcipher.0.dylib -> libs/lib/libsqlcipher.0.dylib
> /usr/local/lib/libsqlcipher.a -> libs/lib/libsqlcipher.a
> /usr/local/lib/libsqlcipher.dylib -> libs/lib/libsqlcipher.dylib
> Copying include files…
> /usr/local/include/vpx -> libs/include/vpx
> /usr/local/include/vpx/vp8.h -> libs/include/vpx/vp8.h
> /usr/local/include/vpx/vp8cx.h -> libs/include/vpx/vp8cx.h
> /usr/local/include/vpx/vp8dx.h -> libs/include/vpx/vp8dx.h
> /usr/local/include/vpx/vpx_codec.h -> libs/include/vpx/vpx_codec.h
> /usr/local/include/vpx/vpx_decoder.h -> libs/include/vpx/vpx_decoder.h
> /usr/local/include/vpx/vpx_encoder.h -> libs/include/vpx/vpx_encoder.h
> /usr/local/include/vpx/vpx_frame_buffer.h -> libs/include/vpx/vpx_frame_buffer.h
> /usr/local/include/vpx/vpx_image.h -> libs/include/vpx/vpx_image.h
> /usr/local/include/vpx/vpx_integer.h -> libs/include/vpx/vpx_integer.h
> /usr/local/include/sodium -> libs/include/sodium
> /usr/local/include/sodium/core.h -> libs/include/sodium/core.h
> /usr/local/include/sodium/crypto_aead_aes256gcm.h -> libs/include/sodium/crypto_aead_aes256gcm.h
> /usr/local/include/sodium/crypto_aead_chacha20poly1305.h -> libs/include/sodium/crypto_aead_chacha20poly1305.h
> /usr/local/include/sodium/crypto_auth.h -> libs/include/sodium/crypto_auth.h
> /usr/local/include/sodium/crypto_auth_hmacsha256.h -> libs/include/sodium/crypto_auth_hmacsha256.h
> /usr/local/include/sodium/crypto_auth_hmacsha512.h -> libs/include/sodium/crypto_auth_hmacsha512.h
> /usr/local/include/sodium/crypto_auth_hmacsha512256.h -> libs/include/sodium/crypto_auth_hmacsha512256.h
> /usr/local/include/sodium/crypto_box.h -> libs/include/sodium/crypto_box.h
> /usr/local/include/sodium/crypto_box_curve25519xsalsa20poly1305.h -> libs/include/sodium/crypto_box_curve25519xsalsa20poly1305.h
> /usr/local/include/sodium/crypto_core_hchacha20.h -> libs/include/sodium/crypto_core_hchacha20.h
> /usr/local/include/sodium/crypto_core_hsalsa20.h -> libs/include/sodium/crypto_core_hsalsa20.h
> /usr/local/include/sodium/crypto_core_salsa20.h -> libs/include/sodium/crypto_core_salsa20.h
> /usr/local/include/sodium/crypto_core_salsa2012.h -> libs/include/sodium/crypto_core_salsa2012.h
> /usr/local/include/sodium/crypto_core_salsa208.h -> libs/include/sodium/crypto_core_salsa208.h
> /usr/local/include/sodium/crypto_generichash.h -> libs/include/sodium/crypto_generichash.h
> /usr/local/include/sodium/crypto_generichash_blake2b.h -> libs/include/sodium/crypto_generichash_blake2b.h
> /usr/local/include/sodium/crypto_hash.h -> libs/include/sodium/crypto_hash.h
> /usr/local/include/sodium/crypto_hash_sha256.h -> libs/include/sodium/crypto_hash_sha256.h
> /usr/local/include/sodium/crypto_hash_sha512.h -> libs/include/sodium/crypto_hash_sha512.h
> /usr/local/include/sodium/crypto_int32.h -> libs/include/sodium/crypto_int32.h
> /usr/local/include/sodium/crypto_int64.h -> libs/include/sodium/crypto_int64.h
> /usr/local/include/sodium/crypto_onetimeauth.h -> libs/include/sodium/crypto_onetimeauth.h
> /usr/local/include/sodium/crypto_onetimeauth_poly1305.h -> libs/include/sodium/crypto_onetimeauth_poly1305.h
> /usr/local/include/sodium/crypto_pwhash.h -> libs/include/sodium/crypto_pwhash.h
> /usr/local/include/sodium/crypto_pwhash_argon2i.h -> libs/include/sodium/crypto_pwhash_argon2i.h
> /usr/local/include/sodium/crypto_pwhash_scryptsalsa208sha256.h -> libs/include/sodium/crypto_pwhash_scryptsalsa208sha256.h
> /usr/local/include/sodium/crypto_scalarmult.h -> libs/include/sodium/crypto_scalarmult.h
> /usr/local/include/sodium/crypto_scalarmult_curve25519.h -> libs/include/sodium/crypto_scalarmult_curve25519.h
> /usr/local/include/sodium/crypto_secretbox.h -> libs/include/sodium/crypto_secretbox.h
> /usr/local/include/sodium/crypto_secretbox_xsalsa20poly1305.h -> libs/include/sodium/crypto_secretbox_xsalsa20poly1305.h
> /usr/local/include/sodium/crypto_shorthash.h -> libs/include/sodium/crypto_shorthash.h
> /usr/local/include/sodium/crypto_shorthash_siphash24.h -> libs/include/sodium/crypto_shorthash_siphash24.h
> /usr/local/include/sodium/crypto_sign.h -> libs/include/sodium/crypto_sign.h
> /usr/local/include/sodium/crypto_sign_ed25519.h -> libs/include/sodium/crypto_sign_ed25519.h
> /usr/local/include/sodium/crypto_sign_edwards25519sha512batch.h -> libs/include/sodium/crypto_sign_edwards25519sha512batch.h
> /usr/local/include/sodium/crypto_stream.h -> libs/include/sodium/crypto_stream.h
> /usr/local/include/sodium/crypto_stream_aes128ctr.h -> libs/include/sodium/crypto_stream_aes128ctr.h
> /usr/local/include/sodium/crypto_stream_chacha20.h -> libs/include/sodium/crypto_stream_chacha20.h
> /usr/local/include/sodium/crypto_stream_salsa20.h -> libs/include/sodium/crypto_stream_salsa20.h
> /usr/local/include/sodium/crypto_stream_salsa2012.h -> libs/include/sodium/crypto_stream_salsa2012.h
> /usr/local/include/sodium/crypto_stream_salsa208.h -> libs/include/sodium/crypto_stream_salsa208.h
> /usr/local/include/sodium/crypto_stream_xsalsa20.h -> libs/include/sodium/crypto_stream_xsalsa20.h
> /usr/local/include/sodium/crypto_uint16.h -> libs/include/sodium/crypto_uint16.h
> /usr/local/include/sodium/crypto_uint32.h -> libs/include/sodium/crypto_uint32.h
> /usr/local/include/sodium/crypto_uint64.h -> libs/include/sodium/crypto_uint64.h
> /usr/local/include/sodium/crypto_uint8.h -> libs/include/sodium/crypto_uint8.h
> /usr/local/include/sodium/crypto_verify_16.h -> libs/include/sodium/crypto_verify_16.h
> /usr/local/include/sodium/crypto_verify_32.h -> libs/include/sodium/crypto_verify_32.h
> /usr/local/include/sodium/crypto_verify_64.h -> libs/include/sodium/crypto_verify_64.h
> /usr/local/include/sodium/export.h -> libs/include/sodium/export.h
> /usr/local/include/sodium/randombytes.h -> libs/include/sodium/randombytes.h
> /usr/local/include/sodium/randombytes_salsa20_random.h -> libs/include/sodium/randombytes_salsa20_random.h
> /usr/local/include/sodium/randombytes_sysrandom.h -> libs/include/sodium/randombytes_sysrandom.h
> /usr/local/include/sodium/runtime.h -> libs/include/sodium/runtime.h
> /usr/local/include/sodium/utils.h -> libs/include/sodium/utils.h
> /usr/local/include/sodium/version.h -> libs/include/sodium/version.h
> /usr/local/include/sodium.h -> libs/include/sodium.h
> /usr/local/include/qrencode.h -> libs/include/qrencode.h
> /usr/local/include/libavcodec -> libs/include/libavcodec
> /usr/local/include/libavcodec/avcodec.h -> libs/include/libavcodec/avcodec.h
> /usr/local/include/libavcodec/avdct.h -> libs/include/libavcodec/avdct.h
> /usr/local/include/libavcodec/avfft.h -> libs/include/libavcodec/avfft.h
> /usr/local/include/libavcodec/d3d11va.h -> libs/include/libavcodec/d3d11va.h
> /usr/local/include/libavcodec/dirac.h -> libs/include/libavcodec/dirac.h
> /usr/local/include/libavcodec/dv_profile.h -> libs/include/libavcodec/dv_profile.h
> /usr/local/include/libavcodec/dxva2.h -> libs/include/libavcodec/dxva2.h
> /usr/local/include/libavcodec/jni.h -> libs/include/libavcodec/jni.h
> /usr/local/include/libavcodec/mediacodec.h -> libs/include/libavcodec/mediacodec.h
> /usr/local/include/libavcodec/qsv.h -> libs/include/libavcodec/qsv.h
> /usr/local/include/libavcodec/vaapi.h -> libs/include/libavcodec/vaapi.h
> /usr/local/include/libavcodec/vda.h -> libs/include/libavcodec/vda.h
> /usr/local/include/libavcodec/vdpau.h -> libs/include/libavcodec/vdpau.h
> /usr/local/include/libavcodec/version.h -> libs/include/libavcodec/version.h
> /usr/local/include/libavcodec/videotoolbox.h -> libs/include/libavcodec/videotoolbox.h
> /usr/local/include/libavcodec/vorbis_parser.h -> libs/include/libavcodec/vorbis_parser.h
> /usr/local/include/libavcodec/xvmc.h -> libs/include/libavcodec/xvmc.h
> /usr/local/include/libavdevice -> libs/include/libavdevice
> /usr/local/include/libavdevice/avdevice.h -> libs/include/libavdevice/avdevice.h
> /usr/local/include/libavdevice/version.h -> libs/include/libavdevice/version.h
> /usr/local/include/libavfilter -> libs/include/libavfilter
> /usr/local/include/libavfilter/avfilter.h -> libs/include/libavfilter/avfilter.h
> /usr/local/include/libavfilter/avfiltergraph.h -> libs/include/libavfilter/avfiltergraph.h
> /usr/local/include/libavfilter/buffersink.h -> libs/include/libavfilter/buffersink.h
> /usr/local/include/libavfilter/buffersrc.h -> libs/include/libavfilter/buffersrc.h
> /usr/local/include/libavfilter/version.h -> libs/include/libavfilter/version.h
> /usr/local/include/libavformat -> libs/include/libavformat
> /usr/local/include/libavformat/avformat.h -> libs/include/libavformat/avformat.h
> /usr/local/include/libavformat/avio.h -> libs/include/libavformat/avio.h
> /usr/local/include/libavformat/version.h -> libs/include/libavformat/version.h
> /usr/local/include/libavresample -> libs/include/libavresample
> /usr/local/include/libavresample/avresample.h -> libs/include/libavresample/avresample.h
> /usr/local/include/libavresample/version.h -> libs/include/libavresample/version.h
> /usr/local/include/libavutil -> libs/include/libavutil
> /usr/local/include/libavutil/adler32.h -> libs/include/libavutil/adler32.h
> /usr/local/include/libavutil/aes.h -> libs/include/libavutil/aes.h
> /usr/local/include/libavutil/aes_ctr.h -> libs/include/libavutil/aes_ctr.h
> /usr/local/include/libavutil/attributes.h -> libs/include/libavutil/attributes.h
> /usr/local/include/libavutil/audio_fifo.h -> libs/include/libavutil/audio_fifo.h
> /usr/local/include/libavutil/avassert.h -> libs/include/libavutil/avassert.h
> /usr/local/include/libavutil/avconfig.h -> libs/include/libavutil/avconfig.h
> /usr/local/include/libavutil/avstring.h -> libs/include/libavutil/avstring.h
> /usr/local/include/libavutil/avutil.h -> libs/include/libavutil/avutil.h
> /usr/local/include/libavutil/base64.h -> libs/include/libavutil/base64.h
> /usr/local/include/libavutil/blowfish.h -> libs/include/libavutil/blowfish.h
> /usr/local/include/libavutil/bprint.h -> libs/include/libavutil/bprint.h
> /usr/local/include/libavutil/bswap.h -> libs/include/libavutil/bswap.h
> /usr/local/include/libavutil/buffer.h -> libs/include/libavutil/buffer.h
> /usr/local/include/libavutil/camellia.h -> libs/include/libavutil/camellia.h
> /usr/local/include/libavutil/cast5.h -> libs/include/libavutil/cast5.h
> /usr/local/include/libavutil/channel_layout.h -> libs/include/libavutil/channel_layout.h
> /usr/local/include/libavutil/common.h -> libs/include/libavutil/common.h
> /usr/local/include/libavutil/cpu.h -> libs/include/libavutil/cpu.h
> /usr/local/include/libavutil/crc.h -> libs/include/libavutil/crc.h
> /usr/local/include/libavutil/des.h -> libs/include/libavutil/des.h
> /usr/local/include/libavutil/dict.h -> libs/include/libavutil/dict.h
> /usr/local/include/libavutil/display.h -> libs/include/libavutil/display.h
> /usr/local/include/libavutil/downmix_info.h -> libs/include/libavutil/downmix_info.h
> /usr/local/include/libavutil/error.h -> libs/include/libavutil/error.h
> /usr/local/include/libavutil/eval.h -> libs/include/libavutil/eval.h
> /usr/local/include/libavutil/ffversion.h -> libs/include/libavutil/ffversion.h
> /usr/local/include/libavutil/fifo.h -> libs/include/libavutil/fifo.h
> /usr/local/include/libavutil/file.h -> libs/include/libavutil/file.h
> /usr/local/include/libavutil/frame.h -> libs/include/libavutil/frame.h
> /usr/local/include/libavutil/hash.h -> libs/include/libavutil/hash.h
> /usr/local/include/libavutil/hmac.h -> libs/include/libavutil/hmac.h
> /usr/local/include/libavutil/hwcontext.h -> libs/include/libavutil/hwcontext.h
> /usr/local/include/libavutil/hwcontext_cuda.h -> libs/include/libavutil/hwcontext_cuda.h
> /usr/local/include/libavutil/hwcontext_dxva2.h -> libs/include/libavutil/hwcontext_dxva2.h
> /usr/local/include/libavutil/hwcontext_qsv.h -> libs/include/libavutil/hwcontext_qsv.h
> /usr/local/include/libavutil/hwcontext_vaapi.h -> libs/include/libavutil/hwcontext_vaapi.h
> /usr/local/include/libavutil/hwcontext_vdpau.h -> libs/include/libavutil/hwcontext_vdpau.h
> /usr/local/include/libavutil/imgutils.h -> libs/include/libavutil/imgutils.h
> /usr/local/include/libavutil/intfloat.h -> libs/include/libavutil/intfloat.h
> /usr/local/include/libavutil/intreadwrite.h -> libs/include/libavutil/intreadwrite.h
> /usr/local/include/libavutil/lfg.h -> libs/include/libavutil/lfg.h
> /usr/local/include/libavutil/log.h -> libs/include/libavutil/log.h
> /usr/local/include/libavutil/lzo.h -> libs/include/libavutil/lzo.h
> /usr/local/include/libavutil/macros.h -> libs/include/libavutil/macros.h
> /usr/local/include/libavutil/mastering_display_metadata.h -> libs/include/libavutil/mastering_display_metadata.h
> /usr/local/include/libavutil/mathematics.h -> libs/include/libavutil/mathematics.h
> /usr/local/include/libavutil/md5.h -> libs/include/libavutil/md5.h
> /usr/local/include/libavutil/mem.h -> libs/include/libavutil/mem.h
> /usr/local/include/libavutil/motion_vector.h -> libs/include/libavutil/motion_vector.h
> /usr/local/include/libavutil/murmur3.h -> libs/include/libavutil/murmur3.h
> /usr/local/include/libavutil/opencl.h -> libs/include/libavutil/opencl.h
> /usr/local/include/libavutil/opt.h -> libs/include/libavutil/opt.h
> /usr/local/include/libavutil/parseutils.h -> libs/include/libavutil/parseutils.h
> /usr/local/include/libavutil/pixdesc.h -> libs/include/libavutil/pixdesc.h
> /usr/local/include/libavutil/pixelutils.h -> libs/include/libavutil/pixelutils.h
> /usr/local/include/libavutil/pixfmt.h -> libs/include/libavutil/pixfmt.h
> /usr/local/include/libavutil/random_seed.h -> libs/include/libavutil/random_seed.h
> /usr/local/include/libavutil/rational.h -> libs/include/libavutil/rational.h
> /usr/local/include/libavutil/rc4.h -> libs/include/libavutil/rc4.h
> /usr/local/include/libavutil/replaygain.h -> libs/include/libavutil/replaygain.h
> /usr/local/include/libavutil/ripemd.h -> libs/include/libavutil/ripemd.h
> /usr/local/include/libavutil/samplefmt.h -> libs/include/libavutil/samplefmt.h
> /usr/local/include/libavutil/sha.h -> libs/include/libavutil/sha.h
> /usr/local/include/libavutil/sha512.h -> libs/include/libavutil/sha512.h
> /usr/local/include/libavutil/stereo3d.h -> libs/include/libavutil/stereo3d.h
> /usr/local/include/libavutil/tea.h -> libs/include/libavutil/tea.h
> /usr/local/include/libavutil/threadmessage.h -> libs/include/libavutil/threadmessage.h
> /usr/local/include/libavutil/time.h -> libs/include/libavutil/time.h
> /usr/local/include/libavutil/timecode.h -> libs/include/libavutil/timecode.h
> /usr/local/include/libavutil/timestamp.h -> libs/include/libavutil/timestamp.h
> /usr/local/include/libavutil/tree.h -> libs/include/libavutil/tree.h
> /usr/local/include/libavutil/twofish.h -> libs/include/libavutil/twofish.h
> /usr/local/include/libavutil/version.h -> libs/include/libavutil/version.h
> /usr/local/include/libavutil/xtea.h -> libs/include/libavutil/xtea.h
> /usr/local/include/libswscale -> libs/include/libswscale
> /usr/local/include/libswscale/swscale.h -> libs/include/libswscale/swscale.h
> /usr/local/include/libswscale/version.h -> libs/include/libswscale/version.h
> /usr/local/include/sqlcipher -> libs/include/sqlcipher
> /usr/local/include/sqlcipher/sqlite3.h -> libs/include/sqlcipher/sqlite3.h
> /usr/local/include/sqlcipher/sqlite3ext.h -> libs/include/sqlcipher/sqlite3ext.h
> Done.
> Chibi:~ Chibi$ 
>

**Comment by sudden6** [comment]
You have to call the script again with the `-b` option. Call it with `-h` for help.

**Comment by Mattel88** [comment]
Works all. I forgot to -b 

Keep up the good work. Worked perfectly.
