### ISSUE TITLE
[question] - Clearing chat window

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#415]
What do you think about it?
![qtox-clearing](https://cloud.githubusercontent.com/assets/2544251/4579177/96b4e0d8-4fca-11e4-8c7f-b2ddfdc5154b.png)

**Comment by krepa098** [comment]
How about using /clear? It's probably easier to implement. But I don't really see why I should clear my chat at all. Usecases?

**Comment by zetok** [comment]
There should be a way to just put messages "away", out of users' sight. User still would be able to access messages after scrolling "up" long enough, although messages wouldn't be loaded without a need.

Perhaps there should be an option to clear chat without using keybindings from chat, and there should be option to delete chat history in options (or somewhere else where it should be).

That with implied chat history, which currently doesn't exist.

@krepa098 
Well, as for use case..
You chat with someone (qTox should have support for inline images at that point), and someone during conversation sends you image that you may not want to be associated with you by your work colleagues…

**Comment by zetok** [comment]
BTW, things like `/muhcommand`, except for `/me` should be avoided whenever possible IMHO.

The only feature they present is destroying user experience. User wants to send to contact `/clear` and it removes whole chat history -.-

**Comment by dubslow** [comment]
I'm with zetok on this one, Ctrl L is fine (though I might nitpick with the way the instructions are presented. Maybe a tooltip would be better?)

**Comment by agilob** [comment]
@dubslow in the later release I can write another setting tab for keyboard short-cuts (I want to implement more of them, like Ctrl+O to answer audio-call when calling or call when on chat, Ctrl+P video-call), but this would require "vertical tabs" instead of bottom horizontal. I might add it to my todo list, unless you anyone has some suggestions.

Ctrl+L clears chat in Pidgin and Gajim, so I [copied this behaviour](https://github.com/agilob/qTox/commit/da2561a6f5cffeba8fc63f5e4bdf8030a4f979d2).

**Comment by agilob** [comment]
Implemented, PR awaiting. Closing.
