### ISSUE TITLE
windows cross compilation fails with cmake

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#4150]
It passes with qmake.

https://gist.github.com/towlie/e52e58bd66a83f362dafce8e0c48fc9a

**Comment by Diadlo** [comment]
You have problem with [toxcore](https://github.com/TokTok/c-toxcore) build

**Comment by towlie** [comment]
So you want to tell me that toxcore uses libsqlcipher.
For me it looks like cmake cannot handle these static libs.
Was cmake ever tested in Jenkins for Windows builds? I would like to see that.

**Comment by DX37** [comment]
> Was cmake ever tested in Jenkins for Windows builds? I would like to see that.

At [this](https://build.tox.chat/view/qtox/job/qTox_build_windows_x86_release/1022/consoleFull) moment - [nope](https://build.tox.chat/job/qtox-build-script_src/).

**Comment by Diadlo** [comment]
Is problem still there?

**Comment by towlie** [comment]
Yes, but I assume the reason is a broken cmake from my build environment "mxe". 
The error is the same.
This is the cmakecache: https://gist.github.com/towlie/d375a68dd6293f1b1030490ee12f042f

**Comment by towlie** [comment]
Issue solved with https://github.com/qTox/qTox/pull/4504
But only when you compile c-toxcore with cmake? I see that the autotools variant produces less libs than 
 the cmake variant.
qmake qTox is also incompatible with the c-toxcore libs created with cmake.
