### ISSUE TITLE
How does Tox over Tor work?

### ISSUE THREAD

**Issue by Mattel88** [qTox/qTox#4159]
I'm a bit confused because the whole concept of Tox is p2p which connects directly to the other person. How is it possible to run Tox over Tor then? Does it help in order to "hide" your IP?

**Comment by yurivict** [comment]
My understanding is that Tox doesn't register onion addresses. Instead, it keeps the TCP connection to some of the seed hosts, and gets notifications and calls this way. 2 Tox instances in the tor VMs can connect to each other using the seed host as a proxy. Without the onion addresses there is no way to connect directly.

Practically speaking though, I am not convinced Tox doesn't leak your IP address when the proxy is used. I saw somebody claiming it leaks IP.

**Comment by Mattel88** [comment]
If it leaks the IP address even using Tor it is not a solution for me.

**Comment by zetok** [comment]
>I saw somebody claiming it leaks IP.

Yes, internet is full of people who don't know what they're talking about.

**Comment by Mattel88** [comment]
> Yes, internet is full of people who don't know what they're talking about.

So I do not have to worry? Well I'm still a noob and wanted to ask. :)

**Comment by yurivict** [comment]
@Mattel88 If you want to be 100% sure, like with all other networking software, you should run Tox from the virtual machine connected to Tor. This minimizes the exposure to any potential bugs of this nature. Install Whonix on top of VirtualBox - this will do the trick. Tox works fine this way, even though without using onion addresses it often has to use the third host, which is inefficient.

**Comment by yurivict** [comment]
I just did a simple experiment. With 'Enable UDP'=off, 'Proxy type'=SOCKS5, 'Proxy address'=localhost I looked at system calls it makes, and found this:

```
73692: socket(PF_INET,SOCK_DGRAM|SOCK_CLOEXEC,17) = 38 (0x26)
73692: connect(38,{ AF_INET 104.156.104.15:1 },16) = 0 (0x0)
```

This is the UDP socket for the clearnet IP 104.156.104.15. So Tox does leak IP despite the proxy setting.

With the above network settings all connections should go through the proxy, no UDP should be attempted. No IPs besides 127.0.0.1 should appear in the log.

So you should use Whonix to filter these things.

**Comment by fcore117** [comment]
ISP knows your IP and usually most of websites you visit normally every day, if you really fear IP leak then do not add friends in Tox who you do not know. yurivict: file bug raport about that UDP off

**Comment by yurivict** [comment]
No, you are wrong. ISP doesn't know what user does over Tor.

**Comment by yurivict** [comment]
https://github.com/TokTok/c-toxcore/issues/469

**Comment by g4jc** [comment]
The leaks I have seen are caused by bad user configuration.
1) Disable IPv6
2) Disable UDP
3) Set proxy.
4) Still leaks DNS queries, per bug yurvict mentioned, but not other traffic.

Failing to do this, you will definitely leak over IPv6 and UDP.

**Comment by zetok** [comment]
What @g4jc wrote should be added to the [user manual](https://github.com/qTox/qTox/blob/master/doc/user_manual_en.md) / [FAQ](https://github.com/qTox/qTox/wiki/FAQ).

**Comment by soredake** [comment]
@yurivict can you pls test with https://github.com/rofl0r/proxychains-ng?

**Comment by yurivict** [comment]
@soredake qTox seems to work fine with proxychains-ng on FreeBSD.

**Comment by soredake** [comment]
@yurivict no dns leaks?

**Comment by yurivict** [comment]
I don't see DNS leaks with proxychains-ng.

**Comment by soredake** [comment]
So it's worth mention in user manual or FAQ.

**Comment by yurivict** [comment]
Yes, as a workaround.

**Comment by Qwash** [comment]
>  g4jc commented 5 days ago
> 
> The leaks I have seen are caused by bad user configuration.
> 
>     Disable IPv6
>     Disable UDP
>     Set proxy.
>     Still leaks DNS queries, per bug yurvict mentioned, but not other traffic.
> 
> Failing to do this, you will definitely leak over IPv6 and UDP.
> 

Sorry for that but, I didn't understand, disable the UDP result in IP leak or keeping the UDP result in the leak?

**Comment by yurivict** [comment]
This is still a Tox problem, it shouldn't allow UDP when not available.

**Comment by Diadlo** [comment]
Seems question is answered. Thus closing
