### ISSUE TITLE
Error in qTox repositories for Fedora 24 !

### ISSUE THREAD

**Issue by Nokia808** [qTox/qTox#4160]
Hi. I'm new user for Tox. 

I'm on Fedora 24 X64 bit. I added repository for qTox from following site:
https://software.opensuse.org/download.html?project=home%3Aantonbatenev%3Atox&package=qtox
by entering in my terminal following:
dnf config-manager --add-repo http://download.opensuse.org/repositories/home:antonbatenev:tox/Fedora_24/home:antonbatenev:tox.repo

Then I installed qTox. I launched it, then it connected & I got ID & add someone & chat with him O.K

Latter on I discover that my package manager show me individual
![1](https://cloud.githubusercontent.com/assets/25375330/22751566/c72d0fa8-ee2c-11e6-8f61-d1be80b87ad1.png)
![2](https://cloud.githubusercontent.com/assets/25375330/22751571/cd841e00-ee2c-11e6-8969-af7fff3233fa.png)
![3](https://cloud.githubusercontent.com/assets/25375330/22751579/d20dd16e-ee2c-11e6-9de4-64d28bbff67e.png)
![4](https://cloud.githubusercontent.com/assets/25375330/22751585/d7bff90c-ee2c-11e6-96c3-dfe6fea96804.png)

 package of qTox NOT INSTALLED !!

**Comment by sudden6** [comment]
the repository is maintained by @abbat please open an issue there https://github.com/abbat/tox.pkg

Although I don't think this is not a real issue.

**Comment by soul9** [comment]
This repo is not functioning anymore. There is a new frequently updated repo for fedora on copr: https://copr.fedorainfracloud.org/coprs/eclipseo/tox/ . I think it'd be nice if it were documented.

**Comment by heyakyra** [comment]
@soul9 thank you so much! An official repo would be great, or as you suggest official documentation

**Comment by eclipseo** [comment]
@soul9: I plan to add it to RPMFusion, where it would be available for most users directly.

**Comment by soul9** [comment]
thanks for your repo. would be awesome in rpmfusion!

**Comment by Nokia808** [comment]
@soul9 

Hi. Thank you for your very hard efforts ! But it seem that we will wait for very long time till qTox added to RPFusion repositories ......

For that I have following suggestion:

1) why you do not make AppImage for qTox ?? It will be much easer & will cover most if not all Linux distros. AppImage which include ALL needed dependencies will be very great ! Please notice that RetroShare started to distribute itself as AppImage ...........

Please if you accept this suggestion then make AppImage include ALL NEEDED DEPENDENCIES for qTox & I think that they are not so numerous but in fact few ......... 

2) why you do not use snap for packaging qTox ?? This will make qTox available for most famous Linux distros: Debian + Debian based, Ubuntu & Ubuntu based, Fedora, OpenSUSE, CentOS .....

Best.

**Comment by heyakyra** [comment]
there is already requests for flatpak #3879 and appimage #4874

**Comment by tox-user** [comment]
@Nokia808 we don't have a maintainer that would create and update those packages. Currently the only way to install qTox is to compile it yourself (which is not that difficult by the way).

**Comment by Nokia808** [comment]
Hi again ! I'm not sure if I was clear in what I was like to say or not.

In fact I meant the following: if you have no packagers who create ALL these packageS (.deb, .rpm, snap, ....), you can LIMIT process (from YOUR SIDE) to just creating & updating AppImage package only.

Unfortunately I'm not programmer to help in this regard. But I know - please correct to me - creating & maintaining AppImage is easy process. Recently, QPDF create AppImage. Please see this link:
https://github.com/qpdf/qpdf/issues/160

**Comment by sudden6** [comment]
@Nokia808 unfortunately all of us are more C++ programmers and not experienced in creating appimage or flatpak packages, so "easy process" still will take a lot of work.

If you (or someone else) manage to build scripts to generate such packages we'll happily accept them in the repo though :)

**Comment by sudden6** [comment]
We have appimages and flatpak now.

**Comment by tox-user** [comment]
And qTox for Fedora is available in RPMFusion, which is documented in https://github.com/qTox/qTox/blob/master/INSTALL.md#fedora
