### ISSUE TITLE
Cannot login in encrypted profile

### ISSUE THREAD

**Issue by DX37** [qTox/qTox#4162]
OS: Arch Linux (maybe on other OSes too, I'm not tested this on Windows)
qTox version: 1.8.1.r22.g0bad48ed
Commit hash: 0bad48ed
toxcore: 0.1.5
Qt:  5.8.0

Reproducible: Always

##### Steps to reproduce
For example:
1. Create profile with or without password
2. Set password, if you not set it.
3. Quit qTox and log in again.

##### Observed Behavior
qTox will say `toxcore failed to start, the application will terminate after you close this message` and... you know... terminates after that.

##### Expected Behavior
Normal log in?

##### Additional Info
[qtox.log.gz](https://github.com/qTox/qTox/files/763752/qtox.log.gz)

**Comment by sudden6** [comment]
@DX37 please test with the mentioned PR, it should fix it.

**Comment by yatsenkoanton** [comment]
I have the same issue with the same versions.  Old encrypted profiles are not loading

**Comment by DX37** [comment]
> @DX37 please test with the mentioned PR, it should fix it.

Yep, it works.
