### ISSUE TITLE
Why do I have version 0.1.0 with Toxcore?

### ISSUE THREAD

**Issue by Mattel88** [qTox/qTox#4164]
I'm using qTox with macOS and downloaded the .dmg installer for my mac.

qTox is working fine but I see that it is using the Toxcore version 0.1.0

Why is that?

0.1.6 is available

**Comment by zetok** [comment]
https://github.com/qTox/qTox/blob/1e7fc8cc5293b1e5063f29b40108e3c926c8b25b/osx/qTox-Mac-Deployer-ULTIMATE.sh#L129

**Comment by Mattel88** [comment]
Anything I can do in order to fix that?

**Comment by zetok** [comment]
You can always make a PR to bump the version.

**Comment by sudden6** [comment]
I think it would be a good idea to build with the newest compatible release automatically.

**Comment by zetok** [comment]
> I think it would be a good idea to build with the newest compatible release automatically.

It would result in broken builds, be it sooner or later.

**Comment by Diadlo** [comment]
Seems, answered?
