### ISSUE TITLE
MacOS: The wrong version numbers are showing for "Get info."

### ISSUE THREAD

**Issue by TheOuterLinux** [qTox/qTox#4165]
##### Brief Description
The wrong version numbers are showing for both "Get info" and the Toxcore (unless using TokTok).

OS: macOS Sierra (Technically not OS X anymore)
qTox version: 1.8.1
Commit hash:  https://github.com/qTox/qTox/commit/bdbf2b461bd2fde5c2cc00fca364f76e5b448356
toxcore:  0.1.0
Qt:  5.8.0
Hardware:  Macbook Pro
…

Reproducible: Always

##### Steps to reproduce
1. Right-click qTox app 
2. Select "Get info"

##### Observed Behavior
Version number says 1.7.0
Toxcore version number says 0.1.0

##### Expected Behavior
Should say 1.8.1

##### Additional Info
I'm also a little confused as to why it says its Tox core is 0.1.0. Is it using TokTok Toxcore?

**Comment by zetok** [comment]
> I'm also a little confused as to why it says its Tox core is 0.1.0. Is it using TokTok Toxcore?

#4164
