### ISSUE TITLE
error on startup: "Entry Point Not Found"

### ISSUE THREAD

**Issue by superctr** [qTox/qTox#417]
When starting qtox, it shows an error dialog and exits.

"The procedure entry point U16_to_bytes could not be located in the dynamic link library libtoxcore-0.dll"

Tested on 2 PCs running Windows 7 and with the latest build from the releases section.

**Comment by dubslow** [comment]
@tux3, it's likely related to https://github.com/irungentoo/toxcore/commit/a46810a1976096ec6af2b809d85e6eeaa51b51ad from two weeks ago. It _could_ be a core issue, but I find that unlikely.

Thanks for the report OP. :)

**Comment by DanTheBritish** [comment]
I also get the same error. Windows 7 x64.

**Comment by Allu2** [comment]
I could also reproduce this.
Simple workaround seems to be downloading older release and replacing the libtoxcore-0.dll with the one from it.

**Comment by ShedoSurashu** [comment]
@Allu2 What release did you use to get libtoxcore-0.dll from?

**Comment by dubslow** [comment]
Hey, could everyone here try again with the latest releases? @tux3 made some new ones today, and hopefully he updated his toxcore...

**Comment by tux3** [comment]
This will be fixed for good this weekend.

**Comment by tux3** [comment]
This should be fixed (tested with Wine). From now on toxcore will be rebuilt ever day.
If you still have this issue with the latest qTox please post a comment and I'll reopen.

**Comment by DanTheBritish** [comment]
I'm still getting the same error with the latest windows release, tested with https://github.com/tux3/qTox/releases/tag/qtox-windows-1413651166.09

Is there a link to a public jenkins instance? The links on the readme take to a job that doesn't exist anymore on jenkins.libtoxcore.so

**Comment by tux3** [comment]
There is a semi-public jenkins instance running on my laptop (mlkj.bounceme.net:8080), but it's not always online.

I will fix the links to point to the release page for the moment.

**Comment by tux3** [comment]
This should work now, the latest version is available <a href="https://github.com/tux3/qTox/releases/tag/qtox-windows-1413662115.05">here</a>.
I actually tested it on windows this time, but if you still have this issue anyway, please comment and I'll reopen.

**Comment by DanTheBritish** [comment]
Yep, latest works now. Thanks for looking into this.

**Comment by AleksandrL** [comment]
2014.11.02.
qTox crashes under Windows 7 6.1 7601 Service Pack P1 x64 (64 bit)
Words translated by me to english: "unhandled exception 0x09C095ED (ig4icd32.dll) at qtox.exe: 0xC0000005: permissions denied reading at address 0x00000000".
Have tried almost all releases from 2014-10-26 16:04:03 to 2014-11-02 09:05:38 downloaded here https://github.com/tux3/qTox/releases

**Comment by tux3** [comment]
@AleksandrL thanks, the problem you're having is #570, we're working on a fix

**Comment by AleksandrL** [comment]
Upd./add.
Possible it's because of my old Intel 82945G graphic adapter...
I have started qTox successfully on my new notebook with same OS.
But I still want to run qTox on my old PC.
Thanx.
