### ISSUE TITLE
New OBS package maintainer needed

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#4174]
Since the https://github.com/abbat/tox.pkg and the corresponding OBS repository is no longer maintained, we need a new maintainer who can do that.

**Comment by anthonybilinski** [comment]
I'm moderately competent at bash and looked at packaging a bit, but have no real experience. I like qTox and want to keep the packages running, does that make the cut? :P

**Comment by sudden6** [comment]
@anthonybilinski you are the hero we need :D 

Coincidentally I started with packaging c-toxcore last week, see https://build.opensuse.org/project/show/home:sudden6

It seems to be easier than expected. Maybe want add me on Tox or join #qtox@freenode?

**Comment by anthonybilinski** [comment]
I forked abbat's tox.pkg to https://github.com/anthonybilinski/tox.pkg and have started tracking some of my issues there. My changes are still very messy in the repo, but if people with some build experience want to help out feel free to comment over there.

The build account is up at https://build.opensuse.org/project/show/home:qTox qtox-alpha is building for debian 9 and ubuntu 16.04, but is by no means stable and I don't recommend anyone uses it yet.

**Comment by imperative** [comment]
Great to see (after having tested) that qtox-alpha seems to work with that repo on some Ubuntu versions already, should we add it to the install instructions page of the qTox project?

**Comment by sudden6** [comment]
@imperative I think it's too early yet, we want to move the repo under the qTox org when we cleaned up everything

**Comment by Talkless** [comment]
> I think it's too early yet, we want to move the repo under the qTox org when we cleaned up everything

@sudden6 could you elaborate on that "TODO"? What's the progress in this regard? Thanks!

**Comment by sudden6** [comment]
@Talkless not much, the effort to maintain a OBS repo got a bit dispersed.

@sleep-walker created an experimental repository for openSUSE at https://build.opensuse.org/package/show/server%3Amessaging/qtox with a clean spec file.

For the .deb side there's https://github.com/qTox/qTox/pull/4983 by @Diadlo but I'm unsure about the status.

The problem is still to find people willing to maintain the packages, ideally the distributions would integrate and maintain qTox themselves and we would ping them when a release happened, but I guess they also don't have the resources for that.

**Comment by tc-gd** [comment]
I can keep openSUSE packages in shape and pass bugs to this project. (Un)fortunately I know nothing about debian packaging...
OBS server:messaging/qtox is not that experimental - it's devel project which can be used to pass package to main distributions (which was my intention some months ago).

**Comment by sleep-walker** [comment]
I can keep openSUSE packages in shape and pass bugs to this project. (Un)fortunately I know nothing about debian packaging...
OBS server:messaging/qtox is not that experimental - it's devel project which can be used to pass package to main distributions (which was my intention some months ago).

**Comment by Talkless** [comment]
> ideally the distributions would integrate and maintain qTox themselves and we would ping them when a release happened, but I guess they also don't have the resources for that.

There are Request For Packaging bugs on Debian:
* [For qTox 788040](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=788040)
* [For libtoxcore 739860](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=739860)

**Comment by sleep-walker** [comment]
FYI I updated package moment ago (thanks @anthonybilinski for fixing build issues) and I retriggered review process to get qTox into openSUSE distributions. It's progress can be seen here: https://build.opensuse.org/request/show/588299 (or follow ups if problem is encountered)

I'd recommend to base qTox packaging in OBS on this project (via Linking the package) so we can share one source for all.

You can link this package to your project and enable builds for other distributions there. I can help you with setup.

I am also reachable on #qtox channel in freenode if you need more interactivity.

**Comment by Diadlo** [comment]
Can someone with debian/ubuntu try this repo?
https://bintray.com/qtox/qTox/
Package: qtox-nightly

**Comment by sudden6** [comment]
@sleep-walker If you continue to maintain this repo I think we should put it in our README so all the openSUSE user can easily find it.

Btw, do you know of an easy way to integrate OBS with github? ie we tag a release and the sources in the OBS repo are updated? Or is this not desireable for stability reasons?

@anthonybilinski I think we should drop the plan to continue with https://github.com/anthonybilinski/tox.pkg there was no progress in a long time and at least the spec files are a mess.

**Comment by sleep-walker** [comment]
> @sleep-walker If you continue to maintain this repo I think we should put it in our README so all the openSUSE user can easily find it.

Fine with me. IMHO if they find it via zypper, they won't reach README though.

> Btw, do you know of an easy way to integrate OBS with github? ie we tag a release and the sources in the OBS repo are updated? Or is this not desireable for stability reasons?

There is already _service file which is contains tag or revision and does all the job (downloading tarball, adjusting version, prepare changelog for RPM). I'll check if it can take latest tag automatically but it is reasonable to run it locally and manually anyway.

**Comment by Talkless** [comment]
Just discovered, libtoxcore is in Debian!

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=739860#148

```
$ apt policy libtoxcore*
libtoxcore2:
  Installed: (none)
  Candidate: 0.2.2-1
  Version table:
     0.2.2-1 500
        500 http://debian.mirror.vu.lt/debian unstable/main amd64 Packages
libtoxcore2-dbgsym:
  Installed: (none)
  Candidate: 0.2.2-1
  Version table:
     0.2.2-1 500
        500 http://debug.mirrors.debian.org/debian-debug unstable-debug/main amd64 Packages
libtoxcore-dev:
  Installed: (none)
  Candidate: 0.2.2-1
  Version table:
     0.2.2-1 500
        500 http://debian.mirror.vu.lt/debian unstable/main amd64 Packages
```

**Comment by tox-user** [comment]
Not in stable yet, but at least we finally have some progress on Debian. Great news!

**Comment by Talkless** [comment]
Debian Sid (Buster) now has qtox in package repository! Just accidentally discovered that:
```
$ apt policy qtox
qtox:
  Installed: (none)
  Candidate: 1.16.3-1
  Version table:
     1.16.3-1 500
        500 http://debian.mirror.vu.lt/debian unstable/main amd64 Packages
``` 

Now I have motivation to write AppArmor profile for it!

**Comment by byaka** [comment]
oh, its cool!

**Comment by sudden6** [comment]
qTox is now in the official openSUSE and Debian repos, I guess we don't need our own maintainers then.
