### ISSUE TITLE
[Explained] Huge non-scallable windows (QTox 1.8.1 with Qt 5.6.2)

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#4176]
##### Brief Description
OS: PCLinuxOS - stable, current, rolling distro  
qTox version: 1.8.1  
Commit hash:  
toxcore:  0.1.6
Qt:  5.6.2
Reproducible: Always
##### Steps to reproduce
1. Run QTox
##### Observed Behavior
Login window and then main program window are huge and unscallable. All is similar as in https://github.com/qTox/qTox/issues/3637 . Setting up QT_AUTO_SCREEN_SCALE_FACTOR=0 environment variable fixes an issue.

For comparison - there is no issue in Arch Linux, current stable, rolling with Qt 5.8.0 and qtox, toxcore the same versions.

Sorry, if it's problem, but I did not add notification in existing issue because it concerns another versions, etc.
##### Expected Behavior
"Normal", scallable windows.

**Comment by sudden6** [comment]
I edited your issue to fix the link.

I think this is the same problem as in the other issue report and AFAIK can only be fixed with newer Qt versions or setting the environment variables.

**Comment by ghost** [comment]
Thank you for the info.
