### ISSUE TITLE
File transfer bubbles push timestamps away

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#418]
![filesending weird](https://cloud.githubusercontent.com/assets/4358079/4587580/be86ab0a-502e-11e4-9fdd-1d82f72f55a2.png)

I think it would look better if the right ends of file transfer bubbles were pushed by the timestamps so that timestamps were always visible and the bubbles shrank horizontally. If there's a case where more info needs to be displayed than will fit (long filename, more metadata, whatever), the bubbles could grow vertically and wrap the info text. I think this is preferable to horizontal scroll bars and misaligned timestamps.

Instead of the first screenshot's behavior, it would be like this:
![bubble flow mockup](https://cloud.githubusercontent.com/assets/4358079/4587763/a4a42556-5032-11e4-9a47-a4e7196aed1d.png)

**Comment by krepa098** [comment]
related to 1fdc98873bbb29a041ec5bf591e6899a37ea3f24?

**Comment by zetok** [comment]
Too long file transfer widget when there's no text also doesn't look good

**Comment by apprb** [comment]
> related to  1fdc988 ?

Yes. But before this commit all timestamps become pushed away like this, or names and timespamps become wrapped in a wrong way like in #369.

> Too long file transfer widget when there's no text also doesn't look good

I thought about non-constant widget length too, but chose current variant. 
Will fix this.

**Comment by ProMcTagonist** [comment]
> Too long file transfer widget when there's no text also doesn't look good

Agreed, just noticed that now since I was focused on the other issues

**Comment by agilob** [comment]
close pls

**Comment by ProMcTagonist** [comment]
Why close? The behavior I described is still occurring. 
![timestamps overflow](https://cloud.githubusercontent.com/assets/4358079/4777007/faf30e94-5bc8-11e4-94f7-4ff0e1b3702c.png)

**Comment by dubslow** [comment]
GUI issue fixed by new chatform, comment for reopen
