### ISSUE TITLE
Missing files in qtox.pro

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4212]
These files are missing from qtox.pro:
```
src/groupinvite.h
src/groupinvite.cpp
src/widget/form/groupinvitewidget.h
src/widget/form/groupinvitewidget.cpp
```

qmake build shouldn't be discontinued due to this bug: https://github.com/qTox/qTox/issues/4175

**Comment by sudden6** [comment]
Yes, this is definitely not intended.
