### ISSUE TITLE
Multi-line messages aren't properly copied into the clipboard: U+2028 LINE SEPARATOR (e2 80 a8) is inserted

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4214]
It inserts this character in place of the newline. Newlines are commonly encoded as 0x0a byte.

1.8.1 (rev.60e5375) on FreeBSD
Qt version: 5.6.2

**Comment by zetok** [comment]
For some reason I couldn't even copy full multiline messages, only first selected line was copied.

Note: when copying one should not select whole message (nick, timestamp), but only the text.

When copying whole message (nick, text, timestamp), newlines are copied correctly.

**Comment by yurivict** [comment]
You should paste into the editor, save it as a file, and then look at its hexdump. The character U+2028 makes editors only show the first line, while the whole text is actually there.

**Comment by zetok** [comment]
I did `hexdump -C <<EOF`, pasted, pressed enter, `EOF`, enter, and hexdump showed only the first line. I guess I should get a better terminal?

**Comment by yurivict** [comment]
I am pasting into vim, saving it, then running hexdump on the saved file.

**Comment by ezavod** [comment]
Since qTox version 1.9.0 (Win10 64bit; toxcore: 0.1.7; Qt: 5.6.1) this is fixed for me.
@yurivict can you confirm as well, because I do not really know what has fixed that.

**Comment by yurivict** [comment]
Yes, 1.9.0 seems to have this fixed.
