### ISSUE TITLE
Large icons in menu of systray icon

### ISSUE THREAD

**Issue by DX37** [qTox/qTox#4221]
##### Brief Description

OS: ArchLinux
qTox version: latest from git (v1.8.1-93-gffd7d0e9)
Commit hash: ffd7d0e9
toxcore: 0.1.6
Qt: 5.8.0

Reproducible: Always

Just like that:
![_2017-03-01_22-28-16](https://cloud.githubusercontent.com/assets/12829428/23466860/e57b9076-fece-11e6-8805-3f5457eca99d.png)

**Comment by zetok** [comment]
Is it reproducible with Qt 5.6?
Which tray backend is used?

**Comment by sudden6** [comment]
Also which desktop environment and systray are you using?

**Comment by DX37** [comment]
> Also which desktop environment and systray are you using?

I fully using XFCE4 DE. Systray is an xfce4-panel.

> Is it reproducible with Qt 5.6?
Which tray backend is used?

I dunno. But I can try to downgrade qt5 to compile with it.

**Comment by DX37** [comment]
> I dunno. But I can try to downgrade qt5 to compile with it.

Doh... I can't downgrade to 5.6.1, because compilation will require icu 57, which all other packages can't use because of icu 58 dependency.

I'll set up container for testing...

**Comment by DX37** [comment]
@zetok - I have tested bug. It exists when I using Qt 5.6.1.

**Comment by zetok** [comment]
@DX37 could you provide info about used systray backend from the log, and perhaps try with other tray backends https://github.com/qTox/qTox/wiki/Tray-icon ?

**Comment by DX37** [comment]
> could you provide info about used systray backend from the log

```[12:24:23.513 UTC] widget/systemtrayicon.cpp:61 : Debug: Using GTK backend```

**Comment by DX37** [comment]
> perhaps try with other tray backends

CMake don't support these flags, btw, but I'll test them through QMake.

**Comment by zetok** [comment]
@DX37 you don't need to pass flags to CMake/QMake, just start qTox with `XDG_CURRENT_DESKTOP="" KDE_SESSION_VERSION="" qtox`

**Comment by DX37** [comment]
> you don't need to pass flags to CMake/QMake, just start qTox with XDG_CURRENT_DESKTOP="" KDE_SESSION_VERSION="" qtox

Aha, just tested this! It doesn't work!

Compiled without GTK backend:
```[12:39:27.886 UTC] widget/systemtrayicon.cpp:82 : Debug: Using the Qt backend```
And it's work:
![_2017-03-02_19-41-02](https://cloud.githubusercontent.com/assets/12829428/23507628/8f0c3710-ff80-11e6-8df3-945f932beabf.png)

**Comment by DX37** [comment]
@zetok AHEM (GNOME X.Org. In GNOME on Wayland tray icon can just activate window and didn't show menu at all)
![_2017-03-02_21-12-27](https://cloud.githubusercontent.com/assets/12829428/23510713/3637fde2-ff8d-11e6-8314-06faeac2df59.png)

**Comment by DX37** [comment]
MATE
![12](https://cloud.githubusercontent.com/assets/12829428/23510929/0545c57e-ff8e-11e6-922f-67ef32b511b6.png)

**Comment by DX37** [comment]
Cinnamon
![_2017-03-02_21-21-57](https://cloud.githubusercontent.com/assets/12829428/23511044/74196e06-ff8e-11e6-9f0d-62b60377aaa7.png)
Seems like it's all GTK.

**Comment by zetok** [comment]
Could you see if it's a regression in qTox's code? And if it is, bisect it?

**Comment by DX37** [comment]
> Could you see if it's a regression in qTox's code? And if it is, bisect it?

Okay, I will do that tomorrow (after 12 hours, 'cause I need to sleep...).

**Comment by DX37** [comment]
@zetok Maybe it's this commit - fac0021
But for now I can't test it.

**Comment by DX37** [comment]
@zetok Yep, that's this commit - fac0021. Icons are normal before this changes.

**Comment by Diadlo** [comment]
It's a bit strange, because in #4120 peoples said that Cinnamon and GNOME (maybe not wayland) has fine icons
