### ISSUE TITLE
User lines on screen are duplicated when "Reconnect" is clicked

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4229]
I am not sure what is triggering this, but I observe this after "Reconnect":

![qtox-duplicate-user-records](https://cloud.githubusercontent.com/assets/271906/23531241/65371a3e-ff5a-11e6-9496-8e7cce3a5201.png)

In case of many users, each records gets duplicated.

Observed with the current revision, 60e5375 also has it.
Qt-5.6.2
FreeBSD-11, kde4

**Comment by sudden6** [comment]
I can confirm this bug.

**Comment by sudden6** [comment]
git bisect points to bff25ce8b14c3ed1a71fab4a39cf311166502c8b as the first bad commit

cc @Diadlo

**Comment by Diadlo** [comment]
Should be fixed in #4271
