### ISSUE TITLE
[For Future] Setting widgets: wrapping into QScrollArea are required

### ISSUE THREAD

**Issue by apprb** [qTox/qTox#424]
Eventually it will be very useful.

**Comment by agilob** [comment]
already took care of it, PR will be today when I fix scrollbar CSS.

**Comment by apprb** [comment]
Now so many PR change setting widgets, I think this may wait for acceptance of all these PRs.

**Comment by agilob** [comment]
Sure, I think we can avoid it, for now, adding scrollarea by moving Network settings to another tab #412

**Comment by agilob** [comment]
can be closed, did it yesterday.
