### ISSUE TITLE
Markdown in URL's

### ISSUE THREAD

**Issue by randomname314** [qTox/qTox#4242]
##### Brief Description

OS: Arch Linux
qTox version: v1.8.1-107-g9c482455
Commit hash:  9c482455a8e369ac391c77da101b61a344efe1a0
toxcore:  0.1.5
Qt:  5.8.0

Reproducible: Always

##### Steps to reproduce

1. Send/recive a url with _ _  ~ ~ or other markdown symbols
2. Click
3. ???
4. 404!

http://i.imgur.com/uV7N6WB.png

**Comment by zetok** [comment]
continuation of #4233,

cc @noavarice

**Comment by noavarice** [comment]
My fault, I'm gonna escape all markdown symbols inside of URL's to completely avoid this behavior
