### ISSUE TITLE
There must be calling sound

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#4244]
When I make  call I should hear a calling sound, so I know the connection is there, the sound should stop when call is answered.

**Comment by bdimych** [comment]
+1

**Comment by Khomyachok5** [comment]
+1

**Comment by AliceGrey** [comment]
@agilob @zetok I found this sound sample under creative commons. I cut it shorter for looping if you think it would make a good outgoing call sound I have it as a pcm/wav.

My cut: http://vocaroo.com/i/s1rWgemIvrqW
Original recording under CC: https://www.freesound.org/people/bgrun17/sounds/170692/

**Comment by AliceGrey** [comment]
@zetok @Diadlo This is what I have so far https://github.com/AliceGrey/qTox/commit/caaa76938504e45aae25f56dfb21e307bacfa135

I'm having a hard time finding where to emit/stop the notification loop though.

**Comment by Diadlo** [comment]
@AliceGrey Sorry, that not answer in IRC.
Please, send the PR with this changes. But in short testing I found, that [your sound](http://vocaroo.com/i/s1rWgemIvrqW) different from the [new one](https://github.com/AliceGrey/qTox/blob/caaa76938504e45aae25f56dfb21e307bacfa135/audio/ToxOutgoingCall.pcm)

**Comment by AliceGrey** [comment]
@Diadlo My current changes leave the notification sound ringing even after the call is answered. I still haven't figured out how to get that fixed.

I had to change the sound because the old sound I proposed was too low quality and causing distortion when looped.

**Comment by Diadlo** [comment]
@AliceGrey See, how it works on recipient side

**Comment by Diadlo** [comment]
Added in #4464
