### ISSUE TITLE
Repo description change

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#4246]
I think that it should be changed from:

```
Powerful Tox chat client that follows the Tox design guidelines.
```

to:
```
Most feature-rich Tox client; P2P instant messaging, audio and video calls.
```

Opinions?

cc @Diadlo @sudden6

**Comment by sudden6** [comment]
The phrase `Most feature rich` sounds strange to me, I think `Feature-rich Tox client;....` sounds better. Or some other variant that emphases that qTox has the most features.

**Comment by zetok** [comment]
`The most feature-rich …` ?

**Comment by Diadlo** [comment]
I don't care. Both versions looks good for me

**Comment by sudden6** [comment]
This one is better :)

**Comment by zetok** [comment]
Ok, changed the description.
