### ISSUE TITLE
QObject::connect: signal not found in QThread after camera improvements

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#425]
Is anyone else getting

```
Using embeded bootstrap nodes list
QObject::connect: signal not found in QThread
Core starting with IPv6 enabled
```

introduced in #140 from [widget/camera.cpp](https://github.com/tux3/qTox/pull/410/files#diff-cbbefe493fcb26481c314527a12af8b4R35)

**Comment by ghost** [comment]
I'm getting this message as well.

**Comment by dubslow** [comment]
Ditto
