### ISSUE TITLE
Group Chats

### ISSUE THREAD

**Issue by life777eternal** [qTox/qTox#4253]
Can't add people to group chats or get a group invite link or a group key, or ID.

OS: Windows 7 Professional  
qTox version: 1.8.1
Commit hash:  bdbf2b461bd2fde5c2cc00fca364f76e5b448356
toxcore:  0.1.5
Qt:  5.5.1
Hardware:  ?
…

Reproducible: Always 

##### Steps to reproduce

1. Open qTox
2. Click "Create a Group Chat" at bottom
3. Type group title or hit [Enter] or click beside the name

##### Observed Behavior
Only options when Right-Clicking the group is "Open chat in new window," "Set title," & "Quit group."

##### Expected Behavior
Would be nice to have some more options when Right-clicking on the group chat, such as "Invite people to group," or "Copy Group Invite Link," or maybe even "Show details."

##### Additional Info
It's a bit inconvenient that the Tox Group chats disappear when no one is in them.

----

log located in: https://dropbox.com/s/fs7lkzsbd8intj5/qTox_Log.7z

**Comment by zetok** [comment]
>"Invite people to group,"

You have option to invite people: https://github.com/qTox/qTox/blob/master/doc/user_manual_en.md#contact-menu

> "Show details."

There are no details to be shown. All that client knows about groupchat is already shown in the UI.

>"Copy Group Invite Link,"
>
> It's a bit inconvenient that the Tox Group chats disappear when no one is in them.

Current groupchats don't have that functionality. Perhaps new ones would have something like "Groupchat Link", but I'm not sure about that. You might want to inquire about that people working on toxcore.

As for persistence, there's #896, and there's a PR with them here: https://github.com/TokTok/c-toxcore/pull/217
