### ISSUE TITLE
qTox crash when deleting a contact

### ISSUE THREAD

**Issue by SkyzohKey** [qTox/qTox#4254]
###### Brief Description
OS: Linux 4.4.0-64-generic - elementaryOS Loki (Ubuntu 16.04) 
qTox version: v1.6.0-obs.
Commit hash: 5648106b34fc7dc3ad4e169651a0cbbd0139170a
toxcore: 0.0.0
Qt: Qt 5.5.1
Hardware: x86_64
Reproducible: **Always**

###### Steps to reproduce
1. Login to your profile
2. Wait for a contact to appear online (LainBot inn my case)
3. Right click the contact, «Delete» and check «Remove chat logs»
4. Confirm.

###### Observed Behavior
qTox does crash and doesn't delete the contact.

###### Expected Behavior
qTox don't crash and delete the contact, making it disapear from the contacts list.

**Comment by sudden6** [comment]
can you retest with git master? and if it happens with master provide the logs and a backtrace

**Comment by Diadlo** [comment]
Seems, issue have same reason with #4229
