### ISSUE TITLE
qTox overwrites Tox profiles that it can't parse

### ISSUE THREAD

**Issue by alexbakker** [qTox/qTox#4269]
I'm on qTox 1.8.1

Steps to reproduce:
1. Garble an existing Tox profile. Let's call it garbled_profile.
2. Start qTox with "qtox -p garbled_profile".
3. Watch qTox print "Warning: failed to parse Tox save data" while it overwrites garbled_profile.

I suggest showing a prompt asking the user what to do next instead of simply overwriting it with a new profile.

**Comment by PKEv** [comment]
closed
