### ISSUE TITLE
Cannot invite users to groupchats

### ISSUE THREAD

**Issue by kytvi2p** [qTox/qTox#427]
I'm at rev 4e9d802 (currently the HEAD of master) in Debian Unstable.

I can click the 'groupchat' button and I'll see "Groupchat #0" appear, but I cannot drag an online user into it. (This worked a few days ago). I can be invited by others, e.g. 'GroupBot'. I also cannot right-click and "invite to chat" (well, I can, but nothing happens).

**Comment by kytvi2p** [comment]
Or maybe the way it's done has changed. I can right-cick and invite. _sigh_

**Comment by dubslow** [comment]
The drag and drop should still be working, there's no reason that should have stopped.

**Comment by tux3** [comment]
Is anyone still affected by this bug ?

**Comment by kytvi2p** [comment]
Drag and drop inviting isn't working for me in a8ca4ae.

**Comment by zetok** [comment]
@kytvi2p you know that d&d in qTox isn't the same as in µTox?
You have to drag contact into groupchat "window", not onto groupchat in contact list

**Comment by kytvi2p** [comment]
Well now, THAT works. (I'll close agan; perhaps I misrembered doing the drag in the contact list in qtox). Anyway, if it's supposed to work in the gc window, yes, that is seen here.

I'll re-close my bug since it apparently isn't one, just a misunderstanding of how it should be.
