### ISSUE TITLE
URL's are still broken

### ISSUE THREAD

**Issue by randomname314** [qTox/qTox#4275]
##### Brief Description

OS: Arch Linux 
qTox version: v1.9.0-6-gc7202c8b
Commit hash:  c7202c8b243453d9630a51d7de1f745b4b865abb
toxcore:  0.1.5
Qt:  5.8.0

Reproducible: Always
![2017-03-21-224013_906x73_scrot](https://cloud.githubusercontent.com/assets/8555740/24152749/7b479dd0-0e87-11e7-8ae3-c9b974de86c2.png)

##### Steps to reproduce

1. Send/recive multiple links in message (Shift+Enter)
2.  ???

#####
 ![2017-03-21-224054_953x385_scrot](https://cloud.githubusercontent.com/assets/8555740/24152740/7620b684-0e87-11e7-8ce7-f1558a7740e2.png)

![2017-03-21-213542_806x153_scrot](https://cloud.githubusercontent.com/assets/8555740/24152539/f0ffddf4-0e86-11e7-8388-59aa01ad1ab9.png)

![2017-03-21-224205_930x224_scrot](https://cloud.githubusercontent.com/assets/8555740/24152798/a21493e6-0e87-11e7-922e-0a8eb06fc901.png)

**Comment by zetok** [comment]
@randomname314 
Could you perhaps provide a test case, and upload image to github post, so that it would not disappear?

cc @noavarice
