### ISSUE TITLE
qTox network usage

### ISSUE THREAD

**Issue by wDraw** [qTox/qTox#4277]
I was checking my "Resource Manager" on Windows 7 and saw that Viber had almost no network usage, but qTox was constantly pulling data for whatever reason.

![usage](https://cloud.githubusercontent.com/assets/20287696/24186161/ad08d016-0edf-11e7-89ed-dc24f93f8a28.PNG)

Why is that? And why is it around 8KB/s all the time?

**Comment by zetok** [comment]
I've added a FAQ entry: https://github.com/qTox/qTox/wiki/FAQ#network-usage

If it answers your question, feel free to close the issue :)
