### ISSUE TITLE
Compilation Procedure for Debian 8

### ISSUE THREAD

**Issue by ElLamparto** [qTox/qTox#4278]
I attempted to compile qTox according to the procedure: https://github.com/qTox/qTox/blob/master/INSTALL.md#debian-git

1. There is still one package missing there: libswscale-dev,
2. Toxcore compilation seems to be fine,
2. For qTox, cmake is happy, but make stops on the way:

[ 13%] Building CXX object CMakeFiles/qtox_static.dir/src/video/cameradevice.cpp.o
/home/anna/qTox/src/video/cameradevice.cpp: In static member function ‘static QVector<QPair<QString, QString> > CameraDevice::getRawDeviceListGeneric()’:
/home/anna/qTox/src/video/cameradevice.cpp:275:74: error: ‘const AVClass’ has no member named ‘category’
     if (!iformat->priv_class || !AV_IS_INPUT_DEVICE(iformat->priv_class->category)) {
                                                                          ^
/home/anna/qTox/src/video/cameradevice.cpp:275:82: error: ‘AV_IS_INPUT_DEVICE’ was not declared in this scope
     if (!iformat->priv_class || !AV_IS_INPUT_DEVICE(iformat->priv_class->category)) {
                                                                                  ^
/home/anna/qTox/src/video/cameradevice.cpp:289:45: error: ‘av_opt_set_defaults’ was not declared in this scope
             av_opt_set_defaults(s->priv_data);
                                             ^
/home/anna/qTox/src/video/cameradevice.cpp:299:35: error: ‘AV_OPT_SEARCH_CHILDREN’ was not declared in this scope
     if (av_opt_set_dict2(s, &tmp, AV_OPT_SEARCH_CHILDREN) < 0) {
                                   ^
/home/anna/qTox/src/video/cameradevice.cpp:299:57: error: ‘av_opt_set_dict2’ was not declared in this scope
     if (av_opt_set_dict2(s, &tmp, AV_OPT_SEARCH_CHILDREN) < 0) {
                                                         ^
/home/anna/qTox/src/video/cameradevice.cpp:304:38: error: ‘avdevice_list_devices’ was not declared in this scope
     avdevice_list_devices(s, &devlist);
                                      ^
/home/anna/qTox/src/video/cameradevice.cpp:313:27: error: invalid use of incomplete type ‘struct AVDeviceInfoList’
     devices.resize(devlist->nb_devices);
                           ^
In file included from /home/anna/qTox/src/video/cameradevice.cpp:28:0:
/home/anna/qTox/src/video/cameradevice.h:33:8: error: forward declaration of ‘struct AVDeviceInfoList’
 struct AVDeviceInfoList;
        ^
/home/anna/qTox/src/video/cameradevice.cpp:314:32: error: invalid use of incomplete type ‘struct AVDeviceInfoList’
     for (int i = 0; i < devlist->nb_devices; ++i) {
                                ^
In file included from /home/anna/qTox/src/video/cameradevice.cpp:28:0:
/home/anna/qTox/src/video/cameradevice.h:33:8: error: forward declaration of ‘struct AVDeviceInfoList’
 struct AVDeviceInfoList;
        ^
/home/anna/qTox/src/video/cameradevice.cpp:315:9: error: ‘AVDeviceInfo’ was not declared in this scope
         AVDeviceInfo* dev = devlist->devices[i];
         ^
/home/anna/qTox/src/video/cameradevice.cpp:315:23: error: ‘dev’ was not declared in this scope
         AVDeviceInfo* dev = devlist->devices[i];
                       ^
/home/anna/qTox/src/video/cameradevice.cpp:315:36: error: invalid use of incomplete type ‘struct AVDeviceInfoList’
         AVDeviceInfo* dev = devlist->devices[i];
                                    ^
In file included from /home/anna/qTox/src/video/cameradevice.cpp:28:0:
/home/anna/qTox/src/video/cameradevice.h:33:8: error: forward declaration of ‘struct AVDeviceInfoList’
 struct AVDeviceInfoList;
        ^
/home/anna/qTox/src/video/cameradevice.cpp:319:40: error: ‘avdevice_free_list_devices’ was not declared in this scope
     avdevice_free_list_devices(&devlist);
                                        ^
CMakeFiles/qtox_static.dir/build.make:1587: recipe for target 'CMakeFiles/qtox_static.dir/src/video/cameradevice.cpp.o' failed
make[2]: *** [CMakeFiles/qtox_static.dir/src/video/cameradevice.cpp.o] Error 1
CMakeFiles/Makefile2:995: recipe for target 'CMakeFiles/qtox_static.dir/all' failed
make[1]: *** [CMakeFiles/qtox_static.dir/all] Error 2
Makefile:127: recipe for target 'all' failed

**Comment by zetok** [comment]
https://github.com/qTox/qTox/wiki/Troubleshooting-builds ← is this helpful?

**Comment by ElLamparto** [comment]
zetok, thanks.
I'll wait for the next Debian Stable (Stretch) - prefer not to mess with ffmpeg...
