### ISSUE TITLE
URLs in different lines aren't sent properly: their text is changed

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4290]
This message:
```
https://github.com
https://github.com
```

is sent like:
![qtox-urls](https://cloud.githubusercontent.com/assets/271906/24327368/3b10c6b0-1184-11e7-949a-b270eea412d7.png)

version 1.9.0

**Comment by Diadlo** [comment]
Can you use issue template? There is a lot of useful information, what you skip
Should be fixed on master. Can you test?

**Comment by sudden6** [comment]
This is most probably already fixed by 08208e9aa515270a190ff85a1ba704c8a130c5cd

**Comment by yurivict** [comment]
yes, it is fixed as of 2e4ac3c
