### ISSUE TITLE
Font in message input field differs from font in chat

### ISSUE THREAD

**Issue by DX37** [qTox/qTox#4292]
##### Brief Description

OS: Windows 10
qTox version: Latest nightly (v1.9.0-22-g2e4ac3c)
Commit hash: 2e4ac3c

This bug affects stable v1.8.1 too.
Looks like this:
![2017-03-26 16-40-25 qtox - online](https://cloud.githubusercontent.com/assets/12829428/24330627/ea61d618-124c-11e7-972d-09b2c85f02af.png)

**Comment by zetok** [comment]
Should be fixed by #4300.
