### ISSUE TITLE
Qtox includes quote marks in URL highlight

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#4295]
Expected behavior: exclude double quote marks (") from the blue URL highlight.
But they are consistently included. It's a minor problem, but I assume it's also an easy fix, with a slight tweaking to the regex.

Commit hash: f839abf33fb666f586fef3bda06efd49165c0b2d
qTox version v1.9.0-18-gf839abf

**Comment by zetok** [comment]
I've got the regexp in #4297, but that addresses the problem only partially, i.e. string that is being matched against regexp has escaped HTML, so while regexp doesn't match against `"`, it does match against `&quot;` … No idea how to fix that.

When not matching against letters:
![spectacle aq1995](https://cloud.githubusercontent.com/assets/3148759/24360105/4a22d302-12fe-11e7-80d5-60122f781caf.png)

Same text, but matched against letters:
![spectacle jg9088](https://cloud.githubusercontent.com/assets/3148759/24360479/517b2c16-12ff-11e7-8844-a84989f7c6fb.png)
