### ISSUE TITLE
Who is Puripito?

### ISSUE THREAD

**Issue by dcapeletti** [qTox/qTox#4296]
##### Brief Description

OS: GNU/Linux, Trisquel 7.0
qTox version: v1.6.0-obs
Commit hash:  5648106b34fc7dc3ad4e169651a0cbbd0139170a
toxcore:  0.0.0
Qt:  5.6.1

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. I always get a notification from Puripito that I always reject. I do not know who it is.

##### Observed Behavior
I always receive a notification from Puripito that I always reject. I do not know who it is However, every day I receive it.

##### Expected Behavior
If it's a spam, there should be a way to mark that you never want to receive invitation notifications from that user. It's kind of annoying to always have to reject them.

##### Additional Info
See attached image
![pupirito](https://cloud.githubusercontent.com/assets/5890886/24346401/86497880-12aa-11e7-8353-0e227bea2eab.png)

**Comment by ezavod** [comment]
@dcapeletti Have you tried the [NoSpam](https://github.com/qTox/qTox/blob/master/doc/user_manual_en.md#nospam) feature? It is probably spam. You could find NoSpam in privacy settings.

**Comment by dcapeletti** [comment]
@ezavod I have already generated a random NoSpam. I'll see if I keep getting notifications. You can close this thread.
