### ISSUE TITLE
Add repository for Ubuntu 17.04

### ISSUE THREAD

**Issue by nweyand** [qTox/qTox#4298]
Ubuntu 17.04 will be out in about 2 weeks. It might be intelligent to add a repo for Zesty before it goes from beta to stable and finish testing it so that everyone can use the repo from the first day on.

**Comment by Diadlo** [comment]
https://qtox.github.io/blog/2017/02/15/Maintainer-Wanted.html

**Comment by Mestake** [comment]
Hi, what is the status of ubuntu repo for now? I far as I can see there's no one. If that's true I'd like to create PPA and when it's running and tested submit it for inclusion to mainstream. What do you guys think about it?

**Comment by tox-user** [comment]
Hi, we currently do not have any packages for Ubuntu or Debian, which means there is no repository. It is too much work for the few active developers to maintain such packages, so we need help from the community.

**Comment by Mestake** [comment]
@tox-user Yes, I'm going to create a PPA on launchpad. I'll let you know when it's ready.

**Comment by sudden6** [comment]
qTox is now in the official Debian and Ubuntu repositories.
