### ISSUE TITLE
Update the version available for download to 1.9.0

### ISSUE THREAD

**Issue by nweyand** [qTox/qTox#4299]
According to the [change log](https://github.com/qTox/qTox/blob/master/CHANGELOG.md), version 1.9.0 is out since march 19th . The [download page](https://github.com/qTox/qTox/blob/master/README.md#qtox) still links to version 1.8.1 though.

**Comment by Hasshu** [comment]
Speaking of which, is there any particular reason why Windows doesn't get timely releases?

**Comment by maverick74** [comment]
Without timely updates, i believe this won't go anywhere...

But maybe that's just me...

**Comment by zetok** [comment]
>Speaking of which, is there any particular reason why Windows doesn't get timely releases?

Windows updates depend on @tux3 to do some stuff manually. Given that he doesn't have time for it, they are significantly delayed.

It would be good if there was someone else who would be interested in doing that stuff. AFAIK current qTox maintainers (including myself) aren't interested in doing it. Not really surprising, given that there are no windows users among current maintainers..

Anyway; aside from "official" builds, there is also a Chocolatey package: #4126, perhaps someone would be interested in working on that.

**Comment by tux3** [comment]
I will make sure to update the Windows release today.

**Comment by Hasshu** [comment]
@nweyand Could you rename this issue to "Update the Windows version available for download" or something?

@tux3 Any updates?

**Comment by tux3** [comment]
@Hasshu We're at 1.10.2 now, and everything should be working as intended!

**Comment by Hasshu** [comment]
> We're at 1.10.2 now, and everything should be working as intended!

@tux3 That's exactly the problem, since the latest version is v1.11.0. I just suggested to repurpose this issue to broaden its scope (it was open, anyway). Sorry, I probably should have clarified that.

**Comment by Diadlo** [comment]
@tux3 Is it possible to upload windows build at release page(https://github.com/qTox/qTox/releases/latest/) and link to it?

**Comment by tux3** [comment]
@Hasshu @Diadlo Thanks for the clarification, I've made a new build and updated the download page.
