### ISSUE TITLE
Avira hit while running bootstrap.bat

### ISSUE THREAD

**Issue by nweyand** [qTox/qTox#4303]
Avira detects something called „TR/Agent.eweqd“ (which has helpfully no description on the Avira website) while the bootstrap script works with
`qTox\libs\openal-soft-1.16.0\build\CMakeFiles\CMakeTmp\<random_filename>.exe`

You might want to add a warning about that to the website.

**Comment by zetok** [comment]
Would you mind adding it to [wiki](https://github.com/qTox/qTox/wiki/Problematic-antiviruses)?

**Comment by nweyand** [comment]
done!

**Comment by nweyand** [comment]
The pull request linked to above adds a small warning about there possibly being false positives on some anti virus software and refers to the wiki page zetok referred me to.

**Comment by sudden6** [comment]
Seems closed.
