### ISSUE TITLE
[Suggestion] Use QtAV instead of ffmpeg, openal etc. directly

### ISSUE THREAD

**Issue by nweyand** [qTox/qTox#4306]
[QtAV](https://github.com/wang-bin/QtAV) would have the benefit of outsourcing part of the build management (i.e. somebody else is looking after that everything works fine with the latest versions of the libraries) and therefore possibly increasing future maintainability of qTox. Also it can be downloaded as precompiled binaries for several platforms, drastically reducing the build requirements on those platforms...

EDIT: Did I mention it has some cool features?

**Comment by zetok** [comment]
>QtAV would have the benefit of outsourcing part of the build management (i.e. somebody else is looking after that everything works fine with the latest versions of the libraries) and therefore possibly increasing future maintainability of qTox.

Not really. We would need to ensure that it can be compiled on travis on top of FFmpeg,

Doesn't QtAV error out on its own travis build?

>Also it can be downloaded as precompiled binaries for several platforms, drastically reducing the build requirements on those platforms...

```
$ eix qtav
No matches found
```

It would make packaging harder, given that it's not available in distros' repos.

If it's really better than just using FFmpeg, why not though.

**Comment by sudden6** [comment]
Not a focus of qTox in the near term.
