### ISSUE TITLE
Warnings during bootstrap.bat

### ISSUE THREAD

**Issue by nweyand** [qTox/qTox#4307]
When running bootstrap.bat on Windows, a series of libraries is downloaded and automatically compiled. All of these libraries do generate hundreds of warnings.

Should we report these warnings to the librarie’s maintainers?

**Comment by DX37** [comment]
bootstrap.bat is outdated, remember? At least the last ffmpeg is now version 3.2.4.

**Comment by nweyand** [comment]
True, bootstrap.bat is outdated. But we ares still some time away until all issues with the new build process are addressed. Until they are, I think I am going to make sure the current build process works for me... And if I am working on making it work for me, why not share this with everyone?

**Comment by zetok** [comment]
>All of these libraries do generate hundreds of warnings.

If it's reproducible with newest versions of those libs, sure.

**Comment by sudden6** [comment]
bootstrap.bat doesn't exist anymore.
