### ISSUE TITLE
Segfault on account creation, can't even use qTox

### ISSUE THREAD

**Issue by alexpolevoy** [qTox/qTox#4319]
##### Brief Description

OS: Debian GNU/Linux (Stretch, amd64), qTox is installed from openSuSE Build Service repo
qTox version: can't get there
Commit hash: 5648106b34fc7dc3ad4e169651a0cbbd0139170a
toxcore: ?
Qt: 5.7.1
Hardware: various

Reproducible: Always

##### Steps to reproduce

1. Install qTox
2. Start it up
3. Try to create a new account
4. …
5. ???
6. Segmentation fault.

##### Expected Behavior
Account creation

##### Additional Info
There was no files in ~/.cache/ (even Tox directory there is missing), so I cannot provide any logs or whatever.

**Comment by sudden6** [comment]
Can you check if it's a duplicate of https://github.com/qTox/qTox/issues/4054 ?

**Comment by berndmehnert** [comment]
I have exactly the same problem as alexpolevoy ...
does anybody have some news on this issue?

**Comment by sudden6** [comment]
@bhmehnert check the linked issue, if your backtrace is similar to it, we can't really do anything.

**Comment by alexpolevoy** [comment]
Here's the backtrace:
https://pastebin.com/bju4ecQd
Looks quite similar, but this doesn't mean the issue can be left unresolved.

**Comment by Diadlo** [comment]
@alexpolevoy It's not qTox issue, so we can't fix it

**Comment by alexpolevoy** [comment]
Okay, so what should I do then? Don't tell me to compile it myself. You have a repository, you claim it to be compatible with Debian, but turns out it's not. This may be not your issue, but unless you tell everybody it doesn't work in Debian, it's yours.

**Comment by Diadlo** [comment]
@alexpolevoy "compile myself" will not help. Should we termorary remove official Debian support?
You can use workaround -- old sqlcipher version

**Comment by alexpolevoy** [comment]
@Diadlo Why don't you migrate to newer libs instead? Even the most “i-am-so-stable-but-so-outdated” distro has this lib newer than you did compile your software against. Looks like about time to migrate, otherwise qTox will stay unusable on some (possibly even all) major stuff like *buntus, Mint, Arch, Fedora, openSuSE (just to name a few), which is clearly your problem, not distro maintainers'. Also, suggestion of an encryption library downgrade from developer of such a program (aimed at privacy and security) looks shocking.

**Comment by Diadlo** [comment]
I haven't enough time to make migration (and don't know the suitable lib). If you have -- I will be very thankful for you

**Comment by zetok** [comment]
@alexeysvrv https://qtox.github.io/blog/2017/02/15/Maintainer-Wanted.html - feel free to help with migrating.
