### ISSUE TITLE
[Regression] qTox crashes on group invite

### ISSUE THREAD

**Issue by ezavod** [qTox/qTox#4327]
##### Brief Description

OS: openSUSE Tumbleweed
qTox version: v1.9.0-22-g2e4ac3c6
Commit hash:  2e4ac3c6ac88639967f3015854ccdf63c322af48
toxcore:  0.1.2
Qt:  5.7.1

Reproducible: Always

##### Steps to reproduce
1. Start qTox
2. Create a new group chat by inviting a contact

##### Observed Behavior
qTox crashes as soon as one accept the invite (by clicking the `join` button).
It does not matter if I get invited or if I invite a contact to a new group. In both cases my client crashes.
The other client does not, because it is an older version.

##### Additional Info
`git bisect` blames commit 931e5803cd6c78a12d7f5ede16743a828ea62a69 as the first bad commit.
Maybe related to #4324.

[log.txt](https://github.com/qTox/qTox/files/909674/log.txt)

Edit:
GDB Backtrace: [bt.txt](https://github.com/qTox/qTox/files/910849/bt.txt)

**Comment by sudden6** [comment]
cc @noavarice
