### ISSUE TITLE
qTox doesn't ask password on encrypted profile login

### ISSUE THREAD

**Issue by DX37** [qTox/qTox#4344]
##### Brief Description

OS: Windows (and maybe other OSes)
qTox version: v1.9.0-62-g17abfe3
Commit hash: 17abfe3
toxcore: v0.1.7
Qt: 5.6.2
Reproducible: Always

qTox doesn't ask for password when I login into encrypted profile. As a result, chat database isn't loading, but I still can see my profile and friends list.

qTox log: [qtox.log.gz](https://github.com/qTox/qTox/files/944294/qtox.log.gz)

**Comment by sudden6** [comment]
From the logs it seems your *.tox file isn't encrypted, but settings + db are. Did you perhaps remove the password from your profile with a client other than qTox?

**Comment by DX37** [comment]
> Did you perhaps remove the password from your profile with a client other than qTox?

No, I didn't do any of that.

Now I tested this on Arch Linux. qTox required password, but after login there was `Set profile password` in profile settings. After logout and launch qTox again, it doesn't require password anymore. And I can't set new password because of old password on database.

After creating pure new profile and setting password in the beginning or in profile settings, it still not asking for password after restart.

Here is log again: [qtox.txt](https://github.com/qTox/qTox/files/949477/qtox.txt)

**Comment by sudden6** [comment]
I could reproduce this, working on a fix.
