### ISSUE TITLE
build in Mac OSX

### ISSUE THREAD

**Issue by wellkwen** [qTox/qTox#4346]
I'm new here, but when I try to build with a script, I get an error:

**`.    Starting build process ...

        Now working in /Users/nikki/qTox-Mac_Build

       Starting cmake ...
      /Users/nikki/Desktop/qTox-Mac-Deployer-ULTIMATE.sh: line 226: cmake: command not found`**

**Comment by ezavod** [comment]
@wellkwen It appears that cmake is not installed. Make sure that you run this script with required privileges or try to install cmake manually.

**Comment by zetok** [comment]
@wellkwen did you run the script with appropriate permissions?

**Comment by sudden6** [comment]
Closed because needed information was not provided.
