### ISSUE TITLE
Pulseaudio in windows build

### ISSUE THREAD

**Issue by 0nomatopoeia** [qTox/qTox#4349]
Is there any way to install pulseaudio on the windows build (64 bit)?
And/or what is the status of the echo cancellation in it (eg. how well does it work)?
Alternatively is there any other way to implement working echo cancellation on the windows builds?

OS: Windows 7 x64
qTox version: 1.8.1
Commit hash:  bdbf2b461bd2fde5c2cc00fca364f76e5b448356
toxcore:  0.1.5
Qt:  5.5.1

**Comment by stikonas** [comment]
Pulseaudio does not work on windows. At least there are no attempts since 2011.

**Comment by 0nomatopoeia** [comment]
so...  no other way to implement echo cancellation in the windows build?

**Comment by sudden6** [comment]
I'm currently experimenting with a new approach, but I don't know yet if it will work.

**Comment by 0nomatopoeia** [comment]
ok, let me know if you need help testing it.

**Comment by sudden6** [comment]
@0nomatopoeia take a look at #4367 although you'll probably have troubles compiling it for windows at this time.

**Comment by sudden6** [comment]
Original question answered.
