### ISSUE TITLE
Can't set recording device in PulseAudio

### ISSUE THREAD

**Issue by raichu** [qTox/qTox#435]
During video chat, I can't change the recording device (to the actual microphone) for qtox for some reason.

**Comment by suhr** [comment]
Same thing for audio call.

**Comment by ghost** [comment]
I have yet to have a successful voice chat because qTox keeps using the wrong device and I can't change it.

tux3 pls

**Comment by suhr** [comment]
> qTox keeps using the wrong device and I can't change it

Try to set a proper fallback in pavucontrol and restart qTox.

**Comment by tux3** [comment]
I'll add an audio input/output device selection in the settings

**Comment by tux3** [comment]
I just pushed commits to change the audio devices, just select one from the combo box in the settings and restart.

Note that for the moment you'll _need_ to restart qtox for the changes to take effect, but we can improve that later.
Please tell me if it solved the problem or not.

EDIT: If you still have a problem, please comment and I'll reopen.
