### ISSUE TITLE
Stagnation of the project?

### ISSUE THREAD

**Issue by Tamila-2017** [qTox/qTox#4350]
Hi!

Why do you no longer develop the **qTox** project? He is very necessary for many people!

**Comment by stikonas** [comment]
I'm not qTox developer but there are recent commits. And in any case if you want qTox to move further then contribute patches.

**Comment by sudden6** [comment]
Probably what you're perceiving as stagnation is the lack of package updates, see https://github.com/qTox/qTox/issues/4174. Unfortunately nobody that complained about missing packages was willing to take up the task or mention someone who would be willing to do it.

**Comment by Diadlo** [comment]
We still develop it ;)
I think, question is answered, so closing
