### ISSUE TITLE
Crypto integration

### ISSUE THREAD

**Issue by Ripcurl99983** [qTox/qTox#4354]
Hello qTox,

Machinecoin is a Bitcoin alternative, which is essentially a free open source token system. I used to be the graphics guy for the development team, and we, like you, are always trying to figure out how to get more users. 

I would like to propose integrating a Machinecoin wallet into qTox. Tokens could be used to tip people while chatting. Not only is that fun, but things could evolve from that, such as accepting tokens for files, private chats, or whatever. Those tokens can be also be used for game development or anything else that requires any kind of accounting. We have Twitter bots that are tied to Twitter accounts that have these capabilities, and I know a lot of forums such as Reddit have adopted this concept as well. I used to work for a large corporation that used a chat program as the primary way to communicate across the organization. It was like Skype, but developed internally and better. I always wished it had the capability to tip people that helped me.

Also, if you integrate Machinecoin successfully, most likely a large percentage of other coin teams would fork your project and use it, which could get you more exposure and users (there are 1000's of coins now).... or you could make your own token from what you learn.

Tox was created because of privacy controls, Bitcoin was created because of corrupt banks. I believe our communities are extremely well suited for each other. 

We use a QT wallet for peer to peer transactions. I am not a software developer, but given our similar platforms... c++, Qt, peer to peer, etc. I would think it would be pretty easy to integrate the two clients. Both programs can be kept separate and co-exist in a single chat application, or I'm if you felt the need to limit connections, I'm sure you could use our protocol to connect with other clients.

So, new awesome features, larger user base, and opening the door to a whole new large and established community... for free. Please consider integrating Machinecoin. For us, it would help by bringing a 1st to market product, attract more developers, and we can release some good press.  I would be happy to do whatever I can to make this happen. 

The machinecoin project is at https://github.com/machinecoin-project. 

Thanks for your time

**Comment by sudden6** [comment]
While I agree there are some common goals in both projects, I think for now qTox should keep a narrow focus on being a IM client.

**Comment by Ripcurl99983** [comment]
That's too bad. It seems like peanut butter and jelly to me.

**Comment by Talkless** [comment]
Some sort of qTox plugin API would help for these kind of cases. No need to "marry" one specific cryptocurrency.... ([there are almost a 1000 of them](https://coinmarketcap.com/all/views/all/)).

**Comment by Ripcurl99983** [comment]
I just saw this, thanks! I am gonna send the link to our main dev. I agree about not "marrying" one specific crypto, but gotta start with one 👍

**Comment by sudden6** [comment]
Closing since this most probably won't happen.
