### ISSUE TITLE
Loading profile during call segfaults qTox

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#436]
https://gist.github.com/zetok/bb2b3f714c7c5473716b

Also there's issue with loading.

If one goes to options and just presses "Load" without actually selecting another profile, qTox still goes down. (line 11)

Beside that, profiles don't integrate well with core logging:

```
Error opening logger name: libtoxcore.log with level 1: file already opened!
```

**Comment by dubslow** [comment]
I can't reproduce the logging issue. I would bet that it and a message about threads in your gist are related to having a call active.

**Comment by dubslow** [comment]
Wait, actually, I think I found an unrelated problem. 

I noticed that if you switch profiles while not already connected, the new profile for some reason didn't try to connect.

I did some digging and came to the conclusion (after learning some things from the Qt docs) that I had been violating a couple of threads, and fixed that issue. Switching while offline now seems to work, and probably a class of awkward race conditions that haven't happened by sheer dumb luck has been eliminated.

Edit: zetok, that logging issue is a toxcore problem, not Qt. I guess it isn't closing the logfile on tox_kill()?

**Comment by zetok** [comment]
Segfault happens after:
1. Tried to switch profile during call, got a warning that there's active call
2. Ended call
3. Tried to switch profile again, qTox segfaults

qTox segfaults right after pressing button to switch profile, time period between step 2 and pressing button to switch profile is (I think) under 2-3s.

https://gist.github.com/zetok/5f2cabdd7d7dfea4e180

Edit: I wasn't able to reliably reproduce, but run into that 2 times already

**Comment by dubslow** [comment]
@tux3 Are we sure calls are being properly cleaned up? There's a print in the gist saying clean up was run, yet somehow toxav is being called

**Comment by tux3** [comment]
@dubslow yes I noticed that too, it's possible that we're not telling toxav to end the call when we should be, and just disabling it in Core::calls[] instead
I haven't checked tho.

**Comment by zetok** [comment]
Also segfaults after clicking on `New Tox ID` during call

**Comment by agilob** [comment]
@dubslow just disable all buttons in Profiles group when call is active.

**Comment by zetok** [comment]
> just disable all buttons in Profiles group when call is active.

Now, that wouldn't be nice, since one might want to:
- change name of profile while in call
- export profile while in call
- delete some other unused profile while in call
- make new profile while in call, to switch to new profile later
- import profile while in call, to switch to it later

**Comment by dubslow** [comment]
@zetok, that's because New Tox ID does the same thing as Load.

Maybe disabling only those two buttons...

**Comment by zetok** [comment]
I got a bit different result on d92bad3f9cca3681106a44524b812b0115424dc5 qTox and 3c874bcf62ab4e453d745547512bd8a0835d3bcb core.

What I did:
1. "Ring" call to someone, without actually making it into call
2. `New Tox ID`
3. SIGABRT time!
 ↓
https://gist.github.com/zetok/97dba58728a63e58bcca

**Comment by dubslow** [comment]
> 1. "Ring" call to someone, without actually making it into call

What does that mean?

**Comment by zetok** [comment]
> > 1. "Ring" call to someone, without actually making it into call
> 
> What does that mean?

Call button is yellow.

**Comment by zetok** [comment]
I still have issue with https://github.com/tux3/qTox/issues/436#issuecomment-60018398 , on newest qTox 7b70fd0008f95e17e9e81e7d85738a63bca5e35b ; core c8812d4734bc92be34df076accb3a8e416a94d9d patched with irungentoo/toxcore#1136

Way I've triggered it:
1. Launch qTox
2. `New Tox ID`
3. SIGABRT time!

Backtrace: https://gist.github.com/zetok/d633630d6079188209ec

Edit: Reproducible: Always

**Comment by tux3** [comment]
@zetok irungentoo/toxcore#1136 isn't related to the bug you're having tho.

Just looking at the backtrace, something very bad is going on.
The core thread SHOULD NEVER EVER touch any GUI stuff, and here it's calling Widget::onSettingsClicked directly.

EDIT:

> Widget::getInstance()->onSettingsClicked(); // update ui with new profile (im worried about threading, but it seems to work)
> im worried about threading

Yeah, well.

**Comment by zetok** [comment]
> (…) seems to work

Not anymore :3

**Comment by dubslow** [comment]
Lol, I left it as-was with comment because I wasn't sure how to fix it.

**Comment by tux3** [comment]
Just remember not to do gui stuff outside of the gui thread :)
Use Qt's events if you want to talk to a thread.
