### ISSUE TITLE
Friend disappears

### ISSUE THREAD

**Issue by Geremia** [qTox/qTox#4360]
##### Brief Description

OS:Linux (Slackware-current, kernel 4.4.38)  
qTox version: 1.9.0
Commit hash:  7e0bcf0 
toxcore:  0.1.5
Qt:  5.7.1
…

Reproducible: Always (with one specific buddy)

##### Steps to reproduce

1. Press the reconnect button.
2. One buddy (who is not in a circle) disappears.

I have to make that friend delete me from her buddy list and re-friend me in order to get her to appear again on my qTox client. All her history is still saved on my end, though. The issue is that she disappears from my friend list, and she is no longer listed in my `tox_save.ini`. She is using [Antidote](https://github.com/Antidote-for-Tox/Antidote); however, my other friends who use Antidote don't disappear from my buddy list. She is my only buddy not in a circle. Perhaps this is why she disappears upon my reconnecting.

##### Expected Behavior
The buddy should remain in my list, not disappear.

----

log located in `~/.cache/Tox/qTox/`:

Contains tons of these:
`Critical: Tox save file  "/home/user/.config/tox/tox_save.tox"  couldn't be opened`
and
`persistence/settingsserializer.cpp:278 : Warning: Couldn't open file`

Some settings files in `.config/tox` had the wrong owner for some reason (root instead of user); however, quitting Tox, `chown`ing all the files in `/home/user/.config/tox/` to user, and restarting Tox still doesn't make my disappeared friend reappear.

**Comment by sudden6** [comment]
Please post the log file. Also are you using an encrypted profile? Can you try if this still happens with master?

**Comment by Geremia** [comment]
@sudden6 Here's the `qtox.log`: https://gist.github.com/Geremia/a422846b4132593b88da3bc2c3935f7a

@sudden6 I don't think I'm using an encrypted profile. How do I tell of I am?

**Comment by Geremia** [comment]
I don't know if this is related, but I also cannot invite anyone to groups.

**Comment by sudden6** [comment]
The logs don't really look like a qTox issue. Is there enough space on the filesystem? does `.config/tox` (the folder) have correct permissions?

**Comment by Geremia** [comment]
@sudden6 
>does .config/tox (the folder) have correct permissions?

For some reason some of the files were root. That seemed to be the problem. I'm not sure how they changed to root. Perhaps this is a local issue.

Still, I can't get group invites to work, but this is probably another issue.

This issue can be closed.
