### ISSUE TITLE
Libsodium is now available in Debian/unstable

### ISSUE THREAD

**Issue by sa2ajj** [qTox/qTox#437]
The package is now available in the Debian archive and it'd be nice to either have an option (whlie using `bootstrap.sh`) not to have it downloaded and installed or that the script detects the presence of the library (I'll see if I can provide a patch for that).

**Comment by sa2ajj** [comment]
Looks like I was too quick: there's an option not to install libsodium and I just ignored the suggestion to use `--help` to get more information.

Sorry for the noise.

**Comment by dubslow** [comment]
Well I am glad to know that libsodium has made it into Debian :)

**Comment by sa2ajj** [comment]
https://tracker.debian.org/pkg/libsodium

**Comment by tux3** [comment]
I'm a bit late to the party but thanks for the heads up! This will makes things much simpler if libsodium makes it into testing.
