### ISSUE TITLE
[regression] -p feature is broken: subsequent unstances just bring up the previous instance window and exit

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4384]
This is a regression in 1.10.0 making the use of multiple accounts impossible.

For some reason this doesn't happen every time, it happens intermittently.

The first instance prints this:
```
[16:31:53.769 UTC] ipc.cpp:262 : Debug: Processing event:  "activate" : 1494347513 = false
```

The second instance prints this
```
[16:31:53.267 UTC] ipc.cpp:126 : Debug: postEvent  "activate" to 3395321266
[16:31:54.769 UTC] main.cpp:272 : Debug: Event "activate" was handled by other client.
```
and exits.

qtox should never activate other profile's instances.

**Comment by yurivict** [comment]
@Diadlo , you committed the IPC refactoring 22 days ago, it might be the culprit.

**Comment by sudden6** [comment]
I think I also experienced this.

**Comment by Diadlo** [comment]
@yurivict Why you never use issue template?
What is the steps to reproduce?

**Comment by yurivict** [comment]
> Why you never use issue template?

Because I try to leave the minimal information needed to reproduce the case. -)

> What is the steps to reproduce?

1. Create account1
2. Create account2
3. Log into account1 with ```qtox -p account1```
4. Log into account2 with ```qtox -p account2```
5. Observe that step 4 leads only to account1 being activated

This doesn't happen every time, it is intermittent.

**Comment by Diadlo** [comment]
Way to reproduce:
1. `qtox -p A`
2. Close qtox
3. `qtox -p B`
4. `qtox -p A`
