### ISSUE TITLE
If Tox already does onion routing, why use Tox over Tor?

### ISSUE THREAD

**Issue by Geremia** [qTox/qTox#4386]
The section "[What is stopping people from tracking me through the public DHT?](https://wiki.tox.chat/users/techfaq#what_is_stopping_people_from_tracking_me_through_the_public_dht)" of the [Technical FAQ](https://wiki.tox.chat/users/techfaq) page says:

> Tox generates a temporary public/private key pair used to make connections to peers in the DHT. Onion routing is used to store and locate Tox IDs, to make it more difficult to, for example, associate Alice and Bob together by who they are looking for in the network. [1](https://github.com/irungentoo/toxcore/blob/5ea703c844b12e86702c35b53b0b798fe5f86634/docs/Prevent_Tracking.txt)

If Tox already uses onion routing, then why use [Tox over Tor](https://wiki.tox.chat/users/tox_over_tor_tot)? What's the difference?

<sup>[cross-posted here](https://github.com/TokTok/c-toxcore/issues/544#issue-227456273)</sup>

**Comment by zetok** [comment]
>What's the difference?

Onion routing used in Tox is not equivalent to the one used in Tor. Aside from that, it's used **~only for the DHT** – aside from DHT, peers and friends are connected to each other directly, no onion used. (that's the gist of it, without considering TCP-only mode)

If that answers the question, please close the issue.

**Comment by Geremia** [comment]
@zetok thanks
