### ISSUE TITLE
Wont remember closing of username panel anymore.

### ISSUE THREAD

**Issue by fcore117** [qTox/qTox#4387]
##### Brief Description

OS: Win 7 x64(got report from friend) / Win 10 x64(i replicated this anomaly)
qTox version: v1.9.0
Commit hash:  104-g5d117e6 
toxcore:   0.1.8
Qt:  5.5.1
Hardware:  multiple hw

##### Steps to reproduce

1. Make qTox multi window
2. open user and remove username area (pic with red X)

##### Observed Behavior
Do not remember removing user list window anymore, before it remembered (pic with red X)

##### Expected Behavior
Has to remember closure of username area after re opening friend window. (pic with green OK)

##### Additional Info
(links, images, etc go here)

![1](https://cloud.githubusercontent.com/assets/1313813/25889605/fa53d8fc-3572-11e7-9a3a-d1f7227a2131.PNG)
![2](https://cloud.githubusercontent.com/assets/1313813/25889609/fd188664-3572-11e7-9110-8f3de163b205.PNG)

**Comment by ezavod** [comment]
Can reproduce.
`git bisect` blames commit add8d51a2913fa6979674247696da9d397d252b5 as the culprit.
