### ISSUE TITLE
[Feature Request] Show dates in chat log

### ISSUE THREAD

**Issue by SlugFiller** [qTox/qTox#4388]
I like to keep my computer, and my Tox, open 24/7. The problem is, messages which arrive show the time of arrival, but not the date. Contrast with Skype, which has a clear horizontal line separating messages which have arrived on different dates. This is particularly annoying with online/offline messages, which often arrive in large bulks, without proper alert, and I have no idea how long ago they were received (As in, how long ago my friends were last seen online).

I would love some sort of indication as to on what date a message was received.

**Comment by Diadlo** [comment]
What's wrong with current one?
![image](https://cloud.githubusercontent.com/assets/6306608/25932683/79911e2e-361b-11e7-8323-ef045603501c.png)

**Comment by SlugFiller** [comment]
Oh, I see the problem now. It doesn't activate for status messages. In fact, status messages across date lines seem to disable this display. This should be retagged as bug, then:
![toxdates](https://cloud.githubusercontent.com/assets/5435495/26002311/ed44248e-3737-11e7-8dd7-2534a18a7f80.png)

Version commit hash pictured: d320b1f259efc4a9200c00ca624d8289383c7f9e
