### ISSUE TITLE
Can't make friends between two accounts

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4398]
Both hosts are qTox-1.9.0 with toxcore-0.1.8 on FreeBSD-11. The problem exists when both run with no proxy, and when both run with SOCK5 proxy.

What I did:
1. Copied ToxID on host2
2. Pressed "+" button on host1, pasted host2's ToxID, hit the"Add friend" button
3. host2 got a message "Friendship requested", which I accepted
4. Friends never got connected, they never became green on either end, never changed names from toxid.

I am not sure if this is a qTox or a toxcore problem.

I tried twice with the same result.

This is a major problem because the essential function, establishing a connection, fails.

**Comment by sudden6** [comment]
How long did you wait for the clients to connect? It sometimes takes several minutes for them to find each other.

**Comment by yurivict** [comment]
I waited many minutes. It sometimes took 1-2 minutes before, but this time even after 20-30 minutes there was no result.

I think, the recent toxcore version update also has to do with this, because before this never happened with 1.9.0.

**Comment by sudden6** [comment]
Ok. Can you find out if it was the toxcore change or a qTox one?

**Comment by ati3** [comment]
I have a similar problem between 1.9.0 (Windows 10) and 1.6.0 (Linux Mint), no proxy. I tried three times from both sides.

**Comment by Diadlo** [comment]
Is it still relevant?
