### ISSUE TITLE
"Failed to prepare statement "SELECT count(*) FROM sqlite_master" with error 26" while making an attempt to open chat logs by qTox

### ISSUE THREAD

**Issue by imf1ne86** [qTox/qTox#4408]
**qTox Version:**
Git commit: _5648106b34fc7dc3ad4e169651a0cbbd0139170a_
Built on:  14:11:53 May  5 2017 ( 1493993510 )

**Platform:**
Kernel: Linux 3.16.0-0.bpo.4-amd64 (x86_64)
Compiled: #1 SMP Debian 3.16.7-ckt4-3~bpo70+1 (2015-02-12)
Default C Compiler: GNU C Compiler version 4.7.2 (Debian 4.7.2-5) 
Distribution: Debian GNU/Linux 7.11

**Steps:**
1. Type "qtox" into a command line - a form with the "Имя пользователя" ("Username") field and the "Пароль" ("Password") field is returned
2. Type the correct data to get authenticated
3. Hit the "Загрузить" ("Load") button, watching at the same time what the application is printing into stdout - an error is being returned as a result

**Found Errors:**
1. The application returns a modal window with the text as follows, "qTox не может загрузить историю переписки, она будет отключена" ("qTox couldn't open your chat logs, they will be disabled") (see the "screenshot.png" file).

![screenshot](https://cloud.githubusercontent.com/assets/23280162/26042192/6f072cba-395d-11e7-968e-c0b469f0eb5a.png)

**Notes:**
1. In stdout, there are the following lines,
```
[03:10:07.417 UTC] persistence/db/rawdatabase.cpp:514 : Warning: Failed to prepare statement "SELECT count(*) FROM sqlite_master" with error 26
[03:10:07.417 UTC] persistence/db/rawdatabase.cpp:153 : Warning: Database is unusable, check that the password is correct
[03:10:07.479 UTC] persistence/profile.cpp:80 : Warning: Failed to open history for profile "ofdhdsfh34rewow"
```

**Comment by zetok** [comment]
Is is reproducible on 1.10.1? 1.6 that you're using is rather old.

**Comment by imf1ne86** [comment]
I am currently running:
qTox, ver. 1.6.0-obs
toxcore, ver. 0.0.0
Qt, ver. 5.6.1

qTox is taken from the official repository at http://download.opensuse.org/repositories/home:/antonbatenev:/tox/Debian_7.0/:

$ cat /etc/apt/sources.list | grep 'tox'
deb http://download.opensuse.org/repositories/home:/antonbatenev:/tox/Debian_7.0/ /

But I'm gonna get the latest version of qTox from Git:
$ git clone https://github.com/qTox/qTox.git
$ mkdir -p _build && cd _build && cmake ../ && make -j4

CMake Error at CMakeLists.txt:7 (cmake_minimum_required):
  CMake 2.8.11 or higher is required.  You are running version 2.8.9


-- Configuring incomplete, errors occurred!

Unfortunately, I cannot run 1.10.1 on Debian GNU/Linux 7.11.

**Comment by zetok** [comment]
> qTox is taken from the official repository at http://download.opensuse.org/repositories/home:/antonbatenev:/tox/Debian_7.0/

Since it has only outdated, buggy builds, it has been removed from official repos.

>Unfortunately, I cannot run 1.10.1 on Debian GNU/Linux 7.11.

Yeah, Debian 7 is not supported.

I'm closing the issue then, if you manage to reproduce it on newest qTox please comment for reopen.
