### ISSUE TITLE
Causing a segfault while trying to "permanently delete all chat history" on qTox

### ISSUE THREAD

**Issue by imf1ne86** [qTox/qTox#4409]
**qTox Version:**
Git commit: 5648106b34fc7dc3ad4e169651a0cbbd0139170a
Built on:  14:11:53 May  5 2017 ( 1493993510 )

**Platform:**
Kernel: Linux 3.16.0-0.bpo.4-amd64 (x86_64)
Compiled: #1 SMP Debian 3.16.7-ckt4-3~bpo70+1 (2015-02-12)
Default C Compiler: GNU C Compiler version 4.7.2 (Debian 4.7.2-5) 
Distribution: Debian GNU/Linux 7.11

**Steps:**
1. Repeat all the steps from Error #4408
2. Open the "Change your settings" tab
3. Then, choose the "Privacy" tab which is in the upper menu
4. Find the "Keep chat history" checkbox
5. Set it turned off - the program returns a message as follows, "Do you want to permanently delete all chat history?"
6. Choose the affirmative answer - an error is being returned as a result

**Found Errors:**
1. Causing a segfault while trying to "permanently delete all chat history" on qTox.

**Notes:**
1. This is dependant on Error #4408.

**Comment by zetok** [comment]
Is is reproducible on 1.10.1? 1.6 that you're using is rather old.

**Comment by imf1ne86** [comment]
I am currently running:
qTox, ver. 1.6.0-obs
toxcore, ver. 0.0.0
Qt, ver. 5.6.1

qTox is taken from the official repository at http://download.opensuse.org/repositories/home:/antonbatenev:/tox/Debian_7.0/:

$ cat /etc/apt/sources.list | grep 'tox'
deb http://download.opensuse.org/repositories/home:/antonbatenev:/tox/Debian_7.0/ /

But I'm gonna get the latest version of qTox from Git:
$ git clone https://github.com/qTox/qTox.git
$ mkdir -p _build && cd _build && cmake ../ && make -j4

CMake Error at CMakeLists.txt:7 (cmake_minimum_required):
  CMake 2.8.11 or higher is required.  You are running version 2.8.9


-- Configuring incomplete, errors occurred!

Unfortunately, I cannot run 1.10.1 on Debian GNU/Linux 7.11.

**Comment by zetok** [comment]
> qTox is taken from the official repository at http://download.opensuse.org/repositories/home:/antonbatenev:/tox/Debian_7.0/

Since it has only outdated, buggy builds, it has been removed from official repos.

>Unfortunately, I cannot run 1.10.1 on Debian GNU/Linux 7.11.

Yeah, Debian 7 is not supported.

I'm closing the issue then, if you manage to reproduce it on newest qTox please comment for reopen.
