### ISSUE TITLE
Long chat history causes absurdly long resizing time

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#4410]
Window resizing takes an absurd time when you have lots of chat history. I tried popping into the profile sqlite3 database and doing `drop table history` and that instantly fixed it. It is probably a _very_ bad idea to try to display such a long history at once.

OS: Linux Mint 18.1 Serana
qTox version:  qTox version v1.6.0-obs.
Commit hash:  5648106b34fc7dc3ad4e169651a0cbbd0139170a
toxcore version: 0.0.0 (bit confused about this one, but that's what it shows in the about section)
Qt version: 5.5.1
Hardware:  8GB i7 laptop with 256gb SSD. Everything else runs fine on it.
Reproducible: Always

Recommended solution: 

- Reduce visible history.
- Maybe add option to choose how much history qTox tries to display in the window.
- In the long term, maybe add interface for browsing qTox history. Might be a good idea in the short term to just make a shell script to browse history. I already implemented a crude version of that already, and can release it if anyone is interested.

Edit: Actually, I think the shell script would get too complicated if I wrote something reasonably sophisticated, with the ability to convert the sqlite tables into a decent display with who said what, etc. Might want to refactor with Python instead.

**Comment by yurivict** [comment]
Duplicate of https://github.com/qTox/qTox/issues/4215

**Comment by zetok** [comment]
@avrildev 
>Reduce visible history.

It's already limited to last 7 days, but yeah, it's not optimal and should be loaded dynamically (#1198).

>In the long term, maybe add interface for browsing qTox history. Might be a good idea in the short term to just make a shell script to browse history. I already implemented a crude version of that already, and can release it if anyone is interested.

You might want to check out https://github.com/sqlitebrowser/sqlitebrowser

Since the issue is a duplicate, closing.

**Comment by ghost** [comment]
@zetok @yurivict

I was wondering about that, but the person in question didn't recognize the fundamental issue being if you have a long chat history, so I didn't see this as a duplicate bug report. Hopefully at least my observations are noted?

Edit:
On the topic of sqlitebrowser, I meant a tool that'd be more designed for fuzzy searches and having a clean interface.
