### ISSUE TITLE
Can't compile on Raspbian Jessie

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#4413]
Attempting to compile with `simple_make.sh`. Compiled and installed ffmpeg manually (via `make install`).  Confirmed that `ld.so.conf.d/libc.conf` is present and contains reference to `/usr/local/lib`.

Build log: https://gist.github.com/avrildev/d46d277014a0fa0d5288612dacf16fce

Attempting to compile commit hash fd04a2832aa885d260ded4e476eefcddd49237b3 from stable branch.

**OS info**

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux
pi@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie

**Comment by sudden6** [comment]
please try to compile from the `v1.10.1` tag, those are the stable releases.

**Comment by Diadlo** [comment]
Can reproduce on master. But with another error
```
CMake Error at cmake/Dependencies.cmake:72 (message):
  LIBSWSCALE package, library or framework not found
```

**Comment by sudden6** [comment]
Google pointed me to our own bug report https://github.com/qTox/qTox/issues/2027

Please check if that fixes the issue.

**Comment by Diadlo** [comment]
Seems `sudo apt install libswscale-dev` fix it

**Comment by ghost** [comment]
@Diadlo Yeah, I ran into that problem, but didn't mention it because official compiling instructions gave that as a fix for a known problem on Debian. :P

@sudden6 Er, how do I compile from the `v1.10.1` tag? Sorry, still a bit of a git noob.

**Comment by sudden6** [comment]
@avrildev `git checkout v1.10.1`

**Comment by Diadlo** [comment]
@avrildev
```
git fetch origin
git checkout v1.10.1
```

**Comment by ghost** [comment]
@sudden6 Tried compiling from `v1.10.1`. Failed with similar error. (Some ffmpeg functions are declared out of scope apparently, maybe a header file is out of date?)

Build log: https://gist.github.com/avrildev/5b2789c1149eb61e3a2f3898e78b6a55

Edit:  _Apparently_ my account is flagged, because... well, they don't bother to give you a reason. I suppose my family did always tell me I talked like a robot.

Edit 2: unflagged, yay!

Edit 3: I read the git man page, and you can also clone from a tag like a branch, e.g.:

`git clone "https://github.com/qTox/qTox" -b "v1.10.1"`

Just in case anyone has popped in from a search engine and needs help with this.

**Comment by ghost** [comment]
I reinstalled ffmpeg, just to make sure it was installed properly. Rather than following the compiling instructions this time, I installed it as such:

`./configure --enable-shared --prefix=/usr`

`make -j$(nproc)`

`sudo make install`

`sudo ldconfig`

This resulted in yet another failed build in the same vein.

Edit: actually, it failed in a slightly different way. The error messages are similar, but it got 80% of the way before failing this time.

https://gist.github.com/avrildev/e41bbe19e764ff47f91740bc0fee574a

Will give the full log if it's relevant, just let me know.

Installed ffmpeg from ffmpeg-3.2.2.tar.bz2 tarball.

**Comment by sudden6** [comment]
I think in the last build log the error messages suggest that the linker couldn't find the necessary `*.so` files. That's progress^^

Where did ffmpeg get installed? It should be `/usr/local/lib` or `/usr/local/lib64` (not sure if both directories exist on Debian). Are you sure `--prefix=/usr` is correct? Did you remove all the files from the previous ffmpeg install?

**Comment by ghost** [comment]
@sudden6 I originally tried installing ffmpeg via the official qtox compilation instructions, which currently advise you to drop this bash script in `libs/` that then installs the important parts of the ffmpeg library in that one directory. So yeah, the machine should be clean of broken installs. I only skimmed the script, but since it didn't need sudo, it couldn't have installed globally.

The default prefix is `/usr/local/` I believe, which makes it install under `/usr/local/lib` `/usr/local/bin` etc. Changing it to `/usr` was meant as a precaution, as some programs ( `toxic`, I'm looking at you) apparently don't search under `/usr/local/lib` during runtime. (I'm pretty sure this has nothing to do with ldconfig, either. I did check and the glib conf for that includes `/usr/local/lib` under the directories searched.)

Anyway, back on topic, using `/usr` as the prefix theoretically means everything should be installed under `/usr/lib` or `/usr/lib64`... aaand I just noticed swscale is part of ffmpeg, so there are probably two versions installed. The one from the ffmpeg library, and the one from the debian repos. That might be causing conflict. BRB, testing this.
 
P.S. I checked and it was `/usr/lib`. `lib64` doesn't exist  on Raspbian apparently.

Edit: Apparently header files aren't installed by the ffmpeg package. Compilation complained about libswscale-dev missing.

**Comment by sudden6** [comment]
Unfortunately the install instructions are probably not really up to date. Can you update them with the steps you did when it works?

You should never manually install anything into `/usr/lib/*` it's package manager directory and breaks things, as you just discovered.

Having `libswscale` installed by ffmpeg and the debian packages is probably not a good idea.

**Comment by ghost** [comment]
@sudden6 I _knew_ it might break things, but my experience has been it also breaks things when you _don't_ install to `/usr/`. :P I am glad this project conforms to the standards, tho. I'll reinstall ffmpeg in `/usr/local` and report back.

**Comment by ghost** [comment]
@sudden6 It compiled! I don't know _why_ that worked, but apparently somehow the two versions of swscale were interfering with each other.

So now we know that  compiling ffmpeg from source, installing that globally, NOT CHANGING THE PREFIX,  works to build qTox on Raspbian. Would anyone be interested in pull requests on your build instructions? I'd like to replicate my experiment on a fresh raspberry pi install, then add instructions known to work on the latest Raspbian. They probably apply to Debian too, but wouldn't assume that without testing. :P

**Comment by sudden6** [comment]
A pull request will be very welcome.
