### ISSUE TITLE
Chat window is jerky/lagging by scrolling

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#4418]
##### Brief Description

OS: Mac OS X Sierra
qTox version: qTox-Version v1.10.1
Commit hash:  981953ef140e6c11a83078ac80647f912de1e07d
toxcore:  0.1.0
Qt-Version: 5.8.0  
Hardware:  Macbook Pro 13" (Touch Bar) Late 2016

Reproducible: Always

##### Steps to reproduce

1. go to a chat window
2. scroll down or up

##### Additional Info

- it isn't important how much text is in the chat window
- (my opinion) I think it is not really important for people who have understood online security as something important, however, a normal user will not change until this is fixed.

**Comment by sudden6** [comment]
I can't reproduce this on Linux, scrolling behaves normal there, maybe your Macbook is busy doing other stuff?

**Comment by ghost** [comment]
No, I have testet by looking on the mac task manager. Other Macbook Late 2016 13" Touch Bar users?

**Comment by ghost** [comment]
I have new installed qTox. Problem is fixed.
