### ISSUE TITLE
Crash when attempting to remove a circle with a user in it

### ISSUE THREAD

**Issue by guitarpicva** [qTox/qTox#4419]
##### Brief Description

OS: Windows 10 64-bit
qTox version: v1.9.0-104-g5d117e6
Commit hash: 5d117e6af854de194dc16575f1fe5c95a43741c8
toxcore: 0.1.8
Qt: 5.5.1
Hardware: 
…

Reproducible: Always 

##### Steps to reproduce
1. Add user to a new circle
2. Attempt to remove circle with a user in it

##### Observed Behavior
Crash when attempting to remove circle with a user in it

##### Expected Behavior
Warning dialog to instruct user to remove all people from the circle before removing it
--or--
Disable the menu item if the circle is not empty

**Comment by ezavod** [comment]
Can reproduce.
`git bisect` blames 4d806a36616e3d0a506c4385aba32cf5169054a7 as culprit.

> Expected Behavior
Warning dialog to instruct user to remove all people from the circle before removing it
--or--
Disable the menu item if the circle is not empty

Before this commit if a populated circle is deleted the contained contacts go back to the main list.

**Comment by Diadlo** [comment]
@ezavod Thanks for bisect. Can you test the PR? #4423
