### ISSUE TITLE
Style selector doesn't seem to affect other settings tabs

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#442]
The general tab changes, but as far as I can tell, the others don't. I'm mostly using the profile UI and the video combo box as my reference -- they don't look anything like the style/emote selectors.

@agilob

**Comment by tux3** [comment]
Rather the style changes are applied everywhere only after a restart (of qTox).

**Comment by agilob** [comment]
ok, I have fix for this, it reloads head and body from settingswidget.
