### ISSUE TITLE
don't work links in chats

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#4420]
##### Brief Description

OS: Windows 
qTox version: 1.9

Reproducible: Always

**Comment by ezavod** [comment]
@PKEv 
Could you please provide some more information (and maybe an example) what does not work for you.
This would make it a lot easier for somebody to fix it.

 Links work fine for me (qTox 65b1463933869db2d24d43d80e07c6013454bc18), except issue #4295.

**Comment by PKEv** [comment]
![default](https://cloud.githubusercontent.com/assets/6053197/26539851/268530fe-4457-11e7-8f75-fbb501598747.PNG)
After updating, the links become non-clickable

**Comment by PKEv** [comment]
Is there any configuration of link activity?
On another computer this is not (after the update)

**Comment by ezavod** [comment]
> Is there any configuration of link activity?

You are right, one could enable/disable links in `Settings -> User Interface -> Chat -> Text Style Format`.
Links work with: `Show formatting characters` or `Don't show formatting characters`.
They do not work when set to `Plaintext`!

Note: One has to **restart** qTox to update the displayed chat history.

**Comment by PKEv** [comment]
OK, this help

**Comment by Hasshu** [comment]
What if one doesn't need text formatting, but would like hyperlinks to be recognized?

This issue should be reopened.

**Comment by Diadlo** [comment]
cc @noavarice

**Comment by msva** [comment]
It is also strange thing, that "enabling links" (with a way that @ezavod mentioned above) brakes smileys (they become an "empty" icon).

And mostly bad thing is that previously qTox applied all the settings (including formatting and themes) on-the-fly just fine, and now it requires restart. I think, it's very fat regression 😿

**Comment by zetok** [comment]
@msva
>And mostly bad thing is that previously qTox applied all the settings (including formatting and themes) on-the-fly just fine, and now it requires restart. I think, it's very fat regression 😿

Not quite, formatting settings were and still are applied only to the new messages (or restart for all).

**Comment by msva** [comment]
Well, maybe only for incoming ones (if at all). I just checked it right now, and formatting options does not apply on new outgoing messages 😭

**Comment by msva** [comment]
well, my bad. I checked with wrong way :) You're right @zetok 

And also I've found that changing "plain text" to "bla-bla formatting characters" brakes rendering not for all ascii-smiles, but only some of them.

I guess, that ones containing "formatting symbols", lol.

For example, `:-/`, `:-*` and `^_^` 😀

**Comment by Diadlo** [comment]
Fixed in #4593

**Comment by Hasshu** [comment]
@Diadlo @noavarice We've got a regression: when a URL contains certain characters (like parentheses or Unicode), qTox now recognizes it only up to the offending character.

Try these links, for example:
https://en.wikipedia.org/wiki/Seal_(East_Asia)
https://ja.wikipedia.org/wiki/印章

Running qTox v1.13.0 (latest Windows build).

**Comment by msva** [comment]
To be honest, first one is broken even in other Qt apps (like "Psi" jabber 
client or KDE's "KMail" e-mail client)

**Comment by mschilli87** [comment]
@msva: Still, I can happily click (and follow) the link above in my Qt-based browser ([qutebrowser](https://www.qutebrowser.org/)). :wink:

**Comment by Diadlo** [comment]
@Hasshu It's different issue. Please, open new issue
