### ISSUE TITLE
Exclude Style Tags from copied URLs

### ISSUE THREAD

**Issue by ezavod** [qTox/qTox#4422]
##### Brief Description
qTox version: 65b1463933869db2d24d43d80e07c6013454bc18

Reproducible: Always

##### Steps to reproduce

1. Write `>https://qtox.github.io/` to a friend.
    Generally works if link is at the end of citation like `> look at this https://qtox.github.io/`.
2. Observe the normal looking link with citation mark in front.
3. Click the link (or do right click -> `Copy link address`)

##### Observed Behavior
The redirected/copied link is `https://qtox.github.io/</span>`

##### Expected Behavior
Exclude style tags.

##### Additional Info
Similar to #4295, but easier to solve, because the tag is generated by qTox and not some unpredictable user input.

**Comment by sudden6** [comment]
Can you confirm this is fixed by #4427 ?

**Comment by ezavod** [comment]
Solves the problem.
