### ISSUE TITLE
Custom bootstrap node

### ISSUE THREAD

**Issue by loskiq** [qTox/qTox#4429]
##### Brief Description

OS: Windows 7
qTox version: v1.9.0-104-g5d117e6
Commit hash:  5d117e6af854de194dc16575f1fe5c95a43741c8
toxcore:  0.1.8
Qt:  5.5.1
…

How to use a custom bootstrap node?

![image](https://cloud.githubusercontent.com/assets/22175047/26558731/a6389d2a-44b3-11e7-95f5-5680801725eb.png)

**Comment by sudden6** [comment]
You would have to edit `res/settings.ini` and recompile qTox. Why do you want to use a custom bootstrap node?

**Comment by loskiq** [comment]
@sudden6 I want to help Tox and I want a full anonymity

**Comment by Diadlo** [comment]
1) Custom bootstrap node don't change level of your anonymity. https://wiki.tox.chat/users/nodes#bootstrap_nodes
2) Anonymity -- not the goal of Tox.
3) If you want anonymity -- use Tor proxy.

**Comment by loskiq** [comment]
@sudden6 why is this option turned off by default?

**Comment by sudden6** [comment]
Because it isn't really needed, as Diadlo said a custom bootstrap node doesn't help your anonymity.

And if you run a bootstrap node, it's most useful if you make it available for everyone.

**Comment by loskiq** [comment]
@sudden6 then why do users create their nodes?

**Comment by sudden6** [comment]
Because to enter the Tox network you need some known "entry points" with a fixed IP. If you want to run your own bootstrap node and make it available to others you should go to the `#tox-dev` and `#toktok` IRC channels on freenode.

**Comment by zetok** [comment]
>You would have to edit `res/settings.ini` and recompile qTox.

Actually, one just needs to edit `settings.ini` that qTox places in the config dir.

>then why do users create their nodes?

In addition to what @sudden6 wrote, one can setup bootstrap node on a network that is not connected to the internet – that's practically the only case where one would want to use non-default bootstrap nodes. And if someone is going to setup bootstrap node, something like editing a config file to use the bootstrap node is not a problem. Thus no need for GUI setting.

If that answers your question, please close the issue.

**Comment by loskiq** [comment]
@zetok I found only the file `qtox.ini`

`[DHT%20Server]`
`useCustomList=true`
`dhtServerList\size=1`
`dhtServerList\1\name=a68366`
`dhtServerList\1\userId=AEC204B9A4501412D5F0BB67D9C81B5DB3EE6ADA64122D32A3E9B093D544327D`
`dhtServerList\1\address=51.254.84.212`
`dhtServerList\1\port=33445`

Correctly?

**Comment by quantumpacket** [comment]
One reason I see being able to customize the list is to prioritize/re-order servers so to choose the nearest ones. This can be made a read-only list, which you can drag and re-order. If I live in France I might want to prioritize connecting to European nodes before attempting to connect to nodes in North/South America. Not sure how much of a speed/reliability improvement that would make though. As for being able to add custom nodes using the UI, I don't see a compelling reason to do so.

**Comment by sudden6** [comment]
@loskiq yes, this looks correct.

@quantumpacket We deliberately choose random bootstrap nodes, because this balances the load evenly. AFAIK the distance to the bootstrap node has nearly no influence on the time it takes to connect to the DHT.

**Comment by mikhailnov** [comment]
I've made my own node and want qtox to use the first in  priority to make audio quality better, anonymity is not the most important factor.

I tried adding it to ~/.config/qtox/qtox.ini, but qtox overrides this list after startup

```
dhtServerList\1\address=tox.dumalogiya.ru
dhtServerList\1\name=mikhailnov
dhtServerList\1\port=33445
dhtServerList\1\userId=2DAE6EB8C16131761A675D7C723F618FBA9D29DD8B4E0A39E7E3E8D7055EF113
```

**Comment by loskiq** [comment]
@mikhailnov `useCustomList=true`

**Comment by zetok** [comment]
Since the original question seems to have been answered, closing the issue.
