### ISSUE TITLE
Image from camera is inverted vertically

### ISSUE THREAD

**Issue by and299** [qTox/qTox#4443]
##### Brief Description

OS: Linux OpenSuse 42.2
qTox version: Nightly
Commit hash: build without git
toxcore: 0.1.8
Qt: 5.6.1
Hardware: 
laptop Asus K50AB

Reproducible: Always 

##### Steps to reproduce

1. Inverted camera image vertically

##### Observed Behavior

Inverted camera image vertically

##### Additional Info

uTox camera image normal

Thanks!

----

More information on how to write good bug reports in the wiki: https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by zetok** [comment]
Sounds like a bug in FFmpeg. It should be reported upstream with more details, e.g. exact camera model.

**Comment by sudden6** [comment]
Closed because needed information was not provided.
