### ISSUE TITLE
qTox loads normally but messages/calls/videocalls & status icons not working. Is it bug?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#4444]
##### Brief Description

OS: Windows 10
qTox version: v1.9.0-104-g5d117e6.
Commit hash: 5d117e6af854de194dc16575f1fe5c95a43741e8
toxcore:  0.1.8
Qt:  5.5.1
Hardware:  
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. ?
2. 
3. …

##### Additional Info
(links, images, etc go here)

----

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by sudden6** [comment]
Can you please include the log file?

**Comment by sudden6** [comment]
Closed because needed information was not provided.
