### ISSUE TITLE
Regressing: links to file in  local network not worked

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#4445]
##### Brief Description

OS: Windows 
qTox version: 1.9

Reproducible: Always 

##### Steps to reproduce

1. copy file from local network
2. paste to message input field
3. send

##### Observed Behavior
Link is displayed as text

##### Expected Behavior
Link is displayed as a hyperlink with the ability to go and open a remote file

##### Additional Info
example: file://192.168.3.15/box/Agent

**Comment by ezavod** [comment]
Seems to be reproducible since 3e2bfdd5482daaa21dfa54b0f78125359ca16bad.
Only links to files on local machine (`file://localhost/box/Agent` or `file:///box/Agent`) work.

**Comment by PKEv** [comment]
Please return back very uncomfortable to use

**Comment by PKEv** [comment]
@noavarice please fix your bug

**Comment by noavarice** [comment]
I apologize for such a long waiting. This bug will be fixed as fast as I will get enough time, hopefully in next 1-2 days

**Comment by PKEv** [comment]
Please make corrections .... please

**Comment by anthonybilinski** [comment]
This looks like it was fixed in e9209b06. It isn't reproducible off tip.
