### ISSUE TITLE
Socks5 not working

### ISSUE THREAD

**Issue by loskiq** [qTox/qTox#4448]
##### Brief Description

OS: Windows 7 x64
qTox version: v1.10.0-56-g98a01df
Commit hash:  98a01dfefc6e4d9da254c635f19f5defd7a403bd
toxcore:  0.1.8
Qt:  5.5.1
Hardware:  Intel Pentium G3420
…

Program freezes

![image](https://cloud.githubusercontent.com/assets/22175047/26816600/1d4e6722-4a9b-11e7-8380-7ec9ee3ef542.png)

**Comment by sudden6** [comment]
@zetok IIRC you also had problems with proxies, could you solve them somehow?

**Comment by demonlite** [comment]
SOCKS5 proxy work for me on v1.10.2.
But! If "Enable UDP" is checked and wrong IP in address editbox the green status indicator is turned On. Only indicator. Message delivering are not work.

**Comment by Diadlo** [comment]
@demonlite Can you create separate issue?
@loskiq Can you check your issue on current master?

**Comment by loskiq** [comment]
@Diadlo Sorry, but I can not compile qTox from source code

**Comment by Diadlo** [comment]
@loskiq Ok. Can you download latest version?

**Comment by soredake** [comment]
Same problem, yesterdays master, after upgrading socks settings is lost, and when i trying to set proxy, qtox freezes.

**Comment by Diadlo** [comment]
@soredake Can you post qTox log here?

**Comment by soredake** [comment]
@Diadlo socks settings don't freeze qtox now on master.
