### ISSUE TITLE
[Regression] Changed save path on Windows

### ISSUE THREAD

**Issue by ezavod** [qTox/qTox#4449]
I used qTox (dd60edb3d77e92d42b4e5716595646146bfc2b55) on Windows 10 and all user data (profile, settings etc.) were saved in `%appdata%/tox/`.
After update to 98a01dfefc6e4d9da254c635f19f5defd7a403bd qTox is looking for user data in  `%appdata%/tox/qTox/tox/`(the `/qTox/tox/` dirs were newly created).
So it apperear as if there are no existing profiles and settings were reseted.

Could be solved by just coping files to new location, but this is confusing for novice users.
Furthermore this breaks the [wiki](https://github.com/qTox/qTox/wiki/Profile) pages about the profile.

Note:
Using Qt 5.6.2 and also reproducible under Win 7.
If one deletes `%appdata%/tox/` the newly created path starts with `%appdata%/Tox/`.
It appears to me as if f616ff36b6db9142f6e49b2b8bc436b6652aa329 is the cause.

**Comment by sudden6** [comment]
cc @Diadlo
