### ISSUE TITLE
[RESOLVED] Building qtox 1.10.2 on PCLinuxOS - redundant semicolon - "-D_REENTRANT;-pthread"

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#4457]
##### Brief Description

OS: PCLinuxOS (stable, rolling, fully updated)
qTox version: 1.10.2  
Commit hash:  b73603b45a32e63a649294537a62a9f11176c73d
toxcore:  0.1.8
Qt:  5.9.0

Reproducible: Always

##### Steps to reproduce

1. Try to compile

##### Observed Behavior
Critcal part of build log is:
`/usr/bin/c++  -DENABLE_SYSTRAY_GTK_BACKEND=1 -DENABLE_SYSTRAY_STATUSNOTIFIER_BACKEND=1 -DGIT_DESCRIBE=\"1.10.2\" -DGIT_VERSION=\"b73603b45a32e63a649294537a62a9f11176c73d\" -DLOG_TO_FILE=1 -DQTOX_PLATFORM_EXT=1 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_MESSAGELOGCONTEXT=1 -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DTIMESTAMP=1497124721 -I/home/marcin/src/rpm/BUILD/qTox-1.10.2/build/qtox_static_autogen/include -I/home/marcin/src/rpm/BUILD/qTox-1.10.2/build -I/home/marcin/src/rpm/BUILD/qTox-1.10.2 -I/usr/include/sqlcipher -I/usr/include/AL -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/directfb -I/usr/include/libdrm -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libxml2 -isystem /usr/lib64/qt5/include -isystem /usr/lib64/qt5/include/QtCore -isystem /usr/lib64/qt5/./mkspecs/linux-g++ -isystem /usr/lib64/qt5/include/QtGui -isystem /usr/lib64/qt5/include/QtNetwork -isystem /usr/lib64/qt5/include/QtOpenGL -isystem /usr/lib64/qt5/include/QtWidgets -isystem /usr/lib64/qt5/include/QtSql -isystem /usr/lib64/qt5/include/QtSvg -isystem /usr/lib64/qt5/include/QtXml  -O2  -pipe -Wformat -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -std=c++11 -fno-exceptions -fno-rtti -fPIE -Wstrict-overflow -Wstrict-aliasing -fstack-protector-all -Wstack-protector               -pthread  -D_REENTRANT;-pthread -DNDEBUG   -fPIC -std=gnu++11 -o CMakeFiles/qtox_static.dir/src/chatlog/chatlinecontent.cpp.o -c /home/marcin/src/rpm/BUILD/qTox-1.10.2/src/chatlog/chatlinecontent.cpp
c++: fatal error: no input files
compilation terminated.
/bin/sh: -pthread: command not found`

##### Additional Info
Available in attached **_qtox.txt_** file.

As you see in third subparagraph - I have working "hack", but want to fix / improve generating of compiler flags - it's rather on the system side, maybe not QTox, but maybe logs will give any information how to find ... IT - the alien which inserts semicolon ;]
[qtox.txt](https://github.com/qTox/qTox/files/1066109/qtox.txt)

Issue is similar to report #4175 . I don't want to double reports, but only give more information.

Another similar issue - [other project.](https://github.com/JuliaInterop/CxxWrap.jl/issues/26#issue-198030680)

**Comment by sudden6** [comment]
PCLinuxOS is a BSD right? I think this issue has been solved with cf72136b1417fd43c0c2db56f59c1500be80cf20 please try again with newest master.

**Comment by Diadlo** [comment]
@sudden6 Not. It's just fix #4439

**Comment by sudden6** [comment]
I'm still not sure whether @yurivict meant this fixes all the cmake problems or just one...

**Comment by Diadlo** [comment]
cf72136b1417fd43c0c2db56f59c1500be80cf20 just remove using [update-versions.sh](https://github.com/qTox/qTox/blob/master/tools/update-versions.sh), which doesn't touch CMake at all

**Comment by ghost** [comment]
It's ordinary linux - uname -a
`Linux pclos 4.8.12-pclos1 #1 SMP Fri Dec 2 15:35:43 CST 2016 x86_64 x86_64 x86_64 GNU/Linux`

Compiling the latest master source code gives the same error.

**Comment by sudden6** [comment]
Then there must be some bug in our cmake scripts

**Comment by zetok** [comment]
The only place where it could be added is https://github.com/qTox/qTox/blob/d90a60bdf7abcc03b0c74fae6f9f3b4bd43b76ed/cmake/Dependencies.cmake#L77

**Comment by ghost** [comment]
Some time ago I've been built packages for Mageia Cauldron ... works without any hacks. I suspect PCLinuxOS settings but can't find it ...
`ls -lah *tox*`
`-rw-r--r-- 1 marcin marcin 3,5M 05-15 20:08 qtox-1.10.0-1.mga6.src.rpm`
`-rw-r--r-- 1 marcin marcin 444K 05-13 19:40 toxcore-0.1.8-1.mga6.src.rpm`

 [Look here](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/qtox) - in Arch Linux there is PURE cmake - without any macros. It's building without any errors. Maybe GCC version or something ... 

@zetok 
I you will have proposal how to modify thie line you've mentioned - I'll test it soon.
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${${pkg}_CFLAGS_OTHER}" PARENT_SCOPE)`

**Comment by zetok** [comment]
Could be `pkg-config`

**Comment by ghost** [comment]
Ok - this change:
`%__sed -i 's/set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${${pkg}_CFLAGS_OTHER}" PARENT_SCOPE)/set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${${pkg-config}_CFLAGS_OTHER}" PARENT_SCOPE)/g' cmake/Dependencies.cmake`

**produces this set of flags - there is lack of -pthread at all?**
`/usr/bin/c++  -DENABLE_SYSTRAY_GTK_BACKEND=1 -DENABLE_SYSTRAY_STATUSNOTIFIER_BACKEND=1 -DGIT_DESCRIBE=\"1.10.2\" -DGIT_VERSION=\"b73603b45a32e63a649294537a62a9f11176c73d\" -DLOG_TO_FILE=1 -DQTOX_PLATFORM_EXT=1 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_MESSAGELOGCONTEXT=1 -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DTIMESTAMP=1497134854 -I/home/marcin/src/rpm/BUILD/qTox-1.10.2/build/qtox_static_autogen/include -I/home/marcin/src/rpm/BUILD/qTox-1.10.2/build -I/home/marcin/src/rpm/BUILD/qTox-1.10.2 -I/usr/include/sqlcipher -I/usr/include/AL -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/directfb -I/usr/include/libdrm -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libxml2 -isystem /usr/lib64/qt5/include -isystem /usr/lib64/qt5/include/QtCore -isystem /usr/lib64/qt5/./mkspecs/linux-g++ -isystem /usr/lib64/qt5/include/QtGui -isystem /usr/lib64/qt5/include/QtNetwork -isystem /usr/lib64/qt5/include/QtOpenGL -isystem /usr/lib64/qt5/include/QtWidgets -isystem /usr/lib64/qt5/include/QtSql -isystem /usr/lib64/qt5/include/QtSvg -isystem /usr/lib64/qt5/include/QtXml  -O2  -pipe -Wformat -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -std=c++11 -fno-exceptions -fno-rtti -fPIE -Wstrict-overflow -Wstrict-aliasing -fstack-protector-all -Wstack-protector                  -DNDEBUG   -fPIC -std=gnu++11 -o CMakeFiles/qtox_static.dir/src/widget/friendwidget.cpp.o -c /home/marcin/src/rpm/BUILD/qTox-1.10.2/src/widget/friendwidget.cpp`

**I've forgotten to show this listing before - there is no semicolon:**
`pkg-config gtk+-2.0 --cflags`
Result:
`-D_REENTRANT -pthread -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/directfb -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/harfbuzz -I/usr/include/libxml2 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include`

**_How to live? ;-D_**

**Comment by sudden6** [comment]
The semicolon could be created by cmakes internal list handling

**Comment by yurivict** [comment]
@sudden6 When I first found the problem with failing sed, it has built for me on the FreeBSD. But for some reason now I can't repeat this, and it fails after the sed problem has been fixed. So there is still a problem with cmake.

**Comment by yurivict** [comment]
On FreeBSD, the problem involves ```-D_THREAD_SAFE;-pthread```. cmake doesn't like -D_THREAD_SAFE in .pc files.

The file ```/usr/local/libdata/pkgconfig/x11.pc``` has ```Cflags: -I${includedir} -D_THREAD_SAFE``` 
The file ```/usr/local/libdata/pkgconfig/check.pc``` has ```Cflags: -I${includedir} -D_THREAD_SAFE -pthread```

cmake build succeeds when ```-D_THREAD_SAFE``` is removed from those lines.

**Comment by Diadlo** [comment]
@yurivict check dependency was removed. So problem in x11.pc?

**Comment by yurivict** [comment]
@Diadlo Yes, the problem now is only with x11.pc. Try adding some define on linux into your x11.pc, you might get the same crash. This might just be a generic cmake bug that it doesn't remove semicolons when -D is present in pkg-config output.

**Comment by Diadlo** [comment]
https://cmake.org/pipermail/cmake/2013-June/055182.html

**Comment by yurivict** [comment]
Isn't cmake supposed to strip semicolons by itself? It itself adds them.
In any case, I created a bug report https://gitlab.kitware.com/cmake/cmake/issues/16958

**Comment by ghost** [comment]
Maybe [**this**](https://cmake.org/Wiki/CMake_FAQ#Why_do_I_have_unwanted_semicolons_.3B_in_my_compiler_flags.3F) will help with something.

##### Why do I have unwanted semicolons ; in my compiler flags?

> CMake has a list data type. A list is stored as a string of semicolon-separated list elements. Whitespace separated arguments to a SET statement are interpreted as list elements. For instance, SET(var a b c d e) will give "var" a value of a;b;c;d;e and this list can be used by other CMake commands. However, if you pass ${var} to a non-CMake external tool, such as a compiler's command line, you are passing a;b;c;d;e which is not what you want. Instead you either need to pass "${var}", so that the list will be converted to a whitespace-separated string, or you need to SET(var "a b c d e") in the 1st place so that you're working with a string, not a list.

**Comment by yurivict** [comment]
826e1c3 still fails.

**Comment by Diadlo** [comment]
Seems, it's problem with PkgConfig cmake package

**Comment by Diadlo** [comment]
https://gist.github.com/Diadlo/59b7dd16f40075676e7d17c5219a4a51

**Comment by yurivict** [comment]
Let upstream cmake deal with this. The workaround is good enough.

**Comment by ghost** [comment]
Added this [patch](http://wklej.org/hash/55ac5b0a552/txt/) - with no luck.

**Comment by Diadlo** [comment]
@marcin-82 Try to add `"` around `${_pkgconfig_invoke_result}` in `/usr/share/cmake-3.8/Modules/FindPkgConfig.cmake` (path can be a bit different)

**Comment by yurivict** [comment]
@marcin-82  try 1755f42

**Comment by ghost** [comment]
Added double quotes in penultimate line:
```root@pclos ~# grep "\${_pkgconfig_invoke_result}" /usr/share/cmake/Modules/FindPkgConfig.cmake```

```
    string(REGEX REPLACE "[\r\n]"                  " " _pkgconfig_invoke_result "${_pkgconfig_invoke_result}")
      string(REGEX REPLACE "${_regexp}" " " _pkgconfig_invoke_result "${_pkgconfig_invoke_result}")
    #message(STATUS "  ${_varname} ... ${_pkgconfig_invoke_result}")
    set(_pkgconfig_${_varname} "${_pkgconfig_invoke_result}")
    _pkgconfig_set(${_prefix}_${_varname} "${_pkgconfig_invoke_result}")
```

_EDITED_
Still no luck

**Comment by Diadlo** [comment]
@marcin-82 JFYI: Github supports multiline text with \``` $text_here \```. Can you update your output?

**Comment by ghost** [comment]
OK. Finally I applied patch in place mentioned by @yurivict . It works - rpm building ends with success. Thank you very much: **_authors and all contributors_** in this thread. I also thanks user [tele.](https://github.com/tele1)

I'ts more gentle solution that brute force sed ;]

Because we're targeted to packaging last stable releases, I've used QTox 1.10.2 release and added just two patches (cmake flags fix and desktop file fix). All went good.

``` 
# Patch source
# https://github.com/qTox/qTox/issues/4457
# https://github.com/qTox/qTox/commit/1755f426d9869a1bdad581b12cde2f7e67f5f5d2

--- qTox-1.10.2.orig/CMakeLists.txt     2017-06-01 21:02:25.007729664 +0200
+++ qTox-1.10.2/CMakeLists.txt  2017-06-11 11:43:29.755035080 +0200
@@ -522,6 +522,15 @@
   ${PROJECT_NAME}_static
   ${ALL_LIBRARIES})
 
+# Workaround for CMake bug when using it with pkg-config.
+# Workaround from: https://cmake.org/pipermail/cmake/2013-June/055182.html
+# qTox issues: #4175 #4457
+# Upstream issue: https://gitlab.kitware.com/cmake/cmake/issues/16958
+#
+# Remove this workaround when we no longer need to support CMake that does
+# not include the fix.
+string(REPLACE ";" " " CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
+
 # test(s?) are broken on osx (just travis?)
 if (NOT APPLE)
     include(Testing)
```

Info about installed package:
```
[root@pclos ~]# rpm -qi qtox
Name        : qtox                         Relocations: (not relocatable)
Version     : 1.10.2                            Vendor: PCLinuxOS
Release     : 2pclos2017                    Build Date: nie, 11 cze 2017, 12:15:03
Install Date: nie, 11 cze 2017, 12:18:47       Build Host: pclos
Group       : Networking/Instant messaging   Source RPM: qtox-1.10.2-2pclos2017.src.rpm
Size        : 12263862                         License: GPLv3
Signature   : (none)
Packager    : 
URL         : https://qtox.github.io/
Summary     : Powerful Tox client written in C++/Qt that follows the Tox design guidelines
Description :
Powerful Tox client written in C++/Qt that follows the Tox design guidelines.
```
