### ISSUE TITLE
instuctions for compiling qtox lacks finding compiled toxcore, Fedora 25

### ISSUE THREAD

**Issue by jontis** [qTox/qTox#4468]
when compiling qtox with cmake, it will not find your manually compiled toxcore.
You need to add the directory containing libtoxcore.pc to your PKG_CONFIG_PATH

check for presence with pkg-config --libs libtoxcore

**Comment by sudden6** [comment]
On my system `make install` installs toxcore into `/usr/local/` by default. This directory is also in the default search path for `pkg-config`. Is this different on Fedora?

**Comment by jontis** [comment]
maybe. I have successfully compiled this app. This issue post is to help others do the same and spread the usage of tox.
I am using a Fedora 25 - 64 system, upgraded from F24.
Toxcore, by manual compilation, has been automatically installed to /usr/local/lib
pkg-config default search directories for my systems seems to be:
/usr/lib64/pkgconfig
/usr/share/pkgconfig

please let me know how I can help more.

**Comment by noavarice** [comment]
I have the same issue with installing libtoxcore on Fedora 25 because PKG_CONFIG_PATH was not configured by default

**Comment by sudden6** [comment]
Can one of you make a PR and point this out for Fedora in `INSTALL.md`?

**Comment by zetok** [comment]
Closed in 5f418538817a2a8094717d9f1c793b356f1a53b2
