### ISSUE TITLE
qTox does not handle common POSIX signals and quits abruptly

### ISSUE THREAD

**Issue by Talkless** [qTox/qTox#4470]
##### Brief Description

OS: Linux (and probably macOS?)
qTox version: current HEAD
Qt:  5.3.2, 5.9.0

Reproducible: Always

##### Steps to reproduce

**Case #1:** 
1. Launch qTox in terminal.
2. Close terminal.
3. qTox quits with `SIGHUP` signal, without `Debug: Clean exit with status 0` to log - abruptly.

**Case #2:**
1. Launch qTox in terminal.
2. Press `Ctrl + C`.
3. qTox quits with `SIGINT` signal, again abruptly.

**Case #3:**
1. Launch qTox in any way
2. Terminate it using your favourite GUI task manager or with `killall`
3. qTox quits with `SIGTERM` signal, again abruptly.

##### Observed Behavior

Terminating qTox with POSIX signal does not write last debug message, this is evidence that `main`() did not finish, so Qt event loop did not quit, destructors not called, etc, etc. This might corrupt user data.

##### Expected Behavior

qTox should quit cleanly when terminated with common POSIX signals such as `SIGINT`, `SIGHUP` and `SIGTERM`.

**Comment by Talkless** [comment]
I am willing to provide PR for this bug.

I would like to suggest to implement `PosixSignalNotifier`, or `NativeQuitNotifier` (when fixing possible Windows logout issues too, making it cross-platform) helper class that would catch common OS-native quit notifications, and forward it to `QCoreApplication::quit()` so that qTox could exit properly.

**Comment by sudden6** [comment]
@Talkless Yes, a PR will be very welcome. Maybe we should also implement http://doc.qt.io/qt-4.8/qcoreapplication.html#aboutToQuit correctly.

**Comment by Talkless** [comment]
@sudden6 about `aboutToQuit`: I am not very familiar with qTox internals yet, but I imagine good-behaving application should clean up appropriately by destructors in main(), though again, I lack qTox specifics to comment that. 

Please elaborate if it's relevant to this task.

**Comment by sudden6** [comment]
If I read the docs to http://doc.qt.io/qt-5.6/qapplication.html#exec correctly, this signal should be used to handle cleanup tasks (In qTox mainly the db and saving settings). I'm not entirely sure if we should also do this in qTox or if this is in scope for your idea, but it may be worth a look.

**Comment by Diadlo** [comment]
@sudden6 unfortunately `aboutToQuit` not fix the issue

**Comment by Talkless** [comment]
@Diadlo @sudden6 @zetok 
Should I add this helper class to:

- src/platform/posixsignalnotifier.h
- src/platform/signal/posixsignalnotifier.h
- src/platform/unix/posixsignalnotifier.h
- src/unix/posixsignalnotifier.h
- ???

I doubt it needs QTOX_PLATFORM_EXT switch as id toes not need extra dependencies.

And off-topic question: what's up with decision to use lower case file names? It hurts eyes trying to read longer file names without either camel or snake case...

**Comment by Talkless** [comment]
Also, what BSD would you recommend for testing qTox ? TrueOS, PC-BSD, ..? I would like to spend as less time as possible for installing/configuring...

**Comment by Diadlo** [comment]
@Talkless I don't mind about camelCase in file names, if no one has an objection we can change it in project. 
You class will be platform-dependent -> it should be in `src/platform`. Currently we don't split classes in `src/platofrm` by system, so IMO `unix` subfolder superfluous.
Feel free to test on whatever platform you want. I hope, @yurivict will help with testing on FreeBSD

**Comment by sudden6** [comment]
Personally I'd prefer staying with lowercase filenames, because this seems to be the Unix/Linux standard way and is probably the most compatible way. Also Qt has it's source code with this convention and I think it could lead to problems with Linux <-> Windows.

I agree with @Diadlo, you should put it in `src/platform`.

**Comment by yurivict** [comment]
> I hope, @yurivict will help with testing on FreeBSD

@Diadlo  any time, just tell me what to test.

**Comment by Talkless** [comment]
I would like to test myself before bothering anyone here. @yurivict could you recommend TrueOS/PC-BSD or whatever for easies entry? 

Also, there are no FreeBSD build instructions in INSTALL.md...

**Comment by Talkless** [comment]
@yurivict I've installed TrueOS, but cmake fails to find toxcore.

`bootstrap.sh` compiled tox (had to create fake /usr/local/bin/nproc), and it is installed:
```
 ../configure_aux/install-sh -c -d '/usr/local/bin'
  /bin/sh ../libtool   --mode=install /usr/bin/install -c DHT_bootstrap '/usr/local/bin'
libtool: install: /usr/bin/install -c .libs/DHT_bootstrap /usr/local/bin/DHT_bootstrap
 ../configure_aux/install-sh -c -d '/usr/local/include/tox'
 /usr/bin/install -c -m 644 ../toxav/toxav.h '/usr/local/include/tox'
 ../configure_aux/install-sh -c -d '/usr/local/include/tox'
 /usr/bin/install -c -m 644 ../toxcore/tox.h '/usr/local/include/tox'
 ../configure_aux/install-sh -c -d '/usr/local/include/tox'
 /usr/bin/install -c -m 644 ../toxdns/toxdns.h '/usr/local/include/tox'
 ../configure_aux/install-sh -c -d '/usr/local/include/tox'
 /usr/bin/install -c -m 644 ../toxencryptsave/toxencryptsave.h '/usr/local/include/tox'
 configure_aux/install-sh -c -d '/usr/local/lib/pkgconfig'
 /usr/bin/install -c -m 644 ./libtoxcore.pc ./libtoxav.pc '/usr/local/lib/pkgconfig'
```

But `cmake` does not find it:
```
-- Checking for one of the modules 'toxcore'
-- TOXCORE not found
-- Checking for one of the modules 'toxav'
-- TOXAV not found
-- Checking for one of the modules 'toxencryptsave'
-- TOXENCRYPTSAVE not found
-- Checking for one of the modules 'libtoxcore'
CMake Error at cmake/Dependencies.cmake:70 (message):
  TOXCORE package, library or framework not found
Call Stack (most recent call first):
  cmake/Dependencies.cmake:113 (search_dependency)
  CMakeLists.txt:80 (include)
```
I guess it's something with pkg-config..? How do I tell CMake to find tox usr /usr/local..?

**Comment by yurivict** [comment]
@Talkless 
> Also, there are no FreeBSD build instructions in INSTALL.md...

pkg install qTox

**Comment by Talkless** [comment]
Uhm, I want to compile and test new feature what is not yet available in repos...

**Comment by yurivict** [comment]
> Uhm, I want to compile and test new feature what is not yet available in repos...

qTox port has a switch.

**Comment by Talkless** [comment]
Could you please elaborate how do I use ports to compile qTox. I am completely geen on FreeBSD.

I need it to fetch specific branch from my github repo.

**Comment by Talkless** [comment]
@sudden6 @Diadlo Do you know who could compile and test my [signals branch](https://github.com/Talkless/qTox/tree/signals) on macOS?
Basically, test is like this:

1. run qTox, can be launched in terminal.
2. terminate qtox using four different signals:
`killall -SIGHUP qtox`
`killall -SIGINT qtox`
`killall -SIGQUIT qtox`
` killall -SIGTERM qtox`

In all cases, qtox output (or log) should have "Exit with status 0" last entry, meaning it quit in the right way.

**Comment by Diadlo** [comment]
@Talkless Currently -- no one :(

**Comment by yurivict** [comment]
> I need it to fetch specific branch from my github repo.

Set: ```GH_TAGNAME=xxxxxxx```

Run:  ```make makesum install clean```

**Comment by Talkless** [comment]
OK I've managed to build, thanks @yurivict .
