### ISSUE TITLE
Windows downloads broken

### ISSUE THREAD

**Issue by raingloom** [qTox/qTox#4485]
Friend told me they couldn't download the hot new chat thingy I recommended. I checked and I can't either. I get an empty page with some JavaScript, I have NoJS, so I whitelisted and reloaded. Still nothing.

They are not at all tech savvy so compiling is out of the question, I installed it for myself via `pacman` on Arhc Linux, so I'm good.

AFAIK they are not on any weird network, I know my network has some weird firewalling but so far it only broke GOG's downloads.

What's going on here?

**Comment by Diadlo** [comment]
@sudden6 Is it related with your jenkins work?

**Comment by Diadlo** [comment]
@raingloom It's about windows installer?

**Comment by sudden6** [comment]
@Diadlo no, these builds are not live on the website

**Comment by Diadlo** [comment]
cc @tux3

**Comment by sudden6** [comment]
build.tox.chat seems down

**Comment by Diadlo** [comment]
Seems, fixed
