### ISSUE TITLE
Memory leak on Linux

### ISSUE THREAD

**Issue by kargaroc** [qTox/qTox#4486]
##### Brief Description

OS: Arch Linux (updated 22-Jun-2017)
qTox version: latest git
Commit hash:  8b6d3a19efd12d66ca69b5c57647c536ef910365
toxcore:  1:0.1.9-3 (stable Arch package)
Qt:  5.9.0
Hardware:  Linux x86_64 + Nvidia property driver
…

Reproducible: Sometimes

##### Steps to reproduce

1. Launch qTox and sign in
2. Go to the settings a flip through a few tabs
3. Click on the call button a few times (even if it does nothing)

##### Observed Behavior
The memory usage of the program skyrockets

##### Expected Behavior
The memory usage of the program should stay more or less the same

##### Additional Info

----
[qtox.log.gz](https://github.com/qTox/qTox/files/1098957/qtox.log.gz)

**Comment by kargaroc** [comment]
I'm willing to bet this is a Toxcore bug, since it happens in the Toxic client as well.  Either that or its in Pulseaudio or whatever.  In Toxic, all you need to do is get a sound to play, and it crashes and leaks memory.

Running it in GDB and LLDB suggests something about __lll_lock_wait() but I don't know if that's relevant.

**Comment by yurivict** [comment]
You can build qTox with debug info, and use google perftools to find what loses memory: http://goog-perftools.sourceforge.net/doc/heap_profiler.html

**Comment by a-no-n** [comment]
This seems to be caused by audio output devices. You can avoid this in the meantime by setting
`audioOutDevEnabled=false`
in qtox.ini

**Comment by a-no-n** [comment]
I've narrowed this down to OpenAL 1.18 - Downgrading to 1.17 fixes the memory leak in qTox and other clients. Is this something handled in each client or in toxcore?

**Comment by yurivict** [comment]
Looks like you should report it to OpenAL then.

**Comment by a-no-n** [comment]
@yurivict 
[Already fixed upstream in OpenAL](https://github.com/kcat/openal-soft/commit/d4f3490a880f779f460332689a396ade69840f50) . It will  be included in 1.18.1 . Might as well close since this isn't a qTox issue.

**Comment by yurivict** [comment]
You can close this bug then.
