### ISSUE TITLE
Compile error on cameradevice.cpp

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#4487]
##### Brief Description

OS: Xubuntu 16.04 LTS, 32 bit
qTox version: 1.10.2
Commit hash: release version from GITHub (https://github.com/qTox/qTox/releases)
Qt:  5.5.1
Hardware: Desktop PC  

Reproducible: Always 

##### Steps to reproduce

Followed exactly the instructions from https://github.com/qTox/qTox/blob/master/INSTALL.md, including installation of all dependencies.

##### Observed Behavior

cmake succeeds flawlessly. Building then fails at
```
[ 45%] Building CXX object CMakeFiles/qtox_static.dir/src/video/cameradevice.cpp.o
/Data/qTox-1.10.2/src/video/cameradevice.cpp: In static member function ‘static QVector<QPair<QString, QString> > CameraDevice::getRawDeviceListGeneric()’:
/Data/qTox-1.10.2/src/video/cameradevice.cpp:275:74: error: ‘const AVClass {aka const struct AVClass}’ has no member named ‘category’
     if (!iformat->priv_class || !AV_IS_INPUT_DEVICE(iformat->priv_class->category)) {
                                                                          ^
/Data/qTox-1.10.2/src/video/cameradevice.cpp:275:82: error: ‘AV_IS_INPUT_DEVICE’ was not declared in this scope
     if (!iformat->priv_class || !AV_IS_INPUT_DEVICE(iformat->priv_class->category)) {
                                                                                  ^
/Data/qTox-1.10.2/src/video/cameradevice.cpp:289:45: error: ‘av_opt_set_defaults’ was not declared in this scope
             av_opt_set_defaults(s->priv_data);
```
..and many more error messages.

##### Expected Behavior

Building succeeds.

##### Additional Info

I do have qTox installed on this computer (commit hash 5648106b34fc7dc3ad4e169651a0cbbd0139170a), which works well. This version I obtained (I think) via the .deb package.

I also managed to compile exactly the 1.10.2 version successfully on a 64-bit laptop, with otherwise identical Xubuntu system.

**Comment by sudden6** [comment]
can you check the installed versions of ffmpeg and it's header files?

**Comment by ghost** [comment]
On both computer I get the identical output:
```
$ ffmpeg
ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
```
I don't know how to check versions of the header file. I do find on the 32 bit computer, as example,
```
$ locate avcodec.h
/usr/include/i386-linux-gnu/libavcodec/avcodec.h
/usr/include/i386-linux-gnu/libavfilter/avcodec.h
/usr/local/include/libavcodec/avcodec.h
```
On the 64-bit machine only the first two appear (with x86_64 prefix).

Could you please advise how I get useful information on the header file versions?

**Comment by sudden6** [comment]
`dpkg -s ffmpeg-devel` and `dpkg -s ffmpeg` should produce the output we need.

**Comment by ghost** [comment]
If get on the 32-bit machine (where the qTox compilation fails):
```
$ dpkg -s ffmpeg-devel
dpkg-query: package 'ffmpeg-devel' is not installed and no information is available

$ dpkg -s ffmpeg
Package: ffmpeg
Status: install ok installed
Priority: optional
Section: video
Installed-Size: 1887
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: i386
Multi-Arch: foreign
Version: 7:2.8.11-0ubuntu0.16.04.1
Replaces: libav-tools (<< 6:12~~), qt-faststart (<< 7:2.7.1-3~)
Depends: libavcodec-ffmpeg56 (>= 7:2.7) | libavcodec-ffmpeg-extra56 (>= 7:2.7), libavdevice-ffmpeg56 (>= 7:2.6), libavfilter-ffmpeg5 (>= 7:2.4), libavformat-ffmpeg56 (>= 7:2.6), libavresample-ffmpeg2 (>= 7:2.4), libavutil-ffmpeg54 (>= 7:2.5), libc6 (>= 2.4), libpostproc-ffmpeg53 (>= 7:2.4), libsdl1.2debian (>= 1.2.11), libswresample-ffmpeg1 (>= 7:2.4), libswscale-ffmpeg3 (>= 7:2.4), libvdpau1 (>= 0.2), libx11-6
Suggests: ffmpeg-doc
Breaks: libav-tools (<< 6:12~~), qt-faststart (<< 7:2.7.1-3~)
Conffiles:
 /etc/ffserver.conf 81b94256d412c37f0f81214b3737ac53
Description: Tools for transcoding, streaming and playing of multimedia files
 FFmpeg is the leading multimedia framework, able to decode, encode, transcode,
 mux, demux, stream, filter and play pretty much anything that humans and
 machines have created. It supports the most obscure ancient formats up to the
 cutting edge.
 .
 This package contains:
  * ffmpeg: a command line tool to convert multimedia files between formats
  * ffserver: a multimedia streaming server for live broadcasts
  * ffplay: a simple media player based on SDL and the FFmpeg libraries
  * ffprobe: a simple multimedia stream analyzer
  * qt-faststart: a utility to rearrange Quicktime files
Homepage: https://ffmpeg.org/
Original-Maintainer: Debian Multimedia Maintainers <pkg-multimedia-maintainers@lists.alioth.debian.org>
```
The result on the 64-bit machine is identical (also that `ffmpeg-devel` is not installed), except that it says `Installed-Size: 1855`, and of course `Architecture: amd64`.

**Comment by ghost** [comment]
In the meantime I upgraded the 32-bit computer to xubuntu 17.10. I still get the same error message when compiling. Is there some advice how to proceed?

**Comment by Diadlo** [comment]
@OGZH-GIT Try to install `ffmpeg-devel`

**Comment by ghost** [comment]
Thanks, I tried this before, but searching for this in Synaptic results in the attached screen shot, which seems to indicate that all is installed. However, there might be other things belonging to `ffmeg-devel` which Synaptic does not find and I don't know about. 
![screenshot_2017-10-21_16-09-14](https://user-images.githubusercontent.com/16050452/31852585-6b1476ae-b67a-11e7-81e3-343e47bd5f26.png)

**Comment by sudden6** [comment]
can you try with the newest tag `v1.12.1`? I think 1.10.2 doesn't have support for ffmpeg > 2.8

**Comment by ghost** [comment]
My last attempts were already with `v1.12.1`.

**Comment by ghost** [comment]
Positive: I tried it with a fresh grml boot from a xubuntu 17.10 32-bit iso image. Using ` ./simple_make.sh`, the crucial step `Building CXX object CMakeFiles/qtox_static.dir/src/video/camerasource.cpp.o` succeeded.
Negative: Still, on my usual computer the compilation error persists, even when using the script. Must be a particular incompatibility, maybe with `libavutil`, where some of the symbols mentioned in the compilation error seem to come from.

**Comment by ghost** [comment]
Following the inspiration from the previous post: I realized that I have two installations of the libav... libraries, one in `/usr/local/include`, one in `/usr/include/i386-linux-gnu`, the former possibly manually installed much earlier. After removing/renaming the local versions, and similar with `/usr/local/lib`/`/usr/lib/i386-linux-gnu`, qTox compiles and links now successfully.
