### ISSUE TITLE
Multiple Windows: Disable Sidebar?

### ISSUE THREAD

**Issue by yani** [qTox/qTox#4490]
Is it normal behavior, that when you have both options for multiple individual windows checked; that those windows still have the active chats list, but only with one chat?

You can hide the list by dragging it to the side, but the chat window does not remember this, and resets it after it's been closed.

![](https://v0id.us/uploads/qtox_2017-06-26_00-12-02.png)

**Comment by Diadlo** [comment]
Use cursor to resize this part. It will hide when you resize it to small width

**Comment by yani** [comment]
That's what I said:

"You can hide the list by dragging it off screen, but the chat window does not remember this, and resets it after it's been closed."

I should have used "dragging it to the side"

**Comment by ezavod** [comment]
@Yanikore Which commit hash do you use?
Probably duplicate of #4387.
If possible try latest master.

**Comment by yani** [comment]
Yes it seems to be a duplicate.

I'm using version 1.10.2 through the Windows installer.
