### ISSUE TITLE
project sends me mail

### ISSUE THREAD

**Issue by Tux** [qTox/qTox#450]
I do not have anything to do with this project, but still I get mail for every change.
I assume someone added the wrong tux to the receiver list
I am NOT tux3
Could you please take me off the qTox notification list?

**Comment by dubslow** [comment]
Lol, that's awkward. You don't have it in your watch list, right?

**Comment by Tux** [comment]
On Fri, 17 Oct 2014 05:31:19 -0700, dubslow notifications@github.com
wrote:

> Lol, that's awkward. You don't have it in your watch list, right?

Correct

## 

H.Merijn Brand  http://tux.nl   Perl Monger  http://amsterdam.pm.org/
using perl5.00307 .. 5.21   porting perl5 on HP-UX, AIX, and openSUSE
http://mirrors.develooper.com/hpux/        http://www.test-smoke.org/
http://qa.perl.org   http://www.goldmark.org/jeff/stupid-disclaimers/

**Comment by tux3** [comment]
It seems that someone @ mentionned you by mistake (https://github.com/tux3/qTox/issues?q=mentions%3ATux)

I edited that particular comment the fix the mention, you may still have to unsuscribe from this thread manually, or you can ignore the whole repo (in the Watch dropdown, next to the Star button).

If you still get unwanted mails from github you may want to simply tweak your settings (https://github.com/settings/notifications and https://github.com/settings/emails).

Sorry.
