### ISSUE TITLE
Allow typing Unicode (on Linux) somehow.

### ISSUE THREAD

**Issue by raingloom** [qTox/qTox#4506]
Most graphical Linux applications allow one to type in Unicode character codes by pressing Ctrl+Shift+U, I wanted to use this to send an unsupported emoji and noticed I can't use it in qTox. Is this a QT limitation? Can it be worked around?

It's not a hugely important thing, since it can be worked around (eg.:writing things in Emacs and pasting them) and has limited use, but it'd be nice to have.

**Comment by yurivict** [comment]
It works for me in qTox in xfce4.

**Comment by raingloom** [comment]
Then I'll edit this into a bug report later, I guess.

**Comment by yurivict** [comment]
Which OS/window manager you use where this fails?

**Comment by sudden6** [comment]
According to this https://en.wikipedia.org/wiki/Unicode_input#In_X11_.28Linux_and_Unix_variants.29 Qt doesn't support that. Does entering unicode this way work for you in other Qt applications?

**Comment by yurivict** [comment]
@sudden6 You are right, this was a side-effect of IBus.

This bug should be closed as invalid.

**Comment by raingloom** [comment]
I tried it with transmission-qt and that does not work either. Thanks for the wiki link, I only knew about the ctr-shift-u method.
