### ISSUE TITLE
1.11.0 build fails: 'toxpk_test.moc' file not found

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4518]
```
test/core/toxpk_test.cpp:90:10: fatal error: 'toxpk_test.moc' file not found
#include "toxpk_test.moc"
         ^~~~~~~~~~~~~~~~
1 error generated.
```

Found on the FreeBSD 11.1 using cmake.

Revision dd9b324 was building successfully.

**Comment by sudden6** [comment]
Can you find out what commit introduced this regression?

**Comment by yurivict** [comment]
Now even dd9b324 doesn't build for me. It used to build fine, I have qTox installed that says it was built from dd9b324.

What changed - cmake and other packages got updated on this system.
My guess is that this is some kind of cmake problem again.

1.11.0 fails with:
```
test/core/toxpk_test.cpp:90:10: fatal error: 'toxpk_test.moc' file not found
#include "toxpk_test.moc"
         ^~~~~~~~~~~~~~~~
1 error generated.
```

Revision dd9b324 fails with:
```
test/chatlog/textformatter_test.cpp:250:10: fatal error: 'textformatter_test.moc' file not found
#include "textformatter_test.moc"
         ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by yurivict** [comment]
Why isn't toxpk_test.cpp listed in any CMakeLists.txt files?

The only mention of ```toxpk_test``` is:
```
# grep -r toxpk_test work/
work/qTox-1.11.0/test/core/toxpk_test.cpp:#include "toxpk_test.moc"
```

**Comment by sudden6** [comment]
@yurivict maybe try removing `CMakeCache.txt` and the `CMakeFiles` folder? If you do an out of tree build, make sure that the source directory doesn't have these files either.

**Comment by Diadlo** [comment]
@yurivict It's used [here](https://github.com/qTox/qTox/blob/master/cmake/Testing.cmake#L23)

**Comment by yurivict** [comment]
When I comment out ```include(Testing)```, it still fails:
```
CMakeFiles/qtox.dir/src/main.cpp.o: In function `main':
src/main.cpp:(.text+0x1521): undefined reference to `Settings::currentProfileIdChanged(unsigned int)'
src/main.cpp:(.text+0x156d): undefined reference to `Settings::staticMetaObject'
```

It doesn't run Qt's moc for some reason?

cmake framework for FreeBSD ports is used. It successfully builds hundreds of other cmake-based projects the same way. So it doesn't look like clean is a problem.

**Comment by yurivict** [comment]
'moc' is never called for some reason. On Linux, does log show moc calls?

Only moc files produced are these:
```
./work/qTox-1.11.0/CMakeFiles/qtox_static.dir/qtox_static_autogen/moc_compilation.cpp.o
./work/qTox-1.11.0/CMakeFiles/qtox.dir/qtox_autogen/moc_compilation.cpp.o
./work/qTox-1.11.0/qtox_static_autogen/moc_compilation.cpp
./work/qTox-1.11.0/qtox_autogen/moc_compilation.cpp
```
Shouldn't there be a lot more of them?

**Comment by sudden6** [comment]
yes, moc is run on linux

**Comment by sudden6** [comment]
here the full build output on linux for reference: https://gist.github.com/sudden6/06359e7c88ed55652cecc80edcbf01a0

**Comment by yurivict** [comment]
```Automatic moc for target ``` are totally missing.

**Comment by sudden6** [comment]
do you have automoc installed? here it's in it's own package

**Comment by yurivict** [comment]
automoc5 is missing. I am asking on their mailing list.

**Comment by yurivict** [comment]
This turned out to be induced by some system inconsistency, and is now resolved.
Sorry for the disturbance.
