### ISSUE TITLE
UI issue: call button too big to fit

### ISSUE THREAD

**Issue by djfd** [qTox/qTox#4520]
Hi,

##### Brief Description

OS: arch linux  x64 recent
qTox version: v1.10.2.
Commit hash: b73603b45a32e63a649294537a62a9f11176c73d
toxcore: 0.1.9 
Qt:  5.9.1

Reproducible: Always

##### Steps to reproduce

1. just run it to see

##### Observed Behavior
voice call button is too big to fit to its container

##### Expected Behavior
expected to fit (compare with video call button)

##### Additional Info
1) issue screenshot
![callbutton-issue](https://user-images.githubusercontent.com/126338/28401252-2121f3d0-6d5c-11e7-831e-324588cc4c28.png)

2) fix call button issue patch proposal
[call-button-issue-fix.patch.txt](https://github.com/qTox/qTox/files/1161188/call-button-issue-fix.patch.txt)

3) russian language translation improvement patch proposal (currently ```[we are] Calling theParty``` translation to russian read exactly opposite, i.e. ```We are being called by theParty```) 
[improve-russian.patch.txt](https://github.com/qTox/qTox/files/1161189/improve-russian.patch.txt)

thanks

**Comment by Diadlo** [comment]
Shoukd be fixed in last release v1.11 and on master. Can you update and retest?

**Comment by sudden6** [comment]
@djfd about the translation update, can you either submit a PR or follow the instructions here: https://github.com/qTox/qTox/blob/master/translations/README.md

**Comment by sudden6** [comment]
Closed because needed information was not provided.
