### ISSUE TITLE
Difficultes with synced same profile (thru export) on multiple devices

### ISSUE THREAD

**Issue by ppcharlier** [qTox/qTox#4521]
I use Antidote for Tox on my iPhone, with the tox file exported from qTox it bugged, saying the file is corrupted.
So I made the opposite and created a profil in Antidote, then imported it in qTox and that worked.
But they seem to have it difficult to work, either on the same network or with the iPhone on cellular network and mac on WiFi.

I'm on macOS 10.12.5 (16F73), using qTox version v1.10.2 (with toxcore  0.1.0)

##### Brief Description

OS: Windows / OS X / Linux (include version and/or distro)
qTox version: v1.10.2
Commit hash: b73603b45a32e63a649294537a62a9f11176c73d
toxcore: 0.1.0
Qt: 5.9.0
Hardware: MacBook Pro 13,3  (2016 with TouchBar)

Reproducible: Always 

##### Steps to reproduce
1. Create profile with Antidote for Tox on iOS
2. Export profile to .tox file and import in qTox on macOS
3. Connect both devices to Tox network
4. Having a 2 profile serving as Test Contact
5. Try to add the Test Contact on both Antidote and qTox is yet a problem, when it's already added to qTox

##### Observed Behavior
the Test Contact doesn't receive a request when Antidote add the contact, thus making it impossible to add, unless playing with deleting the Test Contact from qTox and main profile from Test Contact's app.

##### Expected Behavior
Sync seamlessly thru tox protocol

**Comment by ppcharlier** [comment]
Connections happens between the different sessions when I play with the online status of the differents apps. It's not every time effective

**Comment by sudden6** [comment]
Are you trying to use the same profile at the same time on different devices?

**Comment by sudden6** [comment]
Also for testing you can use https://toxme.io/u/echobot it's usually pretty fast.

**Comment by ppcharlier** [comment]
Yes indeed, shared between the two apps through a .tox file

**Comment by sudden6** [comment]
Being online with the same ID on multiple devices at the same time is currently not supported in Tox.

**Comment by ppcharlier** [comment]
Ok thank you for your answer. I hope it'll be added later :)

have a nice day
