### ISSUE TITLE
compilation error "libsqlcipher.so: undefined reference to..." (ubuntu 16.04)

### ISSUE THREAD

**Issue by yatsenkoanton** [qTox/qTox#4534]
##### Brief Description

OS: ubuntu 16.04  
qTox version: 1.11 
Commit hash:  
toxcore:  0.1.2

I am unable to compile qTox on Ubuntu. I followed step-by-step instructions and get the following errors during compilation:

```
[ 85%] Linking CXX executable qtox
/usr/local/lib/libsqlcipher.so: undefined reference to `EVP_CIPHER_block_size@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `EVP_CIPHER_iv_length@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `EVP_CipherInit@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `RAND_bytes@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `HMAC_Update@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `HMAC_Init_ex@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `EVP_CIPHER_CTX_cleanup@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `EVP_CIPHER_CTX_set_padding@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `OPENSSL_add_all_algorithms_noconf@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `HMAC_CTX_init@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `EVP_CipherUpdate@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `OBJ_nid2sn@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `EVP_CIPHER_nid@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `RAND_add@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `EVP_CIPHER_key_length@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `HMAC_Final@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `EVP_get_cipherbyname@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `EVP_sha1@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libsoxr.so.0: undefined reference to `GOMP_parallel@GOMP_4.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `PKCS5_PBKDF2_HMAC_SHA1@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `HMAC_CTX_cleanup@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `EVP_cleanup@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `EVP_CipherFinal@OPENSSL_1.0.0'
/usr/local/lib/libsqlcipher.so: undefined reference to `EVP_MD_size@OPENSSL_1.0.0'
collect2: error: ld returned 1 exit status
```
i tried to reinstall sqlcipher and openssl - it doesn't help at all. I also have to mention, that I was able to successfully build 1.6 version around half a year ago on the same system. 
Any suggestions?
I am grateful for your help.

**Comment by ghost** [comment]
I have seen before that maybe is related with the libcipher version. Actually, everytime that I want to open qtox (after an upgrade) I must downgrade the library: with sudo dpkg -i libsqlcipher0_3.2.0-1.1+b2_amd64.deb (the "maximum" version that qtox supports)

**Comment by yatsenkoanton** [comment]
Thank you for your answer, but unfortunately it didn't work. I installed 3.2.0 packages and nothing changed. Then I compiled 3.2.0 version from source and made sure that libsqlcipher.so had been updated and still received the same compilation errors.

**Comment by yurivict** [comment]
> Actually, everytime that I want to open qtox (after an upgrade) I must downgrade the library: with sudo dpkg -i libsqlcipher0_3.2.0-1.1+b2_amd64.deb

@Clarin98 You need to complain to the maintainer of the ubuntu package that it doesn't work out of the box.

**Comment by zetok** [comment]
@yatsenkoanton 
qTox compiles & works for me just fine with `dev-db/sqlcipher-3.4.1` on Gentoo. As @yurivict said, it seems to be a problem with sqlcipher package in your distro.

>Then I compiled 3.2.0 version from source and made sure that libsqlcipher.so had been updated and still received the same compilation errors.

Did you remove the one installed from distro repo?

**Comment by yatsenkoanton** [comment]
Yes. I remove my sqlcipher, libsqlcipher-dev and libsqlcipher0 packages (all 3.2.0-1.1) using apt-get. Then I compile and install the latest version of sqlcipher from github using instructions.  It compiles and installs without errors: it seems to find openssl 
```
checking for crypto library to use... openssl

checking for HMAC_Init_ex in -lcrypto... yes
``` 
and /usr/local/lib/libsqlcipher.so, libsqlcipher.so.0 and libsqlcipher.so.0.8.6 are updated (they are changed at the time of installation, the size is changed as well). But I still get the same errors. Maybe it's the problem with openssl? I really have no idea what is the problem.

**Comment by yatsenkoanton** [comment]
Okay, I fixed the problem. When I manually moved librypto files to /usr/local/lib from /usr/lib/x86_64-linux-gnu/ directory, qTox has compiled just fine and works smoothly.

I also had an error "//usr/lib/x86_64-linux-gnu/libsoxr.so.0: undefined reference to `GOMP_parallel@GOMP_4.0'" , but was fixed by upgrading libgcc from 4.8.5-2 to 5.2.0-0 version, so it was not a big deal.

I still don't know if it was my system's problem or qTox cmake issue. I find it strange that libcrypto.so from /usr/lib/x86_64-linux-gnu/ directory was ignored...

**Comment by yurivict** [comment]
cmake files error that they fail to look for sqlcipher?

**Comment by yurivict** [comment]
Nope, configure fails with no sqlcipher:
```
-- Checking for one of the modules 'sqlcipher'
CMake Error at cmake/Dependencies.cmake:72 (message):
  SQLCIPHER package, library or framework not found
Call Stack (most recent call first):
  cmake/Dependencies.cmake:103 (search_dependency)
  CMakeLists.txt:73 (include)


-- Configuring incomplete, errors occurred!
See also "/wrkdirs/usr/ports/net-im/qTox/work/qTox-c4baff4/CMakeFiles/CMakeOutput.log".
*** Error code 1
```

**Comment by yatsenkoanton** [comment]
no, I had all libraries installed and cmake was able to find all of them while configuring, errors  were appearing during compilation: I assume that compiler didn't check /usr/lib/x86_64-linux-gnu/ directory for lybcrypto.so. When I moved it from there to /usr/local/lib, compilation ended successfully.  It was not sqlcipher problem I suppose.

**Comment by yurivict** [comment]
@yatsenkoanton You should uninstall and install the packages again. If you still have the problem, please contact the package maintainer as there is most certainly nothing wrong with qTox from what you described.

**Comment by zetok** [comment]
Since it's a downstream issue and nothing on qTox side can be done about it, closing the issue.

**Comment by jontis** [comment]
Just adding, I also had this problem when compiling on Mint 18.3 (ubuntu 16.04.3 LTS)

OS: Mint 18.3 (ubuntu 16.04.3 LTS)
qTox version: 1.13
Commit hash:
toxcore: 0.2.0

Putting a symlink fixed it.
sudo ln -s /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /usr/local/lib/libcrypto.so
