### ISSUE TITLE
[suggestion] Change subscribeOutput/unsubscribeOutput definitions

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4538]
These two functions aren't properly defined IMO:
```
    virtual void subscribeOutput(uint& sourceId) = 0;
    virtual void unsubscribeOutput(uint& sourceId) = 0;
```

Problems:
* ```subscribeOutput``` shoudn't receive the sourceId value, it should only return it
* ```subscribeOutput``` should receive the human-readable output identification, like user name or chat name/id. Some audio engines (ex. Jack) allow multiple identifiable outputs.
* ```unsubscribeOutput``` should only receive sourceId as ```uint sourceId```

This probably can be fixed very easily.

**Comment by Diadlo** [comment]
What class are you talking about?

**Comment by yurivict** [comment]
Class is Audio.

**Comment by Diadlo** [comment]
1. I'm not sure, how does currently audio works, ~but how you can subscribe without specifing source?~ probably, I'm agree
2. How does chat name/id related with audio at all? If I understand `Audio` correctly, 'output' here is output device, not place, where audio played
3. I'm agree. But seems in this case `unsubscribeOutput` should return bool to make possible nullify `sourceId` on caller side

**Comment by yurivict** [comment]
> I'm not sure, how does currenly audio works, but how you can subscribe without specifing source?

```subscribeOutput``` only returns sid. It is always 0 when it's passed.

> How does chat name/id related with audio at all? If I understand Audio correctly, 'output' here is output device, not place, where audio played

Subscribing to a specific output creates a separate stream. Sound server supports multiple named streams. They ultimately are routed to the physical speaker, but one can reroute them in any other way using standard audio tools. Without having a stream name available, they will appear as numbers, which isn't easy to read and match.

> I'm agree. But seems in this case unsubscribeOutput should return bool to make possible nullify sourceId on caller side

```unsubscribeOutput``` is always assumed successful, so ```bool``` will probably not be necessary.

**Comment by Diadlo** [comment]
2. What role will be played this name? It will be only stored inside audio backend?

**Comment by yurivict** [comment]
> What role will be played this name? It will be only stored inside audio backend?

It will be shown on the audio server as qTox having the output called 'output-JohnSmith' while you talk to the user 'JohnSmith'. One can, for example, set a rule to pass all such streams (originating in qTox and having a specific name) through some filters, etc. Or to save them. This adds flexibility in what can be done with specific audio streams.

**Comment by sudden6** [comment]
@yurivict 1 & 3 are good ideas, 2 isn't really possible and doesn't make sense with the current audio architecture, because everything is mixed inside OpenAL and then passed on to the operating systems audio backend as one stream.

I think it would make sense to separate the notification sounds from the call audio streams, but I have yet to come across a messenger that supports multiple call audio streams to multiple audio devices.

**Comment by yurivict** [comment]
@sudden6 2. isn't for OpanAL, it is for Jack. It can totally use names. In Jack you can reroute audio streams, and in the PulseAudio too. I have to use output-sidN for now because of the lack of the human-readable description.

> I think it would make sense to separate the notification sounds

I am running the test Jack backend, and they are perfectly separated.

**Comment by sudden6** [comment]
Ok, I didn't know you are writing an audio backend. With an extra backend what you say is certainly possible.

Maybe we can extend the audio interface, with something like `subscribeOutput(QString description = "")`, and pass e.g. the peer or groupname when registering a stream.

**Comment by yurivict** [comment]
Yes, it should be:
```
uint subscribeOutput(const QString& description);
```

**Comment by sudden6** [comment]
Right, making the description a default parameter is probably not a good idea.

**Comment by yurivict** [comment]
What do you suggest then? Audio backend registers the output inside of ```subscribeOutput```, so it needs the name there. It actually has to be non-empty.

**Comment by sudden6** [comment]
I think you misunderstood, I think your solution is the correct one.

**Comment by yurivict** [comment]
Sorry, I misread your answer. Was still half-asleep. -)

**Comment by sudden6** [comment]
This code was completely refactored in the meantime.
