### ISSUE TITLE
Fonts are broken in qTox

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4554]
For example, try changing the font of outDevLabel in src/widget/form/settings/avform.ui to something very different, like "Steve". When app runs, it still shows with "Sans Serif" font.

So, as it is, it is impossible to change fonts of individual elements.

**Comment by mikhailnov** [comment]
qTox would better take the system default Qt font

**Comment by yurivict** [comment]
> qTox would better take the system default Qt font

Not all systems support system default font. There is no single place where this font is set. This is why there are font family names set by apps. qTox doesn't respect families set in .ui files.

**Comment by Diadlo** [comment]
@yurivict I suppose, better name for the issue is "Fonts are doesn't work as I want" ;)
qTox uses [`Style`](https://github.com/qTox/qTox/blob/master/src/widget/style.cpp) class to work with fonts

**Comment by yurivict** [comment]
In other words, it uses css stylesheets that overload specified in .ui fonts.

@Diadlo  FYI, style.cpp also has an unrelated function Style::scaleSvgImage in it. Seems like it should be in utils.cpp or something. Also, static functions appFont and qssifyFont are not labeled as static.)

**Comment by Diadlo** [comment]
@yurivict `utils.cpp` is a bad practice. It have to wide meaning -> many functions can be placed there without any real reason. `scaneSvgImage` looks like something related with style, so I think it's good place for it. About static functions -- you are right, feel free to fix :)

**Comment by yurivict** [comment]
> utils.cpp is a bad practice.

All opinions are respected -)
