### ISSUE TITLE
Entry point not found

### ISSUE THREAD

**Issue by tetryl** [qTox/qTox#456]
On windows I ran it for the first time and get the error "The procedure U16_to_bytes could not be located in the dynamic link library libtoxcore-0.dll."

**Comment by msteinbeck** [comment]
I can confirm

**Comment by tux3** [comment]
My build system is currently using an outdated version of toxcore consistently, this will be fixed this weekend and shouldn't happen again.

**Comment by tux3** [comment]
This should be fixed (tested with Wine). From now on toxcore will be rebuilt ever day.
If you still have this issue with the latest qTox please post a comment and I'll reopen.

**Comment by tetryl** [comment]
I still have a problem with the latest build. [qTox Windows 2014-10-18 18:52:46]

also the windows download link on the frontpage is broken.

**Comment by agilob** [comment]
@tetryl download from [here](https://github.com/tux3/qTox/releases)

**Comment by tux3** [comment]
This should work now, the latest version is available <a href="https://github.com/tux3/qTox/releases/tag/qtox-windows-1413662115.05">here</a>.
I actually tested it on windows this time, but if you still have this issue anyway, please comment and I'll reopen.
