### ISSUE TITLE
Never add Windows media codecs requirement(WMF, QT Multimedia)

### ISSUE THREAD

**Issue by fcore117** [qTox/qTox#4564]
Just a note and you can close this afterwards, please do not ever add QT multimedia based system inside qTox as it requires horrible WMF codecs, keep ffpmeg always as it is independent from system. There are lots of people who use Windows N aka without Windows Media Player trash.

**Comment by nurupo** [comment]
Qt Multimedia is as "independent from system" as ffmpeg is, they both cross-platform and use system-specific APIs for video capture, as you have to talk to OS if you want to communicate with any hardware peripherals. The only difference is that Qt Multimedia either doesn't work or works horribly, especially on Windows, last time I tested it, while ffmpeg works great everywhere. So there is no need to worry about qTox switching to using Qt Multimedia for webcam capture.

**Comment by fcore117** [comment]
Thanks for confirmation and relief, there are some other QT software that just gives notify sound and requires WMP trashware installation. Windows N is made possible thanks to Europe demands. 

half-offtopic but just for example even Chromium uses FFMpeg as a core for playback.
