### ISSUE TITLE
Wrong text formatting when using slashes

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#4566]
##### Brief Description
qTox version:  qTox-Version v1.11.0-63-g1e90106a
Commit hash:  1e90106a08a2eab90218b9e587ad7ce68ed0a4e9
…

Reproducible: Always 

##### Steps to reproduce

1. Enable `Text Style Format: Show formatting Characters`
2. Write `he/she/it` in a chat

##### Observed Behavior

The word `she` is formatted in italic.

##### Expected Behavior

Should be without special formatting since there's no whitespace on both sides of the word.

**Comment by anthonybilinski** [comment]
Probably related to this, if I type 
> :/

I get the broken piece of paper with a folded corner emoji, but if I type
> :\\

I get the frowny emoji.

![image](https://user-images.githubusercontent.com/10469203/30354730-1e922be2-97e3-11e7-924c-1d1cd25031e2.png)

If I copy paste the two, I see
>:/\</i>

and
>:\

respectively.

**Comment by jessica181920** [comment]
It seems this is no longer an issue.
