### ISSUE TITLE
qTox doesn't seem to use libQt5Sql, but installation instructions, cmake, etc. say that it's required

### ISSUE THREAD

**Issue by nurupo** [qTox/qTox#4567]
Was confused by this https://github.com/voidlinux/void-packages/commit/03bbc343309ad5e687e6fed7973123229c82fe36 commit as why they link against Qt SQL libraries, since, as far as I can see (`grep -i -R --colour 'sql' *`), the only SQL library that qTox uses is `libsqlcipher`, which is a fork of `libsqlite` with encryption added on top, so you don't even have to install a vanilla `libsqlite`, not to mention Qt5's SQL libraries. If this is correct, then the sqlite and Qt5 SQL library requirements must be removed from all instructions, build scripts and cmake files, as they are not being used by qTox.

**Comment by sudden6** [comment]
You are right, the qt sql stuff isn't needed and was probably forgotten to remove.
