### ISSUE TITLE
Blink tray icon on new message when not minimized

### ISSUE THREAD

**Issue by ChristophHaag** [qTox/qTox#4568]
At least here on KDE Plasma on Archlinux, the qtox tray icon only blinks on new unread messages while qtox is minimized. I often have lots of windows open and qtox in the background, so if I happen to miss the notification sound, I miss the new message for quite a while until I happen to look at the window.

Even if people don't want this, it should be a configuration setting. I imagine General tab can be expanded with the bottom two points:
```
On new message:
    [] Play sound
         [] Play sound while Busy
    [] Blink tray icon
         [] Only when minimized
```

**Comment by sudden6** [comment]
Can you include the Qt + qTox versions like in the template please?

**Comment by ChristophHaag** [comment]
Qt 5.9.1
qtox master

Why are you asking? I thought it was more of a general feature request, but should it be working like that already?

I mean that the tray icon is not indicating messages when the qtox window is open on the desktop, but not focused and I think it should, like e.g. pidgin.

**Comment by sudden6** [comment]
I think the taskbar should blink, so maybe it's a bug, don't have time to look into it right now though.
Also `qTox master` is not a good version, because as time passes `master` changes, use the commit hash from which you built.

**Comment by ChristophHaag** [comment]
Oh sorry, that's the current master 5d159e0203bdd0e72153cce9ca5c0fe8483ba0db.

Maybe I'll look myself into the code some time.

**Comment by sudden6** [comment]
Looking into the code is probably the fastest and most helpful way :)

**Comment by ChristophHaag** [comment]
I spent some time with a debugger and I can tell you where it happens, but I'm not exactly sure why:

https://github.com/qTox/qTox/blob/5d159e0203bdd0e72153cce9ca5c0fe8483ba0db/src/widget/widget.cpp#L1873

When the window is minimized, the WindowActivate event does not happen.

When the window is not minimized and unfocused, the event does happen. resetIcon(); is called, which sets eventFlag to false at which point the icon stops blinking instantly.

Googling suggested to use
```
    case QEvent::ActivationChange:
        if(this->isActiveWindow())
```

instead, but it doesn't really change anything. I think the window is "activated" in the code somewhere when a new message arrives, even though it doesn't get focused.

The event should really only happen when the window gets focused, not when the window gets "activated", whatever that means (it starts blinking in the taskbar, I think that's the "urgent" window hint for the window manager. Not exactly sure because I don't know window managers so well).

**Comment by ChristophHaag** [comment]
I knew I've seen it somewhere.

This here is the problem:

https://github.com/qTox/qTox/blob/5d159e0203bdd0e72153cce9ca5c0fe8483ba0db/src/widget/widget.cpp#L1404

If I comment that line out, the tray icon blinks correctly until the window is focused.

**Comment by ChristophHaag** [comment]
Uhm I somehow did not really realize there's another "New Message"  setting on the User Interface tab where I had "Focus Window" enabled. If I disable "Focus Window", the icon blinks as intended with the original code.

The actual issue here is rather that "Focus Window" does not actually focus the window, at least not on kde's kwin window manager.

**Comment by ChristophHaag** [comment]
Never mind, it was kwin's focus stealing prevention setting.

There was actually no issue here, just a couple of things working together so I didn't understand what's happening.

Sorry for the noise. :)
