### ISSUE TITLE
[Regression] dark system theme broken again

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#457]
@krepa098 change you made in c4529d4 in CSS overwrites fixes I wrote several days ago for dark themes 

![tox](https://cloud.githubusercontent.com/assets/2544251/4684931/9451652a-5635-11e4-9d6c-cc2ef6a6d083.png)
![tox1](https://cloud.githubusercontent.com/assets/2544251/4684930/9449cf18-5635-11e4-84d7-4b8a5f3cef60.png)
![tox2](https://cloud.githubusercontent.com/assets/2544251/4684976/13fc8fd4-5636-11e4-8309-93a3be488226.png)

I can fix this if you work on light themes.

**Comment by krepa098** [comment]
Sorry for that. I removed the background color from QWidget as it caused problems (win98-style widgets).

**Comment by agilob** [comment]
Check [the file](https://github.com/tux3/qTox/blob/master/ui/settings/mainContent.css) now, QGroupBox is defined twice ;D

I thought Win-98 style was fixed by selecting Qt theme (Fusion?), it solved the problem on my system at least. We discussed it [here](https://github.com/tux3/qTox/issues/406), no one responded it's not fixed and author closed the issue. I'll try to fix it tomorrow, when I have patch ready, I'll ask you to test it.
