### ISSUE TITLE
Crashes on trying to start video call without video

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#458]
This is design flaw in Tox that I can audio call a friend, and said friend can arbitrarily upgrade the call to video without my permission. Since I don't have a webcam, toxav segfaults with what I assume is null video frames.

The latter can be worked around, most easily by @krepa098, but the former needs more attention.

https://gist.github.com/dubslow/2fb0a53b7ffdf0487933

**Comment by tux3** [comment]
We should be able to get one way video regardless, it used to work when I tested locally some time ago. 
(Or if toxav can't help but fail, at least downgrade immediately back to audio only without crashing.)

**Comment by krepa098** [comment]
Any idea on how to reproduce? Unfortunately the backtrace isn't that helpful.

**Comment by tux3** [comment]
I haven't tried to reproduce yet, but if you call uTox <-> qTox on the same computer, uTox should get exclusive access to the cam, leaving qTox thinking there's no working camera. Maybe then uTox changing the call to video could repro the crash.

**Comment by dubslow** [comment]
I got this on trying to call irungentoo's video stream from yesterday or the day before or whenever. Essenetially, I audio called him, and his client upgraded to video call, whence the crash.

@krepa098 ^^. Audio-call a client who is transmitting video, i.e. "upgrades" the call to such.

@tux3 I've only ever had qtox, so fighting for the webcam is not a possible source of this bug.

**Comment by tux3** [comment]
@dubslow I don't think it's a problem of fighting with the webcam, but I though maybe it would be a way to reproduce someone upgrading a call while you don't have a webcam.

Actually I tried doing just that and ... it didn't crash but there's definitely a bug there.
When I upgraded the call to video, qTox opened a video view for every single person in my contact list, online or not. I think I'm officially the first person to get into a video call with audiobotze and groupbot \o/

![pic4](https://cloud.githubusercontent.com/assets/5155966/4692652/8ab90c7e-5771-11e4-8b3d-b4f267cd7a3b.jpg)

**Comment by tux3** [comment]
Yep, ChatForm::onAvMediaChange doesn't check the callId, found that bug, not sure if it'll fix this issue though.

**Comment by zetok** [comment]
Is it still reproducible?

**Comment by tux3** [comment]
I think that this is fixed.
