### ISSUE TITLE
Windows nightly isn't built for 2 weeks due to linking error

### ISSUE THREAD

**Issue by DX37** [qTox/qTox#4580]
This is from log:
```
linking release/qtox.exe
./release/openal2.o:openal2.cpp:(.text+0x4f): undefined reference to `filter_audio'
./release/openal2.o:openal2.cpp:(.text+0xd76): undefined reference to `pass_audio_output'
./release/openal2.o:openal2.cpp:(.text+0xed8): undefined reference to `new_filter_audio'
./release/openal2.o:openal2.cpp:(.text+0x1089): undefined reference to `set_echo_delay_ms'
./release/openal2.o:openal2.cpp:(.text+0x10b7): undefined reference to `enable_disable_filters'
./release/openal2.o:openal2.cpp:(.text+0x1192): undefined reference to `kill_filter_audio'
collect2: error: ld returned 1 exit status
```

**Comment by sudden6** [comment]
I think this comes from the OpenAL2 backend being built, even if it shouldn't be built on windows.

**Comment by nurupo** [comment]
~~~Looks like it can't find libfilteraudio symbols. Perhaps qtox is not linking to that library, or the link order is incorrect. The openal we use on Jenkins, as well as the one we use in `windows/cross-compile/build.sh` of this repo, is irungentoo's fork of openal-soft that uses irungentoo's filter_audio, which is the audio filtering taken from webrtc code. It's likely that this "feat(audio): make the libfilteraudio dependency optional" commit https://github.com/qTox/qTox/commit/8652fe99e3cb80fac22a601c89ba405962c5537d have caused this issue, as libfilteraudio is required when using irungentoo's openal-soft fork. It's not required if you use the upstream openal-soft though, which is what the committer was likely assuming.~~~

**Comment by nurupo** [comment]
Also, this commit https://github.com/qTox/qTox/commit/8652fe99e3cb80fac22a601c89ba405962c5537d didn't make libfilteraudio optional, it outright removed the use of it. There is no option to use it, qTox never will link to it.

**Comment by nurupo** [comment]
Ok, I see, it's actually has been made optional in another commit, not the one that claims to make it optional, but the one that adds it for OSX https://github.com/qTox/qTox/commit/8f2401fee64d0b5535bd4d737a1caf2bffa30682.

**Comment by nurupo** [comment]
Ok, never-mind, didn't know `openal2.cpp` is a qTox file. You can ignore my last messages, thought that was openal library.

**Comment by nurupo** [comment]
Shouldn't the `.pro` file define `USE_FILTERAUDIO`? Jenkins is still using qmake.

**Comment by nurupo** [comment]
The issue seems to be that [qmake tries to build `openal2.cpp`](https://github.com/qTox/qTox/blob/5d159e0203bdd0e72153cce9ca5c0fe8483ba0db/qtox.pro#L464), encounters all those libfilteraudio symbols in it and can't find them anywhere, as `-lfilteraudio` was added [only for non-Windows](https://github.com/qTox/qTox/blob/5d159e0203bdd0e72153cce9ca5c0fe8483ba0db/qtox.pro#L256), so it fails on Windows.
