### ISSUE TITLE
Icon qtox.svg should be installed in compressed form

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4582]
It currently installs ```share/icons/hicolor/scalable/apps/qtox.svg```. The FreeBSD port has to run ```gzip -Sz qtox.svg``` to convert it to ```qtox.svgz```. It would be nice if cmake did this automatically during install.

**Comment by sudden6** [comment]
Does anyone know if that's also supported in Linux DEs?

**Comment by yurivict** [comment]
Yes, please see the list of files from some package on Ubuntu: https://packages.ubuntu.com/trusty/amd64/linuxdcpp/filelist

**Comment by Diadlo** [comment]
@yurivict I did not find `*.svgz` by your link

**Comment by yurivict** [comment]
Sorry: https://packages.ubuntu.com/trusty/amd64/dragonplayer/filelist

**Comment by sudden6** [comment]
~Uhm, I don't see any `*.svgz` file there?~

Didn't refresh the page.
