### ISSUE TITLE
Comment in qtox.desktop needs changes

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4584]
It currently says: "qTox is a powerful Tox client that follows the Tox design guidelines."

Problems:
1. No need to say that this is qTox, because this is obvious from the application name.
2. It isn't translated. Other apps have many sections like this:
```
Comment[fr]=Xxx
Comment[it]=Xxx
```

I recommend: "Qt 5 based Tox instant messenger for secure communication"
No need for the period in the end. I don't think users really care that it is design guidelines compliant or not - no need to mention this.

**Comment by jnishwanth** [comment]
Looks like this issue is fixed except for the translation to different languages

**Comment by sudden6** [comment]
Translations merged
