### ISSUE TITLE
cmake doesn't look for filteraudio headers

### ISSUE THREAD

**Issue by nurupo** [qTox/qTox#4587]
cmake can't find filteraudio headers when filteraudio is not system-wide installed, which is the case when, for example, cross-compiling qTox to Windows. You can reproduce my issue by cross-compiling qTox to Windows with https://github.com/qTox/qTox/pull/4588 changes.

filteraudio doesn't provide pkg-config files, so cmake [falls back to using `find_library`](https://github.com/qTox/qTox/blob/5d159e0203bdd0e72153cce9ca5c0fe8483ba0db/cmake/Dependencies.cmake#L62). It does find the library successfully, but the issue is that it only looks for the library, when it also should be looking for the headers in the addition. This is what I get

```
-- FILTERAUDIO LIBRARY_DIRS: 
-- FILTERAUDIO INCLUDE_DIRS: 
-- FILTERAUDIO CFLAGS_OTHER: 
-- FILTERAUDIO LIBRARIES:    /workspace/i686/dep-cache/libfilteraudio/lib/libfilteraudio.a
-- FILTERAUDIO found
-- using filteraudio
```

As you can see, `INCLUDE_DIRS` is empty. And then I get

```
In file included from /build/qtox/src/audio/audio.cpp:23:0:
/build/qtox/src/audio/backend/openal2.h:41:26: fatal error: filter_audio.h: No such file or directory
compilation terminated.
```

To fix this, [besides just doing `find_library()` call]((https://github.com/qTox/qTox/blob/5d159e0203bdd0e72153cce9ca5c0fe8483ba0db/cmake/Dependencies.cmake#L62)), it should be doing something like

```
find_path(${pkg}_INCLUDE_DIRS NAMES filter_audio.h)
```

You'd want to either pass `filter_audio.h` as an extra argument to `search_dependency()`, or write a [`FindFilteraudio.cmake` module](https://cmake.org/Wiki/CMake:How_To_Find_Libraries) and use `find_package(filteraudio)`.

**Comment by sudden6** [comment]
I think we can justify the usage of [evil uTox technology](https://github.com/uTox/uTox/blob/develop/cmake/Findlibfilteraudio.cmake) here.

**Comment by nurupo** [comment]
Ok, that's easy enough, I will make a PR.
