### ISSUE TITLE
Graphical glitch when switching profile

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#459]
26eb08aa00bdfe4ea3d2d90103c417239736c741
![rr](https://cloud.githubusercontent.com/assets/3148759/4687045/a8e2c034-564d-11e4-964d-b17ddbe44396.png)
In place where contact list would be

Steps to reproduce:
1. Profile with some contacts
2. Switch to profile with no contacts

**Comment by dubslow** [comment]
I believe if you move the cursor over them, they disappear.

Regardless of if that's true or not, I'm not really sure what the issue could be, much less how to solve it.

**Comment by zetok** [comment]
Yep, it disappears when clicked on it/hovered over it.

Still, it is a graphical issue, it appears exactly in place where contacts from previous profile were.

**Comment by zetok** [comment]
Hm, that graphical glitch is also present when there are no contacts, groupchat is created and then removed.
