### ISSUE TITLE
Link to Windows 32-bit portable build throws 404

### ISSUE THREAD

**Issue by leafcutterant** [qTox/qTox#4592]
##### Brief Description

On the qTox Github opening page, clicking on the Windows 32-bit potable download (https://qtox-win.pkg.tox.chat/qtox/win32/download-portable) throws a 404 error:

```
HTTP ERROR 404

Problem accessing /view/qtox/job/qTox-stable_build_windows_x86_release/lastSuccessfulBuild/artifact/qTox-stable_build_windows_x86_release_1.11.0.zip. Reason:

    Not Found

Powered by Jetty://
```

Reproducible: Always

**Comment by ezavod** [comment]
Note: The link refers to https://build.tox.chat/view/qtox/job/qTox-stable_build_windows_x86_release/lastSuccessfulBuild/artifact/qTox-stable_build_windows_x86_release_1.11.0.zip, which seems unavailable. It seems that the filename is `qTox-stable_build_windows_x86_release.zip`.
As a workaround https://build.tox.chat/view/qtox/job/qTox-stable_build_windows_x86_release/lastSuccessfulBuild/artifact/qTox-stable_build_windows_x86_release.zip seems to work.

**Comment by xz00311** [comment]
thanks

**Comment by sudden6** [comment]
Portable builds have been discontinued.
