### ISSUE TITLE
Add missing checks for toxcore libraries in cmake

### ISSUE THREAD

**Issue by Fighter19** [qTox/qTox#4594]
A check for libtoxencryptsave & libtoxdns is missing, resulting in a build error, when they're needed (and not installed).

**Comment by Diadlo** [comment]
What OS do you use?

**Comment by Fighter19** [comment]
Ubuntu. Using the PPA to install toxcore binaries (and headers)

Am 02.09.2017 11:45 schrieb "Polshakov Dmitry" <notifications@github.com>:

**Comment by sudden6** [comment]
The c-toxcore libraries are checked here: https://github.com/qTox/qTox/blob/master/cmake/Dependencies.cmake#L106-L117

What do you think is missing?

What error messages do you get?

**Comment by Fighter19** [comment]
The headers defined in the source files could not be found (during compilation).
(toxcore.h and toxencryptsave.h)

**Comment by sudden6** [comment]
Did you install the headers?
normally library packages don't provide them, they are in `-dev` packages. Also which PPA do you use?

**Comment by Fighter19** [comment]
Installing them fixed that. (My point was just that the configure script should check for the headers first).
I used the one suggested on tox.chat

https://pkg.tox.chat/debian
