### ISSUE TITLE
Name and status are not updated when profile is switched

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#460]

**Comment by dubslow** [comment]
Unable to reproduce

**Comment by zetok** [comment]
http://a.pomf.se/nvrzcf.webm

**Comment by agilob** [comment]
Walk-around for #460 and #459 would be to restart application in IdentityForm::onLoadClicked()

```
qApp->quit();
QProcess::startDetached(qApp->arguments()[0], qApp->arguments());
```

I've tried fixing #459, but gave up after 90minutes ;/

**Comment by dubslow** [comment]
Ah I see... hmm. Can you confirm that if you actually set a status on the new account that they update correctly?

**Comment by dubslow** [comment]
Well I'm assuming I was right with the above comment. New profiles don't have names/statuses, so there wasn't anything for the UI to set. Fixed by adding default name and status -- your profile above will continue to show that behavior, but no others will.
