### ISSUE TITLE
Codeblock no longer work with leading whitespace after HTML formatting refactor

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#4602]
https://github.com/qTox/qTox/pull/4158 added the behaviour that "styling applies only if non-whitespace symbol follows opening formatting symbol and also non-whitespace symbol preceds closing"

For the use of codeblocks, I (and my co-worker) used to format as follows:
\`
big block of code
\`

to keep the backticks out of code that we wanted to copy paste. The new behaviour of needing the backticks touching the code without whitespace in between seems undesirable. Additionally, I can't think of any other reason to start a line with a backtick other than code, so I don't see the value in this change.

##### Observed Behavior

\`
test
\`
does not format "test" as code.

##### Expected Behavior
\`
test
\`
formats "test" as code.

**Comment by Diadlo** [comment]
@anthonybilinski No, this is the right behaviour. ` used to one line code and ``` for multiline

**Comment by anthonybilinski** [comment]
Ah, you're right. I will just change my use to triple back ticks. Thanks for the answer.
