### ISSUE TITLE
qtox login box appears, even if I am already logged in

### ISSUE THREAD

**Issue by DoctorSubtilis** [qTox/qTox#4609]
##### Brief Description

OS: Linux Kubuntu 17.04
qTox version: v1.11.0-89-g359a42f7
Commit hash: 359a42f78e8edf073d6132bca8954a55094385c5 
toxcore: 0.1.2
Qt: 5.7.1
Hardware: "00:00.0 Host bridge: Intel Corporation Device 590f (rev 06)
00:02.0 VGA compatible controller: Intel Corporation Device 5912 (rev 04)
00:08.0 System peripheral: Intel Corporation Skylake Gaussian Mixture Model
00:14.0 USB controller: Intel Corporation 200 Series PCH USB 3.0 xHCI Controller
00:14.2 Signal processing controller: Intel Corporation 200 Series PCH Thermal Subsystem
00:16.0 Communication controller: Intel Corporation 200 Series PCH CSME HECI #1
00:17.0 SATA controller: Intel Corporation 200 Series PCH SATA controller [AHCI mode]
00:1c.0 PCI bridge: Intel Corporation 200 Series PCH PCI Express Root Port #7 (rev f0)
00:1f.0 ISA bridge: Intel Corporation 200 Series PCH LPC Controller (B250)
00:1f.2 Memory controller: Intel Corporation 200 Series PCH PMC
00:1f.3 Audio device: Intel Corporation 200 Series PCH HD Audio
00:1f.4 SMBus: Intel Corporation 200 Series PCH SMBus Controller
01:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)
 
…

Reproducible: Always 

##### Steps to reproduce

1. start new session
2. a login box appears
3. closing it, the program, qtox, works normally

##### Observed Behavior
strange login box (my profile is without password)

##### Expected Behavior
no login box

##### Additional Info
(links, images, etc go here)
[qtox.txt](https://github.com/qTox/qTox/files/1267171/qtox.txt)

**Comment by DoctorSubtilis** [comment]
**Solution**: remove from autostart the *.desktop created with qtox (with -p "nameprofile") and add a new autostart item (without -p "nameprofile").

**Comment by sudden6** [comment]
I can't find anything odd in the logs, is the login box the qTox login box?

**Comment by DoctorSubtilis** [comment]
Yes. 
Work around: not place qtox in autostart, but leave opened when logout, so there is no login box at the next session, though qtox is starting (not from autostart, but from restore session).

**Comment by sudden6** [comment]
Very strange, do you have any ideas if this correlates with anything you do in qTox? As you seem to be the only one currently with this issue, maybe you can bisect it or debug it with qtcreator?

**Comment by DoctorSubtilis** [comment]
No idea... It's not a critical problem. What do you mean "debug with qtcreator"?

**Comment by sudden6** [comment]
qtcreator is the a development system for qt, which we use to develop qTox. You could set a breakpoint to the function displaying the loginform and take a look at why it's shown.

**Comment by DoctorSubtilis** [comment]
I'm not a developer :) . Too hard for me. Thank you!

**Comment by spyjoshx** [comment]
I can confirm that I USED to have this problem as well. It does not happen anymore.
System:
Ubuntu 16.04
Gnome 3
