### ISSUE TITLE
[Feature request] A way to ignore groupchat participants

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#4626]
##### Brief Description

Originally proposed in #4596 by @tetsaicn. Kinda like contact blocking proposed in #1120, but for groupchat participants, instead of friends.

Reproducible: Always

##### Steps to reproduce

1. Have someone spamming in groupchat

##### Observed Behavior
They keep spamming, it's not possible to ignore.

##### Expected Behavior
Messages from ignored participant would not be displayed.

##### UI

R-clicking on the username in the chatform, or in the list of participants would invoke menu in which there's a button to ignore/unignore.

Ignored participant could have their nick displayed with a different colour (colour alone is not very good) or some sort of symbol next to their nick to show that they're ignored.

##### Further concept

Perhaps there should be something like automatic rate-limiting, i.e. automatically ignoring participants that send hundreds/thousands of messages per minute. Automatic ignore would be removed shortly after the spam from participant ends, or if user manually removes the ignore. No idea if automatic rate-limiting would be desirable.

**Comment by mhtvsSFrpHdE** [comment]
Yep.
Right now if someone is invited into a group, seems even the creator of the group can't be drop him out. And there isn't any kind of group chat management.
We actually need one or more group chat manager(admin) who have the abilitity to...

Mute someone for a limited time.
Remove someone from group chat.
Decline join group chat request.
Decline join group chat request forever.

In Addition, if there is a pinned message shows to everyone,
that would be nice for tracking news, rules, etc.

**Comment by Diadlo** [comment]
Particularly fixed in #4610

**Comment by tox-user** [comment]
Implemented in https://github.com/qTox/qTox/pull/5124.
