### ISSUE TITLE
qtox repo @opensuse offline & not coming back?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#4635]
OS: Linux (*buntu 16.04)
qTox version: 201708291918~v1.6.0
Commit hash: 5648106b34fc7dc3ad4e169651a0cbbd0139170a
toxcore:  0.0.0 (?)
Qt version: 5.5.1
Reproducible: Always

For a couple of days now the repo `http://download.opensuse.org/repositories/home:/antonbatenev:/tox/xUbuntu_16.04/` seems to be offline. Coming here, I see that install instructions for qtox are to install and build, in stead of using this ppa and doing an apt install.

- Does this mean the original suse repo is history and won't be coming back online? Or is it just offline for the time being?
- If so, will there be another ppa for qtox? Can you share when and what it will be?

**Comment by sudden6** [comment]
Yes it's offline permanently and this one won't come back, see #4174 for details.

Please close this if all your questions are answered.

**Comment by ghost** [comment]
@sudden6 - THX for your reply! OK, get it, especially after looking at #4174, like you suggested.
Confusingly, `http://download.opensuse.org/repositories/home:/antonbatenev:/tox/xUbuntu_16.04/` seems to be online again now, so it's good to know that this will be flaky and, taking your remark, will disappear eventually.
Just to confirm: looking at the the discussion at #4174 with the potential new package maintainer, am I correct to assume that, if people prefer "_a ppa *tox_" instead of a "_local build tox_", they better go for utox instead of qtox?

**Comment by Diadlo** [comment]
@BelladonnavGF Projects differ not only in the presence of a repository. Inital question was answered, so closing
