### ISSUE TITLE
Sometimes qtox consumes 100% CPU after wifi dis/reconnects

### ISSUE THREAD

**Issue by l29ah** [qTox/qTox#4639]
Gentoo Linux, 1f44d603c4995de2c4fe5c218c0c3172ecc84c24, toxcore HEAD, qt-5.7.1; was there with earlier versions too.
Nothing suspicious in the log.

**Comment by sudden6** [comment]
How often is this reproducible?

Anybody knows how to debug this? Maybe using `perf` to find the offending function is possible?

**Comment by Diadlo** [comment]
Callgrind?

**Comment by Diadlo** [comment]
Also, probably, tox tries to reconnect => it use almost all available CPU. If so, it's normal, that process use all CPU while work

**Comment by Diadlo** [comment]
Needed info not provided for over a month, thus closing.
