### ISSUE TITLE
Audio cuts in and out during voice call, Lost packet in log

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#4640]
##### Brief Description
Linux mint 18.2
qTox version: v1.11.0-104-gb87248c
Commit hash: b87248c36b515083e00e12fc30be2e81c59f8050
toxcore: 0.1.2
Qt: 5.5.1
Hardware:  Desktop, 16GB RAM, SSD, i5, networking 30Mbps/5Mbps

##### Observed Behavior
In voice call for a couple minutes, computer under fairly heavy disk/network/cpu load updating a VM. Voice started cutting out for periods of 0.5s to 5s. Audio quality sounds fine during the periods it's still streaming. Closing and re-starting the call did not change the behaviour. Going to the audio/video settings menu seemed to fix the problem, could be to do with audio subscription/unsubscription or buffer clearing, or could just be coincidence. After that point the call was stable and high quality for the next hour.

In log I saw many "Recommended bitrate" messages, which are ignored by qTox, and "Lost packet" messages from toxcore.

##### Expected Behavior
If resource or network limitation is truly the problem, quality degradation would be preferred to periodic complete cut outs, possibly with accompanying UI letting the user know.

##### Additional Info
Full log file: [audio-breakup.txt](https://github.com/qTox/qTox/files/1290827/audio-breakup.txt)
Point when I started a call with the same person without improvement: 23:35:46
Point when it got better with A/V settings open: 23:36:11

**Comment by sudden6** [comment]
Audio bitrate change is currently not implemented. IIRC the reason was, that toxcore didn't provide reliable bitrate hints. Maybe that has changed in the mean time?

**Comment by anthonybilinski** [comment]
I can't comment on the reliability of the callback, but in toxav.c, the callback reduces only video quality if it's a video and audio call, and reduces only audio quality if it's an audio call. My logs indicate that qTox was repeatedly getting notifications to reduce video bitrate. So it looks like toxcore is incorrectly thinking that my audio only call had a high video bitrate, which perhaps affects its transport of audio?

The behaviour of the callback checking function doesn't look like it's changed between 0.1.2 and tip, but the incorrect thinking that there is video bitrate might have. I can see if I can reproduce this on tip of toxcore.

qTox build instructions indicate to use compile toxcore 0.1.2. Is there a stability reason for this rather than using the latest release, 0.1.10?

**Comment by sudden6** [comment]
I also only heard it from other, so it's probably time to retest that.

No, it's best to build against the newest toxcore release.

**Comment by anthonybilinski** [comment]
It's been disabled since here: https://github.com/qTox/qTox/commit/db52ef6e6a843faa8543b4726a5c281b8f1e1d97

We also set video bitrate on call accept even if it's not video, which is the reason for what I was seeing in logs.

I've re-enabled bitrate changing, with a minimum set below which we ignore any toxcore recommendation and accept drops, like is suggested in that follow up. Going some testing first and establish some reasonable minimums and make sure it recovers to defaults when network recovers.

**Comment by sudden6** [comment]
With the minimum values, maybe https://wiki.xiph.org/Opus_Recommended_Settings#Bandwidth_Transition_Thresholds will be helpful.

**Comment by anthonybilinski** [comment]
Testing on tip of toxcore, with both natural bad network by bouncing traffic around the world and with artificial extremely high packet loss using iptables I didn't see any "Recommended bitrate" callbacks calls by core, unfortunately. I saw errors that caused dropped frames of both audio and video, like "toxav_audio_send_frame error: Lock busy, dropping frame", but it seems unrelated to needing to reduce bandwidth.

Looks like there's not a whole lot that can be done for this in qTox at this point.

**Comment by anthonybilinski** [comment]
I've used audio calls extensively in both 1-1 and group calls, and haven't noticed this in ~1 year, now on qTox master tip (v1.16.3+) and toxcore 0.2.10. I think it's fair to consider this fixed.
