### ISSUE TITLE
All tooltips under settings display as blank beige boxes

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#4641]
##### Brief Description

OS: Ubuntu 16.04 Unity
qTox version v1.11.0-117-gedd43b7.
Commit hash:  edd43b7212234b5a2b6e12b2fe5e6cf0294cb398
toxcore:  0.1.10
Qt:  5.5.1

Reproducible: Always

##### Steps to reproduce

1. Open settings menu
2. Hover over any setting

##### Observed Behavior
A beige box of varying size depending on the setting appears, but contains no text.

##### Expected Behavior
The tool tip appears containing text.

#### Additional notes
Not present for my friend, also on Ubuntu 16.04, but on Gnome

**Comment by Diadlo** [comment]
I suppouse it can be problem with colors. Can you check, maybe it's light-gray text on white background? Or something like this

**Comment by anthonybilinski** [comment]
You are correct! If I zoom in all the way I can see the beigey-white text on the beige background ![broken-tooltip](https://user-images.githubusercontent.com/10469203/30295677-427b0cf6-96f6-11e7-9ccf-00335baa3f6f.png)

**Comment by Diadlo** [comment]
Yes, AFAIK it's proglem with css
