### ISSUE TITLE
:\ emoji is broken by font styling

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#4646]
##### Brief Description

Commit hash:  c4995971

Reproducible: Always

##### Steps to reproduce

1. Enable "Show formatting characters" from text style formatting
2. Send :\

##### Observed Behavior
![image](https://user-images.githubusercontent.com/10469203/30356051-dea07fc6-97eb-11e7-9841-e51e124fb8e7.png)

##### Expected Behavior
![image](https://user-images.githubusercontent.com/10469203/30356058-e6abaf88-97eb-11e7-82dc-6f44af7c2f58.png)

##### Additional Info
I've narrowed it down to the the regex `(?<=^|[^/<])[/]{1}(?![/ \n]).+?(?<![/< \n])[/]{1}(?=$|[^/])` matching against `<img title=":/" src="key::/"\>` in textformatter.cpp

It matches against `/" src="key::/` and inserts italics turning it into `<img title=":<i>/" src="key::/</i>"\>` resulting in a broken emoji. I don't have enough regex-foo to go beyond that.

**Comment by sudden6** [comment]
Should be handled by #4593

**Comment by zetok** [comment]
Mentioned PR was merged, and it seems to be fixed on 154002c0, thus closing this PR. If it's not fixed, please comment for reopen.

**Comment by anthonybilinski** [comment]
Confirmed fixed :+1:
