### ISSUE TITLE
qtox.pro links the same libraries both statically and dynamically

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#4653]
Commit hash:  d974c60f

At https://github.com/qTox/qTox/blob/d974c60f0cbdecb48454c8e4c8952dc009c9228e/qtox.pro#L234 we link avformat, avcodec, avutil, and swscale dynamically, right after linking them statically at https://github.com/qTox/qTox/blob/d974c60f0cbdecb48454c8e4c8952dc009c9228e/qtox.pro#L213

This seems like a mistake, but I'm no expert on build systems. From my googling it looks like statically and dynamically linking the same library is never something that you should do.

**Comment by sudden6** [comment]
Since this could be something leftover from Jenkins build fixes, cc @tux3  and @nurupo

**Comment by anthonybilinski** [comment]
Closing since qtox.pro has been removed.
