### ISSUE TITLE
Profiles are erased when have same name

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#466]
26eb08aa00bdfe4ea3d2d90103c417239736c741

There are 2 profiles to import: `./{1,2}/profile.tox`

After importing both of them, one is silently erased.

Please fix.

**Comment by ghost** [comment]
Perhaps the files for profiles could be named a la Mozilla's convention, with a bit of random alphanumeric text before the profile name to prevent name collisions.

ab1cd2ef.same_profile_name.tox
3gh4ij5kl.same_profile_name.tox

Or perhaps just append _X to duplicate profile names.

profile.tox
profile_1.tox

**Comment by dubslow** [comment]
I'll just check for an existing profile with that name, but I can't get to it now.
