### ISSUE TITLE
Ubuntu tooltips for emoji, file attach, and send are solid black

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#4667]
##### Brief Description

OS: Ubuntu 16.04 Unity
Commit hash:  6a5a7564
Qt: 5.5.1

Reproducible: Always

##### Steps to reproduce

1. Hover any of the bottom right buttons

##### Observed Behavior
![tooltip](https://user-images.githubusercontent.com/10469203/30666907-a06d496c-9e0a-11e7-8c14-5263a7f56605.png)

This is probably another CSS issue like #4641. Could be a clash between our custom CSS and theme default CSS. Is the goal to have our CSS follow system theme, or our styling be consistent across themes? Currently it seems like most of our CSS defines absolute colours regardless of theme.

**Comment by anthonybilinski** [comment]
This was caused by my change in fc1ed101 which changed the text colour of QToolTip's to black so that my setting's tooltips were visible.

**Comment by sudden6** [comment]
The goal was to make qTox look uniform across all platforms. But IMO it would be good to have a setting to follow the system theme.

**Comment by anthonybilinski** [comment]
For the "uniform across all platforms" mode (which I think is the intended default mode), is there some kind of reference design? Currently (Ubuntu 16.04 Unity) my tooltips in the settings menu are black on beige. My tooltips for the bottom left {add friends, create group..} are white on black, which my bottom right buttons (now broken) used to be before I changed the colour for settings tooltips to black on beige in #4641, which I guess leaked into the bottom right buttons causing them to be black on black.

My friend on Ubuntu 16.04 Gnome has his bottom right buttons as black on beige, so I think if I forced the colour of the text there to be white (solving my problem), it would then break the tooltips for him.

Should all tooltips be black on beige? Should main buttons be white on black with more minor tooltips as black on beige? Not really sure how to advance on this without causing a domino effect of more UI problems for users on different platforms.

**Comment by sudden6** [comment]
I wonder how how the black color from the text leaked into the the background color of the other tooltips, probably the hierarchy of the styling is pretty fucked up.

For "uniform across all platforms" mode, the general design of tooltips should be black text on beige or white background, this seems to still be the default for most things.

**Comment by anthonybilinski** [comment]
Yeah it must have been a parent style falling onto a child widget that has no explicit tooltip properties defined, and just inherited whatever.

I'll change these tooltip's to be hardcoded black on beige at a higher level in the styling tree to match my other tooltips, and then test on a couple platforms that that doesn't cause any other problems.

**Comment by anthonybilinski** [comment]
https://bugreports.qt.io/browse/QTBUG-41313
:rage:
