### ISSUE TITLE
[Feature request]: Command line option to create a new profile

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#4673]
With an instance of qTox running, it's not possible to open a new profile. You can open an existing profile with "qtox -p <profileName>", but if <profileName> doesn't exist, it errors and exits. Running with just "qtox" activates the existing open window.

It seems like the only existing way to create a new profile while logged in is to log out (to get to the login screen), create the profile, then log back in, which is obviously inconvenient.

I think adding a command line option "qtox -l" ('l' for "login") that opens the  login window regardless of running instances, and maybe also making "qtox -p <invalidProfileName>" open the login screen instead of exiting, since then the user gets a dropdown of available profiles, in case they misspelled the profile they wanted.

I don't think actually creating the profile from command line is useful, since then there would be plaintext passwords in history, we'd lose the nice password strength meter etc.

**Comment by sudden6** [comment]
IMO a that would be a great idea, also it wouldn't break any backwards compatibility, which makes it even greater ;)

To be honest I don't even like the default behavior of opening the running instance and would like to see the login screen in that case.

**Comment by anthonybilinski** [comment]
Yeah I agree personally, but like I brought up in https://github.com/qTox/qTox/issues/3483#issuecomment-329955463, some people have the use pattern of closing to tray, then opening from start/search/side-bar and expecting that to re-open the running instance. I can't think of a way to make it work naturally for both use cases :(

**Comment by anthonybilinski** [comment]
It might make sense to link "default open behaviour" to the "exit to system tray" setting. If exit to tray is selected, try to activate the running instance and force the user to "qtox -l" to open login directly, and if exit to tray is not selected (default) it opens login directly on new open, since users would likely just un-minimize their running instance from sidebar/bottom bar/alt-tab if that's what they wanted.
