### ISSUE TITLE
[Regression] Can't set auto away time

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#4680]
OS: Ubuntu 16.04
Commit hash:  8108bfdc

Reproducible: Always

On commit 8108bfdc and its descendants, my auto away time is greyed out and unselectable.
![image](https://user-images.githubusercontent.com/10469203/30768058-9746fb0e-9fb7-11e7-9071-aa4918da777f.png)

On commit ed634ae0 (it's only parent) it works as expected.

**Comment by sudden6** [comment]
Interesting, can you upload the output of a fresh cmake run?

**Comment by anthonybilinski** [comment]
pre-change: [pre-cmake.txt](https://github.com/qTox/qTox/files/1328638/pre-cmake.txt)
post-change: [post-cmake.txt](https://github.com/qTox/qTox/files/1328640/post-cmake.txt)

key difference being XSS found becomes XSS not found

**Comment by sudden6** [comment]
I guess the problem lies in this line: https://github.com/qTox/qTox/blob/master/cmake/Dependencies.cmake#L64

since the last changes from @nurupo the headers also required to mark a package as found, and for libxss no headers are found.

I'll see if i can fix that.

**Comment by nurupo** [comment]
Oh wow, I have made such a silly mistake. I will make a PR fixing that, sorry.

**Comment by nurupo** [comment]
>and for libxss no headers are found.

Well, the issue is that the `arg_HEADER` is empty to begin with when looking for XSS, there was no `HEADER` argument provided when calling this function. So the fix is either provide the name of the header file (which is probably the best fix) or change the if-condition so that finding the header is not required when it's not specified (which is what I have done in the PR). The better fix is better because it supports the case when `libxss` is not system-wide installed, while the latter fix doesn't. I should probably change my PR to use the better fix, huh.  What is the name of XSS's header file that cmake should be looking for?

**Comment by sudden6** [comment]
Oh, your fix is also needed, but I just discovered that `libXss` comes with `*.pc` files, so I think we can use pkg-config to find it.

**Comment by nurupo** [comment]
There is also a thing that cmake comes with [a find module for all x11 libs, including libxss](https://github.com/Kitware/CMake/blob/master/Modules/FindX11.cmake), but we don't really want to use both `search_dependency()` and the find modules.

**Comment by sudden6** [comment]
If there exist find modules for all libs we need, we should really consider using them.

**Comment by nurupo** [comment]
That would mean removing `search_dependency()` and replacing it with find modules. I honestly not even sure what is better.

**Comment by nurupo** [comment]
>If there exist find modules for all libs 

Not for all of the libraries have them, but I would expect that majority do. They also inconsistent most of the time, e.g. one module might define `LIBFOO_LIBRARIES` with just a single lib, while another `LIBFOO_LIB`, while yet another` LIBFOO_LIBRARY`.

**Comment by reyaz006** [comment]
I'm not quite sure I understand this. I have the same problem on Windows (1.13.0). Was this issue closed because the supposed fix was implemented or because there are no plans to fix it?

**Comment by sudden6** [comment]
@reyaz006 you're probably hit by https://github.com/qTox/qTox/issues/4860 not this issue. For both a fix is in master, but there wasn't a release since then. You can use the nightly builds until we ship a new release.
