### ISSUE TITLE
Group chat is restricted by core?

### ISSUE THREAD

**Issue by szh7379** [qTox/qTox#4683]
I had post it there. 

https://github.com/TokTok/c-toxcore/issues/595

but the devs didn't focus on it, and look like qTox is more active than toxcore.

Tox's group was bad, people need to creat it when they log in every time. right, it is p2p, no data be saved in server, but i think an universal value of a group can be created in everyone's drive, when you log in, if the tox can't find it online, then creat it. it can sovle the problem.

Like this funtion,  i don't know if qTox can implement it independently in qTox, or it must be built-in toxcore.

**Comment by sudden6** [comment]
There's actually https://github.com/TokTok/c-toxcore/pull/295 to do exactly what you propose. Maybe you should comment there.

If that answers everything please close this issue.

**Comment by szh7379** [comment]
@sudden6 Thank you, just too many time, my fault, i think it is easy,  it go so far as one year.
