### ISSUE TITLE
Icons, images, and emoji do not appear

### ISSUE THREAD

**Issue by meanie-py** [qTox/qTox#4685]
##### Brief Description
Icons, images, and emoji do not appear in the latest stable windows build or in the nightly.

OS: Windows 8.1
qTox version:  v1.11.0-36-g0843b77
Commit hash:   0843b770c64204a078e0d73fe5f3b71b8ef17e52
toxcore:  0.1.9
Qt:   5.6.2
Hardware:  
…

Reproducible: Always

##### Steps to reproduce

1. Download the latest stable version or nightly version
2. Open the executable on windows
3. Viola

##### Observed Behavior
See the image attached.

##### Additional Info
Log: [qtox.txt](https://github.com/qTox/qTox/files/1327758/qtox.txt)
![capture](https://user-images.githubusercontent.com/9333731/30786787-bcd165a0-a140-11e7-9216-dc9831199d80.PNG)

**Comment by anthonybilinski** [comment]
No longer present on Windows as of v1.17.6, closing.
