### ISSUE TITLE
Feature request: microphone voice activation

### ISSUE THREAD

**Issue by tox-user** [qTox/qTox#4686]
It's often important for the user to able to control which sounds are transmitted. It also helps to save the bandwidth and if there is any echo from the speakers such feature could make it less annoying if the user was able to tune the sensitivity of voice activation.

There should be a setting in qTox that allows to enable this feature and it would also be great if there could be a slider for sensitivity.

If I understand correctly push to talk with a global hotkey is either very hard or impossible to add to qTox. This feature could replace the need for push to talk for many users. You can find more reasons to why this is important in this issue: https://github.com/qTox/qTox/issues/903

**Comment by sudden6** [comment]
Note to devs: voice activation could maybe be implemented through libfilteraudio, which provides voice activity detection (VAD).

**Comment by gstark667** [comment]
I am interested in this as well.

I looked through the filter_audio library and I've found the previously mentioned VAD funcitonality.
I'm going to try implementing this in my own forked repo and I'll submit a PR if I come up with something usable.

**Comment by gstark667** [comment]
@tox-user are you looking for volume based voice detection (such as what teamspeak, mumble and discord offer)?

I looked at the VAD that libfilteraudio provides and it appears to be more oriented towards removing things that are not human voice. It doesn't really give a good representation of whether or not the user is talking.

I have a working implementation in my fork: https://github.com/gstark31897/qTox
I was able to implement it for the current audio pipeline (and I can add it to the experimental pipeline) since I did it without libfilteraudio.
I need to clean it up a bit before I make a PR.

**Comment by tox-user** [comment]
@gstark31897 I would like the audio to be transmitted only when the user is talking, like in those apps that you mentioned.

I tested your feature with echo bot (echobot@toxme.io) and it is working, but unfortunately my voice often cuts out when threshold is above zero which makes a conversation impossible. It seems that it gets worse when threshold is higher. I like the volume display that you added, it helps with setting microphone gain.

**Comment by gstark667** [comment]
@tox-user thanks for the feedback.

I was thinking about ways to eliminate the cutout issues. I'm current considering using multiple audio frames to get a better average volume and/or using a timer to continue broadcasting after the volume has fallen below the threshold. I haven't gotten around to either, but I'll update this thread when I make some progress.

**Comment by tox-user** [comment]
@gstark31897 sounds like a good idea. Good luck! Maybe you can check how it's implemented it in Mumble: https://github.com/mumble-voip/mumble. 

Their readme says that they're using Qt. I'm curious if Mumble has a global hotkey for push to talk and how they've done it. Maybe the same approach could be used to add it to qTox.

**Comment by gstark667** [comment]
@tox-user I took a quick look at mumble, it appears that they have a minimum and maximum threshold for audio (mumble starts broadcasting when it goes over the threshold and it stops broadcasting when it goes under the threshold). It might be worth doing, so I'll try it out when I get to it.

Mumble does have global hotkeys, but it appears that they created separate implementations for each platform. I'm interested in working on the push to talk request after I finish the voice activation work, but it should probably be part of a different PR.

**Comment by gstark667** [comment]
@tox-user I think I've got most of the audio cutout solved. I ended up implementing a timer that keeps audio on for a specified period after the volume drops below the threshold (this is the "voice hold" option in the audio settings menu). The repo I sent you has the updated code if you want to check it out.

I have a bit of cleanup and checking to do, but I should be able to do a PR soon if you're happy with the change.

**Comment by tox-user** [comment]
@gstark31897 it works much better now! The audio was still cutting out a bit out, but it's possible that the issue was on my side. You should create a pull request and let more people test it and see what they think. There probably will need to be some way for to switch between voice activation and regular mode and I think two sliders for this might be too confusing for most users. Perhaps you should choose the best value for voice hold and just use that. Those are details though.

Before you create a pull request maybe it would be a good idea to create a new branch and make all your changes into just one or a few commits? With so many changes it might be easier to review them that way. You might also want to read about commit message format if you haven't yet: https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#commit

**Comment by gstark667** [comment]
@tox-user sorry I haven't responded on this for a few weeks, university picked up and I haven't had time to work on it.

I'll pick a value to use for voice hold and pull out the second slider.
I'll also squash my commits together and make a branch for review (with a proper commit message) and make a pr this weekend.

**Comment by Diadlo** [comment]
Implemented in #4790
