### ISSUE TITLE
Update bootstrap nodes list

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#4690]
The bootstrap nodes list hasn't been updated in a while, fetch the active nodes from nodes.tox.chat and put them into the default `settings.ini`

**Comment by anthonybilinski** [comment]
The time to seeing friends online after opening client is much much faster with this change. It went from annoyingly slow (~20s) to almost instant (~3s). Updating the list more often is probably worthwhile, and perhaps investigation into the bootstrapping algorithm to better handle offline nodes, though that's possibly in the hands of toxcore.
