### ISSUE TITLE
 add libsodium-dev to debian build dependencies in INSTALL.md

### ISSUE THREAD

**Issue by klopsi** [qTox/qTox#4691]
##### Brief Description
* Add libsodium-dev to debian build dependencies in INSTALL.md

* Add note that toxcore needs to be built seperately.

**Comment by PKEv** [comment]
closed

**Comment by tox-user** [comment]
Currently we do list libsodium-dev as one of the dependencies on Debian. We also have instructions for compiling toxcore. 

Closing.
