### ISSUE TITLE
cmake link error: undefined reference to symbol 'crypto_hash_sha256'

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#4695]
##### Brief Description

OS: Ubuntu 16.04
Commit hash:  c81de4f5fdffc0dd3783fba7eee077c792f70bc6
toxcore:  4ceaad505db02e048a227df99802a7728ffa78af

Reproducible: Always

##### Steps to reproduce

1. Build on OBS

##### Observed Behavior
```
[  224s] [ 85%] Linking CXX executable qtox
[  224s] /usr/bin/cmake -E cmake_link_script CMakeFiles/qtox.dir/link.txt --verbose=1
[  224s] /usr/bin/x86_64-linux-gnu-g++   -g -O2 -fdebug-prefix-map=/usr/src/packages/BUILD=. -fstack-protector-strong -Wformat -Werror=format-security  -std=c++11 -fno-exceptions -fno-rtti -fPIE -Wstrict-overflow -Wstrict-aliasing -fstack-protector-all -Wstack-protector -pthread -pthread   -Wl,-Bsymbolic-functions -Wl,-z,relro -pie -Wl,-z,now -Wl,-z,relro CMakeFiles/qtox.dir/qrc_res.cpp.o CMakeFiles/qtox.dir/qrc_translations.cpp.o CMakeFiles/qtox.dir/qrc_emojione.cpp.o CMakeFiles/qtox.dir/qrc_smileys.cpp.o CMakeFiles/qtox.dir/src/main.cpp.o CMakeFiles/qtox.dir/qtox_automoc.cpp.o  -o qtox -rdynamic libqtox_static.a /usr/lib/x86_64-linux-gnu/libQt5Network.so.5.6.1 /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5.6.1 /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5.6.1 /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.6.1 /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5.6.1 -lavcodec -lavdevice -lavformat -lavutil -lexif -lqrencode -lsodium -lswscale -lsqlcipher -lvpx -lm -ltoxcore -ltoxdns -ltoxencryptsave -lm -lpthread -ltoxav -lopus -lvpx -lm -ltoxcore -ltoxdns -ltoxencryptsave -lm -lpthread -lopenal -lX11 -lXss -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lglib-2.0 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.6.1 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.6.1 -ltoxav -lopus -lopenal -lX11 -lXss -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lfontconfig -lfreetype 
[  225s] /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libtoxcore.a(libtoxcore_la-crypto_core.o): undefined reference to symbol 'crypto_hash_sha256'
[  225s] //usr/lib/x86_64-linux-gnu/libsodium.so.18: error adding symbols: DSO missing from command line
[  225s] collect2: error: ld returned 1 exit status
[  225s] CMakeFiles/qtox.dir/build.make:3305: recipe for target 'qtox' failed
```

##### Additional Info
full log: [failed-link.txt](https://github.com/qTox/qTox/files/1338636/failed-link.txt)

I don't see this when building locally, but my link arguments locally are a bit different. I think the issue is that libsodium is linked before libtoxcore in the argument list. I workaround I used was to add ${ALL_LIBRARIES} as twice as the target_link_libraries to qTox, so the libraries are in the correct order no matter what, but this seems a bit hacky.

**Comment by sudden6** [comment]
shouldn't libtoxcore already link against libsodium via pkg-config flags? maybe they are not passed correctly?

**Comment by anthonybilinski** [comment]
I'm not sure if this answers your question, but changing toxcore/other/pkgconfig/toxcore.pc.in to include -lsodium under Libs does not fix the issue in qTox, and moving qTox's dependency search in cmake/Dependencies.cmake of toxcore before the dependency search of libsodium does fix the issue.

**Comment by sudden6** [comment]
I see you are using c-toxcore built with automake, can you try one built with cmake?
For reference, output on your build system:
``` [  252s] -- TOXCORE LIBRARIES:    toxcore;toxdns;toxencryptsave;m;pthread ```

and output of pkg-config on my system:
``` pkg-config --libs toxcore -L/usr/local/lib -ltoxcore -lpthread -lrt -ltoxcrypto -ltoxnetwork -ltoxdht -ltoxnetcrypto -ltoxfriends -ltoxmessenger -ltoxgroup -lsodium ```

Somehow in your build it doesn't seem to include `-lsodium` which I guess is the reason it doesn't work.

**Comment by anthonybilinski** [comment]
Building toxcore with cmake does allow qTox to link correctly against it without any qTox build hacks. Unfortunately I get some some other errors on 64-bit versions only, and since automake seems to be their recommended build method currently I'll follow up with TokTok regarding that. Ticket: https://github.com/TokTok/c-toxcore/issues/599
