### ISSUE TITLE
return-statement with no value [add Travis CI to project]

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#47]
```
widget/camera.cpp: In member function ‘virtual bool Camera::present(const QVideoFrame&)’:
widget/camera.cpp:89:9: error: return-statement with no value, in function returning ‘bool’ [-fpermissive]
make: *** [camera.o] Error 1
```

Consider adding Travis CI to repo for checking build status after commits and pull requests.

**Comment by tux3** [comment]
I'm always compiling locally before pushing. This was a mistake, I accidentally pushed without it and didn't notice.
Jenkins warned me after the push and history was rewritten, sorry.

**Comment by suhr** [comment]
> This was a mistake, I accidentally pushed without it and didn't notice.

Better to add git's pre-commit hook to automatize this.

**Comment by tux3** [comment]
I guess, but it feels a bit redundant since I already have jenkins and local builds.
