### ISSUE TITLE
Blog inside qTox

### ISSUE THREAD

**Issue by abcd99** [qTox/qTox#4714]
OS: all  
qTox version: all

##### Expected Behavior
Briar has a built-in blog. You can use it to post news and updates about your life. Your blog is automatically shared with your contacts, and their blogs are shared with you. so we hope that Tox  can write blog too. Tox's number of users more than 100 million, like WeChat or Skype. In the near future, people are in love with Tox, every day habitual look at friends blog. This will turn the authoritarian state into a country of freedom of expression. For example China, Please help us without freedom of speech,please.

**Comment by sudden6** [comment]
You should also open an issue in https://github.com/TokTok/c-toxcore, because such a feature should be implemented for all Tox clients probably.

**Comment by sudden6** [comment]
This is not in the current focus of qTox anymore.
