### ISSUE TITLE
Do Tox has a Tracker Server?

### ISSUE THREAD

**Issue by abcd99** [qTox/qTox#4715]
Do Tox has a Tracker Server?  If the server is blocked, will the tox work?  What is stopping people from doing DNS cache pollution（DNS cache poisoning）?

**Comment by tox-user** [comment]
I don't know the answer, but perhaps this will help: https://tox.chat/faq.html#tox-central-servers

**Comment by Diadlo** [comment]
Answered, then close

**Comment by tox-user** [comment]
The link I provided only answered the first part of the question. It doesn't answer if Tox can work when bootstrap nodes are censored nor the part about DNS.
