### ISSUE TITLE
impossible to send messages to people. when i send a message it has a reload sign. my friends can talk to me but not me

### ISSUE THREAD

**Issue by azulek96** [qTox/qTox#4719]
![inkedqtox_screenshot_2017-10-09 00-50-17 435_li](https://user-
##### Brief Description

OS: Windows 10
qTox version: v1.11.0
Commit hash: 66b133c8d4a4d8f60e62475b0b56b509527b1488
toxcore: 0.1.9
Qt: 5.6.2
Hardware: 
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. 
2. 
3. …

##### Additional Info
(links, images, etc go here)

----

More information on how to write good bug reports in the wiki: https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by sudden6** [comment]
1. Screenshot link is broken
2. you are using a very old version of qTox, try with the nightly builds from https://build.tox.chat/view/qtox/job/qTox-cmake-nightly_build_windows_x86-64_release/

**Comment by Diadlo** [comment]
Needed info not provided for over a month, thus closing.
