### ISSUE TITLE
[Proposal] Don't upscale image preview, only downscale if necessary

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#4733]
##### Observed Behavior
Hovering over an image in chat causes it to preview. The image is scaled to keep aspect ration and be 50% of screen height and/or 50% of screen width.

Sending a small image i.e. of a piece of text can result in a huge preview of giant blurry grey text that is harder to read than if it was just displayed at the actual size of the capture. I don't think upscaling is generally desirable and it adds blur.

##### Expected Behavior
If the image's width and height are both under 50% of screen, do not scale at all and preview at natural size. If either is larger, then downscale to 50%, like we currently do.

Do people agree that this behaviour should be changed, or do they prefer the way it is, scaling any size image to be 50% of width and 50% of height?

**Comment by sudden6** [comment]
I think this is a good idea.
