### ISSUE TITLE
CPU 25% Loading Iddle

### ISSUE THREAD

**Issue by Nochatman** [qTox/qTox#4739]
##### Brief Description

After Update version, constant CPU loading in Iddle

OS: Windows Server 2016
qTox version: version v1.11.0.
Commit hash:  66b133c8d4a4d8f60e62475b0b56b509527b1488
toxcore:  0.1.9
Qt:  5.6.2
Hardware:  Intel Xeon 1270 V6 - 64Gb - SSD NVMe
…

Reproducible: Always after update

##### Steps to reproduce

1. Update para new version
2. After login, CPU constant in 25%
3. …

http://i64.tinypic.com/15gug44.jpg
----

**Comment by sudden6** [comment]
Does this only happen directly after the update or constantly?

**Comment by Diadlo** [comment]
Screenshot from the issue: ![image](https://user-images.githubusercontent.com/6306608/33175305-659bbd84-d06c-11e7-9074-233f056ff8c3.png)

**Comment by ChristophHaag** [comment]
On Linux I get high cpu usage with current git master bb26485db6fed706f4ebccaffe35740394210032

![screenshot_20171128_151519](https://user-images.githubusercontent.com/781076/33324131-fbb55d8a-d44e-11e7-8e8d-c38dd66b29af.png)

It happens as long as the GUI is displayed. Minimized or minimized to tray icon it doesn't cause load.

May be the same issue.

qt5 5.9.3

edit: My issue is only 4 days old so I made a new one https://github.com/qTox/qTox/issues/4843

**Comment by ChristophHaag** [comment]
> 73dcbd2e60e98d305f4d1d36c6d2a1b4bcd9de13 is the first bad commit

`MaskablePixmapWidget::paintEvent()` is called a lot and it looks like `QLabel::setPixmap()` is an expensive function to call https://github.com/qTox/qTox/commit/73dcbd2e60e98d305f4d1d36c6d2a1b4bcd9de13?diff=unified#diff-ac3ece10b10583d2d275f26a143e91a4R97
