### ISSUE TITLE
No audio output whatsoever

### ISSUE THREAD

**Issue by XQ6FOD** [qTox/qTox#4742]
OS: Windows XP SP3
qTox version: v1.11.0
Commit hash: 66b133c8d4a4d8f60e62475b0b56b509527b1488
toxcore: 0.1.9
Qt: 5.6.2
Hardware: ASUS P8H77-V LE mainboard, Intel G2010 CPU, 4GB RAM, Soundblaster Audigy using kX driver 

Reproducible: Always

##### Steps to reproduce

Install qTox, try to use.

##### Observed Behavior

No audio output whatsoever. No sounds for messages, connections, etc, no test sound, and no received audio. At the same time, my TX audio is fine (other parties can hear me), video works both ways, text messages too. Seems to be some bug in qTox-to-soundcard communication. This soundcard and driver combination has worked flawlessly with every other software I ever tried, including another Tox client. qTox defaults to the correct playback device (kX Wave SB0092 10k2 [d000] 0/1). Windows system sounds, movie player audio, etc, all continues to work well while qTox audio doesn't get through. Volume slider in qTox is fully up. Moving volume slider, toggling test sound checkbox, still absolutely no audio output from qTox. No error messages displayed either.

##### Expected Behavior

Normal audio output.

----

**Comment by tox-user** [comment]
Maybe try newer qTox version?

**Comment by sudden6** [comment]
That's already the newest version, unfortunately we forgot to bump the version number in the code...

**Comment by sudden6** [comment]
No follow up, closing.
