### ISSUE TITLE
[Feature] more useflags under gentoo

### ISSUE THREAD

**Issue by alphaonex86** [qTox/qTox#4758]
##### Brief Description

OS: Linux Gentoo
qTox version: last

Hi, I wish more useflags under Gentoo to minimize the dep, and drop the not used code. For example I wish drop the support of video and call (and then drop the dep ffmpeg v4l), drop audio, to keep just text and file.

Cheers,

**Comment by sudden6** [comment]
Audio and Video are very tightly integrated with qTox and it would be a huge amount of work to remove it. Maybe your use case is better served by https://github.com/JFreegman/toxic
