### ISSUE TITLE
Error trying to install .deb

### ISSUE THREAD

**Issue by dcharles525** [qTox/qTox#478]
Error: Dependency is not satisfiable: libstdc++6(>=4.9)

Linux Min, 64 bit deb

**Comment by dubslow** [comment]
Mint? Which version? That should almost certainly not happen on 17.

**Comment by dcharles525** [comment]
I'm running Linux Mint 17 actually...:/

**Comment by tux3** [comment]
Seems like I compiled with GCC 4.9 by mistake, I'll downgrade to an older version.

EDIT: I can't seem to find libstdc++-6 4.8 anywhere, I'll try building ubuntu's gcc-4.8 but no promises.

**Comment by dubslow** [comment]
Give this a try https://jenkins.libtoxcore.so/job/qTox-Linux-pkg/

**Comment by dubslow** [comment]
```
<tpe> qtox depends on libstdc++6 (>= 4.9); however:
<tpe>   Version of libstdc++6:amd64 on system is 4.8.2-19ubuntu1.
```

I linked him to the most recent build, so...

**Comment by tux3** [comment]
> I linked him to the most recent build

You mean my packages or toxcore.so's packages ?
I built gcc-4.8 (Debian 4.8.2-19ubuntu1) and got rid of 4.9 but somehow it still links with libstdc++6 4.9

So I managed to build packages that I can't even install on the build machine. I'm that bad at packaging!

**Comment by dubslow** [comment]
That was these releases, he was having more symbol issues with the Jenkins build.

**Comment by tux3** [comment]
I'll try doing something stupid like linking libstdc++ statically and see if it works.

**Comment by dubslow** [comment]
............LOL

**Comment by tux3** [comment]
.. yep, that was a Bad Idea™

I think I'll just give up and make real packages. No static linking other packages and one package per distro version (deb stable, deb testing, ubuntu, etc).

**Comment by dubslow** [comment]
@tux3 @stqism 

Concerning OpenCV and the Ubuntuverse™, this was just posted to #tox:

> <mind_combatant> so, from the apt repository, qtox is currently uninstallable for me. it depends on "libopencv2.4-highgui" and "libopencv2.4-core", but in at least the ubuntu repos, those are named "libopencv-highgui2.4" and "libopencv-core2.4", so it can't resolve the dependencies.

As far as I know, this is a new observation, and would also seem to be the core problem. stqism I suggested it before (half in jest), but it might be worth it to setup an Ubuntu 14.04 virtual machine somewhere Jenkins can use and create separate Ubuntu packages from the Debian stable ones.

**Comment by tux3** [comment]
I've seen that <a href="https://github.com/kytvi2p/qTox">Kill Your TV has made separate packages</a> for Debian (stable/unstable) and Ubuntu 14.04, though I haven't tested all of them.

Perhaps we could duplicate this setup.

**Comment by dubslow** [comment]
Indeed, twas the inspiration :D

**Comment by dcharles525** [comment]
Tried latest binary..I SAW QTOX POP UP :tada: 

Then an error :( 

No settings file found, using defaults 
Settings: Loading from  ":/conf/settings.ini" 
Using embeded bootstrap nodes list 
Error loading translation "en" 
No system tray detected! 
Core: loading Tox from "/home/david/.config/tox/data" 
./qtox: symbol lookup error: ./qtox: undefined symbol: _ZN9QTextEdit18setPlaceholderTextERK7QString

On Elementary OS 64bit

So close guys :)

**Comment by tux3** [comment]
This should be fixed.
