### ISSUE TITLE
Why is qTox using so much bandwidth?

### ISSUE THREAD

**Issue by ste-h** [qTox/qTox#4795]
##### Brief Description

OS: Windows10
qTox version: v1.7.0
Commit hash:  12c21b21d2d62a27b0002c1add7e4d7faa0d018d
toxcore:   0.1.5
Qt:  Qt version: 5.5.1
…

Reproducible: Always

##### Steps to reproduce

1.  have qtox open
2.  look network usage

##### Observed Behavior
qTox is consantly using 100B/s to 1.5Kb/s DL and UL

I don't do any file transfers / calls / videos etc using qTox, only text messages / links to 3 people.

##### Expected Behavior

Less data usage than skype microsoft botnet - currently tox has used over 2x the upload and I often screenshare / cam using Skype

##### Additional Info
https://i.imgur.com/LqxwPxi.png - less than a weeks worth of data usage, no file transfers / calls etc
----

Is there any explation for why qtox would be using so much data? I've checked with a few other people and they've noticed similar usage but for whatever reason they aren't phased by it.

**Comment by Chiitoo** [comment]
It's not uncommon to be wondering about this, and in fact, there is this FAQ entry:

https://github.com/qTox/qTox/wiki/FAQ#network-usage

It states the following:

> qTox is P2P – it needs to search, connect to, and maintain the connection to the friends and other network nodes all the time in order to stay online. This generates network traffic. The more friends you have, the bigger network usage.
> 
> Networking is managed by toxcore library, and eventual improvements to qTox's network usage depend on toxcore development.

That said, I'm not certain at this time /how/ much exactly should be expected, as I never /really/ looked into it yet myself...

**Comment by tox-user** [comment]
You could try a newer version of qTox. It will use a newer version of toxcore and it might have improved since the version you are using.

**Comment by sudden6** [comment]
1.7 is pretty outdated, in recent versions there were some improvements to reduce idle data usage, you might want to upgrade and test again.

**Comment by sudden6** [comment]
Probably not an issue and no reply, closing.
