### ISSUE TITLE
WIP: ToxIdenticon - howto

### ISSUE THREAD

**Issue by zoff99** [qTox/qTox#4798]
https://github.com/zoff99/ToxAndroidRefImpl/blob/zoff99/Identicon_spec_dra/Identicon.md

**Comment by zoff99** [comment]
@sudden6 can you have a quick look?

**Comment by sudden6** [comment]
Personally I find the formatting pretty hard to read, but I think the algorithm is correct.

**Comment by sudden6** [comment]
Now that the spec is done, I'll close this one.
