### ISSUE TITLE
Crash after sleep

### ISSUE THREAD

**Issue by tobeaver** [qTox/qTox#4802]
In the case of error, in `tox_conference_peer_get_name_size`, it return `length == ~0` and segmentation fault occurs. This is happen when internet link is lost.
```
./src/core/core.cpp
    QStringList names;
    for (uint32_t i = 0; i < nPeers; ++i) {
        size_t length = tox_conference_peer_get_name_size(tox, groupId, i, &error);
        QByteArray name(length, Qt::Uninitialized); // <<<<< Crash here <<<<<
        uint8_t* namePtr = static_cast<uint8_t*>(static_cast<void*>(name.data()));
        bool ok = tox_conference_peer_get_name(tox, groupId, i, namePtr, &error);
        if (ok && parsePeerQueryError(error)) {
            names.append(ToxString(name).getQString());
        }
    }
```

**Comment by sudden6** [comment]
for clarification, with `length == ~0` you mean length is 0, right?

**Comment by Diadlo** [comment]
@sudden6 No `~0` is bitwise "not" for zero => -1

**Comment by sudden6** [comment]
stupid me, shouldn't look at code before coffee...

**Comment by Diadlo** [comment]
In real, result of `tox_conference_peer_get_name_size` is undefined on error and we should check the `error` value
