### ISSUE TITLE
Where are the Ubuntu installation deb files or a new repository?

### ISSUE THREAD

**Issue by phd21** [qTox/qTox#4816]
Dear qTox,

I love this qTox software, but it is becoming difficult to recommend when you cannot find easy to install options for Ubuntu users.

Where are the Ubuntu installation deb files (64-bit and 32-bit)  or a new Ubuntu type repository???? 

The "openSUSE" antonbatenev:tox / qtox webpage had wonderful options, what happened to it?

Can't you post the current Ubuntu deb files for 16.04 and 14.04 on this GitHub site or create a PPA on launchpad ?? 

You could even use a free cloud storage provider (pCloud or Mega.nz) temporarily if need be to upload current builds, and then post shared links for people to use under the Linux column of this GitHub, then contact webupd8 and other websites for posting the new information.

Best regards to all of you at qtox,
Phil
phd21

**Comment by nurupo** [comment]
https://qtox.github.io/blog/2017/02/15/Maintainer-Wanted.html

**Comment by phd21** [comment]
Hi nurupo and qTox people,

Per my post, until you have a working repository back up and running, could you please provide links to the most recent stable working Ubuntu 16.04 and 14.04 deb files (64-bit and 32-bit) files for people to download, preferably on your Github qtox download page under the Linux column where the other download options are?

If need be, If you email me the Ubuntu installation files, I'll put them on one of my own cloud storage providers and give you the shared links to them. Although you can easily create a free "qTox" cloud account on "pCloud" or "Mega.nz" and do the same thing. This at least would be a good working short term option until you have a repository up and running again.

Thank you.

Best regards to all of you at qTox and yours,
Phil
phd21mint@gmail.com

**Comment by nurupo** [comment]
Have you read the blog post? There is no one who would create qTox packages (aka the "deb files"). You can't upload packages if there are none.

**Comment by phd21** [comment]
Hi nurupo,

Thank you for responding ...

Indeed I have read the post, and I have been using qTox for years now and recommending it for years to everyone in the Linux Mint forums and elsewhere. That repo is not fully functional or stable yet - their words, not mine. I did not see options for Ubuntu 14.04, I tried downloading the "alpha" files and they would not install on my current Linux Mint 18.2 (ubuntu 16.04) system, error conflict with currently install qTox....

I  know that the OpenSuse repositories had these stable "Ubuntu" deb files for at least a year, are you saying that nobody has a copy of these files before that repository shutdown? Was nobody at qTox notified that the "opensuse" repo was being shutdown and made backups of all current versions of qTox installation files and source code before that shutdown happened???

Best regards
Phil
phd21

**Comment by nurupo** [comment]
>are you saying that nobody has a copy of these files before that repository shutdown?

That I don't know. But what it matters if someone has made a copy or not? Even if someone had a copy of it, there still wouldn't be any packages as there is no one who would make them.

**Comment by phd21** [comment]
Obviously I mean backed up the already compiled installation binaries for the various Ubuntu versions that were already easily available on the "openSUSE" antonbatenev:tox / qtox webpage under "grab binaries" option at the bottom, there were only 2 files (32-bit or 64-bit) per Ubuntu version?

**Comment by phd21** [comment]
Hi qTox, nurupo, Diadlo , etc...

I was thinking that maybe if you contacted "antonbatenev", or "OpenSUSE", that they might have backups of the repository, including the various Ubuntu binary installation files (deb files), before it was shutdown.

Just in case though, I searched my installed systems, and my backups to see what qTox Ubuntu installation files (binaries) that I had, and here is what I have. Please feel free to use these.
Shared links to qTox Ubuntu binaries (deb) files

These qTox Ubuntu installation files (binaries) below came directly from the OpenSUSE repos, they might be a little older, but they should work well until the new qTox repository is up and running properly.

Ubuntu 14.04 (08-05-2016)
64-bit
https://mega.nz/#!O1hHFARB!I2FRte4_KmsVk5KM3jTq_w_laB_-B9n0SBX57kBOPiE

32-bit
https://mega.nz/#!3oRwRIjb!OBY7nEsGfvUg8QXe7itxeeS7mx9arDNQbA8DP4_GZCk


Ubuntu 16.04 (08-05-2016)

64-bit
https://mega.nz/#!f9Rkma7D!gXWUmjfrLomoLa3f_n2pmcfZ-G2qpQvW7w3RpY2zcHg

32-bit
https://mega.nz/#!ms5TyYaZ!ol46DenvQkHs1ijfZlhuJISwMjbL-Veim_z0Wyhod0M


These qTox binaries came directly from my Linux Mint KDE systems, are 64-bit only, but are newer

08-29-2017

Ubuntu 16.04 - Linux Mint 18.2 - 64-bit only
https://mega.nz/#!mgYVhR6S!Po4vv_hLhApJRqDyeOCeFpjy3eOkvZ-V9dLySATJL3I

Ubuntu 14.04 - Linux Mint 17.3 - 64-bit only
https://mega.nz/#!vpZzAaZJ!IZhFQX4PAEPygy2Ux1pDpKeLhi2y2rT5mv1HwkGfFhk


Hope this helps ...

**Comment by nurupo** [comment]
There is little sense in linking to a 1 year old qTox version.

Also, I suggest everyone agains downloading binaries from untrusted sources, like your mega.nz links. Who knows if you have added some malware into those builds.

**Comment by phd21** [comment]
Hi nurupo, and anyone else,

First, I am an ex-software developer myself with decades of professional computer experience in supporting various software and hardware for businesses and people all over the USA (nationwide). I have been helping people in the Linux Mint forums since January 2014 with over 4900 posts and replies. I really do love the qTox software because it is light on system resources, secure,  and it just works super well.  I use it myself. I have been actively promoting this qTox software for years on the Linux Mint forum. Feel free to verify this, I am user "phd21" on the Linux Mint forums.

Just like anyone can, and probably should, whenever you download anything, run it through a virus and malware scanner to make sure it is safe to use. I ran these files through the "VirusTotal" website which uses over 50 anti-virus and anti-malware scanners, and "Linux Malware Detect" (LMD) and ClamAV scanners that I have installed on my systems, and there were no viruses or malware detected.

For those of us that already have qTox installed, this is not really a big issue, except for the repository errors that we now get when updating which is easy to resolve.

So, what do you suggest to people using Ubuntu 14.04 and Linux Mint 17.x or Ubuntu 16.04 and Linux Mint 18.x on how to install this wonderful qTox application, considering that most users are inexperienced and will not be able to compile it from source code?

I am just suggesting an alternative for Linux users to be able to install qTox now until a new repository is up and running well. Even though some of the installation files are from over a year ago, they should install and work very well. Two of the 64-bit installation files and their links are fairly new from 08-2017, and this is also why I was asking if anyone else had copies of the newer easy to install Ubuntu installation deb files ...

Best regards,
Phil
Linux Mint user: phd21

**Comment by sudden6** [comment]
Edited the title to make it a bit less aggressive.

@phd21 The issue is not in distributing the files, but in creating working *.deb files for the distributions. If you want to accelerate the work on packages feel free to fork https://github.com/anthonybilinski/tox.pkg and contribute changes. Maybe you can even get one of the Linux Mint maintainers to create an official package for qTox.

**Comment by tox-user** [comment]
Can't you download builds from here https://github.com/qTox/qTox/releases ? It won't be as convenient as .deb, but is probably better than compiling from source.

**Comment by nurupo** [comment]
@phd21 I'm not trying to be rude, there is really no way for us to check if those packages have been modified. Also, malware scanners generally scan for signatures of known malware, it's very unlikely that they would find a backdoor you could have put into those packages. You should know this if you really have decades of experience in software development.

@tox-user where do you see Linux builds on the Releases page? There are no Linux build in there, only source code and macOS builds.

**Comment by phd21** [comment]
@tox-user - I do not see any Linux binary installers, like "deb" files either? If you do, where are they?

@nurupo - I have not altered the qTox installation files that I linked in any way shape or form. If there exists any modifications like a "backdoor" programming routine, then it was already there when I got the files. Obviously if the qTox developers created checksum and signature verification files for the installation files, then we could use that to verify the files. Of course the developers who have backup copies of their source code which created these binaries on those dates, they can do file and file content comparisons to check for any differences. The one binary deb file for Ubuntu 14.04 (Linux Mint 17.x) from 08-2017, I could not find that deb file in my Linux Mint KDE 17.3 system, so I used the repackaging command "sudo dpkg-repack qtox" to re-create that, but the others were literally the exact downloads from the "openSUSE" antonbatenev  repository. And, your comments could apply to any software from anyone including developers.

**Comment by tox-user** [comment]
@phd21 there aren't any files for GNU/Linux, I was wrong. Posting packages of old qTox versions does not solve the problem though. We need to have packages for every new version. We need someone who will make them.
@nurupo sorry, my bad, I shouldn't have assumed that without checking. So why are there builds for macOS, but not for GNU/Linux nor Windows?

**Comment by phd21** [comment]
Hi sudden6,

Thank you for your quick responses.

Is "anthonybilinski/tox.pkg" on GitHub going to be the new qTox maintainer? If so, thanks to him and all of you involved in this project. Should all new questions and comments be posted there, instead of here?

What I find confusing is that for awhile now "antonbatenev" through the "openSUSE" system has been providing numerous and various excellent easy installation options for qTox, including deb binary installation files for the various Ubuntu versions in both 64-bit and 32-bit, including Ubuntu 14.04. Does he have backups of those files that you can get before the "openSUSE" site went down? Can't those processes which created those installation files still be done in Github or Launchpad like it was done through "OpenSUSE" with some modifications of course?

I do not see instructions for compiling qTox for Ubuntu 14.04 (Linux Mint 17.x) even those these still have LTS until 2019.  Just for the sake of it, I have been following the instructions to compile qTox in my Linux Mint KDE 17.3 (64-bit) system from the current GitHub source code, and it seemed to go well until the end and it fails with 
"The following packages have unmet dependencies:
 libvpx-dev : Depends: libvpx1 (= 1.3.0-2) but 1.3.0-3~trusty is to be installed"

I am pretty sure I will be able to compile current qtox source code in my Linux Mint KDE 18.2 system based on Ubuntu 16.04, and I will let you know how that goes.

I will also contact the Linux Mint team and see if there is anyone interested in providing "official Linux Mint packages". 

I am very happy to see that this "qTox" project is going to be maintained and updated because it is excellent Tox software.

Best regards to everyone and Happy Holiday Season to everyone ...

**Comment by nurupo** [comment]
>Obviously if the qTox developers created checksum and signature verification files for the installation files, then we could use that to verify the files.

@phd21 The `.deb` files are signed and hashed, that's how deb package repositories work, you had to add the packager's signing key into your keychain before you could download packages from the OBS, but since those signatures and hashes are part of a deb repository, they disappeared together with the repository. You might still have them on your systems though, somewhere in apt files, probably in `/var/lib/apt/lists/`.

>So why are there builds for macOS, but not for GNU/Linux nor Windows?

@tox-user you are asking the wrong person, you should ask qTox developers about instead, I'm more of a side-contributor of qTox.

**Comment by sudden6** [comment]
@phd21 

> Is "anthonybilinski/tox.pkg" on GitHub going to be the new qTox maintainer?

The plan is to integrate his work into the qTox GH organisation when it's done. Unfortunately he and I lack freetime at the moment to do it.

> Should all new questions and comments be posted there, instead of here?

I think they get more visibility here. @anthonybilinski what do you think?

> I will also contact the Linux Mint team and see if there is anyone interested in providing "official Linux Mint packages".

That would be very helpful, because nobody of us really has packaging experience, so everything takes much longer without having something to see how it's done right.

**Comment by phd21** [comment]
Hi sudden6, and all the qTox people,

Okay, I will let you know what the Linux Mint Team say, or they might contact you directly.

In the meantime, I booted into my Linux Mint KDE 18.2 system based on Ubuntu 16.04 and followed the instructions for compiling the current qTox and it worked well. So far, I like the new changes I have seen. 

Now, I am wondering how to create an easy to install Linux deb binary file from it and what files would be required from the "qTox" folder that I used for compiling qTox which I am guessing would have to include the tox core I compiled as well. Then, for creating Menu Items during the deb installation as well. 

FYI: I also really like the "AppImage" packaging approach because all dependencies are packaged with it, so it works on most Linux platforms as long as "fuse" is installed which it usually is by default. Another positive aspect of using AppImages is that you can usually use them on older systems, for example I have been able to run applications designed, compiled, and packaged for Ubuntu 16.04 in my Linux Mint 17.3 system based on Ubuntu 14.04 using AppImages.

Because I compiled this on my 64-bit computer does that mean this will only work on 64-bit computers, or will this work on both 64-bit and 32-bit computers? Are there compiling options for creating 64-bit and 32-bit binaries on a 64-bit computer, or during the packaging process?  I do not have Linux software packaging experience for multiple operating systems and platforms, or for just multiple Linux platforms. 

Out of curiosity, the new version shows 1.12 versus my previous one of 1.6 which appears to be newer from a mathematical point of view? Why not use a date and time stamp for versions rather than whatever  sequence it is using, similar to what the binary installation files seem to do?

I was looking at these links:

Packaging New Software
http://packaging.ubuntu.com/html/packaging-new-software.html

Easy way to create a Debian package and local package repository, 22 March 2013
https://linuxconfig.org/easy-way-to-create-a-debian-package-and-local-package-repository

Simple Deb Package Creation -  January 25, 2016
http://www.hackgnar.com/2016/01/simple-deb-package-creation.html

Creating AppImages
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages

Creating Linux Apps That Run Anywhere with AppImage · JULY 28, 2017
https://www.booleanworld.com/creating-linux-apps-run-anywhere-appimage/


Best regards,
Phil
Tox ID: phd21
Linux Mint forum user: "phd21"

**Comment by tox-user** [comment]
@sudden6 why aren't there qTox builds for more operating systems in https://github.com/qTox/qTox/releases (newest only has macOS) and on https://tox.chat/download.html (Windows and macOS). Why aren't there GNU/Linux builds and why aren't builds for all OSes available in both places? Another weird thing is that if you look here there used to be builds for different OSes: https://github.com/qTox/qTox/releases?after=v1.7.1

**Comment by sudden6** [comment]
@phd21 AppImage and Flatpak were brought up, but there was nobody willing to do them or maintain them. Also I have yet to see some apps distributed that way and updating is also unclear to me.

The linked git tox.pkg repo already contains some basic files to build a .deb, maybe it's easier for you to start from there for you.

@tox-user all the supported ways to get install files are listed in our README.md, this contains binaries for Windows and macOS. For Linux the way to distribute software is traditionally via a repository and that's what this thread is about :)

**Comment by phd21** [comment]
Hi sudden6,

There are a lot of applications packaged as AppImages now, as for how they are maintained and updated, I do not know yet. Kdenlive, OpenShot, Avidemux, Krita, DigiKam, MuseScore, Wire Messenger, etc... see bottom of page in link below

"Many upstream projects like Krita, Subsurface, MuseScore, KDevelop, and digiKam have started to provide AppImages directly on their download pages. More AppImages for other applications like Atom, Arduino, Blender, Chromium, Firefox, LibreOffice, and QCAD can be downloaded here (64-bit)."

https://appimage.org/

...

**Comment by phd21** [comment]
Hi sudden6,

I heard back from one of the people on the Linux Mint team, and here is their reply...  They recommend using the "flatpak" packaging option. The only issue I have with using "flatpak" is that it does not support Ubuntu 14.04 (which Linux Mint 17.x is based upon) and is still supported through 2019 (LTS).

"The best solution is for them to make a Flatpak package and put that on the Flathub website. Linux Mint 18.3 comes pre-configured with Flathub as a package repository so users can install Flatpak packages through Software Manager just like they can with other packages.

By making a Flatpak package the developers will have to do the work only once as a Flatpak package is usable on all Linux distros that support Flatpak.

See a list of other programs available through Flathub here: https://flathub.org/apps.html

There is information on the Flatpak website for developers to learn how to make a Flatpak package: http://flatpak.org/hello-world.html
"
Hope this helps ...

**Comment by phd21** [comment]
Hi sudden6,

While doing more research on packaging options for software this, I came across this link. I am wondering if this is what the previous repository was using? Can even create and maintain AppImage files automatically.

Does the qTox source code support Ubuntu 14.04 anymore, or could it with minor modifications? As I stated before, I could not compile it in that.

OBS is free for anyone ...
http://openbuildservice.org/

Using Open Build Service to generate AppImages
Short link to this page: https://git.io/obs-ai 
https://github.com/AppImage/AppImageKit/wiki/Using-Open-Build-Service

Let me (us) know what you think...

**Comment by sudden6** [comment]
@phd21 yes, that's what the previous repo was using and we try to use it again.

Thanks for the link to generate AppImages, I didn't know this is possible with OBS. Seems there's also support for GH hooks on pushes, so we could even provide real nightly packages.

**Comment by phd21** [comment]
Hi sudden6,

You are welcome.

I was pleased to see that OBS supported GitHub and AppImages as well. And, you could support stable and nightly releases with binaries like deb files too (I Think) for various Ubuntu / Debian systems along with AppImages.

**Comment by jontis** [comment]
Great to see this one addressed. Having a working easy ubuntu / mint repo is key to reaching a large user base, which is exactly what we want :-)

**Comment by sudden6** [comment]
@phd21 Some `qtox` packages are ready on https://build.opensuse.org/project/show/home:qTox if you want to test. Officially they are still unsupported until some testing polishing.

**Comment by jontis** [comment]
That worked great :-) I pulled the Ubuntu 16.04 .debs and installed into Mint 18.1

**Comment by phd21** [comment]
Hi sudden6,

Ok, nicely done!

I also installed the 64-bit version from that link using the "xUbuntu 16.04" clicked link to goto download repository at top, clicked the amd64 folder, select the "qtox_201711271502~v1.13.0_amd64.deb" file, and it installed and shows a nightly version in the "about" section instead of an actual version number now.  I have an even older computer than I am using now that is 32-bit with Linux Mint 18.x (Ubuntu 16.04) that I am going to try installing the 32-bit version on, and will let you know how that goes.

Questions: 
1.) Does this "qtox_201711271502~v1.13.0_amd64.deb" include all the necessary dependencies like the toxcore? I noticed other "deb" files in this folder. What is the "alpha" version"

2.) Do you remember the previous repository? They had a really nice layout for end users to select various Linux distributions, like Ubuntu, then it listed the various versions and repository installation instructions with "grab binary" files, like "deb" files at the bottom.  Of course that is not a big issue right now, you can provide a link to the files on the qTox download page.

3.) What about the "AppImage" file(s)? I did not see that anywhere?

Thank you...

Best regards,
Phil
phd21
qTox ID
D3799F7F46AD814A37D423641E140C48F07FC439754CDB53F85C87256C51DC63B86C4E982EEB

**Comment by sudden6** [comment]
1) no, the toxcore dependency is in another package also in this repository

2) This selection interface should also work for our repository, just a matter of finding the right link.

3) not done yet

**Comment by phd21** [comment]
Hi sudden6,

1. I remember seeing options somewhere for telling OBS to include other dependencies during the build process. Are there options (perhaps in some script or configuration file) that when clicking the main qtox deb file, it will automatically install the toxcore (deb file) package,  (& any other necessary packages), associated with this version of qTox? Otherwise, don't you have to tell users to download the toxcore deb file and install that first, before installing the qtox deb file? I already had the new toxcore installed because I compiled and installed qTox v1.12 from GitHub source code before I downloaded and installed this new v1.13 qTox deb file.

2. I agree, just have to find the right link...

3. I am pretty sure that an AppImage created for Ubuntu 16.04 will work on Ubuntu 14.04, so I am anxious to find out if a qTox AppImage will also work. I already have a few other AppImage applications designed for Ubuntu 16.04 that work perfectly on Ubuntu 14.04. Otherwise you can still provide links for Linux Ubuntu 14.04 (Linux Mint 17.x, etc...) users to download and use the qTox version 1.6 which works well too.

Regards ...

**Comment by phd21** [comment]
Hi sudden6,

I finally had a chance to try installing the new nightly qTox v1.13 deb file in my 32-bit Linux Mint KDE 18.x system based on Ubuntu 16.04 and it worked.  I did not install the toxcore separately either.

**Comment by phd21** [comment]
Hi sudden6, anthonybilinski, and anyone else at qTox,

I hope you all had a wonderful and Merry Christmas, Happy Holidays, etc...

Happy New Years to all of you and yours !!!

While helping others on the Linux Mint forums, I came across a very interesting project called "linuxdeployqt" which helps to easily create AppImage files for Linux software. Although you can use the OBS system, this may prove to be an easier and quicker method to creating and maintaining AppImages, and the developer seems nice and willing to help other developers. 

probonopd/linuxdeployqt
https://github.com/probonopd/linuxdeployqt

Hope this helps ...

Best regards to you and yours,
Phil (phd21)
phd21mint@gmail.com

**Comment by Jeeppler** [comment]
Hello,

is there any reason why qTox cannot be installed via the general `https://pkg.tox.chat/debian` package repository? Is just the maintainer missing or is there any technical reason for that?

**Comment by sudden6** [comment]
@Jeeppler no technical reason, just no maintainer.

**Comment by Jeeppler** [comment]
@sudden6 thank you for the answer.

**Comment by bentolor** [comment]
#4174

**Comment by Talkless** [comment]
Looks like we will have qtox in Debian Buster (an so some next Ubuntu release). It is currently available in Sid repository:

```
$ apt policy qtox
qtox:
  Installed: (none)
  Candidate: 1.16.3-1
  Version table:
     1.16.3-1 500
        500 http://debian.mirror.vu.lt/debian unstable/main amd64 Packages
```

**Comment by sudden6** [comment]
@Talkless great news!

**Comment by nurupo** [comment]
@Talkless It does look very promising but don't get your hopes too high until it actually happens, as a package being in Sid/Testing doesn't necessarily mean that it will be in the next Stable release, package maintainers still have the right to pull the packages out for any reason, e.g. if they decide the package is not ready for Stable.

**Comment by Talkless** [comment]
> as a package being in Sid/Testing doesn't necessarily mean that it will be in the next Stable release

True, but it's just a step forward. Let's hope for the best.

**Comment by anthonybilinski** [comment]
qTox is now in Debian and Ubuntu repos from their package maintainers, plus we have AppImage and Flatpak releases. Closing since we won't be providing our own packages going forward.
