### ISSUE TITLE
Video not working

### ISSUE THREAD

**Issue by Nene-efo** [qTox/qTox#4825]
My organization downloaded this application on the 20th of November but the video function is not working. When you make a video call, it switches the camera but shows no image.
OS: Windows 10
qTox version: v1.12.1
Commit hash: d65c30b879ee2f00c16816aa332567fd627c0b2b
toxcore: 0.1.10
Qt: 5.6.3
Hardware: 
Hp 15

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. 
2. 
3. …

##### Additional Info
(links, images, etc go here)

----

More information on how to write good bug reports in the wiki: https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by Diadlo** [comment]
Can you provide more information? Start with qTox log.
Maybe duplicate of #4764

**Comment by Diadlo** [comment]
Needed info not provided for over a month, thus closing.
