### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by stqism** [qTox/qTox#483]
Please use libnotify or something (dbus if you're edgy) to do desktop notifcations, here's a tutorial http://ubuntuforums.org/showthread.php?t=2179045

**Comment by agilob** [comment]
before this, I need to rewrite hiding to tray.

**Comment by tux3** [comment]
Of course Qt doesn't support that, so two solutions afaik:
- If we want to use platform specific libraries then on mac Growl is apparently the popular solution, on linux libnotify and on windows there's no consensus as far as I can tell.
- Or we could make our own notifications by showing a custom borderless always-on-top widget. The advantage is no extra dependencies and a consistent look/functionality on all platforms.

**Comment by agilob** [comment]
I thought about:
- [OSD](https://wiki.ubuntu.com/NotifyOSD)
- [native from Qt](http://qt-project.org/doc/qt-4.8/images/systemtray-example.png)

**Comment by dubslow** [comment]
Again, I believe we should copy what Quassel has. They support Windows, OS X, and various other unices, and their notification is definitely native on my platform (Cinammon 2.0).

https://github.com/quassel/quassel/search?utf8=%E2%9C%93&q=notification

```
bill@Gravemind⌚0847 ~/quassel/src/qtui ∰∂ ls *notificationbackend.h
dockmanagernotificationbackend.h  phononnotificationbackend.h
indicatornotificationbackend.h    snorenotificationbackend.h
knotificationbackend.h            systraynotificationbackend.h
osxnotificationbackend.h          taskbarnotificationbackend.h
```

**Comment by tux3** [comment]
What does Quasel's system depends on ? I like the result, but how is it implemented ?
It sorta looks like it requires some Obj-C

**Comment by dubslow** [comment]
As far as I know, it's Qt/C++ same as us.

**Comment by tux3** [comment]
@dubslow 
This <a href"https://github.com/quassel/quassel/blob/1b7bda6032edddeb3d6895916e1c968acef19979/src/qtui/osxnotificationbackend.mm">osxnotificationbackend.mm</a> in particular looks like obj-c

Anyway, if it works and it's C++, then that'd probably save a lot of work. 

@agilob 
The <a href="https://qt-project.org/doc/qt-5/qsystemtrayicon.html#showMessage">doc for Qt's QSystemTrayIcon</a> says that the messages may not appear at all. On OSX it only works if Growl is installed, and it's not clear if it'll work on all linux WMs. Have you tried it before maybe ?

**Comment by dubslow** [comment]
Very true, but that's the only one, and it's the mac one, so not terribly surprising...

**Comment by agilob** [comment]
I have used it in a few application (with QApplication::allert) and had no problems at all, but I use only Linux, and those applications were for Linux only. I have to move QSystemTrayIcon from main.cpp to widget.cpp to implement r-click menu for the icon and then I can write system Qt-style notifications.

If @dubslow wants to copy code from another project, maybe from Clementine?
![notiication](https://cloud.githubusercontent.com/assets/2544251/4704068/8b77840c-586f-11e4-80f9-d98db3521ebf.png)

**Comment by dubslow** [comment]
Sure, I'm most interested in anything that:
- Is Qt
- Is C++ (or very largely such)
- Has all three major OSs covered with native notifications

Quassel fits, and seems like Clementine does too

**Comment by krepa098** [comment]
libnotify seems to have a GTK dependency. The best solution is probably writing a small abstraction layer around the platform's native notification mechanism (like Quassel). Depending on what our needs are, we can get away with dbus on Linux and QSystemTrayIcon::showMessage on Windows and OSX (where it seems to use Growl).

**Comment by agilob** [comment]
What kind of notifications do you want? I'll make settings for selected:
1. friend is online
2. friend calling a/v
3. friend request
4. new message in a private chat
5. invited to group
6. new message in a group
7. friend changed status message to <message>
8. < your suggestion >

![notification](https://cloud.githubusercontent.com/assets/2544251/4717814/7fc60ee4-5919-11e4-9dc8-6b7f7ca23b8c.png)
![notification1](https://cloud.githubusercontent.com/assets/2544251/4717815/7fe4a746-5919-11e4-9e86-490097af1bc8.png)

I'll need someone to test it on Gnome, OS X and Windows, and with me on my pc (KDE).

**Comment by zetok** [comment]
@agilob I think those need tuning, as in:

> 1. friend is online

\- option to display notification for friends globally
- option to display notification for particular friend
Perhaps this one should be about changing status, without just limiting to friends coming online. If so, then perhaps there would be needed gradual change what kind of status changes should user be notified about

> \2. friend calling a/v

\- global option to display or not notifications
- per friend setting
Is is possible to accept/decline a/v call from notification? IIRC proprietary crap is capable of that..?

> \3. friend request

\- global option to display or not notifications
Is it possible to accept/decline FR from within notification? Or when clicked on notification, it would open qTox already on given FR?

> \4. new message in a private chat

\- global option to display or not notification
- per "friend" setting
Is it possible to directly open chat window with given friend when clicking on notification?

> \5. invited to group

\- global option to display or not notification
Is it possible to accept or decline groupchat invitation from within notification? (no, current auto-accept invite in qTox isn't a desirable behaviour, if something, it should be an option)

> \6. new message in a group

\- whether to display notification of every message in group chat
- whether to display notification on highlights

---

\8. file transfer

\- global option whether to display
- per friend option whether to display
Is it possible to accept/decline file transfer from within notification?

---

About "per friend" options, I think that it should be located in pop-up menu when r-clicking on contact.

```
_________________
| Muh option 1   |_________________________________________
| Notifications >||Display file transfer notifications    ✔|
|________________||Display groupchat invite notifications ✗|
                  |________________________________________|
```

**Comment by agilob** [comment]
Wohha that's a lot of options, I'll need another tab for this, I think.
Yes, all of them are possible, as I can implement 'interaction level' between Widget.cpp and Notification class.

All options 'per friend', do you want it to be saved in a file or 'per session' (option reset after restart)?

**Comment by zetok** [comment]
I think that saving in a file would be preferable, since users might not want to recreate their notification settings for hundreds of friends every application restart..

**Comment by agilob** [comment]
@tux3  where's 7.?

![notification](https://cloud.githubusercontent.com/assets/2544251/4723310/c6b371ac-5946-11e4-8e5f-0fea85f4c30b.png)

**Comment by zetok** [comment]
> > 1. friend is online
> 
> Perhaps this one should be about changing status, without just limiting to friends coming online. If so, then perhaps there would be needed gradual change what kind of status changes should user be notified about

Notify status changes:

```
✔ Online
✔ Away
✗ Busy
```

---

> \7. friend changed status message to 

\- global option whether to display notification
- per friend option

Would be nice to know what was previous status message, but I guess that it would require implementing tracking of status messages, so at least for now it looks like something that can wait (if it is a desirable behaviour).

**Comment by tux3** [comment]
@agilob 

> @tux3 where's 7.?

What ? Did you mean to @ mention someone else ?

**Comment by agilob** [comment]
No, after 6. you added 8. number 7 is missing.

**Comment by tux3** [comment]
I did not, @zetok did though.

Either I'm completely missing what you're trying to say,  or you're seeing my name on posts I didn't write and something very weird is going on. Here's what I'm seeing : https://i.imgur.com/SsS7T53.jpg and https://i.imgur.com/zYpYLGT.jpg, there are no other lists with 6 and 8 on this thread.

**Comment by agilob** [comment]
my bad ;D
I though you wrote the post with the list above ;D

![notification2](https://cloud.githubusercontent.com/assets/2544251/4724208/a080a54c-594e-11e4-9284-075ad54d1fc8.png)

**Comment by tux3** [comment]
Ok, you had me worried for a moment :)

**Comment by agilob** [comment]
I worried myself now :<

**Comment by Xylemon** [comment]
What is the status on this? Desktop Notifications would be incredibly useful.

**Comment by agilob** [comment]
I''l try to come back to this feature asap.

**Comment by jurf** [comment]
+1 for this. I use Gnome and qTox since Venom is deprecated and it's incredibly annoying to have all messages going through the gnome notifications where I can respond to the without changing the window except for tox.

**Comment by urras** [comment]
:+1: I seriously need this

**Comment by urras** [comment]
Any updates?

**Comment by baskervald** [comment]
Is there a way that you could have libnotify be an option, possibly? I'm aware it depends on GTK and I'm not exactly sure of the intricacies of using it in a Qt project, but every other notificatiton on my system uses libnotify and things can get a bit cluttered with a million different types of notifications for each program.

**Comment by tux3** [comment]
Ideally we would have native notifications on every platforms. Libnotify could be a solution, but if there's already a Qt-ish library that works natively on all platforms, I'd rather we went with that.

I'd like to depend on a portable library that hides the platform specific madness, instead of a zillions libraries if possible.

I'm not actively working on this right now, mostly due to lack of time, but it's definitely planned.

**Comment by baskervald** [comment]
Maybe add in an option to make it run a command (with placeholders) when
you get a message? That would at least allow people an option for now (for
example, using notify-send, like I currently do with Skype) and it would be
fairly quick and easy to implement for now.

**Comment by ProMcTagonist** [comment]
qTox running custom commands on events would be great. But I would prefer if this effort was spent directly on cross-platform/toolkit/DE notifications when the time is available to and commands-on-events was added much later.

**Comment by chrismcfee** [comment]
I would be extremely interested in growl notifications. The current notification system on OSX is pretty sub-par.

**Comment by baskervald** [comment]
@ProMcTagonist well, the running a command option was intended to be a stop-gap, so people could use their own notification commands without having to implement something fancy and cross-platform for now.

**Comment by SkyzohKey** [comment]
You can use [QxtToolTip](http://libqxt.bitbucket.org/doc/0.6/qxttooltip.html) class in [Qxt](http://dev.libqxt.org/libqxt/wiki/Home). It enables you to show any arbitrary widget as a tooltip. So i think you can create your custom widget and show it using `QxtToolTip` in the proper position. You can use this static function :

```
void QxtToolTip::show ( const QPoint & pos, QWidget * tooltip, QWidget * parent = 0, const QRect & rect = QRect() )   [static]
```

It can be like:

```
#include <QxtToolTip>

MyCustomWidget widget;
QPoint myPosition(x,y);
QxtToolTip::show ( &myPosition, &widget, parent);
```

**Comment by suhr** [comment]
> LIBQXT IS NO LONGER MAINTAINED

**Comment by SkyzohKey** [comment]
I found this https://github.com/Snorenotify/Snorenotify/

**Comment by SkyzohKey** [comment]
Bump. Qxt is maybe no longer maintained but it works right. Just take the `Qxt::ToolTip` class as an example to make your own native desktop notifications. It should be simple to do :)

**Comment by zetok** [comment]
Looks like #2082 is going to fix this.

**Comment by bhelm** [comment]
I hope so. Without desktop notifications and audio notifications, i almost never notice new messages as they arrive. The new message indication is very subtile at the moment.

**Comment by zetok** [comment]
> Without desktop notifications and audio notifications (…)

Well, there is audio notification - if it doesn't work though, then it's a bug, and an issue should be opened.

![new message notification](https://cloud.githubusercontent.com/assets/3148759/12641200/17fe7954-c5a6-11e5-9991-796215d18217.png)

**Comment by bhelm** [comment]
the audio is no problem on the tox site. My system does not have any audio output devices.
i have recompiled my tox with #2771 . now not only the desktop notifications are working, tox tray icon and task bar item started to flash, which was not the case in my previous git build.

**Comment by zetok** [comment]
Update: there's #2921 for those who would want to help.

**Comment by sudden6** [comment]
There are now desktop notifications on Linux.
