### ISSUE TITLE
v1.13.0 Release

### ISSUE THREAD

**Issue by quantumpacket** [qTox/qTox#4839]
On https://github.com/qTox/qTox/releases the v1.13.0 release has the incorrect filename versions as v1.12.0, which is ever more odd as the prior release was v1.12.1. Were the correct files uploaded?

Also my build script failed when GPG verifying the git clone for this release. Upon inspection I get the following:

```sh
$ git tag --verify v1.13.0
error: v1.13.0: cannot verify a non-tag object of type commit.
```

Yet when I do:

```sh
$ git tag --verify v1.12.1
object d65c30b879ee2f00c16816aa332567fd627c0b2b
type commit
tag v1.12.1
tagger sudden6 <sudden6@gmx.at> 1507758564 +0200

Fix build errors that prevented a build on Windows.
gpg: Signature made Wed 11 Oct 2017 05:49:27 PM EDT
gpg:                using RSA key 279509B499E032B9
gpg: Good signature from "sudden6 <sudden6@gmx.at>" [unknown]
...
```

**Comment by tox-user** [comment]
~~File names for source code and the code itself are correct versions. I don't know about other files.~~

**Comment by tox-user** [comment]
The names are correct. Files labeled v1.12.0 are versions 1.12.0 and v1.13.0 are 1.13.0. Looks like some of the wrong files were uploaded.

**Comment by Diadlo** [comment]
@quantumpacket Both issues should be fixed now. Don't forget `git fetch upstream --tags`
