### ISSUE TITLE
High CPU load since 73dcbd2e60e98d305f4d1d36c6d2a1b4bcd9de13

### ISSUE THREAD

**Issue by ChristophHaag** [qTox/qTox#4843]
OS: Archlinux
Qt: 5.9.3
Hardware:  RX 480 with latest mesa git

Reproducible: Always

CPU load is high in both qTox and X since commit 73dcbd2e60e98d305f4d1d36c6d2a1b4bcd9de13 as long as the GUI is visible.

MaskablePixmapWidget::paintEvent() is called a lot and it looks like QLabel::setPixmap() is an expensive function to call https://github.com/qTox/qTox/commit/73dcbd2e60e98d305f4d1d36c6d2a1b4bcd9de13#diff-ac3ece10b10583d2d275f26a143e91a4R97. Commenting that one line out makes CPU load very low again, but of course some icons are missing.

**Comment by sudden6** [comment]
can reproduce

IMO when we can fix that, we should push a v1.13.1
cc: @Diadlo

**Comment by Diadlo** [comment]
@sudden6 73dcbd2e60e98d305f4d1d36c6d2a1b4bcd9de13 was merged after release, so currently we shouldn't push the v1.13.1

**Comment by sudden6** [comment]
Sorry, my mistake, thought the release was affected.
