### ISSUE TITLE
GNU Emacs integration

### ISSUE THREAD

**Issue by averter** [qTox/qTox#4846]
I love qtox and everything it comes with. I will certainly stick with this project in the long run, and therefore, I would like to propose an integration with the wonderful text editor, GNU emacs. A qtox-mode essentially. Any ideas on how difficult this would be? Thanks.

**Comment by anthonybilinski** [comment]
Are you looking for basically a CLI tox client that can be run as an emacs mode? There's an existing CLI client [toxic](https://wiki.tox.chat/clients/toxic) that may be a better starting point rather than stripping away the heavy GUI of qTox.

**Comment by averter** [comment]
That's an interesting option. One could basically run a toxic process in a separate buffer.
 The other day I tried to install toxic though the official debian repo without luck. For some reason the package does not show up. I will give it another more in depth try and post here the results.

**Comment by sudden6** [comment]
Closing, not relevant to qTox.
