### ISSUE TITLE
didnt work send file button

### ISSUE THREAD

**Issue by koshakm5** [qTox/qTox#4854]
##### Brief Description

OS: Windows 7 x64
qTox version: v1.13.0
Commit hash:  ga3a361b

Reproducible: Always

**Comment by tox-user** [comment]
Happens on GNU/Linux too. I can still send the files by dragging and dropping them into the window though.

**Comment by PKEv** [comment]
I have this functionality
OS: Windows 7 x64
qTox version: v1.13.0

**Comment by koshakm5** [comment]
it broke in the nightly builds
released 13.0 works fine

**Comment by sudden6** [comment]
@koshakm5 can you pinpoint at which date it broke? Or even better do a git bisect?

**Comment by koshakm5** [comment]
@sudden6 v1.13.0-9-gbb26485 already broke, but dont know when exactly

**Comment by sudden6** [comment]
I guess https://github.com/qTox/qTox/commit/1eb0c4af263602c74d3f899123a18af15437d676#diff-0c0389e8efc13cb0ad556dca8cbff4b3R151 is the line with the error. It should be connected to `&ChatForm::onAttachClicked`

Can you test if the send attachment button sends a message if the text edit is not empty?

**Comment by koshakm5** [comment]
ok, if the text edit is not empty - this button sent text

**Comment by sudden6** [comment]
Thx, preparing a patch already :)

**Comment by koshakm5** [comment]
thanks
