### ISSUE TITLE
Loosing microphone input in video calls when moving qTox window

### ISSUE THREAD

**Issue by dirteat** [qTox/qTox#4857]
##### Brief Description

OS: Linux Mageia 6
qtox: version 1.13.0
toxcore:  0.1.10
Qt:  5.6.2
Hardware: desktop
…

Reproducible: Always

##### Steps to reproduce

1. Engage a video calls with a toxic friend
2. Everything works
3. Click on the window and move it.

##### Observed Behavior
Your friend does not hear you anymore although I am perfectly able to hear him.
The video stream is unaffected. We have to start again a new call and the microphone input is fine again (without restarting qtox).

##### Expected Behavior
uuu? I don't expect moving the qTox window to break the sound input ;)

**Comment by sudden6** [comment]
Can you post the log output when you move the window?

**Comment by eatdust** [comment]
Here we go, I have moved the windows, microphone gets killed and I used the Export Debug Log button just after. I have removed some parts, hours before the incriminated conversation. So the issue happened within these logs, certainly towards the end (but I cannot see anything)

[microphone.log](https://github.com/qTox/qTox/files/1565109/microphone.log)

**Comment by eatdust** [comment]
Just to say that this issue has disappeared with latest qtox-1.15.0 and toxcore-0.2.2.
Thanks to whoever fixed this!

**Comment by tox-user** [comment]
I'm glad that it's fixed! Closing.
