### ISSUE TITLE
[Feature Request] Message notifications

### ISSUE THREAD

**Issue by joeBwanKenobi** [qTox/qTox#4858]
##### Brief Description

OS: OS X, Windows 7
qTox version: v1.12.0.

##### Observed Behavior
When a new message is received a green outline stroke shows up around the status indicator of the user who has messaged you.  

##### Expected Behavior
Could it be adjusted so that this outline stroke, or ring used as a new message indicator could be a different color like yellow or red?  This has been an issue with folks that are less tech savvy in my company, as they don't differentiate well between the regular status indicator and new message indicator.  

----

**Comment by sudden6** [comment]
I agree, it's not very clear as a new message indicator.

A problem I see with the suggested approach is, that yellow and red are also used to indicate the online status already. Maybe we can find something better?

**Comment by koshakm5** [comment]
I think big(1.5x) orange circle with message counter will be nice.
or leave the indicator as it is now, but make outer ring flashing

**Comment by tox-user** [comment]
It might be better to leave the ring as it is and just highlight the contact with some color:

![qtox highlight friend on message yellow](https://user-images.githubusercontent.com/32248732/33951962-4dc7bfe8-e028-11e7-8adc-e5146157d811.png)

![qtox highlight friend on message blue](https://user-images.githubusercontent.com/32248732/33951964-4ef97c44-e028-11e7-957d-68b2db4e484b.png)

**Comment by tox-user** [comment]
![qtox new message indicator 1](https://user-images.githubusercontent.com/32248732/34888600-bde822a2-f7c2-11e7-8600-a104dc536f62.png)

![qtox new message indicator 2](https://user-images.githubusercontent.com/32248732/34888601-be5ab6aa-f7c2-11e7-9ebb-28a2a921861b.png)

![qtox new message indicator 3](https://user-images.githubusercontent.com/32248732/34888603-bed8f470-f7c2-11e7-888a-9c290571e26a.png)

**Comment by sudden6** [comment]
@tox-user Nice design, I especially like the second one.

Maybe we can differentiate online status by color and notification by form of the symbol?

EDIT: Can you open a PR where you add the svg for these symbols to the qTox repo?

**Comment by tox-user** [comment]
Done! Different symbols for different types of notifications would be a good idea.

**Comment by SkyzohKey** [comment]
Also see how the design is implemented in The Universal Tox Client on the screenshot -> https://tox-rebrand.herokuapp.com/download 😇 

I'd be proud to let you use the icons, making it license compatible with qTox

**Comment by tox-user** [comment]
Which icons do you mean?

**Comment by SkyzohKey** [comment]
Woops, icons doesn't appears on the screenshot. I meant these ones:

![Icons](https://i.imgur.com/du7MQF2.png)

The point is not to have another icon. The point is to change the font-weight of the contact items that have unread messages + adding a timestamp of the last message. This gives more informations to the user without having it to "learn" another icon.

**Comment by tox-user** [comment]
> The point is to change the font-weight of the contact items that have unread messages + adding a timestamp of the last message. This gives more informations to the user without having it to "learn" another icon.

The icons look very similar to the ones we currently use, but that's a great idea! Thanks for the suggestion!

**Comment by SkyzohKey** [comment]
Eventualy you can even add a little colored dot after the name line so that it catches user attention a bit more :)

**Comment by sudden6** [comment]
Closing since the icon now looks different when a message is received.
