### ISSUE TITLE
inactive autoaway time selection

### ISSUE THREAD

**Issue by koshakm5** [qTox/qTox#4860]
![capture](https://user-images.githubusercontent.com/34250813/33883462-f111c874-df4c-11e7-8d66-0ae0db49de44.PNG)
##### Brief Description

OS: Windows 7 x64
qTox version: v1.13.0
Commit hash:  8de8c14
toxcore:  0.1.10
Qt:  5.9.3

Reproducible: Always

**Comment by sudden6** [comment]
On Linux this is working as expected. ~I guess it's a missing dependency on the build server.~

EDIT: turned out to be a bug in the cmake script, PR with fix opened.
