### ISSUE TITLE
Why does qTox link to gtk20 and not to gtk30?

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4863]
If gtk20 is used for notifications on gtk2-based systems, why isn't then gtk30 used too? gtk3 is the next generation of gtk2, there must be gtk3-based systems too? Telegram client source, for example, links with both gtk20 and gtk30 for similar reasons.

**Comment by Diadlo** [comment]
Because it requires additional support

**Comment by yurivict** [comment]
As an additional idea, you might want to link with gtk (2 and 3) dynamically, so that it will not incur the runtime dependency when it isn't needed. Currently it causes installation of gtk20 even when it isn't otherwise needed.

**Comment by sudden6** [comment]
@yurivict If you can make the dynamic switching work, I'd happily accept a patch. In the mean time though I  don't see that as a very urgent problem, since gtk2 is still very widely used.

**Comment by anthonybilinski** [comment]
Linking to GTK 2 was removed in e85d3f522a4f38a5fb189dafa0b47b38f365dbf0, which is present in v1.17.0 forwards. It was replaced with using Qt for tray icons, so GTK 3 is not linked either. Closing.
