### ISSUE TITLE
Utilise gnome-keyring and kwallet to store password

### ISSUE THREAD

**Issue by physkets** [qTox/qTox#4864]
This in an enhancement/feature-request

It would be nice if qTox could use facilities provided by these Desktop Environs to store and unlock the profile, so that those who like to have all their accounts unlocked on login can have that.

**Comment by sudden6** [comment]
I guess this is basically the same as https://github.com/qTox/qTox/issues/4136 right?

**Comment by anthonybilinski** [comment]
Looks the same. Closing as duplicate.
