### ISSUE TITLE
Just installed but does not download latest software when updating.

### ISSUE THREAD

**Issue by samiam128** [qTox/qTox#4872]
##### Additional Info
(links, images, etc go here)

----

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by sudden6** [comment]
@samiam128 please fill out the issue template.

**Comment by sudden6** [comment]
No info provided, also updater is disabled.
