### ISSUE TITLE
OSX qTox after the first program start, no incoming Window / Button

### ISSUE THREAD

**Issue by fidi456** [qTox/qTox#4885]
##### Brief Description

OS: OSX 10.13.2
qTox version: Nightly
Commit hash:  build without git
toxcore:  0.1.11
Qt:  5.10.0

Reproducible: Always

##### Steps to reproduce

when qTox starts for the first time (Autostart), the call pickup and video will not work. The incoming call window is missing. In this case the Add Friends window is open or active
![bildschirmfoto 2018-01-03 um 10 23 12](https://user-images.githubusercontent.com/34652984/34515891-acc069b2-f074-11e7-9279-4e81c76eef53.jpg)
Second call without terminating the program, window incoming call comes only video has to be started manually, setting Audio Video
![1](https://user-images.githubusercontent.com/34652984/34515937-e87b8702-f074-11e7-8b1f-932b3d09b978.jpg)

Third call, everything works fine until the next reboot.
[qtox.txt](https://github.com/qTox/qTox/files/1600044/qtox.txt)

Next try
The call window comes when a friend in online status is selected (first autostart), but video must be turned on manually. After this process, qTox runs normally (Audio/Video)
![bildschirmfoto 2018-01-03 um 11 27 56](https://user-images.githubusercontent.com/34652984/34517296-c1985d4e-f07a-11e7-8a99-aaa6a7c0e4e1.jpg)

[qtox2.txt](https://github.com/qTox/qTox/files/1600046/qtox2.txt)

**Comment by sudden6** [comment]
Can you check if that's fixed by #4886 ?

**Comment by fidi456** [comment]
@sudden6 that's the similar mistake.
Have it tested on my Linux Mint 18 computer (qTox Commit Hash 
5648106b34fc7dc3ad4e169651a0cbbd0139170a, Toxcore 0.0.0 QT 5.5.1):
From restarted qTox on MAC call to my linux machine Mint 18, on Linux the call works with call window. Only on the Mac, I have to start the camera manually. After completing the call on the Linux computer and call back to the mac, must select the friend on the Mac, then also appear the call window on the Mac. Without selection, it does not work on the Mac

**Comment by fidi456** [comment]
@sudden6 Works with the fixed # 4886, the camera only has to be started manually at the first start

**Comment by sudden6** [comment]
> the camera only has to be started manually at the first start

Can you explain in more detail what "started manually" means? (I also speak German if it's easier for you to explain in that language)

**Comment by fidi456** [comment]
@sudden6 Deutsch ist mir lieber, das heisst wenn ich das Programm das erste mal starte und den Video Anruf annehme,  muss ich in qTox unter Einstellungen auf Audio/Video gehen das die Facetime Cam startet. Aber nur das erste mal, beim zweiten mal funktioniert es. Für mich wäre das kein Problem, der Anrufer sagt mir schon ob er mich sieht.

**Comment by sudden6** [comment]
> Deutsch ist mir lieber, das heisst wenn ich das Programm das erste mal starte und den Video Anruf annehme, muss ich in qTox unter Einstellungen auf Audio/Video gehen das die Facetime Cam startet. Aber nur das erste mal, beim zweiten mal funktioniert es. Für mich wäre das kein Problem, der Anrufer sagt mir schon ob er mich sieht.

Rough translation for non German speakers:
> When qTox is started, one needs to go to Settings -> Audio/Video to start the facetime camera, else the video will not work on the first answered call. On following calls the camera works instantly.

This seems still to be the same bug as in https://github.com/qTox/qTox/issues/4866, right?. Maybe #4880 fixes that, but else I'm afraid someone will have to debug that live on the Mac.

**Comment by fidi456** [comment]
@sudden6 #4886 war nur die Kamera Funktion #4880 hat auch nicht funktioniert. Was ich probiert habe, nach dem ersten Start die Einstellung Audio/Video aufgerufen und dann das Fenster geschlossen. Anruf kam und Video geht. Das heißt wenn beim Start als erstes die Videoeinstellungen aufgerufen werden funktioniert es. 
Ich probiere es weiter, soweit funktioniert es für mich.

**Comment by sudden6** [comment]
Ok, if it's working after opening the video settings once after starting qTox, it's probably a problem with saving/restoring the selected camera/videomode.

**Comment by sudden6** [comment]
Is this still an issue?

**Comment by fidi456** [comment]
No, the last release v.1.14.1 works on Mac OS High Sierra. For information on the official download page (tox.chat) is still the 1.13.0 version, has all the old problems.

**Comment by sudden6** [comment]
Ok, I'll close this then.

**Comment by anthonybilinski** [comment]
Created https://github.com/Tox/tox.chat/pull/198/files regarding tox.chat download version being out of date.

EDIT: it's been updated.
