### ISSUE TITLE
Echo when chat partner uses loudspeakers

### ISSUE THREAD

**Issue by hkarel** [qTox/qTox#4904]
I was faced with the problem of reverse echo. When my interlocutor uses loudspeakers all that I say in my microphone - I also hear in my headphones. And my voice sounds louder than the voice of the interlocutor, which greatly hinders the conversation and ultimately annoying. If the interlocutor changes the loudspeakers to the headphones, then the problem disappears.

OS: Kubuntu 14.04
qTox gitrev: ea6364ae020ead729adffad3073283d63fc98ba0 (and above, I use my own assembly)
toxcore:  0.1.11
Qt:  5.9.3

**Comment by sudden6** [comment]
Interlocutor = friend you're talking to?

He should enable echo cancelling in his qTox (Experimental audio backend).

**Comment by hkarel** [comment]
> Interlocutor = friend you're talking to?

yes.

> He should enable echo cancelling in his qTox (Experimental audio backend).

I did so, but a friend does not hear me at all, although I hear it well.

Is there anyone from Russian-speaking developers with whom I could check this functionality? Doing such tests with parents is not very easy.

**Comment by sudden6** [comment]
The one with the speakers has to setup echo cancelling, not the one with the headset.

cc @Diadlo

**Comment by Diadlo** [comment]
@hkarel Feel free to ask me in tox (Diadlo@toxme.io)

**Comment by Diadlo** [comment]
Experimental backend works really bad :(
If I enable it and restart qTox, I don't hear any sound. Friend hear me (but with noise)
Treshold works bad too. If I increase value a bit my voice starts disappear and friend can't hear most of my phrases.

**Comment by sudden6** [comment]
Just tested it yesterday too, came to the same result.

With the experimental audio backend there's no sound at all, no notifications and no test sound in the audio settings.

**Comment by hkarel** [comment]
I confirm the words @Diadlo, we checked the system together. Unfortunately I can not help here by the code, I'm not at all competent in the sound system.

**Comment by sudden6** [comment]
It's probably some stupid easy mistake, because it worked before. Maybe git bisect can find the problematic change.

**Comment by tox-user** [comment]
Could microphone voice activation have something to do with it?
