### ISSUE TITLE
Unable to send and friend request

### ISSUE THREAD

**Issue by AceVir** [qTox/qTox#4908]
Hi,

I tried to send a friend request to someone by putting in her ID on the TOX ID field, after hitting the 'Send request button', she was added on my contacts but when I tried to send her a message, (of course I have to click on her ID first on my contacts list and compose a message) it won't send the message because the last digits of her qtox ID was missing (it shows incorrect ID but I'm pretty sure that I put her correct ID when I tried to send her a request). So I tried deleting her ID on my contacts list and retried sending her a friend request but same thing happened, so it ended up as no request was sent to her. I also asked her to send me a request instead, but I'm not seeing or getting any request.

OS: Windows / OS X / Linux (include version and/or distro)  
qTox version: (version numbers in menu `Settings → About`)  
Commit hash:  
toxcore:  
Qt:  
Hardware:  
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. 
2. 
3. …

##### Additional Info
(links, images, etc go here)

----

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA%\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by tox-user** [comment]
Could you fill out the template? Your OS, qTox version etc.

**Comment by sudden6** [comment]
> the last digits of her qtox ID was missing

This is correct behavior, the contact list only shows the public key part of a ToxID.

Were both of you online at the time of sending the friend request? Did you get connected (Your status circle and hers both green)?

EDIT: Did the public key in the contact list turn into her username?

**Comment by sudden6** [comment]
@tox-user Since you seem to be very active here, do you want to become part of any of the qTox OS specific teams?

**Comment by tox-user** [comment]
@sudden6 Sure, why not! :)

**Comment by sudden6** [comment]
@tox-user which team do you want to join? Linux, windows, mac or all of them?

**Comment by tox-user** [comment]
@sudden6 I currently only run Linux, so I think that would be the best one for me.

**Comment by sudden6** [comment]
@tox-user invitation sent, would also be cool if you could join #qtox on freenode :)

@AceVir sorry for hijacking your issue, was not sure how to establish contact otherwise

**Comment by AceVir** [comment]
Hi qTox Team,

Everything seems to be working fine. Thanks a lot!
