### ISSUE TITLE
Focus on text box when opening qTox

### ISSUE THREAD

**Issue by stqism** [qTox/qTox#491]
When opening qTox from minimizing make it default to typing in the message box please, manually selecting the text box sucks

**Comment by tux3** [comment]
Right now when minimizing to the taskbar/tray icon the focus is kept. If you were focused before minimizing, it should stay focused after.

Do you want to just force focusing in (so you will loose anything you selected), or do you not have what I described above ?

**Comment by zetok** [comment]
There should be focus in input box when resuming from minimize, if no text was selected prior to minimizing.

**Comment by zetok** [comment]
Currently qTox switches focus to input field when user starts typing - thus closing issue. If that behaviour isn't the best / desired one, please open a new issue, describing how exactly behaviour isn't ideal and proposed way of solving it considering not breaking (too much?) current workflow in qTox.
