### ISSUE TITLE
Compile for Tails

### ISSUE THREAD

**Issue by AlexLarkin** [qTox/qTox#4910]
Hello. I compiled qTox using simple_make.sh and took qtox binary file. But, when I tried run it into another system, it showed me in console that several libraries missing. I tried run it in Tails. How can I compile qTox to run in any Linux systems without any dependencies. 

OS: Tails Linux / Linux Mint 18.3
qTox version: 1.13.0-26-gff2fc18

P.S. Sorry for my bad English

**Comment by tox-user** [comment]
Maybe you could create an appimage?

**Comment by sudden6** [comment]
No follow-up
