### ISSUE TITLE
"Save chat log" function should save log with dates

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4912]
Currently there are only timestamps, which is meaningless when the log covers more than one day.

**Comment by sudden6** [comment]
Agreed.

**Comment by isav83** [comment]
Is it issue fixed? I save chat log via "Export to file" and log saved with dates in format "[date] [time] [message]".

**Comment by anthonybilinski** [comment]
Behaviour was changed in ed514d71667d87c30acd1f41213d8ec8c6041b04 to include datestamp. Thanks for pointing it out.
