### ISSUE TITLE
Unable to connect or go online with a Proxy/VPN connection

### ISSUE THREAD

**Issue by AceVir** [qTox/qTox#4914]
##### Brief Description
Hello,

Just wondering if you could help me on this? I am unable to go online when internet connection I am using is proxy/VPN that was given by a developer. Is it really won't gonna work? or do I have to download different qTox for this to work with a VPN connection?

Thanks a lot. Help please.

OS: Windows / OS X / Linux (include version and/or distro)  
qTox version: (version numbers in menu `Settings → About`)  
Commit hash:  
toxcore:  
Qt:  
Hardware:  
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. 
2. 
3. …

##### Additional Info
(links, images, etc go here)

----

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA%\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by sudden6** [comment]
> by a developer

developer of qTox?

also please fill out the issue template.

**Comment by AceVir** [comment]
Nope, a internet developer. Anyway, don't worry about it. I'll just check
on it.

Thank you
