### ISSUE TITLE
Unable to close qtox on gnome

### ISSUE THREAD

**Issue by NicoHood** [qTox/qTox#4919]
##### Brief Description

OS: ArchLinux
qTox version: v1.13.0.
Commit hash:  531defd0aa66af1b128f7293bc08718ce2cc064f
toxcore version: 0.1.11
Qt:   5.10.0
Hardware:  i7 haswell 4xxx
gnome-shell 3.26.2+9+ga3736d3a3-1

Reproducible: Always 

##### Steps to reproduce

1. Open qtox
2. Close it
3. Open system monitor, qtox is still running

##### Observed Behavior
Qtox is still running, you cannot close it with gnome, as there is no tray menu anymore.

##### Expected Behavior
The application will close on DEs without tray. Pidgin does the same

**Comment by sudden6** [comment]
Can you post the last lines of the log when this happens?

EDIT: Did you check the settings and can confirm "Close to tray" is disabled?

**Comment by NicoHood** [comment]
Disabling close to tray worked for me. Thanks!
