### ISSUE TITLE
[Feature request] Data usage indicator

### ISSUE THREAD

**Issue by physkets** [qTox/qTox#4921]
A counter/indicator/graph displaying the data usage would be nice.

The possible stats could be:

 * cumulative consumption since (i) install, (ii) beginning of current session
 * rate/speed of usage, (i) current and (ii) average

There may be more interesting things...

**Comment by tox-user** [comment]
This could be interesting when improving data usage in Tox (to measure the improvement).

**Comment by vtronko** [comment]
You mean network bandwidth usage, right?

**Comment by physkets** [comment]
@innermous Well, yes, but bandwidth is just speed. I mean that and also cumulative usage.

**Comment by MishraShivendra** [comment]
Shouldn't this go to tox core? Not sure if any such API already there. Wouldn't this be inaccurate if we show statistics of data read/written from qtox?
Any input?
@sudden6

**Comment by anthonybilinski** [comment]
From qTox we could see message/voice/video data sizes, but we'd miss the protocol overhead on each packet, plus more importantly the constant DHT chatter which is pretty significant for overall data usage. Yes, we would need some toxcore API support to do this well.

**Comment by sudden6** [comment]
In my opinion this is not really a feature to integrate into qTox, there are better tools to follow per application data usage than we ever could build. What we also can't really measure, but maybe is important, is packet re-transmissions.

**Comment by tox-user** [comment]
It would be a useful feature for some people, but I agree that it doesn't make much sense to implement it in a messenger. It's better to use external programs that are made for this.

**Comment by sudden6** [comment]
Closing since the general agreement seems to be that it's out of scope.
