### ISSUE TITLE
Questions about tox account

### ISSUE THREAD

**Issue by sam1275** [qTox/qTox#4927]
##### Brief Description
OS: Windows 7
qTox version: 1.13.0
Reproducible: Always

##### Additional Info
There are 3 files per username under configuration folder:
.db .ini .tox
1. What are each file's purpose?
2. If I lose these files, but I still remember my ID and password, can I get my account back?
3. If I forget my password, can I recover it?
4. How can I use the same account on different machines (with same/different OS)?
5. Can I logon to the same account on different machines at the same time?

**Comment by Diadlo** [comment]
1.1. `db` file contains history.
1.2. `ini` file contains qTox settings.
1.3. `tox` file is your tox account.
2. `tox` is the main file if you loose it you finally lose your account. Other files not so important.
3. No, you can't restore your password.
4. Currently there is only one way to login on other device -- only copy your `tox` file. It can be used by other tox clients.
5. You can login in one account only from one machine at the same time.

In tox you haven't login, you have nickname that can be changed in every moment of time and key (stored in .tox file) which can be encrypted by password.

**Comment by sam1275** [comment]
Thank you very much.

You seemed also answered a question that I forgot to list:
6. Will my account be in danger if the files are leaked to others, but without my password?
So the answer is no, right?

Also there's more...
4 again. Is it possible to transfer the file to mobile OS like Android and iOS?
~~7. If I restore my old configure files, will my account info (name, contacts, etc.) be restored to the old state, or will it still in the latest state (already in the mesh network)?~~
8. Will the .tox file format change in the future? Will my old tox file become unusable in a future release and lose my account?

Answer to 7: I tested, those are stored only in .tox file, instead of the network.

**Comment by Diadlo** [comment]
6. No danger (if your password is not weak :P)
4 again. Yes, manualy with USB (or whatever do you use)
8. Yes, it can (and it will). Before changing file structure it should be well tested by developers. But in theory file can be broken, yes. Always do backup of important files :)
