### ISSUE TITLE
Error when installing from apt-get

### ISSUE THREAD

**Issue by dcharles525** [qTox/qTox#493]
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qtox : Depends: libopencv-core2.4 but it is not installable
        Depends: libopencv-highgui2.4 but it is not installable
        Depends: libqt5core5a but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by zetok** [comment]
@stqism

**Comment by zetok** [comment]
@dcharles525 mint 17, or is it elementary?

**Comment by dcharles525** [comment]
@zetok elementary

**Comment by stqism** [comment]
This issue is because we build against opencv2.4, for stable and stable distros we're going to provide packages for opencv2.4 as soon as we can.

**Comment by tux3** [comment]
Should be fixed.
