### ISSUE TITLE
Compiling from source. qTox release 1.13.0. make failing with ‘tox_pass_key_new’ was not declared in this scope

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#4930]
##### Brief Description

Compiling from source. qTox release 1.13.0

Linux librem 4.14.0-3-amd64 #1 SMP Debian 4.14.13-1 (2018-01-14) x86_64 GNU/Linux

Linux version 4.14.0-3-amd64 (debian-kernel@lists.debian.org) (gcc version 7.2.0 (Debian 7.2.0-19)) #1 SMP Debian 4.14.13-1 (2018-01-14)

DISTRIB_ID=PureOS
DISTRIB_RELEASE=8
DISTRIB_CODENAME=green
DISTRIB_DESCRIPTION="PureOS GNU/Linux 8"
PRETTY_NAME="PureOS GNU/Linux"
NAME="PureOS GNU/Linux"
ID=pureos
HOME_URL="https://pureos.net/"
SUPPORT_URL="https://puri.sm/faq/#faq-pureosandsoftware"
BUG_REPORT_URL="https://tracker.pureos.net/"

Reproducible: Always 

##### Steps to reproduce

Steps to install from source in INSTALL.md

make step to build qTox

##### Observed Behavior

make error output
```
[ 24%] Building CXX object CMakeFiles/qtox_static.dir/src/core/toxencrypt.cpp.o
/home/t3sserakt/Downloads/qTox-1.13.0/src/core/toxencrypt.cpp: In static member function ‘static std::unique_ptr<ToxEncrypt> ToxEncrypt::makeToxEncrypt(const QString&)’:
/home/t3sserakt/Downloads/qTox-1.13.0/src/core/toxencrypt.cpp:158:29: error: ‘tox_pass_key_new’ was not declared in this scope
     Tox_Pass_Key* passKey = tox_pass_key_new();
                             ^~~~~~~~~~~~~~~~
/home/t3sserakt/Downloads/qTox-1.13.0/src/core/toxencrypt.cpp:158:29: note: suggested alternative: ‘tox_pass_key_free’
     Tox_Pass_Key* passKey = tox_pass_key_new();
                             ^~~~~~~~~~~~~~~~
                             tox_pass_key_free
/home/t3sserakt/Downloads/qTox-1.13.0/src/core/toxencrypt.cpp:162:67: error: cannot convert ‘Tox_Pass_Key*’ to ‘const uint8_t* {aka const unsigned char*}’ for argument ‘1’ to ‘Tox_Pass_Key* tox_pass_key_derive(const uint8_t*, size_t, TOX_ERR_KEY_DERIVATION*)’
                         static_cast<size_t>(pass.length()), &error);
                                                                   ^
/home/t3sserakt/Downloads/qTox-1.13.0/src/core/toxencrypt.cpp: In static member function ‘static std::unique_ptr<ToxEncrypt> ToxEncrypt::makeToxEncrypt(const QString&, const QByteArray&)’:
/home/t3sserakt/Downloads/qTox-1.13.0/src/core/toxencrypt.cpp:198:29: error: ‘tox_pass_key_new’ was not declared in this scope
     Tox_Pass_Key* passKey = tox_pass_key_new();
                             ^~~~~~~~~~~~~~~~
/home/t3sserakt/Downloads/qTox-1.13.0/src/core/toxencrypt.cpp:198:29: note: suggested alternative: ‘tox_pass_key_free’
     Tox_Pass_Key* passKey = tox_pass_key_new();
                             ^~~~~~~~~~~~~~~~
                             tox_pass_key_free
/home/t3sserakt/Downloads/qTox-1.13.0/src/core/toxencrypt.cpp:202:86: error: cannot convert ‘Tox_Pass_Key*’ to ‘const uint8_t* {aka const unsigned char*}’ for argument ‘1’ to ‘Tox_Pass_Key* tox_pass_key_derive_with_salt(const uint8_t*, size_t, const uint8_t*, TOX_ERR_KEY_DERIVATION*)’
                                   static_cast<size_t>(pass.length()), salt, &keyError);
```

##### Expected Behavior

Build not failing

**Comment by sudden6** [comment]
you are probably compiling against a wrong toxcore version, could you tell us the qtox commit hash and the toxcore commit hash you're building from?

**Comment by ghost** [comment]
toxcore: cd8080f6d180677d03edff4878305c655c29bd69
qTox:     https://github.com/qTox/qTox/archive/v1.13.0.zip

**Comment by anthonybilinski** [comment]
@ffelgenh cd8080f6d180677d03edff4878305c655c29bd69 is past the toxcore 0.2.0 rev bump, which is not yet release. qTox is built against the last release of toxcore, which is v0.1.11.
Please run `git checkout v0.1.11` in your toxcore repo and recompile & install toxcore, then try building qTox again.

**Comment by ghost** [comment]
That worked, thx!
