### ISSUE TITLE
Nightly version are outdated

### ISSUE THREAD

**Issue by ntfshard** [qTox/qTox#4935]
##### Brief Description

OS: Window 32/68
qTox version: nightly
Commit hash:  n/a
toxcore:  n/a
Qt:  n/a
Hardware:  n/a

Reproducible: Always

##### Steps to reproduce
1. goto https://github.com/qTox/qTox
2. download windows nightly build
3. open archive

##### Observed Behavior
files modification date == 2017-12-28 21:33

##### Expected Behavior
today - files modification date < 1 week

##### Additional Info
On the https://tox.chat/download.html page nightly links following to 404 error

**Comment by tox-user** [comment]
The 404 error on https://tox.chat/download.html is fixed now.

**Comment by tox-user** [comment]
Outdated nightly builds are still not fixed. @nurupo could you try to link qTox repo with toxcore 0.1.11? Nightly builds are failing with current version (I assume it's 0.2.0?) and the last working nightly we have is from december 2017. Unless the reason the builds are failing is something else?

**Comment by Chiitoo** [comment]
Was updating my local builds, and it did seem to me, that they use the current master?  I might be completely wrong!
```
Project qTox-cmake-nightly_build_windows_x86-64_release:

Copied 1 artifact from
"libtoxcore-toktok_build_windows_x86-64_static_release"
build number 222

[...]

Copied 1 artifact from
"libtoxcore-toktok_src"
build number 205

[...]

git checkout -f 6f6c4dc2bd8820e6bccb9353ad42c951dc7adcd4
```

**Comment by ntfshard** [comment]
Did you verify the links?

**Comment by tox-user** [comment]
@sudden6, @Diadlo the cmake nightly builds are still failing https://build.tox.chat/view/qtox/

**Comment by Diadlo** [comment]
Still failing. Now I have no ideas why
https://build.tox.chat/view/qtox/job/qTox-cmake-nightly_build_windows_x86-64_debug/lastFailedBuild/console

**Comment by Diadlo** [comment]
@sudden6 Is it ok, that toxcore compiled statically? I think, it requires `libpthread`

**Comment by sudden6** [comment]
I'm not sure. Since the same setup seems to work with toxcore v0.1.11, I suspect something in toxcore changed. Also nurupo is looking into it when he has time.
