### ISSUE TITLE
Missing Dependencies in INSTALL.md

### ISSUE THREAD

**Issue by spyjoshx** [qTox/qTox#4945]
I was compiling qtox on Ubuntu 17.10, and following the instructions in INSTALL.md. When running cmake for qTox, I was missing the packages libavcodec-dev and libavdevice-dev. You should probably add those to your dependencies lists. ;)

**Comment by sudden6** [comment]
can you open a PR to add them?

**Comment by spyjoshx** [comment]
I've never done a Pull Request before... But I'd love to try! ;)
EDIT: I'm stupid. I was looking at the wrong dependencies list! I was following the instructions for 15.04+ and not 16.04+. No problems here! Just looking at the wrong table.

**Comment by sudden6** [comment]
ok, closing then
