### ISSUE TITLE
webcam VID_13D3&PID_5702 is not working

### ISSUE THREAD

**Issue by b-fett** [qTox/qTox#4947]
##### Brief Description
Q|A
-- | --
OS |Windows 7 (6.1.7601)
qTox version|  v1.13.0.
Commit hash| https://github.com/qTox/qTox/commit/531defd0aa66af1b128f7293bc08718ce2cc064f
toxcore| 0.1.10
Qt| 5.9.3
Hardware| Asus 1215N, webcam: VID_13D3&PID_5702
Reproducible| Always

##### Steps to reproduce
1. Run program
2. Go to settings, tab Audio/Video
3. Choose webcam as current video device (may choose any resolution, no matter)

##### Observed Behavior
Frame under video settings displays stub image.
![image](https://user-images.githubusercontent.com/33630339/35830070-a04b3fea-0acd-11e8-9e60-b5f1963012e0.png)

##### Expected Behavior
Frame displays image from webcam.

##### Additional Info
Webcam is okay, i tested it with other soft.

##### Log
[qtox.log](https://github.com/qTox/qTox/files/1696900/qtox.log)

**Comment by anthonybilinski** [comment]
@b-fett it looks likely to be the same issue as https://github.com/qTox/qTox/issues/4764
Could you try the build at https://circleci.com/api/v1/project/qTox/qTox/latest/artifacts/0/$CIRCLE_ARTIFACTS/x86_64/qtox_x86_64_release.zip?filter=successful&branch=pull%2F4909 and see if it fixes your issue?

**Comment by b-fett** [comment]
@anthonybilinski , appreciate for quick response. This build is fine for me. Now i get webcam picture.

**Comment by anthonybilinski** [comment]
Great. This fix is merged in, but there hasn't been a release since the fix. The next released qTox should not have this issue, until then you can use this build.
