### ISSUE TITLE
-p option does not open new instance, instead activates already running instance

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#4948]
##### Brief Description

OS: Ubuntu 17.10
qTox version: 1.13.0
Commit hash:  d2deec7c554b3df651fe789dfb7964748329eff4
toxcore: 0.1.11
Qt:  5.9.1

Reproducible: Rarely

##### Steps to reproduce

1. Open one instance
2. Open second instance using `-p` command. First instance had been open for ~10 minutes, connected, messages sent, etc.

##### Observed Behavior
First profile:
```
[06:04:04.173 UTC] ipc.cpp:61 : Debug: Our global IPC ID is  5937137295508197568
```
...

Second profile:
```
$ qtox -p qTest
[06:24:31.846 UTC] persistence/settings.cpp:133 : Debug: "Loading settings from /home/abilinski/.config/tox/qtox.ini"
[06:24:32.013 UTC] ipc.cpp:61 : Debug: Our global IPC ID is  11867555921098719186
[06:24:32.013 UTC] ipc.cpp:73 : Debug: Attaching to the global shared memory
[06:24:32.013 UTC] main.cpp:256 : Debug: built on:  19:52:03 Feb  2 2018 ( 1517470392 )
[06:24:32.013 UTC] main.cpp:257 : Debug: commit:  2311b2f3a32053583c6033fa21949558f182dac8
[06:24:32.071 UTC] ipc.cpp:128 : Debug: postEvent  "activate" to 3206496587
[06:24:33.077 UTC] main.cpp:317 : Debug: Another qTox instance is already running. If you want to start a second instance, please open login screen (qtox -l) or start with a profile (qtox -p <profile name>).
```
Once in this state, no other profile can be opened using `-p`. Using `qtox -l` correctly opens the login window instead of activating the existing profile.
##### Expected Behavior
-p launches a new instance.

**Comment by Diadlo** [comment]
Just and suggestion: try to add some debug messages in all IPC functions to see, what new instance send and what old instance receive

**Comment by anthonybilinski** [comment]
I finally repro'd this issue locally and was able to attach gdb to both the new and the running profile:
on new instance in postEvent:
ipc.cpp:
```
(gdb) print name.toLatin1().data()
$5 = 0x555556250e48 "activate"
(gdb) print data.toStdString()
$7 = ""
(gdb) print dest
$9 = 3206496587
main.cpp:
(gdb) print Settings::makeProfileId(profileName)
$13 = 3206496587
```
on running instance, processing ipc event:
ipc.cpp:
```
(gdb) print evt->dest
$4 = 3206496587
(gdb) print Settings::getInstance().getCurrentProfileId()
$5 = 3206496587
```
re-run running instance form main.cpp:
```
(gdb) print Settings::makeProfileId(profileName)
$3 = 3651057879
```
so it looks like my running instance is somehow having its ProfileId changed to the correct ProfileId of the second profile, so when the second profile posts an event to itself, the first profile picks it up and activates. Not yet sure how that ProfileId is being changed...

**Comment by anthonybilinski** [comment]
I found the repro case!
1. launched qTestEncrypted: `qTox -p qTestEncrypted`
    * IPC is init with qTestEncrypted's ID
2. Login prompt is opened for password entry. Select a different profile, `qTest`
3. `qTest` loads, still using `qTestEncrypted`'s IPC ID
4. launch qTestEncrypted profile: `qTox -p qTestEncrypted`
    * Sends activate to `qTest`'s instance.
5. launch qTest profile: `qTox -p qTest`
    * Sends activate to its own IPC ID which is not in use, then tries to open new instance but fails to lock.
