### ISSUE TITLE
Why deleted qApp->setQuitOnLastWindowClosed(false) ?

### ISSUE THREAD

**Issue by hkarel** [qTox/qTox#4949]
Why deleted qApp->setQuitOnLastWindowClosed(false) ? 
gitrev: 11f263ffc37e282625ac14e5b6c6bee99287976a
Now the application just exits, and not hidden in the tray

**Comment by tox-user** [comment]
I confirm that with close to tray enabled qTox doesn't minimize to tray as expected and exits instead.

**Comment by sudden6** [comment]
An oversight during testing because I don't use that feature.
