### ISSUE TITLE
Camera preview borked since UI redesign

### ISSUE THREAD

**Issue by bricky149** [qTox/qTox#495]
![boog](https://cloud.githubusercontent.com/assets/4836781/4711105/b450bfd4-58b4-11e4-927a-7d0d95c8ad83.png)
The settings also reset upon restarting qTox, likely not saved.

**Comment by dubslow** [comment]
@agilob

**Comment by agilob** [comment]
I can't reproduce, it works on my machine and it saves settings. Anyone else having this problem?

**Comment by dcharles525** [comment]
My video is fine, settings are not saved though.

**Comment by tux3** [comment]
If you put the Hue/Brightness/Saturation/Contrast back to normal values, does the video work again ?

**Comment by bricky149** [comment]
It does nothing for me, tux. I've tried messing with the sliders, restarting and even unplugging and plugging my webcam back in before filing this issue.

**Comment by agilob** [comment]
Do you compile it from sources or download binary?

**Comment by bricky149** [comment]
I download the binary, I'm too dumb to compile it from source.

**Comment by dubslow** [comment]
@agilob Try adding a bunch of print statements. @bricky149 can you run this from terminal to see the logging messages?

**Comment by bricky149** [comment]
Can't right now since it's late for me here, I'll test at the earliest opportunity.

**Comment by agilob** [comment]
@dubslow [I modified](https://github.com/tux3/qTox/commit/68309ef55e9159beb710c6815ea758a2acc996d5) only one file - avsettings.ui, I don't think this commit would broke webcam support on Windows. I didn't do any more changes in audio/video support. It would be best if @bricky149 could test qTox after and before this one particular commit.

**Comment by bricky149** [comment]
@agilob It wasn't that commit that broke it, it had something to do with embedding the settings window into the application itself.
I'm not getting any debug messages in Command Prompt either. It would be better(?) if I could set up Qt to work with this project.

**Comment by agilob** [comment]
@bricky149 could you confirm if the problem still exists?

**Comment by bricky149** [comment]
The problem still exists. (I was away without internet so I couldn't reply sooner)
![qtoxcamera](https://cloud.githubusercontent.com/assets/4836781/4808392/1c169d8c-5ea0-11e4-8ed7-0b81fd3e3145.png)

**Comment by bricky149** [comment]
![qtoxwebcam](https://cloud.githubusercontent.com/assets/4836781/4873335/aeb10c7a-620d-11e4-8225-65ff2f03425e.png)
Debug log:
2014-01-11 21:20:11 file logger starting
21:20:11 built on:  15:27:14 Nov  1 2014
21:20:11 commit:  fd67a375eabcde1c391cc1baebd4a007d276c0c7 
21:20:11 Settings: Loading from  "C:/Users/Shane/AppData/Roaming/tox/settings.ini"
21:20:11 Using embeded bootstrap nodes list
21:20:11 Error loading translation "en"
21:20:11 Problem creating accessible interface for:  Widget(0x5129b38, name = "MainWindow") 
Make sure to deploy Qt with accessibility plugins.
21:20:11 Core: loading Tox from "C:/Users/Shane/AppData/Roaming/tox/bricky149.tox"
21:20:12 Core starting with IPv6 disabled. LAN discovery may not work properly.
21:20:12 Core::loadConfiguration: reading from  "C:/Users/Shane/AppData/Roaming/tox/bricky149.tox"
21:20:12 VideoSurface: Init
21:20:12 VideoSurface: Init
21:20:12 VideoSurface: Init
21:20:12 VideoSurface: Init
21:20:14 Core: Bootstraping to the DHT ...
21:20:14 "Core: Bootstraping from astonex, addr 37.59.102.176, port 33445"
21:20:14 "Core: Bootstraping from nurupo, addr 192.210.149.121, port 33445"
21:20:15 Core: Connected to DHT
21:20:15 Settings: Saving in  "C:/Users/Shane/AppData/Roaming/tox/settings.ini"
21:20:15 Core: writing tox_save to  "C:/Users/Shane/AppData/Roaming/tox/bricky149.tox"
21:20:25 CameraWorker: Resume
21:20:31 CameraWorker: Resolutions (QSize(160, 120) ,  QSize(320, 240) ,  QSize(424, 240) ,  QSize(640, 360) ,  QSize(640, 480) ,  QSize(800, 600) ,  QSize(960, 720) ,  QSize(1280, 720) ,  QSize(1280, 800) ) 
21:20:31 VideoSurface: Resize pbo  3072000 ( QSize(1280, 800) ) bytes (before 0 )
21:20:39 Settings: Saving in  "C:/Users/Shane/AppData/Roaming/tox/settings.ini"
21:20:39 Core: writing tox_save to  "C:/Users/Shane/AppData/Roaming/tox/bricky149.tox"
21:20:39 Settings: Saving in  "C:/Users/Shane/AppData/Roaming/tox/settings.ini"
21:20:39 Core: writing tox_save to  "C:/Users/Shane/AppData/Roaming/tox/bricky149.tox"

**Comment by cotti** [comment]
Hello, I have a similar issue. I have a Logitech C920, with proper drivers and everything. Just tested in the latest nightly build (2014-11-09 08:53:15).

Before the UI change, it wouldn't even load. Now, it blinks for a few seconds, then shows only garbage in the same fashion as shown in the above screenshots.

Also, the resolution is reset if I move to another configuration tab and then back.

**Comment by bricky149** [comment]
Any update on this? Sliders are due to #527.
![previewnowerk](https://cloud.githubusercontent.com/assets/4836781/5064147/15a2a4aa-6dfa-11e4-98a0-cf2883ffd97b.png)

**Comment by zetok** [comment]
Am I right thinking that it's a windows-only bug?

**Comment by tux3** [comment]
@zetok  I think so, but I had a similar problem a long time ago on my linux

**Comment by bricky149** [comment]
Quick update - For a while, going to the A/V settings has caused my webcam light to continuously flash for about 5 seconds (probably probing) and forces saturation to 0.
![qtoxwebcam](https://cloud.githubusercontent.com/assets/4836781/6342328/3344f0f8-bbcf-11e4-8bf6-fcb4666172dc.jpg)

**Comment by tux3** [comment]
@bricky149 so, except the sliders and probing, it does work now ?

**Comment by bricky149** [comment]
@tux3 It has been like this for a while but every time I go into qTox's A/V settings the only way to undo the undesirable settings is to open Skype and change them via the webcam settings panel.

**Comment by koobs** [comment]
+1
- Logitech C920, latest drivers
- Latest successful qTox build (@ 20150311-20:14:00 UTC+11)

I see:
- On-camera flashing for ~5 seconds on first initialization
- Switches to native 1920x1200 resolution. All sliders: 0
- Flashing (~1-2 seconds) on subsequent inits (Switching between Privacy Audio/Video Tabs)
- Brightness is extremely low, appears to be no color. Framerate appears smooth.
- Changing slider values has no effect
- Changing resolution appears to work (preview changes) for some, but not all values

**Comment by huettenhain** [comment]
Something similar happens for me. I have two devices:

1) Lenovo Yoga Pro (builtin camera)
When I start the preview in qTox, it works but is only greyscale. The sliders do not appear to have any effect. When I launch skype now, the image is still greyscale - but I can use skype to access my camera's settings and set them back to normal. This fixes the image quality in skype. When I launch qTox again and look at the preview, it is greyscale again.

2) Logitech USB Webcam, unfortunately it's old and I have no idea which model this is.
Essentially, the same thing happens: When I launch the preview in qTox, the camera blinks for a long while, then I get an "image" which is just grey, and I don't mean greyscale but actually just a monocolor grey screen. Again when I launch the camera preview in skype, it still is monocolor grey, and when I look at the camera settings provided by Skype, I can see that saturation, contrast and brightness are all set to 0. Resetting these values in Skype fixes the image in Skype, but as soon as I open the qTox preview, the same thing as before happens. Again, the sliders for hue, saturation and constrast do not seem to have any effect in qTox.

**Comment by agilob** [comment]
bump
Is it still broken?

**Comment by tux3** [comment]
It probably is still broken, since there was no major change to the video code since then.

I'll be working on the video code soon, so hopefully I'll get a chance to fix that in the process.

**Comment by agilob** [comment]
I remember this issue and there was no major change in 'ui redesign' too. I changed only layout of widgets ;)
Ok, thanks.

**Comment by flyingfences** [comment]
I downloaded the Windows x64 binary just now and I am also having the complete desaturation issue. The sliders do nothing. My webcam light does blink repeatedly as the camera is initialized. Everything works properly in Skype, but as soon as I start using the cam in qTox, it goes grayscale again. This is the built-in camera on an HP ZBook 15.
![qtoxdesaturation](https://cloud.githubusercontent.com/assets/8800368/8074792/85bb8f1c-0f04-11e5-9901-fcb7d753a4be.png)

**Comment by tux3** [comment]
@flyingfences Where did you download the Windows version?

**Comment by flyingfences** [comment]
@tux3 I got it from the Tox wiki at https://wiki.tox.im/Binaries#Windows which directed me to https://tux3-dev.tox.im/jenkins/job/qTox-win64-nsis/lastSuccessfulBuild/artifact/setup-qtox64.exe

**Comment by agilob** [comment]
Bump

Is it still na issue?

**Comment by koobs** [comment]
No longer an issue (for me) with Logitech C920 using Native UVC driver (not Logitech Webcam Software) on version: https://github.com/tux3/qTox/commit/f10b4eaee7072bb9fbad5490be016455ba934bcf. 

Edit 20150822: Switch to native UVC driver may not be related (See: https://github.com/tux3/qTox/issues/495#issuecomment-128263433)

However:
- Controls are no longer visible. Not sure if they were removed, or just not enumerated correctly by qTox

**Comment by agilob** [comment]
They were removed when we switched to ffmpeg from opencv.

**Comment by agilob** [comment]
Closing since no one can reproduce.

**Comment by koobs** [comment]
To clarify, closing because noone has (yet) been able to reproduce **since** the switch from ffmpeg to opencv.

ie: can **no longer** reproduce, assuming fixed.
