### ISSUE TITLE
License of the Classic smileys

### ISSUE THREAD

**Issue by eclipseo** [qTox/qTox#4954]
Hello,

Currently the "Classic" smileys are licensed under CC BY-NC:

./angry.png: CC by-nc
./cool.png: CC by-nc
./crying.png: CC by-nc
./happy.png: CC by-nc
./laugh.png: CC by-nc
./laugh_closed_eyes.png: CC by-nc
./plain.png: CC by-nc
./sad.png: CC by-nc
./scared.png: CC by-nc
./smile.png: CC by-nc
./stunned.png: CC by-nc
./tongue.png: CC by-nc
./uncertain.png: CC by-nc
./wink.png: CC by-nc

The problem is that license is "not Free" as defined by the FSF which prevents its inclusion in free distribution like Fedora. Would you mind relicensing these smileys as CC-BY?

**Comment by anthonybilinski** [comment]
I believe @krepa098 is the sole copyright holder, since they are the original author and there have been no modifiers. @krepa098 do you mind relicensing this smiley pack under CC-BY, CC-BY-SA, or CC0 since I believe those are all compatible as part of a GPL project?

**Comment by tox-user** [comment]
Can we use some license that requires the art to remain free? Just like GPL does for software?

**Comment by anthonybilinski** [comment]
CC-BY-SA does effectively that with its "ShareAlike" clause: "This license lets others remix, tweak, and build upon your work even for commercial purposes, as long as they credit you and license their new creations under the identical terms."
https://creativecommons.org/share-your-work/licensing-types-examples/licensing-examples/#sa

EDIT: to clarify, other CC licenses also require the art to remain free by being irrevocable, they just don't guarantee modifications made are free as well, like CC-BY-SA and GPL do.

**Comment by tox-user** [comment]
@eclipseo could you link to a list of free licenses for art? How do you know this one is not considered free by the FSF?

**Comment by eclipseo** [comment]
I'm working for Fedora so I can provide the list of approved licenses used in our project: https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#Content_Licenses

There's also this list by the FSF https://www.gnu.org/licenses/license-list.html#OtherLicenses

>How do you know this one is not considered free by the FSF?

It is stated here: https://www.gnu.org/licenses/license-list.html#CC-BY-NC

**Comment by krepa098** [comment]
I don't mind changing the license. CC-BY-SA seems like a sensible choice.

**Comment by eclipseo** [comment]
If this is okay then, you just need to update the icons' metadata or add a license file in the directory like some other smiley package.

**Comment by anthonybilinski** [comment]
I think updating the metadata would be preferred even if adding a license file, just so that the license in metadata and license in file don't conflict.
