### ISSUE TITLE
All is working but qtox isn't compiled

### ISSUE THREAD

**Issue by xyloforce** [qTox/qTox#4963]
##### Brief Description

OS: Linux (KDE neon 5.12 based on Ubuntu)  

Reproducible: Always

##### Steps to reproduce

1. Follow the [tutoriel](https://github.com/qTox/qTox/blob/master/INSTALL.md#install-git) & correct all the errors
2. Enter "./qtox"
3. Bash says he can't find the file

##### Additional Info
Screen of Konsole :
![image](https://user-images.githubusercontent.com/36670653/36433941-1328acb4-165e-11e8-9ce4-da3bf331a069.png)

I'm sorry to give so little information but I don't know which ones may be needed...

**Comment by Diadlo** [comment]
Probably, because you have builded toxcore?)

**Comment by xyloforce** [comment]
.... That's right. I didn't noticed the line "Run in qTox directory". Many, many thanks :) Now it works.

P.S : I don't know if it's a good idea to add this here but I add to install the package "qttools5-dev" without the -tools at the end to make things work, otherwise I add the error "By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "Qt5LinguistTools", but CMake did not find one.". It seems it isn't listed in the dependencies for Ubuntu :)

**Comment by sudden6** [comment]
@xyloforce would be nice if you could open a PR for that :)

**Comment by xyloforce** [comment]
I tried, I hope it worked :) Obtained that :
![image](https://user-images.githubusercontent.com/36670653/36482546-f2b0d752-1713-11e8-9d34-413627413111.png)

Should I merge or wait ?

**Comment by tox-user** [comment]
You need to create a pull request in qTox/qTox repository. To do that go to https://github.com/qTox/qTox/pulls and click on "New pull request button" there. Then select your branch "xyloforce-patch-1".

**Comment by Diadlo** [comment]
Or just open https://github.com/qTox/qTox/ and probably there will be long green line with button

**Comment by xyloforce** [comment]
But I can't select my branch... ? ^^ I'm sorry, I feel so newbie, and so I am... I clicked on the "merge pull request" from the screenshot above & it worked, now the file has the addition I wanted to make, so that's nice, no ? Did I made a mistake ? If I did, please excuse me :/

**Comment by Diadlo** [comment]
You send PR in your own repo and merge it

**Comment by Diadlo** [comment]
You can open PR at this link:
https://github.com/qTox/qTox/compare/master...xyloforce:xyloforce-patch-1

**Comment by xyloforce** [comment]
Ok, it's done ! Hope it worked (and many thanks to you for your help :) )

**Comment by anthonybilinski** [comment]
PR for docs update is merged: https://github.com/qTox/qTox/pull/4968
Original issue is resolved. Closing.
