### ISSUE TITLE
Import profile

### ISSUE THREAD

**Issue by jbshirk** [qTox/qTox#497]
I started out with tox/poison and now want to use qtox. I'd like to use the same ID and contacts but poison does not export the profile. Where does it store this info and where does qtox look for the import file, and what should be its format? I am assuming the file begins with copy/paste of tox ID.

OS X Mavericks

**Comment by zetok** [comment]
AFAIK format in which Poison stores its data isn't compatible with other clients.

Please correct me if I'm wrong, @stal888

**Comment by stal888** [comment]
A tool exists to convert Poison format to utox, toxic, etc. formats.

**Comment by zetok** [comment]
@stal888 the only tool I found was described as tool to convert from `tox_save()` → `Poison format`: https://github.com/stal888/Poison/issues/30
Did you have this one on mind, or some other tool?

**Comment by stal888** [comment]
this one: https://github.com/stal888/Poison/blob/master/objective_tox/testing/mio/mio.c

**Comment by jbshirk** [comment]
Thanks for the ideas. I'm not going to compile that mio.c -- anyway Poison did not even save my profile and its contacts when I shut it down. There was an option to do so before I shut it down but it just went thru the motions and didn't save anything. I'm glad I'm done with it. I'll just rebuild my contacts manually.

**Comment by timofonic** [comment]
I'm trying to import an Antox profile, no way...

I try to open the .tox file by double click, copied to the program folder, etc.

**Comment by zetok** [comment]
@timofonic did you put it in your [`tox`](https://github.com/tux3/qTox/wiki/Profile) directory?

#2050 would be good to have though..
