### ISSUE TITLE
Is possible to add a function that can use p2p search for unknown peoples who want become a "We Media" in future ?

### ISSUE THREAD

**Issue by pituielfsgrk** [qTox/qTox#4973]
retroshare is a full function pt/eMule,and whith p2p chat,p2p website,file share ,it can use p2p search like eMule,but without introducer you cant use any function except chat.Is possible tox to add open p2p search like eMule for the peoples who want become a "We Media"? because is hard to persuade friend to use a new chat to replace the popular chat software.and Mancur Lloyd Olson proven the "dictatorship bandit government "the same as north Korea will ban the website.

**Comment by shurric** [comment]
what

**Comment by anthonybilinski** [comment]
I'm also having a hard time understanding. Can you try to clarify and link to some of the resources you're talking about? For me it's 10 new projects I haven't heard about all together.

Are you wanting Tox to become a full peer-to-peer network on top of which generic applications can be written, like with [retroshare](http://retroshare.net/)? What do you mean by "become a "We Media" "?

Are you just looking for a way to search for friends from within Tox?
