### ISSUE TITLE
Cannot see peer video during call, only squiggly lines

### ISSUE THREAD

**Issue by TM7412** [qTox/qTox#4974]
I first posted this on Reddit (https://www.reddit.com/r/projecttox/comments/802jbx/qtox_video_not_working_properly/), but it was suggested that it was better for me to post a bug report here to find a solution to my qTox video problem.

The issue: Incoming video on a laptop is just squiggly lines. The sending computer receives video/audio perfectly & its webcam thumbnail shows that its audio/video is working fine, the laptop just doesn’t seem to be receiving the video, although it does receive the audio from the sending webcam’s built-in microphone (Logitech C270).

FWIW, both computers work perfectly using Wire.

*******************************
OS: Linux Mint 18.1 64-bit Cinnamon
qTox version: You are using qTox version Nightly.
Commit hash: build without git
toxcore version: 0.1.10
Qt version: 5.5.1
Hardware: Core i3-2310M; 4 GB RAM; integrated Intel graphics chip 

qTox debug log: [qtox-log-.txt](https://github.com/qTox/qTox/files/1765224/qtox-log-.txt)

**Comment by anthonybilinski** [comment]
By webcam thumbnail, is that the preview within qTox settings->Audio/Video, or is that some external view? If external, does the qTox preview work?

**Comment by TM7412** [comment]
The webcam thumbnail is visible both in the settings area & within an actual qTox video call on the PC (desktop), but no video is received by the other PC (laptop) during the call. The laptop only shows its own thumbnail & squiggly lines from the incoming video.

**Comment by anthonybilinski** [comment]
Is the log and versioning/OS info all from the laptop? Also can you post a screenshot the squiggly lines?

Can you try updating to both qTox and toxcore tip and trying again, currently your toxcore is one release behind.

All of the `Warning: Pixel format not found` is suspicious and looks like https://github.com/qTox/qTox/issues/4764 but since the issue is decoding the peer's video and not some weird format from your local webcam it's probably not related..

**Comment by TM7412** [comment]
Yes, the log and version info is all from the laptop.

I thought I had the latest version of qTox, but I will try updating it later today when I have more time and see if that fixes the problem. If not, I will do a screen grab and post it here.

Thanks for your help.

**Comment by sudden6** [comment]
There's still a bug in c-toxcore 0.1.x with high resolution video, you can try to use the lowest possible resolution.

**Comment by TM7412** [comment]
@anthonybilinski - According to https://github.com/qTox/qTox/releases/latest and Synaptic Package Manager I have the latest stable v. installed (v1.13.0) on both computers. I downloaded & installed from the .deb (qtox_201711271502~v1.13.0_amd64.deb). I don’t know why qTox Settings > About - shows the wrong version.

@sudden6 - I am testing various resolution settings now & will update with results soon.

**Comment by TM7412** [comment]
Update:

I don’t know why or how, but everything is working now. My buddy & I did a video call between the two computers & each of us went through & tried each video resolution option in the settings areas & video started coming through on the laptop. Once it started working, we were able to set to the highest resolutions & it now works.

Thanks for your help everyone.
