### ISSUE TITLE
Disabling notification has no effect under gnome

### ISSUE THREAD

**Issue by zero-master** [qTox/qTox#4979]
qTox, version: 531defd0aa66af1b128f7293bc08718ce2cc064f
Built: 04:36:19 Jan  4 2018

Arch Linux

**Comment by Diadlo** [comment]
Can you fill issue template? How to reproduce the issue? What happens, what do you expect?

**Comment by zero-master** [comment]
1. Try disabling notification

![image](https://user-images.githubusercontent.com/1130261/36846027-f9b6e5e2-1d93-11e8-85fa-173b8e3da25e.png)

2. Now, keep qtox open in the tray

3. Message to this account from some other account

You'll end up receiving a notification popup.

I don't know how else I can stop the notification.

This is with Gnome on Arch Linux, installed from AUR.

**Comment by Diadlo** [comment]
But qTox hasn't notification popups. Also, if I understand it correctly, it's GNOME settings => with it you can only disable notifications of GNOME applications, but not others

**Comment by sudden6** [comment]
In qTox settings got to `User Interface` -> `New Message` and disable it. Report back if that helps.

**Comment by zero-master** [comment]
I had it disabled but it doesn't work.

![image](https://user-images.githubusercontent.com/1130261/36933912-09acadf4-1f1c-11e8-8cf0-9607fcb6adbd.png)

**Comment by sudden6** [comment]
Can you show us this notification popup and the log output of qTox when a notification happens?

**Comment by tox-user** [comment]
Here an example of a notification I get in the top bar:
![qtox notifications](https://user-images.githubusercontent.com/32248732/36941545-d0f3b05e-1f55-11e8-9bda-839971f3a569.png)

**Comment by sudden6** [comment]
GNOME seems to do something special here, no idea where that notification comes from.

**Comment by tox-user** [comment]
@anthonybilinski found out that we use https://doc.qt.io/qt-5/qapplication.html#alert in widget.cpp. That could be the cause.

**Comment by sudden6** [comment]
The alert should be disabled when applying the setting from above. Maybe it's not properly disabled.

**Comment by anthonybilinski** [comment]
The setting under UI -> new message -> open window when disabled disables opening the window, but doesn't disable calling alert():
```
bool Widget::newMessageAlert(QWidget* currentWindow, bool isActive, bool sound, bool notify)
{
    bool inactiveWindow = isMinimized() || !currentWindow->isActiveWindow();

    if (!inactiveWindow && isActive) {
        return false;
    }

    if (notify) {
        if (inactiveWindow) {
            QApplication::alert(currentWindow);
            eventFlag = true;
        }
```
so we alert just based on the window not being active and bool notify which is passed in. To fix this we should probably add another notification setting to not call alert at all. It seems somewhat independent from opening window or selecting window.
