### ISSUE TITLE
multi-connections?

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#498]
```
"Core: Bootstraping from aitjcize, addr 54.199.139.199, port 33445"
"Core: Bootstraping from astonex, addr 37.59.102.176, port 33445"
---> Core: Connected to DHT
Settings: Saving in  "/home/agilob/.config/tox/settings.ini"
Core: writing tox_save to  "/home/agilob/.config/tox/agilob.tox"
Core: Disconnected to DHT
---> Core: Connected to DHT
Settings: Saving in  "/home/agilob/.config/tox/settings.ini"
Core: writing tox_save to  "/home/agilob/.config/tox/agilob.tox"
Core: Disconnected to DHT
---> Core: Connected to DHT
```

Why does qTox establish 3 connections? This might be problematic in the future, as I got 2 notification about GroupBot changing status to online, I assume, two notifications come from two servers? And why is it saving and loading config on start and quit so many times?

**Comment by tux3** [comment]
Apparently, you got disconnected twice in a row, but I'm not sure why. Does it happen every time ?

**Comment by agilob** [comment]
80% of times (no, didn't count) I start qTox

**Comment by tux3** [comment]
I can't reproduce, did you change the network settings (IPv6, UDP, proxy,..) ?
If not can you get a log from toxcore ?

**Comment by agilob** [comment]
IPv6 and UDP enabled.

> If not can you get a log from toxcore ?

how can I do that?

**Comment by zetok** [comment]
you would have to compile core with support for logging:
https://github.com/irungentoo/toxcore/blob/master/configure.ac#L86
and perhaps:
https://github.com/irungentoo/toxcore/blob/master/configure.ac#L99,L100

**Comment by dubslow** [comment]
This is the same problem as #340, and ultimately is a core issue with tox_isconnected(). In the meantime, we can up the tolerance I introduced for 340 (near Core::process). Don't go higher than ~50, and even that is ~2.5 seconds of waiting...

**Comment by dubslow** [comment]
Should be improved by https://github.com/irungentoo/toxcore/commit/44f63db6223efe04e6b5f9547c2e47ae5da2d521

**Comment by tux3** [comment]
Is this still a problem after irungentoo/toxcore@44f63db ?

**Comment by agilob** [comment]
Yes, I'm still able to reproduce it 
https://gist.github.com/agilob/faafd7f3b52835922798#file-gistfile1-txt

**Comment by dubslow** [comment]
I have too, but there's still not much we can do about it. It's harmless aside from the messages printed though.

**Comment by agilob** [comment]
µTox and ratox do the same. I think this can be moved to toxcore or closed.
