### ISSUE TITLE
toxcore does not compile on Debian

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#4992]
autoreconf -if
libtoolize: $pkgltdldir is not a directory: `/usr/local/share /libtool'
autoreconf: libtoolize failed with exit status: 1
:(
How do I fix it?

**Comment by tox-user** [comment]
Use cmake. For example:
```
cmake .
make
make install
```

**Comment by tox-user** [comment]
In the future you should post issues related to toxcore in https://github.com/toktok/c-toxcore.

**Comment by Diadlo** [comment]
As @tox-user said, you posted your issue in wrong repo
