### ISSUE TITLE
Can't switch back after switching Tox profile during call

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#500]
How to reproduce:
1. Be in call
2. Go to settings
3. Go to identity
4. Click "New Tox ID"
5. Choose other ID in list
6. Click "Load"

Expected result:
Tox profile is switched

Actual result:
"You can't switch profiles while a call is active!" error pops up.

Note:
When creating a new Tox ID, qTox automatically switches to it, so it allowed me to switch to a new ID during a call (due to creation) but refused to let me switch back, even though it killed the call.

**Comment by dubslow** [comment]
It shouldn't have let you make a new profile while in a call, I'll fix that as well as a workaround for a related bug soon...
