### ISSUE TITLE
Create new setup for Windows builds

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#5001]
Since the autoupdater was disabled (always broken) we have no real workflow to publish Windows builds anymore. Now we need to make a few decisions to continue providing Windows builds.

- Signed images or not signed images?
- Continue using build.tox.chat for our release builds or release them on Github using CircleCI or TravisCI?

**Comment by tox-user** [comment]
We should sign the builds with GPG and be able to do it in a way that would allow us to publish the signatures on tox.chat and on qtox.github.io. The downloads should be available on qtox.github.io too. uTox hosts their binaries on their own website, maybe we could do that as well?

**Comment by Diadlo** [comment]
Or fix updater :/

@tox-user we shouldn't sign what was builded not by us, but by the 3rd server

**Comment by sudden6** [comment]
@Diadlo I don't think fixing the updater is doable in a short term (<2 weeks)

Personally I would favor a workflow similar to our MacOS builds right now. TravisCI builds the setup file, then one of the maintainers would GPG sign it.

I know this is not really ideal, but I think it's the best compromise between amount of work needed on every release and security.

**Comment by Diadlo** [comment]
@sudden6 I'm ok with TravisCI/CircleCI build. But I'm not in favor of GPG sign of build made by 3rd server.

**Comment by sudden6** [comment]
But how else should we provide some reasonable protection against someone exchanging the binary? With signing we can at least protect against someone later exchanging the release without anyone noticing. This would minimize the time an attack window is open.

**Comment by Diadlo** [comment]
@sudden6 We can post file hash

**Comment by sudden6** [comment]
If you can exchange the file, you can also exchange the hash.

**Comment by anthonybilinski** [comment]
IMO using a 3rd party build isn't really worse than having one of us build and sign, since our builds aren't binary reproducible it's just taking our word against Travis CI's, and I don't think any one of us is _that_ must more trustworthy than a third party org.

RE: us signing a build which we can't verify: it seems worthwhile in that we can say "this was the original hash" cryptographically securely, but we can't say "this binary is legit" because we can't verify that. In that way signing seems ok to me as long as we make it clear what we're saying. If users don't want to trust either one of us or a third party to faithfully build the release, since we don't have reproducible builds, their only option is to compile themselves.

**Comment by tox-user** [comment]
GPG is a must have and the hashes too. If we can't provide secure builds, we should not provide them at all. qTox is supposed to be a secure program. We need to find a way to have reproducible builds, at least in the same environment. If we could make it possible for all developers to check, if the binary hasn't been changed, that would be a big success. Then we could have one of us make the build and the rest would verify it by building in exactly the same environment and checking if the hash matches. Then such build and a file containing the hashes would be signed by a developer. In my opinion this is a high priority issue and we should take care of it as soon as possible.

**Comment by sudden6** [comment]
@anthonybilinski I fully agree with you. I think we should go this way as a short term solution.

@tox-user Reproducible builds would be very nice, but I doubt it's that easy. Debian is working on this for years and they need quite a few patches to their toochain IIRC. See also https://wiki.debian.org/ReproducibleBuilds

**Comment by sudden6** [comment]
I'm working on creating windows setup files inside travis now

**Comment by anthonybilinski** [comment]
Going to move this comment https://github.com/qTox/qTox/issues/5252#issuecomment-406420091 here from @quantumpacket since it relates to the discussion of unsigned releases:
>If that's the case, should we really be providing untrusted 3rd party binaries when tagging a new release? That's a sure footgun for installing a tampered qTox. worried I think that a release asset should not be provided if it can't be verified by a user. So maybe omit the AppImage file and/or others until they have a means of verification?

I'm not sure if even signing third party builds to ensure they are the original artifacts (if they're being distributed in untrusted places) even if we can't currently independently verify the contents of the artifacts resolves this concern.

**Comment by sudden6** [comment]
I think as long as we don't have reproducible builds we can't really improve the situation.

**Comment by tox-user** [comment]
We can. If we don't think the builds are safe we shouldn't distribute them. If we distribute them they should be signed.

**Comment by Diadlo** [comment]
We can build releases in docker and sign it

**Comment by sudden6** [comment]
> We can build releases in docker and sign it

Then we are again at the point, why should one of our systems be more trustworthy than Travis?

**Comment by Diadlo** [comment]
@sudden6 
> Then we are again at the point, why should one of our systems be more trustworthy than Travis?

Because it's open source project and can run locally. Do you trust to your compiler? :P

**Comment by sudden6** [comment]
> Because it's open source project and can run locally. Do you trust to your compiler? :P

The question is if a user should trust our compilers more than the Travis CI ones :)

**Comment by tox-user** [comment]
Reproducible builds are the answer. Until we get them just sign the damn builds please :).

**Comment by sudden6** [comment]
There is now a workflow to publish Windows builds using Docker and CircleCI. Reproducible builds are a different problem.
