### ISSUE TITLE
qTox crash

### ISSUE THREAD

**Issue by shinodem** [qTox/qTox#5002]
Os: windows 10
I have crash qtox at using, can't reproduce it but it crashing ~ from v1.13 or early even at latest 1.14. one or more times per day.
My friends have the same issue. 
In logs is nothing special, windows log gives Application Error (100) 1000

 System 

  - Provider 

   [ Name]  Application Error 
 
  - EventID 1000 

   [ Qualifiers]  0 
 
   Level 2 
 
   Task 100 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2018-03-14T09:50:57.227949700Z 
 
   EventRecordID 152747 
 
   Channel Application 
 
   Computer DESKTOP-7IJV0TM 
 
   Security 
 

- EventData 

   qtox.exe 
   0.0.0.0 
   00000000 
   qtox.exe 
   0.0.0.0 
   00000000 
   c0000005 
   00000000000a32c2 
   2290 
   01d3bb5be8774b9a 
   I:\qTox_build_windows_x86-64_release\qtox.exe 
   I:\qTox_build_windows_x86-64_release\qtox.exe 
   b12b472b-2a02-40c1-b092-af261356b04a

**Comment by tox-user** [comment]
Can you upload the log from qTox? It should be located in %APPDATA%\tox or C:\Users\username\AppData.

**Comment by shinodem** [comment]
[qtox.log](https://github.com/qTox/qTox/files/1811735/qtox.log) here you go, but where is nothing special in that time period. Time should be near 9:50:57 utc

**Comment by tox-user** [comment]
What were you doing in qTox at the time in crashed?

**Comment by shinodem** [comment]
I asked my friend too, he and i was writing message during crash, this is for last 3 crash, maybe i am wrong but it seem can crushed randomly during receiving message too

**Comment by sudden6** [comment]
Can you try with https://build.tox.chat/view/qtox/job/qTox-cmake-stable_build_windows_x86-64_debug/lastSuccessfulBuild/artifact/qTox-cmake-stable_build_windows_x86-64_debug.zip and run `debug-automatic.bat` then wait until it crashes please upload the backtrace.

**Comment by shinodem** [comment]
Ok will try. Is it only creates log at crash?

**Comment by sudden6** [comment]
It should run qTox in a debugger and provide the backtrace on a crash

**Comment by towlie** [comment]
I can confirm this crash on Windows 10 too. It happens rarely on my side but it seems to depend on message receiving.

**Comment by shinodem** [comment]
Finally it crashed =) here log
[20180316092245.txt](https://github.com/qTox/qTox/files/1818405/20180316092245.txt)
during crash i was in browser and no one writing to me, just crashed in idle

**Comment by anthonybilinski** [comment]
Thanks for the log, very helpful :)

I think the culprit is SmileyPack::cleanupIconsCache:
```
        std::shared_ptr<QIcon>& icon = it->second;
        if (icon.use_count() == 1) {
            it = cachedIcon.erase(it);
            icon.reset();
```
>References and iterators to the erased elements are invalidated.

http://en.cppreference.com/w/cpp/container/map/erase

We take a reference to the item, erase it, then access that reference. This seems like the issue.

Since the item is a shared_ptr anyway, no reset is required since it will be auto-destructed on removal of the last reference.

**Comment by Diadlo** [comment]
Segafult at [smileypack.cpp:130](https://github.com/qTox/qTox/blob/master/src/persistence/smileypack.cpp#L130)
Seems issue introduced by `fa2159490`
But seems error exists only at Windows

**Comment by Diadlo** [comment]
@anthonybilinski For some reason, when I tested it, object is not distructed without `reset`. Maybe we need to recheck it

**Comment by shinodem** [comment]
Not sure if it helps to find culprit, that crush is pretty rare, yesterday it work whole day without crash and just crashed today at morning, for my friend it still works without crash, he was used smiley. Hm i just send send several smiley and it crashed again, but after restart i can't reproduce it again.

**Comment by anthonybilinski** [comment]
@Diadlo running
```
#include <memory>
#include <iostream>
#include <map>
#include <string>
#include <unistd.h>

class TestClass {
public:
        TestClass() { std::cout << "Constructing TestClass" << std::endl; }
        ~TestClass() { std::cout << "Destructing TestClass" << std::endl; }
};

int main(void)
{
        std::map<std::string, std::shared_ptr<TestClass>> myMap;
        std::cout << "adding to map" << std::endl;
        myMap["index"] = std::shared_ptr<TestClass>(new TestClass());
        auto it = myMap.find("index");
        {
                std::cout << "taking second reference" << std::endl;
                auto fooRef = myMap["index"];
                std::cout << "count: " << it->second.use_count() << std::endl;
                std::cout << "removing second reference" << std::endl;
        }
        std::cout << "count: " << it->second.use_count() << std::endl;
        std::cout << "erasing from map" << std::endl;
        myMap.erase(it);
        sleep(1);
        std::cout << "exiting" << std::endl;
}
```
I see
```
adding to map
Constructing TestClass
taking second reference
count: 2
removing second reference
count: 1
erasing from map
Destructing TestClass
exiting
```
in which case `it` is still in scope when the shared pointer destructs TestClass. This seems very similar to our case. Can you repro the object not being destructed?
