### ISSUE TITLE
kde4 smiley pack pushes text out of line

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#501]
![qtox_smiley_bug](https://cloud.githubusercontent.com/assets/1885159/4735190/80ce7186-59dd-11e4-894e-e48eb5714447.png)

qTox should probably enforce the max height of a smiley to be the same as the max height of a text line, to prevent graphical issues like these.

EDIT: This seems to happen with "Boxed" too, so it's not emoticon-pack-specific.

**Comment by dubslow** [comment]
Now the smileys are rather pixelated. Depending on your point of view, they might be considered worse than before.

**Comment by tux3** [comment]
Yeah, it's not that great. Maybe we should just vertically center the name/date
