### ISSUE TITLE
[wishlist] Retrieve own info from ToxMe

### ISSUE THREAD

**Issue by CristianCantoro** [qTox/qTox#5014]
##### Brief Description

OS: Ubuntu 16.04.4 LTS
qTox version: v1.14.0-1-gb0710213
Commit hash: b071021351c03dcdca3c7ede096b5ce55721e637
toxcore: 0.2.1
Qt: 5.5.1
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce
Always

##### Steps to reproduce

1. Open profile 
2.  See section "Register on ToxMe

##### Observed Behavior
It is only possible to register on ToxMe, what if I am already registered on ToxMe with my username?

##### Expected Behavior
I would like to be able to pull my info from ToxMe.

**Comment by tox-user** [comment]
Interesting idea. What kind of information would like to be able to get?

**Comment by CristianCantoro** [comment]
all the information that are on ToxMe, the point is that you can use qTox to update your ToxMe information. The scenario I have in mind is when you change computer, you may want to update your Tox ID on ToxMe.

**Comment by anthonybilinski** [comment]
Basically, have UI equivalent to https://toxme.io/edit_ui included inside qTox so that using your toxme password, you can update your record to point to a new ToxId, correct?

**Comment by CristianCantoro** [comment]
yes!

**Comment by anthonybilinski** [comment]
ToxMe support was removed from qTox as part of https://github.com/qTox/qTox/pull/5898 due to it going offline permanently https://github.com/qTox/qTox/issues/5897. Closing this issue as it's no longer relevant.
