### ISSUE TITLE
Is tools/buildPackages.sh supposed to work?

### ISSUE THREAD

**Issue by mcondarelli** [qTox/qTox#5019]
##### Brief Description
Debian package build fails.

OS: Linux (debian stretch)  
qTox version: (git)  

Reproducible: Always

##### Steps to reproduce

1. ./bootstrap.sh
Ok.
2. tools/buildPackages.sh 
...
qTox-master/windows/toolchain-x86_64-w64-mingw32.cmake
[ERROR] Unknown parameter "-t"
...

After removing the offending "-t" flag
I get:
2a. tools/buildPackages.sh 
…
debuild: fatal error at line 660:
cannot find readable debian/changelog anywhere!
Are you in the source code tree?
debuild: fatal error at line 660:
cannot find readable debian/changelog anywhere!
Are you in the source code tree?
File "./qtox_1.0-1*.deb" not found.
mv: cannot stat '*.deb': No such file or directory
mv: cannot stat '*.rpm': No such file or directory

Are these scripts supposed to be working?
What am I doing wrong?

Note: the locally compiled qTox works as expected.

**Comment by sudden6** [comment]
last meaningful edit was from 2014, seems to be very outdated. I'll remove it.
