### ISSUE TITLE
HTML in sent messages gets rendered to screen when reloading previous message in chatbox

### ISSUE THREAD

**Issue by Toj** [qTox/qTox#5020]
##### Brief Description

After sending a message containing HTML code and pressing the up arrow on the keyboard (to load the previous sent message again into the chatbox), the HTML code is stripped out, but it's effects are rendered to the new message assuming the entire message isn't stripped out.

Eg, if you send someone 'TEXT' that is styled with HTML, and press the up arrow in the chatbox to try and send it again, it will show 'TEXT' styled with whatever HTML was stripped out.

# [See this video](https://i.imgur.com/DpkNQlO.mp4)

##### Versions

OS: Affects both Linux & Windows on at least the latest qTox release
qTox version: 1.13, latest

##### Reproducible: 
Always

##### Expected Behavior
For the HTML code to not be stripped out or applied to the message; for it to simply load the previous sent message into the chatbox

**Comment by tox-user** [comment]
I can reproduce this on 1.14 as well.

**Comment by anthonybilinski** [comment]
This was merged as ebdc675cbc2dd0054306d461c382568c6148bf60.
