### ISSUE TITLE
In this version video doesn't work

### ISSUE THREAD

**Issue by Denis33** [qTox/qTox#5033]
##### Brief Description

OS: Windows 7 SP 1 (6.1)
qTox version: v1.13.0
Commit hash: 531defd0aa66af1b128f7293bc08718ce2cc064f
toxcore: 0.1.10
Qt: 5.9.3
Hardware: 
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. 
2. 
3. …

##### Additional Info
(links, images, etc go here)

----

More information on how to write good bug reports in the wiki: https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by Denis33** [comment]
В этой версии не работает видео звонок

**Comment by sudden6** [comment]
Please try to fill out the issue template. Also I don't understand Russian(?), ping @Diadlo

**Comment by HoraceBianchon** [comment]
Привет. Пожалуйста, напишите конректно, что не работает.
Посоветую использовать последнюю версию 1.14... там исправлены многие баги, среди них есть 
связанные со видеозванком.

Hi. Please write specifically that does not work.
I'll advise you to use the latest version 1.14 ... there are fixed many bugs, among them there are related to the video-call.

**Comment by Diadlo** [comment]
@sudden6 Title was updated

**Comment by sudden6** [comment]
@Diadlo thx

@Denis33 Version 1.13.0 is known to have video problems, try 1.14.1

**Comment by sudden6** [comment]
No response for several months, closing.
