### ISSUE TITLE
"Placeholder" UI elements appear on Settings>About page

### ISSUE THREAD

**Issue by Fare8545** [qTox/qTox#5040]
##### Brief Description
For the nightly qTox versions I've compiled on Fedora for the past few weeks at least (unsure if it affects other OS/stable versions or not), "Update text" and "Downloading update 0%" always appear on the About qTox page. (I don't even think Linux versions support auto updating, since you get them from packages or compile it yourself)
##### Version

OS: Linux (Fedora 27)
qTox version: qTox version v1.14.0-19-g0be49c64
Commit hash:  0be49c648c34a5708a23f67b19b8c5ef165ab97a (This is just the version I am on, but the commit isn't related to the issue)
Qt:  5.9.4

##### Additional Info
Image of what it shows (just above license info)
![Image](https://i.imgur.com/2SPOASF.png)

**Comment by tox-user** [comment]
This affects stable versions on GNU/Linux too. We don't have automatic updates anymore, so this should be removed.
