### ISSUE TITLE
Compilation error on MX Linux

### ISSUE THREAD

**Issue by tox-user** [qTox/qTox#5041]
Issue posted by TheOuterLinux on reddit
##### Brief Description

OS: MX Linux (Debian Stretch)  
qTox version: ?
Commit hash: ?
toxcore: downloaded by simple_make.sh
Hardware: Macbook Pro 2014
Camera is FaceTimeHD and I load it manually via "sudo modprobe facetimehd"
It comes from a combination of installing "isight-firmware-tools" and a kext file you have to grab from a MacOS system. The camera works fine in Cheese, guvcview, and hasciicam.
…

Reproducible: Always

##### Steps to reproduce

1. Run simple_make.sh

##### Observed Behavior
```
.../qTox/src/video/camerasource.cpp: In constructor ‘CameraSource::CameraSource()’:
.../qTox/src/video/camerasource.cpp:112:5: error: ‘void av_register_all()’ is deprecated [-Werror=deprecated-declarations]
     av_register_all();
     ^~~~~~~~~~~~~~~
In file included from /usr/local/include/libavdevice/avdevice.h:51:0,
                 from .../qTox/src/video/camerasource.cpp:22:
/usr/local/include/libavformat/avformat.h:2025:6: note: declared here
 void av_register_all(void);
      ^~~~~~~~~~~~~~~
.../qTox/src/video/camerasource.cpp:112:21: error: ‘void av_register_all()’ is deprecated [-Werror=deprecated-declarations]
     av_register_all();
                     ^
In file included from /usr/local/include/libavdevice/avdevice.h:51:0,
                 from .../qTox/src/video/camerasource.cpp:22:
/usr/local/include/libavformat/avformat.h:2025:6: note: declared here
 void av_register_all(void);
      ^~~~~~~~~~~~~~~
[ 24%] Building CXX object CMakeFiles/qtox_static.dir/src/video/groupnetcamview.cpp.o
[ 25%] Building CXX object CMakeFiles/qtox_static.dir/src/video/netcamview.cpp.o
[ 25%] Building CXX object CMakeFiles/qtox_static.dir/src/video/videoframe.cpp.o
cc1plus: all warnings being treated as errors
CMakeFiles/qtox_static.dir/build.make:1554: recipe for target 'CMakeFiles/qtox_static.dir/src/video/camerasource.cpp.o' failed
make[2]: *** [CMakeFiles/qtox_static.dir/src/video/camerasource.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:219: recipe for target 'CMakeFiles/qtox_static.dir/all' failed
make[1]: *** [CMakeFiles/qtox_static.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

##### Expected Behavior
Compile without error.

##### Additional Info
The Linux distro is technically called "MX Linux," but it is based on Debian Stretch. I have the neccessary isight and kext files installed/grabbed and can get Cheese, guvcview, and hasciicam working without issues. However, I would like to note that my ffmpeg absolutely hates trying to use my webcam (facetimehd; /dev/video0), with a frame rate of about 0.2 fps. I have compiled ffmpeg from source before, but to get it to work properly, I have to uninstall apt's ffmpeg which means I loose kdenlive and a few other programs. When I compile from source and try to reinstall those programs, the previously installed ffmpeg has to install anyway because apt doesn't detect the newer version. So, qTox needs to be able to use:
```
ffmpeg version 3.3.4-1mx17+1 Copyright (c) 2000-2017 the FFmpeg developers
built with gcc 6.3.0 (Debian 6.3.0-18) 20170516
```

**Comment by sudden6** [comment]
The ffmpeg project seems to have changed something, because `av_register_all()` is now deprecated. Unfortunately I couldn't find any info what's the replacement or how to use the newer API.

Since this is only a warning you can remove the line `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror")` to disable error on warnings and make it succeed.

**Comment by sudden6** [comment]
This is fixed on master since some time.
