### ISSUE TITLE
Anthony Bilinski 's GPG key is not listed in README.md

### ISSUE THREAD

**Issue by farseerfc** [qTox/qTox#5048]
The 1.14.1 release is signed by GPG key "Anthony Bilinski <me@abilinski.com>" with fingerprint:
```
pub   rsa4096 2017-09-18 [SC]
      7EB3 39FE 8817 47E7 01B7  D472 EBE3 6E66 A842 9B99
uid           [ unknown] Anthony Bilinski <me@abilinski.com>
sub   rsa4096 2017-09-18 [E]
sub   rsa4096 2018-01-19 [S]
```

But this key is not listed in [README.md](https://github.com/qTox/qTox/blob/1d86fa8813b020b152d849b4c39a837d5ab2c0e1/README.md) , instead a different key fingerprint is listed:
`74AD B7A7 F8EC C100 9916  C4E4 2AA8 E0DA 1B31 FB3C      - Anthony Bilinski`

Please comform the key fingerprint by listing it in the README.md

**Comment by anthonybilinski** [comment]
Hi @farseerfc, I just pulled the release off github and see:
```
$ gpg2 -v --verify --with-fingerprint v1.14.1.tar.lz.asc v1.14.1.tar.lz
gpg: armor header: Version: GnuPG v1
gpg: Signature made Wed 21 Mar 2018 03:21:38 PM PDT
gpg:                using RSA key 2AA8E0DA1B31FB3C
gpg: using subkey 2AA8E0DA1B31FB3C instead of primary key EBE36E66A8429B99
gpg: using pgp trust model
gpg: Good signature from "Anthony Bilinski <me@abilinski.com>" [ultimate]
Primary key fingerprint: 7EB3 39FE 8817 47E7 01B7  D472 EBE3 6E66 A842 9B99
     Subkey fingerprint: 74AD B7A7 F8EC C100 9916  C4E4 2AA8 E0DA 1B31 FB3C
gpg: binary signature, digest algorithm SHA1, key algorithm rsa4096
```
as you can see, that subkey matched. I think the issue is just that by default gpg is only showing my primary key's fingerprint, but my subkey's fingerprint is that in the readme file, and the subkey was used to sign the release.

**Comment by farseerfc** [comment]
Thanks, I didn't notice it was a subkey. To make it more clear, I think it will be helpful to list all signing keys including the subkey fingerprints in the README.md file.
I will close this issue for now.

**Comment by anthonybilinski** [comment]
The subkey is the signing key used, and its fingerprint is listed in the readme, so "it will be helpful to list all signing keys including the subkey fingerprints in the README.md file" is already done. I don't think any changes are needed. I don't think including my master key's fingerprint when it's not used directly makes sense.

All that was needed is when listing my fingerprints, to add `--with-subkey-fingerprint` so that the subkey fingerprint is shown for your third line of `sub   rsa4096 2018-01-19 [S]`

**Comment by anthonybilinski** [comment]
Doing some research, it looks my understanding of subkeys and fingerprints was wrong. It looks like the master key fingerprint should be what is publicized, even if only the subkey is going to be used. I'll update the readme, but would like some input with people more familiar with GPG :D
