### ISSUE TITLE
libtoxcore.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by JoshuaPettus** [qTox/qTox#5073]
##### Brief Description

OS: Linux Ubuntu Mate 17.10
qTox version: 1.14.1+
Commit hash:  
toxcore:  2.1

Reproducible: Always

##### Steps to reproduce

1.  Build and install toxcore 2.1
2.  Build and install qTox 1.14.1
3.  Run qTox

##### Observed Behavior

qTox successfully compiles and installs on Ubuntu mate.  Cmake detects the toxcore library at compile and successfully builds off of it, but then at runtime qTox says it can not find it...  the library itself installed in the normal location /usr/local/lib/ so nothing special there

Full error is as follows:
"qtox: error while loading shared libraries: libtoxcore.so.2: cannot open shared object file: No such file or directory"

**Comment by Diadlo** [comment]
1. Check if `libtoxcore.so.2` exists in `/usr/local/lib`
2. If it exists, as temporary you can try `LD_LIBRARY_PATH="/usr/local/lib" ./qtox`
3. If it helps, read [this](https://ubuntuforums.org/showthread.php?t=420008)

Does it help?

**Comment by JoshuaPettus** [comment]
Thank-you so much! That did it and very good to know for the future.  I am still scratching my head as to why I didn't hit this issue before with the previous versions of qtox and toxcore...maybe I figured a way around it and forgot..

**Comment by sudden6** [comment]
@JoshuaPettus close this then?
