### ISSUE TITLE
Is untagged-fff6ac19f1972e461878 the latest release?

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#5087]
Github shows that it is.

There is a way somewhere to say that the tag isn't a release.

**Comment by Diadlo** [comment]
@yurivict As `untagged` name says, this is not tag, but release :)
AFAIK It's temorary solution to test windows builds. @sudden6  Am I right?

**Comment by sudden6** [comment]
It was an accident while rebasing #5083 I'll delete them

**Comment by anthonybilinski** [comment]
Tags are now gone and no longer show up under github releases.
