### ISSUE TITLE
Text in the settings is clipped/squished vertically when the window is too small

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#509]
Screenshot:
![pic13](https://cloud.githubusercontent.com/assets/5155966/4756573/7c6c574c-5ace-11e4-8826-b2eb71b6be5d.jpg)

The minimum size should be higher, but maybe we should move some options to other tabs.
It's probably better to have a tab with few options, than the main tab being completely unreadable. After all we already have an empty tab (privacy).

**Comment by agilob** [comment]
https://github.com/tux3/qTox/pull/475 fixed here, check commits

> After all we already have an empty tab (privacy).

https://github.com/tux3/qTox/pull/423 this PR fills Privacy tab, logs, encryption, typing notifications, etc.

**Comment by tux3** [comment]
Whoops. Ok.
