### ISSUE TITLE
Some settings not being saved to qTox.ini

### ISSUE THREAD

**Issue by zl3ai** [qTox/qTox#5091]
##### Brief Description

OS: Windows 10 (10.0)
qTox version: v.1.14.1
Commit hash: fe552f28b63c7e7ae8159d2b55cb921dd45d9c1d
toxcore: 0.2.1
Qt: 5.9.3
Hardware: 
Acer laptop

Reproducible: Always

##### Steps to reproduce

1.  Tick 'Start in tray', 'Minimise to tray', 'Close to tray' on General Settings.
2.  Close qTox, then shut down computer.
3.  Turn on computer.

##### Observed Behavior

Notifications no longer work after restarting computer.

##### Expected Behavior

Notifications should work after restarting computer.

##### Additional Info

"Fixed" by manually editing qtox.ini so that autostartInTray, closeToTray and minimizeToTray are all 'true'. This suggests that some settings are not being saved correctly.

**Comment by sudden6** [comment]
Can you re-test with the current release?

**Comment by zl3ai** [comment]
OK thanks, I downloaded and installed the latest release and it now works properly.

**Comment by sudden6** [comment]
closing then :)
