### ISSUE TITLE
[BUG] Theme color can't be changed

### ISSUE THREAD

**Issue by MonaMoonlight** [qTox/qTox#5092]
##### Brief Description

OS: Pop!_OS 17.10 (Artful Aardvark)
qTox version: v1.15.0
Commit hash: 02d6c63acaac0ae95fa8be3a1b9301657e6a4a94
toxcore: 0.2.2
Qt: 5.9.1
Hardware: MBP 2010
…

Reproducible: Always

##### Steps to reproduce

1. Select a color scheme other than default for the Theme in Settings.

##### Observed Behavior

Theme color does not change on any setting, but remains on the default color scheme.

##### Expected Behavior

Theme colour should change from default to Blue, Olive, Red or Violet when their respective setting is chosen.

##### Additional Info

Previous version (1.14.1) did not have this issue.

**Comment by anthonybilinski** [comment]
Almost definitely related to https://github.com/qTox/qTox/pull/5081. Crap. I thought I tested it :'(

EDIT: Just tested again off tip and it's working fine for me on Ubuntu 16.04.

**Comment by anthonybilinski** [comment]
Checking now it looks like the three things effected by theme colour are: self status button, friend list, and settings buttons bottom left.

v1.15.0 behaviour is that only the friends list colour changes when theme colour is changed. All three are set to the theme colour that's set when qTox is opened.

@MonaMoonlight is this the same as you see?

**Comment by MonaMoonlight** [comment]
>Checking now it looks like the three things effected by theme colour are: self status button, friend list, and settings buttons bottom left.
>
> v1.15.0 behaviour is that only the friends list colour changes when theme colour is changed. All three are set to the theme colour that's set when qTox is opened.
>
> @MonaMoonlight is this the same as you see?

@anthonybilinski Oh heck.
Yeah, the friends list does change color, but _not_ the status button or the settings buttons.
