### ISSUE TITLE
Video Preview Problem on Debian 32bit

### ISSUE THREAD

**Issue by ElLamparto** [qTox/qTox#5097]
qTox v1.15.0.
Commit hash: 02d6c63acaac0ae95fa8be3a1b9301657e6a4a94
toxcore: 0.2.2
Qt: 5.7.1

After starting qTox / AV settings, the selected webcam is ok, but there is no picture.

[18:52:54.846 UTC] video/camerasource.cpp:267 : Debug: Opening device  "none"
[18:52:54.846 UTC] video/cameradevice.cpp:152 : Debug: Tried to open the null device
[18:52:54.846 UTC] video/camerasource.cpp:280 : Warning: Failed to open device!

Workaround: Set video source to None, then reselect the webcam. The picture appears ok.

**Comment by sudden6** [comment]
Can you try backing up and then deleting the `.config/tox/` folder? Does this happen on 64bit debian too?

**Comment by ElLamparto** [comment]
I have no Debian 64bit, unfortunately. But the same problem exists on Win7 32bit.

*** Deleting config and creation of a new profile doesn't fix anything.***

After startup a good video source is selected, but no video.
After selecting None and then the webcam, picture appears.

One more thing:
In versions prior to 1.15.0, I had a combo box with resolutions 120/240/480. 
In the 1.15.0 the only resolution available is 120p. On both: Windows and Linux.

**Comment by anthonybilinski** [comment]
I can repro the issue on Ubuntu 18.04. Setting the webcam and switching away and back to the AV settings page is fine, but leaving the webcam selected then closing and re-opening qTox has the webcam remain selected in AV settings, but the preview not start until it's de-selected and re-selected.

>One more thing

That's definitely from https://github.com/qTox/qTox/pull/5075 which changed selection criteria of which resolutions are displayed. I'll work on a quick fix for that now.

**Comment by ElLamparto** [comment]
It seems to work correctly now (v1.16.3-47-ge22a22d0)
