### ISSUE TITLE
unable to load encrypted database after restart

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#510]
@apprb 
1. remove databases from .config/tox/
2. start qtox
3. enable 'Encrypt log'
4. set password
5. "conversation" with groupbot
6. restart
7. provide correct or incorrect password
8. ./qtox

```
built on:  18:26:26 Oct 23 2014
commit:  f1601f389fc56c6ccabbf086c8c8f9e6ad814285 

Settings: Loading from  "/home/agilob/.config/tox/settings.ini"
Using embeded bootstrap nodes list
Error loading translation "en"
Core: loading Tox from "/home/agilob/.config/tox/agilob.tox"
Core starting with IPv6 enabled
Core::loadConfiguration: reading from  "/home/agilob/.config/tox/agilob.tox"
(QSize(160, 120) ,  QSize(320, 240) ,  QSize(640, 480) ,  QSize(352, 288) )
Settings: Saving in  "/home/agilob/.config/tox/settings.ini"
Core: writing tox_save to  "/home/agilob/.config/tox/agilob.tox"
Settings: Saving in  "/home/agilob/.config/tox/settings.ini"
Core: writing tox_save to  "/home/agilob/.config/tox/agilob.tox"
Settings: Saving in  "/home/agilob/.config/tox/settings.ini"
------------------------------------------------------------
```

No error.

File isn't empty.

```
~/.config/tox » ls -l
total 224

-rw-rw-r-- 1 agilob agilob 18977 Oct 23 18:32 agilob.qtox_history.encrypted
-rw------- 1 agilob agilob 38283 Oct 23 18:32 agilob.tox
```

Database is encrypted.

```
~/.config/tox » sqlite3 agilob.qtox_history.encrypted
SQLite version 3.8.7 2014-10-17 11:24:17
Enter ".help" for usage hints.
sqlite> .schema
Error: file is encrypted or is not a database
```

**Comment by dubslow** [comment]
Still needs some major fixes, see PR

**Comment by tux3** [comment]
Encryption is now disabled for the moment.

**Comment by agilob** [comment]
@tux3 i still can tick 'encrypt history', you disabled 'encrypt tox datafile' only ;)

**Comment by tux3** [comment]
@agilob weird, I did disable both but somehow it only works on 'encrypt tox datafile' :/

Whatever, I made the checkbox non-checkable. That should do it.

**Comment by apprb** [comment]
Can't get you idea, sorry.

If you mean that qtox can't load encrypted history after restart it is definitely a bug.
If it is about sqlite cli and encrypted history file this is normal behavior. sqlite3 can't open encrypted history file, not only because it encrypted, but also because it have completely different format to normal sqlite database.

**Comment by agilob** [comment]
> If you mean that qtox can't load encrypted history after restart it is definitely a bug.

this

**Comment by apprb** [comment]
> remove databases from .config/tox/

*.qtox_history.encrypted file only?

> provide correct or incorrect password

In the case of incorrect password qtox just accept this password?

Will try to reproduce after back home.

**Comment by agilob** [comment]
> *.qtox_history.encrypted file only?

and `agilob.qtox_history`

It doesn't matter if I provide correct or incorrect password, qTox quits after pressing enter in password filed.

**Comment by tux3** [comment]
> qTox quits after pressing enter in password filed.

It crashes ? Even with the latest version ?
If so, can you get a backtrace ?

**Comment by dubslow** [comment]
Before anyone goes any further about encryption, please apply https://github.com/dubslow/qTox/commits/history and report back on if/how it works/doesn't work.

@tux3 @apprb @agilob

**Comment by agilob** [comment]
@tux3 @dubslow  https://gist.github.com/agilob/e64dcd2f5e89af10493e
As I said, no error :p 

@apprb do you wan't me to try to fix it **for me** and send you patch (next week)?

**Comment by apprb** [comment]
@agilob tomorrow (probably today) I'll prepare branch with detailed debug info in order to understand what exactly works in a wrong way for you.

**Comment by apprb** [comment]
@agilob, can you try this: apprb@2e4dd46 paste debug log somewhere?

**Comment by agilob** [comment]
```
Core starting with IPv6 enabled
Core::loadConfiguration: reading from  "/home/agilob/.config/tox/agilob.tox"
-- HistoryKeeper::checkPassword()
-- HistoryKeeper::checkPassword(): logging enabled
-- HistoryKeeper::checkPassword(): encryption enabled
-- EncryptedDb::check: "/home/agilob/.config/tox/agilob.qtox_history.encrypted"
Settings: Saving in  "/home/agilob/.config/tox/settings.ini"
Core: writing tox_save to  "/home/agilob/.config/tox/agilob.tox"
Settings: Saving in  "/home/agilob/.config/tox/settings.ini"
Core: writing tox_save to  "/home/agilob/.config/tox/agilob.tox"
Settings: Saving in  "/home/agilob/.config/tox/settings.ini"
------------------------------------------------------------
~/qTox(branch:encr_tst) » 
```

https://gist.github.com/agilob/9bd86bb15ac9bf85b1e9

**Comment by apprb** [comment]
Probably notifications from gist doesn't work.

> To make it clear. Am I understand correctly. Right after entering correct password to encrypted history qTox closes by itself?
> And in the case of unencrypted history everything is OK?

I updated that branch. Now it prints more debug info around password check.
And as for now I don't any clue about why it doesn't work.

**Comment by agilob** [comment]
I'll try to fix it for me after 10th.

**Comment by agilob** [comment]
omg, I just spent 3h trying to find problem... ok, I have not bt, there's nothing left after the crash... I wasn't able to find breakpoints before the crash... I messed with the code leaving a lot of qDebug messages... here's "[a patch](https://gist.github.com/agilob/ca5f995b845c44e9d08f)".
What is worth noticing... Thanks to multithreading each time I run qTox, there are different qDebug messages and their order is different!

What I think might be related is libsqlite version(?), [in 3.7.17 there were thousands of micro-optimisations](http://permalink.gmane.org/gmane.comp.db.sqlite.general/90549), could you check your versions?

```
sqlite3 -version
3.8.7.1 2014-10-29 13:59:56 3b7b72c4685aa5cf5e675c2c47ebec10d9704221
$ pacman -Q | grep sqlite
lib32-sqlite 3.8.7.1-1
sqlite 3.8.7.1-1
```

**Comment by tux3** [comment]
I have sqlite 3.8.7-1 and it works for me

<blockquote><pre>
root@laptop:~# apt-cache show libsqlite3-0 | head -n 3
Package: libsqlite3-0
Source: sqlite3
Version: 3.8.7-1
root@laptop:~# apt-cache show libqt5sql5-sqlite | head -n 3
Package: libqt5sql5-sqlite
Source: qtbase-opensource-src (5.3.2+dfsg-4)
Version: 5.3.2+dfsg-4+b1
</pre></blockquote>

**Comment by apprb** [comment]
I have the same version.

```
$ yaourt -Qi sqlite | grep Version
Version        : 3.8.7.1-1
$ sqlite3 -version
3.8.7.1 2014-10-29 13:59:56 3b7b72c4685aa5cf5e675c2c47ebec10d9704221
```

I have an idea, could you send me your compiled binary, and I try it under my environment. Probably it'll reveal something.

**Comment by agilob** [comment]
@apprb  http://agilob.net/qtox

Dynamically linked, if you want staticly, tell me how to build it.

**Comment by apprb** [comment]
Your binary works pretty well on my laptop.
Try to apply [this patch](https://gist.github.com/apprb/ca6bc3dca98aebf3f717) and try to run qTox with encrypted db. All messages will be just stored in encrypted file without actual inserting it in the sqlite table (to test is the problem in sqlite)

**Comment by agilob** [comment]
still the same problem https://gist.github.com/agilob/91ac3d3a670825af5901

I removed history databases and created them again with qTox, then I tried to run it with encrypted logs: https://gist.github.com/agilob/0b39cf65b0076c7b97fd

**Comment by apprb** [comment]
Add me:

```
FF2AD0FF4D2EE8BAFC8A5319BDEF782F0107E93579CEB3EC50BCF4D40928402D972EFA9A42DB
```

It can help to find the problem faster :)

**Comment by dubslow** [comment]
Fixed in encryption branch, which AFAICT is ready for merging, save for it crashes horribly on @zetok's (and only zetok's) system...
