### ISSUE TITLE
Single mechanism for changing the version of the product

### ISSUE THREAD

**Issue by hkarel** [qTox/qTox#5100]
In the commit 3c15cd2b10dc084416ead98eb9c270578642d436 the product version was updated to 1.15.0. But this change did not affect all platforms. Those who build the project using CMAKE still see version 1.14.0. 
Maybe it makes sense to work out a single mechanism for changing the product version for all platforms? For example, uniform VERSION file.

**Comment by Diadlo** [comment]
@hkarel Probably you need to fetch tags to get latest version. Try `git fetch --tags`

**Comment by hkarel** [comment]
> @hkarel Probably you need to fetch tags to get latest version. Try git fetch --tags

Yes, that's right, my jamb. It was necessary to update the tags. 
And if it's not difficult for developers to change the version number in different places, then probably everything should be left as it is now...

**Comment by sudden6** [comment]
There's a script to update all the version numbers and it's part of the release steps in MAINTAINING.md so I think we should be good :)

**Comment by hkarel** [comment]
Ok, then there's nothing to worry about :)
