### ISSUE TITLE
Wrong name marked in green in group header

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5116]
##### Brief Description

OS: Ubuntu 16.04
qTox version: v1.14.1+
Commit hash:  498c04ba50e91ff183b593ec3cebe381bde215a4
toxcore:  v0.2.2
Qt:  5.5.1

Reproducible: Always

##### Steps to reproduce

1. Join "Tox Public Chat" group through toxync

##### Observed Behavior
Wrong name is highlighted in green (not my own):
![image](https://user-images.githubusercontent.com/10469203/39546808-7bd42e62-4e0a-11e8-8dad-557553a408d8.png)

##### Expected Behavior
Mark my own name in green.

I think the issue is that Group::regeneratePeerList iterates over peers in the group by peer number, but then inserts those peers into a map of <pub key, name>, then when this is handed to GroupChatForm::updateUserNames, it's given a list of all of the names in the map (from .values()) and iterates over them with the assumption that peerNumber == index. This is no longer true, because the list GroupChatForm::updateUserNames is using is just in whatever order the map stored it in, not sorted by peer number.

**Comment by anthonybilinski** [comment]
ping @sudden6 probably from 498c04ba50e91ff183b593ec3cebe381bde215a4

**Comment by sudden6** [comment]
Can confirm this is caused by my commit.

**Comment by tox-user** [comment]
Peer's public keys don't match their user names. Perhaps some list is sorted in a wrong way.

**Comment by sudden6** [comment]
@tox-user yes that's the case, I'm already working on a fix, but it's a bit complex.
