### ISSUE TITLE
Abnormal disk usage when using history

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#512]
Upon receiving a lot of messages qTox hangs while doing a lot of tiny writes, instead of dumping on disk chunks of data

**Comment by dubslow** [comment]
Encrypted or not?

**Comment by agilob** [comment]
encrypted, takes more CPU than firefox, X, kde-plasma and skype together.

**Comment by dubslow** [comment]
Yeah... the encryption in use is slow as balls currently, it probably shouldn't have been merged... see the PR comment...

**Comment by tux3** [comment]
Encryption is now disabled for the moment.

**Comment by zetok** [comment]
I didn't use encryption

**Comment by tux3** [comment]
I profiled but I can't find anything blatantly wrong with the history (and I have a really slow hard drive!). Most of the CPU time was spent on networking encryption and HTML rendering.
I'll try again with more smaller messages later.

**Comment by zetok** [comment]
So I've launched qTox after emerging newest version.

It took quite a long time, so while it was launching I managed to emerge iotop (if you don't know what I'm aiming at, Portage is **really slow** when it comes to emerging packages, especially when used with HDD and btrfs..). Unfortunately I forgot to compile kernel with an option required by iotop to work, so no real statistics.

When qTox has been launching, there were some disk reads, but what was surprising is that there was quite a lot of writes. Worst thing is that it was (I think) made up mostly of small reads/writes, which basically made speed to be ~600 KB/s on a HDD. That was DB update, right?

Also FYI, when it comes to btrfs, invoking a lot of "sync" really handicaps performance. I don't really see any better explanation for observed behaviour, so either code does something in really bad way, or you shouldn't invoke "sync" almost at all.

After all it took <~10 min to launch qTox

**Comment by tux3** [comment]
> After all it took <~10 min to launch qTox

That's obviously not okay, not even close, but if it takes THAT long, something is probably going on.

Try putting qTox in /dev/shm, enable "Make qTox portable" and try again. If it still takes 10 minutes from a RAM disk, then it's something else.

**Comment by apprb** [comment]
Most likely it is DB update (filling up sent_status table).
Good news: it is one time process.
But anyway I'll rewrite this part this evening.

**Comment by tux3** [comment]
> Most likely it is DB update (filling up sent_status table).

I can confirm that after running it through a debugger.
