### ISSUE TITLE
crash due to musl-libc's small stacksize

### ISSUE THREAD

**Issue by xhebox** [qTox/qTox#5127]
##### Brief Description

OS: Linux(with musl-libc)
qTox version: v0.1-14-g7b34dc99  
Reproducible: Sometimes

##### Steps to reproduce

1. get a musl-libc distro and install qtox(alpine maybe)
2. adding enough friends etc... let the profile to be bigger and bigger, or it wont crash(i've ran qtox with musl for a long time. it was long after my daily use of qtox.)

##### Observed Behavior
Crashed without any reason(no null pointer, no memory corruption) at `DHT_save (dht=0x7fffd9a5c020, data=0x3ccacfc "") at c-toxcore-0.2.2/toxcore/DHT.c:2811
`
#### A working hot-fix patch & problems

```
--- qTox-1.15.0/src/persistence/profile.cpp     2018-04-20 04:50:47.000000000 +0800
+++ qTox-1.15.0/src/persistence/profile.cpp     2018-04-20 04:50:47.000000000 +0800
@@ -62,6 +62,7 @@
 
     coreThread = new QThread();
     coreThread->setObjectName("qTox Core");
+    coreThread->setStackSize(524288);
     core = new Core(coreThread, *this, &Settings::getInstance());
     QObject::connect(core, &Core::idSet, this,
                      [this, password](const ToxId& id) { loadDatabase(id, password); },
```

1. This patch worked well with musl, but no good with glibc. Glibc has a stack of 8M, much bigger than the value 512K. Maybe using `StackSize()` to detect the original size, if it's too small(80K like musl, or 128K), set 512K for them. 512K is the size i set for blender(that 3D software), so this should be a reasonably enough size.

2. Also, i am not sure if you agree to patch this for a specific libc, if not, just close the issue.

**Comment by sudden6** [comment]
The problem with exhausting the stack seems to be in https://github.com/TokTok/c-toxcore/blob/master/toxcore/DHT.c#L2810 if the backtrace is valid and happens always at the same position. So there are two things to do here:

1. Notify the people in the c-toxcore repository that this is a problem and fix it at the root (I couldn't find an obvious issue at the moment)

2. Implement a workaround for qTox. IMO since this is a tiny patch it would be justified to enable it conditionally with macros to detect musl.

**Comment by xhebox** [comment]
There's nothing logically wrong with c-toxcore :). The stack is too small and qtox trigger the segfault. if you say root cause, that's musl-libc, which sets a 80K stacksize limit for all application by default.

I will issue this to toxcore later. We should have a discussion to estimate the general stack cost by toxcore.

**Comment by sudden6** [comment]
In my opinion c-toxcore shouldn't need that much stack, it's probably just an oversight somewhere.

**Comment by xhebox** [comment]
Emm, that's not sure. This should not be decided by 'in my opinion' but an acute statistic of stack size(both stack size of qtox & a simple app like a bot). As if it's an oversight, it must be a really secret one, and it's hard to find out. Of course, it could not be better if you find it. And it's also possible that not toxcore used too much stack, but qtox.

 I do not know how to track down the stack usage exactly. I am waiting for a reply.

**Comment by anthonybilinski** [comment]
Fixed in https://github.com/TokTok/c-toxcore/issues/886, thanks for the report and followup, xhebox.
