### ISSUE TITLE
Can't send messages after joining a persistent group

### ISSUE THREAD

**Issue by tox-user** [qTox/qTox#5129]
##### Brief Description

OS: Debian
qTox version: 1.15
Commit hash:  48179b6a19807383e298661a21f97db3b140eb44
toxcore:  0.2.2 with persistent groups
…

Reproducible: Sometimes / Rarely

##### Steps to reproduce

1. Join a group
2. Try to send a message

##### Observed Behavior
1. You can't see the other peer
2. You can receive messages, but yours are not being sent
3. There is no "Message failed to send" error
4. After a minute you can see the other peer and can send messages - everything starts working

I don't think I have ever seen it happen without persistent groups, but it's possible it happens with regular ones as well. I reproduced it on LAN too, so it can't be anything wrong with my internet connection.

##### Expected Behavior
User is always able to send messages and see other peers.

```
core/core.cpp:536 : Debug: "AV group invite by 0"
audio/backend/openal.cpp:341 : Debug: Opening audio output "Built-in Audio Analog Stereo"
audio/backend/openal.cpp:353 : Debug: Opened audio output "Built-in Audio Analog Stereo"
core/core.cpp:1265 : Debug: "Trying to join AV groupchat invite sent by friend 0"
core/core.cpp:568 : Debug: "Group 0 peerlist changed"
widget/widget.cpp:1750 : Debug: onGroupNamelistChanged: Group  0  not found, creating it
core/coreav.cpp:608 : Debug: "Leaving group call 0"
core/coreav.cpp:608 : Debug: "Leaving group call 0"
core/core.cpp:568 : Debug: "Group 0 peerlist changed"
```

The last log message is when everything started working.

**Comment by sudden6** [comment]
This seems to not happen anymore on master
