### ISSUE TITLE
with qtox 1.15 on kubuntu 18.04 I hear my voice in the speakers

### ISSUE THREAD

**Issue by DoctorSubtilis** [qTox/qTox#5131]
##### Brief Description

OS: Linux Kubuntu 18.04
qTox version: 1.15.0-29-g3751cf71  
Commit hash:  3751cf7176225701e05b8129396f91b8a8b92b50
toxcore:  0.1.2
Qt: 5.9.5 
Hardware:  Card Intel 200 Series PCH HD Audio driver: snd_hda_intel
           Sound: Advanced Linux Sound Architecture v: k4.15.0-20-generic

…

Reproducible: Always

##### Steps to reproduce

1. start a call
2. When i speak, I hear my voice in the speakers
3. The person with I speak don't hear nothing

##### Additional Info
in settings -> audio-video I see the "volume" blue bar moving with the sound (of clementine e.g.)

----

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA%\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.
[qtox.log](https://github.com/qTox/qTox/files/1989183/qtox.log)

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by tox-user** [comment]
Does this happen in group chat or in a normal call between two people?

**Comment by DoctorSubtilis** [comment]
Between two people, but today this problem is not occurred. This evening I will do new attempts. Thank you.

**Comment by DoctorSubtilis** [comment]
Between two people, but today this problem is not occurred. This evening I will do new attempts. Thank you.

**Comment by DoctorSubtilis** [comment]
This evening I don't hear my voice on speakers, the other person hear my voice well, but her voice is irregularly discontinuous (I hear 1 word and not 3).

**Comment by tox-user** [comment]
Can you update toxcore and try again? 0.1.2 is a very old version. The other person should update too if they are using the same version.

**Comment by DoctorSubtilis** [comment]
I have already recently updated qtox _with toxcore_, following [this instructions](https://askubuntu.com/questions/951031/how-can-i-install-qtox-on-kubuntu-17-04): not correct?

**Comment by DoctorSubtilis** [comment]
Done, with this new compiling settings:
"git clone https://github.com/toktok/c-toxcore.git toxcore
cd toxcore
**git checkout v0.2.2**
autoreconf -if
./configure
make -j$(nproc)
sudo make install
echo '/usr/local/lib/' | sudo tee -a /etc/ld.so.conf.d/locallib.conf
sudo ldconfig"

But I cannot update toxcore of the other person :(

**Comment by DoctorSubtilis** [comment]
There is another issue: the webcam led is always illuminated, not only during a call: once it was not like that; why?

**Comment by tox-user** [comment]
>I have already recently updated qtox with toxcore, following this instructions: not correct?

I don't know for sure. You can run simple_make.sh script which will install toxcore and qTox for you.

What version of toxcore you are running right now? Does using the new version fix the issue? If it doesn't, give us a log from when this problem occurs.

**Comment by DoctorSubtilis** [comment]
Now the 0.2.2 one, but the problem recently is solved! Thank you
