### ISSUE TITLE
the 64-bit Windows Installer recognised as malware by Avira Free Antivirus

### ISSUE THREAD

**Issue by jimitree** [qTox/qTox#5132]
Wanted to execute the 64-bit Windows installer file on my Windows 7 Professional but the Avira Free Antivirus denies the access to the installer file and moves it to the quarantine. Avira reports "HEUR/APC", which is described as "A generic detection routine designed to detect common family characteristics shared in several variants. This special detection routine was developed in order to detect unknown variants and will be enhanced continuously." (https://www.avira.com/en/support-threats-summary-product?tid=26757&threat=HEUR%252FAPC&track=1)

**Comment by ilovelinux** [comment]
I think it's a false positive:
https://github.com/qTox/qTox/wiki/Problematic-antiviruses
https://github.com/qTox/qTox/issues?q=virus

**Comment by tox-user** [comment]
>https://github.com/qTox/qTox/wiki/Problematic-antiviruses

There is a lot of them :D

**Comment by tox-user** [comment]
@jimitree have you tried to contact Avira?

**Comment by sudden6** [comment]
no reaction, closing
