### ISSUE TITLE
the webcam led is always illuminated

### ISSUE THREAD

**Issue by DoctorSubtilis** [qTox/qTox#5135]
##### Brief Description

OS: Kubuntu 18.04
qTox version: 1.15.0-29-g3751cf71.
Commit hash:  3751cf7176225701e05b8129396f91b8a8b92b50
toxcore:  0.2.2
Qt:  Qt version: 5.9.5
Hardware:  CPU:       Dual core Intel Core i3-7100 (-MCP-) cache: 3072 KB
           clock speeds: max: 3900 MHz 1: 800 MHz 2: 800 MHz

…

Reproducible: Always

##### Steps to reproduce

1. activate qtox
2. the webcam led is always illuminated, not only during a call

##### Observed Behavior
the webcam led is always illuminated, not only during a call

##### Expected Behavior
the webcam led is illuminated only during a call

##### Additional Info
(links, images, etc go here)

----

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA%\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by DoctorSubtilis** [comment]
After a reboot the problem seems solved!
EDIT
_After a call the led remain illuminated_. So closed and reopened: no led. But I believe that is a bug.

**Comment by sudden6** [comment]
Please attach a log form where this happens.

**Comment by stikonas** [comment]
Is it not related to https://github.com/qTox/qTox/pull/5121 ?

**Comment by DoctorSubtilis** [comment]
Here: [qtox.log](https://github.com/qTox/qTox/files/1996632/qtox.log)

**Comment by sudden6** [comment]
@stikonas I want to make sure it is.

Hmm, according to the log, the webcam should be off after the last message. Definitely needs an investigation.

**Comment by DoctorSubtilis** [comment]
I confirm the bug: the LED remains illuminated even after the end of a call; or sometimes the webcam is not completely recognized. In short: either always or never.

**Comment by sudden6** [comment]
This is probably not an issue anymore, if it still is, please open a new issue.
