### ISSUE TITLE
Full screen broken on Wayland

### ISSUE THREAD

**Issue by stikonas** [qTox/qTox#5136]
##### Brief Description

OS: Gentoo GNU/Linux  
Commit hash:  d6df8883e399b95a55c5a5870497c1dcd45a3917
toxcore:  git master
Qt:  5.9.4
…

Reproducible: Always

##### Steps to reproduce

1. Click "Full Screen" on Plasma Wayland session

##### Observed Behavior
Video surface moves to another location but is not full screen 

##### Additional Info
Might be a bug in QtWayland? Since it works if qtox is started with
QT_QPA_PLATFORM=xcb qTox

**Comment by tox-user** [comment]
Do you have problems like that with other Qt applications on Wayland? Do you use multiple monitors? Does this problem in qTox happen only on Wayland?

**Comment by stikonas** [comment]
This only happens on Wayland, and in fact only as a native Wayland client (QT_QPA_PLATFORM=wayland), does not happen if qTox runs as X client via XWayland (QT_QPA_PLATFORM=xcb).

Right now I was testing with single monitor.

I'm a bit struggling to find other Qt applications that can turn fullscreen on and run as Wayland client. Vlc is still not ported... I tried krbf, it also fails to turn on full screen but in a different way (it opens another window which I guess is supposed to be full screen but is not).

I guess I'll report this bug to QtWayland.

**Comment by stikonas** [comment]
Actually there are already some bugs https://bugreports.qt.io/browse/QTCREATORBUG-20400?jql=text%20~%20%22Wayland%20full%20screen%22

Maybe I'll instead try to add some qDebugs to 
void GenericNetCamView::enterFullScreen()
and check if I can spot any differences with QT_QPA_PLATFORM= xcb or wayland

**Comment by tox-user** [comment]
Good idea. The problem must be with this code:
```
void GenericNetCamView::enterFullScreen()
{
    setWindowFlags(Qt::Window | Qt::CustomizeWindowHint | Qt::FramelessWindowHint);
    showFullScreen();
    enterFullScreenButton->hide();
    toggleMessagesButton->hide();

    const auto screenSize = QApplication::desktop()->screenGeometry(this);
    buttonPanel->setGeometry((screenSize.width() / 2) - buttonPanel->width() / 2,
            screenSize.height() - BTN_PANEL_HEIGHT - 25, BTN_PANEL_WIDTH, BTN_PANEL_HEIGHT);
    buttonPanel->show();
    buttonPanel->activateWindow();
    buttonPanel->raise();
}
```

**Comment by tox-user** [comment]
Try pressing `F11` to enable full screen mode in qTox and see if that works.

**Comment by stikonas** [comment]
Again, works only via XWayland. Nothing at all happens as wayland client.

Do you have a reference where the location in the code for F11 is? It might be easier to test this than making calls...

EDIT: found it in src/widget/widget.cpp

**Comment by stikonas** [comment]
Might be fixed in Qt 5.12:
https://bugreports.qt.io/browse/QTBUG-63748

**Comment by stikonas** [comment]
Actually `F11` already mostly works with Qt 5.11rc (Plasma toolbar is still on top of qTox window, but that's definitely not something qtox can do). Haven't tested the video widget yet.

**Comment by tox-user** [comment]
Good to know! If this is an issue with Qt we might need to provide a newer version with our appimage and flatpak. @sudden6 what do you think?

**Comment by stikonas** [comment]
Well, I would say just wait and upgrade Qt naturally. It's only on Wayland anyway.

**Comment by tox-user** [comment]
Wayland will soon be the default on Ubuntu.

**Comment by stikonas** [comment]
@tox-user Well, I was running Qt 5.11 Release Candidate with the following patch https://code.qt.io/cgit/qt/qtwayland.git/commit/?h=dev&id=c5ab40d2573fde27a14d7c05d8693966c65a400c
In any case you should wait until it is stable, hopefully it will happen before Ubuntu ships with Wayland.

**Comment by sudden6** [comment]
Upgrading the Qt version in the appimage is a good idea anyway. Shouldn't be too hard too.

**Comment by stikonas** [comment]
Just tried it on Qt 5.12 and it works. I guess I'll close this issue.
