### ISSUE TITLE
Make use of a normal Qt file chooser dialog

### ISSUE THREAD

**Issue by robschi** [qTox/qTox#5139]
To fix "https://github.com/flathub/flathub/pull/379#pullrequestreview-118545657", the usage of a normal Qt file chooser dialog is apparently needed to avoid the requirement for the "--filesystem=<permission>" flag in flatpak.

**Comment by sudden6** [comment]
I'm against this change, because the native dialog integrates much better with each platform. IMO we could look into making a compile/runtime switch for that and use it for the flatpaks, but for me it's not a high priority.

What do other people think?

**Comment by anthonybilinski** [comment]
I agree that the native dialogue is better, we had an issue https://github.com/qTox/qTox/issues/3494 that made us switch to native dialogues recently, and before that switch I had a friend comment on the weird ugly file picker (Qt) on Windows. If it's not too much trouble to use native dialogues for flatpacks I think that's preferred, but I'm not really aware of what that would require

**Comment by tox-user** [comment]
We should keep the native file picker. It never fails and is well integrated into the system.

**Comment by Diadlo** [comment]
@tox-user 
> It never fails

It's ~wrong)
See #3443 for the details

**Comment by tox-user** [comment]
True, but it says the problem was only with Nautilus and only on Arch Linux.

**Comment by tox-user** [comment]
When some other program fails it's not our fault.

**Comment by robschi** [comment]
For me personal "ugly" does not matter in this case, because you have to see the file picker only a small amount of time.
And if it is English instead of French, this sounds like a bug which should be reported at the proper places.

I don't know the policy at Flathub for using the "--filesystem=" flag, but in consideration of Sandboxing it does make sense to not use it, if it is not really required.

**Comment by robschi** [comment]
I don't know if this is a problem with the flatpak version of qTox, but I am not able to select a "Default directory to save files:" for "Autoaccept files" over the GUI?

![screen](https://user-images.githubusercontent.com/32980119/40808579-e3c64d00-6527-11e8-9796-6a78a86fe530.jpg)

**Comment by zetok** [comment]
>I don't know the policy at Flathub for using the "--filesystem=" flag, but in consideration of Sandboxing it does make sense to not use it, if it is not really required.

Apparently it is required by flathub to make things work. Rather than changing things in qTox, it sounds like flathub should be fixed to not cause problems over using native file picker.

Since everyone agrees that using shitty pile picker is a bad idea, this issue should be closed.

>I don't know if this is a problem with the flatpak version of qTox, but I am not able to select a "Default directory to save files:" for "Autoaccept files" over the GUI?

That would be a separate issue. Lets have separate issues for separate problems to ease tracking whether they're properly addressed.

**Comment by sudden6** [comment]
> Since everyone agrees that using shitty pile picker is a bad idea, this issue should be closed.

Closing then.
