### ISSUE TITLE
No way to resize nickname column in chat

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#514]
Sometime the nickname column is too small in chat, especially on high DPI displays.

**Comment by zetok** [comment]
Done in #2013, should be closed after PR will be merged.

**Comment by anthonybilinski** [comment]
If this is talking about the friend list column, it is currently resizable.
If it's talking about the author column in group chats, duplicate of https://github.com/qTox/qTox/issues/635.
Either way, closing.
