### ISSUE TITLE
Crash on sending or receiving a message

### ISSUE THREAD

**Issue by reyaz006** [qTox/qTox#5143]
I'm having this crash for several latest builds from what I remember. Happens mostly when I haven't communicated for a long time while qTox is running.

OS: Windows 8.1 x64 6.3.9600.2.0.0.256.4
qTox version: v1.14.0-47-g2cfdc7b
Commit hash:  2cfdc7b3cc48d5f8407a0914061b234e754a1c47
toxcore:  0.2.1
Qt:  5.9.4
Hardware:  4770k, 16GB RAM
…

Reproducible: Sometimes / Rarely

##### Steps to reproduce

1. Start qTox.
2. Leave it minimized.
3. Don't send or receive any messages for a long period (possibly >24h)
4. Send or receive a message.

##### Observed Behavior
qTox may crash and display a error window like [this one](https://i.imgur.com/9iUHGjj.png) (not like [that one](https://i.stack.imgur.com/R0PgU.png)).
While this error message is active, qTox appears responsive and I even can read the message. But it won't be saved in chat history, and can't be copied.

##### Expected Behavior
qTox should not crash.

##### Additional Info
While the error message doesn't contain any useful information, I've found Windows recorded a Report.wer file for it. Here is most useful information from it:

```
Sig[0].Name=Application Name
Sig[0].Value=qtox.exe
Sig[1].Name=Application Version
Sig[1].Value=0.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=00000000
Sig[3].Name=Fault Module Name
Sig[3].Value=Qt5Core.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=5.9.4.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=00000000
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=000000000009ca2b
```

A log from another crash says this:

```
Sig[3].Value=qtox.exe
Sig[6].Value=c0000005
Sig[7].Value=00000000000a5d02
```

Here is what it looks like qtox.log content recorded during the crash:
```
[00:14:30.569 UTC] core/core.cpp:402 : Debug: Disconnected from the DHT
[00:14:32.382 UTC] core/core.cpp:430 : Debug: "Connecting to ***:33445 (***)"
[00:14:32.382 UTC] core/core.cpp:430 : Debug: "Connecting to ***:2306 (***)"
[00:14:36.571 UTC] core/core.cpp:399 : Debug: Connected to the DHT
[00:14:36.585 UTC] persistence/profile.cpp:323 : Debug: Saving tox save to  "C:/Users/***/AppData/Roaming/tox\\tox_save.tox"
[00:14:36.587 UTC] persistence/profile.cpp:326 : Critical: Tox save file  "C:/Users/***/AppData/Roaming/tox\\tox_save.tox"  couldn't be opened
[00:34:48.196 UTC] core/corefile.cpp:285 : Debug: "Received empty avatar request 8:65536"
[01:18:38.571 UTC] core/core.cpp:402 : Debug: Disconnected from the DHT
[01:18:39.570 UTC] core/core.cpp:399 : Debug: Connected to the DHT
[01:18:39.571 UTC] persistence/profile.cpp:323 : Debug: Saving tox save to  "C:/Users/***/AppData/Roaming/tox\\tox_save.tox"
[01:59:38.570 UTC] core/core.cpp:402 : Debug: Disconnected from the DHT
[01:59:40.382 UTC] core/core.cpp:430 : Debug: "Connecting to ***:33445 (***)"
[01:59:40.382 UTC] core/core.cpp:430 : Debug: "Connecting to ***:33445 (***)"
[01:59:46.006 UTC] core/core.cpp:430 : Debug: "Connecting to ***:33445 (***)"
[01:59:46.006 UTC] core/core.cpp:439 : Debug: "Error bootstrapping from ***"
[01:59:46.006 UTC] core/core.cpp:443 : Debug: "Error adding TCP relay from ***"
[01:59:46.006 UTC] core/core.cpp:430 : Debug: "Connecting to ***:33445 (***)"
[01:59:46.570 UTC] core/core.cpp:399 : Debug: Connected to the DHT
[01:59:46.570 UTC] persistence/profile.cpp:323 : Debug: Saving tox save to  "C:/Users/***/AppData/Roaming/tox\\tox_save.tox"
[01:59:46.572 UTC] persistence/profile.cpp:326 : Critical: Tox save file  "C:/Users/***/AppData/Roaming/tox\\tox_save.tox"  couldn't be opened
[03:33:09.572 UTC] core/core.cpp:402 : Debug: Disconnected from the DHT
[03:33:10.571 UTC] core/core.cpp:399 : Debug: Connected to the DHT
[03:33:10.571 UTC] persistence/profile.cpp:323 : Debug: Saving tox save to  "C:/Users/***/AppData/Roaming/tox\\tox_save.tox"
[03:55:28.572 UTC] core/core.cpp:402 : Debug: Disconnected from the DHT
[03:55:29.573 UTC] core/core.cpp:399 : Debug: Connected to the DHT
[03:55:29.573 UTC] persistence/profile.cpp:323 : Debug: Saving tox save to  "C:/Users/***/AppData/Roaming/tox\\tox_save.tox"
[03:55:29.575 UTC] persistence/profile.cpp:326 : Critical: Tox save file  "C:/Users/***/AppData/Roaming/tox\\tox_save.tox"  couldn't be opened
[03:55:30.572 UTC] core/core.cpp:402 : Debug: Disconnected from the DHT
[03:55:31.572 UTC] core/core.cpp:399 : Debug: Connected to the DHT
[03:55:31.572 UTC] persistence/profile.cpp:323 : Debug: Saving tox save to  "C:/Users/***/AppData/Roaming/tox\\tox_save.tox"
[03:55:31.576 UTC] persistence/profile.cpp:326 : Critical: Tox save file  "C:/Users/***/AppData/Roaming/tox\\tox_save.tox"  couldn't be opened
[04:56:41.571 UTC] core/core.cpp:402 : Debug: Disconnected from the DHT
[04:56:42.571 UTC] core/core.cpp:399 : Debug: Connected to the DHT
[04:56:42.587 UTC] persistence/profile.cpp:323 : Debug: Saving tox save to  "C:/Users/***/AppData/Roaming/tox\\tox_save.tox"
[04:56:42.588 UTC] persistence/profile.cpp:326 : Critical: Tox save file  "C:/Users/***/AppData/Roaming/tox\\tox_save.tox"  couldn't be opened
[05:15:41.322 UTC] audio/backend/openal.cpp:341 : Debug: Opening audio output "*** (Realtek High Definition Audio)"
[05:15:41.327 UTC] audio/backend/openal.cpp:349 : Warning: Cannot open output audio device "*** (Realtek High Definition Audio)"
[05:15:47.259 UTC] audio/backend/openal.cpp:341 : Debug: Opening audio output "*** (Realtek High Definition Audio)"
[05:15:47.259 UTC] audio/backend/openal.cpp:349 : Warning: Cannot open output audio device "*** (Realtek High Definition Audio)"
[05:42:47.650 UTC] :0 : Warning: QObject::~QObject: Timers cannot be stopped from another thread
```

**Comment by tox-user** [comment]
Can you update qTox to the newest 1.15.0 and see if it still happens?

**Comment by reyaz006** [comment]
Will do.

The updater says there is no new version, by the way.

**Comment by tox-user** [comment]
The updated doesn't work anymore. You need to download it from https://tox.chat.

**Comment by reyaz006** [comment]
Happened again on 1.15.0. This time I got 5 messages and here is what I woke up to: 

![image](https://user-images.githubusercontent.com/6751344/40226889-a0272c82-5a95-11e8-805d-2467e50c6d5a.png)


The log didn't record anything during that time, and sadly there are no crash logs.

**Comment by tox-user** [comment]
This part looks suspicious:
```
persistence/profile.cpp:326 : Critical: Tox save file  "C:/Users/***/AppData/Roaming/tox\\tox_save.tox"  couldn't be opened
```

and maybe this - I'm not sure if it's normal:
```
audio/backend/openal.cpp:349 : Warning: Cannot open output audio device "*** (Realtek High Definition Audio)"
```

**Comment by reyaz006** [comment]
>This part looks suspicious

It also does this when exiting qTox, I don't see any side-effects though. Nothing else is locking the file of course.

>and maybe this - I'm not sure if it's normal

I've checked and the whole qtox.log file has only 2 of those lines with the interval ~6 minutes. If it was related to the crash, I think there would be more of them.

**Comment by reyaz006** [comment]
Happened again on trying to send a message now. This time the same window was followed by another error:

`unknown software exception (0x40000015) at 0x62b746be`

libwinpthread-1.dll was loaded at 0x62b70000, checked with ProcExp.

**Comment by tox-user** [comment]
It would probably help if you could give us a backtrace, but I don't know how to do that on Windows. @qTox/windows-team is there a simple way?

**Comment by sudden6** [comment]
You can get a windows build + debugger here: https://build.tox.chat/view/qtox/job/qTox-cmake-nightly_build_windows_x86-64_debug/

@tox-user for other build types take a look at build.tox.chat and filter by `qtox`

**Comment by reyaz006** [comment]
Another case of `unknown software exception (0x40000015) at 0x62b746be` happened today.

>You can get a windows build + debugger here: https://build.tox.chat/view/qtox/job/qTox-cmake-nightly_build_windows_x86-64_debug/

Do I just use this version instead of regular, then wait for the crash and there should be some debug log automatically created?

**Comment by sudden6** [comment]
@reyaz006 yes, just run `debug-automatic.bat` and wait for the crash. Btw, are you sure your system is 100% stable? ie no overclocking, no problematic antivirus and working power supply? Just asking because you seem to be the only person with this issue and I've had similar random crashes on an unstable system.

**Comment by reyaz006** [comment]
My system is up for 15 days already, there are no hardware issues from what I see, and there are no viruses nor anti-viruses installed. I'm noticing a rather strange behavior of some background applications while playing certain game with certain anti-cheat system embedded, though. I'm still not sure if it's the source of this issue.

**Comment by reyaz006** [comment]
Here goes:
(there are few Russian strings but there should be no problem with those)

> [12:46:48.533 UTC] core/core.cpp:402 : Debug: Disconnected from the DHT
> [12:46:49.532 UTC] core/core.cpp:399 : Debug: Connected to the DHT
> [12:46:49.532 UTC] persistence/profile.cpp:323 : Debug: Saving tox save to  "C:/Users/***/AppData/Roaming/tox\\tox_save.tox"
> [12:46:49.534 UTC] persistence/profile.cpp:326 : Critical: Tox save file  "C:/Users/***/AppData/Roaming/tox\\tox_save.tox"  couldn't be opened
> [17:08:14.104 UTC] audio/backend/openal.cpp:341 : Debug: Opening audio output "Колонки (Realtek High Definition Audio)"
> AL lib: (EE) MMDevApiLoad: Failed to create event: 1450
> AL lib: (EE) DSoundLoad: Failed to load dsound.dll
> [New Thread 14504.0x5eac]
> [17:08:14.130 UTC] audio/backend/openal.cpp:349 : Warning: Cannot open output audio device "Колонки (Realtek High Definition Audio)"
> [17:08:20.233 UTC] :0 : Warning: DirectWrite: CreateFontFaceFromHDC() failed (Недостаточно системных ресурсов для завершения операции.) for QFontDef(Family="MS Shell Dlg 2", pointsize=9, pixelsize=12, styleHint=5, weight=75, stretch=100, hintingPreference=0) LOGFONT("MS Shell Dlg 2", lfWidth=0, lfHeight=-12) dpi=96
> [17:08:22.540 UTC] :0 : Warning: ShellExecute 'http://www.google.com' failed (error 5).
> [17:08:23.728 UTC] :0 : Warning: Data set on unsupported clipboard mode. QMimeData object will be deleted.

...

>910 more lines of "Warning: Data set on unsupported clipboard mode. QMimeData object will be deleted."

...

> [17:08:31.363 UTC] :0 : Warning: Data set on unsupported clipboard mode. QMimeData object will be deleted.
> [17:09:30.547 UTC] :0 : Warning: QObject::~QObject: Timers cannot be stopped from another thread
> 
> Program exited with code 03.
> warning: QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
> 
> warning: QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
> 
> warning: QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
> 
> warning: QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
> 
> warning: WER/CrashAPI:661: ERROR WerpHeapInitialize failed
> 
> warning: WER/CrashAPI:1596: ERROR WerpInitPEBStore failed
> 
> warning: WER/CrashAPI:661: ERROR WerpHeapInitialize failed
> 
> warning: WER/CrashAPI:1596: ERROR WerpInitPEBStore failed
> 
> +if $_exitcode != -999 
> ++quit 0

**Comment by reyaz006** [comment]
Something new:
(suspicious fragments from the second run)

> [17:13:11.802 UTC] :0 : Warning: Data set on unsupported clipboard mode. QMimeData object will be deleted.
> [17:13:11.886 UTC] :0 : Warning: Data set on unsupported clipboard mode. QMimeData o[New Thread 21372.0x3a8c]
> bject will be deleted.
> [17:13:42.688 UTC] audio/backend/openal.cpp:341 : Debug: Opening audio output "РљРѕР»РѕРЅРєРё (Realtek High Definition Audio)"
> [17:13:42.712 UTC] audio/backend/openal.cpp:353 : Debug: Opened audio output "РљРѕР»РѕРЅРєРё (Realtek High Definition Audio)"
> [17:13:43.164 UTC] audio/backend/openal.cpp:502 : Debug: Closing audio output
> [17:14:49.733 UTC] :0 : Warning: Data set on unsupported clipboard mode. QMimeData object will be deleted.
> [17:14:49.738 UTC] :0 : Warning: Data set on unsupported clipboard mode. QMimeData object will be deleted.
> [17:14:49.741 UTC] :0 : Warning: Data set on unsupported clipboard mode. QMimeData object will be deleted.
> [17:14:49.746 UTC] :0 : Warning: Data set on unsupported clipboard mode. QMimeData object will be deleted.
---
> [17:19:28.241 UTC] :0 : Warning: Data set on unsupported clipboard mode. QMimeData object will be deleted.
> [17:19:28.244 UTC] :0 : Warning: Data set on unsupported clipboard mode. QMimeData object will be deleted.
> [17:19:28.246 UTC] :0 : Warning: Data set on unsupported clipboard mode. QMimeData obje[New Thread 21372.0x3598]
> [New Thread 21372.0x44cc]
> [New Thread 21372.0x32e4]
> [New Thread 21372.0x3fdc]
> [New Thread 21372.0x5c14]
> [New Thread 21372.0x1d94]
> [New Thread 21372.0x5e3c]
> [New Thread 21372.0x61f0]
> [New Thread 21372.0x3380]
> [New Thread 21372.0x3894]
> [New Thread 21372.0x5e34]
> ct will be deleted.
> [17:19:28.250 UTC] :0 : Warning: Data set on unsupported clipboard mode. QMimeData object will be deleted.
> [17:19:28.253 UTC] :0 : Warning: Data set on unsupported clipboard mode. QMimeData object will be deleted.
> [17:19:28.255 UTC] :0 : Warning: Data set on unsupported clipboard mode. QMimeData object will be deleted.
---
> [08:19:30.848 UTC] persistence/profile.cpp:323 : Debug: Saving tox save to  "C:/Users/***/AppData/Roaming/tox\\tox_save.tox"
> [10:02:29.827 UTC] core/core.cpp:402 : Debug: Disconnecte[New Thread 21372.0x14f0]
> [New Thread 21372.0x2a50]
> [New Thread 21372.0x5e14]
> [New Thread 21372.0x41d4]
> [New Thread 21372.0x4bb4]
> [New Thread 21372.0x520c]
> [New Thread 21372.0x52dc]
> [New Thread 21372.0x47d0]
> [New Thread 21372.0x6004]
> [New Thread 21372.0x2f40]
> [New Thread 21372.0x53a8]
> [New Thread 21372.0x2f50]
> [New Thread 21372.0x4c7c]
> [New Thread 21372.0x5c8c]
> [New Thread 21372.0x2d38]
> [New Thread 21372.0x5994]
> [New Thread 21372.0x3bd4]
> [New Thread 21372.0x5a48]
> [New Thread 21372.0x5370]
> [New Thread 21372.0x3754]
> [New Thread 21372.0x3c84]
> [New Thread 21372.0x5074]
> [New Thread 21372.0x5778]
> [New Thread 21372.0x309c]
> [New Thread 21372.0x6070]
> [New Thread 21372.0x2290]
> [New Thread 21372.0x1200]
> [New Thread 21372.0x4084]
> [New Thread 21372.0x2808]
> [New Thread 21372.0x2904]
> [New Thread 21372.0x3808]
> [New Thread 21372.0x425c]
> [New Thread 21372.0x21ac]
> [New Thread 21372.0x5ebc]
> [New Thread 21372.0x5628]
> [New Thread 21372.0x1970]
> [New Thread 21372.0x4664]
> [New Thread 21372.0x1028]
> [New Thread 21372.0x3868]
> [New Thread 21372.0x150c]
> [New Thread 21372.0x13b8]
> [New Thread 21372.0x29a8]
> [New Thread 21372.0x54e4]
> [New Thread 21372.0x1870]
> [New Thread 21372.0x1168]
> [New Thread 21372.0x2c20]
> [New Thread 21372.0x5534]
> [New Thread 21372.0x488c]
> d from the DHT
> [10:02:30.832 UTC] core/core.cpp:399 : Debug: Connected to the DHT
---
> [20:30:57.491 UTC] audio/backend/openal.cpp:341 : Debug: Opening audio output "РљРѕР»РѕРЅРєРё (Realtek High Definition Audio)"
> [20:30:57.492 UTC] audio/backend/openal.cpp:353 : Debug: Opened audio output "РљРѕР»РѕРЅР[New Thread 21372.0x1b8c]
> [New Thread 21372.0x5944]
> [New Thread 21372.0x5870]
> [New Thread 21372.0x2854]
> [New Thread 21372.0x798]
> [New Thread 21372.0x5c20]
> [New Thread 21372.0x5f30]
> єРё (Realtek High Definition Audio)"
> [20:30:57.952 UTC] audio/backend/openal.cpp:502 : Debug: Closing audio output
> [20:31:23.577 UTC] audio/backend/openal.cpp:341 : Debug: Opening audio output "РљРѕР»РѕРЅРєРё (Realtek High Definition Audio)"
> [20:31:23.577 UTC] audio/backend/openal.cpp:353 : Debug: Opened audio output "РљРѕР»РѕРЅРєРё (Realtek High Definition Audio)"
> [20:31:24.035 UTC] audio/backend/openal.cpp:502 : Debug: Closing audio output
---
> [21:00:30.820 UTC] core/core.cpp:399 : Debug: Connected to the DHT
> [21:00:30.820 UTC] persistence/profile.cpp:323 : Debug: Saving tox save to  "C:/Users/***/AppData/Roaming/tox\\tox_save.tox"
> [21:00:30.828 UTC] persistence/profile.cpp:326 : Critical: Tox save file  "C:/Users/***/AppData/Roaming/tox\\tox_save.tox"  couldn't be opened
> [21:42:39.346 UTC] audio/backend/openal.cpp:341 : Debug: Opening audio output "РљРѕР»РѕРЅРєРё (Realtek High Definition Audio)"
> AL lib: (EE) ALCmmdevPlayback_open: Failed to create message events: 1450
> AL lib: (EE) ALCmmdevPlayback_open: Device init failed: 0x80004005
> [21:42:39.346 UTC] audio/backend/openal.cpp:349 : Warning: Cannot open output audio device "РљРѕР»РѕРЅРєРё (Realtek High Definition Audio)"
> [21:43:10.279 UTC] audio/backend/openal.cpp:341 : Debug: Opening audio output "РљРѕР»РѕРЅРєРё (Realtek High Definition Audio)"
> AL lib: (EE) ALCmmdevPlayback_open: Failed to create message events: 1450
> AL lib: (EE) ALCmmdevPlayback_open: Device init failed: 0x80004005
> [21:43:10.279 UTC] audio/backend/openal.cpp:349 : Warning: Cannot open output audio device "РљРѕР»РѕРЅРєРё (Realtek High Definition Audio)"
> [22:22:15.560 UTC] audio/backend/openal.cpp:341 : Debug: Opening audio output "РљРѕР»РѕРЅРєРё (Realtek High Definition Audio)"
> AL lib: (EE) ALCmmdevPlayback_open: Failed to create message events: 1450
> AL lib: (EE) ALCmmdevPlayback_open: Device init failed: 0x80004005
> [22:22:15.560 UTC] audio/backend/openal.cpp:349 : Warning: Cannot open output audio device "РљРѕР»РѕРЅРєРё (Realtek High Definition Audio)"
> [22:22:44.985 UTC] :0 : Warning: QObject::~QObject: Timers cannot be stopped from another thread
> 
> Program exited with code 03.
> warning: SHIMVIEW: ShimInfo(Complete)
> 
> 
> warning: QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
> 
> warning: QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
> 
> warning: QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
> 
> warning: QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
> 
> warning: Application "\??\*:\***\OperaPortable\launcher.exe" found in cache
> 
> warning: Application "\??\*:\***\OperaPortable\launcher.exe" Cache bypassed reason 0x86
> 
> warning: Application "\??\*:\***\OperaPortable\launcher.exe" found in cache
> 
> warning: Application "\??\*:\***\OperaPortable\launcher.exe" Cache bypassed reason 0x86
> 
> warning: Application "\??\*:\***\OperaPortable\launcher.exe" found in cache
> 
> warning: Application "\??\*:\***\OperaPortable\launcher.exe" Cache bypassed reason 0x86
> 
> warning: Application "\??\*:\***\OperaPortable\launcher.exe" found in cache
> 
> warning: Application "\??\*:\***\OperaPortable\launcher.exe" Cache bypassed reason 0x86
> 
> +if $_exitcode != -999 
> ++quit 0

Points of interest:
- There is something wrong with debug logging and perhaps it's connected to Cyrillic symbols in my custom audio device name. You can see that at several points lines get interrupted by New Thread messages.
- This time Cyrillic characters are not properly displayed in the log file for some reason.
- I have 2 audio devices and often switch between them. Second device is not Realtek.
- The active audio device during this crash was not Realtek. (Personally I think application should use "Primary Audio Device" without trying to identify it and assuming it won't be changed.)
- Many warnings about "unsupported clipboard mode", even before the crash. Before, I assumed it was only after the crash hits qTox (while error message is there, I can still use qTox), and I'm unable to copy anything I select in the chat window.

Is this helpful? I hope it is. Let me know if more debug information is needed.

**Comment by sudden6** [comment]
Very outdated
