### ISSUE TITLE
Missing password for ToxMe

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#5144]
I'm not sure where to post this because I don't know what kind of bug is that and what exact project it refers to.
After I imported my backed up profile in qTox, the password in "Register on ToxMe" field disappeared. I am still able to update the profile through the program but I'm unable to do that on the toxme.io website anymore.
Is there any way to retrieve the password from the profile file if it's even stored there?

Arch Linux
qTox 1.15.0
Commit hash 02d6c63acaac0ae95fa8be3a1b9301657e6a4a94
toxcore 0.2.2
Qt 5.10.1

**Comment by quantumpacket** [comment]
You can contact the maintainer of the site using the contact info in the readme on https://github.com/LittleVulpix/toxme he'll just have you contact him via the same tox id you need the password reset for.

**Comment by tox-user** [comment]
The password is stored in the profile together with all other details from toxme, but I don't think qTox gives us a way to see it. If you can compile it yourself, you could add one line of code to this function from src/widget/form/profileform.cpp to be able to see your toxme password:

```
void ProfileForm::showExistingToxme()
{
	QStringList info = Settings::getInstance().getToxmeInfo().split("@");
	bodyUI->toxmeUsername->setText(info[0]);
	bodyUI->toxmeServersList->addItem(info[1]);

	QString bio = Settings::getInstance().getToxmeBio();
	bodyUI->toxmeBio->setText(bio);

	bool priv = Settings::getInstance().getToxmePriv();
	bodyUI->toxmePrivacy->setChecked(priv);

	QString pass = Settings::getInstance().getToxmePass();
	bodyUI->toxmePassword->setText(pass);
	bodyUI->toxmePassword->show();
	bodyUI->toxmePasswordLabel->show();

	bodyUI->toxmeRegisterButton->hide();
	bodyUI->toxmeUpdateButton->show();
}
```

**Comment by Diadlo** [comment]
It, probably, saved somewhere in config file. Check ~/.config/tox/User.conf (not sure about extension)

**Comment by ghost** [comment]
@quantumpacket I'll consider that, thanks.

@tox-user normally the password is actually displayed in the same field, see attached screenshot where the red line is. I'm not sure if I still need to edit the code.

@Diadlo extensions of profile and config files are .tox and .ini but I'm unable to open them because of unknown encoding. Not a single advanced code editor can open them.

What I think is that my file could get corrupted or something. I'm gonna try to import the profile on a different distribution.

![screenshot_20180516_205409](https://user-images.githubusercontent.com/38018978/40135095-0db2c378-594d-11e8-996b-d866ef6551ff.png)

**Comment by sudden6** [comment]
Do you use a password for you tox profile? because then you have an encrypted profile and can't open it in an editor without decrypting it first.

**Comment by ghost** [comment]
@sudden6 I tried removing password, the amount of content in the file increases but still unable to read.

**Comment by sudden6** [comment]
Then it seems like the ini file got corrupted somehow, normally if unencrypted it's just text.

**Comment by tox-user** [comment]
>normally the password is actually displayed in the same field

I didn't know about that. I don't know what could have caused your issue. At this moment your best option of getting your toxme password back might be modifying the code. You can add this line `qDebug() << "toxme pass: " << pass;`. Like this:

```
	bodyUI->toxmePrivacy->setChecked(priv);

	QString pass = Settings::getInstance().getToxmePass();
	qDebug() << "toxme pass: " << pass;
	bodyUI->toxmePassword->setText(pass);
	bodyUI->toxmePassword->show();
	bodyUI->toxmePasswordLabel->show();
```

Then your password should show up in the log when you go to your profile settings.

**Comment by Diadlo** [comment]
@tox-user Since password doesn't shown in UI, why it will in logs?

**Comment by ghost** [comment]
@tox-user it returns nothing unfortunately.
`widget/form/profileform.cpp:497 : Debug: toxme pass:  ""`

**Comment by sudden6** [comment]
@brokenechored I think then you can only follow the advice of @quantumpacket 

Btw, do you have an idea how the ini got corrupted?

**Comment by ghost** [comment]
@sudden6 I don't know about .ini, I only backed up .tox. Maybe because I exported/imported it a couple times in the past, not sure.

**Comment by tox-user** [comment]
@Diadlo I wanted to make sure that the password exists in the .ini file.

Since the export option only allows users to backup their profile and not their settings, you won't be able to get your toxme password back, unless you still have that old .ini file somewhere.

**Comment by tox-user** [comment]
Implementing this could solve the problem: https://github.com/qTox/qTox/issues/1656.

**Comment by ghost** [comment]
I can't contact @LittleVulpix on Tox, there is no response. Maybe they'll see this topic here since I tagged them.
Anyway, I wonder if there is a possibility to implement a feature in GUI that would allow deleting profile from the network instead of simple info updating. The file still has some sort of access, maybe it would be possible to send an account termination signal if the network supports that of course. I don't have a problem with re-creating profile file since the current one is corrupted anyway so it would help a lot.

**Comment by tox-user** [comment]
If I understand correctly, none of your files are corrupted. Your toxme password was stored in an .ini file that contains all the settings. You only copied your profile file (.tox), so qTox created a new .ini file for you. If you could recover your old settings file, you would recover your password.

You want a button that would remove your account from toxme? Does toxme allow that?

**Comment by ghost** [comment]
@tox-user if files do not unencrypt when the local password is removed then that tells me there is some sort of corruption. It was discussed already.
As I said before I don't have .ini, I only backed up .tox.

> You want a button that would remove your account from toxme? Does toxme allow that?

Apparently it does judging by the delete button on the website.

![screenshot_20180531_191103](https://user-images.githubusercontent.com/38018978/40794025-b4c6d630-6506-11e8-9fce-06d942262fd8.png)

**Comment by LittleVulpix** [comment]
@brokenechored hey, sorry about being unreachable on tox. Actually I had taken down the qtox contact cause people were spamming me with friend requests to "test the service" even though it clearly stated that my contact was only for technical issues.

Yes, toxme.io allows you to delete your own account as seen above. 

I'll leave my toxmeio tox running for a bit so please do contact me there and we'll sort it out, if you have the appropriate means of verifying the account in question is yours.

**Comment by ghost** [comment]
@LittleVulpix thanks for the response, I've resent you the request on Tox.

**Comment by sudden6** [comment]
Seems solved.

**Comment by LittleVulpix** [comment]
@sudden6 Yep, it is indeed. Sorry for not responding here.
