### ISSUE TITLE
The io.github.qtox.qTox.appdata.xml should ideally have OARS and version tags added.

### ISSUE THREAD

**Issue by robschi** [qTox/qTox#5152]
Copied this from:
https://github.com/flathub/flathub/pull/379#issuecomment-387563335

nedrichards wrote:
The [upstream appdata](https://github.com/qTox/qTox/blob/master/res/io.github.qtox.qTox.appdata.xml) should ideally have [OARS](https://hughsie.github.io/oars/) and version tags added.

**Comment by sudden6** [comment]
I came up with
```
  <content_rating type="oars-1.1">
    <content_attribute id="violence-cartoon">none</content_attribute>
    <content_attribute id="violence-fantasy">none</content_attribute>
    <content_attribute id="violence-realistic">none</content_attribute>
    <content_attribute id="violence-bloodshed">none</content_attribute>
    <content_attribute id="violence-sexual">none</content_attribute>
    <content_attribute id="violence-desecration">none</content_attribute>
    <content_attribute id="violence-slavery">none</content_attribute>
    <content_attribute id="violence-worship">none</content_attribute>
    <content_attribute id="drugs-alcohol">none</content_attribute>
    <content_attribute id="drugs-narcotics">none</content_attribute>
    <content_attribute id="drugs-tobacco">none</content_attribute>
    <content_attribute id="sex-nudity">none</content_attribute>
    <content_attribute id="sex-themes">none</content_attribute>
    <content_attribute id="sex-homosexuality">none</content_attribute>
    <content_attribute id="sex-prostitution">none</content_attribute>
    <content_attribute id="sex-adultery">none</content_attribute>
    <content_attribute id="sex-appearance">none</content_attribute>
    <content_attribute id="language-profanity">none</content_attribute>
    <content_attribute id="language-humor">none</content_attribute>
    <content_attribute id="language-discrimination">none</content_attribute>
    <content_attribute id="social-chat">intense</content_attribute>
    <content_attribute id="social-info">none</content_attribute>
    <content_attribute id="social-audio">intense</content_attribute>
    <content_attribute id="social-location">none</content_attribute>
    <content_attribute id="social-contacts">none</content_attribute>
    <content_attribute id="money-purchasing">none</content_attribute>
    <content_attribute id="money-gambling">none</content_attribute>
  </content_rating>
```

after following their assistant, but I have no idea what that means. I'm also not sure if this system can be applied to Tox in a reliable way, because it depends on the users you chat with.

**Comment by robschi** [comment]
Maybe also:
<content_attribute id="social-contacts">intense</content_attribute>

Then the entries are the same as in "im.riot.Riot" or "org.signal.Signal", and this sounds not to wrong.

**Comment by sudden6** [comment]
Can you open a PR? I will not have time for some time to fix this.

**Comment by robschi** [comment]
Before I can make a PR here, I really need to learn how exactly this works. 
But following the "Generate Data" on the OARS page I got this:

  <content_rating type="oars-1.0">
    <content_attribute id="violence-cartoon">none</content_attribute>
    <content_attribute id="violence-fantasy">none</content_attribute>
    <content_attribute id="violence-realistic">none</content_attribute>
    <content_attribute id="violence-bloodshed">none</content_attribute>
    <content_attribute id="violence-sexual">none</content_attribute>
    <content_attribute id="drugs-alcohol">none</content_attribute>
    <content_attribute id="drugs-narcotics">none</content_attribute>
    <content_attribute id="drugs-tobacco">none</content_attribute>
    <content_attribute id="sex-nudity">none</content_attribute>
    <content_attribute id="sex-themes">none</content_attribute>
    <content_attribute id="language-profanity">none</content_attribute>
    <content_attribute id="language-humor">none</content_attribute>
    <content_attribute id="language-discrimination">none</content_attribute>
    <content_attribute id="social-chat">intense</content_attribute>
    <content_attribute id="social-info">none</content_attribute>
    <content_attribute id="social-audio">intense</content_attribute>
    <content_attribute id="social-location">none</content_attribute>
    <content_attribute id="social-contacts">none</content_attribute>
    <content_attribute id="money-purchasing">none</content_attribute>
    <content_attribute id="money-gambling">none</content_attribute>
  </content_rating>

**Comment by sudden6** [comment]
@robschi for the qTox specific stuff you can get a lot of info here: https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md

Most importantly, name your commits according to our guidelines, because we generate the changelog from that.

**Comment by zetok** [comment]
>The upstream appdata should ideally have OARS

According to https://github.com/flathub/flathub/issues/158 it doesn't have to have it. So it can safely be ignored.
