### ISSUE TITLE
Add tooltips for green icons

### ISSUE THREAD

**Issue by philip-bl** [qTox/qTox#516]
Green icons have no tooltips and some users might not understand what they are supposed to do. For example in the top right o qtox I don't understand what 2 smaller icons are supposed to be. So they all should have tooltips which appear if you hold cursor on the icon.

**Comment by dubslow** [comment]
Duplicate of some old Mouseym issue.

OP, could you please make a precise list of which buttons need tooltips? Bonus points for what the tooltip should be. (Adding tooltips is easy, but enumerating which buttons and writing succinct tooltips is hard. Make a dev's life easier and less tedious :D)

**Comment by philip-bl** [comment]
http://i.imgur.com/bGnFmhB.png

**Comment by philip-bl** [comment]
Audio call is probably better than Voice call.

**Comment by tux3** [comment]
The two small green buttons are "toggle speakers" and "toggle microphone" when in call. They more or less work.

**Comment by zetok** [comment]
s/Attach file/Send file(s)/  ?

**Comment by dubslow** [comment]
Thanks @b-filip , that's exactly what the doctor ordered. :)
