### ISSUE TITLE
There is no pulseaudio in 1.15.0

### ISSUE THREAD

**Issue by SergeyDjam** [qTox/qTox#5161]
##### Brief Description

OS: Linux (ROSA Fresh 8.1 x86_64)  
qTox version: 1.15.0
Commit hash:  
toxcore:  c-toxcore-0.2.2
Qt:  5.6.1
Hardware:  DELL Inspiron 5040
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. start qTox
2. preferens - Audio/Video
3. Audio - ALSA default and noaudio. No PULSEAUDIO
???

My distro PULSEAUDIO only

##### Additional Info
(links, images, etc go here)

----

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA%\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by sudden6** [comment]
You probably see the ALSA fallback of pulseaudio, try to deactivate it. qTox doesn't care which audio backend you have, it works with pulseaudio and ALSA.

**Comment by ghost** [comment]
Might be related: I have JACK and Pulseaudio installed, but can only choose 'JACK Default' or 'Disabled' as playback device. But I have all expected options for the capture device. - qTox 1.16 un Xubuntu.

**Comment by ghost** [comment]
To illustrate the issue, still persisting in latest qTox, these are my Pulse volume control pages for input and output devices:
![inputdevices](https://user-images.githubusercontent.com/16050452/46256031-37d2a600-c4a5-11e8-9c68-f8102b7ff61a.png)
![outputdevices](https://user-images.githubusercontent.com/16050452/46256032-37d2a600-c4a5-11e8-878e-1dbcd119f960.png)

And this is how the qTox interface looks like, where the 'Capture device' list indeed reflects all options on the Pulse input page, but as playback device only 'JACK Default' is allowed.
![qtox](https://user-images.githubusercontent.com/16050452/46256034-37d2a600-c4a5-11e8-90c8-b8f4f07ebc39.png)

Pulse and JACK operate on different sound cards, and usually all Pulse-aware applications allow 'Jack sink' as output device. It seems as if qTox connects directly to JACK for output.

I compile qTox with `simple_make.sh`, in case there would be some options to set.

**Comment by sudden6** [comment]
> I compile qTox with simple_make.sh, in case there would be some options to set.

No there are no options to set.

qTox uses https://github.com/kcat/openal-soft for audio handling and this library probably determined that JACK is the best thing for audio input/output. I guess you can only disable JACK or find a way to to let openal-soft ignore the JACK server.

Does qTox work normally if you don't run JACK?

**Comment by ghost** [comment]
When stopping the JACK server before starting qTox, the usual Pulse audio output device appears as expected. If I then enable JACK while qTox is running, and switch once back and forth in the configuration tabs, the Pulse JACK sink also appears (this sink in the Pulse bridge to JACK).

When JACK is running already at qTox start, only the proper JACK server is available as output device, Pulse does not appear. Also stopping/starting JACK does not change this.

Note also that the **input** device list is always correct, showning the Pulse JACK source (bridge from JACK) also if JACK was running at program start.

**Comment by anthonybilinski** [comment]
Agreed with sudden6 that this seems entirely in the hands of openal-soft. There's not much we can do about it in qTox if the issue still exists. Closing.
