### ISSUE TITLE
Flatpak: qTox can't find my webcam

### ISSUE THREAD

**Issue by robschi** [qTox/qTox#5162]
##### Brief Description

**OS:** 
Linux 4.16.0-1-amd64 #1 SMP Debian 4.16.5-1 (2018-04-29) x86_64 GNU/Linux
(Debian testing with lxqt)
**qTox version:**
You are using qTox version v1.15.0.
**Commit hash:**
Commit hash: 02d6c63acaac0ae95fa8be3a1b9301657e6a4a94
**toxcore:**
toxcore version: 0.2.2
**Qt:**
Qt version: 5.10.1
**Hardware:**
see v4l2-ctl.log

Reproducible: Always

##### Steps to reproduce

1. Have a webcam 
2. Install [qtox flatpak](https://flathub.org/apps/details/io.github.qtox.qTox) and open it.
3. Try to open the webcam

##### Observed Behavior
No video capturing device is found

##### Additional Info
Did play around with various flatpak options and looked in .json files of other flatpaks like skype (where the webcam works), but could find nothing do solve the problem, and we have already "--device=all" set in our .json file.
Maybe it has something to do "PipeWire", but I don't really know what that is.

[qtox.log](https://github.com/qTox/qTox/files/2059989/qtox.log)
[v4l2-ctl.log](https://github.com/qTox/qTox/files/2059990/v4l2-ctl.log)

**Comment by sudden6** [comment]
Can confirm on openSUSE Tumbleweed. No idea what's causing this, theoretically if qTox has access to the videodevice it should be able to do video right?

EDIT: works normally without flatpak. Maybe the ffmpeg-flatpak we're building with is not a normal ffmpeg?

**Comment by yurivict** [comment]
ffmpeg needs to have the libv4l2 option enabled in it to be usable with webcams: ```--enable-libv4l2```.

**Comment by sudden6** [comment]
I think we can just take the ffmpeg build instructions from https://github.com/flathub/org.freedesktop.Platform.ffmpeg/blob/master/org.freedesktop.Platform.ffmpeg.json and enable only the needed stuff like in https://github.com/qTox/qTox/blob/master/windows/cross-compile/build.sh#L455

Does anybody see problems with this approach?

**Comment by tox-user** [comment]
If we already do that, why not?

**Comment by sudden6** [comment]
I'm working on a fix for this.

**Comment by sudden6** [comment]
[qtox.flatpak.zip](https://github.com/qTox/qTox/files/2177711/qtox.flatpak.zip)

The attached file should fix this problem, can someone please test it?

**Comment by sudden6** [comment]
Should be fixed with the newest version
