### ISSUE TITLE
GitLab Mirror Not Syncing

### ISSUE THREAD

**Issue by quantumpacket** [qTox/qTox#5169]
Migrating over to GitLab and noticed the qTox mirror is no longer syncing.

See: https://gitlab.com/qTox/qTox_mirror

> Mirrored from https://github.com/qTox/qTox.git.
The repository failed to update 3 days ago.
Repository mirroring has been paused due to too many failed attempts, and can be resumed by a project master.
Last successful update 5 days ago.

Also, could the GPG keys for the devs be uploaded to GitLab so signatures verify? Right now they all show up as unverified in the UI. https://gitlab.com/qTox/qTox_mirror/commits/master

**Comment by tox-user** [comment]
Who created that mirror? I don't really feel like creating a gitlab account to upload my key, but having qTox code in more than one place is a good idea.

**Comment by quantumpacket** [comment]
According to https://gitlab.com/groups/qTox/-/group_members @zetok was the first member.

**Comment by sudden6** [comment]
yes this was zetoks idea and he did it, maybe in the light of current events we should make sure the mirror at least works.

**Comment by tux3** [comment]
From a glance it seems to be [a bug on GitLab's side](https://gitlab.com/gitlab-org/gitlab-ee/issues/5191), as soon as there's a fix or a workaround we can update it.

**Comment by quantumpacket** [comment]
I was able to mirror this repo on GitLab without any problems and it would sync fine. So that bug may not be related?

**Comment by tux3** [comment]
I'm not sure what exactly triggers this problem, but simply retrying the sync didn't fix it.

If you have any ideas I'm more than happy to try them :)

**Comment by quantumpacket** [comment]
Since mine was a new mirror, maybe delete the current mirror and re-add it? That *shouldn't* break anything AFAIK.

**Comment by tux3** [comment]
Alright let's hope it doesn't break then! I moved the broken repo to qTox_mirror_old and imported a new qTox_mirror.

Tell me if it looks good to you and we can close this.

**Comment by quantumpacket** [comment]
Is the new mirror made public? It's not showing up for me. https://gitlab.com/qTox/qTox_mirror

**Comment by tux3** [comment]
Should be working now

**Comment by quantumpacket** [comment]
Seems to be syncing fine now. Closing, thanks!
