### ISSUE TITLE
History doesn't work

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#517]
After restarting qTox (since it noticeably slowed down after sending few messages) I have no history of sent/received messages.

Pls fix.

Edit: I didn't use encryption

**Comment by tux3** [comment]
Currently you need to load the history manually (right click -> Load history -> Pick the current date).

Does it work if you do that ?

**Comment by zetok** [comment]
oh, didn't think it would work like that, sorry for making issue

**Comment by dubslow** [comment]
I'm with zetok on this, manually loading should be non default option at best, if not simply just not a thing.

**Comment by tux3** [comment]
I agree with both of you, @apprb said it just didn't come to mind.
You can make a new issue if you want.
