### ISSUE TITLE
qtox vanishes when I change monitors

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#518]
Run qtox. 

Unplug VGA cable. 

Plug it into another monitor. 

qTox is gone.

I thought i could get around it by hiding it in the tray during the unplugging and replugging, but it vanishes all the same. Debian Jessie Openbox.

```
QBackingStore::flush() called for  QWidgetWindow(0x848ce78, name = "QSystemTrayIconSysWindow")  which does not have a handle.
requestSystemTrayWindowDock failed.
```

**Comment by dubslow** [comment]
@agilob ? This sounds like a fun one to fix. :)

**Comment by dubslow** [comment]
Also sort of related, when I change workspace qTox gets minimized to tray... that's a bit annoying.

**Comment by agilob** [comment]
Possibly another(?) Qt5 bug?
https://bugs.launchpad.net/qpdfview/+bug/1334682
https://bugreports.qt-project.org/browse/QTBUG-40168

No idea, I don't have second screen, not even place to put on one my desk ;/

**Comment by suhr** [comment]
Is this still an issue with fresh Qt5?

**Comment by antis81** [comment]
I have a second monitor available and can at least help in reproducing this (tomorrow). Looks not like a Qt5 bug - we'll see.

**Comment by agilob** [comment]
I couldn't reproduce it on Arch with qt5.4 but a friend I asked for helped reproduced it on fedora. I'm thinking this might be also desktop environment dependent.

**Comment by suhr** [comment]
@agilob Does your friend have the same Qt5 version?

**Comment by ProMcTagonist** [comment]
I can't re-test with multiple monitors right now but I'll get on it within the next couple of days.

**Comment by antis81** [comment]
I tried to reproduce with Lubuntu 15.04. Short answer: Cannot reproduce.

Long answer:
I plugged in a single second VGA monitor. Checked all positions with qTox window ...
- ... on left (primary) monitor
- ... on right (secondary) monitor
- ... centred between both monitors

Then on each setup I did:
1. Unplug monitor 
2. Re-plug monitor

Result: Nothing happened -> qTox and every other application stays in place. 

@ProMcTagonist Question: Can you please provide more info about the steps to reproduce and system info (distro, qtox version, qt version)? Did you call XRandR (actively trigger the monitor detection) after re-plugging the second monitor?

---

Btw.: Where do I find exact qTox version info (with current build number)?

**Comment by ProMcTagonist** [comment]
@antis81 I definitely didn't call xrandr manually. This issue is a year old so I don't know about versions.

But I only had a single monitor connected at any one time, as opposed to your simultaneous multi-monitor setup.

I was using tint2 for my tray, if that helps.

**Comment by antis81** [comment]
@ProMcTagonist Ah ok - that's of course a completely different setup. AFAIK there's no auto-detection in xrandr yet, when the monitor setup changes while the computer is running. Thus, after changing monitors, X still thinks you are connected to the first monitor. Try to call `xrandr --auto` to trigger an auto-setup.

Can you check what happens, if you just unplug and re-plug the same monitor?

Apart from that it sounds like an issue with the window manager. The panel doesn't matter here (for me it's cairo-dock). The laptop I use, has a fixed monitor attached and I only have a single (second) monitor available. So I'm not sure if I can help any further.

**Comment by zetok** [comment]
@TheLastProject could you re-test newest qTox (preferably binary from wiki, since it's bundled with newer than Gentoo has Qt 5.5) ?

**Comment by anoadragon453** [comment]
I suggest closing unless can be reproduced on latest qTox/Qt build.

**Comment by agilob** [comment]
btw I can't reproduce it on KDE5 ArchLinux. Can anyone?

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.

If issue is still not fixed, please comment for reopen.
