### ISSUE TITLE
qTox fails to launch with missing libvpx error

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#5180]
##### Brief Description

OS: Opensuse Tumbleweed  
commit hash: 2a8ab03e46dd08efc4051a01bea56fe6a4c38a11

Reproducible: Always

qTox fails to launch with a library error. This has been going on for a while. 

##### Steps to reproduce

1. run qtox

##### Observed Behavior

qTox fails to start with message:

```
qtox: error while loading shared libraries: libvpx.so.4: cannot open shared object file: No such file or directory
```

##### Expected Behavior
qTox launches

##### Extra

```cmake . ``` includes in its output:

```
-- VPX LIBRARY_DIRS: 
-- VPX INCLUDE_DIRS: 
-- VPX CFLAGS_OTHER: 
-- VPX LIBRARIES:    vpx;m
-- VPX found
```

```zypper search libvpx``` reveals:

```
S  | Name          | Summary                                               | Type   
---+---------------+-------------------------------------------------------+--------
i+ | libvpx-devel  | Development files for libvpx, a VP8/VP9 codec library | package
i+ | libvpx5       | VP8/VP9 codec library                                 | package
```

Does qTox hard-require libvpx 4 instead of 5?

Also, Toxic launches.

**Comment by ezavod** [comment]
@ProMcTagonist Just to clarify, you're using a prebuild package or are you building from source?
I'm also using Tumbleweed (up to date) and don't have this error when building from source.

**Comment by ProMcTagonist** [comment]
I primarily build from source. I just tested both, and I get the same error when using the package and when building from source.

**Comment by ezavod** [comment]
That is strange since I have only vpx5 installed and `find /usr -name "*vpx*"` doesn't show anything else.
Maybe check if there are some old and broken dependencies that cmake finds and mistakenly links (or reinstalling the packages might also do the trick).

**Comment by ProMcTagonist** [comment]
```
$ find /usr -name "*vpx*"
/usr/include/vpx
/usr/include/vpx/vpx_integer.h
/usr/include/vpx/vpx_encoder.h
/usr/include/vpx/vpx_image.h
/usr/include/vpx/vpx_frame_buffer.h
/usr/include/vpx/vpx_codec.h
/usr/include/vpx/vpx_decoder.h
/usr/share/texmf/fonts/enc/dvips/sourcecodepro/a_7ovpxh.enc
/usr/share/ffmpeg/libvpx-720p.ffpreset
/usr/share/ffmpeg/libvpx-720p50_60.ffpreset
/usr/share/ffmpeg/libvpx-360p.ffpreset
/usr/share/ffmpeg/libvpx-1080p50_60.ffpreset
/usr/share/ffmpeg/libvpx-1080p.ffpreset
find: ‘/usr/share/polkit-1/rules.d’: Permission denied
/usr/share/doc/packages/libvpx5
/usr/lib64/pkgconfig/vpx.pc
/usr/lib64/libvpx.so.5.0.0
/usr/lib64/libvpx.so.5.0
/usr/lib64/vlc/plugins/codec/libvpx_plugin.so
/usr/lib64/gstreamer-1.0/libgstvpx.so
/usr/lib64/libvpx.so
/usr/lib64/libvpx.so.5
```

Similar to yours?

**Comment by ezavod** [comment]
Got the same except the ffmpeg stuff, but that's probably unrelated.
I don't know enough about cmake to pinpoint the exact source of this bug, but I've had incidents like this before in which updates forgot to replace old entries.

What is the output of `ldconfig -p | grep vpx`?

Mine is `libvpx.so.5 (libc6,x86-64) => /usr/lib64/libvpx.so.5` and `libvpx.so (libc6,x86-64) => /usr/lib64/libvpx.so`.

**Comment by ProMcTagonist** [comment]
```
libvpx.so.5 (libc6,x86-64) => /usr/lib64/libvpx.so.5
libvpx.so (libc6,x86-64) => /usr/lib64/libvpx.so
```

**Comment by sudden6** [comment]
ping @sleep-walker

**Comment by zetok** [comment]
>Does qTox hard-require libvpx 4 instead of 5?

There's no specified dependency on any specific version of it in cmake files, AFAICT.

>I primarily build from source. I just tested both, and I get the same error when using the package and when building from source.

Just to make sure: did you rebuild qTox after libvpx updates, from clean source (`git clone --depth 1` or equiv.)?

**Comment by sleep-walker** [comment]
I'm sorry, I have to missed this during my vacation.

1. qTox works for me
2. the way how it is packaged it requires anything with vpx pkg-config file
3. binary itself depends on vpx 5
````
# ldd /usr/bin/qtox | grep vpx
        libvpx.so.5 => /usr/lib64/libvpx.so.5 (0x00007f6e74823000)
````
4. current version of package doesn't seem to require libvpx at all (on RPM symbol level) which seems to be wrong (as this dependency is found out from linker information) and can be the reason for your problems. At the same time it seems that you haven't updated your system for a while and mere `zypper dup` would probably fix your issue.

For sure it is not qTox upstream issue and this ticket can be IMHO closed.
