### ISSUE TITLE
No automatic login option !

### ISSUE THREAD

**Issue by Nokia808** [qTox/qTox#5183]
##### Brief Description

OS: Windows / OS X / Linux Fedora 28 X64
qTox version: 1.15.0 (2.fc28)
Commit hash:  I do not know what "commit hash" mean ?
toxcore:  0.2.2 (2.fc28)
Qt:  4.8.7 (40.fc28)
Hardware:

-----------------
Hi. 
1st I would like to say thank you very much for your very hard efforts to make this very nice application available for free & being open source.

There is annoying issue. I need to enter my credentials (password) every time I launch qTox ! There is no "automatic login" / "save my password" / "automatic load profile" option ! 

Is this intended as security measure, or just yet unavailable option & will be available in feature ?

**Comment by ezavod** [comment]
You could remove the password via your profile page (click on your avatar on top left corner, scroll to the bottom). Without a password qTox does auto login.

However this is a obviously **bad idea from an privacy/security point of view,** if that's a concern you might have.

See also #4136 and the first comment.

**Comment by tox-user** [comment]
If qTox remembered your password, anyone who has access to your computer would be able to log in to your profile. What is the point of having a password then? Feel free to correct me if I'm wrong.

**Comment by naxuroqa** [comment]
Theoretically you could store the password in a keyring, which gets unlocked on login. I'm not aware of a platform or even DE independent library to support this, most other projects do this via plugins.

**Comment by tox-user** [comment]
That sounds exactly like a password protected Tox profile - it gets unlocked on login.

**Comment by naxuroqa** [comment]
The profile would indeed still be password protected. The password would then be stored in password manager like keepass/kwallet/gnome-keyring, which would be unlocked when you log on your user account.

**Comment by Nokia808** [comment]
Hi all. Thank you for all replies !

Why, & why qTox has no build in saving option for profile password in encrypted way ??!!!

I use Rambox, a universal messenger application. Currently it store password (if user select to store it) encrypted by hash it using MD5 method. And there is in the developer plan for version 1.0.0 of Rambox to change method of encryption to something more strong & secure. Please notice this links:

A list of planned features & bugs to be fixed in version 1.0.0 of Rambox:
https://github.com/saenzramiro/rambox/milestones/1.0.0

Of the above plan, see the following:
https://github.com/saenzramiro/rambox/issues/545

I'm not programmer, but I thing that as long as Rambox able to store password of login in encrypted way then qTox should be also. You can certainly use something more strong & secure than MD5 hash method.

I wish the above links (2nd one) will be benefit to you.

Best.

**Comment by sudden6** [comment]
1. MD5 is broken and is widely considered insecure, you should really convince the developer to use something else

2. automatic login and encrypted profiles is mutually exclusive, because you need to store the password somewhere and logically if qTox can read it, the attacker can too.

The only real solution to this is using the systems keychain as @naxuroqa suggested. There was even a PR for this, but it didn't get finished.

**Comment by naxuroqa** [comment]
Sadly seems like the dev abandoned it back then https://github.com/qTox/qTox/pull/3332

**Comment by ghost** [comment]
I like to add that OS keyring integration (Ubuntu / GNOME keyring in my case) is a mandatory feature to my opinion for a program like qTox. Of course the application should ask the user if it should store the credentials in the keyring.

**Comment by sudden6** [comment]
So this comes down to create integration with a keychain for this we have  #4136 and I'll close this.
