### ISSUE TITLE
Crash when reconnecting twice with an invalid proxy

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#5187]
See https://github.com/qTox/qTox/pull/5185#issuecomment-399696465 for the details.

**Comment by tox-user** [comment]
Version: 1.15.0
Commit: 254b861ded5c0710cf74496200e47c57cd811e1a

**Comment by sudden6** [comment]
This is fixed at 8e5598572abc4a481267aa3855e06394a0b7b7b9
