### ISSUE TITLE
qTox do not want to be installed on Linux

### ISSUE THREAD

**Issue by Abdula-2015** [qTox/qTox#5188]
OS: **CentOS 6.9 / 32 bit**
Hardware:  **Acer Aspire E5-511-P1HX** 
Reproducible: **Always** 

##### Steps to reproduce

1. I install the **RPM Fusion** "updates i386" and "updates-testing i386" repository to my Linux CentOS 6.9.
2. After that execute the command:

`yum install qtox`

3. But  i get an error that **Such a package is missing**

What should I do now?

**Comment by sudden6** [comment]
We do not provide any packages so far. You can compile qTox from source like in https://github.com/qTox/qTox/blob/master/INSTALL.md#linux or try our experimental Flatpak package https://flathub.org/apps/details/io.github.qtox.qTox (video via webcam doesn't work there).

**Comment by Abdula-2015** [comment]
I have been using qTox for many years. I really like this program! :)

But I do  not want to use the compilation procedure. Because It is very difficult for ordinary users, and also clogs the system.
Like most people, I use packages.
Why do not you make packages? Do not you want mass popularity of qTox?

**Comment by sudden6** [comment]
We have ongoing projects to package qTox as Flatpak package and as AppImage, but they are not yet finalized. For classical distro packages we rely on external maintainers, simply because we have not enough man power to manage these for every distribution on earth.

As for compiling yourself, we ship `simple_make.sh` which handles all necessary commands that should make it as easy as installing via package manager.

**Comment by Abdula-2015** [comment]
> EDIT: For Fedora and OpenSUSE people from the community have stepped up and maintain packages, if you too want to take on that task, we will happily help you with the build process of qTox.

I told you that I'm just a simple user :)
Therefore, I do not know how and do not want to do such complex things as compiling or building packages.

I can only use the finished packages.

But you did not answer my question: why do not  installed the package under your instructions?

**Comment by tox-user** [comment]
>why do not installed the package under your instructions?

I don't think we have a package for your distribution. I think RPM Fusion is only for Fedora.

>Why did qtox disappear for Linux in https://tox.chat/download.html?

I'm not sure what you mean, but we used to have our own repository with packages. We don't have it anymore: https://blog.tox.chat/2018/02/shutdown-of-the-debian-and-ubuntu-package-repository.

In a few days qTox 1.16 will be released. It will have an Appimage package, which you can run very easily by double clicking the file. It contains all required packages, so you will not have to install anything. You will need to be patient and wait a few days for the 1.16 release.

@sudden6 simple_make is missing yum package manager as a way to install dependencies so it won't work on CentOS

**Comment by Abdula-2015** [comment]
But do chess Appimage package a big place on the disc?

**Comment by sudden6** [comment]
@tox-user I think nobody ever requested it, nor did someone implement it.

**Comment by tox-user** [comment]
@Abdula-2015 less than 100MB

**Comment by Abdula-2015** [comment]
This is very much! RPM or DEB packages occupy 3 - 11 Mb.

**Comment by sudden6** [comment]
We now have an official AppImage and Flatpak build: https://github.com/qTox/qTox/releases/latest

**Comment by Abdula-2015** [comment]
This AppImage and Flatpak do not want to run.
He report an error:  

> Can not start a binary file

**Comment by sudden6** [comment]
This could be because the files are for 64 bit systems and I just noticed you run 32 bit.

**Comment by Abdula-2015** [comment]
Yes, I have a 32 bit OS - CentOS 6.9 / **32 bit**
What should I do?

**Comment by sudden6** [comment]
I think for such an old system your only way will be to compile from source. https://github.com/qTox/qTox/blob/master/INSTALL.md#linux contains the instructions, you probably have to search the web for some dependencies because they are named differently. Though I have to admit it could be very hard to get all the dependencies qTox needs in recent enough version.

**Comment by Abdula-2015** [comment]
And why do not you make qTox the 32 bits version of Flatpak or Appimage?

**Comment by sudden6** [comment]
Flathub makes them, but we likely won't because 32Bit is fading out. Major distros already reduce their 32Bit efforts.

**Comment by sudden6** [comment]
qTox is now in some major distros official repositories and provides AppImages and Flatpaks
