### ISSUE TITLE
UVC video locked at 120pixels resolution

### ISSUE THREAD

**Issue by eatdust** [qTox/qTox#5198]
On two different machines, with two different cameras, both being detected as "UVC camera", the resolution is fixed to 120 and cannot be changed.

Linux mageia
qTox version: 1.15.0
Commit hash:  build without git
toxcore:   0.2.2
Qt:  5.9.4
Hardware:  x86_64
…

Reproducible: Always

##### Steps to reproduce

1. Go to settings and check the available resolutions of your UVC camera
2. it is 120 pixels only
3. …

##### Observed Behavior

Locally, the feedback image from my camera looks fine, at low resolution though, 120 pixels. But in a videocall, my friends told me my video stream is completely corrupted, green horizontal lines are crossing the images. Same behaviour
[qtox.log](https://github.com/qTox/qTox/files/2148444/qtox.log)

 on two different machines with different UVC cameras.

##### Expected Behavior

I should be able to select the resolution other than 120p. I suspect the green line issues might be a consequence of forcing a non-supported resolution to the camera.

I have also tried to delete the directory .config/tox, no change !!

**Comment by sudden6** [comment]
please post the output of `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

Can you compile from source using https://github.com/qTox/qTox/blob/master/simple_make.sh and retest?

**Comment by eatdust** [comment]
Here we go, I have only v4l-ctl. It reports only 120pixel resolution, but that seems to be related to which mode the camera is put in.

If I start qtox, then v4l-ctl reports onlt 120 pixels resolution. But if I start guvcview, then guvcview finds the native res and after that v4l-ctl reports 960 pixels resolution.

Running again qtox after does not fix the issue, the camera, and v4l-ctl are back to only 120 pixels res.

PS: building with simple_make.sh --> exactly same behaviour!

[v4l2-ctl_all_after_guvcview.log](https://github.com/qTox/qTox/files/2158658/v4l2-ctl_all_after_guvcview.log)
[v4l2-ctl_all_after_qtox.log](https://github.com/qTox/qTox/files/2158659/v4l2-ctl_all_after_qtox.log)

**Comment by sudden6** [comment]
It could be because qTox requests 30fps, but your webcam only supports 15fps at the higher resolution, we will need to check the mode selection logic.

**Comment by eatdust** [comment]
Fixed with latest toxcore 0.2.4 and qtox-1.16.3, I am closing. Thanks guys!
