### ISSUE TITLE
"./bootstrap.sh --local" fails

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#5199]
##### Brief Description

Regression: calling "./bootstrap.sh --local" fails since commit ead2152d6f0d15f7e662975fb3ed8525109794c3

OS: GNU/Linux (Debian 9)
qTox version: git
Commit hash:  ae350a648366f196008f21504f5579e8730cb187
toxcore:  0.2.2
Reproducible: Always

##### Steps to reproduce

1. git clone the repository
2. ./bootstrap.sh --local

##### Observed Behavior

Fails at installation with:

[100%] Built target auto_set_name_test
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/libtoxcore.so.2.2.0
CMake Error at cmake_install.cmake:48 (file):
  file INSTALL cannot copy file
  "/home/.../qTox/libs/libtoxcore-v0.2.2/libtoxcore.so.2.2.0"
  to "/usr/local/lib/libtoxcore.so.2.2.0".

Makefile:104: recipe for target 'install' failed
make: *** [install] Error 1

##### Expected Behavior

With the --local option it should install to a directory inside the source tree, but instead it attemps to install to a system directory

##### Additional Info

The bug seems to be introduced with commit:
https://github.com/qTox/qTox/commit/ead2152d6f0d15f7e662975fb3ed8525109794c3
Before that commit, or the last release (v1.15.0) still worked.
toxcore should be configured to install to "${BASE_DIR}" when --local is set.

**Comment by tox-user** [comment]
Can you test if it works with PR https://github.com/qTox/qTox/pull/5203 ?

**Comment by ghost** [comment]
Yes: I tested it and it works for me. Thanks.
