### ISSUE TITLE
Portable idea

### ISSUE THREAD

**Issue by fcore117** [qTox/qTox#52]
Maybe add portable support this way when someone makes "config" folder in toxgui folder then toxgui uses it instead of user profile.

**Comment by tux3** [comment]
This isn't planned at the moment. 
I try to follow the consensus, wich is to save the configuration in the user's profile (e.g. ~/.config/tox/ on linux)

I will probably add support for multiple accounts on the same computer and profile at some point, so people shouldn't need to make config folders.
Why do you need toxgui to be portable ?

**Comment by fcore117** [comment]
i always have used software in portable mode from usb hdd, with windows and linux too. Blender as example can use config folder if created manually, but by default it uses profile. For me portable is critical.

If you plan portable support i think it is easy to do, first search config folder if not exists then toxgui uses profile folder.

**Comment by tux3** [comment]
Okay. How about an option in the settings to simply save the profile in the working directory, like uTox does ?

**Comment by fcore117** [comment]
very good idea, where is toxgui own .ini setting written then?

**Comment by tux3** [comment]
Always along the tox_save, so if you enable the option it's in the working directory, and if you disable it it's in ~/.config/tox/ (like now).

**Comment by fcore117** [comment]
very very good, this is exactly like portable. Thanks.

**Comment by msteinbeck** [comment]
+1

**Comment by tux3** [comment]
This was fixed by the latest commit, closing.
