### ISSUE TITLE
Mac on first use, webcams/mic activated

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#520]
> [15:26:01] <Gabou> a friend of mine was running qtox on mac os x for the first time and he is very disappointed : it launched webcam + micro the first time

**Comment by tux3** [comment]
This should not be possible, unless the video preview was visible or a call was active.

Where is that qtox binary from ? Can I get a copy ?

**Comment by dubslow** [comment]
> <Gabou> bunslow: I'll ask him and see
> <toweI> Gabou:  what is the issue there? only that is uses the webcam and mic right from start without need?
> <Gabou> toweI: he launched qtox, and he saw the light of the webcam
> <Gabou> he didn't ask for a video or so, he didn't have any contact, first time
> <toweI> bunslow: I can confirm this for windows too
> <toweI> I am using the github binaries

**Comment by towlie** [comment]
@tux3 The same happens for me on windows. The application freezes (it is a blank window) at start until the webcam turns off (that makes qtox start time take 5 seconds). 
Using the github binaries.

**Comment by tux3** [comment]
Oooh, that would be the resolution probing then.

It shouldn't start the webcam at all. And certainly not the mic. Maybe that depends on the model of webcam.

I guess we could delay that until the first actual use of the webcam anyway.

**Comment by tux3** [comment]
This should work now, but I can't test since my webcam doesn't do that.

If you still have this bug, please leave a comment and I'll reopen.
A new version for windows should be available in ~15 minutes.

**Comment by towlie** [comment]
@tux3 It still happens and it happened already before your webcam probe commits if I remember right.

**Comment by tux3** [comment]
My jenkins build failed silently and uploaded an older release.

**Comment by dubslow** [comment]
...lmao

**Comment by tux3** [comment]
Okay, this windows release should work : https://github.com/tux3/qTox/releases/download/qtox-windows-1414153433.22/qTox-win32.zip

**Comment by towlie** [comment]
@tux3 qtox does not start "entrypoint "tox_derive_key_from_pass" was not found in DLL libtoxencryptsave-0.dll". Sounds like something of the latest toxcore commits.

**Comment by dubslow** [comment]
That's... odd. Nothing was changed regarding that particular function in the last week... at any rate, a toxcore update certainly wouldn't hurt.

**Comment by tux3** [comment]
I found another problem with my jenkins setup.

There's <a href="http://mlkj.bounceme.net:8080/job/qTox-win32/106/console">a new build in progress</a>  hopefully this time it'll work.

EDIT: download there https://github.com/tux3/qTox/releases/download/qtox-windows-1414156852.51/qTox-win32.zip

**Comment by towlie** [comment]
Issue fixed for windows. 
But I have a sidenote that the camera probe is slow and makes the camera LED blink for 5 seconds everytime you open the camera settings. Also those sliders there don't work. (well one slider worked but I cannot change it back)
Shall I make an other issue for that?

Well it is acutally 10s here and this also happens on every first video call started. (restart qtox > new video call > new 10 s waiting time)

**Comment by dubslow** [comment]
Yes

**Comment by zetok** [comment]
Issue still present on Linux, qTox 330ea59618ed5c3ad0fa44afac1d49a2426c2555

**Comment by MatejKovacic** [comment]
I have found out uTox 0.2.o (I am using it on Ubuntu 14.10) is accessing laptop camera all the time. If you run uTox and then try to run Cheese (app for video capturing), Cheese says that camera device is in use.

The fact is there is no video chat active in uTox, and it still is "blocking" camera.

**Comment by tux3** [comment]
This should be fixed with FFmpeg.
