### ISSUE TITLE
Triple-clicking selects entire message, regardless of which mouse button is pressed last

### ISSUE THREAD

**Issue by Hasshu** [qTox/qTox#5211]
(Left) double-clicking followed by right-clicking, wheel-clicking, or even pressing extra mouse buttons results in the entire message being selected. Seems to be ~~collateral damage~~ a side effect of #4305.

OS: Windows 7 Ultimate (64-bit)
qTox version: v1.15.0
Commit hash: 02d6c63acaac0ae95fa8be3a1b9301657e6a4a94
toxcore: v0.2.2
Qt: v5.9.4

**Comment by tox-user** [comment]
This is not a standard behaviour, but is it really a problem? Why?

**Comment by Hasshu** [comment]
It is a problem. When I need to, say, quote something I selected by double-clicking, I end up opening the context menu for the entire message instead. And having to wait before the third click is both unintuitive and inconvenient.
