### ISSUE TITLE
Please upload the signature for 1.16 release

### ISSUE THREAD

**Issue by farseerfc** [qTox/qTox#5217]
Seeing 1.16 is released 12 hours ago but no signatures from the developpers so far, please upload the signature as previous releases.
Thanks you.

**Comment by quantumpacket** [comment]
The tag is signed if you want to verify via git. `git tag --verify v1.16.0`

**Comment by farseerfc** [comment]
@quantumpacket yes thanks. But it will be more helpful to use [this script](https://github.com/qTox/qTox/blob/master/tools/create-tarball.sh) to create a seperate signature for the released souce code tarball.

**Comment by sudden6** [comment]
Done. Sorry, was busy fixing our CI for AppImage and Flatpak.

**Comment by farseerfc** [comment]
@sudden6 thank you!
