### ISSUE TITLE
Don't build

### ISSUE THREAD

**Issue by SergeyDjam** [qTox/qTox#5218]
##### Brief Description

OS: Linux (ROSA Linux R8.1 x86_64)  
qTox version:  >= 1.16.0
Commit hash:  
toxcore:  0.2.3
Qt:  5.6.1
Hardware:  Dell Inspiron 5040

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. download tar.gz pack from github
2. unpak to qtox-source dir
3. make -p build
4. cd build && cmake ..
5. make

result:
[ 77%] Linking CXX executable qtox
libqtox_static.a(coreav.cpp.o): In function `CoreAV::CoreAV(Tox*)':
coreav.cpp:(.text+0x1af): undefined reference to `toxav_new'
coreav.cpp:(.text+0x1d8): undefined reference to `toxav_callback_call'
coreav.cpp:(.text+0x1f6): undefined reference to `toxav_callback_call_state'
coreav.cpp:(.text+0x214): undefined reference to `toxav_callback_audio_bit_rate'
coreav.cpp:(.text+0x232): undefined reference to `toxav_callback_video_bit_rate'
coreav.cpp:(.text+0x250): undefined reference to `toxav_callback_audio_receive_frame'
coreav.cpp:(.text+0x26e): undefined reference to `toxav_callback_video_receive_frame'
libqtox_static.a(coreav.cpp.o): In function `CoreAV::~CoreAV()':
coreav.cpp:(.text+0x36b): undefined reference to `toxav_kill'
libqtox_static.a(coreav.cpp.o): In function `CoreAV::process()':
coreav.cpp:(.text+0xa9a): undefined reference to `toxav_iterate'
coreav.cpp:(.text+0xaaa): undefined reference to `toxav_iteration_interval'
libqtox_static.a(coreav.cpp.o): In function `CoreAV::answerCall(unsigned int, bool)':
coreav.cpp:(.text+0x13a6): undefined reference to `toxav_answer'
coreav.cpp:(.text+0x1454): undefined reference to `toxav_call_control'
libqtox_static.a(coreav.cpp.o): In function `CoreAV::startCall(unsigned int, bool)':
coreav.cpp:(.text+0x1a24): undefined reference to `toxav_call'
libqtox_static.a(coreav.cpp.o): In function `CoreAV::cancelCall(unsigned int)':
coreav.cpp:(.text+0x1eb3): undefined reference to `toxav_call_control'
libqtox_static.a(coreav.cpp.o): In function `CoreAV::sendCallAudio(unsigned int, short const*, unsigned long, unsigned char, unsigned int) const':
coreav.cpp:(.text+0x245a): undefined reference to `toxav_audio_send_frame'
libqtox_static.a(coreav.cpp.o): In function `CoreAV::sendCallVideo(unsigned int, std::shared_ptr<VideoFrame>)':
coreav.cpp:(.text+0x26dd): undefined reference to `toxav_video_set_bit_rate'
coreav.cpp:(.text+0x2781): undefined reference to `toxav_video_send_frame'
libqtox_static.a(coreav.cpp.o): In function `CoreAV::sendGroupCallAudio(int, short const*, unsigned long, unsigned char, unsigned int) const':
coreav.cpp:(.text+0x336e): undefined reference to `toxav_get_tox'
coreav.cpp:(.text+0x3392): undefined reference to `toxav_group_send_audio'
libqtox_static.a(coreav.cpp.o): In function `CoreAV::sendNoVideo()':
coreav.cpp:(.text+0x3bff): undefined reference to `toxav_video_set_bit_rate'
libqtox_static.a(coreav.cpp.o): In function `CoreAV::callCallback(ToxAV*, unsigned int, bool, bool, void*)':
coreav.cpp:(.text+0x40c3): undefined reference to `toxav_call_control'
libqtox_static.a(core.cpp.o): In function `Core::onGroupInvite(Tox*, unsigned int, TOX_CONFERENCE_TYPE, unsigned char const*, unsigned long, void*)':
core.cpp:(.text+0x1f96): undefined reference to `toxav_join_av_groupchat'
libqtox_static.a(core.cpp.o): In function `Core::joinGroupchat(GroupInvite const&) const':
core.cpp:(.text+0x532a): undefined reference to `toxav_join_av_groupchat'
libqtox_static.a(core.cpp.o): In function `Core::createGroup(unsigned char)':
core.cpp:(.text+0x55cd): undefined reference to `toxav_add_av_groupchat'
collect2: ошибка: выполнение ld завершилось с кодом возврата 1
make[2]: *** [CMakeFiles/qtox.dir/build.make:3333: qtox] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:106: CMakeFiles/qtox.dir/all] Ошибка 2
make: *** [Makefile:139: all] Ошибка 2

rpm -qa | grep tox
pidgin-plugin-tox-0.5.1-2-rosa2014.1.x86_64
qtox-1.15.0-1-rosa2014.1.x86_64
c-toxcore-0.2.3-1-rosa2014.1.x86_64
c-toxcore-devel-0.2.3-1-rosa2014.1.x86_64
lib64toxcore2-0.2.3-1-rosa2014.1.x86_64
lib64toxcore-devel-0.2.3-1-rosa2014.1.x86_64
lib64toxencryptsave2-0.2.3-1-rosa2014.1.x86_64
lib64toxav2-0.2.3-1-rosa2014.1.x86_64
lib64toxencryptsave-devel-0.2.3-1-rosa2014.1.x86_64
lib64toxav-devel-0.2.3-1-rosa2014.1.x86_64

cmake ..
-- using ccache
-- LIBAVCODEC LIBRARY_DIRS: 
-- LIBAVCODEC INCLUDE_DIRS: 
-- LIBAVCODEC CFLAGS_OTHER: 
-- LIBAVCODEC LIBRARIES:    avcodec
-- LIBAVCODEC found
-- LIBAVDEVICE LIBRARY_DIRS: 
-- LIBAVDEVICE INCLUDE_DIRS: 
-- LIBAVDEVICE CFLAGS_OTHER: 
-- LIBAVDEVICE LIBRARIES:    avdevice
-- LIBAVDEVICE found
-- LIBAVFORMAT LIBRARY_DIRS: 
-- LIBAVFORMAT INCLUDE_DIRS: 
-- LIBAVFORMAT CFLAGS_OTHER: 
-- LIBAVFORMAT LIBRARIES:    avformat
-- LIBAVFORMAT found
-- LIBAVUTIL LIBRARY_DIRS: 
-- LIBAVUTIL INCLUDE_DIRS: 
-- LIBAVUTIL CFLAGS_OTHER: 
-- LIBAVUTIL LIBRARIES:    avutil
-- LIBAVUTIL found
-- LIBEXIF LIBRARY_DIRS: 
-- LIBEXIF INCLUDE_DIRS: /usr/include/libexif
-- LIBEXIF CFLAGS_OTHER: 
-- LIBEXIF LIBRARIES:    exif
-- LIBEXIF found
-- LIBQRENCODE LIBRARY_DIRS: 
-- LIBQRENCODE INCLUDE_DIRS: 
-- LIBQRENCODE CFLAGS_OTHER: 
-- LIBQRENCODE LIBRARIES:    qrencode
-- LIBQRENCODE found
-- LIBSODIUM LIBRARY_DIRS: 
-- LIBSODIUM INCLUDE_DIRS: 
-- LIBSODIUM CFLAGS_OTHER: 
-- LIBSODIUM LIBRARIES:    sodium
-- LIBSODIUM found
-- LIBSWSCALE LIBRARY_DIRS: 
-- LIBSWSCALE INCLUDE_DIRS: 
-- LIBSWSCALE CFLAGS_OTHER: 
-- LIBSWSCALE LIBRARIES:    swscale
-- LIBSWSCALE found
-- SQLCIPHER LIBRARY_DIRS: 
-- SQLCIPHER INCLUDE_DIRS: /usr/include/sqlcipher
-- SQLCIPHER CFLAGS_OTHER: 
-- SQLCIPHER LIBRARIES:    sqlcipher
-- SQLCIPHER found
-- VPX LIBRARY_DIRS: 
-- VPX INCLUDE_DIRS: 
-- VPX CFLAGS_OTHER: 
-- VPX LIBRARIES:    vpx;m
-- VPX found
-- TOXCORE LIBRARY_DIRS: 
-- TOXCORE INCLUDE_DIRS: 
-- TOXCORE CFLAGS_OTHER: 
-- TOXCORE LIBRARIES:    toxcore;toxencryptsave;m;pthread
-- TOXCORE found
-- Checking for one of the modules 'toxav'
-- TOXAV not found
-- Checking for one of the modules 'toxencryptsave'
-- TOXENCRYPTSAVE not found
-- OPENAL LIBRARY_DIRS: 
-- OPENAL INCLUDE_DIRS: /usr/include/AL
-- OPENAL CFLAGS_OTHER: 
-- OPENAL LIBRARIES:    openal
-- OPENAL found
-- X11 LIBRARY_DIRS: 
-- X11 INCLUDE_DIRS: 
-- X11 CFLAGS_OTHER: 
-- X11 LIBRARIES:    X11
-- X11 found
-- XSS LIBRARY_DIRS: 
-- XSS INCLUDE_DIRS: 
-- XSS CFLAGS_OTHER: 
-- XSS LIBRARIES:    Xss
-- XSS found
-- Using platform extensions
-- GDK_PIXBUF LIBRARY_DIRS: 
-- GDK_PIXBUF INCLUDE_DIRS: /usr/include/gdk-pixbuf-2.0;/usr/include/libpng16;/usr/include/glib-2.0;/usr/lib64/glib-2.0/include
-- GDK_PIXBUF CFLAGS_OTHER: -pthread
-- GDK_PIXBUF LIBRARIES:    gdk_pixbuf-2.0;gobject-2.0;glib-2.0
-- GDK_PIXBUF found
-- GLIB LIBRARY_DIRS: 
-- GLIB INCLUDE_DIRS: /usr/include/glib-2.0;/usr/lib64/glib-2.0/include
-- GLIB CFLAGS_OTHER: 
-- GLIB LIBRARIES:    glib-2.0
-- GLIB found
-- GTK LIBRARY_DIRS: 
-- GTK INCLUDE_DIRS: /usr/include/gtk-2.0;/usr/lib64/gtk-2.0/include;/usr/include/pango-1.0;/usr/include/atk-1.0;/usr/include/cairo;/usr/include/pixman-1;/usr/include/gdk-pixbuf-2.0;/usr/include/libpng16;/usr/include/pango-1.0;/usr/include/freetype2;/usr/include/libpng16;/usr/include/harfbuzz;/usr/include/libxml2;/usr/include/freetype2;/usr/include/libpng16;/usr/include/harfbuzz;/usr/include/glib-2.0;/usr/lib64/glib-2.0/include
-- GTK CFLAGS_OTHER: -pthread
-- GTK LIBRARIES:    gtk-x11-2.0;gdk-x11-2.0;pangocairo-1.0;atk-1.0;cairo;gdk_pixbuf-2.0;gio-2.0;pangoft2-1.0;pango-1.0;gobject-2.0;glib-2.0;fontconfig;freetype
-- GTK found
-- FILTERAUDIO LIBRARY_DIRS: 
-- FILTERAUDIO INCLUDE_DIRS: /usr/include
-- FILTERAUDIO CFLAGS_OTHER: 
-- FILTERAUDIO LIBRARIES:    /usr/lib64/libfilteraudio.so
-- FILTERAUDIO found
-- using filteraudio
-- CMAKE_C_FLAGS: 
-- CMAKE_CXX_FLAGS:  -std=c++11 -fno-exceptions -fno-rtti -Wstrict-overflow -Wstrict-aliasing -Werror -fstack-protector-all -Wstack-protector -pthread -pthread
-- Configuring done
-- Generating done
-- Build files have been written to: /home/admin/rpmbuild/BUILD/qTox-1.16.1

no problem but make - problem

on <= 1.15.0 no problem

##### Additional Info
(links, images, etc go here)

----

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA%\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by eclipseo** [comment]
Your packaging of c-toxcore is wrong. Since 0.2.x, toxcore moved from automake to cmake and merged the previous 4 libraries libtoxav, libtoxcore, libtoxdns and libtoxencryptsave into one: libtoxcore

You need to rethink your SPEC to build with cmake and output only one library. See the build guide here: https://github.com/TokTok/c-toxcore/blob/master/INSTALL.md#unix-like

**Comment by tox-user** [comment]
Remove toxcore, build it with cmake and try again.

**Comment by SergeyDjam** [comment]
1. urpme -a toxcore
2. rpm -qa | grep tox

3. cmake
cmake -DCMAKE_BUILD_TYPE:STRING=Release -DUSE_FILTERAUDIO=1 STRIP=/bin/true -DCMAKE_INSTALL_PREFIX=/usr -DAUTOUPDATE_ENABLED=0 ..
-- The C compiler identification is GNU 4.9.4
-- The CXX compiler identification is GNU 4.9.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- using ccache
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Checking for one of the modules 'libavcodec'
-- LIBAVCODEC LIBRARY_DIRS: 
-- LIBAVCODEC INCLUDE_DIRS: 
-- LIBAVCODEC CFLAGS_OTHER: 
-- LIBAVCODEC LIBRARIES:    avcodec
-- LIBAVCODEC found
-- Checking for one of the modules 'libavdevice'
-- LIBAVDEVICE LIBRARY_DIRS: 
-- LIBAVDEVICE INCLUDE_DIRS: 
-- LIBAVDEVICE CFLAGS_OTHER: 
-- LIBAVDEVICE LIBRARIES:    avdevice
-- LIBAVDEVICE found
-- Checking for one of the modules 'libavformat'
-- LIBAVFORMAT LIBRARY_DIRS: 
-- LIBAVFORMAT INCLUDE_DIRS: 
-- LIBAVFORMAT CFLAGS_OTHER: 
-- LIBAVFORMAT LIBRARIES:    avformat
-- LIBAVFORMAT found
-- Checking for one of the modules 'libavutil'
-- LIBAVUTIL LIBRARY_DIRS: 
-- LIBAVUTIL INCLUDE_DIRS: 
-- LIBAVUTIL CFLAGS_OTHER: 
-- LIBAVUTIL LIBRARIES:    avutil
-- LIBAVUTIL found
-- Checking for one of the modules 'libexif'
-- LIBEXIF LIBRARY_DIRS: 
-- LIBEXIF INCLUDE_DIRS: /usr/include/libexif
-- LIBEXIF CFLAGS_OTHER: 
-- LIBEXIF LIBRARIES:    exif
-- LIBEXIF found
-- Checking for one of the modules 'libqrencode'
-- LIBQRENCODE LIBRARY_DIRS: 
-- LIBQRENCODE INCLUDE_DIRS: 
-- LIBQRENCODE CFLAGS_OTHER: 
-- LIBQRENCODE LIBRARIES:    qrencode
-- LIBQRENCODE found
-- Checking for one of the modules 'libsodium'
-- LIBSODIUM LIBRARY_DIRS: 
-- LIBSODIUM INCLUDE_DIRS: 
-- LIBSODIUM CFLAGS_OTHER: 
-- LIBSODIUM LIBRARIES:    sodium
-- LIBSODIUM found
-- Checking for one of the modules 'libswscale'
-- LIBSWSCALE LIBRARY_DIRS: 
-- LIBSWSCALE INCLUDE_DIRS: 
-- LIBSWSCALE CFLAGS_OTHER: 
-- LIBSWSCALE LIBRARIES:    swscale
-- LIBSWSCALE found
-- Checking for one of the modules 'sqlcipher'
-- SQLCIPHER LIBRARY_DIRS: 
-- SQLCIPHER INCLUDE_DIRS: /usr/include/sqlcipher
-- SQLCIPHER CFLAGS_OTHER: 
-- SQLCIPHER LIBRARIES:    sqlcipher
-- SQLCIPHER found
-- Checking for one of the modules 'vpx'
-- VPX LIBRARY_DIRS: 
-- VPX INCLUDE_DIRS: 
-- VPX CFLAGS_OTHER: 
-- VPX LIBRARIES:    vpx;m
-- VPX found
-- Checking for one of the modules 'toxcore'
-- TOXCORE not found
-- Checking for one of the modules 'toxav'
-- TOXAV not found
-- Checking for one of the modules 'toxencryptsave'
-- TOXENCRYPTSAVE not found
-- Checking for one of the modules 'libtoxcore'
CMake Error at cmake/Dependencies.cmake:74 (message):
  TOXCORE package, library or framework not found
Call Stack (most recent call first):
  cmake/Dependencies.cmake:129 (search_dependency)
  CMakeLists.txt:89 (include)


-- Configuring incomplete, errors occurred!
See also "/home/admin/rpmbuild/BUILD/qTox-1.16.1/build/CMakeFiles/CMakeOutput.log".
error: Неверный код возврата из /var/tmp/rpm-tmp.60648 (%build)


Ошибки сборки пакетов:
    Неверный код возврата из /var/tmp/rpm-tmp.60648 (%build)

**Comment by SergeyDjam** [comment]
cmake ..
-- The C compiler identification is GNU 4.9.4
-- The CXX compiler identification is GNU 4.9.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- using ccache
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Checking for one of the modules 'libavcodec'
-- LIBAVCODEC LIBRARY_DIRS: 
-- LIBAVCODEC INCLUDE_DIRS: 
-- LIBAVCODEC CFLAGS_OTHER: 
-- LIBAVCODEC LIBRARIES:    avcodec
-- LIBAVCODEC found
-- Checking for one of the modules 'libavdevice'
-- LIBAVDEVICE LIBRARY_DIRS: 
-- LIBAVDEVICE INCLUDE_DIRS: 
-- LIBAVDEVICE CFLAGS_OTHER: 
-- LIBAVDEVICE LIBRARIES:    avdevice
-- LIBAVDEVICE found
-- Checking for one of the modules 'libavformat'
-- LIBAVFORMAT LIBRARY_DIRS: 
-- LIBAVFORMAT INCLUDE_DIRS: 
-- LIBAVFORMAT CFLAGS_OTHER: 
-- LIBAVFORMAT LIBRARIES:    avformat
-- LIBAVFORMAT found
-- Checking for one of the modules 'libavutil'
-- LIBAVUTIL LIBRARY_DIRS: 
-- LIBAVUTIL INCLUDE_DIRS: 
-- LIBAVUTIL CFLAGS_OTHER: 
-- LIBAVUTIL LIBRARIES:    avutil
-- LIBAVUTIL found
-- Checking for one of the modules 'libexif'
-- LIBEXIF LIBRARY_DIRS: 
-- LIBEXIF INCLUDE_DIRS: /usr/include/libexif
-- LIBEXIF CFLAGS_OTHER: 
-- LIBEXIF LIBRARIES:    exif
-- LIBEXIF found
-- Checking for one of the modules 'libqrencode'
-- LIBQRENCODE LIBRARY_DIRS: 
-- LIBQRENCODE INCLUDE_DIRS: 
-- LIBQRENCODE CFLAGS_OTHER: 
-- LIBQRENCODE LIBRARIES:    qrencode
-- LIBQRENCODE found
-- Checking for one of the modules 'libsodium'
-- LIBSODIUM LIBRARY_DIRS: 
-- LIBSODIUM INCLUDE_DIRS: 
-- LIBSODIUM CFLAGS_OTHER: 
-- LIBSODIUM LIBRARIES:    sodium
-- LIBSODIUM found
-- Checking for one of the modules 'libswscale'
-- LIBSWSCALE LIBRARY_DIRS: 
-- LIBSWSCALE INCLUDE_DIRS: 
-- LIBSWSCALE CFLAGS_OTHER: 
-- LIBSWSCALE LIBRARIES:    swscale
-- LIBSWSCALE found
-- Checking for one of the modules 'sqlcipher'
-- SQLCIPHER LIBRARY_DIRS: 
-- SQLCIPHER INCLUDE_DIRS: /usr/include/sqlcipher
-- SQLCIPHER CFLAGS_OTHER: 
-- SQLCIPHER LIBRARIES:    sqlcipher
-- SQLCIPHER found
-- Checking for one of the modules 'vpx'
-- VPX LIBRARY_DIRS: 
-- VPX INCLUDE_DIRS: 
-- VPX CFLAGS_OTHER: 
-- VPX LIBRARIES:    vpx;m
-- VPX found
-- Checking for one of the modules 'toxcore'
-- TOXCORE not found
-- Checking for one of the modules 'toxav'
-- TOXAV not found
-- Checking for one of the modules 'toxencryptsave'
-- TOXENCRYPTSAVE not found
-- Checking for one of the modules 'libtoxcore'
CMake Error at cmake/Dependencies.cmake:74 (message):
  TOXCORE package, library or framework not found
Call Stack (most recent call first):
  cmake/Dependencies.cmake:129 (search_dependency)
  CMakeLists.txt:89 (include)


-- Configuring incomplete, errors occurred!
See also "/home/admin/rpmbuild/BUILD/qTox-1.16.1/build/CMakeFiles/CMakeOutput.log".

**Comment by SergeyDjam** [comment]
Thank you, @eclipseo. I rebuild toxcore.

**Comment by tox-user** [comment]
@SergeyDjam is your issue fixed?

**Comment by anthonybilinski** [comment]
Seems fixed, closing. Please re-open if you're still having problems.

**Comment by XXLCXX** [comment]
Путин - это фашист сыоего народа!!!
