### ISSUE TITLE
Write basic test for Core

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#5231]
The test should run at TravisCI and at least include:

- startup without proxy
- startup with invalid proxy
- loading of unencrypted save file
- loading of encrypted save file
- try loading a broken save file
- saving a save file

More tests and ideas welcome

**Comment by zetok** [comment]
- create profile
- delete profile
- encrypt profile
- decrypt profile
- rename profile
- delete history
- change password and check if new one works

**Comment by sudden6** [comment]
@zetok these are all operations that happen outside the `Core` module. The core module is only the wrapper around toxcore.

I think this would fit better in a new issue.

**Comment by zetok** [comment]
Oh, I see, I thought it was about core functionality.

**Comment by sudden6** [comment]
Basic tests for `Core` have been implemented here: https://github.com/qTox/qTox/blob/master/test/core/core_test.cpp
