### ISSUE TITLE
Rework our Travis CI setup

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#5233]
Currently a PR build takes at least 15min, which is quite long for the instant feedback.

Tasks:

-  check if we can reduce that time
- maybe don't execute all builds on every PR and create nightly builds via Travis Cron

**Comment by anthonybilinski** [comment]
Closing due to overhaul of CI system and switch to GH actions which is more parallel, the first linux builds now complete in ~5-6 mins, even though macOS and flatpak still take ~15mins, this should give faster feedback to users.
