### ISSUE TITLE
Popup window spam when illegal Windows filename is received by Linux client

### ISSUE THREAD

**Issue by a-no-n** [qTox/qTox#5242]
##### Popup window spam when illegal Windows filename is received by Linux client

OS: Linux (multiple distros tested)  
qTox version: 1.16.1
Commit hash: 4921b8868f02ddcfc06d617be886547d59a388d6
toxcore:  0.2.2
Qt:  5.11.1

Reproducible: Always

##### Steps to reproduce

1. From a Linux Tox client send a file whose name contains an illegal Windows character (e.g. ':') to a Linux qTox client

##### Observed Behavior
Without accepting the file (and for each file) qTox will open many (31) popups which need to be sequentially closed to use the main window again. The illegal characters get replaced with underscores.

##### Expected Behavior

Windows file renaming should not trigger for Linux clients

##### Additional Info
![qtox](https://user-images.githubusercontent.com/28546781/42727978-e1dd8f72-879f-11e8-9ac2-ae24c5167d31.png)

[19:56:38.300 UTC] core/corefile.cpp:327 : Debug: "Cleaned filename"
[19:56:38.300 UTC] core/corefile.cpp:333 : Debug: "Received file request 30:196608 kind 0"

**Comment by sudden6** [comment]
This is fixed in 291e86d9f9ea877fd92daa3b83ac283d56b305d5 but we need to push a new release.

**Comment by tox-user** [comment]
Wait it wasn't fixed in 1.16.0?

**Comment by tox-user** [comment]
Ok I guess this is a different bug than I thought.

**Comment by sudden6** [comment]
No unfortunately not.

**Comment by anthonybilinski** [comment]
The fix in 291e86d9f9ea877fd92daa3b83ac283d56b305d5 (which is part of now released v1.16.3) doesn't completely address this ticket. It does make it only open 1 dialogue instead of a bunch, but  "Windows file renaming should not trigger for Linux clients" is unchanged.
