### ISSUE TITLE
Feature request:  OTP support

### ISSUE THREAD

**Issue by Emily7777** [qTox/qTox#5255]
As amazing as qTox is, it still fails against keyloggers.

OTP or support for Only Key PGP chat feature would close that attack vector.

Anything like this planned?

**Comment by sudden6** [comment]
Can you elaborate a bit what this "Only Key PGP" thing is? I have never heard of it. Can you also elaborate how this protects against keyloggers?

**Comment by physkets** [comment]
Unless it means that you encrypt in your head, and type out in base64, it won't protect you from a key-logger.
