### ISSUE TITLE
Failed to open database

### ISSUE THREAD

**Issue by xif-fr** [qTox/qTox#5263]
##### Brief Description

qTox fails to open database (see error.log) and, therefore, some features don't work (it's not critical for me, but still a bit annoying).
This is an old bug I have (at least 6 month, maybe 1 year, I don't remember).
Note that I build qTox by hand (and it's always a bit hacky) because the binary is not compatible with 10.9 since a long time.
I would be happy to do some debug if a direction is given.

OS: OS X 10.9
qTox version: all versions for ~6 months, including latest
toxcore:  v0.2.* (at least, and including latest)
Qt:  5.8.0
sqlcipher:  latest (3.4.2)

Reproducible: Always

##### Steps to reproduce

1. Create a new profile

or

1. Open an existing profile

##### Observed Behavior

- Error log : Warning: Failed to open database for profile "a"
- Error message : qTox couldn't open your chat logs, they will be disabled.
- Faux offline messaging not working
- qTox crashes when "Keep chat history" is disabled

Full log : [error.log](https://github.com/qTox/qTox/files/2216062/error.log)

**Comment by anthonybilinski** [comment]
@xif-fr can you try creating a profile without a password? Does saving history work in that case?

**Comment by xif-fr** [comment]
Yes it works fine without password.

**Comment by anthonybilinski** [comment]
We've had other issues that were fixed with encrypted database loading, e.g. https://github.com/qTox/qTox/issues/5952 fixed in https://github.com/qTox/qTox/pull/6084.

If encrypted history still isn't working on v1.17.4, please comment and I'll re-open.
