### ISSUE TITLE
qTox crashes on Windows 8 when you select a web camera

### ISSUE THREAD

**Issue by Monsterovich** [qTox/qTox#5264]
##### Brief Description

OS: Windows 8.1
qTox version: v1.16.3

Works fine on my computer with Linux.

See video:
https://www.youtube.com/watch?v=ddAeEWZT8iU

**Comment by anthonybilinski** [comment]
Can you post qTox logs from the crash? Does it still crash if you select the webcam while not in a video call?

**Comment by Monsterovich** [comment]
>Can you post qTox logs from the crash?

If I only knew where are they on Windows.

>Does it still crash if you select the webcam while not in a video call?

No, it doesn't. But, it does when I take a call.

**Comment by tox-user** [comment]
On Windows the log is stored in: `%APPDATA%\tox\`.
I guess the full path would be something like: `C:/Users/YourUser/AppData/tox`

**Comment by anthonybilinski** [comment]
Not reproducible on tip and no logs provided, not much to go off here. Closing.
