### ISSUE TITLE
qTox v1.16.3 fails to start on XP 32bit - bcrypt.dll missing

### ISSUE THREAD

**Issue by ElLamparto** [qTox/qTox#5268]
It runs fine on Win7 32bit.

**Comment by Diadlo** [comment]
Windows XP is not supported by Microsoft for a long time. Not sure, that qTox does. @sudden6 what do you think?

**Comment by sudden6** [comment]
Seems to be a problem with Win XP if it runs on Win7, I don't think we should support such an old OS.

**Comment by ElLamparto** [comment]
Well, quite a lot of people still use XP, especially in companies. My mother use it too and until her HD dies, she will not upgrade OS. qTox 1.11.0 works fine on XP.

If keeping XP compatibility costs a lot, maybe it is better to give up.
However if it is a matter of adding a few dlls to the installator, please do it.

Thanks :)

**Comment by sudden6** [comment]
I think it's not as simple as adding a dll, because Qt doesn't support XP anymore. You can still try though.

I'll close this as wontfix as the consensus seems to be that XP is not worth the trouble anymore.
