### ISSUE TITLE
qtox sliders in video/audio settings don't work (windows)

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#527]

**Comment by tux3** [comment]
The audio sliders are not supposed to work, as for the video sliders I think that your webcam simply does not support this.

Maybe there's a way to detect that and disable the sliders.

**Comment by towlie** [comment]
One slider worked but I could not change it back. I don't know which it was because qtox resets.
I only noticed that the video was brighter
I would not call it brighter, it's more colorless now.
So I cannot change it back.

**Comment by towlie** [comment]
Comment updated.

**Comment by krepa098** [comment]
Well it's black and white for me :)

Unfortunately the value range for brightness, saturation etc. seems to be driver dependent. Currently it's from 0 to 1 but your driver could expect values from lets say 0 to 255 and there is no way to query the expected value range.

**Comment by towlie** [comment]
Yes black and white fits better. The problem ist that I cannot change it back.

**Comment by tux3** [comment]
Maybe query the value of the slider on the first start, if it's <=1 chances are it's in [0,1], otherwise it's probably in [0,255] ?

**Comment by towlie** [comment]
About the driver thing: I am using the windows 7 standard driver for a notebook VGA camera.

**Comment by krepa098** [comment]
From Skype I got:
Brightness -64 to 127
Saturation 0 to 128
Hue -40 to 40
Contrast 0 to 127

**Comment by towlie** [comment]
I got:
Brightness -127 to 127
Contrast 0 to 64
Hue -90 to 90
Saturation 0 to 100
Other things:
Sharpness 0 to 4
Gamma 1 to 9
White balance 2800 to 6500
Background 0 to 2
@tux3 so the cam should support it?

**Comment by agilob** [comment]
There is something wrong with it:
1. set brightness ~50% 
2. restart qtox
3. check preview
5. preview is very dark
6. set to 100% to see it as it was before restarting

It happened to me a few times with different sliders.

**Comment by tux3** [comment]
> @tux3 so the cam should support it?

It Just Works™ with my webcam right now, but I'm not sure how to get it to work with every webcam. What I said earlier was a stupid idea.

**Comment by towlie** [comment]
I think skype doesn't change the webcam settings directly. It uses a windows function. (It pops out a generic window which other programms call too)

**Comment by bricky149** [comment]
Skype calls the driver's settings for the device. Maybe qTox should do the same instead of trying to map different devices' settings to each slider.

**Comment by cotti** [comment]
Yeah, other programs that feature camera support (OBS, etc) can call upon the driver's settings and use them as a baseline for further modifications inside the application if necessary. 

It should be the primary source of values (brightness, contrast, hue, etc) and _then_ qTox can offer an override if the user wishes to, with a checkbox or something to enable the sliders.

**Comment by tux3** [comment]
The audio sliders work, and the video sliders are gone, closing.
