### ISSUE TITLE
UDP setting

### ISSUE THREAD

**Issue by Neilglee** [qTox/qTox#5276]
I recently changed from ADSL to Fibre, when I enable the UDP setting in QTox my browser and connection stop working. Have tried all the inbound firewall rules and nothing
OS: Windows 7 SP 1 (6.1)
qTox version: v1.16.1
Commit hash: 4921b8868f02ddcfc06d617be886547d59a388d6
toxcore: 0.2.3
Qt: 5.9.6
Hardware: 
Win 7 64 bit …
Firefox Quantum up tp date
Reproducible: Always 

##### Steps to reproduce

1. activate udp in qtox
2. 
3. …

##### Observed Behavior
browser and internet stop working

##### Expected Behavior
To work

##### Additional Info
(links, images, etc go here)

----

More information on how to write good bug reports in the wiki: https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by sudden6** [comment]
This is a known problem with some routers and already tracked in https://github.com/qTox/qTox/issues/4249 and https://wiki.tox.chat/users/troubleshooting

You can only disable UDP for now or get a different router.

**Comment by Neilglee** [comment]
Hi Thank you for the prompt reply, unfortunately the router is supplied and managed by the ISP and will not let me use my own router. the router supplied is a mikro tik hAP ac Lite.
I have disabled the udp and even asked the isp about the problem, they enabled the upnp which is not a good idea so i disabled it.

    On Saturday, 28 July 2018, 12:42:45 GMT+2, sudden6 <notifications@github.com> wrote:  
 
 
This is a known problem with some routers and already tracked in #4249 and https://wiki.tox.chat/users/troubleshooting

You can only disable UDP for now or get a different router.

**Comment by fcore117** [comment]
I have told similar years ago that Tox is quite bad for network especially when family tries to use behind one router, family i tested Tox was same story that router is by ISP that gives internet and IPTV.

i wish developers luck on finding good robust solution for network massive usage. I have watched Tox progress almost from beginning and i have tested Tox wit lot of different situations.

Now that Skype 8 has become true bloatware that is worst than ever and world needs light in future that is offered by Tox.

**Comment by anthonybilinski** [comment]
What's causing the problem isn't really massive network usage, it's more the large number of connections being tracked by your router when Tox is in UDP mode and connecting to many nodes in the DHT.

The problem should be completely fixed by going to settings -> Advanced -> uncheck "Enable UDP". If you still experience problems after that, please re-open the issue.
