### ISSUE TITLE
Error on MacOS with qTox Source Code

### ISSUE THREAD

**Issue by shyamalschandra** [qTox/qTox#5277]
I get the following error on MacOS High Sierra 10.13.6 with qTox Source Code when following the instructions on the source code installation:

```
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
CMake Error at cmake/Dependencies.cmake:9 (find_package):
  By not providing "FindQt5Concurrent.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5Concurrent", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Concurrent"
  with any of the following names:

    Qt5ConcurrentConfig.cmake
    qt5concurrent-config.cmake

  Add the installation prefix of "Qt5Concurrent" to CMAKE_PREFIX_PATH or set
  "Qt5Concurrent_DIR" to a directory containing one of the above files.  If
  "Qt5Concurrent" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:90 (include)


-- Configuring incomplete, errors occurred!
```

What is missing in Qt5Concurrent in clear English?

Why isn't this patched yet?  Do you test the source build against the latest version of OSX?

Thanks!

**Comment by sudden6** [comment]
Which instructions did you follow exactly? The script or the manual way?

The error points to a Qt5 module, either your Qt installation is too old or not correctly installed.

The script is tested on Travis CI on every commit and it's not broken at the moment. I don't know which OSX version is used on Travis CI.

**Comment by shyamalschandra** [comment]
Okay, thanks!  Bye.  This product is broken.
