### ISSUE TITLE
Provide sign for *.zip or *.tar.gz

### ISSUE THREAD

**Issue by EGD** [qTox/qTox#5278]
Please, provide sign file *.zip.asc or *.tar.gz.asc.
This is necessary to verify the archive signature for creating the openSUSE package.

**Comment by sudden6** [comment]
why can't openSUSE not use our provided and signed *.tar.lz files?

**Comment by EGD** [comment]
Comment from package maintainer:
> Also i want not lz-packages, because lzip is not in standard install of distro.

**Comment by sudden6** [comment]
fair enough, I'll see if we can override the GH provided tar.gz with our own signed ones.

**Comment by physkets** [comment]
I think most packages are moving to the `.xz` format (for eg. the [linux kernel](https://www.kernel.org/minor-changes-to-tarball-release-format.html)). So maybe that would be a better option?

**Comment by anthonybilinski** [comment]
That would remove any hurdle of overriding the GH provided uploads. @sudden6 should I go ahead and upload a signed .xz for 1.16.3, or is there a reason to wait for 1.17.0?

**Comment by sudden6** [comment]
no, I see no problem uploading one at the moment

**Comment by anthonybilinski** [comment]
Reading this over again, EGD specifically requested `.zip` or `.tar.gz`, so maybe a `.tar.xz` wouldn't fix anything.

@EGD would a `.tar.xz` be acceptable for openSUSE package creation?

**Comment by EGD** [comment]
> would a .tar.xz be acceptable for openSUSE package creation?

in future yes

**Comment by anthonybilinski** [comment]
@EGD the signed .tar.gz has been added to v1.16.3 release, and will continue to be available in future releases.

**Comment by EGD** [comment]
@anthonybilinski, please, check

v1.16.3.tar.gz.asc contains _BAD signature_

```
> LANG=C gpg --verify v1.16.3.tar.gz.asc 
gpg: assuming signed data in 'v1.16.3.tar.gz'
gpg: Signature made Tue Aug 28 23:06:41 2018 MSK
gpg:                using RSA key 0x2AA8E0DA1B31FB3C
gpg: BAD signature from "Anthony Bilinski <me@abilinski.com>" [unknown]
```

v1.16.3.tar.lz.asc verified correctly
```
> LANG=C gpg --verify v1.16.3.tar.lz.asc 
gpg: assuming signed data in 'v1.16.3.tar.lz'
gpg: Signature made Sat Jul 21 01:09:27 2018 MSK
gpg:                using RSA key 0x2AA8E0DA1B31FB3C
gpg: Good signature from "Anthony Bilinski <me@abilinski.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 7EB3 39FE 8817 47E7 01B7  D472 EBE3 6E66 A842 9B99
     Subkey fingerprint: 74AD B7A7 F8EC C100 9916  C4E4 2AA8 E0DA 1B31 FB3C
```

**Comment by anthonybilinski** [comment]
I just downloaded from github and verified the signature and it looks correct here:
```
$ gpg2 --verify v1.16.3.tar.lz.asc 
gpg: assuming signed data in 'v1.16.3.tar.lz'
gpg: Signature made Fri 20 Jul 2018 03:09:27 PM PDT
gpg:                using RSA key 2AA8E0DA1B31FB3C
gpg: Good signature from "Anthony Bilinski <me@abilinski.com>" [ultimate]
$ gpg2 --verify v1.16.3.tar.gz.asc 
gpg: assuming signed data in 'v1.16.3.tar.gz'
gpg: Signature made Tue 28 Aug 2018 01:06:41 PM PDT
gpg:                using RSA key 2AA8E0DA1B31FB3C
gpg: Good signature from "Anthony Bilinski <me@abilinski.com>" [ultimate]
```
Are you sure you're checking the right file? Could you try re-downloading in an empty directory to make sure? If there's still a problem I'm not sure what's going on..

**Comment by EGD** [comment]
sorry, my bad

**Comment by physkets** [comment]
@anthonybilinski Sorry, I wasn't clear. I'd meant replacing the `.lz` one with a `.xz`, while retaining the `.gz` for legacy reasons, and then removing it at a later point in time. The XZ format uses an a newer version of the LZMA algorithm.
