### ISSUE TITLE
[Windows] qTox crashes sending/receiving messages from uTox

### ISSUE THREAD

**Issue by DanTheBritish** [qTox/qTox#528]
Binary from this release: https://github.com/tux3/qTox/releases/tag/qtox-windows-1414164457.49
Latest uTox build on Jenkins. Both clients running on Windows x64.

Only tested with uTox, don't have any other clients to test with right now.

I would provide logs but I don't see a way to find them.

**Comment by tux3** [comment]
This is due to a missing DLL, you can use an older release in the meantime and I will upload a new one soon.

**Comment by tux3** [comment]
The fixed version is available here : https://github.com/tux3/qTox/releases/download/qtox-windows-1414171836.15/qTox-win32.zip

If you still have this bug with the new version please leave a comment and I'll reopen.

**Comment by DanTheBritish** [comment]
Crash still occurs with the build you linked.

**Comment by tux3** [comment]
Strange, it worked with wine.

I'll try on windows.

**Comment by ghost** [comment]
hey, i just tried this version: https://github.com/tux3/qTox/releases/tag/qtox-windows-1414171836.15

always crashes when i send a message to someone :/

**Comment by agilob** [comment]
not sure if related, but version from today doesn't have sound in call with uTox. qTox from two days ago works fine. uTox user can hear me, I can't hear them.

**Comment by tux3** [comment]
I found the problem, more missing DLLs.

@agilob it's probably not related, you should make a new issue

**Comment by DanTheBritish** [comment]
Messaging is indeed fixed in the newest build. Thanks.
