### ISSUE TITLE
qTox crashes when I select Audio/Video in settings

### ISSUE THREAD

**Issue by ToxFox** [qTox/qTox#5281]
##### Brief Description

OS: Windows 10 Home 64 bit
 qTox version: v1.16.3.
Commit hash: 8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.3
Qt:  5.9.6
Hardware:  
HP ENVY 17 Notebook PC
Camera built in: HP Truevision HD

Reproducible: Always 

##### Steps to reproduce

1. Open settings
2. go to Audio/Video
3. select by clicking
4. the camera led going on, nothing else, then after about 2 sec. qTox delete itself.

##### Observed Behavior
qTox delete itself...
next step is new login with PW

##### Additional Info
[Report.txt](https://github.com/qTox/qTox/files/2258793/Report.txt)

**Comment by Eolia** [comment]
Hi,
Same issue on Win7 64 bits

**Comment by tox-user** [comment]
Can you upload the log?

**Comment by Eolia** [comment]
![image](https://user-images.githubusercontent.com/10416885/43999588-a1e7cf1e-9e0f-11e8-91e3-8b2c651fae85.png)

I don't see anything in the log :-/
[error.log](https://github.com/qTox/qTox/files/2280790/error.log)

**Comment by tox-user** [comment]
From what I can see it crashes soon after this:
```
video/camerasource.cpp:271 : Debug: Opening device "none" subscriptions: 1
video/cameradevice.cpp:152 : Debug: Tried to open the null device
video/camerasource.cpp:284 : Warning: Failed to open device!
platform/camera/directshow.cpp:174 : Warning: Could't find the device  ""
widget/form/settings/avform.cpp:389 : Debug: available Modes:
widget/form/settings/avform.cpp:298 : Debug: selected Modes:
audio/backend/openal.cpp:680 : Debug: Audio source 3 created. Sources active: 1
audio/backend/openal.cpp:244 : Debug: Subscribed to audio input device [ 1 subscriptions ]
```

**Comment by Eolia** [comment]
Well it worked right after installation.
The webcam works and is recognized by other software.

I will try to reinstall the driver of the cam ...

**Comment by Eolia** [comment]
Same problem after removing / reinstalling the cam driver.

**Comment by ToxFox** [comment]
@tox-user 

here the log from the last break down after clicking in settings on Audio/Video

[qtox.log](https://github.com/qTox/qTox/files/2284722/qtox.log)

**Comment by anthonybilinski** [comment]
Looks like the issue was closed accidentally, re-opening.

**Comment by tox-user** [comment]
Looks like this might be the crash:
```
audio/backend/openal.cpp:680 : Debug: Audio source 3 created. Sources active: 1
video/camerasource.cpp:388 : Debug: Closing device "none" subscriptions: 0
audio/backend/openal.cpp:244 : Debug: Subscribed to audio input device [ 1 subscriptions ]
video/camerasource.cpp:271 : Debug: Opening device "video=@device_pnp_\\\\?\\usb#vid_0bda&pid_5775&mi_00#7&6ce6ce6&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\\global" subscriptions: 1
```

**Comment by tox-user** [comment]
Did we have any audio or video refactors lately?

**Comment by tox-user** [comment]
@ToxFox, @Eolia have you enabled experimental audio backend?

**Comment by Eolia** [comment]
@ToxFox Yes but now I can't remove it :-(

**Comment by ToxFox** [comment]
@tox-user 
about I can not open the Audio/Video frame, I cannot tell you if I enabled oder not the "experimental audio backend"......... sorry.
But it can be, I do not remember.
And as long as I can not open it, I can not change.........
A proverb : Cat is bite in her own tail.......
I think, I have to reinstall the programm?

**Comment by tox-user** [comment]
There might be a way to fix this, but I'm not sure. @qTox/core, @qTox/windows-team is there a way to edit settings and disable experimental audio backend?

**Comment by sudden6** [comment]
I don't think one can manually edit the settings, but backing up the ini files and then removing them should start with fresh settings.

**Comment by Eolia** [comment]
![image](https://user-images.githubusercontent.com/10416885/44252150-8846ba80-a1fb-11e8-9b1e-fcdb3a4ddc64.png)
Ok, thanks, after deleting my profile.ini everything is working again.

**Comment by ToxFox** [comment]
Heureka !  I did it.
Deleting the Audio and Video Part in the qTox ini file and safe it. 
Then start the programm and open the settings. 
Open the Audio/Video-Frame and that works. Nothing happens. Then click in the frame the "experimenal....." to of.  After a few seconds the programm break down! 
BUT After restarting, all is working well now. 
I checked it two times.......
Hope that solve the problem permanently.
THANKS at all !!!

**Comment by anthonybilinski** [comment]
Glad deleting the section from profile.ini is a good workaround. Root cause looks is a duplicate of #5292.

**Comment by Eolia** [comment]
Curious ... it would be rather [https://github.com/qTox/qTox/issues/5292](#5292) which is a duplicate of this original post ^^

**Comment by anthonybilinski** [comment]
That's true, but the other issues' title and comments were more on topic to the actual bug so I decided to keep that one. Either way both are linked.
