### ISSUE TITLE
Add: Automatic spelling checker

### ISSUE THREAD

**Issue by ANrd3243** [qTox/qTox#5282]
Specially russian,

**Comment by Diadlo** [comment]
@ANrd3243 please, fill issue template

**Comment by sudden6** [comment]
This is implemented for Linux and Mac on master and will be in the next release. You can also compile from source to have it now.

**Comment by tox-user** [comment]
Does the spell check not work on Windows?

**Comment by sudden6** [comment]
No, the needed library is not built, as well as the dictionary backend. Probably needs updates for the build script.

**Comment by anthonybilinski** [comment]
I created https://github.com/qTox/qTox/issues/5316 to address adding required dependencies to Windows build. This issue has nothing else actionable, closing.
