### ISSUE TITLE
Why use qTox to transfer file, file ID change?

### ISSUE THREAD

**Issue by kpwd** [qTox/qTox#5283]
OS: Windows
qTox version: 1.16.3
Commit hash: 8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.3
Qt:  5.9.6

Reproducible: Always

1. Use qTox  to send a file 
2. My client use function "tox_file_get_file_id()" to get file id
3. When I use qTox  to send a file  ,file id always change ,but file id of avatar not change

##### Observed Behavior
file id always change when try send file 

##### Expected Behavior
file id always not change when try send file 

##### Additional Info
(links, images, etc go here)

Sorry,I am poor at English~
Looking forward to hearing from you

**Comment by anthonybilinski** [comment]
Just tested and file hash did not change (would would be a very big problem). Going to rename the issue to focus on file ID changing instead of file hash.

**Comment by kpwd** [comment]
oh,maybe...but how to get file hash?(client is file receiver )

**Comment by sudden6** [comment]
Probably not relevant anymore
