### ISSUE TITLE
New message Notify Focus should NOT be the default setting

### ISSUE THREAD

**Issue by MadBertus** [qTox/qTox#5284]
##### Brief Description
OS: Windows 7 / Lubuntu 
qTox version: 1.15.0. & idk

Reproducible: Always on current versions

##### Expected Behavior
Unintrusive & not obnoxious and actually quite amazing instant messanger

##### Steps to reproduce
1. Do something and have Tox turned on.
2. Go to kill your currently opened program with Alt+F4, yet get new message on tox, so it becomes the main active program, and the alt+F4 kills it instead of the intended target.
3. Realize there s an option to turn off the Focus Window of new message and turn it off, be satisfied with qtox for a while.
4. Reboot, and then relive steps 1 & 2, because qtox didnt save the settings and its again in defaults.
5. Repeat step 4 couple of times till it pisses you off enough, so it gets you to writes to the devs
6. Write to the devs of qTox on github, and hope they will fix it soon.

##### Observed Behavior
Pissing people off with new message Focus Window & it being the default settings

**Comment by anthonybilinski** [comment]
Are you using Cinnamon? If so I think it's a Cinnamon bug that we've seen before, duplicate of https://github.com/qTox/qTox/issues/4301. 

I opened this ticket https://github.com/linuxmint/Cinnamon/issues/6926 in Cinnamon's repo but haven't gotten a reply.

If not, is the checkbox actually checked the second time, or looks unchecked but behaves like it is checked?

**Comment by MadBertus** [comment]
Nope, its Lubuntu 18.04 so LXDE, also I m using qTox there as appImage if that has some relevance. Got the same issue on Windows 7 SP1 tho.

Yes the checkbox is always checked after reboot.

**Comment by sudden6** [comment]
Seems to be a problem of not saving the settings correctly then. Are other settings from that page saved correctly for you?

**Comment by MadBertus** [comment]
Nope, doesnt seem to be saving even any other settings on that page. But as the issue title says - my main problem is that the Focus window is turned on by default, so even if you would be new user, you would still need to go to settings to prevent the extremely annoying behaviour of qTox, while the default settings should be something that majority of the users will be satisfied with "out of the box", without any needed change to make the experience bearable. So imho the change of default settings should have bit higher priority before saving of the settings, although yes, the not saving settings are quite annoying too.

**Comment by tox-user** [comment]
I don't think this setting is on by default. I've never seen it happen. I didn't even know qTox had such feature until now.

Can you give us a log?

**Comment by sudden6** [comment]
I also just noticed, you're using an old qTox version, try updating to 1.16.x first.

**Comment by anthonybilinski** [comment]
Default for "Focus Window" is `true`: https://github.com/qTox/qTox/blob/7ff1d6053a57a29ee6fcc062feb32894c848f415/src/persistence/settings.cpp#L210


I agree with @FP4 that it should default `false`. It seems intrusive to grab focus and interrupt whatever's being done on any new message by default. I'll open a PR to make the change, let me know if anyone thinks default to `true` is preferred in general case.
