### ISSUE TITLE
qTox crashes on ubuntu 16.04

### ISSUE THREAD

**Issue by zoff99** [qTox/qTox#5290]
##### Brief Description

OS: Linux ubuntu 16.04
qTox version:  
Commit hash:  unsure
toxcore:  
Qt:  system installed
Hardware:  
…

Reproducible: Always

crash in Widget::onTryCreateTrayIcon()

if i change the function to:
```
void Widget::onTryCreateTrayIcon()
{
        disconnect(timer, &QTimer::timeout, this, &Widget::onTryCreateTrayIcon);
        if (!icon) {
            qWarning() << "No system tray detected!";
            show();
        }
}
```
then it works fine

**Comment by tux3** [comment]
When qTox starts up, it should output something like ` widget/systemtrayicon.cpp:83 : Debug: Using the Qt backend`. It can also show `Using GTK backend` or `Using Unity backend`. 

Can you tell which one of those qTox is outputing (if any)?

I've tried all three on a fresh Ubuntu 16.04.5, but I can't reproduce so if you know how to get a backtrace, that would also be very helpful.

Thanks for the report

**Comment by zoff99** [comment]
@tux3 i did not specify the commit hash used, because i am not sure if this happens with master.
issue is a placeholde so that i dont forget.
let me check the actual version ...

**Comment by zoff99** [comment]
@iphydf what version of qTox are you using in toktok-stack ? is it changed from the original source?

**Comment by tox-user** [comment]
Try using qTox 1.16 or current master and see if this problem keeps happening (then tells us in what version). If not you should report it in https://github.com/toktok/qTox repository instead (if that's what you are using).

**Comment by sudden6** [comment]
No response, closing.
