### ISSUE TITLE
qTox crashes if "Enable experimental audio backend" is checked on Audio/Video settings

### ISSUE THREAD

**Issue by dumabg** [qTox/qTox#5292]
##### Brief Description

OS: Windows 10 Pro 1803  
qTox version: 1.16.3
Commit hash:  8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.3
Qt: 5.9.6
Hardware:  
laptop MSI GL72M 7RDX

Reproducible: Always

##### Steps to reproduce

1. Check "Enable experimental audio backend" on Audio/Video settings
2. Close qTox
3. Open qTox and go to Audio/Video settings.
4. Crash
[qtox.txt](https://github.com/qTox/qTox/files/2282609/qtox.txt)

**Comment by tox-user** [comment]
I think it crashes here:
```
audio/backend/openal.cpp:680 : Debug: Audio source 3 created. Sources active: 1
video/camerasource.cpp:388 : Debug: Closing device "none" subscriptions: 0
video/camerasource.cpp:271 : Debug: Opening device "video=@device_pnp_\\\\?\\usb#vid_0bda&pid_5775&mi_00#7&6ce6ce6&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\\global" subscriptions: 1
```

Looks similar to: https://github.com/qTox/qTox/issues/5281. Does it only happen with experimental audio backend enabled?

**Comment by HoraceBianchon** [comment]
I my case it crashes here:

`audio/backend/openal2.cpp:330    alcRenderSamplesSOFT(alProxyDev, outBuf, AUDIO_FRAME_SAMPLE_COUNT_PER_CHANNEL);`

**Comment by HoraceBianchon** [comment]
When I compile with openal 1.16.0 (coming with "D:\qTox\windows\cross-compile\build.sh" in my pc) it crash in point that I wrote in previous comment. With openal 1.18.2 it works without crash.

Can someone check that?

**Comment by tox-user** [comment]
@qTox/windows-team has the version of openal been changed in Windows build lately?

**Comment by dumabg** [comment]
Yes, it only crash if experimental audio backend is enabled

**Comment by sudden6** [comment]
I could not see any relevant changes in the build script: https://github.com/qTox/qTox/commits/master/windows/cross-compile/build.sh recently.

**Comment by tbertels** [comment]
Note that the only way to disable this preference is then to edit the qtox.ini file and to change enableBackend2 to false. Not very user friendly.
So it may be a good idea to add a preference cleanShutdown. It would be checked when starting qTox:
* if false: disable experimental preferences
* if true: set to false
And when closing qTox, it would be switched to true.

**Comment by anthonybilinski** [comment]
The experimental audio backend was removed in 4f7056385f5f0619b00cad354d2ea9b49e369f0b, which effects qTox v1.17.0 forward, closing.
