### ISSUE TITLE
Newest user to group chat always displays as <Empty>

### ISSUE THREAD

**Issue by zellchristensen** [qTox/qTox#5294]
##### Brief Description

OS: Windows 7
qTox version: v1.16.3
Commit hash:  8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.3

Reproducible: Seems always

##### Steps to reproduce

1. Invite user to new or existing group chat.
2. User must accept invite

##### Observed Behavior

The newest user to join has their display name as \<Empty\> to all existing users.
The new user sees the user list correctly on join.

![2018-08-15_12-49-50](https://user-images.githubusercontent.com/38737447/44163807-ea94a380-a0b3-11e8-920a-40ad2c4c5018.png)

##### Expected Behavior

The user's display name should be displayed in the list.

##### Additional Info

Changing your own display name fixes the problem for the \<Empty\> but if any other user changes their display name, it won't be updated if you ever had the \<Empty\> issue.

**Comment by tox-user** [comment]
Confirmed. It's an old bug that has been haunting us for a few releases now.
