### ISSUE TITLE
Download link broken

### ISSUE THREAD

**Issue by jpfleury** [qTox/qTox#5296]
On the page https://tox.chat/download.html the download link for Linux qTox AppImage 64-bit is broken (page not found on Github).

The broken link is https://github.com/qTox/qTox/releases/download/v1.16.3/qTox-v1.16.3.x86_64.AppImage

**Comment by sudden6** [comment]
It seems v1.16.3 and v1.16.2 are missing the `x86_64` part from the AppImage filename.

**Comment by anthonybilinski** [comment]
Problem explanation and proposed solution: https://github.com/qTox/qTox/pull/5271#issuecomment-416821582.

**Comment by sudden6** [comment]
Link is working again.
