### ISSUE TITLE
Group chats lost on restart

### ISSUE THREAD

**Issue by Tcll** [qTox/qTox#5301]
##### Brief Description
any created Group chats are lost on restart
I can't confirm contacts because I haven't added any

OS: Linux (Xubuntu 16.04.3)  
qTox version: v1.16.3 
Commit hash:  8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.3
Qt:  5.7.1

##### Hardware:  
    CPU: AMD Athlon II x2 2.73GHz
    RAM: 2x 2GB DDR3 (probably 1600MHz if not 1333MHz)
    GPU: Galaxy Nvidia GeForce Gt 430 PCIe 1GB

Reproducible: Always

##### Steps to reproduce

(from new user install)
1. Download and run (configuring executable) qTox-v1.16.3.AppImage
2. Configure your profile, and add some group chats (optionally type some stuff)
3. restart

##### Observed Behavior

the contacts pane is completely empty after restart

##### Expected Behavior

created group chats should remain

I should note that I'm not using portable mode

**Comment by anthonybilinski** [comment]
This is unfortunately a limitation of the upstream core library. See https://github.com/qTox/qTox/issues/896.

Toxcore may add this functionality "soon" https://github.com/TokTok/c-toxcore/pull/1069, after which qTox will integrate it with high priority.

Contacts are persistent (as well as their history, if you have history enabled).

Closing as duplicate.

**Comment by mb720** [comment]
As this is now said to be fixed in toxcore, are there plans to have persistent groups in qTox?

**Comment by anthonybilinski** [comment]
qTox has persistent groups in nightlies, available at https://github.com/qTox/qTox-nightly-releases/releases/ci-master-latest but we haven't made a release since adding support. The next release is tracked here: https://github.com/qTox/qTox/milestone/23.
