### ISSUE TITLE
[Regression] Audio calls don't work anymore

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#532]
https://gist.github.com/dubslow/717e0376be858010bd80

Several thousand lines of the same; I called audiobot.

**Comment by dubslow** [comment]
Okay, confirmed older commit worked, `git bisect`ing now

**Comment by tux3** [comment]
Thanks, I was about to ask :)

**Comment by dubslow** [comment]
Aww fuck, segfaulted while I tried to send ~20 files to keep audiobot occupied...

**Comment by dubslow** [comment]
Well audiobot is dead ATM, but 6caa9f1e9fd1820a27ed25326176882b22d47f5e works at least

**Comment by dubslow** [comment]
Audiobot is being flaky and I'm getting bored, so shelving the bisect for now

**Comment by agilob** [comment]
fixed here, tested with audiobotze.
