### ISSUE TITLE
Issue with adding users to group?

### ISSUE THREAD

**Issue by docelic** [qTox/qTox#5323]
##### Brief Description

OS: Linux (Devuan Ascii )
qTox version: You are using qTox version v1.16.3-80-g7ff1d605.
Commit hash:  7ff1d6053a57a29ee6fcc062feb32894c848f415
toxcore:  0.2.3
Qt:  5.7.1
Hardware:  Lenovo Carbon X1
…

Reproducible: Always

##### Steps to reproduce

1. Open qTox
2. Create a new group via clicking on the groups icon, choosing "Create new group", and setting a name for it after creation
3. Click on the new group and verify it says "1 user in chat" (user being yourself)
4. Right-click on some online friend
5. Choose option "Invite to group"

##### Observed Behavior

The menu "Invite to group" does not open further (it doesn't show any submenus), so adding/inviting user to a group is not possible.

##### Expected Behavior

The menu "Invite to group" opens further to show the list of available groups, and results in the user being invited to group.

**Comment by sudden6** [comment]
I could not reproduce this one on https://github.com/qTox/qTox/commit/6052612250d70a5383ebc9e83ec4faa4d0dcf747

Can you try a newer version? Did you try with a fresh profile?

**Comment by docelic** [comment]
@sudden6 which branch should I be looking at? I compiled the version I got after doing a standard "git clone" of the github repository (so, master branch).

Regarding profile, yes, it was a new profile on the first-time install of qTox.

**Comment by sudden6** [comment]
master branch is ok and should be fine.

I have no idea then about the cause. It could be the rather old version of Qt you're using, but I'm not sure.

**Comment by anthonybilinski** [comment]
I also can't repro. @docelic is "Invite to group" greyed out like it is for offline friends, or is it black like it is for the other options? And the new group does show in your contacts list?

**Comment by docelic** [comment]
@sudden6 I am using latest Qt (Qt 5.11).
@anthonybilinski It is enabled, I can move the mouse to it like an active widget, but then no submenu opens with the list of groups.

Please see the attached screenshot. As you see, there is a group present named "TEST GROUP" with 1 user (myself, I just created it), and I want to invite the user just below it into the group. But the "Invite to group" menu does not show any submenus.

![qtox-issue](https://user-images.githubusercontent.com/112993/45186532-15df5e00-b22e-11e8-8531-a3c7c1f2cf1c.png)

**Comment by docelic** [comment]
My information just above that Qt 5.11 is used was incorrect. The binary was built using Qt 5.7 as mentioned at the beginning of the thread (Qt: 5.7.1).

After a re-compilation with 5.11, it works. I couldn't tell if just the recompile, or the switch to 5.11, solved it.

Since you reported above that you couldn't reproduce it yourself, I am closing this issue, thanks.
