### ISSUE TITLE
gtk and qt uniform themes

### ISSUE THREAD

**Issue by whoizit** [qTox/qTox#5325]
I just use gtk2/3 theme (https://www.gnome-look.org/p/1174889/) 

This manual for uniform looking themes https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications#QGtkStyle

it works with keepassxc (qt5) 
![2018-09-04-005712_1280x1006_scrot](https://user-images.githubusercontent.com/359276/45002306-036ee580-afde-11e8-945a-1453a0df60af.png)

but it not works (not properly works) with qTox (qt5)
![2018-09-04-004415_1280x1006_scrot](https://user-images.githubusercontent.com/359276/45002307-04077c00-afde-11e8-85ab-d5f283efd612.png)

what I do wrong? How can I fix it?
With style None the same behaviour

**Comment by sudden6** [comment]
Unfortunately qTox overrides many of the Qt default theme things. This was initially done to make Windows/Linux/MacOS look uniform, but creates issues with special themes.

You can fix this by improving the theme handling and code in qTox.

**Comment by pizdjuk** [comment]
have the same problem here. How can I undo this overrideing? Any patch? Where I have to look for?

**Comment by whoizit** [comment]
with dark style this issue not mattered for me anymore https://github.com/qTox/qTox/pull/5558
