### ISSUE TITLE
File rejected by peer causes crash

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#533]
https://gist.github.com/dubslow/def91a97cae72d81d246

**Comment by tux3** [comment]
Did you try to send a weird file maybe ?

I can't see many reasons why QFile::readAll() would crash :/

**Comment by dubslow** [comment]
Nope, just the Star Wars Episode IV soundtrack in m4a form (23 tracks I think the log says)

Isn't there some hardcoded MAX_FILE_TRANSFERS or some such?

**Comment by tux3** [comment]
No max file transfers afaik. There's a max for calls and groupchats tho.

But having 23 FT threads probably triggered some rare race condition.

**Comment by krepa098** [comment]
Seems like ToxFile::file gets deleted and then accessed by FileTransferInstance.

**Comment by dubslow** [comment]
This is reproducible, ~~but the backtrace isn't.~~

https://gist.github.com/dubslow/121baa71d7fe90b09f7c

~~Sadly the first one wasn't with debugging symbols, so no line number. I'll try to reproduce that bt.~~

~~Edit: Try three times, get three different bts... threading...~~

Always crashes in constructor, but which line exactly is apparently different each time. That detail is irrelevant though.

**Comment by dubslow** [comment]
Reading in slightly more detail, audiobot accepted 16 files just fine. Though I crashed it, I somewhat suspect 17 would crash qTox, cause that's when audiobot starts rejecting them. krepa's probably right.

**Comment by apprb** [comment]
It was race condition problem.
As small bonus: my attempt to send 148 files with total size about 67MB swallowed all my 8GB RAM and 4 GB swap )

Update: this small bonus actually is #266
