### ISSUE TITLE
Proposal: "update available" notification based on latest github release or bootstrap versions

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5335]
Without adding any centralized server polling, it's still possible for qTox to check if it's an older version than other nodes in the network.

Bootstrap nodes return a version number that correspond to toxcore release versions. If qTox collected that information while already bootstrapping, and there is at least a qTox patch release for every toxcore release (not done currently, but it seems like a good idea to me), then anytime qTox bootstraps and sees a node with a newer version of toxcore than what is running, we could show a notifier than there's probably a new version available and that the user should go check.

This is obviously not as complete as the old window auto updater or linux package based updating, but it would be totally cross platform (including source builds, appImage, etc.) and contained within qTox, plus not leak any metadata.

**Comment by anthonybilinski** [comment]
Another more direct option is to just ping a qTox-owned server or the github release page to see the latest version available of qTox. This would be more reliable since it would use qTox version directly instead of toxcore version, allowing us to either not release a qTox version if there's a trivial toxcore version bump, or release a qTox patch despite no toxcore version bump. The request could follow client proxy settings using https, so the only meta data leaked for non-proxy users would be that "IP address came online at this time" which is already visible in the public DHT.

Are there privacy concerns with this?

**Comment by sudden6** [comment]
I think relying on the bootstrap nodes version string is probably not a good idea, since they are not well defined.

For the second proposal, I think this would be a quite good idea to implement for the releases we distribute over GH. But I would disable this via cmake by default, because else we'll produce the update message for distributions too.

**Comment by anthonybilinski** [comment]
Agree, bootstrap is definitely worse, I just thought it added some level of anonymity, but thinking about it more I don't think a basic https request (following proxy rules) leaks any info at all.

>disable this via cmake by default

Sure, I agree we wouldn't want distributed packages to show it (unless maybe they're multiple versions behind? but oh well in that case I guess.). We could set it to enabled for Windows build, OSX, AppImage, Flatpak, then the only people missing it would be those who compiled locally themselves without the flag, but then again that's kind of their own responsibility.

**Comment by anthonybilinski** [comment]
Thoughts on using a domain that we own (and would have to acquire) instead of the github release page, so that we have more control over the API and lifetime of the service? If we point at github releases and for some reason move off github in the future, old clients might be stuck checking an invalid URL.

I don't mind paying registration since there's no non-profit setup (yet?).

**Comment by sudden6** [comment]
> (following proxy rules) 
This is an important detail.

IMO for the start GH would be good enough, maybe with tox.chat as fallback?

Not sure about flatpak, since I think it has update abilities integrated in the package management? I would only enable it for our official builds we distribute over GH for Windows, OSX, Flatpak and AppImage. But not for the flathub.org Flatpak.

**Comment by anthonybilinski** [comment]
Sounds good, I have version dynamic version checking (following proxy rules) from github working with a notification in the UI if a newer version is available. Now just struggling to make the UI less ugly.

**Comment by sudden6** [comment]
Nice, maybe we can then also integrate it with the notifications PR.
