### ISSUE TITLE
Coding style proposal: Avoid using truthiness of values as booleans

### ISSUE THREAD

**Issue by iphydf** [qTox/qTox#5336]
`if (icon)` what type is `icon`? In this case, it's a pointer. `if (eventIcon)` how about now? Well, it's a bool. How about `if (evt)`?

I suggest avoiding the very common C style "lots of stuff converts to bool in boolean context" and pretending to have a stricter type system (by convention).

**Comment by sudden6** [comment]
I think this makes sense, @Diadlo @anthonybilinski what do you think?

**Comment by Diadlo** [comment]
I already suggested avoid implicit cast pointer to bool @sudden6 in PM. Agree

**Comment by anthonybilinski** [comment]
I think specifying `if (icon != nullptr) { }` is redundant and not very useful. Sure the type isn't specified in the line, but it's specified at the point of icon's declaration, which (should) be close by. The information is also definitively known at compile time so can be displayed by IDEs on hover etc. Implicit null check also allows smart pointers to override bool operator to check nullness, without having to check different conditions based on the type of smart pointer used, and update those conditions if the underlying smart pointer type changes.

This seems a similar question to using `auto` where `auto icon = getIcon()` is ambiguous about it's type, but `Event* icon = getIcon()` is duplicating the information of the return type. In this case we've already favoured using auto.

Another option in [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation) and to prefix pointer names to indicate that they're pointers, such as `Event* pEvt = new Event()`, but again type information is being duplicated.

**Comment by sudden6** [comment]
@anthonybilinski IIRC the smart pointers also overload the cast to pointer, so comparing against `nullptr` returns the expected result.

About `auto`, I think this one makes only sense if you're dealing with a very long or complex type name, e.g. iterators and in my opinion if you're using iterators the intent is quite clear.

**Comment by anthonybilinski** [comment]
True, smart pointers to cast to pointer. Optional types may not, but ion that case checking against none type instead of nullptr does more explicitly show intent. IMO checking `if (pointer)` is so common in C/C++ that it's familiar, and feel like the job of showing type is that of the IDE not the code, but I don't feel strongly about this and it has popular approval, so go ahead :)

**Comment by sudden6** [comment]
We now refer to the CppCoreGuidelines which have a rule for the discussed case: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es87-dont-add-redundant--or--to-conditions that says to avoid redundant comparison operators. So I think this can be closed now.
