### ISSUE TITLE
Coding style proposal: Avoid singletons

### ISSUE THREAD

**Issue by iphydf** [qTox/qTox#5339]
qTox has lots of singletons requiring global constructors and destructors. The latter are particularly dangerous, but the former require careful programming so they don't start depending on other singletons (since construction order is unspecified). It's best to avoid them entirely if possible (RCC needs it to register stuff, but in many cases, it's not necessary).

**Comment by anthonybilinski** [comment]
Agreed. All the maintainer's I've talked to agree as well, I think, it's just a matter of going through and fixing the 100s of uses of the existing singletons. I've created a PR to add the suggestion to coding_standards.md.
