### ISSUE TITLE
enable UDP can not be checked

### ISSUE THREAD

**Issue by fatherMatrix** [qTox/qTox#5343]
##### Brief Description

OS: Windows 
qTox version: v1.16.3
Commit hash:  8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.3
Qt:  5.9.6

Reproducible: Always 

##### Steps to reproduce

1. Settings 
2. Advance
3. Enable UDP

##### Observed Behavior

  The "Enable UDP" just can not be choosen and it was disabled.

##### Expected Behavior

  It should be enabled because tox core may use UDP to provide more efficient performance.

**Comment by anthonybilinski** [comment]
Sounds like a duplicate of https://github.com/qTox/qTox/issues/5311, fixed by https://github.com/qTox/qTox/pull/5313 (but not yet released).

The workaround is to select "None" as proxy type.

**Comment by fatherMatrix** [comment]
Woo~，it's so embarrassing...
Thank you for your reply~

**Comment by anthonybilinski** [comment]
Not your fault, it's a bug in the default setting that isn't obvious in the UI :)
