### ISSUE TITLE
debian - rename required packages

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#535]
GlaxY | can't install qtox on debian jessie, it requires libopencv2.4-core and libopencv2.4-highgui but in debian this packages are called libopencv-core2.4 and libopencv-highgui2.4

**Comment by dubslow** [comment]
@stqism same error as in the other issue

**Comment by agilob** [comment]
I knew I saw it somewhere ;)

**Comment by stqism** [comment]
This issue should be resolved in 15 minutes.
