### ISSUE TITLE
[Feature request] Allow user to set name of new profile before creating it

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#536]
Something like box for name input, and next to it button `Create new Tox ID`, and new profile would be created with given name?

**Comment by dubslow** [comment]
~~Maybe just add a line to the dialog?~~

*Make a dialog, lol

**Comment by zetok** [comment]
I'm not sure what would be an advantage of the dialog, since:

```
_________  __________________
|________| |Create new Tox ID|
           ––––––––––––––––––
```

In ↑ you can click 1 on empty name field, write your desired profile name, and press `Enter` to create new profile, or use mouse to press button `New Tox ID`. Thus 1 click, keyboard or 1 click, keyboard and click to create new profile.

How ergonomic would be dialog?

**Comment by dubslow** [comment]
I guess the button could be moved down a row with an input...

**Comment by zetok** [comment]
Looks like this was done.
