### ISSUE TITLE
Fix errors in qTox.appdata.xml reported by appstream-util validate

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#5361]
`appstream-util validate appstream-util validate res/io.github.qtox.qTox.appdata.xml` shows the following errors with our AppStream description file:

```
res/io.github.qtox.qTox.appdata.xml: FAILED:
• tag-missing           : <translation> not specified
• style-invalid         : <caption> cannot end in '.' [A sample conversation taking place on qTox.]
• style-invalid         : <caption> is too long [A sample groupchat discussion taking place on qTox.];longest allowed is 50 chars
• style-invalid         : <caption> cannot end in '.' [A sample groupchat discussion taking place on qTox.]
• attribute-missing     : <release> has no timestamp
• style-invalid         : <summary> cannot end in '.' [Powerful Tox chat client that follows the Tox design guidelines.]
• style-invalid         : <p> does not end in '.|:|!' [A New Kind of Instant Messaging]
• style-invalid         : <p> is too short [With the rise of government monitoring programs, qTox provides an easy to use application that allows you to connect with friends and family without anyone else listening in. While other big-name services require you to pay for features, qTox is totally free, and comes without advertising.]
• style-invalid         : Content before <ul> is too short [68], at least 300 characters required
• style-invalid         : <li> is too long [Security: qTox takes your privacy seriously. With leading-class encryption, you can rest assured knowing that the only people reading your messages are the ones you send them to.] maximum is 100 chars
• style-invalid         : <li> is too long [Ease of Use: Unlike other secure messaging solutions, qTox does not require you to be a computer programmer to use it. qTox comes out-of-the-box with an easy-to-use interface that allows you to focus on your conversations.] maximum is 100 chars
• style-invalid         : <li> is too long [Freedom: qTox is both free for you to use, and free for you to change. You are completely free to both use and modify qTox. Furthermore, qTox will never harass you with ads, or require you to pay for features.] maximum is 100 chars
• style-invalid         : Too many <p> tags for a good description [5/4]
Validation of files failed
```

This file is directly shown on https://flathub.org/apps/details/io.github.qtox.qTox) and most of the things are probably easy to fix.

**Comment by sudden6** [comment]
We should also update the description text to the one we use for our repository.

**Comment by zetok** [comment]
Well, all the elements marked as `style-invalid` sound like the "validation" utility trying to find problems where there are none.

Which brings down the number of actual problems to 2. <strike>It really does make me want to write a wrapper script that would make it work properly.</strike> I actually ended up writing the script to filter it. If you want, I'll make a PR to add it to repo.

>We should also update the description text to the one we use for our repository.

But the `<description>` seems to be fine? Or do you mean `<summary>`, which indeed should be changed to repo description. And now that I look at the README.md, it does contain the `<summary>` text right at the top of it, and that too probably should be changed to repo description.

**Comment by sudden6** [comment]
The style things don't really have to be fixed for now and qTox translations are compiled in, so we can't reference them in the appdata.xml.

The version tag issue has been fixed, so closing.
