### ISSUE TITLE
[UX] Some indication Tox ID has been copied

### ISSUE THREAD

**Issue by DanTheBritish** [qTox/qTox#537]
Currently, when you click your Tox ID to copy it, there's no indication that it worked.

Perhaps the box could glow green and fade back to white to indicate that there was an action.

**Comment by zetok** [comment]
> Perhaps the box could glow green and fade back to white to indicate that

What about colour-blind people?

IMHO showing `✔` right next to `(click to copy)` to indicate that copying was successful would be much better..

Edit: or `✔` should be showed in right upper "corner" of `Tox ID` "box".
