### ISSUE TITLE
Malwarebytes reports Trojan in qTox

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#5381]
##### Brief Description

OS: Windows 8.1 64-bit 
qTox version: 1.16.3
Commit hash:  8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.3
Qt:  5.9.6
Reproducible: Sometimes

##### Steps to reproduce

1. Install Malwarebytes and get a free trial including Real-Time Protection
2. Make sure all options in Malwarebytes Real-Time Protection is enabled and have qTox to automatically connect when Windows starts.
3. Then reboot and check Malwarebytes notifications.

##### Additional Info
Attached Malwarebytes Report:
[malwarebytes-qtox.txt](https://github.com/qTox/qTox/files/2460270/malwarebytes-qtox.txt)

**Comment by sudden6** [comment]
Probably triggers some heuristic, see https://github.com/qTox/qTox/wiki/Problematic-antiviruses
