### ISSUE TITLE
Friend name change isn't reflected in group header

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5384]
##### Brief Description
qTox version: v1.16.3+
Commit hash: 064dccf8b49212b65c2c114fc87a9226b5ecf518

Reproducible: Always

##### Steps to reproduce

1. Invite friend to group
2. Have friend change their name

##### Observed Behavior
Friend name is changed in friends list right away, but in group header the friend's name is changed to the last set friend name. i.g.:
1. friend has name 'A'
group list of members shows 'A'
2. friend changed name to 'B'
group list of members still shows 'A'
3. friend changed name to 'C'
group list of members still shows 'B'
4. friend changed name to 'A'
group list of members still shows 'C'

**Comment by sudden6** [comment]
Not reproducible on https://github.com/qTox/qTox/commit/49507d76d823088f74ffc02760186a6793b3e16e anymore for me. Tried with two fresh profiles.

**Comment by anthonybilinski** [comment]
Confirmed, I just reproduced the issue on 064dccf8b49212b65c2c114fc87a9226b5ecf518 and can't on tip.
