### ISSUE TITLE
The qTox main window was disappeared

### ISSUE THREAD

**Issue by jakieoymj-github** [qTox/qTox#5392]
##### Brief Description

OS: Ubuntu 18.04.1 LTS
qTox version: v1.16.3-123-gbdfa3938
Commit hash: bdfa393
toxcore: 0.2.8
Qt: 5.11.1

Reproducible: Always

##### Steps to reproduce
start qtox

##### Observed Behavior
The qTox main window not display after login window. But it seems qTox running background.

**Comment by anthonybilinski** [comment]
@jakieoymj-github which of "show system tray icon", "start in tray", "minimize to tray", "close to tray" are checked under settings -> general?

![image](https://user-images.githubusercontent.com/10469203/46908765-7ff9bb80-cedc-11e8-93e8-850705cd36d5.png)

**Comment by jakieoymj-github** [comment]
yah, you are right, the main window back while after I deleted qtox.ini. thanks very much. but it should give something prompt I thought. I did a lot like uninstall QT and reinstall it :)
the deleted qtox.ini content:
`[GUI]`
`...`
`minimizeOnClose=false`
`minimizeToTray=true`
`notify=true`
`...`

`[%General]`
`...`
`autostartInTray=true`
`closeToTray=true`
`showSystemTray=true`
`...`
