### ISSUE TITLE
Search history doesn't find anything if history has not been loaded

### ISSUE THREAD

**Issue by sphaerophoria** [qTox/qTox#5396]
##### Brief Description

Search history doesn't find anything if history has not been loaded

OS: Windows
qTox version: (version numbers in menu `Settings → About`)  
Commit hash:  aa7542f729346fc87b113259c361d781bbac5da8
toxcore:  0.2.7
Qt:  5.11

Reproducible: Always 

##### Steps to reproduce

1. Clear chatlog
2. Search for anything
3. Send message
4. Search for anything
5. Load anything from history
6. Search for anything

##### Observed Behavior

1. Chatlog cleared
2. Nothing found
3. Message sent
4. Nothing found (unless it's what you just sent)
5. History loaded
6. Results from chat history now appear

##### Expected Behavior

We should always search chat history

**Comment by sudden6** [comment]
Confirmed.

**Comment by sudden6** [comment]
Fixed with #5467
