### ISSUE TITLE
Misleading error message for ToxMe lookup

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#5398]
##### Brief Description

Reproducible: Always

##### Steps to reproduce

1. Disable network connection
2. Go to "Add friend" page
3. Add "echobot@toxme.io"

##### Observed Behavior

Message box with `echobot@toxme.io Tox ID is invalid or does not exist` pops up

##### Expected Behavior

Message box says something that the network request failed

The message is misleading in the way that `echobot@toxme.io` does exist, just qTox couldn't look it up because there was no network connection.

**Comment by anthonybilinski** [comment]
ToxMe support was removed from qTox as part of https://github.com/qTox/qTox/pull/5898 due to it going offline permanently https://github.com/qTox/qTox/issues/5897. Closing this issue as it's no longer relevant.
