### ISSUE TITLE
Ability to share desktop

### ISSUE THREAD

**Issue by nut-neek** [qTox/qTox#540]
It would be very nice to see this functionality in qTox

**Comment by msteinbeck** [comment]
Isn't it a planned feature in toxcore?

**Comment by ProMcTagonist** [comment]
toxcore isn't involved at all. It doesn't care where it gets video frames from, it just sends them.

**Comment by dubslow** [comment]
However, grabbing images from the desktop is client independent, and thus to avoid redundancies could well be a core feature.

**Comment by urras** [comment]
I'm pretty sure uTox has this feature already. Not sure how it was implemented though.

**Comment by nut-neek** [comment]
Found some solution for this issue in the following thread: http://superuser.com/questions/411897/using-desktop-as-fake-webcam-on-linux. However it doesn't solve problem entirely. For most of my calleagues (target group to use this feature with) option with a fake camera is too complicate.

**Comment by ProMcTagonist** [comment]
@nut-neek That's a workaround for when a VOIP program doesn't already have the feature to share the desktop. qTox will. No need to trick it.

**Comment by Xylemon** [comment]
Any update on this?

**Comment by tux3** [comment]
First we still need to stabilize video (fix bugs/bad design), then it shouldn't be too hard to make it happen.

**Comment by PKEv** [comment]
Any update on this?

**Comment by tux3** [comment]
I'll be working on this now.

**Comment by tux3** [comment]
I implemented it for X11 (Linux), I'll test and add Windows support tommorrow.

**Comment by PKEv** [comment]
Cool!

**Comment by SkyzohKey** [comment]
Nice !

**Comment by urras** [comment]
:+1:

**Comment by ProMcTagonist** [comment]
Awesome :+1:

**Comment by zetok** [comment]
does toxav now support multiple a/v streams?

Or rewrite of it?

If not, then it's only going to work without active video call, right?

**Comment by ProMcTagonist** [comment]
qTox should be able to composite multiple video feeds. Picture-in-picture.

**Comment by tux3** [comment]
This is implemented in Linux and Windows and probably implemented on Mac (but as usual, I can't test it!).
