### ISSUE TITLE
the image of an integrated cam is distorted

### ISSUE THREAD

**Issue by pizdjuk** [qTox/qTox#5402]
##### Brief Description

OS: Linux Mint 18.3
qTox version: 1.16.3
Commit hash:  8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.3
Qt:  5.7.1
Hardware:  Lenovo T470s,
Webcam: Bus 001 Device 004: ID 04f2:b5ab Chicony Electronics Co., Ltd 

Reproducible: Always

##### Steps to reproduce
0. In the settings set the resolution of the integrated webcam to 240p or 480p
1. Vedeocall anybody with any client (qtox,utox)
2. The image of me is distorted: there are only picture with diagonal colored lines to see.
3. The image of friend is ok. Sound is ok.

##### Observed Behavior

The problem is triggered (probably!) only with integrated cam.
[camera_info.txt](https://github.com/qTox/qTox/files/2502513/camera_info.txt)
[tox_debug.log](https://github.com/qTox/qTox/files/2502521/tox_debug.log)

**Comment by pizdjuk** [comment]
cam info: http://dpaste.com/0WCFZ1S
log file: http://dpaste.com/26TXVYS

**Comment by sudden6** [comment]
can you tell us which video mode was selected in qTox and possibly a screenshot of the distorted video?

**Comment by pizdjuk** [comment]
A screenshot is not possible. Since I have not two compuers here.
I tried to change videomodes, but the problem occurs in every mode. The last mode I tried was 240p.

If you agree with it, I cpuld call you from my qtox.

**Comment by pizdjuk** [comment]
When I see how the screen look out from the other side last time (end of july), it looked out like a distorted synchro, i.e. diagonal colored rays.

**Comment by sudden6** [comment]
you can initiate a video call with https://toxme.io/u/echobot so you don't need two computers. Alternatively you can start two instances of qTox on one PC.

**Comment by pizdjuk** [comment]
>you can initiate a video call with https://toxme.io/u/echobot 
tnx! I've already searched for a long time for a working tox-bot!

>Alternatively you can start two instances of qTox on one PC.
done!

![scrsht](https://user-images.githubusercontent.com/35386958/47269354-2c155500-d522-11e8-97f5-2628e6de937e.png)

**Comment by sudden6** [comment]
Does the mini picture of your own video show the correct image?

**Comment by pizdjuk** [comment]
>Does the mini picture of your own video show the correct image?

the mini picture is an avatar, because on one instance of qtox I cahnged the video source to "none".

**Comment by sudden6** [comment]
I mean the mini picture on the instance sending the webcam video. If I understand your setup correctly, it's hidden behind the top level qTox instance in your screenshot.

**Comment by pizdjuk** [comment]
Yes, this mini picture is showed correctly

**Comment by sudden6** [comment]
ok, thanks

So we know that qTox does get the image properly from the webcam, but either passes it wrong to c-toxcore or retrieves it wrong from c-toxcore on the receiving side.

**Comment by Diadlo** [comment]
Duplicate of #2529?

**Comment by sudden6** [comment]
@Diadlo don't think so, this has a different pattern of corruption.

I'm pretty sure that #2529 was because of toxcore truncating video frames, but that was fixed in 0.2.0

**Comment by pizdjuk** [comment]
I have some updates: the bug is triggered on 240p and 480p. With 360p and 720p all seems to be ok!

**Comment by sudden6** [comment]
@pizdjuk that's very good info

```
[14:37:42.046 UTC] widget/form/settings/avform.cpp:307 : Debug: width: 1280, height: 720, FPS: 30.000000, pixel format: mjpeg
[14:37:42.047 UTC] widget/form/settings/avform.cpp:307 : Debug: width: 848, height: 480, FPS: 30.000000, pixel format: mjpeg
[14:37:42.047 UTC] widget/form/settings/avform.cpp:307 : Debug: width: 640, height: 360, FPS: 30.000000, pixel format: mjpeg
[14:37:42.047 UTC] widget/form/settings/avform.cpp:307 : Debug: width: 424, height: 240, FPS: 30.000000, pixel format: mjpeg
```

I learned from @strfry that VP8 has some internal blocksize of 16x16 pixels and the failing resolutions have widths that are not divisible by 16, so I very much suspect we are feeding the vp8 codec wrong data or  are interpreting it's return data wrong.

**Comment by sudden6** [comment]
I found a way to reproduce this:

- ensure `v4l2loopback` kernel module is installed
- load this kernel module with `sudo modprobe v4l2loopback`
- create test video with `ffmpeg -re -f lavfi -i testsrc=size=424x240:rate=15 -f v4l2 /dev/video0`, adjust `video0` to first free video device index in your system
- call someone via qTox to observer the effects of this bug

**Comment by sudden6** [comment]
It turned out that vp8 was not the culprit, but a logic bug in qTox when preparing the frames for c-toxcore.

@pizdjuk can you test the referenced PR? I'm pretty sure it fixes your problem.

**Comment by pizdjuk** [comment]
>@pizdjuk can you test the referenced PR? I'm pretty sure it fixes your problem.

I cannot compile toxcore with following error:

/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libsodium.a(libsodium_la-box_curve25519xsalsa20poly1305.o): relocation R_X86_64_PC32 against symbol `crypto_box_curve25519xsalsa20poly1305_beforenm' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value

And so I cannot compile qtox :(

**Comment by Diadlo** [comment]
@pizdjuk If your distro supports Docker, try to use `./docker/build-ubuntu.sh && ./docker/start-qtox.sh `

**Comment by pizdjuk** [comment]
Is there other way? It will download half of a distro o.O

**Comment by pizdjuk** [comment]
Ok. I finally compiled it. One question (it took me 1 hour to understand :) I thinked, that the patch is in branch, and was wondering why the bug still is there ))

But finally I applied the patch by hands and it works fine now!

**Comment by sudden6** [comment]
@pizdjuk great to hear, I think you helped to solve some very hard to reproduce bug here, thank you :)

@Diadlo could you review the PR so I can merge it into master?
