### ISSUE TITLE
Tox tray icon wrong place or gone [UI]

### ISSUE THREAD

**Issue by EibrielInv** [qTox/qTox#541]
On Ubuntu 14.04, the Tox try icon is on a wrong place on the left.

![tuxbug](https://cloud.githubusercontent.com/assets/172656/4781852/2480d038-5cc4-11e4-9005-bcc88d602046.png)

**Comment by agilob** [comment]
5th bug in Qt 
https://bugreports.qt-project.org/browse/QTBUG-31762?focusedCommentId=222553&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel

http://forum.selur.de/topic581-info-unity-system-tray-icon-wrong-position.html

**Comment by agilob** [comment]
@Eibriel @mannol  If I built for you qTox with qt5.0 and qt5.3, could you confirm if the bug is resolved in any of those builds?

version: 5.3.2-2 https://upload.agilob.net/qtox
~/Projects/qtox(branch:master) » sha1sum qtox
a27975295615f474d4ea3080de3bb588aa36f8a8  qtox

please check sha1 before running ;)

**Comment by EibrielInv** [comment]
sha1sum do not match

**Comment by agilob** [comment]
that upload script is shitty, everyone can overwrite my files ;/
c1331ea17c0fb45dc94e1a95b8e757c14b795b8f http://b.agilob.net/qtox5322

**Comment by EibrielInv** [comment]
Sorry, but:

```
./qtox5322: error while loading shared libraries: libtoxcore.so.0: cannot open shared object file: No such file or directory
```

:(

**Comment by dubslow** [comment]
Is it possible for you to run `./bootstrap.sh`? That ought to install at least that dependency... @agilob this is one of many reasons why packaging has been so hard lol

**Comment by strk** [comment]
@Eibriel try `sudo ldconfig` (add -v | grep libtox # to see more)

**Comment by agilob** [comment]
@strk  toxcore is dynamically linked.

**Comment by strk** [comment]
ldconfig tells the dynamic linker to re-scan the standard directories to update his mapping of available libraries. The message says there's no libtoxcore.so.0, if it can be found on the filesystem then an ldconfig run is needed (was needed for me, after manually compiling and installing it on ubuntu 14.04)

**Comment by agilob** [comment]
I know what it does. dubslow asked him to run `./bootstrap.sh`, see line [150](https://github.com/tux3/qTox/blob/master/bootstrap.sh#L150).

**Comment by strk** [comment]
Ah, nice, thank you

**Comment by dubslow** [comment]
@agilob, note that it may not solve his problem -- there are likely many other dynamically linked dependencies that he doesn't have (unless he's a Qt 5 dev for other projects).

**Comment by EibrielInv** [comment]
@agilob after compiling some dependencies now I get:

```
./qtox5322: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./qtox5322)
```

Any chance to make a build like the one in https://jenkins.libtoxcore.so/job/qTox-linux-amd64/ ? (static I think)

**Comment by dubslow** [comment]
@agilob You can also send @stqism a patch and ask if he can apply the patch and make a package from that.

Or, if @Eibriel is willing, since he compiled some dependencies he could also just compile qTox itself with your patch.

**Comment by strk** [comment]
I'm completely missing the tray icon on lubuntu 14.04 with gnome-fallback session. 
This is libqt5-5.2.1. I haven't tried with the Unity interface. Should I file a separate ticket ?

**Comment by agilob** [comment]
You can, but it's still bug in Qt ;/

@strk try this http://askubuntu.com/questions/343788/skype-nofitication-icon-on-gnome-session-fallback-12-04

**Comment by ghost** [comment]
The tray icon can be disabled in general settings. It is disabled by default on Linux and enabled by default on Windows and Mac, where it should be working.

**Comment by strk** [comment]
@agilob the ubuntu question you point to is unrelated, the solution is about installing 386 libraries but I do get teh skype icon and I'm building qtox myself (so I get a 64bit binary).

As of today I do see some activity in the "tray" when I check/uncheck the "Show system tray icon": another icon is slightly moved to the left when I check it, as for making space for the qtox icon, but no icon is shown. Checking the "Light icon" makes a single while pixel appears too, and _IT_WORKS_ as an icon, just is very hard to click on :)

**Comment by nazar-pc** [comment]
Ubuntu 15.04 I do have icon, but it appears in top lest corner instead of proper place (the same was with ownCloud client some time ago, but after their fix for icon position I'm missing ownCloud icon completely).
Skype is in proper place (QT-based too).

**Comment by zetok** [comment]
@nazar-pc AFAIK skype uses qt4, which is different from qt5.
Thanks for checking.

**Comment by nazar-pc** [comment]
@zetok, yes, but Skype doesn't render icon without `sni-qt:i386` package, what is that and why there is no such package for QT5? Hard to believe that there is no way to get icon in right place with QT5. This is just ridiculous.

**Comment by strk** [comment]
For the record, as eb6a563f8b6fd31ca63ba46e618cf2495bb583a5 the icon is again NOT visible at all.
This is with gnome-panel 1:3.8.0-1ubuntu12.2 amd64

**Comment by nazar-pc** [comment]
I can confirm, now no icon at all. Become completely useless.

**Comment by strk** [comment]
The code sets image path with this form: ":img/taskbar/light/taskbar_online_2x.png" -- where is that file supposed to be installed ? What determines location of the ":img" directory ?

**Comment by strk** [comment]
I do have         <file>img/taskbar/light/taskbar_online_2x.png</file> in res.qrc and the img/taskbar/light/taskbar_online_2x.png file exists in the directory from which qTox starts, and is readable.

**Comment by nazar-pc** [comment]
Actually, if uncheck/check again in settings to show icon - it appears, prior to moment when qtox is hidden.

**Comment by strk** [comment]
I've added a ->showMessage() call to get a popup and now I can see where the icon is supposed to be. It's on the top-left side of the leftmost monitor (dual-monitor setup) but isn't visible. The tooltip is.

Adding a debugging line to show ->geometry() I see:
XXX Widget: geometry is  QRect(2232,0 1x24)

**Comment by dubslow** [comment]
The colon at the front means that the file is embedded in the binary, as coded in res.qrc.

I've forgotten the context, did something cause the icon to no longer appear? Did you choose the light icon in settings? IIRC dark is the default and previously only style...

**Comment by strk** [comment]
The icon never appeared to me, if not as a single pixel in a weird place.
The light icon in setting is just a test, neither one work. The light one
I can see as a pixel by using a single monitor, the dark one I can never see.

**Comment by srkunze** [comment]
For me, the icon (both light and dark) appears in the top left corner of the screen. I assume it is supposed to reside somehwere next to wifi, keyboard layout, mail, speaker etc.

**Comment by asmexcaliburwoods** [comment]
Ubuntu 14.04.1 with MATE Desktop Environment 1.8.1 — no qTox tray icon at all. 

```
apt-show-versions qtox
qtox:i386/nightly 1.0-947 uptodate
```

**Comment by strk** [comment]
For the record, today I saw the tray icon for the first time. Not sure it was an QT upgrade or a qTox upgrade, but I guess the former as nothing changed in qTox about this ? Both normal and "Light" icons work now, only are (unexpectedly) at the center of the panel, near the IBus (keyboard) selector.

**Comment by strk** [comment]
Eh.. spoke too early. Unchecking the "Show system tray icon" correctly makes the icon disappear but checking it again does not bring it back :(

**Comment by ArchangeGabriel** [comment]
QT 5.4 has changes about tray support.
Le 22 janv. 2015 15:28, "Sandro Santilli" notifications@github.com a
écrit :

**Comment by strk** [comment]
On Thu, Jan 22, 2015 at 06:32:12AM -0800, Bruno Pagani wrote:

> QT 5.4 has changes about tray support.

I'm still at 5.2

**Comment by srkunze** [comment]
Is there something we can do to resolve the issue? I would like to use the icon but for Ubuntu it is located in the most wrong place: where the menu and close button is.

**Comment by ghost** [comment]
In order to use the tray in Ubuntu, an app seems to have to support Unity's appindicator protocol.

https://unity.ubuntu.com/projects/appindicators/

For APIs and code examples, see also
https://wiki.ubuntu.com/DesktopExperienceTeam/ApplicationIndicators

**Comment by tux3** [comment]
I'll be implementing an appindicator backend since this is unlikely to get fixed properly by upstream any time soon.

**Comment by strk** [comment]
Uhm, it didn't fix the issue I reported. This is Ubuntu 14.04 64bit, gnome panel 1:3.8.0-1ubuntu12.2, qt 5.2.1+dfsg-1ubuntu14.2

**Comment by tux3** [comment]
@strk 
The new implementation is not enabled by default, because a large part of users don't need the special Unity tray icon (Windows, Mac, other Linux distros...) and it requires 3 new libraries.

It should be enabled in the coming days on the official Linux Jenkins builds, and you can compile it yourself in the meantime if you pass ENABLE_SYSTRAY_UNITY_BACKEND=YES to qmake when building qTox.

If it still isn't fixed and you're positive you have the Unity backend enabled, please leave a comment again.

**Comment by srkunze** [comment]
Compiled it with `qmake ENABLE_SYSTRAY_UNITY_BACKEND=YES` after a `make clean` and it works as intended. Thanks.

Waiting for the repository update.

**Comment by dubslow** [comment]
Should be in the repo now as `qtox-unity`.

**Comment by nazar-pc** [comment]
Thanks, @dubslow, it works now. One more thing - can you make that qtox-unity will replace (conflict with) qtox on installation, otherwise it fails to install if qtox already installed.

**Comment by dubslow** [comment]
In a few minutes they should conflict.

**Comment by srkunze** [comment]
I hope the Desktop Launcher also will use the new qtox-unity.
