### ISSUE TITLE
Ones fullscreen toggled, there is no way to untoggle it

### ISSUE THREAD

**Issue by pizdjuk** [qTox/qTox#5420]
##### Brief Description
OS: Linux Mint 18.3
qTox version: 1.16.3
Commit hash: 8eed684
toxcore: 0.2.3
Qt: 5.7.1
Hardware: Lenovo T470s,
Webcam: Bus 001 Device 004: ID 04f2:b5ab Chicony Electronics Co., Ltd
Reproducible: Unknown yet

##### Steps to reproduce

1.  Videocall someone
2. Go to the fullscreen
3. switsch to the other virtual desktop
4. switch back

##### Observed Behavior

The screen is not scaled anymore on a whole screen. The rest of screen is "freezed". There are no knobs to get out of fullscreen.

**Comment by sudden6** [comment]
I don't know if this is a qTox problem or something with Qt. Your Qt version is pretty old, maybe a newer one fixes it?

**Comment by pizdjuk** [comment]
It's a static build.
And I cannot compile from source, there are many errors, that I can not overtake.

**Comment by pizdjuk** [comment]
I tested this with git-version of qtox, and the bug didn't appear. So I would close it, till it reappear (probably)
