### ISSUE TITLE
Provide an installer for windows releases

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#543]
Subj. Windows users don't like raw archives.

**Comment by zetok** [comment]
Perhaps some code from [µTox updater](https://github.com/notsecure/utox-update/) could be used?

**Comment by tux3** [comment]
The updater is a separate problem, for the installer I'll probably be using NSIS unless we can find something better.

**Comment by tux3** [comment]
I added a NSIS install script here : e111b8ee9030a0f3dd9561dfa40b1af7f8319d2f

I'll update my jenkins to publish an installer instead of a .zip later today.

**Comment by tux3** [comment]
The first release of the qTox installer is available here (25MB) : https://github.com/tux3/qTox/releases/download/qtox-windows-1414335843.91/setup-qtox.exe

I only tested it through wine at the moment, if it doesn't work as expected, please leave a comment and I'll try to fix it asap.

**Comment by tux3** [comment]
It works for me on Windows.
If you have a bug please comment and I'll reopen. Or make a separate issue.
