### ISSUE TITLE
[Feature request] Make magnet links clickable

### ISSUE THREAD

**Issue by tvladyslav** [qTox/qTox#5437]
Treat [magnet](https://en.wikipedia.org/wiki/Magnet_URI_scheme) links as links (i.e. make them clickable).

**Comment by anthonybilinski** [comment]
our URI patterns: https://github.com/qTox/qTox/blob/ea9f4298382fb4f0a9693a20466e2a79a256edf9/src/chatlog/textformatter.cpp#L85 could be extended to support any URI scheme pattern, but that may cause over-matching given the broad nature of URIs being just "any word with a colon in it". I'm not a huge fan of adding an increasingly large list of URIs to support, but maybe that's the best option we have.

**Comment by sudden6** [comment]
fixed by #5500
