### ISSUE TITLE
Strange behaviour of "auto away"

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#546]
Auto-away is triggered (marks me as `Away`) independently of whether I am doing something or not on PC. The only time auto-away doesn't mark me as `Away` is when I do something in qTox.

I think that it's not a desirable behaviour, and should be changed.

Happens under i3wm.

**Comment by dubslow** [comment]
That's how most IM systems work... and global activity detection is significantly harder and requires platform specific code... see the comments in the code I made about this issue (forget where, but `//.*away` as a regex should be able to locate it quickly enough)

**Comment by suhr** [comment]
What about linux-only global activity detection? Applications like easystroke or xneur have no problem with global mouse/keyboard tracking.

**Comment by dubslow** [comment]
The comments in the code link to how to do it for all three major OSs.

**Comment by ghost** [comment]
You all may want to check out and test https://github.com/tux3/qTox/pull/862

**Comment by dubslow** [comment]
Has been implemented by novist ^
