### ISSUE TITLE
text color turns to white on white background with some gtk-themes

### ISSUE THREAD

**Issue by pizdjuk** [qTox/qTox#5461]
##### Brief Description

OS: Linux 
Commit hash:  
Reproducible: Always 

##### Steps to reproduce

1. Set MATE Theme to Mate BLACK

Workaround: edit the msgEdit.css and add the line color: black;

[font_color_patch.txt](https://github.com/qTox/qTox/files/2682899/font_color_patch.txt)

**Comment by sudden6** [comment]
Does #5457 fix this for you?

**Comment by sudden6** [comment]
@pizdjuk I have merged the linked PR, can you confirm it's fixed on master?

**Comment by pizdjuk** [comment]
Cannot compile:

make[2]: *** No rule to make target 'ui/msgEdit/msgEdit.css', needed by 'qrc_res.cpp'.  Stop.
CMakeFiles/Makefile2:106: recipe for target 'CMakeFiles/qtox.dir/all' failed
make[1]: *** [CMakeFiles/qtox.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sudden6** [comment]
did you completely clean the build directory? CMake sometimes doesn't like it if there are files left over.

**Comment by pizdjuk** [comment]
Ok, compiled. No problem with font anymore
