### ISSUE TITLE
Tray icon should animate while there are unread incoming messages.

### ISSUE THREAD

**Issue by dimgel** [qTox/qTox#547]
Pleeeeease. :) For linux.

**Comment by agilob** [comment]
Yup, yup, I know. Busy by university atm.

**Comment by dimgel** [comment]
Or it maybe simpler just to activate chat window in background (so it does not get focus but shows bright/blinking on taskbar).

**Comment by agilob** [comment]
I thought about blinking tray icon actually.

**Comment by ghost** [comment]
Im wondering what we want here. Blinking icon is fine by me. I even [implemented](https://github.com/novist/qTox/commit/2ffc2f6f9316f6e6d9f3acfc9bfcfb6095d8d53a) it. However the way skype is doing it i think is better. You know orange bubble with a white number of unread messages. @ItsDuke do you think that could be pulled off here? Im thinking like icons for 1-9 and one for unread count above 9 (maybe orange bubble with `...`?). Should you think we can do animated icons that would be even better. I could pull it off too. So what do you people think? Poke @dubslow @tux3 @zetok.

**Comment by dimgel** [comment]
IMHO there's no need to show unread count - you've got to attend anyway. But blinking or animating - anything would be much better than nothing. Currently tox is unusable only because of the lack of notifications. Activating window on incoming is unusable. I configured KDE to prevent it getting focus so it just hilights on taskbar requiring attention, but this only works when it activates from minimized-to-tray state. If window is already open and overlapped by other windows - I see nothing.

**Comment by ItsDuke** [comment]
@novist @dimgel Maybe I'm going crazy here, but didn't we (including myself) already have a thread about this? Except it was about just a blinking notification, and not including the unread count.

**Comment by ghost** [comment]
@ItsDuke yes indeed we did. It happened in some other PR or issue that i could not find. Anyhow im still not convinced blinking is best approach. It makes one notice however it does not look that good. Especially since blinking i did was simply alternating between light and dark tray icons. I think there could be better visually appealing blinking done. Hey or.. How about normal icon alternating with one that has orange dot in the middle (where green is for "online" status)?

**Comment by ghost** [comment]
K before any of you could wake up i got this done [here](https://github.com/novist/qTox/compare/tray-new-message-notification):
![demo](https://cloud.githubusercontent.com/assets/7602544/5891968/528f94d2-a4b8-11e4-99a9-6cf41f879cf8.gif)

**Comment by dimgel** [comment]
I think blinking whole icon (e.g. light/dark as you suggested earlier) is easier noticable. And should blink faster. I would not notice the latter one by peripheral vision.

**Comment by ItsDuke** [comment]
@novist speaking honestly, I didn't even realize your image was a gif until I stared at it for more than a second. I feel that the brightness and warmth of the color values you chose are so close, that it's not nearly attention grabbing enough to be a notification. That's mainly why a lot of the notification samples I tried dealt with white-to-black/color or vice-versa. That also alleviates any future problems we might have with folks who have full-to-limited vision deficiencies.

**Comment by dubslow** [comment]
Quassel has like a .8 second period (as opposed to like 2 second period for that gif)

I like it though, just faster lol

**Comment by ghost** [comment]
Well im no designer. I cant come up with a good image ;) Period is 1s though. I reused same timer for auto-away check. Though i think color show does look lame and very unprofessional. While for visually impaired its good i think we need a better looking option for rest. Maybe this can be done as option? Selecting kind of notification person likes?
