### ISSUE TITLE
Compilation fails: undefined reference to `tox_max_hostname_length'

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#5470]
##### Brief Description

OS: Kubuntu 18.10
qTox version: commit ea9f4298382fb4f0a9693a20466e2a79a256edf9 (HEAD -> master, origin/master, origin/HEAD)

Commit hash:  ea9f4298382fb4f0a9693a20466e2a79a256edf9
toxcore:  v0.2.7
Qt:  5
Hardware:  
…

Reproducible: Always

##### Steps to reproduce

1. `make`

##### Observed Behavior
```
$make
[  0%] Automatic MOC for target qtox_static
[  0%] Built target qtox_static_autogen
[ 61%] Built target qtox_static
[ 62%] Automatic MOC for target test_textformatter
[ 62%] Built target test_textformatter_autogen
[ 63%] Built target test_textformatter
[ 63%] Automatic MOC for target test_toxid
[ 63%] Built target test_toxid_autogen
[ 64%] Built target test_toxid
[ 65%] Automatic MOC for target qtox
[ 78%] Built target qtox_autogen
[ 78%] Linking CXX executable qtox
/usr/bin/ld: libqtox_static.a(toxoptions.cpp.o): in function `ToxOptions::makeToxOptions(QByteArray const&, ICoreSettings const*)':
/media/raffaele/DATA/data/programmi/qTox/src/core/toxoptions.cpp:102: undefined reference to `tox_max_hostname_length'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/qtox.dir/build.make:3269: qtox] Error 1
make[1]: *** [CMakeFiles/Makefile2:150: CMakeFiles/qtox.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by anthonybilinski** [comment]
@raffam could you check if `/usr/local/lib/libtoxcore.so.2.7.0` exists on your computer, and if so what `ls -l /usr/local/lib/libtoxcore.so` and `/usr/local/lib/libtoxcore.so.2` symlink to? `nm /usr/local/lib/libtoxcore.so.2.7.0 | grep tox_max_hostname_length` will make absolutely sure that the symbol exists, but it's almost definitely that toxcore isn't installed properly.

Could you try reinstalling Toxcore and then re-running cmake for qTox and re-installing it too?

**Comment by ghost** [comment]
```
/usr/local/lib$ ls -l libtoxcore*
-rw-r--r-- 1 root root 668480 dic 22 21:55 libtoxcore.a
lrwxrwxrwx 1 root root     15 dic 22 21:56 libtoxcore.so -> libtoxcore.so.2
lrwxrwxrwx 1 root root     19 dic 22 21:56 libtoxcore.so.2 -> libtoxcore.so.2.7.0
-rw-r--r-- 1 root root 508280 dic 22 21:55 libtoxcore.so.2.7.0
```

```
$nm /usr/local/lib/libtoxcore.so.2.7.0 | grep tox_max_hostname_length
0000000000046680 T tox_max_hostname_length
```

**Comment by ghost** [comment]
The problem seems to be related to the fact that I had libtoxcore **also** installed from the Ubuntu repository, and on top of that I have compiled and installed the toxcore as the qTox building instructions stated

For me the solution was
`sudo apt-get remove libtoxcore2 libtoxcore-dev`

I then re-run `make install` on toxcore and qTox then compiled
