### ISSUE TITLE
Unable To Choose Secondary Drive / Partition To Save Downloads To

### ISSUE THREAD

**Issue by 2635599** [qTox/qTox#5473]
OS: Linux Mint Cinnamon 4.15.0-43-generic
qTox version: v1.16.3
Commit hash: 8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore: 0.2.3
Qt: 5.11.1

i opened setting so i could change the default directory for saving files and the only options are for locations on the os drive. to me that is a bug. i have a specific folder on a secondary drive that i save everything to before checking it, using it, and ultimately putting it in it's appropriate folder. is there any way to fix this so i can pick any location on my system to save the files? thanks

**Comment by Chiitoo** [comment]
That definitely doesn't seem normal.

What file system is the partition using that you can't save to?

I can't see this issue at all, but I'm only using ext4 here at this time.

**Comment by 2635599** [comment]
in the window on the left besides mc2635599 there should als be listed CombinedPartitions. everything is ext4 on gpt drives.

https://i.imgur.com/1MRLknd.png

**Comment by Chiitoo** [comment]
Hmmm, that looks like the gtk+ 3 chooser dialog.

If you click on the '<' on top, left from the path with 'home' etc., can you get to the root file system, then to where ever those partitions are mounted at? (Often '/mnt' or '/media'.)

**Comment by 2635599** [comment]
my secondary partition / drive mount points are as follows
/home/CombinedPartitions/drive or partition name

as i stated above the only thing showing under home is mc2635599, CombinedPartitions should be showing as well but isn't.

**Comment by Chiitoo** [comment]
Ah, I see.  Weird.

I guess you should be able to set it manually in the 'qtox.ini' file, under '$HOME/.config/tox' when all else fails.  I'll try to get to testing if it happens to me too, somewhere with more GTK than I have right now.

Does the file chooser work okay with other applications you have?

**Comment by 2635599** [comment]
https://vimeo.com/308201009

yea i have no other save issues with saving files wherever i want with whatever program i want. seems to be a one off. is editing that file pretty much straightforward, and if so do i need to take ownership of it first?

just thought rude of me not to say happy hollidays however you celebrate them, and thank you for taking the time on xmas day to help. it's greatly appreciated.

**Comment by Chiitoo** [comment]
You should see a 'globalAutoAcceptDir' in the file, so I'd simply edit that to the path I want.

Speaking of ownership of files, I meant to ask earlier, just to make sure, that if the permissions on the files and directories are set so that the user qTox is running as can see them?

You'd definitely permissions to edit the file, but normally the user qTox is running as already would have those (else it would not be able to save any settings for example, if it would run at all).

Yeah, merry holidays and all that!  More or less just another day to me.  :]

**Comment by 2635599** [comment]
yea i own everything on all my secondary partitions. plex media server didn't like the default /home/mc2635599/partition name so i ended up creating /home/combinedpartitions/partition name and going into disk and point each one to the folder i created for it. then once mounted taking ownership via a terminal command.

**Comment by 2635599** [comment]
o.k. looks like we are in business. changed the part in the qtox.ini and looks good. thanks ever so much.

**Comment by 2635599** [comment]
o.k. reopened for obe more question. is everything for qtox located here "io.github.qtox.qTox"? i ask cause i  use freefilesync to backup various folders so all i have to do is reinstall a program, shut it down, replace it's folder, and have all my setting in place.

**Comment by Chiitoo** [comment]
See for example: https://github.com/qTox/qTox/wiki/Profile

Some of that will change in the hopefully-not-too-distant future though.

See: https://github.com/qTox/qTox/issues/5410

**Comment by sudden6** [comment]
@2635599 are you using the flatpak build? Because their sandboxing could explain this weird issue with your partitions being unavailable.

**Comment by 2635599** [comment]
no i'm not running the flat pack.

**Comment by 2635599** [comment]
sudden6 i finally read the linked page and i'll be blunt. the idea of having the files spread out all over the place is pure bs. we need a unified location for ALL files, so we can simply grab the qtox parent folder and use it for backing up qtox.

**Comment by sudden6** [comment]
ok, then I don't know why the file picker behaves in this strange way for you.

what's wrong with the paths?

**Comment by 2635599** [comment]
i was referring to what you guys have planned, not how it is now. from what i see the one folder i asked about above contains everything i need to restore. from your linked thread it looks like you guys are planning to have the files in more than one location. if i've misread apologies.

**Comment by anthonybilinski** [comment]
Feedback noted, will be taken into consideration when paths get reworked. Note that we do have a "portable" mode which will store all files in the same directory as the binary for maximally contained files.
