### ISSUE TITLE
not excepting toxme.io

### ISSUE THREAD

**Issue by 2635599** [qTox/qTox#5475]
linux mint cinnamon 19.1 tessa 64 bit

just removed and added qtox back and when i go to register on the serber i get told that it does not support toxme. i' at a loss help.

**Comment by anthonybilinski** [comment]
I just tested adding a profile to toxme.io, and it registered fine. Could you clarify what your issue is?

Are you trying to register the same username with a new Tox profile from within qTox's profile settings?

**Comment by 2635599** [comment]
![qtox](https://user-images.githubusercontent.com/22320686/50580250-0c8f8800-0e01-11e9-9f63-3638498caaa1.png)

**Comment by anthonybilinski** [comment]
I still don't see a problem from your picture, that just looks like a normal profile settings page. What causes you to see the error of "Server doesn't support Toxme"? Are you sure you had "toxme.io" as the server name, which should be selectable from the dropdown?

**Comment by 2635599** [comment]
yes quit sure, as for the drop down menu there is nothing else to select.  so from your previous post you're sating that mddle section is for registering a new account?

**Comment by anthonybilinski** [comment]
Yes, this middle section (as per title and button) is only for registering with ToxMe. If you would like to log in to your ToxMe account using your old password from registering to update your ToxID, currently you have to do that through the website here: https://toxme.io/edit_ui

There is a feature request to add this functionality to qTox already here: https://github.com/qTox/qTox/issues/5014

**Comment by 2635599** [comment]
o.k. thanks
