### ISSUE TITLE
"Peer has joined group" message misses one peer

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5478]
##### Brief Description
OS: Ubuntu 18.04
qTox version: v1.16.3+
Commit hash:  aa83edf7599acafcfb546eb02d18834aeb6efa20
toxcore:  v0.2.8
Qt:  5.9.5

Reproducible: Sometimes

##### Steps to reproduce

1. Load persistent group with multiple members

Happened on 3/3 of the groups I reconnected to, two with 3 members and one with 6 members. Each time I was short exactly one name.

##### Observed Behavior
1. "A new user joined" message for each peer, but missing one name message.
![image](https://user-images.githubusercontent.com/10469203/50703889-61521f00-100a-11e9-88f9-92ccb691e5a3.png)

##### Expected Behavior
1. Anytime there is a "A new user joined" message, it should be followed by a name message.

@Monsterovich in case you have something in mind.

**Comment by anthonybilinski** [comment]
From timestamps, it looks like the "<Name> has joined the group" message is only printed when the next "A new user has connected" message is printed, causing me to miss the last "<Name>" message.

**Comment by Monsterovich** [comment]
I assume that the user you painted over with red color has no nickname. Am I right?

**Comment by anthonybilinski** [comment]
In the group header, all members do have nicknames in all of the groups. Red's name shows the same as it shows in my friends list.

**Comment by Monsterovich** [comment]
>In the group header, all members do have nicknames in all of the groups. Red's name shows the same as it shows in my friends list.

1. When a user joins the group, his nickname is actually "<empty>" by default so "A new user has connected to the group" message is triggered.
2. If this user *has a* nickname, it will be changed from "<empty>". This events triggers "$name$ has joined the group message."

I think you just have an alias for your "blue" friend but his name is actually empty. Please check out if this is the case. You may also contact me and we'll test this together.

**Comment by anthonybilinski** [comment]
I agree with your view of (intended) behaviour.
>I think you just have an alias for your "blue" friend but his name is actually empty

I don't think this is the case. I don't have an alias for the friend set, and also the same friend is in a different group with me, where his name is logged properly. Again the last peer to join that other group's name is not logged, it just happens to be a different friend for that group.

I'll send you a Tox invite :)
