### ISSUE TITLE
Broken highlighting / URL underlining

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#548]
http://a.pomf.se/magblj.png

Message highlighting and URL underlining don't effect the entire piece of text. Additionally, highlights seem to add an extra newline or something.

**Comment by ghost** [comment]
CSI ENHANCE
http://a.pomf.se/ytvqnk.png
http://a.pomf.se/ioifos.png

**Comment by tux3** [comment]
Does it change anything if you select/unselect the text ?

**Comment by ghost** [comment]
Selected text has a solid selection color but once unselected, the highlighting still has random spaces.

**Comment by ghost** [comment]
ohgod.png
http://a.pomf.se/ddmiyl.png

**Comment by dubslow** [comment]
Isn't this upstream, since it's just html styling?

**Comment by tux3** [comment]
It seems to be upstream, but maybe there's a workaround ?

What OS / windows manager were you running qTox on ?

**Comment by tux3** [comment]
I can't fix this easily from qTox's code, it's an upstream bug.
