### ISSUE TITLE
Emoji parsing uses too much CPU

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5486]
##### Brief Description

OS: Arch Linux Arm, Linux 3.10.18
qTox version: v1.16.3+  
Commit hash: f2e8567b21b140ad1b459a2ff7dfc4e61ce66369
toxcore: 0.2.8
Qt: 5.12.0
Hardware: ARM Chromebook, armv7l 

Reproducible: Always

##### Steps to reproduce

1. Enable settings -> user interface -> use emoticons
2. Have about 50 friends, most with at least 100 messages (the default loaded on start)
3. Restart qTox

##### Observed Behavior
After entering password, about 3m20s of 100% CPU usage before qTox main window opens.

##### Expected Behavior
qTox to open within a couple seconds.

##### Additional Info
With perf, I've identified that almost all of the startup CPU usage is in libpcre2, used by Qt's regex. Disabling emoticons makes the problem go away almost completely, meaning the problem is isolated to `SmileyPack::smileyfied`, where we iterate over all of our emoticon keys (~100) for every possible start position in the passed in string, causing ~1000 regex expressions to be constructed for each message passed in.

Regex should probably be avoided completely here if we're going to try to match 100s of keys to every character spot of every message, even if it makes the start/end whitespace constraints easier.

**Comment by sudden6** [comment]
I think I've seen this slow startup issue too on my weak laptop. I think it might make sense to construct one bigger regex containing all the keys for smileys to improve the performance. I guess creating and compiling a regex is expensive, but not the actual execution of the search.

If that doesn't work I'd have the following ideas to solve this problem:
- Load messages only when first displaying a contact or even only when the chat is visible (would free a lot of RAM probably)
- Load messages asynchronously without blocking startup

**Comment by sudden6** [comment]
I took a deeper look at this issue and it seems we're just doing stupid stuff here, working on it.
