### ISSUE TITLE
QAction not found

### ISSUE THREAD

**Issue by f-florian** [qTox/qTox#5488]
##### Brief Description
I just tried to compile branch master, and I got the following error:
`<path-to-source>/qTox/ui_loadhistorydialog.h:13:10: fatal error: 'QtGui/QAction' file not found`
`#include <QtGui/QAction>`

It seems to be due to the fact that QAction has moved to the QtWidgets module, because I get
`$ locate -i qaction`
`/usr/include/qt4/Qt/qaction.h`
`/usr/include/qt4/Qt/qactiongroup.h`
`/usr/include/qt4/QtGui/QAction`
`/usr/include/qt4/QtGui/QActionEvent`
`/usr/include/qt4/QtGui/QActionGroup`
`/usr/include/qt4/QtGui/qaction.h`
`/usr/include/qt4/QtGui/qactiongroup.h`
`/usr/include/x86_64-linux-gnu/qt5/QtGui/QActionEvent`
`/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QAction`
`/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QActionGroup`
`/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qaction.h`
`/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qactiongroup.h`
see also [Qt Widgets C++ Classes](http://doc.qt.io/qt-5/qtwidgets-module.html) and [Qt GUI C++ Classes](http://doc.qt.io/qt-5/qtgui-module.html) for the latest Qt version.

OS: Ubuntu 16.04.5 LTS
qTox version: git master branch
Commit hash: 92d3c959a1bc80688957c4775eb781e8804b76df 
Qt:  5.5.1

**Comment by Chiitoo** [comment]
I believe that file is generated at compile time, and for whatever reason your configuration seems to be picking up the Qt 4 header.

For example, here's a snippet from a build I just did here:

```
 1 ********************************************************************************
 2 ** Form generated from reading UI file 'loadhistorydialog.ui'
 3 **
 4 ** Created by: Qt User Interface Compiler version 5.12.1
 5 **
 6 ** WARNING! All changes made in this file will be lost when recompiling UI file!
 7 ********************************************************************************/
 8
 9 #ifndef UI_LOADHISTORYDIALOG_H
10 #define UI_LOADHISTORYDIALOG_H
11
12 #include <QtCore/QVariant>
13 #include <QtWidgets/QApplication>
14 #include <QtWidgets/QCalendarWidget>
15 #include <QtWidgets/QDialog>
16 #include <QtWidgets/QDialogButtonBox>
17 #include <QtWidgets/QLabel>
18 #include <QtWidgets/QVBoxLayout>
19
20 QT_BEGIN_NAMESPACE
21
22 class Ui_LoadHistoryDialog
23 {
[...]
```

How are you configuring and building qTox exactly, and what does the header of your header look like?

**Comment by f-florian** [comment]
> I believe that file is generated at compile time

Of course it is, I did not notice the `ui_` prefix before. So a `make clean; make` solves this problem; sorry for the useless report.

I still wonder how could I compile it the first time though, since qt5 was already installed and I am not aware of changes in the qt configuration on this machine since then.

**Comment by Chiitoo** [comment]
> I still wonder how could I compile it the first time

Magic, probably.  :]

Glad it was a simple fix like that, even if the actual cause might remain as a bit of a mystery still.
