### ISSUE TITLE
qTox crashed when pasting large text

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#549]
32c33024623444e327346cd779ecbff8e447003a

https://gist.github.com/zetok/7c98eb040eae5451001d

I've tried to send test sample of text to ToxBot, qTox didn't like it.

**Comment by zetok** [comment]
Reproducible on cb812005824f3bd8222ecebd156421b78c3f00fd

**Comment by dubslow** [comment]
I would bet this is related to tab completion. Can you test https://github.com/tux3/qTox/commit/cd59117fa940d851c244b2f259abbe5c0888535c? If you can't reproduce there but can reproduce on https://github.com/tux3/qTox/commit/b6d581a462880ce7fe4919f3008fee5da14442a5, then it's definitely tab completion problem (specifically, with how [KeyPressEvents are intercepted from the chat input](https://gist.github.com/zetok/7c98eb040eae5451001d#file-gistfile1-txt-L46)).

**Comment by zetok** [comment]
@dubslow same result on cd59117fa940d851c244b2f259abbe5c0888535c

**Comment by dubslow** [comment]
Shit really?

What message are you sending?

@apprb

**Comment by zetok** [comment]
@dubslow test sample I've used, copied into qTox using leafpad: http://a.pomf.se/fffboi.7z

**Comment by tux3** [comment]
Does it still happen if you just paste the text into qTox but don't send the message ?

What if you wait a couple of minute between copypasting and sending ?

**Comment by zetok** [comment]
@tux3 still aborts when pasting without sending, though something interesting, when gdb catches abort:
![ABORT](https://cloud.githubusercontent.com/assets/3148759/4799938/0b0a13e0-5e21-11e4-87fd-7e2e8909c7ae.png)

**Comment by apprb** [comment]
Tried yesterday to send whole text:
1) Just pasting is OK, but you have to wait some time (probably `GenericChatForm::msgEdit->setUndoRedoEnabled(false);` may be usefull).
2) Sending: I got bored to wait.

**Comment by dubslow** [comment]
Fixed?

**Comment by zetok** [comment]
@dubslow can't really verify, since when I've pasted text RAM usage in matter of seconds increased to >1.4GB before I've pressed ^C in gdb.

EDIT: oh, I guess it's probably "fixed", since it no longer has SIGABRT when trying to use  >512MB of RAM when pasting text…

**Comment by tux3** [comment]
Welp.
