### ISSUE TITLE
Information Regarding Audio Codec

### ISSUE THREAD

**Issue by humabajwa** [qTox/qTox#5491]
I need to know where exactly in the code is the audio codec used. Where in the code does the audio stream enter the codec and is encoded?

##### Brief Description

OS: Windows / OS X / Linux (include version and/or distro)  
qTox version: (version numbers in menu `Settings → About`)  
Commit hash:  
toxcore:  
Qt:  
Hardware:  
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. 
2. 
3. …

##### Additional Info
(links, images, etc go here)

----

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA%\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by anthonybilinski** [comment]
qTox uses [Toxcore](https://github.com/TokTok/c-toxcore) which handles the Tox protocol, including encoding and decoding audio and video. Toxcore uses libopus for audio, so the actual encoding is handled by libopus [here](https://github.com/TokTok/c-toxcore/blob/98b754e1f22220f10196760389371dba6d139c6f/toxav/toxav.c#L776).
