### ISSUE TITLE
QSplitter between friendlist and chatwindow

### ISSUE THREAD

**Issue by msteinbeck** [qTox/qTox#55]
It would be useful if a user could adjust the width of the friendlist/chatwindow.

**Comment by F1ynn** [comment]
Working on it. There's a lot that has to be adjusted before it looks good, but I should be done by tomorrow.

**Comment by ProMcTagonist** [comment]
Nice :)

**Comment by msteinbeck** [comment]
I obviously meant QSplitter instead of QSlider

**Comment by F1ynn** [comment]
Added in latest PR. Note that depending on your CPU speed there may be some flickering when resizing, this isn't an ideal implementation but it does work.

**Comment by tux3** [comment]
Fixed by @F1ynn 's PR
