### ISSUE TITLE
qTox application icon looks bad on KDE

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#550]
This should be listed as a very minor enhancement, but...:
![qtox_logo_kde](https://cloud.githubusercontent.com/assets/1885159/4791421/e130ea60-5ddc-11e4-90e9-517f84366926.png)
(The uTox logo obviously looks better than the stretched out qTox one)

**Comment by TheLastProject** [comment]
This issue seems to have been fixed somewhere along the way. Closing this.

**Comment by dubslow** [comment]
Was likely an upstream issue. Whether it was KDE or Qt, who knows. (I guess probably the latter, since uTox shares the former?)
