### ISSUE TITLE
[suggestion] Please port qTox to Android

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#5503]
---Problem---
Over a few years I was trying first Antox, then Trifa on Android. Both have problems - they don't see that their peers are online, crash, etc. Trifa might appear to be working at a first glance, but in the real world conditions it just doesn't work.

They both are reimplementations of Tox in other languages (Java?). IMO, this is the source of problems, since reimplementations of such complex software is bug-prone, and this is what happens with them: they are perpetually buggy with no hope in sight.

---Solution---
Instead of reimplementing Tox on Android from scratch and go through many rounds of bug fixing, some stable existing client should be ported there. qTox is a good candidate.

Qt docs say that it is available for Android: http://doc.qt.io/qt-5/android.html

**Comment by 2635599** [comment]
you have antox, and it's easy to copy your user file into it. it's what i did.

**Comment by yurivict** [comment]
@2635599 Copying files isn't a point.

**Comment by sudden6** [comment]
@yurivict Short answer: no

Longer answer: First we barely have enough people to maintain and develop qTox on the existing platforms. Second, Android would need a complete rewrite of the user interface + build system for Android.

> They both are reimplementations of Tox in other languages (Java?)

This is wrong, they both use the same c-toxcore (maybe not Trifa, it probably has some patches) just wrapped with a Jave interface.

**Comment by anthonybilinski** [comment]
I agree with @sudden6. It would be nice to have in the distant distant future, but qTox on desktop is still not very stable and still missing many features. We should limit scope of the project until what we have now is full featured and robust, and possibly expand once we're there. I also don't think it would be a small amount of work, even if we can re-use some of the existing desktop qTox.

**Comment by wuniversales** [comment]
Any news about this?
I'm still waiting for news in this regard. :(

**Comment by sudden6** [comment]
qTox will never be an Android client. If you want Android try https://github.com/evilcorpltd/aTox or https://github.com/zoff99/ToxAndroidRefImpl
