### ISSUE TITLE
When joining a group audio call, all peers show as in call

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5506]
##### Brief Description

OS: Windows + Ubuntu 18.04
qTox version: 1.16.3+
toxcore:  v0.2.9

Reproducible: Always

##### Steps to reproduce

1. Join an audio group with multiple members.
2. Join the call.

##### Observed Behavior
1. All members of the group will show as in the call, whether or not they really are.
2. If a member joins then leaves the call, their avatar will be correctly removed.
3. If a member rejoins their avatar will be correctly re-added.

##### Expected Behavior
1. When joining an audio call, only group members in the call's avatars are shown as in the call.

**Comment by sudden6** [comment]
I think this behavior happens, because qTox by default creates audio groups for everything to work around the fact that you can not change the type of a group (text/audio) after it was created.
For people not audio calling, qTox just doesn't send any audio or plays received audio.

I'm afraid, I doubt this will be easy to fix.

**Comment by anthonybilinski** [comment]
It looks like the way we're dynamically displaying and hiding group peer avatars when they're "in the call" is by just saying, if we've received audio data from them recently they are, if we haven't, remove them. This same logic works fine when first joining the group call, e.g. by removing:
```
    for (const auto& peerPk : names.keys()) {
        if (peerPk != ownPk) {
            static_cast<GroupNetCamView*>(view)->addPeer(peerPk, names.find(peerPk).value());
        }
    }
```
from GroupChatForm::createNetcam. Change is tested.

I'll create a PR with this change soon.
