### ISSUE TITLE
The peerlist area is too small

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#551]
It glitches and becomes totally unreadable sometimes too. But that aside, if it isn't going to be a vertical column, could it slide out down like a drawer so we can see everyone in it? At least enough to scroll.

**Comment by zetok** [comment]
Proposed way of fixing #382 would close this issue.

**Comment by ProMcTagonist** [comment]
Peers are now wrapped in current qTox.

![peerlist fixed](https://cloud.githubusercontent.com/assets/4358079/4925456/3a3b87be-652b-11e4-9d7a-be98bd9bc77d.png)

This fixes not being able to see a large amount of peers.
But what happens when it overflows, when you have hundreds of peers? Separate issue?

**Comment by tux3** [comment]
> But what happens when it overflows, when you have hundreds of peers? 

You mean when you have so many peers that it can't possibly fit ?
The last peers on the list will be hidden. 
Would you rather have a scrollbar maybe ?

![image5](https://cloud.githubusercontent.com/assets/5155966/4964337/bb66e94e-6758-11e4-8ffe-6eb851c047cb.jpg)

> Separate issue?

Yep.
