### ISSUE TITLE
Closing qTox while in group call segfaults after exit

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5518]
##### Brief Description
Reproducible: Almost Always

##### Steps to reproduce

1. Be in a group audio call.
2. Close qTox without leaving the call or group.

##### Observed Behavior
1. qTox closes, but segfaults after saving.

##### Expected Behavior
Clean exit.

##### Additional Info
CoreAv's static groupCalls destructor calls ~ToxGroupCall, which calls into our static OpenAL variable. This looks like a classic static destruction race, where the two variables are constructed in a semi-random order and destroyed in a semi-random order, even though ~ToxGroupCall depends on OpenAL.

**Comment by anthonybilinski** [comment]
This is still present after the audio refactor in 22362d29400a3bc1684d227e355feb52fd28c9de. Even though Audio is no longer a singleton, Core still is.

**Comment by sudden6** [comment]
Once https://github.com/qTox/qTox/pull/5926 is merged, this should be re-evaluated as it makes Core and Audio completely threadsafe and should prevent this issue.

**Comment by anthonybilinski** [comment]
Hm looks like https://github.com/qTox/qTox/pull/5921 should have fixed this as well. I'll test before your change as well to see :P

**Comment by anthonybilinski** [comment]
I just tested on 17bbe24ec571c01aae0a8130dcad8f112d8afa2c (right before #5921) with a group of 4 profiles in a group call together. The 2 that closed while still in the call both segfaulted.

I then tested on 08436bc2f1c3a0dfa05590c99f6c329b88a5e91f (right after #5921) and closed 3 of the profiles while still in the call, with none of them crashing. Closing.
