### ISSUE TITLE
Fix qTox Package Errors in Debian Buster

### ISSUE THREAD

**Issue by Nurmagoz** [qTox/qTox#5520]
##### Brief Description

OS: GNU/Linux , Debian 9
qTox version: qtox (1.16.3-1)  

Please Fix Errors Reported in Debian Buster: 

https://tracker.debian.org/pkg/qtox

**Comment by sudden6** [comment]
@yangfl you seem to be maintaining this package, can we help in some way to fix these issues?

**Comment by yangfl** [comment]
They are not serious bugs that will affect next Debian release. I'll address them althogether at next qtox release.

**Comment by Nurmagoz** [comment]
> This package is failing and has never passed. 

https://ci.debian.net/packages/q/qtox/testing/amd64/

**Comment by anthonybilinski** [comment]
Looks like this was fixed 2020-11-05 based on above link, closing.
