### ISSUE TITLE
Audio group peer avatars become duplicated

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5536]
Commit hash: f5aa07f5694a9172bb0bb6c4870cf5486a3460a7
Reproducible: Rarely

##### Steps to reproduce

1. Be in a group audio call for a couple hours.

##### Observed Behavior
Peer avatar pictures of some peers became duplicated:
![image](https://user-images.githubusercontent.com/10469203/51828475-84d25780-22a0-11e9-9409-af602ea88e23.png)

**Comment by sudden6** [comment]
I'd guess that's because we use `groupId` there instead of the more unique `ToxPk`.
