### ISSUE TITLE
Groups with default names fail to load on next start

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5542]
##### Brief Description
qTox version: v1.16.3+
Commit hash:  d2508e7eac26d731c746333b5d74e9a051d3f5b7
toxcore:  v0.2.9

Reproducible: Always

##### Steps to reproduce

1. Create a group.
2. Don't change from the default, e.g. "Groupchat #0"
3. Restart qTox.

##### Observed Behavior
1. The group does not appear in the contacts list on load.
2. ```core/core.cpp:58 : Warning: Invalid conference title length``` is logged.

##### Expected Behavior
1. The group appears in the contacts list with the same name "Groupchat #0" as was seen on creation.

##### Additional Info
We likely don't call down to toxcore to set group title and the "Groupchat #0" title is only used in UI. Either we should set "Groupchat #0" in toxcore on group creation, or we should check for 0-length titles in toxcore and instead of fetching their name, send them to qTox and again generate a default title.

IMO setting the name in toxcore would be better so that peers using other clients would see the same name, and so that the name wouldn't change numbers between starts.

**Comment by sudden6** [comment]
> IMO setting the name in toxcore would be better so that peers using other clients would see the same name, and so that the name wouldn't change numbers between starts.

I support this.

**Comment by anthonybilinski** [comment]
Thinking about this more, even if we do set our "Groupchat 1"-style name on creation, there are still a couple problems
1) what if someone else creates the group, or clears the name? we don't want  to be fighting other clients to ensure a name is always set when it's valid to have an empty name. We need to be able to gracefully handle an empty-named groupchat for this reason.
2) If we save the string "Groupchat 1" name, and create the name just off the toxcore group ID on creation, since those IDs are not unique across instance restarts (AFAIK) we could end up creating a group with the same title as a loaded group, confusing the user.

Just handling empty titles with generated names on load fixes both of these issues, but then we're left with the changing titles across client restart problem.

What about including part of the groups' long-term unique ID (32 byte, persistent) in the UI when the name is empty, e.g. <Groupchat 39F56A7FE>, and similarly setting that title if and only if we are the ones creating the group?

**Comment by Kribylet** [comment]
Probably related to https://github.com/qTox/qTox/issues/5694
