### ISSUE TITLE
Hangs when switching from the Video/Audio tab

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#5544]
Version qTox-1.16.3_4 freezes when the video test screen was shown on the Video/Audio tab and the user switches out to some other screen.

FreeBSD 11.2, built from the port.

**Comment by sudden6** [comment]
Can you please fill out the issue template? Also logs can be helpful.

**Comment by anthonybilinski** [comment]
@yurivict  a similar bug was fixed in https://github.com/qTox/qTox/pull/5517 which was merged a couple days before your issue was created as 093962e3ec05aa21a27083e9d7e096c00194568d. Could you try updating to tip and see if the issue still occurs?

**Comment by sudden6** [comment]
No response, assuming this is not a problem anymore.
