### ISSUE TITLE
Emoticons

### ISSUE THREAD

**Issue by Knux14** [qTox/qTox#555]
Hi there,
My friend Cylgom made a pack of opensource icons for you (originally for µTox but he wants it for any Tox client)

Here's the link: http://cylgom.net/projects_details.php?id=11

**Comment by tux3** [comment]
Thanks, I think we can add those along with @krepa098's and ship both with qTox if nobody has any objection.

Do you have a "text version" for all the emoticons, though ? I haven't seen one on the website.
By text version I mean for exemple :) for :smile: and :o for :open_mouth:

**Comment by krepa098** [comment]
I don't mind :)
Btw. there's no emoticons.xml.

**Comment by nullgemm** [comment]
Hi, I'm the author of that pack ;)
I'll try to write the emoticons.xml as soon as I can, I'll post a message here when it's done.
Btw, Knux didn't mentionned it, but these emoticons are open-source and licensed under WTFPL.
Feel free **not** to credit me :p

**Comment by nullgemm** [comment]
@krepa098 @tux3 
http://www.mediafire.com/download/ffx6eqjqro02528/cylgom_icons_qTox.zip
Here it is : I wrote the emoticons.xml file and added some new icons to the pack.
I tried it in qTox and it works, but the icons seems to be scaled down, is this normal ?

**Comment by dubslow** [comment]
Yes, because if they're too large the HTML renderer expands the line to fit the smiley size, and it doesn't render very well.

https://github.com/tux3/qTox/issues/501

There are probably other solutions that would allow not scaling the smiley, but they would be fairly complex I think.

**Comment by krepa098** [comment]
Indeed they are really tiny now. Hopefully we can get them back to a reasonable size in a not too distant future.
Anyway, your smiley pack is working fine. :smiley:

**Comment by dubslow** [comment]
Don't forget the :Kappa:

**Comment by tux3** [comment]
Of course :)
![pic2](https://cloud.githubusercontent.com/assets/5155966/4832392/ad0201be-5f9b-11e4-8bb5-f23bdd82b707.jpg)

**Comment by dubslow** [comment]
I mean in the other pack :P
