### ISSUE TITLE
Dark/custom theme request

### ISSUE THREAD

**Issue by DekyYT** [qTox/qTox#5556]
Hello! I am pretty new to this program but, I would like to request a way to make the qTox client dark/have a custom theme. Something like css or who knows what. It would be a neat little thing, I see it already has support for styles.

**Comment by quantumpacket** [comment]
See issue #1639

**Comment by 2635599** [comment]
agree 1,000,000,000% we need a dark theme and perhaps an entire gui overhaul.

**Comment by rubberbandaid** [comment]
"agree 1,000,000,000% we need a dark theme and perhaps an entire gui overhaul."
qTox does not need an entire GUI overhaul, at least IMO. The GUI is great as it is.
A dark theme, maybe. But please leave the GUI as is.

**Comment by 2635599** [comment]
liking 

https://github.com/qTox/qTox/pull/5558

> "agree 1,000,000,000% we need a dark theme and perhaps an entire gui overhaul."
> qTox does not need an entire GUI overhaul, at least IMO. The GUI is great as it is.
> A dark theme, maybe. But please leave the GUI as is.

you might be right.a good dark theme would distract from the form of qtox.

**Comment by rubberbandaid** [comment]
Please reread what I posted. Those are two totally separate items.

**Comment by DekyYT** [comment]
a GUI overhaul? hmm, i don't know, i quite like it, i think it looks great

**Comment by sudden6** [comment]
Done by #5558
