### ISSUE TITLE
Qtox crashes when acepting a call or switching to audio/video under settings

### ISSUE THREAD

**Issue by razzor1984** [qTox/qTox#5560]
##### Brief Description

OS: Windows - 1803/17134.590
qTox version: You are using qTox version v1.16.3
Commit hash: 8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.3
Qt:  5.9.6
Hardware:  Ryzen // RX580 //32gb ram
…

Reproducible: Always

##### Steps to reproduce

1. Open qTOX
2. Go to settings (geearweheel) click to Audio/Video

Or
Simply call somebody or take a call 

##### Observed Behavior

QTox Crashes / Closes

##### Expected Behavior
Qtox should not crash or close itself

##### Additional Info
Output of: C:/Users/XXX/AppData/Roaming/tox/qtox.log

```
> [22:36:45.336 UTC] persistence/settings.cpp:133 : Debug: "Loading settings from C:/Users/XXX/AppData/Roaming/tox/qtox.ini"
> [22:36:45.352 UTC] ipc.cpp:61 : Debug: Our global IPC ID is  3169903406987816468
> [22:36:45.353 UTC] main.cpp:258 : Debug: commit:  8eed684c37bd711de2ca4bd863f5f0509edcdc2d
> [22:37:05.665 UTC] persistence/profile.cpp:117 : Debug: Loading tox save  "C:/Users/XXX/AppData/Roaming/tox\\yxyxyxy.tox"
> [22:37:05.731 UTC] persistence/settings.cpp:462 : Debug: "Saving global settings at C:/Users/XXX/AppData/Roaming/tox\\qtox.ini"
> [22:37:05.768 UTC] persistence/settings.cpp:335 : Debug: Loading personal settings from "C:/Users/XXX/AppData/Roaming/tox/yxyxyxy.ini"
> [22:37:05.770 UTC] nexus.cpp:87 : Debug: Starting up
> [22:37:06.258 UTC] :0 : Warning:   OpenType support missing for "MS Shell Dlg 2", script 16
> [22:37:06.259 UTC] :0 : Warning:   OpenType support missing for "Arial", script 16
> [22:37:06.261 UTC] :0 : Warning:   OpenType support missing for "MS UI Gothic", script 16
> [22:37:06.261 UTC] :0 : Warning:   OpenType support missing for "SimSun", script 16
> [22:37:06.381 UTC] core/core.cpp:202 : Debug: Loading user profile
> [22:37:06.381 UTC] core/toxoptions.cpp:65 : Warning: Core starting with IPv6 disabled. LAN discovery may not work properly.
> [22:37:06.386 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:Messenger.c:messenger_load_state_callback:3160: Load state: contains unrecognized part (len 0, type 20)\n"
> [22:37:06.682 UTC] persistence/profile.cpp:82 : Debug: Self avatar not found, will broadcast empty avatar to friends
> [22:37:06.789 UTC] widget/systemtrayicon.cpp:83 : Debug: Using the Qt backend
> [22:37:07.616 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:network.c:receivepacket:636: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.\r\n"
> [22:37:08.493 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:network.c:sendpacket:562: attempted to send message with network family 10 (probably IPv6) on IPv4 socket"
> [22:37:08.493 UTC] core/core.cpp:357 : Debug: "Connecting to 46.229.52.198:33445 (Stranger)"
> [22:37:08.494 UTC] core/core.cpp:357 : Debug: "Connecting to 2a02:c200:1:10:3:1:605:1337:5190 (tastytea)"
> [22:37:08.494 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:network.c:sendpacket:562: attempted to send message with network family 10 (probably IPv6) on IPv4 socket"
> [22:37:08.616 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:network.c:receivepacket:636: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.\r\n"
> [22:37:10.495 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:network.c:sendpacket:562: attempted to send message with network family 10 (probably IPv6) on IPv4 socket"
> [22:37:10.618 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:network.c:receivepacket:636: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.\r\n"
> [22:37:12.492 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:network.c:sendpacket:562: attempted to send message with network family 10 (probably IPv6) on IPv4 socket"
> [22:37:12.554 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:network.c:receivepacket:636: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.\r\n"
> [22:37:12.616 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:network.c:receivepacket:636: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.\r\n"
> [22:37:13.553 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:network.c:receivepacket:636: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.\r\n"
> [22:37:14.116 UTC] core/core.cpp:357 : Debug: "Connecting to 185.14.30.213:443 (dvor)"
> [22:37:14.117 UTC] core/core.cpp:357 : Debug: "Connecting to 37.48.122.22:33445 (Pokemon)"
> [22:37:14.554 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:network.c:receivepacket:636: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.\r\n"
> [22:37:14.616 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:network.c:receivepacket:636: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.\r\n"
> [22:37:15.492 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:network.c:sendpacket:562: attempted to send message with network family 10 (probably IPv6) on IPv4 socket"
> [22:37:15.494 UTC] core/core.cpp:326 : Debug: Connected to the DHT
> [22:37:15.496 UTC] persistence/profile.cpp:329 : Debug: Saving tox save to  "C:/Users/XXX/AppData/Roaming/tox\\yxyxyxy.tox"
> [22:37:15.555 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:network.c:receivepacket:636: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.\r\n"
> [22:37:15.617 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:network.c:receivepacket:636: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.\r\n"
> [22:37:28.938 UTC] audio/backend/openal2.cpp:215 : Debug: Opening audio output "Lautsprecher (Realtek High Definition Audio)"
> [22:37:28.942 UTC] audio/backend/openal2.cpp:227 : Debug: Opened audio output "Lautsprecher (Realtek High Definition Audio)"
> [22:37:29.007 UTC] audio/backend/openal2.cpp:199 : Debug: Echo cancelation enabled
> [22:37:29.044 UTC] video/camerasource.cpp:271 : Debug: Opening device "none" subscriptions: 1
> [22:37:29.044 UTC] video/cameradevice.cpp:152 : Debug: Tried to open the null device
> [22:37:29.044 UTC] video/camerasource.cpp:284 : Warning: Failed to open device!
> [22:37:29.051 UTC] widget/form/settings/avform.cpp:389 : Debug: available Modes:
> [22:37:29.051 UTC] widget/form/settings/avform.cpp:298 : Debug: selected Modes:
> [22:37:29.052 UTC] audio/backend/openal.cpp:680 : Debug: Audio source 3 created. Sources active: 1
> [22:37:29.052 UTC] audio/backend/openal.cpp:298 : Debug: Opening audio input "Front Microphone (2- Realtek Hi"
> [22:37:29.052 UTC] audio/backend/openal.cpp:316 : Warning: Failed to initialize audio input device: "Front Microphone (2- Realtek Hi"
> [22:37:29.052 UTC] audio/backend/openal.cpp:239 : Warning: Failed to subscribe to audio input device.
> 
```

**Comment by anthonybilinski** [comment]
Hi @razzor1984, v1.16.3 is getting a bit old. Could you try a nightly build from https://tox.chat/download.html and see if you can reproduce the issue?

**Comment by razzor1984** [comment]
Hi @anthonybilinski 
Tested it with the newest nightly
qTox version: You are using qTox version v1.16.3-273-gd2508e7.
Commit hash: d2508e7eac26d731c746333b5d74e9a051d3f5b7
toxcore: 0.2.9
Qt: 5.9.3

Sadly the same outcome :(

thats the output from the debuglog:
 >[11:36:35.194 UTC] persistence/settings.cpp:133 : Debug: "Loading settings from C:/Users/xxxx/AppData/Roaming/tox/qtox.ini"
>[11:36:35.221 UTC] ipc.cpp:61 : Debug: Our global IPC ID is  3169903406987816468
>[11:36:35.222 UTC] main.cpp:272 : Debug: commit:  d2508e7eac26d731c746333b5d74e9a051d3f5b7
>[11:36:35.230 UTC] persistence/profile.cpp:140 : Debug: Loading tox save  "C:/Users/xxxx/AppData/Roaming/tox\\tox_save.tox"
>[11:36:35.231 UTC] core/toxoptions.cpp:93 : Warning: Core starting with IPv6 disabled. LAN discovery may not work properly.
>[11:36:35.231 UTC] persistence/settings.cpp:464 : Debug: "Saving global settings at C:/Users/xxxx/AppData/Roaming/tox\\qtox.ini"
>[11:36:35.277 UTC] persistence/settings.cpp:338 : Debug: Loading personal settings from "C:/Users/xxxx/AppData/Roaming/tox/tox_save.ini"
>[11:36:35.283 UTC] nexus.cpp:83 : Debug: Starting up
>[11:36:37.926 UTC] :0 : Warning:   OpenType support missing for "MS Shell Dlg 2", script 16
>[11:36:37.932 UTC] :0 : Warning:   OpenType support missing for "Arial", script 16
>[11:36:37.939 UTC] :0 : Warning:   OpenType support missing for "MS UI Gothic", script 16
>[11:36:37.943 UTC] :0 : Warning:   OpenType support missing for "SimSun", script 16
>[11:36:38.069 UTC] persistence/profile.cpp:321 : Debug: Self avatar not found, will broadcast empty avatar to friends
>[11:36:38.696 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:39.635 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:39.697 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:39.759 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:39.884 UTC] core/core.cpp:440 : Debug: "Connecting to 45.59.119.218:33445 (ru_maniac)"
>[11:36:39.885 UTC] core/core.cpp:440 : Debug: "Connecting to 149.56.140.5:33445 (velusip)"
>[11:36:40.072 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:40.259 UTC] widget/systemtrayicon.cpp:83 : Debug: Using the Qt backend
>[11:36:40.635 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:40.697 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:40.760 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:40.964 UTC] net/updatecheck.cpp:90 : Info: qTox is up to date
>[11:36:41.697 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:41.759 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:42.634 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:42.696 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:43.697 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:43.759 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:43.823 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:44.823 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:45.509 UTC] core/core.cpp:440 : Debug: "Connecting to 2001:1af8:4700:a115:6::b:33445 (Pokemon)"
>[11:36:45.509 UTC] network.c:491 : Critical: attempted to send message with network family 10 (probably IPv6) on IPv4 socket
>[11:36:45.510 UTC] core/core.cpp:440 : Debug: "Connecting to tmux.ru:33445 (nrn)"
>[11:36:46.619 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:46.681 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:47.618 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:47.746 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:48.619 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
>[11:36:48.651 UTC] audio/backend/openal2.cpp:215 : Debug: Opening audio output "Lautsprecher (Realtek High Definition Audio)"
>[11:36:48.654 UTC] audio/backend/openal2.cpp:227 : Debug: Opened audio output "Lautsprecher (Realtek High Definition Audio)"
>[11:36:48.725 UTC] audio/backend/openal2.cpp:199 : Debug: Echo cancelation enabled
>[11:36:48.761 UTC] video/camerasource.cpp:271 : Debug: Opening device "none" subscriptions: 1
>[11:36:48.761 UTC] video/cameradevice.cpp:152 : Debug: Tried to open the null device
>[11:36:48.761 UTC] video/camerasource.cpp:284 : Warning: Failed to open device!
>[11:36:48.768 UTC] widget/form/settings/avform.cpp:398 : Debug: available Modes:
>[11:36:48.768 UTC] widget/form/settings/avform.cpp:230 : Critical: Trying to select best mode from empty modes list
>[11:36:48.768 UTC] widget/form/settings/avform.cpp:307 : Debug: selected Modes:
>[11:36:48.768 UTC] audio/backend/openal.cpp:680 : Debug: Audio source 3 created. Sources active: 1
>[11:36:48.768 UTC] audio/backend/openal.cpp:298 : Debug: Opening audio input "Front Microphone (2- Realtek High Definition Audio)"
>[11:36:48.769 UTC] audio/backend/openal.cpp:316 : Warning: Failed to initialize audio input device: "Front Microphone (2- Realtek High Definition Audio)"
>[11:36:48.769 UTC] audio/backend/openal.cpp:239 : Warning: Failed to subscribe to audio input device.
>[11:36:48.870 UTC] network.c:565 : Critical: Unexpected error reading from socket: 10054, Eine vorhandene Verbindung wurde vom Remotehost geschlossen.

**Comment by anthonybilinski** [comment]
@razzor1984 it looks like you have "Experimental Audio Backend" enabled under settings -> Audio/Video, which from my experience is _very_ experimental.

If you're crashing before you can even get to that settings page, you can manually edit the settings file at edit `%APPDATA%\tox\qtox.ini` and changing the line `enableBackend2=true` to `enableBackend2=false`. If you're having troubles editing the file, just deleting the file will also reset you to default settings (all settings).

Can you give that a try?

**Comment by Re4mstr** [comment]
Just tried this with the latest available nightly.

Same issue.

For some reason, changing "enableBackend2=true" -> "false", does not fix the crash. Deleting the qtox.ini file fixes this.

**Comment by anthonybilinski** [comment]
I'll close this ticket as duplicate since https://github.com/qTox/qTox/issues/5292 covers the same issue. We should probably disable this "experiment" or at least make it easier to revert since this seems like a common problem.
