### ISSUE TITLE
How to open qtox in Qt creator? I can't find the file "qtox.pro"

### ISSUE THREAD

**Issue by SteveCruise** [qTox/qTox#5567]
##### Brief Description

OS: ubuntu 18.10
qTox version: 2.9
Qt:  5.12
Hardware:  
…

##### Observed Behavior

How to open qtox in Qt creator? I can't find the file "qtox.pro".

**Comment by Diadlo** [comment]
Use CMakeLists.txt file

**Comment by SteveCruise** [comment]
@Diadlo Thanks a lot. Would you mind explaining a bit more specifical?

**Comment by Diadlo** [comment]
@SteveCruise "pro" files it's project files for qmake build system. qTox uses cmake build system => CMakeLists.txt file. Is it clear enough?

**Comment by SteveCruise** [comment]
@Diadlo Great thanks. I successfully build it in Qt. Thank you for your answer.

**Comment by ntuhubin** [comment]
> @Diadlo Great thanks. I successfully build it in Qt. Thank you for your answer.

How do you open Qtox in Qtcreator？
