### ISSUE TITLE
Voice call sound is crazy. I can hear myself but not the other person.

### ISSUE THREAD

**Issue by RobertThompson3072** [qTox/qTox#5568]
Brief Description
OS: Windows 7 Ultimate 32 bit.
qTox version: (version numbers in menu `Settings → About`)  
Commit hash:  8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.3
Qt:  Qt version: 5.9.6
Hardware:  Any of them, from both sides.

Reproducible: Rarely.

 Steps to reproduce
1. Make a voice call.
2. Stay on the call for a few hours.
3. And if you're "lucky" enough, you could be (like i was) frozen, doing exactly nothing and the bug will kick in. No idea why.

Observed Behavior
I was on a call for at least 4 hours+, playing a Flash game on Facebook (just mentioning in case of possible technical relation to this) and all sounds off on everything, i always keep it all off by default except QTox. All of a sudden, i wasn't hearing the other person anymore but hearing myself... I could hear before the other person's computer sounds too, whatever they can hear i can hear it too just lower, about 25% of the caller's volume is their computer sound volume. But this time, i could hear myself amplified like x10 times or something and the same with the other side's computer sounds, which was a YouTube video and i could no longer understand anything because of distortion of sound but still was hammering my head even at 5% sound so i had to put it to 3%...

Sorry for going so long but this is completely nuts, there's a bunch of problems i've been fine with but this one now ended me and the other person re-installing QTox and restarting computers multiple times, changing microphones and headphones and settings on computer and QTx (including notifications) and still no change, except now last re-call, i can't hear myself either or the other person's computer, i'm receiving zero sound from QTox, except notifications and the call start and end and such.

---> As i mentioned, might be important to remind you i already had all of these problems and was fine with them, the only problem that came up now was not being able to hear the other person and the amplification of the sounds i got in and now the final change, me receiving zero sound.

Expected Behavior
I expected it to fix by itself after restarts (it happened before) but even after restarting computer (me and the other side) and re-installing QTox still nothing changed, same problem.

Additional Info
No images or links that could serve anything here i believe, if needed, please let me know. Most likely i should re-do this whole report with your following advices since it's my first time on GitHub or reporting pretty much anything.
I see i can't hear anything from QTox or even Facebook for example... So it seems something else besides QTox on my side is the problem.
Update: Now it works. I did nothing, clicked on System Sounds -> Sound Scheme by mistake thanks to clicking it to see what's in it and it changed by scrolling, so i turned it back to the default and now it works... This is still crazy and makes no sense. Pleas stabilize voice or give us the option to kick off privacy but have a functioning QTox version.
----
I would gladly share the log with you by the way, but i just copied the thing and it's showing 2'347 lines and 240K+ chars without line endings... So i'll just guess you're better without it. But just in case it may serve anything, i have it saved.

**Comment by RobertThompson3072** [comment]
Very sorry for the readability of this but i feel stupid here, not used to this format.

Update: I still have the same problem just doesn't seem to be QTox only. It appears on Facebook Messenger too and it's exclusively only on voice calls, video calls or anything make no difference as it's just the voice in and out having a mess and it's only when on a call, every other sound of notifications or videos or anything whatsoever works great. All drivers checked and updated, all settings fixed and checked multiple times each, i can't seem to find anything wrong anywhere but still have a problem.
Checked and changed hardware also. What in the world could it be? I have the exact same problem on Tablet on another account and continues now with a different internet service provider too, so it's perplexing how this is even possible. None of it should be possible, nothing seems to tell me otherwise or even put that to doubt yet.

Please help me out, passing a second week with this problem now and absolutely no clues anywhere no matter how many troubleshootings i've done and instructions followed and info checked. I just hope someone could figure out the problem which seems to be limited to internet connection probably since no less than 3-4 devices have the same problem and different softwares used still have the same problem on each of those devices and yet, the service provider being only 2 options seems the one with the least of things it has proven to be okay so far, which is unbelievable to me how it could be so.

Thanks for your time in advance and sorry for taking so much of it. Just kind of desperate by now really.

**Comment by sudden6** [comment]
This sounds more like a problem with your audio hardware/software than with anything else. I can't really help you there.

You can try if this is fixed by using a cheap USB headset, but since you say it also happens with other programs, it's most certainly not qTox related.
