### ISSUE TITLE
qTox segfaults when clickspamming "Reconnect" and trying switch to "Identity"

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#557]
When I tried to switch to `Identity` tab after clickspamming `Rectonnect` button qTox segfaulted.

Steps to reproduce:
1. Clickspam `Reconnect` for few seconds, preferably fast enough for qTox to become almost/a bit not responsive
2. Try to switch to `Identity` tab
3. qTox segfaults

Reproducible: Always

qTox: 7a6b349e173fa1863fa77f0703d2931137d3b407
core: 70869b601ebd546aee2a909d9baa322cd4973227

https://gist.github.com/zetok/24371f7079b8a5e6a032

**Comment by tux3** [comment]
Ah, yes. Trying to display our tox id while tox is dead is not a good idea.

Maybe we should just freeze the GUI until Toxcore and Toxav are started again, this would save a lot of trouble fixing edge cases.

**Comment by dubslow** [comment]
Or maybe simpler to do, but more loc, is add a bunch of `if (!tox) return;`s everywhere

**Comment by tux3** [comment]
Yeah, but then we'd have forms/widgets with empty or buggy fields..

Just restarting tox shouldn't take long, loading things and connecting to the DHT is different.
