### ISSUE TITLE
Bloated IM window in multiple windows mode

### ISSUE THREAD

**Issue by Lokomojo** [qTox/qTox#5574]
##### Brief Description

OS: Windows
qTox version: 1.16.3
Commit hash:  8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.3

Reproducible: Always 

##### Steps to reproduce

1.  Enable Multiple Windows Mode
2.  Enable "Open each chat in an individual window"

##### Observed Behavior

Message window has a large amount of wasted space on the left hand side.  With the selected options, this space serves no purpose and shouldn't be visible..

https://gyazo.com/28c45096f51c6d8db8d40d0589f53251

##### Expected Behavior

Unnecessary area should be hidden

**Comment by Chiitoo** [comment]
You should be able to grab the line between the chat and the contact list there, and drag it left/right.  :]

**Comment by jessica181920** [comment]
@Chiitoo this works fine but it might be a good idea to make it hidden by default/remove it as it's unnecessary when opening each chat in an individual window is enabled. It's only useful when multiple chats occupy the same window.

**Comment by Lokomojo** [comment]
Yes, exactly this. You can hide it, but it serves no purpose so it shouldn't be visible by default

**Comment by Diadlo** [comment]
Seems, duplicate of #3458, so it will be closed. Please comment if it isn't
