### ISSUE TITLE
Video broken on OSX

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#558]
Reported/found by zetok/irungentoo

Please post infos, logs or backtraces here if you have any.

**Comment by stqism** [comment]
Filed a bug on this issue here: http://tox.lighthouseapp.com/projects/123754-tox/tickets/4-video-broken-on-os-x

**Comment by dubslow** [comment]
@krepa098 ^^

**Comment by krepa098** [comment]
Your build predates 0d840870008254e8ddc8e13ca224486edbddc9f1. Please retry using the latest version.

**Comment by dubslow** [comment]
Closeable?

**Comment by stqism** [comment]
@dubslow Totally closable.
