### ISSUE TITLE
Use emoji fonts instead of manually adding emoji svgs and updating XML files

### ISSUE THREAD

**Issue by jessica181920** [qTox/qTox#5585]
Instead of having to update the SVGs and maintain large XML files for displaying certain unicode emoji characters as emoticon SVGs, we should use FOSS color emoji font files, and update those occasionally by checking their respective repos. For example, [Noto Color Emoji](https://github.com/googlei18n/noto-emoji) has a compiled font file under the SIL open font license. It would be smarter to use a font that contains these emojis and have qtox use the emojis for the section of text that contains emojis. It will make updating the emojis a simpler/easier process.

**Comment by anthonybilinski** [comment]
We've also had multiple bugs to do with text parsing. Making it so we don't need to manually parse multi-byte characters (or multi-character characters https://github.com/qTox/qTox/issues/5147) with regex and replace them with html tags where we're also trying to add html tags. This seems like a good idea to me.

**Comment by sudden6** [comment]
Just a few questions to clarify things:

- The of Noto Color Emoji says that it's not working on MacOS browser, does this also apply when we use the font via Qt?
- Is this a font containing both letters and emoji or just emoji? If it contains only emoji how do we select the font for normal text?
- At the moment qTox supports different sizes for text and emoji, I guess this will not work then anymore? (I don't really care about this working, but want to know about the changes)
- At the moment qTox supports selecting different styles of emoji, are there other fonts that provide the emoji?
- Will this work out of the box with our emoji picker? (I would not be too sad if we have to throw it away, but I expect some work here)

Despite these open questions I'm much in favor of replacing our hacky custom emoji with something more standardized :+1:

**Comment by Vort** [comment]
Use of smileys, which have no corresponding Unicode codes, should also be possible.

**Comment by sudden6** [comment]
@Vort can you give some examples?

**Comment by Vort** [comment]
Here is a good example:
![ts](https://user-images.githubusercontent.com/1242858/54917891-7d78a480-4f05-11e9-9531-125fb1253ba3.png)

**Comment by jessica181920** [comment]
> Use of smileys, which have no corresponding Unicode codes, should also be possible.

> Here is a good example:
> ![ts](https://user-images.githubusercontent.com/1242858/54917891-7d78a480-4f05-11e9-9531-125fb1253ba3.png)

The reason this should be avoided is due to bad cross-client compatibility. The way it has been recommended to solve this is use stickers. For now, the standard requires that emotes be unicode emojis in order to be uniform across clients.

**Comment by jessica181920** [comment]
Also after a lengthy discussion with sudden6 I think we've determined the best way to handle emojis for now, and too many problems could arise from fonts and how they are displayed. Also, in order to populate the emoji menu, you still need to construct an XML table, so this would not be much of an enhancement, if any at all.
