### ISSUE TITLE
I can not upload bzatsya can not speak fraza

### ISSUE THREAD

**Issue by comicaza** [qTox/qTox#5587]
##### Brief DescriptionI can not upload bzatsya can not speak fraza

OS: Windows 8 (6.2)
qTox version: v1.16.3
Commit hash: 8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore: 0.2.3
Qt: 5.9.6
Hardware: 
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. 
2. 
3. …

##### Additional Info
(links, images, etc go here)

----

More information on how to write good bug reports in the wiki: https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by anthonybilinski** [comment]
We need way more information than this to start working on an issue. Please try to fill out as many fields of the issue template as possible, and try to translate the problem to English.

**Comment by jessica181920** [comment]
![bzatsya](https://user-images.githubusercontent.com/48566407/55028715-5357dd00-5000-11e9-9c9a-f34e35f95f89.png)
uploading bzatsya and speaking fraza currently working for me, friend

**Comment by comicaza** [comment]
We change the code to highlight only partially blue, SEND ME AN INVITATION no one managed to, installation again without result, nothing worked try for yourself to write me my nickname: "FRAZA" OR "AMMAT"

26 березня 2019, 20:05:05, від "Anthony Bilinski" <notifications@github.com>:

We need way more information than this to start working on an issue. Please try to fill out as many fields of the issue template as possible, and try to translate the problem to English.

**Comment by comicaza** [comment]
We change the code to highlight only partially blue, SEND ME AN INVITATION no one managed to, installation again without result, nothing worked try for yourself to write me my nickname: "FRAZA" OR "AMMAT"
 
WRITES: THE FAILED TOX ID
26 березня 2019, 20:05:09, від "Anthony Bilinski" <notifications@github.com>:

Closed #5587.

**Comment by comicaza** [comment]
26 березня 2019, 21:50:29, від jessica181920 <notifications@github.com>:


uploading bzatsya and speaking fraza currently working for me, friend

**Comment by anthonybilinski** [comment]
@comicaza if you're trying to add a friend

1. Wait until you become online (~30s)
![image](https://user-images.githubusercontent.com/10469203/55101050-7629d600-5080-11e9-8713-b621acd08679.png)
2. Click avatar picture
![image](https://user-images.githubusercontent.com/10469203/55101102-99ed1c00-5080-11e9-94bc-c10a70fd6e43.png)
3. Copy your Tox ID
![image](https://user-images.githubusercontent.com/10469203/55101174-c0ab5280-5080-11e9-98d6-702516672082.png)
4. Give that to a friend with some existing method of communication.
5. Have friend select "add friend" button
![image](https://user-images.githubusercontent.com/10469203/55101290-ffd9a380-5080-11e9-9496-7a79dc59a6f1.png)
6. Have friend enter your Tox ID and send a friend request.
![image](https://user-images.githubusercontent.com/10469203/55101305-0c5dfc00-5081-11e9-9a24-16ceee6b19ae.png)

If you're having problems could you include logs, screenshots, and steps to reproduce the issue?
