### ISSUE TITLE
Changing theme doesn't update file transfer widgets

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5592]
##### Brief Description

OS: Ubuntu 18.04
qTox version: v1.16.3+
Commit hash: 993f6fa
toxcore: 0.2.9
Qt: 5.9.5
Hardware: Destkop

Reproducible: Always

##### Steps to reproduce

1. Select default theme.
2. Send or receive a file.
3. Change to dark theme.
4. Send or receive a file.

##### Observed Behavior
File transfer widgets keep the theme that they were created with, instead of updating when the theme is changed, resulting in different widgets with different themes in your chatlog:
![image](https://user-images.githubusercontent.com/10469203/55100280-be47f900-507e-11e9-9af2-3e89d43ffb36.png)

##### Expected Behavior
Existing file transfer widgets are updated to the appropriate theme when application theme is changed.

**Comment by TriKriSta** [comment]
Updating theme without restart program does code harder. I think to delete this function after added functions for save groups histories.

**Comment by anthonybilinski** [comment]
Sorry I don't understand, what does theme changes not propagating have to do with group history? Which function are you talking about deleting?

**Comment by TriKriSta** [comment]
I'm talking about the function that updates themes without restart program.
now if the program is restarted that deletes group history, so I added functions for update themes.
when functions for saving groups histories will be added, the function for update themes will no longer be needed
