### ISSUE TITLE
qtox shows a blank window on startup (windows)

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#562]
![qtox](https://cloud.githubusercontent.com/assets/6986141/4825624/1a819fd6-5f67-11e4-8c49-74ba7d635840.png)
On slower PCs qtox is blank for 5 seconds. It looks like it is loading something too long.

**Comment by dubslow** [comment]
Yeah I've noticed this too, been like this less than a month I think, but I'm not sure what causes it.

**Comment by tux3** [comment]
Note: This only happens on the first start for me.

**Comment by dubslow** [comment]
It happens every time I start qTox, a good three seconds of a window outline before it fills in.

Still takes less time than Skype to start up (if you exclude connecting to the DHT) though -- it's just not very pretty.

**Comment by tux3** [comment]
I profiled recently on Linux and 50% of the time spent starting up is toxcore doing crypto, 30% is adding our contacts and creating the chat form/parsing the CSS for each contact.

**Comment by dubslow** [comment]
The point is it should either show a holdover inside the border, or the border itself should also be invisible. (The former is preferable I think, so that at least _something_ happens immediately.)

**Comment by towlie** [comment]
Happens everytime I start qTox too.

**Comment by towlie** [comment]
It seems that it doesn't happen anymore.
