### ISSUE TITLE
No message tone, please solve

### ISSUE THREAD

**Issue by louisliu1985** [qTox/qTox#5621]
##### Brief Description
Original Title: 没有信息提示音，请解决

OS: Windows 10 (10.0)
qTox version: v1.16.3
Commit hash: 8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore: 0.2.3
Qt: 5.9.6
Hardware: 
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. 
2. 
3. …

##### Additional Info
(links, images, etc go here)

----

More information on how to write good bug reports in the wiki: https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by anthonybilinski** [comment]
@louisliu1985 what steps do you take to see this issue? Can you provide logs (settings -> advanced -> copy debug log) from when the issue occurs?
