### ISSUE TITLE
Dark theme friend info pane is difficult to read

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5625]
##### Brief Description

Commit hash:  ec500b667306e913cd37d14b6aa1ef8bddfa4d91

Reproducible: Always

##### Steps to reproduce

1. Right click friend in friend list.
2. Click show details

##### Observed Behavior
Multiple text fields of the friend information are very difficult to read.
![image](https://user-images.githubusercontent.com/10469203/56194575-250a6380-5fe8-11e9-8074-d73d57453d98.png)

##### Expected Behavior
Correctly coloured text/background so that all info is easily legible.

**Comment by sudden6** [comment]
Fixed by  #5627
