### ISSUE TITLE
Dark theme group name highlight is hard to read

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5626]
##### Brief Description

Commit hash:  ec500b667306e913cd37d14b6aa1ef8bddfa4d91

Reproducible: Always

##### Steps to reproduce

1. Enter group.
2. Have someone mention your name.

##### Observed Behavior
Highlight colour makes text within the highlight difficult to read:
![image](https://user-images.githubusercontent.com/10469203/56194940-cb566900-5fe8-11e9-96fa-481fca952e37.png)

##### Expected Behavior
Highlight or text colour changed for dark theme to make it relatively legible.

**Comment by sudden6** [comment]
Should be fixed by #5627

**Comment by anthonybilinski** [comment]
It is, closing.
