### ISSUE TITLE
Dark theme white padding issue

### ISSUE THREAD

**Issue by jessica181920** [qTox/qTox#5629]
So one of the bits of padding/whitespace on the left side of the chat area seems to be left white on the dark theme, as if to be used as some kind of really thick "divider." It's awfully striking and out of place, and also it makes the GUI a bit inconsistent. For example, look how this space functions on the default theme:
![darktheme1](https://user-images.githubusercontent.com/48566407/56383967-b822e380-620a-11e9-9233-bb67e4a73c18.png)

The horizontal divider that separates the chat with the name, status, avatar, etc is evenly padded on both sides with white space. Also, the background of the selected user you're chatting matches the chat background and they are "conjoined" together which looks nice, as the selected user and the chat window all flow together in the same color to make it clear which friend you're chatting. Now look at how the dark theme looks:
![darktheme2](https://user-images.githubusercontent.com/48566407/56384102-12bc3f80-620b-11e9-8387-9f85bef16674.png)

That padding is way too thick to be used as some kind of "divider" and even so, a divider doesn't look good as it doesn't keep the style where the selected user and chat background conjoin/flow together. After several painstaking hours in photoshop, I bring you how the dark theme should look:
![darktheme3](https://user-images.githubusercontent.com/48566407/56384163-49925580-620b-11e9-8153-e187cccd38c7.png)

@TriKriSta

**Comment by sudden6** [comment]
should be closed by #5627

**Comment by anthonybilinski** [comment]
It is, closing.
