### ISSUE TITLE
can't become online

### ISSUE THREAD

**Issue by hueldoeu** [qTox/qTox#5644]
i can install and start qtox easily and it shows up. even webcam works in settings. first time i connected with another pc. the other pc uses lubuntu 16.04 32-bit very old hardware non-sse2 cpu but login works great. however, on windows 10 x64 login and connection successfull also i could hear myself, lubuntu pc is not far away. then i restarted both systems and i can't login on qtox windows 10 anymore. new install didnt help. i am thinking about a firewall problem. why did it work the first time but now anymore? should i register a new profile? new profile didnt help

##### Brief Description

OS: Windows 10 x64 1809
qTox version: v1.16.3
Commit hash:  ?
toxcore:  0.2.3
Qt:  5.9.6
Hardware:  i5-7300HQ nvidia 1050ti acer nitro 5
…

Reproducible: Always

##### Steps to reproduce

1. start laptop and windows 10
2. start qtox
3. can login but won't become online, other pc sees me offline, i see the lubuntu client as offline because 10 is offline, lubuntu client itself gets green => online, both qtox

##### Additional Info
(links, images, etc go here)

----

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA%\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by hueldoeu** [comment]
i solved it, i knew it was a blocked port because it's always a port. i activated upnp under control settings => network => change advanced sharing ...
https://www.computerhope.com/issues/ch001367.htm#windows-10

    Open the Control Panel.
    Click Network and Internet
    Click Network and Sharing Center.
    In the left pane, click the link for Change advanced sharing settings.
    In the Network Discovery section, select the option for Turn on network discovery and click the Save changes button.

**Comment by anthonybilinski** [comment]
@hueldoeu ~Tox uses local network discovery which looks like what was enabled with that Windows settings, but even without local network discovery two two clients should have found each other through the DHT like normal~ oops, it looks like that actually enabled upnp like you said - but still Tox should hole punch your router's NAT even without upnp enabled. Do you know if the problematic Windows profile is able to connect to Tox profiles that aren't on your network?

If you router is old / bad it could help to use TCP mode to reduce the number of connections qTox makes. To try that out you can untick `settings -> advanced -> Enable UDP` in qTox. Note that in this case your communication will be securely related through a volunteer TCP relay.

It would also help to get logs if this happens again, you can get those from `settings -> advanced -> copy/export debug log`.

**Comment by hueldoeu** [comment]
I will test and enable udp tcp relay soon.

I don't know about problematic windows profiles

**Comment by hueldoeu** [comment]
i can't change udp in qtox. it's greyed out and uncheck already.
