### ISSUE TITLE
Split sentence on advancedform.cpp

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#5651]
There is a split sentence on the adcanvedform.cpp file (https://github.com/qTox/qTox/blob/master/src/widget/form/settings/advancedform.cpp)

```
    QString warningBody = tr("Unless you %1 know what you are doing, "
                             "please do %2 change anything here. Changes "
                             "made here may lead to problems with qTox, and even "
                             "to loss of your data, e.g. history.")
                              .arg(QString("<b>%1</b>").arg(tr("really")))
.arg(QString("<b>%1</b>").arg(tr("not")));
```

Many languages do not work like English. For example, to make a proper Turkish sentence, I have to change the word order in this sentence.

If there are two sentences, please use two sentences.

**Comment by Diadlo** [comment]
Just use `%1` and `%2` in different order in your translation string, if it's needed

Example: "Пожалуйста, %2 меняйте тут ничего, пока убедитесь, что вы %1 понимаете, что делаете"

**Comment by ghost** [comment]
Does not it possible to use `<b>` tags directly?

**Comment by Diadlo** [comment]
@libreajans This is not entirely correct, because a translator can remove them

**Comment by ghost** [comment]
Ok, what you wish.
