### ISSUE TITLE
Group peers with empty name are handled inconsistently

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5660]
##### Brief Description

qTox version: v1.16.3+
Commit hash:  6522988e8c2ef408278c0602ac9fd756b235b77b
toxcore:  v0.2.9

Reproducible: Always

##### Steps to reproduce

1. Have a friend in a group, without an alias set.
2. The friend removes their name.

##### Observed Behavior
1. The friend's name is shown as their public key in the friend chat.
2. The friend's name is shown as <Empty> in the group.

##### Steps to reproduce

1. Have a friend in a group, with an alias set and an empty name.
2. Clear the alias.

##### Observed Behavior
1. The friend's name is shown as their public key in the friend chat.
2. The friend's name is shown as their public key in the group chat.

##### Expected Behavior

Consistent behaviour between the two cases. @sudden6 should `<Empty>` be removed completely and peer PK be used in place, like it is for friends? Or should `<Empty>` always be used in place of peer PK in groups?

**Comment by sudden6** [comment]
I'd prefer PK everywhere and never `<Empty>`.
