### ISSUE TITLE
Customize Qtox to make the doorbell using videocall

### ISSUE THREAD

**Issue by HuuThanhHung** [qTox/qTox#5665]
Hello all,
i am newbie and i just find out about qtox just a month.

i want to set up a system base on qtox.
i want to just press BUTTON and it will call to 1TOX ID CONSTANT.

I don't know clearly about the flow so if you have any idea to help me so just comment below!
THANK YOU SO MUCH!!!

**Comment by sudden6** [comment]
Hi,

You can do this with a custom Tox client, e.g. https://github.com/zoff99/ToxDoorspy maybe the owner of this repo can help you set things up.
