### ISSUE TITLE
Call ring no longer loops after audio refactor

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5680]
##### Brief Description

OS: Ubuntu 19.04
qTox version: v1.16.3+
Commit hash:  22362d29400a3bc1684d227e355feb52fd28c9de
toxcore:  v0.2.9
Qt:  5.12.2
Hardware:  Desktop

Reproducible: Always

##### Steps to reproduce

1. Be called.

##### Observed Behavior
1. Call ring is played once.

##### Expected Behavior
1. Call ring is looped until answered or dismissed.

**Comment by sudden6** [comment]
On which side does this happen? The person being called (callee?) or on the person doing the call (caller)

**Comment by anthonybilinski** [comment]
Both sides. It looks like the issue is that `AlSink::startLoop` is called, then immediately after `AlSink::playMono16Sound` is called which cancels the loop in `OpenAL::playMono16Sound` with `alSourcei(sourceId, AL_LOOPING, AL_FALSE);`
