### ISSUE TITLE
Crash when logging back in after logging out while owning a group chat

### ISSUE THREAD

**Issue by Kribylet** [qTox/qTox#5694]
##### Brief Description

OS: Linux Mint 19.1
qTox version: master
Commit hash: 8568a14 
toxcore:  v0.2.9
Qt:  5.9.5
Hardware:  Desktop

Reproducible: Always

##### Steps to reproduce

1. Create new profiles A and B
2. B adds A as friend
3. A requests a groupchat with B through right-click on B in friend list
4. B accepts and joins group chat
5. A enters profile page by clicking own display picture, selects logout
6. A logs back in, crashes if/when B is found online

##### Observed Behavior
Crashing upon logging in if detecting participant of previous group chat online

##### Additional Info

[backtrace.txt](https://github.com/qTox/qTox/files/3272102/backtrace.txt)

**Comment by Kribylet** [comment]
Probably related to https://github.com/qTox/qTox/issues/5542

**Comment by anthonybilinski** [comment]
To expand a bit for posterity, #5542 causes groups to not be loaded when they have no name, so the group is never added to our GroupList. But the group still exists in toxcore, so we get callbacks for it, which the assert catches. The assert here is a good check that caught an issue - the core problem is that we 1) save groups with no length and 2) don't handle 0-length names that are saved, as discussed in #5542.

**Comment by anthonybilinski** [comment]
Fixed by https://github.com/qTox/qTox/pull/5695.
