### ISSUE TITLE
Segfault when trying to open a group chat in new window

### ISSUE THREAD

**Issue by Kribylet** [qTox/qTox#5697]
##### Brief Description

OS: Linux Mint 19.1
qTox version:  1.16.3
Commit hash:   8568a14
toxcore:  v0.2.9
Qt:  5.9.5
Hardware:  Desktop

Reproducible: Always

##### Steps to reproduce

1. Join a group chat
2. Try to open the group chat in a new window

##### Observed Behavior
Segfault crash

##### Expected Behavior
Group chat opens in a new window

##### Additional Info
[backtrace.txt](https://github.com/qTox/qTox/files/3283262/backtrace.txt)

https://github.com/qTox/qTox/pull/5693 proposed to fix similar issues elsewhere does NOT resolve this issue

**Comment by Kribylet** [comment]
I've been trying to narrow this down; I've found an alternate sequence that will cause a very similar segfault (d->size in QByteArray):

1. Right click a friend and open chat in a separate window
2. Click the "Create a group chat" graphical button (but do nothing else)
3. Right click the friend you opened a chat in a separate window with in the group chat name list
Segfault occurs.

**Comment by Kribylet** [comment]
Commenting out contentdialogmanager.cpp:64->67 allows the separate window group chat to render without a segfault, but trying to send messages will still segfault.

`GroupWidget* ContentDialogManager::addGroupToDialog(...)`
`{`
`...`
`ContentDialog* lastDialog = getGroupDialog(groupId);`
    `if (lastDialog) {`
     `     lastDialog->removeGroup(groupId);`
    `}`
`...`
`}`

I believe some resources are being shared that wasn't accounted for

**Comment by TriKriSta** [comment]
@Kribylet maybe need delete it, for fix this problem
`    // FIXME: emit should be removed`
`    emit widget->chatroomWidgetClicked(widget);`

**Comment by sudden6** [comment]
@Kribylet does this crash still happen or did #5730 fix it?

**Comment by anthonybilinski** [comment]
I can't repro this, though I am on a newer Qt version at 5.12.4. I think it's very likely #5730 fixed this issue as well, since opening the chat in a new window is very similar to just opening the chat like https://github.com/qTox/qTox/issues/5570 which is what was fixed. We also had a lot of reports when that issue was active, and we haven't heard anything about this one in months. I'll close, but please comment if it's still present.

**Comment by anthonybilinski** [comment]
Hmm actually the bug and workaround only effect Qt versions between 5.11.0 and 5.12.4, whereas this was reported with version 5.9.5. @Kribylet can you still repro this issue?

**Comment by Kribylet** [comment]
Confirmed just now that the steps in the initial issue will cause a segfault crash on Qt 5.9.5.

The steps in the second post will also still cause a segfault crash on Qt 5.9.5.

**Comment by sudden6** [comment]
@Kribylet is this still present with 1.17.2?

**Comment by Kribylet** [comment]
Does not reproduce in 1.17.2 when using Qt 5.9.5!

**Comment by sudden6** [comment]
Great!
