### ISSUE TITLE
qtox crash

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#570]
https://gist.github.com/towlie/3b007d1e61416430fded

**Comment by tux3** [comment]
> #8  0x004261c5 in Core::process (this=0x0) at src/core.cpp:318
> 
> <hr/>
> 
> toweI> tux3: I a aborted a file transfer and send and received the letter "p"

**Comment by towlie** [comment]
Another crash:
https://gist.github.com/towlie/006607192fc188294993
This time I did nothing.

**Comment by dubslow** [comment]
> #8 0x004261c5 in Core::process (this=0x0) at src/core.cpp:318

It's like Windows doesn't understand how to read code...

**Comment by tux3** [comment]
And I can reproduce but I have no idea what could possibly be causing that.
My crash happenned just while starting, before I could do anything

<blockquote><pre>Début du débogage
built on:  19:15:04 Nov  2 2014
commit:  built without git 
Settings: Loading from  "C:/Users/Tux/AppData/Roaming/tox/settings.ini"
Using embeded bootstrap nodes list
Loaded translation "fr"
Core: loading Tox from "C:/Users/Tux/AppData/Roaming/tox/D517DE997AFD.tox"
Core starting with IPv6 enabled
Core::loadConfiguration: reading from  "C:/Users/Tux/AppData/Roaming/tox/D517DE997AFD.tox"
VideoSurface: Init
Core: Connected to DHT
VideoSurface: Init
VideoSurface: Init
VideoSurface: Init
VideoSurface: Init
Settings: Saving in  "C:/Users/Tux/AppData/Roaming/tox/settings.ini"
Core: writing tox_save to  "C:/Users/Tux/AppData/Roaming/tox/D517DE997AFD.tox"
</pre></blockquote>

Full backtrace: https://gist.github.com/tux3/17bf3d4177f07e568e66

Perhaps my pthreadGC2.dll is wrong, or maybe that's a bug in toxcore.

**Comment by tux3** [comment]
Now I'm _almost_ sure that this is a bug in toxcore.

In <b>net_crypto.c:wipe_crypto_connection:1347</b> we're calling pthread_mutex_destroy on a nullptr.

![2014-11-02 22_13_42-](https://cloud.githubusercontent.com/assets/5155966/4876875/681ca738-62d5-11e4-8a7d-def818886f79.jpg)

**Comment by towlie** [comment]
Good to see that there is progress. So you found something in toxcore?

**Comment by tux3** [comment]
I think so, but I haven't had the time confirm it or to work on a fix yet.

I'm surprised that it only happens on Windows.

**Comment by towlie** [comment]
It didn't crash anymore but I am using the 64 bit version now. Maybe it happenes because of a bug in libwinpthread on 32 bit versions?

**Comment by tux3** [comment]
Maybe, I'll close it for now since it looks fixed (and seems to be a toxcore bug). If someone still has the same issue, please leave a comment.
