### ISSUE TITLE
qTox nightly flatpak crashes when switching to group view

### ISSUE THREAD

**Issue by toxlover** [qTox/qTox#5708]
##### Brief Description

OS: Linux Ubuntu 18 LTS  
qTox version: Latest nightly from https://github.com/qTox/qTox-nightly-releases  
Commit hash:  a2020e9e3ddb51aec2707104b2f1a4197408df92
toxcore:  Not sure
Qt:  Not sure
Hardware:  Newish Lenovo laptop
…

Reproducible: Always

##### Steps to reproduce

1. Be joined to a group chat that you were invited to (persistent)
2. Quit qTox
3. Launch qTox and wait for it to fully connect / populate
4. Click on a regular 1:1 chat
5. Click on a group chat

##### Observed Behavior

qTox seems to segfault at step 5 above. Probably related to #5570 and I so assume could be fixed by simply updating that libraries that the flatpak brings in with it e.g. QT?

##### Expected Behavior

Should not crash. :)

**Comment by anthonybilinski** [comment]
Indeed our flatpak uses the KDE runtime version 5.11, which I think includes Qt 5.11 which is effect by the bug. I'm not sure if 5.12.4 is available in flatpak, if not we should downgrade to 5.9.8, or workaround #5570 in qTox's code so we can go back to working well on any modern Qt version.

**Comment by anthonybilinski** [comment]
Our flatpak uses Qt 5.15 now which shouldn't have the bug, also we did manage to workaround https://github.com/qTox/qTox/issues/5570 in qTox so even with Qt 5.11 it should be fixed. Closing.
