### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#571]
Reported by @zetok 

https://gist.github.com/zetok/c39b3b39e51fa40cd74b

**Comment by dubslow** [comment]
I saw this once, but wasn't able to reproduce...

**Comment by tux3** [comment]
Looking at that backtrace again, that's very likely a Qt bug, or an unrelated issue that happens to crash Qt internally. Closing, since it doesn't seem to be a common problem and probably not even in qTox.
