### ISSUE TITLE
history doesn't load

### ISSUE THREAD

**Issue by TriKriSta** [qTox/qTox#5714]
##### Brief Description

OS: Arch Linux
qTox version: v1.16.3-476-g033f28e6
Commit hash: 033f28e67ecd61cd0fdb6cc0e8de8a2bc920e1d7
toxcore: 0.2.9
Qt: 5.12.4

Reproducible: Always

##### Steps to reproduce

1. start the program
2. go to friend chat and see empty chat without history

**Comment by hart0** [comment]
~~I think I am experiencing this or something similar as well in this version, if I scroll up I can only see history going back 5-10 days, and scrolling up further does nothing. However, doing ctrl+f to find some random existing string of text in the history works to force load chat farther back for me, I got it to show 4 months worth this way.~~ Looks like what I was talking about is normal behavior

**Comment by TriKriSta** [comment]
If I understand correctly, then you describe the normal behavior for the program.
this #5672 allows you to load history when scrolling

**Comment by Diadlo** [comment]
@sphaerophoria Can it be the result of your refactoring?

**Comment by sphaerophoria** [comment]
@Diadlo it could be, but I don't have a good explanation for why I would see different behavior on my machine vs anyone elses. I don't think I introduced any new races between the chat widgets and history. I'll take a stab at reproing later today. @TriKriSta is this only reproducible after 22a4c38bfd9bf4eda43bc7a871d95661dfc04a0c? Do you see any interesting log messages on the failure?

**Comment by TriKriSta** [comment]
@sphaerophoria before 22a4c38 history loads good
this code `QDateTime::fromMSecsSinceEpoch(std::numeric_limits<int64_t>::max()));` generated this date (вс мая 16 19:47:04 -292275056) for me, so I changed it on `QDateTime::currentDateTime()`

**Comment by sphaerophoria** [comment]
woah i wonder why thats different from mine. I intentionally didnt use
currentdatetime because i want history to be loaded if I change my
timezone. Ill see if theres a better option tonight.

**Comment by 0xf00f** [comment]
I am seeing the same issue in a today's source build.

On opening the chat, previous messages are not loaded. New messages show correctly, until you restart qTox. Old messages are not show even when I choose to "Load chat history" from today's date.

The chat history is saved correctly, since it is loaded and show automatically in version v1.16.3-459-g0a95f9fc.

**Comment by 0xf00f** [comment]
With the latest change I get a crash with a Segmentation fault when entering any chat. 

Nothing in the debug log.
