### ISSUE TITLE
Move travis nightlies to toxcore 0.2.9

### ISSUE THREAD

**Issue by jessica181920** [qTox/qTox#5718]
@sudden6 
travis nightlies use toxcore 0.2.8. I decided to try one of the "official" travis nightlies, and all that happened is my persistent groups were removed because of the old version of toxcore.

![screen3](https://user-images.githubusercontent.com/48566407/60000229-4d9b8300-9653-11e9-9e5c-333d1fecbe11.png)

I'm still using the Jenkins builds right now for nightlies. Also, while you update toxcore to the latest version, I'll go ahead and ask both you and @nurupo to update Qt to 5.9.8.

Thanks!

**Comment by nurupo** [comment]
I will try making a PR updating qTox Windows deps later today, if I don't forget about it and if I get it to build without issues locally.

**Comment by nurupo** [comment]
I was thinking about updating Qt to 5.12.4 actually, instead of 5.9.8, [assuming we can](https://bugreports.qt.io/browse/QTBUG-70487) get [it to build](https://bugreports.qt.io/browse/QTBUG-70490). We need to wait for Debian Buster release for that though, as I think Qt 5.12 requires a more recent version of a C++ compiler than what Stretch has, if my memory is correct. The current docker image is Stretch-based.

**Comment by nurupo** [comment]
As for updating Qt on Jenkins, I will probably leave it as it is now. Not much point in updating it if we are moving nightlies to GitHub Releases / Travis anyway.

**Comment by jessica181920** [comment]
> I was thinking about updating Qt to 5.12.4 actually, instead of 5.9.8, [assuming we can](https://bugreports.qt.io/browse/QTBUG-70487) get [it to build](https://bugreports.qt.io/browse/QTBUG-70490).

Last time I discussed this with @sudden6 in March, he couldn't get it to build, hence my current suggestion to continue using 5.9. If we can get it to build, obviously it'd be important to make sure to avoid 5.12.3 because apparently it introduces a lot of segfaults (not at the fault of qTox)

**Comment by jessica181920** [comment]
I've never tested 5.12.4 so I can't speak to its stability but Anthony seems to believe it's perfectly stable if we can get it to build
