### ISSUE TITLE
qTox doesn't allow transferred images to be clicked

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#573]
When sending or receiving any normal file, you can click on the green transfer thing to open it in the default viewer. However, this somehow does not work for pictures, which simply don't open.

**Comment by minj** [comment]
Actually the 'click on the green transfer thing' does not work for me with any file on manjaro/openbox (94db81d).

It works from the 'Transferred Files' tab though.

Apparently there is no issue on Win7.

**Comment by tux3** [comment]
Is this still a problem?

I can't reproduce, and if it's still a bug with the lastest Qt I'm not sure what other solution we have to find the environment's default image viewer.

**Comment by zetok** [comment]
I couldn't reproduce under i3wm on Hardened Gentoo. `.png` image was successfully opened by `gwenview`

Steps:
1. Dragged and dropped image into `qTox S`
2. Accepted file transfer in `qTox R`
3. Clicked on `✔` in both clients, both opened file successfully.

@TheLastProject mind trying again, and if it still doesn't work, providing more info (qTox log) / steps to reproduce?

**Comment by TheLastProject** [comment]
This has been working for me since ages now, can't even recall when it was fixed. I'll close this.
