### ISSUE TITLE
Crash when receiving message in separate friend chat window

### ISSUE THREAD

**Issue by Kribylet** [qTox/qTox#5732]
##### Brief Description

OS: Linux Mint 19.1
qTox version: v1.16.3-479-gc524e52d.
Commit hash:  gc524e52d
toxcore:  v.0.2.9
Qt:  5.9.5
Hardware:  Desktop

Reproducible: Always

##### Steps to reproduce

1. Open separate chat window for a friend
2. Receive a message from that friend

##### Observed Behavior
Typing prompts appears/disappears normally, actually receiving a message crashes.

##### Expected Behavior
Receiving the message in the separate chat window normally.

##### Additional information: 
[backtrace.txt](https://github.com/qTox/qTox/files/3342666/backtrace.txt)

**Comment by sudden6** [comment]
Can you attach a backtrace? I'm attaching this to the v1.17.0 release, because this crash severely impacts the usability of qTox.

**Comment by sudden6** [comment]
@Kribylet is this fixed by 59a59fdc09ee5cbf32c915b94cb8ba8e8f0a29b1?

**Comment by Kribylet** [comment]
@sudden6 Yes, this issue can be closed.
