### ISSUE TITLE
Loaded faux offline messages are sometimes not delivered since refactor

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5734]
##### Brief Description
qTox version: v1.16.3+
Commit hash:  e7e6bff318a995cf4fe80b7660a67a4148053046
toxcore:  v0.2.10
Qt:  5.12.2
Hardware:  Desktop

Reproducible: Always

##### Steps to reproduce

1. Create a new profile
2. Add another profile, don't accept the friend invite
3. Send an offline message
4. Restart qTox

##### Observed Behavior
1. Before restarting, the message is pending. Spinner is spinning, message is in both `history` table and `faux_offline_pending`.
2. After restarting, the message is not pending. There is no spinner, only  a timestamp. The message is not delivered to the friend once we see them come online. The message is still correctly present in the `faux_offline_pending` table.

##### Expected Behavior
1. Faux offline messages are displayer as pending in chat, and sent when we see the friend come online

##### Additional Info
This bug has been hit during normal use, but I couldn't repro reliably until this case. Bug was only seen after @sphaerophoria's chat refactor.

In ChatHistory. I see this in gdb, which looks like an issue:
```
Thread 1 "qtox" hit Breakpoint 2, ChatHistory::loadHistoryIntoSessionChatLog (this=0x5555560f7da0, start=...) at /home/abilinski/builds/qTox/src/model/chathistory.cpp:365                                 
365                 if (isComplete) {                                                                                    
(gdb) p message.isSent                                                                                                             
$15 = false                                                                                                              
(gdb) p isComplete                                                                                                                                                                                         
$16 = true                                                                                                                                                                                                 
```

**Comment by jessica181920** [comment]
I've been trying to hit bugs today, and this bug is actually way easier to hit.

1. Send an offline message
2. Restart qtox

It will be marked as sent with a timestamp and not pending. I don't think this information is that useful anymore since the cause of the bug seems to be known and there's a PR being worked on.

**Comment by anthonybilinski** [comment]
This was fixed by https://github.com/qTox/qTox/pull/5773. Oops, forgot the issue number in the commit.
