### ISSUE TITLE
How many friends to support group chat at most？

### ISSUE THREAD

**Issue by zhuzhenlongn** [qTox/qTox#5737]
When I create a group，I can invite some friends into my group， but I don't know the most count of friends I can Invite. Can you tell me how many friends Tox can support?

**Comment by sudden6** [comment]
There is no hard upper limit that I know of, bandwidth might be an issue for very large groups.

**Comment by anthonybilinski** [comment]
Toktok/c-toxcore would have more insight into the protocol side, and https://github.com/TokTok/c-toxcore/issues/1327 has a more complete answer. I'll close this, and follow-up questions can be asked there.
