### ISSUE TITLE
Please upload continuous builds to GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [qTox/qTox#5754]
Please upload continuous builds to GitHub Releases, as the last release is several months old and I would like to test the latest commits.

This tool simplifies it:
https://github.com/probonopd/uploadtool

Thanks for your consideration.

**Comment by Chiitoo** [comment]
While perhaps not exactly the same, there are nightlies: https://github.com/qTox/qTox-nightly-releases/releases

**Comment by probonopd** [comment]
Ah cool, exactly what I was looking for @Chiitoo - only that I'd have expected to find them conveniently at https://github.com/qTox/qTox/releases rather than in a separate repository. Thanks :+1
