### ISSUE TITLE
Problem scrolling up through chat log (scroll bar stuck to bottom)

### ISSUE THREAD

**Issue by hart0** [qTox/qTox#5755]
##### Brief Description
When the chat view is scrolled down all the way to the most recent message (so it’s not possible to scroll down any more), attempting to scroll up in the history with touchpad/scroll wheel doesn't do anything.
 
qTox version: You are using qTox version v1.16.3-570-g174d6ef8
Commit hash: https://github.com/qTox/qTox/commit/174d6ef8ca07f892c4ad329107f03978645bf1ab
toxcore: v0.2.10
Qt: 5.12.4
Hardware: Laptop
 
Reproducible: Always
 
##### Steps to reproduce
- View someone's chat, and be all the way scrolled down (default view, showing newest messages)
- Try to scroll up with touchpad/scroll wheel to view older messages
 
##### Observed Behavior
It doesn't scroll up, it stays at the very bottom. The cursor sometimes appears to quickly change between the pointer and text-cursor as if it's trying to do something but it never scrolls up. However, manually dragging the scrollbar will cause it to scroll up like normal, and touchpad scrolling DOES work if the original position before scrolling isn't at the bottom. The only time scrolling with touchpad doesn't work is when the chat is scrolled all the way down.

Trying to scroll up VERY quickly and with a lot of pressure seems to work as expected, I get this issue when scrolling up at normal or slow speed.

Here’s a video (Scrolling up after clicking on chat area, nothing happens)

https://gfycat.com/acrobaticprestigiousislandcanary
 
##### Expected Behavior
Scrolling to work from any position.
 
I think it's related to these changes - https://github.com/qTox/qTox/commit/be55759555eecc60adf84fd3eb5ae6d993c5edbe -, I can scroll normally if I compile an earlier version

**Comment by sudden6** [comment]
ping @TriKriSta because you are the author of the mentioned PR

I have to add, I noticed a bug with scrolling too. Sometimes when I send a message in a group automatic scrolling doesn't scroll enough and I can not read about half of the last line.

**Comment by TriKriSta** [comment]
@hart0 Does this bug repeats if use mouse?

@sudden6 bug (about half of the last line) maybe fixed there (#5693)

**Comment by hart0** [comment]
>Does this bug repeats of use mouse?

Yes, but I noticed something while testing with mouse+scroll wheel. If I use a mouse scroll wheel and slowly scroll up it has the same effect and doesn’t move, however if I scroll up really fast it seems to override the stickyness and it does scroll up. 

I tried with the touchpad again and if I scroll up very fast with a lot of pressure it works as well, but normal speeds (like what’s required to scroll up a webpage) aren’t fast enough.

**Comment by sudden6** [comment]
I now hit exactly this bug (stuck on bottom of chat) and sending a message fixed it.

**Comment by sudden6** [comment]
@TriKriSta will try #5693

**Comment by anthonybilinski** [comment]
Fixed by #5777.
