### ISSUE TITLE
compact mode

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#576]
Would anyone find it useful to have a compact mode (view)?

Currently we have a few friends on lists, but it will became problematic to find friends when the list is several screens long (+50 friends?). I thought about creating a compact mode that would look similar to Gajim. 

`|<status icon> name               <avatar>|`
status message as tooltip.

![gajim compact mode](http://fc03.deviantart.net/fs71/i/2010/272/7/9/valium_icons_for_gajim_by_kalushary-d2zpp8x.png)

**Comment by dubslow** [comment]
This would probably go well with the separate chat windows thing

**Comment by zetok** [comment]
Changing current view `| <avatar> name <status icon> |` IMHO isn't a good idea.

Shouldn't just displaying smaller avatar do the job?

Also, from Gajim screenshot it looks like status message also is displayed: http://gajim.org/imgs/gajim_roster.png

Edit: by "Changing current view" I meant that new optional view shouldn't change order in which things are placed

**Comment by agilob** [comment]
@dubslow: yes.

@zetok depending on configuration, it shows status message or doesn't. 
![gajim-bug](https://cloud.githubusercontent.com/assets/2544251/4835052/675fd60a-5fb3-11e4-9fdc-6798eecd4519.png)
I would like to make avatar smaller and remove status message, but it's a discussion.

**Comment by ProMcTagonist** [comment]
I think the status message should appear in a tooltip instantly on hover regardless of mode, since they're usually truncated normally, and I would definitely use this compact mode. Should @itsDuke be consulted?

**Comment by zetok** [comment]
Tooltips appearing instantly would be really annoying IMHO. Their current speed of appearing is good.

**Comment by ItsDuke** [comment]
> Tooltips appearing instantly would be really annoying IMHO. Their current speed of appearing is good.

This is perfect.

**Comment by ProMcTagonist** [comment]
Compact mode is merged.
