### ISSUE TITLE
Messages are sometimes marked as pending in chatform, even when delivered in db

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5763]
##### Brief Description

OS: Ubuntu 19.04
qTox version: v1.16.3+
Commit hash:  040c6b95aed26dfc7950770ed4dca379e8be2bc5
toxcore:  v0.2.10
Qt:  v5.12.2
Hardware:  Desktop, loopback network between Alice and Bob

Reproducible: Always

##### Steps to reproduce
1. Alice turbospams Bob.
2. Alice closes qTox and opens her database with sqlite3, selecting all from `faux_offline_pending` table.

##### Observed Behavior
1) Alice sees all but her last message as pending.
2) Bob receives all messages as they're sent.
3) When manually inspecting her db, Alice does not see her turbospam in the `faux_offline_pending` table.

Credit to @jessica181920 for initially finding the bug, and finding this simplified repro case.

**Comment by jessica181920** [comment]
> Credit to @jessica181920 for initially finding the bug, and finding this simplified repro case.

You really don't have to do that lol

**Comment by sudden6** [comment]
Could this be fixed with #5735?

**Comment by anthonybilinski** [comment]
No, it's still reproducible running #5735.

**Comment by anthonybilinski** [comment]
https://github.com/qTox/qTox/blob/master/src/widget/form/genericchatform.cpp#L1032 returns early based on that big if statement. In the case of quickly sent messages, we get:

message A sent
message B sent
message A complete, stop spinner - but nope, not the last message, return early
message B complete, stop spinner - last message, ok.

I don't understand why we skip out on rendering when render is called on a message or range of messages that aren't either the first message, a new message, or up to the first message. With completion we could be updating any message any number of positions back in the chatform, so it seems like all three restrictions need to be removed.

Also if this was an expected precondition of renderMessages - why not assert instead of silently returning?

I'll open a PR with them removed and ask @sphaerophoria to take a look to make sure it's a mistake and that I'm not missing some greater purpose of the check.
