### ISSUE TITLE
Have user editable bootstrap nodelist

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5767]
When the bootstrap nodes list was stored in the .ini file, it was easily visible and editable by users. Now that it's stored in the json file as provided by nodes.tox.chat, it's still in an easy to edit json format, but is packaged inside the binary, making it near impossible for users to manually edit.

It would be good for the bootstrap list to stay as an external editable config file, so that users can easily create custom private DHTs, view the list, and quickly adds nodes in case of outages / blocks without having to wait for a release.

**Comment by bygiro** [comment]
I'm wondering why this feature (a must have), is not implemented yet, is there any particular reason behind?

**Comment by anthonybilinski** [comment]
No specific reason, but I agree it is important. I'll focus on it as my next issue.

**Comment by Nurmagoz** [comment]
Is this implementation going to resolve: 

https://github.com/TokTok/c-toxcore/issues/475

or unrelated?

**Comment by anthonybilinski** [comment]
Unrelated. This will only allow qTox users to choose which bootstrap nodes and TCP relays they want to use by default, but won't allow for any non-relayed Tor usage or communication over anonymity networks like TokTok/c-toxcore#475 is asking for, AFAIK those would require additional protocol support.
