### ISSUE TITLE
File transfer UI gets frozen after chatlog is modified

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5768]
##### Brief Description

OS: Ubuntu 19.04
qTox version: v1.16.3+
Commit hash:  040c6b95aed26dfc7950770ed4dca379e8be2bc5
toxcore:  v0.2.10
Qt:  v5.12.2
Hardware:  Desktop

Reproducible: Always

##### Steps to reproduce

1. Alice sends a file C to Bob.
2. Bob accepts the file.
3. While the file is still transferring, Alice sends file D to Bob.
4. Bob accepts the file.

##### Observed Behavior
While the second file is transferring, both Alice and Bob observe file C stop updating - speed is frozen, time estimate is frozen, pause and cancel don't work on either end. File C stays frozen after file D is complete.

##### Expected Behavior
Both files transfer at the same time.

##### Additional Info
@Monsterovich found that this works correctly in b445031912ae943d7580ea21f6813e9f71bc03ee. Credit to him for finding the bug.

**Comment by Kribylet** [comment]
Another file transfer is not necessary, any new message ID being added will freeze the transfer UI component 
In that case, the file transfer itself occurs in the background normally
If there are two transfers and one finishes, an inordinate amount of onFileUpdated signals are emitted causing 20+ renderItem calls per ns from then on, and this seems to freeze the actual download progress as well. I speculate it either emits enough render calls to freeze the download, or that the onFileUpdated are overwriting file progress.

**Comment by anthonybilinski** [comment]
I can't reproduce this issue testing on current v1.17-dev tip 8f44fb63552056c9752474251e16630608c789a7.

I don't see anything obvious between when this was reported on 040c6b95aed26dfc7950770ed4dca379e8be2bc5 and now that would have fixed it, which is concerning.

Has anyone seen this bug recently? I wonder if some timing has just changed and we happen to be narrowly avoiding the same bug.

**Comment by anthonybilinski** [comment]
I'm going to close this as cannot reproduce since I haven't observed it in months with 100s of file transfers during chat, and we haven't had any additional comments. If the issue is seen again please comment or file a new issue and there will be more investigation.
