### ISSUE TITLE
Download problems with latest version

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#5770]
edit from anthonybilinski: I'm going to paste the whole issue back in here from my email notification after it was edited out, since it was a valid report with no identifying info. Sorry Mr. Ghost.
original post:

Brief Description

OS: Windows / OS X / Linux (include version and/or distro) : Ubuntu 19.04, KDE desktop
qTox version: (version numbers in menu Settings → About): v1.16.3-579-g040c6b95.
Commit hash: 040c6b9
toxcore: 0.2.10
Qt: 5.12.2
Hardware: I think this is too generic .... intel i7, nvidia 1500
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce
Always
Steps to reproduce

    Open qTox
    Configure it to automatically download to a folder
    Ask a contact to send a file with a filename that already exist in your folder
    The download will not start automatically. It will tell you "Accept to receive this file" and gets stalled at 0%
    Click on the check in the download box. qTox will ask you for a new filename. Give it a new unique file name and press OK. Nothing happens, the download is still stalled
    Click on the "X" in the download dialog box. nothing happens, the download is still stalled at 0% and "Accept to receive this file" is displayed

Observed Behavior

Nothing happens. The download is stalled
Expected Behavior

The download should start / interrupt

**Comment by ghost** [comment]
aaaaa

**Comment by hart0** [comment]
I am getting the same bug 2 on nightly, where about half of the time when a friend sends me a file and I accept, it gets downloaded but the UI never updates or changes that box which asks whether or not to accept the download.

**Comment by sudden6** [comment]
I can confirm that at least BUG1 also sporadically happens to me, setting high priority because of the number of users affected.

**Comment by anthonybilinski** [comment]
reposting the ghost's first comment, from email notification:

I am also experiencing problems with the GUI. When I start qTox, the first time I click on a contact the message windows is like "detached" and in another window. After I close the new windows and click on a new contact, this time the message window is correctly embedded in the first window

**Comment by anthonybilinski** [comment]
I saw bug1 months ago, but haven't seen it more recently. Is anyone still seeing the issue of file transfer UI getting stuck?

**Comment by anthonybilinski** [comment]
Going to close the issue since I can't reproduce it and I haven't seen it after many file transfers over months. If people still see it with a nightly, please comment or open a new issue.
