### ISSUE TITLE
I forgot qtox password

### ISSUE THREAD

**Issue by tyggdd** [qTox/qTox#5774]
I forgot my password and the archive .txt where password was written hasnt it written yet, someone know what could ido?? Or how can i recovery the old .txt archive where is my password written, an app or something??

qtox-windows 10

**Comment by anthonybilinski** [comment]
> the archive .txt where password was written hasnt it written yet

what exactly do you mean by this? was the file saved then deleted? or was it never saved at all?
* I would check whatever editor you were using to write the .txt, maybe it keeps copies of recently opened files or something
* If the file was saved then deleted, check recylcing bin to see if the file is there.

> Or how can i recovery the old .txt archive where is my password written, an app or something

There's definitely nothing we can do on the qTox side except recommend that you create a new profile and re-add your friends, unfortunately :(

Also I know this probably isn't what you want to hear right now, but keeping passwords in a .txt file is quite insecure. An encrypted password manager would be more secure, or probably even pen + paper would be safer.

**Comment by tyggdd** [comment]
> > the archive .txt where password was written hasnt it written yet
> 
> what exactly do you mean by this? was the file saved then deleted? or was it never saved at all?
> 
> * I would check whatever editor you were using to write the .txt, maybe it keeps copies of recently opened files or something
> * If the file was saved then deleted, check recylcing bin to see if the file is there.
> 
> > Or how can i recovery the old .txt archive where is my password written, an app or something
> 
> There's definitely nothing we can do on the qTox side except recommend that you create a new profile and re-add your friends, unfortunately :(
> 
> Also I know this probably isn't what you want to hear right now, but keeping passwords in a .txt file is quite insecure. An encrypted password manager would be more secure, or probably even pen + paper would be safer.

the file was other version where my password wasnt written and that version, i didnt know and i saved that version, deleting the right version of file.
i dont have the id of my friends to add them :(

**Comment by anthonybilinski** [comment]
The Tox IDs of friends are also encrypted by the password, so those aren't recoverable either. I'm sorry, but I don't think there's anyway that we can help :(
