### ISSUE TITLE
How to handle previously unsent messages after fix

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5776]
There is some strange behaviour as a result of recent message loading improvements, currently held back by https://github.com/qTox/qTox/pull/5773.

Setup: For a few years, qTox has loaded the latest 2 weeks of chat per friend, and sent only pending messages that were loaded. This meant if you wrote some messages to an offline friend, closed qTox, came back 3 weeks later, and chatted with that friend, those original messages would never be delivered.

Problem scenario:
1. Alice has been using qTox on only stable releases for a few years chatting with many different friends. Sometimes there were gaps in conversations with friends of more than 2 weeks, and more recently she sent over 100 pending messages in a row  - exceeding the more recent 100 messages loaded on start. Alices faux_offline_pending table has an assortment of old messages, spanning random points in the last few years for multiple friends.
2. Alice updates to qTox 1.17.0 with fixed message loading - which now sends all pending messages without an arbitrary 2 week or 100 message limit. She sees nothing different.
3. Alice's friends, Bob, Charlie, and some other alphabetical names all message her "wtf??". She has no idea what's going on.
4. After some back and forth, she finds out her friends each got different sets of random contextless messages, but she doesn't see them in her chatlog.
5. All the Alices open issues on qTox.

Proposed solution:
* Add a db "schema" version bump. On upgrade, remove all messages from faux_offline_pending that are more than 100 messages back in a chatlog.

Effect: all messages that were previously stuck as pending will not be sent on upgrade. They will remain unsent forever. Any new message added to history after this point will send whenever it can, with no 2 week or 100 message limit of any kind. Only existing messages are effected.

* Add a new message state to represent undelivered but not pending messages.

Effect: messages that have been removed from faux_offline_pending by the upgrade will not be shown with a "delivered" timestamp in the chatlog. It will be clear that those messages weren't sent when looking back.

Downsides of this solution:
* messages that would be sent correctly and in order could be left un-sent, in the case of someone having the last 300 messages of their chatlog all be pending, then upgrade to 1.17.0. (We would only send the latest 100 instead of the last 300).
    * this is a small side-effect IMO since it is effectively existing behaviour for one more qTox start.
* coding work, extra table in db forever
    * IMO worth the improved user upgrade experience. permanent db table is cheap (tiny storage, isolated from rest of codebase).

Thoughts on the default case compared to my proposed upgrade, or thoughts on any alternative solutions?

**Comment by sudden6** [comment]
Personally I like your solution 1 better, since the conditions to trigger the problem seem pretty specific (100 unsent messages in a row) and I think this will keep the qTox code cleaner in the long term.

How did you even find out this issue exists?

**Comment by Diadlo** [comment]
Can we remove not 100 unsent message, but all unsent but last two week?

**Comment by sudden6** [comment]
@Diadlo I don't really understand what you mean, can you explain it in more detail or with different words?

**Comment by anthonybilinski** [comment]
> since the conditions to trigger the problem seem pretty specific (100 unsent messages in a row)

I think the older (pre April 2018) condition we had of latest 2 weeks of history being loaded was easier to accidentally hit. Any chat that went dead for a couple weeks after some pending offline messages would trigger this condition.

> How did you even find out this issue exists?

I hit it personally on both one of my test profiles and my main profile.

> Can we remove not 100 unsent message, but all unsent but last two week?

> I don't really understand what you mean

Because we can have 1) message stuck because they were more than 2 weeks old, or 2) messages stuck because they were more than 100 back - I suggested putting 2)'s messages into this state, but Diadlo is suggesting we put 1)'s messages into this state instead. I think in either case there's some downside - I picked 2) just because it was the newer case, but I do think 1) was the easier to hit case. I'm fine having the deciding factor be 2 weeks instead of 100 messages.

**Comment by sudden6** [comment]
After some thinking your solution 2 seems to be also acceptable for me. I think in general it would make sense to also keep track of failed messages that were never sent, including an appropriate icon in the UI.

For discussion I also have a counter proposal:

For each user determine the time of the last successfully delivered message and re-send all pending messages that are newer than this time.

I think this wouldn't cause too much upgrade code and would avoid the need to introduce a new table to the db. From the user perspective I think it would make sense, because if there are newer successful messages, the loss of the previous ones has probably been detected or didn't matter for the conversation.

**Comment by anthonybilinski** [comment]
> For each user determine the time of the last successfully delivered message and re-send all pending messages that are newer than this time.

I think this makes more sense than the other two options (last 100 or last 2 weeks), interrupts conversation the least, and covers either case that caused them to be stuck.

> I think this wouldn't cause too much upgrade code and would avoid the need to introduce a new table to the db.

Instead of creating a new table for the stuck messages, compute which of the faux_offline_pending messages are actually stuck on each history load, and gives those the appropriate icon, and avoid sending them? I think I prefer having a new table storing them in the correct state, and quarantining the weird logic to a once-run upgrade function than having to decide on each run which of the faux_offline_pending message are really pending, and which are broken. It's true there will be another "schema" bump and upgrade code, but that code is still needed even if we don't create a new table.

**Comment by sudden6** [comment]
> Instead of creating a new table for the stuck messages, compute which of the faux_offline_pending messages are actually stuck on each history load, and gives those the appropriate icon, and avoid sending them?

I wouldn't give them any special icon and just resend them unconditionally. I think it could be the case that qTox is killed before receiving the message receipt. In this case the message would be marked undelivered in the db and be essentially stuck. So I think we need some logic anyway to clean these out.

**Comment by anthonybilinski** [comment]
To summarize a chat with @sudden6 considering pros and cons of just deleting these messages from history completely, instead of creating a new table to track them as broken:
1) no new table
2) no new icon
3) no special chatform handling

cons:
1) history is changed

both cases:
1) upgrade logic to check which messages are invalid
2) communication-wise functionally equivalent

After some chat we agreed the creating the table and handling the broken messages with upgrade-style logic would be best, using the criteria of unsent messages older than the last delivered message being considered broken.
