### ISSUE TITLE
Tray icon doesn't indicate status

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#578]
Maybe show the orb over top of it, if not change the lock color.

**Comment by suhr** [comment]
Lock icon is pretty ugly anyway. Why not change it to something else?

**Comment by ProMcTagonist** [comment]
It's got to clearly and obviously be Tox sitting in your tray. I don't know anything else that can do that but the lock.
I don't think the lock is particularly ugly. Might be because my tray is so tiny.
![qtox tray icon ideas](https://cloud.githubusercontent.com/assets/4358079/4871746/2e39b6ba-61c6-11e4-86dd-ec28dac4a479.png)

**Comment by suhr** [comment]
> I don't think the lock is particularly ugly. Might be because my tray is so tiny.

Looks ugly for me.

![2014-11-01-165158_1280x1024_scrot](https://cloud.githubusercontent.com/assets/65870/4871920/6bf9d838-61ce-11e4-88c7-6022d5e09c20.png)

**Comment by ProMcTagonist** [comment]
Ew. 

@ItsDuke

**Comment by ItsDuke** [comment]
@suhr I wonder why it doesn't have an alpha channel?

**Comment by agilob** [comment]
I receive the same feedback from one more user today, this screenshot
![inline](https://cloud.githubusercontent.com/assets/2544251/4875350/4ab91056-6293-11e4-98cd-81f510007b2c.png)

@ProMcTagonist could you share that set of icons?

**Comment by ProMcTagonist** [comment]
@agilob I just quickly GIMPed a little screenshot of my tray to see how it would look. I don't have any real-res icons or vectors. It should be as simple as changing the fill on the shapes to the desired colors in inkscape, though.

**Comment by ItsDuke** [comment]
Does anyone know where the vector is? That would help greatly.

**Comment by ProMcTagonist** [comment]
@itsDuke I believe this is it. https://github.com/tux3/qTox/blob/master/img/icons/qtox.svg

**Comment by ItsDuke** [comment]
I'm hesitant about simply making a few different colors and calling it good. Mainly because it's parallel to how we worked on the status dots. The status dots are not only different colors, but different shapes as well so that folks with certain color vision deficiencies or people using low color/high contrast settings on their monitors can tell the difference as well.

I wonder if having tox offline would simply yield the regular tox logo, but all of the other statuses (online, idle, away, etc), would be better suited by showing the applicable status orb in the taskbar.

Thoughts?

**Comment by ProMcTagonist** [comment]
That's definitely a valid concern. I didn't even realize the thought behind the orb shapes, props on that. 
I'm wary of having just a floating dot in the tray, though, it could be confusing. Could we overlay the orb on the tox lock, replacing the little person? 

![toxup tray 1](https://cloud.githubusercontent.com/assets/4358079/4911310/65b9c41e-648b-11e4-8b44-bda76d743830.png)
or maybe
![toxup tray 2](https://cloud.githubusercontent.com/assets/4358079/4911311/65c14bda-648b-11e4-83b1-e778b05d232c.png)

While making those I've discovered that the UI guidelines actually call the red hollow circle away, while every client is actually using it as offline, calling the yellow "idle" half-filled circle "away" and using something of their own making for busy, which is absent altogether from the UI guidelines. qTox actually uses a red-colored copy of the idle symbol for busy, which does not work at all for being able to tell them apart without color. 

So, some client devs and @ItsDuke need to talk about that.

**Comment by dubslow** [comment]
To be honest, I have quite good vision (both of color and not), and I often fail to notice the difference between busy and offline, because they share a color and most of a shape... if the busy was filled red, that would be much better than half filled red (but then it's also confusable with online for color blind people).

Maybe half filled vertically instead of horizontally?

**Comment by ProMcTagonist** [comment]
If we're making an icon for busy now I vote for http://upload.wikimedia.org/wikipedia/commons/a/a5/Road-sign-no-entry.svg as I'm pretty sure it's what early Venom used, since it's what I thought busy was this whole time until investigating.

**Comment by dubslow** [comment]
That works too.

**Comment by ItsDuke** [comment]
@ProMcTagonist When the status orbs were originally being worked on, it was three statuses: Green for online, yellow for idle, and red for either offline or away. (Or showing no dot whatsoever for offline).

While I agree that there should be some consistency, it's not my place to force all the different versions to conform to that idea.

**Comment by ProMcTagonist** [comment]
@ItsDuke would you be open to defining a real sign for busy in the UI repo, since there's nothing there now but all clients have implemented busy anyway and the icon scene for it is a mess?

**Comment by dubslow** [comment]
^^

**Comment by agilob** [comment]
@ProMcTagonist  the second screenshot looks great!

**Comment by ItsDuke** [comment]
I could have sworn I uploaded these earlier this mroning, but now when I come back they seem to be missing. Oh well. Here they are again.

![small](https://cloud.githubusercontent.com/assets/7714365/4928168/d43e6262-6541-11e4-8d02-aefe7c5e4fba.PNG)

![large](https://cloud.githubusercontent.com/assets/7714365/4928170/d7597270-6541-11e4-938e-007cb3af8f7c.PNG)

**Comment by suhr** [comment]
> Invisible

Can toxcore into invisible mode yet? It definitely should be in qTox as feature.

**Comment by dubslow** [comment]
I don't think it can...

**Comment by ProMcTagonist** [comment]
@ItsDuke I like them :)

@suhr @dubslow It can't at the moment. Or at least, it would be identical to being offline. I'm not sure if it's even conceptually possible to look offline and still be able to get requests and messages.

**Comment by ItsDuke** [comment]
@suhr @ProMcTagonist @dubslow 

To be fair I don't remember who asked me for an invisible status orb, but I figured I might as well make one just in case it gets implemented in the future.

**Comment by dubslow** [comment]
@ItsDuke where are those images located? I don't see anything in your repo

**Comment by ItsDuke** [comment]
@dubslow I'm about to save these out, any idea what size and filetype I should save them as?

**Comment by dubslow** [comment]
https://github.com/tux3/qTox/tree/master/ui

^ Looks like current images are .png

**Comment by dubslow** [comment]
@ItsDuke Any progress on the [Tox logo+status](https://github.com/tux3/qTox/issues/578#issuecomment-61900064) images?

**Comment by ItsDuke** [comment]
Yes indeedy, see https://github.com/ItsDuke/Tox-UI/commit/0aef5a94d61ca0086dc7eac3ef811a3f60de07df. You'll see that the status folder has some updated images, and there is a new "taskbar" folder with the necessary imagery inside.

**Comment by dubslow** [comment]
<3

**Comment by ghost** [comment]
@ItsDuke how about a version that would look good on dark background? At the moment users of dark desktop themes see just say small green dot and features of padlock are indistinguishable.

**Comment by ProMcTagonist** [comment]
Example of ^ on a fresh #! install.
![tray](https://cloud.githubusercontent.com/assets/4358079/5365446/dcddd7bc-7fa0-11e4-84c3-2446e1db73af.png)

**Comment by ghost** [comment]
This is odd. Did you do anything special to make it show up?

**Comment by ItsDuke** [comment]
@novist @ProMcTagonist https://github.com/ItsDuke/Tox-UI/tree/master/taskbar

Enjoy!

**Comment by ProMcTagonist** [comment]
Nice! :)

**Comment by Xylemon** [comment]
@ItsDuke That's looking better. I never was a big fan of the busy icon, it seemed too much like the offline one which lead to confusion. What I do have to say though is the new busy icon does make me think of a "blocked" icon, if one is ever to be created.

**Comment by ProMcTagonist** [comment]
@Xylemon 
What do you think of this?
![dnd-128](https://cloud.githubusercontent.com/assets/4358079/5408388/316f7314-818e-11e4-8f38-92faac27f5e0.jpg)

I'm partial to it, it looked good in old venom.

I'm closing this issue now because the tray icon does indicate status. Thanks everybody.
