### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [qTox/qTox#5785]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the function “CameraSource::destroyInstance”](https://github.com/qTox/qTox/blob/17083b50ba3de2ddbb2e534f4c30509bedab016b/src/video/camerasource.cpp#L132 "Update candidate").

**Comment by sudden6** [comment]
Good catch, would welcome a PR for it.
