### ISSUE TITLE
qTox Mac Deplayment error

### ISSUE THREAD

**Issue by rong-00gle** [qTox/qTox#5786]
##### Brief Description

OS: OS X 10.12.6
qTox version: v.1.16.3
Commit hash:  
toxcore:  0.2.10
Qt:  5.13.0
Hardware:  

```
ERROR: Cannot resolve rpath "@rpath/libtoxcore.2.dylib"
ERROR:  using QSet("/usr/local/Cellar/qt/5.13.0/lib", "/usr/local/Cellar/ffmpeg/4.1.4_1/lib", "/usr/local/Cellar/libsodium/1.0.18/lib", "/usr/local/Cellar/openal-soft/1.19.1/lib", "/usr/local/Cellar/libexif/0.6.21/lib", "/usr/local/Cellar/libvpx/1.8.1/lib", "/usr/local/Cellar/sqlcipher/4.2.0/lib", "/usr/local/Cellar/qrencode/4.0.2/lib")
ERROR: no file at "/usr/lib/libfilteraudio.0.dylib"
```

![qtox-deploy-error](https://user-images.githubusercontent.com/47773007/62942812-ba7efe00-bdf6-11e9-877c-0d843196223a.png)

**Comment by sudden6** [comment]
Are you building from the `v1.16.3` tag or from the master branch?

Is this a fresh build? Did you set any specific settings?

**Comment by rong-00gle** [comment]
@sudden6 thanks for quick response

yes i am building from master branch, build success in linux and mac, by while creating dmg file giving me this error. 

![qtox_version](https://user-images.githubusercontent.com/47773007/62994294-c3181880-be78-11e9-9904-886ba3896257.png)

yes made some changes in src/persistence/setting.cpp

`s.setIniCodec("UTF-8");

    s.beginGroup("Login");
    {
        autoLogin = s.value("autoLogin", true).toBool();
    }
    s.endGroup();

    s.beginGroup("General");
    {
        translation = s.value("translation", "en").toString();
        showSystemTray = s.value("showSystemTray", false).toBool();
        autostartInTray = s.value("autostartInTray", false).toBool();
        closeToTray = s.value("closeToTray", false).toBool();
        if (currentProfile.isEmpty()) {
            currentProfile = s.value("currentProfile", "").toString();
            currentProfileId = makeProfileId(currentProfile);
        }
        autoAwayTime = s.value("autoAwayTime", 5).toInt();
        checkUpdates = s.value("checkUpdates", false).toBool();
        // note: notifySound and busySound UI elements are now under UI settings
        // page, but kept under General in settings file to be backwards compatible
        notifySound = s.value("notifySound", true).toBool();
        notifyHide = s.value("notifyHide", false).toBool();
        busySound = s.value("busySound", false).toBool();
        autoSaveEnabled = s.value("autoSaveEnabled", false).toBool();
        globalAutoAcceptDir = s.value("globalAutoAcceptDir",
                                      QStandardPaths::locate(QStandardPaths::HomeLocation, QString(),
                                                             QStandardPaths::LocateDirectory))
                                  .toString();
        autoAcceptMaxSize =
            static_cast<size_t>(s.value("autoAcceptMaxSize", 20 << 20 /*20 MB*/).toLongLong());
        stylePreference = static_cast<StyleType>(s.value("stylePreference", 1).toInt());
    }
    s.endGroup();

    s.beginGroup("Advanced");
    {
        makeToxPortable = s.value("makeToxPortable", false).toBool();
        enableIPv6 = s.value("enableIPv6", false).toBool();
        forceTCP = s.value("forceTCP", true).toBool();
        enableLanDiscovery = s.value("enableLanDiscovery", false).toBool();
    }
    s.endGroup();

    s.beginGroup("Widgets");
    {
        QList<QString> objectNames = s.childKeys();
        for (const QString& name : objectNames)
            widgetSettings[name] = s.value(name).toByteArray();
    }
    s.endGroup();

    s.beginGroup("GUI");
    {
        showWindow = s.value("showWindow", true).toBool();
        notify = s.value("notify", true).toBool();
        desktopNotify = s.value("desktopNotify", true).toBool();
        groupAlwaysNotify = s.value("groupAlwaysNotify", true).toBool();
        groupchatPosition = s.value("groupchatPosition", true).toBool();
        separateWindow = s.value("separateWindow", false).toBool();
        dontGroupWindows = s.value("dontGroupWindows", false).toBool();
        showIdenticons = s.value("showIdenticons", true).toBool();

        const QString DEFAULT_SMILEYS = ":/smileys/emojione/emoticons.xml";
        smileyPack = s.value("smileyPack", DEFAULT_SMILEYS).toString();
        if (!QFile::exists(smileyPack)) {
            smileyPack = DEFAULT_SMILEYS;
        }

        emojiFontPointSize = s.value("emojiFontPointSize", 24).toInt();
        firstColumnHandlePos = s.value("firstColumnHandlePos", 50).toInt();
        secondColumnHandlePosFromRight = s.value("secondColumnHandlePosFromRight", 50).toInt();
        timestampFormat = s.value("timestampFormat", "hh:mm:ss").toString();
        dateFormat = s.value("dateFormat", "yyyy-MM-dd").toString();
        minimizeOnClose = s.value("minimizeOnClose", false).toBool();
        minimizeToTray = s.value("minimizeToTray", false).toBool();
        lightTrayIcon = s.value("lightTrayIcon", false).toBool();
        useEmoticons = s.value("useEmoticons", true).toBool();
        statusChangeNotificationEnabled = s.value("statusChangeNotificationEnabled", false).toBool();
        spellCheckingEnabled = s.value("spellCheckingEnabled", true).toBool();
        themeColor = s.value("themeColor", 0).toInt();
        style = s.value("style", "").toString();`

**Comment by sudden6** [comment]
Ok, these changes are probably not the issue.

This is strange, since on our CI setup there are no problems.

Maybe our CI script for Mac can help you: https://github.com/qTox/qTox/blob/master/.travis/build-osx.sh?

EDIT:

From the error message I suspect this might have something to do with the dependencies, did you run the commands to install them?
