### ISSUE TITLE
Extra DHT node connection which are not defined

### ISSUE THREAD

**Issue by rong-00gle** [qTox/qTox#5787]
##### Brief Description
I have defined hosted a DHT-bootstrap node and defined that node in qtox.ini and res/settings.ini

```
[DHT%20Server]
dhtServerList\1\address=A.B.C.D
dhtServerList\1\name=node
dhtServerList\1\port=33445
dhtServerList\1\userId=publickey
dhtServerList\size=1
useCustomList=false
```

But while qtox in running it still making some other connection as well, i wanna know why qtox is connected other nodes which are not defined in source code and is their anything i am missing?

**What i want:**
I want my qtox client to make connection with my DHT-Node only, no matter what it should find all tox-id from this dht node. 

OS: Linux Ubuntu 18.04
qTox version: 1.16.3 Release
toxcore version: 0.2.10 
Qt:  5.9.5
Hardware:  
…

Reproducible: Always

![Screenshot from 2019-08-14 10-56-46](https://user-images.githubusercontent.com/47773007/62996403-3bcfa280-be82-11e9-9ff7-01d6b57806db.png)

[qtox.log](https://github.com/qTox/qTox/files/3499924/qtox.log)
[qtox.ini.txt](https://github.com/qTox/qTox/files/3499972/qtox.ini.txt)

**Comment by sudden6** [comment]
From:

```[05:20:23.139 UTC] core/core.cpp:357 : Debug: "Connecting to A.B.C.D:33445 (node)"
[05:20:23.140 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:network.c:sendpacket:484: attempted to send message of length 113 on uninitialised socket"
[05:20:23.140 UTC] core/core.cpp:357 : Debug: "Connecting to A.B.C.D:33445 (node)"
[05:20:23.141 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:network.c:sendpacket:484: attempted to send message of length 113 on uninitialised socket"
[05:20:27.639 UTC] core/core.cpp:357 : Debug: "Connecting to A.B.C.D:33445 (node)"
[05:20:27.640 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:network.c:sendpacket:484: attempted to send message of length 113 on uninitialised socket"
[05:20:27.640 UTC] core/core.cpp:357 : Debug: "Connecting to A.B.C.D:33445 (node)"
[05:20:27.640 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:network.c:sendpacket:484: attempted to send message of length 113 on uninitialised socket"
[05:20:31.208 UTC] core/core.cpp:326 : Debug: Connected to the DHT
```

I can see that your modifications to qTox are correct and you only bootstrap from A.B.C.D

I think what's happening here is that, your bootstrap node works correctly and shares its list of nodes with your client. This is working as intended to integrate your node into the distributed hash table of Tox.

**Comment by rong-00gle** [comment]
my bootstrap node status

![dht-node](https://user-images.githubusercontent.com/47773007/63206818-839c3700-c0d9-11e9-9e68-4909e0a02108.png)

**No 'bootstrap_nodes' setting in the configuration file. Skipping bootstrapping.** so client shouldn't find peers from any other IP-Addresses or DHT-Node.

**Comment by sudden6** [comment]
Do you have any other clients running in your local network and the "LAN discovery" feature enabled?

**Comment by rong-00gle** [comment]
Sometimes there are more than one client in my local network, all these clients runs with same qtox.ini settings

```
[Advanced]
dbSyncType=21926
enableIPv6=false
enableLanDiscovery=false
forceTCP=true
makeToxPortable=false
```

**Comment by sudden6** [comment]
Are you running the latest commit from master? IIRC there was a fix for connection settings not being correctly applied.

If you're already running on master, I have no idea why that could happen, maybe there is something with nodes exchanging TCP relays that I don't know about.

**Comment by rong-00gle** [comment]
I am using Latest release v1.16.3.

**Comment by sudden6** [comment]
Can you try a build from the latest commit: https://github.com/qTox/qTox/commit/412f14558150e4da76acb3d639f5a23dca58b33b? One of the nightly builds should work too: https://github.com/qTox/qTox-nightly-releases/releases

**Comment by sudden6** [comment]
Another suggestion from zugz in the #toktok IRC channel was to try everything with new tox profiles, as the tox profiles may store peers of the DHT to make startup faster.

**Comment by nurupo** [comment]
Right, tox profile stores a list of DHT nodes it was previously connected to, which toxcore will try to connect to automatically, there is no option to tell it not to.

Btw, note that nodes shared information of other nodes among themselves. If you have a totally isolated bootstrap node A and a totally isolated client B and you connect them to each other, they would be communicating only among themselves. But if a client C that knows of other DHT nodes connects to either A or B, the knowledge of those other nodes will spread to A and B and they will try connecting to those nodes. If your goal is to keep your tox network isolated, the best solution is by introducing a slight protocol breaking change. Many DHT implementations have a version or passphrase field exactly for this purpose. Not sure if toxcore has something like this, probably not, but if it does, it's certainly not exposed in the API.
