### ISSUE TITLE
Graphical glitchez

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#579]
This happens: http://a.pomf.se/yzwokk.webm

Also, can you pls add an option to disable tray? It looks like shit on ubuntu.
![pic related](http://a.pomf.se/wwozvw.png)

**Comment by tux3** [comment]
Dup of #541 

Disabling the tray sounds like a good idea on ubuntu.

**Comment by ghost** [comment]
Don't forget to see webm :^)

**Comment by tux3** [comment]
Right, I'll fix the groupchat-still-shown-after-you-quit-it one right now, as for the resizable friendlist disappearing I used to have this bug a month or so ago and though it was fixed, I'll take a look at it.
