### ISSUE TITLE
How to get groupchat id?

### ISSUE THREAD

**Issue by whoizit** [qTox/qTox#5790]
I need a group chat id so as not to add everyone as a friend and invite to chat

**Comment by sudden6** [comment]
Can you explain in more detail what you want?

**Comment by whoizit** [comment]
I want to publish group chat id so anyone can join to the chat

**Comment by sudden6** [comment]
This is not possible with the current Tox protocol, each person that should join a must be invited by someone already in the groupchat.

There exist however bots that can help with that issue.
