### ISSUE TITLE
disable group join leave messages

### ISSUE THREAD

**Issue by whoizit** [qTox/qTox#5792]
how to disable join leave messages in group chats? Can't find this option in preferences

**Comment by sudden6** [comment]
As far as I know there is no such option.

Not sure if we want to consider it, but what are the reasons you want to disable these messages?

**Comment by whoizit** [comment]
because it's noise

![2019-08-19_21-41](https://user-images.githubusercontent.com/359276/63290414-126fa600-c2ca-11e9-911d-e47dc4febe7b.png)

**Comment by anthonybilinski** [comment]
This seems reasonable to me - in large groups with low chat, like on IRC, my chatlog ends up being 98% connect and disconnect messages making it hard to see new messages. I haven't seen many large Tox groups like that, but apparently they exist :)

**Comment by TriKriSta** [comment]
as an option, you can use the menu "Go to current date". it deletes these messages.

**Comment by anthonybilinski** [comment]
That works.. but I still think having a setting would be nice instead of relying on the side-effects of an unrelated feature :smile:

**Comment by anthonybilinski** [comment]
This was implemented in https://github.com/qTox/qTox/pull/6457.
