### ISSUE TITLE
Settings are reset each time (Ubuntu 14.10)

### ISSUE THREAD

**Issue by qherreros** [qTox/qTox#581]
Hi,

I tried qTox last week and it seems that settings (as well as tox ID, name, ...) are reset each time I launch it. When I activate the "make utox portable" it seems to work just fine.

I use qTox from official repository with Ubuntu 14.10. uTox is also installed on this computer.

**Comment by dubslow** [comment]
Can you try `ls ~/.config/tox`? What messages do you see when you run qTox from the terminal?

**Comment by tux3** [comment]
Doesn't seem to be a problem anymore, closing. If someone still has this issue, please post a comment and try to give more details.
