### ISSUE TITLE
Desktop Share Squiggly Lines

### ISSUE THREAD

**Issue by templa876** [qTox/qTox#5817]
When i attempt to video call my friend and do screen share it causes him to see my screen as squiggly lines. I have video device on "desktop" & resolution on "Screen 1" the preview pane shows the video perfectly but he only gets squiggly lines. I have tried restarting computer still does not help.

OS: Windows
qTox version: v 1.16.3  
Commit hash:  8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.3
Qt:  5.9.6
Hardware:  Windows 10;
Processor: i3-5010u 2.10GHZ 2100MHZ 2 cores

Reproducible: Always

##### Steps to reproduce

1. video call
2.  screen doesn's show

![Unbenannt](https://user-images.githubusercontent.com/54919477/64302543-e141d780-cf51-11e9-9059-f6c50e995d66.jpg)

**Comment by sudden6** [comment]
Can you check if that still occurs on one of the nightly builds? See: https://github.com/qTox/qTox-nightly-releases/releases for downloads

**Comment by templa876** [comment]
> Can you check if that still occurs on one of the nightly builds? See: https://github.com/qTox/qTox-nightly-releases/releases for downloads

how do i install the nightly build such as this not very tech savy, it comes in multiple files do i download them all, and do i uninstall my current qtox, in addition does it matter what version my friend has thanks very much :)

**Comment by sudden6** [comment]
If you take one of the *.zip files, you can just extract it and run `qtox.exe`, the *.exe files are normal installers.

>  in addition does it matter what version my friend has thanks very much :)

Ideally they would also use the latest nightly build for this test.

**Comment by anthonybilinski** [comment]
Based on description of https://github.com/qTox/qTox/issues/5820#issue-490705043, sounds like the nightly fixed this issue for templa876.
