### ISSUE TITLE
mac os版本，最小化之后显示离线，无法接收消息

### ISSUE THREAD

**Issue by louisliu1985** [qTox/qTox#5822]
##### Brief Description

OS: macOS 10.14
qTox version: v1.16.3
Commit hash: 8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore: 0.2.3
Qt: 5.11.1
Hardware: 
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. 
2. 
3. …

##### Additional Info
(links, images, etc go here)

----

More information on how to write good bug reports in the wiki: https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by sudden6** [comment]
Please write your bug report in English or try a translation service.
