### ISSUE TITLE
64 bit, 32 bit nightly - HTTP ERROR 404

### ISSUE THREAD

**Issue by UnlimitedChild** [qTox/qTox#5831]
HTTP ERROR 404
Problem accessing /view/qtox/job/qTox-cmake-nightly_build_windows_x86-64_release/lastSuccessfulBuild/artifact/qTox-cmake-nightly_build_windows_x86-64_release.zip. Reason:

    Not Found

**Comment by sudden6** [comment]
Nightly builds have moved to: https://github.com/qTox/qTox-nightly-releases/releases
