### ISSUE TITLE
Offline & can't see other online clients

### ISSUE THREAD

**Issue by TalkLounge** [qTox/qTox#5835]
Hi!
If I start qTox, I'm offline. From one day to another, qTox won't connect to other clients. I've already reinstalled qTox with the newest version and restarted my pc a few times now. The issue is since ~ 5 days now.
Right-click on the grey circle doesn't work and right-click on the qTox task bar logo and set my status to online doesn't work as well. 
If I'm online with my uTox Account(TalkLounge2) on the same pc, normally qTox shows TalkLounge2 as online. This doesn't work now as well.

**System Data**
OS: Windows 10 (10.0)
qTox version: v1.16.3
Commit hash: 8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore: 0.2.3
Qt: 5.9.6

**qTox Window**
![qTox Window](https://i.imgur.com/ahbojLU.png)

**Error.log**
[Error.log](https://pastebin.com/c5ceGbPM)
Pastebin log is available for one year.
Some information to the error.log:
At 16:55 I've started qTox.
At 16:56 I've opend qTox, because normally it starts hidden in task bar
At 16:57 I've exported the error log.
Note: I've censored the log at some point with XXX.

Any ideas?
Thanks for your help.

**Comment by jessica181920** [comment]
1.16.3 is unfortunately pretty old... the bootstrap node list on that might be outdated enough to not be able to get you connected. I wouldn't really think so since there are plenty of nodes that have been running for a long time.

Just to rule it out, try a nightly build real fast:
https://github.com/qTox/qTox-nightly-releases/releases/tag/ci-master-latest

You probably want either qtox-x86_64-release.zip (archive) or setup-qtox-x86_64-release.exe (installer).

**Comment by jessica181920** [comment]
I just read your log. Definitely try the nightly build, and also, go into settings, click the "advanced" tab, click "enable UDP" and then restart qtox. See if that helps.

**Comment by jessica181920** [comment]
Okay I think I know what's happened, you hit an old bug: #5311

This bug has been fixed a long time ago, but we haven't made a new release in a long time. 1.16.3 is over a year old. If you update to the latest nightly version, it will certainly fix your problem. However, if you don't want to install the nightly and you want to continue using 1.16.3, go to settings, click the advanced tab, and change the "proxy type" option to "none" and restart qtox.

In the event that it is your bootstrap nodes, which is unlikely, those will be updated as well with the nightly build. In older versions of qtox, you were able to manually edit your bootstrap node list. We moved to json, and when we did, the bootstrap nodes are now compiled in the binaries, so to edit them you have to compile qtox. I was talking to @anthonybilinski one day and mentioned this, there's a ticket open for it here: #5767 so this will hopefully be fixed someday soon.

Hope this helped.

**Comment by TalkLounge** [comment]
> go into settings, click the "advanced" tab, click "enable UDP" and then restart qtox.

Thanks, that worked.
Maybe a new qTox stable version would be nice from time to time. I will try the nightly version tomorrow.
