### ISSUE TITLE
 Data Recovery Method Qtox

### ISSUE THREAD

**Issue by moh26000** [qTox/qTox#5851]
![Capture](https://user-images.githubusercontent.com/55385827/65704344-48006f80-e07e-11e9-8abc-99b56c2945bc.PNG)

**Comment by moh26000** [comment]
D23C3B99EEEC04B14CBFEEC5D6C73D5233D51391EC13DF9C8236A2EE4E9929474C09B364E1B7

**Comment by sudden6** [comment]
What is your question/problem?

**Comment by anthonybilinski** [comment]
@moh26000 posted the same screenshot at around the same time here https://github.com/qTox/qTox/issues/367#issuecomment-535566516 and his problem there was resolved.. so this might be too. I guess we'll just close after a bit if there's no answer.
