### ISSUE TITLE
Migration from gtk2 to gtk3

### ISSUE THREAD

**Issue by TriKriSta** [qTox/qTox#5859]
I had a problem with building qTox.
I found the problem it is conflict glib2 2.62.1 with gtk2

some errors:

`/usr/include/gtk-2.0/gtk/gtktypeutils.h:236: error: ‘GTypeDebugFlags’ is deprecated
/usr/include/gtk-2.0/gtk/gtktooltips.h:73: error: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead
`
I did downgrading package glib2 2.62.1 to 2.60.7 it fixed the problem.

I think in future qTox need migration to gtk3 to avoid this problem.

**Comment by sudden6** [comment]
We should also re-check why we even have that dependency and if it's still needed at all.

**Comment by TriKriSta** [comment]
qTox uses gtk for system tray icons
maybe need to use only QSystemTrayIcon for it?

**Comment by sudden6** [comment]
I don't know, IIRC we once used some special code for Ubuntus Unity, not sure if Qt got everything properly working in newer versions of QSystemTrayIcon. It needs to be tested.

**Comment by Diadlo** [comment]
There is no more Ubuntu's Unity. [Proof](https://www.omgubuntu.co.uk/2017/04/ubuntu-18-04-ship-gnome-desktop-not-unity).

**Comment by TriKriSta** [comment]
I checked QSystemTrayIcon on Ubuntu Unity. It works badly. The program after hiding doesn't show if use launcher(

**Comment by anthonybilinski** [comment]
We should maybe prune back our use of env specific icons, and prefer to use Qt's backend when available. Related issue: https://github.com/qTox/qTox/issues/5881#issuecomment-541519590. From https://stackoverflow.com/questions/41917903/gtk-3-statusicon-replacement, it looks like there isn't a GTK+ 3 replacement?

**Comment by sudden6** [comment]
@anthonybilinski I agree, with removing specialized backends in favour of Qt.

From the link it seems however that GTK+ 3 doesn't support tray icons at all? Maybe we need a solution for such platforms too.

**Comment by anthonybilinski** [comment]
@TriKriSta I just tried on Ubuntu 16.04 with Unity, and during qTox start it logs that it's using the Qt tray icon backend, and it works well from my testing (menu works, status change, hiding to tray and restoring).

Which Ubuntu version were you on specifically? Can you post logs from it not working? And what do you mean exactly by "after hiding"? The qTox settings "minimize to tray" + minimizing?

**Comment by anthonybilinski** [comment]
@sudden6 in my testing at https://github.com/qTox/qTox/issues/5881#issuecomment-541892457, e.g. Arch which fails compilation because GTK is too old in qTox, still functions correctly when the Qt tray backend is forced, so I'm not sure we need to worry about GTK+ 3's lack of tray support if Qt is handling it for us (however it is), and based on that testing, switching to Qt backend for all DEs is looking promising.

**Comment by TriKriSta** [comment]
@anthonybilinski Oh, I tested it again, and it works normally (in Ubuntu 16.4).
