### ISSUE TITLE
Desktop audio

### ISSUE THREAD

**Issue by MangaD** [qTox/qTox#5864]
It is possible to share screen but it doesn't seem possible to share the desktop audio. Could this be implemented?

**Comment by sudden6** [comment]
On Linux with pulseaudio this can be done by selecting the `Monitor` interface of a sound card. I don't know if Windows makes the combined sound output even accessible?

**Comment by MangaD** [comment]
@sudden6 I see `Monitor of Built-in Audio Analog Stereo`. If this is it then this issue can be closed.

**Comment by sudden6** [comment]
@MangaD yes, this is it. Does that work for you?

**Comment by MangaD** [comment]
@sudden6 Yes it does, I will close this issue.
