### ISSUE TITLE
Download nightly build links leads to 404

### ISSUE THREAD

**Issue by ntfshard** [qTox/qTox#5867]
##### Brief Description

OS: Windows
Reproducible: Always

##### Steps to reproduce

1. goto https://github.com/qTox/qTox
2. click **64 bit** or **32 bit** nightly links
3. page 404

**Comment by sudden6** [comment]
The linked Pull Request contains a fix for your problem.

**Comment by ntfshard** [comment]
No more old fashion zip files? That's sucks
