### ISSUE TITLE
When I compiled with windows , I can't find bootstrap.bat

### ISSUE THREAD

**Issue by zhb110708** [qTox/qTox#5869]
##### Brief Description

OS: Windows 
qTox version: newest,but I don't know

I use visual studio 2019 to compile qTox source code, I just installed tools below Native, but no idea about how to use

**Comment by sudden6** [comment]
Building qTox with Visual Studio is not supported. You can take a look at https://github.com/qTox/qTox/pull/5347 and see if you can make it work, but we build the releases with a docker container via cross-compilation from Linux.

**Comment by zhb110708** [comment]
ok，I'll try
