### ISSUE TITLE
Emoticons don't appear correctly in exported logs

### ISSUE THREAD

**Issue by tsdko** [qTox/qTox#588]
Log exported from Windows 8.1 opened on Xubuntu 14.04.
There are ￼ characters in place of emoticons.
I think the best way would be making emoticons appear (in logs) as their text equivalents if possible.

**Comment by suhr** [comment]
Same thing with coping text from chat, linux.

**Comment by dubslow** [comment]
@apprb

**Comment by apprb** [comment]
In the history every message stored as it was received.
Probably issue is in emoticons itself. Do its work well under your linux setup?

**Comment by suhr** [comment]
> Probably issue is in emoticons itself.

Yes it is. How to reproduce:
- Send text message with emoticon
- Highlight and copy text with emoticon from chat
- ??????
- ￼

**Comment by apprb** [comment]
About this. This probably won't be fixed until chat form be reimplemented (see last comments in #266).

**Comment by dubslow** [comment]
^^ Done. Fixed?

**Comment by suhr** [comment]
Yes, fixed.

**Comment by tsdko** [comment]
Seems to be fixed
