### ISSUE TITLE
Tray icon not visible on Ubuntu 19.04 with gnome3

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5881]
##### Brief Description

OS: Ubuntu 19.04, default theme, gnome3.
qTox version: v1.16.3+
Commit hash:  93c9eef51f8143c3e3e5c1e63e0cc64d1d533f6e
toxcore:  0.2.10
Qt:  5.12.2
Hardware:  Desktop

Possibly related to https://github.com/qTox/qTox/issues/5599 and https://github.com/qTox/qTox/issues/5846.

Reproducible: Always

##### Steps to reproduce

1. Open qTox

##### Observed Behavior
No qTox tray icon appears. When qTox is the active application, it does show up here:
![image](https://user-images.githubusercontent.com/10469203/66724982-6a65ed00-ede1-11e9-86b4-8d98fd4c6403.png)

but our tray icon menu isn't present, and that entry goes away as soon as a different application is selected.

In logs I see
`[06:34:22.124 UTC] widget/systemtrayicon.cpp:62 : Debug: Using GTK backend`
and
`[06:35:38.182 UTC] widget/systemtrayicon.cpp:92 : Debug: Deleting SystemTrayIcon`

##### Expected Behavior
Tray icon is correctly displayed, and the normal menu is present.

**Comment by anthonybilinski** [comment]
If I force the Qt icon backend (by hacking `SystemTrayIcon`, the icon displays correctly on my system.

When it was still using the GTK backend, every call seemed to be succeeding, items were being added to the menu, callbacks were being hooked up etc.

This narrows my issue down to the GTK backend specific code, or maybe a dep problem (e.g. still using GTK 2?) in this environment.

**Comment by anthonybilinski** [comment]
Why do we do native backends anyway? It looks like it was introduced in f75e32e1e3b601c1090e6b24a23a212756b4614a, when it went from just having Qt, to having both Qt and unity, which I think was done because unity's implementation was buggy. Now that unity is dying out, is it possible to just unify to Qt's system tray icon?

GTK was first added in 8a83a6114fb52079ae337a2af649e9ab158bfbde with the commit message:

> Implement GTK systray icon backend
> This one is deprecated, but should work much better than any other system tray icon backend we currently have, both in term of supported features and reliability. It justs needs some testing to see where we can enable it now.

If it was deprecated back in 2015, that could be why it's not working now.

From https://doc.qt.io/qt-5/qsystemtrayicon.html#details, supported environments for the Qt tray icon are
* All supported versions of Windows.
* All window managers and independent tray implementations for X11 that implement the http://standards.freedesktop.org/systemtray-spec/systemtray-spec-0.2.html freedesktop.org XEmbed system tray specification.
* All X11 desktop environments that implement the D-Bus http://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem specification, including recent versions of KDE and Unity.
* All supported versions of macOS.

I'm not totally sure if this covers all of our supported OSes and versions, but I think it's worth looking into and then just scrapping all platform specific tray implementations.

**Comment by sudden6** [comment]
I fully agree with scraping all special tray icons and moving to `QSystemTrayIcon`. It probably got a lot better since the time the special backends were needed.

**Comment by anthonybilinski** [comment]
I'll start going through supported OSes testing exactly how broken the tray is for them on both our current implementation and the strictly Qt implementation. Our status `status notifier` backend is supported, but never selected in `SystemTrayIcon`'s constructor, so that's dead code. The only backends we actually use are:
```
ENABLE_SYSTRAY_GTK_BACKEND
	else if (desktop == "xfce" || desktop.contains("gnome") || desktop == "mate"
	 	|| desktop == "x-cinnamon") {

ENABLE_SYSTRAY_UNITY_BACKEND
	if (desktop == "unity") {

else Qt
```
| Env  | Current implementation | Qt-only implementation |
| ------------- | ------------- | ------------- |
| Ubuntu 16.04 Unity  | Uses Qt backend, works well, icon displays well, menu works, status works  | Same  |
| Ubuntu 16.04 Gnome  | Uses GTK backend, no tray shows up at all.  | Works well, icon is too large for the tray so is cropped on top and bottom, but menu works, status works etc.  |
| Arch with XFCE4  | Doesn't compile because our GTK is outdated..  | Works great.  |
| Fedora 29 Gnome Wayland  | No system tray detected | N/A  |
| Fedora 29 Gnome X11 | No system tray detected | N/A  |
| Fedora 29 KDE Plasma  | Uses Qt backend, works well  | Same  |
| Fedora 30 KDE Plasma  | Uses Qt backend, works well  | Same  |
| openSUSE Leap 15, KDE  | Uses Qt backend, works well  | Same  |
| Debian 9  | Uses GTK backend, it works!!  | continues to work perfectly  |
| Debian 10 wayland/x11 system/gnome classic  | No system tray detected  | N/A  |

**Conclusion:** Supporting only QSystemTrayIcon won't regress any tested systems, and will break our dependency on deprecated GTK+2, as well as fixing the icon on Ubuntu when it's using the GTK backend.

RE: investigating adding https://launchpad.net/sni-qt as an optional dependency:

| Env  | Without sni-qt | With sni-qt |
| ------------- | ------------- | ------------- |
| Ubuntu 18.04 Gnome  | Icon displays in top right corner right next to network/power/sound icons. Displays well, functions properly.  | Icon displays about 5cm left of where it did previously, leaving a large gap between qTox and the network/sound/power icons. qTox icon still works correctly. |
| Ubuntu 19.04 Gnome  | shows up right next to other icons, works properly | Same. |
| Ubuntu 16.04 Unity | came pre-installed. removing the package - still works perfectly  | works perfectly |
| Ubuntu 16.04 Gnome | removing the package - still works well but icon is cropped like before  | icon cropped like before |

**Conclusion:** No reason to add sni-qt as an optional dependency.

**Comment by sudden6** [comment]
I can add the following data point:

openSUSE Leap 15, KDE

Uses Qt backend

Works, icon displays well, menu works, status works
