### ISSUE TITLE
Change log ?

### ISSUE THREAD

**Issue by darkman088** [qTox/qTox#590]
Hello,

I would kindly like to ask, whether there is a change log (list) of this project somehwere ? I would love to see what's new in each version and whether it makes sense for me to download and upgade...

Thanks a lot !!

**Comment by agilob** [comment]
we don't do any versioning, but I think it wouldn't be a problem to do as a wiki page in this project.

**Comment by DanTheBritish** [comment]
I suppose you could use the Git commit log, a lot of the messages are quite descriptive, and you can pick up a lot of information from the source code changes. Granted, this isn't a per-version changelog, but it's a good way to see the latest changes.

A note on this is that it isn't very user friendly.

**Comment by darkman088** [comment]
OK, just I will show you from where I've gotten to this question:

https://github.com/notsecure/uTox/issues/634
ou 
https://jenkins.libtoxcore.so/job/Sync%20uTox/changes

Seems like uTox won't be developed anymore :-( Do you guys know something about that ?

**Comment by agilob** [comment]
ups, I don't like it, qTox should have competition.

**Comment by dubslow** [comment]
@darkman088 notsecure is a student, he may be more active over winter break

**Comment by darkman088** [comment]
@dubslow - OK, fine, let's wish him all the best in his studies then!! But I can't believe that there are just 2 developers - one working on uTox and one working on qTox... I thought like there are at least 5-6 people pushing qTox further... I the last build I checked a few days ago, there were awesome things like encrypting the contacts file, saving chat history (which I will ALWAYS keep turned off!). But they were just checkboxes, as I found out a few seconds later... No functionality yet behind them... :-/

**Comment by dubslow** [comment]
Theres... 1, 2, 3, 4, 5 people working at various paces on qTox. I haven't been terribly active myself lately.

And yes, uTox has one developer; core has ~2. Frankly, it's amazing how much has been accomplished by so little manpower (most of which is irungentoo anyways).

**Comment by suhr** [comment]
@darkman088 Lazy developers are lazy and some people usually make only one thing like UI or translation. Tox is still not very popular, so new features are coming pretty slow.

**Comment by darkman088** [comment]
Yeah, I see how much work has been put into this - this is how it is very very hard for me to believe, that there can be just 1 developer...
@suhr - and exactly this is where controversy comes! How to get popular, if new features are coming slow... People want to see something vivid, functional, etc... I want to inform all my Skype contacts, that I have dropped Skype (I didn't sign in for AT LEAST 2 months!!) about Tox and invite them to join... But how one can enjoy using it, when one is not able to rename a chat-buddy in the contacts !!
I have been checking 2 more programs - they open a million of useless windows, Tox is No 1 with just one window !!!
What I would like to point out here - I am not a developer, but I have a LOT of experience in using software and administering software - I can be very helpful with ideas how to make this program REALLY user friendly and with a very high productivity. But without developers, it is simply not possible...

**Comment by agilob** [comment]
> I can be very helpful with ideas how to make this program REALLY user friendly

please make screenshots describing your ideas.

**Comment by suhr** [comment]
> I can be very helpful with ideas how to make this program REALLY user friendly and with a very high productivity

You're welcome! That's what we have `enhancement` issues for.

**Comment by dubslow** [comment]
You can always hire a full time dev :P:P

**Comment by agilob** [comment]
pls hire me

**Comment by darkman088** [comment]
Hello everyone,

first of all - screenshots... You can make screenshots of something existing. How can I make screenshots of functionality, that hasn't been implemented yet.
I have been opening many issues, containing ideas, I can try to put everything here together.

Functionality:
1. The possibility to rename a user is a must. If I know somebody as Peter from university, for example, I don't want to see his nick from some game, that I've never played and I don't associate this person with! I want to override his nick in MY client to read Peter!
2. Portability option - it is not nice to search for utox_save in program files......\??????

Design - here I will start with a general remark, before I start giving ideas. It is obvious, that nobody designing the interface, had a long contact list. From what I see, if someone from your contacts gets below the visible area, it is quite hard to notice any of his attempt to contact you. Therefore:

1) There should be... how to call it - notification area about the entire activity. Examples: 
a) chats - on receiving a text message, the green dot for the contact gets bigger. If you need to scroll to his name, in order to see it - you probably won't see it. YES, there is the bubble from the notification area, which I consider GREAT! But some other people might not like it - so perhaps it is good to have it as an option (on/off)
b) And that is MUCH worse - if somebody is calling - yes, THANK GOD, we finally have the ringtone!
But how to figure out who exactly is calling ? Again - scroll, search, figure out who has the yellow button (obviously only through finding the yellow button, one is able to answer a call!)... It takes time and it promptly turns into a missed call, especially bearing in mind that it keeps ringing for just 10 seconds !!!
My recommendation - call notification WITH a pickup button AT LEAST as a bubble in the notification area, the same as with chats. Having an independent part of the main window for this will be good as well. Also on your cell phones - when somebody calls you, you don't need to find him in the phone book, before you pick up!

2) There should be a button for rejecting calls. If I am busy with something else and the ringtone is VERY disturbing, there should be a way to reject the call. Also if I call someone by mistake, I should be able to quickly hang up, this is currently not possible.

3) It would be nice to see the call duration while heading a voice conversation.

4) Yesterday I've been extensively testing group chats - is it really only possible to invite people to the chat ONLY by dropping them above the group chat contact ? Try this with a long contact list - that's what I call cumbersome! My suggestion for the entire process: 
- Create a new group chat
- Click on it to display its contents in the right side (if not already)
- Scroll your contact list till the contact that you want to invite becomes visible
- Drop that contact INTO the chat window, not over Groupchat #0. 
  Currently even with a pressed button (for dragging), the chat window with that user becomes visible!

That is for now, only the first rough ideas, I am sure that through time I will get much more suggestions.

**Comment by tux3** [comment]
We now have change logs browsable online for each release of the stable branch.
