### ISSUE TITLE
"%APPDATA%/tox/" places data in qTox program folder

### ISSUE THREAD

**Issue by bricky149** [qTox/qTox#591]
Self-explanatory, it's not in the expected place to find profiles, etc.

**Comment by tux3** [comment]
I'm not sure what you mean, we moved the data to %APPDATA%/tox/ for compatibility with other clients and as per the STS (https://github.com/Tox/Tox-STS/blob/master/STS.md#tox-data-directory)

Do you mean that you lost your old profile when you updated qTox ?

**Comment by bricky149** [comment]
I didn't lose anything, just this happened.
![toxdata](https://cloud.githubusercontent.com/assets/4836781/4871886/35b3a60c-61cc-11e4-905c-7faf6bba6f2a.png)

**Comment by tux3** [comment]
Oh.

**Comment by bricky149** [comment]
Since this commit qTox crashes on exit. Can anyone else confirm?

Debug log shows an unnecessary double save upon exit.
21:20:39 Settings: Saving in  "C:/Users/Shane/AppData/Roaming/tox/settings.ini"
21:20:39 Core: writing tox_save to  "C:/Users/Shane/AppData/Roaming/tox/bricky149.tox"
21:20:39 Settings: Saving in  "C:/Users/Shane/AppData/Roaming/tox/settings.ini"
21:20:39 Core: writing tox_save to  "C:/Users/Shane/AppData/Roaming/tox/bricky149.tox"

**Comment by dubslow** [comment]
The double save has been there for ages and ages; I guess we all consider it Mostly Harmless™. I doubt it's related to the crash on exit.

Is it reproducible? Are you sure it's that commit specifically?

**Comment by tux3** [comment]
The crash on exit is caused by b78737632e1750abffc27cc6773e5a3d87fe1159

Both Settings and logFile are static, so logFile can be destroyed before Settings, and ~Settings uses the log ..

**Comment by dubslow** [comment]
Hmm. Isn't ~Settings run by the `delete w;`? And if so, then why is logFile being cleaned up before then? There's something about how static works that I'm not understanding here...

**Comment by tux3** [comment]
static basically means "constructed before main" and "destroyed after main", and the objects are normally destroyed in reverse order of construction as always. Basically.

Except when they aren't in the same translation unit, then the order of destruction is undefined. Wich is what just happened.

**Comment by dubslow** [comment]
But isn't Settings destroyed before main is finished?

**Comment by tux3** [comment]
No, Settings is static. It's destroyed after main and after the atexits, by definition.

If you try to call ~Settings in ~Widget it'll probably crash due to double-freeing.
