### ISSUE TITLE
Groups disappear

### ISSUE THREAD

**Issue by 6607320** [qTox/qTox#5913]
OS: Windows 10 (10.0)
qTox version: v1.16.3
Commit hash: 8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore: 0.2.3
Qt: 5.9.6

I create a group, add members to the group, but when all members are offline, the group disappears.

**Comment by sudden6** [comment]
This is a limitation of the 1.16.3 version. If you're willing to take the risk of untested and possibly broken builds you can switch to the nightly builds listed here: https://github.com/qTox/qTox-nightly-releases/releases

**Comment by andriusign** [comment]
Confirmed here:
qTox version v1.16.3
toxcore version: 0.2.3
Qt version: 5.11.3
Linux Mint 19.1 Cinnamon 4.0.10, kernel 5.0.0-32-generic

Does anyone know when the new release is due? It looks like last 1.16.3 version is a bit outdated (2018 last release).

**Comment by sudden6** [comment]
This is the issue tracker for the next release: https://github.com/qTox/qTox/milestone/23
