### ISSUE TITLE
Dark theme leaves chatform unchanged until restart

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5924]
##### Brief Description

OS: Ubuntu 19.10
qTox version: v1.16.3+
Commit hash:  1a726b54cd2e1d72c6cb6f0f9a733e904f5e5371
toxcore:  0.2.10
Qt:  5.12.4
Hardware:  Desktop

Reproducible: Always

##### Steps to reproduce

1. Start qTox with default theme
2. Change theme to "dark"

##### Observed Behavior
Theme is half changed to dark, half kept with default theme, causing an ugly mix:
![image](https://user-images.githubusercontent.com/10469203/68665958-daa68200-04f7-11ea-89fc-9543532253db.png)

##### Expected Behavior
The entire application is updated to the new theme.

##### Additional Info
Restarting qTox with dark theme selected results in the entire application being correctly styled:
![image](https://user-images.githubusercontent.com/10469203/68666002-ee51e880-04f7-11ea-9d91-c1b3bdae336a.png)

**Comment by TriKriSta** [comment]
I had this problem some time ago. But this problem disappeared for me and I don't know why.
Do you have this problem with Qt 5.13?

**Comment by Chiitoo** [comment]
I do believe the same happens here, though I use the multi-window mode, and closing any open chat window, and reopening it will correct this.

Additionally, the 'Type your message here...' as well as the typing font colour are not updated either.

Qt 5.14 (master) here currently.

**Comment by bodwok** [comment]
Hello,
It seems that QSS are updated correctly if add this code:
`setStyleSheet("");`
`QWidgetList wgts = findChildren<QWidget*>();`
`for (auto x : wgts) {`
`    x->setStyleSheet("");`
`}`
 to the beginning of the function Widget::reloadTheme

**Comment by sudden6** [comment]
#6079 was only a partial fix according to the PR text
