### ISSUE TITLE
Ctrl+Q shortcut doesn't quit qTox when *Close to tray* option is enabled

### ISSUE THREAD

**Issue by vedgy** [qTox/qTox#5925]
##### Brief Description

OS: Manjaro Linux, Xfce
qTox version: 1.16.3
Commit hash: 8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore: 0.2.10
Qt: (build) 5.12.0; (runtime) 5.13.1
Hardware:  Desktop computer

Reproducible: Always

##### Steps to reproduce

1. Enable the *Close to tray* option in General qTox settings.
2. Press Ctrl+Q.

##### Observed Behavior
qTox is hidden to tray.

##### Expected Behavior
qTox exits. This is the behavior I have observed in numerous other applications; I don't recall seeing any other application hidden to tray after triggering the Ctrl+Q shortcut.

##### Additional Info
I've found the following possibly relevant line in the qTox log:
> widget/systemtrayicon.cpp:62 : Debug: Using GTK backend

**Comment by sudden6** [comment]
For me this would be the expected behavior. 

@anthonybilinski what do you think?

**Comment by vedgy** [comment]
@sudden6, I'm surprised you'd expect this. Let me provide two more arguments against the current behavior:
1. Ctrl+**Q** stands for **Quit**, not *Close*.
2. Window managers usually provide a possibly configurable shortcut for closing the active window, e.g. Alt+F4, but they can't provide a shortcut for graceful quitting of the active application. So currently there is no way to quit qTox via a shortcut. As far as I know, the *Exit* tray icon context menu item is the only way to quit qTox when *Close to tray* is enabled.

**Comment by anthonybilinski** [comment]
> @anthonybilinski what do you think?

I don't run with "close to tray" on basically any apps, and only ever hit the ctrl+q shortcut by mistake - but at first thought I'd think it would behave the same as clicking , e.g. close to tray. But my feeling isn't strong here.

> This is the behavior I have observed in numerous other applications; I don't recall seeing any other application hidden to tray after triggering the Ctrl+Q shortcut.

This seems like a strong enough argument by itself to me, if there really is consistent behaviour across apps in this regard, following that makes sense to me.

The one app I often see closed to tray is Steam, which uses the term "Exit" in its menu before it closes to tray. The Quit vs Close vs Exit distinction isn't very clear to me.

**Comment by vedgy** [comment]
See this answer: https://ux.stackexchange.com/a/50896.
Basically *Quit* on Mac corresponds to *Exit* on Windows. Also closing the last app window usually doesn't completely quit the app on Mac (it remains running and visible in the Dock), but *Main menu->Quit* and *Ctrl+Q* do.
_EDIT: in fact, the shortcut is *Cmd+Q* on Mac, but I usually swap Cmd and Ctrl in System Preferences. Anyway, *Cmd+Q* clearly corresponds to the less ubiquitous *Ctrl+Q* shortcut on GNU/Linux and Windows._
I just verified that *Ctrl+Q* completely exits Pidgin, Audacious and Goldendict on my GNU/Linux system when *Close to tray* is enabled.

**Comment by sudden6** [comment]
This new arguments look reasonable to me, seems it needs to be changed then.
