### ISSUE TITLE
Cannot change or save header file?

### ISSUE THREAD

**Issue by HuuThanhHung** [qTox/qTox#5927]
Hello everyone, how can i save the header file when i want to change some things?

**Comment by anthonybilinski** [comment]
Hi, I don't think I understand what you're asking, or what this has to do with qTox, but in a few common editors, you can save a file like this:
```
vim: :w<Enter>
emacs: C-x C-s
ed: w<Enter>
notepad: C-s
```
in some graphical editors, you can click on "File" and then "Save":

![image](https://user-images.githubusercontent.com/10469203/68991245-83fbb980-0811-11ea-9807-af970db173ef.png)

I'll close the issue assuming your question is answered, but if you have further questions, feel free to comment.
