### ISSUE TITLE
settings file should be per profile

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#594]
File auto accept and the friend address database both contain ID-specific information.

**Comment by agilob** [comment]
I would prefer global settings.ini. Why do you think it should be per profile?

**Comment by zetok** [comment]
Because in 1 profile you could set to not use camera/mic, whereas in other you could set it to use camera/mic.
That and many more things.

To that there's issue with supporting multiple profiles running at once in separate qTox instances, where global config setting is IMHO a really bad idea.

**Comment by agilob** [comment]
> To that there's issue with supporting multiple profiles running at once in separate qTox instances, where global config setting is IMHO a really bad idea.

Well... I think it would be a good idea, I don't want to select the same settings many times as I create new profiles. I also want/expect all profile to behave the same way.

**Comment by dubslow** [comment]
@agilob As I said in OP, the settings file contains friend addresses of the profiles in use. This currently means that using qTox on a public computer is not safe, unless the user manually deletes or otherwise sanitizes settings.ini after closing qTox.

Safety on public computers is fairly important IMO; it's the main reason I added a "Delete profile" button to the profiles UI.

**Comment by agilob** [comment]
We can just put friends in separate file and encrypt it with the same pass as toxcore and logs.

**Comment by dubslow** [comment]
That is viable as well.
