### ISSUE TITLE
what kind of routing(Prefix routing/....) and algorithm( Plaxon et al /Tapetry/PastryChord) we use in qtox? 

### ISSUE THREAD

**Issue by HuuThanhHung** [qTox/qTox#5944]
i am find out more about how can we connect in qtox but i don't know what kind of p2p system (Pure Peer-to-peer System or Super-peer Architecture or Structured) and what kind of routing(Prefix routing/....) and algorithm( Plaxon et al /Tapetry/PastryChord) we use in qtox?
Hope you can help me! thank you!

**Comment by anthonybilinski** [comment]
https://github.com/TokTok/c-toxcore are the owners of the library that actually implements the DHT, and you might be able to chat to some devs at #toktok on IRC, but as far as I know:
1) what kind of p2p system: Pure peer-to-peer. The only "special" nodes in the network are bootstrap nodes (which are just regular nodes with a stable address) and TCP relays, which users can opt-in to use if they don't want to use the UDP DHT directly.
2) what kind of routing: I'm not sure I understand this quesiton, toxcore will use whatever default routes are available, unless you set proxy settings explicitly in settings -> advanced in qTox.
3) and algorithm: I think the DHT design is made by Tox, so isn't using a specific implementation.

You might want to check out the spec at https://toktok.ltd/spec.html.

**Comment by sudden6** [comment]
3) AFAIK Tox uses a Kademlia like DHT

**Comment by HuuThanhHung** [comment]
thank you @anthonybilinski and @sudden6
