### ISSUE TITLE
account location

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#5945]
Where is my account located?

**Comment by anthonybilinski** [comment]
Please translate submitted issues to English. You can use a translating service like google translate.

Your account is completely local. There are 3 parts that qTox saves,
<user>.tox - which is your Tox profile, containing your long term key paid.
<user>.db - chat history
<user>.ini, qtox.ini - client settings, check box settings etc.

All three can be found
on Linux: `~/.config/tox`
on Windows: `%APPDATA%\tox\`
on maxOS: `~/Library/'Application Support'/Tox/`

The info is available in the Wiki: Please see https://github.com/qTox/qTox/wiki/Profile
