### ISSUE TITLE
All uploads fail / don't start, download run at about 4 KB / s and mostly fails either

### ISSUE THREAD

**Issue by Christsnatcher** [qTox/qTox#5950]
Hello,

qTox works perfectly for me except when it comes to dealing with up- or downloads. Uploads 
stay either forever in the "Waiting to send state", or fail after some time, downloads are performed with about 4 KB / s and mostly fail either (guess because of timeout).

Interesting is that under Advanced settings the "Enable UDP" option was greyed out for me from the start, despite me opening and forwarding the given port. Of course I granted the client in- and outbound access through my firewall.

OS: Windows 8.1 x64
qTox version: v1.16.3.
Commit hash:  8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.3
Qt:  5.9.6
Hardware:  
i7 3770 @3,4 GHz
16 GB DDR3 RAM
NVIDIA GTX 1050ti 4 GB

Reproducible: Always

##### Steps to reproduce

Drag / drop or select a file to upload or try to download a file provided by a person you talk to.

##### Observed Behavior

Uploads never start, downloads crawl at about 4 KB / s and mostly fail.

##### Expected Behavior

Uploads and downloads working properly (obviously).

------

Find my logfile in attached.

Thank you.

[qtox.zip](https://github.com/qTox/qTox/files/4029379/qtox.zip)

**Comment by sudden6** [comment]
> Interesting is that under Advanced settings the "Enable UDP" option was greyed out for me from the start

Can you make sure that `Proxy Type` is set to `None` (maybe switch to something else and back to `None`)

On first glance I couldn't find anything obviously wrong in the log.

You can also try one of our nightly builds: https://github.com/qTox/qTox-nightly-releases/releases but make sure to backup your profile folder.

**Comment by Christsnatcher** [comment]
Thank you very much! Proxy was set to "None", but chosing another option and setting it back to "None" again then actually made the formerly greyed out UDP connecting option available (I would never have thought of this solution to be honest), and enabling it resolved all my initial up- and download problems, everything runs perfectly fine now, thank you again!

**Comment by sudden6** [comment]
Nice to hear it's working now :)
