### ISSUE TITLE
check if the node in question has all needed fields

### ISSUE THREAD

**Issue by jayzhan211** [qTox/qTox#5951]
https://github.com/qTox/qTox/blob/9765cf5c7212a0207414c09ce159d2548cbcade9/src/net/bootstrapnodeupdater.cpp#L115-L126

line 120 should be `found &= node.contains(key);` instead of `found |= node.contains(key);
`

**Comment by sudden6** [comment]
This indeed looks like a bug, would you submit a PR?

**Comment by sudden6** [comment]
Thanks for the fix!
