### ISSUE TITLE
How change my ToxId by myself?

### ISSUE THREAD

**Issue by AAAnikeev** [qTox/qTox#5956]
##### Brief Description

OS: Astra-linux 1.6(Debian, Linux kernel 4.15.0)
qTox version: Nighty
Commit hash: build without git
toxcore: 0.2.10
Qt: 5.11.0

I want configure my account by settings from other server(such as ToxId and friend list). Is it possible to set toxId by myself, not random?

As i think i only need find the way to set public key, noSpam key i could change in qtox and calculate checksum.

**Comment by sudden6** [comment]
This is not possible. To move a Tox profile (ToxID + friends) from one computer to another you have to move the `*.tox` file. Also note that it is not possible to be online with the same ToxID at the same time with two different devices.
