### ISSUE TITLE
No indication of call being rejected

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#600]
```
"Core: AV ringing with 1 without video"
Core: AV reject
```

↑ Ring to peer, peer rejects call, after that qTox shows ↓
![no wai](https://cloud.githubusercontent.com/assets/3148759/4875119/50fe13bc-6284-11e4-80c5-8f9645d0e0a5.png)

**Comment by zetok** [comment]
There should be something in chat log, showing what actually happened, similar to 

![muh indication](https://cloud.githubusercontent.com/assets/3148759/4849439/bface6c8-6061-11e4-9258-e8b5c6a4e6b8.png)

**Comment by tux3** [comment]
If we start adding messages in the chat about what happens with calls, we might as well do it for more events (not just when someone rejects a call), so let's make another issue for that!

**Comment by zetok** [comment]
k, #601
