### ISSUE TITLE
error: implicit conversion from 'unsigned long' to 'float' changes value from 281474976710655 to 281474976710656

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#6000]
OS: FreeBSD 12 amd64
Rev. ```1.16.3-784-g981ecfca```

```
/wrkdirs/usr/ports/net-im/qTox/work/qTox-1.16.3-784-g981ecfca/src/widget/tool/identicon.cpp:112:75: error: implicit conversion from 'unsigned long' to 'float' changes value from 281474976710655 to 281474976710656 [-Werror,-Wimplicit-int-float-conversion]
           / (((static_cast<uint64_t>(1)) << (8 * IDENTICON_COLOR_BYTES)) - 1);
           ~  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
1 error generated.
```

Log: http://beefy18.nyi.freebsd.org/data/head-amd64-default/p528397_s358971/logs/qTox-1.16.3.784.log (IPv6 URL)

**Comment by anthonybilinski** [comment]
I've created https://github.com/qTox/qTox/pull/6031 to make that conversion explicit. I couldn't repro the warning locally though, including building with clang, so I can't verify that my change will remove the warning. @yurivict could you check that?

p.s. log file is attached here: [qTox-1.16.3.784.log](https://github.com/qTox/qTox/files/4364942/qTox-1.16.3.784.log) for those of us stuck on IPv4

**Comment by yurivict** [comment]
What version of clang did you try?

clang-10 is the version that failed.

**Comment by anthonybilinski** [comment]
Ah I've got 9.0.0 here. I'll try with clang 10.
