### ISSUE TITLE
`ChatLineContent` mentions `Q_INTERFACES(QGraphicsItem)`, but QGraphicsItem is not an interface

### ISSUE THREAD

**Issue by iphydf** [qTox/qTox#6004]
Also, why does it do this? It is the only mention of `Q_INTERFACES` in the entire codebase.

**Comment by anthonybilinski** [comment]
Qt doesn't like removing it:
`AutoMoc: qTox/src/chatlog/chatlinecontent.h:70: Warning: Class ChatLineContent implements the interface QGraphicsItem but does not list it in Q_INTERFACES. qobject_cast to QGraphicsItem will not work!`

I didn't find a very thorough explanation in Qt docs of why we need that, but from https://stackoverflow.com/a/34558992 I think it's a property of `QGraphicsItem`, and giving the ability to `qobject_cast` from a `QGraphicsItem` to a `ChatLineContent`. Even though we don't actually use that particular `qobject_cast`. I think we have to keep it as-is.

**Comment by iphydf** [comment]
Then I don't know what I'm doing wrong, but: `qtox/src/chatlog/chatlinecontent.h:30: Error: Undefined interface`.

**Comment by iphydf** [comment]
Missing include path.
