### ISSUE TITLE
Add notifications in chat about calls

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#601]
In similar way to current implementation of notification about undelivered messages

![muh notification](https://cloud.githubusercontent.com/assets/3148759/4849439/bface6c8-6061-11e4-9258-e8b5c6a4e6b8.png)

**Comment by agilob** [comment]
close pls.

**Comment by zetok** [comment]
There are still no notifications about call being cancelled

**Comment by agilob** [comment]
@zetok you're talking about issue #600 ;)

**Comment by zetok** [comment]
@agilob nope ;)
