### ISSUE TITLE
Remove "std::move" from loadToxData in src/persistence/profile.cpp

### ISSUE THREAD

**Issue by iphydf** [qTox/qTox#6011]
RVO doesn't work when using std::move here.

**Comment by anthonybilinski** [comment]
Due to the conditional return based on runtime data, couldn't RVO not take place?

**Comment by iphydf** [comment]
That's correct. RVO doesn't work regardless in that function, but the std::move prevents it from working even if the code changes. Right now, the move helps nothing at all.
