### ISSUE TITLE
Provide a Virtual Method Anchor for Classes in Headers

### ISSUE THREAD

**Issue by iphydf** [qTox/qTox#6036]
*If a class is defined in a header file and has a vtable (either it has virtual methods or it derives from classes with virtual methods), it must always have at least one out-of-line virtual method in the class. Without this, the compiler will copy the vtable and RTTI into every .o file that #includes the header, bloating .o file sizes and increasing link times.*

Source: http://llvm.org/docs/CodingStandards.html#provide-a-virtual-method-anchor-for-classes-in-headers

In most cases, this is just a matter of adding an explicitly defined destructor and defining it in the .cpp file.

**Comment by PeeyushRawat** [comment]
I would like to give it a try.

**Comment by brandonmosher** [comment]
I'd like to take on this issue if no one else has started yet.

**Comment by anthonybilinski** [comment]
Go for it, AFAIK no one has.
