### ISSUE TITLE
[Windows] qTox crashes upon receiving invite to groupchat

### ISSUE THREAD

**Issue by DanTheBritish** [qTox/qTox#604]
Tested with groupbot, qTox Windows release http://github.com/tux3/qTox/releases/tag/qtox-windows-1414934926.31

**Comment by tux3** [comment]
This could be a dup of #570, but there's no way to tell without a crash report / backtrace.

**Comment by DanTheBritish** [comment]
Is there a way for me to provide one?

**Comment by tux3** [comment]
You can find a log at %APPDATA%/tox/qtox.log, but you can't get a backtrace without running a debug version of qTox throught a debugger.

**Comment by dubslow** [comment]
If we add sufficiently many debug statements, we ought to be able to at least localize the crash. 

Additionally, it could also be related to #394

**Comment by agilob** [comment]
I was just able to reproduce it ONCE (in several times) on Linux:
1. send `invite <number>` to GroupBot

It crashed on my second try with GroupBot

**Comment by dubslow** [comment]
...crashed? Do you have a bt?

**Comment by agilob** [comment]
No, crashed when I run it from KDE launcher :<

**Comment by DanTheBritish** [comment]
I'll find the log later today, currently at work without access to my home desktop

**Comment by agilob** [comment]
got it!

```
"Core: Group invite by 3"
"Trying to join groupchat invite by friend 3"
"Core: Group namelist change 0:0 0"
"Core: Group namelist change 0:0 2"
Widget::onGroupNamelistChanged: Group not found, creating it
"Core: Group namelist change 0:1 0"
qtox: malloc.c:2904: __libc_malloc: Assertion `!victim || ((((mchunkptr)((char*)(victim) - 2*(sizeof(size_t)))))->size & 0x2) || ar_ptr == (((((mchunkptr)((char*)(victim) - 2*(sizeof(size_t)))))->size & 0x4) ? ((heap_info *) ((unsigned long) (((mchunkptr)((char*)(victim) - 2*(sizeof(size_t))))) & ~((2 * (4 * 1024 * 1024 * sizeof(long))) - 1)))->ar_ptr : &main_arena)' failed.
[1]    15374 abort (core dumped)  ./qtox
```

dmesg:

``````
[520936.664979] QThread[5622]: segfault at 930 ip 00007f91d30d47a0 sp 00007f91a30f86d8 error 4 in libtoxcore.so.0.0.0[7f91d30bb000+2f000]
[521802.430123] QThread[8385]: segfault at 930 ip 00007ffca4dcc7a0 sp 00007ffc754b67c8 error 4 in libtoxcore.so.0.0.0[7ffca4db3000+2f000]
[522195.562580] QThread[11808]: segfault at 58 ip 00007f32f7d7e6c4 sp 00007f32cb0f86e0 error 4 in libQt5Core.so.5.3.2[7f32f7ac6000+4c0000]
[538540.648297] ptrace of pid 17571 was attempted by: gdb (pid 17622)
[538759.279934] qtox[17923]: segfault at 32 ip 00007f09c4530a8d sp 00007fffbb2868f0 error 4 in libQt5Core.so.5.3.2[7f09c4274000+4c0000]```
``````

**Comment by dubslow** [comment]
Any bt?

**Comment by agilob** [comment]
No, this time I run qtox from terminal.

**Comment by zetok** [comment]
@agilob why won't you debug core, since it was dumped?
`gdb $(which qtox) ur_core`

**Comment by agilob** [comment]
Because:
1. wasn't hunting for that bug
2. it happened when I wasn't in terminal (run from KDE - Alt+F2)

**Comment by DanTheBritish** [comment]
This is all that's in the log https://gist.github.com/LapFox/5ff4bb1645162bbeda1f

**Comment by dubslow** [comment]
LapFox that's a crash log? Because if so it's crashing after joining the groupchat

**Comment by DanTheBritish** [comment]
Yup, that's all there is.

**Comment by DanTheBritish** [comment]
Derp. Looked into it, and turns out it's because qTox started using my uTox ID, because the profile directory had changed. Turns out sending a group invite to yourself isn't a good idea.

Tested with a different Tox ID and it works fine on the same build, and on the latest.
