### ISSUE TITLE
"bitbucket.org/kardianos/osext" is gone, replace with "github.com/kardianos/osext"

### ISSUE THREAD

**Issue by iphydf** [qTox/qTox#6043]
In osx/updater/updater.go, we're referencing an ancient Go package, which has moved to a new location. Right now, the updater doesn't build (should we test this on travis?).

**Comment by sudden6** [comment]
I pretty sure this updater is dead code and can be removed. qTox doesn't automatically update anymore, but displays a notification instead.

**Comment by theanshm** [comment]
I would like to work on this issue of this issue is open to work on. As I am new to open source contributions I might need a push in right direction but I am willing to learn.

**Comment by enkeyz** [comment]
Close this. It's fixed.

**Comment by anthonybilinski** [comment]
Agreed, updated in 6d99e9099f2a5d013a915b334d5d41b5f8bdfb9d and then removed fully in 8768f6be3795d19a108432f56d0a691568364c07.
