### ISSUE TITLE
"Update available" is illuminated when the git-describe version is ahead of the latest released version

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#6049]
Here https://github.com/qTox/qTox/blob/master/src/net/updatecheck.cpp#L84 it simply compares strings. ```git describe``` returns ```1.16.3-784-g981ecfca``` and it illuminates "Update available", comparing ```1.16.3-784-g981ecfca``` against the "latest" version of ```1.16.3```.

**Comment by anthonybilinski** [comment]
The code you linked matches only the version part of the git describe using regex, and compares that against the latest release. Have you actually seen `1.16.3-784-g981ecfca` trigger "Update available"? Currently I see it handled correctly:
![image](https://user-images.githubusercontent.com/10469203/77795766-562e4900-702b-11ea-9f64-d7d467887030.png)

**Comment by yurivict** [comment]
Indeed. The version string passed to qTox wasn't exactly as Git returned it.


Thanks!
