### ISSUE TITLE
Links to nightly builds for Windows are broken

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#6095]
The links in our README.md for Windows nightly builds are 404ing. Thanks @myphs for reporting.

**Comment by ghost** [comment]
The OS X nightly build link is broken, too.

**Comment by Chiitoo** [comment]
I confirmed them not working at the time of the report as well, but they all seem to work now.

The 'AppImage nightly' seems to not start a download, but instead links to the tag page, but I guess this is intended.

**Comment by sudden6** [comment]
> I confirmed them not working at the time of the report as well, but they all seem to work now.

Confirmed too, will close.

> The 'AppImage nightly' seems to not start a download, but instead links to the tag page, but I guess this is intended.

Yes, since AppImage files contain the commit hash in the filename it's not possible to link to them.
