### ISSUE TITLE
Video call see same person on both ends

### ISSUE THREAD

**Issue by joshatt** [qTox/qTox#6096]
##### Brief Description

OS: Windows 7
qTox version: (version numbers in menu `Settings → About`)  1.16.3

Reproducible: Always 

A year ago I installed Antox on my android phone, tried to communicate with Antidote iphone, it did not work well, in most cases my status keeps offline, and other issues when trying to set up audio or video call. 
Anyway, I dropped it there.

Today I did some more tests. I installed qtox on windows and applied another account in there. And Antox in android is up-to-date. By enabling UDP, it seemed to have solved my always offline issue in Antox android? But there comes this new issue with video call - both android and computer see the person with android phone, instead of each other, and, in computer the image turned 90 degree.

**Comment by sudden6** [comment]
Try using this Android client to test: https://github.com/zoff99/ToxAndroidRefImpl

Antox is horribly outdated and not maintained anymore.

**Comment by joshatt** [comment]
> Try using this Android client to test: https://github.com/zoff99/ToxAndroidRefImpl
> 
> Antox is horribly outdated and not maintained anymore.

Thanks for your help.
