### ISSUE TITLE
Group disapears

### ISSUE THREAD

**Issue by PARoby** [qTox/qTox#6098]
Hey,

I'm not sure if it is normal but when I quit and I come back on my account all of the groups I was in disapeared. Is it normal and is there a way to make the groups persist?

Thanks in advance

**Comment by sudden6** [comment]
Try a nightly build, the last release doesn't have support for persistent groups.

**Comment by anthonybilinski** [comment]
Groups weren't persistent previously, but persistent groups are implemented as of the latest release https://github.com/qTox/qTox/releases/tag/v1.17.2 which came out yesterday. Please update, if you still experience the issue we can re-open this ticket.
