### ISSUE TITLE
utox is finished ?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#610]
hi 

after reading the domain name http://utoxisfinished.info, I want to ask if it's really that utox  development is finished ?

**Comment by tux3** [comment]
The domain name was registered as a joke, don't worry it doesn't mean anything!

**Comment by agilob** [comment]
@tux3 do you have any information if µTox is not dead?

**Comment by dubslow** [comment]
Its main dev, @notsecure, is a student and has been focusing on school since the end of summer. Presumably he'll be active over winter break or worst case next summer.

**Comment by ghost** [comment]
can't help, but whats funny about it? I think devs shouldn't pi*\* on someone else project...

**Comment by TheLastProject** [comment]
@Linuxhippy Don't worry, uTox and qTox developers don't actually attack each other. They're just making playful jokes, laughing about it together.

**Comment by tux3** [comment]
@Linuxhippy Like @TheLastProject said, we're not actually fighting each other,  it's friendly competition at most :)

uTox is a perfectly fine and lightweight client, it's not dead and I don't want it to die. If it works for you, then great!
You should try to assume good faith, of course we're not "pissing" on each other's projects. We're working towards the same goal, after all !

**Comment by GrayHatter** [comment]
/me unzips

http://qtox.rip

you can thank @nurupo for bringing this thread to my attention.

(Just playin' @tux3, you know I love ya mate!)
