### ISSUE TITLE
Update check should not notify if local version is greater than latest release

### ISSUE THREAD

**Issue by hart0** [qTox/qTox#6112]
##### Brief Description

OS: Fedora
qTox version: v1.17.1-181-g00d08d98
toxcore:  0.2.11
Qt:  5.13.12

Reproducible: Always

##### Observed Behavior

I noticed that there is a new feature that tries to show when an update is available. I built the newest github master version earlier today and immediately after launching it, it's showing the green colored settings cog and the about section showing a green "Update available" button even though the build is the newest.

[Screenshot](https://i.imgur.com/yjLyxq4.png)

Clicking the "Update available" button takes you to the github release page which lists version 1.16.3 as the newest release which is from 2018.

##### Expected Behavior
For it to not show "Update available" when you are running the newest release/a build newer than the current release.

Edit: I can see why it's happening, and why it probably won't be an issue for very long. It looks like it's [comparing](https://github.com/qTox/qTox/blob/00d08d98874d18bbee007c4da295515e0cb8a7c8/src/net/updatecheck.cpp#L84) the version of the program against the last release (which would both have been 1.16.3.x up until fairly recently) but since something in the program got changed to 1.17 and the 1.17 release hasn't happened yet or isn't set as the "latest release" on github, they aren't equal any more.

Instead of checking if latestVersion and curVer are equal or not, maybe it would be better to see if latestVersion is a higher number or not.

**Comment by anthonybilinski** [comment]
>Edit: I can see why it's happening, and why it probably won't be an issue for very long. It looks like it's comparing the version of the program against the last release (which would both have been 1.16.3.x up until fairly recently) but since something in the program got changed to 1.17 and the 1.17 release hasn't happened yet or isn't set as the "latest release" on github, they aren't equal any more.

Exactly right, v1.17.0 and v1.17.1 are in kind of half-released states. They aren't releases yet on github because our release build process failed, but their git tags were still pushed. Because of this our update check sees that you're running v1.17.1, and that the latest release is v1.16.3, sees they aren't equal, and says an update is available.

> Instead of checking if latestVersion and curVer are equal or not, maybe it would be better to see if latestVersion is a higher number or not.

True that that would fix this, though in general we should never really have versions higher than our latest release. We can still improve that check in the future.

**Comment by anthonybilinski** [comment]
This should be resolved now that v1.17.2 is out. I'll update the ticket to improve the update notification anyway.

**Comment by anthonybilinski** [comment]
Oops we are correctly already only checking for published releases and no tags. The issue is that our tags are pushed before our release is published, which leads to a gap where the compile version is higher than remote, like you experienced.
