### ISSUE TITLE
Icon is stretched in gnome 3 window bar in top left

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#6121]
##### Brief Description

OS: Ubuntu 20.04
qTox version: v1.17.2+
Commit hash:  82547263
toxcore:  v0.2.10
Qt:  v5.12.8

Reproducible: Always

##### Observed Behavior
1. Icon on left bar, in tray top right, and in application search are all the right aspect ratio:
![image](https://user-images.githubusercontent.com/10469203/80762983-689c1680-8af2-11ea-9b1c-26f205e28729.png)
![image](https://user-images.githubusercontent.com/10469203/80762973-633ecc00-8af2-11ea-9040-62f4b4d73808.png)
![image](https://user-images.githubusercontent.com/10469203/80762999-6df96100-8af2-11ea-9913-6d3cb856ef9e.png)
2. Icon in the Window selector top left is stretched:
![image](https://user-images.githubusercontent.com/10469203/80763026-7ce01380-8af2-11ea-91b9-f425c38c96cb.png)

**Comment by Hasshu** [comment]
It's a GNOME [issue](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2578).

**Comment by anthonybilinski** [comment]
Aha, thanks for the link. Guess we'll just wait until it's fixed upstream.

**Comment by warisb** [comment]
FWIW, I'm using GNOME 3.36.8 on Ubuntu 20.04 and I'm not seeing the issue.
![image](https://user-images.githubusercontent.com/29346402/108612316-54d0e200-739c-11eb-8e3d-48785165e313.png)

**Comment by anthonybilinski** [comment]
Nice, fixed on Ubuntu 20.10 too, closing.
