### ISSUE TITLE
qTox Group chats: saving history log.

### ISSUE THREAD

**Issue by TerminalHash** [qTox/qTox#6127]
Hello!
When will there finally be a normal saving and loading of group chat history? The fact that their work is repaired is, of course, good, but still I would like to be fully working.

**Comment by TerminalHash** [comment]
When you start the client, I note.

**Comment by anthonybilinski** [comment]
#5452 is tracking group history. #5454 was created to start adding it, but is old and out of date. Finishing group history is planned for the next minor release of qTox: https://github.com/qTox/qTox/milestone/25 which is planned for September.

I'll close this issue since it's a duplicate of #5452.
