### ISSUE TITLE
Audio notifications can't play

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#6144]
##### Brief Description
OS: Ubuntu 20.04
qTox version: v1.17.2+
Commit hash: 14571abaa30c80f8ebaae33c22c9f500cad7242a
toxcore:  v0.2.12
Qt:  5.12.8

Reproducible: Always

##### Steps to reproduce

1. Receive a message without qTox in focus

##### Observed Behavior
1. No audio notification is played.
```
[07:25:24.871 UTC] ../audio/src/backend/openal.cpp:480 : Debug: Trying to open non-existent sound file
```
is logged.

Ping @sudden6, regressed since https://github.com/qTox/qTox/pull/6119

**Comment by sudden6** [comment]
Interesting, I see nothing obvious in that commit that could cause this behavior.

**Comment by anthonybilinski** [comment]
Maybe splitting the audio resources into their own module caused them not to be included by Qt in the qTox binary?

**Comment by sudden6** [comment]
Then all other sounds wouldn't work either, did the ringtone work for you?

**Comment by anthonybilinski** [comment]
Just tested on master tip, ring tones also don't work with the same error:
```
[23:52:19.513 UTC] ../audio/src/backend/openal.cpp:480 : Debug: Trying to open non-existent sound file
```
