### ISSUE TITLE
copy/paste status message

### ISSUE THREAD

**Issue by sergio49** [qTox/qTox#6146]
Hi,
When I want to copy and paste (with Ctrl+V) a status message, the paste is done in the "search contact" input area, not in the status input area.
Using right click + paste works.

OS: Linux (Ubuntu 19.10)  
qTox version: 1.17.2  
Commit hash:  
toxcore:  0.2.11
Qt:  
…

Reproducible: Always

copy text from a text file and paste it with Ctrl+V in the status message zone

##### Observed Behavior
text is past under, in the search contact zone

##### Expected Behavior
text should be paste in the status message zone

**Comment by isav83** [comment]
>Using right click + paste works.

Do you activate status field (using left or right click) before paste with Ctrl+V?

**Comment by anthonybilinski** [comment]
I can't reproduce this with v1.17.6. Selecting the status message box and hitting ctrl+v pastes in the status box, ctrl+z undoes the paste, selecting the text in the status box first then pasting it overwrites it all with the paste. Everything seems to be working as expected.

Without selecting the status field first the text is pasted to the chat box which is intended, so going to close as not reproducible.
