### ISSUE TITLE
[Feature request] improve design of proxy support

### ISSUE THREAD

**Issue by Nokia808** [qTox/qTox#6150]
Hi. I would like to suggest the following to improve design for proxy support GUI:
Make 4 available choices:

1) none,
2) Tor,
3) i2p,
4) custom

This will make it easier for users to set Tor/i2p by make built-in configuration for Tor/i2p (I mean built-in preconfigured setting to Tor system package / i2p or i2pd daemon that should be already installed by user).

Custom [option 4] will allow user to set other Internet proxy or local non-internet network.

I saw this design in "Privacy Browser" of Android, & liked it. Review kindly this request & see if it is useful to qTox or not.

Best.

**Comment by sudden6** [comment]
Adding the default settings for Tor doesn't look too complicated IMO. I don't know if anyone ever ran Tox over I2P though?

**Comment by Nokia808** [comment]
@sudden6 
Thank you too much for your nice replay!
Regarding i2p network, it is too much better than Tor network for following causes:

1) it is fully  decentralized, being a peer-to-peer project, while Tor network is centralized;
2) i2p can be used in 2 mode: with outproxy disabled & with outproxy enabled. With outproxy disabled it will achieved too much stronger security level than default Internet or even Tor network usage;
3) i2p is more heavily encrypted than Tor communication .....

From the point (2) & (3), run qTox (or broadly speaking: making communication via Tox protocol) over i2p with outproxy disabled this will mean extra level of security for outstanding level .....

I wish you will take this in mind & including i2p option in your future version ......

Best.

**Comment by Nokia808** [comment]
I need to remember here, regarding Tor network, about the following:
Tor network does not support any udp connection (while i2p already supporting). So that if you add preconfigured Tor proxy setting, then it's activation should lead automatically to disabling udp connection in advanced setting of qTox ....... And it will be very cute if the original udp setting that was existing just before activating Tor selection, will be return as it was before when user deselect Tor: for ex if udp was enabled before selecting Tor then it should be enabled again when user deselect Tor & if udp was disabled before selecting Tor then it should be remain disabled when user deselect Tor .....

**Comment by Nokia808** [comment]
@sudden6 
Kindly, can you join the following issue that I already opened on i2pd repository:
https://github.com/PurpleI2P/i2pd/issues/1521

They asking about "How instances communicate between each other" ?

We have already "Retroshare" do this & have a setting ..... But qTox, they not know about it's use over i2p (which is certainly possible) & for that need data ......

**Comment by sudden6** [comment]
@Nokia808 Sorry, I don't have time to look into whether Tox works over I2P, you're on your own on that one. All the options that c-toxcore provides are already exposed via the existing GUI, so IF(very big if) I2P and Tox can work together you should be able to set it up.

The change to add a specific setting for Tor on the other hand is only a cosmetic one to add a preset.

**Comment by Nokia808** [comment]
@sudden6 
Dear just look for last 3 comments on https://github.com/PurpleI2P/i2pd/issues/1521
I was confused between what Retroshare done when run over Tor/i2p & what qTox need from such connection. qTox need Tor just to hide real user IP not to run COMPLETELY HIDDEN WITHIN Tor to gain additional layer of security .... Moreover, qTox (& Retroshare itself) have no any need to Tor or i2p to overcome a firewall block because they are both SERVERLESS.

Also, "qTox (and Tox itself) somehow used bootstrap nodes to make connections between users, but that need investigation and support from tox developers, who will create I2P nodes available 24/7 and add them to bootstrap."

From all this, I think it is now the time to close this request because it is none sense at this stage of Tox development level (no bootstrap within i2p network itself), & also because all what user need to set qTox run over Tor network (to nerely hide heir/his real IP) is:
proxy type: SOCKS
address: 127.0.0.1
port: 9050

Sorry for bothering you all this time with this request !

**Comment by Nokia808** [comment]
@sudden6 
Dear I forgot the problem of udp checked by default in "advanced" tab. What happened if user set Tor proxy & forget to disable udp ? If this make problem, then we should re-open this issue because there will be rational for preconfigured built-in Tor setting that enabling it will disable udp automatically ...

**Comment by sudden6** [comment]
IIRC the udp box should be unchecked automatically when you select a proxy type other than `None`.

**Comment by Nokia808** [comment]
@sudden6 
This is very good ! I was afraid that I need to re-open this issue again just for this. Now it is clear that every thing is okay & well designed & no need to re-open this issue.
