### ISSUE TITLE
Weird Green Lines Appearing On Affected User's Windows Surface Tablet When Attempting To Display My Debian 10 Buster Laptop's Webcam

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#6155]
##### Brief Description

OS: Windows / OS X / Linux (include version and/or distro): My Machine: Debian 10 Buster on Thinkpad T440s computer which runs QTox just fine, Affected User's Machine: Windows 10 on Windows Surface Tablet
qTox version: (version numbers in menu `Settings → About`): v1.16.3-2-debian on Debian laptop, latest version for Windows 10 executable installer (not sure what they installed but they pulled the latest version as of May 24, 2020 from the QTox website)
Commit hash:  
toxcore:  
Qt:  
…

Reproducible: Always

* Note: I tried doing multiple video calls to see if it was an issue with my settings.

What's weird is that I'm able to see my webcam under the Audio/Video settings just fine.

##### Steps to reproduce

1. Make a phone call from Debian 10 Buster laptop to a user with Microsoft Surface tablet running QTox.
2. Observe on Debian laptop that I'm able to see my webcam, and the other user's webcam just fine.
3. However, on the affected Windows Surface Tablet, the affected user is seeing weird green bars instead of my webcam.

##### Observed Behavior

Same as mentioned in "Steps to reproduce"

##### Expected Behavior

I would expect that since I'm able to view both webcams just fine on my Debian laptop that the affected Microsoft Surface tablet should be able to see the same.

##### Additional Info
(links, images, etc go here)

NOTE: I have blocked out faces because of respect for myself and the person I was chatting with.

Screenshot from affected MS Surface tablet that shows they were able to see their own webcam, but saw my webcam as a series of weird green gradient lines.

Also for reference, the blocked out image is the affected user's webcam on the MS Surface tablet while my webcam is shown as the green gradient lines:

![Debian Laptop Screenshot](https://user-images.githubusercontent.com/28350451/82763173-5c426b00-9dcb-11ea-82e2-83575840967b.jpeg)

Screenshot from my Debian Buster 10 laptop which shows that I was able to view my own webcam as well as the other person's webcam from their MS Surface tablet:

![Windows Surface Tablet Screenshot](https://user-images.githubusercontent.com/28350451/82763177-63697900-9dcb-11ea-94d6-c1b5fcd24ef7.jpeg)

----

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA%\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by sudden6** [comment]
@SBanya You are using qTox v1.16.3 which is very outdated and has known video bugs, try to get the newest release(https://github.com/qTox/qTox/releases/tag/v1.17.2) and I think this should be solved.

**Comment by ghost** [comment]
@sudden6 Ok, thanks for letting me know.

Yet another reason why Debian's 'apt' package manager kind of sucks in that regards, though I do like the overall system stability. This is the second time this has happened (first was 'youtube-dl' being outdated).

Thanks for letting me know.

I have to now decide whether or not the 'flatpak' or AppImage route is the right way for an easy installation as I'm more inclined for the easier installation route so I don't have to manually remove all of the files in case building from source doesn't work out too well.

Will update this bug ticket after a re-test with the latest version, 1.17.2.

**Comment by sudden6** [comment]
I'd recommend the AppImage then, as the flatpak has a known bug with detecting video devices at the moment.

**Comment by ghost** [comment]
Thanks, that worked for me.
