### ISSUE TITLE
qtox isn't startup

### ISSUE THREAD

**Issue by ybibaev** [qTox/qTox#616]
crash at start with errror: 'qtox: error while loading shared libraries: libopencv_core.so.2.3: cannot open shared object file: No such file or directory'

**Comment by dubslow** [comment]
Where are you getting your binary? 2.4 should be statically linked.

**Comment by ybibaev** [comment]
from http://repo.tox.im/deb/ testing main

**Comment by dubslow** [comment]
What distro are you using? @stqism

**Comment by ybibaev** [comment]
ubuntu 14.04

**Comment by agilob** [comment]
One more person reported it today on irc, ubuntu 14.04 32 bits. Maybe we consider static builds with opencv2.4?

**Comment by stqism** [comment]
This is an i386 issue @urras was supposed to fix. But it looks like it's still an issue so I'll do it myself. 

The problem with statically linking is that in no situation does static opencv with Qt support compile, so the current workaround is to build against 2.4 and in the future provide a workaround package for stable. (funny enough if you ln -s 2.3 on stable to 2.4 and force install the package it launches perfectly fine.)

**Comment by urras** [comment]
Should be working now, sorry for the inconvenience.
