### ISSUE TITLE
[Question] Does Fedora RPMFusion package offical from you ?

### ISSUE THREAD

**Issue by Nokia808** [qTox/qTox#6162]
Hi. JUst I need to know if qTox .rpm packages that available for Fedora users from RPMFusion repositories are official made by you or not ? 

I noticed that they are not updated till now to the last version of qTox.

I'm currently on flatpak package but no camera & this may continue till August or even more ...

Best.

**Comment by sudden6** [comment]
No it's not made by us, none of the packages in the distros are. But some maintainers occasionally check in here when they report bugs from their distros.

**Comment by Nokia808** [comment]
@sudden6 
Thank you. I will close issue. But only one further question: why on this repository you recommend RPMFusion package over flatpak in-spite the fact that flatpak on FlatHub is official package made by you ?

**Comment by sudden6** [comment]
Because the "normal" way to install software on linux systems used to be via packages. qTox is older than Flatpak became popular and this just stayed :)

**Comment by Nokia808** [comment]
@sudden6 
So, in real flatpak package is better, being up to date & more secure, as long as it is made by developer(s) ...

**Comment by sudden6** [comment]
Neither of them is more secure I'd say, but yes Flatpak is usually more up to date, but native packages are usually more integrated in the distro. Depends on what you want in the end.
