### ISSUE TITLE
Feature Request: Gaming Overlay

### ISSUE THREAD

**Issue by trymeouteh** [qTox/qTox#6172]
It will be cool if it was possible to have a overlay on Windows and Linux for gaming. This way you can send messages, make calls and end calls within a game.

**Comment by anthonybilinski** [comment]
This would be a nice to have, but I don't think we have the dev bandwidth to do this anytime in the foreseeable future, since we're focussing more on fixing bugs and core features. I'll close this for now, but it could be revisited in the more distant future.
