### ISSUE TITLE
Feature Request: Remote Control For Calls

### ISSUE THREAD

**Issue by trymeouteh** [qTox/qTox#6173]
A cool feature will be the ability to answer a call, make a call or end a call on qTox using your phone. I know this will require maybe working with AnTox. This will be handy if you are in a game and you want to answer the call on your computer and not your phone.

https://github.com/Antox/Antox/issues/524

**Comment by skeletonium** [comment]
@trymeouteh
qTox would need some way to authorize and securely communicate with the Tox phone client profile, informing it of incoming calls and giving it permission to accept them. If more permissions were added as well, it could be one way to implement partial multidevice support. Tox in general still lacks proper multidevice support (things like running the same profile on different devices at the same time). But that seems to be mostly an upstream issue.

It would of course require working with the Android client and its support of this feature as well. Keep in mind however that Antox is not actively developed anymore. See https://github.com/Antox/Antox/issues/523.

Other than [TRIfA](https://github.com/zoff99/ToxAndroidRefImpl/tree/zoff99/dev003a), which is well maintained and still in development, another promising Android client for the future is [aTox](https://github.com/evilcorpltd/aTox). It's stable and seems to have a nice UI, but doesn't support all the features that TRIfA does.

> This will be handy if you are in a game and you want to answer the call on your computer and not your phone.

The use case seems a bit limited, something like https://github.com/qTox/qTox/issues/6172  would probably be easier, although I'm not sure how would the implementation work. I don't think this feature will be on the roadmap that soon, though, with much else still being in development.

**Comment by anthonybilinski** [comment]
I agree overall with what @skeletonium said above.

This would require a custom protocol between specific mobile apps, which would be a lot of work for what seems like a niche feature to me.

Multidevice support I think should come first and would also require a custom protocol. Once that's working (which may take years) this can be reconsidered to build on it, but also #6172 seems like it accomplishes a pretty similar thing with a more standard UI.

For the foreseeable future we're focussing on more core features and we have limited dev bandwidth. I'll close this for now, but it could be reconsidered later.
