### ISSUE TITLE
Is qtox-win.pkg.tox.chat still being used?

### ISSUE THREAD

**Issue by nurupo** [qTox/qTox#6177]
Was going over tox.chat's DNS records dong some clean up and saw `qtox-win.pkg.tox.chat`. Is it okay to remove that dns record? To my knowledge the server itself has been decommissioned (by oranges?) for long time now and is no longer used by qTox. I still have to ask, just in case, since you guys know better what is used and what is not.

**Comment by sudden6** [comment]
Yes you can remove it.

**Comment by nurupo** [comment]
Removed.
