### ISSUE TITLE
QIODevice::write: device not open [Mac OS X 10.10]

### ISSUE THREAD

**Issue by szymonlopaciuk** [qTox/qTox#618]
I haven't used it before the update of my OS X, so I'm not sure if that's the reason, but I can't think of any other. The program crashes on startup with a bunch of "QIODevice::write: device not open" lines, and then segfaults.

Whole crash report:
https://gist.github.com/szymciolop/aac2a0d0fc25ea3ad43e

**Comment by dubslow** [comment]
That's very interesting, it seems that qtox can't open its log file... I can add a workaround when I get back to my computer.

**Comment by dubslow** [comment]
I guess this should be closed, because it no longer crashes at least
