### ISSUE TITLE
Firejail qTox with Nvidia Driver (or multiple versions of libGL.so)

### ISSUE THREAD

**Issue by ParadiseStudios** [qTox/qTox#6188]
##### Brief Description

OS: Linux Buster
qTox version: qTox version v1.16.3-2-debian
Commit hash: build without git
toxcore: 0.2.9
Qt: 5.11.3

Reproducible: Always

##### Steps to reproduce

1. Install firejail version 0.9.58.2
2. Run firejail qtox

##### Observed Behavior
```
Reading profile /etc/firejail/qtox.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Warning: networking feature is disabled in Firejail configuration file
Parent pid 9937, child pid 9938
Warning: skipping pki for private /etc
Warning: skipping crypto-policies for private /etc
Private /etc installed in 58.12 ms
1 program installed in 18.40 ms
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Blacklist violations are logged to syslog
Child process initialized in 153.84 ms
qtox: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory
Parent is shutting down, bye...
```
##### Fix
```
sudo nano /etc/firejail/qtox.profile
```

> Add alternatives to the private-etc line.

https://github.com/netblue30/firejail/issues/2399#issuecomment-464462779

##### Additional Info
```
nvidia-detect
Detected NVIDIA GPUs:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation G92 [GeForce 9600 GSO] [10de:0610] (rev a2)

Checking card:  NVIDIA Corporation G92 [GeForce 9600 GSO] (rev a2)
Your card is only supported up to the 340 legacy drivers series.
It is recommended to install the
    nvidia-legacy-340xx-driver
package.
```

```
grep "X Driver" /var/log/Xorg.0.log
[   148.359] (II) NVIDIA dlloader X Driver  340.108  Wed Dec 11 14:06:00 PST 2019
```

**Comment by Diadlo** [comment]
It looks like it's an issue on firejail, isn't it? Probably qTox has nothing to do here

**Comment by ParadiseStudios** [comment]
You're right. I wasn't sure where to post it since it deals with a Firejail qTox profile. I just wanted others who were having the same problem to be able to find the solution. Should I move it to https://github.com/netblue30/firejail/?

**Comment by Diadlo** [comment]
I read a discussion on the linked issue and it looks like the problem has to be solved. `alternatives` already added in [qtox profile](https://github.com/netblue30/firejail/blob/master/etc/profile-m-z/qtox.profile#L46)). Maybe you use the old version of firejail? In any case, I think it's better to discuss with firejail developers about details.
