### ISSUE TITLE
toxme

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#6189]
##### Brief When I try to log in to toxme, after a moment I get an error in toxme. The server can't handle toxme. What could be happening?

OS: Windows 10 (10.0)
qTox version: v1.16.3
Commit hash: 8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore: 0.2.3
Qt: 5.9.6
Hardware: 
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. 
2. 
3. …

##### Additional Info
(links, images, etc go here)

----

More information on how to write good bug reports in the wiki: https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by anthonybilinski** [comment]
The server running toxme.io was taken offline by its host. In qTox version 1.17.0, toxme support was removed from qTox. You can grab the latest release here: https://github.com/qTox/qTox/releases/tag/v1.17.2 which will remove that option from UI, but we don't see toxme support coming back any time soon.
