### ISSUE TITLE
Feature Update - Seen status.

### ISSUE THREAD

**Issue by dummypimp** [qTox/qTox#6206]
#@##### Brief Description

OS: Windows / OS X / Linux (include version and/or distro)  
qTox version: (version numbers in menu `Settings → About`)  
Commit hash:  
toxcore:  
Qt:  
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. 
2. 
3. …

##### Additional Info
(links, images, etc go here)

----

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA%\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by sudden6** [comment]
Please describe in more detail what you want.

**Comment by anthonybilinski** [comment]
It sounds like they're asking for read receipts for messages, which would be a duplicate of https://github.com/qTox/qTox/issues/1083. They're not supported by toxcore, so wouldn't be easy to add, but could maybe be done using toxext in the future.

**Comment by sudden6** [comment]
@anthonybilinski I couldn't read that from their description, but lets close as duplicate of #1083
