### ISSUE TITLE
qTox horribly slows down when resizing contact list

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#622]
http://a.pomf.se/toforq.webm

**Comment by dubslow** [comment]
gg.

**Comment by tux3** [comment]
@krepa098's new chat form would probably help with that.

It lags because rendering the chat is just that expensive.

**Comment by krepa098** [comment]
Yes, that's what I'm currently working on. It's quite tricky as it requires cheating in one way or the other.

EDIT:
It's not actually slow because of the rendering. It's slow because it has to recalculate the entire text layout.

**Comment by msteinbeck** [comment]
I tried the current qTox version with Windows 7 and can't reproduce that laggy behavior. Maybe it was fixed?? If so, plz close this issue

**Comment by tux3** [comment]
@retuxx have you tried with a _lot_ of text in the chat form ?

**Comment by msteinbeck** [comment]
> have you tried with a lot of text in the chat form ?

I tested with about 100 lines. If one has thousands of lines its going to be very slow

**Comment by dubslow** [comment]
qTox needs to be able to handle 10s of 1000s of lines without problem.

**Comment by msteinbeck** [comment]
> qTox needs to be able to handle 10s of 1000s of lines without problem.

Yes

> It's not actually slow because of the rendering. It's slow because it has to recalculate the entire text layout.

Any ideas, progress here?

**Comment by dubslow** [comment]
Have you tried the ChatLog v3 branch? It's significantly better from what I hear.

**Comment by tux3** [comment]
I believe this is fixed by the new chat form.
