### ISSUE TITLE
Add SystemMessages to IChatLog, treat them like other chat messages

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#6222]
##### Brief Description

This issue depends on https://github.com/qTox/qTox/issues/6221 so that system messages can have a `ChatLogIdx` and be referenced like other chat messages.

To allow for the view class ChatLog (not an implementer of IChatLog, confusing, I know), to be able to dynamically remove messages and then request messages from IChatLog to re-populate its view when the user scrolls, IChatLog needs to be able to provide all messages that ChatLog would need to display, which includes system messages.

**Comment by sphaerophoria** [comment]
Alright I've got a mostly finished implementation that seems pretty straightforward on top of #6290.

I wanted to implement something to prove that the schema in #6290 was sane and it seems fine. No system messages currently use more than 2 arguments, so 4 arguments in the schema may be overkill, but some null blobs never hurt anybody.

Implementation is up at https://github.com/sphaerophoria/qTox/tree/6222-system-messages-history

Quick demo of the feature at 
https://user-images.githubusercontent.com/1069811/105949814-30dee280-6022-11eb-81dc-ea8b370124cf.mp4

And a screenshot of the system messages table

![image](https://user-images.githubusercontent.com/1069811/105949918-59ff7300-6022-11eb-8015-7d6e2e57382f.png)

I'm pretty happy with this. Will file a PR after finding a home for the SystemMessages type and getting #6290 merged

**Comment by anthonybilinski** [comment]
Completed by https://github.com/qTox/qTox/pull/6311
