### ISSUE TITLE
Translate file dialog

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#623]
File dialog is not translated. Cut-Copy-Paste menu is also not translated.

**Comment by agilob** [comment]
@suhr which file dialog? Do you mean not translated or untranslatable? 

---

Some menus are provided by operating system:

![menu](https://cloud.githubusercontent.com/assets/2544251/4910191/2c305596-647c-11e4-9c68-f6c912a01668.png)
![menu1](https://cloud.githubusercontent.com/assets/2544251/4910202/53d89964-647c-11e4-9b34-34f1fc807e14.png)

and are not directly translatable by Qt application. I believe we do not want to overwrite and translate them. If that's what you mean.

**Comment by suhr** [comment]
> which file dialog?

Choosing file to send, profile to load/save.

> Some menus are provided by operating system

Ok, but why they're in english on system with russian locale?

**Comment by zetok** [comment]
@suhr if your `LC_MESSAGES` is set correctly, then it's simply about Qt file picker being not translated, which is ~outside of qTox scope

![lng](https://cloud.githubusercontent.com/assets/3148759/4910809/46aac1d8-6484-11e4-9f33-526e99197d36.png)

**Comment by agilob** [comment]
OK, I get what you mean and I think it's not worth doing (at this stage?) Just to get QFileDialog in your language, [this is](https://gist.github.com/agilob/04db4fb37e5e4fbdc19c) how many translations are needed to have only one window translated. Think about QMenu (right click menus, Copy/Paste/Undo/Redo/Select all/Delete/...), platform depended strings (like Attach as tab to/Keep above in KDE), right click on QScrollBar...

I've just tried it, and we can do that, but automatic .ts file generation (`lupdate qtox.pro -ts translations/pl.ts` will overwrite manual changes. Manual changes are required to keep strings like Cancel/Copy translated.
