### ISSUE TITLE
Unnecessary linkification

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#624]
The string:

"awww... what a shame"

Becomes:

"ahttp://www... what a shame"

**Comment by dubslow** [comment]
Grrrr, Qt doesn't support lookbehind assertions...

Edit: Thank god for `\b`  (said no one ever)

**Comment by dubslow** [comment]
For future reference, if we want to readdress this at some point:

https://github.com/quassel/quassel/blob/1b7bda6032edddeb3d6895916e1c968acef19979/src/uisupport/clickable.cpp#L51-L118
