### ISSUE TITLE
Appimage does not start at user logon

### ISSUE THREAD

**Issue by minhchuvolam** [qTox/qTox#6241]
##### Brief Description

OS: Ubuntu 20.04
qTox version: v1.17.2 
Commit hash:  465d82606813439ee14425f7462903bb39f2da30
toxcore: 0.2.11
Qt:  5.7.1

Reproducible: Always

##### Steps to reproduce

1.  Run Appimage
2. Set Autostart
3. Logout and log back in

##### Observed Behavior

qTox does not start
##### Expected Behavior

qTox started automatically

**Comment by wsgcsysadmin** [comment]
qTox creates a file in ~/.config/autostart/ named "qTox\ -\ YOURUSERNAME.desktop".


This file contains:
> [Desktop Entry]
> Type=Application
> Name=qTox
> Exec="/tmp/.mount_qTox-vpxOiBd/local/bin/qtox" -p "YOURUSERNAME"

The Exec key points to a temporary mount point that is different every time the AppImage file is run. It should point to the AppImage file itself. Like this:
Exec=/PATH/TO/qTox-v1.17.3.x86_64.AppImage -p "wsgcme"

**Comment by minhchuvolam** [comment]
Thanks. That works.  But I think this should be done automatically by script instead of the user has to manually update the desktop file.

**Comment by anthonybilinski** [comment]
Thanks for the explanation of the issue @wsgcsysadmin. PR #6382 opened to do that automatically.
