### ISSUE TITLE
Invite to group option greyed out

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#6243]
Hello,
I have created a test group and not seem to be able to invite users onto it (that one probably requires the invite bot). I tried however added a user in the group, but the option for that appears to be greyed out.
I am on the Desktop Linux application, v1.17.2
![Screenshot_20201024_153334](https://user-images.githubusercontent.com/13089641/97081954-a5af1480-160e-11eb-9c0a-4e3ef8d7720c.png)

**Comment by anthonybilinski** [comment]
Currently only friends that are online can be invited to a group. Once that initial invitation is accepted, they will automatically rejoin and reconnect to anyone else in the group as long as there's one friend in common online in the group at the time.

**Comment by ghost** [comment]
That seems to make sense. I've got another problem now, I cannot seem to message that user, the message has a stuck progress circle alongside it. Does he have to accept the friend request first?

**Comment by anthonybilinski** [comment]
Yes, messages can only be delivered when your friend shows as online. Until they've accepted the friend request, due to the design of Tox, you can't tell when they're online or how to connect to them. As well if they've accepted the request but are currently offline, that is indistinguishable to you as them not having accepted it.

Messages with the spinning circle will be delivered to the friend as soon as your see them come online, which will happen when they accept the request.

**Comment by ghost** [comment]
Got it, now it worked, was able to message and invite the user into group
Two little problems now:

After logging out and logging back in, the messages sent into the gruop are no longer visible. Is it by design? Only the chat history with the user remains.

The button for sharing media into the group is apparently greyed out. Not that important but just being curious.

**Comment by sudden6** [comment]
> the messages sent into the gruop are no longer visible. Is it by design?

This is a missing feature in qTox that is not yet implemented.

> The button for sharing media into the group is apparently greyed out.

This is a limitation of the current toxcore (The library implementing the communication protocol) implementation.

**Comment by ghost** [comment]
I understood, thank you very much. Looking forward to future versions of this. Especially in today's time, programs like these are more needed than ever.
