### ISSUE TITLE
Accoustic Echo

### ISSUE THREAD

**Issue by Alexander033018** [qTox/qTox#6269]
Brief Description

OS: Windows 7 SP 1 (6.1)
qTox version: v1.17.3
Commit hash: c0e9a3b79609681e5b9f6bbf8f9a36cb1993dc5f
toxcore: 0.2.12
Qt: 5.12.9
Hardware: RAM 4 GB
Reproducible: Always

Steps to reproduce

1. Acoustic feedback.
2. It is impossible to talk.
3. Echoes and whistles are constantly heard.
4. Checked with two callers.

More information on how to write good bug reports in the wiki: https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by anthonybilinski** [comment]
Are you describing acoustic echo from sound coming out of your peer's speakers re-entering their microphone? If that's the case, acoustic echo cancellation is a missing feature from qTox, so using headphones is your best option to avoid this issue.

If you mean some other kind of echo please clarify.

**Comment by Alexander033018** [comment]
Please, add acoustic echo cancellation to qTox.
It is impossible to use the program without it.

**Comment by Xanuman** [comment]
Echo cancellation and noise cancellation are essential.

In particular, you can use the code from this library:

WebRTC VoiceEngine includes Acoustic Echo Cancellation (AEC), Noise Suppression (NS)

**Comment by anthonybilinski** [comment]
Understood, I agree it's an important missing feature. The issue duplicates https://github.com/qTox/qTox/issues/1655 though, so I will close it. I've added your lib suggestion: https://github.com/qTox/qTox/issues/1655#issuecomment-762779325.
