### ISSUE TITLE
DNS requests don't use Tor.

### ISSUE THREAD

**Issue by Jookia** [qTox/qTox#627]
When using Tor, DNS requests aren't passed through it. Most programs have a 'Remote DNS' option to alleviate this. This means your Tox friend lookups are sent to over the clear network.

**Comment by dubslow** [comment]
This is a core issue.

@irungentoo

**Comment by tux3** [comment]
@dubslow it's not actually! last I checked we're using Qt directly to do the DNS lookup.

**Comment by tux3** [comment]
Unfortunately, Qt doesn't support proxying TXT DNS queries.

I have half a mind to just roll my own 10 lines DNS lookup on top of QUdpSocket, which does have SOCKS5 support.

EDIT: I just remembered that Tor doesn't actually support resolving TXT queries, so it is simply not possible at the moment to use Tox DNS over Tor afaik. Maybe we should display a warning or simply disable Tox DNS when the proxy is active.

**Comment by dubslow** [comment]
Doesn't core have a dns module that we're supposed to be using? I assumed that's what we are using...

https://github.com/irungentoo/toxcore/blob/master/toxdns/toxdns.h

**Comment by tux3** [comment]
The toxdns API sounds looks like it's only half finished (where's the definition of the DNS object ? How to actually send anything ?), apparently it only works with utox.org (while a lot of people use toxme.se), and it still doesn't solve the problem that Tor can't handle UDP or TXT DNS queries, wich is what it seems to use according to the doc.

Our current implementation works with any domain, but it's not secure at all. Both the query and response are transmitted in plaintext and can't go through Tor either.

**Comment by dubslow** [comment]
(stqism says it works fine with toxme.se)

Edit: uTox example: https://github.com/notsecure/uTox/blob/master/dns.c

**Comment by stqism** [comment]
Hey folks,
toxdns is required to do tox3, encrypted lookups. What the library does is take the name you want to lookup + the servers public key and return the record the client then needs to lookup, then it decrypts when the client fetched during its lookup and passes the Tox ID to a integer you specified in decrypt.

During this process the client is 100% responsible for the actual DNS request, what to lookup and decrypting it is done by libtoxdns.

The process looks a little like this:
- Pass the servers public key to `tox_dns3_new()`, returning a dns3_object.
- Pass the server object + a string, a request ID, and the name to `tox_generate_dns3_string`
- The client looks up string + _tox + domain and saves this
- The client passes the object, a integer for the Tox ID, the record returned by the earlier request, and the request ID from `tox_generate_dns3_string`to `tox_decrypt_dns3_TXT`
- The client adds the Tox ID integer from a step ago like normal

For simplicities sake I removed some length arguments from the API, these are documented here: https://libtoxcore.so/api/toxdns_8h.html

Note: the public key for toxme.se is at https://toxme.se/pk, in txt record format at `_tox.toxme.se`, and `5D72C517DF6AEC54F1E977A6B6F25914EA4CF7277A85027CD9F5196DF17E0B13`

**Comment by dubslow** [comment]
Well at least that encrypts the request, but... still no way to anonymize it unfortunately... still, twould be a major step in the right direction.

**Comment by tux3** [comment]
Thanks @stqism, that makes more sense.

Do you know if there's a generic way to get an arbitrary tox3 server's public key, though ? e.g. is GET-ing /pk a standardized tox3 thing ?

I think we should try to start using tox3 asap whenever we know the public key, and fallback silently if we don't for now.

**Comment by stqism** [comment]
While the STS dictates `_tox.domain`, `utox.org` does not seem to follow this.

The most sane approach is to preload a couple keys for popular domains.

The key for `utox.org` might be `D3154F65D28A5B41A05D4AC7E4B39C6B1C233CC857FB365C56E8392737462A12`, though I can't verify this.

**Comment by tux3** [comment]
Thanks, I'll add tox3 support asap, and pin utox.org and toxme.se's public keys.

**Comment by tux3** [comment]
We have tox3 support as of 0b6a4a648118c4a75dd64b418125928fa58a08fe, but Tor support is currently impossible by design. Closing for now.

**Comment by Jookia** [comment]
Could you perhaps disable DNS requests when using a proxy, to prevent leaks then? Also why would it be possible by design?

**Comment by zetok** [comment]
Instead of completely disabling it, why not offer an option for user to decide whether it should be disabled?
(or give  option like `muh anonymity` that would simply "optimize" qTox for Tor usage)

**Comment by tux3** [comment]
> Could you perhaps disable DNS requests when using a proxy, to prevent leaks ?

Yes, that's probably the safest idea. 

Or maybe give a warning "this is insecure/not proxies blablabla, do you really want to do this" each time we need to do a DNS request ?
