### ISSUE TITLE
Copy multi-lines of text and send it as a single message, not multiple message

### ISSUE THREAD

**Issue by danrobi11** [qTox/qTox#6273]
Plz take example on how Briar send multi-lines. It makes it very easy to copy a single message in which contains multiple lines of text. 
Try to send 10 lines of code to someone in Qtox, hes going to have some fun with that!
After, send 10 lines of code in Briar and see how easy it is for the receiver to copy that 10 lines of code. 
[Briar flatpak](https://code.briarproject.org/briar/briar-gtk/)
Sry im upset but it really gets me that we have to make a file and send it just for a few lines, when it should be easy as copy/paste/send only.
Although, Thank you for Qtox ;)

**Comment by anthonybilinski** [comment]
I'm not sure I understand the issue. Are you saying that large messages are split into multiple smaller one, or that when copying many small messages it doesn't copy as one larger one, or that it's hard to copy text out of a single large message without including author and date?

RE: title, if I copy multiple lines of text and send it back, it sends as a single message: 
![image](https://user-images.githubusercontent.com/10469203/107161347-0ad60e00-6951-11eb-82af-718629f3b75e.png)

**Comment by danrobi11** [comment]
@anthonybilinski 

Yes you're right I just tested and It does send in 1 block. My bad. Closing
