### ISSUE TITLE
The webcam is shown in the list twice

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#6276]
##### Brief Description

OS: FreeBSD 12.2
qTox version: 1.17.3
toxcore:  0.2.12
Qt:  5.15.2
…

Reproducible: Always

##### Observed Behavior
![image](https://user-images.githubusercontent.com/271906/103107948-f2f03800-45f7-11eb-8f5a-40281e6ad132.png)

**Comment by anthonybilinski** [comment]
I see this too: 
![image](https://user-images.githubusercontent.com/10469203/106975046-a295eb00-670a-11eb-8342-c68ff28dfb7e.png)

It looks like it might be from https://github.com/qTox/qTox/blob/177f37b0a9586b96c23f9808d064812b38c01781/src/platform/camera/v4l2.cpp#L195 which just iterates on all `/dev/video*` devices. My webcam creates both `video0` and `video1` for some reason. OBS still shows it as a single camera input, so we must be able to do this more intelligently.
