### ISSUE TITLE
qtox not working I can't upload documents I cant call out or do video both people have qtox id #

### ISSUE THREAD

**Issue by Lorinkal** [qTox/qTox#6277]
##### Brief Description

OS: Windows / OS X / Linux (include version and/or distro)  
qTox version: (version numbers in menu `Settings → About`)  
Commit hash:  
toxcore:  
Qt:  
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. 
2. 
3. …

##### Additional Info
(links, images, etc go here)

----

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA%\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by Lorinkal** [comment]
Can anybody give me a tutorial on useing qtox I need help I can't upload documents or make any calls.
Lorin

**Comment by sudden6** [comment]
Here's some general user manual: https://github.com/qTox/qTox/blob/master/doc/user_manual_en.md

What concrete problem do you have?
What doesn't work with document sending?
What doesn't work with making a call?
Does text chat work?

You need to give more information than "it doesn't work".

**Comment by anthonybilinski** [comment]
After the reddit post here: https://www.reddit.com/r/projecttox/comments/klugq5/qtox_will_not_let_me_upload_files/ Lorin added me and sent a file and everything seemed to work ok. I think the issue was likely that the friend was just offline.
