### ISSUE TITLE
List of parameters in settings.ini that are not possible to change in GUI

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#628]
- smoothAnimation
- customEmojiFont
- emojiFontFamily
- ~~emojiFontPointSize~~
- firstColumnHandlePos
- secondColumnHandlePosFromRight
- ~~timestampFormat~~*
- nativeStyle
- ~~globalAutoAcceptDir~~*

If we have no plan to add GUI for some of them maybe it would be better to hard code those values and remove from settings.cpp and remove those several lines of code?

 * I can add those settings in GUI, those two are useful.

**Comment by zetok** [comment]
`emojiFontPointSize` is about size of emoticons? if so, ability to change it would be nice, since I myself hardly can see emoticons, and my sight isn't even bad, as is the case with many people..

**Comment by DanTheBritish** [comment]
> ability to change it would be nice, since I myself hardly can see emoticons

On my 1440p monitor, they're absolutely tiny. Until #530 is implemented, any text and emoticon size control is basically mandatory.

**Comment by dubslow** [comment]
globalAutoAcceptDir does in fact have an interface.

nativeStyle I believe was removed by @krepa098 a while ago?

**Comment by krepa098** [comment]
I removed something like nativeWindowDecoration. nativeStyle should disable some of the CSS to provide a "native" look. But at the moment it does nothing useful.

**Comment by agilob** [comment]
I think we can remove `nativeStyle`, it's overwritten by style selector anyway.
