### ISSUE TITLE
Disable emoticons completely

### ISSUE THREAD

**Issue by raisingw** [qTox/qTox#629]
Not to bash qTox's emoticons specifically, but an option to display only the original text would be great. I tend to switch graphical emoticons off in everything that will allow me to do so.

**Comment by agilob** [comment]
It's on my private todo list.

**Comment by zetok** [comment]
with `useEmoticon=false` in `settings.ini` emoticons are still used

**Comment by agilob** [comment]
https://github.com/tux3/qTox/pull/630

> This is in settings only, does not include support in ChatForm or global autosave, only timestamping is supported globally.

I couldn't file code responsible for that in ChatForm :P
