### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#63]
Need to tr() every visible and relevant string in the code, then start making some translations with Qt Linguist.

**Comment by suhr** [comment]
I can help with russian translation.

**Comment by tux3** [comment]
Okay, I can do french myself.
I'll update this issue (or make a new one) when it's ready to be translated

**Comment by msteinbeck** [comment]
I can do German translations

**Comment by tux3** [comment]
Ok, I'll start making it translatable soon, then.

**Comment by tux3** [comment]
The french and russian translations are merged, @retuxx you can start german in you want.

**Comment by msteinbeck** [comment]
Will be ready tomorrow

**Comment by EibrielInv** [comment]
How can I contribute Spanish translations?

**Comment by tux3** [comment]
@Eibriel You'll need to download Qt Linguist and open the file translations/es.ts

When you're done translating, click "Release" inside Qt Linguist and create a pull request with the new translations/es.ts and translations/es.qm

(Note that someone needs to create translations/es.ts first by running the tool "luptdate", I'll do it later today or you can do it yourself if you know how)

**Comment by suhr** [comment]
> How can I contribute Spanish translations?

Run `lupdate qtox.pro -ts translations/es.ts` in project dir, when open `translations/es.ts` in Qt Linguist, translate, save and click "Release" inside Qt Linguist.

**Comment by EibrielInv** [comment]
Thanks!! QT Linguist is part of QT5 Designer ?

**Comment by suhr** [comment]
It is a part of qt5-tools just like Qt Designer, yes.
