### ISSUE TITLE
CMake build fails on latest (?) commit

### ISSUE THREAD

**Issue by crabctrl** [qTox/qTox#6307]
##### Brief Description

OS: Windows / OS X / Linux (include version and/or distro)  
qTox version: master (v1.17.3-331-g5d269018)
Commit hash: 5d2690184033bd651ae60ed4d9a2f681de805cc0
toxcore:  0.2.11
Qt:  5.15.2
…

Reproducible: Always

##### Steps to reproduce

1. Attempt to compile qtox
2. Get fatal cmake errors

Obviously, the main branch isn't exactly meant to be stable, but still thought I'd make a note of it. I'm unsure of the exact commit which introduced this problem.

```
CMake Error at cmake/Dependencies.cmake:35 (find_package):
  By not providing "FindToxExt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ToxExt", but
  CMake did not find one.

  Could not find a package configuration file provided by "ToxExt" with any
  of the following names:

    ToxExtConfig.cmake
    toxext-config.cmake

  Add the installation prefix of "ToxExt" to CMAKE_PREFIX_PATH or set
  "ToxExt_DIR" to a directory containing one of the above files.  If "ToxExt"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:137 (include)
```

**Comment by anthonybilinski** [comment]
qTox added new dependencies, toxext and tox_extension_messages recently that can't be found on your system, install instructions can be found here https://github.com/qTox/qTox/blob/master/INSTALL.md#compile-extensions for building from source. Overall added in 59038088cb804f20e19af6bc809a9843d6dbf6e7.

You should be able to follow those two steps then run cmake again and have it find them.
