### ISSUE TITLE
Encrypt Tox Data

### ISSUE THREAD

**Issue by hk1mm** [qTox/qTox#631]
Hi,

New user of qTox, I see in the private TAB that I am unable to check the case to encrypt Tox Data : is this means that communication in qTox are not secure ??

Thanks.

**Comment by agilob** [comment]
Tox file is your user file, the same about encrypted logs, has nothing to do with networking/communication. This will be enabled after we solve one more issue. Your communication is encrypted.

**Comment by hk1mm** [comment]
Ok agilob thank you for your fast response..
