### ISSUE TITLE
it.ts translation

### ISSUE THREAD

**Issue by redtide** [qTox/qTox#6320]
I've found some errors/issues in the Italian translation. I've registered on Weblate but it said that the translations are locked, so for now I posted this issue with [this patch](https://github.com/redtide/qTox/commit/d6824044320b50d9c4d43a047a0ea06ffe9aa6d3.patch) as reminder. There might be some other ones but they seems to not be reflected in the UI, so I'm not sure about them (the (un)mute call ones, the warning in the advanced settings tab is half translated).

**Comment by anthonybilinski** [comment]
Locked because of https://github.com/qTox/qTox/pull/6315 still pending, which is integrating the changes from Weblate. It'll be unlocked as soon as that's merged, and then changed can be made directly on Weblate again.

I'll poke another maintainer to review that so that it can get in and we can unlock Weblate.

**Comment by redtide** [comment]
It seems that Weblate translations update removed several strings, I guess it needs to be reviewed after merge or something? I'm new to that platform, I was using Transifex in the past and then changed translations only locally using Poedit/Qt Linguist.

**Comment by anthonybilinski** [comment]
It will remove strings where source strings were removed in code, i.e. if some UI was changed to either reword something or change a concept altogether. Once this PR is merged, Weblate will be synced to qTox master and those source strings will be removed from Weblate as well.

We should be syncing more frequently to avoid source strings getting deleted without being synced back to Weblate for a long time, like has happened now.

**Comment by anthonybilinski** [comment]
https://github.com/qTox/qTox/pull/6315 is merged and Weblate has been updated and unlocked, so translations can be made again.

I can merge this patch manually, but future translations can be made there.

Thanks for the contribution :)

**Comment by redtide** [comment]
Thank you!
Is it possible to download the translation and upload it once done locally instead editing on the website?
Also, can I close this?

**Comment by anthonybilinski** [comment]
I've applied the patch and uploaded it to Weblate.

Generally you should be able to go to https://hosted.weblate.org/projects/tox/qtox/it/ then go to Files -> Download Translation, make your edits, then go to Files -> Upload Translation.

**Comment by redtide** [comment]
Thank you!
