### ISSUE TITLE
Offline qtox, while actually I am online

### ISSUE THREAD

**Issue by LorenzoUser** [qTox/qTox#6326]
Since some days I noticed a red circle while actually I am online. I tried to switch on the "online button" manually, but nothing happens. People cannot see me online, and I cannot read their messages.
Could you please suggest me how to deal with this issue?
Thanks

##### Brief Description

OS: Windows 10 (10.0)
qTox version: v1.16.3
Commit hash: 8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore: 0.2.3
Qt: 5.9.6
Hardware: 
Lenovo Thinkpad

Reproducible: Always

##### Steps to reproduce

1. Offline, while I'm currently online
2. Close and open the app again
3. Try to switch it on manually 

##### Observed Behavior
None happens. Still offline

##### Expected Behavior
Switching online

##### Addition
![Untitled-1](https://user-images.githubusercontent.com/82050315/113756968-5834e880-9712-11eb-8852-3799905ba5bf.jpg)
al Info
(links, images, etc go here)

----

More information on how to write good bug reports in the wiki: https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by sudden6** [comment]
This happens when qTox can not connect to the DHT (other Tox clients), what does the log file say?
