### ISSUE TITLE
Support Tox URI

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#633]
Subj.

**Comment by dubslow** [comment]
Duplicate of #250 :)

**Comment by suhr** [comment]
Well, probably “Tox DNS/protocol support” was not a good name for the issue. :)

**Comment by tux3** [comment]
Fixed by a035cc5576de40dec5b2070db06266408a168d07

**Comment by suhr** [comment]
Not really. You still can't use cli for this.

**Comment by tux3** [comment]
What do you mean ?

You can start for exemple "qtox tox:test@toxme.se" or  "qtox tox:56A1ADE4B65B86BCD51CC73E2CD4E542179F47959FE3E0E21B4B0ACDADE51855" and it should work.

**Comment by suhr** [comment]
Ah! I see. But this opens an another client. Also cli should have `--help` option.

**Comment by tux3** [comment]
> Ah! I see. But this opens an another client.

If you already have a qTox instance running, then it won't open another client. The already running instance will display the message! Otherwise it'll start a new instance.

http://a.pomf.se/ohhdfq.webm

> Also cli should have --help option

Yep, CLI options were planned since a long time ago, but nobody's done it yet.

**Comment by suhr** [comment]
Just updated and it works. But cli should be improved.

**Comment by tux3** [comment]
> But cli should be improved.

Yeah, see #207
