### ISSUE TITLE
Gentoo version outdated ?

### ISSUE THREAD

**Issue by JanzenJohn** [qTox/qTox#6331]
OS : Linux Gentoo 5.10.27
qTox : 1.16.3
toxcore = 0.2.12
Qt = 5.15.2

I can't seem to find the option to enable dark theme on gentoo
Is the qTox version on the repo too old ?

**Comment by Chiitoo** [comment]
Yes, though there is also the '9999' Gentoo version available, which would pull 'git master' if you feel adventurous enough.

See also: https://bugs.gentoo.org/746575

**Comment by anthonybilinski** [comment]
OS packaging is handled by the appropriate OS maintainers not by us, so there's not much we can do here. Will close for that reason, but hopefully the package is updated.

Note that using a master version will upgrade your history db to a newer version, which won't be loadable if you go back to a release version before the future 1.18.0.
