### ISSUE TITLE
No desktop notification on Linux

### ISSUE THREAD

**Issue by danrobi11** [qTox/qTox#6336]
Please allow notification to `notify-send` on Linux. That way we could have notification through notifier apps like [dunst](https://github.com/dunst-project/dunst) 

Thank you for qTox.

OS: MX 19.3 (patito feo) x86_64 based Debian GNU/Linux 10 (buster)
SysV init version: 2.93
Kernel: 5.10.0-5mx-amd64
Xorg v1:7.7+19
WM: Spectrwm

**Comment by anthonybilinski** [comment]
qTox has desktop notification support as of `1.17.0` when built with `DESKTOP_NOTIFICATIONS` enabled in cmake, and when settings -> "User Interface" -> "Notify via desktop notifications" is checked. This creates notifications in the same way that `notify-send` does, i.e. through dbus using the freedesktop specification, which can be handled by a daemon in a native feeling way for the DE.

Is this what you're asking for? If not, what do you mean by "notifications to `notify-send`"? qTox and `notify-send` both send to a handler like `dunst`.

**Comment by danrobi11** [comment]
@anthonybilinski 

> what do you mean by "notifications to notify-send"? qTox and notify-send both send to a handler like dunst

 All I know is that I have no notification going through dunst for qtox. 

I forgot to mention that im running the appimage. I might try to compile.

Thank you for the support. Closing.
