### ISSUE TITLE
Replace travis-ci.org for CI

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#6345]
Travis-ci.org is combining to travis-ci.com, which removes the free open source plan that we're currently using for CI on PRs, nighties, master branch builds, and tag builds for release artifacts.

We need to find an alternative service. The current shutdown date for travis-ci.org is targetted at 2021-06-15, but it has already been pushed back many times, so who knows.

Options to evaluate would be:
1. travis-ci.com
2. circleci
3. github actions
4. Azure DevOps 
5. jenkins
6. builds.sr.ht
7. probably lots of others than I haven't though of, will update list.

Criteria should be:
1. Free
2. macOS build support
3. Lower the dev setup cost and maintenance cost the better.
4. High enough build allowances for PRs (and updates to PRs), nightlies, releases. We could maybe reduce our usage here.
5. Other thoughts.

Something else to consider is that [CIRP](https://github.com/nurupo/ci-release-publisher), our release uploader that we use to move artifacts from travis-ci to github releases may need to be updated as well.

**Comment by anthonybilinski** [comment]
based on some quick research and my opinion:

1. travis-ci.com
    1. Payment switched from "free for open source" to "you can get some free credits as an open source project if you contact support." I emailed support asking for about 1 month of credits, after 3 months they emailed back and gave me about 3 days of credits, saying I'd need to contact support again if I wanted more. Overall this seems like technically free, but extremely limited.
    2. macOS builds are supported. Cost for macOS minutes in credits is significantly higher than other OSes.
    3. Dev setup would be minimal since we already support travis-ci.org. Ongoing maintenance would be high, just trying to continuously acquire credits.
    4. We almost certainly wouldn't have enough credits for close to our current level of builds. Maybe we could do weekly builds + tags for releases, but drop PRs and nightlies?
    5. Overall this seems like a pretty poor option.
2. circleci
    1. Free allocation for Linux and macOS, but significantly less for macOS: https://circleci.com/open-source/
    2. We seem to currently use their "free" plan which doesn't support macOS, not their "open source" plan which does. We should probably switch? If we do switch, yes.
    3. We already have Windows builds (cross compiled from Linux) on circlCI, so it's probably fairly low switching cost. Credits are flat rate and recurring, so it shouldn't require ongoing maintenance.
    4. We're currently way over our allowance :o of 2500 credits/week on the free plan, but the OSS plan gives 100,000/week, which looks like it would absolutely be plenty.
    5. Switching to the OSS plan, giving us way more credits and macOS builds seems like a relatively low effort option that meets all our needs.
3. GH actions
    1. I think it has unlimited* free minutes for public repos, and "2,000 Actions minutes/month " for private repos. So yes.
    2. Yes.
    3. Would be a totally new CI platform for us, but would have tight integration with our code and artifact deployment, at least. Is probably more tailored for easily pickup too, so at least for a new option, it's probably not too bad. Ongoing maintenance should be low since their credits are either unlimited or flat continuous amount.
    4. Unsure on exactly build allowances, if it really is unlimited, then definitely enough.
    5. aTox uses these and is happy with them. Would couple our CI to our repo hosting, which would increase repo switching cost. It doesn't feel like the repo will be moving soon or that github is losing steam, but who knows.
4. Azure devops
    1. Yes, https://azure.microsoft.com/en-us/pricing/details/devops/azure-devops-services/ "10 Free parallel jobs with unlimited minutes per month"
    2. Yes.
    3. Expected low ongoing dev cost, but some startup due to new platform.
    4. Yes, unlimited.
    5. aTox uses these too, and is happy with them.
5. Jenkins
    1. Would require payment for the actual machine/electricity of running the builds. Probably still cheap compared to paid cloud services, but a lot more expensive than free. "Apple’s macOS license do not allow you to run macOS on non-Apple hardware", none of us maintainers have a Apple hardware.
    2. According to Apple's license, only with Apple hardware.
    3. Dev setup cost would be larger due to the DIY nature, and would require ongoing maintenance since it's self-managed.
    4. Yes, basically unlimited build allowance. I think a single slow machine running at home could handle all the builds that we want.
    5. We used to have builds done by tox.chat I believe, I think only for releases. I don't know much about the history of that. Apple's hardware requirement could be circumvented with e.g. https://github.com/myspaghetti/macos-virtualbox, but I don't think that's a good official position to have.
6. builds.sr.ht
    1. Will no longer be free once they enter beta https://man.sr.ht/ops/builds.sr.ht-migration.md.
7. self hosted sr.ht
    1. Same properties as Jenkins.

I'd probably think circle CI upgrading to the OSS plan would be easiest, and we're already familiar with the platform. GH actions would be my second choice since they're overall easy and well supported.

@nurupo mentioned on libera IRC #qtox "i think it might be worth migrating to github actions, since its part of github rather than some 3rd party company like circle-ci or travis-ci that have different goals than github" which is a fair point.

I don't have strong preference between the different cloud providers that meet the criteria. If we do go with GH actions, is there a reason to stick with circleci as well? I feel like this time we've been using both travis and circleci, it let to twice as much maintenance with the benefit being PR speed or minutes, which hopefully whatever new service could just handle on its own.

@sudden6 have any opinions here?

**Comment by nurupo** [comment]
>@nurupo mentioned on libera IRC #qtox "i think it might be worth migrating to github actions, since its part of github rather than some 3rd party company like circle-ci or travis-ci that have different goals than github" which is a fair point.

Just to clarify, since this was said in context. My point was that Circle-CI could follow Travis-CI's example and too unreasonably restrict the free/open-source usage of their service, since they are a business and are making money off their paid customers. GitHub is obviously a business too, but open-source projects are an integral part of GitHub, so it would seem less likely that they would cut off open-source projects like that.

---

>Something else to consider is that CIRP, our release uploader that we use to move artifacts from travis-ci to github releases may need to be updated as well.

It's used only for the nightly builds, but yes, it would need to be ported to a new CI platform as it's Travis-specific.

---

Circle-CI, GitHub Actions and Azure Pipelines all seem good to me.

Circle-CI's macOS offering seems a bit limited in comparison to other CIs, 400,000/month of credits (27d18h40m/month at [10 credits/min](https://circleci.com/pricing/#compute-options-table)) for Linux but 25,000/month of credits (8h20m/month at [50 credits/min](https://circleci.com/pricing/#compute-options-table)) for macOS. Do we need more than 8h of macOS builds or is that enough?

**Comment by anthonybilinski** [comment]
Thanks, 8h/mo seems low to me. Currently our PR build for macOS takes about 30 mins on travis-ci.org, and that's re-run on every PR update. So even with 1 PR/week we could hit the limit.

I started working on mirroring our current travis setup with github actions at https://github.com/anthonybilinski/qTox/tree/gh_actions, and it's pretty painless. I don't think the factor of it being a new platform is much of a reason to favour circleci over GH actions anymore.

Also fwiw aTox switched from Azure DevOps + GH actions to just relying on GH actions.

I'll keep going on this and hopefully nothing big comes up.

**Comment by anthonybilinski** [comment]
Re-opening. https://github.com/qTox/qTox/pull/6350 only covered the PR portion roughly to unblock merges. Nightlies, tags, and artifact deploying as well as cleanup still need to be done by before next release (or sooner for nightly builds).
