### ISSUE TITLE
Failed to send file when the receiver is offline

### ISSUE THREAD

**Issue by scidumb** [qTox/qTox#6357]
##### Brief Description

OS: Linux Mint 20
qTox version: v1.16.3-2build1-debian
Commit hash: build without git
toxcore: 0.2.10
Qt: 5.12.5
Reproducible: Always 
##### Steps to reproduce
send a file to the receiver when he/she is offline; Then get message "Failed to send file ***"

I noticed there was a discussion on this in 2017 (https://github.com/qTox/qTox/issues/1293), and didn't expect it to happen now in the new version.

**Comment by anthonybilinski** [comment]
#1293 still covers the needed functionality and has more history, so I'll close this as a duplicate.

Unfortunately it's still the current state of faux-offline file transfers (i.e. not implemented), but it's in our plans to be done in the next couple months.
