### ISSUE TITLE
Is there an easy way to convert plaintext to profile.db chat history?

### ISSUE THREAD

**Issue by AngelTs** [qTox/qTox#6364]
Is it easy way to convert early exported Chat History (in text file) from plaintext to profile.db?

**Comment by anthonybilinski** [comment]
No, unfortunately exporting chat to file is a one way operation.

It doesn't have 100% of the info needed to go back, but could theoretically be manually reconstructed through some database hacking.

**Comment by AngelTs** [comment]
I found a way, but it is not easy or fast- spent hole day (23.20.2021). I managed to restore 232 lines of old chat, early exported to txt , back in profile.db and now it shows correct on calendar in qTox window client.
1.
The critical part is to manage to link correct "chat_id" and "sender_alias" fields from "history" table with respective "id" filed of "peers" table and "owner" field of "aliases" table.
2.
You can use Epoch Convertor (https://www.epochconverter.com/batch) to convert human-readable dates to epoch dates:
2021-06-16T16:06:17+03:00 => 1623848777
Then add three zeros to the end 1623848777 => 1623848777000 (to prevent wrong dates, visualized in chat history like 1970 ...)
3.
Use Google Sheets to many consecutive manipulations until build the text file, which will be ready to import in History table in profile.db in DB.Browser.for.SQLite-3.12.2-win64 and to create the new one.
4.
Replace with the new profile.db in you installed qTox dir

**Comment by anthonybilinski** [comment]
Congrats!
