### ISSUE TITLE
Mention if this project is still alive

### ISSUE THREAD

**Issue by davidfavor** [qTox/qTox#6367]
Many issue tickets have gone months without any updates from a developer.

Mention if this project is still under active development.

Thanks.

**Comment by anthonybilinski** [comment]
It's still under development, there is work going into things for the next release, and PRs are accepted. The main contributors are all a bit busy at the moment so commit rate has slowed, and our issue backlog is a mess so some issues don't get comments for a long time even when there's heavier development.

**Comment by davidfavor** [comment]
Thanks for the update!
