### ISSUE TITLE
Calls - PLEASE kindly fix a few small issues...

### ISSUE THREAD

**Issue by darkman088** [qTox/qTox#637]
Hello together,

I have tested the LAST available qTox version:
https://github.com/tux3/qTox/releases/download/qtox-windows-1415229528.94/setup-qtox.exe
I have noticed the following few glitches, please be so kind to fix them, I think it should be quite easy:
1) The ringing duration - this issue has been fixed and closed. Or at least I was assured it is. Why is it not reflected in the last version I was able to download ?
2) The ringtone itself makes just 2 rings and then there is silence. Could you please make it repeat until the call is either answered or cancelled by the calling party or it times out ? (I think this issue has already been addressed, sorry if it is like that!
3) There are text notifications in the chat text area - ... calling and ... stopped calling. Those are leaving quite a lot of space before and after themselves - could you kindly reduce this space ? IMHO it just takes space and the resulting sparse text doesn't look good.

Many thanks in advance and sorry again, if something is repeating...

P.S.: I LOVE the sound when I receive a message! And you implemented the smilies !!! Now it REALLY looks like a finished program! And there is also an installer! RESPECT !!!

**Comment by dubslow** [comment]
As far as 2) goes, when I added the ringtone it was a hacky play-once-and-done. To do it properly would mean making a separate thread that loops the ringtone until told to stop. I have very little experience with threads, so I avoided it at the time, though it really would make for excellent experience gained, so maybe I should do it properly...

**Comment by darkman088** [comment]
Yeaaaah, DO IT DO IT DO IT :-) I will be the moral support bringing you the coffee and saying GOOD GOOD, you will make it !!!
And what about 1) and 3) please ?

**Comment by krepa098** [comment]
> would mean making a separate thread that loops the ringtone until told to stop

I think you can use alSourcei(sourceID, AL_LOOPING, AL_TRUE) :wink:

**Comment by agilob** [comment]
@krepa098 showed us once new, optimized chat widget, so probably this will be replaced, there are a few more glitches in the current one, all caused by HTML.

**Comment by dubslow** [comment]
Yeah but... how do you get it to stop? :P

**Comment by darkman088** [comment]
Hey, I just checked the latest qTox - you made the possibility to copy the Tox ID and to rename the user !!! That is soooo COOL !!! Unfortunately the situation for the points here is still the same...
Also agilob has written some popup for dropping calls, it hasn't been included in the latest release and I was not able to check it, because I don't know how to build this thing under windows.

**Comment by dubslow** [comment]
agliob hasn't made a pull request -- presumably he wants to do some more work on it

**Comment by agilob** [comment]
> agliob hasn't made a pull request -- presumably he wants to do some more work on it

Yh... no. It's a prototype, I can't do GIMP or PS, so it's easier for me to visualize idea with... working code. I wasn't going to finish that feature in my branch until decided how to implement it, [another idea was to show animated pop-up](https://github.com/tux3/qTox/issues/515#issuecomment-61551871).

**Comment by darkman088** [comment]
Hi agilob! I very much like your ideas !! No idea what is making you to feel unsure about your development, but I think that it is a VERY good idea to make a pull request and include your work in a next version!! I am REALLY longing to see this implemented! This is basically one of the last things I am missing in the program, before I will declare it for PERFECT !!! The entire team working on it has done OUTSTANDING work on implementing the features for aliasing a user and getting the Tox ID !! Just KEEP the good work going !!!

**Comment by darkman088** [comment]
Hello all,

I have now again installed the latest qTox version: qTox Windows 2014-11-30 12:46:06
Unfortunately I have noticed, that the status on this topic is still the same:
- The ringtone duration is still 10-15 seconds only. Despite many assurances that it has been increased to 45 or 60 seconds, I still can't confirm the modification.
- There is still no possibility to reject a call, despite the fact, that agilob has already presented a nice solution to this issue quite some time ago...
  Kindly advise...

**Comment by dubslow** [comment]
We get there when we get there, unfortunately.

We were discussing the reject interface with the UI designer, @ItsDuke, but after reaching a consensus we haven't actually gotten the necessary image files to implement it.

A properly done ringer will likely accompany that when it happens.

**Comment by ItsDuke** [comment]
@dubslow oh, was everyone in consensus that my little idea was the way to go? I wasn't aware.

**Comment by darkman088** [comment]
@ItsDuke can you pls repeat your idea ? I am not sure to remember it...
@Dubslow - sorry my understanding was that it is ready. Can you kindly suggest an implementation date ? Do you think that a nice Christmas present would be feasible ? Thanks !!

**Comment by ItsDuke** [comment]
@darkman088 No problem

![ring](https://cloud.githubusercontent.com/assets/7714365/5306775/43145bac-7bd5-11e4-94c5-64f8070c1139.gif)

**Comment by Xylemon** [comment]
@ItsDuke I really like the way this looks.

**Comment by darkman088** [comment]
Yes, I like it as well !!! Please go for it and implement it. It is not a show stopper for using the program, but it will make life so much nicer :-)

**Comment by ItsDuke** [comment]
So it would seem that most folks like this little notification. Amy I correct in assuming that the phone button, grey box, and circular buttons would all be drawn by the program, so don't require a png? So the only actual graphics required are the phone, check, and x symbols?

**Comment by zetok** [comment]
[✔](http://graphemica.com/%E2%9C%94)
[✗ ](http://graphemica.com/%E2%9C%97) ?

@ItsDuke probably

**Comment by ItsDuke** [comment]
@zetok I hope you're not suggesting we use those ;P

**Comment by zetok** [comment]
@ItsDuke well… :D
Not really a suggestion, but rather I wanted to make sure that using them (and some others to which one could click to) is a bad idea.

**Comment by darkman088** [comment]
Please kindly make the x button red :-P And the other one green :-)

**Comment by ItsDuke** [comment]
@darkman088 are they not already?

**Comment by darkman088** [comment]
Hello everybody!

What's going on ? What is the status on this one ? More than a month has passed, and no updates...
I hope this hasn't been forgotten !!

**Comment by Zer0-One** [comment]
+1 to @ItsDuke 's mockup, i really like the animated handset

**Comment by tux3** [comment]
I'll be implementing @ItsDuke's mockup this weekend if all goes well.

**Comment by tux3** [comment]
@ItsDuke I can't find images for the phone and buttons, can you upload them ? A png or svg would be fine.

If you don't have the time, I'll try to recreate them.

**Comment by ItsDuke** [comment]
@tux3 sorry about the wait on this one, I've just been moving recently, and just now settling into some kind of routine approaching "normalcy". I should have these saved out either later tonight or tomorrow!

**Comment by tux3** [comment]
@ItsDuke Thanks. I'll just code the logic and use placeholders in the meantime.

**Comment by tux3** [comment]
Here is what it looks like for now with placeholder buttons.
![image5](https://cloud.githubusercontent.com/assets/5155966/5892027/09eb3f34-a4b2-11e4-936a-2a5c373209af.jpg)

**Comment by krepa098** [comment]
Nice! I guess we should also use this for emoticons. Maybe even for adding friends as the current solution looks too sparse imo.

**Comment by tux3** [comment]
@ItsDuke if the incoming call is a video call, is there a special animated video icon too ?

**Comment by tux3** [comment]
I tried upscaling the buttons from the mockup, here's what it looks like :
![image6](https://cloud.githubusercontent.com/assets/5155966/5892599/c138efa2-a4c5-11e4-8b7f-85e4c820f15f.jpg)

This is merged in master, since it's clearly an improvement over nothing at all, and we can replace the images with high-quality versions later.

**Comment by ItsDuke** [comment]
@tux so, it appears that all of the icons necessary to complete this were already in my repo back in June. I spent the better part of the afternoon sorting them and saving them all out in different sizes, and then I checked my repo and they're all there.

I guess no one (including myself) thought to look?

**Comment by dubslow** [comment]
lol

**Comment by tux3** [comment]
@ItsDuke I did check your repo but I must have missed them, sorry.

Just to be sure, you're talking about yes.png/no.png, there aren't ones with the green/red circle in background ?

**Comment by ItsDuke** [comment]
@tux3 whoops, do I need to create a circle element? I just assumed one would be drawn by the program. Wasn't sure about the SOP for buttons in Tox.

**Comment by tux3** [comment]
@ItsDuke It's alright then I'll take your current images and go from there, thanks!

**Comment by Tux** [comment]
@ItsDuke  @tux != @tux3 please use the correct user tag. please!

**Comment by ItsDuke** [comment]
@tux sorry for pissing in your coffee m8

**Comment by darkman088** [comment]
Are you that far, so I could try this nifty thing ? I'm looking forward to it soooo much! :-)

**Comment by tux3** [comment]
@darkman088 you can try it right now if you update qTox :)

**Comment by darkman088** [comment]
Hi, I finally had a few free moments to have a look at it - it is AMAZING !! It looks very good and it's working !!! Congrats guys, you rock !! And you've added soooo many new features !!
Now I am really missing just a loud and long-ringing ringtone, which will send missed
calls to the past :-)

Thank you!!

**Comment by ayyyy** [comment]
Hey, when will the ringtone be a loop, not just one ring? How about an option to change the ringtone to our liking?
Thanks

**Comment by darkman088** [comment]
+1, but with both hands for these VERY necessary goodies !!

**Comment by tux3** [comment]
This has been fixed.
