### ISSUE TITLE
Friend list flashes and stalls when sorted by activity mode since 6347

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#6372]
##### Brief Description

OS: Arch 2021-08-31
qTox version: v1.17.3+
Commit hash:  bde6dc0df0583a2c869612a010533bb6246ad7e2
toxcore:  v0.2.12
Qt:  5.15.2

Reproducible: Always

##### Steps to reproduce

1. Sort friend list by activity
2. Send a message to a friend

##### Observed Behavior
1. Friend list flashes
2. The more friends in your friend list, the longer the flash takes
3. The GUI freezes for the duration of the flash, which isn't noticeable with 1 friend, but is very noticeable with ~100

##### Expected Behavior
1. Like when sorted by name, sending a message to a friend doesn't cause the friend list to flash or pause GUI.
2. User experience to match before a24f99df0d488450447e0c9360613dbcd9e30fd8, when in activity mode the friend list didn't flash or pause when sending a message.

##### Additional Info
@bodwok do you have any first guesses for how this was changed in your PR or where to fix it? No problem if not.

**Comment by anthonybilinski** [comment]
This is coming from mostly https://github.com/qTox/qTox/blob/76fc2f8b8a6a71762fd4080d1829b710a10534ec/src/model/friendlist/friendlistmanager.cpp#L70 which takes about 60ms on my profile on my desktop, and then about 30ms from https://github.com/qTox/qTox/blob/76fc2f8b8a6a71762fd4080d1829b710a10534ec/src/model/friendlist/friendlistmanager.cpp#L136, which is being done on every message send since when sorting by activity can change the position of the friend in the friend list.

I'm not sure how needed the first is in Qt, but even if we can't improve them, we could shortcut most of the work when sending or receiving a message. In those cases, we don't need to resort the entire list, just move one item at most, or usually 0 items.

**Comment by bodwok** [comment]
I'll look it

**Comment by bodwok** [comment]
Good point. I made some changes.
