### ISSUE TITLE
EXEC_CRASH on invite from groupbot when already in a split groupchat

### ISSUE THREAD

**Issue by stqism** [qTox/qTox#638]
So... this happened http://tox.lighthouseapp.com/projects/123754-tox/tickets/10-qtox-crash-on-invite

**Comment by dubslow** [comment]
Strange -- it was realloc'ing something while writing to file, but the realloc was on something that wasn't alloc'd... very strange...

**Comment by tux3** [comment]
Wait. myMessageHandler is not threadsafe at all, yet we're using qt_message_output all other the place.

Thread 4 is in Core::onGroupNamelistChange, whose very first operation is a call to qDebug, and Thread 0 crashed in the middle of myMessageHandler

Wanna bet it's a threading problem ?

**Comment by dubslow** [comment]
Nope. :)
