### ISSUE TITLE
Broken cinnamon after installing from source

### ISSUE THREAD

**Issue by lupa18** [qTox/qTox#639]
Hello,
I'm with Linux Mint 16 (Ubuntu 13.10) and I did this: 
    git clone https://github.com/tux3/qTox.git
    cd qTox
    ./simple_make.sh

then cinnamon make a "Fatal error" and could not start again.

**Comment by dubslow** [comment]
I find that... highly unlikely to say the least. The _only_ possible thing is maybe some of the packages that ./simple_make.sh tries to install may have done something, but even that is a bit of a stretch. This is what it does, for the record:

```
sudo apt-get install build-essential qt5-qmake qt5-default libopenal-dev libopencv-dev \
libtool autotools-dev automake checkinstall check libopus-dev libvpx-dev
```

What happens if you only run this?

```
./bootstrap.sh
qmake
make
```

**Comment by lupa18** [comment]
I don't know because we need urgently use the computer and I had to reinstall mint, now version 17.

**Comment by tux3** [comment]
This does not seem to be a bug with qTox. If someone still has this problem, please comment and I'll reopen.
