### ISSUE TITLE
Docker.ubuntu build hangs

### ISSUE THREAD

**Issue by brandonmosher** [qTox/qTox#6396]
##### Brief Description

Building Docker.ubuntu hangs because the keyboard-configuration package requires user-input during installation. This could be fixed by changing:
```
RUN apt-get update ...
```
to:
```
RUN DEBIAN_FRONTEND=noninteractive apt-get update ...
```

**Comment by anthonybilinski** [comment]
I don't see any hang when running this myself through `build-ubuntu.sh`. What prompt are you seeing? Is it on update or on install, I thought update doesn't require config and install is already passed `-y` https://github.com/qTox/qTox/blob/da5c165f4116dce736def63b1b917523b848db09/docker/Dockerfile.ubuntu#L20 which should auto-answer `yes` to avoid blocking.

**Comment by brandonmosher** [comment]
Whoops... I ran it again and it works fine. The issue was that I changed "From ubuntu:16.04" to "From ubuntu" to use my locally cached ubuntu image. For some reason, the newer ubuntu image requires the noninteractive flag even with the -y and --force-yes options. Otherwise it prompts for keyboard and timezone configuration and the build never completes. Feel free to close this.

**Comment by anthonybilinski** [comment]
Ah alright. There might be package name changes between the versions anyway, so I think our docker file sticking with its specified version will be most reliable. I guess might a well add `DEBIAN_FRONTEND=noninteractive` now so that it doesn't cause issues later when we update Ubuntu. I'll update a PR for that.

**Comment by anthonybilinski** [comment]
PR opened: https://github.com/qTox/qTox/pull/6398. Build now passes on "ubuntu", but fails on "debian" due to qt5-default package not existing. We'll have to update that when we make the version switch, but both now have DEBIAN_FRONTEND=noninteractive.

**Comment by anthonybilinski** [comment]
PR merged, but keep in mind my previous comment - still the dockerfiles only support the specific version in them.
