### ISSUE TITLE
Login issues too qTox. App doesnt seem to remeber passwords and will lock entry of different user name

### ISSUE THREAD

**Issue by JoeBurner** [qTox/qTox#6410]
##### Brief Description

OS: Windows / OS X / Linux (include version and/or distro)  
qTox version: (version numbers in menu `Settings → About`)  
Commit hash:  
toxcore:  
Qt:  
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. 
2. 
3. …

##### Additional Info
(links, images, etc go here)

----

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA%\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by anthonybilinski** [comment]
I need more info before I can start to look into this. Are you able to reproduce this issue with a new profile and known password?

qTox has no lock-out feature for password retries, so it locking out a different user doesn't really seem possible.

Is it a new profile or an old profile that's having this issue? If it's a new profile, and you're sure you're typing your password in right, I'd guess that you initially set it wrong when creating the profile.

**Comment by JoeBurner** [comment]
I have created several new profiles and passwords ensuring to write them
down. None of them work.

**Comment by anthonybilinski** [comment]
What OS are you on and what version of qTox are you using? Can you attach qTox logs?

Does a password-less profile load fine for you?

**Comment by JoeBurner** [comment]
https://gyazo.com/18d27deb05891525f50aee124583491a

I thought with GitHub I could at least access something to delete the
profiles cluttering up my login screen or enter a new one and whats the
import about?

**Comment by anthonybilinski** [comment]
Sorry for the slow response. Currently in qTox the only way to delete a profile is after you've logged in by clicking on your profile.

You can still manually delete the profile files "<profile>.db" "<profile>.tox" "<profile.ini>" from `%APPDATA%\tox\` on Windows

You should still be able to create a new profile from the login screen by clicking "New profile".

"Import" takes a tox profile that was exported from a different chat client and copies it into qTox.

Logs would still be quite useful here, they're stored in the same location in a .log file, and trying with a new profile with a very simple password like "123456" to be sure it's not working.
