### ISSUE TITLE
Reduce excessive text spacing in chat window.

### ISSUE THREAD

**Issue by clort81** [qTox/qTox#6424]
##### Brief Description

OS: Windows / OS X / Linux (include version and/or distro)  
Manjaro Linux
qTox version: (version numbers in menu `Settings → About`)  
1.16.1.r32

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce
always

##### Observed Behavior
excessive spacing between chat lines

##### Expected Behavior
less excessive spacing between chat lines

**Comment by anthonybilinski** [comment]
Lots of overlap with https://github.com/qTox/qTox/issues/3007, will close as a duplicate and track discussion and work there.
