### ISSUE TITLE
Visual bug in chat window / messages disappear

### ISSUE THREAD

**Issue by luffah** [qTox/qTox#6441]
Sorry for the short and without participation report.
I just suggest a test for the next release.

I used qTox-8c34fa8f7d34e6555533f392925164b47da12d8c-x86_64.AppImage on Linux Ubuntu
and encountered a visual bug described below. This a llitle bit unconfortable minor bug.

Here the test procedure:
- open a chat window with a long time contact with history
- scroll back to some weeks or days and copy 2 or 3 messages
- paste it in a new message
- send message
- scroll the window to the bottom of the chat history and check recent messages : all messages between the day of the pasted message and now  had disappeared
- if you restart qtox, you can check the chat history is not actually changed

**Comment by anthonybilinski** [comment]
This looks related to a bunch of chat log bugs that were fixed in 6a10abf1b385ce2a45cb53ee3726b35a54abc1ac, which is slightly later than the version you're running.

Could you try updating to a nightly and see if the issue is no longer reproducible? https://github.com/qTox/qTox/releases/nightly

Note that updating may upgrade your chat history which is not then downgradable - but you're already on a recent commit that's incompatible with 1.17.4 so that's probably not a huge concern for you.

**Comment by luffah** [comment]
I tried to switch with version 1.17.4.
The issue doesn't appear, but, no history is stored on this version while the checkbox to preserve history is checked.
(maybe a conflict on database ?)

I ll wait to see v1.18+

**Comment by anthonybilinski** [comment]
v1.17.4 is earlier (in some ways) than your original version, which is incompatible with the chat history database, so not being able to open chat history is expected. Generally our chat history database can only be upgraded, not downgraded, and the order of the versions here are:

v1.17.4 -> your original version 8c34fa8f (bug) -> fix -> nightly (today) -> v1.18.0 (future).

So a currently nightly should still resolve your issue if you want to try it out. Also note that your chat history is still safe when you're on an older version like v1.17.4, even though qTox can't open it, but new history is not being recorded.

If you want to wait for v1.18.0, that should also resolve your issue, but then unfortunately you won't be able to run without either going back to 8c34fa8f with the visual bug, or staying on v1.17.4 with no history being recorded until then.

**Comment by luffah** [comment]
No problem for me.
I know the bug and will adapt.
