### ISSUE TITLE
Nightly portable wont work

### ISSUE THREAD

**Issue by fcore117** [qTox/qTox#6443]
Just try to enable portable mode, wont work and do not create files in own directory.

**Comment by anthonybilinski** [comment]
Thanks for the find.

Looks like this was introduced in 5d56a3c0397ed6decf21b28553c5e45687585791

Before `Settings::loadGlobal` used to set `makeToxPortable = Settings::isToxPortable();` before figuring out its own paths which used `makeToxPortable`'s state.

After that change, `Settings` creates `Paths` in non-portable mode by default, but doesn't update it based on Setting's decision of if we've started in portable mode i.e. the state of `makeToxPortable`, so Settings just continuously gets non-portable paths.

**Comment by maxwood-forester** [comment]
This appears to still be a problem when using the AppImage version on TAILS 5.4, which is based on GNOME + Debian 11.
