### ISSUE TITLE
about privacy Please add google detection function

### ISSUE THREAD

**Issue by wzzjhc** [qTox/qTox#6444]
About Privacy*********
Please add google detection function************
For example: if this function is turned on, it will automatically detect whether the local ping to google after qtox is started, if the ping cannot be google, it will be offline automatically.
***********
This function should be continuous during software startup

**Comment by ste-h** [comment]
dont add this

**Comment by anthonybilinski** [comment]
@wzzjhc what would be the purpose of that? Already if qTox can't connect to nodes, it will be offline automatically, and this has the drawback of letting google know the IP and time that anyone opens qTox.

It could maybe be done in a more privacy oriented matter, but I'm not sure of a benefit.
