### ISSUE TITLE
Make the status images look like the mockup

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#65]
Sorry for the delay, mannol

**Comment by ProMcTagonist** [comment]
Does this mean making the own status icon the same size as the others, and making the context menu into a dropdown from the own status icon that doesn't change place depending on where you click?

**Comment by tux3** [comment]
The status icon will be the same size as the other, like in the mockup or in uTox.
I could make the dropdown menu not change place, if you want.

**Comment by ProMcTagonist** [comment]
That would be good, I think. Right now it feels like I'm accidentally right clicking, and it's a bit weird.
But I should also mention that now that there's status changing, toxgui is my fulltime client :) Thanks for all the hard work.

**Comment by tux3** [comment]
No problem :)
I'll do that soon.

**Comment by F1ynn** [comment]
Should be done. Alignment isn't perfect yet, but will get to that soon.

**Comment by tux3** [comment]
Fixed by PR.
