### ISSUE TITLE
Clicking tox: link in browser opens new qTox

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#650]
https://toxme.se/u/tux3, click link, get new qtox

Nothing in the log file either, presumably because the original has it open... and I'm not sure if running chrome from terminal will show the new qtox messages...

Edit: Might be because it's using the installed binary, not my compiled one...

**Comment by tux3** [comment]
Can you open qTox throught the web browser link and post the output of <code>ps aux | grep qtox</code> so I know the command line it was launched with ?

Also, you should be able to get a log file.

**Comment by dubslow** [comment]
Well since edits would be missed, the old global binary wasn't logging to file; I overwrote the global with my compile, and now all instances log to file just fine, but it still doesn't work. The new instance does properly attach to existing shared memory.

Apparently it isn't being passed any argument though.

```
ps aux | grep qtox
bill     23717  0.0  0.0   5844   620 pts/4    S+   13:14   0:00 tail -n 50 -f qtox.log
bill     23861  1.9  0.6 1327064 104316 pts/1  Sl+  13:16   0:03 ./qtox
bill     24078  6.9  0.6 1326172 101116 ?      Sl   13:19   0:00 qtox
bill     24154  0.0  0.0  10352   936 pts/3    S+   13:19   0:00 grep --colour=auto qtox
```

I believe it would be prudent for a second instance with no args to immediately quit (maybe with an error message about already running).

**Comment by tux3** [comment]
Then that's a bug in how your web browser handles tox: links. 

If it isn't passing the link to qTox, there isn't much I can do about it :)

**Comment by dubslow** [comment]
Well Chrome is a pretty common browser :P

**Comment by tux3** [comment]
Well, I just checked with Iceweasel on Linux and it works for me.

Maybe on chrome the command line is missing a %1 or something at the end ?
How did you set up chrome to open tox: links in the first place ?

**Comment by dubslow** [comment]
Iceweasel doesn't strictly conform to desktop file standards :)

Also accept pls :P

**Comment by tux3** [comment]
Ah, that's possible, I don't know at all how the desktop file standards work :)
I just set it up manually in about:config for Iceweasel

I didn't know that .desktop files could do things like this, it's pretty cool.

**Comment by dubslow** [comment]
It's how it's done at all.

How is Iceweasel even working if you don't have a desktop file installed?

**Comment by tux3** [comment]
Sorry, I edited my post above. I added it manually through about:config

**Comment by dubslow** [comment]
Ah lol. The user shouldn't have to configure anything -- the .desktop is how it's declared globally. Not sure how to do it for Mac or Windows though.

Also not invalid :)

**Comment by tux3** [comment]
Yeah, I though the installer would have to go tweaking each browser's config, but desktop files are nice too :)

I don't know if there's something like that on Win and Mac tho.

**Comment by tux3** [comment]
A quick search says we have to create some reg keys on Windows.

<blockquote><pre>
REGEDIT4
[HKEY_CLASSES_ROOT\tox]
@="URL:tox Protocol"
"URL Protocol"=""
[HKEY_CLASSES_ROOT\tox\shell]
[HKEY_CLASSES_ROOT\tox\shell\open]
[HKEY_CLASSES_ROOT\tox\shell\open\command]
@="\"C:\\Program Files\\qTox\\bin\\qtox.exe\" \"%1\"" 
</pre></blockquote>

**Comment by dubslow** [comment]
I barely know that the registry is a thing :P
