### ISSUE TITLE
AcquireSRWLockExclusive not found in dll kernel32.dll

### ISSUE THREAD

**Issue by JeanPaulLucien** [qTox/qTox#6544]
##### Brief Description

OS: Windows XP 32-bit SP3
qTox version: 1.17.6

…

Reproducible: Always 

##### Steps to reproduce

1. Install qTox
2. Start qTox
3. Get error message

Message; AcquireSRWLockExclusive not found in dll kernel32.dll

**Comment by anthonybilinski** [comment]
Windows XP is no longer supported by Qt, and given qTox's dependence on Qt, we don't have much of an option to support XP. Generally we don't support qTox for operating systems past their vendor end-of-life either. Sorry for the inconvenience.

If interested, you could try building qTox with a downgraded Qt version to see if that would resolve it, though our Windows compilation is only set up for Linux hosts.

**Comment by JeanPaulLucien** [comment]
@anthonybilinski what about to use i.e. Miranda-NG experience? Miranda is works on Windows XP well, tox protocol, but without calls.

**Comment by anthonybilinski** [comment]
I'm not sure what you're asking? If you're saying why can't qTox work if Miranda-NG does - Qt being our graphics front-end is the reason. There's no restriction by Tox or Toxcore, but qTox isn't dropping Qt as a dependency any time soon.
