### ISSUE TITLE
Names in groupchat don't reflect whether users are really in groupchat

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#656]
![muh pple](https://cloud.githubusercontent.com/assets/3148759/4952764/8a2d164a-6678-11e4-99a5-6b0869659570.png)

qtox 7372fe53146b774f048b1743bf3ca51296ce1eca

Seems to require some time to trigger.

**Comment by apprb** [comment]
![png](https://cloud.githubusercontent.com/assets/6405341/4953035/b283eab2-667b-11e4-89dd-ad180bbbbf3d.png)
My screen few moments later

**Comment by dubslow** [comment]
This is on my list of things to do today

**Comment by zetok** [comment]
I think that it's fixed by now
