### ISSUE TITLE
qtox_history doesn't retain contact names

### ISSUE THREAD

**Issue by tsdko** [qTox/qTox#659]
Let's suppose there's a chat:

```
[13:36:41] tsun: foo
(tsun has changed their name to dere)
[13:36:48] dere: bar
```

Later on, after loading the history, it will look like this:

```
[13:36:41] dere: foo
[13:36:48] dere: bar
```

**Comment by zetok** [comment]
Why should it contain name other than your present?

**Comment by tsdko** [comment]
Not sure how other people feel about that, but I think history should contain the chat state exactly as it was during the time of the chat, including names, status changes, etc.

**Comment by ProMcTagonist** [comment]
The chat archive should be an archive. Name changes are relevant and often critical to understanding context.

**Comment by dubslow** [comment]
Uh... wrong issue, @tux3?

**Comment by tux3** [comment]
Oops! Indeed.

**Comment by zetok** [comment]
Note from #1189:
Beside saving nicks, saving when change happened (and in what way) might be wanted.
