### ISSUE TITLE
TestFriendListManager::testSortByName occasionally fails in CI

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#6606]
##### Brief Description

OS: All
qTox version: v1.17.4+
Commit hash:  0352ada08c7efa4ad6523071bde566f506daeb4d
toxcore:  v0.2.17
Qt:  Multiple

Reproducible: Rarely

##### Steps to reproduce

1. Run test_friendlistmanager

##### Observed Behaviour
Once in a while, this exact comparison fails:
`TestFriendListManager::testSortByName` fails with:
```
   Actual   (fromManager->getNameItem())  : ".test online"
   Expected (fromSortedVec->getNameItem()): "123"
   Loc: [/Users/runner/work/qTox/qTox/test/model/friendlistmanager_test.cpp(348)]
```
It's not easily reproducible, and there's no code changes between passes and fails. Just retrying the job is enough to get it to pass. It fails on any of the CI environments. I haven't seen it locally, but across the different CI jobs I have a lot more test runs in CI.

https://github.com/anthonybilinski/qTox/runs/5764770322?check_suite_focus=true#step:5:776

##### Expected Behaviour
1. Consistent test results.
2. Passing test results.

##### Additional Info
The inconsistent results seem like a race or memory safety issue, but AddressSanitizer finds no issues with the test, and the test seems completely synchronous.. so not sure what's going on here.

**Comment by bodwok** [comment]
It seems that the cause of the failure was in the uninitialized variable `FriendListManager::groupsOnTop` in the test. In qTox it is initialized from `FriendListWidget`.
