### ISSUE TITLE
qTox sometimes renders kana as squares

### ISSUE THREAD

**Issue by tsdko** [qTox/qTox#661]
![](http://web.archive.org/web/20150612023441/http://a.pomf.se/xkgico.png)
Doesn't affect kanji.
Seems to happen randomly, when I restarted it looked normal again, after the next restart it went back to squares.

OS: Xubuntu 14.04 LiveUSB, no additional fonts installed

**Comment by tux3** [comment]
Can someone still reproduce with the latest versions of Qt?

**Comment by agilob** [comment]
Yes, I can reproduce it.

**Comment by agilob** [comment]
I'm pretty sure this is caused by missing characters in a font.

**Comment by zetok** [comment]
hm, there isn't even a test case against which it could be reproduced - i.e. no text that could be copypasted.

I haven't seen any squares related to japanese / chinese / korean in a long time.

Should be closed?

**Comment by agilob** [comment]
I think so, this issue is related to missing fonts/characters in operating system. I have some characters, but not even most of them. Do we ship qtox with hardcoded fonts, there are some fonts in res/. Do we use them?

![fonts](https://cloud.githubusercontent.com/assets/2544251/7749521/12196216-ffc6-11e4-82bf-d858381e4a74.png)

**Comment by tsdko** [comment]
Well, that's why I put "sometimes" in the title. The fonts were there, qTox just didn't use them after a client restart.

**Comment by zetok** [comment]
Is it still reproducible on newest qTox?

Can't reproduce on qTox edc35ba9dfce0eae1557016933147c926f04a22d with Qt 5.5.1 on Gentoo.

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.
