### ISSUE TITLE
[Feature Request] private tracker

### ISSUE THREAD

**Issue by bradfordzhang** [qTox/qTox#6620]
many people have not good internet connection.
can we set up own tracker like bt/pt?

**Comment by anthonybilinski** [comment]
TCP relays the closest thing to that, though not really that similar. They'll handle most of the DHT work for you, so will reduce network usage on your part, but they will also relay all of your traffic which can increase latency, decrease bandwidth, and centralize your chat metadata with an untrusted volunteer relay. To enable that in qTox, go to settings -> advanced and uncheck "enable UDP", then restart qTox.

You could host your own TCP relay, and could add it to your bootstrap list with a nightly build: https://github.com/qTox/qTox/blob/master/doc/user_manual_en.md#bootstrap-nodes, thought your TCP relay will be shared by your client, so can pass arbitrary traffic for other users.

I'm not sure if an analog of a tracker makes sense in tox, I'm not very involved on the protocol side of things. It might be worth bringing up with [toktok/c-toxcore](https://github.com/TokTok/c-toxcore) or [#toktok](https://web.libera.chat/#toktok) on libera IRC to discuss with protocol devs.

**Comment by bradfordzhang** [comment]
okay thanks a lot about that

**Comment by bradfordzhang** [comment]
Actually, the thing I want is like http://***.***/announce
when i want to chat with someone i POST  http://***.***/announce/HISID then "the tracker" send me a possible way to connect him.
it can sync from an "offical tracker", and everyone can set up a "private tracker".

**Comment by bradfordzhang** [comment]
It likes relay server but just help handshake. As soon as the handshake is done, the chat members will connect straightly.
