### ISSUE TITLE
[Question] how to hide status notification in chatbox

### ISSUE THREAD

**Issue by eqn-grp** [qTox/qTox#6624]
Hello,

i want to hide this,  it fills the chatbox.

![image](https://user-images.githubusercontent.com/81374084/163796799-366dae10-f94c-497c-9a7c-4527673aa0d3.png)

**Comment by anthonybilinski** [comment]
Uncheck Settings -> General -> "Show contacts' status changes"

![image](https://user-images.githubusercontent.com/10469203/163799872-9bcb74ae-a39c-466b-bd3c-f482a6402850.png)
