### ISSUE TITLE
Show QR code of tox id

### ISSUE THREAD

**Issue by nshopik** [qTox/qTox#663]
Helps with adding friend on mobile, it seems no know desktop client support that

**Comment by agilob** [comment]
That's pretty easy.
https://stackoverflow.com/questions/21400254/how-to-draw-a-qr-code-with-qt-in-native-c-c

**Comment by tmolteno** [comment]
This would be fantastic. It would really make a big difference.

**Comment by agilob** [comment]
OK, I have code ready for this, but does anyone know how to make it look nice? I can use the popup from call notification appearing above Tox ID or just popup a window with QrCode.
Calling @itsduke

**Comment by ItsDuke** [comment]
Questions: is this for the desktop or mobile version? In what capacity is this used? Is the user wanting to make a QR code of their own ID? Is this a way to add a friend?

I guess I'm just confused as to how and in what capacity this is used, so I can better understand how it should look.

**Comment by zetok** [comment]
@agilob if you're using some additional dependency, is it made in a way that could be turned on/off by compile-time switch?

**Comment by zetok** [comment]
@ItsDuke it's a QR code of own id. Use case is to display own QR code on screeen of your pc/laptop, and your friends could easily scan it using their phones, and "automatically" add it in their mobile Tox client.
