### ISSUE TITLE
Error Message on Fresh Install

### ISSUE THREAD

**Issue by zellchristensen** [qTox/qTox#6630]
##### Brief Description

OS: Windows 7 x64
qTox version: 1.17.6
Commit hash:  [54345d1085628950af4176e6b4873513db0de4f3](https://github.com/qTox/qTox/commit/54345d1085628950af4176e6b4873513db0de4f3)
toxcore:  0.2.13
Qt:  5.12.12
…

Reproducible: Always

##### Steps to reproduce

1. Install qTox to default location (C:\Program Files\qTox) with 64 bit EXE file
2. Make sure Run qTox is checked on the last window of the install
![setup-qtox-x86_64-release_ev2RV4jCjh](https://user-images.githubusercontent.com/38737447/166098114-2add5c0b-2eed-4cbb-abbf-50a9d3811ccf.png)

##### Observed Behavior
Error message occurs when attempting to run automatically.
![explorer_qgguspDyVl](https://user-images.githubusercontent.com/38737447/166098116-791cfa62-66a2-40dd-bd4b-3e42fc1831a8.png)

##### Expected Behavior
Starts normally

##### Additional Info
It works fine using any shortcuts and only occurs during the auto start after initial install.

**Comment by anthonybilinski** [comment]
Was fixed right after release: https://github.com/qTox/qTox/pull/6535, fix will be present in the next release.
