### ISSUE TITLE
How comes this was removed?

### ISSUE THREAD

**Issue by HybridZach** [qTox/qTox#6632]
I use to be able to change the connection settings proxy type on the fly using the "reconnect" button, but now its removed, and you have to apply the SOCKS5 proxy for example close qtox, then re-open it for it to take effect, where as before you could apply the SOCKS5 proxy and then simply click "reconnect".

**Comment by anthonybilinski** [comment]
It was removed in https://github.com/qTox/qTox/pull/5778. It was basically very architecturally flawed, caused bugs (see linked issues), and didn't work properly. In the long term, we'd like to put it back and have to work properly, but until then not providing the broken option is safer for users.

**Comment by HybridZach** [comment]
Ah that's fair enough, thanks.

**Comment by HybridZach** [comment]
Is there a way to change this setting via config file? I see in the qtox.ini the advanced stuff but when I have use Tor enabled I can't see anything for it in the config. 

Reason being I switch from VPN to Tor a bunch and having the ability to switch before opening and closing the application helps avoid exposure to my isp connection.

**Comment by anthonybilinski** [comment]
Settings are split between qtox.ini and \<profile\>.ini, the second being encrypted for password-protected profiles, and is in a binary format, so isn't easy to edit like qtox.ini.

You can set proxy settings from command line when launching qTox to avoid the first start leak using the `-P` switch, which is in any release from 1.17.0 onward: https://github.com/qTox/qTox/blob/08fdd3a2c727f5eac34eac4f9c7b2c48f722e1a7/doc/user_manual_en.md#commandline-proxy-options
