### ISSUE TITLE
QCommandLineParser: argument list cannot be empty

### ISSUE THREAD

**Issue by Chiitoo** [qTox/qTox#6641]
##### Brief Description

OS: Gentoo Linux
qTox version: git master
Commit hash: 665a6c4e3df0ffb2e2be20da3b0c60d9a6c7a0d5
toxcore: 0.2.13
Qt: 5.15.4 (with KDE patchset)

Reproducible: Always

##### Steps to reproduce

1. Compile qTox at commit 665a6c4e3df0ffb2e2be20da3b0c60d9a6c7a0d5.
2. Execute qTox.

##### Observed Behavior

At commit 665a6c4e3df [1]:

```
[13:50:04.784 UTC] :0 : Warning: QCommandLineParser: argument list cannot be empty, it should contain at least the executable name
qTox:
```

Maybe to be expected without the other commits, at d2fe222b89b [2]:

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

At commit fd930cfbb21 [3] qTox still runs, but I saw this when terminating:

```
[13:44:18.200 UTC] main.cpp:76 : Debug: Cleanup success
[13:44:18.200 UTC] main.cpp:452 : Debug: Exit with status 0
qtox: pthread_mutex_lock.c:94: ___pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
Aborted
```

1. https://github.com/qTox/qTox/commit/665a6c4e3df0ffb2e2be20da3b0c60d9a6c7a0d5
2. https://github.com/qTox/qTox/commit/d2fe222b89b71dbaaf8a7fb4213e1c729383c5c1
3. https://github.com/qTox/qTox/commit/fd930cfbb219ec64e3b55f1d28a254c21af874bc

##### Expected Behavior

qTox executes as intended.

##### Additional Info

Also reported by CalimeroTeknik via IRC at #qtox.

**Comment by sudden6** [comment]
@Chiitoo It seems that this makes it impossible to use qTox right?

@anthonybilinski We should probably try and execute the qTox binary in CI to detect such error earlier. Simple test case would be to check the output of `qtox --help` or something simillar.

**Comment by Chiitoo** [comment]
Indeed, it doesn't run at all beyond that (and some normal output before that point but not far at all).

**Comment by sudden6** [comment]
@Chiitoo thanks for the report!

**Comment by sudden6** [comment]
I tried to reproduce on latest master, but didn't get the crash you're getting, seem to not affect all users.

**Comment by Chiitoo** [comment]
Yeah, seems odd.  @anthonybilinski mentioned the same in IRC.

Tried also on another machine with an earlier Qt version (5.15.3) in case something went odd there, but the same thing happens with it.

Need to dive deeper methinks.

**Comment by sudden6** [comment]
I have had another report that the latest qTox git version in the Arch User Repository is also broken. @anthonybilinski I think that would be a good start to investigate this.

**Comment by anthonybilinski** [comment]
I'm able to repro a consistent segfault starting at 7c519c389536905594bc3291a5e379e15b97614d, only when building with release build, not debug build. AddressSanitizer doesn't find anything, and I don't see an obvious reason why this would break it. I'm testing on arch with Qt "5.15.4+kde+r168-1", but that commit did move around our QCommandLineParser usage so there's a good chance something's wrong there rather than with Qt.

Looking into it.

**Comment by anthonybilinski** [comment]
Fix ready for review at https://github.com/qTox/qTox/pull/6644.
