### ISSUE TITLE
24-hour timestamps

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#665]
In addition to the current options, if it's not too much trouble.

**Comment by agilob** [comment]
There are 24-hour timestamps possible to choose in general settings.

![timestamp](https://cloud.githubusercontent.com/assets/2544251/4961478/cf4e5a62-66ce-11e4-8240-c8cd0548e5fb.png)

please be more specific.

**Comment by ProMcTagonist** [comment]
OP a faget issue closed
