### ISSUE TITLE
Alert settings

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#666]
Choosing what messages trigger what alerts, like in XChat.

![hexchat alert settings](https://cloud.githubusercontent.com/assets/4358079/4961420/28b44054-66ce-11e4-88ca-aa3036b70f7f.png)

**Comment by agilob** [comment]
https://github.com/tux3/qTox/issues/483

**Comment by ProMcTagonist** [comment]
Search didn't turn that up but I see the settings panel in the responses, nice
