### ISSUE TITLE
qmake fails after cd24e97ebda0e36d976ef44763df032a9e859e07

### ISSUE THREAD

**Issue by infoman** [qTox/qTox#668]
$ /usr/lib/qt5/bin/qmake 
RCC: Error in 'res.qrc': Cannot find file 'translations/fr.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/ru.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/de.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/it.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/pl.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/fi.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/mannol.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/uk.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/pirate.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/bg.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/sv.qm'

**Comment by zetok** [comment]
Yes, qTox requires linguist to generate translation files now, you should look for it in your distro repo

**Comment by infoman** [comment]
hmmm, seems that build succeeds when installing linguist-tools, but the output of qmake is very confusing and makes me feel like there's an error and don't even try to run make
