### ISSUE TITLE
[Regression] Missing notifications in chat about status change

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#671]

**Comment by zetok** [comment]
on e1b95105bc322b3485a81a633391ee8d9214b425 there are still no status change notifications if there were no messages sent between clients

**Comment by tux3** [comment]
That's on purpose, apparently.
Make a separate issue and fight to death with whoever made that commit ?

EDIT: It was @dubslow's idea !
https://github.com/tux3/qTox/pull/422#issuecomment-58730256

**Comment by agilob** [comment]
it's a feature.

**Comment by agilob** [comment]
Can I make a regression about it?

Didn't start conversation, I have all status changes in history. Who else thinks it's a bug?

![bug1](https://cloud.githubusercontent.com/assets/2544251/4967431/e80e5820-6810-11e4-9e84-76addba35d04.png)

**Comment by zetok** [comment]
It's a feature to me.

**Comment by agilob** [comment]
Why do you need those notification from not started conversations?

**Comment by zetok** [comment]
I don't need them, just prefer them to be there.

Edit: Actually one can use those notifications to determine how reliable core is..

**Comment by agilob** [comment]
I think I'll add another setting for this, because I hate it... 

![znowu1](https://cloud.githubusercontent.com/assets/2544251/4967638/b09fdc94-681d-11e4-8e62-9f69b31b62bb.png)

Oszczędzaj RAM gdziekolwiek jestes!

**Comment by zetok** [comment]
What you've shown is an example of core malfunctioning, along with  #676, which was supposed to be fixed

Edit:
![core](https://cloud.githubusercontent.com/assets/3148759/4967678/6159a3ca-681f-11e4-9f70-3eb5c7782093.png)

**Comment by agilob** [comment]
> What you've shown is an example of core malfunctioning, along with #676, which was supposed to be fixed

No, my internet connection is shit. Second day with broken fibre line in city I'm in....

**Comment by zetok** [comment]
![#676](https://cloud.githubusercontent.com/assets/3148759/4967684/c686965e-681f-11e4-9857-953254d78dc5.png)
↑ #676
