### ISSUE TITLE
[Trivial] Status options aren't capitalised.

### ISSUE THREAD

**Issue by bricky149** [qTox/qTox#674]
Self-explanatory.
![qtoxmenu](https://cloud.githubusercontent.com/assets/4836781/4964757/996cd4a6-6763-11e4-8db6-a4a943b972f7.png)

**Comment by suhr** [comment]
But should they?

**Comment by tux3** [comment]
I think so ?

Other programs capitalize every options in the tray menus too.

**Comment by zetok** [comment]
They definitely should be. Without capitalization they looked disgusting.
