### ISSUE TITLE
Crash after accepting a friend request

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#681]
Reported by @zetok 

qTox was in tray, crashed after clicking accept.

Log ends with:
Settings: Saving in  "/home/zetok/.config/tox/settings.ini"
Core: writing tox_save to  "/home/zetok/.config/tox/zetok.tox"

**Comment by zetok** [comment]
I was able to reliably reproduce it. Sent from µTox.
FR message contained:

```
asdf asdf
muh FR
```

When under gdb:

```
[Inferior 1 (process 29857) exited normally]
```

From libtoxcore.log:

```
============== Starting logger [29857] ==============
Time: Sun Nov  9 13:02:07 2014

[29857] [DEBUG] [0] [network.c:570 new_networking()] Dual-stack socket: enabled
[29857] [DEBUG] [0] [network.c:584 new_networking()] Local multicast group FF02::1 joined successfully
[29857] [DEBUG] [0] [network.c:613 new_networking()] Bound successfully to [::]:33446
[29857] [DEBUG] [1] [msi.c:1584 msi_init_session()] New msi session: 0x7fffb4004900 max calls: 16
[29857] [DEBUG] [81810] [msi.c:1624 msi_terminate_session()] Terminated session: 0x7fffb4004900
============== Closing logger [29857] ==============
Time: Sun Nov  9 13:03:29 2014
```

**Comment by tux3** [comment]
> [Inferior 1 (process 29857) exited normally]

... that's not a crash ?

There's no backtrace, of course ?

**Comment by zetok** [comment]
None.

**Comment by dubslow** [comment]
Start setting breakpoints I guess (e.g. `break[widget.cpp:79` (https://github.com/tux3/qTox/blob/master/src/widget/widget.cpp#L795)).

Does this happen with other FR messages or without a message?

**Comment by tux3** [comment]
I think that this is fixed, can anyone reproduce ?

**Comment by dubslow** [comment]
This one's weird, that's for sure.

Core::acceptFriendRequest appears to be run, since I get my debug statement from it, but when I set a break point for the line immediately after the debug statement, gdb swears there's no threads and that qTox has already exited.

```
void Core::acceptFriendRequest(const QString& userId)
{
    int friendId = tox_add_friend_norequest(tox, CUserId(userId).data());
    if (friendId == -1) {
        emit failedToAddFriend(userId);
    } else {
        saveConfiguration(); // 713
        qDebug() << "Core: accepted friend, setting Widget"; // 714
        emit friendAdded(friendId, userId); // 715
    }
}
```

```
break core.cpp:715 
Settings: Saving in  "/home/bill/.config/tox/settings.ini"
Core: writing tox_save to  "/home/bill/.config/tox/Dubslow.tox"
Widget: friend request dialog done
Settings: Saving in  "/home/bill/.config/tox/settings.ini"
Settings: Saving in  "/home/bill/.config/tox/settings.ini"
Core: writing tox_save to  "/home/bill/.config/tox/Dubslow.tox"
Core: writing tox_save to  "/home/bill/.config/tox/Dubslow.tox"
Core: accepted friend, setting Widget // THIS IS LINE 714 EXECUTING
[Thread 0x7fffc48d6700 (LWP 5508) exited]
AL lib: FreeContext: (0xc5e290) Deleting 1 Source(s)
[Thread 0x7fffc57d7700 (LWP 5505) exited]
[Thread 0x7fffc5fd8700 (LWP 5503) exited]
[Thread 0x7fffca7da700 (LWP 5502) exited]
[Thread 0x7fffb3ffe700 (LWP 5510) exited]
[Thread 0x7fffd9dd6700 (LWP 5497) exited]
[Thread 0x7fffd0f51700 (LWP 5498) exited]
[Thread 0x7fffdc173700 (LWP 5496) exited]
[Inferior 1 (process 5491) exited normally]
(gdb) break core.cpp:715
Breakpoint 1 at 0x473786: file src/core.cpp, line 715.
(gdb) info threads    // BUT AT LINE 715 THERE ARE ALREADY NO THREADS?
No threads.
(gdb) n
The program is not being run.
```

Edit: I just confirmed that setting the break point at 713, one line _before_ the debug, gives the exact same result: the message is already printed and the program is already terminated.

Here's another symptom: upon restarting, the receiving qTox doesn't see the friend supposedly accepted in the friend's list; but if the sender removes and readds the receiver, then the sender immediately appears in the receiver's friends list with no request dialog being presented. So how come the friend isn't shown upon restart, and it takes a secondary FR for the sender to appear?

@tux3

**Comment by suhr** [comment]
Rejecting a friend request causes the same thing.

**Comment by tux3** [comment]
Now that sounds like fun.

**Comment by dubslow** [comment]
Hoyl fucking derp, can you say "that makes no sense"

**Comment by tux3** [comment]
Actually, that makes a ton of sense. That's just incredibly stupid in this case.
When you close all windows, Qt exits ...

**Comment by dubslow** [comment]
Ya, except they're not closed, just minimized. Huge difference.

**Comment by tux3** [comment]
Well I agree that it's a bit confusing to exit on close() but not on hide(), and still count hide()-en windows as closed...
