### ISSUE TITLE
Create a qTox updater, for Windows only at first

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#683]
Related to #263

See branch autoupdate

I'm writting down some detailed info because I'm going to forget half of it otherwise...

<hr/>

I'm making an auto-updater for qTox, at first it'll work on Windows only since the environment is much simpler (dump all files in the working directory, C:/Program Files/qTox/bin/), whereas on Mac/Linux you need to get the install paths right or you wreck the system ...

Everything is signed with ed25519 using libsodium (because that's what toxcore uses, so we get it for free), if ANY data or metadata is tampered with the updater will abort immediately. 
qTox has a hardcoded [update server/public key] pair (which points to [127.0.0.1/my public key] right now, since I don't have a real server), but all the tools to make a third party update server are available. Except the private key, obviously.

How it works roughly:
- Connect to the update server (with HTTP(S)), get /qtox/win32/version, if it's different from our GIT_VERSION, an update is available and we keep going (if the user agrees)
- Get the flist (/qtox/win32/flist), a list of every file in the new update along with where to install them and their signature
- Compare with our local flist, and build a diff, a list of files we need to download
- Create an empty ./update/ folder in our usual AppData location (because you don't need admin privilege to write there), write the diff flist and download the update files there (GET /qtox/win32/files/$FILE). The diff isn't signed, but nobody cares, it the difference of two signed files. If localhost wants to tamper with it, it's localhost's problem.
- Exit qTox, on the next restart, if the update folder exists, start the update tool and exit.
- The update tool install the updates, deletes the update folder, and restart qTox

This is a bit harder to get right than I though. 1000 lines of code already and all it does is get a list of files to update. But it should be rock solid.

<hr/>

**Comment by HostFat** [comment]
Thank you! :)

**Comment by zetok** [comment]
IMHO creating autoupdater for Linux is a waste of time, since there are Tox repos in which qTox is available for rpm/deb based distros. Arch has their unsupported AUR stuff, and for Gentoo there's overlay.

**Comment by tux3** [comment]
Agreed, that's the package manager's job. 
But just in case we ever need it, the updater is generic, it should work on any OS and for any purpose.

**Comment by dubslow** [comment]
I agree that on GNU-Linux it's largely pointless.

Is it possible to install Mac programs from the command line? (I.e., the equivalent of `dpkg -i qtox.deb` except for .dmgs or .apps or however Macs work) If so, then we don't need to bother installing anything manually and it would be simpler than Windows.

**Comment by tux3** [comment]
The code is pretty much ready for Windows, now I have some packaging and sysadmining to do...

If anyone finds a gaping flaw in the security (or anything really), do tell. I'm a bit tired so it's possible I missed something obvious/did something stupid.

TODO: 
- Update the update server tools so that they are actually usable
- Add a qTox-win32-updater build to my Jenkins, ship the result with the qTox installer
- Host the update server on Amazon EC2 ?

**Comment by dubslow** [comment]
@stqism can host

**Comment by tux3** [comment]
@dubslow @stqism 
What I would need is a public facing HTTP server w/ FTP/SSH or anything else that I can script to push updates automatically, and that can handle maybe ~50MB of traffic per day for now.
And of course it needs to be absolutely positively one hundred percent perfectly safe, if someone were to find the update server's private key it's game over for anyone with updates on.

Is that possible ? Should I just go get a free EC2 ?

**Comment by tux3** [comment]
I made an Amazon S3 bucket here :  https://s3.amazonaws.com/qtox-updater/

**Comment by tux3** [comment]
This SHOULD work with the lastest version of qTox. Probably.

Updates are pushed to Amazon S3 only every saturday, because I'm on the free tier.

**Comment by stqism** [comment]
Minor update for people watching this issue, qTox on OS X now fully supports the updater and pushes signed updates to the Tox build CDN within minutes of toxcore or @tux3 pushing a commit.

The key used to sign is isolated away on a machine that only we have have access to, and not hosted on some VPS.

Also note that the OS X pkg and app are codesigned by our keys for extra redundancy.

**Comment by rugk** [comment]
According to the Readme also Linux installers are there now.
