### ISSUE TITLE
Optional specific messages for failedTo* signals (/src/core)

### ISSUE THREAD

**Issue by saneki** [qTox/qTox#684]
Maybe have an optional QString param for the failedTo\* signals for more specific error messages in certain cases? For example, earlier I was trying to add a friend that was already in my contact list, and got the error "Couldn't request friendship" when "Couldn't request friendship: Friend is already added" or something similar would have been more helpful.

I'm willing to implement this, but want to get some feedback.

**Comment by tux3** [comment]
I've always meant to do this, but somehow I haven't done it yet.

If you want to implement it, go ahead, otherwise I'll do it later.

**Comment by tux3** [comment]
Merged in fbbffc08062002af1a0077ccf4a57c13dd4eda61
