### ISSUE TITLE
can't open qTox on my mac (OSX)

### ISSUE THREAD

**Issue by StorytellerKaji** [qTox/qTox#685]
Hi, I downloaded the most recent qTox on my mac, and I can't get it to open. Here's the error log I get:

Process:         qtox [197]
Path:            /Applications/qtox.app/Contents/MacOS/qtox
Identifier:      im.tox.qtox
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [108]

Date/Time:       2014-11-09 10:34:54.551 -0800
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6

Interval Since Last Report:          7029705 sec
Crashes Since Last Report:           66
Per-App Crashes Since Last Report:   5
Anonymous UUID:                      D660B3FB-22BC-4B8D-85C0-9FB97527B45C

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000
Crashed Thread:  0

Dyld Error Message:
  Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /Applications/qtox.app/Contents/MacOS/qtox
  Reason: image not found

Binary Images:
    0x7fff5fc00000 -     0x7fff5fc3be0f  dyld 132.1 (???) <29DECB19-0193-2575-D838-CF743F0400B2> /usr/lib/dyld

Model: iMac9,1, BootROM IM91.008D.B08, 2 processors, Intel Core 2 Duo, 3.06 GHz, 4 GB, SMC 1.45f0
Graphics: NVIDIA GeForce GT 130, NVIDIA GeForce GT 130, PCIe, 512 MB
Memory Module: global_name
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x8E), Broadcom BCM43xx 1.0 (5.10.131.42.4)
Bluetooth: Version 2.4.5f3, 2 service, 19 devices, 1 incoming serial ports
Network Service: AirPort, AirPort, en1
Serial ATA Device: WDC WD1001FALS-40K1B0, 931.51 GB
Serial ATA Device: OPTIARC DVD RW AD-5670S
USB Device: USB2.0 Hub, 0x05e3  (Genesys Logic, Inc.), 0x0606, 0x26400000 / 2
USB Device: USB Reader, 0x058f  (Alcor Micro, Corp.), 0x6337, 0x26430000 / 4
USB Device: Apple Optical USB Mouse, 0x05ac  (Apple Inc.), 0x0304, 0x26420000 / 3
USB Device: Built-in iSight, 0x05ac  (Apple Inc.), 0x8502, 0x24400000 / 3
USB Device: My Book 1110, 0x1058  (Western Digital Technologies, Inc.), 0x1110, 0x24100000 / 2
USB Device: IR Receiver, 0x05ac  (Apple Inc.), 0x8242, 0x04500000 / 2
USB Device: DasKeyboard, 0x04d9  (Holtek Semiconductor, Inc.), 0x1919, 0x06200000 / 3
USB Device: BRCM2046 Hub, 0x0a5c  (Broadcom Corp.), 0x4500, 0x06100000 / 2
USB Device: Bluetooth USB Host Controller, 0x05ac  (Apple Inc.), 0x8215, 0x06110000 / 5

**Comment by tux3** [comment]
You seem to be missing a library called /usr/lib/libc++.1.dylib, that's probably a packaging problem.

@stqism @urras

**Comment by StorytellerKaji** [comment]
Thank you- I downloaded my copy yesterday from the qTox link under OSX on the binaries page (https://wiki.tox.im/Binaries).

**Comment by dubslow** [comment]
The age of the OS is probably related.

**Comment by stqism** [comment]
Found the issue, `OS Version: Mac OS X 10.6.8 (10K549)`

@dubslow Correct

@tux3: It's neither a bug nor packaging.

@StorytellerKaji:
When building OS X applications you use something called weak linking that lets you run it on older versions of the OS X nicely by not depending on things not in older versions. (Something Linux really needs)

As Apple stopped supporting `10.6.x` years ago and Qt5 only supports `10.7+` we consciously chose to make so the binaries were weak linked against `10.7` because it wouldn't run on older versions of the OS regardless.

**Comment by ghost** [comment]
This information could be useful in README.md. Something like

> This client runs on Windows, Linux and Mac (10.7 or newer) natively.

instead of just

> This client runs on Windows, Linux and Mac natively.

maybe?

**Comment by stqism** [comment]
@kehugter I disagree, we shouldn't have to specify that long depreciated versions of OSes aren't supported.

May as well add a not supported on Windows 2000 and Debian 4 note too if we're playing that game.

OS X's case is fun though, Apple only supports the last 2 major versions and sometimes the one right after as the majority of users happen to always run the latest version and they've got a run fast policy that works.

I'm sure more people use Windows 2000 and lower than things before 10.7 as well.

That note is incorrect for another reason as well, you can technically get qTox working on 10.6 but OS X has changed so much that we'd have a ton of bugs and issues on 10.10/10.9 if we did so.

**Comment by ghost** [comment]
I see, @stqism. Since the hardware specs prevent users with old computers from updating to newer OSX major releases, I thought there would be more people in the same boat (it's not my computer, I'm a novice in everything Mac-exclusive).

> That note is incorrect for another reason as well, you can technically get qTox working on 10.6

For the record, I was referring more to the "native" part.
