### ISSUE TITLE
Add option to show chat in front when receiving a notification 

### ISSUE THREAD

**Issue by darkcoconuts** [qTox/qTox#688]
I use this option in skype 'when somebody starts a chat with me...' 'open a chat window in front of me'
When I get a new message skype opens itself to the person who sent me a message. This is a good option for those who don't like audio notifications, or can't hear them and is useful when the user isn't around to hear them so they can see they've gotten a message upon returning. 

I started adding this option in my fork https://github.com/darkcoconuts/qTox but I'm new to github, qt and c++ so I've only added the option and had it call this->show which only opens tox to whereever it was and not to the contact and I didn't do anything with the translations. 

I'd love to help add this option myself but I think I need a little help from this point on in regards to how the translations are handled and how to go about tracking which contact sent a message so we can open qtox to them.

**Comment by dubslow** [comment]
Translations are simple, you only wrap whatever UI string you have in a `tr()` call. The only thing you need to do in a .ui file is `<string comment="Note to translators (e.g. about context)">String to tr</string>`, and even the context is optional (so as it is now is totally fine).

Your code is good, what's your background? For "new to github, qt and c++" you've done it pretty much exactly how any other dev would have.

I'll do the rest right now or within a few hours, hopefully that'll get you started on more qTox internals.

**Comment by darkcoconuts** [comment]
I've done some java in school and know a bit about object oriented programming along with watching some qt tutorials a while back, so I'm not totally new. Adding this kind of option wasn't too hard because I just searched the codebase for closetotray and copied what I needed and the code seemed easy to read. 

Thank you for the kind words and for finishing off the feature, I'll be keeping an eye out for other ways to contribute.

**Comment by dubslow** [comment]
Hmm, it doesn't actually unminimize for me, though it does switch to the proper chatroom.
