### ISSUE TITLE
Setting alias isn't persistent for some contacts

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#697]
I'm not sure why, but it so far didn't work only for 1 contact (I havent' tried with all contacts). I'm able to successfully set an alias for some contacts, but when I try to set an alias `stqism` for contact named `Sean` it's reverted when I restart qTox.

Pls fix, I really need to be able to set `stqism` as an alias.

**Comment by apprb** [comment]
Can you check the toxId length of this contact in settings.ini file?

**Comment by zetok** [comment]
There was an improvement, I was able to set `stqism` as an alias for `Sean`.

Unfortunately it doesn't seem to work all the time.

I've added new contact and set an alias while contact still was shown as ID only. Contact came online, I've restarted qTox, and after restart alias wasn't set.

**Comment by zetok** [comment]
Strange, setting alias again for same contact worked.

**Comment by zetok** [comment]
Actually setting `stqism` for `Sean` worked only across few reboots, and then it was reset to being without an alias.

I suspect that it happens due to me running 2 instances of qTox, which overwrite settings.ini

I just launch 2 instances of qTox, and in one of them switch to another profile.

I wasn't able to reliably reproduce, it just happens.

**Comment by dubslow** [comment]
Running two instances is not supported, for the reason you mentioned. (Running them as two different users might work though.)

**Comment by zetok** [comment]
It still doesn't work, though this time for different contact.

Alias of contact contained some japanese letters, `(`, `)`, spaces, some letters from latin alphabet and IIRC `,`.
After some restarts it was reduced to just some japanese letters.

**Comment by TheLastProject** [comment]
qTox lost an alias I set to someone once, but it did persist the second time. I have not been able to reproduce the issue.

**Comment by zetok** [comment]
Thanks to `Sean` coming online I have confirmation of my suspicion: **alias is changed to peer's nick**.

Happened with 2 contacts already.

Pls fix.

**Comment by dubslow** [comment]
Still an issue?

**Comment by tucnak** [comment]
Reporting in, can confirm for current master.
