### ISSUE TITLE
qtox-updater.exe crashes

### ISSUE THREAD

**Issue by Draako** [qTox/qTox#702]
With auto-update on I get this error every time I start qTox:

`The application was unable to start correctly (0xc0000005).`

Dump files:

https://mega.co.nz/#F!0ElCQSJT!qixzjsU2c9_3MpSiSF884Q

**Comment by tux3** [comment]
Auto-updates are experimental, I wouldn't recommend to use them until at least next week.

I'll try to fix this and in the meantime you can delete the folder %APPDATA%/tox/update/ to make qTox start again.

**Comment by tux3** [comment]
This should be fixed. Note that auto-updates are still very much experimental, I'd still wait until next week.
