### ISSUE TITLE
The provided Linux binary didn't run for me

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#71]
That's the July 1st version mentioned in the README.

It fails thusly: `./toxgui 
./toxgui: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'CXXABI_1.3.8' not found (required by ./toxgui)`

I'll try and compile it myself in the next 24 hours or so and see what (if anything) is up.

This is up-to-date Mint 17.

**Comment by msteinbeck** [comment]
stackoverflow says:

> GCC 4.9 introduces a newer C++ ABI version than your system libstdc++ has...

I think the Linux binary was build with Arch Linux which seems to be not runnable on Ubuntu/Mint.

**Comment by tux3** [comment]
The binary was build with Debian Sid, wich uses a very recent C++ ABI. I'll try to link it statically next time.

Closing, but next time I build a linux binary, it should work.
