### ISSUE TITLE
Show identicons instead of default picture of no avatar

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#711]
Subj.

**Comment by tsdko** [comment]
What kind of identicons would fit the current design?

**Comment by tux3** [comment]
Personally I'm not too fond of identicons, but if that's what people want, why not.

@ItsDuke what do you think ?

**Comment by zetok** [comment]
IMHO they shouldn't replace default avatar

**Comment by ItsDuke** [comment]
@tux3 I agree, I really don't like the way they look. I mean I suppose there could always be an option to simply have your avatar be an identicon as opposed to uploading an image, but I don't think it should be on by default.

**Comment by suhr** [comment]
> I suppose there could always be an option to simply have your avatar be an identicon as opposed to uploading an image, but I don't think it should be on by default.

I actually mean having identicons in friend list.

**Comment by agilob** [comment]
A way to avoid adding indentation (ugly empty field) and to keep avatars it to swap status icon with avatar:
![virus1](https://cloud.githubusercontent.com/assets/2544251/5015593/00b1912a-6a97-11e4-8351-499277217595.png)

How do you like that?

**Comment by dubslow** [comment]
Just about every other program in the world with avatars has them on the left

**Comment by suhr** [comment]
> Just about every other program in the world with avatars has them on the left

This. Avatars identify users even more than names. That's why I ask for identicons support, actually.

**Comment by apprb** [comment]
I can agree that feature like aliases for names but for avatars potentially is good. 
But implementing identicons in the client... I don't think it is a good idea.

**Comment by lehitoskin** [comment]
@dubslow In pidgin, the avatars are on the right.

**Comment by zetok** [comment]
Is there any good argument against identicons, as an opt-out feature?

Since they will be generated based on PK, what can be used for it, that would produce visually exactly the same image regardless of the output image resolution?

Is that doable?

**Comment by ovalseven8** [comment]
> Is there any good argument against identicons, as an opt-out feature?

Personally, I really like the idea to have identicons based on the PK. And if the user doesn't like the identicon, he could just choose another avatar. Because of that (and because too many options are not good anyway), it should not even be opt-out.

**Comment by ProMcTagonist** [comment]
With the stipulation that identicons be generated locally, without contacting any of the popular webservices that make them, I agree with @ovalseven8.

**Comment by SkyzohKey** [comment]
![](http://i.imgur.com/zXXlIrF.png)

**Comment by ovalseven8** [comment]
@SkyzohKey: Based on https://gist.github.com/benwaffle/35ad7d6c49a6336ea1a8?

**Comment by SkyzohKey** [comment]
The hsl2rgb/parse_base16 functions are from @benwaffle, yes. The @benwaffle code is a rewrite of this → https://gist.github.com/SkyzohKey/83e8e4c9ae2ef54db602

**Comment by Getron** [comment]
But please, without the ugly white background of icon. It would not match the dark background of client.

**Comment by zetok** [comment]
I wrote something that could be used as identicon, and that actually represents PK. Image made from a random PK:

![out](https://cloud.githubusercontent.com/assets/3148759/20437626/9516b23c-adac-11e6-8d6a-af376854ccbf.png)

Would there be interest in it?

**Comment by zetok** [comment]
Reworked it, previous one looked ~ugly. The downside of new approach is that PK data is only duplicated.

![out](https://cloud.githubusercontent.com/assets/3148759/20441391/353f7582-adbc-11e6-8413-f7f94344f063.png)

![spectacle jd8726](https://cloud.githubusercontent.com/assets/3148759/20441397/3ea0bf78-adbc-11e6-845b-6d00e1973d6b.png)
↓
![spectacle cf9900](https://cloud.githubusercontent.com/assets/3148759/20441401/4392e362-adbc-11e6-8b79-4490e97dd627.png)

**Comment by ovalseven8** [comment]
The identicons by @SkyzohKey look much better IMHO: https://github.com/qTox/qTox/issues/711#issuecomment-202103191

**Comment by zetok** [comment]
@ovalseven8 ~yeah. With that in mind:
1. There is no spec for @SkyzohKey's implementation, and their implementation being in vala means that it won't be used in clients, aside from @SkyzohKey's client. My implementation in Rust can provide easy to use, statically linked lib with C interface that all clients could easily compile & use.
2. It doesn't provide info about the PK, while what I've implemented is a "pure" PK, and if someone wanted, they could decode that to the PK.

Note that color "scheme" of my implementation could be changed.

**Comment by zetok** [comment]
![out](https://cloud.githubusercontent.com/assets/3148759/20444026/502b93e8-adc7-11e6-9863-d3256e754cf5.png)
![out](https://cloud.githubusercontent.com/assets/3148759/20444070/8235203e-adc7-11e6-9c2d-c9129256a644.png)
![out](https://cloud.githubusercontent.com/assets/3148759/20444172/e5cc7e80-adc7-11e6-87a2-5d60e17a0dfd.png)

**Comment by benwaffle** [comment]
@SkyzohKey 's implementation is based on github's identicons. It can be easily ported to C and other languages

**Comment by zetok** [comment]
@benwaffle are there any docs?

**Comment by benwaffle** [comment]
@zetok nope, it was just ported from JS https://github.com/stewartlord/identicon.js

**Comment by zetok** [comment]
Well, if there would be, I could write it in Rust.

**Comment by sudden6** [comment]
@zetok Since you seem to have all the complicated code for drawing the image already, I think it would be easy to port the algorithm from JS to Rust.

If you don't want to do it, maybe I can do it.

EDIT: It would also be better to create the identicon from a hash of the private key, this way it can't be faked.

**Comment by zetok** [comment]
@sudden6 well, the code isn't really that compilcated, the main logic is just a single line, rest is just colors & mirroring the image created from PK: https://gist.github.com/zetok/2a2dab30e75666e89bcc6c8467cace48#file-main-rs-L83

All the heavy-lifting is done by a lib :)

**Comment by sudden6** [comment]
I also did an identicon algorithm based on https://github.com/stewartlord/identicon.js/blob/master/identicon.js but extended it to compute two colors from the hash. Additionally the algorithm ensures that there will be always a light and a dark color, to aid colorblind people. See these examples:

![out0](https://cloud.githubusercontent.com/assets/5585762/20608588/735f96e6-b283-11e6-8ba7-3b58f0bde80c.png)
![out1](https://cloud.githubusercontent.com/assets/5585762/20608589/73618d16-b283-11e6-8818-c59e08ee0b63.png)
![out2](https://cloud.githubusercontent.com/assets/5585762/20608590/73627e06-b283-11e6-9089-3286f7661a13.png)

What do you all think of them?

**Comment by ovalseven8** [comment]
Looks fine.

More important, however, is that if clients use identicons that they use the same library IMHO. If I use two different clients it would be nice to have the same identicons too :)

**Comment by sudden6** [comment]
@ovalseven8 yep, I plan to write a specification on how to generate them and publish a library for that.

**Comment by SkyzohKey** [comment]
@sudden6 
>EDIT: It would also be better to create the identicon from a hash of the private key, this way it can't be faked.

Ricin already does that by hashing the public key with SHA512 before generating the identicon :)

**Comment by sudden6** [comment]
@SkyzohKey so Ricin is setting a default avatar with identicon(SHA512(SK))?

After a little bit more thinking I came to the conclusion that making the identicon from the SK is useless, because you're basically broadcasting the avatar to anyone who you're "friends" with, so it can be easily copied.

I think it's better to generate the identicon from the PK on the client side, this way it's guaranteed that the PK of the identicon matches the PK of the friend. But the clients would need a way to signal the difference between an identicon and the custom avatar, this way there would be no sense of false security.

**Comment by SkyzohKey** [comment]
@sudden6 that's why the identicon is never sent to friends, only kept local until you use a real avatar. Letting the friend's client decide whether to display a blank avatar or an identicon. 

EDIT: Nope, ricin works like `identicon(SHA512(PUBLIC_KEY))` for friends/self and `identicon(SHA512(GROUP_NAME))` for groupchats. x)

**Comment by sudden6** [comment]
@SkyzohKey ah, sorry I misread that. Then it's the same thing that I meant. What is the point in hashing with SHA512 instead of SHA256, Tox PKs are only 256 Bit anyways?

**Comment by SkyzohKey** [comment]
@sudden6 no real point here, that was a fully subjective choice x')

**Comment by leafcutterant** [comment]
+1 for identicons. @sudden6, i like your idea of only two colors.
