### ISSUE TITLE
[Regression] Status is reverted from "Busy" to "Online"

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#715]
Auto-away is set to `0`, and I don't exactly know what causes status to be reverted. Happens after some period of time.

Edit: qTox 9e7ee848e88dd359224f55a6c066ea1819125268
Edit2: 133fb2f9d3edeb7d7ca58908ca92a9753c3f7c66 is also affected

**Comment by dubslow** [comment]
Hmm, very strange indeed. Can you confirm that there are no messages about auto away being activated?

At any rate, it's only supposed to be activated when the status is online, and not when it's busy (and that of course only when set).

**Comment by zetok** [comment]
Haven't seen any. From what I remember there were no messages in log whatsoever about status change.

I'll look for it though, and if I'll notice anything relevant I'll drop a comment.

**Comment by dubslow** [comment]
I added a print when status is changed to online.

**Comment by zetok** [comment]
I see

```
Widget: something set the status to online
```

Edit:
From code it would seem that ↑ should be printed when status changes due to r-click on tray icon and changing status, right? Too bad that I haven't made any r-click..

Edit2: although I did l-click to open qTox from tray

**Comment by dubslow** [comment]
@zetok Can you say one way or the other whether this is still an issue?

**Comment by zetok** [comment]
Doesn't seem to be an issue any longer.

**Comment by zetok** [comment]
Actually it's still reproducible, and log seems to show what triggers it:

```
Core: Dropped audio frame
Core: Dropped audio frame
Core: Dropped audio frame
Core: Disconnected to DHT
Core: Connected to DHT
Settings: Saving in  "/home/zetok/.config/tox/settings.ini"
Core: writing tox_save to  "/home/zetok/.config/tox/zetok.tox"
Widget: something set the status to online
Core: Dropped audio frame
```

Edit: qTox 0608989f16a2787cadbb11bb1adf8b292d2c96b5

:3

**Comment by dubslow** [comment]
Ah, you didn't go from busy to online, you went from busy to offline to online.

**Comment by tux3** [comment]
Something's wrong with how we get disconnected/reconnected from the DHT for no reason at all.

I tried unplugging my ethernet cable with qTox running and it took a good 20s for that to register and qTox to get disconnected. But sometimes this thing happens and you get disconnected in a split second even though everything's fine.
