### ISSUE TITLE
[Feature request] Detect new audio devices on runtime

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#724]
Currently qTox doesn't detect new audio devices on runtime.

To test:
`# modprobe snd-dummy` ← spawns dummy audio device, qTox should be able to detect it on runtime

Use case: pluggable USB sound cards, etc

**Comment by zetok** [comment]
As far as little of testing could tell, it now works for me.

**Comment by dubslow** [comment]
There was a slight code change committed that we all forgot to comment about here
