### ISSUE TITLE
Virus detected !

### ISSUE THREAD

**Issue by hk1mm** [qTox/qTox#731]
Hi.

GData internet security detect "qtox-updater.exe" of the latest release of qTox (only in the latest release) : https://github.com/tux3/qTox/releases/download/qtox-windows-1415790218.48/setup-qtox.exe as a virus. (Virus: Gen:Variant.Kazy.205528).

**Comment by suhr** [comment]
Actually, Virustotal doesn't find this.
https://www.virustotal.com/ru/file/7484c02690219f07e8ab2f06b8f88a39679af82d83aaa9012d4c0ea774c14d3b/analysis/1415805328/

**Comment by agilob** [comment]
![virus](https://cloud.githubusercontent.com/assets/2544251/5012948/00a6ecf8-6a82-11e4-9e30-f5c6d708a3f8.png)

**Comment by suhr** [comment]
Oh that heuristics.

**Comment by hk1mm** [comment]
I have sent the file to GData Laboratory to infirm/confirm this detection.. i will copy the report here as soon as GData respond..

**Comment by tux3** [comment]
Dammit I hate AV companies. They let anything serious slip through but you can't drop any files anywhere or you're flagged as malware. 
I hope they fix the false positive or I'll have to obfuscate things.

**Comment by hk1mm** [comment]
Message from GData :

Thank you for your sample/URL submission.
A ticket has been created for your submission and it has been placed into the processing queue. 
Our analysts will examine your submission and you will get a reply with the solution or with the verdict for the submitted files/URLs. 

Please note that we are getting a large number of submissions per day, so processing of your ticket may take time. 
Thank you for your patience.

Best regards,
SecurityResponse Team

**Comment by tux3** [comment]
Thansk @hk1mm

**Comment by hk1mm** [comment]
Hi... GData was updated : "qtox-updater.exe" is no longer detected as a virus. All files of actual latest release of qTox are CLEAN.

**Comment by tux3** [comment]
Thanks, @hk1mm
