### ISSUE TITLE
Invite not working on tempbot

### ISSUE THREAD

**Issue by dcharles525** [qTox/qTox#737]
getting error when submitting invite to tempbot

"Core: AV group invite by 10" 
"Trying to join AV groupchat invite sent by friend 10" 
Widget::onGroupInviteReceived: Unable to accept  group invite

**Comment by dubslow** [comment]
This is a core problem unfortunately, since those messages are printed only when toxav_join_av_groupchat returns -1. It's impossible to know why unless you activate core logging (which I believe is a compile time option, unfortunately).

**Comment by zetok** [comment]
@dcharles525 That was supposed to be fixed with 4bb91143d7288006dc3a46091f497c2e0f74e8ae , and it did in my case. Could you provide from log qTox commit you're on?

**Comment by dcharles525** [comment]
Looks like an update did the trick.
