### ISSUE TITLE
Group calls inconsistent.

### ISSUE THREAD

**Issue by Jookia** [qTox/qTox#741]
I'm chatting with karolherbst and anagromataf. Anagromataf can hear me, I can't hear either of them and karolherbst is having ALSA errors.

My log:

```
...
"Core: Leaving group call 0"
"Core: Joining group call 0"
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
"Core: Leaving group call 0"
"Core: Group namelist change 0:1 1"
Core::getGroupPeerName: Unknown error
"Core: Group namelist change 0:0 0"
Widget::onGroupNamelistChanged: Group not found, creating it
"Core: Group namelist change 0:0 2"
Widget::createGroup: Group already exists
"Core: Group namelist change 0:1 0"
"Core: Group namelist change 0:1 2"
"Core: AV group invite by 13"
"Trying to join AV groupchat invite sent by friend 13"
"Core: Group namelist change 1:0 0"
"Core: Group namelist change 1:0 2"
"Core: Group namelist change 1:1 0"
"Core: Group namelist change 1:1 2"
"Core: Group namelist change 1:2 0"
Widget::onGroupNamelistChanged: Group not found, creating it
"Core: Group namelist change 1:2 2"



"Core: Joining group call 1"
"Core: AV invite from 12 without video"
onAvInvite
onAvInvite
onAvInvite
onAvInvite
onAvInvite
onAvInvite
onAvInvite
onAvInvite
onAvInvite
onAvInvite
onAvInvite
onAvInvite
onAvInvite
onAvInvite
onAnswerCallTriggered
"Core: answering call 0 without video"
"Core: AV start from 12 without video"
"Core: preparing call 0"
onAvStart
onAvStart
onAvStart
onAvStart
onAvStart
onAvStart
onAvStart
onAvStart
onAvStart
onAvStart
onAvStart
onAvStart
onAvStart
onAvStart
onHangupCallTriggered
"Core: hanging up call 0"
"Core: AV ending from 12"
"Core: cleaning up call 0"
onAvEnding
onAvEnding
onAvEnding
onAvEnding
onAvEnding
onAvEnding
onAvEnding
onAvEnding
onAvEnding
onAvEnding
onAvEnding
onAvEnding
onAvEnding
onAvEnding
"Core: Leaving group call 1"
"Core: Joining group call 1"



"Core: Leaving group call 1"
"Core: Joining group call 1"
VideoSurface: Init
CameraWorker: Resume
CameraWorker: Resolutions (QSize(0, 0) ) 
CameraWorker: Suspend
CameraWorker: Resume
CameraWorker: Suspend
"Core: Group namelist change 1:0 1"
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
Core: toxav_group_send_audio error
```

**Comment by karolherbst** [comment]
My log:

Settings: Loading from  "/home/karol/.config/tox/settings.ini"
Using embeded bootstrap nodes list
built on:  18:56:46 Nov 13 2014 ( 1415901400 )
commit:  211005e8dee75d23ae7c921ef8fc1e8d04524ae0 

IPC: Our global ID is  5504395877786025544
IPC: Attaching to the global shared memory
service is "org.kde.StatusNotifierItem-2220-1"
Registering a client interface to the KStatusNotifierWatcher
Core: loading Tox from "/home/karol/.config/tox/4D9561062404.tox"
Core starting with IPv6 disabled. LAN discovery may not work properly.
Core::loadConfiguration: reading from  "/home/karol/.config/tox/4D9561062404.tox"
Core: Error loading self avatar
Core: Bootstraping to the DHT ...
"Core: Bootstraping from aitjcize, addr 54.199.139.199, port 33445"
"Core: Bootstraping from astonex, addr 37.59.102.176, port 33445"
Core: Connected to DHT
Settings: Saving in  "/home/karol/.config/tox/settings.ini"
Core: writing tox_save to  "/home/karol/.config/tox/4D9561062404.tox"
Widget: something set the status to online
Core: Disconnected to DHT
IPC: Previous owner timed out, taking ownership
Core: Connected to DHT
Settings: Saving in  "/home/karol/.config/tox/settings.ini"
Core: writing tox_save to  "/home/karol/.config/tox/4D9561062404.tox"
Widget: something set the status to online
Core: Disconnected to DHT
Core: Connected to DHT
Settings: Saving in  "/home/karol/.config/tox/settings.ini"
Core: writing tox_save to  "/home/karol/.config/tox/4D9561062404.tox"
Widget: something set the status to online
Core: Disconnected to DHT
Core: Connected to DHT
Settings: Saving in  "/home/karol/.config/tox/settings.ini"
Core: writing tox_save to  "/home/karol/.config/tox/4D9561062404.tox"
Widget: something set the status to online
"Core: AV group invite by 0"
"Trying to join AV groupchat invite sent by friend 0"
"Core: Group namelist change 0:0 0"
"Core: Group namelist change 0:0 2"
Widget::onGroupNamelistChanged: Group not found, creating it
"Core: Group namelist change 0:1 0"
"Core: Group namelist change 0:1 2"
"Core: Group namelist change 0:2 0"
"Core: Group namelist change 0:2 2"
"Core: Joining group call 0"
void QWindow::setTransientParent(QWindow_) QWidgetWindow(0x3dffc70, name = "QWidgetClassWindow") must be a top level window.
void QWindow::setTransientParent(QWindow_) QWidgetWindow(0x3e6e560, name = "audioGroupWindow") must be a top level window.
QXcbConnection: XCB error: 5 (BadAtom), sequence: 10569, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
QXcbConnection: XCB error: 5 (BadAtom), sequence: 10572, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
QXcbConnection: XCB error: 5 (BadAtom), sequence: 10601, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
QXcbConnection: XCB error: 5 (BadAtom), sequence: 10632, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
QXcbConnection: XCB error: 5 (BadAtom), sequence: 10661, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
QXcbConnection: XCB error: 5 (BadAtom), sequence: 10742, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
QXcbConnection: XCB error: 5 (BadAtom), sequence: 10745, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
QXcbConnection: XCB error: 5 (BadAtom), sequence: 10748, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
VideoSurface: Init
CameraWorker: Resume
CameraWorker: Resolutions (QSize(0, 0) ) 
CameraWorker: Suspend
AL lib: (EE) alsa_available_samples: avail update failed: Broken pipe
"Core: Group namelist change 0:1 1"
AL lib: (EE) alsa_available_samples: avail update failed: Broken pipe
AL lib: (EE) alsa_available_samples: avail update failed: Broken pipe
"Core: Leaving group call 0"
"Core: Group namelist change 0:2 0"
Group::addPeer: peerId already used, overwriting anyway
"Core: Group namelist change 0:2 2"
"Core: Joining group call 0"
AL lib: (EE) alsa_start_capture: start failed: File descriptor in bad state
Settings: Saving in  "/home/karol/.config/tox/settings.ini"
Core: writing tox_save to  "/home/karol/.config/tox/4D9561062404.tox"
Illegal instruction

**Comment by TheSiege** [comment]
i basically get Core: Dropped audio frame when karolherbst tries to talk
and sometimes 
Core: toxav_group_send_audio error 
sometimes

**Comment by tux3** [comment]
This should be fixed.

**Comment by karolherbst** [comment]
yeah I think I can confirm this. Thanks a lot
