### ISSUE TITLE
Error in video call

### ISSUE THREAD

**Issue by dcharles525** [qTox/qTox#743]
toxav_send_video error: -5

I get the error above when starting a video call, my video never shows up in the call but my audio is fine.

**Comment by tux3** [comment]
Note: -5 is ErrorNoRtpSession : Trying to perform rtp action on invalid session

This implies that toxav_prepare_transmission probably failed.

**Comment by tux3** [comment]
Can you try again with the latest version and tell me if you see a toxav_prepare_transmission error in the log ?

**Comment by dcharles525** [comment]
hm weird, I just tried the latest, and no issues video calling.... I am going to try and reproduce again.
