### ISSUE TITLE
If qTox doesn't exit cleanly whilst in a groupchat all messages aren't visible

### ISSUE THREAD

**Issue by bricky149** [qTox/qTox#747]
I couldn't see messages I sent either. Closing cleanly and rejoining the group worked around it.
![qtoxnomessagesaftercrash](https://cloud.githubusercontent.com/assets/4836781/5047763/34a812ae-6c10-11e4-85b6-acb92c9801ca.png)

**Comment by dubslow** [comment]
I don't understand the problem. You mean if clicking the X fails to exit cleanly (which I've never seen), then... something in the UI is borked? I mean, qTox did try to shut down... clearly I'm missing something.

**Comment by bricky149** [comment]
I ended the process myself instead of closing qTox (I came across #746 at the time). That is what I meant by 'unclean'.

**Comment by dubslow** [comment]
How did qTox fail to exit cleanly? That would seem to be a rather more serious issue.

**Comment by bricky149** [comment]
Like I said I ended the process manually because I lost the window. I had the tray icon disabled but with minimise to tray enabled.

**Comment by dubslow** [comment]
Ohhhh. So upon closing to tray, groupchat messages disappear? (Or all messages?)

**Comment by bricky149** [comment]
That's not it.
1. I join a group.
2. I end the process instead of closing normally.
3. I reopen qTox and rejoin the group.
4. I can't see messages I've sent or what others have sent.

I have to close it properly, reopen it and rejoin the group to work around the problem.

**Comment by dubslow** [comment]
Ah, much better.

That is indeed strange. So after ending qTox, and starting it again completely from scratch, no messages appear? And only if you close it again properly does restarting work?

**Comment by bricky149** [comment]
Yes, that's right. Does it sound like a database issue? I can't check now since I'm technically supposed to be asleep. :P

**Comment by dubslow** [comment]
Frankly I have no idea. And you've tested that this only applies to groupchats, not 1 on 1s?

@apprb thoughts?

**Comment by apprb** [comment]
Can't get your idea, sorry.
If you are asking about history in groupchats, then it is still not implemented and it is no way in the first place to retrieve messages from previous qtox runs.
But if qtox doesn't display any message at all during one run in groupchat (including yours) then this is the real problem.

**Comment by tux3** [comment]
> If you are asking about history in groupchats, then it is still not implemented and it is no way in the first place to retrieve messages from previous qtox runs.

This is what had me confused.
You're _not supposed_ to see any old message/history when you join a group, as far as I know.

**Comment by bricky149** [comment]
The screenshot was supposed to indicate I couldn't see my own, or other user's, messages.
I'm not sure how else I can phrase it.

**Comment by tux3** [comment]
Ah, ok. I get it.

That's very strange indeed. Can you post the qtox.log ?

**Comment by bricky149** [comment]
Currently at a political conference on my phone. I'll do so when I get home.

**Comment by bricky149** [comment]
Unable to reproduce at this time.
It may have something to do with the newly introduced synchronous DB write but since I'm using 'normal', and was tested using 'full', I'm not seeing any unexpected behaviour. If it was 'off' then I'd sort of understand.
Closing as invalid.
