### ISSUE TITLE
Bad scaling on high dpi screens

### ISSUE THREAD

**Issue by CrazyCrab** [qTox/qTox#75]
I have a small display with large resolution (166 dpi) and on it toxgui looks bad.
https://i.imgur.com/q1sdEfY.png
Looks like some things scale and others don't. Look at the screenshot - the black part is too narrow, the status texts are too small (looks like all other inscriptions scale with dpi but statuses don't).

**Comment by CrazyCrab** [comment]
Also tox id in settings is too small
https://imgur.com/3dbQGE4

**Comment by tux3** [comment]
You can now resize the black part (the friend list), and I made the Tox ID in settings way bigger.
I'll try to see what's wrong with the status texts.

**Comment by CrazyCrab** [comment]
Bigger Tox ID is good but not good enough.
See these 2 screenshots:
http://i.imgur.com/RuAMdNy.png http://i.imgur.com/Tr3BPen.png
First screenshot shows toxgui with dpi 96. Second screenshot shows toxgui with dpi 166. 
Notice that all fonts except font used for Tox ID are scaled, but  Tox ID remains the same size on both screenshots. It should be scaled too.

**Comment by CrazyCrab** [comment]
Btw you can change dpi (if you use GNU/Linux with X server) with command

```
xrandr --dpi 166
```

**Comment by tux3** [comment]
> Btw you can change dpi (if you use GNU/Linux with X server) with command

Didn't know that, I'll make some tests.
Edit: Actually it doesn't work on my computer, but I think I know what the problem is anyway

**Comment by stqism** [comment]
Tested qTox at 2560x1600 on a 13 inch screen, scaled perfect on my Mac http://i.x-n.su/015211211014.png

**Comment by tux3** [comment]
I tested on linux with 166 dpi on a small resolution (1366x768) to confirm and it scales right for me too.
https://i.imgur.com/ni158gE.jpg

It seems to be fixed, if someone still has this bug please leave a comment and I'll reopen.

**Comment by philip-bl** [comment]
Still has a few problems for me:
http://i.imgur.com/cvs6cZK.png

**Comment by philip-bl** [comment]
And some more problems:
http://i.imgur.com/4TjHjlM.png
- nickname and status get on top of each other
- no way to make nickname column in a conversation wider

**Comment by tux3** [comment]
I fixed the names getting on top of each other, and the icons being clipped.

The nickname column that you can't resize is imo a separate issue, since it's a problem regardless of DPI anyway, so I made an issue here : #514

As always if you still have a problem please comment and I'll reopen.

**Comment by philip-bl** [comment]
Another problem with names getting on top of each other in group chats (top left corner) 
http://i.imgur.com/bnCwt1N.png

**Comment by DanTheBritish** [comment]
How does one scale the application on windows? I don't see an option for it on the GUI.

**Comment by philip-bl** [comment]
I think in control panel in resolution settings there should be an option to scale all elements. I guess that's the analogue to setting dpi for xorg.

**Comment by DanTheBritish** [comment]
Wait I need to scale my whole OS? I can't just up the scaling of the application like uTox?

**Comment by dubslow** [comment]
@LapFox DPI means how the pixels are used. It's not something any program control, but is rather controlled by whatever is rendering the graphics, which typically makes the option available through the OS.

**Comment by DanTheBritish** [comment]
uTox seems to offer nice scaling (Maybe that's the wrong word then?) for my 1440p monitor with their 150% DPI setting. From what I see, there's no option in qTox for DPI adjust, so maybe I should open a different issue to add such feature.

**Comment by dubslow** [comment]
Huh, probably. Would you mind showing me a screenshot of the uTox option?

**Comment by DanTheBritish** [comment]
qTox: http://i.imgur.com/hC6SOnK.png
uTox (100% DPI): http://i.imgur.com/cPHTQlr.png
uTox (150% DPI): http://i.imgur.com/dtlw8EY.png

I prefer 150% DPI because the text size is much more readable. For reference, I'm using a 27" 2560x1440 display, with a DPI of 109.

**Comment by dubslow** [comment]
Oooh, nice.

@tux3 ^

**Comment by tux3** [comment]
Well, let's make a separate issue for that : #530
Although I'm not sure if that's (easily) possible with Qt.
