### ISSUE TITLE
Auto away firing while using qtox on windows

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#751]

**Comment by zetok** [comment]
I think that it happened for me too

**Comment by dubslow** [comment]
Could you be more specific please? You mean firing instantly or some such?

**Comment by tux3** [comment]
Someone reported that the auto-away changed the status to away while in the middle of using qTox, on windows.

I don't have more details and didn't try to repro yet.

**Comment by dubslow** [comment]
Oops, I forgot how it works somewhere along the way and messed it up a while ago.

I'll have a fix (along with some others hopefully) in a couple of hours.

**Comment by dubslow** [comment]
This is actually one of those cases where you look at the code and think "what moron wrote this code" and then you `git blame` and see the horrifying truth...
