### ISSUE TITLE
Mic button gets misaligned on two-line user list

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#752]
![snapshot105](https://cloud.githubusercontent.com/assets/1885159/5052943/b89eb812-6c45-11e4-87ac-64a3647179d5.png)

**Comment by TheLastProject** [comment]
Bug has returned:
![snapshot139](https://cloud.githubusercontent.com/assets/1885159/5509737/90127aa0-87bb-11e4-874f-e5c538bec98b.png)

My guess would be this is either related to 5861c6daa56eca4870f83c34badd22a59ba72db5 or f8d870f374749d059d91952df94880feb26ae69b but I have not bisected.

**Comment by tux3** [comment]
This is probably due to 5861c6daa56eca4870f83c34badd22a59ba72db5 apparently removing the blank stretches around the button.
