### ISSUE TITLE
Change of group chat title does not change qTox title bar

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#753]
If the group chat is titled "example", the qTox title bar is "example - qTox". However, if someone changes the group chat title to "another example", the qTox title bar remains "example - qTox", until you click the group chat again.

This may also happen with normal user renaming, but I have not tested this.

**Comment by dubslow** [comment]
> if someone changes the group chat title to "another example", the qTox title bar remains "another example - qTox"

Is that a typo?

**Comment by TheLastProject** [comment]
@dubslow Fixed, I'm tired, sorry :(

**Comment by dubslow** [comment]
Haha no worries man. Was wondering if I was misreading or something.
