### ISSUE TITLE
Need something to indicate who is currently talking

### ISSUE THREAD

**Issue by Zer0-One** [qTox/qTox#757]
In popular voice chat clients, you usually see something that indicates who is currently talking/making noise. In skype, this shows up as a blue outline around the avatar of the person speaking. In mumble, a set of lips next the user's name turns red.

There are a few different ways this could be implemented, but perhaps the simplest would be just hilighting the name (in the groupchat user list) of whoever is currently transmitting audio using a text outline.

**Comment by ProMcTagonist** [comment]
+1

**Comment by urras** [comment]
Yeah, uTox already has this. Also, it would be nice if qTox could highlight one's own nick (in uTox, one's own nick is highlighted in green). ![ayy](http://a.pomf.se/pobydj.png)

**Comment by zetok** [comment]
IMHO it's still not fixed, since relying on colours ~fails in case of visually-impaired people.

Please reopen.

**Comment by ProMcTagonist** [comment]
Agreed with @zetok, current speakers should be bolded (**not** everyone) in addition to being colored, and we should make sure the colors show up okay against white for colourblind users.

**Comment by dubslow** [comment]
https://github.com/tux3/qTox/blob/master/src/widget/form/groupchatform.cpp#L159

^ Line you can change to whatever and submit a PR, if you have a specific color in mind

**Comment by zetok** [comment]
@dubslow 
![muh colour change](https://cloud.githubusercontent.com/assets/3148759/6653124/9afe48e0-ca7d-11e4-9cd7-9b7b68f00411.png)

Beside that, **it's not about what colour is**, but rather, that only colour present doesn't solve problem.

There is needed additional indicator.
