### ISSUE TITLE
[Regresssion] qTox segfaults when making a call

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#760]
https://gist.github.com/zetok/cd75521a315b66fc5b48

Reproducible: always

Doesn't matter whether it's a direct call, or a groupchat.

Edit: segfaults when making a call to qTox (both instances segfault) or µTox (only qTox segfaults).

**Comment by tux3** [comment]
Stereo. We can't handle stereo.

toxcore is mono by default, but zetok has a patched toxcore.
