### ISSUE TITLE
Updater updates itself on launch every single time

### ISSUE THREAD

**Issue by stqism** [qTox/qTox#770]
Launch qTox from the CLI on OS X,

```
[sean@salyut.local:~] ~/Applications/qtox.app/Contents/MacOS/qtox
Settings: Loading from  "/Users/sean/Library/Preferences/tox/settings.ini"
Using embeded bootstrap nodes list
built on:  15:36:40 Nov 15 2014 ( 1416094555 )
commit:  007a10346db4a5c2f32e5958fb9a7570ec2b2322 

AutoUpdater::getLocalFlist: Can't open local flist
AutoUpdater::parseflist: Empty data
AutoUpdater: About to start the qTox updater to install a local update
[sean@salyut.local:~] installer: Package name is qTox
installer: Upgrading at base path /Users/sean
installer: The upgrade was successful.

[sean@salyut.local:~]
```

Relaunch it again, same issue.

Note that after installer finishes it closes itself normally.

**Comment by tux3** [comment]
> AutoUpdater: About to start the qTox updater to install a local update

qTox uses the presence of the folder "~/Library/Preferences/tox/update/" to know if there's an update ready to be installed.

The installer must delete this folde once it's done installing an update, and then restart qTox.
Otherwise qTox can't know if the update was installed or not.

**Comment by stqism** [comment]
Resolved this issue.
