### ISSUE TITLE
Copying text is hard

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#783]
It is very difficult to select messages properly. Often, a lot of additional text like the time is selected, with a lot of unnecessary spacing added.

Text and "result":
![snapshot110](https://cloud.githubusercontent.com/assets/1885159/5062971/ec7b3db0-6dd3-11e4-82b1-6bddcbd520b0.png)

Desired result:
Tox User: and I'm having trouble with jtoxcore
Tox User: especially when I'm trying to add a friend
Impy: I'm sure someone in #tox-dev could help you out with that

**Comment by dubslow** [comment]
There's a 3rd incarnation of the chat form in the works, thanks to @krepa098. Hopefully it will solve this (as well as several other problems related to the chat form).

**Comment by krepa098** [comment]
Yes that's possibly. It currently mimics the old behavior but I have to rewrite the selection stuff anyway.

**Comment by dubslow** [comment]
Fixed by new chatform, comment for reopen
