### ISSUE TITLE
Usability quoting

### ISSUE THREAD

**Issue by ValdekGreen** [qTox/qTox#784]
Quoting on drag'n'drop, context menu option, or Ctrl+C __ Ctrl+V auto-quote (perfectly like markdown quoting, probably hard to implement)

**Comment by dubslow** [comment]
Could you elaborate please? I have no idea what you're talking about, or what Skype does.

**Comment by DanTheBritish** [comment]
I think he means when copy+pasting messages from the chat log into the same chat, Skype shows the message like this:

> hh:mm:ss <username>: Quoted message

Literally, like markdown quoting.

**Comment by neko259** [comment]
He means a faster quoting. Currently to quote some message you need to select it, copy, enter ">" and paste the message. Some other messaging clients allow auto-quoting (inserting ">") by copy-pasting, or a button to paste selected text as a quote.
// Discussed this with @ValdekGreen

**Comment by msteinbeck** [comment]
I think this issue can be closed, because a copied line gets pasted with: [hh:mm:ss] [username] [message].
