### ISSUE TITLE
Ui freezes

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#799]
Call was active and qtcreator debug mode was on. Option tab ´´Audio/Video´´ was selected and Arch/linux was used. Audio I/O devices were chosen several times and then peer hung up. After that (15-20 s later) I noticed that video preview was still active (lagging heavily) and then it unfroze.

Ayy qTox.log: https://gist.github.com/mannol/3623092c36da47a7eee4

PS. Used core from patch #1163

**Comment by tux3** [comment]
It froze while you were switching audio devices like crazy, or at what time exactly ?

Also, the log says that you only changed the audio device once, is that a bug too ?

**Comment by ghost** [comment]
I had audio/video tab opened for a minute or two and changed a device (I think the last time it happened I changed device only once actually hence the log. But I usually switch devices a few times. Doesn't really matter as long as the a/v tab is active it will happen.) during that period. My guess would be it has something to do with video preview...

**Comment by tux3** [comment]
This seems to be a dupe of the all too common "the a/v tabs freezes qTox" bug, except this is the first time I heard of it unfreezing eventually.

This should be fixed after the video code overhaul.

**Comment by tux3** [comment]
This should be fixed with FFmpeg.
