### ISSUE TITLE
Adding friend 2 times causes qTox to crash

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#801]
qTox 0608989f16a2787cadbb11bb1adf8b292d2c96b5

https://gist.github.com/zetok/fe70b8f0c93a98f288c8

Reproducible: Always

Steps to reproduce:
1. Add friend
2. Quickly remove friend
3. Add same friend
4. qTox crashes

Relevant part of log (without ID):

```
Core: Connected to DHT
Settings: Saving in  "/home/zetok/.config/tox/settings.ini"
Core: writing tox_save to  "/home/zetok/.config/tox/_3.tox"
Widget: something set the status to online
Settings: Saving in  "/home/zetok/.config/tox/settings.ini"
Core: writing tox_save to  "/home/zetok/.config/tox/_3.tox"
[New Thread 0x7fffd4e93700 (LWP 3217)]
"Core: requesting friendship of  "
Settings: Saving in  "/home/zetok/.config/tox/settings.ini"
Core: writing tox_save to  "/home/zetok/.config/tox/_3.tox"
Settings: Saving in  "/home/zetok/.config/tox/settings.ini"
Core: writing tox_save to  "/home/zetok/.config/tox/_3.tox"
"Core: requesting friendship of  "
Settings: Saving in  "/home/zetok/.config/tox/settings.ini"
Core: writing tox_save to  "/home/zetok/.config/tox/_3.tox"

Program received signal SIGSEGV, Segmentation fault.
```

**Comment by tux3** [comment]
Can't reproduce, and the backtrace says that your computer is <strike>cursed</strike> misconfigured.

This is very likely to be a problem with your libraries, I can't do anything with this backtrace, sorry. If you get a different backtrace for the same bug, please post it.

**Comment by zetok** [comment]
I can confirm that removing shit called nvidia and using radeon makes issue disappear on newest qTox

**Comment by zetok** [comment]
reproducible on 9bc6ae57fa1028752c9d882139d740ab98255a48: https://gist.github.com/zetok/64018147d5ddb746f83a

Please reopen, since it still affects me.

**Comment by tux3** [comment]
Pretty sure this is a bug with nouveau, or perhaps with how Qt talks to nouveau. That backtrace is practically the same as the first you posted. We're just trying to construct a perfectly normal Qt object and Nouveau crashes on us. 

Unless there's a _really_ obscure arcane bug that somehow only crashes nouveau and only on your computer, that's not a problem with qTox, that looks like a problem with your setup :/

**Comment by dubslow** [comment]
Was this fixed?
