### ISSUE TITLE
Put the Audio in its own thread completely, refactor out of coreav

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#802]
This way we can send/receive the 1v1 and group audio completely in their own threads without shooting ourself in the foot because you can't start/stop a QTimer accross thread boundaries.

Make Core construct Audio (?). Move everything related to the audio thread, add slots to Audio to start/stop our timers.
Maybe move the alSources and others into their own arrays in Audio, and just keep a handle in the ToxCall/ToxGroupCall we can pass to Audio. Or move the whole ToxCall to be accessible by both somehow.

**Comment by dubslow** [comment]
Isn't this done by mannol's core refactor and associated changes here?

**Comment by tux3** [comment]
No, the audio is still being run in the Core or GUI thread (!).

We'd need to move the timers and callbacks to the audio thread, which means another object living in the audio thread that can receive events to stop the timer, because we can't stop timers accross thread boundaries. So the Audio singleton will do the job perfectly.
