### ISSUE TITLE
[Build System] Occasional duplicate builds under GitHub 'releases'

### ISSUE THREAD

**Issue by bricky149** [qTox/qTox#803]
Sometimes there are builds with the same changeset and are tagged as separate releases.
![dupebuilds](https://cloud.githubusercontent.com/assets/4836781/5081314/01b2b03a-6ec6-11e4-9285-05c29ab0509c.png)

**Comment by dubslow** [comment]
We should honestly delete a lot of the older ones...

**Comment by dubslow** [comment]
Releases will slowly be deleted
