### ISSUE TITLE
context menu of chat should contain "copy" and "select all" entry

### ISSUE THREAD

**Issue by karolherbst** [qTox/qTox#808]
currently there are only history related entries, so I guess the default entries of a readonly textbox are overwritten.

**Comment by agilob** [comment]
@krepa098 Does it depend on https://github.com/tux3/qTox/pull/974?
Is it implemented in ChatV3 (screenshot suggests so)?

**Comment by zetok** [comment]
There is no `Select all` thing

**Comment by dubslow** [comment]
GUI issue fixed by new chatform, comment for reopen

**Comment by karolherbst** [comment]
yeah, thanks. One issue though: "disabled" entries in the chat message field are not displayed as disabled for me, I can't select them though.

**Comment by karolherbst** [comment]
also emoticons doesn't work
