### ISSUE TITLE
Error while looking up DNS

### ISSUE THREAD

**Issue by harciga** [qTox/qTox#81]
Just built toxgui on OS X 10.8 and I get this DNS error, I'm linking against glib 2.40 fwiw
![screen shot 2014-07-04 at 11 52 01 pm](https://cloud.githubusercontent.com/assets/1581814/3485780/28e1cffa-0400-11e4-909b-819d5db82c40.png)

**Comment by tux3** [comment]
That's because groupchat@toxme.se does not exist, you're probably looking for groupbot@toxme.se

I'll add a more descriptive error message
