### ISSUE TITLE
compiling on debian and armhf

### ISSUE THREAD

**Issue by spackonaut** [qTox/qTox#812]
Hi I tried to install qtox with on an arm A20 processor running debian wheezy. I used the simple_make.sh but it fails with following error:

g++ -c -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIE -DGIT_VERSION="\"4d4067cf88d41201a3a17d5053507f3f3e0196e2\"" -DTIMESTAMP=1416376202 -DLOG_TO_FILE -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I. -Ilibs/include -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtOpenGL -isystem /usr/include/arm-linux-gnueabihf/qt5/QtWidgets -isystem /usr/include/arm-linux-gnueabihf/qt5/QtSql -isystem /usr/include/arm-linux-gnueabihf/qt5/QtXml -isystem /usr/include/arm-linux-gnueabihf/qt5/QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I. -o addfriendform.o src/widget/form/addfriendform.cpp
In file included from ./ui_mainwindow.h:28:0,
                 from src/widget/form/addfriendform.cpp:23:
./src/widget/adjustingscrollarea.h:28:46: error: expected ‘;’ at end of member declaration
./src/widget/adjustingscrollarea.h:28:48: error: ‘override’ does not name a type
./src/widget/adjustingscrollarea.h:29:30: error: expected ‘;’ at end of member declaration
./src/widget/adjustingscrollarea.h:29:36: error: ‘override’ does not name a type
In file included from ./src/core.h:27:0,
                 from src/widget/form/addfriendform.cpp:24:
./src/coreav.h:37:19: sorry, unimplemented: non-static data member initializers
./src/coreav.h:37:19: error: ISO C++ forbids in-class initialization of non-const static member ‘active’
make: **\* [addfriendform.o] Error 1

Additional information:
 cat /proc/cpuinfo 
Processor       : ARMv7 Processor rev 4 (v7l)
processor       : 0
BogoMIPS        : 239.41

processor       : 1
BogoMIPS        : 240.23

Features        : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 4

Hardware        : sun7i
Revision        : 0000
Serial          : 0000000000000000

g++ --version:
g++ (Debian 4.6.3-14) 4.6.3

uname -a:
Linux A20 3.4.67+ #6 SMP PREEMPT Fri Nov 1 17:32:40 EET 2013 armv7l GNU/Linux

lsb_release -a:
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.7 (wheezy)
Release:        7.7
Codename:       wheezy

qmake --version:
QMake version 3.0
Using Qt version 5.3.2 in /usr/lib/arm-linux-gnueabihf

If you need more info let me know. Hope you can help me.

**Comment by suhr** [comment]
> g++ (Debian 4.6.3-14) 4.6.3

qTox needs GCC ≥ 4.8 to compile (since it uses C++11).

**Comment by dubslow** [comment]
Indeed:

> ./src/coreav.h:37:19: sorry, unimplemented: non-static data member initializers
> ./src/coreav.h:37:19: error: ISO C++ forbids in-class initialization of non-const static member ‘active’

http://stackoverflow.com/questions/13662441/c11-allows-in-class-initialization-of-non-static-and-non-const-members-what-c

**Comment by zetok** [comment]
@spackonaut in case you couldn't find it yourself: https://github.com/tux3/qTox/blob/master/INSTALL.md#dependencies

**Comment by spackonaut** [comment]
Thanks a lot for you super fast reply.
