### ISSUE TITLE
qTox randomly sends messages to contacts

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#813]
![2014-11-17 ui mockup qtox screenshot button groupchat reactions description](https://cloud.githubusercontent.com/assets/3148759/5104505/a33c5a22-6fda-11e4-8d58-c50bd15cbe39.png)

![snapshot2](https://cloud.githubusercontent.com/assets/3148759/5104518/c56b4fd6-6fda-11e4-98a3-7efd78222e8b.png)

As you can see, `Hmm` was from yesterday, and it was **not sent by me!**

Those messages were sent upon qTox restart.

---

---

Also, groupbot seemed to receive some messages as well:
![2014-11-17 ui mockup qtox screenshot button groupchat reactions description](https://cloud.githubusercontent.com/assets/3148759/5104508/a640f41c-6fda-11e4-8e47-8e058db856d5.png)

Edit: qTox 4d4067cf88d41201a3a17d5053507f3f3e0196e2

**Comment by zetok** [comment]
![2014-11-17 qtox broken read receipts bunslow](https://cloud.githubusercontent.com/assets/3148759/5105146/899384f4-6fe1-11e4-96b0-34a3232c72d0.png)

↑ first symptoms, from 2 days ago (would have posted sooner, but I _needed_ @dubslow consent, and screenshot from him today ↓

![zetok](https://cloud.githubusercontent.com/assets/3148759/5105163/c0ea5464-6fe1-11e4-8e96-aa2b007dcfe5.png)

**Comment by dubslow** [comment]
Looks like there's two related bugs:

1) @apprb The faux offline messaging is sending messages _received_ from friends

2) Some messages _from_ friends are erroneously processed as "no read receipt". Judging from the most recent screenshot here, it looks like 2) is the cause of 1).

1) could be solved by some error checks, but that would only mask the underlying problem of 2).
