### ISSUE TITLE
Voice chat doesnt work

### ISSUE THREAD

**Issue by Tidro** [qTox/qTox#816]
Windows 7 | sp 1 | ultimate
Trying voice chat with my friend - no sound and every restart reset volume microphone & playback
![screenshot 2014-11-19 001](https://cloud.githubusercontent.com/assets/6688139/5113718/cefade46-7042-11e4-9c3d-abea130de2dc.png)
In log:
23:16:08 Audio: Cannot open output audio device
23:16:08 Audio: Cannot open input audio device
in config:
[Audio]
inDev=\x41c\x438\x43a\x440\x43e\x444\x43e\x43d (2- \x423\x441\x442\x440\x43e\x439\x441\x442\x432\x43e \x441 \x43f\x43e\x434\x434\x435\x440\x436\x43a\x43e\x439 High Definition Audio)
outDev=\x414\x438\x43d\x430\x43c\x438\x43a\x438 (2- \x423\x441\x442\x440\x43e\x439\x441\x442\x432\x43e \x441 \x43f\x43e\x434\x434\x435\x440\x436\x43a\x43e\x439 High Definition Audio)

AND 
i cannot enable checkboxes here
![screenshot 2014-11-19 001](https://cloud.githubusercontent.com/assets/6688139/5113854/404ce368-7044-11e4-9a03-2bdaccb82e96.png)

Using last stable build x64

**Comment by tux3** [comment]
The volume and microphone volumes don't actually do anyhing yet.

And the checkboxes for encryption are currently disable because some encryption features need to be finalized.

As for not having any sound, it's not clear why qTox can't open the audio devices. I'll make some tests on my end.

**Comment by Tidro** [comment]
Maybe because i have russian windows (and my friend), utox and other clients work fine

**Comment by suhr** [comment]
Seems related: https://github.com/tux3/qTox/issues/810. Sound notifications doesn't work too?

**Comment by Tidro** [comment]
Sound notifications doesn't work too?
Doesnt work

**Comment by dubslow** [comment]
A fix concerning UTF-8 and device names was just pushed (https://github.com/tux3/qTox/commit/3a107e33c8c4bd69926d72efc2a20f51792c3896). @Tidro Does this solve your problem?

**Comment by tux3** [comment]
This is probably fixed; closing for now. If you still have this issue, please leave a comment.

**Comment by pantran** [comment]
This is unfortunately not fixed. The commit only fixes 32-bit, what was the reason for this? A contact with russian Windows 8 (64 bit) apparently has the same problem as above and in #831. Would you apply the fix to 64 bit?

**Comment by zetok** [comment]
@pantran which qTox version doesn't want to work (shown on About page)?

**Comment by pantran** [comment]
can not check right away but guessing about a week old, a nightly build

**Comment by pantran** [comment]
(thanks for the commit, nevertheless) I still see more of ifdef Q_OS_WIN32 in the file and guess more fixes are needed (both video and audio is affected both in and out, in different situations)
video is possibly a different issue but it seemed to follow the same pattern, depending on visiting the settings page and who calls whom

**Comment by zetok** [comment]
> I still see more of ifdef Q_OS_WIN32

Oh, right, thanks for pointing that out - will fix.

**Comment by pantran** [comment]
thanks, looking forward to the next night build

**Comment by zetok** [comment]
@pantran could you check whether 32 and 64 bit builds work correctly with those changes?
32: https://build.tox.chat/job/qTox-testing_build_windows_x86_release/2/artifact/qTox-testing_build_windows_x86_release.zip
64: https://build.tox.chat/job/qTox-testing_build_windows_x86-64_release/14/artifact/qTox-testing_build_windows_x86-64_release.zip

**Comment by pantran** [comment]
sure, not immediately but I will report back as soon as the affected party will be able to test

**Comment by pantran** [comment]
sorry could not contact that affected party any more, which means I will not be able to verify the result.

anyway, looking at the code I believe the fix was due to both 32 and 64 bit windows and your change https://github.com/zetok/qTox/commit/b2b50c26ce64c8abead744277517f4655ca184e5 looks right. your prompt answer and fix were impressive, thanks.
