### ISSUE TITLE
Friend request window > Possible enhancement

### ISSUE THREAD

**Issue by hk1mm** [qTox/qTox#817]
Possible enhancement : When receiving a friend request, it will be nice if we also receive the "pseudo" of the sender because with only the "ID" we can't be identify the friend. Thank you.

**Comment by hk1mm** [comment]
Thank you for your reactivity tux3 !

**Comment by dubslow** [comment]
I believe this is a core issue

**Comment by tux3** [comment]
It is. Are you aware of any plans to add it in toxcore ?

**Comment by agilob** [comment]
ok...
