### ISSUE TITLE
Artifacts in file transfer progress

### ISSUE THREAD

**Issue by neko259** [qTox/qTox#818]
![223](https://cloud.githubusercontent.com/assets/770566/5115707/48cbfc4c-704c-11e4-8e50-a2a1c1a7895a.png)

**Comment by zetok** [comment]
I just ran into that on qTox 9bc6ae57fa1028752c9d882139d740ab98255a48 patched with #920, #957, #962, #965, #966 and compiled with Qt 5.4.0

No "special" filenames.

Reproducible: always

**Comment by dubslow** [comment]
Err... zetok can you bisect or otherwise attempt to discern which patch introduces this regression? Since head doesn't have it?

**Comment by suhr** [comment]
I use non of patches but have the same issue.

**Comment by dubslow** [comment]
Oh, I assumed this was a new issue, my bad

**Comment by TheLastProject** [comment]
This is the first time I run into it, so it seems to be a rare condition, but apparently something that can still happen in the latest qTox (I last updated yesterday):
![3](https://cloud.githubusercontent.com/assets/1885159/6094113/93585da0-af1c-11e4-8bb5-017126d6e7f7.png)

**Comment by zetok** [comment]
@TheLastProject it's fixed in chatform v3

**Comment by TheLastProject** [comment]
This is indeed fixed for me, yes.
