### ISSUE TITLE
echo/noise cancellation

### ISSUE THREAD

**Issue by excalibur1234** [qTox/qTox#820]
this is needed by all users, who want to use qtox without a headset but with speakers and a microphone.

a lot of skype users use a usb camera with integrated microphone and speakers built-into their computer screen. this makes talking really comfortable.
please enable them to use qtox instead of skype.

**Comment by cjpit** [comment]
webrtc has aec in it, maybe code can be pulled from there...

**Comment by zetok** [comment]
@cjpit thanks for info, thanks to it ↓

@tux3 https://github.com/irungentoo/filter_audio :3

Edit: if feasible, please make noise/echo cancellation and option, on by default

**Comment by cjpit** [comment]
@zetok @tux3 Awesome :P Another thing webrtc has in it is vad (voice activity detection) I don't know if this may help with group voice as well, just another fyi

**Comment by excalibur1234** [comment]
there has been progress: https://github.com/tux3/qTox/pull/875

**Comment by dubslow** [comment]
@excalibur1234 The audio filtering has been added, is it sufficient for you?

**Comment by zetok** [comment]
@dubslow but it still doesn't cancel echo, just tries to filter noise?

**Comment by ArchangeGabriel** [comment]
Last time I’ve tried, echo was still here and that was a bit annoying.

**Comment by zetok** [comment]
@ArchangeGabriel just to make sure, you did check and option for it in settings, right?

**Comment by ArchangeGabriel** [comment]
Yes, under audio/video.

**Comment by dubslow** [comment]
Okay, the Linux builds in the repo have the same experimental echo cancellation as uTox. Windows builds will be updated as soon as @tux3 wakes up and takes care of it, and Mac users ought to get along with the week+ of updates they're already missing as soon as @stqism fixes whatever he's doing.

Also _ahem_ turns out the previous audio filtering was never working anyways. See the commit right before echo cancellation commit...

**Comment by tux3** [comment]
This should be fixed since I've finally woken up.

**Comment by dfyx** [comment]
Still not fixed as of Nightly 758 (Feb 24th) on OS X.

**Comment by dubslow** [comment]
I didn't get much improvement, on either end, from a non-patched qTox to a patched uTox. More work is required.

**Comment by tux3** [comment]
Libfilteraudio was updated, this should work better now.
