### ISSUE TITLE
Lossless recordings.

### ISSUE THREAD

**Issue by Jookia** [qTox/qTox#821]
I'd be heavily interested in recording system that allows professionals to dump the chat, each individual video stream and each individual stereo audio stream all synchronized. This could be extremely useful for doing recordings and editing them in post production, or just keeping minutes of meetings for archival purposes.

**Comment by jhunnius** [comment]
I'd love to see recordings of all the audio "tracks" as well. One file per participant.
Can be wav, can be FLAC, whatever is easier to implement.
Would be awesome for podcasters with interviewees in their shows.

**Comment by sudden6** [comment]
This is pretty far out of the focus of qTox and a specialized client may be better suited.

**Comment by anthonybilinski** [comment]
A note that Tox protocol defines audio calls as being opus format, which is inherently lossy.

I'd be interested in A/V recording and archiving of conversations - but I agree it's out of scope for the time being.
