### ISSUE TITLE
Missing embedded bootstrap nodes

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#822]
@stqism seems to be having this issue, and this is the underlying cause of his div by zero issue.

I'm not entirely sure how this could be, since all the images are embedded the same way as the nodes, and they obviously work everywhere else...

Is anyone else, especially Mac users, having a problem with this?

**Comment by stqism** [comment]
I just realised not having settings.ini is what caused all those crashes we were having on OS X.

Makes zero sense

**Comment by dubslow** [comment]
Wait what?

**Comment by tux3** [comment]
This should be fixed.
