### ISSUE TITLE
personal feeds / Social media

### ISSUE THREAD

**Issue by Nadano** [qTox/qTox#825]
I think it would be interesting to implement some kind of personal feeds in qtox. Some page with my status, pictures... for my contacts to see. The feeds would be stored locally and sent to the contacts upon conection.

**Comment by zetok** [comment]
@Nadano care to elaborate and provide an exact description of the feature that you would like to see in qTox?

**Comment by ProMcTagonist** [comment]
I'm interested in the concept of userpages. Just a little personal page with a bio and some pictures like Nadano suggested, maybe done in some scriptless html, although not primarily edited that way of course.

It's definitely low priority, but I think it would attract people to be able to theme and share a personal page.

**Comment by Nadano** [comment]
The idea would be to have some feeds stored in your computer and shared
upon demand of the other users.
These information could be accessed, as ProMcTagonist said, in the format
of a userpage or thanks to a "social" tab in qtox. In this tab the
information of your contacts is loaded and interleaved "a la facebook" so
you can see the last updates of the people you follow.
I don't know exactly the insides of tox, but I can imagine that the
implementation is nothing more than a beautified group conversation in
which the feeds are the messages.

Even if it's not the main objective of tox it would allow, for a minimal
effort, people to have some kind of private social platform.

2015-08-21 20:36 GMT+02:00 ProMcTagonist notifications@github.com:

**Comment by zetok** [comment]
> I don't know exactly the insides of tox, but I can imagine that the implementation is nothing more than a beautified group conversation in which the feeds are the messages. 

Well, actually, it is possible to create a true social network on top of toxcore - that's why there's a question of what exactly your request is about, since building a real social network on top of toxcore is kinda beyond qTox's scope `:)`

I think that there's needed more input on what people think about this idea, and if it's going to become a thing, how exact design should be.

**Comment by Zer0-One** [comment]
How would this function in the context of communication with clients that _aren't_ qTox?

**Comment by zetok** [comment]
@Zer0-One either it should become a part of [STS](https://github.com/Tox/Tox-STS) as an extension (or something), or there could be created something entirely new when it comes to "extensions" of clients.

**Comment by sudden6** [comment]
I'm closing this as this idea never really took of in the Tox community.
