### ISSUE TITLE
Possible enhancement > Add invisible status and invisble status for some contacts

### ISSUE THREAD

**Issue by hk1mm** [qTox/qTox#826]
Hi... It will be nice if you can add "Invisible" status for all and some contacts... Thank you.

**Comment by dubslow** [comment]
Is a core issue

**Comment by ghost** [comment]
@tux3 Maybe you add a new `tox core` issue label.

**Comment by tux3** [comment]
@mwuttke97 we have upstream for that :)

**Comment by Getron** [comment]
+1

**Comment by agilob** [comment]
Not supported by toxcore. Should we close it?

**Comment by UralZima** [comment]
Please support toxcore issue: https://github.com/TokTok/c-toxcore/issues/522
