### ISSUE TITLE
Graphical glitch with contact list

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#827]
![broken](https://cloud.githubusercontent.com/assets/3148759/5129770/370a0ee0-70dd-11e4-8597-63133c5c807d.png) ![proper](https://cloud.githubusercontent.com/assets/3148759/5129777/3c5fb192-70dd-11e4-80f8-9a4d73ba7f8c.png)

qTox 0fd3f5e15652dddc6abcc6c09dedf127c42328d5

No idea what causes it. Happens randomly upon qTox launch. Disappears after resizing contact list.

Edit: perhaps it's not noticeable; distance of default "avatar" to the scroll bar

**Comment by msteinbeck** [comment]
Does this glitch still occur with the newest qTox version?

**Comment by zetok** [comment]
No idea. I don't use qTox without compact list, which so far wasn't(?) affected by this.

**Comment by msteinbeck** [comment]
I was not able to reproduce this. Maybe you could test it again. If it doesn't happy anymore, we could close this issue.

**Comment by dubslow** [comment]
Oh I recall a fix for this being merged a long while ago. It was bugging me too lol
