### ISSUE TITLE
Build issue on Yosemite 10.10.1

### ISSUE THREAD

**Issue by t3stt** [qTox/qTox#828]
Hi,

I'm having some issue building qTox on Yosemite.
Please check [0] for the output
Thanks in advance for any hint...
t3stt

[0] https://gist.github.com/t3stt/e1a60843f65aa7c07fad

**Comment by dubslow** [comment]
qTox is written in C++11. Either your compiler is not a C++11 compiler, or you don't have the proper compiler flag set to enable C++11 mode.
