### ISSUE TITLE
Freeze in Audio/Video

### ISSUE THREAD

**Issue by noisykeyboard** [qTox/qTox#829]
Hi,

Whenever I open the Audio/Video tab in the settings, it shows my webcam at about 1 fps and qTox essentially freezes. Once qTox "freezes" I have to kill manually, because it starts eating up CPU like no one's business.

Thanks.

**Comment by ghost** [comment]
This might be related to #799

**Comment by noisykeyboard** [comment]
I looked at it, they both involve the webcam but they seem to be separate issues

**Comment by maxigaz** [comment]
I have the same problem in the latest version under GNU/Linux. However, it not only uses way too much CPU when I click on that tab, but also RAM: it first goes up to about 600 MB, then it just goes up and up. I killed the process when it reached using 2 GB of RAM.

**Comment by DanTheBritish** [comment]
Reproduced with latest build on Xubuntu 15.04, using built in webcam on Thinkpad T430

Edit: Scrot of RAM usage on preview window after 1 minute http://imgur.com/FuSVV0jl.png and after 5 minutes: http://imgur.com/ERZLMFdl.png

**Comment by tux3** [comment]
Could someone try to run qTox within GDB and get a backtrace or two at the point where it's freezing?

It would help immensely trying to determine what is blocking it.

**Comment by DanTheBritish** [comment]
https://gist.github.com/LapFox/ac270b9f160d1dab562d

**Comment by DanTheBritish** [comment]
BT immediately https://gist.github.com/LapFox/e56aeca98100cd3979f1
BT after 1 minute https://gist.github.com/LapFox/cde7da92997c791736a9

**Comment by zetok** [comment]
Can you test [ffmpeg branch](https://github.com/tux3/qTox/tree/ffmpeg) and see whether it improves situation?

Edit: (in regard to freezing, probably not yet ready for use)

**Comment by tux3** [comment]
This should be fixed with FFmpeg.

**Comment by DanTheBritish** [comment]
Confirmed as fixed, great work! :clap: :+1:
