### ISSUE TITLE
Audio not working may be related to system language

### ISSUE THREAD

**Issue by uxname** [qTox/qTox#831]
Windows 7 is not working sound. Audio sliders permanently set to 0 (i change to 50% but after restart qTox it set to 0 again) . Windows Volume Mixer does not even see that qTox uses sound. uTox works fine.
Windows 7 x64 (ru)
![2014-11-21 08-26-55 qtox -](https://cloud.githubusercontent.com/assets/2634142/5138051/520734cc-7158-11e4-934a-b515883f81ff.png)

**Comment by apprb** [comment]
These sliders are just placeholders.

**Comment by uxname** [comment]
apprb, but i can't hear when i call. qTox must support calls at least. It seems like qTox can't use audio devices. Windows says even qTox does not use audio (i seen in audio mixer)

**Comment by apprb** [comment]
But the sound problem itself looks like: #816

**Comment by suhr** [comment]
Known issue: https://github.com/tux3/qTox/issues/816 https://github.com/tux3/qTox/issues/810

**Comment by uxname** [comment]
I'm pretty sure it is related to Russian version of Windows (tried run qTox in VirtualBox in eng. windows - all work fine)

**Comment by uxname** [comment]
I guess that this is due to unicode. Which encoding is used when compiling?

**Comment by dubslow** [comment]
A fix concerning UTF-8 and device names was just pushed (3a107e3). @uxname Does this solve your problem?

**Comment by uxname** [comment]
@dubslow Damn. No :(

**Comment by uxname** [comment]
Yes! But not completely.
Now i can see this
![2015-01-15 12-13-09](https://cloud.githubusercontent.com/assets/2634142/5754953/140bf74c-9cb0-11e4-8682-65a242cfee8b.png)
And does not sound when calling.
And audio output begins to work when calling AND ONLY after I go to the tab with the audio settings.
And does not work microphone.

**Comment by derMart** [comment]
see https://github.com/tux3/qTox/issues/1014

**Comment by soredake** [comment]
@uxname 

> And audio output begins to work when calling AND ONLY after I go to the tab with the audio settings.

Same for me.

**Comment by dubslow** [comment]
@derMart @tux3 ^^

**Comment by tux3** [comment]
@uxname @fenque can you post the content of qtox.log ?

**Comment by soredake** [comment]
@tux3 https://a.pomf.se/dlcqec.log

**Comment by uxname** [comment]
I have updated today and now working perfect! Thanks you very much :)
