### ISSUE TITLE
[Regression] Changing input device takes forever

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#832]
qTox 0fd3f5e15652dddc6abcc6c09dedf127c42328d5

**Comment by dubslow** [comment]
Reconfirm please?

**Comment by zetok** [comment]
@dubslow sorry for late reply, I didn't have much time.

<s>Anyway, changing device doesn't work when I'm in groupchat, and input device is  not muted.
Reproducible on 79dd992d813fa742f7e731d052f32db74770d5a8</s>

Edit: actually it does seem to work, but takes some time to happen

**Comment by zetok** [comment]
I can't reproduce this issue any longer.
