### ISSUE TITLE
``Copy friend ID'' doesn't copy a usable friend ID

### ISSUE THREAD

**Issue by F1ynn** [qTox/qTox#84]
It only returns their public key, leaving out the nospam and checksum bits.

Will fix soonish.

**Comment by msteinbeck** [comment]
Do we have any progress here?

**Comment by F1ynn** [comment]
Haven't had time yet, sorry. Based on a brief glance a few days ago, the nospam isn't stored in the standard tox data file so it might be somewhat interesting fixing this.

**Comment by lehitoskin** [comment]
The Nospam value isn't saved in Tox. Unless you keep a separate DB of Tox IDs, there's no way to retain it.

**Comment by msteinbeck** [comment]
> Unless you keep a separate DB of Tox IDs

Do we have any plans to do this?
