### ISSUE TITLE
minimize to tray doesn't disable opening new instance

### ISSUE THREAD

**Issue by rubo77** [qTox/qTox#840]
- On Windows "Pin to Taskbar" the open instance of qTox
- then minimize qTox to Tray 
- then I click on the Icon in my starter Taskbar (not the tray icon) then there is started a new instance of qTox.

Instead the minimized instance should maximize.

(tested on Windows 7 64bit and Windows 8.1 64 bit)

**Comment by ghost** [comment]
This was fixed in beae534d66deb1db2a44941c4f942f536009aeb6

**Comment by Draako** [comment]
This issue has to be reopened.

**Comment by ghost** [comment]
Can not reproduce

**Comment by Draako** [comment]
I experience that behavior for quite a few builds. Windows 7 x64

Once I run qTox as the second instance (from pinned to taskbar) it stays in processes taking 25% of CPU.

**Comment by ghost** [comment]
Could you try running qTox from it's folder in "Program Files" and tell me if it does same thing?

**Comment by Draako** [comment]
It opens for a short while and then it disappears from processes. The only problem seems to be when it runs from pinned to taskbar.

![qtox](https://cloud.githubusercontent.com/assets/8077316/6234251/3f494a64-b6d1-11e4-9c17-a65753cf3dce.jpg)

**Comment by ghost** [comment]
K now it makes sense. After it disappears i bet window of your main instance is showed too. It fails when running from taskbar because shortcut includes your profile. Ill fix it some time this week.

**Comment by Draako** [comment]
Shouldn't it be that the second instance is not there at all and the main one overtakes any request to run qTox? I don't mean to be rude, I'm just curious since other programmes seem to behave this way, e.g. XMPlay.

**Comment by ghost** [comment]
Thats how it is supposed to work. New instance sends a message to already running instance basically saying "wake up and show window" and then exits. Also its not supposed to show tray icon and all. Code doing this stuff must be little bit messy heh.
