### ISSUE TITLE
Save file dialog doesn't have default file name

### ISSUE THREAD

**Issue by rubo77** [qTox/qTox#841]
On Linux Ubuntu 14.10 when I export the profile, the suggested Filename is missing in the save-dialogue.

When you enter a filename yourself then, there isn't added any file-extension (`.tox` is missing)

If the extension is missing, there is no way to import the profile. You have to add the extension by hand on your file system

**Comment by dubslow** [comment]
Unfortunately I believe this is an upstream bug with `QFileDialog::getSaveFileName`. It says that if the "current dir" argument includes a filename in the path, as qTox does, then that filename well appear in the dialog; however, as you report, this isn't actually happening. 

I have the same issue with saving friends' file transfers on LMDE/Cinnamon 2.0. Up until now I thought it was just me, but now I'm thinking it's a Qt issue.

**Comment by dubslow** [comment]
This was fixed for me by updating to... Qt 5.3, I believe.
