### ISSUE TITLE
Still getting this error

### ISSUE THREAD

**Issue by dcharles525** [qTox/qTox#842]
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qtox : Depends: libqt5core5a but it is not installable
        Depends: libopencv-core2.4 but it is not installable
        Depends: libopencv-highgui2.4 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by zetok** [comment]
which distro?

**Comment by dcharles525** [comment]
Elementary OS

**Comment by rubo77** [comment]
Have you tried aptitude?

Sometim's it resolves problems

**Comment by dcharles525** [comment]
Nope that didn't work either!

**Comment by dcharles525** [comment]
And if I just try to use the binary I get this error:

./qtox: symbol lookup error: ./qtox: undefined symbol: _ZN18QCommandLineParserC1Ev

Awhile back qtox worked fine on eOS, but for the last two months or so its just been error after error....

**Comment by dubslow** [comment]
@stqism

**Comment by notpushkin** [comment]
_Ping_
~~I'm getting this error as well.~~ Distro: Linux Mint 16
Not the error in the OP, but this one:

```
ale@ale-Lenovo-B590 ~ $ qtox 
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 14: reading configurations from ~/.fonts.conf is deprecated.
qtox: symbol lookup error: qtox: undefined symbol: _ZN18QCommandLineParserC1Ev
```

**Comment by zetok** [comment]
@iamale since you've hit that issue, it means that mint 16 isn't supported. You could try to get qt5 stuff from some repo… Even then "errors" encountered using provided binaries may not be real bugs..

**Comment by dubslow** [comment]
@stqism ?

**Comment by notpushkin** [comment]
@zetok Should I probably try recompiling it from source?

**Comment by stqism** [comment]
@dubslow: my theory is that it's based off some odd Ub

**Comment by stqism** [comment]
*Ubuntu release with only an old version of Qt under 5.2. Note that qTox doesn't even compile with anything older. 

Sorry about 2 messages, can't edit on my phone.

**Comment by dcharles525** [comment]
doesn't happen anymore
