### ISSUE TITLE
[OS X] coreaudiod high cpu usage

### ISSUE THREAD

**Issue by vjay82** [qTox/qTox#844]
Hi,

starting qTox on my machine (MacBookPro Late 2008) immediately causes the core audio daemon to consume 6-7% CPU until qTox is closed.
I guess you let the audio devices opened all the time, where a call/ settings bound open/ close behaviour should suffice.

![screen shot 2014-11-23 at 14 53 02](https://cloud.githubusercontent.com/assets/905939/5157765/a5106ea8-7320-11e4-8d32-148bb3a1567b.png)

**Comment by antis81** [comment]
Phew, that's an old one… I'm sure it is fixed upstream (by #2509 or before) -> closing. Please reopen, if issue still apears.
