### ISSUE TITLE
Please Add BlackBerry 10 devices support

### ISSUE THREAD

**Issue by T-REX-XP** [qTox/qTox#847]
Hi! Unfortunately, android app does not work on BB 10 OS.
Could you compile Qt version for bb10 platform ??
Qt app may recompile for bb10 support like app Sachesi(app for BlackBerry which written on Qt and available for all platform (Win,Mac,Linux, BB10) )

thanks.

**Comment by srkunze** [comment]
It seems there is movement on the Antox area: https://wiki.tox.im/Binaries

Does this work for you?

**Comment by T-REX-XP** [comment]
```
                                                                                  Hello, sorry but, android client antxo doesn't work for me. He is closing, when I click registration on my BlackBerry q10. Thanks.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Sven R. KunzeSent: Sunday, 1 February 2015 18:31To: tux3/qToxReply To: tux3/qToxCc: T-REX-XPSubject: Re: [qTox] Please Add BlackBerry 10 devices support (#847)It seems there is movement on the Antox area: https://wiki.tox.im/Binaries
```

Does this work for you?

—Reply to this email directly or view it on GitHub.

**Comment by srkunze** [comment]
This won't be fixed. https://github.com/tox4j/tox4j/issues/29

**Comment by sonOfRa** [comment]
Not that while it won't be fixed in tox4j (due to JNI reasons), I don't know what the Qt folks are doing to support Blackberry. But I don't really have much hope on that front either.

**Comment by suhr** [comment]
Is this considered as issue yet?

**Comment by ProMcTagonist** [comment]
@T-REX-XP You should talk to the developers of:

https://github.com/emmanuelduv/harbour-tox

and

https://github.com/krobelus/cyanide

Sailfish apps are more easily portable to other Qt-based phone systems like Ubuntu and BlackBerry, and perhaps one of those developers will be interested.

**Comment by sudden6** [comment]
There are no intentions to support this platform.

**Comment by zetok** [comment]
Closing, since qTox currently doesn't have support for mobile.

If (when?) qTox gains support for the mobile, question of supporting a platform that practically no one uses could be raised again.

Oops, gh didn't show @sudden6's comment until it was too late :/
