### ISSUE TITLE
Friend list trembles on resizing

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#85]
How to reproduce: keep moving splitter left and right fast enough.

**Comment by msteinbeck** [comment]
I can confirm. But it only happens sometimes and does not depend on how fast I move the slider.

**Comment by tux3** [comment]
I can reproduce too, and iirc Flynn said it was to be expected, maybe he knows how to fix it.

**Comment by F1ynn** [comment]
Unfortunately this is a side effect of how the friendWidgets are drawn right now. I'll see what I can do to fix it when I rework them to enable drag ordering.

**Comment by msteinbeck** [comment]
> I rework them to enable drag ordering

I'm not sure if it breaks the general mockup, but it would be really awesome if a user is able to "detach" a friend to a separate window.

**Comment by suhr** [comment]
> but it would be really awesome if a user is able to "detach" a friend to a separate window

Or even hide it.

**Comment by F1ynn** [comment]
> "detach" a friend to a separate window.

That would be awesome, but require a non-insignificant amount of work. Maybe in the future?

> Or even hide it.

Hide a friend entry? That's definitely doable. Maybe talk to Duke and see what sort of interface the feature should have, if you can come up with something that everyone likes I'd be happy to implement it (time permitting of course).

**Comment by msteinbeck** [comment]
> That would be awesome, but require a non-insignificant amount of work. Maybe in the future?

I thought as much

**Comment by msteinbeck** [comment]
> Unfortunately this is a side effect of how the friendWidgets are drawn right now.

I was looking for a fix to avoid the resizing hack you made. I'm not completely done and maybe you already know it, but one thing is to change layout direction of the friendList widget from RightToLeft to LeftToRight. Applying this will cause the bug, that the status icon of each friend is fixed and not aligned to the right border. Maybe you will find a fix for that. As far as I can see switching the layout direction and disabling the updateFriendListWidth will fix the trembling bug.

**Comment by F1ynn** [comment]
> change layout direction of the friendList widget from RightToLeft to LeftToRight

Unfortunately that moves the scrollbar over to the right as well, breaking compatability with the mockup and messing up the overall visual style of the program.

The best way to fix this bug (that I know of anyway) short of rewriting the FriendWidgets is to disable updateFriendListWidth() and then force the FriendWidget width to not exceed the width of the parent container. I couldn't get it to do that so I cheated by adding updateFriendListWidth(), but it should be possible to fix.

Thanks for working on this, let me know what you come up with!
