### ISSUE TITLE
qTox opens status changing on secondary monitor

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#853]
qTox is maximized on the primary monitor
The secondary monitor is placed above the primary monitor
KDE 4.13.3

Overly cropped screenshot (the gray bar is the top of the qTox window, everything above it is on the secondary monitor):
![qtox_multi_monitor_bug](https://cloud.githubusercontent.com/assets/1885159/5184974/edd6c780-74bb-11e4-826a-2997b7673c11.png)

**Comment by dubslow** [comment]
Could this be a Qt issue? This is the only relevant code: https://github.com/tux3/qTox/blob/master/src/widget/widget.cpp#L81-L101

**Comment by TheLastProject** [comment]
Hard to tell. Just to be sure, this is the menu that appears when clicking the button next to your nickname, not the system tray (you seemed to have linked me to system tray code).

**Comment by dubslow** [comment]
Oh ah, nevermind that comment then lol.

**Comment by zetok** [comment]
Is this still an issue?

**Comment by zetok** [comment]
No answer, I assume that it was fixed, closing.
