### ISSUE TITLE
Small visual issues

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#864]
Yes, these are indeed very minor, but I wanted to document them regardless.
- [x] Changing group title/user alias by clicking on nick causes edit bar to touch the microphone button

![snapshot123](https://cloud.githubusercontent.com/assets/1885159/5205384/03af67b6-7597-11e4-89fe-2df773506f26.png)
- [ ] Line below person/group chatting with does not extend all the way left, but does extend all the way right
- [x] Contact info is aligned slightly below own info, causing the line below the contact info to not align nicely

![snapshot124](https://cloud.githubusercontent.com/assets/1885159/5205414/453acfae-7597-11e4-8d85-cafe9c101be1.png)

**Comment by suhr** [comment]
@agilob

**Comment by TheLastProject** [comment]
Sorry for bumping this, but I wanted to make sure that, despite the pull request made for this, the second issue still exists:

![linemargin](https://cloud.githubusercontent.com/assets/1885159/6766981/00c83358-d01d-11e4-9f48-dbc736a78262.png)

**Comment by agilob** [comment]
This issue can't be fixed, that white space is QSplitter (separator), just to show you I changed its color from white to green:
![addons2](https://cloud.githubusercontent.com/assets/2544251/6767074/108b719c-d018-11e4-8c1c-79a9ae657d48.png)

**Comment by ghost** [comment]
Remove the line; problem solved :^)))

**Comment by agilob** [comment]
Line removed in my PR with themes. It's not worth writing size-independent style for qsplitter just to add a few pixels.

**Comment by zetok** [comment]
@agilob but your PR hasn't been merged yet.. #1882

**Comment by tux3** [comment]
It would be hard to make the line cross over the QSplitter, what if we made the line have the same margin on the right as on the left?

![snap8](https://cloud.githubusercontent.com/assets/5155966/12470404/1ff30a60-bff4-11e5-913d-18c40af8071e.jpg)

It's only a couple lines changed, but I think it looks better.

**Comment by zetok** [comment]
I guess that adding a margin could work, given that it would seem like a by-design UI, rather than a bug.
