### ISSUE TITLE
AV Settings tab should not automatically start video preview

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#865]
I opened the tab, which started the camera which meant I started spamming the group call with my webcam's mic feed.

On the other hand, it worked just fine out of the box ^_^

Also this is probably a duplicate lol

**Comment by tux3** [comment]
Group calls aren't automatically joined anymore, so this should be fixed.

**Comment by ProMcTagonist** [comment]
Observing the video preview shouldn't start streaming your camera anywhere it wasn't before, though...

**Comment by tux3** [comment]
It won't.
