### ISSUE TITLE
Build uses include files from /usr/local/include instead of /usr/include

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#872]
~~Build log~~
UPD: see title.

**Comment by apprb** [comment]
Outdated toxcore?

**Comment by suhr** [comment]
Nope, recently compiled one.

**Comment by dubslow** [comment]
Hmm, @novist this may be related to the issues I was having compiling it...

**Comment by cebe** [comment]
> Build uses include files from /usr/local/include instead of /usr/include

isn't it normal to search both path for header files?

**Comment by ghost** [comment]
https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html
It does not say if include paths are in order but its logical assumption. After all why would i install library myself if i do not want to use it?

**Comment by msteinbeck** [comment]
Is this issue still relevant, can it be closed?
