### ISSUE TITLE
qTox losts connection after suspend/resume

### ISSUE THREAD

**Issue by akhilman** [qTox/qTox#883]
On Debian GNU/Linux after suspend for a long time and resume qTox losts connection. It shows that group chat has one user but user list stays like it was before suspend. Also messenging doesn't work.

I have to push reconnect button in settings to bring tox back.

**Comment by dubslow** [comment]
Note to self: on disconnect, update groupchats

**Comment by vladimiry** [comment]
@zetok I don't use qTox due to issue, since I would have to close and open app again to get see contact online. But I just tested it again and I can confirm that #1315 issue (and therefore this current issue) is still in place, no auto rec-connection after sleep mode (at least fo case if windows <--> arch linux machines were used).

**Comment by zetok** [comment]
@vladimiry does pressing `Reconnect` (in settings) help?

**Comment by PavelSann** [comment]
If you click Reconnect (in settings) then the connection is restored. 
I checked on two notebooks.(Win7 x64, Win10 x64)

**Comment by vladimiry** [comment]
So far I have no way to test "Reconnect" button, but either-way there is no difference whether I click "Reconnect" or restart app, it's still would be inconvenient since when I use app I assume that client shows me all contacts online status without a need to restart/reconnect actions.

**Comment by vladimiry** [comment]
I just have tested "Reconnect" button, it doesn't work in my case. We pressed that button on both sides several times (Arch linux and Windows) with no success. But when contact on Windows has written something to me (to kind of "offline contact") we became "online" after a few seconds.

**Comment by tux3** [comment]
Superseded by #2820
