### ISSUE TITLE
fix file adding

### ISSUE THREAD

**Issue by iShift** [qTox/qTox#885]
When i try to drag and drop to message box qtox can't sent it:

![2014-12-01 11 25 16](https://cloud.githubusercontent.com/assets/426427/5242864/d39bb426-794c-11e4-8fa6-daa32bd44942.png)

**Comment by zetok** [comment]
Can't reproduce on 3f234fb2eb33fb70bd30d350b4a48171671ad36f. Could it be that it's os x specific issue?

**Comment by minj** [comment]
file upload via drag&drop does not work with qtox-windows-1420801591.34 but does work with 94db81d on linux.

**Comment by zetok** [comment]
> When i try to drag and drop to message box qtox can't sent it:

Actually, if by "message box" you mean input field, then this is currently a desired behaviour. Image can be sent through `drag & drop` by dropping image on chatform.

@minj newest qTox builds for windows should have that working, if not, please comment for reopen.

**Comment by minj** [comment]
@zetok I had opened #1878 for my case and it turned out to be unreproducible so nothing to do here.
