### ISSUE TITLE
tox v1 DNS broken?

### ISSUE THREAD

**Issue by Epictek** [qTox/qTox#886]
I have 2 adressses that do not seem to work in qTox but work fine in uTox. In qTox it says ID not found.

Output from uTox (qTox gives no verbose output):

```
Parsed: (bot@tox.moe)->(bot._tox.tox.moe) pin=0
^Host: bot._tox.tox.moe
Attempting:
v=tox1; id=CA461E4347D804205B61A0FE7C6C407CC55DE64052FCCCC63CC05F161F02302025905CE2D8D3
```

```
Parsed: (kieran@coldron.com)->(kieran._tox.coldron.com) pin=0
^Host: kieran._tox.coldron.com
Attempting:
v=tox1;id=896FE243EDD1CACB43A5EA428CD03C9CD5A5D265F034AA2A2594088170557622ED60C8100651

```

**Comment by dubslow** [comment]
@irungentoo

Someone (and it was irungentoo I believe) told @tux3 that v1 dns was insecure, so it was disabled. uTox shouldn't be using it either.

**Comment by dubslow** [comment]
https://github.com/tux3/qTox/commit/8ece7041fdd99d2fe93e216fffcb1039eff463e4

**Comment by zetok** [comment]
tox1 is not secure, but since there's no other way to use anything beside it for users who store their DNS records on their domains, it should be available in qTox

**Comment by dubslow** [comment]
Yeah I have an idea to re-enable with with the checkContinue popup box

**Comment by tux3** [comment]
It should be possible to setup Tox3 DNS on your own servers too, although it's a bit harder.

That said I agree that a popux box to use tox1 would be a better solution than not finding anything, as long as it clearly states that tox1 is insecure.
