### ISSUE TITLE
Camera resolution isn't saved in settings

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#888]
http://support.libtoxcore.so/help/discussions/problems/21-qtox-not-all-settings-saved-in-preferences

**Comment by agilob** [comment]
When camera is busy on Linux, eg. by µtox or any other application qTox is not able to detect resolutions (linux specific behaviour(?)), saving resolution will cause problems. I don't think it's a good idea, especially when qTox is portable and settings can be moved between devices.

![camera busy](https://cloud.githubusercontent.com/assets/2544251/5301635/356a7dea-7bd2-11e4-9be0-a9bde3105599.png)

**Comment by zetok** [comment]
> When camera is busy on Linux, eg. by µtox or any other application qTox is not able to detect resolutions (linux specific behaviour(?)), saving resolution will cause problems. I don't think it's a good idea, especially when qTox is portable and settings can be moved between devices.

Err, not quite. Saving itself shouldn't cause problems. Problems would appear when saved settings would be loaded - only in cases where camera isn't the one that was used before though.

Thus it would be good to be able to save both camera, and resolution. When loading settings, in a case where camera differs (or there's none at all), saved resolution simply should not be used.

**Comment by tux3** [comment]
This is 13 months later, but I'm happy to say that this has been fixed some time ago!
