### ISSUE TITLE
Squashed icons on OSX

### ISSUE THREAD

**Issue by mouseym** [qTox/qTox#89]
Some of the buttons on the UI are squashed together (file picker/emoticon picker and chat button)

**Comment by F1ynn** [comment]
Weird. Can you post a screenshot of a file transfer in progress? The little buttons there are drawn slightly differently, if they're fine then I should be able to fix this pretty easily.

**Comment by mouseym** [comment]
Can't get a transfer in progress pic, but will this do?

**Comment by F1ynn** [comment]
That's perfect, thanks. I'll get a fix out soon.

**Comment by F1ynn** [comment]
Should be fixed in latest pull request, let me know if they're still broken.

**Comment by mouseym** [comment]
It fixed it, but caused another problem;

Now the A/V buttons are cut off

**Comment by F1ynn** [comment]
Dangit. Okay, I'll try again in a bit.

**Comment by mouseym** [comment]
closing this as it now seems to be fixed
