### ISSUE TITLE
Call duration timer keeps running if call is ended due to contact going offline

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#891]
See topic

**Comment by dubslow** [comment]
@agilob https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by agilob** [comment]
@dubslow  oki! Will try it next time.

**Comment by TheLastProject** [comment]
I'm sorry for reopening something this old but the bug is apparently back:
![qtox_call_offline](https://cloud.githubusercontent.com/assets/1885159/6320039/2c8755c2-bad4-11e4-9982-c7ed397aa8b9.png)

**Comment by zetok** [comment]
@TheLastProject I've just tried, and I couldn't reproduce - is this still affecting you?

**Comment by zetok** [comment]
No answer, couldn't reproduce; I assume that it was fixed, thus closing.
