### ISSUE TITLE
Crashes when accessing Audio/Video Settings

### ISSUE THREAD

**Issue by jaredStef** [qTox/qTox#892]
When I click "Audio/Video" under settings the app crashes. 
Pastebin of error - http://pastebin.com/R5Kx3xME

**Comment by dcharles525** [comment]
Happens to me to sometimes

**Comment by dubslow** [comment]
dcharles you're not on OS X right? So it's a more general problem?

@BigxMac It looks like from the back trace you were in the middle of a call when this happened?

**Comment by dcharles525** [comment]
@dubslow yeah I'm on Linux

**Comment by jaredStef** [comment]
I was in a call at the time but it also happens when I am not in calls. The bug always reproduces itself.

**Comment by dubslow** [comment]
Strangely enough though, the crash you paste binned was in the thread playing audio for you, not in the AV settings tab. I guess that means there's a race condition somewhere. @tux3 @krepa098

**Comment by dcharles525** [comment]
It happens every time I reboot my computer. 

So I boot it up and go to the settings tab and it crashes, but if I reopen qTox and go to the settings tab then it lags for a second then it works. 

Hope this help! :)

**Comment by jaredStef** [comment]
It never works at all. Even if I restart my computer, or completely quit the application it still crashes. I don't have a webcam so maybe that may having something to do with it

**Comment by dubslow** [comment]
Hmm I don't have a webcam either but it doesn't crash for me on GNU-Linux

But then again this is very complicated lol

**Comment by jaredStef** [comment]
I can send another crash report when I am not in a call so that maybe it will print a different stack trace. I'll send it soon.

**Comment by jaredStef** [comment]
http://pastebin.com/bHtPqm11

**Comment by tux3** [comment]
It's still the same nullptr dereferences in OpenAL, this is really confusing.

**Comment by Kanrinin-sama** [comment]
My friend never told me until recently, but he's getting this too. He's on x64 Win 7. Today, I formatted my machine and have a new Win 10, and it started happening to me as well! (Win10 before today I never had such a problem). This is quite confusing, as I have no idea what I did differently to make this start happening...

This is my log, and I could get his, but I don't know how much it would help at this point.
http://pastebin.com/Cm8dm67P

**Comment by suhr** [comment]
Can be closed now.

**Comment by ProMcTagonist** [comment]
@suhr what was it? Old AV api?

**Comment by suhr** [comment]
qTox video internals changed too, for example today it uses ffmpeg.
