### ISSUE TITLE
Crash under WinXP while establishing video connection

### ISSUE THREAD

**Issue by nullachtfuffzehn** [qTox/qTox#895]
Under WinXP SP3 the program crashes when it tries to establish a video connection. I can see the partner for a couple of seconds. My camera is switching on, but the partner doesn't get the video. Also I can't see the video of the camera in the settings even though it is recoginzed and switched on. It was the same model of camera as my partner has. My partner had Win7. Did I make something wrong in the settings?

**Comment by dubslow** [comment]
Uhhh... I'm not sure the binaries even support XP... @tux3 ?

**Comment by nullachtfuffzehn** [comment]
At least I found no comment, that it wouldn't work under XP. But if not, it's not a biggie for me. It just would be nice also for other users to tell them, that XP is not supported. That would save you from silly questions like mine.

**Comment by tux3** [comment]
It should work under XP, as far as I know. I don't remember using any non-XP API, but I could be wrong.

@nullachtfuffzehn  Can you upload the file qtox.log ? It's in the folder %APPDATA%/tox/

**Comment by nullachtfuffzehn** [comment]
Thanks for your quick response. 
![qtox log](https://cloud.githubusercontent.com/assets/10077962/5345079/1ccf1d5e-7f15-11e4-9832-1a4734e7d551.png)
It's the log file, but the system won't let me load it up, so I renamed into a .png
In the meantime I tried it with another Computer, Win7 Pro, the connection was estabilshed, but I just got a green screen from the opponent, while he could see me clear and fast. I tested the connection another way (RTC-Browserclient) and it worked well.

**Comment by dubslow** [comment]
This is how to do text on Github :)

https://gist.github.com/dubslow/9d0563ba4277295b36ac

**Comment by nullachtfuffzehn** [comment]
Sorry, I have no experience with github... :-D

**Comment by tux3** [comment]
This should be fixed with FFmpeg.
