### ISSUE TITLE
Preserve group chats after restart/disconnect (persistent) & notify on new messages

### ISSUE THREAD

**Issue by Scratch-net** [qTox/qTox#896]
It would be nice to have group chats stored so that me & friends wouldn't have to re-create it every time we start qTox.

Also if there's been a network outage (this happens quite often) I need to ask one of my friends to rejoin me to the groupchat, otherwise it does not work.

One more wish is to be notified on new messages in group chats (as an option). Otherwise we have to keep the window open.

As you can see, we use group chats a lot and would be happy if some of these issues are resolved

**Comment by dubslow** [comment]
This is an issue with toxcore that can't be fixed by any particular client. It's on the list of "we rather need this to be at a basic parity level with Skype" things to do.

**Comment by davidak** [comment]
this is important to make the group chats actual usable.

is there an issue in toxcore repo? you should link it here to see progress.

**Comment by dubslow** [comment]
Progress is best monitored from the tox-groupchats IRC channel on freenode. You can also follow the code [here](https://github.com/JFreegman/toxcore)

**Comment by srkunze** [comment]
I think qTox itself will need changes to work with the new groupchat API, right?

**Comment by dubslow** [comment]
Yes, but new groupchats aren't imminent. The new api, on the other hand, is...

**Comment by srkunze** [comment]
Which means a lot of work to do, I suppose.

**Comment by Onepamopa** [comment]
When can we expect a fix on this ?

**Comment by zetok** [comment]
> When can we expect a fix on this ?

It's not a bug, so there's no fix to expect ;)

There's no hard date. Thanks to effort of numerous people, new groupchats have basic functionality already implemented.

As for when they'll be done (aka parity with current features + new stuff + available in clients), I'd expect them in 2017.

**Comment by diimpp** [comment]
It's kinda almost 2018. :D Is it still a issue within toxcore?

Upd: https://github.com/irungentoo/toxcore/issues/1514 Yes, it's

**Comment by tox-user** [comment]
@diimpp the version of toxcore you linked is outdated and not used anymore. Here is the fork that clients use: https://github.com/TokTok/c-toxcore

**Comment by ghost** [comment]
Is this still being worked on? It would definitely be nice to have persistent group chats even if it would mean somehow storing empty rooms for 48-72 hours.

**Comment by tox-user** [comment]
This feature needs to be implemented in toxcore, not in qTox. There is a branch of toxcore that implements this https://github.com/TokTok/c-toxcore/pull/826 and it works, but it's not 100% stable yet. It seems that people stopped working on it. I've heard some are working on new group chats, which would add this and many other features. With the current (slow) development speed it's hard to predict when those things will be finished. It might take months or years, who knows?

**Comment by NulAsh** [comment]
It's merged in toxcore https://github.com/TokTok/c-toxcore/pull/1069

**Comment by anthonybilinski** [comment]
From TokTok/c-toxcore#1069:
>even then it doesn't work if you restart the client rather than just lose your network connection, because saving and loading isn't implemented (yet).

More work is needed in toxcore (preserving groups across client restart as well) before this ticket can be called complete.

**Comment by ThibaultLemaire** [comment]
Definitely a killer feature. True story: I suggested tox to coordinate in a group work at school (send files and stuff). My comrades were actually pretty open about it until we found out that groups weren't persisted. That was a no-go :disappointed:.


I know this isn't exactly the right place to chime in about group chats (since they're a toxcore issue and all), but I find it to be the most stable place to post. I'm kind of confused with all the toxcore forks.

**Comment by anthonybilinski** [comment]
with https://github.com/qTox/qTox/pull/5417 merged and Toxcore's https://github.com/TokTok/c-toxcore/pull/1156 merged persistent group chats are now functional across client restart. Note that there seem to be some bugs in the Toxcore saving that can corrupt a profile save (which https://github.com/TokTok/c-toxcore/pull/1267 seems to fix), so careful testing them for now.

**Comment by sudden6** [comment]
Persistent groupchats are now implemented and mostly stable.
