### ISSUE TITLE
qtox.exe crashes on startup

### ISSUE THREAD

**Issue by RobinMathewRajan** [qTox/qTox#900]
I'm not a programmer. But from my limited knowledge, I think it's a compatibility issue with the video card driver provided by Intel. But the driver is already up-to-date! Intel won't release anymore driver updates for my Motherboard. How to overcome this problem now? 
# Details

qTox build version: qTox Windows 2014-12-01 21:30:42
# Hardware and Software details of my Computer

Motherboard model: Intel D945GCPE
Motherboard Chipset: Intel 945GC (Lakeport-GC) + ICH7

Video Chipset: Intel GMA950
Video Memory: 256 MBytes
Video Card: Intel 82945G Integrated Graphics Controller [Intel]
Video Bus: PCI
Video RAMDAC: Internal
Video BIOS Version: 1374 PC 14.12  08/28/2006  16:30:16
Video Driver Manufacturer: Intel Corporation
Video Driver Description: Intel(R) 82945G Express Chipset Family
Video Driver Provider: Intel Corporation
Video Driver Version: 8.15.10.1930
Video Driver Date: 23-Sep-2009

Processor: Intel Pentium Dual Core E2180
CPU Stepping: M0
CPU Code Name: Conroe-1M
CPU S-Spec: SLA8Y
Microcode Update Revision: A3

OS: Windows 7 SP1 x86

Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: qtox.exe
  Application Version:  0.0.0.0
  Application Timestamp:    06f8c540
  Fault Module Name:    ig4icd32.dll
  Fault Module Version: 8.14.10.1930
  Fault Module Timestamp:   4aba6fc2
  Exception Code:   c0000005
  Exception Offset: 002095ed
  OS Version:   6.1.7601.2.1.0.256.1
  Locale ID:    16393
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

**Comment by dubslow** [comment]
Could you post the contents of <Roaming App Data thing>/tox/qtox.log please?

**Comment by tux3** [comment]
Note :  <Roaming App Data thing> is %APPDATA%

So that's %APPDATA%/tox/qtox.log

**Comment by RobinMathewRajan** [comment]
Of course, here it is.

https://gist.github.com/dubslow/412ace3107906f2f71b2

**Comment by dubslow** [comment]
Do you click on the Audio/Video settings tab at all, or does qTox crash before you even see the GUI?

@tux3 Each invocation has a VideoSurface::init line, hence my question

**Comment by RobinMathewRajan** [comment]
qTox crashes before rendering the GUI.

Screenshot: http://pub.robinmathewrajan.com/contents/bug_reports/qTox/qTox.png

**Comment by agilob** [comment]
Bump

**Comment by tux3** [comment]
That looks like a problem with OpenCV, but I'm not sure without a backtrace.

**Comment by tux3** [comment]
This is actually a (pretty common apparently) problem with your graphic card's OpenGL support and Qt.

There's no easy way to support your hardware without potentially breaking it on other people's machines, so I'm afraid I won't be able to create a workaround this time.

Closing, since it's not really a problem with the qTox code.
