### ISSUE TITLE
qTox segfaulted when in call

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#901]
qTox 24badc06234b613ecfc18ef9b5bf4a168a0c9459
core f1db6e7d6cb94584fbe03a30aebca36666b6e033 with patch ~https://gist.github.com/zetok/a326be414c73eb64c48f (values in patch I've used slightly differ; s/192/64/ ; s/60/20/ )

Backtrace & log: https://gist.github.com/zetok/baa489ecb4115ac25eaf

There were 2 qTox instances, I think that one that crashed had problem with grabbing audio device.

I've managed to reproduce it, but it doesn't happens always/immediately after starting call. 3rd gistfile is log from reproducing, I've switched i/o devices several times.

EDIT: from libtoxcore.log:

```
12:05 22:10:34  25425   ERROR toxav.c:516          - Failed to encode payload: invalid argument
```

**Comment by Epictek** [comment]
Not sure if this will help
https://gist.github.com/Epictek/520e1889b6149d9eb52e

**Comment by dubslow** [comment]
Are you able to reproduce with only one instance?

@Epictek Type `bt` after it segfaults, that's where the most useful information generally is.

@tux3 We really need that AV overhaul :P

**Comment by Epictek** [comment]
@dubslow

<pre>
(gdb) bt
#0  0x00007ffff26d71a4 in opus_decode ()
   from /usr/lib/x86_64-linux-gnu/libopus.so.0
#1  0x00007ffff79a5c6c in cs_do (cs=0x7fffa807dcd0) at ../toxav/codec.c:386
#2  0x0000000000000000 in ?? ()
</pre>

**Comment by dubslow** [comment]
...that's it? Wow

**Comment by Epictek** [comment]
yep...

**Comment by tux3** [comment]
Yeah, I had the same bug some time ago, can't remember what happened. Something somewhere near the audio code is destroying the stack.

**Comment by zetok** [comment]
https://github.com/irungentoo/toxcore/commit/af0d6c0695e3c459989b911b6fb62ce40058440e probably fixed it, will have to check later

**Comment by zetok** [comment]
No longer segfaults, but there's still a problem with missing audio (#1090). If I stumble upon it again, I'll reopen.
