### ISSUE TITLE
qTox trims indentation

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#902]
qTox trims indentation, making it impossible to nicely share indented text.

For example:

```
@media only screen and (max-width: 480px) {
  .top-bar .name
  {
    color: #01A9DC;
  }
  .top-bar .name span
  {
    color: #292929;
  }
}
```

Gets displayed as

```
@media only screen and (max-width: 480px) {
.top-bar .name
{
color: #01A9DC;
}
.top-bar .name span
{
color: #292929;
}
}
```

When having text with multiple levels of indentation, or things like a short Python snippet (which is a language sensitive to indentation), it basically makes the snippet unuseable. It'd be nice to not have to resort to a file transfer for just a few lines of text.

**Comment by zetok** [comment]
It's not and enhancement, it's a bug. Why does qTox mess with user input in the first place?

**Comment by dubslow** [comment]
qTox uses HTML in the chat form, it's not directly qTox's fault. Maybe wrap messages in <pre></pre>?

**Comment by zetok** [comment]
ah, so it'll be solved by 3rd chat form?

**Comment by tux3** [comment]
Is there anything that 3rd chat form won't solve ? I don't think so :)

**Comment by zetok** [comment]
since fix was reverted, please reopen

**Comment by ArchangeGabriel** [comment]
Note that non-breakable space is not an option anyway, they would be copied as non-breakable space, which won’t work in Python for instance.

**Comment by zetok** [comment]
#2013 has it fixed.

**Comment by ghost** [comment]
It does even worse than that with me, with me it forces the whole lot onto one line.

**Comment by zetok** [comment]
Since I can't reproduce lines being joined, would you mind providing some test code sample?

**Comment by zetok** [comment]
@SeventhSonOfASeventhSon also, which qTox version?

**Comment by ghost** [comment]
@zetok: Example:

So that this:

```
for (int i = 0; i < 5; i++){
    System.out.println(i);
    System.out.println(i);
    System.out.println(i);

}
```

Becomes this:

```
for (int i = 0; i < 5; i++){System.out.println(i);System.out.println(i);System.out.println(i);}
```

**Comment by ghost** [comment]
@zetok: qTox version `1.3.0-38-ga48c422-1`.

**Comment by zetok** [comment]
That's weird, on exactly the same version (a48c4225938834db0d4406cff54a07378e9636f4) I can't reproduce lines being joined.

~~What OS are you using?~~ nvm, I've read issue again.

**Comment by ghost** [comment]
@zetok: Ubuntu GNOME 15.10 with GNOME 3.18.

**Comment by zetok** [comment]
Ok, I could reproduce the problem with the other code sample from issue #3016 - lines being joined is not this issue, but #3016.

**Comment by ghost** [comment]
@zetok: Though it's probably related in some way, how does a strange illegal character being put in have anything to do with all lines being joined?

**Comment by zetok** [comment]
This issue was fixed, thus closing.
