### ISSUE TITLE
Crash on audio call start

### ISSUE THREAD

**Issue by Haarolean** [qTox/qTox#904]
Hi,

I tried to send file to AudioM8 and call him. I can't hear anything or even client crashes right after pressing call button. Last version.

**Comment by Haarolean** [comment]
Audio doesn't even work in qTox completely.

**Comment by dubslow** [comment]
Yeah... AV needs some love in qTox

**Comment by tux3** [comment]
Please post the qtox.log or a backtrace if you know how to get one.

**Comment by Haarolean** [comment]
@tux3 no idea. Didn't find anything in %appdata%/tox folder. Where can I find it?

**Comment by dubslow** [comment]
It really should be %APPDATA%/tox/qtox.log, that's the only place it should be

**Comment by Haarolean** [comment]
@dubslow https://gist.github.com/Zeluboba/1c57930df8c000dd4b90

**Comment by tux3** [comment]
This should be fixed as of today.
