### ISSUE TITLE
Copypaste doesn't work

### ISSUE THREAD

**Issue by Haarolean** [qTox/qTox#906]
No needed articles on right-click menu. Ctrl+C doesn't work as well. Last version.
We need to do it very quickly using ctrl+c and pressing mouse on text.

**Comment by Xylemon** [comment]
Same here, would like to see this fixed in chat.

**Comment by dubslow** [comment]
Ctrl+C works in the usual way for me, though having it on the context menu would be nice as well...

**Comment by zetok** [comment]
I had some problems with copying from qTox, it didn't work always, and when it "worked", it did not copy all selected text

Possibly will be fixed with 3rd chat?

**Comment by dubslow** [comment]
I certainly hope so. I haven't seen much from @krepa098 lately though.

**Comment by ghost** [comment]
Copy+paste is broken for me as well. On the rare occasion I can copy at all, it only copies the very last line of text.

**Comment by krepa098** [comment]
> I certainly hope so. I haven't seen much from @krepa098 lately though.

Yes I'm currently running short on time.

> Possibly will be fixed with 3rd chat?

Selection is an implementation detail so this is what I came up with:
![interface1](https://cloud.githubusercontent.com/assets/4587853/5357399/65f2086a-7fa7-11e4-8814-2248bc615b3f.jpg)
Precise selection (only within the same message)

![interface2](https://cloud.githubusercontent.com/assets/4587853/5357395/62545366-7fa7-11e4-94ad-0f180a52d8df.jpg)
Multi-message selection

Suggestions?

**Comment by zetok** [comment]
@krepa098 about multi-message selection:

By starting selection from text message only, only message text will be selected.
By starting selection from timestamp, timestamp and message will be selected, unless selection would end at nick, then everything would be selected.
Selection started from nick would behave in similar way to selection by timestamp, but in opposite direction.

I hope it is possible to implement it like that?

**Comment by dubslow** [comment]
@krepa098 I would like to add you on Tox so we can communicate more, as opposed to merely over Github issues which isn't really appropriate for general discussion. I'm `dubslow@toxme.se`. (@tux3 and @apprb may be interested as well.)

**Comment by Haarolean** [comment]
copypaste is not the biggest curernt problem for qTox.

**Comment by dubslow** [comment]
True, but if we want it to be a quality program, the chatform will need a total rewrite.

**Comment by zetok** [comment]
I've noticed that ~~copypaste~~ copying from qTox stopped working completely for me after #857 got merged

**Comment by Haarolean** [comment]
For me, selected text becomes inactive instantly and still there's no 'copy' item in right-click menu.

**Comment by Jookia** [comment]
When you select text the cursor goes back to the chat box so you can type, and there's nothing to copy there, but if you don't let go of the selection and hold the mouse button in and click it works. Perhaps selecting should keep focus in the chat window, or re-focus when typing.

**Comment by olologin** [comment]
https://bugreports.qt.io/browse/QTBUG-32274?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel

Keyboard shortcuts (In multi-language mode) doesn't work in X11 because of QTextEdit bug, but it fixed in 5.4, if someone build it with 5.4 i think at least 1 annoying bug disappears

**Comment by dubslow** [comment]
GUI issue fixed by new chatform, comment for reopen
