### ISSUE TITLE
Dns resolve is broken

### ISSUE THREAD

**Issue by Haarolean** [qTox/qTox#907]
Users can't add me using tox1 record.
I'm zeluboba@cronfire.ru.
Record is valid.

**Comment by suhr** [comment]
Tox DNSv1 considered insecure.

**Comment by Epictek** [comment]
#886

**Comment by Haarolean** [comment]
@suhr It should be supported. As @irungentoo said.

**Comment by rbi** [comment]
Tox1 still does not work for me. I've tried it with my own DNS record and with "zeluboba@cronfire.ru" from above which still seem to have a valid TXT record. I can see the message box asking if I want to use unsecure tox1. When I confirm it another message box appears telling that the Tox ID does not exist.

Looking at the network traffic with wireshark qTox seams to only query for "_tox.cronfire.ru" before the first message box appears. After I confirmed it no more DNS queries where attempted.

I tried it with version c568a4db051762c3ec084415194df9335b4b1d55.
