### ISSUE TITLE
Segfault with system tray settings

### ISSUE THREAD

**Issue by Epictek** [qTox/qTox#908]
https://gist.github.com/Epictek/e2c0e63cf9c7460505e1
Tried  making a new config directory and that didn't solve it

**Comment by dubslow** [comment]
If you compile it yourself, please try it with debugging symbols as well.

How often is this reproducible? Consistently, sometimes, or rarely?

**Comment by Epictek** [comment]
https://gist.github.com/Epictek/b5a33d87f599c6b34fa6
Happens consistently at every startup, started after I updated toxcore I believe.

**Comment by Epictek** [comment]
still have this problem :(

**Comment by dubslow** [comment]
The backtrace is consistent as well, correct?

**Comment by Epictek** [comment]
Yes

**Comment by dubslow** [comment]
Do you compile it yourself, or do you use a binary from somewhere?

**Comment by Epictek** [comment]
I usually compile it myself but I have also tried the binary from the jenkins

**Comment by Epictek** [comment]
Just tried an older build and it seems to be working fine.
could this be the problem?

> #1  0x000000000045162a in Widget::updateTrayIcon() ()

I don't have a system tray, I use dwm windows manager

**Comment by Epictek** [comment]
build #434 seems to be the last build that works

**Comment by dubslow** [comment]
Uh... what build is that? 434 is a pull request from ages ago... We can chat on IRC if that'd be faster.

**Comment by Epictek** [comment]
https://jenkins.libtoxcore.so/job/qTox-linux-amd64/434/

Off to bed soon but can chat in IRC tomorrow if we need to

**Comment by dubslow** [comment]
Okay. If you don't mind, a `git bisect` would be fantastic. I'm `bunslow` on IRC, pm me whenever you're on. (Actually, I might have some errands to do tomorrow, I'll try and respond though.)

**Comment by Epictek** [comment]
e989379535ae4f9c1edeea62633b4e7a5b5395b9 is the first bad commit
commit e989379535ae4f9c1edeea62633b4e7a5b5395b9
Author: Maximilian
Date:   Wed Nov 26 16:57:25 2014 +0100

```
Refactored system tray settings in generalform
```

:040000 040000 19a902e786138dc984b6c9c688e07f913527ded0 9c10bff0d499442ce537e624a7027328f0cb00f0 M  src
