### ISSUE TITLE
crash on close when updating [updater module issue]

### ISSUE THREAD

**Issue by hethhhhh** [qTox/qTox#909]
Hello there.
I'm having some issues when updating qTox via the build in updater. I'm using qTox32 builds from:
https://github.com/tux3/qTox/releases
I'm on Windows 7 64bit.

When I install and run qTox, when there is an update available it offers to download and install it later.
When I confirm and close the client, the qTox process stays in memory in an endless loop on one of the CPU cores. I have to kill it and restart manually. Then the process restarts, and I can press "Yes" again on the update, repeating the aforementioned cycle.

I've been updating manually every time a new release is up, but that's getting a bit tedious with everyday releases now.

Any clues what's wrong? there is nothing in the log file about the update and/or crash.

This behaviour is from the first time I installed qTox, about a month or so ago.

Tested with the pre-latest release.

**Comment by tux3** [comment]
I'm on it.

**Comment by hethhhhh** [comment]
This issue is still a problem in the current releases.

**Comment by dubslow** [comment]
The updaters were disabled today until qTox gets new api support. Are you sure?

**Comment by dubslow** [comment]
You shouldn't have gotten any version yesterday I mean... unless you got an old version that you reinstalled yesterday?

**Comment by dubslow** [comment]
Ah. tux3 was telling me he's had issues getting Windows builds working with the new QR code stuff, so maybe a false update was accidentally pushed while he was fiddling with that?

**Comment by tux3** [comment]
I was careful not to push any bad updates when tinkering with the QR codes, so it's not that.

@hethhhhh Can you post the content of the qTox log ?

I think I know what could be the problem, since the jenkins publishes updates every few days, but we haven't actually built anything, Jenkins just pushes empty updates with a new timestamp.

So qTox thinks there's a new updates, downloads nothing since nothing changed, and the empty update doesn't actually get installed, so there's the infinite loop.

I went ahead and removed the version files from the update server until this gets fixed.

**Comment by hethhhhh** [comment]
tail from qtox.log

2015-05-04 14:12:58 file logger starting
14:12:58 built on:  07:51:41 Jan 15 2015 ( 1421308168 )
14:12:58 commit:  33dfb8896257a0b3e30b4bc491abf01bb2f22f77 

14:12:58 IPC: Our global ID is  212379246<CUT>
14:12:58 IPC: Creating the global shared memory and taking ownership
14:12:58 Core: loading Tox from "C:/Users/<user>/AppData/Roaming/tox/<handle>.tox"
14:12:58 Audio:  "Trying to open output Speakers (2- Realtek High Definition Audio)"
14:12:58 Audio: Opening audio output  "Speakers (2- Realtek High Definition Audio)"
14:12:58 Audio:  "Trying to open input Microphone (2- Realtek High Definition Audio)"
14:12:58 Audio: Opening audio input  "Microphone (2- Realtek High Definition Audio)"
14:12:59 Core starting with IPv6 enabled
14:12:59 Core::loadConfiguration: reading from  "C:/Users/<user>/AppData/Roaming/tox/<handle>.tox"
14:13:00 VideoSurface: Init
14:13:00 VideoSurface: Init
14:13:00 VideoSurface: Init
14:13:00 VideoSurface: Init
14:13:00 VideoSurface: Init
14:13:00 VideoSurface: Init
14:13:00 VideoSurface: Init
14:13:00 VideoSurface: Init
14:13:00 VideoSurface: Init
14:13:00 VideoSurface: Init
14:13:00 VideoSurface: Init
14:13:00 VideoSurface: Init
14:13:00 timestamp: 1426360174 , str: "ac9b327fe7eb6c05c9ac353128de6593<CUT>"
14:13:01 Core: Bootstrapping to the DHT ...
14:13:01 "Core: Bootstrapping from <CUT>"
14:13:01 "Core: Bootstrapping from <CUT>"
14:13:06 Core: Connected to DHT
14:13:06 Settings: Saving in  "C:/Users/<user>/AppData/Roaming/tox/qtox.ini"
14:13:06 Core: writing tox_save to  "C:/Users/<user>/AppData/Roaming/tox/<handle>.tox"
14:13:07 Core: Disconnected to DHT
14:13:09 Core: Bootstrapping to the DHT ...
14:13:09 "Core: Bootstrapping from <CUT>"
14:13:09 "Core: Bootstrapping from <CUT>"
14:13:12 Core: Connected to DHT
14:13:12 Settings: Saving in  "C:/Users/<user>/AppData/Roaming/tox/qtox.ini"
14:13:12 Core: writing tox_save to  "C:/Users/<user>/AppData/Roaming/tox/<handle>.tox"
14:16:47 Settings: Saving in  "C:/Users/<user>/AppData/Roaming/tox/qtox.ini"
14:16:47 Core: writing tox_save to  "C:/Users/<user>/AppData/Roaming/tox/<handle>.tox"
14:16:48 Audio:  "Closing input"
14:16:48 Audio:  "Closing output"

2015-07-04 23:27:09 file logger starting
23:27:09 built on:  07:51:41 Jan 15 2015 ( 1421308168 )
23:27:09 commit:  33dfb8896257a0b3e30b4bc491abf01bb2f22f77 

23:27:09 IPC: Our global ID is  31783404<CUT>
23:27:09 IPC: Creating the global shared memory and taking ownership
23:27:09 Core: loading Tox from "C:/Users/<user>/AppData/Roaming/tox/<handle>.tox"
23:27:09 Audio:  "Trying to open output Speakers (2- Realtek High Definition Audio)"
23:27:17 Audio: Opening audio output  "Speakers (2- Realtek High Definition Audio)"
23:27:17 Audio:  "Trying to open input Microphone (2- Realtek High Definition Audio)"
23:27:17 Audio: Opening audio input  "Microphone (2- Realtek High Definition Audio)"
23:27:31 Core starting with IPv6 enabled
23:27:31 Core::loadConfiguration: reading from  "C:/Users/<user>/AppData/Roaming/tox/<handle>.tox"
23:27:31 VideoSurface: Init
23:27:32 VideoSurface: Init
23:27:32 VideoSurface: Init
23:27:32 VideoSurface: Init
23:27:32 VideoSurface: Init
23:27:32 VideoSurface: Init
23:27:32 VideoSurface: Init
23:27:32 VideoSurface: Init
23:27:32 VideoSurface: Init
23:27:32 VideoSurface: Init
23:27:32 VideoSurface: Init
23:27:32 VideoSurface: Init
23:27:32 timestamp: 1426360174 , str: "ac9b327fe7eb6c05c9ac353128de6593<CUT>"
23:27:33 Core: Bootstrapping to the DHT ...
23:27:33 "Core: Bootstrapping from <CUT>"
23:27:33 "Core: Bootstrapping from <CUT>"
23:27:34 Core: Connected to DHT
23:27:34 Settings: Saving in  "C:/Users/<user>/AppData/Roaming/tox/qtox.ini"
23:27:35 Core: writing tox_save to  "C:/Users/<user>/AppData/Roaming/tox/<handle>.tox"
23:27:36 Core: Disconnected to DHT
23:27:37 Core: Bootstrapping to the DHT ...
23:27:37 "Core: Bootstrapping from <CUT>"
23:27:37 "Core: Bootstrapping from <CUT>"
23:27:40 Core: Connected to DHT
23:27:40 Settings: Saving in  "C:/Users/<user>/AppData/Roaming/tox/qtox.ini"
23:27:40 Core: writing tox_save to  "C:/Users/<user>/AppData/Roaming/tox/<handle>.tox"
23:27:41 Core: Disconnected to DHT
23:27:42 Core: Connected to DHT
23:27:42 Settings: Saving in  "C:/Users/<user>/AppData/Roaming/tox/qtox.ini"
23:27:42 Core: writing tox_save to  "C:/Users/<user>/AppData/Roaming/tox/<handle>.tox"
23:28:02 Settings: Saving in  "C:/Users/<user>/AppData/Roaming/tox/qtox.ini"
23:28:02 Core: writing tox_save to  "C:/Users/<user>/AppData/Roaming/tox/<handle>.tox"
23:28:03 Audio:  "Closing input"
23:28:03 Audio:  "Closing output"

**Comment by tux3** [comment]
There is a partial fix, so this shouldn't be an issue anymore.
