### ISSUE TITLE
On OS X, the call buttons overlap

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#910]
~~The OS X before Yosemite~~ Mavericks with a retina display, regardless of size

![sarah2](https://cloud.githubusercontent.com/assets/6127392/5334791/3dc3b64c-7e60-11e4-85ac-330807677ec6.png)

**Comment by antonkai2k** [comment]
I see same on Mavericks 10.9.5, not Retina display.

**Comment by dubslow** [comment]
And you have the latest qtox? There was a fix committed, but I forgot to close this...

**Comment by antonkai2k** [comment]
Probably yes, I downloaded today from link on main page (https://dist-build.tox.im/qtox.dmg).
Can't find any info about version in settings or somewhere.

**Comment by dubslow** [comment]
If you downloaded it today, then it's up to date... damn.
