### ISSUE TITLE
It takes an awfully long time to connect either with 32-bit or 64-bit versions on Windows 7 64-bit

### ISSUE THREAD

**Issue by ShedoSurashu** [qTox/qTox#913]
Hi! I just got to installing qTox and noticed that it takes an awful lot of time to connect and indicate me as "online". I've tried both 32-bit and 64-bit builds. I've timed at upwards over 5 minutes before the indicator beside my name lights up. Is this normal behavior? My internet doesn't seem to have any problem either. Ontop of that I can't see any online friends either.

**Comment by dubslow** [comment]
Nothing has changed in the qTox or core code recently.

Can you check other clients (e.g. uTox)? Did qTox used to work and recently break?

**Comment by ShedoSurashu** [comment]
Okay, I just tried uTox and it seems to be suffering the same problems. Sorry for the confusion! Where should I direct these questions to? Now I know it isn't a qTox problem.

**Comment by dubslow** [comment]
https://github.com/irungentoo/toxcore
