### ISSUE TITLE
Crash when setting audio/video settings when jack server running

### ISSUE THREAD

**Issue by richard-uk1** [qTox/qTox#915]
When I turn off my jack server, qTox works fine, but when I turn it on and try to select an av output, my system crashes.

**Comment by tux3** [comment]
Could you post the content of ~/.config/tox/qtox.log assuming you're on linux, and maybe a backtrace if you know how to generate one ?

Maybe this willll provide some insight on why the A/V settings crash on OS X.

**Comment by richard-uk1** [comment]
Hi sorry I didn't see your response - I'll get a stacktrace :)

**Comment by dubslow** [comment]
We're usually pretty good about reading and responding to issues. :)

**Comment by richard-uk1** [comment]
I've repeated the issue, apologies but my system doesn't crash, it hangs. Shall I try running it in a debugger and see where it's getting stuck?

**Comment by dubslow** [comment]
Absolutely. No information is bad information. (Just use debugging symbols where possible, and pastebin or gist it rather than straight pasting it here lol.)

**Comment by agilob** [comment]
ymm. no response and no duplicated. please someone make a decision about closing it.

**Comment by richard-uk1** [comment]
This is old and I don't use qTox atm so I suggest closing if no-one else has the issue.

**Comment by zetok** [comment]
I see.
If you would happen to want to retest this, static qTox builds are available: https://wiki.tox.chat/binaries#other_linux

If after retesting issue still be there, please comment for reopen.
