### ISSUE TITLE
Busy icons are inconsistent

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#916]
![inconsistent busy icon](https://cloud.githubusercontent.com/assets/4358079/5365631/73180ad0-7fa2-11e4-95b4-105901eb68ad.png)

**Comment by dubslow** [comment]
I know. Hopefully Soon™ the regular icon will match the tray icon.

**Comment by ProMcTagonist** [comment]
The busy icons are consistent across the interface. Their needed redesign is covered in #1151.
