### ISSUE TITLE
href being stripped from messages

### ISSUE THREAD

**Issue by brylie** [qTox/qTox#924]
When sending a message with the following content:

```
<link rel="stylesheet" href="http://openlayers.org/en/v3.0.0/css/ol.css" type="text/css"\>
```

It comes out on the receiving end like this:

```
<link rel="stylesheet" href=" type="text/css">
```

Oddly enough, the copy/pasted text on the receiving end is correct - it just displays incorrectly in the messenger.

**Comment by ghost** [comment]
That's a bug in the chat form. It uses regular expressions to filter the text ment to display, e.g. for toxURIs and links. I think a better parser / regexp should be written.

**Comment by zetok** [comment]
Closing, since I couldn't reproduce with supplied sample.

If you're still affected, please comment for reopen.
