### ISSUE TITLE
Notifications in MATE + Notification bar

### ISSUE THREAD

**Issue by Dirius77** [qTox/qTox#925]
I don't know if it is just me who is having the problem. But qTox does not send notifications or display in the notifications bar. uTox will send notifications but it doesn't display in the bar (Skype and qBittorrent both do so I know it's working)

**Comment by zetok** [comment]
https://github.com/tux3/qTox/issues/247#issuecomment-59648897 ← tray support under MATE

Notifications aren't yet implemented in qTox

**Comment by suhr** [comment]
Close is favour of https://github.com/tux3/qTox/issues/483.

**Comment by agilob** [comment]
> the notifications bar 

this should be fixed a long time ago and notifications are awaiting merge.
