### ISSUE TITLE
Option in right-click menu to "Copy URL" when right clicking on a link

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#927]
Subj.

**Comment by Hasshu** [comment]
(Shameless) bump.

No matter how you look at it, an issue with (at least) 4 duplicates cannot be "P-low".

**Comment by Hasshu** [comment]
@zetok Thanks.

**Comment by ProMcTagonist** [comment]
Doesn't do anything yet (actually it puts "This should be a link!" into the clipboard)

![copy link address](https://cloud.githubusercontent.com/assets/4358079/20250153/18581c2c-a9bf-11e6-8dbf-2b4c37d09a17.png)

Don't know how exactly to get the text from the message that was clicked on, or only show up when clicking on a link. Looking at Quassel right now (thanks @zetok). Advice appreciated.

Quassel:
https://github.com/quassel/quassel/blob/d29a6e9521e27e5d4d86fec82b5daa71085f87a5/src/qtui/chatitem.cpp#L801

**Comment by zetok** [comment]
@ProMcTagonist could you open a WIP PR with the code you already have added?
