### ISSUE TITLE
Status to indicate 'Currently connecting to Tox network'

### ISSUE THREAD

**Issue by DanTheBritish** [qTox/qTox#929]
Currently, being offline and connecting to the network show the same gray status, could be useful to add one which shows that qTox is currently connecting, not just sitting idle.

**Comment by zetok** [comment]
qTox never sits idle, AFAIK. If it's not connecting, then it's a core bug.

**Comment by dubslow** [comment]
Yes it does, unfortunately. It's one of the issues I assigned to myself (and haven't yet collected enough roundtuits).

**Comment by DanTheBritish** [comment]
This was done a while ago, thanks contributors!

![image](https://cloud.githubusercontent.com/assets/4997521/10575943/c250c8e2-7657-11e5-87a6-4c2d95c3f56e.png)
