### ISSUE TITLE
URL detection breakage

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#932]
Somehow, qTox added text after the URL to the URL
![snapshot131](https://cloud.githubusercontent.com/assets/1885159/5423622/0f52e722-82c7-11e4-8a59-2637e9c2c546.png)

URL generated: https://toxme.se/%C2%A0built%C2%A0directly%C2%A0into%C2%A0the%C2%A0clients

%C2%A0 seems to be the unicode for `&nbsp;`, so I believe this is likely a regression caused by cc4cc7d7a8124618bf183872a2c8904fc86a655c

**Comment by TheLastProject** [comment]
Update: cc4cc7d also broke line-breaking on full words. Maybe spaces should only turned into `&nbsp;` at the beginning of a line?
![snapshot132](https://cloud.githubusercontent.com/assets/1885159/5423676/f2fb7e92-82c9-11e4-97ff-937c645ae2ca.png)

**Comment by ArchangeGabriel** [comment]
This should be closed I think, since the corresponding commit has been reverted and the original issue is still tracked at #902.

**Comment by zetok** [comment]
https://github.com/tux3/qTox/pull/974#issuecomment-68583709 related?
