### ISSUE TITLE
Sending /dev/urandom to your friend segfaults qTox

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#934]
qTox e7cad9b942fd5878138f181bc47f81658452759b

https://gist.github.com/zetok/abdc084f919c9c52073d

**Comment by dubslow** [comment]
I specifically recall tux3 adding code to prevent this...

**Comment by zetok** [comment]
Yes.
It worked well, but since I _really_ needed to send /dev/urandom with qTox I worked around it by drag&dropping /dev/urandom into qTox, rather than choosing it with file picker.

:3

**Comment by Haarolean** [comment]
Lol, that's funny.

**Comment by dubslow** [comment]
> worked around it
