### ISSUE TITLE
Enable building with shared libraries

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#941]
Building with shared libraries would make using different tox clients in parallel much easier.
If the dependencies are alreadiy installed it would also reduce the build process to:
qmake
make

**Comment by tux3** [comment]
Well, you can alreay build with shared libraries. If they are correctly installed on your system, qmake should find them.

I'm not sure what you mean ?

**Comment by sudden6** [comment]
I mean that by default qTox takes all libraries from the directory from the directory where simple_make.sh puts them, but there is no (easy) way to tell the build system it should take the libraries from the default paths like /usr/lib/, /usr/local/lib... whatever it is on your linux distribution.

This would allow the user/tester to use one toxcore with different clients and compare the behavior.
I think that there should atleast be an argument to qmake to enable this behavior. Also this follows more the normal unix way of compiling software.

I hope this clarifies what I try to achieve.

**Comment by dubslow** [comment]
Indeed, that's very good clarification.

**Comment by sudden6** [comment]
I just went ahead and did something, it works for me, but it should get tested.

**Comment by dubslow** [comment]
I was looking at your PR, but I'm realizing that by default bootstrap.sh does use global locations. You have to manually pass it the --local option to have any libraries in the qtox folder. In other words, as far as I can tell, this is already the case.

You can test this by completely obliterating your qtox clone, recloning and running simple_make.sh again, then `sudo updatedb` followed by `locate tox.h`. You should find the on in libs/libtoxcore-latest/toxcore/tox.h (which isn't searched by the build system in any way with any possible options), and the global one.

**Comment by sudden6** [comment]
You are right, the libraries are by default installed in global locations.
But the build system stil adds `-Ilibs/include` to gcc options, which should be no problem if the globaly installed header and the local one are identical, but if they are different I don't know which one is choosen.

Edit: I got a great idea how to solve this:
just supply `INCLUDEPATH += libs/include` and `LIBS += -L$$PWD/libs/lib/` by commandline to qmake only if the --local option is present.

**Comment by zetok** [comment]
The easy way of telling build system to ignore libraries in `libs/` is to remove that directory.

`simple-make.sh` is not intended to replace using just `qmake`, but merely provide an easy way of compiling qTox for those who can't ~~get a proper distro~~ figure out how to install/compile all needed dependencies.

`qmake` uses by default system libraries - if you want to override that, you put libraries in `libs/`

Closing, since it's possible to build qTox with shared libraries, and they're being used by default, provided that one doesn't use `simple-make.sh`.
