### ISSUE TITLE
Avoid greentexting `>_<`

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#945]
Possible solution: don't greentext if next character is less than A or is not a space symbol.

**Comment by zetok** [comment]
I have to disagree on that, I like `>_<` and `>.<` being greentexted. Perhaps if spaces weren't trimmed (#902) one could simply put a space before `>` to avoid greentexting.

**Comment by DanTheBritish** [comment]
:+1: for leading space to avoid greentext

**Comment by ProMcTagonist** [comment]
I agree with the leading space solution.

**Comment by tux3** [comment]
Wontfix for now, then.

**Comment by tux3** [comment]
Oh wait #902 is still open, reopening.
