### ISSUE TITLE
Parallel file uploading uses too much CPU

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#946]
~~Subj.~~ Also, CPU usage is too high.
UPD: well, actually jumping to conclusions. But CPU usage is still high.

**Comment by dubslow** [comment]
How high? Can you be more specific? What processor, how many files of what size, and how much of the core(s)?

Can you profile it to see if it's the encryption time?

**Comment by suhr** [comment]
> What processor

AMD Athlon(tm) 64 X2 Dual Core Processor 5000+

> how many files of what size

~20 with size ~30 MiB.

> Can you profile it to see if it's the encryption time?

Well, I'll try to do this.

**Comment by suhr** [comment]
So, I have run two qTox client with different profiles (one to upload and other one to download), and there's some [flamegraph](http://www.brendangregg.com/flamegraphs.html) (profiled with perf): http://rghost.net/59793373.

Looks like the time of Core::fileTransferInfo is really big.

**Comment by dubslow** [comment]
Excellent, this is the most useful issue report I've seen in a while. :)

Unfortunately, my phone can't open svgs, much less write code...

**Comment by suhr** [comment]
Related: https://github.com/tux3/qTox/issues/266

**Comment by krepa098** [comment]
I guess emitting Core::fileTransferInfo about 4 times per second (instead of 1000x) should be more than enough, right?

**Comment by suhr** [comment]
The new flamegraph, with the new chatform: http://a.pomf.se/dolzbx.svg

**Comment by tux3** [comment]
This is fixed by the new API. 

However I recently pushed a new patch that significantly improves file transfer speed at the cost of more CPU time. If this is still a problem with the new API, please leave a comment.
