### ISSUE TITLE
win32 build config screwed?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#948]
I went through pains of building qTox on windows and i discovered that somehow it fails to build with current config.

I had to move **-liphlpapi** after -lws2_32 because of linker errors.
I had to move **-lsodium** after -ltoxdns because of linker errors.
qTox links to bunch of unnecessary libraries. I removed **-ljpeg -ltiff -lpng -ljasper -lIlmImf -lHalf** and finally it built correctly.

All these changes were done inside win32 { } case. Now i wonder how win32 builds are compiled by buildbot if default config is broken? I did this with mingw 4.9, nothing fancy.

So should i make PR with these fixes..?

**Comment by zetok** [comment]
Yes, PR should definitely be made.
I guess with it #843 could be finally closed?

**Comment by dubslow** [comment]
@tux3

**Comment by tux3** [comment]
I'm surprised that you had to move iphlpapi and sodium, it somehow works just fine on the build bot in that order.

On the other hand  -ljpeg -ltiff -lpng -ljasper -lIlmImf -lHalf are leftovers from when I tried to link OpenCV statically. That was a bad idea.
