### ISSUE TITLE
Right-click Copy friend ID

### ISSUE THREAD

**Issue by Selena-Gomez** [qTox/qTox#951]
When doing so, it doesn't copy the entire ID.
eg (first is entire ID):
56A1ADE4B65B86BCD51CC73E2CD4E542179F47959FE3E0E21B4B0ACDADE51855D34D34D37CB5
56A1ADE4B65B86BCD51CC73E2CD4E542179F47959FE3E0E21B4B0ACDADE51855

**Comment by zetok** [comment]
@tux3 see? it's broken and confuses users

**Comment by dubslow** [comment]
Core does not provide any way for qtox to get the full address, only the id. Qtox has code to work around this, but apparently that isn't working here...

**Comment by zetok** [comment]
@dubslow it never worked

**Comment by apprb** [comment]
It's working. Full toxid is stored in [profile name].ini file but only for friend added by you. Of course if you delete you *.ini file you lose full toxid.

**Comment by tux3** [comment]
Here's an idea. 
If we don't have the full Tox ID, we show an error. Otherwise we return the full ID.

Opinions ?

**Comment by dubslow** [comment]
Rather than an error, show a warning that it's not the full address and put the id in clipboard anyways.

**Comment by zetok** [comment]
I still think that it would be better to not provide this, but if it _has_ to be there, then warning is a good idea.

**Comment by tux3** [comment]
I'm not sure why this isn't in toxcore in the first place. You'd think there would be a sane way to find the contact info of someone who's already in your contact list.

**Comment by taschenlampe** [comment]
Is there any update concerning this issue? Still having this "cut effect". Cheers!

**Comment by taschenlampe** [comment]
No, news concerning this issue? How would you suggest to copy an ID to a chat/an other user using qtox? Any suggestions. Cheers.

**Comment by zetok** [comment]
@taschenlampe it won't (ever) be fixed.

If it's about suggestions, dunno, ask your friends for Tox ID..

If you just want to share friends, then that will be possible in the future (no ETA).

**Comment by zetok** [comment]
@dubslow it's not an upstream problem, it's problem with qTox doing stuff that is not supported, and is known to be broken.

**Comment by dubslow** [comment]
So you'd prefer to remove it entirely?

I thought you were the one who asked for it...?

**Comment by zetok** [comment]
@dubslow I never said that I want it, and I was always saying that it should be at least renamed to `Copy friend's Public Key`, or removed entirely from that dialog, since it's misleading and only confuses users.

**Comment by ProMcTagonist** [comment]
What are core's oppositions to providing a method of getting friend ID? If they're offline they could have changed nospam and made it useless, which could lead to user confusion?

**Comment by dubslow** [comment]
@ProMcTagonist If the friend added you, you don't even have their nospam

**Comment by ProMcTagonist** [comment]
That's what a core method would solve. But the last time I saw gentoo talking about it he expressed that you should just message them and ask for it instead.

**Comment by zetok** [comment]
> That's what a core method would solve.

No.
Core will not provide info on your friends' nospam; there will be a way of sharing friends you have added without it though.

**Comment by agilob** [comment]
Toxcore issue once again. https://github.com/irungentoo/toxcore/issues/1300

**Comment by rysiekpl** [comment]
Sorry to beat this (apparently) dead horse, but I do believe there is an argument to be made for the Tox clients (like qTox) to keep the full 76-digit ToxID in cache for users to be able to copy.

My use-case: I work in a large-ish organisation that _requires_ secure, secret communication. Tox (specifically, qTox and uTox) is one of our tools of choice. We have people that we need to talk with all across the globe, and we need to be able to share contacts (in this case, full ToxIDs) between ourselves -- also when the person whose ToxID is being shared is offline at the moment.

There is no way to do this currently, and waiting for that person to come on-line, _then_ asking them to provide their ToxID, and _then_ sharing it with the person that needs to contact them, and _then_ again waiting until both are on-line -- takes much too much time, and is completely unintuitive.

If qTox could cache the _full_ ToxID, and make it available for the user _with a disclaimer_ saying for example: "This ToxID might have become stale; in case of connection failure, please verify with your contact if that this is still their ToxID" -- that would be a huge boon for us, and would make it easier to convince people to use qTox that much easier.

Come to think of it, couldn't qTox just verify that the ToxID in question is still valid?

**Comment by tux3** [comment]
@rysiekpl The problem is that there's no way to make it work well without toxcore support.
We can have qTox remember the ToxID when you add someone, this is what we used to do, but when someone else adds you qTox doesn't know the full ID.
And there's no way to check that a full ID is valid as far as I know, since only the person who owns that ID can check the NoSpam.

I agree that this would be a nice feature to have. If toxcore won't implement it, then there's always the option of writing protocol extensions. I've avoided writing any extensions for the sake of compatibility, but maybe it's time.

**Comment by rysiekpl** [comment]
@tux3 it doesn't have to work for _every_ contact. Just working for contacts the user added herself would be a huge boon!

For others, there could be information saying "you do not have the full ToxID, as you have not added this contact (the contact added you). You can ask the contact to provide the full ToxID and paste it here: `[textbox]`".

Right now qTox is effectively dropping some information it already has (namely, full ToxID of contacts added by the user) on the floor.

**Comment by zetok** [comment]
@rysiekpl #3405 for sharing contacts, though sharing might not handle your use-case fully.

**Comment by ewtoombs** [comment]
I'm still calling this a bug, since it is still baffling regular users when they can't get the tox ID of a contact that added them. This was not adequately explained. Now, though, the focus should be on reflecting this reality properly in the UI, in a way that people can immediately understand. Next to the Public Key field in friend details, for instance, it should say, "not a tox ID," with some kind of note explaining how nospam works. Because right now, the only way to figure out how nospam works is to file a bug on github not understanding how it works, have it get marked as duplicate, be led back to this bug, and maybe, if the user actually reads right until the end, they will understand what nospam is. This is a failure in UI design.

**Comment by ewtoombs** [comment]
> Right now qTox is effectively dropping some information it already has (namely, full ToxID of contacts added by the user) on the floor.

Exactly. That has nothing to do with toxcore. qtox can store that information itself. Unless qtox just doesn't do that. Does qtox store information that is not accessible to other tox clients? If not, then I could understand why qtox doesn't want to store the tox IDs that it is receiving, but if it does, then there's really no excuse.

**Comment by sudden6** [comment]
@ewtoombs qTox is not storing the full ToxID, because the contact can change it's NoSpam part at any time without telling anyone. So we can never know if the ToxID we might have is still valid.
