### ISSUE TITLE
[Regression] qTox's autocomplete uses sanitized names, not the raw version required for highlighting

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#952]
Which results in highlight not working for me.
![no highlight](https://cloud.githubusercontent.com/assets/3148759/5514924/82e02cd0-884a-11e4-88dd-7016a62c655b.png)

my nick contains null character at the end, and highlighting it worked earlier.

I have seen my nick being highlighted by (I think) older qTox version, while I and other people on newest qTox can't highlight it.

**Comment by dubslow** [comment]
qTox is probably trimming the null character on other clients, which is done by the alias code, which was written after the tab completion code... should be an easy fix, but I still can't code currently...

**Comment by dubslow** [comment]
Heh https://github.com/tux3/qTox/blob/902b13c486f3656eab74d9c318bce9be62336b40/src/widget/friendwidget.cpp#L222
