### ISSUE TITLE
qTox doesn't go online

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#953]
qTox freezes after “Settings: Saving personal in /home/user/.config/tox/qtox.ini” message in STDOUT
It's funny but interface is usable. I can change status in interface but it does not change really. I can change settings but it is ineffective. Exit is clickable in menu but ineffective too.

**Comment by dubslow** [comment]
What? That makes no sense?

**Comment by suhr** [comment]
How to reproduce: create empty file named `‹profile name›.ini.lock`.

**Comment by blackr4in** [comment]
I believe it is better to join this bug with https://github.com/tux3/qTox/issues/1495

**Comment by tux3** [comment]
Fixed in the new API branch, we now delete any stale .lock file on startup if there's no other instance running.
