### ISSUE TITLE
In a groupchat, the list of users trails off the screen

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#96]
```
Groupchat #0   
9 users in chat
name1, name2, name3, name4, name5, name6, name7, na
```

The only way to view names 8 and 9 is to expand the window, hardly a "solution".

(While I'm here, I would add that in my opinion, time stamps should be left of the name so that it can't be confused with the message.)

(Edit the second: What's with the file transfer button that does nothing?)

**Comment by tux3** [comment]
> What's with the file transfer button that does nothing?

What do you mean ?
You need to be connected to someone for the file transfer button to work, is that the problem ?

**Comment by dubslow** [comment]
No, the problem is this:

```
connect(ui->transferButton, SIGNAL(clicked()), this, SLOT(onTransferClicked()));
```



```
void Widget::onTransferClicked()
{

}
```

So one of the four main buttons does literally nothing.

(The transfer button below the emote button works fine I presume, but that's not what I'm talking about.)

**Comment by tux3** [comment]
Oh, okay. Well that's a bad case of "Not Implemented".

It's supposed to be a list of downloaded/sent files, but I haven't gotten around to doing it yet.

**Comment by dubslow** [comment]
A list of all files ever, or only since Tox was opened?

**Comment by tux3** [comment]
Only since it was opened, same as chat logs (a list of all files ever would get confusing since we don't keep chat logs forever).

**Comment by dubslow** [comment]
Actually, sort of similar to the initial bug in this thread, the Tox ID in the Settings widget is highlightable, yet there is no clear indication that what's on screen isn't the full TID (unless the window is somewhat larger than default). Perhaps better would be to add an ellipsis when it's truncated, or better still add a scroll bar.
