### ISSUE TITLE
Video preview is not affected when settings are changed by mouse scroll

### ISSUE THREAD

**Issue by kushagrasurana** [qTox/qTox#960]
Hi
The video preview present in video settings does not update when the slider is moved using mouse scroll.
It changes when slider is moved using mouse press.

**Comment by kushagrasurana** [comment]
writing valueChanged(int) slot for all the sliders solved for me. ( copied from slider moved slot )
eg. for Hue Slider, i implemented valueChanged slot -:

void AVForm::on_HueSlider_valueChanged(int value)
{
    Camera::getInstance()->setProp(Camera::HUE, value / 100.0);
}

**Comment by dubslow** [comment]
The sliders are stubs... I don't know if that's how they were intended to be implemented - were it so easy, why wasn't it done in the first place?

At any rate, feel free to submit a PR with the implemented slots :)

**Comment by zetok** [comment]
since #962 was merged, close?
