### ISSUE TITLE
qTox segfaults when remote cancels file transfer

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#964]
qtox 9bc6ae57fa1028752c9d882139d740ab98255a48 patched with #920 and #962.
I've tried to send 27 files.
https://gist.github.com/zetok/203807faa22e93471895

**Comment by dubslow** [comment]
Is it always preceded by a remote cancel?

**Comment by zetok** [comment]
Yes

**Comment by ProMcTagonist** [comment]
Is this still happpening?

**Comment by suhr** [comment]
Bump.

**Comment by zetok** [comment]
Can't reproduce any longer.
