### ISSUE TITLE
error during make [solution]

### ISSUE THREAD

**Issue by Antonius-git** [qTox/qTox#97]
Commit 65b4c026f4a2aa965f89f28958fe75bceb16475c to toxcore (https://github.com/irungentoo/toxcore/commit/65b4c026f4a2aa965f89f28958fe75bceb16475c) by irungentoo makes
lines 1121 and 1122 of core.cpp experience the following error while making:

core.cpp:1121:33: error: ‘ToxAvCodecSettings’ has no member named ‘video_width’
     calls[callId].codecSettings.video_width = TOXAV_VIDEO_WIDTH;
                                 ^
core.cpp:1122:33: error: ‘ToxAvCodecSettings’ has no member named ‘video_height’
     calls[callId].codecSettings.video_height = TOXAV_VIDEO_HEIGHT;
                                 ^
make: **\* [core.o] Error 1

This can be resolved by changing 'video_width' and 'video_height' to 'max_video_width' and 'max_video_height', to match.

**Comment by F1ynn** [comment]
Should be fixed.
