### ISSUE TITLE
filter audio doesn't work

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#976]
Tested it on windows and there is no difference compared to utox "filter audio". 
It's like a dummy setting.

**Comment by tux3** [comment]
d042c2f3460ab3cd7d5c55a8ad5b1819ec5e6813 should fix this.

qTox was filtering sent audio, instead of received audio.
This caused audio to be potentially filtered twice, or never.

**Comment by dubslow** [comment]
Also the windows builds available before this issue was made were several weeks old, and didn't have filtering of any sort on them.

**Comment by towlie** [comment]
@dubslow I think it is not a windows issue. I tested it on ubuntu and it doesn't filter audio there, too.

You can easily compare it with utox by turning on/off the filter setting.

Oh and @tux3, Toxy is filtering input audio, too. (like utox)

**Comment by tux3** [comment]
I just tested and right now filter_audio works just fine.

Note that you'll need to restart each calls for the changes to take effect.

**Comment by towlie** [comment]
Yes, it works it was just difficult for me to test it correctly, because you have to restart the call.
