### ISSUE TITLE
Auto-expire typing notifications

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#984]
First of all, thank you for the typing notifications, it's great to finally have this feature in qTox (although I don't like the positioning, but I expect that to possibly change with the upcoming new chat form).

I do, however, have the request to auto-expire typing notifications, because people sometimes leave a space, tab, newline, whatever in the chatform, and don't notice. With qTox' current implementation, the party on the other side will most likely think they're writing a very long message and wait for a message that doesn't exist.

I propose the following solution:
When the text field has not changed at all for 15 seconds (not a single character was added/removed), disable the typing notification.

A possible way to implement this would be by running a timer in the background which, after 15 seconds, disables the typing notification for an user, resetting the timer on ChatForm::onTextEditChanged(), and disabling the timer when the typing notification, for any reason, gets disabled (like when the text field gets empty, or when the 15 seconds are reached).

The exact number and implementation is of course up to the awesome developers, I'm just trying to give helpful suggestions :)

**Comment by AlexDaniel** [comment]
3 seconds is OK I think.

**Comment by tux3** [comment]
What about not sending a typing notification if there's only blank space in the chatform ?

I know that sometimes I have to pause for a couple of seconds to think about how to formulate things the best way..
