### ISSUE TITLE
qTox doesn't work with HTTP proxy

### ISSUE THREAD

**Issue by krisiun** [qTox/qTox#986]
I am behind a corporate firewall. I am using cntlm to support ntlm authentication. cntlm listens at 127.0.0.1:3128. I use it as the system wide proxy, so that I don't have to enter password everytime I connect to the internet.

When I provide this proxy to qTox, it doesn't work. The DNS works( I gave it something like user@toxme.se and it was able to resolve the tox id correctly.). But qTox is not connected to the internet; I can't change my status to 'Online'. I tried disabling UDP and IPv6, and the result is the same. :(

I don't know if my company is blocking connections to this particular port which qTox is using. Can somebody give me some instructions how I can test that? Thanks.

OS: Ubuntu 14.04 LTS.
![screenshot from 2015-01-06 12 10 00](https://cloud.githubusercontent.com/assets/6176085/5625199/49b262e8-959c-11e4-9dd6-9f0c6e7251cf.png)

**Comment by dubslow** [comment]
Try uTox, the other desktop client. Let us know if it works or not.

**Comment by krisiun** [comment]
uTox doesn't have http proxy support (only SOCKS). Nevertheless I tried and it doesn't work.

**Comment by dubslow** [comment]
Oh. I assumed it did...

@irungentoo @nurupo note that I haven't really eliminated qtox as the problem, but the api update for http proxies was quite simple...

https://github.com/tux3/qTox/commit/a14da15d79530faf42df495f8b1b70b5be8a96c8

**Comment by nurupo** [comment]
Check if your HTTP proxy is working properly.

Try running

```
printf "CONNECT tox.im:80 HTTP/1.1\nHost: tox.im:80\r\n\r\n" | nc <proxy-ip> <proxy-port>
```

it should reply with something like

```
HTTP/1.1 200 OK
```

Tell us what you get.

**Comment by krisiun** [comment]
Okay, I typed:

printf "CONNECT tox.im:80 HTTP/1.1\nHost: tox.im\r\n\r\n" | nc 127.0.0.1 3128 

127.0.0.1:3128 is where cntlm listens.

It doesn't print anything. The command doesn't terminate, however.

Other connections seem to work fine (I'm typing from the same machine using firefox), so I don't think there's anything really wrong with the proxy. What I doubt however, is that the proxy may be blocking the port which is used by qTox; but I'm not really sure as I'm no network expert. How can I check that?

**Comment by nurupo** [comment]
> It doesn't print anything.

If the proxy didn't reply anything to that, then there is an issue with the proxy.
Here is an example of a proxy that works

```
printf "CONNECT google.com:80 HTTP/1.1\nHost: google.com:80\r\n\r\n" | nc 151.200.170.146 80
```

or

```
printf "CONNECT google.com:80 HTTP/1.1\nHost: google.com:80\r\n\r\n" | nc 109.167.220.137 3128
```

Note that public proxies can go down any moment, so it might not be up anymore when you read this.

Also, public proxies are not very reliable, so you might need to try running this several times before getting a reply.

**Comment by krisiun** [comment]
I don't know what's wrong with my proxy in this particular case. I can access web through firefox, fetch and install packages using apt etc.

**Comment by DanTheBritish** [comment]
This might sound like an obvious question, but are you sure those applications are using the proxy?

On another note, it may be possible that your corporate proxy (not cntlm) is blocking Tox. I don't mean its specifically targeting Tox, but is blocking something which is affecting it. I can't think of a way off of the top of my head to test this.

**Comment by krisiun** [comment]
Yes, all these applications are using the proxy. As you said, the proxy may probably be blocking Tox directly or indirectly. Let me see if there is any way to confirm that.

**Comment by nurupo** [comment]
Are you sure your proxy is an HTTP proxy? The HTTP proxy option won't work with HTTPS, SOCKS or anything else besides an HTTP proxy.

Also, not exactly sure how system-wide proxies work, but Tox doesn't have any code that looks up what system-wide proxy is set up. If all applications' networking goes through the system-wide proxy transparently from applications, i.e. without any effort from applications' part (i.e. without any code that would deal with system-wide proxy setting), then it should just work.

**Comment by krisiun** [comment]
Yes, the proxy is an HTTP proxy, although I use the same proxy as my https_proxy too.

What I have done is to set the variables $http_proxy and $https_proxy. Almost all applications honor these environmental variables.

**Comment by nurupo** [comment]
Pretty sure qTox doesn't look up those env. variables, to make qTox use a proxy you set the proxy in qTox's settings (which I assume what you did).

**Comment by krisiun** [comment]
Yes. I did exactly that.

**Comment by nurupo** [comment]
Okay, then we can forget about it being set system-wide, since it doesn't play here any role and you seem to have set the proxy in qTox correctly.

What puzzels me is that your proxy didn't reply with anything to your attempt of connecting to tox.im/google.com

**Comment by krisiun** [comment]
If you have time, can you please try with some other http proxy, so that we are certain who is at fault here? I would have happily tried, but I can't do it at the moment (we're allowed to access internet only through our corporate proxy) or when I'm at home (no broadband, my dialup connection sucks! Even qTox with a direct connection barely works :( )

Btw, is there any way to know if a proxy blocks traffic through a particular port (without having to ask the network admin of course ;) )?

**Comment by apprb** [comment]
Tried HTTP proxy installed on local computer, everything works as expected.

**Comment by krisiun** [comment]
@apprb: Thanks for testing that for me. :)

Nevermind, then. Corporate proxy is always a headache. 

Thanks everyone involved.

**Comment by DanTheBritish** [comment]
It'd be interesting to know what about the proxy was blocking Tox, that way we'd know if this is something that can be avoided.
