### ISSUE TITLE
Groupchat peer list layout is badly broken

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#988]
Picrelated.

![](http://a.pomf.se/hycsab.png)

**Comment by zetok** [comment]
duplicate of #919?

Edit: it's not really broken, if one doesn't count layout. Someone just set their nick to something long.

**Comment by agilob** [comment]
@zetok no it's a duplicate of #752 which I broke some time ago ;)

It's fixed [here](https://github.com/tux3/qTox/pull/989)
