### ISSUE TITLE
Unable to change font

### ISSUE THREAD

**Issue by redsteakraw** [qTox/qTox#991]
Unable to change font

**Comment by benwaffle** [comment]
:+1:

**Comment by Deleetdk** [comment]
I second this. I often paste table data in IM, but ti doesn't display properly if one doesn't use a monospace font. However, one cannot change font in qTox as far as I can tell, so the tables are difficult to parse visually.

**Comment by ProMcTagonist** [comment]
@Deleetdk your use case will be solved by markup

**Comment by Deleetdk** [comment]
@ProMcTagonist Can you explain? I tried using ticks, but they have no effect.

**Comment by ProMcTagonist** [comment]
Markup isn't implemented yet, but it will be. That'll likely include preformatted text.

**Comment by redsteakraw** [comment]
You shouldn't be changing fonts in markup, the system font should be an option.  Also keep in dyslexic users can't use opendyslexic font which hinders accessibility.  Hard coding of fonts in general is a bug as the font supplied is hardly unicode complete which also hinders internationalization and localization.  As such I recommend de coupling the font or allowing it to be decoupled via a setting.  The drawbacks to accessibility and localization are not worth the "benefits"  of a hardcoded font.  Unicode is complex and vast no one font delivers and a given font will only hold users back from taking advantage of Unicode(including advanced math representation).  I have yet to hear an argument why the font needs to be hardcoded, if you know why feel free to respond.  @ProMcTagonist @dubslow @zetok

**Comment by ProMcTagonist** [comment]
> You shouldn't be changing fonts in markup,

```
I said preformatted text, which is monospace regardless of font, which solves his problem. 
```

**Comment by redsteakraw** [comment]
It may solve **that** problem.  However it doesn't solve the accessibility problems and internationalization problems caused by the hard-coded font.  @ProMcTagonist

**Comment by Deleetdk** [comment]
Or people who just prefer different fonts for readability issues.

**Comment by ProMcTagonist** [comment]
I didn't say it would. I said code block formatting in messages is the job of markup, not changing the display font in your client.

**Comment by Deleetdk** [comment]
Is anyone working on a solution for this problem? I'll set a .05 BTC (≈20 USD) bounty for whoever adds this feature.

**Comment by redsteakraw** [comment]
@Deleetdk I can change easily, I just would need to remove the hardcoded font but this is here by design and most likely won't be accepted.

**Comment by Deleetdk** [comment]
I'll be happy either with font change option (best) or option to use markdown so that I can use a monospace font when required.

**Comment by ProMcTagonist** [comment]
#2832 

no pre yet though

**Comment by antis81** [comment]
Font can now be changed in chat options. Closing.
