### ISSUE TITLE
[Feature Requests] Add little window with outgoing video while making videocall

### ISSUE THREAD

**Issue by Nokta-strigo** [qTox/qTox#994]
There's such feature in Skype: when you make videocall, you can see little rectangle with video from your camera, so you can understand what does your friend see on his end. It would be great to have such option in tox too.

**Comment by ArchangeGabriel** [comment]
I approve on that one, it would be a great thing to have that.

**Comment by dcharles525** [comment]
And a end call, mute on off, and video on off, buttons!! :)

**Comment by Nokta-strigo** [comment]
There are already buttons to mute microphone on/off and to mute speakers on/off (but they are in the chat window, not video window)

**Comment by ArchangeGabriel** [comment]
Indeed, they should be ported to the video window when this one is opened.

**Comment by Nokta-strigo** [comment]
Yes, I think video window should show all controls relating the current call: mute on/off mic/speakers, show video on/off, send video on/off, show text chat, stop call, share desktop, send file, ... All of them on a panel with an autohide option.

**Comment by urras** [comment]
Any update on this?

**Comment by zetok** [comment]
Update: looks like it is done in #2093.

Issue should be closable once PR will gets finished and merged.
