### ISSUE TITLE
Problems during Linux startup and shutdown

### ISSUE THREAD

**Issue by Pagirnis** [qTox/qTox#996]
I have a problem with qTox. I am runing a Linux Mint 17 machine fully upgraded.
If I add program to startup program list without a delay it woun't connect after startup, because at that point wireless is not yet established. This is a minor complaint and not really a problem.
The other thing (and the actual issue) is when I turn off computer without turning off qTox manually the shutdown time is very long as linux is trying to turn off qtox for very long time. Have any ideas what's wrong?

**Comment by dubslow** [comment]
There's a sorry of related issue that will fix the first part; not sure what's causing the latter. Maybe Qt has some default signal handler...

**Comment by zetok** [comment]
@DeXodus just gotta make sure; are problems still reproducible on newest qTox https://wiki.tox.chat/binaries#other_linux ?

Edit: if first problem is reproducible, I suspect that it's an upstream problem with toxcore

**Comment by zetok** [comment]
No answer, assuming that it was fixed, thus closing.
