### ISSUE TITLE
acceleration key support

### ISSUE THREAD

**Issue by xuhdev** [qTox/qTox#997]
Keyboard shortcut to switch to the next contact, previous contact, previous message, etc.

**Comment by AlexDaniel** [comment]
Yes, please!

**Comment by agilob** [comment]
@xuhdev What do you mean by 'previous message'?

**Comment by xuhdev** [comment]
@agilob The previous sent message. For example, I sent you a message but want to correct something, or need to type something similar again, I can just quickly call back the previous sent message and modify it. Similar to calling back the previous command in bash

**Comment by agilob** [comment]
arrow up = pastle previous message?

**Comment by xuhdev** [comment]
@agilob Similar to that, I would suggest that only when the cursor is at the first line.

**Comment by agilob** [comment]
or message box is empty.

**Comment by xuhdev** [comment]
correct

**Comment by agilob** [comment]
Partly done.
https://github.com/tux3/qTox/pull/1048

**Comment by xuhdev** [comment]
@agilob Great! Thanks! We can also add a keyboard shortcut to move between contacts on the left list. Maybe `Alt-N` `Alt-P` or `Shift-Down` `Shift-Up`?

**Comment by srkunze** [comment]
From [Switching and Re-ordering Chats like Browsers do](https://github.com/tux3/qTox/issues/1043#issuecomment-71395165)

ctrl + page-up/down <<< switch to next tab
ctrl + shift + page-up/down <<< move current tab down or up

chat = tab

**Comment by zetok** [comment]
When there'll be new keyboard shortcuts, please edit https://github.com/tux3/qTox/wiki/Keyboard-shortcuts accordingly (it's only for shortcuts that qTox already supports)

**Comment by zetok** [comment]
Closing, since mentioned functionality is in qTox - i.e. switching next/previous contact + pasting previous message.

As for switching between multiple messages, there already exists #310.
