### ISSUE TITLE
Bad font rendering on windows.

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#999]
Running Windows 7
Look at the status messages those are looking a bit blurred. 
And those crippled symbols are supposed to look like this ❆. (On Linux there are looking fine)

![brokenfont](https://cloud.githubusercontent.com/assets/6986141/5669483/2292c972-9778-11e4-81fe-3f85427bce08.png)

**Comment by Baguettedood** [comment]
Could this be related to Cleartype?

**Comment by ProMcTagonist** [comment]
How is it with the new chatform?

**Comment by towlie** [comment]
It's the same with the new chatform.

**Comment by zetok** [comment]
I take that this is still an issue?

**Comment by towlie** [comment]
Yes.

**Comment by jessica181920** [comment]
Status message font seems to have been increased in size and is easily readable. Users can now change base font in the settings and increase the size. The snowflake emoji not scaling well at that size is really more of an issue with Windows' Segoe fonts.

In a nutshell I think this can be closed.

**Comment by anthonybilinski** [comment]
Confirmed on Windows 10, with default font and size, status messages are more visible than attached picture and seem fine to me.
